### ISSUE TITLE
Set up babel aliases for common modules

### ISSUE THREAD

**Issue by brunobar79** [MetaMask/metamask-mobile#100]
like:

`import { strings } from '../../../locales/i18n';`

**Comment by Zidail** [comment]
I hope I'm not necroing this. 

Here's 2 possible solutions:

1. Use a `package.json` file to specify an alias for each module.
2. Use a 3rd party plugin like [babel-plugin-module-resolver](https://github.com/tleunen/babel-plugin-module-resolver).

All methods will require a new eslint plugin for linting.

@brunobar79 Is there perhaps any specific way you'd like to handle this?

**Comment by brunobar79** [comment]
This is a very old issue and should be closed since we’re not interested anymore. Thanks for asking!
