### ISSUE TITLE
[Bug]: Swaps Allowance Error, cannot fetch quotes on Android

### ISSUE THREAD

**Issue by infiniteflower** [MetaMask/metamask-mobile#10091]
### Describe the bug

Cannot fetch quotes after an infinite allowance. 

### Expected behavior

I should be able to fetch quotes

### Screenshots/Recordings

![Screenshot 2024-06-24 at 11 33 10 AM](https://github.com/MetaMask/metamask-mobile/assets/139582705/b0e83401-4cc9-47f4-9880-990d87c5f48b)

### Steps to reproduce

1. Find a token for which you have given infinite approval
2. Go to Swap
3. Try to fetch a quote
4. Observe `swaps-allowance-error`

### Version

7.24.3

### Build type

None

### Device

Android

### Operating system

Android

**Comment by cortisiko** [comment]
relates to https://github.com/MetaMask/metamask-mobile/issues/10037

**Comment by infiniteflower** [comment]
Closing in favor of https://github.com/MetaMask/metamask-mobile/issues/10037
