### ISSUE TITLE
[Bug]: Duplicate offramp transaction prompt when using smart transactions

### ISSUE THREAD

**Issue by georgeweiler** [MetaMask/metamask-mobile#10100]
### Describe the bug

When smart transactions are enabled, the offramp txn prompt is re-triggered after submitting. This allows users to send multiple transactions. Error "origin is required" is displayed.

### Expected behavior

After submitting an offramp transaction, the order details page should be displayed with a "processing" message while the user waits for the transaction to complete

### Screenshots/Recordings

https://github.com/MetaMask/metamask-mobile/assets/15269424/885c3204-359c-4bdb-a3d3-a58da7177fde

### Steps to reproduce

1. turn on smart transactions
2. complete a sell order
3. submit the transaction and see that another transaction prompt is displayed

### Error messages or log output

```shell
origin is required
```

### Version

7.24.0

### Build type

None

### Device

iOS and android

### Operating system

iOS, Android

**Comment by anaamolnar** [comment]
Hey @georgeweiler Can I close this issue?

**Comment by georgeweiler** [comment]
Hi @anaamolnar , yes, the fix was released in  7.24.4. I will close. thanks!
