### ISSUE TITLE
Unable to forget Ledger wallet on iOS

### ISSUE THREAD

**Issue by vivek-consensys** [MetaMask/metamask-mobile#10119]
Bitrise build:- https://app.bitrise.io/app/be69d4368ee7e86d/pipelines/c3a246ef-d60f-495a-8ed8-d72ef901c3a9

1. Add hardware wallet
2. Ledger
3. Connect to Ledger Device
3. Select multiple Ledger accounts
4. Verify they are added on the account list
5. Click 'Add Hardware wallet' -> Ledger
6. Connect to Ledger

Expected:- Forget wallet button is displayed

Actual:- Unable to connect to Ledger, 'Try again' button appears
<img width="369" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMmVTQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3f0411847a3b8413a9d21c96b4a32336b865b1f6/image.png" alt="image.png" />

**Comment by vivek-consensys** [comment]
a few more issues with iOS:- 

- sign tx not working for additional Ledger account
- send tx not working for additional Ledger account


[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd0tUQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7642ae2f899cee34c8f9ad96bacef3e65fa0082e/RPReplay_Final1719405783.MP4)

**Comment by dawnseeker8** [comment]
i have applied the fix in patch to our @metamask/eth-ledger-keyring-bridge library. now the iOS should work like android. here is bitrise build for it https://app.bitrise.io/app/be69d4368ee7e86d/pipelines/d3f0ce4d-44cc-44e1-aa4d-7d017db2c3e5

**Comment by dawnseeker8** [comment]
Assign back to Vivek to test again.

**Comment by vivek-consensys** [comment]
Working as expected, closing.
