### ISSUE TITLE
[Bug]: Send to screen showing wrong account names

### ISSUE THREAD

**Issue by chrisleewilcox** [MetaMask/metamask-mobile#10155]
### Describe the bug

When sending to an account on the `Send to` screen the account names under "Your Accounts" are showing the wrong account names.  Account names should match the Account list modal on the wallet view.

Not able to reproduce on 7.24.4.

Related: #9724 

### Expected behavior

Account names under "Your Accounts" should match the Account list dropdown modal on the wallet view.

### Screenshots/Recordings

https://github.com/MetaMask/metamask-mobile/assets/6626407/7bb9db07-e2bf-4317-938d-b7d2e818ef17

### Steps to reproduce

GIVEN I am on Sent to screen
THEN account names under "Your Accounts" matches account names in account list modal on wallet view (FAILED: account names do not match)

### Version

7.26.0

### Build type

None

### Device

android samsung galaxy A42

### Operating system

iOS, Android

**Comment by owencraston** [comment]
fixed by: https://github.com/MetaMask/metamask-mobile/pull/9724
