### ISSUE TITLE
[Bug]: All confirmations modals are showing wrong account name

### ISSUE THREAD

**Issue by chrisleewilcox** [MetaMask/metamask-mobile#10161]
### Describe the bug

Connect to the test dapp with an imported or hw account using a wallet that has at least one account of each account type (derived, hardware, imported).  Tap any of the buttons that will trigger confirmation modal such as Send Eth and you will see in the modal the account name does not match the account name shown in permission-system modals or account list on wallet view.

Not able to reproduce this in 7.24.4.

Related: #10079 
### Expected behavior

Confirmations modals account names for active/selected/connected account should match account names displayed in account list dropdown in wallet view and account names shown in permissions-systems modals.

### Screenshots/Recordings

https://github.com/MetaMask/metamask-mobile/assets/6626407/c4972123-7753-4f3e-ae9f-cee40e9c7ea7

### Steps to reproduce

GIVEN I am connected to the test dapp
AND account connected is an imported account
AND wallet has multiple account types
WHEN I tap Send ETH
THEN confirmation modal shows connected account name matches account name connected in permissions-systems modal (FAIL: account name does not match permissions-systems connected account name)

### Version

7.26.0

### Build type

None

### Device

any

### Operating system

iOS, Android

**Comment by jpuri** [comment]
This issue may be related to the PR: https://github.com/MetaMask/metamask-mobile/pull/9070

@chrisleewilcox : I am not able to play video in description. Can you plz upload again.

**Comment by chrisleewilcox** [comment]
@jpuri see convo [here](https://consensys.slack.com/archives/C029JG63136/p1719592789618129?thread_ts=1718821371.851179&cid=C029JG63136) on reproducing.

**Comment by owencraston** [comment]
fixed by: https://github.com/MetaMask/metamask-mobile/pull/9724
