### ISSUE TITLE
[Bug]: Browser favorites icons are broken on android devices

### ISSUE THREAD

**Issue by chrisleewilcox** [MetaMask/metamask-mobile#10171]
### Describe the bug

Adding browser favorites on android device shows broken favorite icons on home page favorites tab.

Not an issue with current prod 7.24.4

### Expected behavior

Browser favorite icons should display properly.

### Screenshots/Recordings

7.24.4: https://github.com/MetaMask/metamask-mobile/assets/6626407/faea69e2-dc3c-460d-a190-8584bc5d1d99

7.26.0: https://github.com/MetaMask/metamask-mobile/assets/6626407/57bc8678-bfce-48b9-a802-afc1edf29520

### Steps to reproduce

GIVEN I am on browser homepage
AND I am using an android device
WHEN I navigate to a web3 site
AND I add browser favorite
AND I navigate to homepage
AND I tap on Favorites
THEN all browser favorite icons properly display (FAIL: favorites show broken icon link)

### Version

7.26.0

### Build type

None

### Device

android devices

### Operating system

Android

**Comment by NicolasMassart** [comment]
Tested and could not reproduce. Any specific urls?

**Comment by chrisleewilcox** [comment]
Icons are no longer broken.  

![Image](https://github.com/MetaMask/metamask-mobile/assets/6626407/661776c0-34f4-451a-b1e2-c4c6ed8ef57e)
