### ISSUE TITLE
Incorrect numbering of Ledger accounts when renaming account with 100

### ISSUE THREAD

**Issue by vivek-consensys** [MetaMask/metamask-mobile#10188]
Bitrise build: https://app.bitrise.io/build/b8f59523-8e8a-4834-b673-f1aba5f23405?tab=artifacts

OS: iOS 17.5.1 / iPhone 13

1. Create new wallet / Import SRP
2. Add hardware wallet
3. Add Ledger hardware device
4. Rename hardware device to Ledger Account 100
5. Add hardware wallet
6. Add multiple more Ledger accounts

Expected: Ledger Account 2, 3, 4, 5
Actual: Ledger Account 102, 103, 104, 105

[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd2VpQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--aba88e00e007bfc041edee981aacd94bb940d5bf/RPReplay_Final1719572880.MP4)

**Comment by vivek-consensys** [comment]
Second bug related to AccountController:- 

1. Create new wallet / Import SRP
2. Add hardware wallet
3. Add QR hardware device
4. Add 0-4 accounts on the QR device list 
5. Verify the accounts on the QR hardware list are listed in the same order as it is displayed on the account list


Expected: Accounts to be listed in the same order
Actual: Account not listed in the same order


[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeDZpQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--731a0f5d0dda527dc01cc01929da098cbbfc6149/RPReplay_Final1719570059.MP4)

**Comment by dawnseeker8** [comment]
This bug may not be valid since the naming index is not based on the number in your account name, the index number is generated from length of existing ledger accounts, so even you rename your account name to `Ledger 100`, the next imported ledger account will have name `Ledger 2` since `Ledger 100` will be considered have index of 1 in the account array list.
