### ISSUE TITLE
Can't confirm seed phrase when two words are identical 

### ISSUE THREAD

**Issue by ibrahimtaveras00** [MetaMask/metamask-mobile#1020]
There is an issue when the generated seed phrase contains a repeated word.  You will not be able to progress past the "Confirm seed phrase" view when onboarding because it checks both words if you fill out one.

**Comment by rahimi2709** [comment]
Hi buddies...
I have similar problem in my seed phrase. How can I solve it?

**Comment by brunobar79** [comment]
Created a new branch `repeated-words-seed-repro`  to try to reproduce this issue (no luck yet)

**Comment by brunobar79** [comment]
I'm finally able to reproduce this issue (only in release mode).  Will take a look shortly

**Comment by dpazdan** [comment]
same issue reported on reddit https://www.reddit.com/r/Metamask/comments/ena2ch/same_word_twice_in_seed_phrase/
