### ISSUE TITLE
[Bug]: Network switch toast notification does not disappear

### ISSUE THREAD

**Issue by cortisiko** [MetaMask/metamask-mobile#10221]
### Describe the bug

The toast notification does not disappear after switching from network A to network B. This is causing instability with the e2e tests. Unfortunately, this issue is not consistently reproducible.  

### Screenshots/Recordings

![testFnFailure](https://github.com/MetaMask/metamask-mobile/assets/12821081/60f732e9-1f05-4632-97a0-160a9a30ee65)

### Steps to reproduce

From the network picker in the wallet view:
- switch to any network (i switched to sepolia) 
- Notice after the network education modal appears, the network toast also appears
- The toast appears to be in a broken state. It does not disappear. 

### Version

main (1f9af513bcd4a1124f83df5ec766ef73d604c581)

### Build type

None

### Device

iOS and Android

### Operating system

iOS, Android

**Comment by sleepytanya** [comment]
Same for the account switch v7.27.0:


https://github.com/user-attachments/assets/e34ac676-53c6-4a77-93d8-e3f517b0460a
