### ISSUE TITLE
When upgrading to latest MM version, user unable to add multi account for Ledger 

### ISSUE THREAD

**Issue by vivek-consensys** [MetaMask/metamask-mobile#10265]
Bitrise builds:-
First build - https://app.bitrise.io/build/f699b9ef-bc06-4fbd-9ff8-aaa064aebba9?tab=log
Latest build - https://app.bitrise.io/app/be69d4368ee7e86d/pipelines/4d6fb41b-84eb-4d2c-942b-4425a3cba6a7

OS:- iPhone 13 / iOS 17.5.1

1. Install first build 
2. Recover from SRP
3. Add Ledger device
4. Verify Ledger account is added
5. Upgrade to latest build (replace app)
6. Recover from SRP
7. Add Ledger device
8. Add multiple Ledger accounts

Expected:- Multiple Ledger accounts to be added
Actual:- Multiple Ledger accounts not added in the first attempt

[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeGJFQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--39f3745b946e2cc1a13bdeeeac4af3c622d7f28c/RPReplay_Final1720517449.MP4)

**Comment by dawnseeker8** [comment]
The latest code in this branch `feat/ledger-multiple-accounts-support-rebase` has contain the fix.
