### ISSUE TITLE
Update Android SDK to API Level 34

### ISSUE THREAD

**Issue by sethkfman** [MetaMask/metamask-mobile#10260]
### What is this about?

Your highest non-compliant target API level is Android 13 (API level 33).

To ensure that you can continue to make updates to your app you must:

Update your app to target Android 14 (API level 34) or higher.
Publish a new version of your app to production. Before you do this, you can test your app using internal, closed, or open testing.
Go to Releases overview

Once you've done this, we'll send you an Inbox message to confirm that your app update was successful, and that your app is no longer affected.

For more information:

[Learn more about the requirements](https://support.google.com/googleplay/android-developer/answer/11926878)
[Learn how to update your app](https://support.google.com/googleplay/android-developer/answer/9859350)
[Learn what changes you may need to make in your app](https://developer.android.com/google/play/requirements/target-sdk)
[Read the policy announcement](https://support.google.com/googleplay/android-developer/answer/13411745)

### Stakeholder review needed before the work gets merged

- [X] Engineering (needed in most cases)
- [ ] Design
- [ ] Product
- [ ] QA (automation tests are required to pass before merging PRs but not all changes are covered by automation tests - please review if QA is needed beyond automation tests)
- [ ] Security
- [ ] Legal
- [ ] Marketing
- [ ] Management (please specify)
- [ ] Other (please specify)

**Comment by sethkfman** [comment]
#10352

**Comment by sethkfman** [comment]
https://developer.android.com/about/versions/14/behavior-changes-14#runtime-receivers-exported

**Comment by joaoloureirop** [comment]
To target Android 14 we need to update `react-native` to `0.73.x`

Our current version `0.72.15` targets Android 13 (API Level 33)

https://github.com/facebook/react-native/blob/4cee0a4c06deb3b49c31021ea50766a4d391de1e/packages/react-native/ReactAndroid/build.gradle#L435


Android 14 support was added on react-native 0.73

https://github.com/facebook/react-native/issues/45773#issuecomment-2255726667

https://github.com/facebook/react-native/blob/1eb4bf0d3af1fe267f5de6bf4bbe1e65d41fea1b/packages/react-native/ReactAndroid/src/main/AndroidManifest.xml#L12

**Comment by joaoloureirop** [comment]
solution to try: https://github.com/facebook/react-native/issues/41288#issuecomment-2241527680

**Comment by ThalesBMC** [comment]
> solution to try: [facebook/react-native#41288 (comment)](https://github.com/facebook/react-native/issues/41288#issuecomment-2241527680)

This solution solved the problem for me.

**Comment by joaoloureirop** [comment]
> solution to try: [facebook/react-native#41288 (comment)](https://github.com/facebook/react-native/issues/41288#issuecomment-2241527680)

This solution allows the the broadcast receiver to be registered

<img width="1398" alt="Screenshot 2024-07-30 at 18 05 46" src="https://github.com/user-attachments/assets/f0e0e2f4-40a9-43b7-9b69-c0177b2cddd6">

**Comment by joaoloureirop** [comment]
Another report of successful fix https://github.com/doublesymmetry/react-native-track-player/issues/2327#issuecomment-2241046437



> solution to try: [facebook/react-native#41288 (comment)](https://github.com/facebook/react-native/issues/41288#issuecomment-2241527680)

Applied fix. 
App still crashes on Pixel 8 test device running Android 14

**Comment by ThalesBMC** [comment]
@joaoloureirop Not sure if it will help you, but one thing that was causing me problems was that my Android app was not recognizing the number 34 in this solution that you tried.

Try this:
```
@Override
public Intent registerReceiver(@Nullable BroadcastReceiver receiver, IntentFilter filter) {
    if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.UPSIDE_DOWN_CAKE && getApplicationInfo().targetSdkVersion >= Build.VERSION_CODES.UPSIDE_DOWN_CAKE) {
        return super.registerReceiver(receiver, filter, Context.RECEIVER_EXPORTED);
    } else {
        return super.registerReceiver(receiver, filter);
    }
}
```

**Comment by joaoloureirop** [comment]
Thanks @ThalesBMC 

I rebuilt the app and it now registers the broadcast receiver correctly

**Comment by ThalesBMC** [comment]
> Thanks @ThalesBMC
> 
> I rebuilt the app and it now registers the broadcast receiver correctly

Great to hear that I could help! 😄
