### ISSUE TITLE
[Bug]: Broken Typing at android 13

### ISSUE THREAD

**Issue by ilham89** [MetaMask/metamask-mobile#10276]
### Describe the bug

Broken typing at input, first input correctly fill one character, but next input double character

Spesification : 
- Android 13 TKQ1.221114.001
- OS 1.0.1.0. THGIDXM
- Redmi Note 12 Pro

### Expected behavior

Can typing nomally

### Screenshots/Recordings

https://github.com/MetaMask/metamask-mobile/assets/56493086/6ee03d92-0a59-4dd3-9c34-080f594d90c7

### Steps to reproduce

1. Install metamask version 7.24.4
2. Start typing at all input

### Version

7.24.4

### Build type

None

### Device

Redmi Note 12 Pro Android 13 

### Operating system

Android

### Severity

- Very Urgent, cause I cant login or use the input

**Comment by gauthierpetetin** [comment]
Hi @ilham89 ,
Thanks for reporting this issue.

- Can you please tell us what kind of keyboard you're using? (Google keyboard? other?)
- Also the recording shared above is a black screen, can you please send us another recording?

**Comment by NicolasMassart** [comment]
Not reproduced with Moto edge 30:
- android 13
- gboard 14.2.09.629370537
- indonesian layout

I don't have the autocompletion words appearing on the top of the keyboard as in the video.
I wonder if Redmi has a specific version of the keyboard.

@ilham89 Could you share you device settings/system/language&input/on screen keyboard/Gboard/about screen please?

**Comment by ilham89** [comment]
> Not reproduced with Moto edge 30:
> 
> * android 13
> * gboard 14.2.09.629370537
> * indonesian layout
> 
> I don't have the autocompletion words appearing on the top of the keyboard as in the video. I wonder if Redmi has a specific version of the keyboard.
> 
> @ilham89 Could you share you device settings/system/language&input/on screen keyboard/Gboard/about screen please?

I use same gboard 14.2.09.629370537 as yours, but in redmi

**Comment by gauthierpetetin** [comment]
This issue looks like a duplicate: https://github.com/MetaMask/metamask-mobile/issues/9992

**Comment by Cal-L** [comment]
Closing in favor of https://github.com/MetaMask/metamask-mobile/issues/9992
