### ISSUE TITLE
[Bug]: Gas calcs way off for erc20s using QR codes or deeplinks.

### ISSUE THREAD

**Issue by jjs2484** [MetaMask/metamask-mobile#10281]
### Describe the bug

Gas calcs are way off for erc20s on ETH mainnet. Checked USDC, USDT, and BAT. See picture. ETH seems OK.
.

### Screenshots/Recordings

![Screenshot_20240710_103222_MetaMask (1)](https://github.com/MetaMask/metamask-mobile/assets/3428918/bc66de35-3f13-47f5-97a4-b661187f5428)

### Steps to reproduce

1. Scan a payment QR code ( ethereum:0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48/transfer?address=0xAa28AA0140d13Ce38c804aCf66de4269E9D0CBE6&uint256=2.2e6 ) OR click a deeplink. 

### Version

7.24.4

### Build type

None

### Device

Samsung galaxy

### Operating system

Android

**Comment by gauthierpetetin** [comment]
Hi @MetaMask/sdk-devs , has there been any investigation made on this sev1 issue?

**Comment by gauthierpetetin** [comment]
Re-assigning to @MetaMask/transactions as it doesn't seem related to sdk.
