### ISSUE TITLE
Migrate FileSystemStorage data over to MMKV

### ISSUE THREAD

**Issue by Cal-L** [MetaMask/metamask-mobile#10288]
### What is this about?

This ticket tracks efforts for consolidating the app's storage mechanisms to use MMKV instead. The three libraries used are `MMKV`, `AsyncStorage`, and `FileSystemStorage`.  In addition to reducing to one storage solution, this will provide us with one of the most performant storage solutions available for React Native today. You can read more about it here as well as view the benchmarks for performance benefits - https://github.com/mrousavy/react-native-mmkv.  MMKV has the ability to store strings, booleans, numbers, and ArrayBuffers and is fully synchronous.

### Technical Details

- Create a new migration to migrate FileSystemStorage data over to MMKV. Update `persistConfig.ts`'s MigratedStorage to default to use MMKV and fallback to use FileSystemStorage. This work should resemble what was done here - https://github.com/MetaMask/metamask-mobile/pull/10153

### Acceptance Criteria

From a UX perspective, there should be no functional changes. ex:
- Controller data such as accounts and tokens should be persisted between app sessions
- Should still be able to export state logs

### Stakeholder review needed before the work gets merged

- [ ] Engineering (needed in most cases)
- [ ] Design
- [ ] Product
- [ ] QA (automation tests are required to pass before merging PRs but not all changes are covered by automation tests - please review if QA is needed beyond automation tests)
- [ ] Security
- [ ] Legal
- [ ] Marketing
- [ ] Management (please specify)
- [ ] Other (please specify)

**Comment by gauthierpetetin** [comment]
Closing this issue as not planned anymore, see comment [here](https://github.com/MetaMask/metamask-mobile/pull/10351#issuecomment-2258694003)
