### ISSUE TITLE
[Bug] Duplicate events being recorded on Mixpanel with different properties listed on each

### ISSUE THREAD

**Issue by vivek-consensys** [MetaMask/metamask-mobile#10302]
1. Launch Mixpanel [Mobile Prod]
2. Launch MM 
3. Recover from SRP 
4. Add hardware wallet
5. Add Ledger account
6. Verify the distinct ID from your device on Mixpanel
7. Analyse the mixpanel events

Expected:- 1 event being listed per user action
Actual:- 2 events being listed per user action

https://mixpanel.com/project/1979229/view/132079/app/profile#distinct_id=7A922DA7-FFEF-4CFA-B1CC-98A46990447B
<img width="1720" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL2ZiQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1f6726c48dd7da417ce3cb9773d636b760c70f2b/image.png" alt="image.png" />

https://mixpanel.com/project/3354001/view/3860937/app/profile#distinct_id=0f0fcafb-cdfc-427d-9d84-f0f5399f430a
<img width="1357" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL25iQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f885ab13baa136441d996b6f1545b52c88ce40dc/image.png" alt="image.png" />

1st event with 11 properties:- 
<img width="1417" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd0hjQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--69f6ffe39a9ef589669efbf2b073d9a56947d21e/image.png" alt="image.png" />

2nd event with 12 properties:- 
<img width="1600" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd0xjQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b66f4327f3ecd0fe28b22d691932c03543ba4190/image.png" alt="image.png" />

The device_type is listed on the 2nd event but not the 1st event.

**Comment by dawnseeker8** [comment]
After investigation with Vivek together yesterday, we notice that this issue happen to all event types in both MM Mobile and MM extension (we check the extension production). all metric event has been logged twice and one with proper properties logged and one without properties logged.

**Comment by dawnseeker8** [comment]
just look at some MM mobile (production) metric,  some version of app doesnt have issue, but some version of app start to have, i only saw some version after `7.17.1` (just randomly check) have this double event logs issue.
