### ISSUE TITLE
User asked to backup seed phrase then loses accounts 

### ISSUE THREAD

**Issue by dpazdan** [MetaMask/metamask-mobile#1035]
A user reported syncing seed to mobile from the extension.  Then the user added an account on Mobile.  At that time a notification requested backing up the seed phrase.

The process was completed and at that point, the original account that was synced from the extension, was gone, and a new set of accounts were present.

User then stated adding additional accounts brought them back.  Need further testing and reproduction.

support case: 23980

**Comment by brunobar79** [comment]
The part that doesn't make sense to me is that if you sync from the extension, you don't get prompted to back up.

**Comment by ibrahimtaveras00** [comment]
After some more investigation into this I see what was the issue.  As Bruno stated, it's impossible to get to this "secure your wallet flow"/backup seedphrase by syncing with extension.  

What I did was created a new wallet.  Then created a new account.  Then adding funds to account 2.  Once I was prompted to secure my wallet/backup I created my password.  At this point, you don't even have to continue with the flow, you can simply skip and the behavior above will happen (It will clear out your account, and go back to account 1 showing 0 ETH, but when you create a new account, your correct account will show the correct amount of ETH).

Flow seen here = http://recordit.co/l5SH9n5l9i

Steps to reproduce:
- create a new wallet
- create a new account
- on account 2 add funds (either by requesting from ropsten or sending yourself some ETH)
- wait for "Secure your wallet" modal to pop up
- create your password 
- tap on skip and accept 
- your new account is gone and you're back on account 1

CC @omnat

**Comment by ibrahimtaveras00** [comment]
Possibly related = https://github.com/MetaMask/metamask-mobile/issues/1105
