### ISSUE TITLE
Identify slowdowns causing Android start time

### ISSUE THREAD

**Issue by Cal-L** [MetaMask/metamask-mobile#10379]
### What is this about?

App start times have increased to the point where the Android app is often unusable because of how slow it is. This technical research task is aimed to identify what is causing Android's slow start times. 

# UPDATE FINDINGS:

Based on my findings, these are the areas the areas that result in a significant app start time. The definition of app start time here is the duration for which the native splash screen appears until it disappears.

Based on my findings, these are the areas the areas that result in a significant app start time. The definition of app start time here is the duration for which the native splash screen appears until it disappears. The doc also includes a game plan to tackle these areas - https://www.notion.so/metamask-consensys/Performance-Game-Plan-83ec0133962a4b7682a64c66e65d566c?pvs=4

### Technical Details

Here are tasks that will be researched and results will be posted for each point in this issue
- [ ] Reduce JS bundle
- [ ] Split bundle to reduce memory consumption - https://kirillzyusko.github.io/react-native-bundle-splitter

### Acceptance Criteria

Provide findings from technical details section

### Stakeholder review needed before the work gets merged

- [ ] Engineering (needed in most cases)
- [ ] Design
- [ ] Product
- [ ] QA (automation tests are required to pass before merging PRs but not all changes are covered by automation tests - please review if QA is needed beyond automation tests)
- [ ] Security
- [ ] Legal
- [ ] Marketing
- [ ] Management (please specify)
- [ ] Other (please specify)

**Comment by Cal-L** [comment]
Based on my findings, these are the areas the areas that result in a significant app start time. The definition of app start time here is the duration for which the native splash screen appears until it disappears.
- `Root` -> `PersistGate`
  - This is part of `redux-persist` that prevents the app from being rendered until Redux is rehydrated
- `ActivityView` -> `TransactionsView` -> `Transactions` -> `TransactionElement` -> `componentDidMount` -> `decodeTransaction`
  - It appears this is related to business logic being run as the app is being mounted
- `SharedDeeplinkManager and/or SDKConnect`
  - I suspect this is related to the native modules that it utilizes
- `Engine` -> `constructor`
  - The constructor is over a thousand lines long and initializes all controllers on app start, which is highly inefficient

**Comment by joaoloureirop** [comment]
@ Cal-L Can you identify which one(s) of these areas were negatively impacted between `v7.24.4.. v7.26.0` that would cause performance degradation?

**Comment by joaoloureirop** [comment]
@sethkfman does this ticket supersedes [7.26.0 - Cold/Warm Start Performance Issue #1871](https://github.com/MetaMask/mobile-planning/issues/1871)?

**Comment by Cal-L** [comment]
@joaoloureirop The scope of this has been quite massive already and I think we should keep that specific research task separate. The efforts would compound exponentially since we're dealing with multiple versions. A cleaner more isolated way to approach that would be to check the PRs that were introduced between those versions.

**Comment by Cal-L** [comment]
Findings documented in notion doc in ticket description
