### ISSUE TITLE
[Bug]: Can't connect to the test dapp on iOS

### ISSUE THREAD

**Issue by sleepytanya** [MetaMask/metamask-mobile#10396]
### Describe the bug

Despite the connection page indicating that accounts are connected, there seems to be an issue establishing a connection with the test dApp on iOS. 
After closing the app and opening it again the account appears as connected to the test dapp (thank you @SamuelSalas !)

### Expected behavior

The application can be connected to the test dapp.

### Screenshots/Recordings

https://github.com/user-attachments/assets/8197458c-3a8c-489e-aab1-82ee5a04ba41

### Steps to reproduce

1. Go to https://metamask.github.io/test-dapp/
2. Click 'Connect'
3. Observe that all buttons, with the exception of the Permissions and Connect buttons (which is anticipated), appear to be inactive. 

### Detection stage

In production (default)

### Version

7.28.0

### Build type

None

### Device

iPhone 13

### Operating system

iOS

**Comment by Cal-L** [comment]
Thanks for reporting @sleepytanya. I can't seem to reproduce this issue, what were your steps to reproduce for setting up the app? Could you try this on 7.29.0 or 7.30.0?
