### ISSUE TITLE
Our browser doesn't support scanning of QR codes

### ISSUE THREAD

**Issue by ibrahimtaveras00** [MetaMask/metamask-mobile#1042]
Seen here = https://recordit.co/orsn1p4Mw9

![image](https://user-images.githubusercontent.com/41752922/63962952-e7bbe500-ca61-11e9-9b56-34260b08b3d8.png)

Steps:
- I went to Kyberswap.com
- transfer
- tap on the QR code icon in the address field

**Comment by ibrahimtaveras00** [comment]
https://github.com/MetaMask/metamask-mobile/issues/1117 possibly related as well

**Comment by EtDu** [comment]
Seems like this was never meant to work in a mobile browser. Kyberswap is looking for a value on the browser's `Navigator` API which mobile browsers don't have.

https://github.com/KyberNetwork/KyberSwap/blob/91086eba2136de517bc72922bb8c3362e55230b5/src/js/containers/CommonElements/QRCode.js#L44

**Comment by omnat** [comment]
@andrepimenta wdyt about this? did webview update resolve this already?

**Comment by omnat** [comment]
Won't support this in browser till further relevance and need is clear. 
Consider adding to our developer docs - what we support with browser (or perhaps what's not supported explicitly). And provide alternatives for capabilities possible with other dev tools like deeplinks cc @gantunesr

**Comment by gantunesr** [comment]
Closing this issue taking in consideration the previous comment. Please open a new issue if someone thinks this is relevant and requires to be developed.
