### ISSUE TITLE
[Bug]: During the Blockaid validation process, the spinner that typically indicates activity is not displayed

### ISSUE THREAD

**Issue by sleepytanya** [MetaMask/metamask-mobile#10514]
### Describe the bug

During the Blockaid validation process, the spinner that typically indicates activity is not displayed.
The spinner is visible for some time on Android devices.

Related PR: https://github.com/MetaMask/metamask-mobile/pull/10266

### Expected behavior

A spinner is displayed to indicate that validation is currently in progress.

### Screenshots/Recordings

iPhone 15:

https://github.com/user-attachments/assets/9716b52c-11e0-465c-968e-d0306c5e9f66

Samsung S24+:

https://github.com/user-attachments/assets/5c3a635b-ae9e-499f-bddb-8b604adb6c03

### Steps to reproduce

1. Go to https://metamask.github.io/test-dapp/
2. Submit batch of 10 malicious transactions (validation takes longer)

### Detection stage

In production (default)

### Version

7.28.0

### Build type

None

### Device

Samsung S24+, iPhone 15

### Operating system

iOS, Android

**Comment by bschorchit** [comment]
> **Steps to reproduce**
> 1. Go to https://metamask.github.io/test-dapp/
> 2. Submit batch of 10 malicious transactions (validation takes longer)

Does this only happen for batched requests or is it only easier to reproduce for batched requests?

**Comment by sleepytanya** [comment]
Further investigation has revealed that the issue observed might be a pre-existing one, which has perhaps become more noticeable following the [latest PR](https://github.com/MetaMask/metamask-mobile/pull/10266). It's possible that this is related to performance challenges with batch requests. This is the loader behavior as it appears without the updates introduced in [this PR](https://github.com/MetaMask/metamask-mobile/pull/10266):

Android:


https://github.com/user-attachments/assets/f733fccf-e112-4567-9d5f-12f52a143b06


iOS:


https://github.com/user-attachments/assets/0693e55b-1991-4ac7-9f65-bcf6bed9a0d6

**Comment by jpuri** [comment]
Hey @sleepytanya , @bschorchit : please check attached video, I do not see this issue either in main or 7.29 release branches:


https://github.com/user-attachments/assets/9d86d514-bf34-44d1-8717-23bd0bd25efa

**Comment by sleepytanya** [comment]
@jpuri 
 Batch request makes the issue more visible. Though it happens with other malicious txs too, you may need slow connection to see it.


https://github.com/user-attachments/assets/02e0fc7b-9d39-4e11-bd72-b89b90bf73b3



https://github.com/user-attachments/assets/ddab5de3-5828-446d-84db-0f3257c46e60
