### ISSUE TITLE
[Bug]: Support for security alerts on zkSync, Berachain, Scroll and Metachain One 

### ISSUE THREAD

**Issue by sleepytanya** [MetaMask/metamask-mobile#10524]
### Describe the bug

Support for security alerts on zkSync works as expected.
Security alerts do not work on Scroll and Metachain One. Error banner is shown on Metachain One, on Scroll only malicious transactions are detected, warning for signatures doesn't appear.
Currently Berachain Artio (80085 (0x138d5)) cannot be added to MetaMask, despite being available at the time the PR was created. Therefore, it seems reasonable to temporarily set aside Berachain support.

https://github.com/MetaMask/metamask-mobile/pull/10139

### Expected behavior

Security alerts work on Scroll, Metachain One and zkSync Era

### Screenshots/Recordings

https://github.com/user-attachments/assets/028254bb-46a2-4684-853f-d18f84fc5ad3

<img width="357" alt="Screenshot 2024-08-01 at 10 52 54" src="https://github.com/user-attachments/assets/d18083a5-5da0-448e-bf1c-90a7beab6fbd">

### Steps to reproduce

1. Connect to zkSync, Scroll or Metachain One
2. Connect MetaMask to[ the test dapp](https://metamask.github.io/test-dapp/)
3. Send a malicious transaction / signature

### Detection stage

In production (default)

### Version

7.28.0

### Build type

None

### Device

iPhone 15, Samsung S24+

### Operating system

iOS, Android

**Comment by bschorchit** [comment]
I've tested and Scroll seems to be working correctly. For Metachain, I'm indeed only getting error messages. I'll follow up on those with Blockaid. 

![IMG_8461](https://github.com/user-attachments/assets/535ff091-056a-480d-b01f-bb8476f12a10)

**Comment by bschorchit** [comment]
Closing as it has been solved
