### ISSUE TITLE
if add custom network and goto browser open my dapp, it's ok, but i send tx it can not open Send view.

### ISSUE THREAD

**Issue by yourihua** [MetaMask/metamask-mobile#1052]
if add custom network and goto browser open my dapp, it's ok, but i send tx it can not open Send view.

**Comment by yourihua** [comment]
![image](https://user-images.githubusercontent.com/42401769/64097293-74361280-cd96-11e9-8143-b813a6912565.png)

**Comment by yourihua** [comment]
![image](https://user-images.githubusercontent.com/42401769/64097391-b9f2db00-cd96-11e9-91b5-77bc6641b1df.png)

**Comment by yourihua** [comment]
![image](https://user-images.githubusercontent.com/42401769/64097534-10601980-cd97-11e9-9b39-b70364913033.png)
rpc not exist networkId

**Comment by estebanmino** [comment]
hi @yourihua thanks for reporting, probably related to https://github.com/MetaMask/metamask-mobile/issues/903
