### ISSUE TITLE
metamask_watchAsset

### ISSUE THREAD

**Issue by mdmvgithub** [MetaMask/metamask-mobile#1053]
Hi,
The method 'metamask_watchAsset' seems not to be defined in metamask-mobile.
Do you plan to include it?
Thank you very much.

**Comment by estebanmino** [comment]
Hi @mdmvgithub, we have it as [`wallet_watchAsset`](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-747.md). Let us know if you have any doubt.

**Comment by mdmvgithub** [comment]
Hi,
Thank you for your response.
`web3.wallet` does not exist in my metamask-mobile installation (from Play store), nor in metamask-extension in Chrome

I have created the web3 object using:
`     if (ethereum)
        web3 = new Web3(ethereum);`

May be a problem of outdated versions?

**Comment by estebanmino** [comment]
you can use it as

```
web3.currentProvider.sendAsync({
    method: "wallet_watchAsset",
    params: {
        type: 'ERC20',
	options: {
		address: 'your_token_address',
		symbol: 'your_token_symbol',
		decimals: 18
	}
    }
})
```

**Comment by mdmvgithub** [comment]
Esteban,
I have been using it as you say, it works in the metamask extension, but does fails in metamask-mobile, returning "unknow method"

**Comment by estebanmino** [comment]
@mdmvgithub could you try this code? https://gist.github.com/estebanmino/6e2e35d2a1f3b6492e6b5c24f3198158

![DK1ihuii07](https://user-images.githubusercontent.com/12115171/64361805-47bf0800-cfdb-11e9-92ce-ea88244289a8.gif)

**Comment by mdmvgithub** [comment]
Thank you very much !
It works!
Curiosity: In my installed APP your code does not recognize the ethereum object . Moving the `script` to the header section, it works. Also, it always says 'DaI added' even if I cancel.

This is enough for me, thank you!!!
