### ISSUE TITLE
Smart Transactions result in inability to receive callback messages

### ISSUE THREAD

**Issue by kangkaislove** [MetaMask/metamask-mobile#10555]
### Describe the bug

Dapp uses the walletConnect protocol to call MetaMask to initiate transactions. When MataMask opens Smart Transactions, Dapp cannot receive transaction **callback** information, resulting in subsequent interactions being unable to be processed.

### Expected behavior

Enabling Smart Transactions can also provide callback information related to transactions

### Screenshots/Recordings

![image](https://github.com/user-attachments/assets/d845de97-6bb8-43cf-ae9b-e1e0fbd028df)

### Steps to reproduce

1. Open Dapp developed using WalletConnect V2 protocol
2. Open MataMask, switch to Settings ->Advanced, and enable Smart Transactions
3. Using Dapp to call MataMask to initiate transactions, after MetaMask processes the transaction, it will not callback relevant information through the WalletConnect protocol
4. Due to the lack of callback information, it is unknown whether the transaction was successful or failed, and the subsequent process cannot proceed

### Detection stage

In production (default)

### Version

7.27.1

### Build type

None

### Device

All Android & IOS mobile

### Operating system

iOS, Android

**Comment by Jeday** [comment]
+1 Experiencing same issues in my dapp.

**Comment by Cal-L** [comment]
Assigned to transactions team

**Comment by klejeune** [comment]
This issue has been acknowledged, but it is not a current priority. Closing for now, but feel free to reopen if needed in the future.
