### ISSUE TITLE
Replace `zxcvbn` lib with a solution with a smaller JS footprint

### ISSUE THREAD

**Issue by Cal-L** [MetaMask/metamask-mobile#10552]
### What is this about?

`zxcvbn` is a 800KB lib that is only used for checking the strength of a password. Should be replaced with something more lightweight or regex. This is part of an effort to reduce the JS bundle size

### Technical Details

- Remove `zxcvbn` library
- Replace it with a solution that achieves scanning for password strength with a low JS footprint

### Acceptance Criteria

- Password entry should still trigger the same password strengths as it's being updated
- UI wise, there should be no changes

### Stakeholder review needed before the work gets merged

- [ ] Engineering (needed in most cases)
- [ ] Design
- [ ] Product
- [ ] QA (automation tests are required to pass before merging PRs but not all changes are covered by automation tests - please review if QA is needed beyond automation tests)
- [ ] Security
- [ ] Legal
- [ ] Marketing
- [ ] Management (please specify)
- [ ] Other (please specify)

**Comment by tommasini** [comment]
We decided internally to not change the way that password strength is calculated
