### ISSUE TITLE
Calling contracts functions via QRCode scanning

### ISSUE THREAD

**Issue by antodp** [MetaMask/metamask-mobile#1059]
I tried scanning a QRCode encoding this EIP-681 url:

`ethereum:<contract_address>/approve?address=<spender>&uint256=<amount>`

and the application ended first in the **_Send_** screen and after confirming transaction it gave me this screen (unknown method):

![photo_2019-09-05_16-39-51](https://user-images.githubusercontent.com/20992089/64352207-e65b6100-cffb-11e9-9f5b-63a38dec35d3.jpg)

Is this functionality implemented?

**Comment by 0xbitcoin** [comment]
Hello, please implement this functionality as it is critical to many of the Dapps that I want to build and the one I am building now.  This is HUGE for the Ethereum community

**Comment by admazzola** [comment]
I did some research and the rabbit hole goes a bit deeper.  It seems like at this time, the metamask extension supports 6 different types of TXes: "simpleSend, tokenTransfer, tokenApprove,
    contractDeployment, contractMethodCall"

>   /**
>     Returns a "type" for a transaction out of the following list: simpleSend, tokenTransfer, tokenApprove,
>     contractDeployment, contractMethodCall
>   */
>   async _determineTransactionCategory (txParams);
> 


However, Metamask Mobile only supports two types of transactions, simpleSend and tokenTransfer. 

If you inspect the file 'app/components/views/send' in Metamask Mobile you will see the following: 

> switch (action) {
> 			case 'send-eth':
> 				newTxMeta = {
> 					symbol: 'ETH',
> 					assetType: 'ETH',
> 					type: 'ETHER_TRANSACTION',
> 					...this.handleNewTxMetaRecipient(target_address)
> 				};
> 				if (parameters && parameters.value) {
> 					newTxMeta.value = toBN(parameters.value);
> 					newTxMeta.readableValue = fromWei(newTxMeta.value);
> 				}
> 				break;
> 			case 'send-token': {
> 				const selectedAsset = await this.handleTokenDeeplink(target_address);
> 				newTxMeta = {
> 					assetType: 'ERC20',
> 					type: 'INDIVIDUAL_TOKEN_TRANSACTION',
> 					selectedAsset,
> 					...this.handleNewTxMetaRecipient(parameters.address)
> 				};
> 				if (parameters && parameters.uint256) {
> 					newTxMeta.value = toTokenMinimalUnit(parameters.uint256, selectedAsset.decimals);
> 					newTxMeta.readableValue = String(
> 						renderFromTokenMinimalUnit(newTxMeta.value, selectedAsset.decimals)
> 					);
> 				}
> 				break;
> 			}
> 




This means that /send/index.js requires the other 4 TX types to be supported and then the QRScanner/index.js needs to be slightly modified to properly pass the 'txMeta' data containing one of those six types/actions to /send/index.js .

**Comment by admazzola** [comment]
What this also means is that the app cannot sign tx that do anything other than send eth or send tokens.  Want to interact with a dapp contract?  it actually can't do that yet.

**Comment by omnat** [comment]
Hi @admazzola @0xbitcoin @antodp Is this issue still happening in the latest version (0.2.18)?

**Comment by admazzola** [comment]
Hi Omna,

Yes, EIP 618 still has not been implemented into Metamask Mobile to allow
for 'approve' and 'transfer' methods of ERC20 token contracts to be called
via QR code.

For example, see this website:

https://brunobar79.github.io/eip681-link-generator/#

Then generate a QR code with this string: '
ethereum:0x7132C9f36abE62EAb74CdfDd08C154c9AE45691B/transfer?address=0x7132C9f36abE62EAb74CdfDd08C154c9AE45691B&uint256=1'

Or with this string

**Comment by danfinlay** [comment]
>  So the problem lies more with the core tx handling code and not the QR scanner

I believe you're looking at the tx rendering code, not the tx processing code. We use the dapp browser to interact with contracts all the time.

That said, visually representing contract interactions is very important, and I'd love to see them be able to work from QR code.

Could anyone give an example of a use case for this feature? I think it would help demonstrate its value. Here's one: Scan a QR code on a flier to reserve a spot at an event.

In the meanwhile, you could still always have a QR code to a site that then initiates the transaction. Any times that wouldn't work?

**Comment by EtDu** [comment]
On MMM version 1.0.0, tested using this link: ethereum:0xB8c77482e45F1F44dE1745F52C74426C631bDD52/transfer?address=0x045C619E4D29bBA3b92769508831B681b83d6a96&uint256=1e1

Produces this screen:
![IMG_C9608D3806EE-1](https://user-images.githubusercontent.com/26778340/92474518-8ef36080-f20e-11ea-9c7a-1df42a36c0d4.jpeg)

Looks like the issue has been resolved. Please reopen if you experience this again!

**Comment by ravisriv** [comment]
Hello @EtDu,

My testing is indicating that @admazzola is correct. The most recent release does not support ERC-20 "approve" function in ERC-681 URL link. What @EtDu tested was "transfer" function, not "approve" function. 

ERC-20 "approve" function is needed if the Dapp wants to debit the payer's account if certain conditions are met. For example, if the payer wins an auction. 

For example, here is an "approve" URL:

https://metamask.app.link/send/pay-0x3dD3DfaAdA4d6765Ae19b8964E2BAC0139eeCb40@4/approve?0x0301dcF5Cf918a6E506AEa3C8FC6c57D8EbB8B92&uint256=50023e2

When I click on this deep link, I get the following screen:

![Screenshot 2020-09-08 at 11 02 47 PM](https://user-images.githubusercontent.com/62220449/92563246-2915d180-f22c-11ea-9541-bedc3a76b78b.png)

Further when I generate an "approve" QR code using the "Ethereum Transaction Link Generator" available at:
https://brunobar79.github.io/eip681-link-generator/#   (see below)

![screenshot2](https://user-images.githubusercontent.com/62220449/92564198-a3932100-f22d-11ea-87b5-d594d21b296a.png)

I get the following screens, which not only have incorrect messages but also they are not processing the transaction correctly.

![IMG_2201](https://user-images.githubusercontent.com/62220449/92564340-da693700-f22d-11ea-82bb-5e6dcdf09446.PNG)

![IMG_2202](https://user-images.githubusercontent.com/62220449/92564355-e05f1800-f22d-11ea-96b0-7cfe870ebf55.PNG)

![IMG_2203](https://user-images.githubusercontent.com/62220449/92564373-e7862600-f22d-11ea-9bfd-01342c4bebfa.PNG)

I have tested it with multiple ERC-681 "approve" transactions and none of them works. My impression is that "approve" functionality pursuant to ERC-681 is broken.

(The transactions showing as "Confirmed" in the mobile MetaMask actually failed.")

Thank you.

**Comment by EtDu** [comment]
Thank you for bringing this up @ravisriv. I will leave this issue closed as I see you've created a more relevant one.
