### ISSUE TITLE
[Bug]: Browser favorites show broken icons after upgrade

### ISSUE THREAD

**Issue by chrisleewilcox** [MetaMask/metamask-mobile#10604]
### Describe the bug

After upgrading to the 7.29.0 my existing browser favorites show broken icons.

- ### Workaround for this is to clear browser history and cookies.  

### Expected behavior

Browser favorites should continue to be properly displayed after upgrade.

### Screenshots/Recordings

https://github.com/user-attachments/assets/2f5a5bcf-f9aa-4056-80d0-df31593df0f8

### Steps to reproduce

Browser favorites should continue to be properly displayed after upgrade.

### Detection stage

During release testing

### Version

7.29.0

### Build type

None

### Device

Android

### Operating system

Android

### Additional context

Similar issue occurred in previous release testing and fix was done by resetting cache on homepage.  No app code change was made to fix this.

**Comment by Cal-L** [comment]
@chrisleewilcox Does this happen with earlier upgrades or only to 7.29.0? Could you provide the exact steps leading up to the issue?

**Comment by Cal-L** [comment]
We're not able to reproduce again. Will close for now. Feel free to reopen if it happens again.
