### ISSUE TITLE
[Bug]: Unable to connect to ENS dapp in mobile browser

### ISSUE THREAD

**Issue by plasmacorral** [MetaMask/metamask-mobile#10614]
### Describe the bug

Discovered while preparing a for migration test from release build of v7.28.0 build 1375.  Attempting to connect to the dapp seems to not be working/responding on iOS, but causes MetaMask to stop on my android 14 device. 

### Expected behavior

Able to connect my account to a dapp, and if not handle that more gracefully than an app closure.

### Screenshots/Recordings

[Recording](https://www.loom.com/share/3ce295abfd4a45858dc5a631f906ea50)

### Steps to reproduce

1. Setup wallet
2. open MetaMask mobile browser
3. navigate to app.ens.domains
4. Tap `Connect`
5. Scroll to the right and tap `MetaMask`
6. Note nothing seems to happen
7. Tap `Browser Wallet`- no response
8. Tap `Wallet Connect`
9. Get prompted to select a wallet
10. Tap MetaMask
11. Note that MetaMask closes

### Detection stage

In production (default)

### Version

7.28.0

### Build type

None

### Device

Pixel 5a

### Operating system

Android

### Severity

Once in this condition it is difficult to resolve as the app closes upon trying to close the browser tab.

**Comment by Cal-L** [comment]
This is a regression for 7.26.0, introduced in 7.27.0. Possibly related to react native webview upgrade - https://github.com/MetaMask/metamask-mobile/pull/7759 cc @joaoloureirop

**Comment by joaoloureirop** [comment]
> This is a regression for 7.26.0, introduced in 7.27.0. Possibly related to react native webview upgrade - https://github.com/MetaMask/metamask-mobile/pull/7759 cc @joaoloureirop

The webview-upgrade PR introduced CSP compliance.
This might break dapps that do not expect the provider to be initialized on our side

**Comment by joaoloureirop** [comment]
The Android crash root cause is a malformed SVG from 
`https://app.ens.domains/favicon.svg`

**Comment by Shaik-Sirajuddin** [comment]
facing similar crash when trying to connect to opensea.io or any other website using wallet connect within metamask browser
