### ISSUE TITLE
[Bug]: System Face ID Denial Unintentionally Blocks Device Passcode and FaceID Options in Security Settings 

### ISSUE THREAD

**Issue by vinnyhoward** [MetaMask/metamask-mobile#10615]
### Describe the bug

During the initial app setup, users are presented with a system prompt: "Do you want to allow "MetaMask" to use Face ID?" This prompt has unintended consequences:

If the user selects "No":

The app inadvertently denies access to the Device Passcode option as well as Face ID option in the app's Security & Privacy settings.
Users cannot enable Device Passcode as a backup security measure.

If the user selects "Yes":

Users can access and toggle both Face ID and Device Passcode options in the Security & Privacy settings.

Impact:
This issue potentially reduces the security options available to users who initially decline Face ID, limiting their ability to secure their wallet with alternative methods.

### Expected behavior

Users should have access to the Device Passcode option in Security & Privacy settings regardless of their choice regarding System Face ID during initial setup.

### Screenshots/Recordings

You can ignore the padding UI bug that was fixed [#2452](https://github.com/MetaMask/MetaMask-planning/issues/10547) and [#10547](https://github.com/MetaMask/metamask-mobile/pull/10547)

| System Face ID Enabled  | System Face ID Disabled  |
|:---:|:---:|
| ![system_faceid_enabled](https://github.com/user-attachments/assets/eb793015-f1c6-4758-82dc-821042b6b578)| ![system_faceid_disabled](https://github.com/user-attachments/assets/da184fda-6548-4235-b6d7-e1a9818937e8) | 

### Steps to reproduce

1. Fresh install the MetaMask mobile app.
2. Complete the initial setup by entering the passphrase and password.
3. When prompted "Do you want to allow "MetaMask" to use Face ID?", select "No".
4. Navigate to Settings > Security & Privacy.
5. Observe that the Device Passcode option is not available or cannot be enabled.

### Design
Design Figma link: [here](https://www.figma.com/design/3Lk9NdF5dUDxtJ0l2zsqYW/Mobile-Face-ID-disabled-fix?node-id=1-2&t=huhQlpIHHFnaGXgp-0)
Design screenshot
<img width="893" alt="faceid" src="https://github.com/user-attachments/assets/d39d504d-6653-45c8-91fd-4da158afbc0b">

### Detection stage

In production (default)

### Version

7.28.0

### Build type

None

### Device

iPhone 12 Pro Max

### Operating system

iOS

### Severity

Provides less security for user's and bad user experience

**Comment by Cal-L** [comment]
Just tested and confirmed the findings. To summarize, once FaceID is disabled, a user no longer has the ability to re-enable FaceID from MM Settings page. At this stage, it requires the user to go into their system settings to toggle FaceID to be enabled. Once common UI approach for this condition is to link the user from the MM settings page to the system settings, where they'll be enable to re-enable FaceID. @yanrong-chen Will hand off to you for design support on this
![IMG_5204](https://github.com/user-attachments/assets/021958b4-b23f-41fc-b92f-89b1452681a9)

**Comment by yanrong-chen** [comment]
Here is the [design figma link](https://www.figma.com/design/3Lk9NdF5dUDxtJ0l2zsqYW/Mobile-Face-ID-disabled-fix?node-id=4-2757&t=huhQlpIHHFnaGXgp-0)
A new "Turn on Face ID" bottom sheet will show if users selected "No" at the first place, and then direct users to settings. 
Thank you for @coreyjanssen's content support!
<img width="893" alt="faceid" src="https://github.com/user-attachments/assets/c49c80be-cebd-46cb-9138-c6c95befb956">

**Comment by vinnyhoward** [comment]
This looks awesome! I'll get right on this

**Comment by yanrong-chen** [comment]
Feel free to use the system alert instead just so we are consistent with issue [#10673](https://github.com/MetaMask/metamask-mobile/pull/10673)
<img width="826" alt="Screenshot 2024-08-16 at 10 50 12 AM" src="https://github.com/user-attachments/assets/6fa8c1e1-aea5-4f46-a0ca-37f9ec126fb9">
