### ISSUE TITLE
Ledger - Hd options sync with extension

### ISSUE THREAD

**Issue by angelcheung22** [MetaMask/metamask-mobile#10678]
- confirmed with Alex, UI as below, 
<img width="1868" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMHVTQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d7e27d65e4ae94204bf97eace8ea9bf8a9725229/image.png" alt="image.png" />

- And the account selection dropdown/ & device selection drop down requires update as actionsheet than popup modal per Guto's comment

- Collect metric for deviation path being added. (hd_path)

**Comment by dawnseeker8** [comment]
Regarding the mixpanel new property `hd_path` values:
Here are three values: @vivek-consensys 
```
hd_path =`m/44'/60'/0'/0/0`  -> Ledger live path
hd_path = `m/44'/60'/0'/0`. -> BIP44 path
hd_path = `m/44'/60'/0'`   -> Legacy Path
```

**Comment by vivek-consensys** [comment]
Metrics will only be triggered when event 'Connected Account with hardware wallet' has been executed.

**Comment by vivek-consensys** [comment]
export const LEDGER_LIVE_STRING = 'Ledger Live';
export const LEDGER_BIP44_STRING = 'Ledger BIP44';
export const LEDGER_LEGACY_STRING = 'Ledger Legacy';
export const LEDGER_UNKNOWN_STRING = 'unknown';
