### ISSUE TITLE
Add ability to track JS bundle size over time + comparison capabilities

### ISSUE THREAD

**Issue by Cal-L** [MetaMask/metamask-mobile#10671]
### What is this about?

This task tracks adding a mechanism to enable JS bundle size comparison between CI runs. For example, on Extension, there is a designated repository https://github.com/MetaMask/extension_bundlesize_stats, used for tracking bundle size over time. The goal is to enable similar capabilities on mobile's CI so that we're able to track bundle size that is mapped to a PR, compare the size relative to `main` branch, while maintaining the JS bundle size quality gate based on a threshold defined in the MVP task - https://github.com/MetaMask/metamask-mobile/issues/10527

### Scenario

Reference acceptance criteria section

### Technical Details

- Establish place to track JS bundle size over time. Extension created a new repo for this https://github.com/MetaMask/extension_bundlesize_stats
- In the CI step
  - Update the JS bundle record with the latest JS bundle size mapped to PR metadata such as title, PR number, commit, etc
  - Compare JS bundle size diff relative to main
  - Use metamask bot to output the JS bundle stats in the PR, which includes current bundle size, increase relative to `main`, and link to html generated by source map explorer

### Acceptance Criteria

- JS Bundle size quality gate fails if bundle size exceeds threshold
- JS Bundle size quality gate succeeds if bundle size stays below threshold
- Bundle size is recorded with every CI run that can be referenced later for comparison
- Similar to extension, metamask bot outputs bundle info in the PR, which includes current bundle size, increase relative to `main`, and link to html generated by source map explorer

### Stakeholder review needed before the work gets merged

- [ ] Engineering (needed in most cases)
- [ ] Design
- [ ] Product
- [ ] QA (automation tests are required to pass before merging PRs but not all changes are covered by automation tests - please review if QA is needed beyond automation tests)
- [ ] Security
- [ ] Legal
- [ ] Marketing
- [ ] Management (please specify)
- [ ] Other (please specify)

### References

MVP for JS bundle size - https://github.com/MetaMask/metamask-mobile/issues/10527
Extension's designated repo for tracking bundle size - https://github.com/MetaMask/extension_bundlesize_stats
source-map-explorer - https://github.com/danvk/source-map-explorer?tab=readme-ov-file
Extension's implementation using source-map-explorer - https://github.com/search?q=repo%3AMetaMask%2Fmetamask-extension%20source-map-explorer&type=code

**Comment by bsgrigorov** [comment]
PR merged https://github.com/MetaMask/metamask-mobile/pull/11083
getting bundle size data in here https://github.com/MetaMask/mobile_bundlesize_stats/blob/main/stats/bundle_size_data.js
