### ISSUE TITLE
Enable Merge Queues: GH Action to check for pass/fail SonarQuality Gate

### ISSUE THREAD

**Issue by sethkfman** [MetaMask/metamask-mobile#10689]
### What is this about?

This ticket will enable a GH action that can validate a PR for success/fail of SonarCloud Quality Gate. 

### Scenario

- Test in a standard PR process
  - It should pass/fail in the same manner as the SonarCloud Quality Gate 
- Test in a merge queue
  - It should be skipped 

### Technical Details

- Create a GH action that can detect the success/fail of the SonarCloud Quality Gate
   - [GH action directory](https://github.com/MetaMask/metamask-mobile/tree/main/.github/workflows)
   - Possible options it can be detected looking at the result of a step or comment within the PR 
   - Could look at `on: issue_comment: types: [created]` as trigger for review of pass/fail
- Add a check to the action to skip during Merge Queue Analysis the CLA step check should work [here](https://github.com/MetaMask/metamask-mobile/blob/0d1e8157b01ab26561c4559cbd45bebd13e53a8d/.github/workflows/cla.yml#L10)
- Disable the SonarCloud required build step and require this new action. Will require @Cal-L or @sethkfman. 

### Acceptance Criteria

- Running in a PR stage blocks/passes PR if the quality gate works
- Running in the merge queue allows a PR to successfully complete by skipping this action ([merge-queue-test](https://github.com/MetaMask/metamask-mobile/tree/merge-queue-test))

### Stakeholder review needed before the work gets merged

- [ ] Engineering (needed in most cases)
- [ ] Design
- [ ] Product
- [ ] QA (automation tests are required to pass before merging PRs but not all changes are covered by automation tests - please review if QA is needed beyond automation tests)
- [ ] Security
- [ ] Legal
- [ ] Marketing
- [ ] Management (please specify)
- [ ] Other (please specify)

**Comment by Daniel-Cross** [comment]
Created a workflow that should check the PR comments and return pass or fail based on the Sonar Cloud Quality Gate comment specifically. Should also detect and skip if in Merge Queue Analysis.

Need someone else with more experience with our workflows to double check this works as expected.

cc: @sethkfman
