### ISSUE TITLE
[BUG]: Browser loading site with CloudFlare

### ISSUE THREAD

**Issue by sethkfman** [MetaMask/metamask-mobile#10717]
### What is this about?

A user is having an issue passing the CloudFlare verification of this website, [paipot.com](http://paipot.com/), in the MM app’s built-in browser on iOS. 

The user is running the latest available app, version 7.28.1. It is an infinitive loop of loading and ending up with an error.

The CloudFlare verification process passes on the PC machine, and the Chrome/Brave app is used with no issues.
It seems the MetaMask built-in browser is blocking the verification process from passing, resulting in the page not being loaded.

Error Screen:
![image](https://github.com/user-attachments/assets/a0df54de-a7d1-42d2-8a8a-7ab70da6d4c3)

Verifying Screen:
![image](https://github.com/user-attachments/assets/3451bb49-8f71-49e4-899d-e8c33aa5701f)

### Stakeholder review needed before the work gets merged

- [x] Engineering (needed in most cases)
- [ ] Design
- [ ] Product
- [ ] QA (automation tests are required to pass before merging PRs but not all changes are covered by automation tests - please review if QA is needed beyond automation tests)
- [ ] Security
- [ ] Legal
- [ ] Marketing
- [ ] Management (please specify)
- [ ] Other (please specify)

### References

[Slack Thread](https://consensys.slack.com/archives/C8RSKCNCD/p1724146292941879)

**Comment by DanielTech21** [comment]
Another case with defillama.com website.
![image (3)](https://github.com/user-attachments/assets/786068d5-d429-4755-ba2a-2e359e4c9006)

**Comment by wufd** [comment]
Same issue
