### ISSUE TITLE
Can you support Import JSON Keystore？

### ISSUE THREAD

**Issue by yourihua** [MetaMask/metamask-mobile#1074]
Can you support Import JSON Keystore？

**Comment by brunobar79** [comment]
@bdresser  IMO this is an advanced feature that doesn't fit in the mobile roadmap, but would be good to see if we can pull any number from the extension about how popular is it.

**Comment by omnat** [comment]
We haven't received any more requests around it in some time. It's a nice to have, and has a solid workaround with Private key import. Closing it.
