### ISSUE TITLE
[Bug]: Gas info not loading for send transactions initiated within the wallet

### ISSUE THREAD

**Issue by bschorchit** [MetaMask/metamask-mobile#10895]
### Describe the bug

After updating to v7.29 and starting a send transaction within the app, some users are not able to confirm the transaction due to the gas info never loading. 

The issue happens to all networks, but only for send transactions started within the app. MM swaps and dapp proposed transactions seem to be unaffected. 

### Expected behavior

Gas info to load timely and users be able to confirm the transaction.

### Screenshots/Recordings

![image](https://github.com/user-attachments/assets/42c5b7a8-eb08-4dbf-b770-3d20b9c33324)

### Steps to reproduce

1. Update your app to v7.29
2. Start a send transaction
3. See the MM confirmation for the send transaction with the gas info loading forever

Note: not everyone is able to repro this so there's more steps to repro that we don't know of yet

### Detection stage

In production (default)

### Version

7.29

### Build type

None

### Device

iphone

### Operating system

iOS

**Comment by ripcurldog** [comment]
WHat is the fix for this? I have had this issue for several days?

**Comment by annonymous89** [comment]
This is still an issue on Android phones. Galaxy Z fold 5, Android 14, OneUzi 6.1 is the affected device.

**Comment by yahortsaryk** [comment]
I cannot proceed with sending a transaction on my Galaxy S20 because of this issue. The infinite loading of *Estimated gas fee* blocks me from sending transaction

**Comment by ArteSuaveAngelo** [comment]
> WHat is the fix for this? I have had this issue for several days? I'm using the newest Iphone Pro Max - all up to date with the latest OS (it updated about 4 nights ago)..

Hello, I was able to resolve this by going into the advance settings and resetting my account. This deletes all transactions but keeps your info on metamask. I was able to transfer after. Hope this helps.

**Comment by ArteSuaveAngelo** [comment]
> I cannot proceed with sending a transaction on my Galaxy S20 because of this issue. The infinite loading of **Estimated gas fee** blocks me from sending transactions

Hello, I was able to resolve this by going into the advance settings and resetting my account. This deletes all transactions but keeps your info on metamask. I was able to transfer after. Hope this helps.

**Comment by ArteSuaveAngelo** [comment]
> This is still an issue on Android phones. Galaxy Z fold 5, Android 14, OneUi 6.1 is the affected device.

Hello, I was able to resolve this by going into the advance settings and resetting my account. This deletes all transactions but keeps your info on metamask. I was able to transfer after. Hope this helps.

**Comment by annonymous89** [comment]
> > This is still an issue on Android phones. Galaxy Z fold 5, Android 14, OneUi 6.1 is the affected device.
> 
> Hello, I was able to resolve this by going into the advance settings and resetting my account. This deletes all transactions but keeps your info on metamask. I was able to transfer after. Hope this helps.

This is the fix. Cheers!

**Comment by HoussineAgha** [comment]
I have this problem with deeplink links when trying with sepolia network



![WhatsApp Image 2024-09-03 at 9 47 02 PM](https://github.com/user-attachments/assets/e8af83e1-665b-4d7d-bcaa-5139c2c9143b)
