### ISSUE TITLE
[Bug]: "Unlock with Face ID" and "Unlock with device passcode" are missing from settings on mobile 

### ISSUE THREAD

**Issue by yanrong-chen** [MetaMask/metamask-mobile#10907]
### Describe the bug

I am unable to find "Unlock with Face ID" and "Unlock with device passcode" on the "Security and privacy" page in settings on mobile. There are an empty space between "Auto lock" and "Remember me" instead. 
I am also unable to unlock with Face ID even though it was enabled from my ios system settings.
![IMG_2361](https://github.com/user-attachments/assets/2d123c33-63ee-4637-9473-ecb493a52a03)

### Expected behavior

Expected:
![Uploading 326948166-0eeaee87-caad-47fe-9e98-c9b13be9889f.png…]()

### Screenshots/Recordings

https://github.com/user-attachments/assets/bd1d1e59-a97a-422f-870c-9d82c3b159cf

### Steps to reproduce

1. Go to MetaMask > Settings
2. Go to "Security and privacy"

### Detection stage

In production (default)

### Version

7.29.0

### Build type

None

### Device

Iphone

### Operating system

iOS

**Comment by Cal-L** [comment]
This is an issue since we should see the option to unlock with face ID if it is enabled from the OS level

**Comment by Daniel-Cross** [comment]
@yanrong-chen Tried to replicate this issue today on version `7.31.0` on both a physical iPhone 13 pro and on simulator iPhone 15 pro (18.1 beta) and it seems to be fixed.

Can you please confirm that on the latest version of Metamask this issue is solved for you? If not, please can you provide more details such as device, app and iOS version?

Thanks

**Comment by yanrong-chen** [comment]
@Daniel-Cross Yes, just checked and this seems to be fixed when updated to the latest ios version.

**Comment by gauthierpetetin** [comment]
Hi @yanrong-chen , we're closing this issue for now. Feel free to re-open it if you encounter it again
