### ISSUE TITLE
[Bug]: Dark Mode Token details block explorer button Visibility

### ISSUE THREAD

**Issue by Andepande** [MetaMask/metamask-mobile#10901]
### Describe the bug

In Dark Mode on the Token Overview screen, the navigation button to Block Explorer is not clearly visible due to dark colors.

### Expected behavior

Expected Outcome:
The "View on Block Explorer" and "Token Details" buttons should appear clearly visible in a modal at the bottom of the page.

### Screenshots/Recordings

![image](https://github.com/user-attachments/assets/b3ca5ba4-47de-4d6c-8a4d-cffdb906b9aa)

### Steps to reproduce

Steps to Reproduce:
- Ensure the app/device is in Dark Mode.
- Navigate to the Main Wallet view.
- Import a token, ensuring it displays on the Main Wallet view.
- Select the token and navigate to the Token Overview screen.
- Tap the three-dot menu button (top right of the page) to open additional options.

### Detection stage

During release testing

### Version

v7.30.0 build 1401

### Build type

None

### Device

IOS

### Operating system

iOS

### Additional context

Only on IOS

**Comment by amandaye0h** [comment]
Resolved [in this ticket](https://github.com/MetaMask/metamask-mobile/pull/10562)
