### ISSUE TITLE
[Bug]: "Network added" bottom sheet style and paddings are off

### ISSUE THREAD

**Issue by yanrong-chen** [MetaMask/metamask-mobile#10910]
### Describe the bug

Currently the style and paddings for the new "Network added"bottom sheet are off. Please use Design system defined bottom sheet with header and footer component. 
![screenshot](https://github.com/user-attachments/assets/763e0bca-151a-4056-a524-1779baa1dd19)

### Expected behavior

Expected:
<img width="445" alt="Screenshot 2024-08-29 at 3 59 14 PM" src="https://github.com/user-attachments/assets/611ff02d-2d60-47a3-8190-d241a08945c3">

### Steps to reproduce

1. Go to settings (or open network picker from wallet view)
2. Open "Networks"
3. Add a new network
4. You will see this "network added" bottom sheet

### Detection stage

In production (default)

### Version

7.29.0

### Build type

None

### Device

iphone

### Operating system

iOS

**Comment by amandaye0h** [comment]
@salimtb Can you make sure we update this styling?

**Comment by salimtb** [comment]
> @salimtb Can you make sure we update this styling?

yes i'll take it
