### ISSUE TITLE
Token Detail's Overflow Menu is not themed

### ISSUE THREAD

**Issue by brianacnguyen** [MetaMask/metamask-mobile#10923]
### What is this about?

In token detail page, when the user clicks on the overflow menu, the action buttons are not themed and is hard to see on dark mode
![Simulator Screenshot - iPhone 15 Pro Max - 2024-08-29 at 19 31 16](https://github.com/user-attachments/assets/a61ed159-246e-4bad-99ba-6f270f6bfee9)

### Stakeholder review needed before the work gets merged

- [ ] Engineering (needed in most cases)
- [ ] Design
- [ ] Product
- [ ] QA (automation tests are required to pass before merging PRs but not all changes are covered by automation tests - please review if QA is needed beyond automation tests)
- [ ] Security
- [ ] Legal
- [ ] Marketing
- [ ] Management (please specify)
- [ ] Other (please specify)

**Comment by amandaye0h** [comment]
This has been addressed by @gambinish [in this ticket](https://github.com/MetaMask/metamask-mobile/pull/10562)

**Comment by amandaye0h** [comment]
@brianacnguyen @hilvmason Suggesting we close it if that's ok!

**Comment by amandaye0h** [comment]
Resolved by @gambinish [in this ticket](https://github.com/MetaMask/metamask-mobile/pull/10562)
