### ISSUE TITLE
[Bug]: Close button on Tooltip modals in edit gas flow doesn't work

### ISSUE THREAD

**Issue by SayaGT** [MetaMask/metamask-mobile#10948]
### Describe the bug

Close button on tooltip modals doesn't work and there is no way to get out of the flow other than restarting the app.

Steps to reproduce

1. Create a transaction
2. Click on edit gas
3. Click on Low or Aggressive gas options
4. Click on the tooltips next to the estimated time
5. Try to close the tooltip modal
![IMG_3049](https://github.com/user-attachments/assets/9c71e1dc-6d6c-4361-be03-94f4860d06b8)
![IMG_3048](https://github.com/user-attachments/assets/2f3af393-390c-4694-849c-6202a8ecaf9c)

### Expected behavior

Expected behavior - Modal should close when close button is clicked

### Steps to reproduce

**Steps to reproduce**

1. Create a transaction
2. Click on edit gas
3. Click on Low or Aggressive gas options
4. Click on the tooltips next to the estimated time
5. Try to close the tooltip modal

### Detection stage

In production (default)

### Version

7.30.0

### Build type

None

### Device

iphone 13 pro

### Operating system

iOS

**Comment by digiwand** [comment]
There may be a duplicate ticket cc: @bschorchit
