### ISSUE TITLE
Token details page: Extension and mobile are inconsistent

### ISSUE THREAD

**Issue by jassang** [MetaMask/metamask-mobile#10955]
### What is this about?

Extension features token details and market details, but mobile has neither. [See my other ticket noting inconsistencies within extension, where Matic features token details, but ETH doesn't](https://github.com/MetaMask/metamask-extension/issues/26790).

![image](https://github.com/user-attachments/assets/85754aeb-725d-4b50-afdb-ec4831f14cda)

### Stakeholder review needed before the work gets merged

- [ ] Engineering (needed in most cases)
- [X] Design
- [X] Product
- [ ] QA (automation tests are required to pass before merging PRs but not all changes are covered by automation tests - please review if QA is needed beyond automation tests)
- [ ] Security
- [ ] Legal
- [ ] Marketing
- [ ] Management (please specify)
- [ ] Other (please specify)

**Comment by amandaye0h** [comment]
Resolved mobile issues [in this ticket](https://github.com/MetaMask/metamask-mobile/pull/11112)
 And Extension ordering [in this ticket](https://github.com/MetaMask/metamask-extension/pull/26867)
