### ISSUE TITLE
Token details page: Action buttons are inconsistent and awkward

### ISSUE THREAD

**Issue by jassang** [MetaMask/metamask-mobile#10954]
### What is this about?

This is regarding the send/receive and buy/swap buttons on the token details page. 

When you scroll, swap and buy stay pinned to the bottom, while send and receive remain under the graph. Where's Bridge? Stake could also live on the ETH page. This feels inconsistent. All the actions should live together in one section and behave the same way. 

Also, why is 'Swap' the only one that's highlighted? 

![image](https://github.com/user-attachments/assets/f1319e7d-adce-44a2-9241-d530bd5a835b)

### Stakeholder review needed before the work gets merged

- [ ] Engineering (needed in most cases)
- [X] Design
- [X] Product
- [ ] QA (automation tests are required to pass before merging PRs but not all changes are covered by automation tests - please review if QA is needed beyond automation tests)
- [ ] Security
- [ ] Legal
- [ ] Marketing
- [ ] Management (please specify)
- [ ] Other (please specify)

**Comment by amandaye0h** [comment]
Resolved [in this ticket](https://github.com/MetaMask/metamask-mobile/pull/11112)
