### ISSUE TITLE
[Bug] User able to add Ledger account with existing account name

### ISSUE THREAD

**Issue by vivek-consensys** [MetaMask/metamask-mobile#10967]
Bitrise Build: https://app.bitrise.io/app/be69d4368ee7e86d/build/d217a4db-d343-43ed-887d-c7dc103cb9f2/artifact/308fa13fdcadc0dc/p/7db511ad6b94e0a1e04bc9bea869a583

Device: iOS 17.6.1

1. Install MM
2. Recover from SRP
3. Rename 'Account 1' to 'Ledger 1'
4. Connect Ledger device
5. Add 1 Ledger account
6. Both accounts are displayed on Account list

Expected: Error displays 'Account name already exists' and user unable to add existing account name
Actual: 
<img width="333" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNmVqQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1518b952ff8565cc8a07ece6fc4e18261e572a22/image.png" alt="image.png" />

**Comment by dawnseeker8** [comment]
has fixed the issue with following [PR #12199](https://github.com/MetaMask/metamask-mobile/issues/12199)
