### ISSUE TITLE
[Bug] When adding Ledger accounts from Legacy HD Path, it should be displayed on the Account name

### ISSUE THREAD

**Issue by vivek-consensys** [MetaMask/metamask-mobile#10987]
Bitrise Build: https://app.bitrise.io/build/d217a4db-d343-43ed-887d-c7dc103cb9f2?tab=artifacts
Device: iOS 17.6.1

1. Install MM
2. Restore from SRP
3. Connect to Ledger hardware device
4. Switch to Legacy Ledger accounts
5. Add 2x Legacy accounts

Expected: Legacy tag to be displayed on the account name, when added. 
_Ledger 1 (legacy)_

<img width="719" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMXltQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3425bc2b605ae235b0527103b48fb12292d5c7ad/image.png" alt="image.png" />

Actual: Legacy tag not displayed and added as normal Ledger account

<img width="369" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMXVtQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--aa2420271d29b61b819ec8486401304a4910d57b/Screenshot%202024-09-03%20at%2011.25.43.jpeg" alt="Screenshot 2024-09-03 at 11.25.43.jpeg" />

**Comment by dawnseeker8** [comment]
The fix has been added to latest code in this PR. https://github.com/MetaMask/metamask-mobile/pull/10755

**Comment by dawnseeker8** [comment]
@vivek-consensys  you can test again with this build https://app.bitrise.io/app/be69d4368ee7e86d/pipelines/f0d63a58-394d-4d71-a5e5-7c3b44089643

**Comment by vivek-consensys** [comment]
Fixed with the latest build. 

<img width="332" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMDIyQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c413e57ac6d1d6000ada95326dafb721cf9d384f/image.png" alt="image.png" />
