### ISSUE TITLE
Page load loop on manager.ens.domains 

### ISSUE THREAD

**Issue by chatch** [MetaMask/metamask-mobile#1098]
On Android v0.2.4.

Navigating to "manager.ens.domains" I can see a partial load of the page for about 2 seconds then it returns to a white screen and tries again. Continously loops like this and the DApp is not loaded..

"ens.domains" works fine as do other DApps (I use OpenSea and Kyber).

I tested manager.ens.domains in CoinBase Wallet (Android) and Metamask plugin (Firefox Linux) and it works fine in these environments.

I can't see what's happening but could it be an issue with handling the 301 from http? manager.ens.domains returns "Location: https://manager.ens.domains/" on http request attempts.

**Comment by estebanmino** [comment]
Hi @chatch thanks for reporting, we already fixed this issue with https://github.com/MetaMask/metamask-mobile/issues/1043 fix will be released soon.
