### ISSUE TITLE
Import an Account in android Paste cannot do work.

### ISSUE THREAD

**Issue by yourihua** [MetaMask/metamask-mobile#1099]
Import an Account in android Paste cannot do work.

**Comment by estebanmino** [comment]
Hi @yourihua could you elaborate more on this? I tried going to Import an Account, on Android, from Accounts list, tried to paste a private key and it worked. Thanks.

**Comment by yourihua** [comment]
`componentDidMount = () => {
		this.mounted = true;
		// Workaround https://github.com/facebook/react-native/issues/9958
		this.state.inputWidth &&
			setTimeout(() => {
				this.mounted && this.setState({ inputWidth: '100%' });
			}, 500);
	};`

if i change this code for ImportPrivateKey/index.js, it worked, I do not know why it has to be like this.

**Comment by brunobar79** [comment]
We tried with different android devices and we can't reproduce. Feel free to reopen if the problem persist and include more info (Device, OS version, app version, etc)
