### ISSUE TITLE
Android app is not run in android Studio.

### ISSUE THREAD

**Issue by arindam9851** [MetaMask/metamask-mobile#1102]
ERROR: /home/lenovo/android projects/Work/metamask-mobile-develop/node_modules/react-native/react.gradle (No such file or directory)

**Comment by brunobar79** [comment]
Looks like you are missing the dependencies.  Please take a look at the instructions in the README.md file and make sure you follow all the steps first and make sure you can build the app from your terminal.

Once that’s working choose “add an existing android project” inside Android studio and select the android folder of the repo (not the root).

I can confirm that works correctly.
