### ISSUE TITLE
AccountsController upgrade from v14 to v18

### ISSUE THREAD

**Issue by desi** [MetaMask/metamask-mobile#11041]
### What is this about?

The `AccountsController` is behind by four major versions and needs to be updated.
Upgrade from v14 to v18.

Because this controller is pretty far behind we expect it will have a number of breaking changes that will need to be dealt with so we haven't combined this with any other controller upgrades.

### Scenario

n/a

### Design

n/a

### Technical Details

n/a

### Threat Modeling Framework

n/a

### Acceptance Criteria

- `AccountsController` is on v18

### Stakeholder review needed before the work gets merged

- [X] Engineering (needed in most cases)
- [ ] Design
- [ ] Product
- [ ] QA (automation tests are required to pass before merging PRs but not all changes are covered by automation tests - please review if QA is needed beyond automation tests)
- [ ] Security
- [ ] Legal
- [ ] Marketing
- [ ] Management (please specify)
- [ ] Other (please specify)

**Comment by owencraston** [comment]
The accounts controller was already updated to version 18.1.0 in this PR by @k-g-j: https://github.com/MetaMask/metamask-mobile/pull/10821. An upgrade to version 18.2.0 would be nice though.
