### ISSUE TITLE
[Design quality]: Update the mobile header to the design system header

### ISSUE THREAD

**Issue by amandaye0h** [MetaMask/metamask-mobile#11050]
### Describe the bug

In mobile, the header we have is deprecated across many pages. Updating all headers to the version we have in our design system creates a consistent look and feel.

### Expected behavior

Headers for all pages use [the DS version](https://github.com/MetaMask/metamask-mobile/tree/main/app/component-library/components/HeaderBase), namely:
- Token Details
- Transactions
- Buy
- Sell
- Swap
- Send
- Receive (new receive flow, [ticket #10061](https://github.com/MetaMask/metamask-mobile/pull/10061) )

### Screenshots/Recordings

<img width="1106" alt="Screenshot 2024-10-18 at 12 56 18 AM" src="https://github.com/user-attachments/assets/2cad6425-eb01-4601-8611-1dcc011292ce">

[Figma link](https://www.figma.com/design/bkJ9Ot0HGXiakMqZtQfs8G/Design-Quality?node-id=2362-458)

### Steps to reproduce

1. Open MetaMask
2. Click on Token details

### Detection stage

In production (default)

### Version

11.16.15

### Build type

None

### Device

Samsung

### Operating system

Android

### Additional context

Ping @amandaye0h for context

**Comment by brianacnguyen** [comment]
This issue has been broken down into multiple issues
https://github.com/MetaMask/metamask-mobile/issues/11854
https://github.com/MetaMask/metamask-mobile/issues/12768
https://github.com/MetaMask/metamask-mobile/issues/12769
https://github.com/MetaMask/metamask-mobile/issues/12770
https://github.com/MetaMask/metamask-mobile/issues/12771
https://github.com/MetaMask/metamask-mobile/issues/12772
