### ISSUE TITLE
[Bug] Unspecified error displayed when adding multiple HD path Ledger accounts into Account list

### ISSUE THREAD

**Issue by vivek-consensys** [MetaMask/metamask-mobile#11059]
Bitrise build: https://app.bitrise.io/build/b41192ef-2391-431f-b5fe-db4868994c5e?tab=artifacts
OS: Android 14

1. Install MM
2. Recover from SRP
3. Import Ledger hardware wallet
4. Add 2x Ledger Live accounts into account list
5. Verify 2x Ledger Live accounts are added
6. Add 2x Legacy accounts into account list
7. Verify 2x Legacy accounts are added
8. Add 2x BIP44 Leger accounts into account list

Expected: No errors displayed and 1 account pre-selected 
Actual:- Error displayed on 'Select an Account' page. 2 accounts pre-selected

<img width="369" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeHF5Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4e4c0ee0b0e74d2d2fa64c34c390db009d215aa2/image.png" alt="image.png" />

[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeHV5Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e483e2b629525bbc049cc7294aaefff6acb114e8/Screen_Recording_20240905_145141_MetaMask-QA.mp4)

**Comment by dawnseeker8** [comment]
This issue should be fixed in latest code in https://github.com/MetaMask/metamask-mobile/pull/10755

**Comment by dawnseeker8** [comment]
@vivek-consensys  you can test again with latest build in https://app.bitrise.io/app/be69d4368ee7e86d/pipelines/f0d63a58-394d-4d71-a5e5-7c3b44089643

**Comment by vivek-consensys** [comment]
Fixed with the latest build 
<img width="332" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMUMyQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b3e6df26cd5cbe5c6167863f30035bd5da5232b1/image.png" alt="image.png" />
