### ISSUE TITLE
[Bug]: App freezes for 1 minute then crash when swapping unapproved token

### ISSUE THREAD

**Issue by davibroc** [MetaMask/metamask-mobile#11085]
### Describe the bug

After an app install or app upgrade, or after an account import, if I swap an unapproved token the app will hang and crash after 1 minute.

It started happening with RC 7.27.1 after the TransactionController jumps from v13 to v35 with this commit
https://github.com/MetaMask/metamask-mobile/pull/10263 

If I build the app with the following previous commit it doesn't repro
https://github.com/MetaMask/metamask-mobile/pull/10458

Watch video 

https://github.com/user-attachments/assets/1a884258-a0f3-4ddd-b5ff-4c5b8c131e81

### Expected behavior

The Swap completes successfully

### Steps to reproduce

1. Install the app from scratch on the Android or iOS emulator
2. Import an account with funds, you can use a Tenderly fork to save money
3. Swap ETH->Unapproved token
4. Swap Unapproved token->ETH

Notice the app freezing and then crashing after 1 minute

### Detection stage

During 7.30.0 release testing

### Version

7.27.1 and older

### Build type

None

### Device

iPhone 12 Pro 

### Operating system

iOS

**Comment by infiniteflower** [comment]
I was able to reproduce on iOS simulator on `release/7.26.0`

**Comment by davibroc** [comment]
I was able to reproduce it too up to this commit https://github.com/MetaMask/metamask-mobile/pull/10339 
Since it's your change @infiniteflower I will assign it to you.
Before that commit I am not seeing even a pause at the point where it normally hangs as you see below


https://github.com/user-attachments/assets/8365b459-3706-474c-afbe-c4baf56a336e

**Comment by davibroc** [comment]
@infiniteflower I confirm that this started happening after the TransactionController jumps from v13 to v35 with this commit https://github.com/MetaMask/metamask-mobile/pull/10263 

If I build the app with previous the following previous commit it doesn't repro
https://github.com/MetaMask/metamask-mobile/pull/10458
