### ISSUE TITLE
The Seed Phrase of the two accounts is the same

### ISSUE THREAD

**Issue by yourihua** [MetaMask/metamask-mobile#1110]
If I create two accounts, in the seed seed view, The Seed Phrase of the two accounts is the same.

**Comment by brunobar79** [comment]
One seed phrase is the root of all the accounts you generated with MetaMask.
You might be confusing it with the private key, which is specific to each account.

You can learn more here: https://metamask.github.io/metamask-docs/Main_Concepts/Common_Terms
