### ISSUE TITLE
Update label - importing non ledger account 

### ISSUE THREAD

**Issue by angelcheung22** [MetaMask/metamask-mobile#11128]
when I connect a bunch of Ledger accounts
Then go to Portfolio in the browser
switch on notifications for a non Ledger account
the request to sign the message has a butting “Sign with Ledger” even though that specific account I’m signing isn’t a Ledger account but a native MM account from the SRT. 

Issue:
https://files.slack.com/files-pri/T02P98BKE-F07LN463YE6/img_8919.png

**Comment by dawnseeker8** [comment]
fix in PR #10755

**Comment by vivek-consensys** [comment]
tested using bitrise build : https://app.bitrise.io/build/4cbafa74-85c7-4e1f-86e0-4cc2847d4a53?tab=artifacts

<img width="369" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOFRCQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--46cb7fc2774004f28411c25d3bf71995ec16d720/Screenshot%202024-09-10%20at%2013.11.29.jpeg" alt="Screenshot 2024-09-10 at 13.11.29.jpeg" />
