### ISSUE TITLE
chore(deps): Bump `@metamask/ppom-validator` from `0.32.0` to `0.35.1`

### ISSUE THREAD

**Issue by MajorLift** [MetaMask/metamask-mobile#11134]
### What is this about?

The `PPOMController` is behind by two major versions and needs to be updated.

### Stakeholder review needed before the work gets merged

- [ ] Engineering (needed in most cases)
- [ ] Design
- [ ] Product
- [ ] QA (automation tests are required to pass before merging PRs but not all changes are covered by automation tests - please review if QA is needed beyond automation tests)
- [ ] Security
- [ ] Legal
- [ ] Marketing
- [ ] Management (please specify)
- [ ] Other (please specify)

**Comment by desi** [comment]
[This is blocked by #213](https://github.com/MetaMask/ppom-validator/issues/213)
