### ISSUE TITLE
Livepeer Explorer not working

### ISSUE THREAD

**Issue by chrishobcroft** [MetaMask/metamask-mobile#1114]
https://github.com/MetaMask/metamask-mobile/issues/898 was closed but it's not fixed, and I am unable to reopen it.

So I'm creating a new issue

**Comment by chrishobcroft** [comment]
![Screenshot_20190927-201639](https://user-images.githubusercontent.com/2212651/65796352-48733600-e164-11e9-8abe-a7eb40ca1a21.png)

**Comment by chrishobcroft** [comment]
Here is how the page loads, note that there is no "my account" icon

![Screenshot_20190927-202121](https://user-images.githubusercontent.com/2212651/65796428-76f11100-e164-11e9-9cc4-e0682df9f15f.png)

When I tap on UNLOCK METAMASK it takes me here (metamask.io):

![Uploading Screenshot_20190927-202129.png…]()

**Comment by brunobar79** [comment]
Fixed on both OS
Android:   https://recordit.co/qxDWuNcL8h
iOS: https://recordit.co/KUFlrVOl5h

This should be live before the end of the week.

**Comment by chrishobcroft** [comment]
Bravo!

https://twitter.com/chrishobcroft/status/1179204515230339074?s=19
