### ISSUE TITLE
Not working with qr code scanner from burner wallet

### ISSUE THREAD

**Issue by PaulRBerg** [MetaMask/metamask-mobile#1117]
## Description
Not sure if #73 was about the same issue, but qr code scanning by taking a photo doesn't work in the latest version.

I deployed my own burner at [sablier.burnerfactory.com](https://sablier.burnerfactory.com) and did this:

1. Open the burner in the MetaMask in-app browser
2. Scan a qr code via "Take a Photo"
3. Take photo and when I return the screen is white

Here's a screenshot:

![IMG_6695](https://user-images.githubusercontent.com/8782666/65823522-83f32a80-e260-11e9-93ea-2d11d432e5e4.PNG)

Note: I tried it in Coinbase Wallet and it worked there.

Cc-ing @dmihal in case this is related to [burner-wallet-2](https://github.com/dmihal/burner-wallet-2).

## Environment

- iPhone XR
- iOS 12.3.1
- MetaMask Mobile 0.2.4

**Comment by dmihal** [comment]
I haven't been able to reproduce this in Metamask Mobile on Android, so i'm guessing it's iOS specific

**Comment by estebanmino** [comment]
Hi @PaulRBerg could you try with latest version? We're on v0.2.7 now and we fixed those issues. if not please let us now. Thanks!

**Comment by EtDu** [comment]
Does not appear to be an issue. Please reopen otherwise

**Comment by zech564** [comment]
Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
