### ISSUE TITLE
chore(deps): Bump `@metamask/approval-controller` from `^7.0.1` to `^7.1.0`

### ISSUE THREAD

**Issue by MajorLift** [MetaMask/metamask-mobile#11178]
### What is this about?

This involves removing or replacing the patch for `7.0.2`.

### Stakeholder review needed before the work gets merged

- [ ] Engineering (needed in most cases)
- [ ] Design
- [ ] Product
- [ ] QA (automation tests are required to pass before merging PRs but not all changes are covered by automation tests - please review if QA is needed beyond automation tests)
- [ ] Security
- [ ] Legal
- [ ] Marketing
- [ ] Management (please specify)
- [ ] Other (please specify)

**Comment by mikesposito** [comment]
Target package version is now `^7.1.0`

**Comment by mcmire** [comment]
Closed via https://github.com/MetaMask/metamask-mobile/pull/11911.
