### ISSUE TITLE
Uniswap transaction stuck - seems to be multiple ledger devices issue

### ISSUE THREAD

**Issue by angelcheung22** [MetaMask/metamask-mobile#11215]
I tried to transact on Uniswap in the browser and also Swap directly, in both cases I got stuck on this screen - it never connects and sends the tx/msg for signing to the Ledger device. With noting that I added different accounts on different Ledger devices. MetaMask is allowed to use bluetooth, bluetooth is enabled on the device, I’m in the Ethereum app on the device but it gets stuck on this screen. Worth testing on your side. See screenshots for both Uniswap approve and Swap. Worth noting that the Ledger app does manage to connect to the device and send stuff for signature, so it seems to be a MetaMask issue.

<img width="369" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMnpYQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9f56254c1363a477b38ce6ebf1a6d6453b3ab41e/image.png" alt="image.png" />
<img width="369" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMjNYQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--db74874cfd2ca3a4e0eefebc02a89096e21f48fc/image.png" alt="image.png" />

>
I’m on the latest version and iOS. But I think it has to do with the fact that I am connecting multiple Ledger accounts from different Ledger devices. Because I did manage to transact with one of them not the other (either it didn’t connect or it smsaid that the device was locked wheb it wasn’t).

**Comment by coreyjanssen** [comment]
@angelcheung22 updated error content here:

Multiple devices aren’t supported yet. To add a new Ledger device, you’ll need to remove an older one.

**Comment by vivek-consensys** [comment]
Bitrise build :- https://app.bitrise.io/app/be69d4368ee7e86d/pipelines/6f47f9ba-2392-4d4e-8a68-ae198b574582?tab=artifacts

Steps followed:- 

1. I connect Ledger 1 and add 2x accounts
2. I attempt to connect Ledger 2
3. Error message is displayed
4. I disconnect Ledger 1 and all accounts are removed
5. I attempt to connect Ledger 2
6. Error message is still displayed

Expected: Error message to be removed as there are no Ledger devices connected. 


https://github.com/user-attachments/assets/b9849821-be1c-4bd4-b811-ccc60a438a14
