### ISSUE TITLE
MM is stuck once click out of swap pop up - UI issue

### ISSUE THREAD

**Issue by angelcheung22** [MetaMask/metamask-mobile#11216]
in the case of uniswap in the browser, if I click outside the popup it goes to the Ledger website in the background and if I swipe the popup away I’m stuck on the Ledger website there’s no way to change tab, go back or anything, you don’t even see the MetaMask controls anymore, the only way to get unstuck is to hard shut MetaMask.

**Comment by vivek-consensys** [comment]
MM also crashing when user rejects the txn on the device, when swapping. 

[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBenN6Qnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8d54ab43db845febde47fa78240c0aff20dbbff9/RPReplay_Final1728461873.MP4)

**Comment by vivek-consensys** [comment]
Tested on bitrise [build](https://app.bitrise.io/app/be69d4368ee7e86d/installable-artifacts/e9f4e40029fc0ec4/public-install-page/3719bf3a2458ffa5f346334553f44a0e)

Working as expected without any app crashes when clicking out of the swap pop up.


[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBLzVUQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2f91c055f569543c339c53ef7d3e214ea7ee6da4/ScreenRecording_10-17-2024%2012-04-00_1.MP4)
