### ISSUE TITLE
window.web3 and window.ethereum both of them returns undefined on sub pages...

### ISSUE THREAD

**Issue by ersanyakit** [MetaMask/metamask-mobile#1140]
Platform : Android
Metamask Version : 0.24(17)

typeof window.ethereum always returns "undefined"
typeof window.web3 always returns "undefined"

web3 and ethereum working correctly on a website home page... 
but sub pages in a website always returns undefined...

          let msg = "type of window.ethereum :"+typeof window.ethereum;
                    msg += "\r\ntype of window.web3:"+typeof window.web3;
                    msg += "\r\nMetaMask is not accessible!";

**In Sub Page**
![photo5819179708665934306](https://user-images.githubusercontent.com/10724463/66247774-5e1ac980-e729-11e9-8992-7b08f4a5a010.jpg)

**In Home Page**
![photo5819179708665934307](https://user-images.githubusercontent.com/10724463/66248024-bf8f6800-e72a-11e9-992a-6115b7533fcf.jpg)

**Comment by ersanyakit** [comment]
@estebanmino any news for this issue? because our clients getting problems on metamask...

**Comment by ibrahimtaveras00** [comment]
@ersanyakit we are now on version 0.2.18
If you update to that version are you still experiencing this issue?

**Comment by sparrowDom** [comment]
I am experiencing a similar problem on our [dapp's homepage](http://ousd.com/). `window.ethereum` and `window.web3` are both `undefined` sometimes. I have 3 devices: iPhone6, OnePlus 6t & OnePlus 8 Pro all running Metamask v1.0.3 (37).

This never happens on the iPhone and OnePlus 6t, but ~50% of the time on page refresh on OnePlus 8 Pro. 

@ibrahimtaveras00 happy to provide any additional info or reproduction steps if needed.

**Comment by omnat** [comment]
Related #1975
