### ISSUE TITLE
'View: Root TypeError: Invalid URL:null' instead of displaying the expected 'Something went wrong' window for incorrect links inserted in MetaMask's in-build browser.

### ISSUE THREAD

**Issue by ZbrancaI** [MetaMask/metamask-mobile#11479]
Entering an incorrect URL triggered the error 'View: Root TypeError: Invalid URL:null' instead of displaying the expected 'Something went wrong' window. This issue seems to occur specifically when there's a mistake in the protocol section ('https//:'). If the error is made elsewhere in the URL, the proper error window appears.

Steps to reproduce:

1. Open the wallet;
2. Open the in-build browser of the wallet;
3. Insert the wrong URL with the mention made in the description (ex: 'htpps://app.uniswap.org');
4. The error 'View: Root TypeError: Invalid URL:null' will occur instead of the 'Something went wrong' window.

- Build: 1437
- Version: 7.32.0
- OS: Android
- Device: Xiaomi Redmi Note 8 Pro

Link to the recording & screenshot:

https://drive.google.com/file/d/1oLiGLQ3XNFMJ9PDjI8A-qJ71uUm1Atet/view?usp=sharing
https://drive.google.com/file/d/1JraUa69u6ZLNFE6Lzb2Xk7qbq6JOkzHz/view?usp=sharing

Expected behavior:

- Entering an incorrect URL, including errors in the protocol section, should trigger the 'Something went wrong' window instead of the 'View: Root TypeError: Invalid URL:null' error.

Actual behavior:

- Entering an incorrect URL, with mistakes on the protocol section, triggers the 'View: Root TypeError: Invalid URL:null'.

Workaround for the error:

- Cleaning the browser history from the Security & Privacy setting.

_Originally posted by @ZbrancaI in https://github.com/MetaMask/mobile-planning/issues/1929#issuecomment-2378879941_

**Comment by smilingkylan** [comment]
@gauthierpetetin Why was this issue closed and removed from "Planning"?

**Comment by gauthierpetetin** [comment]
I was closed by @frankvonhoven on Oct 2, 2024. 
Then, I removed it from planning 3 days ago, as I usually remove old closed issues to clean our board.

@frankvonhoven do you remember why it was closed?
