### ISSUE TITLE
The dark theme on my phone is making some buttons and text in the warning messages invisible. This doesn't affect the buttons' functionality.

### ISSUE THREAD

**Issue by ZbrancaI** [MetaMask/metamask-mobile#11481]
The dark theme on my phone is making some buttons and text in the warning messages invisible. This doesn't affect the buttons' functionality.

Steps to reproduce:

1. Have the device set on dark mode;
2. Open the MetaMask wallet;
3. Open the QR Scanner function;
4. Scan the QR code corresponding to a Private Key;
5. The confirmation window pops up;
6. The 'Private key detected' text and 'cancel'/'yes' buttons are not visible.

- Build: 1437
- Version: 7.32.0
- OS: Android
- Device: Xiaomi Redmi Note 8 Pro

Link to the recording & screenshots:

https://drive.google.com/file/d/1nRe5IyuAwuQwYLXbDxThmw0iNWOBfRd7/view?usp=sharing
https://drive.google.com/file/d/1VVuNEJBwYl-rn_4DbNhgoE3wU3p7RFjF/view?usp=sharing
https://drive.google.com/file/d/1nQvZMf5C95spS_u_A1JCK06xSysRxx3B/view?usp=sharing

Expected behavior:

- The text and the button to be visible even if you're using the dark mode of the phone.

Actual behavior:

- When dark mode is enabled on the device, it causes the pop-up titles and buttons to become invisible. This happens because the window background remains white, while the text and buttons also turn white, blending in and making them unreadable.

Workaround:

- Use light mode on the device

_Originally posted by @ZbrancaI in https://github.com/MetaMask/mobile-planning/issues/1929#issuecomment-2378781250_

**Comment by vinnyhoward** [comment]
I've noticed that this error persists in our android alerts. The button text and title just disappear in dark mode
