### ISSUE TITLE
Rebalance not working

### ISSUE THREAD

**Issue by AboShanab** [MetaMask/metamask-mobile#1149]
As the title, [Rebalance](https://app.rebalance.to/)  doesn't work on MetaMask v0.2.8 (21) @ Android 9.

**Comment by estebanmino** [comment]
Hi @AboShanab, thanks for reporting. Have this worked in previous versions? web3 interactions seem to be working fine and it says `Not optimized or mobile` so I guess it could be related to that. What do you think?

**Comment by AboShanab** [comment]
Hey @estebanmino, I think so, I tried it on another Ethereum dApp browser app and it not working on Mobile so I don't think it's MetaMask related issue. Thanks.
