### ISSUE TITLE
GammaDEX not working

### ISSUE THREAD

**Issue by AboShanab** [MetaMask/metamask-mobile#1150]
As the title, [GammaDEX](https://demo.gammadex.com/#!/wallets/)  doesn't work on MetaMask v0.2.8 (21) @ Android 9.

**Comment by estebanmino** [comment]
Hi @AboShanab could you elaborate on which part is failing, please? I've been trying to find it but I can't. Thanks.

**Comment by AboShanab** [comment]
Hey @estebanmino, sorry for disturbing you. It seems like it was issue on their backend or so, the website is working now on MetaMask so I would like to close this issue. Thanks for your efforts.

**Comment by kleo2012** [comment]
Hi @AboShanab! Can we talk? My telegram @alexmb152
