### ISSUE TITLE
[Bug]: empty personal_sign message on plaintext `message`

### ISSUE THREAD

**Issue by christopherferreira9** [MetaMask/metamask-mobile#11508]
### Describe the bug

When requesting a personal_sign RPC the message is currently empty in the confirmation screen when using plaintext instead of hex. 
This used to be supported and historically, the SDK has been using plaintext directly in the helper `connectAndSign` method. 

### Screenshots/Recordings

https://github.com/user-attachments/assets/c8c7bb50-e3f0-4257-ba91-9f94ad5fa719

### Steps to reproduce

1. Go to https://mmsdk-test-dapp.vercel.app/ on your desktop browser
2. Tap connectAndSign
3. Scan the QR code
4. Approve the connection
5. See error

### Detection stage

On the development branch

### Version

7.31.0

### Build type

None

### Device

iPhone 11

### Operating system

iOS, Android

**Comment by christopherferreira9** [comment]
Can be related to: https://github.com/MetaMask/metamask-mobile/pull/11169

**Comment by bschorchit** [comment]
Hey @christopherferreira9, could the SDK team use the hex format for the `connectAndSign` method? Personal sign should accept hex only formats. We might have unintentionally accepted plain text format in the past.
