### ISSUE TITLE
Updated PoolTogether description & logo

### ISSUE THREAD

**Issue by chuckbergeron** [MetaMask/metamask-mobile#1153]
Hi MetaMask mobile team!

Thanks a ton for featuring PoolTogether in your mobile app, it's really appreciated.

We've gone through a bit of a rebranding and would love to update the icon and description in the dapps section: **"PoolTogether is a prize-linked savings account. By saving money you have a chance to win prizes."** or something closer to that effect.

And either of these logos would be ideal:

![pooltogether-icon--purple-on-white-128@2x](https://user-images.githubusercontent.com/35717/66861883-ae253780-ef44-11e9-9d04-b9397c26dbaf.png)
![pooltogether-icon--white-on-purple-128@2x](https://user-images.githubusercontent.com/35717/66861885-ae253780-ef44-11e9-85e3-5892d7f1ab63.png)

Cheers!

**Comment by brunobar79** [comment]
Just redeployed the homepage and did this change.

**Comment by chuckbergeron** [comment]
Cool, thanks @brunobar79 !
