### ISSUE TITLE
no web3 injected into iframes

### ISSUE THREAD

**Issue by dankins** [MetaMask/metamask-mobile#1154]
This appears to be the same issue that the plugin had way back when:
https://github.com/MetaMask/metamask-extension/issues/1223

I can see web3 in the parent frame but any child iframes do not have `window.web3` available

**Comment by brunobar79** [comment]
Followed up with Nick Reynolds via slack. Here's their use case and why we should support it:

> so there's 2 reasons for our dapp requiring web3 in iframes
> kirby: our dapp connects web3 wallets using a framework known as kirby (https://blog.joincivil.com/kirby-and-the-birth-of-wall-apps-bd6ce396e229) . Kirby works by sending messages from a parent app to a child app using postMessage, and the child iframe needs web3 injected in order to connect to MetaMask.
> embedded components: we're building components for microtipping that newsrooms will embed via iframes in their articles. these embedded components need web3
> for context, it appears that Coinbase Wallet injects web3 into iframes (haven't quite gotten it to work, actually, but the iframe is aware of Coinbase Wallet's web3). And of course, this flow works on desktop with MetaMask extension since that injects web3 into iframes.
> this is all in service of our goal to build tools for publishers that have no experience in this area. using iframes provides a much quicker time to market than directly integrating with their application

**Comment by jbrumwell** [comment]
@brunobar79 I am trying to get our dapp to connect to metamask mobile through an iframe, currently when I try to connect both `window.ethereum` and `window.web3` are undefined.  Was there a regression to the pull request?

**Comment by jcurbelo** [comment]
Same issue here, any updates?

**Comment by Snugface** [comment]
I can confirm having the same issue. I believe I am using a 2021 build of the app that's not been updated for a while

**Comment by Snugface** [comment]
Same issue with a fresh build version 1.0.11 from 2022 of MetaMask(from Google Play) as well.

**Comment by flow3d** [comment]
Seems (intentional)[https://github.com/MetaMask/metamask-mobile/commit/0351a3e81c0a422485da80954ca1b4276700c04d]..? for the last 2 years.
Couldn't find the rationale though

**Comment by Snugface** [comment]
@flow3d Likely due to some bug/feature that was there at the time. Perhaps it's due to be revisited now?

**Comment by jakerockland** [comment]
Any chance of revisiting this? Perhaps with adding an allowlist of known dApp domains that could be iframed? 

This unfortunately currently makes our product Art Blocks, https://artblocks.io, pretty unusable from an end-to-end experience perspective on MetaMask mobile when trying to show the art live-view which is iframed within our app.

cc @asaltste
