### ISSUE TITLE
Cache brew on CircleCI

### ISSUE THREAD

**Issue by brunobar79** [MetaMask/metamask-mobile#1158]
Why? The job `test-e2e-ios`  runs the following commands during `Load dependencies`

brew update
brew install watchman
brew tap wix/brew
brew install --HEAD applesimutils
yarn global add detox-cli

This takes about 6 min 30s and it if we cache it, should take < 1 min, reducing the job time by almost 30%

REF: https://discuss.circleci.com/t/caching-brew/21393/5

**Comment by AlexAtkinson** [comment]
It would be awesome to be able to cache 'brew install'. This is a major drain on my "build credits", considering macOS burns them at a 5x rate (licensing & bloated hardware costs?)

**Comment by daluu** [comment]
So was this closed with no action taken? And @brunobar79, that reference discussion post seems to be gone now? Or it is marked private otherwise unfortunately.

**Comment by AlexAtkinson-Myant** [comment]
Why is this closed? I can't find any documentation on how to implement this?

**Comment by daluu** [comment]
On a related note, I came across this recently regarding the caching: https://blog.artwolf.in/a?ID=1d5ea681-e186-4b14-a874-5efd3192ec11

**Comment by gantunesr** [comment]
Hi @daluu and @AlexAtkinson-Myant, we're not using CircleCI anymore,  thats why I closed the issue

**Comment by AlexAtkinson-Myant** [comment]
Ah. Ty. This issue needs to be ported over to GitHubs space.
