### ISSUE TITLE
Fastlane builds for iOS and Android

### ISSUE THREAD

**Issue by Zidail** [MetaMask/metamask-mobile#1166]
Hey there!

I see that Fastlane has already been added to iOS and I was wondering if this project would be open to leveraging more of it for both Android and iOS.

Here's some, but not all, of the benefits that we stand to gain:

1. Cut out the middle man for the build process. This would mean just calling a command from the cli like `bundle exec fastlane ios release` instead of going through the `yarn command` -> `build.sh` -> `fastlane command`.
2. Clean up the build scripts. There's quite a few things in there that Fastlane already handles, meaning we wouldn't need to maintain it on our side anymore.
3. We update `package.json` and remove quite a few of the pre/release commands from there.
4. Remove the announcement bot. [Fastlane already has an action for that](https://docs.fastlane.tools/actions/slack/).
5. Our deployment code can be unit tested with stuff like [RSpec](https://rspec.info/). We can gain an increase in confidence when updating our build steps. An example would be making sure our process of decoding the base64 Android keystore functions properly.
6. Handles the bothersome iOS Certificates and provisioning so we don't have to with [Fastlane's sigh](https://docs.fastlane.tools/actions/sigh/).
7. When the day comes that this gets put on the Play Store or Apple Store, there's Fastlane actions that takes it all the way to pressing the Go button. [Docs on deployment](https://docs.fastlane.tools/getting-started/ios/appstore-deployment/).
8. Eliminates the "This script/process doesn't work on my machine but works on yours". It standardizes everything.
9. Since Fastlane runs on ruby, we can leverage that language.
10. Linting for everything! We can lint the iOS Podfiles too since that's based on ruby if we ever have any of them.
11. Consolidates quite a huge portion of the build process into one ecosystem/location.
12. Better for error handling.

Now I'm not saying that all of these are critical and since it'd be replacing things that already work they'd be more of a "Nice to Have" instead of a 'Must' in a project.

What do all of you think?

**Comment by brunobar79** [comment]
Hey there!

Thanks for putting this together. Looks great! 
Unfortunately we don't have bandwidth to deal with this now. Our mobile team is pretty small (2 devs / 1 QA )  and our priority right now is to ship v1 ASAP.  

Even if we accept a community PR it will take a lot of time on our end to retest all of our CI flow, from PRs, e2e and deployments (which is critical) and as you said  it's just a nice to have.

I've added the tag `may-revisit-later` so in the future hopefully with a bigger team we can reconsider it.

Thanks again!
