### ISSUE TITLE
[Bug]: Android: Splash screen always showing when opening/closing Token view and other screens

### ISSUE THREAD

**Issue by chrisleewilcox** [MetaMask/metamask-mobile#11697]
### Describe the bug

Every time I tap to open or close Token view I always see splash screen.  I think this leads to performance issues.
I also see the splash screen pop-up in the Send flow.

### Expected behavior

Don't load or show the splash screen every time when opening or closing Token view.

### Screenshots/Recordings

https://github.com/user-attachments/assets/019817c0-b26b-4fcc-98ae-f7fa71e3dc00

### Steps to reproduce

GIVEN I am on wallet view
WHEN I tap on a token
THEN Token view is displayed
AND splash screen is not displayed (FAILED: splash screen is displayed)

### Detection stage

During release testing

### Version

7.33.0

### Build type

None

### Device

Samsung Galaxy 42A Android 13

### Operating system

Android

**Comment by NicolasMassart** [comment]
I confirm this issue also happens on Android emulator, will help for debugging.

**Comment by alfeng6** [comment]
@NicolasMassart can I assign you to this ticket then?

**Comment by NicolasMassart** [comment]
I'm pretty sure it's not specific to the asset screens but something to do with the app navigation
