### ISSUE TITLE
Remove decommissioned IPFS gateway from wallet state

### ISSUE THREAD

**Issue by Gudahtt** [MetaMask/metamask-mobile#11692]
### What is this about?

The IPFS gateway cloudflare-ipfs.com was decommissioned on August 14 2024. Prior to #11401, this IPFS gateway was the default for MetaMask mobile users. That was addressed in #11401, but existing users might still have this decommissioned IPFS gateway configured.

We should write a migration to replace the decommissioned gateway with the new default gateway.

The new default gateway shall be 'dweb.link'.

### Technical Details

We'll need a state migration here. It should specifically target users who have the decommissioned IPFS gateway selected.

### Acceptance Criteria

- The decommissioned IPFS gateway is no longer active for existing users
- The decommissioned IPFS gateway has been replaced by our new default IPFS gateway

### Stakeholder review needed before the work gets merged

- [X] Engineering (needed in most cases)
- [ ] Design
- [ ] Product
- [ ] QA (automation tests are required to pass before merging PRs but not all changes are covered by automation tests - please review if QA is needed beyond automation tests)
- [ ] Security
- [ ] Legal
- [ ] Marketing
- [ ] Management (please specify)
- [ ] Other (please specify)

### References

- Related issue: https://github.com/MetaMask/mobile-planning/issues/1961
- Context: https://github.com/MetaMask/metamask-mobile/pull/11401#discussion_r1775795856

**Comment by Gudahtt** [comment]
I am not sure. For the purposes of this ticket, all that is required is for current users with the Cloudflare IPFS gateway selected to now have `dweb.link` selected.

**Comment by legobeat** [comment]
Reversing the sorting seems reasonable to me (making the new default be the first one)?

**Comment by NicolasMassart** [comment]
I'm not sure if the key used for sorting is used for more than just sorting. So I favoured adding a new key instead of replacing the existing first one.
Ideally also we should have a "default" attribute in this list and reorganise sorting to simply be sorted by how it's in the array. I know array order should not be taken for granted, but most of the time it' works very fine, especially if the impact is low like it's here, just impacting the display order.

**Comment by legobeat** [comment]
> I'm not sure if the key used for sorting is used for more than just sorting. So I favoured adding a new key instead of replacing the existing first one.

Right , I meant that the sorting in UI could be reversed without reassigning keys
