### ISSUE TITLE
Adding down RPC network endpoint crashes app

### ISSUE THREAD

**Issue by ibrahimtaveras00** [MetaMask/metamask-mobile#1171]
Seen here = http://recordit.co/kVCXUHL0KP

![Screen Shot 2019-10-28 at 7 47 52 PM](https://user-images.githubusercontent.com/41752922/67728984-bb6f0700-f9c5-11e9-814b-edd60e3c4ce4.png)

This is on latest develop

Steps to reproduce:
- if you have an account that has an ETH balance on any network this will help... go to that network
- take note of your ETH balance
- go to settings > networks
- add RPC URL http://127.0.0.1:7545
- notice that your ETH balance doesn't update for some reason
- now go to settings > networks and try to remove Ganache

**Comment by estebanmino** [comment]
the bug is when the endpoint is down, for alive endpoints this doesn't happen

**Comment by ibrahimtaveras00** [comment]
This issue has been resolved 👍
