### ISSUE TITLE
UI: Pending tx obstructs view for new tx

### ISSUE THREAD

**Issue by pi0neerpat** [MetaMask/metamask-mobile#1174]
## Problem
![Screenshot_20191030-183245](https://user-images.githubusercontent.com/35622595/67904640-61954b00-fb45-11e9-8cc0-d28089377f29.png)

The "transaction pending" bar prevents users from performing additional transactions. It also prevents navigation buttons.

E.g. submit an approve call, immediately followed by a contract interaction call

This is also true for dapps which have buttons/features which may be blocked by the status bar.

May be related to #177 

## Solution

Move the transaction status bar elsewhere?

**Comment by brunobar79** [comment]
Not ideal but for now try swiping down to dismiss the notification

**Comment by ibrahimtaveras00** [comment]
We took care of this in our latest design updates.  @pi0neerpat check out our latest version, 0.2.18 and let us know what you think!
