### ISSUE TITLE
App doesn't show in "Recent apps" menu

### ISSUE THREAD

**Issue by pi0neerpat** [MetaMask/metamask-mobile#1175]
## Problem
![Screenshot_20191030-190051](https://user-images.githubusercontent.com/35622595/67905472-d2d5fd80-fb47-11e9-87eb-b5ed35a6a762.png)
When switching between apps, Metamask doesn't appear in the recent apps menu bar (at bottom). I've never had this occur for other apps. Maybe this is intentional?

Android v9

**Comment by brunobar79** [comment]
I can't repro on Android 10. 

![](https://files.slack.com/files-pri/T02P98BKE-FQG67ETV5/screenshot_20191112-083454.png)

**Comment by brunobar79** [comment]
I've checked the manifest and:
- we have the correct `android:label` attribute
- we don't have `android:excludeFromRecents`

I think it's fair to assume it's an OS thing (?)  @ibrahimtaveras00  Please add your findings here

**Comment by ibrahimtaveras00** [comment]
Agreed this is an OS thing.  I personally have a Samsung, and you have to launch the app a few times in order for it to appear.  It's not only MM app, all my apps do this for Samsung.  Nonetheless couldn't reproduce on a Pixel.
