### ISSUE TITLE
[Bug]: Ramp Network Switcher Broken after network controller v21 bump

### ISSUE THREAD

**Issue by cryptodev-2s** [MetaMask/metamask-mobile#11783]
### Describe the bug

The Ramp Network Switcher is broken after the network controller bump to v21.

### Steps to reproduce

1. As a user navigating to Buy or Sell while being on an unsupported network for Ramps I want to see the Ramp Network Switcher

        -  Depicts this view
![image](https://github.com/user-attachments/assets/bea2fdf1-8812-47c8-bc04-ace9a2cb0bf7)
        - This are the supported networks, offered to the clients from this API https://on-ramp-content.api.cx.metamask.io/regions/networks

2. Using the Ramp Network Switcher I want to add a supported network using the Networks Details coming from the Ramp api

        - The network details are grabbed from the app “popular networks” list if available
        - If not, they are grabbed from our API: https://on-ramp-content.api.cx.metamask.io/regions/network-details

3. After adding the custom network, I want to switch to that network and navigate to the Ramp flow

We can see in the video that 1 is working, but 2 and 3 are not working anymore:

https://github.com/user-attachments/assets/c7820adf-de3d-4d66-b14c-ae8354af483f

Note: The network adding + switching steps are based on existing components and not made by the ramps team

### Detection stage

On the development branch

### Version

7.32.0

### Build type

None

### Device

Iphone 15 PRO

### Operating system

iOS

**Comment by wachunei** [comment]
Here's an updated video of the bug, the Network Switcher does not work anymore:

https://github.com/user-attachments/assets/7b2296ad-b2eb-479c-8146-e248c18b774c
