### ISSUE TITLE
Geolocation permission

### ISSUE THREAD

**Issue by benjaminaaron** [MetaMask/metamask-mobile#1180]
My DApp needs to be able to ask the user for his location📍

However, the `navigator.geolocation.getCurrentPosition()` call results in the error `"application does not have sufficient geolocation permissions"`. I tried to give this permission to the MetaMask mobile app on Android. But it seems if the App didn't ask for it upon install, I can't just give it that permission afterwards in the Android system settings? 🤔 
Do you have a suggestion what I could try? If possible I would like to avoid having to build your app myself just to add this [here](https://github.com/MetaMask/metamask-mobile/blob/749fee6742196edd0ad48851949beffb04d260c9/android/app/src/main/AndroidManifest.xml#L9) in the `AndroidManifest.xml`:

```html
<uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
```

Edit: just tried it on iOS. There I was asked from the system to give permission. So unlike on Android iOS apparently makes it possible to request app-level permissions later on.

**Comment by brunobar79** [comment]
Replied to the PR and opened #1186 to follow up
