### ISSUE TITLE
[Bug] Unable to find and reconnect to Ledger Stax device after device and phone being locked

### ISSUE THREAD

**Issue by vivek-consensys** [MetaMask/metamask-mobile#11818]
Bitrise build:- https://app.bitrise.io/app/be69d4368ee7e86d/installable-artifacts/44bbaa8d3ed27c38/public-install-page/027da7f6e83955c041d33c8fe5f36577

Device:- Samsung S21 [Android 14]

1. Install MM from Bitrise build
2. Recover from SRP
3. Connect to Ledger Stax device
4. Add accounts from Ledger Live, Legacy and BIP44 hd paths
5. Close app and let the phone lock
6. Allow the Ledger Stax device to lock
7. Wait for a few mins
8. Try to reconnect to Ledger device to forget devices

Expected: User is able to connect to Ledger Stax to delete wallet or add additional accounts
Actual: User unable to connect to Ledger Stax

[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMXhPQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3acede2509bb38c4a27183b86d89f7c78fc7d59f/Screen_Recording_20241016_142752_MetaMask.mp4)

**Comment by dawnseeker8** [comment]
Unable to replicate, please verify again whether it still exist in latest build.

**Comment by vivek-consensys** [comment]
Cannot reproduce using 7.34 RC3. Closing issue.
