### ISSUE TITLE
[Bug]: App crashes on launch after upgrading/install to build 1459 

### ISSUE THREAD

**Issue by chrisleewilcox** [MetaMask/metamask-mobile#11828]
### Describe the bug

App keeps crashing on launch after upgrading current prod to 1459 on iOS...

### Expected behavior

App should not crash after upgrading.
App should not crash after launch/open.

### Screenshots/Recordings

iOS
https://github.com/user-attachments/assets/ccb5e7dd-ec2b-4e36-9160-38788ca73701

Android

### Steps to reproduce

GIVEN I am on 7.32.0
WHEN I upgrade
AND I launch app
THEN app opens as expected (FAIL: app keeps crashing on launch)

### Detection stage

During release testing

### Version

7.33.0

### Build type

None

### Device

iPhone 12 Max iOS 18

### Operating system

iOS

**Comment by gauthierpetetin** [comment]
The root cause of this issue has been reverted
