### ISSUE TITLE
navigatior.geolocation.getCurrentPosition not working on Android

### ISSUE THREAD

**Issue by brunobar79** [MetaMask/metamask-mobile#1186]
Instead of adding the permission at the manifest level, we should ask for it at runtime using the PermissionsAndroid API 

Here's a gist that handles that in a decent way: https://gist.github.com/raldred/b08cf60712eb87d81f05437444dff4ae

We might need to override navigator.geolocation.getCurrentLocation so we can catch the exception when it's not enabled:
`PositionError {code: 2, message: "application does not have sufficient geolocation permissions."}`

and then send a message to native to request it and resolve the promise on approval.

An easy way to test this is to go to mylocation.org => Browser Geolocation

**Comment by benjaminaaron** [comment]
Thanks @brunobar79, sounds indeed like a more sensible approach than adding it to the manifest.

Do you think I can trigger this ask-at-runtime from my DApp already now or are your proposed changes in the Android app necessary first?

**Comment by brunobar79** [comment]
@benjaminaaron  Unfortunately no, we need to wire up things first between within the webview so we can prompt for the permission on the app side, then return the location to the webview context.

I suggest you to watch this issue so you are aware of the progress.

**Comment by omnat** [comment]
@rickycodes to check if this is working with the webview updates we've made recently. 
cc @andrepimenta

**Comment by gantunesr** [comment]
Both platforms should have the geolocation disabled

**Comment by vorcigernix** [comment]
Guys, this renders metamask unusable for any location based activity. Can't believe you simply closed it, stating it is okay.

**Comment by guidoroxs** [comment]
Upvote for re-opening it. I have an app that needs to use location based activity using MMM, and at the moment the user is unable to use the browser portion for this.

**Comment by Madeindreams** [comment]
I vote to reopen this issue as well!

**Comment by sbeben** [comment]
subscribe on this one
