### ISSUE TITLE
[Bug]:  For some networks added from the MetaMask Popular Networks list, users encounter a red warning stating, 'According to our records, the network name may not correctly match this chain ID,' same warning in shown for Linea.

### ISSUE THREAD

**Issue by sleepytanya** [MetaMask/metamask-mobile#11893]
### Describe the bug

When selecting networks from the MetaMask Popular Networks list, users may encounter a red warning stating, 'According to our records, the network name may not correctly match this chain ID,' accompanied by a suggested network name on the network details screen. 
Warning is displayed for Linea, BNB, Optimism, Avalanche, zkSync Era.

### Expected behavior

-

### Screenshots/Recordings

<img width="1435" alt="Screenshot 2024-10-19 at 22 01 00" src="https://github.com/user-attachments/assets/de9abd1f-ef88-4fe0-b66a-6bc3c35a6642">

<img width="919" alt="Screenshot 2024-10-19 at 22 01 28" src="https://github.com/user-attachments/assets/b1bfccd8-0a7e-4c7b-9528-b2d4130580b1">

### Steps to reproduce

1. Go to networks list
2. Click 'Edit' next to Linea or any other network mentioned in the description

### Detection stage

During release testing

### Version

7.34.0(1462)

### Build type

None

### Device

iPhone 15

### Operating system

iOS

**Comment by NicolasMassart** [comment]
Close this as the fix was [cherry picked in 7.34.0](https://github.com/MetaMask/metamask-mobile/pull/11974)
