### ISSUE TITLE
[Bug]: All types of Signatures (including Malicious) fail with the Error: undefined is not an object (evaluating '(yield R(this,,"f"). call (this, {name:'Await Approval', parentContext:v},(function(e) {var s;return R(M,n,"m",D).call(M,C,t, {traceContext:e,action|d:null==p||null==(s=p.id)?void 0:s.toString))}))).resultCallbacks)

### ISSUE THREAD

**Issue by sleepytanya** [MetaMask/metamask-mobile#11896]
### Describe the bug

All types of Signatures (including Malicious) fail with the 
`Error: undefined is not an object (evaluating '(yield R(this,,"f"). call (this, {name:'Await Approval', parentContext:v},(function(e) {var s;return R(M,n,"m",D).call(M,C,t, {traceContext:e,action|d:null==p||null==(s=p.id)?void 0:s.toString))}))).resultCallbacks)`

### Expected behavior

-

### Screenshots/Recordings

iOS:

<img width="1448" alt="Screenshot 2024-10-20 at 01 56 41" src="https://github.com/user-attachments/assets/cfd97095-8c57-4064-9332-28376518822e">

Android:

<img width="945" alt="Screenshot 2024-10-20 at 01 54 45" src="https://github.com/user-attachments/assets/87509e37-040d-43f9-94ea-b42788d38cec">

### Steps to reproduce

1. Go to[ test dapp](https://metamask.github.io/test-dapp/)
2. Trigger any signature

### Detection stage

During release testing

### Version

7.34.0 (1462)

### Build type

None

### Device

iPhone 15, Samsung S24+

### Operating system

iOS, Android

**Comment by bschorchit** [comment]
Closing a this has been fixed by this cherry pick: https://github.com/MetaMask/metamask-mobile/commit/cccb81327670900dab9f9569e9fcac11fad491cf#diff-5ee34bab878e5bc84ca66a05fcdb62a6af9ad5d90a032e204c66ea29de3b0a19
