### ISSUE TITLE
[Bug]: Ethereum Mainnet name is displayed as Mainnet on Android

### ISSUE THREAD

**Issue by sleepytanya** [MetaMask/metamask-mobile#11895]
### Describe the bug

Ethereum Mainnet name is displayed as Mainnet on Android.

UPDATE: Duplicate mainnet's are also show in Settings > Security & Privacy: Show Incoming Transactions
https://consensys.slack.com/archives/C07RSA2E6N7/p1729795476305579

### Expected behavior

-

### Screenshots/Recordings

Android:

![androidMainnet](https://github.com/user-attachments/assets/ba335d18-bf5a-48d6-8f7a-5b5528e09051)

Correct chain name on iOS:

![iosEthereum4](https://github.com/user-attachments/assets/e7fb2cef-723d-4369-8f55-f20424e99c3a)

### Steps to reproduce

1. Open networks menu

### Detection stage

During release testing

### Version

7.34.0

### Build type

None

### Device

Samsung S24+

### Operating system

Android

**Comment by salimtb** [comment]
cherry-pick PR available [here](https://github.com/MetaMask/metamask-mobile/pull/12082)
