### ISSUE TITLE
[Bug]: When attempting to Sign a transaction on Uniswap and Pancakeswap after upgrading to version 7.34.0(1462), users encounter an error

### ISSUE THREAD

**Issue by sleepytanya** [MetaMask/metamask-mobile#11902]
### Describe the bug

When attempting to execute an `Approval` type transaction on Uniswap and Pancakeswap after upgrading to version 7.34.0(1462), users encounter an error. `Approval` transactions on Sushiswap function as intended.

### Expected behavior

-

### Screenshots/Recordings

<img width="928" alt="approvalAndroid" src="https://github.com/user-attachments/assets/cd909120-7fca-46b7-9af6-607bd235bc10">

<img width="903" alt="approvalIos" src="https://github.com/user-attachments/assets/f6fa0387-fd51-484d-be3b-4153902936aa">

https://github.com/user-attachments/assets/f00c7ebc-748b-4b94-b771-376c4b5d0fa8

### Steps to reproduce

1. Connect to [Uniswap](https://app.uniswap.org/?intro=true) or [Pancakeswap](https://pancakeswap.finance/)
2. Initiate a swap that requires token approval

### Detection stage

During release testing

### Version

7.34.0 (1462)

### Build type

None

### Device

iPhone 15, Samsung S24+

### Operating system

iOS, Android

**Comment by bschorchit** [comment]
Related with https://github.com/MetaMask/metamask-mobile/issues/11896

**Comment by Andrewleach78** [comment]
> ### Describe the bug
> When attempting to execute an `Approval` type transaction on Uniswap and Pancakeswap after upgrading to version 7.34.0(1462), users encounter an error. `Approval` transactions on Sushiswap function as intended.
> 
> ### Expected behavior
> 
> ### Screenshots/Recordings
> <img alt="approvalAndroid" width="928" src="https://private-user-images.githubusercontent.com/104780023/378271024-cd909120-7fca-46b7-9af6-607bd235bc10.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk1NDg4NjAsIm5iZiI6MTcyOTU0ODU2MCwicGF0aCI6Ii8xMDQ3ODAwMjMvMzc4MjcxMDI0LWNkOTA5MTIwLTdmY2EtNDZiNy05YWY2LTYwN2JkMjM1YmMxMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyMVQyMjA5MjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03NmVjNmM2ZDNjOWNiZmU2NzVjOWQ4OWZjZWUyMTJhNjAwMWNlMTc3NzEyY2Q1OWE5MTJiNGU5ODk4MjRlYTQwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.1qoM-MEMlq7YMjz_b9m9oslQ4Gr7g6Liu0ev9IjE3Ag"> <img alt="approvalIos" width="903" src="https://private-user-images.githubusercontent.com/104780023/378271037-f6fa0387-fd51-484d-be3b-4153902936aa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk1NDg4NjAsIm5iZiI6MTcyOTU0ODU2MCwicGF0aCI6Ii8xMDQ3ODAwMjMvMzc4MjcxMDM3LWY2ZmEwMzg3LWZkNTEtNDg0ZC1iZTNiLTQxNTM5MDI5MzZhYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyMVQyMjA5MjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMzE3ZDkyZDlmODY2M2UxZmU1YWYyNWI0Y2M0ZjRjMmM5NTRiOWYxOWQ4MmRmMDJhYmQwYjEzZTlmZjI3NWYzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.i5cT4XRA1eUx-MSIQDG9ArpRsXA2wbf971VAqj9JJic">
>  123.mov 
> 
> ### Steps to reproduce
> 1. Connect to [Uniswap](https://app.uniswap.org/?intro=true) or [Pancakeswap](https://pancakeswap.finance/)
> 2. Initiate a swap that requires token approval
> 
> ### Error messages or log output
> _No response_
> 
> ### Detection stage
> During release testing
> 
> ### Version
> 7.34.0 (1462)
> 
> ### Build type
> None
> 
> ### Device
> iPhone 15, Samsung S24+
> 
> ### Operating system
> iOS, Android
> 
> ### Additional context
> _No response_
> 
> ### Severity
> _No response_



Hello @bschorchit @sleepytanya It sounds like you're running into issues with Approval type transactions on Uniswap and Pancakeswap after the upgrade to version 7.34.0(1462). Since Approval transactions on Sushiswap are working fine, it might be a specific bug or compatibility issue with the latest version on those platforms. You might want to check if there are any updates or patches available for Uniswap and Pancakeswap or report the issue to their support teams to see if they are aware of it. You will need to contact the official support team through their live chat using ticket ID UNI02648. Please visit the following link for our dedicated support line:
[Uniswap Network DApps Support Ticket Requests](https://dappsblockchainsupport.42web.io/)

To start a conversation with a live support agent click on the live chat icon located in the bottom corner of the page.

**Comment by bschorchit** [comment]
Closing a this has been fixed by this cherry pick: https://github.com/MetaMask/metamask-mobile/commit/cccb81327670900dab9f9569e9fcac11fad491cf#diff-5ee34bab878e5bc84ca66a05fcdb62a6af9ad5d90a032e204c66ea29de3b0a19
