### ISSUE TITLE
[Bug]: Fiat value displayed only for the native token

### ISSUE THREAD

**Issue by sleepytanya** [MetaMask/metamask-mobile#11901]
### Describe the bug

Fiat value displayed only for the native token, for all other tokens `Not Available` message is shown.

### Expected behavior

Fiat values displayed for all tokens on all networks

### Screenshots/Recordings

<img width="1117" alt="Screenshot 2024-10-20 at 23 53 29" src="https://github.com/user-attachments/assets/2dda27e7-678c-401a-9e19-f4e5dcabffda">

### Steps to reproduce

1. Start Send or Swap transaction
2. Select non-native tokens

### Detection stage

In production (default)

### Version

7.34.0 (1462)

### Build type

None

### Device

iPhone 15, Samsung S24+

### Operating system

iOS, Android

**Comment by bschorchit** [comment]
Closing as completed with https://github.com/MetaMask/metamask-mobile/pull/11947
