### ISSUE TITLE
[Bug]: Deeplinks not displaying error for networks not added to wallet and displaying Confirm screen for wrong network

### ISSUE THREAD

**Issue by chrisleewilcox** [MetaMask/metamask-mobile#11966]
### Describe the bug

Tapping on a send deeplink for a network that has not been added to the wallet will still create the Confirm Send screen for the selected network which can potentially send incorrect tokens.  Tapping on a deeplink for a network that hasn't been added to the wallet then the mobile app should display an alert/error that indicates network not recognized and not do anything else (should not create the Confirm screen).

BNB Send deeplink: https://metamask.app.link/send/0x2990079bcdEe240329a520d2444386FC119da21a@56?value=3e18

### Expected behavior

Tapping on a deeplink for a network that hasn't been added to the wallet then the mobile app should display an alert/error that indicates network not recognized and not do anything else (should not create the Confirm screen).

### Screenshots/Recordings

https://github.com/user-attachments/assets/c1dc14c4-5348-456d-931b-7ec43cf347d3

7.33.0
![image](https://github.com/user-attachments/assets/194563db-4636-442c-a68a-cda6de51099c)
### Steps to reproduce

GIVEN I don't have BNB network added to my wallet
WHEN I tap a send deeplink for BNB network
THEN mobile app is sent to the foreground of device
AND device alert warning indicating network not recognized (FAILED: no alert is displayed)
AND no other action is taken (FAILED: Confirm screen for sending assets is displayed)

### Detection stage

During release testing

### Version

7.34.0

### Build type

None

### Device

Any

### Operating system

iOS, Android

**Comment by christopherferreira9** [comment]
Fixed by https://github.com/MetaMask/metamask-mobile/pull/12048
