### ISSUE TITLE
[Bug]: Adding block explorer shows Add Custom Network modal

### ISSUE THREAD

**Issue by chrisleewilcox** [MetaMask/metamask-mobile#11992]
### Describe the bug

After trying to add a block explorer the Add Custom Network modal pops-up.  I am adding block explorer by using device keypad enter button because the Add Block Explorer URL button is not reachable, keypad in the way.  May be because of the keypad that is causing this.

Have not been able to successfully add a block explorer.

### Expected behavior

Should not see the Add Custom Network Modal when trying to add block explorer.

### Screenshots/Recordings

https://drive.google.com/file/d/1u20JOJRvD3tGUD40wMkLZDFkskmL36Rk/view

### Steps to reproduce

This is my best guest of how steps should work.  Please consult PM.

GIVEN I am adding a block explorer to a network
WHEN I input 'https://eth.blockscout.com/' (FAILED: input field is behind keypad) 
AND I tap 'Add Block Explorer URL' button (FAILED: not able to tap button, not visible)
BUT I can also tap `<enter>` on keypad
THEN Edit Network screen is displayed
WHEN I tap 'Save' button
THEN Select Network modal is displayed
AND added block explorer is saved for the proper network

### Detection stage

In production (default)

### Version

7.34.0

### Build type

None

### Device

Any

### Operating system

iOS, Android

**Comment by salimtb** [comment]
cherry-pick ready for review [here](https://github.com/MetaMask/metamask-mobile/pull/12052)
