### ISSUE TITLE
[Bug]: Browser: Not able to connect wallet to marketplaces opensea, rarible, magiceden, others???

### ISSUE THREAD

**Issue by chrisleewilcox** [MetaMask/metamask-mobile#12014]
### Describe the bug

Not able to connect my wallet to some marketplaces such as opensea.  Getting an error attempting to connect wallet to marketplaces using in-app browser.  Works on current prod.  Works for this release on portfolio, test dapp, uniswap, pancakeswap.  Just not working on the following marketplaces...

- opensea.io
- https://aerodrome.finance/
- rarible.com
- magiceden.io

### Expected behavior

Should be able to connect wallet to marketplaces such as opensea and rarible using in-app browser.

### Screenshots/Recordings

https://consensys.slack.com/files/U031PATKAVD/F07TPGG1K6D/rpreplay_final1729758697.mp4

### Steps to reproduce

GIVEN I am on browser view
WHEN I navigate to opensea.io
AND I tap to connect wallet
THEN I am able to connect my wallet (FAILED: not able to connect wallet)
AND I am able to sign if prompted

### Detection stage

During release testing

### Version

7.34.0

### Build type

None

### Device

Any

### Operating system

iOS, Android

**Comment by joaoloureirop** [comment]
@chrisleewilcox what were your actions before attempting to connect to these listed dapps?

from a warm start, there seems to be no issues connecting to them.

Recordings below

Opensea redirecting to play store incident. Present on both v7.34.0 and current production v7.33.0

v7.33.0
https://github.com/user-attachments/assets/207368a1-6e26-4e43-a959-680f99dcee45


v7.34.0
https://github.com/user-attachments/assets/ed82a80f-9c83-4744-8c22-0f251a7c7004


Connecting to magiceden, rarible and aerodrome

https://github.com/user-attachments/assets/4ef2e78e-49d6-489c-97ab-ec68d52c6566

**Comment by joaoloureirop** [comment]
Bug is already fixed on release branch `release/7.34.0`.

Fixed on [this cherry-pick](https://github.com/MetaMask/metamask-mobile/commit/cccb81327670900dab9f9569e9fcac11fad491cf) on [this code change](https://github.com/MetaMask/metamask-mobile/commit/cccb81327670900dab9f9569e9fcac11fad491cf#diff-5ee34bab878e5bc84ca66a05fcdb62a6af9ad5d90a032e204c66ea29de3b0a19R157)

Bug was introduced on 0fc0d42a71fd294785e6061575275c5f6317e0f1 which was the HEAD reference when the [last 7.34.0 RC was cut](https://app.bitrise.io/build/17ba681c-f7d4-4a60-9dde-7af0729a1b22?tab=log)

**Comment by chrisleewilcox** [comment]
This issue has been resolved on 7.34.0 build 1468.
