### ISSUE TITLE
[Bug]: Alert no longer showing after tapping send deeplink when switching to a network that hasn't been added to wallet, Confirm send screen displayed for wrong network

### ISSUE THREAD

**Issue by chrisleewilcox** [MetaMask/metamask-mobile#12035]
### Describe the bug

Related: #11984 

Alert no longer showing after tapping send deeplink when switching to a network that hasn't been added to wallet.  When this happens the Confirm send screen is displayed for the wrong network which can lead to a potential FLI.   

### Expected behavior

- Alert should be displayed indicating network needs to be added to wallet
- Confirm screen should not be created/displayed after tapping send deeplink for another network
- App should continue to switch to proper network if network has already been added

### Screenshots/Recordings

See related issue.

### Steps to reproduce

See related issue.

GIVEN I have not added Polygon network to wallet
WHEN I tap on a Polygon send asset deeplink
THEN mobile app is launched/open
AND alert is displayed indicating can't find network (FAILED: alert is not displayed)
AND app takes no further action (FAILED: Confirm send modal is displayed)

### Detection stage

During release testing

### Version

7.34.0

### Build type

None

### Device

Any

### Operating system

iOS, Android

**Comment by salimtb** [comment]
this bug has been fixed with this [PR](https://github.com/MetaMask/metamask-mobile/pull/12048), i created the cherry-pick PR [here](https://github.com/MetaMask/metamask-mobile/pull/12072)
