### ISSUE TITLE
[Bug]: Saved contacts erased after restarting the app

### ISSUE THREAD

**Issue by anaamolnar** [MetaMask/metamask-mobile#12044]
### Describe the bug

When I save a contact and restart the app, the contacts are deleted

### Steps to reproduce

1. Settings->Contacts
2. Add contact
3. Save
4. Exit the app
5. Reopen it
6. Navigate to Contacts list
7. The contact will not be there

### Detection stage

In production (default)

### Version

7.33.0

### Build type

None

### Device

iPhone

### Operating system

iOS

**Comment by plasmacorral** [comment]
With this failure it increases the risk of a user falling victim to address poisoning.

**Comment by hesterbruikman** [comment]
Adding context to the severity label: was able to reproduce that upgrading to 7.32.0 cleared Contacts. Meaning this does not only affect users that Add a contact on a given version, it rather affects all users upgrading to 7.32.0
