### ISSUE TITLE
[Bug]: ITMS-90899: Macs with Apple silicon support issue

### ISSUE THREAD

**Issue by sethkfman** [MetaMask/metamask-mobile#12113]
### Describe the bug

The app isn‘t compatible with the provided minimum macOS version of 11.0. It can run on macOS 12.0 or later. Please specify an LSMinimumSystemVersion value of 12.0 or later in a new build, or select a compatible version in App Store Connect. For details, visit: https://developer.apple.com/help/app-store-connect/manage-your-apps-availability/manage-availability-of-iphone-and-ipad-apps-on-macs-with-apple-silicon.

### Steps to reproduce

Submit app to apple and see if you receive email alert with  ITMS-90899 error

### Detection stage

In production (default)

### Version

7.34.0

### Build type

Other (please specify exactly where you obtained this build in "Additional Context" section)

### Device

Mac

### Operating system

iOS

**Comment by NicolasMassart** [comment]
To be fixed on next release
