### ISSUE TITLE
TX Pending Indefinitely For ENS

### ISSUE THREAD

**Issue by scottcbusiness** [MetaMask/metamask-mobile#1213]
I am able to edit certain records like adding a description, but when trying to add cryptocurrency addresses like LTC or BTC it says TX Pending and no confirmation window appears so it stays pending indefinitely making me unable to make changes. I've tested it as well on every desktop browser with extension with no luck.

**Comment by brunobar79** [comment]
I believe this is related to #1209

**Comment by scottcbusiness** [comment]
I'm not having the exact same issue. I can add URL and description records. When adding coins records, it doesn't work. Either I get no popup, or I do and approve and it says TX Pending infdefinitely on any browser mobile or PC.

Scott Cunningham
Social Media Marketer

Blockchain Content Creator & Entrepreneur
m:
[519-880-6174](tel:5198806174)

e:
scottcbusiness@protonmail.com

All Social Links & More: http://www.scottcbusiness.com
Schedule A Meeting With Me: https://calendly.com/scottcbusiness
[image]

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by brunobar79** [comment]
Oh, I see...  If it's happening on desktop too then it's very likely to be a problem in the ENS manager itself.  I suggest you to report it here: https://github.com/ensdomains/ens-app
