### ISSUE TITLE
[Bug]: When using the custom RPC https://eth.llamarpc.com, transaction gas fees appear to be significantly higher in the mobile app compared to the Extension

### ISSUE THREAD

**Issue by sleepytanya** [MetaMask/metamask-mobile#12156]
### Describe the bug

When using the custom RPC https://eth.llamarpc.com/, transaction gas fees appear to be significantly higher in the mobile app ($303.95) compared to the Extension, where llama RPC displays gas prices within a normal range.

### Expected behavior

-

### Screenshots/Recordings

https://github.com/user-attachments/assets/2569deb6-8e03-4705-b8bd-d4a4017c240e

https://github.com/user-attachments/assets/83ae0c99-f174-460e-a808-f191a784c8e0

### Steps to reproduce

1. Add https://eth.llamarpc.com
2. Start a transaction

### Detection stage

During release testing

### Version

7.34.0 (1473)

### Build type

None

### Device

iPhone 15, Samsung S24+

### Operating system

iOS, Android

**Comment by OGPoyraz** [comment]
@sleepytanya transaction controller is now updated in the mobile in this PR
https://github.com/MetaMask/metamask-mobile/pull/12159

Would you mind check this one more time on `main` branch?
