### ISSUE TITLE
support EIP1102 `eth_requestAccounts` 

### ISSUE THREAD

**Issue by rstormsf** [MetaMask/metamask-mobile#1216]
currently, it doesn't work.

`ethereum.send('eth_requestAccounts', [])`

`ethereum.enable()` is deprecated

https://github.com/ethereum/EIPs/blob/master/EIPS/eip-1102.md

![image](https://user-images.githubusercontent.com/9360827/69133139-42198000-0a6a-11ea-8a79-2d35ef8ff366.png)

**Comment by brunobar79** [comment]
`eth_requestAccounts` is supported and I'm not able to reproduce with the latest version of the app v0.2.11 neither on Android or iOS.

Here's the console of both browsers (left android / right iOS):

![Screen Shot 2019-11-19 at 2 12 12 PM](https://user-images.githubusercontent.com/1247834/69178031-c275ca80-0ad6-11ea-97a3-8c7cf7e9b2a9.png)

Is there any website where I can try to repro?
