### ISSUE TITLE
Better asset onboarding options

### ISSUE THREAD

**Issue by bdresser** [MetaMask/metamask-mobile#1217]
As part of V1, we should make it easier for new users to get crypto. 

This feature will be defined as part of design issue: https://github.com/MetaMask/Design/issues/122

**Comment by bdresser** [comment]
Relates to https://github.com/MetaMask/metamask-mobile/issues/767

**Comment by ibrahimtaveras00** [comment]
Implemented in https://github.com/MetaMask/metamask-mobile/pull/1666
