### ISSUE TITLE
Establish pattern for splitting Engine.ts file

### ISSUE THREAD

**Issue by Cal-L** [MetaMask/metamask-mobile#12184]
### What is this about?

The `Engine.ts` file is a large ~2500 LOC file that holds the logic for controller initialization and is used in many places in the app. The goal here is to establish a pattern for splitting out the file so that it is:
- Easier to manage
- Better testability
- Reduce non-relevant codeowner reviews (saves time on PRs)
- More scalable solution

### Technical Details

- Since controllers tend to be dependent on one another, the imports from abstracted files can be functions that take  dependent controllers as args to ensure initialization order is respected. For example, if `TokenListController` is dependent on `NetworkController`, the abstracted TokenListController file could look like `initializeTokenListController(networkController: NetworkController)`

### Acceptance Criteria

- App behavior should remain the same
- Abstract at least one area as POV that can be applied to other pieces later on

### Stakeholder review needed before the work gets merged

- [ ] Engineering (needed in most cases)
- [ ] Design
- [ ] Product
- [ ] QA (automation tests are required to pass before merging PRs but not all changes are covered by automation tests - please review if QA is needed beyond automation tests)
- [ ] Security
- [ ] Legal
- [ ] Marketing
- [ ] Management (please specify)
- [ ] Other (please specify)

### References

- Slack thread - https://consensys.slack.com/archives/C02U025CVU4/p1730814155345939

**Comment by gauthierpetetin** [comment]
[Slack thread](https://consensys.slack.com/archives/CTQAGKY5V/p1733391886721619)
