### ISSUE TITLE
Request to check log from device?

### ISSUE THREAD

**Issue by birdkingz** [MetaMask/metamask-mobile#1226]
Is there any way to check console log from phone itself?
(Without pulling the whole repo to build the app locally)

**Comment by brunobar79** [comment]
You can debug the browser on Android & iOS without having to build the app yourself.
Just follow this instructions:

Yes! Android: https://developers.google.com/web/tools/chrome-devtools/remote-debugging/webviews

iOS: https://medium.com/@mattcroak718/debugging-your-iphone-mobile-web-app-using-safari-development-tools-71240657c487

**Comment by EvilJordan** [comment]
I'm not sure if this is still relevant, or if it is, I'm doing something majorly wrong. I am iOS and can successfully debug sites in Safari, but anything in a browser view within an app never shows up in my Develop menu. Anyone know why?

**Comment by pacxiu** [comment]
@EvilJordan seems like you need to run app in dev mode - https://github.com/MetaMask/metamask-mobile/commit/1ce40360071c9887b74dd22bf75a7c8da370a1e3#diff-13a968b413463fc5fe1bd31271be82051f23d834ccb11e5f871cffba0badeb45

**Comment by shendel** [comment]
Why are you kidding developers?

Is it difficult to make a separate build (apk) with debugging enabled and put it here?

90% of programmers don't give a fuck at heart how to compile applications for android and ios

I spent two days compiling this repository
What we have:
Brands are broken (develop, v1.5.0, 1.5.0, v1.4.0)
Dependencies are broken
The instruction in readme is outdated for a long time

The output is a non-working dev-build, which does not work after entering the password ...

In the end, I spat on the whole thing (and cursed you in my head) - put firebug-lite on my d-app - and what do you think I found? (on the official google-play client)?

**Comment by shendel** [comment]
`window` object has no `ethereum`
two days....
two days Karl.... 
to understand that this is not my fault - but yours https://github.com/MetaMask/metamask-mobile/issues/1975

You are not MetaMask - you are MetaЛыганы
![image](https://user-images.githubusercontent.com/1880211/99319638-ed763400-287a-11eb-8c55-66c57ba9fd14.png)
Make a build for developers, like all other self-respecting service providers
Don't waste our time (developers) solving your bugs

**Comment by shendel** [comment]
@pacxiu P.P.S localnetworkip.xip.io dont work - config in xml not correct - there must be false (for ignore security and allow them) like localhost, 10.1.0.1 and 10.1.0.2

**Comment by shendel** [comment]
@rekmarks , @omnat any ideas exists?? i se you are prerere v1.0.6, v1.0.7, but no more info about this bug....

**Comment by omnat** [comment]
Hi @shendel , fix for #1975 will be available in v1.0.9 release. Does that answer your question?

**Comment by shendel** [comment]
@omnat I watched the process of solving the problem, it has not been updated in Google Play yet (1.0.8 last release there), so I cannot report the solution to the problem, I'm waiting for the update in the store to the latest version

**Comment by sharma66mahesh** [comment]
Asking us to build and run the android app is a terrible idea
https://docs.metamask.io/guide/mobile-best-practices.html#website-testing-and-debugging

**Comment by paulrberg** [comment]
Any updates on this? I'm getting an "Internal JSON-RPC error" only on MetaMask Mobile and I don't know what triggers it. Building the app myself is quite a chore ..

At least for iOS, a simple dev-channel app downloadable via TestFlight would go a long way!

**Comment by pieman64** [comment]
@paulrberg is that with iOS or Android and do you have debugging enabled in your dapp to see the error?

My dapp is fine with MetaMask on desktop and Android but recently stopped working with iOS.

**Comment by omnat** [comment]
@gantunesr @andrepimenta thoughts?

**Comment by pieman64** [comment]
Turned out to be the RPC for Polygon that was failing, now changed it to https://polygon-rpc.com/ and iOS is fine again now.

**Comment by robotzero1** [comment]
Easiest way to see console.log and errors is to use Sentry.io. Sign up for a free account and add something like this before your closing head tag. See their docs and examples for how to do it 100% properly.

```
<script  src="https://browser.sentry-cdn.com/6.19.2/bundle.js"  crossorigin="anonymous"></script>
<script src="https://browser.sentry-cdn.com/6.19.2/captureconsole.min.js"></script>

<script type="module" defer>
    Sentry.init({
        dsn: "https://8xxxxxb@oxxxxxx4.ingest.sentry.io/6xxxxx7",
        debug: false,
        integrations: [
            new Sentry.Integrations.CaptureConsole({
                levels: ['log', 'info', 'warn', 'error', 'debug', 'assert']
            })
        ],
    });
</script>
```
