### ISSUE TITLE
Add amount= replacing the value=

### ISSUE THREAD

**Issue by Mvfaassen** [MetaMask/metamask-mobile#1229]
for externals like myself, it's easier to add a numeric value instead of the uint and e18 value differentiation. 

It would be nice if instead of: https://metamask.app.link/send/0x2B855d3c31B6218605bA9975Ff52Ce02A34bb4bd@1?value=5e16 

you would have the option to fill out:

https://metamask.app.link/send/0x2B855d3c31B6218605bA9975Ff52Ce02A34bb4bd@1?amount=0,05

**Comment by brunobar79** [comment]
Thanks for the suggestion.  The reason we did it like this was to keep the link as close as possible to EIP-681 which uses the same notation: https://github.com/ethereum/EIPs/blob/master/EIPS/eip-681.md#semantics
