### ISSUE TITLE
Simplex - unable to find "buy with cc" option

### ISSUE THREAD

**Issue by dpazdan** [MetaMask/metamask-mobile#1231]
Under https://home.metamask.io/buy-crypto we have Simplex as an option to buy with credit card.  However, it just redirects to their main page, and there seems to be no way to actually buy on their site.

I think they partner with dapps to integrate directly into their sites.

**Comment by brunobar79** [comment]
This should be solved when we integrate fiat on ramp.  In the meantime we can delete it from the list.
In the meantime we should fix it once we take care of #987

**Comment by EtDu** [comment]
https://home.metamask.io/buy-crypto doesn't work anymore, Simplex is removed. Fiat on ramp is implemented.
