### ISSUE TITLE
autoRefreshOnNetworkChange not supported on metamask mobile

### ISSUE THREAD

**Issue by gpersoon** [MetaMask/metamask-mobile#1232]
Setting 
```JS
ethereum.autoRefreshOnNetworkChange = false;
```
Doesn't make a difference on metamask mobile. It still reloads the page after a network change, unlink the metamask extension.
Also see: https://metamask.github.io/metamask-docs/API_Reference/Ethereum_Provider
(although this function will be removed in the future, it allows to prepare for the future updates)

**Comment by brunobar79** [comment]
This should be fixed by #1236

**Comment by fahimaltinordu** [comment]
> Setting
> 
> ```js
> ethereum.autoRefreshOnNetworkChange = false;
> ```
> 
> Doesn't make a difference on metamask mobile. It still reloads the page after a network change, unlink the metamask extension.
> Also see: https://metamask.github.io/metamask-docs/API_Reference/Ethereum_Provider
> (although this function will be removed in the future, it allows to prepare for the future updates)

Hi @gpersoon, could you solve this issue? i have the same problem. metamask mobile browser still refresh the page
