### ISSUE TITLE
[Bug]: On Base when approving WETH via a dApp, the max button is not there, and the input field for specifying the amount to approve is not active

### ISSUE THREAD

**Issue by sleepytanya** [MetaMask/metamask-mobile#12320]
### Describe the bug

On Base when approving WETH via a dApp, the max button is not there, and the input field for specifying the amount to approve is not active. Users are unable to enter the desired approval amount, leading to the "Approve" button being inactive as well (greyed out). 

Bug is present in prod 7.33.2, in 7.34.0 (1475) Approval works as expected

Related (?) https://github.com/MetaMask/metamask-mobile/issues/11129

### Expected behavior

-

### Screenshots/Recordings

<img width="714" alt="Screenshot 2024-11-17 at 13 49 20" src="https://github.com/user-attachments/assets/8b0e9966-53c6-445a-8fab-85a885d6094c">

https://github.com/user-attachments/assets/b9e98737-5482-4387-ae3f-e5bf2e2ef364

https://github.com/user-attachments/assets/c8d6fc02-339c-4828-a1d8-06658336a0b2

### Steps to reproduce

1. Connect to Base
2. Approve WETH

### Detection stage

In production (default)

### Version

7.33.2

### Build type

None

### Device

iPhone 15

### Operating system

iOS

**Comment by bschorchit** [comment]
Should we close this as this is already fixed in v7.34, @sleepytanya? Or did I misunderstand something?

**Comment by sleepytanya** [comment]
@bschorchit 

Double checked in 7.37.0 - fixed:


https://github.com/user-attachments/assets/6234ac57-16dd-48f9-999f-a1f469820ee8
