### ISSUE TITLE
Request: Add support for Ledger Nano X

### ISSUE THREAD

**Issue by tobutridaz** [MetaMask/metamask-mobile#1237]
With Ledger Nano X capable of communicating with a phone over Bluetooth, it would be desirable to be able to use it to interact with dapps in the Metamask mobile browser .

**Comment by Skelectric** [comment]
Frankly, this is needed ASAP. There is currently no way to interact with dApps on mobile using hardware wallets.

**Comment by 47X** [comment]
this is a must have, I see it is added to v1 milestone but posting just to upvote

**Comment by ivan-prodanov** [comment]
I strongly encourage this to be reprioritized. You’ve got no idea how many threads exist on reddit from users requesting it.

**Comment by aaronovz1** [comment]
Any updates?

**Comment by twocell** [comment]
For most users i know, the mobile version of metamask is useless without this - just saying.

**Comment by MrCleanerPickerUpper** [comment]
Looking forward to an update on this issue.

**Comment by ivan-prodanov** [comment]
Me too. Team?

**Comment by LayerState** [comment]
This is a must and will be a game changer if actually done : metamask will capture the whole mobile wallet space if they do this.

**Comment by shufune** [comment]
Yes please, this would be incredible.

**Comment by totengu** [comment]
bought ledger nano X thinking it supports metamask mobile app, any chance it will be? kind of useless without hardware wallet support

**Comment by ivan-prodanov** [comment]
Apparently the team sees no future in hardware wallets. This whole thing looks absolutely ridiculous **unless** they're cooking something big as an alternative to HW wallets. I seriously hope so.

**Comment by mallachari** [comment]
According to this comment it is something that is worked on currently so there's a chance it might actually be added. https://www.reddit.com/r/Metamask/comments/jq21bb/hardware_wallets_ledger_nano_on_metamask_mobile/gbq936a

**Comment by omnat** [comment]
Hi all, thank you all for advocating for this feature - you are absolutely right, this is definitely a priority. Will post here if we are seeking feedback on the experience.

**Comment by pre-vail** [comment]
I was able to import my Nano X into MM for iOS

https://www.reddit.com/r/Metamask/comments/jq21bb/hardware_wallets_ledger_nano_on_metamask_mobile/gi60hcc

**Comment by krasi-georgiev** [comment]
This sounds strange there should be no way to see the private key of your ledger.

**Comment by ivan-prodanov** [comment]
Yeah it sounds like you imported your MM desktop account into MM mobile.

**Comment by pre-vail** [comment]
If anyone else is using Windows can you try and see if you can view your Nano X private key? I suspect that it may only be allowed using the MM Chrome extension for Windows.

Also, apparently you can get access to your private key using the following tool. Check out the last section - Generate private keys (advanced)

https://support.ledger.com/hc/en-us/articles/115005297709-Export-your-accounts

I think this would allow you to basically do what I did regardless of whether you’re using Windows or MacOS, although I haven’t tried it.

**Comment by Skelectric** [comment]
> I was able to execute a transaction.
> 
> https://www.reddit.com/r/Metamask/comments/jq21bb/hardware_wallets_ledger_nano_on_metamask_mobile/gi8ql0t

There's no way you imported your Nano X's private key into Metamask because (1) it's not accessible by design and (2) your seed wouldn't be compatible with Metamask anyway and (3) you definitely didn't stumble into a non-existent feature by accident. It sounds like you just imported the Metamask seed, so please stop cluttering this thread, it spams notifications to people who are actually interested in the support being officially released.

**Comment by pre-vail** [comment]
> There is currently no way to interact with dApps on mobile using hardware wallets. Being able to safely transact with DeFi on-the-go would be a great enhancement.

Cluttering this thread? You can’t be serious. I’m doing EXACTLY what you claim can’t be done. I’ve now done numerous transactions on tokensets.com. You keep waiting on them to officially release the feature while I continue to “safely transact with DeFi on-the-go”.

**Comment by rubberducketh** [comment]
@pre-vail are you signing each transaction on your ledger? If not, then you're effectively not using a hardware wallet and you're facing all the security risks of a hot wallet.

**Comment by cchike** [comment]
My new Nano X just came in and I'd gotten it for the sole purpose of using it on Metamask mobile. I was shocked that this wasn't already a feature, and I'm disappointed I spent my money on this for nothing :\

**Comment by NessDan** [comment]
Hey everyone, we have a [feature request for Ledger Nano X support on the Chrome extension and/or the Mobile app!](https://community.metamask.io/t/add-bluetooth-support-to-mobile-app-and-or-chrome-extension-ledger-nano-x/658) If it gets enough votes, it could be implemented!

Please go vote on the linked Metamask community page!

**Comment by richf62** [comment]
Opened issue in 2019 and still no action!! Come on Ledger get your act together!!!

**Comment by lucasprates** [comment]
This is just an absurd that it has passed almost two years and no one is prioritizing this. Absolutely bummer.

**Comment by AnonyKwan** [comment]
+1

**Comment by ZrowGz** [comment]
This should be one of your highest priorities at this point, as it should be with ledger.

**Comment by liondani** [comment]
Any news?

**Comment by jakues** [comment]
waiting the feature released :(

**Comment by alexanderjeurissen** [comment]
> Hi all, thank you all for advocating for this feature - you are absolutely right, this is definitely a priority. Will post here if we are seeking feedback on the experience.

@omnat You indicated in *December, 1st, 2020* that this feature request was deemed high priority. Since then things have remained quiet on the MetaMask team side.

Could you provide an update on when this feature is scheduled on your current roadmap, and what progress have been made (if any) up until now ? I think setting expectations here and providing some clarity will go a long way in garnering trust of your users/community. 

Cc: @estebanmino @andrepimenta

**Comment by DeathMoJo** [comment]
Let's make it happen! Thank you!

**Comment by losmibb** [comment]
Please implement this feature, it is badly needed for HW that already supports bluetooth.

**Comment by ZrowGz** [comment]
> If anyone else is using Windows can you try and see if you can view your Nano X private key? I suspect that it may only be allowed using the MM Chrome extension for Windows.
> 
> Also, apparently you can get access to your private key using the following tool. Check out the last section - Generate private keys (advanced)
> 
> https://support.ledger.com/hc/en-us/articles/115005297709-Export-your-accounts
> 
> I think this would allow you to basically do what I did regardless of whether you’re using Windows or MacOS, although I haven’t tried it.

By doing this ^^^ you are restoring your ledger wallet into Metamask and basically circumventing all the security benefits of ever having used a hardware device. Don't import your hardware wallet into a software wallet! 

I have been using the stupid work around that is accessing it through Ledger Live on a computer, and just not transacting with hardware-secured assets when AFK, which is nonsensical for such a powerful app to deny us access to! Unfortunately, I have had to use the Metamask hot wallet I created when first setting up Metamask, but I keep far fewer assets in there because of the lesser security; not willing to risk my security for convenience! 

Come on metamask & ledger! Let's make this space even more accessible to all the new users and their $$$ looking to buy in on this mega dip ;)

**Comment by trupsalms** [comment]
I'd like to be about to see my ledger from my metamask mobile app

**Comment by crazysoldier** [comment]
I just logged in after a long time just to approve that this is the only and most wanted feature for every serious crypto User I know! 
Nobody wants to save privatekeys in a hot wallet connected to the internet! 
And as I am going to travel now I need a working mobile solution for my weekly DeFi tasks like updating my farming and credit positions.
I would even pay some dev to implement this if needed.
Now I need to buy a new MacBook Air just to put my ledger in contract mode in the browser … 
I can understand it’s hard to work with ledger but you willpower your main product if some competition comes out with a working app now.

Cheers

**Comment by trx314** [comment]
how is it even possible that this is not implemented? I bought a nano x (my third ledger) to not have to deal with cables anymore, and it actually is useless on that matter. Besides being bigger and heavier.

**Comment by takan55** [comment]
It's been over 1.5 years and still been waiting. This will never happen I guess.

**Comment by lucasprates** [comment]
Unfortunately no one at metamask, or other projects, care about mobile safety while browsing, creating this. I still cannot use my wallets on mobile because of this. 
If it takes more 6 months, I might create an app myself.

**Comment by Aeroxander** [comment]
It looks like Rainbow Wallet will have Ledger integration soon so then you can connect to DApps with Walletconnect!

**Comment by ivan-prodanov** [comment]
Technically you can already connect to dapps using Walletconnect & ledger nano X.

**Comment by phho0698** [comment]
I have moved everything I had on metamask on my desktop so that it requires interaction with my ledge nano x in order to approve transaction for defi etc. This is awesome. The problem now is that this feature isn't supported on the metamask mobile app. I can't even see the ledger protected metamask account and therefore have to carry a laptop with me every time. Please add this feature I feel alot of people are waiting for it!

**Comment by omnat** [comment]
Hi all, this is Omna from the MetaMask team again.
We understand hardware wallet on mobile is in huge demand and will be valuable to add. 

Our team has been pretty resource constraint, and adding hardware wallet support will mean increased maintenance as well. We are working on getting that extra capacity for supporting hardware wallets, but can't promise a timeline yet, but want you all to know that this is on our roadmap now. Some of you have shared some work arounds, including using hardware wallets with MetaMask extension till then. 

Thanks for opening and sharing your thoughts on the issue, this is also one of the top voted feature requests on our community forum https://community.metamask.io/c/feature-requests-ideas/13

**Comment by atomicdada** [comment]
Please MM devs !! you can do it guys !!!!
Sucks really bad no beeing able to use my ledger through MM on my Phone

Xmas is coming !!!! i know what i'm wishing for this Xmas ;-)

Keep up the good work !

**Comment by bertho-zero** [comment]
I can give money for this issue

**Comment by soldev42** [comment]
Must have feature, hurry up team!

**Comment by Karp256** [comment]
Is there a chance this is a problem with some sort of limitation put in by apple on IOS apps ability to interact with 3rd part devices in such a manner?

**Comment by alexanderjeurissen** [comment]
> Is there a chance this is a problem with some sort of limitation put in by apple on IOS apps ability to interact with 3rd part devices in such a manner?

No, the Ledger Live iOS app interacts with the hardware wallet just fine, both for managing as well as signing transactions through wallet connect protocol.

**Comment by alexanderjeurissen** [comment]
> Hi all, this is Omna from the MetaMask team again.
> 
> We understand hardware wallet on mobile is in huge demand and will be valuable to add. 
> 
> 
> 
> Our team has been pretty resource constraint, and adding hardware wallet support will mean increased maintenance as well. We are working on getting that extra capacity for supporting hardware wallets, but can't promise a timeline yet, but want you all to know that this is on our roadmap now. Some of you have shared some work arounds, including using hardware wallets with MetaMask extension till then. 
> 
> 
> 
> Thanks for opening and sharing your thoughts on the issue, this is also one of the top voted feature requests on our community forum https://community.metamask.io/c/feature-requests-ideas/13

@omnat has the team considered using something like bounty source to allow the community to financially support the development of this feature ? (Or perhaps set up GitHub sponsorship) I'd be more then happy to help support the development of this and other features and from previous messages in this thread I seem to not be alone in this either !

**Comment by christopher-siegel** [comment]
Any updates on this? 
It's frustrating to have a Ledger Nano X and not be able to use it with MetaMask. 

I'd rather have this feature than a dark mode! 
Hope this is still being developed, let the community support it if needed

**Comment by ivomarsan** [comment]
It'll be a great feature. I love swap $BNB to $ECOIN in my Chromebook or Laptop, but I cant do this in my smartphone.

Either readonly mode it will be great as well. Just for watch my crypto assets in Metamask

**Comment by ivomarsan** [comment]
Trust Wallet has a feature to add just bscscan address to readonly. It will be perfect for now in Metamask

**Comment by SweetmanTech** [comment]
Seems like Mobile Metamask + Ledger still isn't supported?

Guess I'll be looking at alternative apps to download.

Goal is to validate my NFT for my Twitter pfp.

**Comment by mickaphd** [comment]
Any update from the team on this? Zerion (or even Green for BTC) on iOS can connect to a nano X via bluetooth. A shame that we still don’t have a « real » MetaMask or Frame app on those device.

**Comment by AlexJupiter** [comment]
I'm happy to report that hardware wallet support in general is actively in development on mobile. We'll be making some larger public announcements in the next month or so, but we're starting with the QR hardware wallets (e.g. Keystone) first and then quickly moving onto Ledger.  When there's a rough ETA for a Ledger integration I'll drop it in here.

**Comment by mickaphd** [comment]
Many thanks @AlexJupiter. Being able to use MetaMask with a Ledger on iOS/iPadOS/Android for both L1 and L2 will be a game changer imo. Can't wait to test it.

**Comment by vzvedran** [comment]
Hi, this would be really great addition to metamask. Terra station wallet supports it as well, you might find this useful:

https://github.com/terra-money/station-mobile/commit/3ec15b9a620432dee47378f5b6e621d93780748a

**Comment by ivan-prodanov** [comment]
MetaMask is a lagging by a lot and the logic behind some roadmap decisions baffles me the least for *not* giving us a reason _why_ a certain decision is taken. For example - Ledger is the most popular hardware wallet. The decision is to go with Keystone first, after years of neglecting what the community wants.

Since ledger is the most popular hardware wallet especially utilizing MetaMask, let’s focus on what we have *right now* - desktop integration, which sucks *by a lot*. I’ve switched to Frame wallet long ago for the simple reason that *already have* better UX with desktop ledger hardware wallet integration. Furthermore they *actually listen to feedback* and respond:
1. I requested support in Safari. There’s lots of Mac users yet no wallet works with the native browser.

2. Mobile app with ledger hardware support.

Took no more than 1 day to get them to agree on this.

I’m sorry MetaMask but given the lack of information and context on your decisions and vision and reasons as to why this vision exists and such decisions are taken, I can conclude that you can do better than that. Until this changes you won’t have me as a user, who’s been using your software for years. 


Get your shit together❗️

**Comment by AlexJupiter** [comment]
@ivan-prodanov understanding your concerns here! Hopefully we'll have something exciting to report to you soon...

**Comment by CRASH-Tech** [comment]
Need this!

**Comment by gantunesr** [comment]
As Alex mentioned previously, at the moment we're working on integrating Keystone and Ledger to MetaMask Mobile. We'll drop more updates during the following weeks

**Comment by varanauskas** [comment]
For others looking for progress I have found a PR addressing this that is quite active: #4088

**Comment by moretti** [comment]
Ledger is also developing a mobile browser extension (iOS only for now): https://get-connect.ledger.com/

**Comment by venatiodecorus** [comment]
Ledger Live event at the end of the month. Maybe some good news there :)

**Comment by cryptedx** [comment]
PUSH!

**Comment by gantunesr** [comment]
Hey everyone! thank you for all your patience so far, the Ledger integration in a WIP at the moment. We'll have more updates in the followings weeks.

**Comment by ps350** [comment]
Is there any update on this? The Ledger blog (a link to which was tweeted by Metamask official Twitter account) stated this functionality should be rolling out in Fall 2022, and we are well past that timeframe.

**Comment by okayplanet** [comment]
> 

Where can I read these updates?

**Comment by ahh1539** [comment]
Just tell us if this feature has been abandoned so we can find MetaMask alternatives and stop wasting time.

**Comment by Bobm89** [comment]
Any progress?

**Comment by Bobm89** [comment]
Is the ledger support abandoned in Metamask?

**Comment by okayplanet** [comment]
@gantunesr are you still familiar with the status of this effort?

**Comment by bertho-zero** [comment]
This request is more than 3 years old, it is so necessary that it is incomprehensible.

**Comment by ahh1539** [comment]
This feature has been officially abandoned. I will be providing a list of alternative wallets shortly.

**Comment by AlexJupiter** [comment]
Hi all! We really appreciate the interest in this feature. We are still working on this and aim to ship it over the next couple of months. Apologies for the silence but sometimes these things are more difficult than they seem 😅 .

**Comment by ps350** [comment]
@ahh1539 Would love to switch to an alternative if available. Last I checked, couldn't find a single mobile wallet that supported Ledger integration for Ethereum and it's L2s.

**Comment by varanauskas** [comment]
Ledger has an application to allow it's usage with web3 apps in beta now
https://get-connect.ledger.com

**Comment by bertho-zero** [comment]
> Ledger has an application to allow it's usage with web3 apps in beta now https://get-connect.ledger.com

Only for iOS

**Comment by bertho-zero** [comment]
https://github.com/MetaMask/metamask-mobile/pull/5652

**Comment by Bobm89** [comment]
Any planned merge date?
