### ISSUE TITLE
[Bug]: On Android devices, nonce customization remains accessible even when STX transactions are enabled

### ISSUE THREAD

**Issue by sleepytanya** [MetaMask/metamask-mobile#12390]
### Describe the bug

On Android devices, nonce customization remains accessible even when STX transactions are enabled. Attempting to send a transaction with a low nonce value results in an 'Internal JSON-RPC error', while sending transactions with a high nonce value leads to the execution of regular, non-STX transactions.

On iOS nonce customization is disabled when sending STX.

### Expected behavior

-

### Screenshots/Recordings

iOS works as expected - nonce field is not displayed:

https://github.com/user-attachments/assets/738d4e6b-369c-4756-82b4-9d35f004fa1a

Android - nonce can be modified while STX is ON:

https://github.com/user-attachments/assets/0a4db1bb-175e-4591-92af-45dea321da77

### Steps to reproduce

1. Enable STX in Settings
2. Enable Nonce customization in Settings
3. Send an STX, observe that user can interact with the nonce input field

### Detection stage

During release testing

### Version

7.36.0 (1501)

### Build type

None

### Device

Samsung S24+

### Operating system

Android

**Comment by sleepytanya** [comment]
Not present on latest `main`
Bitrise build https://app.bitrise.io/build/33f86ced-fc2e-4c83-9c38-76eeca6952dc?tab=artifacts


https://github.com/user-attachments/assets/0a3d8628-1be4-4320-86ce-374248a45f5e

**Comment by Unik0rnMaggie** [comment]
Unable to reproduce on the below device, on Ethereum Mainnet:

- Device Pixel 6 Pro
- OS:  Android 14

The nonce field appears only when STX is turned OFF. 

This is only applicable for Ethereum Mainnet. For all other networks, the nonce field appears also when STX is turned ON.

I obtained the build from [here](https://app.bitrise.io/app/be69d4368ee7e86d/installable-artifacts/7e0c5081d3c5e128/public-install-page/2bc791b8c282341bfcc0ada2f3b55638)


https://github.com/user-attachments/assets/8b816b28-c4b3-4c2d-b92b-f210f60632e0

**Comment by sleepytanya** [comment]
Issue is not present in the latest RC 7.36.0 (1503):


https://github.com/user-attachments/assets/50345768-4ce5-4405-b627-230f08474224
