### ISSUE TITLE
[Bug]: metamask cannot unlock

### ISSUE THREAD

**Issue by Hso1P** [MetaMask/metamask-mobile#12412]
### Describe the bug

I unlock my metamaks with face id and nithing happen even ut is correct

### Screenshots/Recordings

https://github.com/user-attachments/assets/3b942a30-b527-4986-875b-7fae7929a6f8

### Steps to reproduce

I open metamask It took. Faceid show correct and nothing happen

### Detection stage

In beta

### Version

7.35.1

### Build type

None

### Browser

Other (please elaborate in the "Additional Context" section)

### Operating system

Other (please elaborate in the "Additional Context" section)

### Additional context

IOS

**Comment by DanielTech21** [comment]
Hi @Hso1P 

Thank you for creating this issue.

One of our engineers will look into this.

**Comment by gauthierpetetin** [comment]
Hello, thanks for reporting this issue.
Could it be a duplicate of https://github.com/MetaMask/metamask-mobile/issues/12322
If yes, can we close this issue?

**Comment by gauthierpetetin** [comment]
Closing a duplicate of https://github.com/MetaMask/metamask-mobile/issues/12322 after discussion with @frankvonhoven .
