### ISSUE TITLE
Android: Approves waaaay more DAI than it should

### ISSUE THREAD

**Issue by auryn-macmillan** [MetaMask/metamask-mobile#1243]
Tried buying a sponsorship from [sp.brightid.org](https://sp.brightid.org) from the metamask mobile app today, and noticed that it wanted me to approve 10^18 DAI :grimacing: 

Needless to say, I rejected the transaction.

At first I thought it was an issue with their code, but when I tried it on my desktop it behaved as expected.

Here is the relevant code snippet.

```
dai = parseFloat($("#spDai").val()) * 10 ** 18;
  ptContract.approve.sendTransaction(addresses.sp_minter, dai, function (error, result) {}
```

On desktop it asks to approve 1DAI
![Screenshot from 2019-12-10 10-19-40](https://user-images.githubusercontent.com/8453294/70542394-a8a83000-1b36-11ea-8d95-1cd493da52a9.png)

On mobile it asks to approve 1,000,000,000,000,000,000 DAI
![image](https://user-images.githubusercontent.com/8453294/70542500-cd9ca300-1b36-11ea-841d-724c32615970.png)

**Comment by estebanmino** [comment]
Hi @auryn-macmillan, thanks for reporting! we're aware of this and we're working to get it up to date with the extension behavior.
