### ISSUE TITLE
Browser doesn't support Oauth2 

### ISSUE THREAD

**Issue by octavioamu** [MetaMask/metamask-mobile#1244]
Seems the browser have problems with the redirect codes.

To reproduce go to github.com login and then go to gitcoin.co and try to login.  

Android MM v0.2.12(25)

**Comment by owocki** [comment]
hey @danfinlay any objections if i throw up a bounty for someone to investigate this?  🙏

**Comment by danfinlay** [comment]
Probably not, as long as its terms are clearly defined.

**Comment by DaniellMesquita** [comment]
It should be a priority issue.

**Comment by owocki** [comment]
bountying https://github.com/MetaMask/metamask-mobile/issues/1273

@danfinlay ill bankroll the bounty, but will need ur help picking a contributor

**Comment by owocki** [comment]
i put up a bounty https://github.com/MetaMask/metamask-mobile/issues/1273

**Comment by omnat** [comment]
@octavioamu is this still an issue? Could you try reproducing on the latest version?

**Comment by ibrahimtaveras00** [comment]
Seems like this is related to = https://github.com/MetaMask/metamask-mobile/issues/1273 which seems to have been resolved
