### ISSUE TITLE
codepen.io stuck on captcha detection

### ISSUE THREAD

**Issue by octavioamu** [MetaMask/metamask-mobile#1245]
codepen.io is detecting the browser as suspicious and not even able to see the site. 

Go to codepen.io google captcha screen didn't pass. 
Android MM v0.2.12(25)

**Comment by brunobar79** [comment]
Thanks for reporting. 
Honestly I don't think there's not much we can do on this one since we're not even using a custom user agent. 

If you have any idea please share it.

**Comment by octavioamu** [comment]
I will take a look with chrome devtools when I get some time but I think this issue and the oauth2 not supported are very important for any browser. I wasn't able to login into any oauth2 application. 
In my way to see it seems like should be an important issue, since is preventing to login or even enter sites.

**Comment by rickycodes** [comment]
@octavioamu this should be working now
