### ISSUE TITLE
[Bug]: The app breaks with an error when user attempts to edit suggested gas fees for swap

### ISSUE THREAD

**Issue by sleepytanya** [MetaMask/metamask-mobile#12457]
### Describe the bug

Error occurs for swaps initiated from within the wallet and for swaps initiated from dApps. 

Error message iOS:

<img width="494" alt="Screenshot 2024-11-26 at 23 35 00" src="https://github.com/user-attachments/assets/5d1b39fc-a64b-4e3a-bcfb-6d5aa6255366">

Error message Android:

<img width="497" alt="Screenshot 2024-11-26 at 23 35 10" src="https://github.com/user-attachments/assets/1637e9ec-a20e-492f-a606-b37e0c715f3b">

### Expected behavior

-

### Screenshots/Recordings

Android:

https://github.com/user-attachments/assets/ca1805fc-a738-4906-a568-ffafba96da12

iOS:

https://github.com/user-attachments/assets/61f0fa4c-d989-4296-befd-cbf4f99d3240

### Steps to reproduce

1. Start swap transaction
2. Edit gas fees

### Detection stage

During release testing

### Version

7.36.0 (1504)

### Build type

None

### Device

Samsung S24+, iPhone 15

### Operating system

iOS, Android

**Comment by vpintorico** [comment]
Adding confirmations here since this bug seems related with [#12387](https://github.com/MetaMask/metamask-mobile/issues/12387)

**Comment by sleepytanya** [comment]
@Unik0rnMaggie 
 Closing in favor of  https://github.com/MetaMask/metamask-mobile/issues/12395
