### ISSUE TITLE
Call Back to Native App

### ISSUE THREAD

**Issue by Pavan-Unikwork** [MetaMask/metamask-mobile#1247]
I am Using Metamask for transection from my app. I am using deep linking for that.
I am successfully redirected on Transection page of the application and can do the payment.
But after successful payment How can I come back to my APP or Is there any way to get a notification or delegate method for that to know transaction status
Thanks in advance

**Comment by brunobar79** [comment]
There's no way of getting a callback to a native app for now but that should be solved by #902
