### ISSUE TITLE
Not found USDC

### ISSUE THREAD

**Issue by Pavan-Unikwork** [MetaMask/metamask-mobile#1248]
I have a sync phone app(Beta) with my chrome extension. If fetch all my wallet data.
When I set "Rinkeby test network". Wallet details show my ether correct but usdc incorrect.

**Comment by Pavan-Unikwork** [comment]
> I have a sync phone app(Beta) with my chrome extension. If fetch all my wallet data.
> When I set "Rinkeby test network". Wallet details show my ether correct but usdc incorrect.
> ![Screenshot 2019-12-14 at 5 40 29 PM](https://user-images.githubusercontent.com/58810639/70848525-e12e6d80-1e98-11ea-9ab9-31cac8d62e05.png)
> ![Image from iOS](https://user-images.githubusercontent.com/58810639/70848544-2eaada80-1e99-11ea-9790-b919da6291ed.png)
> So please review #it.

**Comment by brunobar79** [comment]
We only autodetect tokens on mainnet. You can add it manually through "Add token" if you know the address of the contract
