### ISSUE TITLE
Second transaction is not shown to the user

### ISSUE THREAD

**Issue by PaulRBerg** [MetaMask/metamask-mobile#1249]
## Description
Here's my transaction flow:

1. Approve token
2. Submit dapp tx

And an approximation for my JavaScript code that creates these two transactions (with ethers.js).

```javascript
const txs = [];
const tokenApprovalTx = await createTokenApprovalTx();
txs.push(tokenApprovalTx);
const sablierTx = await createSablierTx();
txs.push(sablierTx);
```

The 2n transaction is not picked up by the mobile browser and the user doesn't see it at all.

## Expected Behaviour

The user should be prompted to sign the 2nd transaction, even if they just previously submitted another one.

## Steps

1. Go to [pay.sablier.finance](https://pay.sablier.finance)
2. Log in
3. Have some Eth and Dai
4. Tap "Stream Money"
5. Fill the form with "0.01", any recipient and any duration (caveat: if you don't pay yourself, the money is lost)
6. Submit form

## Environment

- iPhone XR and iOS 12.3.1
- MetaMask Mobile v0.2.8

**Comment by PaulRBerg** [comment]
Any updates on this? this issue has caused trouble for a lot of our users. The dapp cannot be used with Metamask Mobile at all.

**Comment by brunobar79** [comment]
@PaulRBerg  Can you add to the code snippet of what do you do with the tx array? That will help a lot.

**Comment by PaulRBerg** [comment]
Hey @brunobar79 I created a gist for you:

https://gist.github.com/PaulRBerg/eadb8eeed13f0cb7d8576723948d532c

See the `submit` function.

**Comment by dpazdan** [comment]
related support case 29299

**Comment by dpazdan** [comment]
I was able to replicate this bug when trying to add OXT tokens to orchid account setup: http://account.orchid.technology/

**Comment by PaulRBerg** [comment]
I haven't tested it, but the same bug might occur on [gitcoin.co/grants](https://gitcoin.co/grants/) too. They have a similar transaction flow.

**Comment by brunobar79** [comment]
Thanks for the info. I'm gonna create a very simple repro app in ropsten to be able to debug better.

**Comment by danjm** [comment]
@PaulRBerg Can you confirm that this is still a bug?

**Comment by PaulRBerg** [comment]
@danjm it works well on version 0.2.14. I'll close this issue for now.

Thanks for the fix!
