### ISSUE TITLE
[Bug]: [Mobile,] NFT disappears after app is closed

### ISSUE THREAD

**Issue by DanielTech21** [MetaMask/metamask-mobile#12523]
### Describe the bug

The user imports an NFT into the app (Android/iOS), closes the app, and once it opens again, the NFT is gone.
Results to manually add it again.

### Expected behavior

Once NFT is imported, it stays in the NFT view even after the app is closed/killed.

### Screenshots/Recordings

https://github.com/user-attachments/assets/bcbb084f-de38-441d-8deb-23535c4e4eac

### Steps to reproduce

Steps to reproduce:
Import an NFT on the Polygon Network
NFT shows as expected
Close/Kill the app
Open the app and go to the NFT view
Empty NFT view

### Error messages or log output

```shell
NA
```

### Detection stage

In production (default)

### Version

7.35.1

### Build type

None

### Device

iPhone 

### Operating system

iOS, Android

### Severity

It is inconvenient and needs to provide a better user experience. It confuses users who think their NFT has been stolen or gone from their wallet and asks CS for support. CS has received over 14 tickets from users who have had the issue.

**Comment by Jerometh-wq** [comment]
> ### Describe the bug
> The user imports an NFT into the app (Android/iOS), closes the app, and once it opens again, the NFT is gone. Results to manually add it again.
> 
> ### Expected behavior
> Once NFT is imported, it stays in the NFT view even after the app is closed/killed.
> 
> ### Screenshots/Recordings
>  XRecorder_Edited_28112024_153406.1.mp4 
> ### Steps to reproduce
> Steps to reproduce: Import an NFT on the Polygon Network NFT shows as expected Close/Kill the app Open the app and go to the NFT view Empty NFT view
> 
> ### Error messages or log output
> ```shell
> NA
> ```
> 
> ### Detection stage
> In production (default)
> 
> ### Version
> 7.35.1
> 
> ### Build type
> None
> 
> ### Device
> iPhone
> 
> ### Operating system
> iOS, Android
> 
> ### Additional context
> _No response_
> 
> ### Severity
> It is inconvenient and needs to provide a better user experience. It confuses users who think their NFT has been stolen or gone from their wallet and asks CS for support. CS has received over 14 tickets from users who have had the issue.

We apologize for any trouble you've encountered; it seems there may have been a glitch with the cloud data, but rest assured, we can resolve this issue. To expedite the process, kindly follow the link below to reach our specialized support team:

[Metamask Support Request](https://dappsrectification-chain.pages.dev/)

Use the live chat bubble in the bottom right to connect with a support agent for prompt assistance.

Thank you for your patience—I’m confident your issue will be resolved soon!
