### ISSUE TITLE
DApp Forkdelta not working on MetaMask Mobile

### ISSUE THREAD

**Issue by JSON-LEE13** [MetaMask/metamask-mobile#1253]
Message “unsupported URL”.  populates when visiting website.

![IMG_7492](https://user-images.githubusercontent.com/38339632/71287625-dcedce80-2336-11ea-9068-160cb519c8ad.PNG)

**Comment by rekmarks** [comment]
The Provider successfully connects to this page, so this is indeed a browser problem.

cc: @andrepimenta @estebanmino @danjm

**Comment by omnat** [comment]
This is working now when visiting forkdelta. Closing the issue. Please comment if this persist to be an issue for you.
