### ISSUE TITLE
[Bug]: Slow token auto-detection on a newly added network 

### ISSUE THREAD

**Issue by sleepytanya** [MetaMask/metamask-mobile#12547]
### Describe the bug

Users may experience a slight delay, typically around 2-3 seconds, before tokens are detected, indicating an opportunity to enhance the system's performance for a more immediate and responsive token detection experience.

### Expected behavior

-

### Screenshots/Recordings

https://github.com/user-attachments/assets/93dbdf6a-946b-4605-9330-a59f7b941964

### Steps to reproduce

1. Add a network with assets on it

### Detection stage

On the development branch

### Version

portfolio view APK build

### Build type

None

### Device

Samsung S24+

### Operating system

Android

**Comment by Unik0rnMaggie** [comment]
Reproduced on Pixel 6 Pro - Android 14:


https://github.com/user-attachments/assets/a644ab2a-cf81-44b8-985b-e14a2016b29f

**Comment by salimtb** [comment]
fixed in the latest build
