### ISSUE TITLE
[Bug]: All Networks selector switches to Current Network after adding a popular network

### ISSUE THREAD

**Issue by Unik0rnMaggie** [MetaMask/metamask-mobile#12550]
### Describe the bug

While being on the _All Networks_ view and adding a popular network, the network selector switches to _Current Network_

### Expected behavior

Network selector to remain on All Networks

### Screenshots/Recordings

https://github.com/user-attachments/assets/cb5d5571-9b70-4aa8-91f9-2c5801ab51b0

### Steps to reproduce

1. Select _All Networks_ in the network selector
2. Add any popular network
3. Notice the network is switched from _ALL networks_ to _Current Network_

### Detection stage

In beta

### Version

7.35.1 (1502)

### Build type

Other (please specify exactly where you obtained this build in "Additional Context" section)

### Device

Pixel 6 Pro

### Operating system

Android

### Additional context

QA build

**Comment by sleepytanya** [comment]
In the latest APK build network selector stays on All Networks after adding a new chain:

https://github.com/user-attachments/assets/cda479f1-6c7d-4c71-97e9-c191ae47c5a2

**Comment by Unik0rnMaggie** [comment]
Same for Android in the latest QA build: network selector stays on All Networks after adding a new chain

https://github.com/user-attachments/assets/2da92376-8bc1-4064-b67a-ca0fe7aeb308
