### ISSUE TITLE
DApp LedgerDex Not Working on MetaMask Mobile

### ISSUE THREAD

**Issue by labsterx** [MetaMask/metamask-mobile#1256]
The Dapp LedgerDex (https://app.ledgerdex.com/) has been working fine with the MetaMask plugin on desktop browsers. It also works fine with other mobile wallets such as the ImToken app. However, it doesn't work on the MetaMask mobile app. In particular, login by message signing doesn't work. Users can't log in. 

Please help fixing! Thanks! 

@brunobar79

**Comment by omnat** [comment]
Hi @labsterx, what's specifically the issue? Are you getting the network not supported error even when you are on the stated supported networks? 

Unsure if this is a problem happening of MetaMask side, as haven't seen this issue with any other dapp. Could you let us know which network method you are using?

**Comment by mdpienaar** [comment]
hello. i am also seriously looking for a mobile wallet to connect to ledgerdex.com. as far as i could see imToken wallet cannot import an Ethereum account.

**Comment by mdpienaar** [comment]
the message from ledgerdex.com, not connecting is that the correct network is not used. ledgerdex refers to "Main Ethereum Network" and metamask refers to "Ethereum Main Network". Please refer to the attached printscreen.
![Screenshot_20210112-073603_MetaMask](https://user-images.githubusercontent.com/11485999/104496380-97efa680-55e1-11eb-9561-4beadcea5025.jpg)

**Comment by ibrahimtaveras00** [comment]
This no longer seems to be an issue 

![Screen Shot 2021-01-28 at 6 45 33 PM](https://user-images.githubusercontent.com/41752922/106212723-2f83f600-6199-11eb-9a7c-4cb48370e9d1.png)

@mdpienaar please let us know if you're still experiencing this issue on the latest version ( v1.0.10)

**Comment by mdpienaar** [comment]
Metamask

Thank you for your response.

I can now login to app.ledgerdex.com but experienced the following problems:

(1) Wanting to open Etherscan in a second browser tab, Etherscan could not
be accessed.

(2) Wanting to add Africahead Ipparts (AFA) brand
token: 0xfb48e0dea837f9438309a7e9f0cfe7ee3353a84e, ledgerdex just spinned
without progress, not finding the token. The same happened with the other 3
brand tokens of IPPAEX. They are Divided Party (DiP), Kaeuoi (KAE) and
fonetones (FON) brand tokens.

(3) Moyom (MYM) utility token of Ipparts Exchange (IPPAEX), was visible
after login, but none of the brand tokens of IPPAEX.

(4) Trying to trade MYM, the exchange counter of MYM/WETH, did not open, as
well as AFA/MYM, FON/MYM, KAE/MYM and DiP/MYM not.

Kind regards

Marquard Pienaar
Owner/founder of Africahead
https://africahead.github.io
https://www.africahead.co.za
tel: +27(0)824477125

**Comment by andrepimenta** [comment]
This issue should be fixed in newer versions, please try the live version and open another ticket if the issue still persists.
