### ISSUE TITLE
[Bug]: Sending ETH on Sepolia or Linea test networks fails 

### ISSUE THREAD

**Issue by Unik0rnMaggie** [MetaMask/metamask-mobile#12571]
### Describe the bug

Send ETH on Sepolia or Linea test networks fails - 'Fiat conversions are not available at this moment' message and disabled 'Next' button

### Expected behavior

Be able to send transaction

### Screenshots/Recordings

https://github.com/user-attachments/assets/dcb7e01d-92dc-483e-8318-44e5cd1dc859

### Steps to reproduce

1. Switch to Sepolia or Linea test networks
2. Send ETH token
3. Notice 'Fiat conversions are not available at this moment' message and disabled 'Next' button

### Detection stage

In beta

### Version

v7.35.1 (1502)

### Build type

Other (please specify exactly where you obtained this build in "Additional Context" section)

### Device

Pixel 6 Pro

### Operating system

Android

### Additional context

QA build

**Comment by Unik0rnMaggie** [comment]
Not present in v7.37.0 [build](https://app.bitrise.io/app/be69d4368ee7e86d/installable-artifacts/b090fe2821a733bc/public-install-page/bda331dd74b7ba58e47cb521a8e9a600)

**Comment by sahar-fehri** [comment]
I am able to repro this one on main; i think we can remove portfolio-view label 🙏

**Comment by salimtb** [comment]
fixed within this [commit](https://github.com/MetaMask/metamask-mobile/pull/12431/commits/16abd59b3c5a5a84f248721c7e39320924019f1f)
