### ISSUE TITLE
[Bug]: TypeError: Cannot read property 'totalFiatBalance' of undefined

### ISSUE THREAD

**Issue by Unik0rnMaggie** [MetaMask/metamask-mobile#12570]
### Describe the bug

The error shows up when clicking on _Account selector_ while being on the default test networks Sepolia and Linea

### Expected behavior

No error 

### Screenshots/Recordings

https://github.com/user-attachments/assets/a75ae86e-3a82-422d-9f65-f9a9b60b31e9

![Screenshot_20241205-113412](https://github.com/user-attachments/assets/49f2b163-56cb-477b-9de1-a7ed6fa9f819)

### Steps to reproduce

1.  Have several accounts and networks added
2. Switch to Sepolia or Linea test networks
3. Click on Account selector 
4. Notice error

### Error messages or log output

```shell
View: Root
TypeError: Cannot read property 'totalFiatBalance' of undefined
```

### Detection stage

In beta

### Version

7.35.1 (1502)

### Build type

None

### Device

Pixel 6 Pro

### Operating system

Android

### Additional context

QA build

**Comment by Unik0rnMaggie** [comment]
Fixed in the latest QA build:


https://github.com/user-attachments/assets/b616cbd8-ae87-4e06-b854-3f9d317f64e6

**Comment by sleepytanya** [comment]
The bug is present in the latest APK:

https://github.com/user-attachments/assets/ef334afa-5bd2-461a-93c4-d7df0c6f9062


![Image](https://github.com/user-attachments/assets/368bff3b-e83e-470e-a3cd-68e63b5ce9ed)

**Comment by Unik0rnMaggie** [comment]
Hi Team,

The error is not present for me in the latest QA build shared by @salimtb 

https://github.com/user-attachments/assets/9550c496-b1a8-4c79-8bb4-bc3d03224226
