### ISSUE TITLE
IPFS Broken WebsiteIcon

### ISSUE THREAD

**Issue by xmaysonnave** [MetaMask/metamask-mobile#1261]
IPFS hosted website displays a broken logo when added as a favorite on Metamask Mobile.

![Screenshot_2020-01-06-11-40-02-432_io metamask](https://user-images.githubusercontent.com/20576132/71870538-4eea5400-313c-11ea-8d22-bb949708a583.jpg)

The code responsible to render a website logo is located here :

https://github.com/MetaMask/metamask-mobile/blob/develop/app/components/UI/WebsiteIcon/index.js

and more precisely the following snippet :

/**
 * Get image url from favicon api
 */
getIconUrl = url => {
	const iconUrl = `https://api.faviconkit.com/${getHost(url)}/64`;
	return iconUrl;
};

Our Dapp is hosted on IPFS through ENS :
https://bluelightav.eth and resolved to the following IPFS address:
https://gateway.ipfs.io/ipfs/QmThBQeDdiu67FRo9wUYRJsLksfTY5CcX91ArvDHMtCTPi/

The current logic cannot resolve a valid logo as the getHost(url) will always retrieve gateway.ipfs.io.

The documentation seems to be wrong:

https://metamask.github.io/metamask-docs/Best_Practices/Defining_Your_Icon

As the logic do not rely on the shortcut icon.

https://gateway.ipfs.io/ipfs/bafkreihr4i7fmbxll3yabea5xyrmezca5n7qfd3cj7xw7zkcppnr327vne

or

https://gateway.ipfs.io/ipfs/QmVFTC717mvmnyEMjdrdb62zjkBmdkZ1BqFSmaUa3mbGtF?filename=favicon.ico

are correctly rendered in browser though.

![ksnip_20200106-114132](https://user-images.githubusercontent.com/20576132/71871024-e2705480-313d-11ea-8d49-215a537233f8.png)

Thanks

**Comment by rickycodes** [comment]
Exploring this a bit further and noticing a couple of things...

#### The service (api.faviconkit.com) appears unreliable:

It responds with a 429 status often: "Too many requests", I actually got this on my first try and frequent attempts afterwards:
![image](https://user-images.githubusercontent.com/675259/72641896-2e3ead00-3939-11ea-9ff5-f96cabf081fe.png)

when it doesn't respond with 429 for this particular domain (gateway.ipfs.io) the request responds as 404 (as the original reporter mentioned):

![image](https://user-images.githubusercontent.com/675259/72642665-e91b7a80-393a-11ea-947b-993fdafc0fcf.png)

Maybe we should consider the use of a different service? I'm not familiar with any that offer similar functionality.

Pending that I think we should also have a check in the `getIconUrl` method that verifies the asset can be loaded and provides a reasonable fallback in cases where it cannot (even a 1x1px spacer.gif would be better than a broken image icon).

I actually wrote a react-component a few years ago that does exactly this: https://www.npmjs.com/package/react-load-img

broken images (especially in a mobile app context) is as a bad look!

**Comment by AlexJupiter** [comment]
Tried to check this but couldn't even add a favourite to my home screen on iOS 5.0.1.

**Comment by firnprotocol** [comment]
has there been any progress on this? i think the root cause is that `faviconkit` is unreliable. they don't seem to expose docs explaining their internal processes / debug info / how to force a refresh.

any tips?

**Comment by rd-stark** [comment]
please fix favicon with size 50, https://github.com/MetaMask/metamask-mobile/blob/a4b8ba99fd2ef0ebe0d43a02e21e5d8818ed1a5a/app/components/Views/BrowserTab/index.js#L859

**Comment by hesterbruikman** [comment]
@rd-stark can you elaborate and create a new issue on the icon size please? This seems like a separate request from the failed image loading which is described here and is indeed fixed.
