### ISSUE TITLE
[Bug]: Permissions functionality exhibits differences between the current main and the PV build

### ISSUE THREAD

**Issue by sleepytanya** [MetaMask/metamask-mobile#12619]
### Describe the bug

Permissions menu in `main` and in PV (not sure if it's expected)

![Image](https://github.com/user-attachments/assets/c8e67f3a-a201-4a1e-9aa1-384b06d9a40c)

**PancakeSwap**

`main` build 

Permissions are accurately updated when a user selects a different network in the wallet, with transactions being correctly created on the chosen network. Wallet and dApp networks icons show the selected network.

https://github.com/user-attachments/assets/964e4aba-22bc-496e-9804-114462e826d0

PV build

Transactions created on an incorrect network because the dApp continues to operate under the assumption that it is connected to the previous network until the user manually switches the network within the dApp. The wallet and dApp icons indicate different chains.

https://github.com/user-attachments/assets/9299e687-71d5-47ca-8c3b-68d822fe98c8

In both builds, **SushiSwap** and **Uniswap** exhibit similar behavior in that permissions are not updated until the user manually switches the network within the dApp. Additionally, there is a discrepancy where the wallet and dApp icons indicate different chains.

**SushiSwap**

https://github.com/user-attachments/assets/458cc7f7-b906-49ac-9369-2d5949f8766f

https://github.com/user-attachments/assets/60c6ae36-689e-4d9b-b091-34198c512cfd

**Uniswap**

https://github.com/user-attachments/assets/f43cb574-0b6f-4256-8ffe-85edcf5bf83f

https://github.com/user-attachments/assets/4fe7a620-084c-4a08-bb36-6026d83e53ef

### Expected behavior

-

### Steps to reproduce

1. Connect to a dApp
2. Switch networks

### Error messages or log output

```shell

```

### Detection stage

On the development branch

### Version

main and PV builds

### Build type

None

### Device

Samsung S24+

### Operating system

Android

**Comment by Unik0rnMaggie** [comment]
Permissions Main vs Portfolio view:

![Image](https://github.com/user-attachments/assets/9a2ceca8-8a2a-44ee-8c7e-719bb8111588)

![Image](https://github.com/user-attachments/assets/071fbdcd-fb31-4dbb-81c8-f42529f3ba19)
