### ISSUE TITLE
[Bug]: Portfolio View: BNB token name incorrect

### ISSUE THREAD

**Issue by Unik0rnMaggie** [MetaMask/metamask-mobile#12625]
### Describe the bug

The BNB token name is incorrect `BNB Smart Chain Mainnet`

### Expected behavior

See correct token name `BNB`

### Screenshots/Recordings

https://github.com/user-attachments/assets/cbb9feee-4fb1-4fb9-9665-9dfb29e23313

### Steps to reproduce

1. Switch to BNB chain or "All Networks" view
2. Notice BNB token name is incorrect: `BNB Smart Chain Mainnet` instead of `BNB`

### Error messages or log output

```shell

```

### Detection stage

In beta

### Version

v7.36.0 (1505)

### Build type

Other (please specify exactly where you obtained this build in "Additional Context" section)

### Device

Pixel 6 Pro

### Operating system

Android

### Additional context

Latest QA build for Portfolio View

**Comment by Unik0rnMaggie** [comment]
Not present in build from `main`

![Image](https://github.com/user-attachments/assets/79efa7a8-be53-4cc8-99b0-377c4302f7c5)

**Comment by sleepytanya** [comment]
Bitrise build https://app.bitrise.io/app/be69d4368ee7e86d/installable-artifacts/13eeff1e9ecca49d/public-install-page/73ac6667897d6ece66abb7aa43a7a681

Correct BNB native token:

![Image](https://github.com/user-attachments/assets/10b73cbf-4504-45db-9a2b-698fad843f8a)

**Comment by Unik0rnMaggie** [comment]
Correct BNB token name in the latest [build](https://app.bitrise.io/app/be69d4368ee7e86d/installable-artifacts/13eeff1e9ecca49d/public-install-page/73ac6667897d6ece66abb7aa43a7a681)

Issue will be closed

![Image](https://github.com/user-attachments/assets/e2b71c9f-d249-4a74-983b-d10eca79a73c)

![Image](https://github.com/user-attachments/assets/7b8b30f1-1101-4327-9617-2f5d42d0995a)
