### ISSUE TITLE
[Bug]: Portfolio View: Permissions for connecting to dapps via device browser do not include the new chain permissions feature

### ISSUE THREAD

**Issue by Unik0rnMaggie** [MetaMask/metamask-mobile#12620]
### Describe the bug

When attempting to connect to dapps via the mobile device browser, nothing happens.

### Expected behavior

Be able to connect to dapps via device browser

### Screenshots/Recordings

https://github.com/user-attachments/assets/f577ef09-a0a3-4d8b-b9f2-48ff6d98e22b

### Steps to reproduce

1. Open device browser
2. Access any dapps
3. click on the connect button from the dapp page
4. Notice the Permission request in MetaMask does not include the chain permissions new feature

### Error messages or log output

```shell

```

### Detection stage

In beta

### Version

v7.36.0 (1505)

### Build type

Other (please specify exactly where you obtained this build in "Additional Context" section)

### Device

Pixel 6 Pro

### Operating system

Android

### Additional context

Latest QA build for Portfolio View

_No response_

**Comment by Unik0rnMaggie** [comment]
Retested using the latest QA build for Portfolio view and connection is possible. 

The permissions do not include the new chain permissions feature, similar to [this](https://github.com/MetaMask/metamask-mobile/issues/12619) issue.

Changing name and description of the issue to reflect current testing:

https://github.com/user-attachments/assets/64dc713c-8174-4213-ba08-16f421e03ae1

**Comment by sleepytanya** [comment]
Bitrise build https://app.bitrise.io/app/be69d4368ee7e86d/installable-artifacts/13eeff1e9ecca49d/public-install-page/73ac6667897d6ece66abb7aa43a7a681

External browser dApp connection:

https://github.com/user-attachments/assets/2d2458ed-1032-4dc9-97a3-768e8e1905b9
