### ISSUE TITLE
[Bug]: Metamask Crash When Using Biquid Dapp

### ISSUE THREAD

**Issue by pilab-gwon** [MetaMask/metamask-mobile#12634]
### Describe the bug

I encountered a crash issue while using Metamask with the [Biquid Dapp](https://biquid.io/).

### Expected behavior

Metamask should complete the action without crashing or closing.

### Screenshots/Recordings

https://github.com/user-attachments/assets/162dc6e9-740a-4a25-8896-37de7e6bb71a

### Steps to reproduce

1. Open Metamask App (iOS)
2. Use in-app browser go to [biquid](https://biquid.io/)
3. Go to [Stake page](https://biquid.io/staking) on biquid
4. Perform input 400000 ~ 500000 BFC and click Stake button
5. Confirm > Confirm and encountered a crash issue

### Error messages or log output

```shell

```

### Detection stage

In production (default)

### Version

v7.37.0

### Build type

None

### Device

iPhone 15 Pro Max

### Operating system

iOS

**Comment by DanielTech21** [comment]
Hi @pilab-gwon 

Thank you for bringing this to our attention.

Our team will look into this and let you know the next steps.

**Comment by joaoloureirop** [comment]
related to #10998 

Should be fixed by https://github.com/MetaMask/metamask-mobile/pull/11952

**Comment by sethkfman** [comment]
Completed for release 7.38.0 in early Jan
