### ISSUE TITLE
[Bug]: Proposed Approval limit for swaps on Confirmation screen

### ISSUE THREAD

**Issue by sleepytanya** [MetaMask/metamask-mobile#12681]
### Describe the bug

Spend limits requested by Swaps are the same across all Popular networks

### Expected behavior

-

### Screenshots/Recordings

<img width="882" alt="Image" src="https://github.com/user-attachments/assets/17d07950-3649-438d-aac7-8446c1f9cde2" />

### Steps to reproduce

1. Start swap for token that requires Approval

### Error messages or log output

```shell

```

### Detection stage

During release testing

### Version

7.37.0

### Build type

None

### Device

iPhone 15, Samsung S24+

### Operating system

iOS, Android

**Comment by bschorchit** [comment]
I believe this is the max amount for a spending cap. I see dapps requiring this same value as well. I do believe this is expected, @sleepytanya
