### ISSUE TITLE
Changing network to ropsten doesn't work 

### ISSUE THREAD

**Issue by admazzola** [MetaMask/metamask-mobile#1271]
Changing network to ropsten doesn't change the chainID to 0x3 on a dapp backend from what I can tell.  Test case is http://senderc.com

**Comment by estebanmino** [comment]
Hi @admazzola thanks for reporting. Just fixed a related issue with  https://github.com/MetaMask/metamask-mobile/pull/1275 please let us know if this still happening for you once we release again.
