### ISSUE TITLE
A problem occurred starting process 'command 'secret-tool''

### ISSUE THREAD

**Issue by admazzola** [MetaMask/metamask-mobile#1272]
Installed Android SDK on Linux with OpenJDK8, ran a virtual phone with V28, cloned this project, all tests pass.

Then I run 'yarn start:android' and get the following result: 

yarn run v1.3.2
$ ./scripts/build.sh android debug

-------------------------------------------

  🚀 BUILDING ANDROID IN DEBUG MODE 

-------------------------------------------

* daemon not running; starting now at tcp:5037
* daemon started successfully
info JS server already running.
info Building and installing the app on the device (cd android && ./gradlew app:installDebug)...

> Configure project :@react-native-community_async-storage
WARNING: The option setting 'android.disableResourceValidation=true' is experimental and unsupported.
The current default is 'false'.

> Configure project :@react-native-community_netinfo
WARNING: The option setting 'android.disableResourceValidation=true' is experimental and unsupported.
The current default is 'false'.

> Configure project :app
WARNING: The option setting 'android.disableResourceValidation=true' is experimental and unsupported.
The current default is 'false'.

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred evaluating project ':app'.
> A problem occurred starting process 'command 'secret-tool''

Please help.

**Comment by admazzola** [comment]
EDIT:

I solved this by running: 

sudo apt install libsecret-tools

**Comment by MarthoxGT** [comment]
Thanks a lot @apexmfer you just saved me hours of searching the internet 💖
