### ISSUE TITLE
[Bug]: Switching networks is unresponsive

### ISSUE THREAD

**Issue by Unik0rnMaggie** [MetaMask/metamask-mobile#12726]
### Describe the bug

Unable to switch networks to Base, Polygon, Avalanche, Arbitrum, OP Mainnet

The toast message appears that the network is active, but the network screen does not disappear

### Expected behavior

Be able to switch networks

### Screenshots/Recordings

https://github.com/user-attachments/assets/e953d35c-7bbd-4e1d-9bd8-94c4caa602ac

### Steps to reproduce

1. Try to switch networks to any of the following: Base, Polygon, Avax, Arbitrum, OP Mainnet

### Error messages or log output

```shell

```

### Detection stage

During release testing

### Version

7.38.0

### Build type

Other (please specify exactly where you obtained this build in "Additional Context" section)

### Device

Pixel 6 Pro

### Operating system

Android

### Additional context

I obtained the build from [here](https://app.bitrise.io/app/be69d4368ee7e86d/installable-artifacts/85ba5e0e8319c808/public-install-page/f569a89af0111bece1dff683e9a9d8fb)

**Comment by Unik0rnMaggie** [comment]
Infura key issue. 

Issue fixed and closed.

**Comment by darkwing** [comment]
## Impact

## Root cause

### Related to change?

## Lessons learned

## Corrective actions
