### ISSUE TITLE
provider.chainId is invalid hex number

### ISSUE THREAD

**Issue by Velenir** [MetaMask/metamask-mobile#1274]
`chainId` property on `provider | window.web3 | window.ethereum` returns an incorrect non-hex string, at least on Android 7.

For example `"Ox1"` for mainnet instead of `"0x1"`, that's letter "O" in there. Provider injected by desktop browser extension has correct `chainId`

**Comment by estebanmino** [comment]
Hi @Velenir  thanks for reporting.

**Comment by jishankai** [comment]
Hi. I'm a dapp developer. I got undefined when I was trying to get ```chainId``` by using ```window.web3.currentProvider.chainId or window.ethereum.chainId``` on MetaMask Mobile. It works well on Chrome.

How could I fix this?
