### ISSUE TITLE
[Bug]:  Swap button hidden for non current network

### ISSUE THREAD

**Issue by salimtb** [MetaMask/metamask-mobile#12757]
### Describe the bug

The "Swap" button does not appear for tokens that are not on the currently selected network, even when swaps are supported for that token on the network it belongs to. This creates confusion for users expecting the swap functionality to be available for any supported token.

### Screenshots/Recordings

https://github.com/user-attachments/assets/822407e7-191d-47e0-b5f1-f96c31a84c74

### Steps to reproduce

1. do a fresh install app
2. select popular network
3. go to any token and try to swap from token detail page

### Error messages or log output

```shell

```

### Detection stage

In production (default)

### Version

7.38.0

### Build type

None

### Device

Pixel 7, iphone 14

### Operating system

iOS, Android

**Comment by sleepytanya** [comment]
Related: https://github.com/MetaMask/metamask-mobile/issues/12678

**Comment by darkwing** [comment]
## Impact

## Root cause

### Related to change?

## Lessons learned

## Corrective actions
