### ISSUE TITLE
window.location.reload() doesn't work

### ISSUE THREAD

**Issue by jrainville** [MetaMask/metamask-mobile#1288]
On MetaMask mobile x0.2.13 (26) on Android, using `window.location.reload()` or `window.location.href = window.location.href;` don't do anything.

Obviously, the wanted behaviour would be for the Dapp to reload. 

Reloading using the button in the menu works though.

I tested with both my Dapp code which is: https://github.com/status-im/status-teller-network/blob/master/src/js/pages/Settings/index.js#L14
I also tested using the Chromium Remote device Console and entering the commands in the console don't do anything. I tested in another mobile browser and they worked to reload.

**Comment by Velenir** [comment]
I just made a sandbox for an unrelated issue where I also have reload functionality (with `location.reload()`) and it works as expected.
https://codesandbox.io/s/web3-provider-subscriptions-test-755o9
open https://755o9.csb.app/ in Metamask to try

You can also try `window.location.reload(true)` to skip browser cache, maybe that will help.

**Comment by jrainville** [comment]
Thanks for the sandbox. I tired it and it indeed worked. I guess my Dapp has something blocking the refresh from working. I'll try to figure it out.
Thnaks again
