### ISSUE TITLE
Get App Store listing ready for v1

### ISSUE THREAD

**Issue by brunobar79** [MetaMask/metamask-mobile#1290]
You're gonna need description, icons, screenshots, etc.

CC: @omnat  @cjeria

**Comment by omnat** [comment]
Thanks for this issue! 

We'll plan it when closer to v1 launch and getting the App store ready. Reference video by Bruno: https://consensys.zoom.us/rec/share/tN1oIrDMxFNOEqv92W3SULwzRqfZT6a81SVLq6ANmkoUYKw2YApvm1ejHJj_pHrm
