### ISSUE TITLE
MetaMask(Android) blocks requests to AlchemyAPI

### ISSUE THREAD

**Issue by mqklin** [MetaMask/metamask-mobile#1292]
Here is the proof: [staging.zerion.io](staging.zerion.io)
I use this `index.html` (you can inspect it in the devtools):

```
<!doctype html>
<html>
<head></head>
<body>
  <script>
    const get = async (name, url) => {
      alert(`fetch ${name}`);
      const body = {
        jsonrpc: "2.0",
        id: 0,
        method: "net_version",
        params: []
      };
      return await fetch(
        url,
        {
          method: 'post',
          body: JSON.stringify(body)
        }
      ).then(function(response) {
        return response.json();
      }).then(function(data) {
        alert(`result ${name}: ${JSON.stringify(data)}`);
      }).catch(e => alert(e));
    }
    (async () => {
      try {
        await get('infura', 'https://mainnet.infura.io/v3/7476d55054eb427dbd1f21f314d0b3b8');
        await get('alchemy', 'https://eth-mainnet.alchemyapi.io/jsonrpc/R6mZwt31pb4DdV4cAriiPoxHYJhKcKVa');
      }
      catch (e) {
        alert(e);
      }
    })();
  </script>
</body>
</html>
```

If you open this in browser, it will alert for Infura and for Alchemy.
But if you open it in MetaMask(Android), it will respond only for Infura, but for Alchemy it will throw `TypeError: Failed to fetch`.

**Comment by brunobar79** [comment]
For the record, We are not doing anything specific to block alchemy.  This works fine in iOS https://recordit.co/uFWn7sEBW9 and the reason that I believe having a different behavior is because both apps use a different JS engine (JSC vs v8).

I'll take a look because the syntax looks ok to me.

**Comment by brunobar79** [comment]
This looks like an issue on the alchemy side: 

![Screen Shot 2020-01-23 at 1 02 32 PM](https://user-images.githubusercontent.com/1247834/73010579-a9dca600-3de0-11ea-863f-50eedc220662.png)

**Comment by brunobar79** [comment]
By comparing response headers on both requests:

Infura sets the header `Access-Control-Allow-Origin`  in the response with the value `https://staging.zerio.io`

![Screen Shot 2020-01-23 at 2 04 56 PM](https://user-images.githubusercontent.com/1247834/73015218-9da91680-3de9-11ea-9bdf-b68b90e4304b.png)

Alchemy sets the header `Access-Control-Allow-Origin`  in the response with the value `*` which looks like this JS engine doesn't like it.

![Screen Shot 2020-01-23 at 2 05 13 PM](https://user-images.githubusercontent.com/1247834/73015219-9da91680-3de9-11ea-8f43-3bbf6f19c347.png)

There's no much we can do on our end so I suggest you to report that issue to Alchemy.

**Comment by mqklin** [comment]
@brunobar79 oh, couldn't imagine that the problem is because of engines! Thanks a lot for the investigation! I've already reported it to Alchemy.

**Comment by dphilipson** [comment]
Hi @mqklin, Alchemy dev here. I've just updated our servers to send back your own origin in the access-control-allow-origin header which matches the behavior of Infura. Can you try again?

**Comment by mqklin** [comment]
@dphilipson hey David :) It's still there. But this time the header looks the same. 
@brunobar79 could you please say how have you managed to run MetaMask(Android) in the browser? So I can debug it?

**Comment by brunobar79** [comment]
@mqklin  https://github.com/MetaMask/metamask-mobile/issues/1226

**Comment by mikealchemy** [comment]
@brunobar79 do you have any suggestions for what the underlying cause is now that the Access-Control headers returned by Alchemy and Infura are the same?
