### ISSUE TITLE
PoolTogether doesn't work

### ISSUE THREAD

**Issue by brunobar79** [MetaMask/metamask-mobile#1299]
Doesn’t detect the wallet.

**Comment by rekmarks** [comment]
Testing the app today, their website makes a lot of noise that isn't our fault in the console. They're definitely interacting with our provider object, but do not list MetaMask as one of their supported wallets. They do list WalletConnect, and that's what I'm trying next.

Interestingly, they list Coinbase Wallet, even though IIRC its browser functionality was removed from their mobile app?

![image](https://user-images.githubusercontent.com/25517051/74257952-6623e080-4caa-11ea-9a72-f99ff36f4fb6.png)

![image](https://user-images.githubusercontent.com/25517051/74257980-6f14b200-4caa-11ea-97e7-6b7339792812.png)

**Comment by rekmarks** [comment]
PoolTogether does not support MetaMask, and I'm not going to reach out and ask them to do so until we've shipped the new inpage provider API (i.e., started the deprecation period).

**Comment by omnat** [comment]
A report from user, it might help in this issue.

> While browsing on the PoolToogether website it get freezed, the "home" button wasn't able to move from the error page.
> Only closing this tab fix it.
> 
> As the MetaMask wallet get undetected many time, sometimes closing the App and trying again or closing the tab and select again from the favorites list make your App finally detect MetaMask wallet, this time i selected "Install or Open Trust" to later revert back hoping finally  getting MetaMask wallet detected and that is when i got this error, bug.

![Screenshot_2020-02-21-21-30-12-251_io metamask](https://user-images.githubusercontent.com/44038140/75074150-ee2a9700-54af-11ea-9596-eedd3db983db.jpg)
![Screenshot_2020-02-21-21-30-31-834_io metamask](https://user-images.githubusercontent.com/44038140/75074159-f08cf100-54af-11ea-8a7c-e14c9ab4fcfe.jpg)

**Comment by rekmarks** [comment]
staging.pooltogether.com now works great; app.pooltogether.com is currently not loading on mobile (iOS). Working with PoolTogether to get it resolved.

**Comment by rekmarks** [comment]
The update has been pushed to production!
