### ISSUE TITLE
Rejection on mobile doesn't follow the same standard as extension

### ISSUE THREAD

**Issue by benjlevesque** [MetaMask/metamask-mobile#1314]
Using the chrome extension, when a user Rejects a transaction, the following error will be thrown:

```json
{
  "code": 4001,
  "message": "MetaMask Tx Signature: User denied transaction signature."
}
```

On mobile, when the user Rejects a transaction, the error thrown is an empty object. 

Related EIP: [EIP-1193](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-1193.md#error-object-and-codes)

**Comment by omnat** [comment]
@rickycodes to work with @whymarrh to do a release on gaba to remove dependency for this

**Comment by rickycodes** [comment]
@benjlevesque this should be resolved in the latest release, are you able to confirm?

**Comment by rickycodes** [comment]
![image](https://user-images.githubusercontent.com/675259/76788657-b69eca00-6791-11ea-8a72-8f0a67b6b7e5.png)

this looks like it's working as expect, so I am going to close this for now
