### ISSUE TITLE
Can't connect with Metamask when adding an account as guardian for Argent account

### ISSUE THREAD

**Issue by omnat** [MetaMask/metamask-mobile#1316]
(from support)

### When adding an account as guardian for Argent account

> Metamask doesn't seem to work with Argent on my Xiaomi Redmi Note 4 with Android 7.0:
> https://security.argent.xyz/add-guardian-metamask
> As a side note, a workaround to access https://security.argent.xyz/add-guardian-metamask is to choose an other account then revert back to our selected account, so it seem like a bug in your Android application to me

<img src="https://user-images.githubusercontent.com/44038140/73683634-78cd6280-4677-11ea-9a8b-5e982e9c2063.jpg" width="230" height="400">

### Design note for browser 
Overlay covers top and lower part of the page. 
> "Overlay without any possibility to see or access all the page as upper and lower part are overlayed:

<img src="https://user-images.githubusercontent.com/44038140/73683913-fd1fe580-4677-11ea-8cb1-faaba5f7c242.jpg" width="230" height="400">

### Mobile details
@ibrahimtaveras00 This is from user who reported this bug, but I had the same issue when I tried adding Argent guardian on my OnePlus
<img src="https://user-images.githubusercontent.com/44038140/73684024-38baaf80-4678-11ea-8d80-b288822f9d3a.jpg" width="230" height="400">

**Comment by ibrahimtaveras00** [comment]
Seems to still be happening on 0.2.18

**Comment by omnat** [comment]
@dpazdan has this issue been seen from support lately? Else we close
