### ISSUE TITLE
Fingerprint not identified often

### ISSUE THREAD

**Issue by omnat** [MetaMask/metamask-mobile#1318]
### Problem

Sign in / Unlock with fingerprint is enabled, but fingerprint isn't recognized very often (not always) when I open Metamask. 

## Details
- Fingerprint is always recognized when unlocking mobile, and other apps (incl. Argent)
- After 3 times trying, you are asked to enter password - which is fine logic for a security mechanism. I end up entering wrong password, and this adds onto my frustration.

## Data
I wondered - maybe this just happening with me, but then **we have unusually high number of 'Incorrect password' errors in analytics** - this is an event that gets triggered when a user enter manually a wrong password. Now, this includes people who don't opt-in for 'Sign in with fingerprint'. And majority events are from Android (also majority users from Android)

But considering ~10k events in last month **total**, and ~2k **unique**, that's on an average 5 times in a month for same reason. I am speculating this is a more widespread issue than just me.

![image](https://user-images.githubusercontent.com/44038140/73691947-3b250580-4688-11ea-93b7-22ea8dc01c72.png)

@ibrahimtaveras00 have you noticed this before?

**Comment by TomAFrench** [comment]
I have also been experiencing this often over the past couple days.

**Comment by omnat** [comment]
Support team reported they didn't see any reports on this issue.
cc @dpazdan

**Comment by dpazdan** [comment]
I was able to find one user that reported experiencing issues with fingerprint: support ticket 25994

**Comment by TomAFrench** [comment]
This issue has since stopped for me, at least for the past couple of days.

**Comment by omnat** [comment]
solved with keychain update and design update
