### ISSUE TITLE
Browser web pages showing blank screen

### ISSUE THREAD

**Issue by cjeria** [MetaMask/metamask-mobile#1319]
Tabbed web pages that have been previously created are displaying in a blank screen. Pages only load when retyping URL in the address bar (refreshing the page from the bottom "•••" doesn't work either). 

We might want to also consider adding pull-to-refresh to reload web pages.

<img src="https://user-images.githubusercontent.com/597770/73696403-13866b00-4691-11ea-96e3-ec38490731d0.png" alt="drawing" width="200"/>

**Comment by dpazdan** [comment]
It looks like this happens when the app auto-locks or the user logs out of MetaMask, then logs back in with tabs existing from a previous session

**Comment by estebanmino** [comment]
I can repro this coming back after I closed the app

**Comment by mightypenguin** [comment]
"me too"
Seeing this for kyberswap and compound.finance after coming back to tabs after leaving app.
Refresh/reload button for the tab does nothing.
