### ISSUE TITLE
App crashed when too many digits inserted in the amount screen

### ISSUE THREAD

**Issue by cjeria** [MetaMask/metamask-mobile#1320]
In the send flow, if you input more than 6 digits in the amount field, it crashes the app. See video below:

https://www.dropbox.com/s/6cuexosadkjnhnh/RPReplay_Final1580769612.MP4?dl=0

**Comment by ibrahimtaveras00** [comment]
This may help with debugging: 

![image](https://user-images.githubusercontent.com/41752922/73697870-acc37a80-46ad-11ea-9140-d597c4e88dae.png)
