### ISSUE TITLE
Migrate away from Fabric Crashlytics

### ISSUE THREAD

**Issue by Gudahtt** [MetaMask/metamask-mobile#1321]
The Fabric Crashlytics platform is shutting down on March 31st, as it has been replaced by/migrated to Firebase Crashlytics. We need to migrate to some other service for crash reporting (e.g. Firebase Crashlytics, Sentry, etc.)

**Comment by brat69** [comment]
Hi, I’m a newbie here and i need some help how to post or how this network woks I’m confused with this platform...
