### ISSUE TITLE
Get all CDP accounts from Metamask mobile

### ISSUE THREAD

**Issue by KevalS** [MetaMask/metamask-mobile#1324]
I am calling getCdpsAsc function using web3 wrapper to fetch all CDP accounts associated with my address but its returning empty array. To confirm if there is any issue with my code i checked with other web3 providers and on there i am able to retrieve my open CDP accounts. This is working on metamask desktop version, mobile trust wallet, mobile token pocket but not working on metamask mobile version.

Address of Contract where getCdpsAsc function is 0x592301a23d37c591c5856f28726af820af8e7014
Below is the piece of code used for fetching CDP accounts:

`public getCdpsAsc = {
        async callAsync(
            manager: string,
            guy: string,
            callData: Partial<CallData> = {},
            defaultBlock?: BlockParam,
        ): Promise<[BigNumber[], string[], string[]]
        > {
            const self = this as any as GetCdpsContract;
            const encodedData = self._strictEncodeArguments('getCdpsAsc(address,address)', [manager,
        guy
        ]);
            const callDataWithDefaults = await BaseContract._applyDefaultsToTxDataAsync(
                {
                    to: self.address,
                    ...callData,
                    data: encodedData,
                },
                self._web3Wrapper.getContractDefaults(),
            );
            const rawCallResult = await self._web3Wrapper.callAsync(callDataWithDefaults, defaultBlock);
            BaseContract._throwIfRevertWithReasonCallResult(rawCallResult);
            const abiEncoder = self._lookupAbiEncoder('getCdpsAsc(address,address)');
            // tslint:disable boolean-naming
            const result = abiEncoder.strictDecodeReturnValue<[BigNumber[], string[], string[]]
        >(rawCallResult);
            // tslint:enable boolean-naming
            return result;
        },
    };`

**Comment by gantunesr** [comment]
Hey @KevalS, is this still an issue for you?

**Comment by cortisiko** [comment]
this issue has not have any traction in over a year. Closing it now. Feel free to reopen if the issue still persists.
