### ISSUE TITLE
Design QA

### ISSUE THREAD

**Issue by omnat** [MetaMask/metamask-mobile#1330]
- [ ] Send flow (after merging #1327)
- [x] Approve updates

**Comment by cjeria** [comment]
Approve screen design feedback in this figma file https://www.figma.com/file/8I4cV19n2S5DsVq7Mj9Eva/Approve-Screens-v1?node-id=0%3A1

**Comment by omnat** [comment]
@danjm to pick the padding updates to get it ready for release

**Comment by rickycodes** [comment]
This work was completed in #1455
