### ISSUE TITLE
View my transaction history

### ISSUE THREAD

**Issue by omnat** [MetaMask/metamask-mobile#1353]
- Improve transaction history for better communication of what transaction happened, when, with who
- Clear distinction of incoming & outgoing transactions

**Comment by cjeria** [comment]
In-progress Figma designs [here](https://www.figma.com/file/QRyJiqEFeSDk4ZUidHdB21/1353-View-my-transaction-history?node-id=0%3A1)

**Comment by ibrahimtaveras00** [comment]
Was this completed in our tx notifications update PR?
