### ISSUE TITLE
networkVersion vs. chainId? 

### ISSUE THREAD

**Issue by jmahhh** [MetaMask/metamask-mobile#1375]
Hi, according to the docs `networkVersion` will be deprecated but it's not clear to me what I'm supposed to replace it with. `chainId` is only mentioned in the context of network changes, not checking for a network in the first place. Is this the new preferred approach? 

We currently use `networkVersion` on desktop without issues, but when I try with the mobile wallet apparently the value returned from `networkVersion` is not equal to `1` causing an error, which is how I ended up here.

**Comment by rekmarks** [comment]
Hi @jmahhh, I apologize it took us such a long time to get back to you. `networkVersion` isn't going anywhere, although it is true that we prefer the `chainId`. I recommend familiarizing yourself with the following resources:
- https://eips.ethereum.org/EIPS/eip-155
- https://eips.ethereum.org/EIPS/eip-695
- https://chainid.network

In essence, the EIP-155 chain ID is what's actually used for transaction replay protection in Ethereum, and the only reason this didn't cause backwards compatibility issues is that the network ID and chain ID are the same for Ethereum Mainnet and all of the common/standard test networks.

Whatever the case, the chain ID should always be preferred. Keep in mind that it's always given by MetaMask APIs as a `0x`-prefixed hexadecimal string.

I just tested `net_version` with the latest version of MetaMask Mobile, and it correctly returns the string `1`. That being the case, I'm going to close this issue.
