### ISSUE TITLE
Android start up time - optimize this, make it faster

### ISSUE THREAD

**Issue by omnat** [MetaMask/metamask-mobile#1382]
Android vitals:
![image](https://user-images.githubusercontent.com/44038140/74995810-c4696580-5406-11ea-82c8-8db9637ab996.png)

Restarting the app on Android takes a long time on loading animation. We should definitely optimize this.

**Comment by ibrahimtaveras00** [comment]
![Screen Shot 2020-06-18 at 12 45 50 AM](https://user-images.githubusercontent.com/41752922/84979284-155f4100-b0fd-11ea-9961-71f47f514afa.png)

a tad bit better but not major
