### ISSUE TITLE
recover my account.....

### ISSUE THREAD

**Issue by garyvalenzuela** [MetaMask/metamask-mobile#1388]
pls. help me to recover  my account..

**Comment by danfinlay** [comment]
We use Github to track known problems, so you'll want to email our support team at support@metamask.io .

To help us diagnose your issue, you can download your "state logs" by [following this guide](https://metamask.zendesk.com/hc/en-us/articles/360015290092-How-To-Get-Logs-And-Help-MetaMask-Support-and-Diagnose-Your-Issue), and include them with a description of your problem.
