### ISSUE TITLE
How is the inpage.js injected before page load execution?

### ISSUE THREAD

**Issue by Keref** [MetaMask/metamask-mobile#1391]
HI, I'm trying to understand how Metamask works, I see that in a webpage displayed in a WebView in app/components/Views/BrowserTab/index.js, the js code is first loaded from a local asset then injected via injectedJavaScript={entryScriptWeb3}, which sets the window.ethereum var, and some middleware that intercepts postMessage.

What I don't understand is that injectedJavascript is supposed to be run after page is loaded, so the page code should have already run at that point, a the call to window.ethereum would have returned undefined. The Chrome plugin uses content script, so the window.ethereum and the middleware are set in the DOM before the page is loaded, but here how is it achieved? Does the useWebkit option have an impact on this?

**Comment by omnat** [comment]
Related #1975
