### ISSUE TITLE
Waiting indefinitely for Contract Method to return

### ISSUE THREAD

**Issue by georgk10** [MetaMask/metamask-mobile#1392]
I'm currently developing a Dapp which requires me to interact with a smart contract (of course).
When a user send a transaction to the contract, a javascript function is called which starts a loading screen until the transaction is completed. This is accomplished by just doing:
`await contract.methods.sample_method(args).send(options);`
After the function return the loading screen is closed and the user gets a notification. This whole procedure works perfectly fine with the metamask browser extension, but in the mobile app the function seems to never return, which leads to the loading screen showing up forever, even if a transaction is confirmed.

I'm using a Huawei P30 Lite with android 10 as well as metamask-mobile 0.2.13

**Comment by Velenir** [comment]
#1297 is likely the cause of it, as web3, as far as I know, relies on `newBlockHeaders` subscription to resolve transaction promises

**Comment by georgk10** [comment]
Thanks for the quick response. 
Do you know whether there is any fix or quick workaround atm?

**Comment by Velenir** [comment]
No fix afaik

What you could potentially do is check on the transaction status periodically
Something like:

```js
return new Promise((resolve, reject) => {
  contract.methods.sample_method(args).send(options).on('transactionHash', hash => {
    const interval = setInterval(async () => {
      const txReceipt = await web3.eth.getTransactionReceipt(hash)
      if (txReceipt === null) return // tx still pending
      
      clearInterval(interval)

      if (txReceipt.status) resolve(txReceipt) // tx mined
      else reject(txReceipt)  // tx reverted
    }, 8000) // whatever the average block time is
  }).on('error', (error, receipt) => reject(receipt || error))
  // depending on error type receipt is one of rejected tx or undefined
})
```

Not sure if this will even work. Please report back if you try it out.

**Comment by georgk10** [comment]
Hi, thanks for your hint. I got it working now. Modified your example a bit, but it's almost just copy & paste your code.

This is working perfectly fine for me:
`await contract.methods.sample_method(args).send(options).on('transactionHash', hash => {
                    const interval = setInterval(async () => {
                        const txReceipt = await web3.eth.getTransactionReceipt(hash)
                        if (txReceipt === null){
                            return // tx still pending
                        } else {
                            // remove loading screen here  
                            clearInterval(interval); 
                        }
                    }, 2000);
                });
`
