### ISSUE TITLE
Clearing GWEI value when creating a token throws an error

### ISSUE THREAD

**Issue by rickycodes** [MetaMask/metamask-mobile#1393]
When modifying GWEI value here:

![image](https://user-images.githubusercontent.com/675259/75710503-af0bfb00-5c92-11ea-8355-c856b3c2bd03.png)

clearing the value results in (debug only):

![image](https://user-images.githubusercontent.com/675259/75710635-e8446b00-5c92-11ea-8ea5-46c9f194bb17.png)

**Comment by danjm** [comment]
This appears to have been resolved with the recent redesigns on this screen

**Comment by andrepimenta** [comment]
> This appears to have been resolved with the recent redesigns on this screen

<img width="400" alt="Screenshot 2020-04-02 at 16 04 16" src="https://user-images.githubusercontent.com/4960833/78265967-0ead2e80-74fd-11ea-94c1-2828c84e6767.png">
