### ISSUE TITLE
Token list icons cropped

### ISSUE THREAD

**Issue by cjeria** [MetaMask/metamask-mobile#1407]
The icon container seems to be cropping the above and below areas of the token image. This list is accessible from the send flow when switching the token to send. 

<img src="https://user-images.githubusercontent.com/597770/76250183-2efa0e00-621b-11ea-995e-9dba074acab7.png" width="300" />

**Comment by Bunge07** [comment]
> The icon container seems to be cropping the above and below areas of the token image. This list is accessible from the send flow when switching the token to send.
> 
> <img alt="" width="300" src="https://user-images.githubusercontent.com/597770/76250183-2efa0e00-621b-11ea-995e-9dba074acab7.png">
