### ISSUE TITLE
Enable back button if going from dapp to home

### ISSUE THREAD

**Issue by cjeria** [MetaMask/metamask-mobile#1408]
If I'm on a dapp and I tap the home button, I am unable to go back to the dapp I was previously on. Let's enable the back button if the user was previously on a dapp.

**Comment by danjm** [comment]
see Trello for design

**Comment by andrepimenta** [comment]
Found other issues with the navigation while fixing this issue.

Going back from a dapp and then trying to go forward, it takes you back to home. Also, The back button is available but it does not do anything:
![ezgif-5-f736dbf3e010](https://user-images.githubusercontent.com/4960833/78268085-a01da000-74ff-11ea-8ce4-28902db1b723.gif)

Inside the dapp, there seems to be other issues as well, for example, back button only works after 3 attempts (could be a problem with the dapp itself, but it seems to happen with others as well):
![ezgif-5-f736dbf3e010](https://user-images.githubusercontent.com/4960833/78268596-508ba400-7500-11ea-93f9-aa55ff8708f0.gif)
