### ISSUE TITLE
Update transaction indicator

### ISSUE THREAD

**Issue by cjeria** [MetaMask/metamask-mobile#1414]
Two usability issues have come up with regards to the transaction status indicator.

### **Issue 1** 
After submitting a transaction, a status indicator appears at the bottom of the screen. If tapped, the full transaction history view is loaded moving the user away from the context the user was previously on which could be a dapp where they might be in the middle of a flow.

**Solution**: Instead of moving the user away from the context if they tap on the tx status indicator, we could instead use a **modal** to show the transaction status which keeps the user in-context and prevents them from having to navigate back to the browser.

### **Issue 2** 
The transaction indicator is not dismissable and overlaps important controls like the browsers nav bar that the user might want to access while waiting for the transaction to be processed (see screenshot below).

**Solution**: make the tx status indicator dismissible with and float above the navigation bar when in the browser

<img src="https://user-images.githubusercontent.com/597770/76356752-d85d0480-62ec-11ea-9cba-217e230f7d6a.png" width="340" />

**Comment by cjeria** [comment]
The suggested solution for the notification banner (issue 2)

![image](https://user-images.githubusercontent.com/597770/76358900-a77ece80-62f0-11ea-98a1-6a8f756d07bc.png)

**Comment by mightypenguin** [comment]
Using compound.finance or kyberswap is super annoying because of this UI overlay currently.
Especially if you want to queue multiple pending transactions at the same time.
