### ISSUE TITLE
Tapping on transaction submitted notification returns an Oops notification 

### ISSUE THREAD

**Issue by ibrahimtaveras00** [MetaMask/metamask-mobile#1421]
This does not happen to every single transaction, so it is inconsistent but I may have found a way to get it to happen more frequently:
- either use your own request link or you can use mine (for Rinkeby) 
<img width="419" alt="Screen Shot 2020-03-09 at 3 01 36 PM" src="https://user-images.githubusercontent.com/41752922/76474585-927a6c00-63d2-11ea-8147-e6988dea8a62.png">

- if using your own in the app, simply go to burger menu > Receive > Request > enter in your amount > and then tap QR code and scan it, or send yourself the link
- in my example, upon scanning the QR code, I then get sent to the old send screen, where I continue
- complete the transaction
- now tap on the notification that says "Transaction submitted" 
- notice how it sends you to transaction history with an oops, something went wrong notification?

![Screen Shot 2020-03-11 at 7 56 14 PM](https://user-images.githubusercontent.com/41752922/76474544-6fe85300-63d2-11ea-9642-52e44e7b371c.png)

Flow seen here = https://recordit.co/m4qJzlpA1Q

**Comment by omnat** [comment]
I couldn't replicate this @ibrahimtaveras00 
Tried your QR code and my own. Both worked. Is this error still happening for you?

**Comment by ibrahimtaveras00** [comment]
Just tried again today and was able to reproduce it on the first try on the Google Pixel 3 XL 

Seen here = https://recordit.co/Q8SrbBoEQ7

**Comment by omnat** [comment]
Hmm, just tried it again, and could replicate

**Comment by ibrahimtaveras00** [comment]
I could no longer replicate this issue
