### ISSUE TITLE
"Attributions" shows and an "Whoops,..." screen

### ISSUE THREAD

**Issue by rickycodes** [MetaMask/metamask-mobile#1424]
**Describe the bug**
When navigating to "Attributions" on the about page I encounter the following error screen:

**Screenshots**
<img width='400' src='https://user-images.githubusercontent.com/675259/76775026-25bcf400-677b-11ea-9612-f3c686248813.png' />

**To Reproduce**
_Steps to reproduce the behavior_
1. Go to Settings
2. Click on "About MetaMask"
3. Click on "Attributions"

**Expected behavior**
Not sure what the original intention was, but we shouldn't see this error

**Comment by cjeria** [comment]
This is now fixed by adding an [attributes](https://metamask.io/attributions.html) page to the new website
