### ISSUE TITLE
Error when sending ETC using custom RPC

### ISSUE THREAD

**Issue by fxfrnk** [MetaMask/metamask-mobile#1429]
**Describe the bug**
While connected to the ETC mainnet, it's possible to view your balance of ETC but sending a transaction results in an obscure error (Error: Object object).  

Connecting to the same endpoint on the Metamask extension results in the transaction being sent with no error

**To Reproduce**
_Steps to reproduce the behavior_
1. Connect to mainnet using the following Network settings
   Network Name: (can be anything)
   RPC URL: https://www.ethercluster.com/etc
   Chain ID: 61

2. Using an account with an ETC balance, click Send in the menu
3. Add the a TO address and hit next
4. Enter the value of ETC you want to send and hit next
5. Hit Send

**Expected behavior**
_A clear and concise description of what you expected to happen_
The transaction is submitted and returns a valid tx hash

**Smartphone (please complete the following information):**
 - Device: iPhone Xs
 - OS: iOS 13.3.1
 - MetaMask Mobile Version 0.2.14 (389)

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by omnat** [comment]
@fxfrnk is this issue still happening for you? And could you please share a screenshot of the error if yes.
