### ISSUE TITLE
Problem when trying to install "Yarn install"

### ISSUE THREAD

**Issue by alexiicon** [MetaMask/metamask-mobile#1430]
Hi!
Here what's going on when i run yarn install:  output
metamask-mobile>yarn install
yarn install v1.22.4
[1/4] Resolving packages...
[2/4] Fetching packages...
error Command failed.
Exit code: 128
Command: git
Arguments: ls-remote --tags --heads ssh://git@github.com/MetaMask/lottie-react-native.git
Directory: c:\EtherDB\metamask-mobile
Output:
Host key verification failed.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

c:\EtherDB\metamask-mobile>git ls-remote --tags --heads ssh://git@github.com/MetaMask/lottie-react-native.git
The authenticity of host 'github.com (140.82.118.3)' can't be established.
RSA key fingerprint is SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added 'github.com,140.82.118.3' (RSA) to the list of known hosts.
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

c:\EtherDB\metamask-mobile>

**Comment by idcuesta** [comment]
I have just randomly arrived here when searching for GitHub issues on IP address `140.82.118.3`. At least here I am getting timeout when github.com is resolved to this IP address.

```
 ~/ ping github.com
PING github.com (140.82.118.3): 56 data bytes
Request timeout for icmp_seq 0
Request timeout for icmp_seq 1
Request timeout for icmp_seq 2
Request timeout for icmp_seq 3
Request timeout for icmp_seq 4

 ~/ ping github.com
PING github.com (140.82.118.4): 56 data bytes
64 bytes from 140.82.118.4: icmp_seq=0 ttl=50 time=55.610 ms
64 bytes from 140.82.118.4: icmp_seq=1 ttl=50 time=54.942 ms
64 bytes from 140.82.118.4: icmp_seq=2 ttl=50 time=56.465 ms
64 bytes from 140.82.118.4: icmp_seq=3 ttl=50 time=55.776 ms
```

**Comment by singhvivek2503** [comment]
Me to getting same error

**Comment by GooeyChickenman** [comment]
Adding my own GitHub SSH key resolved it ([tutorial if needed](https://help.github.com/en/enterprise/2.18/user/github/authenticating-to-github/adding-a-new-ssh-key-to-your-github-account))

**Comment by mrbianchi** [comment]
same problem using WSL, but it wasnt an error, just ignorance! thanks
