### ISSUE TITLE
Copy/Paste functionality for addresses on testnet (Kovan, Rinkeby or Görli)

### ISSUE THREAD

**Issue by georgeandrei** [MetaMask/metamask-mobile#1442]
When trying to send ETH on Kovan, Rinkeby or Görli, I am unable to paste an address into the "Address" field in the MetaMask app on Android 10.

Paste works fine on Mainnet and Ropsten.

 - Device: unknown
 - OS: Android 10
 - Version 0.2.14 (27)

![Screenshot_20200320-130029](https://user-images.githubusercontent.com/45980656/77165737-92a5f600-6abb-11ea-844a-562bc2e66267.png)
![Screenshot_20200320-130143](https://user-images.githubusercontent.com/45980656/77165744-95085000-6abb-11ea-8855-ce95df794917.png)
![Screenshot_20200320-130228](https://user-images.githubusercontent.com/45980656/77165747-96397d00-6abb-11ea-8bf3-53e30748a12d.png)

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by criticaltv** [comment]
Bravo, can't wait for this to ship!
