### ISSUE TITLE
Trouble connecting to InstaDapp

### ISSUE THREAD

**Issue by fxfrnk** [MetaMask/metamask-mobile#1444]
**Describe the bug**
_A clear and concise description of what the bug is_
Connecting to InstaDapp from MetaMask is not possible and wheel spins constantly. It's possible to connect using other wallet apps like Trust wallet

**Screenshots**
_If applicable, add screenshots or links to help explain your problem_
![image](https://user-images.githubusercontent.com/11490430/77182873-da208800-6aa3-11ea-95a1-c6282c9992a8.png)

**To Reproduce**
_Steps to reproduce the behavior_
1. Go to https://instadapp.io/dashboard
2. Click on spinning wheel
3. Select 'connect' next to web3 wallet
4. Connection still not possible and wheel still spins

**Expected behavior**
_A clear and concise description of what you expected to happen_
Metamask connects to dapp and balances load

**Smartphone (please complete the following information):**
 - Device: Google Pixel 3 XL, iPhone Xs
 - OS:  Android 10, iOS 13.3.1
 - Version 0.2.14

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by rekmarks** [comment]
I've reached out to InstaDApp and am awaiting a response.

The problem again appears to be due to it taking longer to inject our provider on mobile than desktop.

**Comment by verylihi** [comment]
> I've reached out to InstaDApp and am awaiting a response.
> 
> The problem again appears to be due to it taking longer to inject our provider on mobile than desktop.

Sorry, I do n’t know what I can do. My Pixel 3XL still ca n’t log in to InstaDAPP, so I have to attach a [video link](https://photos.app.goo.gl/TExXMVbHfMX51oK77) 

Very grateful for your help

**Comment by rekmarks** [comment]
@verylihi 对不起，等一下吧 :)

This fix is not yet released. instadapp.io will work in the next version of MetaMask mobile.
