### ISSUE TITLE
Enable Pipelines in CircleCI

### ISSUE THREAD

**Issue by whymarrh** [MetaMask/metamask-mobile#1446]
From an email from CircleCI:

> You are receiving this email because you are a member of one or more paid projects building on CircleCI that does not have pipelines enabled.
>
> We are reaching out to let you know about two upcoming changes to CircleCI:
>
> - **Beginning on March 31, 2020, we will start automatically enabling pipelines for all projects.** Turning on pipelines will allow your team to access new features. Watch our [webinar recording](https://go.circleci.com/Y02m30zkT008E002GMZ0VH4) or [read our docs](https://go.circleci.com/F4EMG00WA0Z0T238000H2km) for detailed information about the transition to pipelines and the benefits that you can expect to see.
> - **The ability to opt-out of our new user interface will be removed starting on April 15th, 2020.** Our team has been hard at work building a [new interface](https://go.circleci.com/p0m00Z04BH080XkM2G0TE32) that is more responsive and makes it easier for you to accomplish your most important tasks in CircleCI. Beginning on April 15, we will start to remove the ability to switch back to our old UI.
>
> To get ahead of these changes we recommend that you update your project settings to [enable pipelines](https://go.circleci.com/X2G0TyM0k000H3mE8024ZU0) and [opt in to the new UI](https://go.circleci.com/JM2GZ80Y4H0kC3E02T000m0) if you haven’t already. At the end of this message, we have included links to the settings for your projects that are not yet using pipelines to make it easy to make the switch.
>
> We’re constantly working to improve CircleCI. These changes will help us deliver the best possible experience for our customers.

From the project settings on CircleCI:

> **Enable pipelines**
>
> Turn on pipelines for this project to gain access to CircleCI’s improved UI and other new features including reusable config, auto-cancellation of redundant builds, and [more.](https://discuss.circleci.com/t/rollout-of-pipelines-functionality/34651)
>
> If you experience any issues when enabling pipelines, check out these [troubleshooting tips.](https://circleci.com/docs/2.0/build-processing/#getting-started)
>
> **NOTE:** If for any reason you’d like to disable pipelines again for a project on a usage-based plan, you can do so by filing a ticket with CircleCI support.

**Comment by nanaluz** [comment]
#1427
