### ISSUE TITLE
Doesn't detect Metamask wallet

### ISSUE THREAD

**Issue by omnat** [MetaMask/metamask-mobile#1452]
**Describe the bug**
The twekenaire.com dapp is not working since the metamask update. It keeps saying I need to connect to metamask

**Screenshots**
![Screenshot_20200316-225220](https://user-images.githubusercontent.com/44038140/77340386-75a33a00-6cea-11ea-9158-f63d1de78601.jpg)

**To Reproduce**
_Steps to reproduce the behavior_

**Expected behavior**
_A clear and concise description of what you expected to happen_

**Smartphone (please complete the following information):**

https://consensys.zendesk.com/agent/tickets/32671
(more info by @fxfrnk coming)

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by fxfrnk** [comment]
> **Describe the bug**
> The **tewkenaire.com** dapp is not working since the metamask update. It keeps saying I need to connect to metamask
> 
> **Screenshots**
see original comment
>
> **To Reproduce**
> _Steps to reproduce the behavior_

1. Go to https://tewkenaire.com/hextew.html
2. Accept request to connect to Dapp
3. Dapp still mentions "Please log into Metamask!" and balances continue to show loading icon (i.e. In Rate, Out Rate, Total Balance, etc.).
 
> **Expected behavior**
> _A clear and concise description of what you expected to happen_
Dapp connects to Metamask, Wallet Address is displayed next to "Wallet:" instead of "Please log into Metamask", and balance load
>
> **Smartphone (please complete the following information):**
> 
* Device: - / iPhone Xs
* OS: Android 10 / iOS 13.3.1
* Version: 0.2.14
> 
> https://consensys.zendesk.com/agent/tickets/32671
> (more info by @fxfrnk coming)
> 
> _to be added after bug submission by internal support / PM_
> **Severity**
> 
> * How critical is the impact of this bug on a user?
> * Add stats if available on % of customers impacted
> * Is this visible to all users?
> * Is this tech debt?

**Comment by rekmarks** [comment]
Tewkenaire is obfuscating its frontend code, making it impractical for us to do anything from our end. If they reach out, we may be able to help them debug, but there's otherwise nothing for us to do here.
