### ISSUE TITLE
Metamask Mobile can no longer sign messages

### ISSUE THREAD

**Issue by BrendanChou** [MetaMask/metamask-mobile#1459]
**Describe the bug**
Can no longer sign messages

**Screenshots**
N/A

**To Reproduce**
Use any previously-supported signing method or signing method supported by Metamask or Metamask Mobile, including web3.eth.sign and eth_signTypedDataV4 (the RPC call invented by Metamask itself).

**Expected behavior**
A popup to sign a message should appear, or at least a javascript error should be thrown.

**Smartphone (please complete the following information):**
 - Device: Pixel 2
 - OS: Android 10
 - Version 0.2.14

Also reported by many other users of dYdX

This was previously working in Version 0.2.10

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by rekmarks** [comment]
Hello @BrendanChou, thank you for bringing this issue to our attention.

We are unable to replicate these failures with any production version of MetaMask (extension or mobile).

To continue our investigation, please respond to the following:

- Are you only experiencing these failures on the provided platform? (Pixel 2, Android 10)
- If not:
  - Are you experiencing the failures using the extension?
  - For mobile, have you tried using iOS?
- Can you provide a gist or snippet with example signature requests?
  - Both web3.eth.sign and eth_signTypedDataV4 would be helpful.
  - If you're using `web3`, please provide the version or indicate whether you're using the MetaMask-provided `window.web3`.

**Comment by BrendanChou** [comment]
I've gotten 1 other report for Metamask on Android failing, and one other report for it failing on an unspecified platform (following up to try and find out that information).
It works fine on browser versions of MetaMask.

I cannot try on Metamask iOS at the moment since the beta is full.

Here is the snippet that works for browser but not mobile.
https://github.com/dydxprotocol/solo/blob/d4a984499851adf1e8ab21f9408892aa8bc5fd63/src/modules/Signer.ts#L64

**Comment by BrendanChou** [comment]
eth.sign method:
https://github.com/dydxprotocol/solo/blob/792a2564e48525e6cf9b23d0d96df9b0eba4df6a/src/modules/OrderSigner.ts#L95

snippet to get the Metamask provider which is then used as a subprovider
```
      if (window.ethereum) {
        return window.ethereum;
      }
      if (window.web3 && window.web3.currentProvider) {
        return window.web3.currentProvider;
      }
```

**Comment by BrendanChou** [comment]
Someone is running into the same issue on iPhone, MMM Version 0.2.14

**Comment by rekmarks** [comment]
We've continued our attempts to reproduce this to no avail, including on a physical iPhone with `0.2.14`. If any spots open up for the mobile beta, we'll try to get you an invite for testing.

Next set of questions:

1. Have you explored the possibility that the signing `data` object is malformed? If you have an error message or a failing example, we could likely tell if that's the case.
2. For these users, are all signing attempts failing or are the failures intermittent?

**Comment by BrendanChou** [comment]
Fails on iOS and Android beta. Was previously working with both operating systems with MetamaskMobile. Also works with every other wallet (mobile or browser)

**Comment by BrendanChou** [comment]
I would ignore the `eth_signTypedData` method for now because even Metamask Browser doesn't support that properly. So would focus on why `web3.eth.sign` doesn't work anymore

**Comment by rekmarks** [comment]
Regarding `web3.eth.sign`, I can't reproduce the failure using `web3@1.2.x` in the mobile browser with any data I provide it. I can't find any errors in our metrics that indicate the failure you're describing.

I require an example of a failing call to `web3.eth.sign` and/or an error message to investigate further.

**Comment by omnat** [comment]
Hi @BrendanChou, is this still an issue on the latest version?

**Comment by BrendanChou** [comment]
Working now!
