### ISSUE TITLE
Sign in with fingerprint fails with Android 7.0 (Xiaomi).

### ISSUE THREAD

**Issue by dpazdan** [MetaMask/metamask-mobile#1463]
Sign in with fingerprint fails with Android 7.0 (Xiaomi).

User reinstalled app and same occurred. 

Support ticket: 32394

**Comment by omnat** [comment]
On OnePlus3T too

**Comment by dpazdan** [comment]
One user reported this info to support:
MetaMask issue concerning the fingerprint mode not working on my Xiaomi (Android 7.0) was due to the fact that i had 2 fingerprints registerd.

So something in MetaMask code doesn't handle it correctly.

Regards,

**Comment by omnat** [comment]
Next step: check if this error occurs still from Sentry

**Comment by omnat** [comment]
@dpazdan could we follow-up if this is still an issue in the latest version? if not, let's close this.
