### ISSUE TITLE
iOS Crash after editing gas price that dapp suggested

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-mobile#1473]
DeFiDad reported

Using hegic.co

It seems to suggest a gas price to metamask.
When the user then opens advanced gas controls and tries to edit the gas price, MetaMask crashes.

**Comment by EtDu** [comment]
@danfinlay Now it makes sense! I stumbled upon this bug while implementing the new design for advanced gas controls. If the gas price is `invalid` and you start to edit the gas limit, the app crashes. Able to consistently reproduce.
![gas_bug](https://user-images.githubusercontent.com/26778340/80682355-ea8d3f00-8af4-11ea-8ae6-2e2fba20bb93.gif)

**Comment by dpazdan** [comment]
another user reported the same to support: 36508

**Comment by EtDu** [comment]
#1512 to the rescueeeee

**Comment by ibrahimtaveras00** [comment]
This issue still seems to be occurring even on current develop/ 0.2.17 version

Seen here = https://recordit.co/XCdB1XkMo2

steps to reproduce: 
- go to https://metamask.github.io/test-dapp/
- create tokens
- approve token
- in txn fee, tap on Edit button
- attempt to edit gas price

**Comment by EtDu** [comment]
This is fixed
