### ISSUE TITLE
Recent update breaks web3 interactions on Cent.co

### ISSUE THREAD

**Issue by dpazdan** [MetaMask/metamask-mobile#1476]
**Describe the bug**
The Cent.co team has reported that all web3 interactions on Cent (e.g. deposit, withdrawal, bounty, tip, seed) using MetaMask mobile are not working since the most recent update (12 March).  The wallet page is not even recognizing MetaMask. 

**Smartphone (please complete the following information):**
 - OS: Android / iOS
 - Version Current Public build 0.2.14 (389)

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by rekmarks** [comment]
Repro:

- Go to beta.cent.co
- Hamburger menu (top left, two horizontal dashes)
- `Account`
- `Wallet` (middle of three options at top of page, under header)
- See if it connects
