### ISSUE TITLE
The coin app seems to not accept my sign on information and I can't get it to work on my phone.

### ISSUE THREAD

**Issue by georgeandrei** [MetaMask/metamask-mobile#1479]
The coin app seems to not accept my sign on information and I can't get it to work on my phone.

![Screenshot_20200326-103205_MetaMask_thumb](https://user-images.githubusercontent.com/45980656/78781050-41956d80-79a8-11ea-8fc4-10545ef035e6.jpg)

**Smartphone (please complete the following information):**
 - Device: Samsung S9 SM-G960W
 - OS: Android 10
 - Version 0.2.14

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by omnat** [comment]
Thanks for reporting @georgeandrei, could you please share a bigger screenshot so we can see what the error is? Thanks!

**Comment by rekmarks** [comment]
@georgeandrei please submit larger screenshots and any error messages (the more complete the better).

**Comment by dpazdan** [comment]
related support issue: 33076

**Comment by rekmarks** [comment]
App identified as my.coinapp.co

It's the Android browser, and specifically CORS. iOS works fine.

Error on Android:
![image](https://user-images.githubusercontent.com/25517051/79146945-06b08280-7d78-11ea-8f59-7e8182cecac0.png)

**Comment by swornov** [comment]
before i had ios later i got a android
