### ISSUE TITLE
ERC20 Token does not show up for account

### ISSUE THREAD

**Issue by Tuanp703** [MetaMask/metamask-mobile#1483]
**Describe the bug**
I added an ethereum account that has ethers and LINK token on Ropsten net.  I added LINK using the Search function and added using that route (it does not seem to know the contract address). If I use the add Custom Token manually it does work. I think the Search and add thru it is bugged.

**Screenshots**
Links contain my android version, metamask version and issue account.
https://1drv.ms/u/s!Athwhc7bxjKBhZVrB8izUQ9ZPUnq9g?e=QL2RBd

**To Reproduce**
_Steps to reproduce the behavior_
1. Add token LINK
2. LINK is added but balance is zero.

**Expected behavior**
_I expect to see 100 LINK tokens for that Ethereum Address. You can confirm this by reviewing the same account on Etherscan. Note that there are 100 LINK tokens

**Smartphone (please complete the following information):**
Android version 9
LG G7 ThinQ
Metamask v0.2.14 (27)

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by estebanmino** [comment]
@Tuanp703 is this still happening or it was only one time and then the balance was correct?

**Comment by estebanmino** [comment]
@Tuanp703  are you sure you didn't add the LINK token address from mainnet? https://etherscan.io/token/0x514910771af9ca656af840dff83e8264ecf986ca

**Comment by Tuanp703** [comment]
It would only work when I added the token address. It seem a bit strange that users need to find the token address when they have already selected the token itself? This extra step, imho, threw off the users as a 'bug' as they expect to see something there when there is another hidden step.

**Comment by omnat** [comment]
@Tuanp703 Could you share a screenshot on where you had to add the token contract address after selecting the token?

**Comment by Tuanp703** [comment]
I was able to resolve this after I have added the contract address. My point was that that the users need to find the token contract address when they have already selected the token itself? This extra step, imho, throws off the users as a 'bug' as they expect to see something there when in reality there is another hidden step.

**Comment by omnat** [comment]
I hear you. Right now using Search you only add tokens that are in this [token registry](https://github.com/MetaMask/eth-contract-metadata). For the tokens that aren't part of this list, users have to use the 'Custom token' option. 

We understand this isn't very clear, and taking this as feedback to improve user experience.
