### ISSUE TITLE
Create DappHeader component and add to Signature Request component

### ISSUE THREAD

**Issue by danjm** [MetaMask/metamask-mobile#1484]
The new designs for confirmation screen can be seen in this figma: https://www.figma.com/file/dzapXt5s0pKBxb9lZkIoDM/%231352---Confirm-transactions?node-id=916%3A125

Each of the confirmation screen has information about the dapp requesting confirmation displayed like this:

![Screenshot from 2020-04-09 22-53-54](https://user-images.githubusercontent.com/7499938/78953953-1ba9bf00-7ab5-11ea-9d70-287a7a09e489.png)

That exact same pattern - icon, dapp origin and selected network - is used in multiple places.

The task is to put those three pieces together into a component. Styles should match the above screenshot and the designs in figma.

Also as part of the task, this new component should be used in the existing signature request screen. That screen currently looks like:

![Screenshot from 2020-04-09 22-29-00](https://user-images.githubusercontent.com/7499938/78954054-77744800-7ab5-11ea-8542-b6bc2736c621.png)

The middle section contains the dapp icon, the dapp name and the dapp origin. The code for this is in the `renderPageInformation` method of `metamask-mobile/app/components/UI/SignatureRequest/index.js`

Replace that code and the use of the `renderPageInformation` method with the new component described above that contains the icon, origin and network and matches the new styles.

Do **not** implement the rest of the signature request screen redesigns as part of this task. Just the dapp info/header component.

**Comment by cjeria** [comment]
@EtDu Here's a direct link to the design in [figma](https://www.figma.com/file/dzapXt5s0pKBxb9lZkIoDM/1352-Confirm-transactions?node-id=899%3A2599). There you will also see the component inside each **transaction screen** for reference. 

Additional context regarding the icons in this [thread](https://consensys.slack.com/archives/G4V2HTG0Y/p1586374346037100)

And some additional notes regarding when to use `function name` and prefix icons. Let me know if you have any questions.
![image](https://user-images.githubusercontent.com/597770/78994128-5b9c9080-7b0d-11ea-875d-94c4f0e249f1.png)

**Comment by EtDu** [comment]
@cjeria  Ok great, so the function name shall be included in the component as well. Also, that thread link appears to be broken.

**Comment by estebanmino** [comment]
@cjeria I'm curious about the election of icons since we've been using https://oblador.github.io/react-native-vector-icons/, I saw the PR @EtDu pushed and we have two new images on the app

**Comment by cjeria** [comment]
@estebanmino yes, these are emoji icons, however, I do realize that they are out the scope of our design system, so let's stick with the standard icons.

![image](https://user-images.githubusercontent.com/597770/79263275-8dd92580-7e60-11ea-9a38-15e588a4c47d.png)
