### ISSUE TITLE
scanQRCode seems to be missing

### ISSUE THREAD

**Issue by kohlivarun5** [MetaMask/metamask-mobile#1485]
**Describe the bug**
`scanQRCode` api to enable QR code scanning seems to have been removed. It cannot be found anymore

**Screenshots**
Sent some screenshots through TestFlight

**Smartphone (please complete the following information):**
 - Device: iPhone11 Pro
 - OS: ios13

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by dpazdan** [comment]
Hi there, did you receive an automated case number from our support system?  If so what was it?  That will help us track the issue and review the screenshots, thanks!

**Comment by omnat** [comment]
Hi @kohlivarun5, can you share steps to reproduce this bug?

**Comment by omnat** [comment]
@kohlivarun5 is this the same issue you are facing? #1042

**Comment by kohlivarun5** [comment]
Seems a similar issue.

It can be replicated using the steps in

https://github.com/MetaMask/metamask-mobile/pull/332


Running https://cipher-qr-scan.netlify.app/ in the app shows scanQRcode is missing.

Unfortunately, I was not given an id from test flight.

**Comment by dan13ram** [comment]
I have the same issue. The scanQRcode method is missing from window.ethereum or window.web3.currentProvider.

**Comment by omnat** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Bug: Scan QR code missing](https://trello.com/c/J58J4xOC/77-bug-scan-qr-code-missing)

**Comment by EtDu** [comment]
@kohlivarun5 

We've decided not to directly support `provider.scanQRCode()` because it isn't apart of our core provider standard. Moreover, dApps can now access QR code scanning functionality with the RPC method, `wallet_scanQRCode`. Please see our docs for more details https://docs.metamask.io/guide/rpc-api.html#mobile-specific-rpc-methods

This fix should be applied in an upcoming release.
