### ISSUE TITLE
unable to stake on go.hex.win dapp 

### ISSUE THREAD

**Issue by georgeandrei** [MetaMask/metamask-mobile#1502]
On the go.hex.win dapp there is a staking feature that does not work properly on the mobile device.

cannot fill in the data for "Stake amount" and "Stake length in days", cannot scroll on the page:

![Screenshot_20200413-213949_MetaMask](https://user-images.githubusercontent.com/45980656/79848268-89b18880-83c9-11ea-8fc0-ce8a663503fe.jpg)

**Smartphone (please complete the following information):**
 - Device: Samsung S20
 - OS: Android
 - Version 0.2.14

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by cortisiko** [comment]
I cannot reproduce this issue: http://recordit.co/nY250Z3stN 

if it still persists, feel free to reopen.
