### ISSUE TITLE
Metamask mobile not working on Aave

### ISSUE THREAD

**Issue by rdymac** [MetaMask/metamask-mobile#1510]
**Bug and repro**

_We have deployed a testing branch so you are able to debug properly if you want, at least on my side its giving an error when trying to make the web3 connection to show a button that would trigger a transaction. You can access the testing branch with virtual console to debug at https://dlp-300-vconsole.testing.aave.com/ Its giving “Network error” is it possible that by default Metamask is blocking the proper connection with the required API that its required to work? Im attaching here screenshots:_

![image002](https://user-images.githubusercontent.com/2995401/80110604-25d0c080-857f-11ea-8eb3-c00b77722f0a.jpg)

![image003](https://user-images.githubusercontent.com/2995401/80110620-29fcde00-857f-11ea-800e-d4ee5bce7fc2.jpg)

_For example in trust wallet and coinbase wallet there is no error and it works properly, similar way in other browser wallets and even in metamask desktop works well:_

![image004](https://user-images.githubusercontent.com/2995401/80110579-1f424900-857f-11ea-8a43-aae4cf283671.jpg)

![image005](https://user-images.githubusercontent.com/2995401/80110568-1baec200-857f-11ea-971a-a67354ec4892.jpg)

**Comment by cortisiko** [comment]
@rdymac is this still an issue for you?
