### ISSUE TITLE
Fails to estimate gas for contract creation

### ISSUE THREAD

**Issue by monokh** [MetaMask/metamask-mobile#1519]
**Describe the bug**
Metamask mobile when prompted for contract creation (data field) fails to estimate gas.
Metamask extension functions correctly.

**Screenshots**
https://0y3py.csb.app/

**To Reproduce**
1. Go to https://0y3py.csb.app/ in the metamask browser
2. Accept prompt to connect
3. Transaction confirmation should pop up
3. Look at gas limit field

It is set at the default 21000 and the transaction will not go through
Compare to behaviour of extension

**Expected behavior**
Gas limit should be calculated and set

**Smartphone (please complete the following information):**
 - Device: Huawei
 - OS: Andorid
 - Version 8.1

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by cortisiko** [comment]
@monokh is this still an issue for you? If so can you provide another dapp we can use to reproduce?
