### ISSUE TITLE
Wrong login redirect

### ISSUE THREAD

**Issue by omnat** [MetaMask/metamask-mobile#1532]
(from support Case: 34915)
@george: The user claims that he was prompted to set up a password, after he set it up, he was redirected instantly to the login page, which worked (he was able to log in), after a while he tried to login again,  but he was instantly taken to the “Welcome page”

@randy: The two cases mentioned above case34915 and case34813, mention users are able to see the 'Get started' screen and the 'Log in' button, but the button does nothing.

**Screenshots**
![Screenshot_20200429-104556](https://user-images.githubusercontent.com/44038140/80850179-7d021100-8bcf-11ea-891e-1ca47c567dc7.gif)

**To Reproduce**
_Steps to reproduce the behavior_

**Expected behavior**
_A clear and concise description of what you expected to happen_

**Smartphone (please complete the following information):**

**Comment by roxxxj** [comment]
Same problem... Have you find a solution ?

**Comment by omnat** [comment]
Thanks for reporting! @roxxxj could you please add steps to reproduce?

**Comment by roxxxj** [comment]
He was at work when the app Ask the password, he enter the password and the app return to the first page. After the work, he enter his login, it work, but 5 sec After, the app returned to de first page again. And he never Can enter After..

**Comment by roxxxj** [comment]
The phone IS a CAT S41 
Android version 8.0.0
The app metamask is 0.2.14
Android device id 5AF057BE41C3EC

**Comment by roxxxj** [comment]
He never Can see his pass phrase, and now the "login" is blocked and he can't enter on his account. (Same screenshot)
