### ISSUE TITLE
Tabs behaving buggy

### ISSUE THREAD

**Issue by omnat** [MetaMask/metamask-mobile#1536]
**Describe the bug**
Noticed 2 things -
- When a user opens a tab from previously opened tabs (before they killed the app), the tab doesn't load (blank page #1319 . Same dapp works if loaded fresh.
![Screenshot_20200501-173649](https://user-images.githubusercontent.com/44038140/80850893-475f2700-8bd3-11ea-8781-5b29578d929a.jpg)

- Opening multiple tabs, with a few tabs browsers... the browser tabs showed the dapp opened in another tab in overview
![Screenshot_20200501-173654](https://user-images.githubusercontent.com/44038140/80850903-51812580-8bd3-11ea-976f-aa5a5c020151.jpg)

![Screenshot_20200501-173534](https://user-images.githubusercontent.com/44038140/80850902-504ff880-8bd3-11ea-83ec-a5a0c6cf78d9.jpg)

maybe related? #1515 

**Smartphone (please complete the following information):**
 - Device: OnePlus 3T
 - OS: Android 9.0.6 OxygenOS
 - Version: 0.2.14

**Comment by AlexJupiter** [comment]
I don't see this on iOS and Android 5.0.1, so since this is an old ticket, I'll close this now.
