### ISSUE TITLE
Move Settings option on nav bar

### ISSUE THREAD

**Issue by omnat** [MetaMask/metamask-mobile#1537]
**Describe the usability problem**
It isn't clear to people where to change the setting from. 

**Screenshots**
![Screenshot_20200501-175627](https://user-images.githubusercontent.com/44038140/80851224-331c2980-8bd5-11ea-889b-2b476a51f6a6.jpg)

**Expected behavior**
Settings option should be a clear 'Settings' menu option. Suggestion to add it above 'Get help' or below 'Log out' options.

------------------------------------------------------------------------------------------------------
_filled out after submission_

**User impact | Usage frequency | Feasibility scores**
_How important is this to the user, what the user wants to accomplish | Daily, weekly, monthly | Small, medium, large_

**Comment by estebanmino** [comment]
@omnat should we remove it from the top?

**Comment by rickycodes** [comment]
I think we should leave it in both places, any user accustomed to where it is might get thrown off?

**Comment by omnat** [comment]
Hmm, in a design conversation, we were considering to have a network indicator up there (where settings icon currently is) in another iteration / later - most likely after v1. 

So as a first suggestion, the idea was to remove it from up there, and add it down as menu option. @cjeria @rachelcope thoughts on this - is it a good pattern to have 2 ways to access Settings?

**Comment by rickycodes** [comment]
> is it a good pattern to have 2 ways to access Settings

I'm also totally fine to remove it in this same PR if we think it's a good idea... it could also be removed later if/when the aforementioned network indicator is ready? fwiw i do think we should have some other UI for switching the network the way we're doing it now is confusing

**Comment by cjeria** [comment]
Based on some observations during user testing (I'd have to refer to previous user test recordings), I do recall users looking for the settings in the drawer down where @omnat is suggesting to put it. That said, I'm leaning towards the decision to remove the icon and placing it on the list at the bottom of the drawer in just one location.

**Comment by rickycodes** [comment]
Okay, I've gone ahead and updated the PR so the settings gear is now removed:

![Screenshot_20200505-123641](https://user-images.githubusercontent.com/675259/81091682-8f30c780-8ecd-11ea-8355-0fe5de2f93fc.png)

**Comment by rachelcope** [comment]
What do you think about adding the gear icon back to the left of "Settings". It is a common icon pattern that could help users more quickly find settings and also a good visual cue for current users who may be looking for where the settings button moved

^ @rickycodes @omnat @cjeria

**Comment by rickycodes** [comment]
@rachelcope I actually, _just_ made the same suggestion to @cjeria on Slack. I'm in favour of doing that and adding it just under the "View on Etherscan" if that makes sense?

**Comment by rachelcope** [comment]
that makes sense to me! 👍

**Comment by cjeria** [comment]
Icon makes sense. Not sure about clustering settings within the account-specific cluster. WDYT @omnat

**Comment by rickycodes** [comment]
Here's what I got now:

![Screenshot_20200505-130001](https://user-images.githubusercontent.com/675259/81093779-91e0ec00-8ed0-11ea-8a39-02d988cd8fb0.png)
