### ISSUE TITLE
Won't connect to dYdX

### ISSUE THREAD

**Issue by ghost** [MetaMask/metamask-mobile#1553]
**Describe the bug**
_Can't connect wallet to dYdX_

**To Reproduce**
_Steps to reproduce the behavior_
1. Go to 'trade.dydx.exchange'
2. Click on 'connect wallet'
3. Choose 'MetaMask'
4. It keeps loading and won't connect

**Smartphone (please complete the following information):**
 - Device: [Xiaomi Redmi Note 5 Pro]
 - Android version [9 PKQ1.180904.001]
 - MIUI version [MIUI Global 11.0.3 | 11.0.3.0(PEIMIXM)]

**Severity**
_It is critical because dYdX is one of the most used DEXes (24h vol: 10m of eth in eth/dai and 7m of eth in eth/usdc)_

**Comment by cfusting** [comment]
+1

**Comment by PJWilkinson** [comment]
+100!

**Comment by ibrahimtaveras00** [comment]
@cfusting and @PJWilkinson please try on the latest version (v1.0.10) and see if it works for you now.

I was able to connect; http://recordit.co/yKJybVaEuG

**Comment by AlexJupiter** [comment]
Seems this issue is fixed now.
