### ISSUE TITLE
When inputting fiat value and proceeding on request flow, ?value=0

### ISSUE THREAD

**Issue by ibrahimtaveras00** [MetaMask/metamask-mobile#1562]
**Describe the bug**

When requesting ETH or another ERC20 token via the request flow, and inputing a dollar amount by toggling/switching to fiat input, it gets passed as value = 0

**Screenshots**

Flow seen here = http://recordit.co/ySDON2sF8D

Enter Amount:
![Screen Shot 2020-05-12 at 5 26 09 PM](https://user-images.githubusercontent.com/41752922/81747279-d262db80-9475-11ea-99ff-c2a8855761c1.png)

Send Link View:
![image](https://user-images.githubusercontent.com/41752922/81747273-d0008180-9475-11ea-9459-57ee1021caf5.png)

**To Reproduce**
_Steps to reproduce the behavior_
1. tap on settings then tap Receive button
2. tap on/select ETH
3. once on request view to enter amount, first thing to do is tap on the currency switcher
![image](https://user-images.githubusercontent.com/41752922/81748807-751c5980-9478-11ea-8fa5-acff7f4c5673.png)
4. notice how it already prefills with 0, now enter in a value and tap on Next
5. notice how in the link it says ?value=0

**Expected behavior**

The value she be the same entered in the previous field/view

**Smartphone (please complete the following information):**
 - Device: Any Android device 
 - OS: Any 
 - Version Any

Note* on iOS it wont allow me to even proceed to next screen; seen here = http://recordit.co/ZVDt6UY9kx

![Screen Shot 2020-05-12 at 5 50 28 PM](https://user-images.githubusercontent.com/41752922/81749158-199e9b80-9479-11ea-968c-1e8772dcea13.png)

- Device: Any iOS device 
 - OS: Any 
 - Version Any

**PS:**

I can only reproduce this bug when my Settings > General > Primary Currency is set to Native

![Screen Shot 2020-05-12 at 5 55 21 PM](https://user-images.githubusercontent.com/41752922/81749518-c6791880-9479-11ea-8e7f-7f440c891b00.png)

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by danjm** [comment]
I think this has been an issue since at least `MetaMask v0.2.14 (27)`

Here is a video where I successfully recreated on v0.2.14: https://streamable.com/y5qq62

**Comment by omnat** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Conversion bug in payment request flow](https://trello.com/c/GGTt5MBq/53-conversion-bug-in-payment-request-flow)

**Comment by omnat** [comment]
https://consensys.slack.com/archives/GBW7S9FSN/p1597868929337200
@EtDu I am suspecting that this PR introduced this issue. 
In the Amount field, you see 0.00 USD, and as soon as you start typing / inputting amount, it changes currency to DAI (in this case - but can be ETH which will be very bad).

**Comment by ibrahimtaveras00** [comment]
I can't seem to reproduce this on android

ETH = https://recordit.co/q3OSECMMCY
DAI = https://recordit.co/K03Kfg7M1c

Nor on iOS = http://recordit.co/uzw9zBj2sZ

**Comment by EtDu** [comment]
I also cannot reproduce if primary currency is native or fiat.

**Comment by ibrahimtaveras00** [comment]
I can only reproduce this coming from the asset overview screen only when the primary currency is native; seen here = http://recordit.co/PHyGm9ZIcW

**Comment by omnat** [comment]
Same, can reproduce with the steps as @ibrahimtaveras00.

**Comment by ibrahimtaveras00** [comment]
This will be fixed in https://github.com/MetaMask/metamask-mobile/pull/1790
