### ISSUE TITLE
Read & Write Feature for Smart Contracts do not work with MetaMask mobile

### ISSUE THREAD

**Issue by dpazdan** [MetaMask/metamask-mobile#1569]
User reported: 
Whenever I want to read or write a smart contract on etherscan (main & testnet) with MetaMask mobile I get the message:
Sorry, we were unable to locate a matching Contract ABI or SourceCode for this contract.

If you are the contract owner, please Verify Your Contract Source Code here.

Using the computer everything works fine. Just the mobile version is flawed.

case: 35940

![image](https://user-images.githubusercontent.com/16330048/81841895-b7917500-9510-11ea-9670-109d6ca884e1.png)

**Comment by EtDu** [comment]
Was able to reproduce 2/10 attempts. Refreshing the browser fixed it in all cases, but sometimes taking a few tries. Leads me to believe the bug is not Metamask related at all, unless there's something I'm missing

**Comment by EtDu** [comment]
This led me to discover another bug https://trello.com/c/JqN0DhCV/89-undefined-is-not-an-object-evaluating-tmessage

**Comment by Enigmatic331** [comment]
Hey @dpazdan - Is this still persisting? We have pushed a couple of fixes to the ABI loading process for the writeContract pages (and its extension pages), which should sort this out. Otherwise, feel free to ping.

Thanks.

**Comment by EtDu** [comment]
@Enigmatic331 Appears to be resolved, thanks!
