### ISSUE TITLE
var(--cape-base)" is not a valid color or brush

### ISSUE THREAD

**Issue by rickycodes** [MetaMask/metamask-mobile#1576]
**Describe the bug**
Cheeze Wizard collectable fails to render

**Screenshots**

![image](https://user-images.githubusercontent.com/675259/81944758-32b76180-95cb-11ea-855c-b5a0ddc510d2.png)

**To Reproduce**
1. Go to 'Wallet'
2. Click on 'Collectables'
3. Scroll down to 'Pasteurised Cheeze Wizard' (a collectable from https://www.cheezewizards.com/)
4. See the following warning (in debug only): '"var(--cape-base)" is not a valid color or brush' and the asset fails to render.

**Expected behavior**
I should be able to see this asset

**Additional details**
The asset appears to be an animated SVG. This one is tricky to reproduce since not all of them fail. (I'm guessing only certain SVGs for Cheeze Wizards actually animate and use css variables?) Some initial googling and I stumbled on the following related issue:

https://github.com/kristerkari/react-native-svg-transformer/issues/50

It looks like we might be able to fix this by updating a dep?

**Comment by AlexJupiter** [comment]
An old issue that could do with being reproduced before taking further.

**Comment by rickycodes** [comment]
@AlexJupiter it's still outstanding. the NFT above is one i still have and it still doesn't render correctly.
