### ISSUE TITLE
MetaMask on Android is sluggish, unresponsive and not a nice experience. Seriously.

### ISSUE THREAD

**Issue by bitcoinmeetups** [MetaMask/metamask-mobile#1594]
MetaMask on Android is sluggish, unresponsive and not a nice experience. Seriously.

1. It takes 30-40 seconds to get past the splash screen. That's just not ok.

2. It's totally slow and sluggish while using it. Everything happens like in a fog. You press a button. You wait. Then something happens. Maybe.

3. There is no password for the wallet.

4. You cannot easily copy the ETH address to the clipboard.

But worst of all is the 30-40 splash screen and the overall sluggishness.

Whoever is working on this app, you HQ guys gotta pull them in their ears or replace them. This is not working. I would almost go as far as saying that MetaMask on Android is a disgrace, especially if compared to the neat experience of the desktop browser extension.

You can, will and must revamp this.

**Comment by kumavis** [comment]
noted

**Comment by Micka33** [comment]
2 years later.
Metamask (current latest version), on:
- Android 11
- Oxygen OS 11.1.2.2
- one plus 6

Is very, very, very slow, to load any website.
If I use, theorbs.io as example, the website doesn't even recognize I am using the app (yes, it works perfectly on desktop and unlike in the app, it loads instantly as well).

Not sure what's going on here, but that makes the app quite obsolete. Or rather, a better than nothing tool, on which I wouldn't rely if I want a snappy experience.

Btw, good luck to the dev team. That's a very good project to work on, keep the effort.

**Comment by iamifeolushola** [comment]
> MetaMask on Android is sluggish, unresponsive and not a nice experience. Seriously.
> 
> 1. It takes 30-40 seconds to get past the splash screen. That's just not ok.
> 2. It's totally slow and sluggish while using it. Everything happens like in a fog. You press a button. You wait. Then something happens. Maybe.
> 3. There is no password for the wallet.
> 4. You cannot easily copy the ETH address to the clipboard.
> 
> But worst of all is the 30-40 splash screen and the overall sluggishness.
> 
> Whoever is working on this app, you HQ guys gotta pull them in their ears or replace them. This is not working. I would almost go as far as saying that MetaMask on Android is a disgrace, especially if compared to the neat experience of the desktop browser extension.
> 
> You can, will and must revamp this.

It's 2024 and MetaMask is still sluggish on mobile *sigh*

**Comment by Hitarthhhh** [comment]
its 2026 and metamask is still sluggish bro
