### ISSUE TITLE
Connect Screen QA Issues

### ISSUE THREAD

**Issue by ibrahimtaveras00** [MetaMask/metamask-mobile#1603]
The following is QA review on https://github.com/MetaMask/metamask-mobile/pull/1508

**Issue 1:**

When a user has a long account name, it overlaps on the box

Examples:

Android > Nexus S
![Screen Shot 2020-05-28 at 3 20 04 PM](https://user-images.githubusercontent.com/41752922/83183993-c5412000-a0f6-11ea-8697-44198c0a97f5.png)

iOS > iPhone SE
![image](https://user-images.githubusercontent.com/41752922/83183971-bbb7b800-a0f6-11ea-9a1e-715264511626.png)

steps to reproduce: 
- go to wallet
- long press on account name
- edit account name to include many characters 

**Issue 2:**

Fiat currency is displayed with more than 2 decimals. 

![image](https://user-images.githubusercontent.com/41752922/83184479-852e6d00-a0f7-11ea-8802-e0a1e582971d.png)

**Issue 3:** 

Seems like the sizing is off on the icon (supposed to be 56x56) as in the mockup 

![Screen Shot 2020-05-28 at 6 00 43 PM](https://user-images.githubusercontent.com/41752922/83199062-730bf900-a10e-11ea-9050-2593425fb158.png)

cc: @cjeria @EtDu

**Comment by cjeria** [comment]
Re: **Issue 1:** I synced with Etienne about using responsive font sizes for smaller screens. @andrepimenta do you know if this is possible? If not, an alternative option would be to break the address out to a new line below the name.
