### ISSUE TITLE
Speed up does not work

### ISSUE THREAD

**Issue by CrackerHax** [MetaMask/metamask-mobile#1626]
**Describe the bug**
_A clear and concise description of what the bug is_
Using "speed up" on mobile app says I do not have eth for gas, but I do. Also it does not let you specify an amount.

**Screenshots**
_If applicable, add screenshots or links to help explain your problem_

**To Reproduce**
_Steps to reproduce the behavior_
1. Make a transaction
2. Hit speed up

**Expected behavior**
_A clear and concise description of what you expected to happen_
Expect it to not tell me I don't have enough funds when I know I do have enough funds. Also expect it to let me enter my own amount for gas.

**Smartphone (please complete the following information):**
 - Device: Visible R2 3230
 - OS: Android
 - 8.1.0

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by dpazdan** [comment]
possibly related support issue: 36821

**Comment by ibrahimtaveras00** [comment]
Seems to also be the case for canceling on mainnet 

![Screen Shot 2020-06-17 at 5 24 47 PM](https://user-images.githubusercontent.com/41752922/84952848-aa901480-b0c0-11ea-96d3-1a6c41ec31f6.png)

cc: @omnat @cjeria @estebanmino

**Comment by estebanmino** [comment]
fixed on https://github.com/MetaMask/metamask-mobile/pull/1684

**Comment by estebanmino** [comment]
thanks @CrackerHax for reporting!
