### ISSUE TITLE
Scrollbar in middle of screen on iPhone

### ISSUE THREAD

**Issue by ibrahimtaveras00** [MetaMask/metamask-mobile#1630]
**Describe the bug**

Scrolling on asset txn history shows bar in middle of screen on iPhones with notches (iphone x, iPhone XR, iPhone Pro i.e.)

**Screenshots**

Seen here = https://recordit.co/1gBwe3shwW

![image](https://user-images.githubusercontent.com/41752922/84552467-d5542480-acde-11ea-8204-03e3d8160c60.png)

**To Reproduce**

1. On a device listed above (I used iPhone X or iPhone 11 Pro) go to any asset that has many txn's
2. Start Scrolling and you'll see the bar appear in the middle

**Expected behavior**

The bar should be aligned all the way to the right

**Smartphone (please complete the following information):**
 - Device: iPhone X, iPhone XR, iPhone 11 Pro (basically iPhones with notches)
 - OS: Any
 - Version Any

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by estebanmino** [comment]
this was fixed here https://github.com/MetaMask/metamask-mobile/pull/1690
