### ISSUE TITLE
No contract events / no transaction confirmation

### ISSUE THREAD

**Issue by benjaminaaron** [MetaMask/metamask-mobile#1632]
**Describe the bug**
I can't find a way to make contract events reach my frontend through MetaMask mobile. I raised this as issue in #1209 and @brunobar79 fixed it in #1236. However, now it seems to be back? I reduced our [Fin4-dApp](https://github.com/FuturICT2) to the absolute minimum and made a few test cases.
👉  Code at [benjaminaaron/dev-dApp](https://github.com/benjaminaaron/dev-dApp), live at [dev.finfour.net](https://dev.finfour.net):

<kbd>
  <img src="https://user-images.githubusercontent.com/5141792/84565647-c5822200-ad6a-11ea-98d9-01a8fb49e878.png">
</kbd>

**Screenshots**
I made screenrecordings with the _dev-dApp_ open on desktop browser and in MetaMask mobile (visible via Chrome remote devices DevTools). One after the other I am clicking the four different ways I implemented to trigger the event on the smart contract. As you can see, while the desktop browser receives the events, they don't get through on MetaMask mobile. Also the transaction confirmations don't land in the console. The pending-transaction animation from your app does work and complete though. I tried the exact same thing with the Status browser: also no contract events (that might very well mean it is totally my fault??), _but_ the transaction confirmations are getting through. Here is the [link to a Google Drive folder with both mp4 files in it](https://drive.google.com/drive/folders/19zQISRX17D0VxDd900X4fI2a2HxiDkw9?usp=sharing) (video quality better when downloaded).

**To Reproduce**
1. Go to `https://dev.finfour.net` on mobile and on desktop
2. Click on `Add contract` and `Subscribe to TestEvent using web3`
3. Now you should be subscribed via drizzle _and_ via web3 to `TestEvent` from the `DevContract`
4. Use the four ways to trigger the contract event and watch the contract events coming through on desktop but not on mobile

**Expected behavior**
Both contract events and transaction results to be getting through to mobile, not just to desktop.

**Smartphone (please complete the following information):**
 - Device: Xiaomi Mi 9
 - OS: MIUI Global 11.0.9 / Android 10
 - Version: v0.2.16 (29)

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by benjaminaaron** [comment]
Update: I included `ethers` and that works! 🥳 
drizzle, web3 and @truffle/contract don't.

**Comment by guruchaithanya** [comment]
Awaiting on drizzle send() transaction also doesn't return and it goes in hung state.

**Comment by AlexJupiter** [comment]
Closing due to this being an old ticket with little update recently. @benjaminaaron @guruchaithanya please get in touch if these issues persist and perhaps we could reopen if so.
