### ISSUE TITLE
Captainbitcoin.io video content will not play on MMM 

### ISSUE THREAD

**Issue by dpazdan** [MetaMask/metamask-mobile#1634]
**Describe the bug**
Users are unable to watch the video content when using Memtamask app - specifically on Android devices.

Error - ‘Autoplay was blocked. Please allow autoplay to watch videos on this page or try another browser’.

Additional info:
This is the error that the browser gives us here - error: {method: ‘play’, name: ‘NotAllowedError’}
It blocks our play function, though we are NOT auto-playing the video, it sees us as spam.
Note, the video is added via iframe.
<iframe src=“https://player.vimeo.com/video/421028353?title=0&amp;byline=0&amp;portrait=0&amp;playsinline=0&amp;autopause=0&amp;controls=0&amp;app_id=122963” width=“426" height=“240” frameborder=“0" allow=“autoplay; fullscreen” allowfullscreen=“” title=“Star trails” data-ready=“true” style=“width: 100%; height: 100%;“></iframe>

related to support ticket: 38087

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by AlexJupiter** [comment]
Still an issue on Android v5.0.1 and I confirmed that auto-play videos work on Android Chrome v100.0.4896.127 so we should probably fix this.

**Comment by francisco-zx** [comment]
is this fixed guys? @AlexJupiter  @tommasini
