### ISSUE TITLE
Quorum Transactions are not working

### ISSUE THREAD

**Issue by hashimreja** [MetaMask/metamask-mobile#1650]
I am using metamask mobile app to sign my transactions using wallet connect from my browser. when ever i try to sign a transaction using metamask it throws an error saying **transaction [object object]**. please make the app compatible with the private block chains as well, _Thanks in advance_.

**Comment by AlexJupiter** [comment]
@hashimreja I'm going to close this issue since it's been open for a long time without progress. Please provide a screenshot / video of this occurring and perhaps we can re-open.
