### ISSUE TITLE
User reports inconsistent NFT tracking & display

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-mobile#1663]
[User on twitter writes](https://twitter.com/An0nym0usNobody/status/1278056851976798209?s=20)

> my @metamask_io
 mobile shows different content everyday in the collectibles section? Sometimes it shows some and other times it doesn’t. Quantities are off compared to what’s really in there and everything. Changes daily.

I pinged OpenSea on the issue, hopefully they reply, otherwise we should look into ways we can make this more stable & consistent.

**Comment by gantunesr** [comment]
Solved in v3.8.0
