### ISSUE TITLE
On current develop, padding is off on edit gas modal 

### ISSUE THREAD

**Issue by ibrahimtaveras00** [MetaMask/metamask-mobile#1664]
**Describe the bug**

Padding is off on the edit gas modal

**Screenshots**

![image](https://user-images.githubusercontent.com/41752922/86182504-1c734f80-bafe-11ea-8532-42623df8e91d.png)

**To Reproduce**

1. Initiate Send flow and select an amount to send
2. Go to Confirm view
3. Tap on edit (for txn fee) 

**Expected behavior**

Padding should be aligned correctly 

![Screen Shot 2020-06-30 at 6 20 49 PM](https://user-images.githubusercontent.com/41752922/86182700-707e3400-bafe-11ea-8da3-8b3ff030a3a0.png)

**Smartphone (please complete the following information):**
 - Device: Android + iPhone
 - OS: any
 - Version current develop branch

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by rickycodes** [comment]
Fairly certain I introduced in this #1558 `af69702e`
