### ISSUE TITLE
On latest develop, MetaMetrics is turned off by default and cannot be enabled 

### ISSUE THREAD

**Issue by ibrahimtaveras00** [MetaMask/metamask-mobile#1669]
**Describe the bug**

MetaMetrics option is being disabled by default even though when I created my new wallet, I agreed and even further tried to enable it via settings but it doesn’t stick

**Screenshots**

Seen here = https://recordit.co/L17gbofuB7

**To Reproduce**
_Steps to reproduce the behavior_
1. start app fresh
2. create new wallet
3. on the "Help us improve MetaMask" view, tap the "I Agree" button
4. open drawer 
5. go to settings > Security & Privacy
6. notice how MetaMetrics is disabled and once you enable it and leave Security & Privacy and go back it's still disabled 

**Expected behavior**

1. It should be enabled by default if user taps "I Agree" on the "Help us improve MetaMask" view
2. Once enabling, it should stick and not disable

**Smartphone (please complete the following information):**
 - Device: Any
 - OS: Any
 - Version latest develop branch

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by estebanmino** [comment]
fixed and merged here https://github.com/MetaMask/metamask-mobile/commit/c3bebf86c5d41d0d222f1eb5ecf12b28fc6a7958
