### ISSUE TITLE
Approve view shows incorrect Amount value

### ISSUE THREAD

**Issue by aurimassteponaitis** [MetaMask/metamask-mobile#1672]
**Describe the bug**
MetaMask browser extension shows correct amount value on ERC20 approve call, but MetaMask mobile app shows incorrect amount value.
I assume that the value should be the same as a user enters, for example 1 and it should be shown as 1 and not as decimal 1000000000000000000.

**Screenshots**
MetaMask mobile app - incorrect Amount.
![Screenshot_5](https://user-images.githubusercontent.com/9442883/86482343-6e181600-bd5a-11ea-8f1a-0850d4c5e41e.png)

MetaMask browser extension - correct Amount.
![86482255-45901c00-bd5a-11ea-9902-0ef3ceda9233](https://user-images.githubusercontent.com/9442883/86482365-77a17e00-bd5a-11ea-87f7-d7d235263939.png)

**To Reproduce**
call ERC20 approve function.

**Expected behavior**
I assume that the value should be the same as a user enters for example 1 and it should be shown as 1 and not as decimal 1000000000000000000.

**Smartphone (please complete the following information):**
 - Device: Nexus 5x
 - OS: Android 9.0
 - Version 0.2.19

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user? 
High. Misleads the user. From user view looks like he's gonna spend way more tokens when he expected.
- Add stats if available on % of customers impacted
- Is this visible to all users?
Yes.
- Is this tech debt?
No.

**Comment by timothywangdev** [comment]
experiencing the exact same issue for months.

**Comment by pi0neerpat** [comment]
Same issue here as well. Amount should be 100 
![Screenshot_20200706-212347](https://user-images.githubusercontent.com/35622595/86682911-08808f80-bfcf-11ea-966f-821087cad51a.png)

**Comment by pi0neerpat** [comment]
I found this PR that was supposed to fix this issue. https://github.com/MetaMask/metamask-mobile/pull/1251

**Comment by estebanmino** [comment]
thanks for pinging @pi0neerpat, we'll take look

**Comment by estebanmino** [comment]
@aurimassteponaitis @timothywangdev @pi0neerpat thanks for reporting! already fixed and pushed a PR with the fix

**Comment by pi0neerpat** [comment]
Awesome thank you! Looking forward to the release.

**Comment by estebanmino** [comment]
fixed and merged here https://github.com/MetaMask/metamask-mobile/commit/c3bebf86c5d41d0d222f1eb5ecf12b28fc6a7958
