### ISSUE TITLE
Cannot detect selected network in metamask mobile

### ISSUE THREAD

**Issue by Sacronux** [MetaMask/metamask-mobile#1696]
In my dApp I am using "ethereum.chainId" to detect which network is selected in the Metamask extension. But when I am trying to connect to my dApp through Metamask mobile app "ethereum.chainId" returns undefined. How can I detect properly with code which network is selected in Metamask mobile app?

Thank you for your answers!

**Comment by Garito** [comment]
Same issue here
With the dapp loaded, if you switch network and click in the selected network it works with the chainChanged event but you need to disable autorefresh
I can't confirm if it works cause the cache loads the old code with the autorefresh

**Comment by asolache** [comment]
Kmon Metamaskers

**Comment by LucasMoskun** [comment]
Would also love a good solution to this -- seems to be the last piece of the puzzle getting my app metamask mobile friendly

**Comment by ibrahimtaveras00** [comment]
We just pushed some updates to chainId in our last release.  @MepuDuaH please update to latest version and let us know if the problem still exists.

Latest:
Android =  v1.0.10 (44)
iOS = v1.0.10 (569)

**Comment by asolache** [comment]
The ux for the mobile browser when trying to add buttons to help add a network to your network list is no t working properly. Please help

**Comment by ibrahimtaveras00** [comment]
@asolache we have https://github.com/MetaMask/metamask-mobile/pull/2318 which should be in the upcoming release (week of April 12th)

**Comment by andrepimenta** [comment]
Should be fixed in newer releases.
