### ISSUE TITLE
Insufficient funds during 'use max' for transactions

### ISSUE THREAD

**Issue by EtDu** [MetaMask/metamask-mobile#1700]
**Describe the bug**
Insufficient funds error when pressing 'use max' during a transaction and fiat is selected as primary currency
**Screenshots**
<img width="379" alt="Screen Shot 2020-07-16 at 2 38 11 PM" src="https://user-images.githubusercontent.com/26778340/87635903-656c0a80-c772-11ea-938d-ad4c24019a9e.png">

**To Reproduce**
_Steps to reproduce the behavior_
1. Go to settings --> general --> select Fiat as primary currency
2. Open the menu and tap send
3 Press 'use max' button when prompted for amount
4. Press 'next', the error appears

**Expected behavior**
_A clear and concise description of what you expected to happen_

**Smartphone (please complete the following information):**

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by ibrahimtaveras00** [comment]
Reproduction steps for crash:
- Tap Send
- Choose any recipient address
- Use Max
- Tap next (Insufficient funds error)
- Change amount to lower so can go Next without error
- Confirmation screen opens, and app crashes

**Comment by EtDu** [comment]
@ibrahimtaveras00 same error in #1687 now merged
