### ISSUE TITLE
Why is Ledger Nano X support ignored?

### ISSUE THREAD

**Issue by ivan-prodanov** [MetaMask/metamask-mobile#1713]
Why are you guys NOT discussing your actions on this? Was added to v1 then got removed. This feature is heavily requested on every other non-dev platform and there's radio silence from you. Why?

**Comment by tobutridaz** [comment]
+10000000

**Comment by aaronovz1** [comment]
Any updates?

**Comment by kriegalex** [comment]
There is a main thread discussing that. They just acknowledged it a few hours ago. I think this one can be closed.

**Comment by gantunesr** [comment]
Check #1237 for more updates about the Ledger integration
