### ISSUE TITLE
Set up more caching for CircleCI

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-mobile#1722]
Currently a majority of the mobile `CircleCI` work is running `brew` in the mac machine. Another significant portion is re-installing CocoaPods.

These are just repetitive installing of dependencies, and cached by setting CircleCI up to save a folder between builds.

- [ ] Cache the brew folder. May be `/usr/local/Homebrew` per [this issue](https://discuss.circleci.com/t/caching-brew/21393/6).
- [ ] Cache the Cocoa Pods.

**Comment by gantunesr** [comment]
Mobile is not using CircleCI anymore
