### ISSUE TITLE
Android App Crashes when choosing sending gwei 

### ISSUE THREAD

**Issue by afmsavage** [MetaMask/metamask-mobile#1742]
**Describe the bug**
_A clear and concise description of what the bug is_

The metamask mobile app crashes every time you try to change the gas price of a web3 generated transaction

**Screenshots**
_If applicable, add screenshots or links to help explain your problem_

**To Reproduce**
_Steps to reproduce the behavior_
1. Go to uniswap and select a token you have not approved for their site.
2. Click on **Approve** $tokenname
3. Click on **Edit** for transaction fee
4. Click **Advanced** 
5. Select the **Gas Price** field ...crash

**Expected behavior**
_A clear and concise description of what you expected to happen_
the app not to crash!

**Smartphone (please complete the following information):**
 - Device: Pixel 3
 - OS: Android 10

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by EtDu** [comment]
Hello, thank you for the report! This bug has been fixed and will be included in the next release.
