### ISSUE TITLE
Release Bugs for v0.2.20

### ISSUE THREAD

**Issue by ibrahimtaveras00** [MetaMask/metamask-mobile#1743]
**Issue 1:**

Add address modal - text input field on send flow is overlapping CTA's

![Screen Shot 2020-07-31 at 1 16 38 PM](https://user-images.githubusercontent.com/41752922/89060150-84e96280-d330-11ea-9baf-eca385be5e64.png)

Steps:
- initiate send flow
- input a valid address
- tap the "Add this address to your address book" link

**Comment by estebanmino** [comment]
fix for that https://github.com/MetaMask/metamask-mobile/pull/1744

**Comment by ibrahimtaveras00** [comment]
**Issue 2:** 

on the "MetaMask Support" page on iOS there is and X to dismiss that page, but nothing happens when I tap it.  I do have the option to dismiss by swiping down (this could be confusing to users) 

This seems to only happen on iPhone's with notches (I'm currently on iPhone X) 

seen here = https://recordit.co/wxWaSogfyd

![image](https://user-images.githubusercontent.com/41752922/89067367-24145700-d33d-11ea-8d1d-747b34252f73.png)

steps: 
- go to the "Secure your wallet" view
- tap on "Why is it important?" 
- when the "Protect your wallet" modal pops up tap "Learn More"
