### ISSUE TITLE
duccum

### ISSUE THREAD

**Issue by loctai5279** [MetaMask/metamask-mobile#1745]
**Describe the bug**
_A clear and concise description of what the bug is_

**Screenshots**
_If applicable, add screenshots or links to help explain your problem_

**To Reproduce**
_Steps to reproduce the behavior_

**Expected behavior**
_A clear and concise description of what you expected to happen_

**Smartphone (please complete the following information):**

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by omnat** [comment]
@loctai5279 Was there a bug you wanted to report?
