### ISSUE TITLE
Warn users whenever an ENS name contains a homoglyph vulnerability

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-mobile#1747]
This is a mobile version of [this extension issue](https://github.com/MetaMask/metamask-extension/issues/9129)

An ENS name is a UTF-8 compatible string of text. That means there are many characters that have the same appearance, or homo-glyph.

This can cause some concerns when using an ENS name:
- Pasting an ENS name that looks correct could actually be wrong. [as tweeted recently](https://twitter.com/NepalBlockchain/status/1290153162007916544?s=19)
- Reverse-resolved ENS names could appear familiar but actually be deliberately crafted to be deceptive.

I had [mentioned this acceptance criteria in a previous issue](https://github.com/MetaMask/metamask-extension/issues/5525#issue-370263922), but a basic check with a vulnerable name and I cannot find any warning.

MyCrypto has a tool called [ens-validation](https://github.com/MyCryptoHQ/ens-validation) that can do the hard part of this already, we just need to design & display the appropriate warnings.

Acceptance criteria:
- Entering a homoglyph-impersonation name on the send screen `to` field should show a warning. Can verify with `vita‍lik.eth`, which is not the same as `vitalik.eth`.
- A confirmation screen showing an ENS name should also show a warning under any homoglyph-containing name. We could also simply not resolve a homoglyph-containing name.

Possible copy for the warning:
- This name has some deceptive letters in it that resemble other letters. It is probably trying to impersonate another well-known name. Did you get this name from someone you trust?

**Comment by cjeria** [comment]
Here are the latest designs 
https://www.figma.com/file/Ny0UospSv8UHgluAMnbbTE/Homoglyph-Warning?node-id=39%3A55

![image](https://user-images.githubusercontent.com/597770/107075715-7c2e8900-67b8-11eb-81a0-bcb0443c3a32.png)

**Comment by rickycodes** [comment]
this was handled in https://github.com/MetaMask/metamask-mobile/issues/2067
