### ISSUE TITLE
Seed phrase prompt blocking / not dismissable

### ISSUE THREAD

**Issue by pi0neerpat** [MetaMask/metamask-mobile#1760]
**Describe the bug**
Backup prompt blocks buttons, with no way to dismiss. 

**Screenshots**
![Screenshot_20200810-093340](https://user-images.githubusercontent.com/35622595/89790365-d55e7e00-daef-11ea-9c49-52c44d9744ab.png)

**To Reproduce**
1. Receive funds (can be testnet) on a clean installed wallet
2. Skip backing up seed phrase

**Expected behavior**
- The seed phrase prompt should be annoying, but not blocking functionality.
- Seed phrase prompt should be dismissable if I only have testnet funds
- Seed phrase prompt should always be dismissable in an "advanced/developer" settings menu

**Smartphone (please complete the following information):**
 - Device: Android
 - OS: v9
 - Version 0.2.19

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by ibrahimtaveras00** [comment]
Hey @pi0neerpat thanks for bringing up.  We actually improved this flow which should be available in our next upcoming release which will allow the banner to be dismissible; seen below:

![backup_banner](https://user-images.githubusercontent.com/41752922/89963719-5dd73e80-dc16-11ea-80bd-154f6b96adf6.gif)

**Comment by pi0neerpat** [comment]
Awesome!
