### ISSUE TITLE
Designs for Mobile Signing Screens 

### ISSUE THREAD

**Issue by bdresser** [MetaMask/metamask-mobile#177]
We need designs for signing screens
`eth_sign`, `personal_sign`, `signTypedData`

`eth_sign` and `personal_sign` (https://github.com/MetaMask/MetaMask/issues/169) are pretty straighforward, can re-use what the extension does 

<img width="200" alt="screen shot 2018-11-20 at 1 50 12 pm" src="https://user-images.githubusercontent.com/1016190/48795546-41210780-eccb-11e8-8556-2e67f1e2e5cf.png">

`signTypedData` (https://github.com/MetaMask/MetaMask/issues/170) needs to be able to handle nested data and has some extra info in the header. (Described in more detail in  https://github.com/MetaMask/metamask-extension/issues/5388, which will define the extension UI for signTypedData)

**Comment by ibrahimtaveras00** [comment]
This is finished
