### ISSUE TITLE
No INR option in Currency conversion

### ISSUE THREAD

**Issue by sebastiantf** [MetaMask/metamask-mobile#1777]
**Describe the usability problem**
The MetaMask Chrome extension has the option to select **INR** (**Indian Rupee**) in the **Currency conversion** settings. But the same is **not available** in the **MetaMask Mobile** mobile application. This would be really helpful for **Indian** users. This missing option also deviates from providing similar experience in both the mobile app and the Chrome extension.

**Screenshots**
![metamask-mobile-no-inr](https://user-images.githubusercontent.com/36922376/90408822-0299c600-e0c6-11ea-8156-a3c883fa3d0f.jpeg)

**Expected behavior**
Option to select **INR** (**Indian Rupee**) in the **Currency conversion** settings is to be allowed

------------------------------------------------------------------------------------------------------
_filled out after submission_

**User impact | Usage frequency | Feasibility scores**
_How important is this to the user, what the user wants to accomplish | Daily, weekly, monthly | Small, medium, large_

**Comment by rickycodes** [comment]
hi @sebastiantf,

thanks for the report!

looking at this a bit more closely I noticed we're actually missing a few conversions and they are:

```
Indian Rupee
FirstBlood
Ukrainian Hryvnia
SAI
```

I'll see about adding those

**Comment by rickycodes** [comment]
the four missing translations have now been added (and merged into `develop`) and will be available on next release
