### ISSUE TITLE
Blank Screen Forever after interacting with smart contract

### ISSUE THREAD

**Issue by beccon4** [MetaMask/metamask-mobile#1786]
**Describe the bug**
Metamask asks for fingerprint, then displays its menu for a fraction of a second and then shows a blank screen forever. No further interaction possible.

**Screenshots**
Short video:
https://wolke.miradata.de/index.php/s/CD3FH3JrwiwHQka

**To Reproduce**
1. Connect Metamask to a private blockchain
2. Deploy a simple ERC721 token smart contract there
3. send some collectibles to the address defined in Metamask (one has to set up the address and tokenid manually to include it)
4. try to send back the tokens to another address
5. try to interact with an web3 based web UI

In step 4 and 5 I was shown the message "insufficient funds" though my account on Metamask has enough (playground) Ethers. I can't tell for sure which step caused the application to lock as I repeated steps 4 and 5 a couple of times.

**Expected behavior**
User can interact with the smart contract

**Smartphone (please complete the following information):**
 - Device: Asus Zenfone X00TD
 - OS: Android 
 - Version 9

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by AlexJupiter** [comment]
Seems this issue is fixed.
