### ISSUE TITLE
Connect prompt not shown after unlock

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-mobile#1798]
Reproduction steps:
- on iOS
- Let metamask lock
- navigate to a site that uses walletConnect for logon, like mooniswap.exchange
- click connect wallet, walletconnect, metamask
- MetaMask opens, requires faceID

Expected:
- connect prompt is shown

Result:
- At first just wallet screen is shown, I had to switch apps to another and back to metamask before it showed the connect screen.

**Comment by rickycodes** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Links are lost when unlocking](https://trello.com/c/0YppNCHW/246-links-are-lost-when-unlocking)
