### ISSUE TITLE
"Add to favorites" shows blank URL

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-mobile#1799]
**Describe the bug**
When I click "Add to favorites" on a new site, I get the title auto-filled, but the URL is blank. This requires the user to enter the URL manually, and saving without filling it out results in a blank bookmark that resolves to a blank page.

**To Reproduce**
1. Go to site
2. Click bottom right "..." button
3. Click "Add to favorites"
4. Notice the "Url" field is empty.

**Expected behavior**
The "url" field should always be populated from the current page.

**Smartphone (please complete the following information):**
 - Device: iPhone 11
 - OS: iOS
 - Version v1.0

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by ibrahimtaveras00** [comment]
This issue seems fixed on both OS's on latest version, v1.0.8
