### ISSUE TITLE
Links are lost when unlocking

### ISSUE THREAD

**Issue by jacobcantele** [MetaMask/metamask-mobile#1804]
**Describe the bug**
When metamask is the default browser on Android, and the metamask app is currently in a locked state, clicking a link in an external app for example an email app, results in the user being prompted to unlock metamask, but after unlocking, the original link that the user clicked is gone.

**To Reproduce**

1. Set MM to default browser 
2. Click a link in your email 
3. Be prompted to unlock 
4. See the link you followed is lost

**Smartphone (please complete the following information):**
 - Device: OnePlus 8 Pro
 - OS: Android 10, Oxygen OS 10.5.13
 

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by omnat** [comment]
Related to #1786 #1798
