### ISSUE TITLE
Could not encrypt data for service com.metamask

### ISSUE THREAD

**Issue by agnelvishal** [MetaMask/metamask-mobile#1811]
**Describe the bug**
Getting this error "Could not encrypt data for service com.metamask" during login. 

**Screenshot**

![Screenshot_2020-09-02-20-57-40-766_io metamask](https://user-images.githubusercontent.com/10105332/92004559-f9fced00-ed5f-11ea-9e51-bb795b02f076.jpg)

**Smartphone :**
 - Device: Redmi Note 7s 
 - OS: Android 9 PK.Q1

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by omnat** [comment]
Hi @agnelvishal, thanks for reporting! Are you able to login to the wallet despite seeing this error?

We are trying to find what the issue is - could you check if you have enough space in your phone? This error might be shown when running low on space too.

**Comment by agnelvishal** [comment]
There is 2.5 gb space free on the phone. Not sure if it is enough. I am unable to login with the error.
