### ISSUE TITLE
Cannot remove favorite if URL is blank

### ISSUE THREAD

**Issue by kenccwong** [MetaMask/metamask-mobile#1818]
**Describe the bug**
Due to issue #1799 a favorite with a blank URL is added. However clicking on remove does not delete the entry even after clicking on OK on "Remove favorite" pop up

**To Reproduce**
1. Reproduce #1799 
2. Save the entry as a favorite
3. Attempt to remove the favorite entry

**Expected behavior**
Blank URL favorite can be removed

**Smartphone (please complete the following information):**
 - Device: Huawei Mate 20
 - OS: Android 10
 - App Version v1.0.2 (36)

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by ibrahimtaveras00** [comment]
@kenccwong this issue has since been resolved in our latest version 1.0.8 on both OS's

We no longer allow the bookmark to be saved without a URL.  Please reopen if you continue to experience any issues.
