### ISSUE TITLE
Mobile app crashes when using SEND MAX button

### ISSUE THREAD

**Issue by rdymac** [MetaMask/metamask-mobile#1820]
**Describe the bug**
Mobile app crashes when using SEND MAX button on a very small Dai send, if the amount to be maxed out is the fiat one (Fiat is selected as Primary Currency).

If you switch the currency used before SEND MAX in the same Send view to native Dai amount, the amount gets filled correctly and the app doesn't crashes.

**Screenshots**
![mobile_app_issue1](https://user-images.githubusercontent.com/2995401/92322813-c954d600-f033-11ea-8421-c4c6c013a0fc.jpg)

.

![mobile_app_issue2](https://user-images.githubusercontent.com/2995401/92322815-cce85d00-f033-11ea-8a99-4e04b515b526.jpg)

.

![mobile_app_issue3](https://user-images.githubusercontent.com/2995401/92322999-66643e80-f035-11ea-89e9-9069e4faeb1a.gif)

.

**To Reproduce**
Account 1 > Dai > Send > tap on SEND MAX > app crashes

**Smartphone (please complete the following information):**
 - Device: iPhone XS
 - OS:  iOS 13.6.1
 - App Version v1.0.1 (522)

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by EtDu** [comment]
Hey! I've attempted to reproduce with primary currency as fiat and the exact same Dai balance with no luck. Are you consistently encountering this bug? If so, could you please share your state logs?
Settings > Advanced > Download State Logs

**Comment by omnat** [comment]
Is this still happening @rdymac?

**Comment by ibrahimtaveras00** [comment]
I have not been able to reproduce on mainnet with DAI, ETH and MANA on latest version v1.0.8.  Not sure if you're still able to reproduce this one @rdymac, I'd say reopen if issue still persists for you.
