### ISSUE TITLE
Can't use SEND MAX on small ETH amounts

### ISSUE THREAD

**Issue by rdymac** [MetaMask/metamask-mobile#1821]
**Describe the bug**
There is only 0.000147 ETH funds in the Account, so the send function: Account > ETH > Send > SEND MAX , doesn't fill out any amount for either ETH nor Fiat value.

**Screenshots**

![mobile_app_ETH_issue3](https://user-images.githubusercontent.com/2995401/92323178-e17a2480-f036-11ea-8948-bedb6e6dddf9.jpg)

.

![mobile_app_ETH_issue2](https://user-images.githubusercontent.com/2995401/92323181-e6d76f00-f036-11ea-949e-0a6e28ddfb34.jpg)

.

![mobile_app_ETH_issue1](https://user-images.githubusercontent.com/2995401/92323187-f35bc780-f036-11ea-8c5c-c22362a6ba54.gif)

**To Reproduce**
_Steps to reproduce the behavior_
1. Have an account with 0.000147 ETH funds
2. go to Account > ETH > Send > SEND MAX
3. Switch between Fiat and ETH amount using the button below
4. See error on ETH never been filled out to the maximum

**Expected behavior**
_A clear and concise description of what you expected to happen_

**Smartphone (please complete the following information):**
 - Device: iPhone XS
 - OS:  iOS 13.6.1
 - App Version v1.0.1 (522)

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by EtDu** [comment]
The reason why it doesn't work is because the total account balance minus the total estimated gas is below zero, therefore the transaction cannot pass through. This is intended behavior but do we want to change to allow users to get past this screen? They will any be met with an insufficient funds message.

WDYT @omnat

**Comment by omnat** [comment]
Option 1: We could give user an error on this screen - `Amount too low, transaction won't complete`
or
Option 2: Let user go past this screen with max amount filled in. And show `Insufficient funds for network fee, get ETH to continue. Buy now` error on next screen and disable confirming.

@cjeria what do you think? I am leaning towards Option 2.

**Comment by EtDu** [comment]
Option 2 makes more sense. The user should be allowed to try their transaction with an extremely low gas even though it's almost sure to fail

**Comment by cjeria** [comment]
Yes, option 2 sounds good to me.
