### ISSUE TITLE
show all accounts when restoring wallet using seed phrase

### ISSUE THREAD

**Issue by naaitsabes** [MetaMask/metamask-mobile#1824]
**Describe the usability problem**

When restoring my account with my seed phrase, not all of my linked wallets showed up. I had to create new wallet and then my old wallet was generated with the funds inside. I had no ETH in that address, only assets.

**Screenshots**
_If applicable, add screenshots or links to help explain the issue_

**Expected behavior**

I expected to have all of my wallets restored directly. The alternative is to put up a message in the UI for the user making it clear that the generation of new wallets goes according to a fixed algorithm so that they understand that they need to press generate new wallet to restore their old wallets. Maybe if this is only applicable when the user has no ETH in that account, it could only be shown then.

------------------------------------------------------------------------------------------------------
_filled out after submission_

**User impact | Usage frequency | Feasibility scores**

It is a usability problem in the restoring wallet section of your wallet. I would deem it quite important and it could potentially save a lot of help requests on different fora.

**Comment by omnat** [comment]
Thanks for reporting! We are working on fixing this.
