### ISSUE TITLE
Android: Security: Cannot paste password into password creation page.

### ISSUE THREAD

**Issue by MicahZoltu** [MetaMask/metamask-mobile#1826]
**Describe the bug**
On the Create Password activity, I am unable to long-press on the password field to paste a password.  No matter how long I long-press, the paste option never appears.

This is a security issue because it means that users cannot use a password manager, they must use a human memorized password (known to be terrible for security).

**To Reproduce**
_Steps to reproduce the behavior_
1. Copy a password from somewhere (e.g., password manager)
2. Get to the Create Password screen.
3. Try to paste the password.
4. Notice that you cannot.

**Expected behavior**
I can paste a password into the password creation field.

**Smartphone (please complete the following information):**
 - Device: OnePlus
 - OS: Android
 - App Version: 1.0.2

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by rickycodes** [comment]
looks like https://github.com/MetaMask/metamask-mobile/issues/1567 (a known issue). I will take a look at patching this shortly
