### ISSUE TITLE
Transiction send error "invalid sender" when sending over private Ethereum network

### ISSUE THREAD

**Issue by pavelkrolevets** [MetaMask/metamask-mobile#1832]
**Describe the bug**

Mobile Metamask fail to send ASK over https:// endpoint of another proof-of-authority network. Error - invalid sender. This indicates that the signature is wrong. It seems the signing function cant generate right sing when chainID !== networkID for private networks. I also tested when chainID == networkID on my local network on

Network Name: ASK Mainnet
New RPC URL: https://blockchain-api-mainnet.permission.io/rpc
ChainID: 222
Symbol: ASK
Block Explorer URL: https://explorer.permission.io/

I am able to receive ASK in the iOS and Android mobile apps. But when I try to send from iOS or Android to another Metamask wallet I receive the error: "Transaction Error - Object [Object]" with no additional information about why it failed. 

**Screenshots**
![image](https://user-images.githubusercontent.com/2865727/93208150-edc05900-f77d-11ea-8f0f-fc8373fb1025.png)
![image](https://user-images.githubusercontent.com/2865727/93208191-06307380-f77e-11ea-88b0-acc5e5b67cd1.png)

**To Reproduce**
1. Add network ASK mainnet in the Mobile Metamask with parameters
Network Name: ASK Mainnet
New RPC URL: https://blockchain-api-mainnet.permission.io/rpc
ChainID: 222
Symbol: ASK
Block Explorer URL: https://explorer.permission.io/
2. Send native tokens to another account.

Another way:
1. Run local private network with chainID !== networkID
2. Send tokens to another account

**Expected behavior**
Transaction should be accepted to the network, but get error - invalid sender. Which indicates that the signature is wrong despite that chainID is provided (222), but networkID is different (2221).

**Smartphone (please complete the following information):**
 - Device: iPhone 6 Plus
 - OS: iOS 13.6
 - App Version v1.0.1(522)

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by pavelkrolevets** [comment]
This maybe related [#1820](https://github.com/MetaMask/metamask-extension/issues/1820)

**Comment by evanliuchina** [comment]
Got exactly the same problem. Did you find any way to work around @pavelkrolevets ?

**Comment by iquidus** [comment]
bump. 

This impacts all networks in which networkId and chainId do not match. Not just private nets, but live public nets also (e.g ethereum classic & ubiq). Signing transactions with networkId is invalid behavior (not to spec), producing invalid transactions (unless the Ids happen to match).

Users can receive funds to metamask mobile on these networks but only to have it stranded as they can't produce valid transactions. Requiring them to import recovery phrase into an alternative wallet to recover said funds.

**Comment by iquidus** [comment]
First time looking at the mobile code but here is one such occurrence (and possibly the main culprit?): https://github.com/MetaMask/metamask-mobile/blob/develop/app/components/UI/PaymentRequest/index.js#L292

**Comment by jyap808** [comment]
Please back port the fix from the main Metamask browser extension.
Network ID <> Chain ID

Thanks
