### ISSUE TITLE
Gas too low error not showing up on wallet transactions

### ISSUE THREAD

**Issue by EtDu** [MetaMask/metamask-mobile#1834]
**Describe the bug**
"Gas price extremely low" error message in custom gas controls is not showing up properly in regular wallet transactions. Does show up in dApp transactions.

**Screenshots**
_If applicable, add screenshots or links to help explain your problem_

**To Reproduce**
_Steps to reproduce the behavior_

**Expected behavior**
_A clear and concise description of what you expected to happen_

**Smartphone (please complete the following information):**
 - App Version [e.g. 1.0.0] - find version number in app from Settings > About MetaMask

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by nicc938** [comment]
ในวันที่ อ. 15 ก.ย. 2020 20:05 Etienne Dusseault <notifications@github.com>
เขียนว่า:

**Comment by nicc938** [comment]
Same this​?

ในวันที่ อ. 15 ก.ย. 2020 20:17 Nicc Lee <juab.leela@gmail.com> เขียนว่า:

**Comment by danigorbaciov** [comment]
for transfer 0,03 ETH - spent gas 0.03 ETH IN ANY SMART CONTRACT WALLET .  to metamask any transfer 0.01 eth
