### ISSUE TITLE
24 word seed phrase

### ISSUE THREAD

**Issue by andreaslillevangbech** [MetaMask/metamask-mobile#1838]
**Describe the usability problem**
_A clear and concise description of the specific usability issue_

**Screenshots**
_If applicable, add screenshots or links to help explain the issue_

**Expected behavior**
_If possible, a clear and concise description / resolution of what you expected to happen_

------------------------------------------------------------------------------------------------------
_filled out after submission_

**User impact | Usage frequency | Feasibility scores**
_How important is this to the user, what the user wants to accomplish | Daily, weekly, monthly | Small, medium, large_

**Comment by nicc938** [comment]
Yes ser

**Comment by andreaslillevangbech** [comment]
It doesnt accect 24 word phrases. Only works with 12 in the mobile app
