### ISSUE TITLE
General Help Debugging Webapp

### ISSUE THREAD

**Issue by LucasMoskun** [MetaMask/metamask-mobile#1842]
I do not know if this is the right place to post this, but I figure I might as well get the conversation started somewhere.

 I have been developing an app that works fine in brave/chrom/firefox on mac os and windows. All of the non-web3/metmask functionality works great on chrome for android. However on metmask my basic react functionality doesn't seem to be working right. (also, some really weird behaviour when connecting to xDai custom rpc, but that's another story). 

So really, as user, who is a developer, I would love a way to see javascript logging/debugging similar to the "developer window" in desktop browsers. Does this exist? How are people debugging their web apps for the metamask mobile version?  

I understand this is probably trivial/basic android development stuff, but couldn't find info elsewhere. I imagine other newbies to the space might be interested in a few pieces of advice. 

Thanks for bringing metamask mobile to life!

**Comment by EtDu** [comment]
@LucasMoskun Thanks for your question.

We're in talks about his right now. At the moment you cannot debug WebViews (browsers) of apps on the google play or apple app store. We intend to keep it this way for security purposes. If you wish to debug the webview, you must clone the MM mobile repo and run the development build on a simulator (iOS or Android), then follow these instructions https://blog.vuplex.com/debugging-webviews

For android, you'll need to add the line shown here https://blog.vuplex.com/debugging-webviews until we get this merged

Our plans

**Comment by EtDu** [comment]
To test your react functionality I would recommend just using the chrome dev tools with the mobile phone view
<img width="96" alt="Screen Shot 2020-09-22 at 1 10 04 PM" src="https://user-images.githubusercontent.com/26778340/93845923-1d6ae600-fcd5-11ea-860b-fa320f56c095.png">

**Comment by LucasMoskun** [comment]
Awesome, thank you for this advice! Seems like plenty to get me going in the right direction. Long live MetaMask!
