### ISSUE TITLE
Unable to resolve module `crypto` from `node_modules\sjcl\sjcl.js`: crypto could not be found within the project.

### ISSUE THREAD

**Issue by ansalbeeone** [MetaMask/metamask-mobile#1849]
error Unable to resolve module `crypto` from `node_modules\sjcl\sjcl.js`: crypto could not be found within the project.

If you are sure the module exists, try these steps:
 1. Clear watchman watches: watchman watch-del-all
 2. Delete node_modules: rm -rf node_modules and run yarn install
 3. Reset Metro's cache: yarn start --reset-cache
 4. Remove the cache: rm -rf /tmp/metro-*. Run CLI with --verbose flag for more details.
Error: Unable to resolve module `crypto` from `node_modules\sjcl\sjcl.js`: crypto could not be found within the project.

**Comment by taylorjdawson** [comment]
@ansalbeeone Getting the same error currently

**Comment by austinmarkus** [comment]
I Know this is old, but for the next person who finds this via a search...

edit shim.js and at the bottom un-comment 
require('crypto')

Re-build and it should work.

**Comment by alfangr** [comment]
i got a different error but I think there is still a similar issue,

> unable to resolve module crypto from .../node_modules/ethereumjs-wallet/dist.browser/index.js crypto could not be found within the project

require('crypto') on the shim.js already commented, anyone can help to solve the issue?
