### ISSUE TITLE
window.ethereum is undefined again

### ISSUE THREAD

**Issue by happypsyduck** [MetaMask/metamask-mobile#1875]
**Describe the bug**
On MetaMask mobile, sometimes the window.ethereum variable does not load. This can be seen across multiple sites. It is not consistent and loads sometimes. Even with a time delay, the variable will sometimes not load. It appears the application fails to inject javascript code. This is for the latest version on Android v1.0.3 (37)

**To Reproduce**
I know it's a year+ later, but MM Mobile can't load window.ethereum at all on iOS.
Totally vanilla HTML and JS (pulled from MM's documentation) and nothing gets loaded:

```
if (window.ethereum) { handleEthereum();
} else {
	window.addEventListener('ethereum#initialized', handleEthereum, {
        once: true,
    });
    setTimeout(handleEthereum, 3000);
}
function handleEthereum() {
	const { ethereum } = window;
	if (ethereum) {
		console.log('Ethereum successfully detected!');
	}
}
```

_Originally posted by @EvilJordan in https://github.com/MetaMask/metamask-mobile/issues/924#issuecomment-698764611_

**Expected behavior**
window.ethereum should load

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user? Unusable until fixed
- Is this visible to all users? Yes

**Comment by happypsyduck** [comment]
So it continues to happen but not as frequently as before if I check for MetaMask after the window has fully loaded: window.load, vs only after the DOM is loaded.

Closing as the failure rate is acceptable.

**Comment by EvilJordan** [comment]
> Closing as the failure rate is acceptable.

Absurd.

**Comment by testaccount49328** [comment]
This still is not working ..connects about 1% of the time.

**Comment by juscamarena** [comment]
I'm trying to upgrade our web3 lib to ethers.js, but it seems when upgrading compatibility is broken and I no longer see window.web or window.ethereum injected when trying out our site on metamask mobile.

It works fine when using metamask on a desktop browser...

**Comment by jamesBsmyth** [comment]
Tried about everything on my end, including the solution mentioned here: https://docs.metamask.io/guide/mobile-best-practices.html#the-provider-window-ethereum

I am:

-Using the "ethereum#initialized" listener from the above link
-Running all ethereum init scripts after window.load
-checking for window.ethereum long after page load (for troubleshooting purposes) 

Even after the window is fully loaded I am unable to see window.ethereum. Does this problem persist for other users or is it just me? When I reload the page completely, window.ethereum is grabbed just fine. On initial page load it is completely unavailable.

**Comment by EvilJordan** [comment]
@jamesBsmyth Do you have a Content Security Policy? If so, that's the issue. MMM breaks completely with **ANY** CSP present, even if it allows all access.

**Comment by adshodgson** [comment]
Having this same issue, is there any update on this?

**Comment by EvilJordan** [comment]
@adshodgson This is what solved it for me: https://github.com/MetaMask/metamask-mobile/issues/2015#issuecomment-767627301

**Comment by 4skinSkywalker** [comment]
Maybe this thing is related to what I show here: [https://github.com/MetaMask/metamask-mobile/issues/3309](https://github.com/MetaMask/metamask-mobile/issues/3309)

**Comment by dev-tom-0108** [comment]
I have an issue with my Huawei phone.
I can't detect the `window.ethereum`

**Comment by tomtomcrypto** [comment]
> I have an issue with my Huawei phone. I can't detect the `window.ethereum`

Yep same, doesn't work on Metamask App & any Android browser on my Huawei. Hoping it is just that phone somehow...

**Comment by Pacheco95** [comment]
Unfortunately I'm facing the same problem. I was unable to get the provider through window `ethereum#initialized` event neither from `window.ethereum`.

**Comment by gnomesaregreat** [comment]
iPhone doesn't work for me  any one also have this problem?
