### ISSUE TITLE
No Error thrown on transaction rejection

### ISSUE THREAD

**Issue by sparrowDom** [MetaMask/metamask-mobile#1880]
**Describe the bug**
When performing a normal contract call user is presented with Confirm Transaction window. When user rejects that transaction an Error should be thrown. This works well in Metamask browser extension but not in Metamask mobile app (on any of the 3 devices). After the user rejects the transaction the code execution is still stuck on the contract call code line.

Interestingly on all devices if I exit the app (send it to background) and re-focus it the exception with the correct error is thrown immediately.

**To Reproduce**
- Do any contract call where user needs to approve the transaction
- reject the transaction
- see if the error has been thrown

**Expected behavior**
I would expect the error to be thrown when the user rejects the transaction

**Smartphone (please complete the following information):**
**Device 1:**
 - Device: iPhone6
 - OS: IOS 12.4
 - App Version v.1.0.1 (522)

**Devices 2&3:**
 - Device: OnePlus 6t & OnePlus 8Pro
 - OS: Android Oxygen 10.3.5 & Android Oxygen 10.5.11
 - App Version v1.0.3 (37)

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by tab00** [comment]
> When performing a normal contract call user is presented with Confirm Transaction window. When user rejects that transaction an Error should be thrown. This works well in Metamask browser extension but not in Metamask mobile app (on any of the 3 devices). After the user rejects the transaction the code execution is still stuck on the contract call code line.

I've just experienced this issue yesterday. Is it meant to have been fixed already?

**Comment by sparrowDom** [comment]
> I've just experienced this issue yesterday. Is it meant to have been fixed already?

Not that I would know of unfortunately

**Comment by anxiubin** [comment]
same here

**Comment by liyueran-bj** [comment]
same here

**Comment by liyueran-bj** [comment]
hello,How was it finally resolved? @sparrowDom

**Comment by Kamikozz** [comment]
Yeah, the same.
1. Send contract.methods.approve().send({ from: '...' }) opens window with accept/reject.
2. Then Reject
3. Sagas that are listening for `Errors` in the `catch` block is ignored
