### ISSUE TITLE
Address bar being treated as a text field instead of an URL field

### ISSUE THREAD

**Issue by jacobc-eth** [MetaMask/metamask-mobile#1900]
**Describe the bug**
On Android, trying to type a website into the address bar results in spaces being added to the URL whenever the user types a period. The field is being recognized as a text field, so it triggers keyboard autocorrect behavior.

**Expected behavior**

This field should expect exact input and disable the user's autocorrect.

**Smartphone (please complete the following information):**
 - Device: OnePlus 8 Pro
 - OS: Android 10

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by jacobcantele** [comment]
![signal-2020-10-18-214515](https://user-images.githubusercontent.com/10467486/96395859-576fc080-118b-11eb-8f0b-c811e5a97b78.jpeg)

**Comment by rickycodes** [comment]
@jacobcantele I've tested this with the default android keyboard and adding a full stop does not unintentionally produce a space:

![url](https://user-images.githubusercontent.com/675259/96826385-462fe980-1401-11eb-9717-4eb31f6abce1.gif)


i noticed you're using Microsoft SwiftKey and I am thinking that's likely what's causing the behaviour you're seeing.

we could look at changing the keyboard type (maybe there's one that wouldn't do this in swift key without altering the behaviour when using the regular keyboard?).
