### ISSUE TITLE
ChainId not found?

### ISSUE THREAD

**Issue by bachlongkocanh** [MetaMask/metamask-mobile#1906]
**Describe the bug**
Dapps that need chainId will fail.
Example: I custom network Binance smart chain to use for `pancakeswap.finance`.
When entering Dapps, the error is ` contract address not found in network`. I try to log `ethereum.chainId` it return `undefined`.

**Screenshots**
<img width="1190" alt="Screen Shot 2020-10-22 at 14 32 47" src="https://user-images.githubusercontent.com/28125294/96839987-17069000-1474-11eb-9ade-c6b9aa77d5bf.png">

**To Reproduce**
_Steps to reproduce the behavior_
1. Custom Binance smart chain
2. Click on 'Browser'
3. Enter 'pancakeswap.finance'
4. Open webview debug

-------------------------------------------------------------

**Comment by matYang** [comment]
similar problem, I logged window.ethereum.chainId and it is undefined

**Comment by matYang** [comment]
as a temp fix, falling back to RPC method `await window.ethereum.request({ method: 'eth_chainId' });` does return the chainId

**Comment by ochikov** [comment]
ethereum.on('chainChanged') event does not return custom network Binance chainId also.

**Comment by 0x20bf** [comment]
can't get chainId .  Why?

**Comment by bachlongkocanh** [comment]
you can use ezDeFi
