### ISSUE TITLE
senTransaction promise doesn't reject when transaction rejected in the wallet

### ISSUE THREAD

**Issue by Velenir** [MetaMask/metamask-mobile#1907]
**Describe the bug**
if I submit a transaction on dapp side and reject on the MetaMask side the promise `web3.eth.sendTransaction() or provider.request({...})` never rejects.

Same happens whether I use the injected provider `window.ethereum` or connect through WalletConnect.

This makes it impossible to know if the user rejected transaction or not, unless I implement a reasonable timeout or some such.

**To Reproduce**

[codesandbox reproduction](https://codesandbox.io/s/sample-ethsendtransaction-with-providerrequest-4um0i?file=/src/App.js)

1. Go to https://4um0i.csb.app/
2. Connect however you wish
3. Submit a tx
4. Reject tx in MetaMask wallet
5. See that nothing happens

**Expected behavior**
When tx is rejected on MetaMask side, I expect to see an error displayed.
It works perfectly with desktop MetaMask and just about any other wallet.

Desktop MetaMask gives this error `MetaMask Tx Signature: User denied transaction signature.`

**Smartphone (please complete the following information):**
 - Device: Lenovo Tab 4 Plus
 - OS: Android 7
 - App Version 1.0.4

-------------------------------------------------------------

**Comment by ScorpionKing** [comment]
I have the same problem
