### ISSUE TITLE
BN from scientific notation errror reported on reddit.

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-mobile#1910]
https://www.reddit.com/r/Metamask/comments/jho92x/audio_issues_metamask_wont_let_me_transfer_audio/?utm_source=share&utm_medium=ios_app&utm_name=iossmf

**Comment by randymetamask** [comment]
@EtDu @rickycodes wasn't this _BigNumber or BN.js_ issue the one fixed on https://github.com/MetaMask/metamask-mobile/pull/1889 ?

**Comment by danfinlay** [comment]
Looks like it to me. Thanks Randy!
