### ISSUE TITLE
Incorrect values on txn details and payment request deeplink

### ISSUE THREAD

**Issue by ibrahimtaveras00** [MetaMask/metamask-mobile#1914]
**Describe the bug**
When sending more than 999 tokens, there are 2 noticeable issues 

- Issue 1: 
txn details show incorrect value

![image](https://user-images.githubusercontent.com/41752922/97237129-f82e3380-17bc-11eb-9e76-b082c1925457.png)

- Issue 2: 
When attempting to send more than 999 tokens in a payment request, the value is incorrect when the confirm view loads

![image](https://user-images.githubusercontent.com/41752922/97237221-21e75a80-17bd-11eb-8cfa-eb32952bd448.png)

Issue 2 currently is broken on playstore, once https://github.com/MetaMask/metamask-mobile/pull/1877 is merged into develop, you should be able to at least load the deeplink to get to the confirm view

**To Reproduce**
_Steps to reproduce the behavior_
to reproduce Issue 2, create a request for more than 999 of any ERC20 token that you want 
or use my example by scanning the QR code in the above screen shot 

for issue 1, once you actually send the tokens, look at the txn details total amount value

**Expected behavior**
For issue 1= the txn details should display the correct value

For issue 2 = the deeplink should have the correct requested value amount

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by roo-shy** [comment]
>> possible example from customer: https://consensys.zendesk.com/agent/tickets/65204

**Comment by ibrahimtaveras00** [comment]
@omnat I already added this one to the backlog

**Comment by roo-shy** [comment]
[#65204](https://consensys.zendesk.com/agent/tickets/65204) ^^

**Comment by ahsimon2** [comment]
I have a different display problem that Roo-shy thought might be related.   However, I am using a Mac Air laptop with the browser extension on chrome.
I have been DCA ing into a new token called eXRD using a uniswap pair called USDC-eXRD.
Most of the transactions appear to complete properly.  except about one in four incorrectly display 0 EXRD received.  The correct amount of eXRD is included in the total, and the etherscan display of the transaction looks like it completed properly.  Attached are some relevant screenshots.  The first is when I pull up the list of assets in my Metamask wallet, and then display the list of transactions for eXRD. 
![Screen Shot 2020-12-01 at 8 52 35 AM](https://user-images.githubusercontent.com/40777712/100768209-d75a8e80-33b7-11eb-9073-df29fd7c561f.png)
![Screen Shot 2020-12-01 at 9 04 18 AM](https://user-images.githubusercontent.com/40777712/100768218-d88bbb80-33b7-11eb-8557-fe21bba8f3fa.png)
![Screen Shot 2020-12-01 at 9 02 58 AM](https://user-images.githubusercontent.com/40777712/100768234-dc1f4280-33b7-11eb-89ba-6b52dd1d3d94.png)

**Comment by omnat** [comment]
Possibly related #2017

**Comment by ahsimon2** [comment]
unrelated issue and github comment had been removed.
