### ISSUE TITLE
Frontend: As an internal team member, I can access Swap feature from my wallet

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-mobile#1919]
Entry point to use swaps is from the wallet view of mobile. Available only on dev build for internal testing.

Notes:
- This feature should be on a dev build (different than mobile production build) so users don't see it, plus we don't cause prod issues due to merge conflicts. 
- Maintain a dev build that's includes prod version changes, so merge conflicts are QA'd and fixed early.

**Comment by omnat** [comment]
https://www.figma.com/file/VVjoLHG6X74lXmh6CN3r7H/Swaps?node-id=608%3A1394
