### ISSUE TITLE
TypeError: undefined is not an object - in what appears to be the mobile in-browser.

### ISSUE THREAD

**Issue by randymetamask** [MetaMask/metamask-mobile#1920]
**Describe the bug**
Troubleshooting and waiting for users' reply.  

Cases: 60663, 61177, 60832

**Screenshots**
![case60663_4A31C001-A0B7-4882-BCEB-9BDBDEE6F97A](https://user-images.githubusercontent.com/72138609/97420540-bc55b400-190b-11eb-85ef-22c609374f6f.png)

**To Reproduce**
_Steps to reproduce the behavior_

**Expected behavior**

**Smartphone (please complete the following information):**
 - Device: 
 - OS: iOS, Android
 - App Version 1.0.4

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by broccolirabe9** [comment]
I'm having issues with this as well, I tried accessing Uniswap and this popped up. Tried deleting and reinstalling the app same error. Was anyone able to show how to fix this?

**Comment by alienalepsy** [comment]
I have had the same issue and reported to Metamask support. Waiting for a fix or explanation on why this is happening
