### ISSUE TITLE
Swaps controller: define API links, and what to do differently than extension swaps controller

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-mobile#1921]
Goal: to apply our learnings from extension swaps work to build an improved swaps controller in MM mobile. In future, extension could migrate to this controller.

**Comment by estebanmino** [comment]
https://app.zenhub.com/workspaces/mobile-repos-5f984938ddc0e4001d4b79cb/issues/metamask/metamask-mobile/1933
