### ISSUE TITLE
Frontend: As an internal user, I want to select the tokens I want to exchange

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-mobile#1922]
- Re-use components like keypad, token list view
- Order list of 'Convert from' and 'Convert to' tokens in the easiest way (e.g., default/alphabetical order)
- Allow selecting tokens from the list only (no search bar)
- Keep slippage amount un-editable (default to 1%)

**Comment by estebanmino** [comment]
https://app.zenhub.com/workspaces/mobile-repos-5f984938ddc0e4001d4b79cb/issues/metamask/metamask-mobile/1939
