### ISSUE TITLE
Frontend: Query for the best quote available for the swap and show it as a result

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-mobile#1927]
- Fetch the best quote from the API
- Use existing loading spinner while retrieving the quote info
- Show the best quote on resulting screen
- Re-use the 'Primary' button component for the button that submits the swap transaction (instead of the slider)
- IF there's no quote found for 15 seconds, show the 'No quotes available' error

**Comment by estebanmino** [comment]
https://app.zenhub.com/workspaces/mobile-repos-5f984938ddc0e4001d4b79cb/issues/metamask/metamask-mobile/1944
