### ISSUE TITLE
Disable fiat values when user is connected to a custom or testnet RPC

### ISSUE THREAD

**Issue by dpazdan** [MetaMask/metamask-mobile#1929]
**Describe the bug**
Users should not see Ethereum mainnet fiat values of a token they have, unless they are on the Ethereum mainnet.  If they are on a testnet or other custom rpc chain, the fiat value should **only** display if it is in fact the value of those tokens on that chain.

Related issue on extension: https://github.com/MetaMask/metamask-extension/issues/9749
support ticket # 60926

**Expected behavior**
No fiat value shows, and the option to set fiat as default is disabled on custom networks.

**Comment by dpazdan** [comment]
this seems to be a good solution https://github.com/MetaMask/metamask-extension/issues/9749#issuecomment-718166452

**Comment by dpazdan** [comment]
also the settings section should not say "ETH" value, it should maybe say primary token value? since it is different on different chains? 
![image](https://user-images.githubusercontent.com/16330048/97489131-26cb1c00-192d-11eb-8837-5209642399c2.png)

**Comment by tze42** [comment]
Regarding - 'Primary Currency' - I also think it shouldn't be disabled if there is no exchange rate available.  
In case of an available value on a custom chain (e.g. xDai Chain), I would suggest to select between 'Native' and 'Fiat'.
