### ISSUE TITLE
window.ethereum missing in Android app (CSP blocked?)

### ISSUE THREAD

**Issue by jurosh** [MetaMask/metamask-mobile#1931]
**Describe the bug**
On IDEX website (eg. https://exchange.idex.io/support/check) there is no `window.web3` or `window.ethereum` injected.

See "Unlocked Wallet" section and `Software Wallet Check - New Web3Ethereum: NO, Older Web3: NO` which is reading `window` values.

**To Reproduce**
1. Open https://exchange.idex.io/support/check or https://exchange.idex.io/unlock
2. See that metamask is not injected on the webpage

**Smartphone:**
 - OS: Android
 - App Version `v1.0.5 (39)`

**Sorry, but no more information**

I don't see any error in console (being recorded after app started), but there might be something hidden cause I was not able to use full inspector using remove WebView debugger (https://github.com/MetaMask/metamask-mobile/issues/1226).

I suspect that there might an issue with [CSP](https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP) which is blocking scripts which Metamask wants to inject. But cannot verify this issue without full console output.

**Comment by mila1808** [comment]
I confirm that I also encounter this issue with Metamask browser only on Android while everything is fine on iPhone.
I have added some debug info and I clearly see that the `web3` is not injected. Consequently, it is always `undefined`

**Comment by rekmarks** [comment]
The provider will not always be available on page load in mobile. Can you please check if using `@metamask/detect-provider` resolves your issue? See our documentation for details: https://docs.metamask.io/guide/mobile-best-practices.html#the-provider-window-ethereum

**Comment by rekmarks** [comment]
Related: #1956

**Comment by jurosh** [comment]
Switched to `@metamask/detect-provider` but same result.

**Comment by jurosh** [comment]
When can we expect this to be released ? No change so far, v1.0.8 (41) on Android.

**Comment by rekmarks** [comment]
@jurosh, it will be fixed in `v1.0.9`, which is almost ready. It should be out in a matter of days. I recommend watching releases for this repository, to receive a notification when it's ready. Keep in mind that it will still take some time for the new version to appear on mobile app stores after the release is prepared.

**Comment by EvilJordan** [comment]
This is not fixed in iOS as of the latest release (https://github.com/MetaMask/metamask-mobile/issues/2015)
