### ISSUE TITLE
Wording on transaction list elements

### ISSUE THREAD

**Issue by estebanmino** [MetaMask/metamask-mobile#1945]
- Mocks for the wording of transaction notifications: https://www.figma.com/file/VVjoLHG6X74lXmh6CN3r7H/Swaps?node-id=616%3A1709
- When I tap on transaction success message, take me to token received history. 

@jakehaugen Could you perhaps add the Figma file for transaction history - how to show a (successful / pending / failed) Swap in account Transaction History (e.g., screenshot from extension), and token histories for both the tokens
![image.png](https://images.zenhubusercontent.com/5c18e51bb423df7568ac3781/5ca58cd9-a528-4fad-939c-adaa091a890c)

**Comment by jakehaugen** [comment]
I think this should cover it, let me know if there are any screens missing: https://www.figma.com/file/VVjoLHG6X74lXmh6CN3r7H/Swaps?node-id=618%3A304
