### ISSUE TITLE
View: Root Error: Text strings must be rendered within a <Text> component.

### ISSUE THREAD

**Issue by randymetamask** [MetaMask/metamask-mobile#1949]
**Describe the bug**

60925's report of the issue description and reproduction steps include interacting with Collectibles

```
View: Root
Error: Text strings must be rendered within a <Text> component.
```

Other cases: 

- 60912 : user tried to use the magic link login at https://polymarket.com in the built-in browser.

**Screenshots**
![2_case60925](https://user-images.githubusercontent.com/72138609/97800491-dfe36c00-1c35-11eb-9b7b-a820f5409690.png)

![1_case60925](https://user-images.githubusercontent.com/72138609/97800480-d0642300-1c35-11eb-8ac3-4a1dd2803818.png)

**To Reproduce**
_Steps to reproduce the behavior_
1. Go to Wallet
2. Click on Collectibles
3. Click on the 1 unidentified contract (which is an aavegotchi.com raffle ticket/token)

_" I have uninstalled and reinstalled the app with my seed phrase, and the same thing happens. "_

**Expected behavior**
_A clear and concise description of what you expected to happen_

**Smartphone (please complete the following information):**
 - Device: 
 - OS: iOS
 - App Version: 1.0.4 

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by thienhieu123** [comment]
@rickycodes  I meet the same problem when I transfer eth on metamask. I test it on Rinkeby
My version : 1.0.9 (564) on iOS and 1.0.9 (43) on Android
Versions before not meet this problem

**Comment by thienhieu123** [comment]
I updated the version 1.0.10. try to uninstall and reinstall but I still not working
