### ISSUE TITLE
Remove ability to replace wallet 

### ISSUE THREAD

**Issue by omnat** [MetaMask/metamask-mobile#1950]
Support reported that some people are overlooking the warning, and proceeding to wipe their wallets without backing up their seedphrase. This is either happening from within the settings > Sync with Extension option or from the Logout > Go Back screen.
 
Let's make this really hard to do (re-installing would be the only option for users to import/create another wallet)

**Comment by omnat** [comment]
Remove:
- 'Sync with MetaMask extension' option from Settings > Advanced
- This message when people try to sync in other QR code contexts
![image.png](https://images.zenhubusercontent.com/5c18e51bb423df7568ac3781/cde7ee50-5330-46d1-b630-ab02b410540a)

**Comment by omnat** [comment]
- Remove this option from Settings
- Error handling when user scans the Sync with mobile QR code from extension wallet
- Redesign the logout experience OR just remove the ability to replace wallet (remove "Go back" button when user logs out)

**Comment by cjeria** [comment]
For this, @omnat and I had discussed the idea of giving the user better directions for what to do if they can't log in to the app.

Here's a simple decision tree for how we might handle this on the login screen
![image.png](https://images.zenhubusercontent.com/59b80272b0222d5de4776ba7/5806a5d3-7d43-4d2b-a5b3-f3b510e79f66)

And this is where the idea sort of generated from
![image.png](https://images.zenhubusercontent.com/59b80272b0222d5de4776ba7/a8e63952-ca81-4eda-8569-a59e6c398229)

[Figma file](https://www.figma.com/file/lcodxIQfO9j0nJwTBvPAYz/Forgot-Password?node-id=58%3A116)
