### ISSUE TITLE
Update transaction history API

### ISSUE THREAD

**Issue by omnat** [MetaMask/metamask-mobile#1953]
Problem: Alethio API is deprecating, so mobile users won't see incoming tokens anymore.

More details of why and what here:
https://docs.google.com/document/d/1hTNZWeUSsIS1xywvzhJ7us_4VfxsqewQaCZPjImhVAE/edit#

Possible options:
- Etherscan for all history
- Internal alternatives

This API decision will be consistent with extension.

**Comment by gantunesr** [comment]
Alethio was removed in the controllers v6.1.0
