### ISSUE TITLE
Error: Invalid SVG when user tried to view Collectibles 

### ISSUE THREAD

**Issue by lsqproduction** [MetaMask/metamask-mobile#1964]
**Describe the bug**
_A clear and concise description of what the bug is_
61970: User reported getting the error message when clicking into the BlockchainCuties group after going into the Collectibles tab. 

View: Root 
Error: Expected > (2:611). If this is valid SVG, it's probably a bug. Please raise an issue

i���7�->� 0D�ڼ_]MTV�>��ۉ��U�;����M���A:; �p �5��p�d

**Screenshots**
_If applicable, add screenshots or links to help explain your problem_
<img width="197" alt="Screen Shot 2020-11-05 at 11 30 46 AM" src="https://user-images.githubusercontent.com/12772017/98268390-74154200-1f5a-11eb-9cbc-0a93aeb8d833.png">

**Expected behavior**
To see the collectibles. 
<img width="189" alt="Screen Shot 2020-11-05 at 11 35 30 AM" src="https://user-images.githubusercontent.com/12772017/98270769-30700780-1f5d-11eb-970c-4613dd5a68a3.png">

**Smartphone (please complete the following information):**
 - Device: [e.g. Androd]
 - App Version 1.0.5

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by roo-shy** [comment]
One of the examples that has been reported: 
> Hi there my metamask isnt working. When i log into my account it shows me that theres an error.

<img width="201" alt="Screen Shot 2020-11-13 at 4 15 30 PM" src="https://user-images.githubusercontent.com/13618162/99126294-7cf5bb80-25cb-11eb-947f-f25dce3ff1b5.png">
