### ISSUE TITLE
Can't remove token on xDai

### ISSUE THREAD

**Issue by omnat** [MetaMask/metamask-mobile#1974]
QA/check why does a custom network interfere with functionality like 'Remove token'.

**Comment by Fatxx** [comment]
Note: Waiting for funds to be provided in order to test this.

**Comment by gantunesr** [comment]
The issue does not appear in the last version of the app (v5.1.0)

https://images.zenhubusercontent.com/141427485/c5031a95-3c07-45c6-9d9e-c248ca865d12/image_from_ios.mp4

**Comment by gantunesr** [comment]
There's another issue around the wallet balance that should be another ticket
