### ISSUE TITLE
OpenSea not rendering images when opened via deeplink

### ISSUE THREAD

**Issue by omnat** [MetaMask/metamask-mobile#1976]
**Describe the bug**
From OpenSea: We've been getting some user reports of issues specific to MetaMask Mobile and OpenSea.  I just reproduced a weird one and I'm wondering if you might be able to help us pin it down.

I'm not getting this behavior when I navigate straight to the account page in MMM or in Opera Touch, so while it's clearly on our side, it seems related to the redirect.

**Screenshots**
https://recordit.co/iRBK3sRMmn

**To Reproduce**
Here's the bug as a story:

- I make my way to OpenSea in Safari
- I navigate to the account page (https://opensea.io/account), which requires a wallet
- I get redirected to /wallet/install where I can pick from a bunch of different wallets
- Everything is still all good.  I select MMM
- I get deep linked into MMM and enter my password
https://opensea.io/account loads partially, but only the skeleton, not the guts

**Expected behavior**
The images on the site render as expected

**Smartphone (please complete the following information):**
 MMM Version: 1.0.3 (528)
iOS: 14.1

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**: Low as a small fraction of users get this when opening the MMM from deeplink 'Open a dapp'. There's a workaround.

**Comment by alexanderatallah** [comment]
Is this script required for reliably waiting for the ethereum provider to be injected? we can't wait for the window `load` event to fire before checking for it? https://www.npmjs.com/package/@metamask/detect-provider

**Comment by omnat** [comment]
@rickycodes adding you as you mentioned you looked a bit into this in standup
