### ISSUE TITLE
Advance Gas inputs scroll behind keyboard

### ISSUE THREAD

**Issue by wachunei** [MetaMask/metamask-mobile#1977]
**Describe the bug**
When editing transaction gas values in advance mode, tapping on the inputs make the modal scroll but inputs return to original position, remaining behind 

**Screenshots**

Video: https://imgur.com/qjK71uD

**To Reproduce**
_Steps to reproduce the behavior_
1. Create a transaction 
2. Click on edit gas
3. Switch to advanced
4. Tap on inputs

**Expected behavior**
View should be aware of keyboard and the contents should not result on being behind it.

**Smartphone (please complete the following information):**
 - Device: iPhone 11 Pro Max
 - OS: iOS 14
 - App Version: 1.0.6 build 544

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by gantunesr** [comment]
Closing this issue since its a old design bug
