### ISSUE TITLE
Support for Custom RPC API

### ISSUE THREAD

**Issue by omnat** [MetaMask/metamask-mobile#1996]
Sites can request users to add a custom network, with all details filled in. 
Related to #652 

User benefit:
- Make the process of adding a custom network easier without compromising on security (of easy verifying this isn't an unintended network)

**Comment by omnat** [comment]
Duplicate of https://app.zenhub.com/workspaces/metamask-mobile-5f984938ddc0e4001d4b79cb/issues/metamask/mobile-planning/65. Closing

**Comment by betbeetle** [comment]
Zenhub link is broken?
