### ISSUE TITLE
Type Error: Cannot read property "url" of undefined

### ISSUE THREAD

**Issue by roo-shy** [MetaMask/metamask-mobile#1997]
**Describe the bug**
During the login

**Screenshot**
<img width="206" alt="Screen Shot 2020-11-16 at 11 28 02 AM" src="https://user-images.githubusercontent.com/13618162/99286687-d1cd4800-27fe-11eb-9e92-46cc18565b21.png">

**To Reproduce**
_Steps to reproduce the behavior_
1. During login the above error pops up

**Smartphone (please complete the following information):** 
 - Device: 
- Samsung Galaxy 8S phone 

**Possible workaround**
Customer tried himself uninstalling / reinstalling the app. He still cant access his account, he entered his seed phrase and used his old password - it didn't allow him to import.

_ZD ticket (referencing for support): https://consensys.zendesk.com/agent/tickets/65316_

**Comment by evertonstz** [comment]
I'm having the same problem on Uniswap.
