### ISSUE TITLE
Update gas estimation API (across the app)

### ISSUE THREAD

**Issue by omnat** [MetaMask/metamask-mobile#1998]
Extension's PR:
https://github.com/MetaMask/metamask-extension/pull/9867

Remove ETH Gas station, and use MetaSwap API instead (GasNow primarily, Etherscan as fall back)

**Comment by omnat** [comment]
### Design needed
@cjeria @jakehaugen this new API doesn't give any time estimate, so we have to adapt the design (remove '42 sec' estimates)
![image.png](https://images.zenhubusercontent.com/5c18e51bb423df7568ac3781/514db18c-c071-482d-abb0-36872d458122)


### Reference
Extension design for gas options doesn't have gas estimates, just for reference. 
![image.png](https://images.zenhubusercontent.com/5c18e51bb423df7568ac3781/fd4f3e04-dd00-4856-b07b-504adfe9b3f7)

**Comment by cjeria** [comment]
Here's a screenshot of the gas control without the time estimate and suggested copy. @estebanmino @omnat let me know if you have any feedback.

"The network fee covers the cost of processing your transaction and storing it on the Ethereum network. MetaMask does not profit from this fee. Select the fee you are willing to pay. The higher the fee the better chances of your transaction getting processed."

![image.png](https://images.zenhubusercontent.com/59b80272b0222d5de4776ba7/8f651379-3694-4a2f-aa2e-756c75c954c3)
