### ISSUE TITLE
When I scan a QR code, whether its a payment request or recipient public address, I want to be redirected with the right values filled in.

### ISSUE THREAD

**Issue by omnat** [MetaMask/metamask-mobile#1999]
@omnat commented on [Mon Oct 19 2020](https://github.com/MetaMask/mobile-planning/issues/29)

Coinbase QR issue reported by support [here](https://consensys.slack.com/archives/GBW7S9FSN/p1606392113279800?thread_ts=1602872815.317800&cid=GBW7S9FSN).
They use another URL standard that doesn't work the same way as our payment request.

**Comment by omnat** [comment]
Moving it back to open as in the release 1.0.7, something went wrong and the PR that had the fix https://github.com/MetaMask/metamask-mobile/pull/1916/files somehow didn't result in fixing part of the issue. 

https://consensys.slack.com/archives/GBW7S9FSN/p1606392113279800?thread_ts=1602872815.317800&cid=GBW7S9FSN
Conversation where support reported that scanning this Coinbase QR code (generated by going to a token then tapping 'Fund account') **pre-fills the recipient address with token address instead of the user wallet public address**. The latest version does show a warning which should prevent users to loss funds to a token address, so that's an improvement from before the release. But the intention was that the QR code scanning results in filling in user address as recipient address. 

cc @andrepimenta @ibrahimtaveras00

**Comment by ibrahimtaveras00** [comment]
That's odd, when I scan the payment request QR that I tested it still works on appstore = https://recordit.co/XCWFOGtSPE

This is the request I scanned
<img width="665" alt="Screen Shot 2020-11-26 at 2 32 56 PM" src="https://user-images.githubusercontent.com/41752922/100386750-49b42300-2ff4-11eb-924d-56bf6a26d0dd.png">

Perhaps not all payment requests are created equally?

**Comment by omnat** [comment]
Ah ok, then that's the issue. 

Coinbase is using a different QR / URL standard than we do in creating our payment request. So our payment request links/QR are working just fine. 

For this issue, we should test with the Coinbase QR code (attached in the Slack thread) that is generated by going to a token in Coinbase, then tapping 'Add Funds'. It generates a QR code that has both params, token address and wallet address. People are scanning this from MetaMask app using the QR scanner in the Send flow. To ensure that scanning this QR leads to filling the 'Recipient address' field with user's public address (and not token address), we have to support this URL standard that Coinbase uses.

**Comment by andrepimenta** [comment]
https://github.com/MetaMask/metamask-mobile/pull/2019
