### ISSUE TITLE
Android browser doesn't clear cache - showing old pages won't update

### ISSUE THREAD

**Issue by VexyCats** [MetaMask/metamask-mobile#2009]
**Describe the bug**

Visiting an old dapp - that I haven't been too in a while on mobile I realized the site was showing the version from months ago. Tried going into the settings and clearing the browse history and privacy, no avail. 

Went into settings, cleared the metamask app's cache, still showing outdated sites. 

Doesn't look like there is a way to clear the browser cache on metamask? Or perform a hard refresh? 

**To Reproduce**
 Can't reproduce unless you've visited an old site and then come backs later after an update. 

**Expected behavior**
_A clear and concise description of what you expected to happen_

**Smartphone (please complete the following information):**
 - Device: Android Huawei 
 - OS: Android 
 - App Version 1.0.5 (39)

**Comment by omnat** [comment]
Hi @VexyCats , could you try to close all tabs and update to the latest version 1.0.7 and respond again if the issue persists?

**Comment by VexyCats** [comment]
Nope - still shows old dapp website. It refuses to update the website, kind of crazy. Cleared the cache, updated the app, closed the browsers, yet it still shows the old cached version of the site. 

Is there a way to remove the cache for the browser?

**Comment by Bloodyline** [comment]
That's still an issue, only way out of this is by using subdomains...

**Comment by Garito** [comment]
This issue is also in ios
any advance?
make the app useless...

**Comment by eltNEG** [comment]
I had the same issue but I used the clear cache option of my phone settings and it worked.

**Comment by tab00** [comment]
I had this issue over the past couple of days. In Android clearing the app's cache via Android settings worked. Clearing browser history in MetaMask app didn't work, which was quite annoying.

But how should it be done in iPhone? I need to remotely instruct a non-tech friend who uses iPhone but I don't have iPhone to try it myself.

**Comment by ubuntutest** [comment]
I still have this problem, I clear the cache from android settings or metamask settings, I keep seeing the old version of the site.

the only way i have to fix it is to clear all stored data from android app settings.

this is madness, I have to re-enter the seed and accounts every time.

any workaround?

**Comment by Yshatyi122** [comment]
0x8344E9c47eF12dcF4A6752aF9CCC9415ED6544A4
