### ISSUE TITLE
Confirmation modal not shown when app is launched and locked (connected via WalletConnect)

### ISSUE THREAD

**Issue by imin314** [MetaMask/metamask-mobile#2010]
**Describe the bug**
If the Metamask app is launched and locked before the transaction, a confirmation modal is not shown. To sign the transaction you need to restart the app.
More importantly, the promiEvent returned by sendTransaction never fires "transactionHash" neither "error" events. This problem persists only when sender dapp is opened on the same device as the Metamask app.

**To Reproduce**
To reproduce the issue, use any dapp with WalletConnect, e. g. this: [walletconnect-example-dapp](https://github.com/WalletConnect/walletconnect-example-dapp).
1. On iOS launch Metamask 1.0.6
2. Wait until the app locks
3. Lauch the dapp on same device
4. Send transaction
5. See that no confirmation modal is shown
6. Relaunch metamask, wait for the modal, confirm transaction
7. Return to the dapp, see that the request is still pending

**Expected behavior**
Confirmation modal is shown, promiEvent is resolved or error event is emitted.

**Smartphone:**
 - Device: iPhone SE
 - OS: iOS 13.6.1
 - App Version: 1.0.6

**Comment by omnat** [comment]
Hi @imin314 , could you try updating to 1.0.7 and respond here if the issue persists?

**Comment by imin314** [comment]
Hi @omnat, thank you for your response. I've tried with 1.0.7 today, and unfortunately the app behaves same as descibed above.

**Comment by ibrahimtaveras00** [comment]
I can't reproduce on v1.0.7 using iPhone X 13.7 on URL = https://example.walletconnect.org/  
seen here = https://recordit.co/wUXzcWAHVX

@imin314 are you trying with a different URL?
Do you have biometrics enabled or disabled on you metamask app?

**Comment by imin314** [comment]
Hi @ibrahimtaveras00,

Sorry, I just noticed that I missed one important step to reproduce the issue. It looks like the problem occurs when there is a time gap > 1min between authorization and sending transaction. Here is the screen record (please skip the part with the timer):

https://filebin.net/safbij9qac3b45ej/metamask?t=h1ojhlnf

**Comment by omnat** [comment]
@imin314 Could you elaborate more
>  the problem occurs when there is a time gap > 1min between authorization and sending transaction

Are you leaving the app after being sent / redirected to MetaMask via WalletConnect? 
Could you check what's your auto-lock setting? Settings > Security & Privacy > Auto-lock

Also please check if you can reproduce this with the latest version.

**Comment by imin314** [comment]
@omnat

> Are you leaving the app after being sent / redirected to MetaMask via WalletConnect?
Could you specify this question? The app automatically redirects me to Metamask app.

> Could you check what's your auto-lock setting? Settings > Security & Privacy > Auto-lock
Metamask automatically locks after 5 seconds.

> Also please check if you can reproduce this with the latest version.
Just tried with Metamask 1.0.8, and transactions still get lost when I wait for 1 minute after authorization before sending them.

**Comment by VexyCats** [comment]
Transactions are being lost on our end as well - but even if the app is not locked, and it was directly connected. It seems when refreshing the dapp - walletconnect connects back to metamask without requiring authorization from the wallet to connect, but the transactions won't be sent. Made an issue about this as well.

**Comment by imin314** [comment]
@VexyCats Thanks for keeping me posted. I noticed that issue too, but didn't identify it as a separate issue on WalletConnect side.
Hope it will be fixed soon.

**Comment by andrepimenta** [comment]
Related to #2045

**Comment by christopherferreira9** [comment]
Hi all! WalletConnect v1 is no longer supported. Please update WalletConnect to v2 with the supported MetaMask wallet (`v7.4.0`)
