### ISSUE TITLE
"Error: cannot unlock without a previous vault" upon entering password

### ISSUE THREAD

**Issue by bharmon3** [MetaMask/metamask-mobile#2011]
**Description**
_Upon closing the app, then reopening it to login, it rejects the user's password and shows the error, "Error: cannot unlock without a previous vault"_

**Screenshots**

_Error_
![Screenshot_20201115-200808](https://user-images.githubusercontent.com/74013053/100138875-9f55c780-2e5c-11eb-9b99-ffac13b57a7a.png)

_User's Device Info_

_Addtional error after uninstalling, reinstalling,  disabled biometrics, closed the app, then reopening_

**To Reproduce**
_Steps to reproduce the behavior_
1. Close the mobile Android app
2. Open it again and enter password
3. Receive the error, "cannot restore without a previous vault"

@rickycodes has been able _not_ been able to reliably reproduce this

**Expected behavior**
_Users should be able to access their already imported wallet by entering their password_

**Smartphone**
 - Device: v60 ThinQ
 - OS: Android
 - App Version 1.0.5

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user? Severe
- Six customers have reported the issue
- Is this visible to all users? No
- Is this tech debt? No

**Comment by 101001000** [comment]
This happened also to me today, metamask locked and I'm not able to login (today metamask has worked worse than habitual and then happened this)

**Comment by omnat** [comment]
@101001000 Sorry to hear. Are you able to fully quit the app and then login?
Could you also please share your device model, OS, and which app version you are on?

**Comment by omnat** [comment]
Another instance: https://www.reddit.com/r/Metamask/comments/k0uqqu/metamask_mobile_has_become_unusable_to_me_more/

**Comment by 101001000** [comment]
> @101001000 Sorry to hear, fixing this is our priority, and we are trying to reproduce it on our end to fix it. Are you able to fully quit the app and then login?
> Could you also please share your device model, OS, and which app version you are on?

Pocophone F1 Metamask 1.0.7 and android 9, I went back and now I can not even login, the button don't do anything

**Comment by randymetamask** [comment]
Another case: 62448

**Comment by 101001000** [comment]
Idk what you can do to reproduce it, I'm a heavy user of the app and suddenly it happened. The same day I had more problems than usual to connect to web apps with metamask and the tokens balance weren't loading properly (but ether balance did), maybe that's relevant

**Comment by nottrunner** [comment]
Having the same issue that started a couple days ago. 

![image](https://user-images.githubusercontent.com/17677506/100604659-d4d33880-32d4-11eb-98bf-9903fc8c4e0b.png)

**Comment by randymetamask** [comment]
_In the mobile version a survey appeared, I completed it, then it asked me for the password to enter, and this error appears:_

![case67052](https://user-images.githubusercontent.com/72138609/100661687-1951e900-3354-11eb-9336-06e78f343b16.jpeg)

From case: 67052

**Comment by doruq** [comment]
Guys how can we fix this? I can't use my mobile metamask for days because of this issue.

**Comment by 101001000** [comment]
Same here, I'm waiting so I can use it again, is annoying

**Comment by Wildhare1979** [comment]
This has been happening for me ever since the official version release on Android. worked fine before.

**Comment by mjgardner33** [comment]
Can someone help me. I'm having this problem, but don't know how to merge

**Comment by bharmon3** [comment]
Version 1.0.8 is live on Android. Please update your app and this issue should be resolved.

**Comment by 101001000** [comment]
> Version 1.0.8 is live on Android. Please update your app and this issue should be resolved.

The lastest release on GitHub and play store is 1.0.7 (I'm a beta tester)

**Comment by mjgardner33** [comment]
I don't think the new version is live yet. At least I don't see it

**Comment by mjgardner33** [comment]
> Version 1.0.8 is live on Android. Please update your app and this issue should be resolved.

It corrupted my data. Thanks...

**Comment by bharmon3** [comment]
@mjgardner33 First, please check that you have your seed phrase and private keys you've imported to your MetaMask wallet. Next, uninstall and install the app again with the version 1.0.8. And import your seed phrase. Let us know if you continue to have an issue.

**Comment by 101001000** [comment]
> @mjgardner33 First, please check that you have your seed phrase and private keys you've imported to your MetaMask wallet. Next, uninstall and install the app again with the version 1.0.8. And import your seed phrase. Let us know if you continue to have an issue.

Without uninstalling and installing: 
![Uploading Screenshot_20201209-154010_MetaMask.png…]()
