### ISSUE TITLE
SSL error: The certificate authority is not trusted

### ISSUE THREAD

**Issue by coomac** [MetaMask/metamask-mobile#2012]
**Describe the bug**
This error message appears when I try to use the built in browser on metamask android to visit any website: 

Oops! something went wrong...
We weren't able to load that page. 
Reason: SSL error: The certificate authority is not trusted.

**Screenshot**
![Screenshot_20201124-140444_Pixel_Launcher](https://user-images.githubusercontent.com/30805606/100146333-5eab7d80-2e5f-11eb-8a00-27ee47f4ed33.png)

**To Reproduce**
1. Open metamask
2. Click on menu and select Browser
3. Page loads for a second and immediately refreshes to show the error. 
The error appears on the homepage (https://home.metamask.io) as well as on any other website manually typed into the address bar. No websites can be accessed because the error cannot be bypassed.

**Expected behavior**
Website should load without an error.

**Smartphone (please complete the following information):**
 - Device: OnePlus 6
 - OS: Android 11, custom rom (Evolution) with Nov 5 Android security update
 - App Version - v1.0.7 (40)

Not sure if this is a problem introduced with the Nov 19 metamask update or from the rom (both were installed around the same time). I have noticed other wallets that are somewhat incompatible with various roms running the Nov security update.

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by omnat** [comment]
Hi @coomac thanks for reporting. Could you try closing all tabs you might have open in your MetaMask browser, quit the app, and try again?
Which sites have you tried accessing that are giving this error?

**Comment by coomac** [comment]
Thanks for getting back to me. I switched to a different rom (also based on
AOSP from Nov 5) and the error vanished. The bug report can be closed. If
the error appears again in the future with a different rom, I will try to
do more digging.

To answer your question though, I had tried the sites for uniswap,
balancer, zapper, yearn finance, bbc and google.

Also, troubleshooting-wise, I had closed all metamask tabs, cleared the
browser history and cookies within metamask,  cleared the app cache/storage
in android settings, wiped dalvik in twrp,  reinstalled the app, and
changed my web view app with no luck.

On Nov 25, 2020 at 1:58 PM, Omna Toshniwal <notifications@github.com>
wrote:

Hi @coomac <https://github.com/coomac> thanks for reporting. Could you try
closing all tabs you might have open in your MetaMask browser, quit the
app, and try again?
Which sites have you tried accessing that are giving this error?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/MetaMask/metamask-mobile/issues/2012#issuecomment-733919224>,
or unsubscribe

**Comment by cuidingfeng** [comment]
I'm debugging my local DAPP. I use the HTTPS certificate generated locally by mkcert, which also reports this error. Is there a way to solve it, thank you

**Comment by lxjwlt** [comment]
I have tried to modify some code underneath and recompiled, it works fine finally:
```xml
  <base-config cleartextTrafficPermitted="false">
    <trust-anchors>
      <certificates src="system" />
      <certificates src="user" />
    </trust-anchors>
  </base-config>
```
<img height="200" alt="image" src="https://user-images.githubusercontent.com/1782819/184669153-3c21a4f7-77c3-491a-848e-44a4f51247d0.png">

**Comment by royaldragonit** [comment]
Hey everyone.
I'm make sure 100% this error only show in android device.
To the fix problem, you need re-configure ssl for your domain.
Can general at [here](https://whatsmychaincert.com/) . 
I tried and working.
