### ISSUE TITLE
Camera Inaccessible to some users in dApps

### ISSUE THREAD

**Issue by jamesBsmyth** [MetaMask/metamask-mobile#2013]
**Describe the bug**
Even after camera is allowed in Metamask Mobile, some users report not having access to the camera from inside the dApp. 

![photo_2020-11-24_16-43-24](https://user-images.githubusercontent.com/33469363/100157133-d346e200-2e88-11eb-8367-69108b1b96a8.jpg)

**To Reproduce**
_Steps to reproduce the behavior_
1. Go to 'app.pruf.io'
2. Click on 'search', then the QR icon
4. See error (QR scanner does not have access to camera)

**Expected behavior**
I would generally expect a prompt from the browser confirming permission to access the camera, but in this case, Meatmask either carried straight through without additional request, or did not work at all. For most users, the application launches the camera, allowing them to scan QR codes. Others, even after allowing access to their device's camera, are reporting the fault described above.

**Smartphone (please complete the following information):**
 - Device: Xiaomi Redmi note 6 Pro, Iphone 7 Plus
 - OS: Android 9.0, iOS 13.5.1
 - App Version: Metamask 1.0.7, Metamask 1.0.7

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?   
- Add stats if available on % of customers impacted
- Is this visible to all users? 
- Is this tech debt? 

***Edit: added iOS version for iPhone

**Comment by jamesBsmyth** [comment]
Closed because we found that nested camera access simply won't be allowed on some devices due to security measures taken on an OS level. Plus, for the time being, NO devices running iOS. Worked around by prompting for user to take/upload photo. in case of a failure to load scanner.

**Comment by carrabre** [comment]
Any update on this?
