### ISSUE TITLE
window.ethereum not detected on iOS

### ISSUE THREAD

**Issue by EvilJordan** [MetaMask/metamask-mobile#2015]
Given the following code, the result is consistently "Please install MetaMask!" **on iOS**:
```
<!DOCTYPE html>
<html>

<head>
    <script>
        if (window.ethereum) {
            handleEthereum();
        } else {
            window.addEventListener('ethereum#initialized', handleEthereum, {
                once: true,
            });

            // If the event is not dispatched by the end of the timeout,
            // the user probably doesn't have MetaMask installed.
            setTimeout(handleEthereum, 3000); // 3 seconds
        }

        function handleEthereum() {
            const {
                ethereum
            } = window;
            if (ethereum && ethereum.isMetaMask) {
                alert('Ethereum successfully detected!');
                // Access the decentralized web!
            } else {
                alert('Please install MetaMask!');
            }
        }
    </script>
</head>

<body>
	Hello!
	<script>
		window.addEventListener('load', async () => {
			setTimeout(handleEthereum, 3000);
		});
	</script>
</body>

</html>
```

This is in reference to a post by @rekmarks in https://github.com/MetaMask/metamask-mobile/issues/1975#issuecomment-735347774_

Bug is also referenced here: https://github.com/MetaMask/metamask-mobile/issues/1875, but was closed for an unknown reason.

**Comment by shendel** [comment]
Try remove script in BODY `window.addEventListener('load', async () => { ....`
event `ethereum#initialized` fired?
Try (in metamask-mobile) reload page - event fired before (after reload press and page start reload) ?

**Comment by EvilJordan** [comment]
> Try remove script in BODY `window.addEventListener('load', async () => { ....`
> event `ethereum#initialized` fired?
> Try (in metamask-mobile) reload page - event fired before (after reload press and page start reload) ?

No. I added the additional body script to emphasize it does not work. This also has been going on for a while (new phone since then and the same issue, but was closed by the team because no one knows what they're doing): https://github.com/MetaMask/metamask-mobile/issues/1875

**Comment by shendel** [comment]
@EvilJordan you are try this? 
![image](https://user-images.githubusercontent.com/1880211/100554574-9030a880-32a6-11eb-9f03-10ad5cdab8ac.png)
event fired?

**Comment by EvilJordan** [comment]
> event fired?

Yes, I have tried it. No, it does not work.

**Comment by shendel** [comment]
@EvilJordan  `ethereum#initialized` fired? - try (in app) - press reload page - then fired this event? (in few seconds)

**Comment by EvilJordan** [comment]
Omg, dude. I know how to test. IT DOES NOT WORK!! IN APP.

**Comment by shendel** [comment]
> Omg, dude. I know how to test. IT DOES NOT WORK!! IN APP.

![image](https://user-images.githubusercontent.com/1880211/100554626-e7cf1400-32a6-11eb-9570-35d6cdff3f3b.png)
Check it on your (in the top) small app

**Comment by EvilJordan** [comment]
Try it on iOS, buddy.

**Comment by shendel** [comment]
> Omg, dude. I know how to test. IT DOES NOT WORK!! IN APP.

Im too. it works for me at the moment this button is pressed))

**Comment by shendel** [comment]
> Try it on iOS, buddy.

alas, I have an android, and I thought (and they too) that this is an android problem, but not only his problem comes out (sorry my english very bad)

**Comment by EvilJordan** [comment]
Thank you for trying to help. This is an iOS problem and has been going on for many months.

**Comment by shendel** [comment]
> > Omg, dude. I know how to test. IT DOES NOT WORK!! IN APP.
> 
> Im too. it works for me at the moment this button is pressed))


))) then this is their bug))) cool reproduction)))

**Comment by shendel** [comment]
> Thank you for trying to help. This is an iOS problem and has been going on for many months.

I spent two days building their application, with debugging enabled, to realize that there is no `window.etherium`

**Comment by shendel** [comment]
> Thank you for trying to help. This is an iOS problem and has been going on for many months.
it's not only iOS - it's for everyone

**Comment by rekmarks** [comment]
Before continuing, for newcomers, I'll note that there is an unrelated, outstanding issue affecting Android only, documented here: #1975 

I've tested multiple sites on my iOS device and with an iOS simulator, and `window.ethereum` is injected on all of them.

This script, adapted from our own examples and #1875 (cc: @happypsyduck), works for me:

```javascript
if (window.ethereum) {
  handleEthereum();
} else {
  window.addEventListener('ethereum#initialized', handleEthereum, {
        once: true,
    });
    setTimeout(handleEthereum, 3000);
}

function handleEthereum() {
  const { ethereum } = window;
  if (ethereum) {
    console.log('Ethereum successfully detected!');
  } else {
    console.error('Foo!');
  }
}
```

Our own [test dapp](https://metamask.github.io/test-dapp) works as well. It uses [`@metamask/detect-provider`](https://npmjs.com/package/@metamask/detect-provider), which basically implements the above snippet.

Now, @EvilJordan, in order to assist you further, I will require the following information, per our bug report issue template:
 - Device: [e.g. iPhone6]
 - OS: [e.g. iOS8.1]
 - App Version [e.g. 1.0.0] - find version number in app from Settings > About MetaMask

**Comment by shendel** [comment]
@EvilJordan this `test code` work on your device?

**Comment by EvilJordan** [comment]
Device: iPhone 12 Mini
OS: 14.3
App Version: 1.0.7 (552)

Also worth noting the exact same behavior on an iPhone SE (original), running the same OS and App version.

I just tried with the provided script and receive the same result: "Foo!"

**Comment by shendel** [comment]
@EvilJordan try check this https://github.com/MetaMask/metamask-mobile/issues/2015#issuecomment-735464422 
Is the bug reproduced?

**Comment by EvilJordan** [comment]
Ok, progress!

For shits, I completely removed my CSP (Content Security Policy). The script now works as intended. So... what's going on with it that needs to be added to a CSP to allow use? Unfortunately, I can't see any debug info in the MM app to self-diagnose.

**Comment by EvilJordan** [comment]
My guess is this: https://github.com/MetaMask/metamask-extension/issues/3133

**Comment by shendel** [comment]
@rekmarks are the certificates out of date? (well why not), inspirit ( :-/ )

**Comment by shendel** [comment]
@rekmarks, this can explain a non-working android, don't go (не зашли)

**Comment by EvilJordan** [comment]
I've narrowed it down to _something_ with the CSP.
Given this line in my .htaccess, it should allow for everything to go through (of course I tagged the `<script>` with a corresponding nonce (`<script nonce='mynonce'>`):
```
Header set Content-Security-Policy "default-src 'nonce-mynonce' 'strict-dynamic' 'self' 'unsafe-inline' 'unsafe-eval' https://*;"
```

For some reason, even the _presence_ of the CSP causes the result to be "Foo!"

If you guys have a way to view or dump the console's webview within a developer build of the app, this should be pretty easy to nail down a root cause.

**Comment by andrepimenta** [comment]
Hey @EvilJordan, we have tested this and the error we get is:
`Refused to execute a script because its hash, its nonce, or 'unsafe-inline' appears in neither the script-src directive nor the default-src directive of the Content Security Policy.`

When we open the site on a safari browser (desktop and mobile), outside of our app, we also get a similar error, which leads us to believe that your code is not working due to an iOS browser incompatibility, and not related to our app.

So it seems that your code is missing some tags in order to work on iOS. If you could do research on this error and try possible solutions on your code would be great, then let us know about the progress!

Thanks!

**Comment by EvilJordan** [comment]
@andrepimenta has solved it!

The issue is a known bug in FF, but apparently also in iOS WebView. Moving the CSP from the server to the page's meta tags fixes things. While I don't believe that's the best implementation of a CSP, it seems that a fix won't be forthcoming since it requires buy-in from multiple parties, would be a large change, and has, apparently, been known for many years.

Regardless, thank you to everyone who put up with me trying to figure this one out! My google-foo clearly is not up to snuff.

**Comment by gravitoken** [comment]
@EvilJordan I am having similar issues, no `window.ethereum` in safari iOS. What CSP tags did you add to solve the issue?

**Comment by mhorsley30896** [comment]
@EvilJordan I am having similar issues, no 'window.ethereum' in safari iOS. What CSP tags did you add to solve the issue?

**Comment by EvilJordan** [comment]
@mhorsley30896 As long as there isn't a CSP being served from in server response headers, you should be able to put anything you want in the `<meta>` tags and be fine. This is how I got [hodlberg.com](hodlberg.com) working.
