### ISSUE TITLE
WalletConnect - Transaction parameters getting overwritten or deleted, metamask trying to create new contract

### ISSUE THREAD

**Issue by DefiCake** [MetaMask/metamask-mobile#2018]
**Describe the bug**
Transaction parameters are being somehow overwritten when confirming transactions on UI

**Screenshots**
![image](https://user-images.githubusercontent.com/46090742/100659630-2caf8500-3351-11eb-8b4c-08a7a5a368ce.png)

**To Reproduce**
I don't know how to reproduce it. Currently I am just using WalletConnect to connect to my goerli test token. When I issue the ERC20 transfer method call, the transfer details are correctly rendered on the app correctly (ie, I get the amount, the name of the token, etc). Next, I hit confirm, the transaction fails and when I check etherscan, the address to where the transaction was sent is NOT the address of the contract (ie, it tries to create a new contract (????????????))

Example: https://goerli.etherscan.io/tx/0x28b1d3adf3d8a7edf230e1f5cf8a17004fd527504fe27355c84938c94b5f7dfd

This transaction has been sent to `0x2c57efca80c993a2ca2a380f5033cd6bcd40412d` instead of `0xB09e0FC4a683109495B8D1C7E0b64A45ABBEd951`, the address of the token smart contract. But when I get displayed the transaction details, everything looks as in the screenshot.

Weird enough, this only happens with the transfer method. I have a mint method that works all good.

UPDATE: I have tried adding the token to the known assets. This way it seems to work.

**Expected behavior**
Actually execute the method, do not create a contract.

**Smartphone (please complete the following information):**
 - Device: Xiaomi Red Mi 9
 - OS: Oreo
 - App Version: v1.0.7

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by WoeOm** [comment]
iOS metamask wallet trigger Dapp erc20 transfer function, it will also become create contract.

**Comment by kelvingoldhub** [comment]
Hi,

i am facing the same issue. Is there any update on the bug??

**Comment by tommasini** [comment]
Hello, @DefiCake, I'm not capable of reproducing the issue, can you tell me if this continues to happen? Can you provide me with some more info on how to reproduce it?
Thank you so much!

**Comment by tommasini** [comment]
@DefiCake I'm closing this issue, please if this happens again, open a new issue!
