### ISSUE TITLE
Metamask Mobile Ignores gasPrice parameter in web3 contract.methods.send

### ISSUE THREAD

**Issue by DevJxyden** [MetaMask/metamask-mobile#2020]
**Describe the bug**
Metamask mobile ignores the gasPrice parameter when calling a smart contract method using latest web3 1.30 library the optional gasPrice while it does work correctly in the desktop function.
e.g.
contract.methods.[methodName](params).send({from:accounts[0], gasPrice:'18000000000'})...

**To Reproduce**
use Web3 library to call a smart contract transaction that changes block chain state and specify a gasPrice. 
In the confirmation screen the gasprice will be auto-calculated and it will ignore any value passed to it.
 
**Expected behavior**
It should have the gas price set as the parameter that was passed to it from the dapp as it does in the desktop chrome extension.  Per documentation, "you may want to suggest a gas price in situations where your application knows more about the target network than we do."

**Smartphone**
 - Device: LG Stylo 5 
 - OS: Android 10
 - App Version v1.07 (40)

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by DevJxyden** [comment]
Appears to work now.

**Comment by tomw1808** [comment]
We're impacted at morpher.com, so a +1 from our side.

Initially we thought it just happened since the new gas price oracle was introduced, but it seems to be unrelated.

**Comment by mqklin** [comment]
We also have this problem at sanr.santiment.net. We develop our own L2 network and transactions there are free, so we set 0 as gasPrice. But MM ignores it and requires user to set at least 0.015 GWEI. Hence users can't use our app in mobile MM.

**Comment by gantunesr** [comment]
@DevJxyden @tomw1808 is this still an issue in the latest release?

@mqklin this is fixed in #3756. It'll be released in v4.3
