### ISSUE TITLE
Android browser crashes when attempting an upload 

### ISSUE THREAD

**Issue by ibrahimtaveras00** [MetaMask/metamask-mobile#2022]
**Describe the bug**

When attempting to upload a file the app crashes 

**To Reproduce**
1. Go to browser
2. Navigate to https://html.com/input-type-file/
3. Attempt to upload an image
4. App crashes (this works on iOS)

**Expected behavior**

App should not crash

**Smartphone (please complete the following information):**
 - Device: Android
 - App Version v1.0.7

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by omnat** [comment]
@wachunei do you think this could be related to the Transak crash? 
Is that issue something we've looked into thus far?

**Comment by wachunei** [comment]
I'd say this is the cause of the Transak crash, definitely related. We have not looked into that yet, but this is the same crash reason (uploading file for kyc)

**Comment by VexyCats** [comment]
Also have the same issue - the app instantly closes and crashes whenever trying to upload a file on any site from the dapp browser.
