### ISSUE TITLE
"accountsChanged" event fires twice on iOS

### ISSUE THREAD

**Issue by lovvtide** [MetaMask/metamask-mobile#2025]
**Describe the bug**
`accountsChanged` handler is being called twice the first time user switches accounts, and failing to be called at all if the user switches immediately back to the original account.

**To Reproduce**
_Steps to reproduce the behavior_
Set account listener like so:
`window.ethereum.on('accountsChanged', (accounts) => { console.log(accounts[0]) });`

**Expected behavior**
I've discovered that this is a two-part bug.

The first part:
When I switch accounts I expect this event to be fired once, with the new account that has just been selected. What happens instead is that it is fired twice, one call immediately after the other, i.e. if I load the app with account1 selected, and then switch to account2, my handler is called twice, first with `[ <account2> ]` (the new address—what I expect) and then immediately *again* with `[ <account1> ]` (the old address I just switched away from. Wrong.)

The second part:
Now, suppose I switch from account2 to another account account3. This works as expected. However, if I switch from account2 *back* to account1 (i.e. I switch back to the account that was selected when the app loaded) the event does not fire at all.

In the documentation it states that "`accountsChanged` will be emitted whenever the user's exposed account address changes". So my hypothesis is that when the event is incorrectly fired the second time, it's making the provider think that the original account you switched away from is still selected, and thus when you switch back to it it does not fire the event because it does not detect any change to the selected account.

I've found a partial work-around by explicitly ignoring the second, extraneous call to the handler. But my dapp is still broken in the case that the user switches back to the same address.

**Smartphone (please complete the following information):**
 - Device: iPhone8
 - OS: iOS 13.3
 - App Version 1.0.7

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by AlexeyApplicature** [comment]
Hello, community. I got the same issue with the Chrome extension. After some tests I got next results:
 - Dapp loaded, MetaMask connected, last selected account is set;
 - First account switch action throws 1 event, everything ok;
 - Second account switch action throws 2 events, not ok;
 - Third account switch action throws 3 events etc.
 Does anyone have any ideas why it works like this? What's the logic of this case? Maybe I don't understand something, but I expect to get only one event emitted for the first, second, third... twenty's account switch action. Thanks.
