### ISSUE TITLE
Remove old builds of MetaMask mobile app from public beta of Testflight

### ISSUE THREAD

**Issue by ravisriv** [MetaMask/metamask-mobile#2041]
**Describe the usability problem**
Some users have been continuing to use Testflight to update their MetaMask. Availability of the old public links for beta testing creates confusion between Apple AppStore and Testflight during updates. For example, in Testflight MetaMask version 1.0.3 is still available. A version update through TestFlight will overwrite the latest release of MetaMask through the AppStore.

**Expected behavior**
On iPhones, Apple App Store should be the only choice for updating MetaMask mobile app.

------------------------------------------------------------------------------------------------------
_filled out after submission_

**User impact | Usage frequency | Feasibility scores**
_How important is this to the user, what the user wants to accomplish | Daily, weekly, monthly | Small, medium, large_

**Comment by omnat** [comment]
The Testflight builds have expired.

**Comment by ravisriv** [comment]
Yes, thank you. Closing this issue now.
