### ISSUE TITLE
Warn users whenever an ENS name contains a homoglyph vulnerability

### ISSUE THREAD

**Issue by omnat** [MetaMask/metamask-mobile#2067]
This issue was on extension repo, and it applies to mobile too. Copying here

Details here: https://github.com/MetaMask/metamask-extension/issues/9129

### Problem
An ENS name is a UTF-8 compatible string of text. That means there are many characters that have the same appearance, or homo-glyph.

This can cause some concerns when using an ENS name:

- Pasting an ENS name that looks correct could actually be wrong. as[ tweeted recently](https://twitter.com/NepalBlockchain/status/1290153162007916544?s=19)
- Reverse-resolved ENS names could appear familiar but actually be deliberately crafted to be deceptive.

MyCrypto has a tool called [ens-validation](https://github.com/MyCryptoHQ/ens-validation) that can do the hard part of this already, we just need to design & display the appropriate warnings.

### Acceptance criteria:

- Entering a homoglyph-impersonation name on the send screen to field should show a warning. Can verify with vita‍lik.eth, which is not the same as vitalik.eth.
- A confirmation screen showing an ENS name should also show a warning under any homoglyph-containing name. We could also simply not resolve a homoglyph-containing name.

#### Possible copy for the warning:

This name has some deceptive letters in it that resemble other letters. It is probably trying to impersonate another well-known name. Did you get this name from someone you trust?

**Comment by omnat** [comment]
Action points 
- Review this [PR](https://github.com/MetaMask/metamask-extension/pull/9187
) and suggest alternative copy and error message UI component

**Comment by omnat** [comment]
Any updates on this one @rachelcope @cjeria ?

**Comment by rachelcope** [comment]
@cjeria let's sync on this today during our 1:1

**Comment by rachelcope** [comment]
Here's the alternative copy that @cjeria and I worked on...

GIVEN: A user is entering an ENS name in the send flow
WHEN: A user enters a recipient with an ENS name that contains a homoglyph
AND: When the users moves focus out of the input 
THEN: An alert should appear warning users of the risk:

> "We have detected an unusual character/s (homoglyph) in the ENS name entered. Check the ENS name/address with your recipient to avoid potential scam."

@cjeria would be the best person to determine what UI alert message component should be used for mobile

**Comment by rachelcope** [comment]
What happens in the use case that an ENS name is created in another language (e.g., Greek, Hebrew, etc) that uses homoglyph characters?

**Comment by cjeria** [comment]
Reusing the generic warning message component here. And the link to the design. https://www.figma.com/file/Ny0UospSv8UHgluAMnbbTE/Homoglyph-Warning?node-id=1%3A70
![image.png](https://images.zenhubusercontent.com/59b80272b0222d5de4776ba7/fa6f5921-a938-4ce1-b482-140c1e07a989)

**Comment by cjeria** [comment]
Came across this homoglyph attack generator while looking at this issue with @rachelcope the other day. It lets you easily generate name with names with homoglyph characters like Ꮩitalik.eth  http://www.irongeek.com/homoglyph-attack-generator.php

**Comment by omnat** [comment]
Made some comments on the Figma file @cjeria @rachelcope 
https://www.figma.com/file/Ny0UospSv8UHgluAMnbbTE/Homoglyph-Warning?node-id=0%3A1

**Comment by cjeria** [comment]
Here's an updated mock for this warning. I've added a line to the copy suggest by Omna. 

One question up for debate is whether we should block the user from continuing if a glyph is detected. I'm leaning toward blocking as this could be dangerous. However, I'm not sure if non-scammers are using homoglyphs in their ENS names?

feedback welcomed @omnat @rachelcope @jakehaugen 
![image.png](https://images.zenhubusercontent.com/59b80272b0222d5de4776ba7/e4304cdf-0c59-49a9-b06a-3dff144f2986)

**Comment by cjeria** [comment]
Updated design https://www.figma.com/file/Ny0UospSv8UHgluAMnbbTE/Homoglyph-Warning?node-id=39%3A55
![image.png](https://images.zenhubusercontent.com/59b80272b0222d5de4776ba7/5dea9626-24b0-4ad8-82eb-38d616dc03d4)

**Comment by mobularay** [comment]
Based on [stand-up on Thursday Apr 22 ](https://www.notion.so/Apr-22-2021-4f26aee247c5471fb750ef5458684f1e), solution was just finalized and about to start implementation. Moved this ticket back to **In-progress** from **review/QA**. Let me know if this is correct, @rickycodes !

**Comment by cjeria** [comment]
Here's the proposed solution for handling "rn" and "m" confusables we landed on. @rachelcope cc'ing you here to cross-reference for the extension
![image](https://user-images.githubusercontent.com/597770/116123574-0380ef80-a678-11eb-9eec-cc6990da32db.png)
