### ISSUE TITLE
Indicate which transactions happened locally in the State logs

### ISSUE THREAD

**Issue by omnat** [MetaMask/metamask-mobile#2069]
## Problem
Currently the state logs in mobile and extension are different. While extension logs show which transactions happened from the device locally, mobile shows the tx history (from Etherscan). This makes it harder for support team to troubleshoot tickets on mobile, and also causes confusion to users who use both mobile and extension. 

### More context
Support team gets too many tickets where people are concerned that their funds were stolen. This typically happens if they see unexpected transaction activity, and often jump to conclusion that either their money was stolen by MetaMask or by some other entity.

To troubleshoot, the support team needs to know if an outgoing transaction happened locally from their device. Once identified that the transaction was indeed done from their device, the support team can inquire further and understand if the perception of loss is due to 

- confusion related to how a transaction, token, protocol works
- a get rich quick scheme
- UX confusion resolvable by some steps (like 'Add token', or check on Etherscan for internal transactions)

## Solution
1. Indicate which transactions happened locally on the logs. 
2. Add indication of local outgoing tx on Tx History UI as well (adding needs-design label if this doesn't bloat the scope too much)

**Comment by jakehaugen** [comment]
Maybe just adding "from this device" after the timestamp would be enough? 

![Screen Shot 2021-01-12 at 11.51.22 AM.png](https://images.zenhubusercontent.com/5f984fc3457f8c0505807a13/002af82d-c888-4ac5-8bd8-1af020db0e9f)

**Comment by omnat** [comment]
For the **confirmed** or **failed** external outgoing transactions, your suggestion works @jakehaugen. 

@estebanmino The way we have the tx history implemented right now, do we currently show **pending** external outgoing transactions?

**Comment by omnat** [comment]
Add an event: "Imported account" in the tx history, as the older transactions won't show the local outgoing tx distinction.

**Comment by jakehaugen** [comment]
Hey @omnat and @estebanmino,

Just thinking -- is "from this device" the correct words? What if someone uses the same wallet on multiple mobile devices? Will it track device by device, or should it say "from mobile app"?

**Comment by jakehaugen** [comment]
Updated design to include "Imported wallet" event. 

Design file: https://www.figma.com/file/QRyJiqEFeSDk4ZUidHdB21/1353-View-my-transaction-history?node-id=198%3A604

![image](https://user-images.githubusercontent.com/11967476/108136419-e542b600-706e-11eb-9d28-c1938b6cd687.png)

**Comment by sethkfman** [comment]
@jakehaugen & @omnat 

This is a reminder to chat on about what defines a transaction from this device (e.g. Send vs. Dapps vs. Swaps vs. Deep-link).

What about displaying the "origin"? ![screenshot-1616795802393.jpg](https://images.zenhubusercontent.com/602c3c981617aad4ad2160f8/93a152cc-b4cf-4287-8325-3d84e75af03b)

**Comment by sethkfman** [comment]
After conversations with @omnat & @jakehaugen the follow features were added/updated:

- Track the time the wallet was setup (either create wallet, import with seed, or sync with extension) 

- Timestamp shared for all accounts generated by this seedphrase

- when a private key was imported - timestamp unique to that specific account

- Change label row to "Account added to this device”

![Screen Shot 2021-03-30 at 2.32.00 PM.png](https://images.zenhubusercontent.com/602c3c981617aad4ad2160f8/b140f3c8-4380-4c36-b3f0-dad11a26993b)

**Comment by mobularay** [comment]
@sethkfman is finishing the controller PR, needs guidance on the next steps in relation with this card before require dev review and QA (will add the tags). @andrepimenta will help out.

**Comment by mobularay** [comment]
PR is ready for review by other Engineers.

**Comment by mobularay** [comment]
Ready for peer review, and then QA

**Comment by mobularay** [comment]
@sethkfman this PR went out with v2.2, correct?
