### ISSUE TITLE
Cannot add token via etherscan 

### ISSUE THREAD

**Issue by ibrahimtaveras00** [MetaMask/metamask-mobile#2073]
**Describe the bug**

Attempt to add a token to your wallet through our browser via [etherscan.io](https://etherscan.io/token/0xdac17f958d2ee523a2206206994597c13d831ec7) it doesn't work

**Screenshots**

Seen here = http://recordit.co/9ToNdvrhw8

on iOS nothing happens, on android I'm presented with this alert:
![Screen Shot 2020-12-15 at 2 51 46 PM](https://user-images.githubusercontent.com/41752922/102265607-5639e600-3ee5-11eb-98f4-c339a503ee00.png)

**To Reproduce**
_Steps to reproduce the behavior_
1. Go to [etherscan.io](https://etherscan.io/token/0xdac17f958d2ee523a2206206994597c13d831ec7)
2. Scroll down to profile summary and tap on the menu and tap on add token to web 3 wallet

**Expected behavior**

I should be able to add the token to my wallet

**Smartphone (please complete the following information):**
 - Device: any
 - OS: both Android and iOS
 - App Version v1.0.8

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by omnat** [comment]
![image.png](https://images.zenhubusercontent.com/5c18e51bb423df7568ac3781/76e6be75-0696-468b-91aa-24d4b6651ff7)

^Closing, as this worked for me on latest version. Perhaps this was fixed with the one of the recent provider updates, and android injection fix.
