### ISSUE TITLE
Favorites doesn't always show for iOS

### ISSUE THREAD

**Issue by ibrahimtaveras00** [MetaMask/metamask-mobile#2075]
**Describe the bug**

Sometimes favorites doesn't display when they should

**To Reproduce**

1. Go to any site on an iPhone device
2. Add the site to favorites 
3. Now tap the home icon on the bottom of the browser 
4. Tap on favorites tab and you will not see any even though you should (opening a new tab doesn't always seem to work, but in some instances it does) 

**Expected behavior**

If a user has favorites, they should accurately be displayed 

**Smartphone (please complete the following information):**
 - Device: iPhones
 - App Version v1.0.8

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by cjeria** [comment]
Adding a friendlier message for the empty state of the browser for iOS users cc @omnat @estebanmino WDYT? 
![image.png](https://images.zenhubusercontent.com/59b80272b0222d5de4776ba7/52920e5f-3f8d-44c0-b725-98554025a1ba)

**Comment by mobularay** [comment]
QA will be done in regression.
