### ISSUE TITLE
Update React Navigation to 5.x

### ISSUE THREAD

**Issue by andrepimenta** [MetaMask/metamask-mobile#2077]
This new release uses a native implementation of navigation which will mean improvements in navigation performance and native feel.
https://reactnavigation.org/blog/2020/02/06/react-navigation-5.0/#native-stack-navigator

**Comment by mobularay** [comment]
Identical to [issue 2654](https://app.zenhub.com/workspaces/metamask-mobile-5f984938ddc0e4001d4b79cb/issues/metamask/metamask-mobile/2654)
