### ISSUE TITLE
Enable me to make safe decisions to transaction requests

### ISSUE THREAD

**Issue by omnat** [MetaMask/metamask-mobile#2080]
## Context
Extension team @rachelcope is redesigning confirmation screens to improve user experience, such that, the user can make an informed and safe decision on whether to confirm or reject a transaction request.
Some of these UX enhancements would improve mobile's transaction UX and make it more reliable.

#### Empower me to verify contracts that I am interacting with
Current confirmation screen doesn't show contract address. Even if under details, we should make it available to 
- View contract address and ability to copy it. Consider adding ability to 'Verify this contract address on Etherscan'
- View name of the contract address if available 
   order to check: - Display bookmarked name if available
    - Show contract-metadata nickname if available
    - Fallback to address. 
- On token allowance request, say "this **contract** is requesting permission to spend tokenX", instead of "this site..." 

#### Clarify how much value transfer or exchange will happen when I confirm a transaction
Transactions confirmations where amount is '0 ETH', and confusion that's causing people

#### Informed consent: Give me complete context before I take accept/confirm
- User consent information should be above-the-fold
- When possible CTA’s should be above-the-fold
- In edge cases where consent information and CTA’s don’t fit above-the-fold, then CTA’s should be in the scrollable area (not fixed)

#### Error prevention:
https://github.com/MetaMask/metamask-extension/issues/10284
e.g., Stale confirmations -- how do we address this in mobile? (especially when app is just put in background). see how this applies to mobile

#### Gas fee updates
Add current selected gas in the custom gas edit modal
Token allowance screen does not show estimated conversion rate for the tx fee

**Comment by omnat** [comment]
I think at this point, we could have a template for all permission requests. The request must have the following

1. Who is making the request: Source info (verifiable by user) of the entity that is requesting the permission 
2. What is the request: Human friendly description of the permission itself, and a way for users to review (and edit - when applicable like in Approval of token allowance) the permission
3. Risks in accepting the request: Concise description of the risks involved in this permission

**Comment by gantunesr** [comment]
Looks like it isn't relevant
