### ISSUE TITLE
Mobile Error : Mobile client does not recognize balance of several ERC20 tokens. Forced to reinstall

### ISSUE THREAD

**Issue by lakejynch** [MetaMask/metamask-mobile#2082]
**Describe the bug**
_Metamask on mobile client (IOS) does not recognize balance when new token is added from list. Refreshing does not work, bug is persistent. Have not attempted to reinstall app. Browser client and etherscan both recognize balances. When attempting to send funds 'Undefined Balance' error is prompted._

**Screenshots**
Version:
![IMG_3964](https://user-images.githubusercontent.com/56452947/103588754-ec937300-4eb7-11eb-8e10-e92678958b52.PNG)

Etherscan:
![IMG_3965](https://user-images.githubusercontent.com/56452947/103588758-ee5d3680-4eb7-11eb-88da-1b838d9865fd.jpg)

Mobile Client:
![IMG_3963](https://user-images.githubusercontent.com/56452947/103588762-ef8e6380-4eb7-11eb-92a9-6ba9a9d12e52.jpg)

**To Reproduce**
_Steps to reproduce the behavior_
1. Send token or swap on DEX
2. Add token to metamask 'List' on mobile
3. Attempt to use tokens

**Smartphone (please complete the following information):**
 - Device: [iPhone 11 Pro]
 - OS: [e.g. iOS 14.2]
 - App Version [e.g. v1.0.8 (554)]

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by lakejynch** [comment]
After attempting to send DAI with 'Unknown Balance' reported, I received the following error:
![IMG_3968](https://user-images.githubusercontent.com/56452947/103589090-a559b200-4eb8-11eb-836e-67601c8cfeb1.PNG)

**Comment by omnat** [comment]
Hi @lakejynch, could you please try removing SNX token and see if that loads all token balances correctly? Thanks! Please let us know, this will help us investigate this issue.

**Comment by lakejynch** [comment]
> Hi @lakejynch, could you please try removing SNX token and see if that loads all token balances correctly? Thanks! Please let us know, this will help us investigate this issue.

Unfortunately I was forced to reinstall and the bug is no longer present.

I exported the state logs and can send them over if that would help, just let me know how/where.

**Comment by omnat** [comment]
Hi @lakejynch, fix for this on the way https://github.com/MetaMask/metamask-mobile/pull/2148
