### ISSUE TITLE
Getting logs in mobile metamask

### ISSUE THREAD

**Issue by kottackalsulvin** [MetaMask/metamask-mobile#2086]
Hi,
I need to debug and test my dapp in mobile metamask browser. I already sync metamask wallet in mobile using metamask extention.

How can I get the console log in mobile metamask browser because my mobile metamask is forcefully shutting down while am using ipfs in dapp?

**Comment by omnat** [comment]
@rickycodes Could you point @kottackalsulvin in the right direction to help get setup for testing their dapp?

**Comment by gantunesr** [comment]
Hey @kottackalsulvin, I'll close this issue for the moment. Feel free to open a new one if you need help
