### ISSUE TITLE
NFT not displayed, nor "discovered"

### ISSUE THREAD

**Issue by SvenMeyer** [MetaMask/metamask-mobile#2108]
Metamask mobile shows my crypto kitties NFTs / ERC721 "automatically / by itself" on Mainnet.

My own, simple OpenZeppelin ERC721 NFT on Kovan testnet does not show up "automatically / by itself", but is visible on etherscan:

https://kovan.etherscan.io/token/0xae5638ba84a03c4edaa70e21f942a70f3f214d04

However, once I manually (!) entered the contract address and Collectible ID my NFT was being displayed.
(A QR scan option for the address would help at least a little bit here).

What does a ERC721 NFT need to provide to "automatically" show up ?

Does it make a difference if Mainnet or Kovan is being used ?
(I have not yet deployed my NFT on Mainnet)

**Comment by crosstec** [comment]
Missed your bug report before I wrote mine but it is very likely this as you refer to kovan network:
https://github.com/MetaMask/metamask-mobile/issues/2110

**Comment by SvenMeyer** [comment]
I was able to get my (simple) ERC721 getting displayed in Metamask mobile once I manually (!) entered the contract address and Collectible ID.
Ideally Metamask mobile would discover the NFT (like etherscan) by itself.
A QR scan option for the address would help at least a little bit as well.
Have not tested if my NFT would automatically been found and displayed on Mainnet though ...

**Comment by SvenMeyer** [comment]
updated initial post with a better description ...

**Comment by SvenMeyer** [comment]
Just tried rinkeby, same problem as on Kovan.
The NFT is minted, but does not automatically show up in Metamask Mobile, however it is being displayed once you type in the NFT contract address and tokenID.

**Comment by omnat** [comment]
As @crosstec suspects, this is likely because we are using OpenSea API to pull NFT lists for accounts. Investigating this on our end too.

**Comment by omnat** [comment]
Closing as this seems same issue as #2110. Lets move our conversation to #2110 @SvenMeyer
