### ISSUE TITLE
"Add Collectibles" not working being connected to different chains than Mainnet

### ISSUE THREAD

**Issue by BennyTheDev** [MetaMask/metamask-mobile#2110]
### **Description**

Adding a ERC 1155 collectible through "Collectibles" => "Add Collectible" will always return an error "You aren't the owner of this collectible." This error is currently is a catch all message based on failure. We may need to add more check cases to display the correct error. More importantly, we'll need to add support for ERC 1155 NFTs.

**To Reproduce**
1. Switch to a different network (in my case xDai)
2. Create an NFT, for example within an ERC1155 collection
2. In MM click on "Collectibles" => "Add Collectible"
3. Enter the address of the collection and the ID of the collectible
4. Wait for the ownership error

### **Acceptance Criteria**

- Collectibles should be addable and show regardless of the chain being used.

- Try to test on:
   - Device: Galaxy Fold 1
   - OS: Android 10
   - Most recent at the time of writing

### **Questions**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

### **Notes**

By quickly checking the code, I assume that checking the ownership operates on mainnet still as the Opensea API seems to be used, only supporting Mainnet and Rinkeby.
-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

**Comment by SvenMeyer** [comment]
Actually it works using Kovan. I was able to get my (simple) ERC721 getting displayed in Metamask mobile once I manually (!) entered the contract address and Collectible ID.
Ideally Metamask mobile would discover the NFT (like etherscan) by itself.
A QR scan option for the address would help at least a little bit as well.
Have not tested if my NFT would automatically been found and displayed on Mainnet though ...

**Comment by crosstec** [comment]
Then it is different with Kovan and/or ERC721 as ERC1155 definitely doesn't work (tried xDai, Sokol, Binance Smart Chain)

**Comment by omnat** [comment]
Hi @crosstec Are ERC1155 working for you as expected on Mainnet and other default networks (rinkeby, kovan, etc.)?

**Comment by mobularay** [comment]
A different [ticket 2391](https://app.zenhub.com/workspaces/metamask-mobile-5f984938ddc0e4001d4b79cb/issues/metamask/metamask-mobile/2391) / [PR 2441](https://github.com/MetaMask/metamask-mobile/pull/2441) should have solved this issue. 

@BennyTheDev, can you confirm if this issue has been resolved for you? Pls let us know. If we don't hear back from you by next week, we'll close this issue :-) Thank you!

**Comment by mobularay** [comment]
Related to #2963. Next steps: discussion @gantunesr @omnat @mobularay @Cal-L

**Comment by gantunesr** [comment]
Fixed in v3.6.0
