### ISSUE TITLE
Advanced feature: Add ability to submit a transaction with custom nonce

### ISSUE THREAD

**Issue by omnat** [MetaMask/metamask-mobile#2126]
This feature is available on extension and helps people submit a transaction with a changed order, typically bumping up a past transaction (either to cancel or to speed up). This is a workaround which helps people when
- their transaction is stuck in pending state for long, e.g., if they have many pending transactions, and this transaction is not 1st in queue
- gas price fluctuations are high and just increasing 10% of gas isn't sufficient to speed up their transaction

User can turn this feature ON from Advanced settings.
Turning this feature ON shows an additional field of adding nonce (with some guidance) on all transaction screens (dapp interactions, send flow)

**Comment by omnat** [comment]
https://www.figma.com/file/7mmg2dOh4wVDlWBNp9sums/Mobile-Custom-Nonce?node-id=7%3A13

**Comment by cjeria** [comment]
Adding a doc with custom nonce learnings cc @omnat @dpazdan @rickycodes 

 https://docs.google.com/document/d/1t59I0LUy2yE_5ZsnHZp63QMdpcRqTm3iNEixRzu8qGY/edit?usp=sharing 

Here's the MVP for mobile
![image.png](https://images.zenhubusercontent.com/59b80272b0222d5de4776ba7/25b136c6-9158-4fcf-b1ce-433041b6c3a0)

**Comment by cjeria** [comment]
@dpazdan brought up a good point for mobile. Currently, you cannot proceed with 0ETH or 0Tokens in the send flow.  This will need to be allowed for people to manually send a cancellation attempt of a pending tx w/custom nonce. 

![image.png](https://images.zenhubusercontent.com/59b80272b0222d5de4776ba7/ad182b05-7889-44a6-a331-0ddfc768c52b)

**Comment by omnat** [comment]
Need to understand technical lift for the ideal version with pending txs. 
@cjeria could you sync with someone on the eng team?

**Comment by cjeria** [comment]
I asked @rickycodes about this earlier this week and he said it seems possible but he'd need time to look closer at this. Maybe @estebanmino can also chime in here. Happy to schedule a call to discuss.

**Comment by cjeria** [comment]
Latest design. Got Ricky's review and l got his OK on this approach.
https://www.figma.com/file/7mmg2dOh4wVDlWBNp9sums/Mobile-Custom-Nonce?node-id=100%3A0
![image.png](https://images.zenhubusercontent.com/59b80272b0222d5de4776ba7/2159ab06-8987-412f-ac06-d3c50c211bad)

**Comment by cjeria** [comment]
Copying over designs for good measure. 

The relocation of the plus/minus buttons was due to increasing the overall width of the nonce number area. 
![image.png](https://images.zenhubusercontent.com/59b80272b0222d5de4776ba7/7fce33f1-aa28-4e00-a66f-5c899caf3d97)

**Comment by mobularay** [comment]
Issue item 3 will be addressed separately in 2271 https://github.com/MetaMask/metamask-mobile/issues/2271

PR for this card is now good for review & QA,

**Comment by mobularay** [comment]
Just wondering if it's possible to break up this Zenhub story into two so that they aligned to the respective PRs in Github? @omnat
