### ISSUE TITLE
Bug: token balance shows 0 if one of the tokens' property fails

### ISSUE THREAD

**Issue by omnat** [MetaMask/metamask-mobile#2128]
### Problem
This is an issue with error handling. When a token (like synthetix, sUSD) fails to render, all other token balances render as 0. This is very confusing, we've seen some support tickets come in for this. 

Workaround not _really_ available: Usually if the user hides the token that is causing the issue (no way to know for them, unless our support team guides them). This workaround isn't scalable. User isn't communicated what is failing and why this might be happening. Even if they reinstall or reimport their wallet, the problem persists.

We have see instances on both iOS and Android

Support tickets for more context:
https://consensys.zendesk.com/agent/tickets/76825
https://consensys.zendesk.com/agent/tickets/76776
https://consensys.zendesk.com/agent/tickets/77294
https://consensys.zendesk.com/agent/tickets/75337

**Comment by omnat** [comment]
Andre has [fix](https://github.com/MetaMask/controllers/blob/develop/src/assets/TokenBalancesController.ts#L99) for this would be to fail only the token that has the issue -- so only the token that fails will show 0 balance, and all other tokens will show the correct balance. 

Ideally, if we can identify which token is failing, then we show that broken (instead of just a 0), e.g., show a warning "Error: can't display this token"

**Comment by jakehaugen** [comment]
Here are the designs: https://www.figma.com/file/cXKVLzEPbIaPvdvupKT18o/Failed-to-load-balance?node-id=0%3A1
