### ISSUE TITLE
v1.0.9 Regression Bug | App crashes when attempting to load site

### ISSUE THREAD

**Issue by ibrahimtaveras00** [MetaMask/metamask-mobile#2138]
**Describe the bug**

When I navigate to https://brunobar79.github.io/dapp-issues-repro/ on an iOS device, the app immediately crashes.

**Screenshots**

Crash seen here = https://recordit.co/w1rjKdnYM4

compared to current prod/appstore version 1.0.8 (554) which works fine and prompts the connect modal = https://recordit.co/2RfM6lV1iq

**To Reproduce**

1. Navigate to https://brunobar79.github.io/dapp-issues-repro/ on an iOS device

**Expected behavior**

it should work like current prod and prompt the connect modal and not crash

**Smartphone (please complete the following information):**
 - Device: iPhone's/iOS
 - App Version v1.0.9 testflight 563

**Comment by rekmarks** [comment]
Interestingly, it doesn't crash in the iOS Simulator. Is it possible that we still interact with iframes in some undefined way, even though we no longer inject our provider in them?

Maybe the `mobile-provider` `shouldInject` function should contain a check that ignores iframes, or we should add logic to ignore/avoid iframes elsewhere.

PR where iframe logic was removed from `mobile-provider`, for reference: https://github.com/MetaMask/mobile-provider/pull/41

**Comment by andrepimenta** [comment]
I think this is due to the webview update
