### ISSUE TITLE
v1.0.9 Regression Bug | Can't get wallet connect to work when launching app or when app is locked

### ISSUE THREAD

**Issue by ibrahimtaveras00** [MetaMask/metamask-mobile#2139]
**Describe the bug**

Android only bug

When I launch the app in a clean state via wallet connect deep link, or when I have the app locked in the background, I am unable to get the prompt to show in app

**Screenshots**

Seen here = https://recordit.co/BFcuPfcPE4 (notice how slow it is to load) 

compared to current prod / playstore with the same exact device + same exact wallet and account = https://recordit.co/zRksc58vde

**To Reproduce**

1. Go to https://example.walletconnect.org/ in a separate browser (chrome) on an android device
2. Connect to MetaMask app via wallet connect
3. Try any call from wallet connect when app is killed or in a locked state

**Expected behavior**

Wallet connect should work like in current prod

**Smartphone (please complete the following information):**
 - Device: Android device
- OS 11
 - App Version [e.g. 1.0.0] - find version number in app from Settings > About MetaMask

**Comment by ibrahimtaveras00** [comment]
I'm realizing this may also be because of the fact that on Rinkeby I have over 500 transactions on this account.  When I import a different wallet with much fewer transactions I'm able to interact with wallet connect with no issues.  Nonetheless, there's still a difference between this version and v1.0.8.

**Comment by estebanmino** [comment]
that difference is not related to https://github.com/MetaMask/metamask-mobile/issues/2140 ?
