### ISSUE TITLE
accountsChanged fired two times

### ISSUE THREAD

**Issue by ochikov** [MetaMask/metamask-mobile#2162]
accountsChanged fired two times when the account is changed on Mobile App when the page is opened from the integrated browser and account is changed.

 - Device: Iphone 7 Plus
 - OS: 13.5.1
 - App Version: 1.0.9

**Comment by omnat** [comment]
Hi @ochikov To understand impact of this on users, could you elaborate more on what problems this causes for you?

**Comment by ochikov** [comment]
> Hi @ochikov To understand impact of this on users, could you elaborate more on what problems this causes for you?

Two events are fired. First the event with the new account address and then once again the event with the old address.

**Comment by omnat** [comment]
And how is it impacting your experience?

**Comment by ochikov** [comment]
> @ochikov And how is it impacting your experience?

I am listening for the event and after the account is changed, I am reloading the page, and make some other App-specific tasks. Dispatching two events one after another with wrong data is affecting my experience as I cannot load the right data for the user.

**Comment by Upperfoot** [comment]
Same exact issue as described by the other users.

This also happens on Android (Samsung S20+), the event fires twice with different data in both calls.

First Event - Correct Account Address
Second Event - Incorrect Account Address

Now, this doesn't happen at all on the desktop version and is a specific issue to Metamask Mobile.

**Comment by deepseafishing** [comment]
Having the same issue here. For me, it doesn't even give me the 2 different events. They're always returning the account that was originally logged in. They're not returning the newly switched account in the accountChanged callback.

**Comment by deepseafishing** [comment]
[MetaMask DEBUG]: Analytics 'trackEvent' - {category: "Accounts", action: "Account Modal", name: "Switched Accounts"} {}__proto__: Object undefined undefined

**Comment by duxiaofeng-github** [comment]
same issue here on android metamask app

**Comment by Markkop** [comment]
Same bug happening for me.
The best workaround I found was setting a cooldown variable to avoid triggering the event's method again.
However, when the user changes the account back to the one he loaded the page, the `accountsChanged` event is not triggered.
```js
let onAccountsChangedCooldown = false

function onAccountsChanged (accounts) {
  if (onAccountsChangedCooldown) return
  onAccountsChangedCooldown = true
  setTimeout(() => { onAccountsChangedCooldown = false }, 1000)
  setAccount(accounts[0])
}

connection.on('accountsChanged', onAccountsChanged)
```

I tried using throttle functions, but they only delayed the second event firing.

**Comment by Markkop** [comment]
I was not able to try the build locally, but looking at the code perhaps this `forEach` is the culprit?
https://github.com/MetaMask/metamask-mobile/blob/3f9d91c60d090a8aa5bb35e44fb484148a7fc7fd/app/components/Views/BrowserTab/index.js#L364-L379

`notifyAllConnections` is being called here when changing accounts
https://github.com/MetaMask/metamask-mobile/blob/3f9d91c60d090a8aa5bb35e44fb484148a7fc7fd/app/components/Views/BrowserTab/index.js#L402-L407

**Comment by wyaricky** [comment]
I've been experiencing similar behavior but it triggers at least 8 times. 

I listen for accountsChanged and have event put my code block in a conditional to check whether the new account matches the account stored in a state variable. Still results in 8+ triggers.

**Comment by thelastinuit** [comment]
For me, `accountsChanged` is being triggered every page I switch to. 

Any solution or hacks so far? 😔

**Comment by thelastinuit** [comment]
> I've been experiencing similar behavior but it triggers at least 8 times.
> 
> I listen for accountsChanged and have event put my code block in a conditional to check whether the new account matches the account stored in a state variable. Still results in 8+ triggers.
> 
> I am also not using any loops in my file

@wyaricky 
did you manage to solve it / hack it?
