### ISSUE TITLE
Custom gas fee with decimal ". " & ", "

### ISSUE THREAD

**Issue by lsqproduction** [MetaMask/metamask-mobile#2169]
**Describe the bug**
**When editing the gas price with ". " the gas prices increases /changes by themselves to stay a whole number**

<img width="449" alt="Screen Shot 2021-01-26 at 10 38 38 AM" src="https://user-images.githubusercontent.com/12772017/105867084-a9ae5200-5fc2-11eb-8d96-a672edc1460b.png">

**When editing the gas price with ", " the app crashes. Some European countries use commas as decimals**

**To Reproduce**
_Steps to reproduce the behavior_
1. Create a transaction
2. Edit network fee
3. click on "Advanced"
4. Edit gas price by adding either a ". ' or ", "

**Expected behavior**
The gas price should stay as how the users edit them to be.

**Smartphone (please complete the following information):**
 - Device: both andrioid and iphone

 - App Version 1.0.9

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by omnat** [comment]
Hi @lsqproduction The Gas price is set in Gwei units, which are the lowest denomination of ETH ([learn more](https://www.investopedia.com/terms/g/gwei-ethereum.asp)), that's why we don't accept decimals in this input field.

**Comment by hirokiht** [comment]
> Hi @lsqproduction The Gas price is set in Gwei units, which are the lowest denomination of ETH ([learn more](https://www.investopedia.com/terms/g/gwei-ethereum.asp)), that's why we don't accept decimals in this input field. Please use integers, so if you wanted to input 65.8, please input 65 or 66.

Gwei is indeed the lowest denomination of ETH, however gas price can be specified in non-integral gwei unit. The total fees (gas unit * gas price) is in gwei. Here's a random transaction in etherscan which uses 19.5 gwei as gas price.
https://etherscan.io/tx/0x25cb3707b55a9c8232fadf361fcc4ca43c290c6d711f133cbd37109f74a02a7e
