### ISSUE TITLE
Asset support for custom networks

### ISSUE THREAD

**Issue by omnat** [MetaMask/metamask-mobile#2171]
### Purpose:
When a user is using a custom network, they expect their assets to be shown in their wallet. In our current implementation the user will get an ownership error, as the assets aren't associated with the chain ID. 

### Requirements:

1. `wallet_watchAsset` works
2. `wallet_watchAsset `supports adding assets for different chain IDs (most likely by just using whatever the currently selected network is)
3. Every asset is associated with a chain ID

Then any dapp can simply send a wallet_watchAsset request to MetaMask, and the asset will appear in the user’s wallet, for the appropriate network.

**Comment by rekmarks** [comment]
If we associate the assets added using `wallet_watchAsset` using the currently selected network (and on reflection, that's probably the only option for now, even if we did change the method parameters to include a `chainId`), we have to make sure to check that the provided address actually corresponds to an asset contract on the currently selected network. I'm not sure if we already do that, but, here it is for the record, anyway.

**Comment by omnat** [comment]
Extension PR: https://github.com/MetaMask/metamask-extension/pull/10510
cc @brad-decker
