### ISSUE TITLE
Update 'seed phrase' wording to 'Secret Recovery phrase'

### ISSUE THREAD

**Issue by omnat** [MetaMask/metamask-mobile#2175]
### Problem:
User's wallet safety depends on their ability to keep their seed phrase safe, secret, and retrievable if/when they need to recover their wallet. However, the term 'seed phrase' isn't descriptive on its own, and often people don't read through our seedphrase flow to fully grasp the importance of it. 

### Acceptance criteria:
To help improve the comprehension of why seed phrase is important and how to keep it safe, we want to
- Change the naming to 'Secret Recovery phrase'
- Add a quick video explainer as an additional & more engaging learning medium in the onboarding flow of the app (also available after the user has onboarded): 
- Don't let the video file make the app size (significantly) heavy such that it makes the app slow or run into storage limit issues.

Figma: https://www.figma.com/file/Di5k5DTvxDWGv5DtIhwMb8/secret-recovery-phrase?node-id=2%3A4739

Video: (with subtitles file) https://github.com/MetaMask/metamask-extension/tree/develop/app/images/videos/recovery-onboarding
https://drive.google.com/file/d/1wGnIPb7OJXB7UeXt7k52vJAI4WgSB3HV/view?usp=sharing

### Out of scope (will add to another analytic story)
Include metric event so we can measure well how many people are viewing the video via mobile app during onboarding, and from settings (and can view this new metric in relation with how many people are completing the backup flow (effectiveness of the video))

**Comment by omnat** [comment]
Extension design for reference @cjeria : https://www.figma.com/file/EN7BT81mLsy0iq0rsGSa3N/Seed-phrase-security?node-id=0%3A1

**Comment by cjeria** [comment]
Suggested placement for the explainer video during onboarding https://www.figma.com/file/Di5k5DTvxDWGv5DtIhwMb8/secret-recovery-phrase?node-id=2%3A4739

**Comment by jakehaugen** [comment]
Looks like the right spot to me! Adding it in settings is nice as well. 

Maybe could use a small copy tweak? I took a pass:

`Don’t risk losing your funds. Watch this 2 minute video and learn how to keep your secret recovery phrase safe. It’s the only way to recover your wallet if you get locked out of the app or change your device. 
`

**Comment by cjeria** [comment]
Here are the final latest designs for adding the video to onboarding and in settings (contextually placed when viewing the seed phrase).

Figma file -> https://www.figma.com/file/Di5k5DTvxDWGv5DtIhwMb8/secret-recovery-phrase?node-id=52%3A199
![image](https://user-images.githubusercontent.com/597770/112190189-00e73200-8bc2-11eb-8619-2040f8b5706d.png)

**Comment by omnat** [comment]
Noting that in designs we haven't replaced 'Seed phrase' with 'Secret recovery phrase' - this makes sense as it's probably easier to find and replace it in code better. 
Just noting it here - please check acceptance criteria.

**Comment by mobularay** [comment]
@omnat CC @rickycodes has the analytic related story to this work been captured in a card in Github? Lmk, thanks!
