### ISSUE TITLE
Add better unit test for number parsing

### ISSUE THREAD

**Issue by omnat** [MetaMask/metamask-mobile#2177]
Current unit tests aren't comprehensive enough, and aren't failing cases that we are handling wrongly. 
cc @wachunei 

- Impacting 'Use Max' 
- Big Number edge cases

**Comment by omnat** [comment]
Unit tests are failing. Let's discuss the proposal to fix this and standardize cross platform (with extension)

**Comment by omnat** [comment]
@wachunei Is this done? Thought we completed this one before swaps release. If done, let's move it in the pipeline / close it. 
cc @mobularay

**Comment by wachunei** [comment]
Improved tests of the original `fromMinimalTokenUnit` function are somewhere there in a branch, but they are failing. the ones I created for swap's function `fromMinimalTokenUnitString` are passing and merged already. I think we need to discussed replacing every use of `fromMinimalTokenUnit` to a compatible adapted use of `fromMinimalTokenUnitString`, which is tested.

**Comment by mobularay** [comment]
Hi Pedro,  do we still need to address the above question, and depending on the conclusion we may need to create a new ticket? 

It is unclear if this ticket is in dev review status, or QA status. Pls add proper labels, thanks so much! @wachunei

**Comment by wachunei** [comment]
Consider this done. Can be closed.

**Comment by mobularay** [comment]
Already merged two months ago!
