### ISSUE TITLE
Can't debug android browser

### ISSUE THREAD

**Issue by CrackerHax** [MetaMask/metamask-mobile#2194]
**Describe the bug**
From documentation:

    `Debugging Android
    For more details, see this page.

    You should be able to inspect the mobile app using the console in the React Native Debugger in Chrome
    To debug a website (dapp) in the browser:
    Navigate to the website in the app's browser
    Go to chrome://inspect
    Select the relevant WebView under Remote Target`

This works for normal android chrome browser but metamask browser is not showing up as a remote target.

**Screenshots**
![image](https://user-images.githubusercontent.com/6037535/106370308-772b8e80-630d-11eb-930e-1a55a705705b.png)

**To Reproduce**
Follow instructions given for debugging.

**Expected behavior**
Expect metamask browser to show up as a remote target.

**Smartphone (please complete the following information):**
 - Device: Samsung a51
 - OS: Android 10
 - App Version 1.0.10 (44)

**Comment by arickuter** [comment]
Same issue on Samsung A32

**Comment by augustovicente** [comment]
Same issue on Xiaomi 12 Lite 5G NE
