### ISSUE TITLE
Creating password never resolves 

### ISSUE THREAD

**Issue by bpriddy** [MetaMask/metamask-mobile#2197]
Ive downloaded the app and started on setting things up, but the creating password screen never resolved. I was able to go to the site on my phone and follow the link to download the app which opened the app, displayed a “deep link not supported” dialog and bypassed the password creation step. I thought the password had simply updated on the backend so I proceeded to send coins to the wallet.  When I open MetaMask from the Home Screen I was met with the same prompt to create a password. I tried again to encounter the same problem

**To Reproduce**
_Steps to reproduce the behavior_
1. Download the app
2. Open and begin setup 
3. Follow prompt to protect wallet
4. Encounter inability to move beyond password creation

**Expected behavior**
the creating password should resolve to the next screen. 

**Smartphone (please complete the following information):**

Device: iPhone 
is: iOS 14.3
 - App Version [e.g. 1.0.0] - find version number in app from Settings > About MetaMask

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by gantunesr** [comment]
Hey @bpriddy, is this still an issue in the latest release?

**Comment by gantunesr** [comment]
Please open a new issue using the "Bug Report" template if this issue persists in the latest release
