### ISSUE TITLE
Captcha doesn't work on Android 

### ISSUE THREAD

**Issue by ibrahimtaveras00** [MetaMask/metamask-mobile#2199]
**Describe the bug**

If I attempt to "Learn more" on the create password page, I am unable to proceed as captcha doesn't work correctly.  Same thing happens if you go to Settings > About MetaMask > Visit our Support Center.  Another location is during onboarding on the "Secure your wallet" page, tap "Why is it important?" and then "Learn More".

**Screenshots**

Seen here = https://recordit.co/lRjByJNErS

**Expected behavior**

Captcha should work and I should be able to proceed

**Smartphone (please complete the following information):**
 - Device: Android
 - OS: Was able to reproduce on OS 9 - 11 may be happening on others as well
 - App Version All versions

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by tommasini** [comment]
This is not happening in emulator pixel 3 Android version 12 and physical device Android version 11
Do not show any Captcha or any I’m not a robot test
Thank you so much for reporting, I'm closing this issue, please if something it's not right reopen it or write a new one.
