### ISSUE TITLE
Metamask eth_chainId return 0 even though the network have 1337 as chainId

### ISSUE THREAD

**Issue by wighawag** [MetaMask/metamask-mobile#2202]
**Describe the bug**
Metamask eth_chainId return 0 even though the network have 1337 as chainId

**To Reproduce**
1. launch ganache on a computer in the same network
2. add network http://192.168.0.x.xip.io:8545 chainId 1337
3. go to an app that return the current chainId, it shows "0"

**Comment by pakokrew** [comment]
I can confirm that, on Android, even when the wallet is on mainnet, `ethereum.chainId` returns 0

On iOS it works fine (returns 1 for mainnet)
