### ISSUE TITLE
Can't login to github

### ISSUE THREAD

**Issue by rickycodes** [MetaMask/metamask-mobile#2207]
**Describe the bug**
Can't login to github on mobile instead it redirects to `/session`:

**Screenshots**
![image](https://user-images.githubusercontent.com/675259/106805502-c38c0c80-6634-11eb-8a7b-4cae1b6a29b1.png)

**To Reproduce**
_Steps to reproduce the behavior_
1. Try to login to Github

**Expected behavior**
I should get logged it

**Smartphone:**
 - Device: Android Pixel3 API29
 - OS: Android version 10
 - App Version: `develop` branch

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by ibrahimtaveras00** [comment]
Also can't log into Google account

![image](https://user-images.githubusercontent.com/41752922/106806725-49f51e00-6636-11eb-88e8-ff7864c7851e.png)

**Comment by rickycodes** [comment]
yea ISTM we might have broken something (maybe cookies) in v1.09

**Comment by itsmontoya** [comment]
We're experiencing this issue for a crypto project login as well

**Comment by Chainfire** [comment]
Seems like a cookie issue. Seeing the same thing with one of our projects, login doesn't work. Works fine from Android Chrome (with WalletConnect), MetaMask on iOS, and desktop browsers - just not on MetaMask on Android.

**Comment by jimrubenstein** [comment]
Any movement on this?

**Comment by Fatxx** [comment]
Closing in favour of https://github.com/MetaMask/metamask-mobile/issues/4245
