### ISSUE TITLE
Validation on custom spend limit

### ISSUE THREAD

**Issue by jakehaugen** [MetaMask/metamask-mobile#2223]
Custom spend limit must be at least the amount specified to swap. If a user attempts to set a lower spend limit we should show and error and disable the "Set" button. 

See designs here: https://www.figma.com/file/VVjoLHG6X74lXmh6CN3r7H/Swaps?node-id=1584%3A2263

_Note: We seem to have mixed patterns on how to show errors on form fields. Use whatever pattern is easiest to implement, although the inline error is preferred. We plan to standardize them in the future. For example, on gas price it shows differently: https://www.figma.com/file/VVjoLHG6X74lXmh6CN3r7H/Swaps?node-id=1584%3A2288 ._

**Comment by estebanmino** [comment]
https://github.com/MetaMask/metamask-mobile/pull/2239
