### ISSUE TITLE
Add tooltip to educate to user about gas fee

### ISSUE THREAD

**Issue by omnat** [MetaMask/metamask-mobile#2232]
As a user, I want to understand what is gas fee, why I have to pay it (specially high even for a small transaction) and if it is a fee that MetaMask controls or charges. 

As a user, BEFORE I get crypto in MetaMask, I want to understand that to make a transaction, there's a network fee I have to pay, so that I can make a decision if I will put funds in MetaMask or not.
^ this need is from people who are more familiar with centralized apps that enable moving around funds without network fee. 

Out of scope:
As a user, when I speed up a transaction, I want to clearly see how much extra gas fee I am paying, and the total gas fee for that transaction.

**Comment by jakehaugen** [comment]
Figma file: https://www.figma.com/file/J8Gg2fYEY9iB0Mmi0DWk5E/Gas-Education?node-id=0%3A1

**Comment by mobularay** [comment]
@jakehaugen will continue to iterate, then sync with Christian for feedback either today or tomorrow.

**Comment by jakehaugen** [comment]
5 changes:

1. Update every mention of "Network fee" to "Gas fee".

2. Show a dialog with messaging about gas fees the FIRST TIME a user attempts to buy crypto in the app.

3. Update how the gas fee is edited (crypto amount is linked, "Edit" button has been removed) for all transaction screens (transaction, send and swaps).

4. Add a tooltip "i" icon that launches a dialog next to the "Gas fee" label on dapp transaction and send screens.

5. In swaps, add a tooltip "i" icon that launches a dialog next to the "Estimated gas fee" label. This launches a dialog with different text than the other transaction screens.

Mocks are here: https://www.figma.com/file/J8Gg2fYEY9iB0Mmi0DWk5E/Gas-Education?node-id=0%3A1

-----

Note: The changes to gas editing (link crypto amount vs. the "edit" button) had mixed reviews. The functionality was not intuitive to some just looking at the static mock ups. My hypothesis is that after interacting with the new version it will become intuitive to users. The main benefit is that it the hit area for the tooltip and edit function much easier to interact with and reduces the chance of not tapping the right hit area. Open to critiques of this change but leaning this way.

**Comment by mobularay** [comment]
The card is back in progress! @jakehaugen when you get a moment, can you add the new info here, pls? Thank you :-)

**Comment by jakehaugen** [comment]
Tooltips copy/design is final.

Switched the on-ramp dialog to a mandatory carousel. Proposed design is here, collecting feedback: https://www.figma.com/file/J8Gg2fYEY9iB0Mmi0DWk5E/Gas-Education?node-id=194%3A1069

@andrepimenta suggested moving this to the next release to avoid rushing.

**Comment by omnat** [comment]
@omnat @cjeria @wachunei to provide final feedback.

**Comment by jakehaugen** [comment]
Finalized the on-ramp carousel that explains gas fees. Mocks are here: https://www.figma.com/file/J8Gg2fYEY9iB0Mmi0DWk5E/Gas-Education?node-id=194%3A1069

Only change in this last round was to remove the "Simulate your swap" link that pushed users to try a swap before buying. Concern was that after they simulate their swap the users needs  to re-enter the buy flow. We should consider adding this link back once we optimize the "Swap > Not enough ETH > Buy more ETH" flow to smooth out the UX.

**Comment by mobularay** [comment]
@jakehaugen confirmed this ticket is now workable, @andrepimenta ! :-) 

Jake will be creating a new ticket to capture the out-of-scope work.

**Comment by mobularay** [comment]
The out of scope work mentioned here is now captured in [issue 2681 ](https://github.com/MetaMask/metamask-mobile/issues/2681)
