### ISSUE TITLE
Change how we pull token icons from eth-contract-metadata

### ISSUE THREAD

**Issue by omnat** [MetaMask/metamask-mobile#2234]
cc @estebanmino

**Comment by omnat** [comment]
Related? https://github.com/MetaMask/metamask-mobile/issues/2236

**Comment by ibrahimtaveras00** [comment]
I see this is in the review column, what needs to be done here in terms of QA? 
cc: @omnat / @estebanmino

**Comment by estebanmino** [comment]
just check the images are loading, is a small change

**Comment by estebanmino** [comment]
@omnat this won't fix that
