### ISSUE TITLE
Collectibles - Icon of _tokenURI (metadata) does not change

### ISSUE THREAD

**Issue by coin77** [MetaMask/metamask-mobile#2264]
I added a customised ERC721 collectible to my iOS Metamask wallet. The ERC721 contains a set of status which can change over time. After adding the collectible, the correct icon from the metadata (_tokenURI) shows up. However, once the _tokenURI changes, the icon under "Collectibles" in Metamask does not change.

**Comment by estebanmino** [comment]
Thanks for reporting @coin77

**Comment by estebanmino** [comment]
we should update the collectibles and not completely ignore if the image changed here https://github.com/MetaMask/controllers/blob/develop/src/assets/AssetsDetectionController.ts#L271

**Comment by mobularay** [comment]
Normally, the "needs-dev-reivew" label is applied at the PR level, but this PR is not showing up, so I am adding the label here to help with visibility

PR: https://github.com/MetaMask/controllers/pull/454
