### ISSUE TITLE
Gas is higher on app compared to Extension

### ISSUE THREAD

**Issue by ibrahimtaveras00** [MetaMask/metamask-mobile#2274]
Gas prices on app higher than on extension 

![Screen Shot 2021-02-22 at 8 28 38 PM](https://user-images.githubusercontent.com/41752922/108880633-7a463180-75d0-11eb-90dc-a2d713833db4.png)

![Screen Shot 2021-02-22 at 8 29 04 PM](https://user-images.githubusercontent.com/41752922/108880673-8205d600-75d0-11eb-9f85-6df72f3d5ce5.png)

![Screen Shot 2021-02-22 at 8 30 01 PM](https://user-images.githubusercontent.com/41752922/108880710-89c57a80-75d0-11eb-92de-01519392f87f.png)

**Comment by ibrahimtaveras00** [comment]
When doing this estimate comparing to extension on an account with same/similar amount of ETH and enough available, I didn't see any extremes

**Comment by omnat** [comment]
Why is the gas fee estimates different for extension v/s mobile? 
Just want to ensure the final fee that user pays for the swap on mobile isn't over estimated (more expensive than needed for the transaction), and not going to be insufficient either to fail the transaction. 

cc @estebanmino
