### ISSUE TITLE
Transaction error when attempt swap ETH to UNI

### ISSUE THREAD

**Issue by ibrahimtaveras00** [MetaMask/metamask-mobile#2275]
Attempted ETH to UNI swap and got a json-rpc error

![Screen Shot 2021-02-22 at 9 04 00 PM](https://user-images.githubusercontent.com/41752922/108880893-bb3e4600-75d0-11eb-93e7-4c5b83f3818e.png)

**Comment by ibrahimtaveras00** [comment]
Another example when attempting LINK to ETH = http://recordit.co/Ng3asFEHjU

**Comment by omnat** [comment]
Related? https://app.zenhub.com/workspaces/metamask-mobile-5f984938ddc0e4001d4b79cb/issues/metamask/metamask-mobile/2014

**Comment by ibrahimtaveras00** [comment]
Couldn't reproduce this in latest builds
