### ISSUE TITLE
App crashes using sites which initiate a blob download

### ISSUE THREAD

**Issue by Lambdac0re** [MetaMask/metamask-mobile#2278]
**Describe the bug**
java.lang.IllegalArgumentException: Can only download HTTP/HTTPS URIs: blob:https://.................

**To Reproduce**
1. Go to https://app.tornado.cash/
2. Click on 'DEPOSIT'
3. MetaMask shuts down

**Expected behavior**
A file download is initiated.

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S7 (SM-G930F)
 - OS: Android 8.0
 - App Version: v1.0.10 (44)

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by mathijs81** [comment]
Same happens when creating a client-side image and trying to save it.
E.g. on https://mdigi.tools/solid-color-image-generator/ clicking the "Download PNG" button crashes metamask on my Android.

**Comment by Lambdac0re** [comment]
Still unfixed, see this issue: #2195
