### ISSUE TITLE
Transaction history only loads on swaps testnet and mainnet

### ISSUE THREAD

**Issue by ibrahimtaveras00** [MetaMask/metamask-mobile#2281]
When I import my account on prod, I see all my txn history from other testnets (rinkeby + ropsten) but currently that's not the case on swaps branch

seen here = https://recordit.co/1ZJG45TYAd

**Comment by omnat** [comment]
That's likely intentional, right @estebanmino ? 
We are now filtering transaction history by chainid, correct?
