### ISSUE TITLE
Android not receiving Wallet Connect + deeplink notifications 

### ISSUE THREAD

**Issue by ibrahimtaveras00** [MetaMask/metamask-mobile#2286]
On iOS when I confirm a txn via wallet connect, I see the notification as I should, but on Android there isn't any notification 

seen here = http://recordit.co/PvpgYLT5TR

**Comment by ibrahimtaveras00** [comment]
Same goes for deeplink Approve confirmation; seen here = http://recordit.co/bdWPs8AuRJ

I used the following deeplink to get there:

https://metamask.app.link/approve/0x1d7a9cd8c67e3c74a84bb76cbc1b606e2e460db5@4/approve?address=0x1FDb169Ef12954F20A15852980e1F0C122BfC1D6&uint256=1

**Comment by estebanmino** [comment]
already fixed

**Comment by ibrahimtaveras00** [comment]
Fixed = http://recordit.co/fBy4hprINN 👍🏽
