### ISSUE TITLE
No web3 detected

### ISSUE THREAD

**Issue by roo-shy** [MetaMask/metamask-mobile#2308]
"no web3 detected" when accessing: stake.yfdai.finance, etherfyer.com

<img width="315" alt="Screen Shot 2021-02-26 at 12 00 43 PM" src="https://user-images.githubusercontent.com/13618162/109337370-4e25ed00-782a-11eb-9fe9-4fa3c46777a4.png">

_Steps to reproduce the behavior_
1. Go to Browser
2. Search stake.yfdai.finance
3. See error: `No web3 detected`

**Expected behavior**
No errors

 - Device: Android
 - App Version [1.0.11] 
 
-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by lsqproduction** [comment]
App Version [1.0.11]
Apple m1 app 
<img width="269" alt="Screen Shot 2021-02-26 at 12 08 52 PM" src="https://user-images.githubusercontent.com/12772017/109338164-824ddd80-782b-11eb-802b-6a56b3a31fca.png">

**Comment by omnat** [comment]
@lsqproduction On iPhone, I tried to reproduce it, and after a few seconds of this Cloudflare screen, it redirected me to the site. I then tapped 'Connect Wallet', and it showed me a Connect request, accepted it, and it worked (got no error). 

@roo-shy On Android, does the user continue to get the `web3 not found` error after the tap 'Connect Wallet' button?

**Comment by lsqproduction** [comment]
@omnat for Android, yes the error message does persist. I tried changing networks and Reintall

**Comment by AlexHerman1** [comment]
zd ticket: 88649

**Comment by DevJxyden** [comment]
I'll second this issue. I cannot get metamask mobile to detect provider but does work in desktop chrome extension. See: https://hpbcentral.com/dapps/HodlLottery/test.html or attached file.
[mmtest.txt](https://github.com/MetaMask/metamask-mobile/files/6206942/mmtest.txt)

**Comment by jigs1996** [comment]
yes, it's the same for me I have used ```@metamask/detect-provider``` to detected web3 providers as specially for metamask.
site: https://app.egg.fi
it's not working on android mobile using metamask browser, but its works in any desktop browser
metamask version is the current one

**Comment by andrepimenta** [comment]
This should be fixed in newer releases.
