### ISSUE TITLE
Browser freezes on load

### ISSUE THREAD

**Issue by Rodri-R** [MetaMask/metamask-mobile#2313]
**Describe the bug**
The browser feature freezes after clicking on it on an Android device.

**Screenshots**
https://user-images.githubusercontent.com/46242399/109423164-c0d7c980-79de-11eb-80e6-31ff6d935200.png

**To Reproduce**
_Steps to reproduce the behavior_
1. I open the app
2. I access my wallet
3. I open the menu and click on Browser
4. Browser freezes, does not load and remains in a white screen.

**Expected behavior**
Open the browser feature and see all the options.

**Smartphone (please complete the following information):**
 - Device: Huawei Mate 10
 - OS: Android 8.0
 - App Version: MetaMask v1.0.11 (46)

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?
![Screenshot_20210228-160221](https://user-images.githubusercontent.com/46242399/109423164-c0d7c980-79de-11eb-80e6-31ff6d935200.png)

**Comment by Fatxx** [comment]
@Rodri-R can you please update to the latest version of MetaMask?

**Comment by gantunesr** [comment]
Hi @Rodri-R, I'll close this issue for the moment, please open a new one if this problem persists
