### ISSUE TITLE
Unable to connect to custom RPC network - Could not fetch chain ID. Is your RPC URL correct?

### ISSUE THREAD

**Issue by Siegrift** [MetaMask/metamask-mobile#2314]
**Describe the bug**
I am running [ganache-cli](https://hub.docker.com/r/trufflesuite/ganache-cli/) on my development machine. I can connect and develop my application using metamask browser extension, but now I want to do the same from metamask mobile app.

When I try to [create a new RPC network](https://metamask.zendesk.com/hc/en-us/articles/360043227612-How-to-add-custom-Network-RPC-and-or-Block-Explorer) I get the following error: `Could not fetch chain ID. Is your RPC URL correct?`

_My motivation is to test wallet connect integration for my Dapp. I am quite sure metamask mobile app should be able to retrieve and connect to the ganache instance - I am running on a local network on both devices (laptop and mobile) and I can access my Dapp from mobile chrome browser. I can also use JSON RPC call to get the `chainId` to ganache from my android device directly. Calling `curl -X POST --data '{"method":"eth_chainId","params":[]}' http://192.168.1.22:8549` gives me back `{"result":"0x539"}` which is `1337` decimal._

**Screenshots**
![156089266_438903020754869_2230286705131080746_n](https://user-images.githubusercontent.com/22679154/109496166-96464900-7a90-11eb-8bfa-2405cabc5f2e.png)

**To Reproduce**
1. Run ganache CLI on some workstation
2. Download metamask mobile wallet and try to register a custom RPC network
3. Be on the same network - (maybe you need to turn off firewall on the workstation)
4. You should be able to access `ganache-cli` - e.g. try the web request I presented above.
5. Try to specify the custom RPC params - see attached screenshot
6. See the error `Could not fetch chain ID. Is your RPC URL correct?`

**Expected behavior**
Connect to the ganache instance and successfully create a new RPC network.

**Smartphone (please complete the following information):**
 - Device: [e.g. Huawei p9]
 - OS: [e.g. Android 7.0]
 - App Version [e.g. 1.0.11]

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by Siegrift** [comment]
This seems to be a duplicate of https://github.com/MetaMask/metamask-mobile/issues/1774, which I didn't find at the time.

However, the steps outlined in that issue are similar to the ones I've made - apart from not mentioning that your firewall may block the incoming requests from your mobile device, so you might need to disable firewall (temporarily)

**Comment by toki-jonathan** [comment]
any update on this? I'm running into the same issue with hardhat.

On Android with latest Metamask on google playstore

**Comment by sg495** [comment]
I am experiencing exactly the same issue with MetaMask 3.2.0 on Android 11, in my case trying to connect to a local Geth node.

**Comment by MarshallMiller** [comment]
I am experiencing the same issue.  I am running MetaMask 3.2.0 on Android 11 and am trying to connect to a HardHat node on a VM running on my local network.  I am running tcpdump in the VM and filtering on the port that the node is listening on and I see no traffic come through when the URI prefix is "http".  If I switch the URI prefix to https I do see traffic come through, but of course this does not work because HardHat does not use SSL/TLS.  Also, I am able to browse to the node URL on my device and I see traffic some through, so I am certain that this is not a firewall issue on my node system.

**Comment by MarshallMiller** [comment]
I stood up a reverse proxy using nginx so that I could try with TLS.  I am able to connect with the Chrome MetaMask extension just fine.  The Android app performs the handshake but the connection ends with Alert (Level: Fatal, Description: Certificate Unknown).  I imported the self-signed CA cert into Android security settings and my browser does no longer gives a warning, but MetaMask still refuses to connect.

**Comment by jzarza-np** [comment]
Same problem for me. It seems Metamask Mobile requires https and not allows http as the desktop version.

I've managed to make it work using a ngrok tunnel (ngrok.com). Despite it isn't the best way to do it, you can work with that for a while.

**Comment by adeebabdulsalam** [comment]
I have run into this same issue. So right now metamask mobile only allow https, but not https

**Comment by hixus** [comment]
Run also into this. What makes it really annoying is that there is no sensible error message, just something about chain id. Especially as metamask browser allows http traffic.

**Comment by ManaanAnsari** [comment]
same issue here :(
metamask app should have some kind of developer mode toggle  
if its enabled allow using HTTP network

**Comment by rho-cassiopeiae** [comment]
Still doesn't work on 7.2.0.
According to the docs, on Android you should connect to `http://{private-ip}.sslip.io:{port}`. But it doesn't work. Fails with "Could not fetch chain ID. Is your RPC URL correct?" error.

ngrok workaround from above works. Simply download ngrok and run `ngrok http {port-of-local-eth-network}` and then from the app connect to the https url that ngrok gives in the output.
