### ISSUE TITLE
Show correct gas on custom networks

### ISSUE THREAD

**Issue by omnat** [MetaMask/metamask-mobile#2316]
As a user, when I am transacting on side chains & layer 2s, show me only the gas price determined on that network (which is usually way lower than the L1/mainnet prices).

This is not going to be a gas estimate, rather a predefined gasPrice. 

Acceptance criteria:
- This should work for all the transactions - user-initiated send, dapp-prompted approve/confirm
- Accurate gas prices based on network
- Do not show option to speedup/cancel these type of transactions
- For all gas estimations (e.g., on mainnet), if the gas API fails (gives an error, or API is down or API is irresponsive), then fall back on gasPrice

Might need to see if we should hide Slow/Default/Fast options in the gas options.

Extension PR for reference: https://github.com/MetaMask/metamask-extension/pull/10444

**Comment by mobularay** [comment]
@andrepimenta needs to resolve the last item in the Acceptance Criteria list above before Peer Review and QA.

**Comment by vittominacori** [comment]
I don't know if related: MetaMask mobile suggests a gas price of 164 gwei on BSC also if I use `gasPrice: '10000000000'` in web3.Contract `deploy(...).send(options)`.
