### ISSUE TITLE
Token list is too short compared to extension 'swap to' list

### ISSUE THREAD

**Issue by omnat** [MetaMask/metamask-mobile#2327]
In the drop down list of tokens, I see only top 5 tokens, not the scrollable list like in extension. Was this by design? Is there a reason to keep it short - the experience of a longer list is better and scrolling is easy enough.
cc @wachunei

**Comment by wachunei** [comment]
Yes

**Comment by ibrahimtaveras00** [comment]
http://recordit.co/I3ueQk6Rr3 👍🏽
