### ISSUE TITLE
MetaMask Mobile assumes all .xyz domains are ENS

### ISSUE THREAD

**Issue by thebaoman** [MetaMask/metamask-mobile#2332]
**Describe the bug**
Metamask mobile is set up to support the ENS integration for .XYZ domain names. However, it assumes that *all* .xyz domain names are ENS names and issues a "failed to resolve" message if they do not load from ENS.

**To Reproduce**
_Steps to reproduce the behavior_
1. Go to 'Browser'
2. Type in 'alphabet.xyz' or 'baoswap.xyz'
3. MetaMask prompts a 'failed to resolve ENS name' error.

**Expected behavior**
If the name fails to resolve in ENS, MetaMask Mobile should then attempt to load the standard http/https domain from DNS.

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by individualpirate** [comment]
This needs to be fixed. I added ENS just so my site could load on Metamask mobile, and it helps, but only if you're connected to Ethereum. If you're connected to other networks it still fails. Bad for all .xyz sites, regardless if they have ENS or not.

**Comment by 0xMadxi** [comment]
Confirmed that this issue still exists.

**Comment by Valentin-Seehausen** [comment]
Is there any response to this? I would like to use the .xyz domain for my crypto project.

Or is there any fix?

**Comment by marekolszewski** [comment]
I agree with the proposed "expected behavior" here. Feels like a pretty easy change to make too.

**Comment by immasandwich** [comment]
@marekolszewski I think that's the behaviour that's occurring when the network is set to Ethereum, but this doesn't happen with Metamask is set to Arbitrum or Avalanche (for example).
