### ISSUE TITLE
Long password raises javax.crypto.IllegalBlockSizeException

### ISSUE THREAD

**Issue by diwangs** [MetaMask/metamask-mobile#2336]
**Describe the bug**
A sufficiently long password (in my case, 128 character) can make user unable to sign in. I consider this a bug because the same password works fine in MetaMask extension.

**Screenshots**
![Screenshot_20210304-040331_MetaMask](https://user-images.githubusercontent.com/27280516/109872636-44bfd900-7c9f-11eb-8d9b-129b220a3cbf.png)

**To Reproduce**
1. Generate new wallet on MetaMask extension
2. When asked for a password, enter a long password (e.g. 128 character)
3. Sync wallet to MetaMask mobile
4. Relaunch MetaMask mobile, you should arrive at the sign-in screen
5. Enter password and press "Log In"
6. Error!

**Expected behavior**
My password should be accepted by MetaMask mobile, just as it is accepted on MetaMask extension.

**Smartphone (please complete the following information):**
 - Device: OnePlus 6
 - OS: LineageOS 17.1
 - App Version: 1.0.11

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by gantunesr** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/MetaMask-Mobile-5f984938ddc0e4001d4b79cb/issues/MetaMask/metamask-mobile/2336?planning-poker) with ZenHub @Fatxx @plasmacorral

**Comment by gantunesr** [comment]
Internal conversation: https://consensys.slack.com/archives/GTQAGKY5V/p1644980997387359
