### ISSUE TITLE
MetaMask doesn't require authentication on next application launch on iOS if home button is pressed when authenticating via Touch ID

### ISSUE THREAD

**Issue by c4bade6fdec3d9cb86a281668cbab42b** [MetaMask/metamask-mobile#2347]
**Describe the bug**
If Touch ID authentication is enabled for MetaMask and if home button is pressed during authentication MetaMask closes but it remains open; meaning it doesn't require authentication on the next time the app is launched.

**Screenshots**

**To Reproduce**
1. Enable Touch  ID for MetaMask authentication.
2. Open MetaMask app.
3. Press the home button
4. App exits and on the next launch it doesn't require authentication.

**Expected behavior**
- If home button is pressed during Touch ID authentication and app exits it should re-authenticate on next app launch.
- When user backgrounds the app before full authentication completion, and foregrounds it again, they shall see the lock screen.
- When user backgrounds the app right after authentication completion, and foregrounds it again, they shall have access to the unlocked app.

**Smartphone (please complete the following information):**
 - Device: iPhone 8 plus
 - OS: iOS 14.4
 - App Version: v1.0.11 (579)

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by wachunei** [comment]
Hello @aXZhbg, thanks for the report. Can you please go to <kbd>Menu » Settings » Security & Privacy » Auto-lock</kbd> and indicate what value you have set?

**Comment by aXZhbg** [comment]
> Hello @aXZhbg, thanks for the report. Can you please go to Menu » Settings » Security & Privacy » Auto-lock and indicate what value you have set?

It is set to "Immediately". The locking works correctly if I press the home button/exit the application any time after the authentication.
The issue arises if home button is pressed when Touch ID prompt is showing.

Just a note -- obviously Touch ID authentication has to pass for this bug to happen.

**Comment by wachunei** [comment]
@aXZhbg When enabling Touch ID/Face ID, this authentication method is used _instead_ of having to type the password every time.

**Comment by aXZhbg** [comment]
> @aXZhbg When enabling Touch ID/Face ID, this authentication method is used _instead_ of having to type the password every time.

Sure, that's not what I'm arguing against -- that part works as intended. The issue/bug is that when during authentication home button is PRESSED so that the haptic feedback happens, the app exits and is unlocked on next launch.

**Comment by sethkfman** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/MetaMask-Mobile-5f984938ddc0e4001d4b79cb/issues/MetaMask/metamask-mobile/2347?planning-poker) with ZenHub @blackdevelopa @cortisiko @owencraston

**Comment by sethkfman** [comment]
Fixed by this PR: https://github.com/MetaMask/metamask-mobile/pull/6653
