### ISSUE TITLE
MetaMask mobile doesn't support full MetaMask API

### ISSUE THREAD

**Issue by Chef-Chungus** [MetaMask/metamask-mobile#2359]
**Describe the bug**
MetaMask Mobile does not support network switching or adding custom networks by API.

**Steps to reproduce (REQUIRED)**
PancakeSwap is using the `switch to network` and `add custom network` API on the website for MetaMask browser extension, the app doesn't work with these.

**Expected behavior**
I expect MetaMask mobile to support the full MetaMask API

**Screenshots**

**Phone details (please complete the following information):**
- IOS 14.4
- Iphone XR
- MetaMask v1.0.11 (579)

**Additional context (Error Messages, etc.)**
Video of the browser extension working as expected. (this is not possible on mobile because it doesn't work)
https://user-images.githubusercontent.com/71833681/110421459-e94b7c00-80e0-11eb-8c49-be8f5fde6847.mov

**Comment by wivern-co-uk** [comment]
Same issue [beefy.finance](https://app.beefy.finance/) is facing.
API method which should be implemented: `wallet_addEthereumChain`
Metamask docs: https://docs.metamask.io/guide/rpc-api.html#wallet-addethereumchain
https://eips.ethereum.org/EIPS/eip-3085

**Comment by ronanyeah** [comment]
I would also like to see `wallet_addEthereumChain` implemented.

**Comment by omnat** [comment]
Thanks for bringing this up. Closing as Release 2.1 (getting release next week) includes the support for Custom Network API support on MetaMask mobile as well.
