### ISSUE TITLE
Correctly recognize the network I am on

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-mobile#2385]
QA - to ensure that when the network changes, it promptly updates the state and the site shows connection to the active network and active account.

This should work both when user is on in-app browser, and when they are opening MetaMask via walletconnect

**Comment by omnat** [comment]
@ibrahimtaveras00 I remember this was done and released. Can you confirm?

**Comment by ibrahimtaveras00** [comment]
I currently still have this issue open https://github.com/MetaMask/metamask-mobile/issues/2113

The uniswap dapp issue was solved, but the issue with having to reload the site while on metamask.github.io/test-dapp still exists (it's the second to reproduce under "on android")

**Comment by mobularay** [comment]
Does this issue requires a Dev to work on it? Or is it solely just QA work? Pls add proper labels (dev review or QA) pls, thank you! @ibrahimtaveras00

**Comment by mobularay** [comment]
Test dapp has this problem; not sure if impacting other dapps. Impacts (as far as we know) MetaMask developers. May need to engage the extension team. Low severity, as far as we know. Will revisit this in two sprints.

**Comment by ibrahimtaveras00** [comment]
While regression testing RC 2.4.0 I could no longer reproduce this issue on neither OS's, so closing this out as it's no longer an issue!
