### ISSUE TITLE
Show me correct gas price for all transactions

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-mobile#2386]
As a user, when I am transacting on side chains / layer 2s, show me only the gas price determined on that network (which is usually way lower than the L1/mainnet prices).

This is not going to be a gas estimate, rather a predefined gasPrice. 

Acceptance criteria:
- This should work for all the transactions - user-initiated send, dapp-prompted approve/confirm
- Accurate gas prices based on network
- Do not show option to speedup/cancel these type of transactions
- On the mainnet, when the gas estimation API is down/fails, then fall back to the default gasPrice 

Might need to see if we should hide Slow/Default/Fast options in the gas options.

**Comment by omnat** [comment]
Same as #2136
