### ISSUE TITLE
Make it easy to add the required network

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-mobile#2387]
As a user, I want to be able to add the site recommended network securely, timely, easily (without having to research much)

Acceptance criteria:
1. Custom Network API works on mobile addEthereumchain method
2. Analytics to note site recommendations (+catch malicious ones), track what network people are using

**Comment by omnat** [comment]
Duplicate of https://github.com/MetaMask/mobile-planning/issues/65
