### ISSUE TITLE
Instead of ETH - show me native currency (+symbol)

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-mobile#2388]
As a user, when I am on a custom network where the native currency is not ETH, show me the native currency & logo/symbol in the balance thumbnails (e.g., in account switcher, default currency in send/receive flows)

**Comment by mobularay** [comment]
@omnat is checking with Jacob if we can get a more holistic list. 
For now, let's show the grey circle with first letter of the currency of the token. Better than showing just the ETH symbol.
