### ISSUE TITLE
View my assets displayed accurately (specific to the network)

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-mobile#2391]
As a user, I want to accurately view the assets I own on the currently active network, including accurate balance. 

Acceptance criteria:
- Assets must be assigned to chain ID 
- This should work for both test nets and other chains
- Assets include all token types we support: ERC20, ERC721, ERC 1155

**Comment by AlexHerman1** [comment]
Zd ticket #109909

**Comment by omnat** [comment]
Will #2110 be resolved with this one?
