### ISSUE TITLE
Suggest to add asset to user's account

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-mobile#2397]
As a dapp developer, I want to request user to add an asset to their account, so that they don't have to manually add custom token.

- Ensure that the dapp can hear/identify which chain the user is on. 
- watchAsset to work on different networks - watchAsset to have a chain ID associated with it (suggest it as an EIP change)

**Requirements:**
wallet_watchAsset works
wallet_watchAsset supports adding assets for different chain IDs (most likely by just using whatever the currently selected network is)

**Comment by omnat** [comment]
Comment by Erik made in #2171 

> If we associate the assets added using wallet_watchAsset using the currently selected network (and on reflection, that's probably the only option for now, even if we did change the method parameters to include a chainId), we have to make sure to check that the provided address actually corresponds to an asset contract on the currently selected network. I'm not sure if we already do that, but, here it is for the record, anyway.

**Comment by estebanmino** [comment]
this is currently working, and will be assigned to specific chainIds with https://github.com/MetaMask/metamask-mobile/pull/2441
the only thing "issue" is that we don't have the correct icons for these tokens so we display identicons instead

**Comment by ibrahimtaveras00** [comment]
This does seem to work on latest develop 

adding USDT on mainnet = http://recordit.co/5vFkmjoTyy

As @estebanmino mentioned, for custom networks, it shows the identicons instead

xDAI Chain = http://recordit.co/azexazhhMG
