### ISSUE TITLE
Technical research for Snap execution environment for mobile

### ISSUE THREAD

**Issue by omnat** [MetaMask/metamask-mobile#2401]
https://docs.google.com/spreadsheets/d/1E5KyFOHhKNm7fUaSH-cayJzZqzEbEQF2_dgUYu6QuCk/edit#gid=0

Purpose of this to test if snaps can run in a secure (contained) & performant way on mobile platform.
Test the different execution environment on mobile

**Comment by andrepimenta** [comment]
Tracking SES compatibility with React Native progress: https://github.com/endojs/endo/issues/661
