### ISSUE TITLE
Token Detection work: Improve token visibility in wallet

### ISSUE THREAD

**Issue by omnat** [MetaMask/metamask-mobile#2409]
See brief here: https://www.notion.so/MetaSwap-s-token-API-for-MetaMask-d8b3f08f81974a23887eb4cb899b3a42

**Comment by mobularay** [comment]
sdfdsfs

**Comment by cjeria** [comment]
copying over a question from [this issue](https://app.zenhub.com/workspaces/metamask-mobile-5f984938ddc0e4001d4b79cb/issues/metamask/metamask-mobile/2394)

Since this issue is related to the [add token issue](https://app.zenhub.com/workspaces/metamask-mobile-5f984938ddc0e4001d4b79cb/issues/metamask/metamask-mobile/2409) Is it possible to detect when the user is trying to add Ethereum tokens when on a non-mainnet network? If so, I was thinking we should suggest to the user to switch to mainnet within the empty state and vis-a-versa (if on mainnet, and they are trying to add BSC token).

Alternatively, what if we add a network dropdown on all custom add network screens (no matter the network) that way if a user is on mainnet and they are trying to add a custom chain token, they can do so from mainnet? cc @omnat @estebanmino

**Comment by omnat** [comment]
(from discussions during mobile design sync April 1st)
**How might we support this user need in a safe way**
1. Consider patterns like we have in swaps 'token available on 6 lists'. In this case, we could consult a bigger token list (perhaps aggregated from various token lists at tokenlists.org). And if we see conflicting info on this token from different lists, then notify user that this token data may be incorrect - proceed with caution. 
2. If the account gets >0 balance on a token (pulled from a big list) - show a subtle indication in the token list (+2 tokens), if user taps on it, then show them the tokens that have and amount - and give the option to user to explicitly add or ignore (or keep hidden) that token.
3. If user adds a custom token that is present in a deny / blacklist, then show warning so user knows this might not be a very trustworthy and they proceed with caution.

**Comment by mobularay** [comment]
Epic documentation: https://www.notion.so/MetaSwap-s-token-API-for-MetaMask-d8b3f08f81974a23887eb4cb899b3a42

**Comment by omnat** [comment]
Update on design:
1. In divergent phase - need to collaborate with people and get the design directions reviewed. 
2. Converge on a direction with alignment
3. After finalizing design on mobile, needs adaptation to extension.

**Comment by mobularay** [comment]
@cjeria focusing on finishing this up after feedback from Engineers :-) Skimming down the designs to MVP, will review with the team again, then pass over to Yanrong to translate to Extension designs. 

Planning for high-level usability testing internally. Will set this up :-)

**Comment by mobularay** [comment]
@omnat and @cjeria to sync on the next MVP versions.

**Comment by mobularay** [comment]
@cjeria and @omnat synced on the MVP work, and after tying up some loose ends, Christian can move this card to "Ready for Development" column today! :-)

**Comment by mobularay** [comment]
Still have some more comments to review in Figma; will stay in "Design in Progress" status until the comments are addressed. https://www.figma.com/file/1QISZ3M6lUs9i5uFUPK5Xu/Token-Detection-(mobile)?node-id=377%3A112

**Comment by mobularay** [comment]
Update from @omnat: last Thursday, metaswaps API is almost ready! So hopefully it will be completed this week, then the implementation work in Mobile can start. This could be a good first project for Cal! 

@omnat and @sethkfman  and Cal to sync on this.

**Comment by mobularay** [comment]
@cjeria bringing different elements together for Extension, Mobile, Swaps, dapps on wrong network :-) 
Looking to get this more completed today. Next step: light usability testing with the new designs? Christian to sync with @omnat after stand-up

**Comment by mobularay** [comment]
Waiting for feedback on copy (tagged on Figma) - @omnat @jakehaugen @wachunei (b/c of swaps related work)

**Comment by mobularay** [comment]
@cjeria to schedule a call to finalize MVP with @omnat , @jakehaugen , @wachunei, @yanrong-chen . Need to align with Extension's work too: https://www.notion.so/Improve-token-detection-d8b3f08f81974a23887eb4cb899b3a42

**Comment by andrepimenta** [comment]
First good projecto for Cal, handing off soon.

**Comment by mobularay** [comment]
@cjeria is the design work for this project completed? :-)
