### ISSUE TITLE
Copyright in the readme states 2016-2019

### ISSUE THREAD

**Issue by shawynot** [MetaMask/metamask-mobile#2412]
**Description**
The license section of the readme states: © ConsenSys AG, 2016-2019

**Screenshots**
_If applicable, add screenshots or links to help explain your problem_
![image](https://user-images.githubusercontent.com/42036966/111682786-24ddf880-87fb-11eb-926a-dd0ea0a245f2.png)

**To Reproduce**
1. Open the readme
2. Scroll to license section
3. Validate the copyright 

**Expected behavior**
The copyright would be updated to the current year. 

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user? Trivial
- Add stats if available on % of customers impacted
- Is this visible to all users? Yes
- Is this tech debt? Unclear

Such a petty issue, hope I did this right and didn't cause any issues!

**Comment by omnat** [comment]
Thanks for notifying, we'll update this.
