### ISSUE TITLE
I can't remove the COLLECTIBLES after add.

### ISSUE THREAD

**Issue by lolieatapple** [MetaMask/metamask-mobile#2424]
I can't remove the COLLECTIBLES after add.

I can add a custom COLLECTIBLES token.

But I can't find how to remove it.

I think you have not design a remove button.

I need to remove, thanks!!!

**Comment by omnat** [comment]
Hi thanks for the feedback. You can remove the collectible but going to Collectible > Open the category > Long tap on the collectible you want to remove > Tap on 'Remove' option that pops up. 
We'll take this feedback to improve the usability so this feature is more discoverable.

**Comment by lolieatapple** [comment]
yes, it works. thanks.
