### ISSUE TITLE
Incorrect warning when Syncing with seedphrase QR

### ISSUE THREAD

**Issue by ibrahimtaveras00** [MetaMask/metamask-mobile#2429]
**Describe the bug**

Use Case: I am trying to sync with extension, except instead of scanning the right QR code, I scan a seedphrase QR code

We no longer have this option in Settings > Advanced, so we should change the wording on this warning to correctly reflect the action being taken

**Screenshots**

<img width="529" alt="Screen Shot 2021-03-23 at 2 44 19 PM" src="https://user-images.githubusercontent.com/41752922/112212471-6b649600-8bf3-11eb-8d22-28b8781665c9.png">

**To Reproduce**

1. Go to Wallet Setup
2. Tap on Sync with MetaMask extension
3. Instead of scanning a Sync QR code, Scan a seedphrase QR code
Here goes a test wallet seedphrase QR I just created to make things more convenient

![Screenshot 2021-03-23 at 4 23 13 PM](https://user-images.githubusercontent.com/41752922/112213119-242ad500-8bf4-11eb-9abc-ec89b23d4db7.png)

**Expected behavior**

I should see an up to date warning that makes sense 

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by omnat** [comment]
Copy suggestion for the warning update:

`Looks like you're trying to sync with your extension wallet. Please use the QR code shown in the 'Sync with mobile' option in MetaMask extension settings.`
cc @cjeria

**Comment by Gudahtt** [comment]
>We no longer have this option in Settings > Advanced, so we should change the wording on this warning to correctly reflect the action being taken

It looks like it's still there to me :thinking: The extension still has mobile sync under 'Settings > Advanced'.

**Comment by ibrahimtaveras00** [comment]
oh hold on I read this wrong, I thought this was alluding how to do it the old way in our app when we used to have the option to sync in our settings.

But now re-reading that error, it totally makes sense because it's saying browser extension.  My bad lol, thanks for pointing out @Gudahtt 

@omnat not sure if we still want to change the wording now, but I was confused and misread that warning.  I'll keep open in case we still want to change

**Comment by Gudahtt** [comment]
Agreed that it is easy to misread! The qualifier "in the extension" is kinda buried there. Plus the lack of quotes around 'Sync with Mobile" makes it seem like it's asking you to navigate there _with_ mobile.

Here's an attempt at re-ordering things to be a bit more clear:

>This isn't the right QR code! To sync with your browser extension, open the extension and navigate to "Settings\" > \"Advanced\" > "Sync with Mobile" then scan the QR code shown.

**Comment by cjeria** [comment]
Here's the idea I brought up during bug triaging regarding QR codes. There a obv. different ways to solve the confusion around scanning the wrong QR code but here's one idea where we could mention in the scan flow (depending on which one) to scan the "Red QR code with the MM fox logo" and do similar for other types of QR codes
![image](https://user-images.githubusercontent.com/597770/114096160-33a45200-9873-11eb-929c-87c20917bc52.png)
