### ISSUE TITLE
Injected web3 provider not available in internal browser when using cloudflare DDOS

### ISSUE THREAD

**Issue by peak3d** [MetaMask/metamask-mobile#2435]
**Describe the bug**
If we launch our dapp (https://app.wows.finance) without cloudflare ddos protection, we can access window.ethereum.
If we activate cloudflare ddos protection, window.ethereum is not available. The only way to connect is going over walletconnect.

**To Reproduce**
_Steps to reproduce the behavior_
1. Go to https://app.wows.finance
2. Log or debug window.ethereum

**Expected behavior**
window.ethereum should be available

**Smartphone (please complete the following information):**
 - Device: [Huawei Mate 10 Pro]
 - OS: [EMUI 9.0.0 / Android Version 9]
 - App Version [2.0.1]
 
**Notes:**
- If you can provide an apk with webview debug information I can support debugging
------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by Gaspachow** [comment]
Hello, noticed the same issue.

It doesn't seem fixed for me on MetaMask 3.1.0 (latest update on Aug 16, 2021) for Android.
I however can't replicate this bug on iOS or Desktop.

This issue has been reported by our users but I found the same problem can be replicated on other notable sites using CloudFlare such as [OpenSea](https://opensea.io) or [Axie Inifinity marketplace](https://marketplace.axieinfinity.com/axie).

More information:
- If I am using a VPN to trigger the CloudFlare browser check, it will stay stuck at `checking browser` indefinitely.
- With no VPN, all sites are accessible but `window.ethereum` is not found.

**Comment by xtools-at** [comment]
hi, this is apparently still an issue, could anyone look into this?

**Comment by hesterbruikman** [comment]
Closing as this issue seems stale and couldn't reproduce with https://app.axieinfinity.com/ that seems to have ddos protection enabled.

**Tested on**
Version:  6.4
OS: Android 11
Device: Galaxy s10e

![Screen_Recording_20230427-151923_MetaMask_1.gif](https://images.zenhubusercontent.com/642ee475fe4785065d435150/78c6faf1-ba44-4a89-9f02-7aa6d342d166)
