### ISSUE TITLE
Transaction History Storage and Performance Improvement

### ISSUE THREAD

**Issue by sethkfman** [MetaMask/metamask-mobile#2438]
**Describe the usability problem**
As a user generates more transaction data their history continues to grow and this has resulted in a couple of issues around storage of transaction data and performance on loading transaction lists. 

**Screenshots**
NA

**Expected behavior**
As a user I would like to be able to view my transaction history for each of my accounts without a performance 

- Some potential options:
    - Create a pagination system for transactions, x number of tx per page
    - Display the most recent x number of tx with a link to Etherscan for older transactions at the bottom of the list

------------------------------------------------------------------------------------------------------
_filled out after submission_

**User impact | Usage frequency | Feasibility scores**
_How important is this to the user, what the user wants to accomplish | Daily, weekly, monthly | Small, medium, large_

**Comment by gantunesr** [comment]
Solution developed by only storing a limited number of transactions.

PR: https://github.com/MetaMask/metamask-mobile/pull/2972
