### ISSUE TITLE
View the FIAT conversion of my tokens

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-mobile#2440]
As a user, irrespective of which network I am on, I want to view the FIAT conversion values of my tokens.

Currently we pull FIAT conversion values by the name of the token (this name might be same on mainnet, and so the conversion rate will be shown that of extension).
- Use Coingecko API for price feeds for the custom networks that Coingecko supports.

Consideration:
- Giving the option to add a price feed link on the custom network form (and API), similar to blockexplorer link.
- Add tooltip when pricing information is not available for a token (apply this tooltip also when a token price isn't available on Ethereum mainnet) -- support team shared the insight that users think that a token isn't usable if it doesn't have a price conversion, and get confused on why it's not shown. Indicating that these prices are pulled from Coingecko might be useful.

**Comment by omnat** [comment]
For BSC Swaps, we can use 1inch API for getting these conversion rates.

**Comment by omnat** [comment]
@omnat to add the link to Coingecko API

**Comment by omnat** [comment]
Related to #2409

**Comment by mobularay** [comment]
Latest update on Slack thread: https://consensys.slack.com/archives/G1L7H42BT/p1621264940427000

**Comment by mobularay** [comment]
https://consensys.slack.com/archives/G1L7H42BT/p1621264940427000

Engineers, pls review this request from @wachunei ^^^

**Comment by mobularay** [comment]
@wachunei has been reviewing [the proposal ](https://github.com/MetaMask/metamask-mobile/issues/2693) on the Slack thread with other Engineers; the proposal is currently residing in the controllers repo.

**Comment by mobularay** [comment]
@wachunei to link to Notion proposal  - thanks!

**Comment by wachunei** [comment]
Here's the Technical Proposal for the TokenRatesController
https://www.notion.so/Multi-chain-TokenRatesControler-9e503b73244f478a8fb63bcd933cb80b
As of now this PR is up to date with this document https://github.com/MetaMask/controllers/pull/476

**Comment by mobularay** [comment]
From Sprint Planning June 20th:
- PR needs one more review from Mark
- Move out of draft after this PR passes test
- Will be upgrading controllers - will turn on the fiat values
- Will rely on [CoinGecko API](https://api.coingecko.com/api/v3/asset_platforms)

@wachunei ^^^
