### ISSUE TITLE
Custom collectibles/NFTs disappear after relaunching the app

### ISSUE THREAD

**Issue by omnat** [MetaMask/metamask-mobile#2465]
Problem: user adds a collectible/NFT to their wallet manually (with 'Add Collectible' flow), and the wallet starts to show the collectible. If the user closes the app, and reopens - the NFT is removed, and they need to re-add it. 

Expected: once a custom NFT is added, it should not disappear when they relaunch the app. If they logout and login again, it should stay as well. It should only disappear if the user explicitly removes it. 

Issue reported here: https://community.metamask.io/t/collectibles-in-metamask-app/620

**Comment by omnat** [comment]
@sethkfman per our discussion, I asked the person who reported this the following questions:

1. Can you see the 2 collectibles that disappear on your MetaMask on OpenSea site?
2. Do you own these collectibles or are you adding them to your wallet to ‘watch’ them?
3. Which network are you on? Ethereum Mainnet?

They might respond here too (I shared this issue link with them too)

**Comment by omnat** [comment]
QA paths to check if the state is reflected correctly after re-opening the app (logging in again)
1. See custom added collectible (not autodetected) that's owned by you
2. See custom added collectible (not autodetected) that's NOT owned by you
3. Don't see the collectible that you removed (which was auto-detected in first place)

^ on Ethereum Mainnet, Matic

**Comment by estebanmino** [comment]
I think I found the problem and pushed a PR in controllers repo. For some reason I don't remember, we're removing collectibles not detected by the 3rd party API, so basically all manually added collectibles that aren't in opensea are going to me removed, always.

**Comment by mobularay** [comment]
@estebanmino have we mislabeled this closed NFT issue with **release v2.2**? If it’s not part of release v2.2, then what happened to it? I checked this [PR](https://github.com/MetaMask/controllers/pull/439) .... I think Mark has included the fix in the controller communication he is working on? Help me understand, pls! :-)    CC @omnat
