### ISSUE TITLE
Hide conversion rates for tokens on custom networks

### ISSUE THREAD

**Issue by omnat** [MetaMask/metamask-mobile#2475]
Till we figure how to implement #2440, let's hide the conversion rates for the tokens on custom networks, to not misrepresent the price conversion in FIAT.

**Comment by mobularay** [comment]
It is unclear if this ticket is at dev review status, or QA status. Pls add proper labels, thanks so much! @wachunei

**Comment by wachunei** [comment]
Closed by #2468
