### ISSUE TITLE
Custom Network: Limit add custom tokens to ERC20 contracts and not addresses

### ISSUE THREAD

**Issue by wachunei** [MetaMask/metamask-mobile#2480]
As a user I want to be able to add custom tokens using an address from a token contract and not a wallet address.

Video of the issue:

https://images.zenhubusercontent.com/141427485/ba35ff56-9b63-48c0-85aa-e2dd94d90eb9/screen_recording_2021_04_07_at_10_56_59.mov

**Comment by mobularay** [comment]
Should sync with Extension team as they agree they need to do the same solution 
CC @brad-decker

**Comment by mobularay** [comment]
Could be medium-low effort and high impact
