### ISSUE TITLE
On-ramp with Wyre need to be update

### ISSUE THREAD

**Issue by DantasPM** [MetaMask/metamask-mobile#2484]
**Describe the bug**
On the on-ramp flow, we have some information that is inaccurate and needs to be updated.
We need to update information in 3 different "buckets":
1) Countries supported
2) Max limit
3) Excluded U.S. states 

*1) Countries Supported*
Currently, we show that Apple Pay is available to U.S. only.
Wyre with its Apple Pay option supports more countries and here is the list of all countries supported by Wyre/Apple Pay: Australia, Austria, Belarus, Belgium, Brazil, Canada, Cyprus, Czech Republic, Denmark, Estonia, Finland, France, Germany, Greece, Hong Kong, Iceland, Ireland, Italy, Japan, Latvia, Lithuania, Luxembourg, New Zealand, Norway, Poland, Portugal, Singapore, Slovakia, Slovenia, Spain, Sweden, Switzerland, The Netherlands.

*2) Max limit*
Currently, we show an inaccurate limit for US onl=y of $450. 
The correct amounts are:
Domestic (US): Weekly: $500 ; Monthly: $2,000; Yearly: $5,000
International: Weekly: $1,000; Monthly: $4,000; Yearly: $7,500

*Excluded U.S. States*
Currently, we show that the following states are excluded: CT, HI, NC, NH, NY, VA and VT. 
Wyre supports all states except NY and TX for cards. 

**Screenshots**
![IMG_E19659BD5F5B-1](https://user-images.githubusercontent.com/77031677/114069086-70f8e780-9853-11eb-9d0c-a6660874a991.jpeg)

![IMG_1BC19B6AA86D-1](https://user-images.githubusercontent.com/77031677/114069167-89690200-9853-11eb-8fd0-d08d9e256c36.jpeg)

**To Reproduce**
_Steps to reproduce the behavior_
1. Go to the app homescreen
2. Click on "Buy"
5. when clicking the "i" also see error

**Expected behavior**
Already covered in the description above. 

**Smartphone (please complete the following information):**
 - Device: iPhone 11
 - OS: iOS 14.4.2
 - App Version - v2.01(605)

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by jakehaugen** [comment]
Chatted with Pedro and Gabriel about some of our constraints. 

**Problem:**
For Apple Pay via Wyre, we only allow users to enter USD amounts and show fees as if the user was in the U.S. However, it is possible to buy outside of the U.S. -- it's just a poor experience (amount required in USD and fee is wrong).

**Solution:**
Allow user to select the currency (or country?) from the "amount" screen. This will update the keyboard and number formatting to be correct for their currency. We will use this as a proxy for location and update the fees shown as well. 

**Issues not solved by this:**
We are still unable to correctly show fees from the "Purchase Method" screen customized to location. This screen will need to be updated to show more detailed fees/limits (for all locations) in a modal window.

**Comment by jakehaugen** [comment]
Latest mocks: https://www.figma.com/file/n13Iyw8hj3nj6mSaFQPnc3/Crypto-On-ramp?node-id=2477%3A2411

**Comment by jakehaugen** [comment]
Final mocks are here: https://www.figma.com/file/n13Iyw8hj3nj6mSaFQPnc3/Crypto-On-ramp?node-id=2477%3A2227

Let's also double check the supported countries we list for Transak to make sure they are updated. I'm not sure where to find those.

**Comment by wachunei** [comment]
> Let's also double check the supported countries we list for Transak to make sure they are updated. I'm not sure where to find those.

I asked Transak to confirm [this list](https://gist.github.com/wachunei/1e909b6725295c3f39dd8b20b0a0d803) is updated or no, they have not answered yet. @DantasPM would you ping them again please? It was on our telegram channel

**Comment by DantasPM** [comment]
For sure. Just did!

**Comment by mobularay** [comment]
Requires user testing in different countries. @wachunei let us know what you need the team to help with :-)

**Comment by mobularay** [comment]
As discussed in May 20 Sprint Grooming session @omnat @wachunei 

- Fees are shown as the sum of network + Wyre fees, not listed separately, as the work here is not using Limits(?) API
- Need ppl in other countries to test - use Kovan ETH to access Wyre testbed, which SHOULD reflect the same experience as if we are on mainnet
-- @omnat @wachunei Tian will discuss and align on the needs of this user testing (number of users, length of testing, etc)
