### ISSUE TITLE
Update end-to-end tests

### ISSUE THREAD

**Issue by omnat** [MetaMask/metamask-mobile#2486]
@ibrahimtaveras00 to add details and break down tasks.

**Comment by ibrahimtaveras00** [comment]
iOS = Fix all tests (8 tests) 

Android = 3 tests passed; 
(fix start exploring, custom RPC, browser tests, address book tests, wallet tests)

**Comment by andrepimenta** [comment]
When opening the url modal on the browser, it would be hidden automatically if the keyboard was not detected. This fixes this behaviours for emulators:
https://github.com/MetaMask/metamask-mobile/pull/2604
