### ISSUE TITLE
Bitrise: CI Setup

### ISSUE THREAD

**Issue by sethkfman** [MetaMask/metamask-mobile#2515]
1. Build Repo
2. Run Unit Tests
3. Add: linter step and dependency checks
4. Add: Lavamoat/other built-in static cod/security tools
4. Feedback to GitHub

**Comment by sethkfman** [comment]
Add: linter step and dependency checks

**Comment by mobularay** [comment]
@sethkfman if this issue is currently a blocker for a few tickets, why is it in "Review/QA" column? Should it be in "In Progress" column? If it's in the correct column, then does it require dev review now, or QA review?

**Comment by sethkfman** [comment]
It is a parent story. It is not a blocker. All the Bitrise stories with dependencies have been moved into the In Review/QA. @mobularay

**Comment by sethkfman** [comment]
1. Contacted Apple Support and they responded that if the certificate entitlements and Keychain ACLs (MacOSX only) have not changed then this is the expected behavior between upgrades. See email below:

> Please include the line below in follow-up emails for this request.

> Follow-up: 768525604

> Hello Seth,

> Thank you for contacting DTS.  My name is Matt Eaton and I will be looking into your incident.  Regarding your description:

> During upgrade testing using the TestFlight builds the biometric was failing after an 
app upgrade from a version created with the old certificate (613) to an app created with 
a new certificate (712).

> This requires the user to enter their password between app upgrades which is undesirable 
from an experience perspective.

> I want to confirm that there were no changes to the entitlements or App Group that is contained in the new provisioning profile?  If there was /not/ an update to the Keychain ACLs or the app entitlement this sounds like common behavior to make sure that when an app is updated that the passcode is used to make sure that a new FaceID or TouchID, that is not meant to be used on the device, is not being used to access sensitive information.  For example, an app accidentally providing a mechanism to setup a FaceID for someone that should not have access to the app.  Similar behavior can also be seen when a user restarts their device or tries to access the FaceID feature in Settings.  The passcode for the device is used to determine that you are supposed to access those settings or the device before FaceID is used.

> If you are seeing a failure here after this password/passcode is enabled for your FaceID/Biometric authentication, please let me know and we can dig in further. 

2. Attempted to get old CircleCI certs and was unsuccessful
3. Attempted to gather logcat/console log data in the iOS/Android release apps and wasn't not able to track down specific issue
   - In reviewing Android logcat the OS is accepting and validating the biometric but the KeyRing.getGenericPassword is not retrieving the password successfully.  
4. Reviewed the react-native-keychain for reported issues without any leads

At this time, I have submitted a requests to the react-native-keychain project and will wait for a response. 

I do think we should start a discussion on what steps to take if there is no resolution. 
 
cc: @mobularay & @omnat
