### ISSUE TITLE
Issues signing messages with WalletConnect

### ISSUE THREAD

**Issue by nlordell** [MetaMask/metamask-mobile#2522]
**Describe the bug**

Using `eth_sign` with WalletConnect never resolves on bad input.

**To Reproduce**

1. Using `connector.signMessage([account, "not a hash"])` to sign an `eth_sign` message, promise never resolves
   - Note that the popup **does appear in the app** for signing the message
   - Selecting "Cancel" instead of "Sign" in the mobile app causes the promise to correctly revert with `MetaMask Message Signature: User denied message signature.`

<details><summary>Sample code:</summary>

```js
import WalletConnectProvider from "@walletconnect/web3-provider";

async function testSigningMethods() {
  const provider = new WalletConnectProvider({
    infuraId: process.env.INFURA_PROJECT_ID,
  });
  const [account] = await provider.enable();

  try {
    const signature = await Promise.race([
      provider.wc.signMessage([account, "Hello MetaMask!"]),
      delay(10000),
    ]);

    if (signature) {
      console.log(`SUCCESS: ${signature}`);
    } else {
      console.log(`TIMEOUT`);
    }
  } catch ({ message }) {
    console.log(`FAILURE: ${message}`);
  }
}
```

</details>

**Expected behavior**

- When handling a WalletConnect `eth_sign` request, the hash of `\x19Ethereum Signed Message:\n${message.length}${message}` should be computed and signed (like `personal_sign`). This would be inline with how [WalletConnect expects `eth_sign` requests to be handled](https://docs.walletconnect.org/json-rpc-api-methods/ethereum#eth_sign).
- Alternatively, if the behaviour of `eth_sign` doesn't want to be changed (although I don't think the legacy argument applies to the MetaMask mobile app with WalletConnect) the promise should reject when signing a message with bad input.

**Smartphone (please complete the following information):**
 - OS: Android 10
 - App Version: 2.0.1

**Comment by nlordell** [comment]
Actually, I just noticed that this also seems to be an issue with the MetaMask extension:
```js
const [account] = await ethereum.request({ method: "eth_requestAccounts" });
const signature = await ethereum.request({
  method: "eth_sign",
  params: [account, "MetaMask"],
}); // never resolves
console.log(signature);
```

**Comment by nlordell** [comment]
OK, I think I see what is going on here. Upon stumbling upon [this](https://docs.metamask.io/guide/signing-data.html#a-brief-history) it looks like MetaMask implements `eth_sign` to take a hash as parameter instead of the message (which is why `personal_sign` is encouraged).

While I understand this stayed this way because of backwards compatibility concerns, shouldn't the promise reject instead of never resolving in the case where the second parameter is not a hash? Additionally, while it makes sense for the `window.ethereum` API to behave this way because of backwards compatibility, shouldn't this not be the case for WalletConnect support for the mobile app (where, AFAIU it should behave mostly identically to `signPersonalMessage`?).

**Comment by gantunesr** [comment]
Related #3583
