### ISSUE TITLE
RESEARCH: Custom Network: Investigate occurrences of JSON-RPC errors

### ISSUE THREAD

**Issue by wachunei** [MetaMask/metamask-mobile#2550]
When using Swaps testnet and QAing Swaps BSC, both with custom RPC networks, we've been facing these errors:

![Screen Shot 2021-04-15 at 6.40.27 PM.png](https://images.zenhubusercontent.com/5f9993a07851dda5331c8fd2/9c047c2b-c808-4479-af9f-3c159b7203d8)

We should investigate if this is common for transactions when using a custom RPC network

**Comment by wachunei** [comment]
I've been trying to reproduce this by using a custom network with the Infura https JSON-RPC endpoint for Rinkeby and I have not found this error. ([tx history](https://rinkeby.etherscan.io/address/0xdfcfa462a38305a755bdf1cf8512e67b7bc712be)).

**Comment by mobularay** [comment]
@ibrahimtaveras00 found this. @wachunei @andrepimenta haven't been able to reproduce. 

So will park this until we have more details, and consider it as a non-blocker for BSC Swaps.

**Comment by omnat** [comment]
Sentry update will go out in 2.3, so we could re-visit this after we have sufficient data coming through to investigate whether this error is still happening + how to resolve it. @wachunei to check it out after a week of 2.3 being out in the wild.

**Comment by ibrahimtaveras00** [comment]
One way to consistently reproduce this txn error:
- Switch to BSC
- Initiate Swaps
- Before actually swapping, lower the GWEI lower than the suggested value (so if 5 lower it to 4 or below)
- Now do the swap

**Comment by mobularay** [comment]
Part of https://app.zenhub.com/workspaces/metamask-mobile-5f984938ddc0e4001d4b79cb/issues/metamask/mobile-planning/93

**Comment by mobularay** [comment]
@wachunei will have more info, but any Engineer can take this on as it might end up being controller-related work.

**Comment by omnat** [comment]
Related(?) #2876

**Comment by gantunesr** [comment]
This issue is no longer relevant. Open a new ticket if it shows up again.
