### ISSUE TITLE
Requesting token doesn't respect network

### ISSUE THREAD

**Issue by ibrahimtaveras00** [MetaMask/metamask-mobile#2557]
**Describe the bug**

When using the request flow, or tapping on a deeplink, we are only respecting the request's network if it's coming from a custom network, but we're not respecting Mainnet nor other default networks

**Screenshots**

In this example, I'm requesting ETH while on mainnet, but upon scanning the QR code, the network isn't being switched to Mainnet; seen here = http://recordit.co/sIUhBU0CMk

**To Reproduce**
_Steps to reproduce the behavior_
1. Create a deeplink in browser or QR code payment request from one network
2. With your device, open app and be on a different network than above request 
3. Scan QR code, or open deeplink from browser

Feel free to use this deeplink which should change network to Rinkeby:

https://metamask.app.link/send/0x1FDb169Ef12954F20A15852980e1F0C122BfC1D6@4?value=1e15

Or scan this payment request QR code:

![Screen Shot 2021-04-20 at 6 48 35 PM](https://user-images.githubusercontent.com/41752922/115473078-0fe4f280-a209-11eb-87e3-b78fc4ec959d.png)

**Expected behavior**

My network should automatically change according to the network of the payment request

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by ibrahimtaveras00** [comment]
This shows how it currently works only on custom networks 

In this example I'm on mainnet, scan a request from xDAI chain and it properly changes my network 

seen here = http://recordit.co/5ArBvHTIlb

**Comment by rahul-kothari** [comment]
Any updates on this?

**Comment by sethkfman** [comment]
Example deep links can be found here: https://www.notion.so/DeepLink-Test-e9b159d196424926809848705ffa015f

**Comment by Fatxx** [comment]
Fixed at #3605
