### ISSUE TITLE
Swaps: refactor controller into a module

### ISSUE THREAD

**Issue by wachunei** [MetaMask/metamask-mobile#2569]
Related Issue: https://github.com/MetaMask/swaps-controllers/pull/28
Related PR: https://github.com/MetaMask/swaps-controllers/pull/29

Copying text for visibility:
> This PR makes swaps-controller a module with controllers as a dependency, moving away from the current pattern which is a fork of controllers at some point of time. With this approach we can avoid having to update/rebase controllers code and manage it as a dependency.

**Comment by mobularay** [comment]
@wachunei does this work need to go into a release? Or just merging into develop and/or main branch is good enough? hope I make sense

**Comment by mobularay** [comment]
Requires @estebanmino and one of (@Gudahtt @rekmarks @danjm ) to review this change.

**Comment by mobularay** [comment]
@wachunei can I remove the "needs-dev-review" label? Also, remind me again if this requires @ibrahimtaveras00  to QA, since this is related to a non-Mobile PR... thanks so much!

**Comment by wachunei** [comment]
This should be closed and only keep #2586 in the board. Closing it.
