### ISSUE TITLE
EIP-1559 UI/UX Design for V1

### ISSUE THREAD

**Issue by omnat** [MetaMask/metamask-mobile#2571]
Epic Definition: https://www.notion.so/EIP-1559-transaction-fee-burning-adfd8b24bc6844f290d229e21d3863f6
Figma file (V1 designs): https://www.figma.com/file/NXvUKcZ0Ocu1GPcT7VxRMx/1559-Gas-Controls?node-id=643%3A5

This ticket holds the UI/UX design work updates

**Comment by mobularay** [comment]
Adding @rickycodes here as some technical research could also be started in parallel with the design work

@rickycodes @brad-decker @jakehaugen @omnat we should discuss about how we want to give credit (hold space in sprints) to the technical research / tidying up and design work - should there be two different cards to distinguish the work types? Also, should Brad be tagged onto these cards in the Mobile sprint board? (I can't tag Kevin here LOL)

**Comment by mobularay** [comment]
Discussed briefly at stand-up today; for now, @rickycodes will be tagged to this card as he is currently in planning phase with Brad. Once Ricky starts any work relating to EIP-1559, including getting the code ready for 1559 development, @mobularay or @rickycodes will create a card to represent that work.

**Comment by omnat** [comment]
Next steps:
1. Will get feedback from TimBeiko
2. Will get user feedback on 2 versions
3. Swaps UI update is part of this design. 

Early next week we'll have prototypes for testing.
