### ISSUE TITLE
Redirect "Get Feedback" to Feature Request / Ideas section on Discourse

### ISSUE THREAD

**Issue by dpazdan** [MetaMask/metamask-mobile#2578]
**Describe the bug**
Currently, Send Feedback opens our ticket form.  This should now direct users to https://community.metamask.io/c/feature-requests-ideas/

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by rickycodes** [comment]
handled by https://github.com/MetaMask/metamask-mobile/pull/2536
