### ISSUE TITLE
Custom tokens and custom networks do not get synced on mobile

### ISSUE THREAD

**Issue by charmpitz** [MetaMask/metamask-mobile#2587]
When syncing with the browser extension on mobile the custom networks (Binance Smart Chain) do now show and you need to add them manually on every device. After adding it the custom tokens also don't show and you need to add them manually.. If I need to use my wallet on multiple devices it becomes really frustrating and easy to forget what tokens I have and what tokens I don't.
The missing tokens issue seems to be happening on existing networks as well (ex: Ethereum Mainnet).

**Comment by schtiefel** [comment]
Yes, the current state is quite annoying. It doesn't even sync added tokens from the "default" networks.
It should definitively sync all networks and all their added tokens.
