### ISSUE TITLE
Collectibles organization under Wallet section

### ISSUE THREAD

**Issue by estebanmino** [MetaMask/metamask-mobile#2591]
Current view is like
![image](https://user-images.githubusercontent.com/12115171/116151365-84f57380-a6b2-11eb-8178-c79193f2a6b8.png)

it should be modified to
https://www.figma.com/file/bZM7M2FrLvhLoltwBZ0kJr/Collectibles?node-id=223%3A888

there's no background work to do for this, just display the collectibles organized in that way, pressing an image should send you to the specific collectible view as it is now, and pressing in the collectible type name should hide or show the dropdown with the collectibles

@cjeria question, what happens when the user has more than 6 for a specific collectible type?

**Comment by cjeria** [comment]
> @cjeria question, what happens when the user has more than 6 for a specific collectible type?

If there are more than six NFTs for a collectible type, show the 7th on a new line (see attached). 
![image](https://user-images.githubusercontent.com/597770/116154777-f971e780-a69d-11eb-80b0-5aa96cbeb578.png)

**Comment by cjeria** [comment]
There are also some suggested transitions and animations when viewing individual NFTs that you can see in this [protoptype](https://www.figma.com/proto/bZM7M2FrLvhLoltwBZ0kJr/Collectibles?node-id=223%3A909&viewport=2213%2C3536%2C1.1978470087051392&frame-preset-name=iPhone%2011%20Pro%20Max&scaling=min-zoom). Also adding a gif for reference. In general, there are 3 viewing states for an NFT.

State 1 - Grid view (default state) 
State 2 - Detail view - when you click on a single NFT to view its front and center with the details "card" also visible in the frame.
State 3 - Full-screen mode - where the NFT takes over the entire frame of the device. Ideally, the user would be able to zoom in and out of the image. If it's a video, this is the state the user can play/pause the video. Happy to chat further about what's feasible if the ideal state isn't possible.

![](http://g.recordit.co/YmpzcWBGHO.gif)

**Comment by estebanmino** [comment]
for state 2 and 3 I created new cards but thanks for the clarification!

**Comment by estebanmino** [comment]
@cjeria do we want the `ADD COLLECTIBLES` button? I noticed is not in figma ![image.png](https://images.zenhubusercontent.com/5bfc3a30c6f0726301cc5393/fb4eb89f-ae44-44e2-91d2-8bc968f33eb1)

and also, what do we show when the wallet doesn't have collectibles?

**Comment by estebanmino** [comment]
@cjeria I started thinking about performance for this card. I an user has many collectibles and we display all at once it could cause some performance issues. What do you think about maybe having one or two collectibles section open at the same time?

**Comment by estebanmino** [comment]
maybe having 3 to 6 rows of collectibles open by default is enough, I'm gonna be putting smaller images on that section as well to not make that component too slow to render

**Comment by estebanmino** [comment]
other option would be to only leave favorites open by default if user has favorites

**Comment by cjeria** [comment]
> do we want the ADD COLLECTIBLES button? I noticed is not in figma

Yes, we're keeping this option, for now, however, let's update the language from `collectibles` to `NFTs`

> what do we show when the wallet doesn't have collectibles?

I had a design for this on another page within [this file](https://www.figma.com/file/bZM7M2FrLvhLoltwBZ0kJr/Collectibles?node-id=423%3A15) but hadn't copied it over. Here's a link to the[ design](https://www.figma.com/file/bZM7M2FrLvhLoltwBZ0kJr/Collectibles?node-id=423%3A15). Let me know if you have any feedback. 
![image.png](https://images.zenhubusercontent.com/59b80272b0222d5de4776ba7/6169fd42-039b-40b1-93f5-72b207416a90)

> I started thinking about performance for this card. I an user has many collectibles and we display all at once it could cause some performance issues. What do you think about maybe having one or two collectibles section open at the same time?

Just having favorites open by default sounds good enough. If there are no favorites, can we have that first section be open? So the first child regardless of how many NFT collections there are.

**Comment by estebanmino** [comment]
https://github.com/MetaMask/metamask-mobile/pull/2618
