### ISSUE TITLE
Favorites section under Collectibles

### ISSUE THREAD

**Issue by estebanmino** [MetaMask/metamask-mobile#2593]
Render the favorite collectibles if any https://www.figma.com/file/bZM7M2FrLvhLoltwBZ0kJr/Collectibles?node-id=223%3A888

If no favorite, that section should not be there empty (right @cjeria ?)

**Comment by cjeria** [comment]
> If no favorite, that section should not be there empty (right @cjeria ?)

That's correct! If no NFT is favorited, the "favorites" section does not show up in the UI

**Comment by cjeria** [comment]
There are also some suggested transitions and animations when viewing individual NFTs that you can see in this [protoptype](https://www.figma.com/proto/bZM7M2FrLvhLoltwBZ0kJr/Collectibles?node-id=223%3A909&viewport=2213%2C3536%2C1.1978470087051392&frame-preset-name=iPhone%2011%20Pro%20Max&scaling=min-zoom). Also adding a gif for reference. In general, there are 3 viewing states for an NFT.

State 1 - Grid view (default state) 
State 2 - Detail view - when you click on a single NFT to view its front and center with the details "card" also visible in the frame.
State 3 - Full-screen mode - where the NFT takes over the entire frame of the device. Ideally, the user would be able to zoom in and out of the image. If it's a video, this is the state the user can play/pause the video. Happy to chat further about what's feasible if the ideal state isn't possible.

![](http://g.recordit.co/YmpzcWBGHO.gif)

**Comment by cjeria** [comment]
posted my last comment in the wrong issue. Deleted and reposted it here https://github.com/MetaMask/metamask-mobile/issues/2591

**Comment by estebanmino** [comment]
https://github.com/MetaMask/metamask-mobile/pull/2618
