### ISSUE TITLE
Can't connect to app.treedefi.com

### ISSUE THREAD

**Issue by guifercon** [MetaMask/metamask-mobile#2609]
**Describe the bug**
Nothing happens when tried to connect the wallet to app.treedefi.com

**Screenshots**
nothing to show, it just closes the selection window

**To Reproduce**
_Steps to reproduce the behavior_
1. Go to 'app.treedefi.com'
2. Click on 'connect'
3. Select 'metamask'
4. See no error message, nothing.

**Expected behavior**
allow access to the funds.

**Smartphone (please complete the following information):**
 - Device: XIAOMI redmi 6
 - OS: [9 PPR1.180610.011]
 - App Version [2.1.3(53)] - find version number in app from Settings > About MetaMask

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by rickycodes** [comment]
@guifercon is this still an issue for you? I tried to load up the URL in question and it worked fine for me: 
![image](https://user-images.githubusercontent.com/675259/117044432-6dcf0b00-acdc-11eb-9bce-af66848b46b5.png)
