### ISSUE TITLE
Custom networks collectible

### ISSUE THREAD

**Issue by estebanmino** [MetaMask/metamask-mobile#2616]
We need to update the way we're displaying NFTs that have limited information

![image.png](https://images.zenhubusercontent.com/5bfc3a30c6f0726301cc5393/a7691ab6-fce8-4057-9650-209c5bd976e9)

**Comment by cjeria** [comment]
Here's a suggestion that makes the unknown NFT somewhat more interesting with a basic gradient and placeholder copy in the details card to indicate to the user it's not a UI bug. Let me know what you think @estebanmino 
![image.png](https://images.zenhubusercontent.com/59b80272b0222d5de4776ba7/959bed64-d2c1-47ac-ab2e-e1140eaf88e0)

**Comment by estebanmino** [comment]
https://github.com/MetaMask/metamask-mobile/pull/2618
