### ISSUE TITLE
Upgrade ethereum util dependencies

### ISSUE THREAD

**Issue by rickycodes** [MetaMask/metamask-mobile#2620]
as part of #2571 we need to update some dependencies in the controllers repo

- [x] eth-keyring-controller
- [x] ethereumjs-tx -> @ethereumjs/tx
- [x] ethereumjs-util
- [ ] ethereumjs-wallet (confirmed no need) 

https://www.notion.so/Upgrade-ethereumjs-tx-dependency-59c2e1be526f448dae39cfc48d3f81d5
https://www.notion.so/Upgrade-ethereumjs-util-dependency-f107fadb0cf5407388020761f915ab6e
https://www.notion.so/Implement-ethereumjs-common-b6004fe650e441aaa546044719deccdd

**Comment by omnat** [comment]
Brad's done most of this work on extension, we can follow through with this list.

**Comment by mobularay** [comment]
@rickycodes @sethkfman can you clarify the relationship b/n this work here and [2271 Tx State Controller ](https://github.com/MetaMask/metamask-mobile/issues/2271) work? Is one blocking the other from completion? Or are they both parallel work that can be done separately, but just need to be completed before our support for EIP-1559 becomes live?

**Comment by mobularay** [comment]
Related Controller PR, currently in PR status: https://github.com/MetaMask/controllers/pull/489

**Comment by mobularay** [comment]
In EIP-1559 stand-up, @rickycodes will enlist @ibrahimtaveras00 help to QA!

**Comment by rickycodes** [comment]
aforementioned QA PR is here: https://github.com/MetaMask/metamask-mobile/pull/2797
