### ISSUE TITLE
deeplink docs

### ISSUE THREAD

**Issue by matheus-gsilva-ifood** [MetaMask/metamask-mobile#2627]
It is not exactly a bug rather I'm asking for guidance.

i would like to implement a deeplink on my app where I'll be using metamask to connect and perform transfer tasks with it. I could not find any documentation anywhere which would explain how it works. 

Are there resources or it is missing?

**Comment by gorevoy** [comment]
Same for me. Developing iOS wallet and want to connect MetaMask to my iOS app same as Zerion does it. What to pass after "metamask://..." when UIApplication.shared.openURL() to trigger "Connect wallet" to my iOS app? Didn't find proper documentation. Thanks in advance.

**Comment by Hayoung079** [comment]
Did you solve it?

**Comment by matheus-gsilva-ifood** [comment]
no, we are waiting for docs.

**Comment by PaulAtFlexa** [comment]
https://metamask.github.io/metamask-deeplinks/# This link shows you how to build them, you can reverse engineer the format from the form.  But I agree, actual documentation would be awesome.  There are missing parameters in that web builder such as gas
