### ISSUE TITLE
Swaps: Custom Token Flow - search by address and get it imported to your wallet

### ISSUE THREAD

**Issue by wachunei** [MetaMask/metamask-mobile#2641]
Crossposted from https://consensyssoftware.atlassian.net/jira/software/projects/META/boards/356/backlog?selectedIssue=META-62

# User Story 

As a user, I want to fetch quotes for (long-tail) assets that are not necessarily available in our metadata aggregator so I can trade any token that is available on defi  

### A/C 

**Given** I want to request a quote  
**When** a token is not available on MetaSwap’s metadata service  
**Then** I want to easily add the token (manually or dynamically) to make it available for trading 

### Technical Details:

- MetaMask Mobile uses `Token` objects in the Swaps flow
- `Token` objects must have these properties: `address: string`, `symbol: string`, `decimal: number`, `occurrences: number`, `iconUrl: string`.

### Current Behavior (Mobile)

- MetaMask Mobile relies 100% on the `Token` objects from the list provided by /tokens endpoint (stored in the Swaps Controller).
- If a user adds a token that is not listed and navigates to Asset View, Swaps button will be disabled.
- If a user opens Swaps flow and searches for a token that is not listed, no search results will be returned.

### Desired Behavior (Mobile) 

- MetaMask Mobile/Swaps Controller could manage a temporary list of custom tokens in order to complete the flow.
- Swaps flow uses a combination of Swaps Controller token list and this temporary list.
- If a user adds a custom token that is not listed and navigates to Asset View, an API request with the token address is made in order to retrieve the `Token` object
  - If a user request is successful the `Token` is added to the temporary list and button is enabled.
  - Otherwise button remains disabled.
- If user opens Swaps flow and searches for an address that is not listed, we should allow the user to ‘add’ the token into the list. Once the data is added, the UI will make an API call to lookup the token metadata. 
  - If request is successful the `Token` is added to the temporary list, search modal is dismissed and token is selected as source/destination.
  - Otherwise we show the token address is not available for swaps and the search modal remains open.

### Why should we pursue it? 

- Opening up MetaSwap to an additional set of long-tailed tokens will:
  - Improve overall UX for end users, increasing the stickiness of the product 
- Opening up MetaSwap to more tokens will can potentially increase volume and therefore help generate an additional source of revenue.

**Comment by mobularay** [comment]
@wachunei had provided a heads-up on the existence of this work at the start of the sprint as new work, but no timeline and commitment.

@jakehaugen just got pulled in to start design work relating to the Mobile aspect of the overall work in Codefi. Expectations from the Swaps team is complete design & implementation this week. @jakehaugen @wachunei @omnat David Pazdan to sync asap on timeline and expectations, and whether this work will follow Mobile normal sprint & release process, or whether this work needs to be released outside of the normal process.

**Comment by mobularay** [comment]
@jakehaugen still reviewing and working on the mocks, but really close. Will sync next with @cjeria in considering custom tokens.

**Comment by wachunei** [comment]
Today during sync with Swaps team we split this task into two task:
- The custom token which is searched and added from the swaps flow itself
- Allowing custom tokens that are already in the users wallet to be available for swap #2699

**Comment by jakehaugen** [comment]
Final mocks are here: https://www.figma.com/file/VVjoLHG6X74lXmh6CN3r7H/Swaps?node-id=2001%3A883
