### ISSUE TITLE
Can no longer deploy contracts in test-dapp

### ISSUE THREAD

**Issue by ibrahimtaveras00** [MetaMask/metamask-mobile#2646]
**Describe the bug**

Can no longer test contract deployments on test-dapp on testnets, it only works on mainnet, and local ganache
- deploy contract
- create token

**Screenshots**

![image](https://user-images.githubusercontent.com/41752922/117489356-87ba5900-af3b-11eb-834d-1ba9e5e551ed.png)

**To Reproduce**
_Steps to reproduce the behavior_
1. Switch to a testnet
2. Go to browser and navigate to https://metamask.github.io/test-dapp/
3. Connect
4. Attempt to "DEPLOY CONTRACT" or "CREATE TOKEN"

**Expected behavior**

It should work how Mainnet works

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by mobularay** [comment]
@andrepimenta will assess how big this issue is and determine whether it's a release blocker or not
