### ISSUE TITLE
Balance undefined for deeplink payment requests on testnets

### ISSUE THREAD

**Issue by ibrahimtaveras00** [MetaMask/metamask-mobile#2647]
**Describe the bug**

if I’m on mainnet, balance is retrieved fine
if i’m on a testnet, balance is undefined and the only way to get it to work is to switch to another account and come back to the same account

**Screenshots**

seen here = http://recordit.co/IAgarmmBjU

**To Reproduce**

1. Switch to any testnet
2. Now on a different browser (chrome/safari) open this deeplink by going to the URL of this issue

https://metamask.app.link/send/0x1FDb169Ef12954F20A15852980e1F0C122BfC1D6@4?value=1e13

3. Notice how balance is undefined 
4. Now if you switch to another account that does have a balance and come back it will populate normally and work

**Expected behavior**

Balance should not be undefined 

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by ibrahimtaveras00** [comment]
Even more of a bigger issue is when you are on mainnet and you do have enough funds to cover the payment request, the send button is disabled and you cannot progress = http://recordit.co/w2a3i8OCc0

![image](https://user-images.githubusercontent.com/41752922/117492750-0addae00-af40-11eb-889b-b94bb066b4d8.png)

**Comment by andrepimenta** [comment]
Syncing with Ricky on this one since it's related to confusables

Also found another issue with confusables:
![Simulator Screen Shot - iPhone 11 Pro - 2021-05-10 at 14.28.52.png](https://images.zenhubusercontent.com/5f99d46607474d60b64035d5/ac630d72-7efc-403b-84b6-44bbbf764922)
