### ISSUE TITLE
Add hardware wallets to mobile MetaMask.

### ISSUE THREAD

**Issue by andrewkm** [MetaMask/metamask-mobile#2653]
With the Ledger Nano X having Bluetooth capabilities, it would be a total game changer if MetaMask allowed us to add hardware wallets.

**Comment by ConorIA** [comment]
See #1237

**Comment by andrewkm** [comment]
Add ledger x support

**Comment by AnonyKwan** [comment]
+1

**Comment by losmibb** [comment]
Using Ledger Nano X with bluetooth when on the move would be awesome! Please implement this feature!
