### ISSUE TITLE
App does not ask for authentication either upon opening or after the designated timeout.

### ISSUE THREAD

**Issue by Sch00ner** [MetaMask/metamask-mobile#2673]
**Describe the bug**
The password set is not requested to open the app or after the time set in the **Auto-lock** option in settings

**Screenshots**

**To Reproduce**
_Steps to reproduce the behavior_
1. Open Metamask app.
2. Set an **Auto-lock** timeout.
3. Wait for the time set.
4. App does not lock or ask for password initially.

**Expected behavior**
App does not ask for password when opening it and after the timeout period.

**Smartphone (please complete the following information):**
 - Device: Nokia 5.3
 - OS: Android 10
 - App Version: 2.2.0 (54)

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by transitori** [comment]
This bug also exists on iOS iPhone X MetaMask v2.5.0 (750). App never locks. Anyone who can access your phone will have full access to your wallet. This is a major bug.

**Comment by transitori** [comment]
I got it to work on iphone by logging out and logging back in. Make sure ‘remember me’ is unchecked on login.

**Comment by Sch00ner** [comment]
> I got it to work on iphone by logging out and logging back in. Make sure ‘remember me’ is unchecked on login.

Can confirm that this works. Closing the issue.
