### ISSUE TITLE
Adding decimals to gas calculation crashes MetaMask

### ISSUE THREAD

**Issue by jacobcantele** [MetaMask/metamask-mobile#2690]
**Describe the bug**
When sending a transaction, editing the "gas price: (GWEI)" field with a decimal point will either result in a negative number or completely crash the app.

This bug exists regardless of platform (Android or iOS), and I've been able to confirm it on three devices. It also happens regardless of which network the user is on.

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by wachunei** [comment]
I reproduced. 

A question here: do we want to allow decimal Gwei custom values?

A suggestion is to safe return when the new value is not a valid format:

```diff
diff --git a/app/components/UI/CustomGas/index.js b/app/components/UI/CustomGas/index.js
index be6d5ab7..9d87dc11 100644
--- a/app/components/UI/CustomGas/index.js
+++ b/app/components/UI/CustomGas/index.js
@@ -486,7 +486,10 @@ class CustomGas extends PureComponent {
 	onGasPriceChange = value => {
 		const { customGasLimitBN } = this.state;
 		//Added because apiEstimateModifiedToWEI doesn't like empty strings
-		const gasPrice = value === '' ? '0' : value.replace(' ', '').replace(',', '.');
+		const gasPrice = value === '' ? '0' : value.replace(/\s|[a-zA-Z]/, '').replace(',', '.');
+		if (!/^\d+$|^\d+\.\d+$/g.test(gasPrice)) {
+			return;
+		}
 		const gasPriceBN = new BN(gasPrice);
 		const gasPriceBNWei = apiEstimateModifiedToWEI(gasPrice);
 		const warningSufficientFunds = this.hasSufficientFunds(customGasLimitBN, gasPriceBNWei);

```

**Comment by mobularay** [comment]
@jacobcantele brought this up in mobile channel over the weekend. @wachunei reviewed over the weekend, and found the root cause. 

This ticket covers the temporary stop-gap work, which is to catch the error properly and prevent the app from crashing. QA and Engineers felt dev review and QA review will be quick, so we are including this work in this sprint. 

Another ticket will be created for long-term work.
