### ISSUE TITLE
Transaction submitted message stuck

### ISSUE THREAD

**Issue by masad08** [MetaMask/metamask-mobile#2696]
Hi
A message of transaction submitted just came, and it is stuck
Cleared cache
Restarted phone
Clear metamask cache and browser history... Closed and opened in metamask different dxes
Used ether et and bsc...
No effect. Still there

Can't use metamask

Couldn't find similar reported.
If there is, please help 
![Screenshot_20210518-190146_MetaMask](https://user-images.githubusercontent.com/72976781/118685219-93dfc980-b80b-11eb-9b0b-38623fd91f89.jpg)

**Comment by mobularay** [comment]
@masad08 thank you so much for reporting this issue here. We have a fix that is being rolled out this week in our latest update (v2.4). This update is currently available on Google Play; it's pending approval on Apple Store :-) Let me know how it goes once your app gets update! 

CC @omnat

**Comment by mobularay** [comment]
Note for internal bug management: keeping this ticket open until end of this sprint. If there is no more feedback or questions, then will close this ticket on June 4th.

**Comment by mobularay** [comment]
@masad08 do you now have v2.4? Are you still seeing this issue? 

Thank you!

**Comment by mobularay** [comment]
Closing this issue since I haven't heard from @masad08
