### ISSUE TITLE
The app is throwing a non descriptive error when opening our staging app URL : View: Root Error: Text strings

### ISSUE THREAD

**Issue by LastKenobi** [MetaMask/metamask-mobile#2716]
**Describe the bug**
We started testing our new staging environment for [AirNFTs](https://www.airnfts.com) and when we tested on Metamask Mobile it suddenly started failing when opening the staging URL https://app-staging.airnfts.com/
It logged the error below 👇

```
View: Root
Error: Text strings must be rendered within a <Text> component.
```

I checked on older issues on this repo, it seems to have come back many times, the issue here is we can't debug it since it's non descriptive, we can't know know for sure which strings threw that error.

Just for more contextual info, this URL doesn't crash on Metamask chrome plugin, only the mobile app.

**Screenshots**

![photo_2021-05-23 02 42 28](https://user-images.githubusercontent.com/82703779/119243570-a3934100-bb70-11eb-9050-ab1d3f905bc3.jpeg)

**To Reproduce**
_Steps to reproduce the behavior_
1. Go to browser
2. Type on 'https://app-staging.airnfts.com/'
3. See error

**Expected behavior**
Metamask shouldn't crash on opening a dapp URL, and if it would crash it should provide a precise error message that would help on debugging

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhoneX, Galaxy S10]
 - OS: [e.g. iOS14, Android 11]
 - App Version : v2.2.0 (54)

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by oesukam** [comment]
Hi @LastKenobi , I'm facing the same issue. 
Did you manage to resolve the issue?

I have just raised a PR,  hope to be approved soon. [PR](https://github.com/MetaMask/metamask-mobile/pull/2720)

**Comment by oesukam** [comment]
@LastKenobi You can correct your website's favicon.ico as a quick fix to resolve your issue
