### ISSUE TITLE
Unable to fetch Chain ID: MM Mobile does not support basic auth

### ISSUE THREAD

**Issue by akegaviar** [MetaMask/metamask-mobile#2717]
**Describe the bug**
When trying to add a network to MetaMask mobile with an endpoint that's basic auth protected (e.g. https://user:password@domain.com), you get the Unable to fetch ChainID

**To Reproduce**
1. Run MM mobile
2. Attempt to add a custom network (e.g. Ethereum Ropsten) with a basic auth endpoint (https://user:password@domain.com)
3. Get the Unable to fetch ChainID error.

**Expected behavior**
I can basic auth protected endpoints.

**Smartphone (please complete the following information):**
 - Device: iPhoneX
 - OS: iOS 14.4.2
 - App Version: MetaMask v2.3.0 (715)

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by beeb** [comment]
Can confirm this bug! Impossible to use a protected custom rpc

**Comment by uwieske** [comment]
Same problem with Chain ID. Is het going to be fixed soon? (timetable knowns?)
