### ISSUE TITLE
Show the contract receiving token allowances on the allowance screen

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-mobile#2723]
**Description**
Apply this to the Approve DAPP Browser flow for smart contract TXs.

**Acceptance Criteria**
- The contract receiving an allowance should be visible on this screen. If this is the first time interacting with this contract, [the user should be prompted to assign the contract a nickname](https://github.com/MetaMask/metamask-mobile/issues/2722).
- Text update per Figma diagram to notify user they are sending funds to smart contract
- Enable pet naming for smart contracts in the token approval flow
- Do not add Dapp smart contract tx to "recents" list in the send flow
- Metrics - https://www.notion.so/Show-receiving-contract-address-on-all-signatures-and-transaction-confirmations-8bfafb22aa18494883d7779735ad429e#5ebd7fbb0f8d40e5bd0367e8fbfb8f58
- Apply the address display fallback logic everywhere where user interacts with an Ethereum address (sending ether, sending tokens, approving token transfers, NFT transfers/approvals, "contract interactions"
- Verify the custom allowance is applied in this new layout

**References**
- Mobile version of: https://github.com/MetaMask/metamask-extension/issues/7574
- Figma Link: https://www.figma.com/file/eEFSq73S1NLEReogz1WTUG/ERC20-token-approval?node-id=634%3A221

![image](https://user-images.githubusercontent.com/542863/119546623-f6bfec00-bd48-11eb-9d2e-73db2d3201c4.png)

Address naming fallback logic https://www.notion.so/address-display-fallback-logic-520b84be34b84952b5cb9fd0b508ce23

Design file ( @yanrong-chen will add) for where to show the contract address, and address book prompt.

**Comment by sethkfman** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/MetaMask-Mobile-5f984938ddc0e4001d4b79cb/issues/MetaMask/metamask-mobile/2723?planning-poker) with ZenHub @blackdevelopa @cortisiko

**Comment by sethkfman** [comment]
@cortisiko When testing this make sure the custom allowance option is behaving as expected. 

For reference: https://github.com/MetaMask/metamask-mobile/pull/3863
