### ISSUE TITLE
window.ethereum is undefined on metamask Android

### ISSUE THREAD

**Issue by JosephSaw** [MetaMask/metamask-mobile#2724]
**Describe the bug**
window.ethereum is undefined on metamask android, therefore I cannot connect my wallet at all.

However, it works on everything else such as Metamask IOS, and the metamask Chrome Extension.

I am using Nuxtjs as my web framework, and onboardjs as my wallet provider.

**Screenshots**
https://pendle-ui-staging.et.r.appspot.com/ - You can check out this URL on the metamask android mobile app. I have installed a 'Vconsole' on the bottom left so that you view the console even on your mobile. 

I have added a code snippet like so 
![image](https://user-images.githubusercontent.com/28586597/119601784-779be800-be1c-11eb-82b6-ed338cf2d9ff.png) 

So you can check if the ethereum object is injected properly.

**To Reproduce**
_Steps to reproduce the behavior_
1. Go to https://pendle-ui-staging.et.r.appspot.com/
2. Click on the green Vconsole button on bottom right
3. Look at the logs to check if window.ethereum is injected (if you are are on metamask android, it is not injected atll)

**Expected behavior**
ethereum object to be injected to the window object 

**Smartphone (please complete the following information):**
 - Device: Android
 - OS: Android Version 10
 - App Version [e.g. 1.0.0] - 2.2.0

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by MrPeanutz** [comment]
This is also happening to our DAPP (pacoca.io), works on all other wallets but not metamask

**Comment by MrPeanutz** [comment]
This was also happening to TrustWallet, but they had it fixed: https://github.com/trustwallet/trust-web3-provider/issues/139

**Comment by JosephSaw** [comment]
Yea, as i doubt there will be any response for a while, our team has decided to migrate our project from Nuxt -> Vue. 🙃

@MrPeanutz what UI framework are you using?

**Comment by MrPeanutz** [comment]
I'm also using nuxt, do you know if this issue is related to nuxt?

**Comment by JosephSaw** [comment]
It seems to be happening only on Nuxt, so I am thinking it's the cause of some incompatibility issue, our team hasn't really been able to pinpoint the exact cause though...

When we tried with a barebone Vue.js project everything seems to be working fine. So we've decided the fastest fix to this would just be to downgrade our project..

**Comment by jamesmorgan** [comment]
I am also seeing this on nuxt - it works in all other dapp browsers but in MM Android and with both onboardjs and classic instantiation, it doesnt seem to recognise web3/ethereum?

**Comment by longhuicode** [comment]
I'm also developing a DApp using nuxt.js and I'm having the same problem

**Comment by romansemko** [comment]
https://test.minted.vodka <-- Same issue on Android 9/10. Android 11 seems to work fine.

**Comment by andrepimenta** [comment]
@JosephSaw Does this still happen in the current live version?

**Comment by HaneulChile** [comment]
Anyone find the solution?

**Comment by NorthHub** [comment]
> I fixed this issue. Just change the `app.html` `<head {{ HEAD_ATTRS }}>` to `<head>` in Nuxt.js and it works. I noticed that the original HTML returned by the server using `<head {{ HEAD_ATTRS }}>` had an extra space in the `<head >` tag, and MetaMask might be injecting the environment based on the `<head>` tag. ![image](https://user-images.githubusercontent.com/20459605/139391825-95872145-a32b-4dc1-a969-1fc538444ee7.png)

I had a similar problem. I disabled html compression and everything worked! Thank you, you saved me!

**Comment by Polar-DANO** [comment]
Similar problem too.
Fixed by adding an app.html with the balise <head> </head> and not <head >. Disabled html compression didn't work for us

**Comment by inflaton** [comment]
> Similar problem too. Fixed by adding an app.html with the balise head without the whitespace. Disabled html compression didn't work for us

thanks - this works for my nuxt dapp. It really saved my day
