### ISSUE TITLE
Metamask pop-up doesn't show on app relaunch

### ISSUE THREAD

**Issue by nithronium** [MetaMask/metamask-mobile#2725]
**Describe the bug**
I am using my Dapp to connect Metamask. Upon clicking "connect", user is redirected to the Metamask and popup shows up for authorization. Later user can interact with the dapp. However, after a couple minutes, if user wants to interact with Dapp and clicks on button to submit transaction, user is redirected to the Metamask app but no popup is shown. 

User has to remove the walletconnect connection from settings and re-authorize, then is able to see the tx popup. This behavior only exists in mobile Metamask and not on the desktop versions.

**To Reproduce**
1. Visit a dapp's website on mobile device, and use wallet connect to connect with Metamask and confirm the authorization.
2. Interact with dapp for 2-3 minutes, send a transaction
3. Minimize the Metamask, and use some other apps for 2-3 minutes
4. Refresh the dapp page, and re-interact, try to send a transaction. App redirects to Metamask but no popup shown for the transaction.

**Expected behavior**
Popup shown on every redirection to Metamask.

**Smartphone (please complete the following information):**
 - Device: iPhone X and various Samsung, Xaomi android devices
 - OS: iOS and Android latest on all devices
 - App Version [e.g. 1.0.0] - v2.2.0

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by gantunesr** [comment]
Related to #3583

**Comment by skyrover7** [comment]
Just my $0.02 on this.

* I have been using deeplinks created by [this generator](https://metamask.github.io/metamask-deeplinks/#) in a react web app for a few months now. It did not properly work before and it seems in recent changes does not even work to the extent it used to. 
* Previously, on mobile, we would direct the user to the deeplink which would open up Metamask. However if the app was starting fresh it would ask for authentication, and once authentication completed, it would not do anything.
* If I would switch back to the browser, and reclick the deeplink, Metamask (now already logged in) would open the dapp properly in the Metamask Browser. This was good, but most people would probably drop off after the first attempt

I recently was trying the same application that is referenced above and now after the redirect to Metamask no action is taken. I can't get the Metamask browser to open in any case. 

Here is the deeplink I am using for reference: https://metamask.app.link/dapp/fractionl.art/

I am on Android, and am waiting for test results from an iphone. This is a pretty critical step when it comes to Web3 sites trying to seamlessly work on mobile. Please help 🙏🏾

**Comment by gantunesr** [comment]
Hey @nithronium and @skyrover7, can you check v4.2.0 to verify if your issue is solved

**Comment by skyrover7** [comment]
@gantunesr thank you for the update!

I tried this on my Android phone. 
* After clicking on the deeplink from the mobile website my phone asked which app to use to complete this activity.
* I chose Metamask
* Metamask opened up fine (both with authentication and if I had recently already authenticated)
* However at this point I would expect the inbuilt browser to open with the site from the deeplink. I am not seeing that happen. 

Let me know if you'd like more details!

**Comment by duyta7598** [comment]
@gantunesr In my case, It only happen few times.
Normaly, user can use metamask to connect or sign message without problem, but sometime It doesn't show pop up on metamask and no error return, so I can't know when it will happen.
Any help would be appreciated!

**Comment by andreahaku** [comment]
> @gantunesr In my case, It only happen few times. Normaly, user can use metamask to connect or sign message without problem, but sometime It doesn't show pop up on metamask and no error return, so I can't know when it will happen. Any help would be appreciated! P.S: Currently I use the newest version of Metamask 5.0.1

Hi @duyta7598 we need something to be able to replicate it as it may not depend on deep links but on something else (like the content of the deep link itself). If you can provide more info it would be great. Thanks.

**Comment by duyta7598** [comment]
@andreahaku Sorry about late response , I used this library walletconnect-react-native-dapp to make a connection between my app and metamask. I don't know if this is a problem but it seem to happen when I add too many metamask accounts in metamask and I test it too many times (like connect and disconnect over and over).
It maybe not a very important problem but it's nice to have some ways to fix

**Comment by andreahaku** [comment]
> @andreahaku Sorry about late response , I used this library walletconnect-react-native-dapp to make a connection between my app and metamask. I don't know if this is a problem but it seem to happen when I add too many metamask accounts in metamask and I test it too many times (like connect and disconnect over and over). It maybe not a very important problem but it's nice to have some ways to fix

Hi @duyta7598 , thanks. I'll try to do some stress testing as well and see if I can replicate the issue. I close the issue for now and if I see that is a potential problem for everyday usage then I'll reopen it. Thanks a lot again.

**Comment by skyrover7** [comment]
Doesn't appear to be resolved on Android. Seen it working well on iphones

**Comment by andreahaku** [comment]
> Doesn't appear to be resolved on Android. Seen it working well on iphones @andreahaku

Which version of the app are you using? Which version of Android?
Also sometimes you need to manually check for the app to be authorised to open that link.

You can check that by:

**Open Android settings , search 'default' and select "Choose Default apps' > "Choose Default apps" > Opening Links > scroll down to MetaMask and tap it > Supported Web addresses > check if links are selected or "verified/trusted" by default (most importantly metamask.app.link). If they are not, then check them/it**

**Comment by skyrover7** [comment]
- Android Version `12`
- App Version: `v5.0.1 (877)`
- Device: Pixel 5

Following the steps you mentioned seems to have resolved the issue. Once I got to `Opening Links` and opened Metamask it showed 0 verified links and an option to `Add Link`. Once I did that, it showed me 5 possible links, of which `metamask.app.link` was included. Once I did this and tried the deeplink it worked well!

However is there no way to enable this by default? It will be hard to guide users to go through these settings changes. Thanks!

**Comment by andreahaku** [comment]
> * Android Version `12`
> * App Version: `v5.0.1 (877)`
> * Device: Pixel 5
> 
> Following the steps you mentioned seems to have resolved the issue. Once I got to `Opening Links` and opened Metamask it showed 0 verified links and an option to `Add Link`. Once I did that, it showed me 5 possible links, of which `metamask.app.link` was included. Once I did this and tried the deeplink it worked well!
> 
> However is there no way to enable this by default? It will be hard to guide users to go through these settings changes. Thanks!

Good news! Probably uninstalling and reinstalling the app should do the trick. It does depend on Android ;)

**Comment by skyrover7** [comment]
Understood, will try it out!
