### ISSUE TITLE
1) Appending bytes to tx payload in `data` field scrambles e.g. displayed ERC20 transfer value & using `sendTransaction` to transfer ERC20s results in contract deployment

### ISSUE THREAD

**Issue by hilmarx** [MetaMask/metamask-mobile#2744]
**Describe the bug:**

When sending transactions on Ethereum, e.g. an ERC `transfer`, you can append `bytes` to the encoded `transfer` payload. This is used by dApps to `enrich` the information of certain transactions with additional data. In our case, it is used to later verify on-chain that certain data which was appended to a regular ERC20 transfer was indeed signed by the user or not. 

It can look something like this:

```typescript

const erc20Interface = new ethers.utils.Interface(["function transfer(address recipient, uint256 amount)"])

const encodedData = erc20Interface.encodeFunctionData("transfer", [receiver, inputAmount])

const appendedData = new ethers.utils.AbiCoder().encode(
        ["address", "uint256"],
        [toCurrency, minimumReturn]
);

const concatData = encodedData + appendedData.substr(2)

const res = await provider.getSigner().sendTransaction({
        data: concatData,
        to: fromCurrency,
        gasLimit: 100000,
})
```

On desktop using Metamask or any other wallet, this works fine. However on Metamask mobile, the extra data which was appended to the regular erc20 encoded data seems to completely mess with the transaction, leading to the amount to be transferred to be completely messed up (Very dangerous) and the `to` field being undefined, resulting in the transaction trying to deploy a contract.

**Screenshots**

How it should look like:
![IMG_1733](https://user-images.githubusercontent.com/19579480/120624210-bf47f280-c460-11eb-8152-30caeb08bca9.PNG)

How it actually looks like:
![IMG_1732](https://user-images.githubusercontent.com/19579480/120624223-c2db7980-c460-11eb-89a3-dfc500b6fd82.PNG)

=> Sending this transaction will result in a contract being deployed which fails. 

**To Reproduce**
Check out this codebase of using `sendTransaction` with a regular erc20 transfer payload (without appended data):

https://github.com/gelatodigital/sorbet-finance/blob/288c42f1dbb786d510265b95aad0cff164a47607/src/components/ExchangePage/index.jsx#L617-L625

You can try it out here:
https://sorbet-finance-git-fix-metamask-mobile-bug-gelato.vercel.app

It works fine, however defeats the purpose of the dApp (we need to append some additional payload to the `data`)

Now, check out this codebase, where we do append additional payload to the data field:
https://github.com/gelatodigital/sorbet-finance/blob/fe8e198d5d2d4c32d0a838b6b9e696c5bd04e496/src/components/ExchangePage/index.jsx#L617-L630

You can try it out here:
https://sorbet-finance-git-fix-metamask-mobile-bug-2-gelato.vercel.app

There you will see the bug occurs. As mentioned before, on Web Metamask and using other Wallets such as Formatic, it works fine. This issue also occurs on Mainnet, not only Matic.

**Smartphone**
 - Device: iPhoneX
 - OS: iOS14.4
 - App Version: v2.4.0
 
 
**EDIT:** 
 
Replying to @MaartenWeber14 comment.

I just checked again and I think you are right, I am talking about two separate issues here. 

**Issue 1)** If you append data to the e.g. `transfer` payload, the displayed values of how will be transferred get completely scrambled as seen in the screenshots of my original comment above.

**Issue 2)** If you use `sendTransaction`, even if you dont append any extra bytes to the payload, the `to` address is interpreted as undefined and a contract gets deployed instead of the `to` address being the ERC20 token.

**Comment by EerieEight** [comment]
Hey all! Half of our users come through MM mobile and this issue is directly affecting them, as well.

**Comment by MaartenAxa** [comment]
@hilmarx are you sure this is caused by appending bytes to the encoded transfer payload? We are experiencing the same issue it seems. Whenever we try to transfer an amount, MM mobile says it's a transfer. But when you accept the tranfer, it tries to deploy a new contract. When inspecting the transaction, the payload is fine, but it seems the to address has been set to undefined indeed, resulting in a failed contract deployment.

However, we aren't appending anything to the payload (as far as I know). We also only have this issue on mobile. On web it works as it should. For reference, we're using WalletConnect to connect to MM and do the transfer.

Hope this thing can be fixed/cleared up soon, as MM is used by a lot of users.

**Comment by hilmarx** [comment]
@MaartenWeber14 thanks for you comment, you are right, I added an EDIT to my original comment above.

**Comment by Gazoh** [comment]
Is there any updates or workarounds?

**Comment by gitpusha** [comment]
Yeah would also be keen to get an update on this!

**Comment by ooGwei** [comment]
Still affected by this bug and appreciate any workarounds as it is directly preventing Mobile users from using a portion of a platform.

**Comment by DeepakMotamarri** [comment]
Appreciate any workarounds or updates on this issue

**Comment by hasanghanavi** [comment]
It's very important issue. No updates yet?

**Comment by CodeXSky** [comment]
It still have this problem when send token erc20 through walletconnect service by web3js. Anyone have solution for that?

**Comment by quan32** [comment]
This bug is so serious, please update ASAP.
Anyone have any temporary solution for this?

**Comment by scrubotage** [comment]
Following up to see if this has been addressed yet.  This is impacting countless users.

**Comment by 1brahimsaid** [comment]
Hi this issue has been plaguing me for weeks, it would be great if we could solve this soon. For now I have to use my PC each time to do this same thing I enjoy on mobile.

**Comment by midas104** [comment]
This issue is caused by code that substitute `value` and `to` transaction properties by encoded transfer data([this one](https://github.com/MetaMask/metamask-mobile/blob/e77e1a3fc11523c8f75a83cab41cf945e693767b/app/components/Nav/Main/index.js#L361))

The easiest fix is to introduce case insensitive search [here](https://github.com/MetaMask/metamask-mobile/blob/e77e1a3fc11523c8f75a83cab41cf945e693767b/app/components/Nav/Main/index.js#L348) because contract map has vary case keys.

Possible fix

```js
// `to` is lowercased on line #316
let asset = props.tokens.find(({ address }) => address.toLowerCase() === to);
if (!asset) {
  // try to lookup contract by lowercased address `to`
  asset = contractMap[Object.keys(contractMap).find(key => key.toLowerCase() === to];
  if (!asset) {
    try {
      asset = {};
      asset.decimals = await AssetsContractController.getTokenDecimals(to);
      asset.symbol = await AssetsContractController.getAssetSymbol(to);
      // adding `to` here as well

      asset.to = to;
    } catch (e) {
      // This could fail when requesting a transfer in other network
      // adding `to` here as well
      asset = { symbol: 'ERC20', decimals: new BN(0), to: to };
    }
  }
}

```

**Comment by midas104** [comment]
PS My dApp is affected when try to submit transaction via WalletConnect

**Comment by 0xBebis** [comment]
facing same issue

**Comment by leon-do** [comment]
same issue. waiting for a solution.

**Comment by zmyqucai8** [comment]
This is a very serious problem why not solve it first？😅

**Comment by mobularay** [comment]
Treat this ticket to represent the 1st issue; @gantunesr will create a separate ticket for the 2nd issue. ]

Estimation for this ticket represents the 1st issue.

**Comment by LouiseCat** [comment]
same issue. waiting for a solution.

**Comment by ptorrent** [comment]
any news ?

**Comment by Yuaimin** [comment]
the problem is too fatal!

**Comment by llioor** [comment]
Big number issue? Community?
+1

**Comment by EtienneHelfer** [comment]
Any news ? this is a huge problem and should be easy to fix
