### ISSUE TITLE
Displaying transactions on metamask android

### ISSUE THREAD

**Issue by buckyroid** [MetaMask/metamask-mobile#2745]
**Describe the bug**
Hi, I am an android dev and facing some trouble when sending transactions from my mobile dapp to metamask(version 0.2.4). It works on other versions and other wallets though. I can connect, but my transactions wont show up. (Btw: I am using walletconnect to interact with metamask) 

**Screenshots**
_If applicable, add screenshots or links to help explain your problem_

**To Reproduce**
_Steps to reproduce the behavior_
1. Connect my user to metamask with walletconnect
2. Create a transaction
3. Send it to metamask
4. Nothing happens

**Expected behavior**
I was expecting my transaction to show up after connection.

**Smartphone (please complete the following information):**
 - Device: Honor 9x, Xiaomi note 9S, Samsung a50
 - OS: android 10, android 11
 - App Version 0.2.4

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by gantunesr** [comment]
Related to #3583

**Comment by gantunesr** [comment]
Hi @buckyroid, can you verify if this is still an issue in the next release (v4.2.0)?

**Comment by buckyroid** [comment]
Hi @gantunesr, it is fixed now, thank you. But now I am having another trouble, I can see my transactions, but when I click confirm, it says "oops something went wrong" and shows an error about nonce undefined. :/

**Comment by gantunesr** [comment]
@buckyroid can you provide a recording or the steps necessary to reproduce this issue??

**Comment by buckyroid** [comment]
@gantunesr just send a transaction and click on accept. It does not accepts it, transaction fails.

**Comment by gantunesr** [comment]
Hey @buckyroid, I'll close this issue in favor of #3927. I'll be posting updates there. Thanks for reporting!
