### ISSUE TITLE
Metadata description not showing

### ISSUE THREAD

**Issue by bigchiano** [MetaMask/metamask-mobile#2753]
**Describe the usability problem**
I have deployed an erc721 smart contract and added to open-sea but when I view nft on metamask app the image and name shows up but I don't see the description of the nft

**Screenshots**
![image](https://user-images.githubusercontent.com/37911422/121026552-25ed4900-c79e-11eb-8b4b-ae6fe93c3f22.png)

Link to smart contract source
https://github.com/ochukochris/opensea-metamask-nft/blob/main/contracts/RandNft.sol

**Expected behavior**
I expect it to show the most basic metadata needed like name, image, and description

**Comment by estebanmino** [comment]
Hi @ochukochris is this your collectible? https://opensea.io/assets/matic/0x9dcdb513f3fccf3499130665d466700085a9fcaa/9001

I don't see anything on opensea now, are you able to see the info you want there?

**Comment by ochukochris** [comment]
I’m sorry I forgot to mention that it is on matic

**Comment by ochukochris** [comment]
> Hi @ochukochris is this your collectible? https://opensea.io/assets/matic/0x9dcdb513f3fccf3499130665d466700085a9fcaa/9001
> 
> I don't see anything on opensea now, are you able to see the info you want there?

Hello

**Comment by gantunesr** [comment]
Hi @bigchiano, this issue should be fixed in the latest release. Please open a new issue if the bug persists.
