### ISSUE TITLE
Failure to launch App on Emulator

### ISSUE THREAD

**Issue by sasi-cognox** [MetaMask/metamask-mobile#2755]
Please help. Failing to launch app to emulator due to  due to 'Execution failed for task ':react-native-aes-crypto:compileDebugJavaWithJavac''

Here's the log of `yarn start:android`
`yarn run v1.22.5`
`$ ./scripts/build.sh android debug`
``
`-------------------------------------------`
``
`  🚀 BUILDING ANDROID IN DEBUG MODE `
``
`-------------------------------------------`
``
`* daemon not running; starting now at tcp:5037`
`* daemon started successfully`
`info Running jetifier to migrate libraries to AndroidX. You can disable it using "--no-jetifier" flag.`
`(node:9349) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency`
`(Use `node --trace-warnings ...` to show where the warning was created)`
`Jetifier found 1917 file(s) to forward-jetify. Using 4 workers...`
`info JS server already running.`
`adb server version (39) doesn't match this client (41); killing...`
`* daemon started successfully`
`info Launching emulator...`
`info Successfully launched emulator.`
`info Installing the app...`
``
`> Configure project :@react-native-community_blur`
`WARNING: The option setting 'android.disableResourceValidation=true' is experimental.`
`The current default is 'false'.`
``
`> Configure project :exodus_react-native-payments`
`WARNING: Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.`
`It will be removed in version 5.0 of the Android Gradle plugin.`
`For more information, see http://d.android.com/r/tools/update-dependency-configurations.html.`
``
`> Configure project :lottie-react-native`
`publishNonDefault is deprecated and has no effect anymore. All variants are now published.`
``
`> Configure project :react-native-aes-crypto-forked`
`WARNING: Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.`
`It will be removed in version 5.0 of the Android Gradle plugin.`
`For more information, see http://d.android.com/r/tools/update-dependency-configurations.html.`
``
`> Configure project :react-native-os`
`WARNING: Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.`
`It will be removed in version 5.0 of the Android Gradle plugin.`
`For more information, see http://d.android.com/r/tools/update-dependency-configurations.html.`
`WARNING: The specified Android SDK Build Tools version (23.0.1) is ignored, as it is below the minimum supported version (29.0.2) for Android Gradle Plugin 4.0.1.`
`Android SDK Build Tools 29.0.2 will be used.`
`To suppress this warning, remove "buildToolsVersion '23.0.1'" from your build.gradle file, as each version of the Android Gradle Plugin now has a default version of the build tools.`
`WARNING: The specified Android SDK Build Tools version (26.0.1) is ignored, as it is below the minimum supported version (29.0.2) for Android Gradle Plugin 4.0.1.`
`Android SDK Build Tools 29.0.2 will be used.`
`To suppress this warning, remove "buildToolsVersion '26.0.1'" from your build.gradle file, as each version of the Android Gradle Plugin now has a default version of the build tools.`
``
`> Task :react-native-aes-crypto:compileDebugJavaWithJavac FAILED`
``
`Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.`
`Use '--warning-mode all' to show the individual deprecation warnings.`
`See https://docs.gradle.org/6.7.1/userguide/command_line_interface.html#sec:command_line_warnings`
`355 actionable tasks: 2 executed, 353 up-to-date`
`/home/sasivr/github/metamask-mobile/node_modules/react-native-aes-crypto/android/src/main/java/com/tectiv3/aes/RCTAes.java:95: error: method pbkdf2Sync(String,String,Integer,Integer) is already defined in class RCTAes`
`        public String pbkdf2Sync(String pwd, String salt, Integer cost, Integer length)`
`                      ^`
`1 error`
``
`FAILURE: Build failed with an exception.`
``
`* What went wrong:`
`Execution failed for task ':react-native-aes-crypto:compileDebugJavaWithJavac'.`
`> Compilation failed; see the compiler error output for details.`
``
`* Try:`
`Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.`
``
`* Get more help at https://help.gradle.org`
``
`BUILD FAILED in 10s`
``
`error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup. Run CLI with --verbose flag for more details.`
`Error: Command failed: ./gradlew app:installDebug -PreactNativeDevServerPort=8081`
`/home/sasivr/github/metamask-mobile/node_modules/react-native-aes-crypto/android/src/main/java/com/tectiv3/aes/RCTAes.java:95: error: method pbkdf2Sync(String,String,Integer,Integer) is already defined in class RCTAes`
`error Command failed with exit code 1.`
`info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.`
``
`Please help`

* What went wrong:
Execution failed for task ':react-native-aes-crypto:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 10s

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup. Run CLI with --verbose flag for more details.
Error: Command failed: ./gradlew app:installDebug -PreactNativeDevServerPort=8081
/home/sasivr/github/metamask-mobile/node_modules/react-native-aes-crypto/android/src/main/java/com/tectiv3/aes/RCTAes.java:95: error: method pbkdf2Sync(String,String,Integer,Integer) is already defined in class RCTAes
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.`

System Specs:
OS - Ubuntu 20.04.2 LTS
Node - v14.17.0

**Expected behavior**
App should be launched on emulator, but it's failing with an error

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by neel-thakker** [comment]
I'm facing the same issue, were you able to fix it ?

**Comment by DarkUD** [comment]
Alternatively what I did after restarting the whole process was :

yarn remove react-native-aes-crypto
yarn add react-native-aes-crypto

it patched the package.json and changed it so we have this line 
"react-native-aes-crypto": "^1.3.10"

then yarn start:android.

It started the emulator without any issue.
