### ISSUE TITLE
Show ENS reverse-resolved name on account detail view

### ISSUE THREAD

**Issue by omnat** [MetaMask/metamask-mobile#2783]
If a user has not changed their account nickname (it is not \Account $[0-9]+\), and an ENS reverse-resolved name is available for that account, then show the reverse-resolved name for that account.

Extension reference: https://github.com/MetaMask/metamask-extension/issues/11273

Requirements:
- Only show ENS reverse-resolved name in the account name (not in the address).

**Account Overview**
![AccountOverview](https://images.zenhubusercontent.com/60d0d9a2caf077062491ff09/c03f315a-c1b2-447a-9be1-4f78425c7f97)

**Accounts List**
![account_list.png](https://images.zenhubusercontent.com/60d0d9a2caf077062491ff09/f3612b2a-f4ea-4652-bdda-b0d90c36a0d3)

**Comment by gantunesr** [comment]
The account name and the address should show the ENS reverse-resolved name?

![ens.png](https://images.zenhubusercontent.com/60d0d9a2caf077062491ff09/b6ebbd8b-466d-4f3a-8f95-64f981aa2b33)

**Comment by mobularay** [comment]
PR: https://github.com/MetaMask/metamask-mobile/pull/2878
