### ISSUE TITLE
NFT removed when the transaction fails

### ISSUE THREAD

**Issue by Garito** [MetaMask/metamask-mobile#2784]
**Describe the bug**
When a user try to transfer the token, if the transaction fails, the wallet shows a correct transaction (which is and error) and the token disappears 

**To Reproduce**
_Steps to reproduce the behavior_
1. Create an ERC721 and use _beforeTokenTransfer to avoid the transfer if the user is not the owner of the token
2. Mint one for the account of the mobile wallet (with a different account that the creator of the token)
3. Transfer the token to another wallet
4. The transaction seems ok and the token is no longer there
5. Go to etherscan to view the transaction
6. Should be failed

**Expected behavior**
The wallet must show an invalid transaction and the token should remain

**Smartphone (please complete the following information):**
 - Device: iPad 5gen
 - OS: IOS14.4.2
 - App Version 2.4.0

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by tommasini** [comment]
I couldn't replicate the bug. 

What I did :

- I created two accounts in the Rinkeby Test Network
![image](https://user-images.githubusercontent.com/46944231/153693608-d7bf747d-6de5-4324-be2b-16b8f36f1475.png)


- On https://testnets.opensea.io/, I bought a Token, the Token Standard was ERC-721 in the Rinkeby blockchain with one of my accounts. 

- I imported them to my account Metamask Wallet for I could see them
- I send them for the other account 
- The transaction in the mobile app was successful
- In the etherscan was successful too (after indexed)

Everything seems to be working as supposed.

**Comment by tommasini** [comment]
Anyone know how could I replicate this error? @gantunesr

**Comment by Garito** [comment]
6 months latter and some updates and now you are interested on this?
what a joke

**Comment by gantunesr** [comment]
@tommasini as the issue indicates, the problems occurs when the tx fails. The app currently removes the collectible when the tx is submitted, it should wait for it to be confirmed before removing the collectible

**Comment by chrisleewilcox** [comment]
@Garito can you do steps 1 and 2 to this address so we have the correct type of NFT to test with: 0x4E99C54C06efbdB7DEdfE34e2Aeb84C0Ce19BE9E

I can't find an NFT with on a test network that has that used _beforeTokenTransfer.
