### ISSUE TITLE
Can't scroll on dapp modal to view warnings/errors 

### ISSUE THREAD

**Issue by ibrahimtaveras00** [MetaMask/metamask-mobile#2794]
**Describe the bug**

I am unable to clearly see any error/warning message when interacting with a dapp

**Screenshots**

![image](https://user-images.githubusercontent.com/41752922/121750009-8f8c9080-cad9-11eb-9e21-f56b9ae5616e.png)

**To Reproduce**
A part of me feels like this may be because I have custom nonce enabled

1. Go to burger menu > settings > advanced 
2. Enable custom nonce and show hex data
3. Attempt to make a warning appear on the dapp modal (not enough ETH, or high gas warning)
4. To pop up a dapp modal easiest way is to go to https://metamask.github.io/test-dapp and after connecting wallet, tap on Send or deploy contract or create token
5. Notice how it gets cut off and you can't scroll 

**Expected behavior**

I should be able to properly view any and all warnings

**Smartphone (please complete the following information):**
 - App Version 2.4.0 +

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by gantunesr** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/MetaMask-Mobile-5f984938ddc0e4001d4b79cb/issues/MetaMask/metamask-mobile/2794?planning-poker) with ZenHub @Fatxx @plasmacorral

**Comment by tommasini** [comment]
Workaround for the scroll view works inside the react-native-modal lib found here: https://github.com/react-native-modal/react-native-modal/issues/236
