### ISSUE TITLE
Add token popup doesn't open

### ISSUE THREAD

**Issue by benjaminbouwyn** [MetaMask/metamask-mobile#2801]
When I click on a link to add token to metamask, the popup doesn't open, and sometime the popup open few seconds/minutes later.

_Steps to reproduce the behavior_
1. Go to pancakeSwap for exemple
2. Click on "add to metamask" (from a pool listing for exemple)
4. Wait for the popup to open

iOS 14.6
Metamask 2.4.0

**Comment by benjaminbouwyn** [comment]
It works if I kill the app and add a token from the first open tab, but if I switch tab it doesn't work anymore

**Comment by gantunesr** [comment]
Hey @benjaminbouwyn, is this still an issue in the latest release?

**Comment by gantunesr** [comment]
Dupe of #3722
