### ISSUE TITLE
metamask app webview: ethereum is not defined when access auth()->user property in laravel

### ISSUE THREAD

**Issue by darkwing** [MetaMask/metamask-mobile#2802]
From user @keanwalker:

> Hi, i have developed a web application with laravel. it is working 100% fine in desktop browser with metamask extension. however when i open the web in metamask mobile app webview, ethereum extension will not be injected into my web whenever i access property of auth()->user, such as user name. without accessing it, on JS level ethereum is found.

> I tried few days to find out the reason, but can't find a solution. it is a bug of metamask webview?

https://github.com/MetaMask/metamask-extension/issues/11243

**Comment by ishaaan** [comment]
Hello @kanwalker,

Did you get the solution. We are facing the same issue.

Thank you!

**Comment by keanwalker** [comment]
yes, took me few days to find out. whenever there is a code to retrieve any
properties of auth()->user in page load,  then it happens.

**Comment by ishaaan** [comment]
Hey @keanwlker,
Thanks a lot for your quick response. Please could you elaborate that how did you fix that.
Best regards,
Ishan

**Comment by keanwalker** [comment]
you gotta separate the code in another page. for e.g, access the metamask
via web3 in page without accessing auth user object, neither frontend or
backend.
