### ISSUE TITLE
FAILURE: Build failed with an exception.

### ISSUE THREAD

**Issue by ds2021168** [MetaMask/metamask-mobile#2807]
Failed to generate the APK file.

[root@vultr android]# ./gradlew assembleRelease

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred evaluating project ':app'.
> A problem occurred starting process 'command 'secret-tool''

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s

[root@vultr android]# sentry-cli --version
sentry-cli 1.66.0

This is what causes it?

**Comment by gantunesr** [comment]
Hey @ds2021168, is this happening in the last version of the code? Try cloning the project again and following the updated README
