### ISSUE TITLE
Copy update for sign method error

### ISSUE THREAD

**Issue by omnat** [MetaMask/metamask-mobile#2820]
copy of extension issue: https://github.com/MetaMask/metamask-extension/issues/11337

Out-of-Scope: no need for translations into other languages

**Comment by sethkfman** [comment]
I just wanted to confirm the copy text accepted text. Also, is this for all eth_sign calls or specific to 3074?

Before:

**Comment by sethkfman** [comment]
Updated view with error styling: 
<img width="413" alt="Screen Shot 2021-06-23 at 12 38 14 PM" src="https://user-images.githubusercontent.com/10342624/123150798-000fa780-d420-11eb-9873-f733bd5b21d1.png">

**Comment by cjeria** [comment]
This might be out-of-scope but just noticing the line-height of the error message is a little tight making the message harder to read. We default to 140% in the design system. Let me know if I should create a separate issue for this.

**Comment by sethkfman** [comment]
![Screen Shot 2021-06-24 at 1.04.20 PM.png](https://images.zenhubusercontent.com/602c3c981617aad4ad2160f8/94dc237c-4afd-4e26-a1d6-b67bbd89378a)

I have updated the line spacing to be 140% across all alerts. See example above.

cc: @cjeria
