### ISSUE TITLE
don't show swaps contract address in recent "Recents"

### ISSUE THREAD

**Issue by rickycodes** [MetaMask/metamask-mobile#2822]
**Describe the bug**

Right now when a user performs a swap the swaps contract address gets added to "Recents". this has resulted in quite a few of our users sending funds to the swaps contract address in error. The hypothetical flow is this:

a) user sends funds to their best friend Esteban
b) user then performs a swap
c) user wants to send funds to their best friend again and assumes the first address on recents is their best friend when in fact it's the swaps contract address. they select that address and send
d) user is angry because their funds went to the wrong address.

**Expected behaviour**

We should have a list of addresses (perhaps malicious ones could also be included?) that never get added to "Recents"

**Comment by mobularay** [comment]
@rickycodes  proposed: solution: hide router_swaps contract addresses - this is fine to merge now. 

@omnat to start a thread on Slack to get ppl's feedback on what to do with other contract addresses, for future iteration (could be an EPIC for UX improvement). This could be a cross-product discussion to be aligned with Extension.
