### ISSUE TITLE
what walletconnect request metamask-mobile handles ?

### ISSUE THREAD

**Issue by garyng2000** [MetaMask/metamask-mobile#2824]
walletconnect use the standard jsonrpc protocol but it seems that metamask mobile only handle some of them(mainly the signing related) but can silently ignore all others.

this technically speaking is wrong because jsonrpc specify that if you cannot handle the request, return an error response, not silently ignore it.

I run my bridge server so I can clearly observe that metamask mobile retrieve the request and even acknowledge it(to the bridge server). But then silence.

so is there a list of what function(rpc calls) does metamask-mobile support in the context of walletconnect ?

**Comment by gantunesr** [comment]
Related to #3581
