### ISSUE TITLE
Immediately resolves name as soon as I enter ".eth", but this excludes the ability to enter many names

### ISSUE THREAD

**Issue by brantlymillegan** [MetaMask/metamask-mobile#2830]
**Describe the bug**
When entering an ENS name into a Recipient field, as soon as I enter a possible ENS suffix, e.g. ".eth" or ".xyz", the app immediately resolves the name and doesn't let me keep typing. This is a problem because subdomains exist in ENS. E.g. the name evan.ethereum.eth exists, but when I try to type it in as soon as I get to "evan.eth..." it resolves the name and doesn't let me keep typing. This would also be a problem if I tried to send to "brantly.xyz.eth", the app cuts me off as soon as i typed in "brantly.xyz", even though "brantly.xyz.eth" and "brantly.xyz" are two different names with different owners and records.

**Screenshots**
_If applicable, add screenshots or links to help explain your problem_

**To Reproduce**
_Steps to reproduce the behavior_
1. Go to MetaMask Mobile on Android
2. Tap "Send"
3. Try to type in to the Recipient field the ENS name "evan.ethereum.eth"
4. You'll see that it cuts you off as soon as you type in "evan.eth..."

**Expected behavior**
You should be able to type in any name, and the app should never stop you from typing in more. As you type in, could present possible names below for you to select, but it shouldn't stop you from typing more.

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S21+
 - OS: latest Android
 - App Version: v2.4.0 (746)

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
Could lead to lost funds

- Add stats if available on % of customers impacted
potentially everyone

- Is this visible to all users?
yes

- Is this tech debt?
no, you just have a wrong implementation of ENS

**Comment by sethkfman** [comment]
@omnat I wanted to bring this issue to your attention. Lets discuss early next week. Thx

**Comment by brantlymillegan** [comment]
@sethkfman @ryanml hey, checking in on this too. Has this been fixed? I see the code referenced above, but I still see the problem in my Android app

**Comment by omnat** [comment]
@ryanml @sethkfman is there a PR up for it? we haven't released this code update yet, correct?
