### ISSUE TITLE
Sync Mobile with Extension no exists menu item

### ISSUE THREAD

**Issue by ghRegEdit** [MetaMask/metamask-mobile#2833]
** Please describe the error **
I am trying to sync a wallet with Metamask extension using a QR code

** Screenshots **

** Steps **
1. I click on the extension in the Chrome browser
2. Go to Settings> Advanced> Synchronization with a mobile device
3. I enter the password for the Metamask wallet
4. A QR code is displayed
5. I open the application
6. From the home screen, click the "QR Icon"
7. Scanning the QR code of the Metamask extension
8. The application on the device reports:
8.1 "Error! It looks like you are trying to sync a wallet with the Metamask extension, to do this open" Settings> Advanced> Synchronize with Metamask extension ""
8.2 I go to "Settings> Advanced", but there is no such item in the settings.
** Expected Behavior **
Expect wallets and network settings to sync between extension and device.

** Smartphone (include the following information): **
  - Device: Sony Xperia XA2 +
  - OS: Android 9
  - Extension version (Google Chrome) [9.6.1]
  - Application version (Android) [2.40] Google Play

-------------------------------------------------- -------------------------------------------------- ------------
- How to sync with a mobile device?

**Comment by omnat** [comment]
@ghRegEdit Just to confirm, when you try to scan the QR code on extension with the QR scanner on mobile homescreen, you expect your wallet on extension and wallet to be in sync continuously, correct? 

There is right now no ability to continuously sync between extension & mobile, only at the initial onboarding time when you want to use your extension wallet on mobile.

**Comment by gantunesr** [comment]
Hey @ghRegEdit, I'll close this issue since the mobile sync feature is disabled temporarily due to security concerns
