### ISSUE TITLE
ERC681 URI doesn't change network on iOS mobile app

### ISSUE THREAD

**Issue by rahul-kothari** [MetaMask/metamask-mobile#2836]
**Describe the bug**
[ERC-681](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-681.md) described a network agnostic URI encoded into a QR Code that wallets could scan and set up the payment.

ethereum:0xdf3e18d64bc6a983f673ab319ccae4f1a57c7010@4?value=2900000000000000
This URI should ask the user to send 0.0029 ETH to `0xdf3e18d64bc6a983f673ab319ccae4f1a57c7010` with chain Id = 4 i.e. Rinkeby testnet.

However, after scanning the QR code in metamask, it continues to stay on the same network that I opened it in, thus discounting the chain id parameter.

Here is the QR code for everyone to test:
![eth-rinkeby](https://user-images.githubusercontent.com/35169918/122740669-1b41b200-d27c-11eb-98f0-adaa1ffc8ce9.png)

**Screenshots**
_If applicable, add screenshots or links to help explain your problem_

**To Reproduce**
_Steps to reproduce the behavior_
1. Open the app, say with network as eth-mainnet
2. Click on the button to scan a qr code
3. Scan the qr code which has a URI for a different network (like rinkeby)

**Expected behavior**
Regardless of whichever network metamask was previously in, it should change to the new network based on the chain ID.

If the relevant chain ID isn't on the app's list of configured networks, then throw a relevant error (such as "network not configured")

**Smartphone (please complete the following information):**
 - Device: iPhone 8
 - OS: iOS 14
 - App Version 2.5.0

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by ligi** [comment]
I can confirm this bug also exists on the Android version of MM - kinda dangerous actually.

**Comment by ibrahimtaveras00** [comment]
Sounds identical to https://github.com/MetaMask/metamask-mobile/issues/2557

**Comment by Fatxx** [comment]
Fixed at #3605
