### ISSUE TITLE
Can not show ERC-721 comptatible NFT on NFTs tab

### ISSUE THREAD

**Issue by bafu** [MetaMask/metamask-mobile#2838]
**Describe the bug**
Add an ERC-721 NFT on ThunderCore (an Ethereum-compatible chain) to the MetaMask mobile App, and the NFT's image can not be shown correctly.

**Screenshots**
<img src="https://user-images.githubusercontent.com/292790/122758881-e4938800-d2cb-11eb-9afe-1ffc2ee0e905.jpg" width="50%">

**To Reproduce**
To run the steps to reproduce, please send your Ethereum wallet address to \<bofu AT numbersprotocol.io\>, and I can help mint an NFT for debugging.

1. Go to `Settings -> Networks`
2. Click on `Add Network`
3. Enter the Network information
    * Network Name: `ThunderCore Mainnet`
    * RPC Url: `https://mainnet-rpc.thundercore.com/`
    * Chain ID: `108`
    * Symbol: `TT`
    * Block Explorer URL: `https://viewblock.io/thundercore`
4. Go to `Wallet home -> NFTs tab` 
5. Click on `ADD NFTs`
6. Ether the NFT information
    * Address: `0x59d6fe14e7bfaf7c89c297be301195b96335df0e`
    * ID: `2421`
    * NFT information on [Viewblock](https://viewblock.io/thundercore/address/0x59d6fe14e7bfaf7c89c297be301195b96335df0e?txsType=nft&specific=2421)
        * [Token URI](https://ipfs.io/ipfs/bafybeihvlfoovrv56iouqdhmqo5fozk3m5xpgmepqezsav77guhy55pmee/) (metadata)
7. The NFT image does not show correctly.

**Expected behavior**
ERC-721 compatible NFT should be shown like an NFT on OpenSea.

<img src="https://user-images.githubusercontent.com/292790/122760725-042bb000-d2ce-11eb-81e7-7803679eb049.jpg" width="50%">

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy Z Fold2
 - OS: Android 11
 - App Version: v2.4.0 (746)

**Comment by bafu** [comment]
It seems that MetaMask only supports OpenSea, is it correct?

[NFT tokens in MetaMask wallet](https://metamask.zendesk.com/hc/en-us/articles/360058238591-NFT-tokens-in-MetaMask-wallet)

> We pull data from opensea.io, it's our 3rd party repository for all NFTs. A collectible ID is a unique identifier since no two NFTs are alike. Please try finding the ID with the app where you purchased it.

**Comment by Ronak-59** [comment]
This might be related to issue #2817

**Comment by sethkfman** [comment]
Included in product backlog

**Comment by jtsiskin** [comment]
Is there a reason that opensea was used instead of the tokenURI standard described in https://eips.ethereum.org/EIPS/eip-721? Can we at least fall back to using whats written in the contract when the opensea query fails? (although ideally, it seems like it should be the other way around)

**Comment by gantunesr** [comment]
Solved in #3343
