### ISSUE TITLE
```suggestion

### ISSUE THREAD

**Issue by saifalmea** [MetaMask/metamask-mobile#2842]
```suggestion
  pod 'BigInt'
```

this wasn't required before?

__Originally posted by @vikmeup in https://github.com/trustwallet/TrustSDK-iOS/pull/96#discussion_r634741764__

**Comment by omnat** [comment]
Hi @saifalmea, could you share more information please on what's the issue about? Is this a bug or a feature request?

**Comment by saifalmea** [comment]
BigInt
