### ISSUE TITLE
WatchAsset method: "Add suggested token" prompt doesn't show correct balance

### ISSUE THREAD

**Issue by omnat** [MetaMask/metamask-mobile#2847]
As an example, if your wallet did have non-zero token balance on this token, it'll still show zero.

![image.png](https://images.zenhubusercontent.com/5c18e51bb423df7568ac3781/51ecf713-9416-47df-930d-a12fe443e01a)

**Comment by ibrahimtaveras00** [comment]
For QA reference = https://www.coingecko.com/en/coins/shiba-inu

**Comment by gantunesr** [comment]
Bug related to a case sensitive match between the keys (address) associated with the token balance.

`0x514910771bf9ca656af840dff83e8264ecf123nm != 0x514910771BF9Ca656af840dff83E8264EcF123NM`

Quick fix: Case insensitive key match.
Proposed fix: Keep all address in lower case in controller.

![Simulator Screen Shot - iPhone 11 Pro - 2021-07-04 at 20.09.58.png](https://images.zenhubusercontent.com/60d0d9a2caf077062491ff09/6cdae753-b094-46ec-bffa-2cebd018125e)

**Comment by wachunei** [comment]
Do you know where this comparison is being made? Is it on our end? If so we should [use this function](https://github.com/MetaMask/metamask-mobile/blob/develop/app/util/general.js#L40)

**Comment by gantunesr** [comment]
Yes, it's on mobile but can be fixed on either side. Great! I'll use that function

**Comment by mobularay** [comment]
PR: https://github.com/MetaMask/metamask-mobile/pull/2866

**Comment by gantunesr** [comment]
UPDATE: I'm refactoring the component into a functional one.
