### ISSUE TITLE
[EIP1559] Controllers - Gas controller proposal implementation and tests

### ISSUE THREAD

**Issue by andrepimenta** [MetaMask/metamask-mobile#2851]
This card represents the ongoing process of implementing and improving the controllers for EIP1559

**Comment by andrepimenta** [comment]
We'll need to upgrade to @ethereumjs/tx in web3-provider-engine and anywhere else we might be using it

**Comment by rickycodes** [comment]
here are the other places:

```
  - Hoisted from "web3-provider-engine#ethereumjs-tx"
   - Hoisted from "ethereumjs-block#ethereumjs-tx"
   - Hoisted from "eth-json-rpc-middleware#ethereumjs-tx"
```
