### ISSUE TITLE
only 4 request is handled for walletconnect ?

### ISSUE THREAD

**Issue by garyng2000** [MetaMask/metamask-mobile#2855]
why only these 4 are handled ?

eth_sendTransaction, eth_sign, personal_sign and eth_signTypedData

and not

eth_signTransaction

also, the standard jsonrpc spec said if you don't handle the method, return to say 'not supported' and not silently ignore it !

**Comment by gantunesr** [comment]
Related to #3581

**Comment by gantunesr** [comment]
Hey @garyng2000, PR #3685 addresses this issue. This will be included in v4.2.0
