### ISSUE TITLE
Support for 3rd Party Authentication

### ISSUE THREAD

**Issue by samyoungnyc** [MetaMask/metamask-mobile#2857]
**Describe the bug**
I am working on a Dapp where I want to 'connect' Metamask accounts to Twitter accounts. This means first using `web3/bnc-onboard` to connect a Metamask wallet (this works perfectly). Once the wallet is connected, the user is prompted to authenticate via Twitter (the provider service for this is Firebase). The bug is 

On the front-end dev side I'm using:

Svelte
Firestore (with Twitter authentication)
Metamask (iOS app - opened when 'Connect Wallet' button is clicked)

The basic flow is:
- Users click a button to connect their wallet - which opens the iOS Metamask app browser
- The user connects their Metamask wallet via `web3/bnc-onboard`
- Once they're connected, a modal comes up with a button to 'verify' their Metamask wallet by authenticating Twitter (done via Firebase Authentication).
- The Metamask Browser opens the Twitter login window properly - but it differs from the web version in that it doesn't open in a new window, but rather in the same browser window.
- After entering the Twitter auth is when the bug occurs. The Twitter authentication page goes to a redirect URL provided to Firebase.
- At this point, the browser seems to get stuck on a page with the Firebase redirect address as the URL (i.e my-app.firebasepp.com). There is nothing displayed on this page, it just stays blank.

My guess is that maybe the expected behavior from Firebase's side is the Twitter Authentication is done in a separate browser window. 

**Expected behavior**
I expected that after entering the Twitter credentials, the redirect would go back to the original page after Authentication. 

**Smartphone (please complete the following information):**
 - Device: iPhone XR & iPhone 12 Pro
 - Browsers: Chrome, Brave, Safari 
 - OS: iOS 14.5
 - App Version: Metamask v.2.5.0 (750)

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by SpasiboKojima** [comment]
Seems like no movement on this one for more than a year? I'm stuck with the same issue using Firebase's Google, Facebook and Twitter login. Also there's an error `Unable to establish a connection with the popup. It may have been blocked by the browser.`
