### ISSUE TITLE
WalletConnect nodemodules a lot of bugs using with ReactNative

### ISSUE THREAD

**Issue by chukhlov** [MetaMask/metamask-mobile#2869]
Hello, i was trying to use WalletConnect with React Native app to navigate and connect user from my app into MetaMask app,
I faced with a lot of errors due to age of modules which are used, different boilerplates throwing a lot of errors too, after all errors i made it work, but popup for connection in wallets appears very randomly and it takes a lot of time, sometimes when you press "Connect" button and navigate back to your app, the state of connection is still FALSE and nothing changed, if somebody made it work and have example connecting your React Native app to MetaMask app with creating session, please help me

**Comment by Amazing1974** [comment]
same here!
@chukhlov what package do you use to connect metamask?
I'm using @walletconnect/react-native-dapp.
I also faced with popup randomly show....

**Comment by gantunesr** [comment]
Related to #3583

**Comment by gantunesr** [comment]
Hey @chukhlov @Amazing1974, is this still an issue after 4.2?

**Comment by gantunesr** [comment]
I'll close this issue for the moment, please open a new one if this is still present in the latest release
