### ISSUE TITLE
Unable to send ethereum in IOS app

### ISSUE THREAD

**Issue by DBTech07** [MetaMask/metamask-mobile#2871]
I just recently started having this problem after the last update, when I go to send ethereum I’m allowed to select the account I want to send to, but once I try to select an amount the app switches to this screen and remains stuck.
![D4BDF61E-1179-4566-98DC-84F088C8D5AC](https://user-images.githubusercontent.com/83129769/124657947-c3549f00-de68-11eb-8ecb-97443fe9b23d.png)
![DFA029AB-42C0-4A2B-B87F-65847B4DEE3C](https://user-images.githubusercontent.com/83129769/124657957-c51e6280-de68-11eb-8830-697eaa699153.png)
I’ve tried restarting my phone, airplane mode, uninstalling and reinstalling MetaMask. This is rather frustrating as my ethereum is stuck in this account at the moment

**Comment by gantunesr** [comment]
Hey @DBTech07, is this happening in last release?

**Comment by gantunesr** [comment]
@DBTech07 I was unable to reproduce this issue. Please open a new issue if this is still occurring in the last release
