### ISSUE TITLE
Metamask Mobile cannot process transactions with gas limit outside 20999-7920027 causing an issue for non-Ethereum networks

### ISSUE THREAD

**Issue by Chef-Chungus** [MetaMask/metamask-mobile#2872]
**Describe the bug**
Metamask Mobile cannot process transactions with gas limit outside 20999-7920027
Exact message: "Gas limit must be greater than 20999 and less than 7290027"
As a result on chains other than ETH when using a custom RPC, sometimes this limitation causes issues. 

E.g. Purchasing 80 PancakeSwap lottery tickets throws this error. 
BSC has 60mm block gas limit, ethereum has 14?mm. As such, it does not make sense for this error/restriction/limitation to exist outside of the ethereum networks.

**Screenshots**
![telegram-cloud-photo-size-5-6282878521269399051-y](https://user-images.githubusercontent.com/71833681/124847388-b86b4d00-dfd5-11eb-834c-cba9b3afc97e.jpg)

**To Reproduce**
_Steps to reproduce the behavior_
1. Switch to BSC network on Metamask Mobile
2. Visit pancakeswap.finance/lottery in the browser
3. Purchase 80 lottery tickets in one transaction

**Expected behavior**
There would be no upper (or lower) limit to the transaction gas limit on the wallet side.

**Smartphone (please complete the following information):**
irrelevant.

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by omnat** [comment]
Related #2896
