### ISSUE TITLE
[EIP3326] wallet_switchEthereumChain

### ISSUE THREAD

**Issue by mwamedacen** [MetaMask/metamask-mobile#2913]
Dapp developer should be able to pilot MetaMask mobile app internal chainId via `wallet_switchEthereumChain`.

This has already been handled in MetaMask extension see https://github.com/MetaMask/metamask-extension/blob/a75092762ff656b3e9193f6f8d0874267f64a864/app/scripts/lib/rpc-method-middleware/handlers/switch-ethereum-chain.js

**Comment by TobyKreiselmaier** [comment]
Same here.

**Comment by gantunesr** [comment]
@mwamedacen is this still an issue? MMM supports these methods for the internal browser

**Comment by mwamedacen** [comment]
> @mwamedacen is this still an issue? MMM supports these methods for the internal browser

Nop, thanks for your reactiveness 🙏 
https://github.com/MetaMask/metamask-mobile/blob/b867867767c094b0f7493d058b76a368cc68e82a/CHANGELOG.md#L103
