### ISSUE TITLE
NFTs are no longer autodetected 

### ISSUE THREAD

**Issue by ibrahimtaveras00** [MetaMask/metamask-mobile#2926]
**Describe the bug**

Previously my NFTs were autodetected, now I have to manually add them

**Screenshots**

seen here = https://recordit.co/SdumevqhjI

**To Reproduce**

1. Import a seedphrase that has an NFT
2. while on wallet view, switch to the NFTs tab
3. Notice nothing shows up, you'll have to manually add it

**Expected behavior**

NFT should be autodetected 

**Smartphone (please complete the following information):**
 - App Version 2.6.0

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by sethkfman** [comment]
Controller PR: https://github.com/MetaMask/controllers/pull/536

**Comment by ibrahimtaveras00** [comment]
This was fixed and released = https://github.com/MetaMask/metamask-mobile/blob/develop/CHANGELOG.md#v300---july-28-2021
