### ISSUE TITLE
chainChanged event not getting fired for WalletConnect

### ISSUE THREAD

**Issue by taylorjdawson** [MetaMask/metamask-mobile#2927]
**Describe the bug**
Walletconnect `chainChanged` event not getting triggered when a user switches their network in the MM Mobile app. 

**To Reproduce**
_Steps to reproduce the behavior_
1. On desktop go to [reactdemo.blocknative.com](https://reactdemo.blocknative.com/)
2. Click **Select Wallet** then **Show More** then select WalletConnect
3. Next click **Wallet Checks** the WalletConnect QR code will appear
4. Open MM Mobile and go to your wallet (if you are not there already)
5. Click the QR code button in the top right 
6. Scan the QR code on your screen with the MM mobile app
7. You should then see your address and balance and most importantly the network displayed in the react-demo
8. Now in the MM Mobile app change networks
9. The you'll notice that the network in the react demo won't update
10. Now change your account in the MM Mobile app. You'll notice that the react demo now updates.

Before you jump to conclusions this is not an issue with the react-demo as demonstrated in [this issue](https://github.com/WalletConnect/walletconnect-monorepo/issues/513) in wallet connect

**Expected behavior**
The `chainChained` event should get fired and it does not.

**Smartphone (please complete the following information):**
 - Device: OnePlus 8 Pro
 - OS: Android 11
 - App Version: 2.5.0

I believe these are [these lines](https://github.com/MetaMask/metamask-mobile/blob/194a1858b96b1f88762f8679380b09dda3c8b29e/app/core/WalletConnect.js#L277-L298) where the issue can be found.

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by pROFESOR11** [comment]
We're facing the same issue. `accountsChanged` event works fine, but `chainChanged` event is not getting triggered when user switches network in the MetaMask mobile app. It is quite serious, because we don't want users to sign transactions on an unintended network.

Device: iPhone 6s Plus
OS: 14.4.2
App Version: 3.0.1

**Comment by kayroy247** [comment]
> We're facing the same issue. `accountsChanged` event works fine, but `chainChanged` event is not getting triggered when user switches network in the MetaMask mobile app. It is quite serious, because we don't want users to sign transactions on an unintended network.
> 
> Device: iPhone 6s Plus
> OS: 14.4.2
> App Version: 3.0.1

I am also facing the same issue with Metamask mobile app.

We are also

**Comment by kinggongzilla** [comment]
we're facing the same issue and would really appreciate a fix

**Comment by nicosampler** [comment]
same issue over here

**Comment by nicosampler** [comment]
this problem is becoming more important for dapps supporting L2

**Comment by acrens** [comment]
same issue over here，When will it be solved？

**Comment by jeremiealbert** [comment]
The problem still exists, it makes metamask-mobile unsuitable to be used with WalletConnect. The user can switch network on its mobile without notifying the app and the app can't decide which chain must be used to perform a transaction. So unsafe that this is a killing bug.

**Comment by garrettparris** [comment]
This problem still exists. For what is most likely the most popular portal for walletConnect, makes it hard to build around this issue.

**Comment by gantunesr** [comment]
Related to #3581 & PR #3300

**Comment by moahammadalt** [comment]
Same issue over here

**Comment by eshaben** [comment]
same issue, please fix! 🙏
