### ISSUE TITLE
Signature queueing bug w/ OpenSea

### ISSUE THREAD

**Issue by gantunesr** [MetaMask/metamask-mobile#2967]
### Description
When the app receives multiple transactions requests from a DApp (OpenSea), the app seems to mishandle the transaction and annul them without the user's consent.

Request:
```json
{
    ...,
    "method": "eth_sendTransaction", 
    "origin": "testnets.opensea.io",
    ...
}
```

Response: 
```json
{
    "error": 
        {
            "code": 4001, 
            "message": "User rejected the transaction"
        }, 
        ...
}
```

### Screenshots

https://images.zenhubusercontent.com/141427485/b5c92ce8-cdd2-41a0-8257-74eb9167e1be/opensea_multiple_txs.mov 

### To Reproduce

_OpenSea case:_
1. Go to opensea or testnet.opensea (use Rinkeby Test Network)
2. List the same NFT multiple times
3. Press "Cancel Listings"

### Expected behavior
Modal should show and give the user the option to accept or reject the transactions. 

---

**Notes**

* Component `Approval`  seems to disappear because the transaction was "rejected". This happens because the next transaction will overtake the current one causing the rejection.
* The method `onUnapprovedTransaction` calls an action to toggle the modal (`toggleDappTransactionModal`).
* The current controllers architecture only allows for one transaction to be handled at the moment.
* In conversations with @andrepimenta it was pointed that this development could take a month of work to fix a small issue affecting OpenSea "Cancel Listings" option, where there is a workaround using the "cancel" option for a single sell.

**Comment by gantunesr** [comment]
[Bug reference](https://consensys.slack.com/archives/CN2H44RAM/p1623604957006700)

Check possible relation with:

- [Issue 2855 - only 4 request is handled for walletconnect ?](https://github.com/MetaMask/metamask-mobile/issues/2855)
- [Issue 2824 - what walletconnect request metamask-mobile handles ?](https://github.com/MetaMask/metamask-mobile/issues/2824)

**Comment by mobularay** [comment]
Tagging this with "**technical research**" for Aug 2- Aug 13 sprint. Actual implementation to be planned for Aug 16 - 27 sprint

**Comment by gantunesr** [comment]
This issue is relevant to discuss with the team and maybe invite some engineers from the extension team. This development would required some changes in the controllers architecture to support multiples transactions.

Also, it is important to keep an eye in case it shows up in other dapps, at the moment it seems to only affect OpenSea. We should raise the priority according to the quantity of dapps and users that are affect by this issue.

cc: @omnat @mobularay

**Comment by mobularay** [comment]
Confirmed with @gantunesr @omnat : shelve this for now; Omna to get back to OpenSea to reassess priority

**Comment by gantunesr** [comment]
I'll close this issue for the moment since it's necessary a refactor of the app architecture to solve this issues
