### ISSUE TITLE
Overlapping on send flow confirm view & dapp confirm view when currency != USD

### ISSUE THREAD

**Issue by ibrahimtaveras00** [MetaMask/metamask-mobile#2969]
**Describe the bug**

If a user has their currency set to something other than USD, the estimated gas fee over laps 

**Out of scope**
Swaps section has taken care of this issue

**Screenshots**

![image](https://user-images.githubusercontent.com/41752922/127931526-edf10768-0164-4fb4-a656-b523044ded79.png)

**To Reproduce**

1. Go to settings > general and change currency to something other than USD
2. Go through send flow
3. Once on confirm view, notice how the padding is off

**Expected behavior**

It should be wrapping to two lines

Here are the wrapping mocks if it makes sense to reference. https://www.figma.com/file/NXvUKcZ0Ocu1GPcT7VxRMx/1559-Gas-Controls?node-id=799%3A1572

**Smartphone (please complete the following information):**
 - App Version 3.0.0

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by mobularay** [comment]
Captured as part of MetaMask UX Papercuts backlog by @bschorchit. Product prioritization can happen at that level.
