### ISSUE TITLE
 [Android Specific Issue] tapping hardware back button on metametrics opt-in view takes me back to wallet set up view

### ISSUE THREAD

**Issue by cortisiko** [MetaMask/metamask-mobile#2978]
**Describe the bug**
This happens when you go through the wallet import flow. Basically whenever you tap on the hardware back button while on metametrics opt-in view you are taken back to the wallet set up view.

**Screenshots**
Unfortunately I am unable to provide any screenshots or screen recordings

**To Reproduce**
_Steps to reproduce the behavior_
1. launch a fresh install of the app
2. from the wallet setup view tap on "import using secret recovery phrase wallet"
3. enter your secret recovery phrase then enter a new password
4. tap import 
5. on the metametrics opt-in view tap on the hardware back button.   
6. Notice you are taken back to the create wallet view 

**Expected behavior**
when you tap the hardware back button you should remain on the metametrics opt-in view and you should see the "Heads up" modal

**Smartphone (please complete the following information):**
 - Device: [Samsung Galaxy S8]
 - OS: [android 9]
 - App Version [3.0.1] 

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by gantunesr** [comment]
This issue is no longer relevant in the last release
