### ISSUE TITLE
tapping on the 'X' to dismiss the "MetaMask Support" view does nothing

### ISSUE THREAD

**Issue by cortisiko** [MetaMask/metamask-mobile#2984]
**Describe the bug**
this bug was first introduced here https://github.com/MetaMask/metamask-mobile/issues/1743 and got fixed. This bug has reappeared. The bug is: 

> on the "MetaMask Support" page on iOS there is and X to dismiss that page, but nothing happens when I tap it. I do have the option to dismiss by swiping down (this could be confusing to users)

On iOS Worse case, you can drag down to dismiss but users may not know to do that. On android there is no way to read the MetaMask support view because the **protect your wallet modal** appears and there is no way to dismiss that modal. 

Protect wallet > tap Start > why is it important > learn more
The bug also appears on android as well. 

**Screenshots**
see behavior on [iOS](http://recordit.co/4kZiv9JETo) and [android](http://recordit.co/2jaoUUfBqf)

**To Reproduce**
in order to reproduce though, you need to have a fresh wallet, and send yourself funds to prompt the Sticky Protect your wallet modal 

_Steps to reproduce the behavior_
1. with a fresh install of the app, create a wallet
2. do not back up your seed phrase
3. send funds to yourself
4. after you send funds to yourself, the "protect your wallet" modal should appear. Tap on the protect your wallet CTA
5. tap the "Start" CTA
6. tap the "Why is it important" link
7. from the "protect your wallet modal" tap "learn more"
8. On iOS try tapping on the "x" in the top left corner. Notice nothing happens. Now on android notice you are unable to read the contents of the view. 

**Expected behavior**
A user should be able to close the MetaMask Support view(iOS) and read the contents of MetaMask Support view (android) 

**Smartphone (please complete the following information):**
 - Device: [iPhone Xr and samsung galaxy S8]
 - OS: [iOS 14.7.1 and android 9]
 - App Version [3.0.1]

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by Fatxx** [comment]
@cortisiko

I can't reproduce this on iPhone 11 Pro Max, iOS 15.2.1 in the current main branch (v4.0.0)

**Comment by cortisiko** [comment]
Agreed @Fatxx , I can no longer reproduce this. Feel free to close.
