### ISSUE TITLE
Cannot login…

### ISSUE THREAD

**Issue by yukestar0210** [MetaMask/metamask-mobile#2989]
MM suddenly says Error: cannot unlock without a previous vault.

what should I do for this??

![Uploading 34FE1684-D4C3-40EF-8431-7D2273EFAD7C.png…]()

**Comment by alvarenmeta** [comment]
have samme issue and i think i dont have, 1 oaccount phrase, what can i do??

**Comment by alvarenmeta** [comment]
mi cel is an iphone x

**Comment by alvarenmeta** [comment]
i can not use my phrase because i lost 1 account there

**Comment by omnat** [comment]
@yukestar0210 @alvarenmeta Can you share reproduction steps for this issue please?

**Comment by gantunesr** [comment]
I'm going to close this issue for now. Please open a new one if the error persist.
