### ISSUE TITLE
How to debug metamask mobile on browser console

### ISSUE THREAD

**Issue by kayroy247** [MetaMask/metamask-mobile#2992]
How can the metamask mobile be debugged atleast to veiw the browser console logs through remote debugging this way: https://developer.chrome.com/docs/devtools/remote-debugging/

**Comment by andrekat** [comment]
There is a section on there website: https://docs.metamask.io/guide/mobile-best-practices.html#website-testing-and-debugging

**Comment by Cal-L** [comment]
Closing issue. Please refer to @andrekat comment above.
