### ISSUE TITLE
Get the actual used gas values, as opposed to only the submitted gas values, on the transaction history view

### ISSUE THREAD

**Issue by andrepimenta** [MetaMask/metamask-mobile#2998]
Figma: https://www.figma.com/file/NXvUKcZ0Ocu1GPcT7VxRMx/1559---Gas-Controls?node-id=1849%3A21411

![image.png](https://images.zenhubusercontent.com/5f99d46607474d60b64035d5/6fd2980a-fae2-4ae5-b1c8-a75b4878e3df)

**Comment by gantunesr** [comment]
Solved in #3099
