### ISSUE TITLE
Contract function call with deep link

### ISSUE THREAD

**Issue by Flawe** [MetaMask/metamask-mobile#3000]
Are there any plans to support calling contract functions from a deep link?

**Comment by omnat** [comment]
Hi @Flawe could you please provide more information on this? Is it an issue or feature request? 

What is the scenarios where you need this? What is the current behavior and what behavior do you expect?

**Comment by Flawe** [comment]
Hi @omnat, apologies this should have been a feature request not bug.

Currently you can trigger payments with a deep link, but you can't call a contract function. It would be useful to be able to use a deep link to redirect the user to the meta mask app and immediately request to sign a contract functional call with arbitrary data and a value amount.

**Comment by pearsonkyle** [comment]
I agree, that would be nice

**Comment by gantunesr** [comment]
related to #3582

**Comment by yusufk** [comment]
Are you sure that triggering payments works @Flawe ? I just tried: https://metamask.app.link/send/pay-0xd5838aD056eaD570111b99D465563854cd00e54A@1?value=1e15 and all it does is open the app.

**Comment by Flawe** [comment]
> Are you sure that triggering payments works @Flawe ? I just tried: https://metamask.app.link/send/pay-0xd5838aD056eaD570111b99D465563854cd00e54A@1?value=1e15 and all it does is open the app.

@yusufk I haven't tried, but I assume it open's the app and attempts to sign the payment transaction? That was my understanding. Even if it does the same with a contract call I would take it tbh.

**Comment by Rohit-2602** [comment]
@omnat Hii, I am also trying to call the smart contract function (mintFunction) using Android App but using this -
```
https://metamask.github.io/metamask-deeplinks/#
```
you can only create deep links for ERC-20 token Transfers or ETH transactions. But there is no way to call ERC721 smart contract.

**Comment by peersky** [comment]
Agree, would be killer feature. 

Many dapps could be built without any frontend at all that way.
