### ISSUE TITLE
Window.ethereum not being injected on Android (again?)

### ISSUE THREAD

**Issue by Flawe** [MetaMask/metamask-mobile#3001]
I'm aware of this having been a previous issue, but it still seems to be happening with Android 11 (and I just updated to August 5 security update).

As an example of my implementation, you can check https://tossaneth.com/eth, where pressing the send button uses window.ethereum for the transaction if it exists, otherwise it serves as a deep link to the same url. It works fine on iOS.

**Comment by HaneulChile** [comment]
Did you find the solution?

**Comment by Flawe** [comment]
@HaneulChile Sadly no, I'm looking at WalletConnect as an alternative.

**Comment by tomtomcrypto** [comment]
Still an issue, recommended doc implementation doesn't work at all.

**Comment by Fatxx** [comment]
The reported website is unavailable, please reopen it if the problem still occurs.
