### ISSUE TITLE
Use V4 of eth_signTypedData when using WalletConnect.

### ISSUE THREAD

**Issue by andrepimenta** [MetaMask/metamask-mobile#3008]
We should consider using eth_signTypedData V4 instead of V3 for WalletConnect. 
But we would need to warn developers first and give adequate time to migrate.
For reference: https://github.com/MetaMask/metamask-mobile/pull/2990

**Comment by pauldemarco** [comment]
This kills green field dApps that are trying to utilize the latest v4 spec that has support for nested structs and arrays, which are quite essential. 

To continue moving forward while supporting old versions, the method call should allow for the preferred version to be specified: ‘eth_signTypedData_v4’

Hoping this can be prioritized its a main blocker for my app.

**Comment by pauldemarco** [comment]
PR #3020 Adds a specific handle for eth_signTypedData_v4, so we can support the new version of the spec without requiring any changes for existing dApps.

@andrepimenta

**Comment by omnat** [comment]
@sethkfman do you want to see if this could be reviewed and included in 3.3? else we plan it for next release / 3.4
