### ISSUE TITLE
Showing wrong transaction data

### ISSUE THREAD

**Issue by AndriiKD** [MetaMask/metamask-mobile#3016]
I try to pay with BNB on Binance smart network. I create transaction of "1 BNB". On desktop everything is ok, values are correct
![image](https://user-images.githubusercontent.com/75253740/129363974-b04995e8-291f-4c8a-9d50-ae1ecab63d90.png)

[_Data_](https://docs.metamask.io/guide/sending-transactions.html#data-semi-optional) param that was used : 0xa9059cbb00000000000000000000000001be34a35947432de8ddb1a8bcd9964f293f7da90000000000000000000000000000000000000000000000000de0b6b3a7640000

For same _data_ param on mobile( same amount to send, same receiver, same smart contract) I have issue -  amount and token name are wrong:

![image](https://user-images.githubusercontent.com/75253740/129363998-a5c755fc-0485-43e6-a8f6-8a4987634c6b.png)
![image](https://user-images.githubusercontent.com/75253740/129364024-926c49df-7991-4c1e-923f-b9b1d899b934.png)

Probably problem is in decoding ABI string that I pass to _data_
I use web3.js to encode this string
Code is following
`var tokenContract = new web3.eth.Contract(contractAbi,contractId);`
 `data = tokenContract.methods.transfer(receiverAdress, amount).encodeABI()` 

Also I tried to pay with CAKE  token - data on mobile was correct

**Expected behavior**
I expect to see "1 BNB" in mobile popup

**Smartphone:**
 - Device: Xiaomi
 - OS: Android 10, MIUI 12
 - App Version 2.6.0(755)

**Comment by llioor** [comment]
+1

**Comment by andrepimenta** [comment]
Duplicated of #2744. Working on it.
