### ISSUE TITLE
Analytics: Wallet Setup, Security, Onboarding and Sync with extension

### ISSUE THREAD

**Issue by wachunei** [MetaMask/metamask-mobile#3019]
#### Analytics:
- [x] Add onboarding analytics events
- [x] Add wallet setup analytics events (create, import)
- [x] Add sync with extension analytics event

#### Navigation Flows:
- [x] Move MetaMetrics opt-in at the beginning of Create Wallet flow
- [x] Move MetaMetrics opt-in at the beginning of Import Wallet flow
- [x] **Move MetaMetrics opt-in at the beginning of Scan QR code flow and convert modal to a full screen view**

#### To do: **Move MetaMetrics opt-in at the beginning of Scan QR code flow and convert modal to a full screen view**

Figma link: https://www.figma.com/file/veJbq3vpAbWXUJKoixZsdL/Sync-with-desktop
<img src="https://images.zenhubusercontent.com/5f9993a07851dda5331c8fd2/22b6e58f-bd7c-4891-ba72-4b88918a4d7e" width="300" />

User should click on any of these three buttons and get the metametrics screen before continuing the flow
![Screen Shot 2021-08-13 at 14.04.38.png](https://images.zenhubusercontent.com/5f9993a07851dda5331c8fd2/6f623177-1c11-4b92-950a-a35241d7439a)

**Comment by mobularay** [comment]
Currently, the metametrics screen is a popup modal in Mobile; design to change this to full-screen is done (see screenshots from @cjeria ). Now development needs to be done.

**Comment by mobularay** [comment]
**Estimation:** 
Development = 5 including using Typescript; 
QA needs to test all the flows = 3

@omnat needs to confirm that QA for MixPanel section is Lorenzo

**Comment by cortisiko** [comment]
bug for whoever takes this ticket. 

the bug:

when i import my account using SRP I do not see the congratulations view with confetti
see the behavior [here](http://g.recordit.co/aaCK8tAciW.gif) compared to the behavior when I [sync with extension](http://g.recordit.co/RiDfovtgnO.gif)

expected behavior: 
the user should see the congratulations view with confetti after the import wallet was successful

cc @omnat

**Comment by omnat** [comment]
@Cal-L @cortisiko 
Can you please message on Slack mobile channel and tag Lorenzo when these analytic events are ready to be QA'd on mixpanel = he can help ensure that we are capturing the events correctly (as expected) on MixPanel.

**Comment by gantunesr** [comment]
Lorenzo pointed out that the event "Opt In" is getting triggered twice in the app, but I didn't see it in the code. cc @wachunei  @Cal-L 

![Screen Shot 2021-09-14 at 22.05.24.png](https://images.zenhubusercontent.com/60d0d9a2caf077062491ff09/54e728bc-d3a5-4ca8-8a59-da9ca99571d2)
