### ISSUE TITLE
I found wallet_switchEthereumChain and wallet_addEthereumChain are not work in my iphone!!!

### ISSUE THREAD

**Issue by KBKUN024** [MetaMask/metamask-mobile#3021]
**Describe the bug**
I can use wallet_switchEthereumChain and wallet_addEthereumChain **normally in mac**,but when I use the browser which is belong to metamask,then click switch button,there are no confirmation of switch network and add network

**Screenshots**
<img width="229" alt="截屏2021-08-14 16 46 05" src="https://user-images.githubusercontent.com/54589019/129440658-857849ac-5b1d-4763-9b52-8f92d379541d.png">
_when I click the button in mac:_
<img width="1754" alt="截屏2021-08-14 16 57 14" src="https://user-images.githubusercontent.com/54589019/129440749-b1886cbf-aad1-48cf-9888-e6ac13c18c75.png">
you can see the confirmation normally.
but when I click the button in my iphone,there is nothing to react,I don't know why

**To Reproduce**
_Steps to reproduce the behavior_
1. click the button in mac,reaction is normal
2. click the button in iphone,there is nothing to react

**Expected behavior**
the expected reaction is like:
![IMG_8686](https://user-images.githubusercontent.com/54589019/129440891-7a4c9397-0baa-4609-b325-85030472045e.PNG)

**Smartphone (please complete the following information):**
 - Device: iphone XR
 - OS: ios 14.4
 - App Version:v3.0.1(766)

my project is based on vue,I use my iphone to access "http://192.168.2.196:8081"(equals to localhost).Recently my project manager wants to access my project in smartphone,but this bug make me so confused so that I can not make it.
I need help!!!!!!!!!!!!!!!!!!!

**Comment by KBKUN024** [comment]
my source code:
`try {
        if (
          this.$refs.fromNet.innerHTML == "Heco Network" &&
          parseInt(await ethereum.request({ method: "eth_chainId" }), 16) == 21
        ) {
          await ethereum.request({
            method: "wallet_switchEthereumChain",
            params: [{ chainId: "0x80" }],
          });
        } else if (
          this.$refs.fromNet.innerHTML == "Cortex Network" &&
          parseInt(await ethereum.request({ method: "eth_chainId" }), 16) == 128
        ) {
          await ethereum.request({
            method: "wallet_switchEthereumChain",
            params: [{ chainId: "0x15" }],
          });
        }
      } catch (switchError) {
        // This error code indicates that the chain has not been added to MetaMask.
        this.errorCode = switchError.code;
        console.log(this.errorCode);
        if (switchError.code === 4902) {
          if (this.$refs.fromNet.innerHTML == "Cortex Network") {
            await ethereum.request({
              method: "wallet_addEthereumChain",
              params: [
                {
                  chainId: "0x15",
                  rpcUrls: [this.netInfo[1].rpcUrl],
                  blockExplorerUrls: [this.netInfo[1].blockExplorer],
                  nativeCurrency: {
                    name: "cortexToken",
                    symbol: "CTXC",
                    decimals: 18,
                  },
                  chainName: "Cortex",
                },
              ],
            });
          } else if (this.$refs.fromNet.innerHTML == "Heco Network") {
            await ethereum.request({
              method: "wallet_addEthereumChain",
              params: [
                {
                  chainId: "0x80",
                  rpcUrls: [this.netInfo[0].rpcUrl],
                  blockExplorerUrls: [this.netInfo[0].blockExplorer],
                  nativeCurrency: {
                    name: "hecoToken",
                    symbol: "HECO",
                    decimals: 18,
                  },
                  chainName: "Heco Mainnet",
                },
              ],
            });
          }
        }
      }`

**Comment by KBKUN024** [comment]
my source code:
<img width="746" alt="截屏2021-08-14 17 13 06" src="https://user-images.githubusercontent.com/54589019/129441143-ec556f97-4584-49aa-b9cd-702aa189087d.png">
<img width="734" alt="截屏2021-08-14 17 13 30" src="https://user-images.githubusercontent.com/54589019/129441147-77e535ef-1beb-4099-9cc9-15cbea04e7d4.png">
<img width="721" alt="截屏2021-08-14 17 13 41" src="https://user-images.githubusercontent.com/54589019/129441151-cce61474-6ba9-4c5a-be18-e2b60ab5f272.png">

**Comment by andrepimenta** [comment]
We are adding support for `wallet_switchEthereumChain` here #2944. But `wallet_addEthereumChain` should already work.

**Comment by omnat** [comment]
Closed to de-duplicate, same issue as #2944, which will be resolved in an upcoming release

**Comment by KBKUN024** [comment]
> Closed to de-duplicate, same issue as #2944, which will be resolved in an upcoming release

You means that in an upcoming release metamask will fix my question,right?

**Comment by sethkfman** [comment]
@KBKUN024 That is correct. The release v3.3.0 rolling out this week will address your issue.

**Comment by KBKUN024** [comment]
Oh！That is great！Thank you for your release！



发自我的iPhone


------------------ Original ------------------
From: sethkfman ***@***.***&gt;
Date: Tue,Sep 14,2021 10:46 PM
To: MetaMask/metamask-mobile ***@***.***&gt;
Cc: KBKUN024 ***@***.***&gt;, Mention ***@***.***&gt;
Subject: Re: [MetaMask/metamask-mobile] I found wallet_switchEthereumChain and wallet_addEthereumChain are not work in my iphone!!! (#3021)

**Comment by seungjoonrim** [comment]
also not working on android for me, any fixes?

**Comment by qieman** [comment]
sufferring same issue

**Comment by michaelvogt** [comment]
Hit this problem also on Android.

**Comment by farruhsydykov** [comment]
Still no solution on android
