### ISSUE TITLE
eth_sendTransaction different behavior on Smartphone than on desktop browser

### ISSUE THREAD

**Issue by andrekat** [MetaMask/metamask-mobile#3022]
Hey!

I am sending a transaction to call a method of a smart contract. The code is working fine on my desktop, where he sends the transaction to the contract address (as specified in the "to" field). However … on my phone or in the MetaMask app itself, it tries to deploy a contract and therfore the transaction fails?!

This is the code I am using to send the transaction (using “request”)

.request({
method: "eth_sendTransaction",
params: [{
"from": "VALIDADDRESS",
"to": "CONTRACTADDRESS",
"data": "HASH_OF_INVOKED_METHOD_SIGNATURE_AND_ENCODED_PARAMETERS"
}]

Transaction sent through MetaMask Mobile:
![image](https://user-images.githubusercontent.com/16321203/129461150-ff755a99-3827-4a77-a1fe-58ed6564970f.png)

Transaction sent through MetaMask Desktop Extension (works as expected)
![image](https://user-images.githubusercontent.com/16321203/129461160-80b7129d-67de-4747-82ad-49fac71e4f76.png)

What is going on here? Did i miss something?

**Expected behavior**
Same behavior on smartphone as on desktop

**Smartphone (please complete the following information):**
 - Device: IPhone 12 Pro Max
 - OS: iOS 14.6
 - App Version: v.3.0.1 (didn't work in previous version as well)

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by AndriiKD** [comment]
https://github.com/MetaMask/metamask-mobile/issues/3016

**Comment by andrekat** [comment]
To overcome this issue right now: 

1) Use the approve() function of an BEP-20 / ERC-20 - this does somehow work on phone (app) and desktop browser 

2) Use transferFrom() on the server side

**Comment by andrepimenta** [comment]
Related to #2744. Working on it.
