### ISSUE TITLE
NFTs no longer in account still display in-app under NFTs section

### ISSUE THREAD

**Issue by dpazdan** [MetaMask/metamask-mobile#3033]
**Describe the bug**
NFTs that are no longer in the account are still showing in-app.

**To Reproduce**
_Steps to reproduce the behavior_
1. Own an nft
2. See it under NFTs on MMM
3. Send NFT or Sell it
4. Come back and see it is still in MMM (even though it is confirmed sent elsewhere.  Can come back days later and it will still show, not just temporarily.

**Expected behavior**
App refresh should update the correct list of NFTs the user owns

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by omnat** [comment]
Possible cause is cache

**Comment by gantunesr** [comment]
Check #3444
