### ISSUE TITLE
switchEthereumChain RPC call results in -32601 error code

### ISSUE THREAD

**Issue by davidcallanan** [MetaMask/metamask-mobile#3035]
**Describe the bug**

This bug occurs on my android mobile device, but not on my windows 10 laptop.

When I call the `wallet_switchEthereumChain` RPC procedure, it results in the -32601 error code.

However, switching chain seems to work fine on another website such as QuickSwap.

**To Reproduce**

```
try {
	await ethereum.request({
		method: "wallet_switchEthereumChain",
		params: [{ chainId: "0x89" }],
	});
} catch(error) {
	console.log(error);
}
```

The above request results in the following error:

```
{
  "code": -32601,
  "message": "The method wallet_switchEthereumChain does not exist/is not available",
}
```

Is this RPC call not supported? I believe it is supported, because the QuickSwap website is successfully switching chain on mobile.

The above call may result in an error if the chain has not already been added. But this error code should be `4902`, right? So maybe the incorrect error code is getting returned?

**Expected behavior**

One of the following:

- If the chain has not yet been added, return error code `4902`.
- If the chain has been added, show dialog to switch chain.

**Smartphone (please complete the following information):**
 - Device: Sony Xperia L4
 - OS: Android
 - App Version: v3.0.1 (766)

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by j05u3** [comment]
Same happens to me, how did you ended up solving it?

**Comment by davidcallanan** [comment]
@j05u3 The way I managed to get it work is that if there is an error when switching chain, I instead register the chain:

```
await ethereum.request({
    method: "wallet_addEthereumChain",
    ...
});
```

If this fails, I then try to `switchEthereumChain` again.

The only time I give up is when the error code is `-32002` which means that there is already a request pending on MetaMask and the user has to manually open the MetaMask UI to accept it. This happens when a user minimizes a popup without accepting or cancelling it, which unfortunately persists even on page reloads.

**Comment by j05u3** [comment]
Thanks, sorry for not updating here, I ended up doing this:

```
    try {
      // TODO: it would be great to check if the nework is installed already
      // (without trying to change), so we can explain better to the user 
      // (I mean: 
      // In case the wallet has the network installed just say
      // "Switch network" instead of "Add and switch network")
      // maybe look here: https://metamask.github.io/api-playground/api-documentation/
      // but I don't think it is a priority for now

      // check if the chain to connect to is installed
      await ethereum.request({
        method: 'wallet_switchEthereumChain',
        params: [{
          chainId:
            chainParameters.chainId
        }], // chainId must be in hexadecimal numbers
      });

      return true;

    } catch (switchErrorCaught) {
      const switchError = switchErrorCaught as any;

      // in case of network not added to wallet yet
      if (checkForUnrecognizedOrNotAddedNetwork(switchError)) {
        try {

          await ethereum.request({
            method: 'wallet_addEthereumChain', // this also switches to that network after adding it
            // if the user adds the network but rejects the switch to it, then 
            // this doesnt throw any error 
            params: [
              chainParameters,
            ],
          });
          // console.log("finished adding network"); // shows always after adding & switching (or rejecting switching)
          
          // making sure the user actually changed to the network requested
          const checkResult = await checkCurrentNetwork(chainParameters);
          if (checkResult === true) return true;
          return false;

        } catch (addError) {
          const addErrorAny = addError as any;
          if (addErrorAny.code === 4001) { // user rejected
            ;
          } else { // other
            Sentry.captureException(addError);
            alert("Error while adding network " + chainParameters.chainName + " 🙀");
          }
        }
      } else if (switchError.code === 4001) { // user rejected
        ;
      } else {
        Sentry.captureException(switchError);
        alert("🙀 Error while switching to network: " + chainParameters.chainName 
        + ". If you are on mobile check that your Metamask app is updated (must be at least the version 3.3.0)");
      }
    }
```

With the recognition function being:
```
function checkForUnrecognizedOrNotAddedNetwork(switchError: any) {
  console.log(switchError);
  // This error code indicates that the chain has not been added to MetaMask
  // if it is not, then install it into the user MetaMask
  if (switchError.code === 4902) {
    return true;
  }

  const message = (switchError.message as string) ?? "";
  const testString = "Unrecognized chain ID";
  if (message.toLowerCase().includes(testString.toLowerCase())) {
    return true;
  }

  return false;
}
```

**Comment by gantunesr** [comment]
Related to #3581
