### ISSUE TITLE
Gas Fee required on IOS when working with Layer 2 Networks but not on Android

### ISSUE THREAD

**Issue by runlinnn** [MetaMask/metamask-mobile#3039]
I had deployed a smart contract on the Layer 2 custom network which was set to be gas-less for all transactions. However, when testing out the smart contract interactions on our Dapp using the MetaMask mobile browser for both the iOS and Android version, the transactions on iOS requires a gas fee while the transactions are able to go through on Android with no gas fee required. 

**Expected behavior**

<img width="167" alt="Picture1" src="https://user-images.githubusercontent.com/68192954/130161723-afbbfce6-84c9-4124-84be-d8e8cbd92bdb.png">

Here is a screenshot of the MetaMask confirmation pop up on Andriod. No gas fee is required for the transaction to go through on the private blockchain. This is the expected behavior.

<img width="167" alt="Picture3" src="https://user-images.githubusercontent.com/68192954/130161970-70e13b6d-08a9-4b49-9a58-12759de5528c.png">

<img width="167" alt="Picture4" src="https://user-images.githubusercontent.com/68192954/130161971-442a2657-7446-4c7a-813a-b9cf1857a4b7.png">

Here is a screenshot of the MetaMask confirmation pop up on iOS. The transaction is unable to go through because of gas fee requirements. However, the expected behaviour should have been the same as the Andriod version.

**To Reproduce**
The window.ethereum provider in the MetaMask mobile app browser is converted it to a ether.js provider via ethers.providers.JsonRpcProvider(). Then a custom RPC network is used since the Dapp should be connected to a private blockchain.

**Smartphone**
OS: 14.4, MetaMask: v 3.0.1
Android: 11, MetaMask: v 3.0.1

This issue only affects the iOS version of Metamask Mobile. We have tried with multiple iOS phones, all of which face the same issue.

**Comment by andrepimenta** [comment]
Thank you for posting this issue. Could you post the parameters that you are passing to the transaction?

**Comment by runlinnn** [comment]
Hi, I'm not sure what you mean by the parameters passed to the transaction? The smart contract method for this transaction does not take in any parameters.

**Comment by gantunesr** [comment]
cc @Fatxx
