### ISSUE TITLE
MSAL Library working incorrectly with Android Metamask Mobile Browser

### ISSUE THREAD

**Issue by dojh111** [MetaMask/metamask-mobile#3041]
Currently, we are developing a blockchain dapp with the react library and node. As authentication is required, we are using Azure AD and the MSAL library to satisfy these needs.

After releasing our dapp, we ran into the issue where the MSAL redirects do not work after the user clicks on the 'sign in' button, and as such, authentication can not be completed.

This issue **only** affects the Android version of Metamask Mobile. We have tried it on the ios version of metamask mobile, and everything works as expected. The application works on native Android browsers also, and only breaks when run on the Android Metamask mobile browser. We have also tried with multiple Android phones, all of which face the same issue.

**To Reproduce**
As this bug happens when integrated with Azure AD, the MSAL library is required.
_Steps to reproduce the behavior_
1. Setup an Azure AD B2C tenant
2. Register an application and a sign in user flow
3. Install the `PublicClientApplication` from the `@azure/msal-browser` npm package
4. Call `loginRedirect` function

**Expected behavior**
After inputting the user's username, password and clicking on the 'sign in' button, the application should proceed with redirects and end up on the specified redirect url

**Smartphone (please complete the following information):**
 - OS: Android 11
 - App Version: Metamask v3.0.1

**Comment by schoolex** [comment]
Hi i am working on a dApp that requires the use of MSAL library for authentication and I am currently facing the same problems. I have updated my Metamask android app to v3.3 but it still does not work.

**Smartphone (please complete the following information):**
OS: Android 11
App Version: Metamask v3.3.0
