### ISSUE TITLE
I found a contract method cannot work well in metamask mobile,but I use it normally in mac.

### ISSUE THREAD

**Issue by KBKUN024** [MetaMask/metamask-mobile#3048]
**Describe the bug**

> I think this is a bug,when I use a contract method(this method was written by workmate) in mm mobile cannot work well,but it can work well in mac.Also when I use another wallet app like 'tokenpocket',the method can work in tokenpocket well.So I want to know the reason.

> In my page,there is a  '**deposit**'  button,when I click it,there will appear two consequences which are picture1 and picture2. Why the same button was clicked but consequences are so different? And if I click the '**deposit**' button,sometimes is picture1 sometimes is picture2,I'm really confused.

> You can see the picture1,in right bottom corner there is a 'confirm' button,now I can click it,because it's not turn into gray.But in picture2 it turns into gray,I cannot click it.And above '0 HECO' there shows '未知方法',it means 'UNKNOWN FUNCTION'

> In addition,the method in 'deposit' button is a contract method,which is written by my workmate,it was used to deposit token between two different chains,because my project is a cross bridge.

**Screenshots**
<img width="331" alt="Snipaste_2021-08-25_10-44-51" src="https://user-images.githubusercontent.com/54589019/130717920-7eea03a8-2ba5-42db-8b97-5fe93f8e0baf.png">
<img width="395" alt="Snipaste_2021-08-25_10-47-31" src="https://user-images.githubusercontent.com/54589019/130718148-0f69e235-ee83-4d82-b94d-4ef48eb049fc.png">
<img width="398" alt="Snipaste_2021-08-25_10-49-07" src="https://user-images.githubusercontent.com/54589019/130718268-4436eeca-5b7c-4659-b5df-f8ad99133d67.png">

**To Reproduce**
_Steps to reproduce the behavior_
1.click 'deposit'
2.sometimes 'confirm' button is avaliable
3.sometimes 'confirm' button is not avaliable,and top of the notification will show 'UNKNOWN FUNCTION'

**Smartphone (please complete the following information):**
 - Device: iphone XR
 - OS: iOS 14.4
 - App Version:v3.1.0(770)

**Comment by KBKUN024** [comment]
@Erik Marks

**Comment by KBKUN024** [comment]
@jknoll

**Comment by KBKUN024** [comment]
please help

**Comment by gantunesr** [comment]
Solved in #3481.

Reach out if the issue persists.
