### ISSUE TITLE
Unable to transfer BEP-20 token - Internal JSON-RPC error

### ISSUE THREAD

**Issue by MHG1990** [MetaMask/metamask-mobile#3049]
**Describe the bug**
I am trying to perform a transaction which transfer some amount of BEP-20 token (Like USDC) from one account to another using Metamask mobile via WalletConnect.

When I want to confirm the transaction on the mobile, I am getting the following error (on both BSC main net & test net): 
Transaction error Internal JSON-RPC error.

I tried to increase the estimated gas fee, then the transaction went through, but it tired to create a contract! below is a transaction log from BSC explorer:
https://bscscan.com/tx/0xd46d5499e4253132cd1961042b02a02d9bad71725f1441c6f90ef678cf155c21

Note : I tried to submit the same transaction using MathWallet, and it worked fine.

**Screenshots**
before confirming the transaction : https://ibb.co/HCLjZq9
after confirming the transaction : https://ibb.co/nrp0Xtq

**To Reproduce**
please find below the source code I am using to prepare the transaction before submitting it via WalletConnect connector:

> import QRCodeModal from "@walletconnect/qrcode-modal";
import WalletConnect from "@walletconnect/client";
import Web3EthAbi  from 'web3-eth-abi';
connector = new WalletConnect(
{
      bridge: "https://bridge.walletconnect.org", // Required
      qrcodeModal: QRCodeModal,
 });
if (!connector.connected)
{
      connector.createSession();
}
const encodedFunctionCall = Web3EthAbi.encodeFunctionCall(
{
  name: 'transfer',
  inputs: [{
	  type: 'address',
	  name: 'dst'
  },{
	  type: 'uint256',
	  name: 'rawAmount'
  }]
}, ['0xED46B7bf3BB944dcB1245BA21A4D496006044340', '1000000000000000000']);
console.log(encodedFunctionCall);
if (connector.connected)
    {
      // Draft transaction
      const tx = {
        from: "0xbfF89Fe7598f162ACC86CfC3267Eb132F69B7e2B", // Required
        to: "0x8AC76a51cc950d9822D68b83fE1Ad97B32Cd580d", // Required (for non contract deployments)
        data: encodedFunctionCall, // Required
        value: "0x00", // Optional
      };
      // Send transaction
      connector
        .sendTransaction(tx)
        .then((result) => {
          // Returns transaction id (hash)
          console.log(result);
        })
        .catch((error) => {
          // Error returned when rejected
          console.error(error);
        });
    }
    else
    {
      console.log("--------------- not connected ------------------");
    }

Please note that **0x8AC76a51cc950d9822D68b83fE1Ad97B32Cd580d** is the address of USDC on BSC main net.

**Smartphone:**
 - Device: Mate 20 Pro
 - OS: Android 10
 - App Version: v3.1.0 (770)

-------------------------------------------------------------

**Comment by TheStarBoys** [comment]
There is a probably available solution that getting gas and gasPrice by using `ethers` or `web3` and filling it instead of hardcode.

**Comment by aisthetes** [comment]
Same on iOS 15.1.1, MetaMask v3.7.0 (795). If you add the token manually, then there is no error.
