### ISSUE TITLE
Android app does not auto lock.

### ISSUE THREAD

**Issue by MicahZoltu** [MetaMask/metamask-mobile#3073]
**Describe the bug**
Auto-lock setting is "After 5 minutes", with biometrics and PIN disabled.  However, after leaving the app closed for multiple days in a row, upon opening the app it automatically logged in.

**To Reproduce**
_Steps to reproduce the behavior_
1. Login to MetaMask.
2. Set auto-lock to 5 minutes.
3. Press home button.
4. Wait more than 5 minutes.
5. Open MetaMask.
6. Notice that you weren't prompted to login.

**Expected behavior**
MetaMask correctly locks after 5 minutes of inactivity.

**Smartphone (please complete the following information):**
 - Device: Android
 - OS: 9
 - App Version: v3.1.0

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by MicahZoltu** [comment]
I have a sneaking suspicion the issue is that the "Remember Me" toggle on the login page may be completely overriding the auto-lock timeout in security settings.

1. A single toggle that someone may accidentally set should not override an explicitly set security setting.
2. "Remember Me" is quite vague and for an end user like me I don't know what it does, but I don't expect it to override my explicitly set security settings.
3. Remember Me feels like it should make it so the app doesn't logout on close, but still respects auto-lock settings (if you exit the app on Android without setting remember me you have to login on next launch even if it is within your auto-lock timeout).

----

On a related note, MetaMask should display a persistent notification when it is unlocked in the notification bar the same as other high security applications like Signal.  The notification should have a button for "logout".

**Comment by plasmacorral** [comment]
Observed on pixel 4a on Android 12 with the January 2022 security update, running wallet v3.8.0.  As @MicahZoltu suggested, it does seem to be related to "Remember me" being enabled.
