### ISSUE TITLE
You have to press the login button twice.

### ISSUE THREAD

**Issue by MicahZoltu** [MetaMask/metamask-mobile#3074]
**Describe the bug**
On the login page, if the cursor is in the password entry box the "LOG IN" button doesn't work.  You have to first get the cursor out of the password entry box before you can press the LOG IN button.

**To Reproduce**
_Steps to reproduce the behavior_
1. Open MetaMask Mobile on Android.
2. Enter a password.
3. Touch LOG IN button.
4. Notice that nothing visible happens other than the cursor stops flashing in the password entry box.
5. Touch LOG IN button again.
6. Notice that you now log in.

**Expected behavior**
Upon entering my password, I can touch the log in button once and log in.

**Smartphone (please complete the following information):**
 - Device: Android
 - OS: 9
 - App Version: 3.1.0 (770)

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by MicahZoltu** [comment]
Note: In step 3 you can touch *anywhere* other than the password entry box to clear the cursor, which will make the login button work.  Inversely, after touching the login button the first time if you touch the password entry box again to put the focus back on it, the log in button will once again not work.

**Comment by amcareem** [comment]
I have experienced the same problem before.
In my case I had just used the redirect link without the "www". Which means In one area it is mentioned http://www.mytestedwebsite/ and the other as  http://mytestedwebsite

Not sure whether this will help or not. But I would say to check the web link.


GOOD LUCK!!!
