### ISSUE TITLE
Lost connection to "MetaMask RpcProvider"

### ISSUE THREAD

**Issue by Velenir** [MetaMask/metamask-mobile#3076]
**Describe the bug**
_A clear and concise description of what the bug is_
When changing network (whether manually or via `wallet_addEthereumChain` rpc method ), the app reloads the page (even if `ethereum.autoRefreshOnNetworkChange=false`) and breaks with `Lost connection to "MetaMask RpcProvider"` (which I see when debugging through chrome://inspect in Android emulator, production app doesn't show anything)

**Screenshots**
_If applicable, add screenshots or links to help explain your problem_

![MMask-lostConnectionOnNetworkSwitch](https://user-images.githubusercontent.com/5121491/131363681-097a2733-1908-46e0-8c3c-bc86accc3c24.png)

https://user-images.githubusercontent.com/5121491/131635236-3f9f4119-67d9-4bfc-aa52-72a125d59198.mp4

https://user-images.githubusercontent.com/5121491/131364023-5c5b6ca8-6a12-4d91-8cef-981ab3cd24f1.mp4

https://user-images.githubusercontent.com/5121491/131364438-54fce083-6689-49b1-b619-339a5ff76ecb.mp4

**To Reproduce**
_Steps to reproduce the behavior_
1. Go to any dapp that supports multiple networks, for example [app.uniswap.org](https://app.uniswap.org/#/swap), [web3modal.com](https://web3modal.com) or [paraswap.io](https://paraswap.io/)
2. Connect on one network
3. Go to Wallet, change to another supported network
4. Go back to the app in Browser
5. The app either doesn't work at all (blank screen on Uniswap) or can't connect (web3modal and paraswap.io) 
6. After manual page reload -- works again

**Expected behavior**
_A clear and concise description of what you expected to happen_
No errors. Working after network switch (would be even nicer without page reload)

**Smartphone (please complete the following information):**
 - Device: Redmi Note 4, Lenovo - TBX704L
 - OS: Android 7(phone & tablet), Android 10 (Emulator)
 - App Version -- v3.1.0 (770)

Btw, where can I get variables to fill in `*.env` files? For debugging locally

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by pkhodaveissi** [comment]
Facing the same problem on 

-- Android, Metamask ver:3.1.0 (770), android ver:10
-- iOS, Metamask ver: 2.5.0 (750), but rarely happens with iOS

**Comment by 4skinSkywalker** [comment]
Same problem here in my dapp: [https://github.com/MetaMask/metamask-mobile/issues/3309](https://github.com/MetaMask/metamask-mobile/issues/3309)

**Comment by JSjump** [comment]
大佬最后怎么解决的？
