### ISSUE TITLE
On switching account, network - the browser (and site) doesn't update right away

### ISSUE THREAD

**Issue by omnat** [MetaMask/metamask-mobile#3078]
### Situation
Using a site in the in-app browser

### Action (s) that lead to the issue
Respond to a connect request or switch account or switch network

### Expected behavior
The action made on MetaMask should be reflected immediately in the site

### Buggy behavior
No response is reflected on the site / browser. You have to manually refresh (if you figure it out) for the change to be reflected.

**Comment by omnat** [comment]
Possibly related, issue with Connect prompt not showing up (web3 wallet not detected) https://consensys.slack.com/archives/GBW7S9FSN/p1630692726173400
cc @andrepimenta

**Comment by andrepimenta** [comment]
Regarding Omna's comment:
The reason why this is not working is because that part of etherscan is inside an iframe and the mobile app doesn’t support injecting web3 into iframes because there is no way of securely communicating with iframes yet
