### ISSUE TITLE
Error: PollingBlockTracker

### ISSUE THREAD

**Issue by shieldwallets** [MetaMask/metamask-mobile#3082]
ERROR    [Error: PollingBlockTracker - encountered an error while attempting to update latest block:
construct@[native code]
Wrapper@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:9435:64
construct@[native code]

_createSuperInternal@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:263169:406
EthereumRpcError@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:263193:26
getEthJsonRpcError@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:263117:78
internal@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:263043:34
createInternalError@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:263670:83
performFetch$@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:263598:38
tryCatch@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:10303:23
invoke@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:10476:32
tryCatch@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:10303:23
invoke@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:10376:30
http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:10386:21
tryCallOne@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:27417:16
http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:27518:27
_callTimer@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:31631:17
_callImmediatesPass@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:31670:17
callImmediates@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:31888:33
__callImmediates@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:7855:35
http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:7640:34
__guard@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:7838:15
flushedQueue@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:7639:21

![meta](https://user-images.githubusercontent.com/88810693/131548835-ed9179f7-23f3-4416-aa00-6c53e64c746f.png)

**Comment by trustwalletvn** [comment]
File
node_modules\eth-block-tracker\src\polling.js

  async _performSync () {
    while (this._isRunning) {
      try {
        await this._updateLatestBlock()
        await timeout(this._pollingInterval, !this._keepEventLoopActive)
      } catch (err) {
        const newErr = new Error(`PollingBlockTracker - encountered an error while attempting to update latest block:\n${err.stack}`)
        try {
          this.emit('error', newErr)
        } catch (emitErr) {
          console.error(newErr)
        }
        await timeout(this._retryTimeout, !this._keepEventLoopActive)
      }
    }
  }

**Comment by gantunesr** [comment]
Hey @shieldwallets, you need to set up a Infura account and use the keys in `.js.env` as `MM_INFURA_PROJECT_ID` for the polling tracker.

**Comment by Doko-Demo-Doa** [comment]
Not working. I have put Infura Project ID into `.js.env` but the error always show up. Did I miss something?

![image](https://user-images.githubusercontent.com/7723097/159169385-556a9423-6a03-442a-9e00-91b48fc20702.png)
