### ISSUE TITLE
Login screen bug

### ISSUE THREAD

**Issue by omnat** [MetaMask/metamask-mobile#3083]
~https://twitter.com/jannellelacra05/status/1431955820388884480~

Related to biometric login due to not having the available data in during decryption. Needs investigation.

**Comment by gantunesr** [comment]
Related #3476

**Comment by gantunesr** [comment]
The tweet referenced in the issue was deleted. @omnat do you have more information about this?

**Comment by gantunesr** [comment]
I'll close the issue since there's no additional information
