### ISSUE TITLE
Deeplink doesn't work

### ISSUE THREAD

**Issue by nghminh163** [MetaMask/metamask-mobile#3085]
**Describe the bug**
- Use deeplink generator from metamask site
- With dapps deeplink site, sometime browser appear with blank site
- With payment request deeplink, nothing happen
**Screenshots**
_If applicable, add screenshots or links to help explain your problem_

**To Reproduce**
_Steps to reproduce the behavior_

**Expected behavior**
_A clear and concise description of what you expected to happen_

**Smartphone (please complete the following information):**
 - OS:  Android 11
 - App Version [e.g. 1.0.0] - find version number in app from Settings > About MetaMask

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by trustwalletvn** [comment]
Mình build thành công bản cho Android rồi.
Nhưng có mấy vấn đề cần giúp đỡ 
Bạn cho mình hỏi
- thay đổi các link trong app vì nó toàn link tới meta, mình muốn nó chuyển tới link website của mình các mục như :
+ nhận trợ giúp
+ yêu cầu tính năng
+ mục cài đặt - giới thiệu- đường liên kết các link trong mục đó
Cảm ơn bạn

**Comment by gantunesr** [comment]
Related #3583

**Comment by gantunesr** [comment]
@nghminh163 can you verify if your issue is solved in v4.2.0
