### ISSUE TITLE
wallet_switchEthereumChain and wallet_addEthereumChain dont do anything

### ISSUE THREAD

**Issue by emadhamad171** [MetaMask/metamask-mobile#3090]
**Describe the bug**
I use wallet_switchEthereumChain and wallet_addEthereumChain in react native dapp, i create session wallet connect and after that when user clicks specific button, i call sendCustomRequest and it only opens metmask mobile and there is no switch confirmation and actually there is no any response, just opens metamask no error nothing

**Screenshots**
<img width="654" alt="Screenshot 2021-09-03 at 11 31 39 AM" src="https://user-images.githubusercontent.com/48877111/131975704-c5b86496-a05c-4015-b070-e24d9065efba.png">

**Expected behavior**
popup with confirmation 
_A clear and concise description of what you expected to happen_

**Smartphone (please complete the following information):**
 - Device: OPPO
 - OS: Android 10

-------------------------------------------------------------
Maybe i missed something, help me to resolve it or this flow not working yet

**Comment by gantunesr** [comment]
Related to #3581

**Comment by mazijie** [comment]
I have the same question, can anyone answer it?

**Comment by gantunesr** [comment]
@DecodingByte This fix will be included in v4.2.0

**Comment by gantunesr** [comment]
@emadhamad171 @DecodingByte can you verify if this is fixed in the latest release

**Comment by hesterbruikman** [comment]
@sethkfman could this issue be related to #3312?

**Comment by mhm13dev** [comment]
This is again not working with Wallet Connect V2.

I can't switch the chains

**Comment by liubin595338764** [comment]
I have also encountered this problem. May I ask how to handle it? This is how I operate.

```
"dependencies": {
    "@walletconnect/ethereum-provider": "^2.8.6",
  },
```

```
import { EthereumProvider } from '@walletconnect/ethereum-provider';

const provider = EthereumProvider.init({
  projectId,
  chains: [5], // REQUIRED chain ids
  showQrModal: true,
  relayUrl: "wss://relay.walletconnect.org",
  optionalChains: [1, 5, 56, 137, 10, 100],
  optionalMethods: [
    'eth_sendTransaction',
    'wallet_switchEthereumChain',
    'wallet_watchAsset',
    'wallet_addEthereumChain',
  ],
  optionalEvents: ['accountsChanged', 'chainChanged', 'network', 'disconnect'],
})


// Switch network
provider.request({
      method: "wallet_switchEthereumChain",
      params: [{ chainId: id.toString(16) }],
  })
```
