### ISSUE TITLE
Android MetaMask contract confirm repeat over 10 times

### ISSUE THREAD

**Issue by ode233** [MetaMask/metamask-mobile#3092]
### **Description**
Yesterday I used Metamask on android mobile to confirm a contract to claim an NFT, I adjust the priority fee and max fee, and checked multiple times, finally confirmed the contract, and then went to my job.
But When I check my wallet a few hours later, I was shocked, the contract confirm repeat 15 times in the same second, which cost me a lot of transaction fees.

This is my first time use Metamask on android mobile, anyone can help or explain what’s happen?

My transaction history in Etherscan
![i1](https://user-images.githubusercontent.com/36733129/132050798-0ecd0ef4-1ce1-4421-bade-4ccacb3a6f6b.png)

My transactions history in MetaMask
![i2](https://user-images.githubusercontent.com/36733129/132051425-f911d969-a34f-4d5f-8028-a250c54c5ce0.png)  ![i3](https://user-images.githubusercontent.com/36733129/132051428-d73aa94f-88f8-4a26-bfad-70aaac99d583.png)

I tried to ask for help in the MetaMask Community, but there was no one to communicate with me except a liar.   
https://community.metamask.io/t/android-metamask-contract-confirm-repeat-over-10-times/9520/8

**Comment by mobularay** [comment]
Hi there, @ode233 , we are reviewing this ticket, and wondering if this issue has happened again to you. We will close this ticket for now, but please reach out to us if this issue has persisted for you 🙏
