### ISSUE TITLE
Can't import account using scanning QR code

### ISSUE THREAD

**Issue by 0xWWW** [MetaMask/metamask-mobile#3105]
On mobile metamask wallet, I tried to import desktop metamask account on mobile device using QR code, but getting a modal with "Ooops! something went wrong..."

**Screenshots**
![File](https://user-images.githubusercontent.com/50073310/132580086-241ee2cb-0ee8-4f16-bc45-343f7a414d74.jpg)

**Comment by gantunesr** [comment]
Hi @0xWWW , The mobile sync feature is disabled temporarily due to security concerns.
