### ISSUE TITLE
Sending MAX amount on SmartBCH chain on iOS doesn't automatically calculate fees

### ISSUE THREAD

**Issue by kaardilugeja** [MetaMask/metamask-mobile#3114]
I was trying to withdraw my funds from SmartBCH chain back to CoinFlex address. When trying to get all funds out I hit the USE MAX button and it fills in the max amount automatically. Except it doesn't leave any funds to pay for fees so get the error : Transaction Error: Internal JSON-RPC error. When choosing a bit less than USE MAX provided by MetaMask then the transaction went through. Apparently when withdrawing funds from MetaMask wallet when you hit the USE MAX button on send screen it will try to send ALL the smartbch you have in there. Which means you won't have enough left to pay for the fees. If you want to withdraw everything then you have to send ALL minus the transaction fee.

Honestly I think this is something that should be calculated automatically by the wallet.

**Screenshots**
https://i.imgur.com/H9Ms2Rs.jpg

**To Reproduce**

1. Go to your SmartBCH wallet
2. Tap on 'Send'
3. Choose address to withdraw your funds to
4. Hit 'Next'
5. Tap 'USE MAX' upper right corner
6. Tap 'Next'
7. Tap 'Send'
8. Get error: 'Transaction Error: Internal JSON-RPC error.'
9. Tap the amount next to 'Estimated gas fee'
10. Get presented with the screenshot above. (Also side note here, it says not enough ETH. I think it should say GWEI for SmartBCH chain?)

**Expected behavior**
Expected behavior would be that MetaMask wallet automatically calculates the fee and deducts it from MAX amount. So I could withdraw all funds and have enaugh left to pay for gas fee. 

**Smartphone:**
 - Device: iPhone 12 Pro Max
 - OS: iOS 14.7.1
 - App Version: MetaMask v3.2.0 (772)

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by SystemDisc** [comment]
This is so annoying. What's the point of the send max button if it's unusable?
