### ISSUE TITLE
Occasionally, the transaction initiated by Dapp cannot be clicked to confirm

### ISSUE THREAD

**Issue by yyzkun** [MetaMask/metamask-mobile#3119]
Sometimes the transaction initiated by the android mobile dapp cannot be clicked on the confirm button, and no error is received. This is accidental. If I can’t click the confirm button, I just compile the gas, and the confirm button can be clicked again.
![微信图片_20210913155435](https://user-images.githubusercontent.com/47763582/133045482-823d856d-0403-4c6e-b118-338180356740.jpg)
![微信图片_20210913155441](https://user-images.githubusercontent.com/47763582/133045501-c23c8d05-cc77-4c99-8714-cf6dad06c5a0.jpg)

**Comment by gantunesr** [comment]
Solved in #3481
