### ISSUE TITLE
Is there anyone alive in this project？

### ISSUE THREAD

**Issue by ubearline** [MetaMask/metamask-mobile#3158]
Mention an issue.
### There was a dead silence.
<br/>

Submit pull request.
### There was a dead silence.

<br/>

E-mail sends

### There was a dead silence.

# Is there anyone alive in this project？

**Comment by sethkfman** [comment]
@ubearline We are working through our community PRs. If you are seeing a slow response please ping the team from the PR in question. Thank you for bringing this to our attention.
