### ISSUE TITLE
Clean SVG to prevent crashes with react-native-svg

### ISSUE THREAD

**Issue by Cal-L** [MetaMask/metamask-mobile#3187]
### **Description**

1. We need to figure out a way to standardize on SVG formats.
2. Figure out the limitations of react-native-svg
3. This issue affects token icons and collectibles

### **Technical Details**

- TBD

### **Acceptance Criteria**

- TBD

### **References**

- https://sentry.io/organizations/metamask/issues/2668486999/?project=2299799&query=is%3Aunresolved&statsPeriod=14d

**Comment by gantunesr** [comment]
This development should reverted the solution in the [PR 2941](https://github.com/MetaMask/metamask-mobile/pull/2941)

**Comment by mobularay** [comment]
https://consensys.slack.com/archives/CBW7S9FSN/p1641322383045200?thread_ts=1641321281.044900&cid=CBW7S9FSN

Will observe if v4.0.0 (upgrade RN) fixes this issue.

**Comment by gantunesr** [comment]
@Cal-L patched the react-native-svg module. Evaluate this bug in v4.0.0 and revert this fix (PR #2941) if possible
