### ISSUE TITLE
keyboard input does not render on screen [Android Samsung Galaxy S8]

### ISSUE THREAD

**Issue by cortisiko** [MetaMask/metamask-mobile#3202]
**Describe the bug**

I am unable to see what I typed. Whenever I tap the 'space' bar on the keyboard the text I inputted appears. 

For example: [Searching for a token in the swap flow](http://recordit.co/4PSeOeUJGV) [same thing whenever I input some text into the browser](http://recordit.co/WoTF7apBRO)**Screenshots**

This broke in v3.3. See similar behavior in [v3.2](http://recordit.co/45ywbA9DBJ)

**To Reproduce**
Go to browser and attempt to search 
or 
search for a token. 

**Expected behavior**
Text should appear correctly when a user types

**Smartphone (please complete the following information):**
 - Device: Android Samsung Galaxy S8
 - OS: [android 8]
 - App Version 3.3

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by mobularay** [comment]
Access to BrowserStack is a blocker // tag-team with Curtis to test out the solution
