### ISSUE TITLE
Txn Status Issue: The speed up and cancel CTA’s appear on the receiver ( the person who received the tokens) end. 

### ISSUE THREAD

**Issue by cortisiko** [MetaMask/metamask-mobile#3222]
**Describe the bug**
The speed up and cancel CTA’s appear on the receiver ( the person who received the tokens) end. Meaning a user sends some eth with a low gas fee to one of his accounts (lets call this the sender account). The sender account then speeds up the transaction. Upon doing so the transaction becomes confirmed. Fine. If you were to go to the receiver account then open up the transactions view, you will see a transaction with the speed up and cancel CTA’s. 

 
**Screenshots**
<img width="324" alt="image" src="https://user-images.githubusercontent.com/12821081/135359947-9825abd1-f807-4f3d-89a3-f66e64ce13e9.png">

**To Reproduce**
1. Go through the send flow to send some eth to one of your accounts
2. Before submitting your txn change the gas fee to low
3. Submit txn 
4. Go to the transaction overview and speed up the txn
5. Wait until the txn is confirmed then switch to the account that you are receiving funds in
6. go to the transaction overview 
7. notice the bug

**Expected behavior**
The receiver transaction overview should not contain any transaction that requires him/her to speed up the transaction. 

**Smartphone (please complete the following information):**
 - App Version [e.g. 1.0.0] - find version number in app from Settings > About MetaMask

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by gantunesr** [comment]
Include as part of the Transactions refactor
