### ISSUE TITLE
Problem with Favorites

### ISSUE THREAD

**Issue by ihorbaz** [MetaMask/metamask-mobile#3224]
**Describe the bug**
After adding page to favorites, button on exact page disappeared for adding, but don't exist link on favorites page when I open new tab

**Screenshots**
![image](https://user-images.githubusercontent.com/79227299/135400248-e53bb22d-905e-43e1-b890-df6e7505a6a5.png)

![image](https://user-images.githubusercontent.com/79227299/135400335-8556ba9d-b86b-43a2-a7cc-b12bfa738623.png)

**To Reproduce**

Just add something to favorites and open new tab

**Expected behavior**
Hope all will work properly after fix and we can use favorites

**Smartphone:**
 - Device: iPhone12
 - OS: iOS14.8
 - App Version [e.g. 3.3.0 (777)]

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by birdhackor** [comment]
I have same issue.

Device: iPhone11 pro
OS: iOS14.8
App Version [e.g. 3.3.0 (777)]

**Comment by cortisiko** [comment]
This was fixed as part of v.3.4.0. If the issue persists feel free to reopen the ticket!
