### ISSUE TITLE
Create component: BottomSheet

### ISSUE THREAD

**Issue by Cal-L** [MetaMask/metamask-mobile#3239]
### **Description**

Create `BottomSheet` component according to the insight report.

### **Technical Details**
- This is a container component, which means that we should be able to use this to wrap other child components
- Include presentation and dismissal animation (Use react-native-reanimated) for best performance
- Include gesture handler for interactions (Ability to swipe to dismiss). Use combo of react-native-reanimated + react-native-gesture-handler for best performance.

### **Acceptance Criteria**
- Create according to insight report 

### References
[Modal Audit FigJam](https://www.figma.com/file/hxYqloYgmVcgsoiVqmGZ8K/Modal-Audit?node-id=0%3A1&t=WcWEbEnjEkGuOdXr-1)
[Figma component](https://www.figma.com/file/HKpPKij9V3TpsyMV1TpV7C/DS-Components?node-id=3180%3A13642)

**Comment by xinnanyemm** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Design-System-61e8a2ae77c3a60012e5003c/issues/MetaMask/metamask-mobile/3239?planning-poker) with Zenhub @Akatori-Design @brianacnguyen @garrettbear
