### ISSUE TITLE
Way too many wallet connect sessions listed in Android wallet

### ISSUE THREAD

**Issue by maraoz** [MetaMask/metamask-mobile#3245]
**Describe the bug**
Multiple wallet connect sessions listed in Settings->Experimental->WalletConnect Sessions->View Sessions on Android, not corresponding to actual walletconnect sessions. I've been using metamask android to browse some dapps via WalletConnect. The experience was generally bad, so I tried to clear the wallet connect info and start over. That's when I found the Settings->Experimental->WalletConnect Sessions->View Sessions section, and found that it was reporting *thousands* of wallet connect sessions.

**To Reproduce**
_Steps to reproduce the behavior_
1. Use metamask android with 2 or 3 dapps via WalletConnect
2. Settings->Experimental->WalletConnect Sessions->View Sessions
3. Scroll down through the roughly ~1000 sessions listed

**Expected behavior**
Only a few sessions listed, corresponding to the amount of times I used WalletConnect (roughly 12-15 times)
This seems to be either a bug in the list, or a bug in the way metamask handles walletconnect sessions.

**Smartphone (please complete the following information):**
 - Device: Google Pixel 5a
 - OS: Android
 - App Version: v3.3.0 (777)

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by maraoz** [comment]
p.s: is it possible to clear all these sessions somehow?

**Comment by petzlux** [comment]
Same here on Android, after a while using WalletConnect, the number of sessions will be so large, that Metamask will start to slow down, and eventually wont even start anymore, and freeze. 

As there is no mass delete to clear the sessions, I am then stuck in a Metamask thats unresponsive.

**Comment by QuanticFlare** [comment]
Same here. Mm mobile is basically unusable now. I can't add any new networks without it crashing out because it slows down too much.

**Comment by mobilekosmos** [comment]
Wow, nice, I though it was only a problem of the beta, since after uninstalling the beta and installing the normal version it worked again, but I can see this issue being real, the app was absolutely unresponsive, you couldn't do anything, and I think it's becoming slower again after ~days.

**Comment by rwbaumg** [comment]
I'm surprised there's no support to bulk-end (or expire+autoremove) WalletConnect sessions already, especially considering the number of sessions cached by Metamask mobile for Android by the time I got around to looking at it (I've been experiencing issues starting new WalletConnect sessions that prompted me to check.) There are hundreds if not thousands of connections listed, including connections closed outside of the mobile app (is there a working refresh/expiration mechanism?), which seems like a lot more than it should be. Going through this list one-by-one is not really an option.

Does anyone have any workarounds that don't involve re-importing wallets on Android? I hate having to re-enter seeds if it can be avoided.....

**Comment by QuanticFlare** [comment]
You can clear connection all in security and privacy > clear privacy data. Tbh, I haven't found it helps with how sluggish the app is though but at least it's something.

**Comment by aksdevac** [comment]
Max number of wc session should be limited. & there is no option to clear other than clearing app data.

**Comment by gantunesr** [comment]
Solved in #3570 and #3566

**Comment by gantunesr** [comment]
This fix will be included in v4.2.0
