### ISSUE TITLE
Cannot swap saitama to etherium 

### ISSUE THREAD

**Issue by milestorme** [MetaMask/metamask-mobile#3246]
**Describe the bug**
When using the swap feature I cannot swap saitama to etherium just says quotes not available adjusting the amount doesn’t change the error no matter how low I go

**Screenshots**
![8944C14A-C30A-4A9C-B46B-825D6DCEC055](https://user-images.githubusercontent.com/44911744/135606097-f0a20d6d-0dab-402c-9177-ccf301c0416e.png)

**To Reproduce**
_Steps to reproduce the behavior_
1. Go to wallet 
2. Click on saitama
3. Select swap
4. Chose etherium to swap to 
5. Select get quotes

**Expected behavior**
Should give quote to swap to etherium 

**Smartphone (please complete the following information):**
 - Device: iPhone 12
 - OS: iOS 14.7.1
 - App Version 3.3.0

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by wachunei** [comment]
Hi @milestorme, this is an expected behavior since this token is currently unavailable to trade using Swaps.
