### ISSUE TITLE
Android browser missing `window.ethereum`

### ISSUE THREAD

**Issue by andrewrothman** [MetaMask/metamask-mobile#3258]
**Describe the bug**

The `window.ethereum` object appears to always be `undefined`, and `ethereum#initialized` is never dispatched.

**To Reproduce**
_Steps to reproduce the behavior_
1. Run a local HTTP server: `python -m SimpleHTTPServer`
2. Run an HTTPS tunnel: `npx localtunnel --port 8000`
3. Create the following file called `index.html` (the contents are based off of [MetaMask Docs -> Best Practices -> Provider Availability](https://docs.metamask.io/guide/mobile-best-practices.html#provider-availability)).
4. Open the HTTPS URL in the MetaMask in-app embedded browser on Android.
5. You will see an alert say "Please install MetaMask!"

```
<html>
  <body>
    <h1>Hi</h1>
  </body>

  <script>
    if (window.ethereum) {
      handleEthereum();
    } else {
      window.addEventListener('ethereum#initialized', handleEthereum, {
        once: true,
      });

      // If the event is not dispatched by the end of the timeout,
      // the user probably doesn't have MetaMask installed.
      setTimeout(handleEthereum, 3000); // 3 seconds
    }

    function handleEthereum() {
      const { ethereum } = window;
      if (ethereum && ethereum.isMetaMask) {
        alert('Ethereum successfully detected!');
        // Access the decentralized web!
      } else {
        alert('Please install MetaMask!');
      }
    }
  </script>
</html>
```

**Expected behavior**

Expected to see "Ethereum successfully detected!".
Found while debugging the same issue in a real-world application.

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy s10e
 - OS: Android 11 - One UI 3.1
 - App Version: MetaMask v3.3.0 (777) from Google Play Store

I can confirm that the above steps alert "Ethereum successfully detected!" on:
- Brave Version 1.30.86 Chromium: 94.0.4606.61 (Official Build) (x86_64) with MetaMask extension 10.1.1
- iPhone 11 - iOS 14.7.1 - MetaMask app v2.5.0 (750) from Apple App Store

**Screenshots**
![Android](https://user-images.githubusercontent.com/742678/135936418-a64ac623-c161-4ca4-b3c4-6a97ce14ec36.jpg)
![iOS](https://user-images.githubusercontent.com/742678/135936858-cab11e34-cef8-4c82-b5e2-d69bac984c0b.PNG)
![Brave](https://user-images.githubusercontent.com/742678/135936942-6a2d0148-b0cb-4c22-8a56-28c157f3313d.png)

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by andrewrothman** [comment]
Related:
https://github.com/MetaMask/metamask-mobile/issues/1975
https://github.com/MetaMask/metamask-mobile/issues/1956
https://github.com/MetaMask/metamask-mobile/issues/1931
https://github.com/MetaMask/metamask-mobile/issues/1140
https://community.metamask.io/t/window-ethereum-is-not-being-injected-on-android-metamask-mobile/3932

**Comment by andrewrothman** [comment]
One thing to mention, I found [this demo app repo](https://github.com/amaurym/login-with-metamask-demo) with [this live deployment link](https://amaurym.com/login-with-metamask-demo/) which **does** work on my Android phone. I'm not sure why this is.

The [code for the login button](https://github.com/amaurym/login-with-metamask-demo/blob/9996714ee8e6c361f73550b9f372558762ffac61/packages/frontend/src/Login/Login.tsx#L63) appears to access the same `window.ethereum` object:

```typescript
const handleClick = async () => {
		// Check if MetaMask is installed
		if (!(window as any).ethereum) {
			window.alert('Please install MetaMask first.');
			return;
		}
```

However it still does't work in the demo provided in the issue description.

**Comment by bcamacho** [comment]
Having the same issue @andrewrothman !

**Comment by soulofmischief** [comment]
I am also experiencing this issue. 

Using the recommended method [described here](https://docs.metamask.io/guide/mobile-best-practices.html#the-provider-window-ethereum).

**Comment by cquex** [comment]
Hey ! 

Anyone still facing the issue ?
How do you solved? 

Help! !

**Comment by HarshalKudale** [comment]
Getting Same Issue with my react website. But in my case it only fails when using react router Dom. When I am on homepage I get window.ethereum as true but when I am on routed urls (eg.domain.com/id/2) then window.ethereum becomes false. Works on desktop.

**Comment by cquex** [comment]
> Getting Same Issue with my react website. But in my case it only fails when using react router Dom. When I am on homepage I get window.ethereum as true but when I am on routed urls (eg.domain.com/id/2) then window.ethereum becomes false. Works on desktop.

Hi ! you need to open your website in the explorer of metamask, and metamask mobile needs to be an https sites, i published my website and configure https on my host. That solves my issue, to connect metamask on mobile.

**Comment by jellesiderius** [comment]
This still seems to be an issue. Can this please be looked at?

**Comment by R-Santev** [comment]
I am also experiencing the same issue whit an HTTPS dApp.

**Comment by rphuber** [comment]
You need to make sure that your html page has a `<head>` tag in it.  The mobile app browser injects the script inside that tag.  based on the html shown by the OP there is no head tag in the document.

**Comment by Fatxx** [comment]
Hello,

For issues related to cookies on Android please follow this issue https://github.com/MetaMask/metamask-mobile/issues/4245, it's already in place [PR#4407](https://github.com/MetaMask/metamask-mobile/pull/4407) to solve this problem.

**Comment by geraldchen890806** [comment]
> This: "You need to make sure that your html page has a `<head>` tag in it." Was one of the reasons I wasn't able to connect on a test page. Is this in the official documentation?

totally agree, wasting my time

**Comment by geraldchen890806** [comment]
another case, if html loaded a <iframe> and iframe has a head tag, MetaMask Android App will unload window.ethereum

**Comment by danbrud** [comment]
> another case, if html loaded a <iframe> and iframe has a head tag, MetaMask Android App will unload window.ethereum

@geraldchen890806 this is interesting. Any way to get around this behavior? I have multiple iframes but I can't afford metamask to unload the provider...

**Comment by tuncakyazi** [comment]
I wouldn't want to get up that topic, but is there anyone to found solution for that "android doesn't get window.etherium on sub-pages" problem.

I was try lots of solution on the internet but it's never see provider on Metamask browser. I checked some other web3 website. It's working on some websites. As i get it from that there is a solution but what.

I don't have any iframe. I'm using nextjs. I am using "@metamask/detect-provider". On main page everythings good working. But if i try to open "www.myweb.com/blabla", only android metamask browser doesn't find to provider. Iphone okay, web okay, only android.

**Comment by toteto** [comment]
Having path via react-router doesn't seem to pose a issue. Here is example of it: https://codesandbox.io/s/stoic-murdock-67r563

Navigating to both `https://67r563.csb.app/` and `https://67r563.csb.app/anyPage/anySubpage/` via the mobile browser yields the same result, the `ethereum` provider being detected.

**Comment by flcoder** [comment]
Still experiencing this in 2023.  What's odd is I have 2 dapps.  One works fine and they use basically the same code.  This is really pretty unacceptable.  And I have customers that cannot connect sometimes and there's no way to diagnose the problem for them.  Really need to step up the game on mobile or some other wallet is just going to take the market share.

**Comment by dzimbeck** [comment]
> 

Did you remember to have a header on the site? Otherwise it won't detect window.ethereum

**Comment by AntonioRitucci** [comment]
Facing similar issue, developing using Angular, on Android Mobile App if I try to access window.ethereum inside https://example.com/subroute it is never injected, https://example.com works fine

**Comment by kylinso** [comment]
This problem still exists to this day, and it cannot be solved by integrating the SDK either.

**Comment by YanYuanFE** [comment]
some issue
