### ISSUE TITLE
Add support for ERC-1155 NFTs

### ISSUE THREAD

**Issue by Cal-L** [MetaMask/metamask-mobile#3273]
### **Description**

We currently support adding NFTs to your wallet. While this works for ERC-721 based NFTs, the action fails when attempting to add ERC-1155 based NFTs, prompting the error: "You aren't the owner of this collectible.". This error is currently a catch all message based on failure and we'll most likely need to add more checks to display a more accurate message. More importantly, we'll need to add support for ERC-1155 based NFTs.

### **Technical Details**

- Add ERC-1155 support to the `AssetsContractController` via implementing a switch logic to handle adding different ERC standards.
- Refine failure message when adding an NFT to check for more specific reasons for failure + display those messages
- If we don't support certain ERC standards, we may implement a fallback using the OpenSea API

### **Acceptance Criteria**

- Adding ERC-721 or 1155 based NFTs should work and not throw an error
- Adding behavior should work the same as previous versions
- Viewing these two types of NFTs should not differ in behavior
- TBD: Figure out way to test error message

### **References**

- [Etherscan - Rarible ERC1155 Factory](https://www.notion.so/078bee8e251d02ee6872b1eaa6dd982a)
- [EIP-1155: Multi Token Standard](https://eips.ethereum.org/EIPS/eip-1155)
- [OpenSea API](https://docs.opensea.io/reference/retrieving-a-single-asset)
- [Community Issue #2110](https://github.com/MetaMask/metamask-mobile/issues/2110)

**Comment by gantunesr** [comment]
Suggestion: Show number of collectibles in the card info.

```javascript
collectibleContract.balanceOf(deployerAddress, 3)
// > 1000000000
```
