### ISSUE TITLE
Cookie issue in MetaMask mobile app

### ISSUE THREAD

**Issue by BeycanDeveloper** [MetaMask/metamask-mobile#3278]
Hello, the cookies feature does not work in the MetaMask mobile application. In this case, the add to cart feature in my DApp is also disabled. Can you provide a solution to this situation?

**Comment by BeycanDeveloper** [comment]
I have developed a few webview apps as native before, but I have no experience with react native. Otherwise I would be interested in solving the problem.

**Comment by cheezcharmer** [comment]
+1 to the issue. i cannot do anything from my php application since it's so reliant on metamask and ability to set cookies. apparently the session id is reset on every page change. would really appreciate some help

**Comment by EpicWebs** [comment]
Maybe need to add:

thirdPartyCookiesEnabled={true}
sharedCookiesEnabled={true}

https://github.com/MetaMask/metamask-mobile/blob/375f742331b66f008b74b0436230e16b7ff1a1df/app/components/Views/BrowserTab/index.js#L1555

?

**Comment by Fatxx** [comment]
Closing in favour of https://github.com/MetaMask/metamask-mobile/issues/4245
