### ISSUE TITLE
WalletConnect - sendCustomRequest - wallet_addEthereumChain is not working

### ISSUE THREAD

**Issue by nohhplus** [MetaMask/metamask-mobile#3279]
WalletConnect - sendCustomRequest - wallet_addEthereumChain is not working
plz add
app/components/Views/BrowserTab/index.js - rpcMethods
to app/core/WalletConnect.js (call_request event - payload.method)

**Comment by gantunesr** [comment]
Related to #3583

**Comment by gantunesr** [comment]
Fix in v4.2.0
