### ISSUE TITLE
Look into Sentry performance monitoring

### ISSUE THREAD

**Issue by Cal-L** [MetaMask/metamask-mobile#3285]
### **Description**

Sentry Performance allows us to `trace` metrics such as API response times, screen load times, etc. It is NOT a performance monitor and is not meant for tracking things such as OS level metrics. For this ticket, we will be looking into this tool, and if needed, implementation. This is for our continued efforts on improving performance for our mobile apps. 

### **Technical Implementation**

- Upgrade Sentry + Integrations library
- Hook integration up to work with React Navigation actions
- Determine what sample size we want. Ex: 0.2 = 20% of traces get recorded

### **Acceptance Criteria**

- Performance metrics should be viewable in the Sentry dashboard
- Non-performance related events should still be tracked as usual

### **References**

- Sentry Performance - https://docs.sentry.io/product/performance/

**Comment by sethkfman** [comment]
Completed
