### ISSUE TITLE
Metamask mobile requires gas fees even for gasless, private networks

### ISSUE THREAD

**Issue by dojh111** [MetaMask/metamask-mobile#3305]
**Describe the bug**
Currently, we are using Metamask Mobile, on both **iOS & Android**, connected to a custom, private network in QBS _Quorum Blockchain Services_. This network has no currency at all, and is unable to generate any.

However, when interacting with our deployed smart contracts on the network, Metamask Mobile still requests for the minimum gas fees. All our smart contracts and interactions are set at **0 fees**. Attached below are some screenshots of the issue.

This issue **DOES NOT** exist on the Metamask Browser Extension.

**Screenshots**
This image shows that the interactions are set to **0**

<img width="522" alt="code-snippet" src="https://user-images.githubusercontent.com/60423568/137836279-76aa3326-76d4-4e10-8704-9e6763b449c2.png">

The error that occurs on the Metamask **iOS & Android** versions of the app that shows up. Note that we are unable to transact when the wallet has no currency.

![MetamaskMobile_Transaction_error](https://user-images.githubusercontent.com/60423568/137836405-3146eb86-c4af-4f6c-9f13-6d573a573874.jpg)

**To Reproduce**
_Steps to reproduce the behavior_
1. Deploy a smart contract on the Consensys QBS network
2. Try to interact with contract with a newly created Metamask account on Metamask Mobile

**Expected behavior**
The transaction should be allowed to go through when on a gasless network, with an account with no currency, instead of blocking the transaction.

We have also done extra testing on a network where gas prices are **0**, but are able to secure currency. Even though the popup still comes up saying that we require gas fees, after the transaction is processed **no gas fees are consumed**, which confirms that it is not an issue with our code/smart contracts.

This issue **does not** exist on the metamask browser extension. But we are targetting users on the Metamask mobile application.

**Smartphone (please complete the following information):**
 - Device: iPhone 8/11/12 Pro as well as Samsung Android
 - App Version: v3.4.1

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by djsatok** [comment]
I would like to bump it. Aurora users also experiencing such issues.

**Comment by enzoliu** [comment]
facing this issue too.

**Comment by Fatxx** [comment]
This is fixed in the latest version, please reopen if it still happens to you.
