### ISSUE TITLE
view data popout doesnt work

### ISSUE THREAD

**Issue by az1az1** [MetaMask/metamask-mobile#3306]
Android 8.1 samsung galaxy
view data popout on transaction review goes to blank grey opaque , no text, doesnt work. settings, turned hex data on, still not working

**Comment by gantunesr** [comment]
hey @az1az1, is this still an issue in the last version?

**Comment by gantunesr** [comment]
@az1az1 can you provide more details about this issue? like device OS, app version, steps to reproduce, and the dapp you're interacting.

**Comment by gantunesr** [comment]
I'll close this issue for the moment, please open a new one if you encounter it in the latest release
