### ISSUE TITLE
Mobile app removes and doesn't re-inject MetaMask provider when changing network

### ISSUE THREAD

**Issue by 4skinSkywalker** [MetaMask/metamask-mobile#3309]
**Describe the bug**
Mobile app seems to remove (and doesn't re-inject) MetaMask provider when changing network, leading to error.

**Screenshots**
![bug-metamask-mobile](https://user-images.githubusercontent.com/17194393/137964592-3b73fb2b-3a0c-433d-b185-aa58a1722613.gif)

**To Reproduce**
What's the GIF above.

**Expected behavior**
I would expect to be able to connect after network switch.

P.S.: I've noticed that touching the URL bar and refreshing by changing some character there and reloading that way solves the issue, but then it comes back.

**Smartphone (please complete the following information):**
 - Device: Android
 - OS: Android 9
 - MetaMask: 3.4.1 (785)

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by 4skinSkywalker** [comment]
OK guys, I've discovered this was something related to routing!
Now I would like to know why!!!

I'm using Angular v12 and I was initially using `redirectTo` in my app-routing file as follows:
```js
const routes: Routes = [
  ...
  { path: '', redirectTo: '/send', pathMatch: 'full' }
  ...
];
```
This was messing up with MetaMask mobile for some reason, even though it shouldn't cause any problem from my point of view.

Removing that empty path redirect and pointing the empty path to that same component it was redirecting too fixed it:
```js
const routes: Routes = [
  { path: '', component: SendComponent },
  ...
];
```
Now it works as expected.
But why was that a problem?

Thanks,
Fredo

**Comment by gantunesr** [comment]
hey @4skinSkywalker, can you check if this is happening in the last release?
