### ISSUE TITLE
Add support for IPFS on NFTs

### ISSUE THREAD

**Issue by Cal-L** [MetaMask/metamask-mobile#3310]
### **Description**

Currently, we do not support displaying IPFS links for NFTs.

### **Technical Details**

- Use existing IPFS resolver for displaying tokens -> NFTs

### **Acceptance Criteria**

- Assets that from from IPFS should be rendering correctly
- Non-IPFS assets should render the same as before

### **References**

NFT References
- [Community Issue #2817](https://github.com/MetaMask/metamask-mobile/issues/2817)
- [Community Issue #2838](https://github.com/MetaMask/metamask-mobile/issues/2838)

**Comment by kinggongzilla** [comment]
@wachunei is this still in progress?
The current MetaMask version 3.6 seems to not support IPFS images of the form "ipfs://[CID]/nft.jpg" 
Note the "/nft.jpg" in the end

NFT images show up correctly on OpenSea, but not in MetaMask mobile app.

**Comment by wachunei** [comment]
@kinggongzilla is this still happening to you? can you please provide a link or (network, address, id) of the collectible? that format should work.

**Comment by kinggongzilla** [comment]
@wachunei Hi! It actually works now. I had to refresh the metadata again for the images to show. MP4 files are not showing, however I assume that is the case in general, correct?

Thank you so much for implementing this! It is a great improvement to our users
