### ISSUE TITLE
[v3.4.x.xxx] MetaMask Mobile not responding to events - no transaction pop-ups triggered

### ISSUE THREAD

**Issue by W3stside** [MetaMask/metamask-mobile#3315]
**Describe the bug**
No responses from app. In-app browser not showing transaction pop ups on events in dApp.
Tested in our own app, uniswap, matcha, balancer, 1inch, nothing is working.

Uniswap/CowSwap/Balancer
Wrapping/unwrapping ETH/WETH - no response
Approving - no response
Trades - no response

Teammate using `v3.3.0` is able to make some transactions

**To Reproduce**
1. Go to app.uniswap.org // cowswap.exchange
2. try wrapping ETH to WETH
3. Button shows pressed in UI but no response from MM mobile
applies to any other kind of transaction

**Expected behavior**
Should be showing transaction popups

**Smartphone (please complete the following information):**
 - Device: `OnePlus 6T 2018`
 - OS: `Android10`
 - App Version [e.g. 1.0.0] - `3.4.1[785]`

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by gantunesr** [comment]
Solved in #3295
