### ISSUE TITLE
Unable to confirm Metamask Mobile Transaction

### ISSUE THREAD

**Issue by dojh111** [MetaMask/metamask-mobile#3318]
**Describe the bug**
On our private blockchain network, when using the Metamask Mobile IOS and Android versions, randomly, the transaction popup does not allow the user to press the "confirm" button, despite having enough currency to pay gas fees.

**Screenshots**
![metamask-mobile-transaction-fail-error](https://user-images.githubusercontent.com/60423568/138212324-4f0431af-d78a-4469-a879-8670f684659b.jpg)

**Expected behavior**
The button should not be disabled for the user to confirm the transaction.

A re-render of the transaction is required for the button to be enabled.

**Smartphone (please complete the following information):**
 - OS: ios and Android
 - Metamask v3.4.1

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by kacperzelichowski** [comment]
@gantunesr yeah sure.

We're actually building a NFT marketplace on BSC network. We use web3 as a way to communicate with the chain methods.
This week we've released a public BETA version of our app, where you can perfom some basic operations like creating your NFT's for sale, buying them, etc. 

Everything seems to be working just fine for browser flows, but whenever we're trying to call contract methods which we use for creating auctions and actually buying the NFT we're getting an `Unknown Method` and the `Confirm` button is greyed out until we hit the `estimated fee` and `save` it.

The contracts are deployed on BSC testnet network. We have the same network set in Metamask Mobile. 

You can visit the marketplace at `https://beta.ultiarena.com/app/home`. However you'll need some of our coin to actually buy something there. If you give me your wallet address I can send you some :). You'll also need some BNB's for the gas.

As you probably know you'll also have to import our coin to your wallet. Below some info you'll need:

```
COIN:

Token contract address: 0x1Ed837F59efA2b69c7e91a7D1bFa06FC9C20ea09
Symbol: ULTI
```

```
NETWORK:

RPC URL: https://data-seed-prebsc-2-s1.binance.org:8545/
Chain ID: 97
Currency symbol: BNB
```

So the flow you'll have to recreate would be:

1. Connect your wallet to our app.
2. Try and buy an NFT listed on the marketplace.
3. The first approve should go through smoothly.
4. The second one will not let you confirm, unless you reestimate the fee.

**Comment by gantunesr** [comment]
Thanks @kacperzelichowski and @dojh111, we will take a look at the issue and give an update asap.

@kacperzelichowski did you experienced this issue on previous versions or it was introduced in 3.4.1? @dojh111 mentioned that it did not existed in the previous version.

**Comment by sethkfman** [comment]
@kacperzelichowski I am looking into the issue but the test net is giving me an error:

**Comment by kacperzelichowski** [comment]
@sethkfman this might be due to the fact that we're still upgrading our contracts. You should be able to buy some of the newer art.

Like this one for example:

https://beta.ultiarena.com/app/asset/b495c26a-ffd5-4228-89f6-727c63ff8b21

**Comment by Fatxx** [comment]
@kacperzelichowski, we're currently investigating the issue, although I'm not able to connect to the RPC URL you sent previously (`Could not fetch chain ID. Is your RPC URL correct?`). 

It also seems that your Dapp is down at the moment. I'm trying to access it on https://beta.ultiarena.com/app/asset/b495c26a-ffd5-4228-89f6-727c63ff8b21.

Please let us know when we can reaccess it since we're trying to solve the issue.

**Comment by imin314** [comment]
We've also encountered this problem with transactions on the Arbitrum Testnet. To reproduce it, please go to [https://bridge.arbitrum.io/](https://bridge.arbitrum.io/) and send ETH from Arbitrum to Mainnet (L2 -> L1). The "Confirm" button is sometimes disabled.

![IMG_5685](https://user-images.githubusercontent.com/40715953/140908650-68e631fd-3a74-4664-a9d4-31fb099d0d9d.gif)

**Comment by beauwilliams** [comment]
I am having the same issue with https://cygorithm.com

It is on BSC testnet too, ID=97 same as above.

I find that if I hold my finger on the screen it works. If I try to re-run the transaction it sometimes also works too

**Comment by beauwilliams** [comment]
I found a fix to hard code in gas price 

confirm button greyed out
```
        .then(contractInstance => contractInstance.methods.mintStandardNFT().send({from: window.userWalletAddress, value: "25000000000000000"},
```

confirm button not greyed out, notice gas price harcoded into fn call
```        .then(contractInstance => contractInstance.methods.mintStandardNFT().send({from: window.userWalletAddress, value: "25000000000000000", gas: 1000000, gasPrice: 12000000000},
```

**Comment by jonsteelman** [comment]
Same issue NFT minting on Fantom Opera **mainnet** on any NFT minting website! This is with latest Mobile Metamask iphone or android. Workaround offered does enable the `Confirm` button...

> the Confirm button is greyed out until we hit the estimated fee and save it.

**Comment by TheStarBoys** [comment]
> I found a fix to hard code in gas price
> 
> confirm button greyed out
> 
> ```
>         .then(contractInstance => contractInstance.methods.mintStandardNFT().send({from: window.userWalletAddress, value: "25000000000000000"},
> ```
> 
> confirm button not greyed out, notice gas price harcoded into fn call
> 
> ```
>     .then(contractInstance => contractInstance.methods.mintStandardNFT().send({from: window.userWalletAddress, value: "25000000000000000", gas: 1000000, gasPrice: 12000000000},
> ```

It is the available solution. But, if gas or gasPrice went wrong, metamask notes you "internal JSON-RPC error".
