### ISSUE TITLE
Support for deep link on Android

### ISSUE THREAD

**Issue by anthonygraignic** [MetaMask/metamask-mobile#3326]
**Describe the usability problem**
When using the Metamask mobile browser, if I encounter a deeplink registered by another app e.g. Instagram/Twitter. The associated app is not launched and the link is loaded on the browser.
This is particularly useful when using social sign-in with apps e.g. Facebook Login, Twitter, Google... 

**Screenshots**
https://developer.android.com/training/app-links

**Expected behavior**
If I click on a deeplink registered by an app installed on the device, I should be asked to launch this app or continue on Metamask.

------------------------------------------------------------------------------------------------------
_filled out after submission_

**User impact | Usage frequency | Feasibility scores**
_How important is this to the user, what the user wants to accomplish | Daily, weekly, monthly | Small, medium, large_

**Comment by gantunesr** [comment]
Partially fixed in #3664.

**Comment by gantunesr** [comment]
Hey @anthonygraignic, for the moment the app only supports the Twitter scheme in v4.1.0. We'll discuss internally the possibility of adding more.

**Comment by anthonygraignic** [comment]
Hey @gantunesr thank for the update and the fix !
But I don't really understand why only the Twitter scheme is supported. Deep linking is supposed to be handled by the OS on Android not by the app.
Could you give more precision ? In my case I wanted to use it for Instagram so 🤷‍♀️.
