### ISSUE TITLE
[5.2] Pressing "home" does not show favorites

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-mobile#3331]
**Describe the bug**
No favorites are shown, even when the user has favorites

**Screenshots**
![IMG_8268](https://user-images.githubusercontent.com/542863/138572752-63deaa91-d46c-4cf0-b55c-7abc8f7c8cb6.jpg)

**To Reproduce**
1. Save some favorites
2. Tap the "home" icon in the bottom bar
3. Notice "no favorites yet".

**Expected behavior**
I expect to see favorites. I can find them by going into tabs and creating a new tab, that path correctly shows favorites.

**Smartphone (please complete the following information):**
 - Device: iPhone 11 Pro
 - OS: iOS 14.8
 - App Version 3.4.1

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by gantunesr** [comment]
Internal conversation:https://consensys.slack.com/archives/CBW7S9FSN/p1638820384468400?thread_ts=1638810018.460500&cid=CBW7S9FSN

**Comment by gantunesr** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/MetaMask-Mobile-5f984938ddc0e4001d4b79cb/issues/MetaMask/metamask-mobile/3331?planning-poker) with ZenHub @Fatxx @plasmacorral

**Comment by dynahpointch** [comment]
WHEN THIS WILL BE FIXED OPEN NOW SINCE TWO YEARS ON REDDIT AND OTHER FORUMS ?
Please when this will bi addressed in the next 50 years and fixed ?

**Comment by AlexHerman1** [comment]
woot!
