### ISSUE TITLE
Fix unidentified nft collection name

### ISSUE THREAD

**Issue by Cal-L** [MetaMask/metamask-mobile#3334]
### **Description**

This ticket aims to fix collection names showing with the label "Unidentified Contract".

### **Technical Details**

- Use `contract -> name` property vs `name` from OpenSea's response
- Reference - https://github.com/MetaMask/metamask-mobile/issues/3275#issuecomment-946034973

### **Acceptance Criteria**

- NFT collections should display correct collection name 

### **References**

- [Community Issue #2772](https://github.com/MetaMask/metamask-mobile/issues/2772)

**Comment by gantunesr** [comment]
Solved in https://github.com/MetaMask/controllers/pull/628

**Comment by Cal-L** [comment]
Mobile PR solved in #3387
