### ISSUE TITLE
NFT Caching issue

### ISSUE THREAD

**Issue by Cal-L** [MetaMask/metamask-mobile#3335]
### **Description**

- NFTs appearing into another accounts and networks, this happens because of an edge async issue between the CollectibleDetectionController, CollectiblesController, and current address and network. This can be verified by changing account/network right after starting the auto detection mechanism by refreshing the wallet view.
- This development also addresses the following breaking changes from the controllers version 21.0.1
  - https://github.com/MetaMask/controllers/pull/645
  - https://github.com/MetaMask/controllers/pull/636
  - https://github.com/MetaMask/controllers/pull/638
  - https://github.com/MetaMask/controllers/pull/655

### **Technical Details**

- Add a check to verify that the NFT is being added in the correct account and network that started the request (controllers layer).
- Add unit and integration testing to the new development and/or update existing tests.

### **Acceptance Criteria**

- NFTs should show up on the correct accounts and networks

### **References**

- [Dave Pazdan's Issue #3033](https://github.com/MetaMask/metamask-mobile/issues/3033)
- [Dan Finlay's Issue #1663](https://github.com/MetaMask/metamask-mobile/issues/1663)
- [Issue #3406](https://github.com/MetaMask/metamask-mobile/issues/3406)

**Comment by gantunesr** [comment]
Related [issue #3406](https://github.com/MetaMask/metamask-mobile/issues/3406)

cc: @Cal-L @omnat

**Comment by gantunesr** [comment]
@wachunei and I have been taking a look at this bug, we have found the issue and @wachunei is already working in the solution

**Comment by mobularay** [comment]
As discussed Nov 11 Sprint Grooming: this ticket can be split into two - 
1) Fix adding logic from autodetect (right network and address) - no design work; all in controller (controller ticket #636)
2) Poll for ownership and Visually provide msg that user no longer own the NFT - requires design work

@wachunei either you or I can create a new ticket for the design work. Lmk how you'd like to proceed. Thanks!

**Comment by wachunei** [comment]
Ownership is going to be tracked in this issue https://github.com/MetaMask/metamask-mobile/issues/3444
