### ISSUE TITLE
Storage limit issue introduced in v3.5.0

### ISSUE THREAD

**Issue by Cal-L** [MetaMask/metamask-mobile#3337]
### **Description**

Curtis discovered a storage limit issue introduced in v3.5.0. Reproducible by creating a wallet, killing the app, and reopening it. After attempting to log in the second time, the app shows a storage limit error.

### **Technical Details**

- Technical research
- UPDATE: Revert commit d155ce9, which introduces this
- Reason: The storage mechanism introduced in the patch resulted in only partial storage of the entire redux store. When the app tries to fetch the persisted data, it doesn't recognize partially cached data as valid JSON, therefore failing.

### **Acceptance Criteria**

- Should not run into a storage limit issue when repeating steps listed in description

### **References**

- [Curtis's Find](https://consensys.slack.com/archives/C029D95J3K8/p1635176560000200)

**Comment by Fatxx** [comment]
Closed at #3338
