### ISSUE TITLE
[iOS] Unable to create wallet when you deny facial biometrics 

### ISSUE THREAD

**Issue by cortisiko** [MetaMask/metamask-mobile#3358]
**Describe the bug**
On iOS, if a new user denies using faceID to log in, there is a error that appears: "The user name or pass phrase is incorrect" 

**Screenshots**
![image](https://user-images.githubusercontent.com/12821081/139487448-65ce5f72-48f4-4907-8c88-968f7cce3691.png)

see [recording](http://recordit.co/LSJEhPJoNJ)

**To Reproduce**
1. on iOS go through the new wallet flow
2. you should be prompted with a modal asking "Do you want to allow 3. MetaMask to use Face ID"
4. tap "don't allow"
5. notice the error

**Expected behavior**
_A clear and concise description of what you expected to happen_

**Smartphone (please complete the following information):**
 - Device: iPhone Xr
 - OS: iOS 14.8
 - App Version: first appeared at v3.0.1

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by sethkfman** [comment]
@cortisiko I am not seeing this issue on:
- iPhone 11Pro
-  v3.6.0
- iOS 15.0.2

**Comment by cortisiko** [comment]
@sethkfman very interesting. I am able to reproduce on 

- iPhone 11
- v3.6.0 (789)
- iOS 15.0.2

See recording [here](http://recordit.co/3Qg53nvq9t)
