### ISSUE TITLE
Lost BUSD

### ISSUE THREAD

**Issue by ustazkhai** [MetaMask/metamask-mobile#3364]
Hi sir,
My name is Rizal, i once have more than 400BUSD in my wallet. Now its gone. Please help me to get it back.

-   wallet address : 0x649AFa409C1a94F2fE2a915233ee948e6c19EdD8
-https://metamask.zendesk.com/hc/requests/443640

**Comment by gantunesr** [comment]
Hey @ustazkhai , I'm going to bring this issue to the support team
