### ISSUE TITLE
ipfs image still not showing

### ISSUE THREAD

**Issue by jjamtiger** [MetaMask/metamask-mobile#3368]
**Describe the bug**
Still not showing NFT Image(IPFS) 

**Screenshots**
![Screenshot_20211103-143132_MetaMask](https://user-images.githubusercontent.com/25046586/140013835-95e12201-79d0-44c7-9b8e-4cd34f46a5a5.jpg)
![Screenshot_20211103-143147_MetaMask](https://user-images.githubusercontent.com/25046586/140013839-b0ad7020-647a-4f01-9574-b226c37c037f.jpg)

**To Reproduce**
_Steps to reproduce the behavior_

**Expected behavior**
I already know ipfs image is not working. so i just downloaded and installed lasted metamask 3.6.0 apk. I re-adding nft list and refresh but not working. i tried pull down and refresh nft, but now working. i tried changing ipfs gateway, but now working. I think still not working  nft image(ipfs).

**Smartphone (please complete the following information):**
 - Device: Galaxy s21
 - OS: android
 - App Version [e.g. 1.0.0] - find version number in app from Settings > About MetaMask 3.6.0

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by jjamtiger** [comment]
I found solution. image to ipfs is ok. but json to ipfs is not working. json must be uploaded website not ipfs.

**Comment by wachunei** [comment]
@jjamtiger version 3.6 supports IPFS hosted metadata, URI grabbed from the contract property `tokenURI`/`URI`. Please confirm this is correct.
