### ISSUE TITLE
method: 'wallet_watchAsset' is not launched in mobile version

### ISSUE THREAD

**Issue by JTorresConsulta** [MetaMask/metamask-mobile#3376]
My code include the next code to add my token. 
https://docs.metamask.io/guide/registering-your-token.html#code-free-example

Works correctly in navigator plugins but not in the mobile version.

**Comment by JTorresConsulta** [comment]
There are humans behind this project... ?

**Comment by AleeeKoi** [comment]
Hi @JTorresConsulta 
I'm having the same issue maybe, I'm coding a react native app that use `Wallet Connect` to integrate my metamask wallet.
So, I'm trying to do this:
```
const walletConnector = useWalletConnect()

await walletConnector.sendCustomRequest({
            method: 'wallet_watchAsset',
            params: {
                type: 'ERC20',
                options: {
                    address: '0xf8056e8286...',
                    symbol: 'FOO',
                    decimals: 18
                }
            }
        })
```

Metamask app opens correctly but nothing happens... have you found a solution?

Thanks

**Comment by gantunesr** [comment]
Related to #3581

**Comment by gabkov** [comment]
Now the token addition works, but the image for the token is not loaded. Android MM app.

**Comment by jcamilli** [comment]
On mobile iOS this is not fixed yet. The token popup comes up (sometimes) but the image is not there and is not added. Also, wallet_watchAsset sometimes does not work unless you kill the app and restart.
