### ISSUE TITLE
Connecting to MetaMask wallet via WalletConnect mobile linking does not work

### ISSUE THREAD

**Issue by MarkOSullivan94** [MetaMask/metamask-mobile#3381]
**Describe the bug**
Whenever opening up a dapp on my mobile web browser, I am unable to connect to my MetaMask wallet when selecting the option to connect to a wallet via Wallet Connect.

**Screenshots**
_If applicable, add screenshots or links to help explain your problem_

<img height="400" alt="Screenshot 2021-11-04 at 22 10 54" src="https://user-images.githubusercontent.com/6950843/140431547-9e32b3e1-04e6-4dbe-9d81-aefd16a2d5a5.png">

<img height="400" alt="Screenshot 2021-11-04 at 22 10 54" src="https://user-images.githubusercontent.com/6950843/140431554-53d4b8e1-e127-472e-a5e8-e4f20b720302.png">

<img height="400" alt="Screenshot 2021-11-04 at 22 10 54" src="https://user-images.githubusercontent.com/6950843/140431556-1fe5995c-0dab-410c-b400-ada5bc07831e.png">

<img height="400" alt="Screenshot 2021-11-04 at 22 10 54" src="https://user-images.githubusercontent.com/6950843/140431559-d5483e1a-6274-4376-9898-bc3242cd8d8a.png">

**To Reproduce**
* Open web browser
* Go to https://app.sushi.com/swap
* Tap `Connect to a wallet`
* Tap `WalletConnect`
* Tap blue `Connect` button
* Select `MetaMask` from list of options
* Nothing appears when the app loads 

**Expected behavior**
I should see the same popup behaviour as when I scan Wallet Connect QR code from my browser which allows me to confirm that I wish to connect

This popup has the title `Connect to this site?` along with two buttons, the left one being a white `Cancel` button and the right a blue `Connect` button.

**Smartphone (please complete the following information):**
 - Device: Pixel 4XL
 - OS: Android 12
 - App Version: v3.6.0 (790)

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by manasovdan** [comment]
same here.
Sometimes it opens popups in Metamask app (popups like connect/sign) but in most of the cases for our dapp it does nothing after being opened by walletconnect

**Comment by manasovdan** [comment]
probably related to #2045

**Comment by sethkfman** [comment]
@MarkOSullivan94  Thank you for documenting the issue with steps to reproduce. We have fixed the issue and it will be applied to the next mobile release. I will follow up on the release date once I have confirmation.

**Comment by MarkOSullivan94** [comment]
Thanks for the update @sethkfman

**Comment by sethkfman** [comment]
3.7.0 is being rollout over this week. 

If you have an Android device you can get access the latest release immediately via the release notes: https://github.com/MetaMask/metamask-mobile/releases/tag/v3.7.0

**Comment by Anthonyslav** [comment]
hey conection not working

**Comment by andreahaku** [comment]
> hey conection not working

hey @Anthonyslav can you please give us more information about that? like how are you implementing it. Which version of the app are you using? Which device. Thanks :)

**Comment by sathudeva7** [comment]
@Anthonyslav have use used bridge: "https://bridge.walletconnect.org" this command inside walletProvider

**Comment by chaitu605** [comment]
> @Anthonyslav have use used bridge: "https://bridge.walletconnect.org" this command inside walletProvider

import {
  EthereumClient,
  modalConnectors,
  walletConnectProvider,
} from "@web3modal/ethereum";
import { configureChains, createClient, WagmiConfig } from "wagmi";
import { Web3Modal } from "@web3modal/react";

const chains = [mainnet];

const { provider, webSocketProvider } = configureChains(chains, [
    walletConnectProvider({
      projectId: "projectid",
    }),
  ]);
  const wagmiClient = createClient({
    autoConnect: true,
    connectors: modalConnectors({
      projectId: "projectId",
      version: "2",
      appName: "Test App",
      chains,

    }),
    provider,
    webSocketProvider,
  });

  const ethereumClient = new EthereumClient(wagmiClient, chains);
  
  return (
  <WagmiConfig client={wagmiClient}>
 <Web3Modal
          projectId="projectId"
          ethereumClient={ethereumClient}
          themeZIndex={1350}
        />
  </WagmiConfig>
  )
  
  where to use bridge here ?

**Comment by chaitu605** [comment]
I m also facing this issue using walletconnect v2 
this is my code 

```
import {
  EthereumClient,
  modalConnectors,
  walletConnectProvider,
} from "@web3modal/ethereum";
import { configureChains, createClient, WagmiConfig } from "wagmi";
import { Web3Modal } from "@web3modal/react";

const chains = [mainnet];

const { provider, webSocketProvider } = configureChains(chains, [
    walletConnectProvider({
      projectId: "projectid",
    }),
  ]);
  const wagmiClient = createClient({
    autoConnect: true,
    connectors: modalConnectors({
      projectId: "projectId",
      version: "2",
      appName: "Test App",
      chains,

    }),
    provider,
    webSocketProvider,
  });

  const ethereumClient = new EthereumClient(wagmiClient, chains);
  
  return (
  <WagmiConfig client={wagmiClient}>
 <Web3Modal
          projectId="projectId"
          ethereumClient={ethereumClient}
          themeZIndex={1350}
        />
  </WagmiConfig>
  )
```
And in another file i m using web3button like this 

```
import {  Web3Button } from "@web3modal/react";
return (
<Web3Button balance="show" />
)

```
when i press this button in mobile browser it prompts to open metamask as select and go in nothing happens no prompt for connect or anything 
Works all good in desktop browser

**Comment by AthiraVGopi** [comment]
Still have issue in android device that initially the connect popup doesn't shown up. when go back and trying second time its showing up for connection.

**Comment by timmyjose** [comment]
Same issue here. It's very quirky - works once in a blue moon, usually not. The Web3Modal redirects to the MetaMask app, but I don't see the "Cnnect" option in the MetaMask app.

**Comment by ssinghbb** [comment]
> Same issue here. It's very quirky - works once in a blue moon, usually not. The Web3Modal redirects to the MetaMask app, but I don't see the "Cnnect" option in the MetaMask app.

Are you able to resolve ?
