### ISSUE TITLE
Encountered the same problem, tested the mnemonic phrase and the account where the private key was imported, and all showed the same error. Tested dapp URL http://39.106.167.166:4002

### ISSUE THREAD

**Issue by afiiijooon** [MetaMask/metamask-mobile#3382]
Encountered the same problem, tested the mnemonic phrase and the account where the private key was imported, and all showed the same error. Tested dapp URL http://39.106.167.166:4002

_Originally posted by @cppfuns in https://github.com/MetaMask/metamask-mobile/issues/2497#issuecomment-931132409_

**Comment by gantunesr** [comment]
Hey @afiiijooon, is this still happening in the last release?

**Comment by gantunesr** [comment]
I will close this issue for now, please open a new one you encounter this bug in the latest release
