### ISSUE TITLE
*eth_signTypedData_v4* do not work with any network where chainId != networkid

### ISSUE THREAD

**Issue by nikolaifedorov** [MetaMask/metamask-mobile#3385]
**Describe the bug**
When a user uses a network that chainId and networkId are different, for example: `Avalanche`, the user can not use `eth_signTypedData_v4`.

`eth_signTypedData_v4` do not work with any network where `chainId != networkid`.
See:
https://github.com/MetaMask/metamask-mobile/blob/develop/app/components/Views/BrowserTab/index.js#L613

**Screenshots**
![image](https://user-images.githubusercontent.com/1577651/140706968-377d3dff-4e02-4016-be37-53e896837cc5.png)

**Expected behavior**
A user can sign a message when using `eth_signTypedData_v4` while working with any network where `chainId != networkid`.

**Smartphone (please complete the following information):**
 - Device: iPhoneX
 - OS: iOS 14.8.1
 - App Version: MetaMask v3.6.0 (790)

-------------------------------------------------------------

**Comment by gantunesr** [comment]
Fix in #3685

**Comment by nikolaifedorov** [comment]
Thanks.
I will wait to merge #3685.
