### ISSUE TITLE
iOS can't load dApp with unknown network

### ISSUE THREAD

**Issue by nschwermann** [MetaMask/metamask-mobile#3391]
**Describe the bug**
when visiting website https://ebisusbay.xyz users are prompted with the following error
"We couldn't resolve that ENS name"
"EnslpfsResolver - no known ens-ipfs registry for chainID '25'"

**Screenshots**

![ios_issue](https://user-images.githubusercontent.com/891141/140798400-eb1478b3-f5a5-4170-a74a-7391541053a8.png)

**To Reproduce**
_Steps to reproduce the behavior_
1.  using iOS 
2. Click on 'Browser and enter url https://ebisusbay.xyz'
3. See error

**Expected behavior**
-Should render the website
-Should prompt user to add new chain if they click wallet icon (this also not working on android but works on desktop)

**Smartphone (please complete the following information):**
 - Device: iPhone
 - OS: unkown, have had several reports of this form users
 - App Version: also unkown

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user? Absolutely critical
- Add stats if available on % of customers impacted: at least 3 out of 50
- Is this visible to all users?
- Is this tech debt?

**Comment by iFrostizz** [comment]
Same for me on my dApp.

**Comment by BlevWasTaken** [comment]
Experiencing the same issue on Android 11. Started just now while on Uniswap on Optimism.

**Comment by gantunesr** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/MetaMask-Mobile-5f984938ddc0e4001d4b79cb/issues/MetaMask/metamask-mobile/3391?planning-poker) with ZenHub @Fatxx @plasmacorral
