### ISSUE TITLE
Android deep link not opening if app is already open

### ISSUE THREAD

**Issue by leon-do** [MetaMask/metamask-mobile#3395]
**Describe the bug**
_A clear and concise description of what the bug is_
https://www.youtube.com/watch?v=lBHlW-7DV6E

**Screenshots**
_If applicable, add screenshots or links to help explain your problem_
https://www.youtube.com/watch?v=lBHlW-7DV6E

**To Reproduce**
_Steps to reproduce the behavior_
1. Open mobile browser (chrome) with deep link 1 (google)
2. This opens metamsk app > metamask browser > google  :thumbsup:
3. BUT if i go back to mobile browser (chrome) and open link 2 (youtube)
4. It will open metamask app > metamask browser > stays on google :thumbsdown:

**Expected behavior**
_A clear and concise description of what you expected to happen_
Expected to open link and redirect to the correct page.

**Smartphone (please complete the following information):**
 - Device: Google Pixel 3a
 - OS: Android
 - App Version [e.g. 1.0.0] - v3.6.0

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by sethkfman** [comment]
@leon-do  Thank you for documenting the issue. We have fixed the issue and it will be applied to the next mobile release. I will follow up on the release date once I have confirmation.

**Comment by leon-do** [comment]
@sethkfman thank you so much!

**Comment by julia1981** [comment]
This issue is really important!

**Comment by hdeppert** [comment]
Experiencing the same issue. When will v3.6.1 be finally released?

**Comment by Vlakdo** [comment]
Please we need this, thank you!

**Comment by sethkfman** [comment]
3.7.0 is being rollout over this week. 

If you have an Android device you can get access the latest release immediately via the release notes: https://github.com/MetaMask/metamask-mobile/releases/tag/v3.7.0
