### ISSUE TITLE
iOS deep link not opening Unity App

### ISSUE THREAD

**Issue by leon-do** [MetaMask/metamask-mobile#3399]
**Describe the bug**
_A clear and concise description of what the bug is_
https://www.youtube.com/watch?v=5wO2k7XnJpA

**Screenshots**
_If applicable, add screenshots or links to help explain your problem_
https://www.youtube.com/watch?v=5wO2k7XnJpA

**To Reproduce**
_Steps to reproduce the behavior_
1. Open chrome browser on iOS with deep link (in video) https://leon-do.github.io/unity-deeplink-example/
2. This opens the unity app 👍 
3. BUT if I open metamask mobile browser on iOS, the link will not open

Note: deep link does not work on iOS but works on android.

**Expected behavior**
_A clear and concise description of what you expected to happen_
Expected to open the same link similar to chrome browser.

**Smartphone (please complete the following information):**
 - Device: iPhone12
 - OS: 14.7.1
 - App Version [e.g. 1.0.0] - v3.6.0

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by leon-do** [comment]
Similar to https://github.com/MetaMask/metamask-mobile/issues/3395

@sethkfman

**Comment by julia1981** [comment]
Same here!

**Comment by hdeppert** [comment]
I can confirm the issue. Can you give an ETA for the fix?

**Comment by sethkfman** [comment]
@hdeppert @leon-do Can you provide me with an example app I can get on the App Store?

**Comment by leon-do** [comment]
@sethkfman 

Here's an example:
https://leon-do.github.io/deeplink-examples/

Open this on Android > Metamask Mobile > Browser > Facebook Link. This Works
Open this on iOS > Metamask Mobile > Browser > Facebook Link. This does not work

Source:
https://github.com/leon-do/deeplink-examples/blob/main/index.html

**Comment by sethkfman** [comment]
@leon-do Thanks for the support. This will be a bigger effort that we need to investigate. Deep linking works different in the MetaMask mobile browser than other browsers. We will be looking into this issue over the next few weeks and will continue to update you.

**Comment by leon-do** [comment]
This bug is also happening with android v3.7.0

https://github.com/MetaMask/metamask-mobile/releases/tag/v3.7.0

**Comment by cryptodev0** [comment]
The same issue

**Comment by hankdangerfield** [comment]
Please fix this Metamask the crypto world needs this

**Comment by moheydy** [comment]
I have same issue please fix this bug we need this

**Comment by lim64952** [comment]
@sethkfman What's the current status now? Any new updates?

**Comment by ilmarioranen** [comment]
I think this bug is a critical hindrance for the mobile + web3 ecosystem and hope it gets treated as such and not forgotten.

**Comment by Ali-QS** [comment]
This should be of highest priority, please fix it asap because my team and hundreds if not thousands of other developers are in need of this, thank you.

**Comment by Asw-S93** [comment]
Please make the mobile branch and the Unity scene itself newbie-friendly, thanks!

**Comment by smihaylov1986** [comment]
Hi guys. I have built exactly the same mobile demo as on the youtube videos ( walletconnect scene and sendtx prefab in the next scene) . The wallet connects perfectly , but when I click SendTX it opens Metamask but doesn't initiate any transaction request. Build is on Android
