### ISSUE TITLE
NFT asset display error, probably a cache issue.

### ISSUE THREAD

**Issue by GoDotDotDot** [MetaMask/metamask-mobile#3406]
**Describe the bug**
I found that when I have more than 2 addresses with NFT on the Android side, then the cache situation occurs. For example, the wallet has 3 addresses, A, B and C. When both A and B have NFT assets, switching between A and B results in a wrong display of NFT assets for A and B. No problem when switching to C, C address does not have any NFT assets.

**Screenshots**
Address A: 
![image](https://user-images.githubusercontent.com/18232635/141340110-77586379-9f1d-443f-b666-c86e1e531a57.png)

Address B:
![image](https://user-images.githubusercontent.com/18232635/141340494-541581c1-0d99-403e-93f2-0586cb199340.png)

Address C:
![image](https://user-images.githubusercontent.com/18232635/141340182-aee7dae7-39b2-4d4a-ab7c-001bec9fd105.png)

**To Reproduce**
_Steps to reproduce the behavior_

**Expected behavior**
Switching to address A displays the NFT assets under address A. Switching to address B displays the NFT assets under address B.

**Smartphone (please complete the following information):**
 - Device: iPhone 11 Pro
 - OS: iOS 15.0
 - App Version: 3.6.0
 
![image](https://user-images.githubusercontent.com/18232635/141340764-71d6872e-f666-4981-99c2-0d867a91abf6.png)

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by GoDotDotDot** [comment]
In fact, address A has only one NFT asset.
![image](https://user-images.githubusercontent.com/18232635/141341278-002498c3-0a31-4810-b4e4-dd5f5c587d0a.png)

The rest are the assets of address B.

**Comment by gantunesr** [comment]
Thanks for reporting this issue @GoDotDotDot, we're taking a look into this problem and I will follow up on the solution and the release in which it'll be included

**Comment by GoDotDotDot** [comment]
I thought I'd try to debug it, too. @gantunesr

**Comment by GoDotDotDot** [comment]
> Thanks for reporting this issue @GoDotDotDot, we're taking a look into this problem and I will follow up on the solution and the release in which it'll be included

I opened a PR and you can review it if you have time.  https://github.com/MetaMask/metamask-mobile/pull/3428  @gantunesr

**Comment by gantunesr** [comment]
Hey @GoDotDotDot, I have reviewed and tested your PR and this development could solve this issue but it would introduce another bugs. We have already found the origin of this bug in the controllers module and a fix is under development right now

**Comment by GoDotDotDot** [comment]
> Hey @GoDotDotDot, I have reviewed and tested your PR and this development could solve this issue but it would introduce another bugs. We have already found the origin of this bug in the controllers module and a fix is under development right now

Yes, according to my pr:

> I have noticed that the controller repository has been updated to 19.0, but Metamask-mobile is still using 18.0. I think the best thing to do is to modify the AssetsDetectionController.detectAssets method and update the collectibleContracts and collectibles attr according to the changing of address. But the current solution is also acceptable.

I also found this problem because I was a bit confused about the version number of controller module, so I didn't deal with it. Thank you. @gantunesr

**Comment by gantunesr** [comment]
Hi @GoDotDotDot, thank you for your input in this issue! Here's an update on the current development.

There was two problems related to this issue, the first one was the wrong assignation of NFTs to different account and/or networks, the solution for this is in the PR #3458 which will be included in the v3.8.0.

The second issue is about showing NFTs which the user is not the owner, this development will be addressed in the ticket [3444](https://github.com/MetaMask/metamask-mobile/issues/3444)

**Comment by GoDotDotDot** [comment]
> Hi @GoDotDotDot, thank you for your input in this issue! Here's an update on the current development.
> 
> There was two problems related to this issue, the first one was the wrong assignation of NFTs to different account and/or networks, the solution for this is in the PR #3458 which will be included in the v3.8.0.
> 
> The second issue is about showing NFTs which the user is not the owner, this development will be addressed in the ticket [3444](https://github.com/MetaMask/metamask-mobile/issues/3444)

thx.

**Comment by gantunesr** [comment]
I'll close this issue for now. For updates check #3444
