### ISSUE TITLE
Consistent error designs

### ISSUE THREAD

**Issue by omnat** [MetaMask/metamask-mobile#341]
### Why?

- **[Error recovery:](https://www.nngroup.com/articles/slips/)** When the app behaves in an unexpected way, the user should know what is happening and how to get unstuck and reach their initial goal.
- **[Error prevention:](https://www.nngroup.com/articles/error-message-guidelines/)** When a user is doing unusual actions, the app should nudge the user towards the expected behavior, or at least alert them gently.

**Designs/ Figma file:** https://www.figma.com/file/aWgwMrzdAuv9VuPdtst64uuw/MetaMask-Design-System?node-id=4218%3A3234

**List of errors:** https://docs.google.com/spreadsheets/d/195Vw7sJcAeIzJFrpH1mE7MNVtb8tyPTJXADUvv4GQ3A/edit#gid=0

### Archive
Scenarios

- How to avoid sending transactions which will likely be blocked (not getting confirmation for long because another transaction is first in queue)
- (Alert) When user is paying too high gas amounts (e.g., $1 gas for $1 amount)
- (Alert) When user sending tx to themselves
- (Alert) When user sending tx to a token / contract address #338 
- (Constraint) When user sending tx to invalid address #5587
- When a tx fails #321 
- When there's a system error, like offline #293

**Comment by omnat** [comment]
https://github.com/MetaMask/metamask-extension/issues/10332

^ extension error design issue

**Comment by mobularay** [comment]
Closing due to move to Notion page: https://www.notion.so/7af6f9afb8634469ac881acb0c9fd9b4?v=ed13daa0b65543a5b045c4fb998510d0&p=6678cbbdd72547ca9f84f5e07fc4b1e2
