### ISSUE TITLE
Walletconnect support unreliable

### ISSUE THREAD

**Issue by mobilekosmos** [MetaMask/metamask-mobile#3415]
**Describe the bug**
Using the walletconnect kotlin sample app, connecting may work the first time, then disconnect and try to connect again and metamask simply won't prompt anything. This happens also with another own implementation, I'm having a nightmare testing my dapp with metamask, sooooooooooooooooo unreliable. I must uninstall it each time I need to test the connection to the wallet otherwise the prompt will simply not appear. Also starting transactions will only work the first time right after linking my app to metamask, then I close metamask and try to send a transaction again no prompt at all.
Also the sessions seams to get dirty, after working a few hours you have many sessions with the same app in the list of sessions inside metamask, and despite you uninstalled the other app there are still sessions being listed which you can "close".

**To Reproduce**
_Steps to reproduce the behavior_
Try the sample from walletconnect https://github.com/mobilekosmos/kotlin-walletconnect-lib/tree/master/sample/app
- Connect and disconnect few times, and try to send a transaction a few times, you will se that metamask most of the time won't react.

**Smartphone (please complete the following information):**
 - Device: Galaxy S9
 - OS: Android 10
 - App Version: 3.6.0

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by mobilekosmos** [comment]
You don't event need to use the linked walletconnect sample to reproduce the issue, simply try it with the uniswap website:
1. open app.uniswap.org
2. Select Connect Wallet
3. Select WalletConnect
4.  Select Mobile
5. Select Metamask

Metamask opens and nothing happens.

**Comment by gantunesr** [comment]
Hey @mobilekosmos, we're doing some upgrades and fixes to our wc integration, this issues should be fixed in future releases.

Related to #3583 , #3552 , #3566 , #3570

**Comment by lightspect** [comment]
Is the issue fixed in the current version 4.2.2? I still cannot get the connect prompt to show whenever I access Metamask from another app or from the web browser.

- Device: Pixel 4
- OS: Android 11
- App Version: 4.2.2
