### ISSUE TITLE
No web3 / ethereum injected into iframes

### ISSUE THREAD

**Issue by jbrumwell** [MetaMask/metamask-mobile#3417]
**Describe the bug**
This looks to have been addressed here https://github.com/MetaMask/metamask-mobile/issues/1154 but is failing in our tests

**To Reproduce**
1. Try to connect to metamask through an iframe on metamask mobile

**Expected behavior**
Should be able to connect and process transactions through an iframe as is the case with the extension

**Smartphone (please complete the following information):**
We have tried multiple phones with the latest metamask mobile installed

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by eltNEG** [comment]
I am having the same issue. My iframe is not able to connect to metamask on mobile. It works fine with the metamask extension

**Comment by nicoelzer** [comment]
Experiencing the same issue, Not working on Mobile, with extension on Desktop it works

**Comment by ZaikinaEvgeniya-2** [comment]
Any updates?
working fine with `window.ethereum` on Desktop,
but on mobile `window.ethereum` is empty

**Comment by tradephonic** [comment]
Same issue, is anyone looking at this?

**Comment by jcurbelo** [comment]
Any updates?

**Comment by Snugface** [comment]
I can confirm this still happens with MetaMask version 1.0.11 on Android 7

**Comment by TmLev** [comment]
Just wanted to let the maintainers know that this issue still persists.
