### ISSUE TITLE
Upgrade to React Native 0.66.3

### ISSUE THREAD

**Issue by Cal-L** [MetaMask/metamask-mobile#3425]
### **Description**

Upgrade React Native from 0.63.4 -> 0.66.3
Few things this addresses:
- Improved Hermes + support on iOS (huge bundle performance improvements)
- Also upgrades Android SDK 30, required by Google Play Store
- Better support for Apple M1 machines

### **Technical Details**

- Upgrade React Native
- Upgrade dependencies (libraries and deprecations)
- Use [upgrade guide](https://react-native-community.github.io/upgrade-helper/?from=0.63.4&to=0.66.3) as reference

### **Acceptance Criteria**

- Samsung keyboard still works
- App still functions the same as pre-upgrade
- Scrollable tab views still scroll (Example: On wallet screen between tokens and NFTs)
- Text input still avoids keyboard
- Double check Android (Android required more configuration for upgrade)

### **References**

- RN Diff - https://react-native-community.github.io/upgrade-helper/?from=0.63.4&to=0.66.3

**Comment by mobularay** [comment]
https://consensys.slack.com/archives/CBW7S9FSN/p1641322383045200?thread_ts=1641321281.044900&cid=CBW7S9FSN

Hypothesis: this issue will be resolved when RN upgrade is complete. Under observation post V4.0.0 release for one sprint
