### ISSUE TITLE
help me storage 

### ISSUE THREAD

**Issue by codelzl** [MetaMask/metamask-mobile#3441]
i cant recover my account 
please help me 
i forget my recover wo
![117529363-10f97c00-af8c-11eb-8bd3-d0456f5dd4dd](https://user-images.githubusercontent.com/43309099/142824044-0a9c7f41-2300-440a-8665-9ed2b1f0503c.png)
rd

**Comment by sethkfman** [comment]
This is a duplicate issue. Please refer to issue #2652 and reopen if the issue persists.
