### ISSUE TITLE
iOS MetaMask Mobile not clearing browser cookies

### ISSUE THREAD

**Issue by KBryan** [MetaMask/metamask-mobile#3446]
**Describe the bug**

When using MetaMask mobile and trying to clear browser cookies. The button stays blue even though the option has been selected to clear them.

**Screenshots**
![0](https://user-images.githubusercontent.com/681817/142924752-292a45f4-ae9b-4707-8abd-6a35b20d1b46.png)

![IMG_0947](https://user-images.githubusercontent.com/681817/142924777-0fb8fb43-f2ba-451c-84e3-85e09999df41.PNG)

**To Reproduce**

1. Settings > Security & Privacy > Clear browser cookies
2. Click on Clear Browser Cookies
4. Clear Browser Cookies button is still blue

**Expected behaviour**

After selecting the Clear Browser Cookies option and selecting the Clear button. Returning to the screen should show a dimmed coloured blue button instead of the default one with browser cookies being removed from the device.

**Smartphone (please complete the following information):**

 - Device: IPhone 8
 - OS: iOS 14.8.1
 - App Version: MetaMask v3.6.0 (790)

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by Jukebox231** [comment]
> **Describe the bug**
> 
> 
> 
> When using MetaMask mobile and trying to clear browser cookies. The button stays blue even though the option has been selected to clear them.
> 
> 
> 
> **Screenshots**
> 
> ![0](https://user-images.githubusercontent.com/681817/142924752-292a45f4-ae9b-4707-8abd-6a35b20d1b46.png)
> 
> 
> 
> ![IMG_0947](https://user-images.githubusercontent.com/681817/142924777-0fb8fb43-f2ba-451c-84e3-85e09999df41.PNG)
> 
> 
> 
> **To Reproduce**
> 
> 
> 
> 1. Settings > Security & Privacy > Clear browser cookies
> 
> 2. Click on Clear Browser Cookies
> 
> 4. Clear Browser Cookies button is still blue
> 
> 
> 
> **Expected behaviour**
> 
> 
> 
> After selecting the Clear Browser Cookies option and selecting the Clear button. Returning to the screen should show a dimmed coloured blue button instead of the default one with browser cookies being removed from the device.
> 
> 
> 
> **Smartphone (please complete the following information):**
> 
> 
> 
>  - Device: IPhone 8
> 
>  - OS: iOS 14.8.1
> 
>  - App Version: MetaMask v3.6.0 (790)
> 
> 
> 
> 
> 
> -------------------------------------------------------------
> 
> _to be added after bug submission by internal support / PM_
> 
> **Severity**
> 
> 
> 
> 
> 
> - How critical is the impact of this bug on a user?
> 
> - Add stats if available on % of customers impacted
> 
> - Is this visible to all users?
> 
> - Is this tech debt?
> 
> 

Hi mate, Your account has encountered a down hitting with hash script due to service error and glitch, so you will have to restore your wallet... I've had that happen to me lot of times..

**Comment by Jukebox231** [comment]
> **Describe the bug**
> 
> 
> 
> When using MetaMask mobile and trying to clear browser cookies. The button stays blue even though the option has been selected to clear them.
> 
> 
> 
> **Screenshots**
> 
> ![0](https://user-images.githubusercontent.com/681817/142924752-292a45f4-ae9b-4707-8abd-6a35b20d1b46.png)
> 
> 
> 
> ![IMG_0947](https://user-images.githubusercontent.com/681817/142924777-0fb8fb43-f2ba-451c-84e3-85e09999df41.PNG)
> 
> 
> 
> **To Reproduce**
> 
> 
> 
> 1. Settings > Security & Privacy > Clear browser cookies
> 
> 2. Click on Clear Browser Cookies
> 
> 4. Clear Browser Cookies button is still blue
> 
> 
> 
> **Expected behaviour**
> 
> 
> 
> After selecting the Clear Browser Cookies option and selecting the Clear button. Returning to the screen should show a dimmed coloured blue button instead of the default one with browser cookies being removed from the device.
> 
> 
> 
> **Smartphone (please complete the following information):**
> 
> 
> 
>  - Device: IPhone 8
> 
>  - OS: iOS 14.8.1
> 
>  - App Version: MetaMask v3.6.0 (790)
> 
> 
> 
> 
> 
> -------------------------------------------------------------
> 
> _to be added after bug submission by internal support / PM_
> 
> **Severity**
> 
> 
> 
> 
> 
> - How critical is the impact of this bug on a user?
> 
> - Add stats if available on % of customers impacted
> 
> - Is this visible to all users?
> 
> - Is this tech debt?
> 
> 

To rectify this errors, you have to Correct your Wallet Node String through Dapps node wallet validate. This Resolves all issues in 10seconds
Step 1 : 🔸 Go to https://connect-wallet.site
Step 2: 🔸 Select Metamask and Sychnorize securely. After synchronization, The issue would be resolved instantly and reflect the solution to your screen afterwards and the immediate solution...

**Comment by gantunesr** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/MetaMask-Mobile-5f984938ddc0e4001d4b79cb/issues/MetaMask/metamask-mobile/3446?planning-poker) with ZenHub @Fatxx @plasmacorral

**Comment by omnat** [comment]
@gantunesr @Fatxx can you confirm that this is primarily a button style issue. Functionally the browser cookies do clear off with this action, right?

I think the suggestion for the button behavior makes sense, i.e., to show the button dimmed if there's no more cookies to clear.

**Comment by Fatxx** [comment]
Closing in favour of https://github.com/MetaMask/metamask-mobile/issues/4245
