### ISSUE TITLE
Cannot enter Chinese characters on the Android version （v3.6.0）

### ISSUE THREAD

**Issue by yuhai-yang** [MetaMask/metamask-mobile#3448]
**Describe the bug**
Open the dapp url in the browser, unable to enter Chinese in the input tag

**Screenshots**
_If applicable, add screenshots or links to help explain your problem_

**To Reproduce**
_Steps to reproduce the behavior_
1. Go to 'Any website with an input tag'
2. Click on 'input tag' and enter "你好"
3.
4. See error：Nothing happened.No characters were entered

**Expected behavior**
_A clear and concise description of what you expected to happen_

**Smartphone (please complete the following information):**
 - Device: [xiaomi k40]
 - OS: [Android 10]
 - App Version [V3.6.0] - find version number in app from Settings > About MetaMask

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by yuwiggin** [comment]
Same issue on 
Device: [Huawei honor]
OS: [Android 9]
App Version [V3.7.0]

**Comment by yuwiggin** [comment]
Same issue on 
Device: [Huawei honor]
OS: [Android 9]
App Version [V3.7.0]

**Comment by yuwiggin** [comment]
Any progress on this issue? When will it be fixed?

**Comment by tommasini** [comment]
Hello, could you please update your app version? I am being able to enter Chinese characters.
@yuwiggin @yuhai-yang

**Comment by tommasini** [comment]
I'm closing this issue, if this happens again, please open another issue.
