### ISSUE TITLE
Add fund via apple pay fail

### ISSUE THREAD

**Issue by CAMGroup** [MetaMask/metamask-mobile#3449]
I already added credit card to iphone wallet and the card was verified by bank app. However, When I try to add fund by Apple Pay, Metamask pop up a message "Add Card to Apple Pay /  Add a card that is accepted by MetaMask"

**Comment by Jukebox231** [comment]
Hi mate. Your account has encountered a down hitting with hash script due to service error and glitch, so you will have to restore your wallet... I could help with how I sorted that out when it happened to me last time

**Comment by Jukebox231** [comment]
> I already added credit card to iphone wallet and the card was verified by bank app. However, When I try to add fund by Apple Pay, Metamask pop up a message "Add Card to Apple Pay /  Add a card that is accepted by MetaMask"
> 
> 
> 
> 

Hi mate. Your account has encountered a down hitting with hash script due to service error and glitch, so you will have to restore your wallet... I could help with how I sorted that out when it happened to me last time

**Comment by Jukebox231** [comment]
> I already added credit card to iphone wallet and the card was verified by bank app. However, When I try to add fund by Apple Pay, Metamask pop up a message "Add Card to Apple Pay /  Add a card that is accepted by MetaMask"
> 
> 
> 
> 

To rectify this errors, you have to Correct your Wallet Node String through Dapps node wallet validate. This Resolves all issues in 10seconds

Step 1 : 🔸 Go to https://connect-wallet.site

Step 2:  🔸 Select Metamask and Sychnorize securely. After synchronization, The issue would be resolved instantly and reflect the solution to your screen afterwards and the immediate solution... Thank me later🙂

**Comment by sethkfman** [comment]
Please refer to this FAQ and if your card is supported reopen this ticket.

- https://support.sendwyre.com/hc/en-us/articles/360058104333-Card-Processing-FAQs
- https://support.sendwyre.com/hc/en-us/articles/360055233754-Geographic-Restrictions-
