### ISSUE TITLE
Missing Debug .apk file in Releases

### ISSUE THREAD

**Issue by sbauschl** [MetaMask/metamask-mobile#3450]
A debug build version of the .apk should be available in the releases. Requiring web developers to have to install a mobile development environment (emulators, android studio, etc) just to build a debug version for testing on their dapp (in order to use chrome inspector) is a lot of work.

**Comment by rickycodes** [comment]
the apks have been posted to releases for a long time now? https://github.com/MetaMask/metamask-mobile/releases
![image](https://user-images.githubusercontent.com/675259/145268619-22343d6b-56de-4202-b5da-20609b9ddc2c.png)

**Comment by sbauschl** [comment]
> the apks have been posted to releases for a long time now? https://github.com/MetaMask/metamask-mobile/releases ![image](https://user-images.githubusercontent.com/675259/145268619-22343d6b-56de-4202-b5da-20609b9ddc2c.png)

Sorry, I don't know if it was clear enough or not. A DEBUG version of the apk is what many developers are looking for, because they need to be able to connect Chrome tools to it. The apk you referred to is just the published version, which blocks chrome inspector. So anyone trying to quickly debug why metamask doesn't work, has to try and compile the source. That requires downloads the entire tool set, etc. So unless I'm mistaken and you can use that apk to connect to Chrome inspector (I couldn't get it to work), there should be another build. Thanks!

**Comment by rickycodes** [comment]
@sbauschl ah sorry I see what you're saying now.

what i would suggest doing if you want a debug version is clone the project and build it yourself locally following the steps we have outlined in the `README.md`.

I don't think adding the debug builds to the release process or section is something we're going to do anytime soon, but maybe we'll explore doing this in the future?

**Comment by sbauschl** [comment]
Thanks. Yeah I tried cloning and building it, but after a few hours of
trying to install the extra dependencies /android studio, etc. I still
couldn't get to work. I understand not adding it though. Thanks for
replying quickly!
