### ISSUE TITLE
Metamask hacked. They know the secret phrase

### ISSUE THREAD

**Issue by kir1010** [MetaMask/metamask-mobile#3466]
I need this wallet, I can't change it. Is it possible to change the secret phrase?

**Comment by qiyufeng** [comment]
You may have downloaded a fake wallet

**Comment by babski123** [comment]
> I need this wallet, I can't change it. Is it possible to change the secret phrase?

You can change a secret phrase afaik, you can however create a new wallet with a new secret phrase, just transfer your assets over to it.

**Comment by kir1010** [comment]
I staked the tokens of the launchpad platform on this wallet...

**Comment by gantunesr** [comment]
Hi @kir1010, we don't store secret phrases and private keys from our users and, as @babski123 pointed out, its not possible to change your secret phrase.

I think its better for you to contact our [customer success team](https://metamask.zendesk.com/hc/en-us) so they can give you a better support with your issue. And remember we'll never ask you for any secret phrase or any sensitive data, so please, never share it.
