### ISSUE TITLE
[IMPROVEMENT] Refactor authentication logic

### ISSUE THREAD

**Issue by Cal-L** [MetaMask/metamask-mobile#3476]
### **Description**

We need to refactor our authentication logic to make it more robust and testable. Currently, much of the auth check logic lives in the Login screen, which requires the Login screen to be mounted for the app to work (should be the other way around). Some redundant logic also exists around initial auth check vs login CTA, which we will consolidate in the refactor. Proposal is to pull out auth business logic into an `AuthService`, which will handle auth between app states + expose log in and log out logic for any components to consume. Refer to `ReviewManager.ts.ts` as an existing example of how this will be architected.

### **Technical Details**

- Pull authentication logic from `Login.js` to new service named `AuthService.ts`
- May have to handle auth status between app states through use of `AppState` module
- Replace all instances listed below to use functions from `AuthService.ts`
   - onboarding (create account)
   - onboarding (import account)
   - log in
   - log out
   - change login methods(remember me, biometric)
   - change password
- Initialize `AuthService`, either in `Root` or `App` file
- TBD: Mock AuthService for test cases?

### **Acceptance Criteria**

- Usual login test cases with and without biometrics
  - Include biometric (fingerprint) being present, but disabled in app level settings.  Toggle `Sign in with Biometrics` to OFF and `Sign in with device PIN` to ON. Ensure that fingerprint does NOT grant access.
  
- Metrics to add to user profile properties:
  - ‘Remember Me’ setting: ON or OFF
  - ‘Biometrics’ setting: ON or OFF
  - ‘Password’ set: YES or NO

**Notion Doc**
https://www.notion.so/Proposal-e4fea54310874b2c98d36ca2161864ac

**Comment by sethkfman** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/MetaMask-Mobile-5f984938ddc0e4001d4b79cb/issues/MetaMask/metamask-mobile/3476?planning-poker) with ZenHub @blackdevelopa @cortisiko

**Comment by plasmacorral** [comment]
Added additional acceptance criteria around disabling biometric and enabling device pin.

**Comment by chrisleewilcox** [comment]
Closing, PRs have been merged.
