### ISSUE TITLE
Browser header input keeps on collapsing

### ISSUE THREAD

**Issue by cortisiko** [MetaMask/metamask-mobile#3486]
**Describe the bug**
If a user were to tap on the header in the browser then tap on "cancel" immediately, the browser gets into a funky state. Every time you tap the browser header again, it collapses immediately. 

 
**Screenshots**
See [here](http://recordit.co/7O7zkDLpOR)
**To Reproduce**
1. create/import your wallet
2. tap on the burger menu to open up the drawer
3. tap on the browser
4. while in the browser tap on the headers. then immediately tap on the "cancel" button
5. tap on the browser header again. Notice you are unable to input anything. 

**Expected behavior**
A user should be able to enter some text in the browser even after the user taps on "cancel" 

**Smartphone (please complete the following information):**
 - App Version [3.7] 

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by Fatxx** [comment]
@cortisiko can't reproduce it anymore. Can you check if this is still happening?

**Comment by Fatxx** [comment]
@cortisiko  can't reproduce it anymore. Can you check if this is still happening?

**Comment by cortisiko** [comment]
closing because I cannot reproduce. I will reopen if the issue surfaces again
