### ISSUE TITLE
Metamask not detected on iOS device due to Content-Security-Policy

### ISSUE THREAD

**Issue by shivam-ln** [MetaMask/metamask-mobile#3489]
I have created a website which uses meta mask to connect with binance mainnet and binance testnet. On Desktop device it is working fine.
For connecting with website on iPhone. i am using Metamask mobile app.
On android device it is detecting meta mask provider but on android device it is not detecting meta mask provider.
Website : Next.JS
I have added  Content-Security-Policy : 
```
"style-src 'unsafe-inline' 'self' *.googleapis.com *.jsdelivr.net *.gstatic.com; script-src 'self' *.google.com www.google.com *.googleapis.com *.jsdelivr.net jsdelivr.net *.gstatic.com; img-src 'self' data: blob:; media-src 'self' data: blob:; manifest-src 'self';font-src *.gstatic.com 'self' *.googleapis.com *.jsdelivr.net jsdelivr.net
```
When i remove above security policy from the code then on iPhone SE metamask mobile app will detects the etherum provider.
i am able to connect to metamask .i cannot remove content security policy so i have tried adding some domain.
i have tried addding following link to content-security-policy but didn't work :
```
metamask.io
*.metamask.io
binance.com
*.binance.com
```

How can i resolve meta mask provider not detected issue on mobile app with security policy ?

**Comment by kaanguru** [comment]
I confirm that any  Content-Security-Policy breaks metamask connection and detection.

**Comment by robertmclaws** [comment]
Is it possible to get this bumped up? Just had to pull our CSP for our entire site at the last second because it blocked our Minting dApp from loading in Metamask. Thanks!

**Comment by LoganAtCrypto** [comment]
Same issue here. It's sad that we have to disable CSP for an entire site to integrate with MetaMask.

**Comment by robertmclaws** [comment]
Even more sad that it has been so long without any information. @rickycodes any advice?

**Comment by robertmclaws** [comment]
@gantunesr Question: is the Metamask team going to prioritize working on CSP?

**Comment by robertmclaws** [comment]
Is anyone going to do anything about this?

**Comment by hskang9** [comment]
Csp policy disables logging in with metamask too.

**Comment by hskang9** [comment]
I think this is related to script-src https://github.com/blockscout/frontend/pull/1167/files
