### ISSUE TITLE
eth_accounts call only responds with the initially loaded account

### ISSUE THREAD

**Issue by FrederikBolding** [MetaMask/metamask-mobile#3496]
**Describe the bug**
It seems that calling `eth_accounts` from a DApp only responds with the selected address which was selected when **loading** the page. Because the middleware relies on the props here: https://github.com/MetaMask/metamask-mobile/blob/ce746d97ac831bd8d69258cb0bd160daa32f4ee1/app/components/Views/BrowserTab/index.js#L429-L434

Those props are not updated inside the middleware when the selected address changes and therefore the `eth_accounts` returns an unexpected value.

This seems like a bug to me, but if this is intended let me know. If it is intended, how is a DApp supposed to request this new information?

I will open a small PR that seems to have fixed the issue locally, but will likely need input as to if it is an appropriate solution 😄   There may be other values stored in these props that should be fetched from elsewhere too! I.e. `privacyMode`.

**Screenshots**
_If applicable, add screenshots or links to help explain your problem_

**To Reproduce**
_Steps to reproduce the behavior_
1. Go to https://rc.app.mycrypto.com/
2. Click on MetaMask
3. Click on Connect
4. Click add in the sidebar to go add another account
5. Switch your selected address in the top left to another address than you used at first
6. Click on MetaMask
7. Click on Connect
8. Only the first address should be added

**Expected behavior**
I expect the `eth_accounts` call to reflect the current state of the wallet, so if I call `eth_accounts` after the selected address has been changed in MetaMask I would expect the new address to be returned.

**Smartphone (please complete the following information):**
Running `develop` branch on an iOS simulator.

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by gantunesr** [comment]
Solved in #3341
