### ISSUE TITLE
Some tokens when set as the "Conversion currency" not showing proper value

### ISSUE THREAD

**Issue by jakehaugen** [MetaMask/metamask-mobile#3498]
**Describe the bug**
Some currencies (tokens it looks like) when set as the “Conversion currency” shows “VALUE” + the abbreviation.

**Screenshots**
In these screenshots I had selected “PAY” and “BNT” as the “Conversion currency” in settings.
![image](https://user-images.githubusercontent.com/11967476/145435909-c7d4cb6a-9349-4374-966e-373499bc8b91.png)
![image](https://user-images.githubusercontent.com/11967476/145435934-45f6eb0b-5df9-40a0-8663-8867052a0eb1.png)

**To Reproduce**
1. Go to 'Settings > General'
2. Select 'BNT' as your 'Conversion currency'
3. Launch a transaction
4. See amount displayed as "VALUE BNT"

**Expected behavior**
It should show the value of the 'Conversion currency'.

**Smartphone (please complete the following information):**
 - Device: iPhone 12 Pro
 - OS: iOS 15.1.1
 - App Version: 3.7.1 (796)

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by gantunesr** [comment]
If the conversion rates fails, show an information pop-up.
