### ISSUE TITLE
Fix setting custom spent limit

### ISSUE THREAD

**Issue by Cal-L** [MetaMask/metamask-mobile#3499]
### **Description**

https://www.notion.so/Setting-the-pre-filled-custom-spend-limit-on-the-edit-permissions-of-an-approve-transaction-doesn-t-9642c2866f4e491f98875e42b8207c10

### **Technical Details**

- TBD

### **Acceptance Criteria**

- TBD

### **References**

- https://www.notion.so/Setting-the-pre-filled-custom-spend-limit-on-the-edit-permissions-of-an-approve-transaction-doesn-t-9642c2866f4e491f98875e42b8207c10

**Comment by cortisiko** [comment]
closing since the issue was fixed in https://github.com/MetaMask/metamask-mobile/pull/3863
