### ISSUE TITLE
Unable to switch from matic to main net after performing a swap

### ISSUE THREAD

**Issue by cortisiko** [MetaMask/metamask-mobile#3504]
**Describe the bug**
After performing a swap,  I went ahead and opened up the network list in the top nav, then switched my network. After attempting to switch networks nothing happens i.e. The network does not change.

_This only happens after you perform your FIRST swap. If i were to kill the app and relaunch it. Perform another swap i can change my network without any issues_. Keep in mind the bug does not appear on develop! Also in order to reproduce a second time this you would probably need a second device OR if using android to reproduce, you will need to clear the app data. 

**Screenshots**
See recording [here](http://recordit.co/bdHQIAJ29k)
**To Reproduce**

1. have a fresh install of the app. Either apk or testflight
2. import my SRP
3. go to chainlist and add matic
4. go to the wallet and perform a swap
5. do not kill the app. wait till the swap is completed
6. once you see the txn complete toast message
7. change your network from matic to mainnet.

**Expected behavior**
A user should be able to switch from matic to main net without any issues. 

**Smartphone (please complete the following information):**
 - App Version [e.g. 1.0.0] - find version number in app from Settings > About MetaMask

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by gantunesr** [comment]
Consult @wachunei about this bug
