### ISSUE TITLE
Connect Metamask Mobile (ios) to my own mobile app

### ISSUE THREAD

**Issue by aasswd** [MetaMask/metamask-mobile#3505]
### **Description**

Hi guys, I'm trying to use metamask mobile on ios as a signer to my own app, exactly like what Opensea app on ios does. However, the existing docs are too vague to follow (cmiimw, but the docs in the [metamask mobile section](https://docs.metamask.io/guide/mobile-best-practices.html#the-provider-window-ethereum) tells you how to connect using the browser in metamask ios, not your own app). It seems to me that Opensea app does not use WalletConnect, does anyone know how to achieve such functionality? Thanks.

**Comment by gantunesr** [comment]
Hey @aasswd, OpenSea does use WC to achieve this, are you still trying to solve this issue?

**Comment by aasswd** [comment]
> Hey @aasswd, OpenSea does use WC to achieve this, are you still trying to solve this issue?

Hi @gantunesr, I have figured out how to use WC to achieve my goal. So it seems that OpenSea modifies the UI?

**Comment by gantunesr** [comment]
Hey @aasswd, I'll close this issue for the moment, feel free to open new one if you need further help.

**Comment by andiskim** [comment]
@gantunesr @aasswd do you guys get an issue where the modal doesn't pop up on metamask when attempting to connect the second time?

**Comment by aasswd** [comment]
> @gantunesr @aasswd do you guys get an issue where the modal doesn't pop up on metamask when attempting to connect the second time?

I remember something like this happened to me. I reinstalled metamask and that seemed to solve my issue.

**Comment by andiskim** [comment]
@aasswd that did it. thank you!

**Comment by dash7ou** [comment]
@gantunesr man, what is that URI for?
 `https://metamask.app.link/wc?uri=`
