### ISSUE TITLE
How did you guys implement Injected wallet feature in Dapps Browser?

### ISSUE THREAD

**Issue by Awais887** [MetaMask/metamask-mobile#3510]
I want to implement the injected wallet popup in Dapp browser to connect wallet just like done in Metamask. Where it provides popup asking if you want to connect the wallet and retrieve user's wallet address in Dapp . How do you guys make the connection with user's wallet and the Dapps brower?

**Comment by gantunesr** [comment]
Hey @Awais887, I'm closing this issue for now, feel free to open a new one if you need more help.
