### ISSUE TITLE
window.ethereum injected inconsistently on Android Metamask app browser

### ISSUE THREAD

**Issue by rohendra** [MetaMask/metamask-mobile#3513]
**Describe the bug**
We have a PHP Laravel based application that works perfectly on Desktop in any browser using Metamask extension.
Same applications also works on iOS inside Metamask mobile browser.

Issue is with Android version of Metamask Mobile App.
User is authenticated via a post request, response is as expected but then when any other action is done, we are redirected to login screen again.
Session is maintained through cookies which are set at server side.

There seems to be something wrong with cookies or some headers not being sent in some requests.

window.ethereum is injected on unauthenticated routes but it is missing on authenticated routes. 

**Smartphone (please complete the following information):**
 - Device: Realme 6 Pro
 - OS: Android 11
 - App Version : 3.8.0

**Comment by lamberto15** [comment]
I have the same problem with android metamask. chainChanged works properly in desktop, but in mobile metamask not work. same with token burn, works in desktop but not in mobile.

**Comment by cquex** [comment]
Hey, having the same issue. Did anyone resolve this ?

**Comment by Fatxx** [comment]
Closing in favour of https://github.com/MetaMask/metamask-mobile/issues/3513
