### ISSUE TITLE
Telegram Login Widget doesn't work with MetaMask mobile

### ISSUE THREAD

**Issue by dban0001** [MetaMask/metamask-mobile#3514]
**Describe the bug**

Disclaimer: I'm not sure if this is actually a bug on MetaMask's side or on Telegram. However, I'm posting it here anyway to get some help.

The [Telegram Sign In Widget](https://core.telegram.org/widgets/login) currently does not work with MetaMask mobile. It works fine on desktop with the browser extension.

The issue is that the Telegram OAuth login flow breaks. I'm wondering if the metamask browser maybe doesn't send referrers or other headers most browsers send and Telegram expects. Or something about a missing web API which Telegram uses.

I don't know what the issue is but any thoughts or pointers would be already highly appreciate. I also need to figure out how to contact Telegram about this.

**Screenshots**
_If applicable, add screenshots or links to help explain your problem_

**To Reproduce**
_Steps to reproduce the behavior_
1. Add the [Telegram Sign In Widget](https://core.telegram.org/widgets/login) to your site
2. Sign into Telegram on MetaMask mobile browser
3. When you signed in with your details and are about to get redirect back, the 
4. See error "Bot domain invalid" (this error comes from the Telegram site)

![9DF8511F-CE95-4E68-9158-C4A60E9EB0EA_1_105_c](https://user-images.githubusercontent.com/15185720/146381414-81ccc67c-7fb2-47e3-9875-510461d72dfd.jpeg)

**Expected behavior**
No issues.

**Smartphone (please complete the following information):**
 - Device: iPhone 11 Pro
 - OS: iOS 15
 - App Version - 3.8.0 (801)

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by EugeneBugor** [comment]
@dban0001 have you got any ideas/solutions for the issue?

**Comment by dban0001** [comment]
I'm afraid I don't, it's a bit hard to say what goes wrong without knowing how this stuff works internally

**Comment by faizov** [comment]
I have this problem :(
