### ISSUE TITLE
Unable to load MetaMask Mobile from Shopify App

### ISSUE THREAD

**Issue by zadmarbella** [MetaMask/metamask-mobile#3521]
**Describe the bug**
We are currently integrating MetaMask in a Shopify App and we are seeing issues with the MetaMask mobile application not connecting the users wallets. We have isolated the issue with the MetaMask mobile. We are seeing the window.ethereum object get wiped out on the load. 

We are not seeing this behaviour on the Desktop Extension. 

Does anyone have any insights on this issue? 

**To Reproduce**
1. From a Shopify App with MetaMask integration Connect Wallet from Mobile App

Current Behaviour: 
Wallet is unable to connect

**Expected behavior**
Wallet is Connected to Shopify App

**Smartphone (please complete the following information):**
 - Device: iPhone/Android
 - OS: Any
 - App Version: 3.8.0

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by omnat** [comment]
Thanks @zadmarbella for raising this. 
To clarify, are you using integrating with MetaMask mobile via Wallet Connect? 

@gantunesr tagging for visibility

**Comment by bitcoinvsalts** [comment]
Hello @zadmarbella please contact at herve76@gmail.com I am interested in your integration and want to help.

**Comment by gantunesr** [comment]
Hi @zadmarbella, I'm trying to fix this issue in MetaMask but I can't reproduce it using other mobile apps that rely on WalletConnect. Can you provide step to reproduce your issue using the Shopify app?

**Comment by omnat** [comment]
Hi @zadmarbella any updates?

**Comment by zadmarbella** [comment]
@omnat 
yeah @gantunesr it only happens in the metamask app itself on mobile.

**Comment by zadmarbella** [comment]
@gantunesr / @andrepimenta  is it possible to get on a call?

**Comment by zadmarbella** [comment]
from @andrepimenta 

The reason why we think it's a problem from shopify website is because there is no error with the provider, it's simply not available to the page which makes us believe a shopify script is removing it or disabling it.
The workaround we recommend would be to use WalletConnect for now. We deprioritized the SDK but we are maintaining and improving WalletConnect.

**Comment by tommasini** [comment]
MetaMask SDK is [available](https://metamask.io/sdk/), so now it's possible to connect.

**Comment by zadmarbella** [comment]
@tommasini Is the metamask mobile issue resolved. What is the remedy?

**Comment by tommasini** [comment]
hey @zadmarbella, thanks a lot for your support!
 Instead of using wallet connect we can use the MetaMask SDK, due to previous comments, it seems a Shopify script is removing it or disabling the Window.ethereum, if you disagree, please explain why and we can re-open this issue to further investigation

**Comment by zadmarbella** [comment]
@tommasini So is the remedy to use the MetaMask SDK? Have you verified that this fixes the issue?

**Comment by zadmarbella** [comment]
@gantunesr right. So my understanding is that using the MetaMask SDK is the remedy for the issue. Just out of curiosity how is it able to connect now? Is there a commit we should be mindful of?
