### ISSUE TITLE
iPad / M1 Apple Silicon Support

### ISSUE THREAD

**Issue by j4nf4b3l** [MetaMask/metamask-mobile#3523]
**Describe the usability problem**
The MetaMask iOS App has no full-screen support for M1 Apple Silicon Macs and iPads.
There is absolutely no reason why it shouldn't be supported.
When self compiling, it works out of box with ticking the iPad support in Xcode settings...

Please fix that in your App in the iOS App Store...

Thanks :)

**Comment by gantunesr** [comment]
Hi @j4nf4b3l, this is duplicated in #3488.
