### ISSUE TITLE
Transaction response is not getting passed back to Dapp

### ISSUE THREAD

**Issue by alexanderMontague** [MetaMask/metamask-mobile#3524]
### **Description**

Hello, sorry if this is the wrong place to post this. I am just puzzled and looking for some more info!

Currently we interact with a contract using ethers, the user authenticates with an injected metamask provider, and everything is dandy. What my problem is now is I am authenticating users on mobile with Wallet Connect, and transactions are _succeeding_, but I do not get any response to update my UI.

Here is an example (names have been replaced but this contract WORKS and is functioning completely fine on desktop)

```javascript
const tx = await signedDemoContract.customContractMethod(PARAM);

console.log("TX", tx);

const txReceipt = await tx.wait();

console.log("TX RES", txReceipt);
```

What happens on mobile is when we hit the contract interaction, the user is redirected to their mobile wallet (I have tested with mobile metamask) and they are given the option to approve or reject the transaction. After approving, I wait on metamask and they give me a notification that the transaction succeeds. I can verify this by checking etherscan.

When I go back to my dapp, the first `console.log('TX')` does not even log. We don't even get to the waiting portion because the first transaction response does not return. So is this an issue in the way I am setting up the contract with ethers, or maybe a metamask/wallet connect problem? Sorry there are a lot of moving parts.

Super bizarre, but it's like Metamask is not even returning the transaction response. Any help is appreciated!!

### **Technical Details**

- Connecting using Wallet Connect
- Also using web3 React
- Redirects to Metamask just fine
- Transactions SUCCEEDS but does not return status to Dapp

**Comment by tab00** [comment]
Is this related to https://github.com/MetaMask/metamask-mobile/issues/1880 ?

My Dapp can't detect `approve` transaction rejection in MetaMask mobile app (but can in desktop browser extension).
