### ISSUE TITLE
Open deep link duplicate 5 or 9 tab

### ISSUE THREAD

**Issue by chaleomwat** [MetaMask/metamask-mobile#3525]
**Describe the bug**
im open deep link but metamask duplicate 5 tab or 9 tab, should be open 1 tab only

**Screenshots**
![Screenshot_2021-12-27-17-52-01-145_io metamask](https://user-images.githubusercontent.com/39171495/147465030-0fcd6c3f-83b7-4674-b3b3-631931a43569.jpg)

![Screenshot_2021-12-27-17-52-48-315_io metamask](https://user-images.githubusercontent.com/39171495/147465039-58495924-31b8-450c-a09b-c95ebfb29e5e.jpg)

**To Reproduce**
1. Generate deep link from [](https://metamask.github.io/metamask-deeplinks/)
2. Open deep link

**Smartphone (please complete the following information):**
 - Device: Android / IOS
 - OS: Android 11 / IOS 15
 - App Version: 3.8.0

**Comment by gantunesr** [comment]
Fix in PR #3570
