### ISSUE TITLE
Cant open Metamask in IOS

### ISSUE THREAD

**Issue by quangvinh-fetchtech** [MetaMask/metamask-mobile#3528]
1. Click Metamask Icon on Iphone
2. Buy 180 Trilion Tokens with very low price.
3. Back to Iphone Home Screen
4. Click Metamask Icon and stand there forerver
![267617487_335797414807659_3734031858928335380_n](https://user-images.githubusercontent.com/79433829/147740225-35a48548-47a1-413c-b53d-99f659bae2e1.jpeg)

**Comment by sethkfman** [comment]
@quangvinh-fetchtech  Can you please provide more detail in step 2

**Comment by Thoneschtv** [comment]
I logged in 2 days and it's stuck on this page as well.  Fix it for iphone 11 pro I can not wake up in the morning to access the app
![DC8C0AF8-70A0-4F0B-B5CE-EDCEDD9BC2D3](https://user-images.githubusercontent.com/97269017/148484724-b2a5da24-9c75-4a0f-9521-224cb76d2881.png)
@sethkfman

**Comment by Thoneschtv** [comment]
Metamask version 3.8.0
Phone ios 15.2
Network: Bsc

**Comment by Thoneschtv** [comment]
Please update the app fix it I can not access it @sethkfman

**Comment by quangvinh-fetchtech** [comment]
Phone ios 14.8
Network:ERC20

I can't access the app to check version now.
Please help fix.

**Comment by Thoneschtv** [comment]
Please suggest an app developer who can fix this problem
@sethkfman ![image](https://user-images.githubusercontent.com/97269017/148646376-a493caa6-be52-413a-b4f7-fda3b3903f3e.png)

**Comment by Thoneschtv** [comment]
wallet connected to many NFT games now inaccessible😪
@sethkfman

**Comment by Fadeli16** [comment]
Is this fixed? I have same issues too

**Comment by quangvinh-fetchtech** [comment]
Not fixed yet. I lost all my money for the Metamask application.

**Comment by Fadeli16** [comment]
Yes me too i have many fund in that wallet 😭

**Comment by gantunesr** [comment]
We're investigating the issue. **Don't re-install the app if you don't have your SRP** (Secret Recovery Phrase). If you do have your SRP, try re-installing the app and recovering your account.

**Comment by levin222** [comment]
I have the same error now !!!

**Comment by levin222** [comment]
ios 15.2
iphone13 
v 4.0.0

**Comment by levin222** [comment]
update to ios 15.3, it still don't work PLS fix it as soon as possible

**Comment by levin222** [comment]
> We're investigating the issue. **Don't re-install the app if you don't have your SRP** (Secret Recovery Phrase). If you do have your SRP, try re-installing the app and recovering your account.
> 
> 

Is there any way to solve this issue soon？ like a testflight version.

**Comment by quangvinh-fetchtech** [comment]
I am waiting for the fix. I can't remember the `secret recovery phrase`. I lost all my token.

**Comment by levin222** [comment]
Update to v4.0.1, still fail to open

**Comment by Fadeli16** [comment]
How much your balance guys? My balance in error metamask 10k$ and still cant open the apps ;(

**Comment by levin222** [comment]
I have 5k$. But I need to Ido at 3     Feb

**Comment by levin222** [comment]
Is that the data files lost finally?

**Comment by gantunesr** [comment]
@Fadeli16 @quangvinh-fetchtech @Thoneschtv v4.1.0 will be released during this week, can you verify is this issue persists

**Comment by gantunesr** [comment]
@levin222 is this v4.1.0?

**Comment by quangvinh-fetchtech** [comment]
Another problem i lost 7k usd because use this app.
![0AF8F5FA-5DBF-4B9C-B41F-57FE816090F7](https://user-images.githubusercontent.com/79433829/154378842-f483e8e9-e864-4cc6-be00-b5d8fa937bc5.png)

**Comment by levin222** [comment]
> @levin222 is this v4.1.0?

Yes it is v4.1.0

**Comment by levin222** [comment]
> @levin222 is this v4.1.0?

Do we lost our tokens forever ？

**Comment by levin222** [comment]
> verify

I try to find my key back like https://metamask.zendesk.com/hc/en-us/articles/360018766351-How-to-use-the-Vault-Decryptor-with-the-MetaMask-Vault-Data

But there is no string like that "{\\\\\\\\\\\\"cipher\\\\\\\\\\\\":\\\\\\\\\\\\"JaX8Z80QMzzqA4XMgPsUuleNLIuxvchXZ5q1SO9GO1kuNUmokUke06op9EF0ZU....

Why?
