### ISSUE TITLE
External App deep linking broken on Android 12

### ISSUE THREAD

**Issue by sethkfman** [MetaMask/metamask-mobile#3534]
**Describe the bug**
On android devices with OS 12 installed, deep links for the dapp browser only open MetaMask and not the dapp browser.

**Screenshots**
NA

**To Reproduce**
_Steps to reproduce the behavior_
1. Load this URL into the browser https://southern-bush-399.notion.site/DeepLink-Test-e9b159d196424926809848705ffa015f 
2. Select any of the links 
3. The link opens MetaMask but does not load the page in the MM browser

**Expected behavior**
Expect the MM browser to be loaded with the deep link site

**Smartphone (please complete the following information):**
 - Device: [Pixel 5]
 - OS: [12]
 - App Version [3.8.0]

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by omnat** [comment]
https://github.com/MetaMask/metamask-mobile/issues/3521
This is perhaps more related to web3 injection, but bringing this up for your visibility in case it intersects with what you are doing Fatia

**Comment by nwilging** [comment]
+1. Same issue, deep link will open the app but will not open the in-app browser or direct to the supplied link.

Samsung Galaxy s21 ultra 5g
Android 12
Metamask 3.8.0 (latest at time of writing)

**Comment by Kriskit** [comment]
Same here.

Android 12
Google Pixel 5
MetaMask 3.8.0

**Comment by djdabs** [comment]
Still having this issue

Android 12
Google Pixel 6
Metamask App 4.2.2

**Comment by TtheBC01** [comment]
Can devs do something?
