### ISSUE TITLE
[ENHANCEMENT] Make it easy for me to add custom networks

### ISSUE THREAD

**Issue by omnat** [MetaMask/metamask-mobile#3545]
### **Description**

Goal: make it easier to add a non-default network. 
Intended effect: Improved L2 experiences

### **Technical Details**
-   Support the following networks
  -   Infura supported networks:
    -   Arbitrum
    -   Optimism
    -   Palm
    -   Polygon
  -   Other popular networks:
    -   Avalanche
    -   Binance Smart Chain
    -   Fantom
    -   Harmony

### **Acceptance Criteria**

- Add 'Add network' button on Network modal
- Order added network lists of users differently: first all mainnets, and then testnets
- Show accurate network details for user consent
- Apply entry points, UI logic & cases as shown in design file
- (Stretch UX Improvement-Create ticket if not completed in this ticket) If network already added and user attempts to add custom network again check and prompt the user that it is already added (check against chain ID)

### **References**

- Design file: https://www.figma.com/file/wfOwLmE52OKY0bSrsQwHPL/Add-popular-custom-network?node-id=468%3A7325
(Saya designer contact)
- Notion link: https://www.notion.so/I-want-to-be-able-to-add-a-popular-custom-network-from-the-custom-network-switcher-modal-7f8c0ae131ea443694396bbf1a36aa1e [refer this to see list of network options to add 
- Sync with Barbara on latest list of networks (that are ready to add) and technical details (done listed above in tech details)

**Comment by sethkfman** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/MetaMask-Mobile-5f984938ddc0e4001d4b79cb/issues/MetaMask/metamask-mobile/3545?planning-poker) with ZenHub @blackdevelopa @cortisiko

**Comment by sethkfman** [comment]
Get design on existing network error message

**Comment by omnat** [comment]
@bschorchit Will update when this story is ready for work - finalizing a design component
@blackdevelopa ^

**Comment by bschorchit** [comment]
> (Stretch UX Improvement-Create ticket if not completed in this ticket) If network already added and user attempts to add custom network again check and prompt the user that it is already added (check against chain ID)

If the network already has been added, it should not appear on add network list. So this might not be needed, @omnat.

**Comment by omnat** [comment]
@bschorchit Will update the ticket with final copy and a design update (adding an icon for some networks) tomorrow (15th Feb) cc @blackdevelopa

**Comment by sethkfman** [comment]
@blackdevelopa Link to all network data: https://www.notion.so/I-want-to-be-able-to-add-a-popular-custom-network-from-the-custom-network-switcher-modal-7f8c0ae131ea443694396bbf1a36aa1e#8df62328b969482482ef9f97982ee8d1

**Comment by blackdevelopa** [comment]
@bschorchit is the imageUrl for these networks available?

**Comment by bschorchit** [comment]
> @bschorchit is the imageUrl for these networks available?

Only for [Optmism](https://github.com/ethereum-optimism/brand-kit/blob/main/assets/svg/Profile-Logo.svg)so far, which we got today. I've also added it to [Notion](https://www.notion.so/I-want-to-be-able-to-add-a-popular-custom-network-from-the-custom-network-switcher-modal-7f8c0ae131ea443694396bbf1a36aa1e#8df62328b969482482ef9f97982ee8d1). We're reaching to the teams to get the proper icons. Aiming to have them all by the end of the week.

**Comment by dokocat** [comment]
Just to be clear, this will allow users coming from apps (web and mobile via walletconnect) requesting the user connect via BSC for example, to have Metamask Mobile present the switch/add network modal as it is on web. Is that correct?

**Comment by sethkfman** [comment]
@omna We need to wait to release for March 28th I think this will be 4.5.0

**Comment by bschorchit** [comment]
There was a delay in extension and the new expected release is March 28th. If you're ready, do you want to release it first on mobile?
Infura requirement was not to release both at the same time, so we can check with them if it's ok to change the order. Proposing this just so extension doesn't block you if you're ready sooner. @sethkfman @omnat

**Comment by sethkfman** [comment]
Ah, yeah. If it is going to be that long I think we should release it. I was just finishing QA this week. 

Do we need to touch base with Infura about our QA testing?

WDYT? @omnat
