### ISSUE TITLE
WC deeplink bug with SDK

### ISSUE THREAD

**Issue by gantunesr** [MetaMask/metamask-mobile#3552]
**Describe the bug**
MetaMask app won't display the connect request when using the WC SDK.

**To Reproduce**
_Steps to reproduce the behavior_
1. Install and run the WC Swift example (https://github.com/WalletConnect/WalletConnectSwift-Example)
2. In the example app, try to connect by pressing 'Connect to WalletConnect'
3. A deeplink should open the MetaMask app

**Expected behavior**
The app should request the user authorization to connect with WC.

**References**

- https://github.com/MetaMask/metamask-mobile/issues/3521

**Comment by rommex** [comment]
I would second that: the MM iOS app is not discoverable via `metamask:` scheme any more for WC use case

**Comment by gantunesr** [comment]
Fixed in v4.2.0
