### ISSUE TITLE
GitHub sign-in errors out in Metamask browser

### ISSUE THREAD

**Issue by igrigorik** [MetaMask/metamask-mobile#3568]
**To Reproduce**
Using built-in Metamask browser (on Android):

1. Navigate to https://gitcoin.co/
1. Attempt GitHub sign-in flow
1. I'm reliably getting "Your browser did something unexpected..."

**Expected behavior**
Successful sign-in and redirect back to gitcoin.co

**Smartphone (please complete the following information):**
 - Device: Pixel 6
 - OS: Android 12
 - App Version: v3.8.0 (801)

**Comment by rickycodes** [comment]
closing because dupe of: https://github.com/MetaMask/metamask-mobile/issues/2207
