### ISSUE TITLE
project website cannot be opened in the built-in browser of Metamask on Android 

### ISSUE THREAD

**Issue by CHEN-MIMIMA** [MetaMask/metamask-mobile#3571]
### **Description**

My project website cannot be opened in the built-in browser of Metamask on Android phone, but it can be opened on ios phone
Who has this situation and how can I solve it？Thanks

![111](https://user-images.githubusercontent.com/97722664/149462504-33e24a9a-3e71-4bb4-96b0-1e64e63e429b.jpg)

**Comment by jim102550** [comment]
My project application can't be opened, have you solved it?

**Comment by CHEN-MIMIMA** [comment]
NO

**Comment by gantunesr** [comment]
Hey @CHEN-MIMIMA, can you provide more details about this? Do you have any website example that has this same issue?

**Comment by Fatxx** [comment]
Close because of inactivity and no additional information.

**Comment by weiliang903** [comment]
Similar problem, using [MetaMask deep link generator](https://metamask.github.io/metamask-deeplinks/#) , after the jump stays in the Wallet interface, and does not open in the browser, @Fatxx  you can try a few times, the problem does exist.
system: ios
MetaMask App: v4.1.0

**Comment by weiliang903** [comment]
This issue should be opened.

**Comment by weiliang903** [comment]
@Fatxx To reproduce the steps, the MetaMask app must be killed in the background.
However, if you open MetaMask and stay in the browser interface, you can open it normally.

**Comment by gantunesr** [comment]
Hi @weiliang903, thanks for reaching out. As it was mentioned in the previous comment, this issue was closed because it lacked information to be included in our development. I recommend you to open a new issue following our "Bug Report" template, you can link this issue in the new one as a reference.
