### ISSUE TITLE
NFT on polygon not automatically display after mint on the NFT tab

### ISSUE THREAD

**Issue by Nzenou** [MetaMask/metamask-mobile#3578]
### **Description**
Hello, 
I have created a collectible on Polygon Matic, and I don't understand why after mint, my nft are displaying on opensea but not on metamask, the only way to see them is to add them manually. 
Is it a way to be automatically displayed like on the ethereum network? 
Perhaps I have to add something to my smart contract? 
Can you help me with that please ? 🙏

**Comment by gantunesr** [comment]
Hey @Nzenou, the autodetect collectible feature is only available for Mainnet for the moment, this feature will be ready to use in other networks in the future.

**Comment by Nzenou** [comment]
hello @gantunesr when you said mainnet you talking about ethereum ? 
Because I have deploy my contract on the polygon mainnet

**Comment by gantunesr** [comment]
Yes, ethereum mainnet (chain ID = 1)

**Comment by Nzenou** [comment]
Do you know when you going to deploy this feature on  polygon matic ?

Thanks in advance

**Comment by gantunesr** [comment]
Hey, we don't have a defined timeline for this enhancement yet

**Comment by gantunesr** [comment]
I have included this to our discussion around the collectibles feature. I'll close this issue for now and open a new one with the corresponding development.
