### ISSUE TITLE
No message returned for message signing with WalletConnect

### ISSUE THREAD

**Issue by vibalater** [MetaMask/metamask-mobile#3580]
**Describe the bug**
Trying to sign message after connecting [wallet connect(v1.7.1)](https://github.com/WalletConnect/walletconnect-monorepo) with metamask but fail. Can connect and popup sign message popup while nothing returned after sign. Meanwhile cancel signing got a return.

I'm not very sure if it is a bug from metamask or wallet connect, but I cannot reproduce it using Rainbow Wallet, a sign message is returned.

**Screenshots**
_If applicable, add screenshots or links to help explain your problem_

**To Reproduce**
_Steps to reproduce the behavior_
1. Open Network tab in developer tool and filter the websocket connection
2. Go to https://wallet-connect-metamask1.vercel.app/ (Source code: https://github.com/vibalater/wallet-connect-metamask1)
3. Click connect and scan the QR code with MetaMask app
4. After connected, wait for sign message popup and then click either sign/cancel button
5. See the websocket message received.

**Expected behavior**
Expected a message received after clicking sign message, but nothing return.

**Smartphone (please complete the following information):**
 - Device: iPhone 8
 - OS: iOS 15.2
 - App Version 3.8.0(801)

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by addmorebass** [comment]
I am dealing with the same issue.

**Comment by gantunesr** [comment]
Fixed in PR #3685
