### ISSUE TITLE
[SDK] Refactor Deeplinks

### ISSUE THREAD

**Issue by andrepimenta** [MetaMask/metamask-mobile#3583]
ETA: 2 weeks

- Look at issues
- Start DeeplinkManager from scratch

DeepLink & WalletConnect Tasks and bugs (filter by deeplink)

- https://github.com/MetaMask/metamask-mobile/issues/1695
- https://github.com/MetaMask/metamask-mobile/issues/3580
- https://github.com/MetaMask/metamask-mobile/issues/3534
- https://github.com/MetaMask/metamask-mobile/issues/3552
- https://github.com/MetaMask/metamask-mobile/issues/3525
- https://github.com/MetaMask/metamask-mobile/issues/3521
- https://github.com/MetaMask/metamask-mobile/issues/3399
- https://github.com/MetaMask/metamask-mobile/issues/3395
- https://github.com/MetaMask/metamask-mobile/issues/3326
- https://github.com/MetaMask/metamask-mobile/issues/3216

Commits/PR:
- https://github.com/MetaMask/metamask-mobile/pull/3570
- https://github.com/MetaMask/metamask-mobile/pull/3566
- https://github.com/MetaMask/metamask-mobile/pull/3560
- https://github.com/MetaMask/metamask-mobile/pull/3220
- https://github.com/MetaMask/metamask-mobile/pull/3120
- https://github.com/MetaMask/metamask-mobile/pull/3627

**Comment by gantunesr** [comment]
I was working on a WC refactor in this branch: `fix/wallet-connect`

**Comment by andreahaku** [comment]
> I was working on a WC refactor in this branch: `fix/wallet-connect`

Awesome. I'll take a look at it as well and add to the above list. Thanks

**Comment by gantunesr** [comment]
Test dapp WC support: https://github.com/MetaMask/test-dapp/tree/wc-support

**Comment by gantunesr** [comment]
Related: https://github.com/MetaMask/metamask-mobile/issues/3546
