### ISSUE TITLE
[SDK] Enable dapps to import a provider

### ISSUE THREAD

**Issue by andrepimenta** [MetaMask/metamask-mobile#3588]
[Gather more feedback] Provider problem - 3 weeks (without QA): 

- Right now the provider was built to be injected. So we need to build a provider (using the same code) that can be imported. (Bring your own provider - search on slack)
- NPM package that dapps can install
- Implement a wrapper, so that when the provider is updated, this also gets updated
- Erik, Mark, DanF - Schedule a meeting with them and get their feedback about the best way to do this
Important to get it right from the beginning

**Comment by zadmarbella** [comment]
Would something like this help? 
https://github.com/0xProject/provider-engine

**Comment by andrepimenta** [comment]
Closing this for now to accommodate new priorities
