### ISSUE TITLE
Enable Dark Mode

### ISSUE THREAD

**Issue by Cal-L** [MetaMask/metamask-mobile#3604]
# Description
- Implement ability to switch between default (light), dark, and system themes

# Technical Details
- [x] In-app theme state should be stored in redux
- [x] Utilize React Native's Appearance API to access system theme
- [x] Use Context API to provide and consume colors within screens and components
- [x] Add button that opens action sheet to switch between themes in General Settings
- [x] Clean up context code in class components (Convert into hooks if necessary)
- [x] Use colors from `@metamask/design-tokens` library

# Acceptance Criteria
- [x] Ability to switch between in app and system theme
- [x] Theme should persist between app sessions (kill/reopen app)
- [ ] Analytics event for detecting theme settings (Reference NFT analytics)
- Ticket to track testing: #3869

**Comment by gantunesr** [comment]
@Cal-L Is this the same as #3556 ?
