### ISSUE TITLE
Grey border appears around the button when clicking on it (Android - swap) 

### ISSUE THREAD

**Issue by gantunesr** [MetaMask/metamask-mobile#3610]
**Describe the bug**
[PAPERCUTS] A grey border is showing up around a button in the swaps flow.

**Screenshots**
<img width="300" alt="Screen Shot 2022-01-20 at 16 19 52" src="https://user-images.githubusercontent.com/17601467/150407444-0245ff74-12f7-433e-b3aa-a43efffa2b88.png">

**To Reproduce**
_Steps to reproduce the behavior_
1. Go to the Amount screen in the swaps flow
2. See button with grey border

**Expected behavior**
The button shouldn't have a grey border

**Smartphone (please complete the following information):**
 - OS: Android

**Comment by Fatxx** [comment]
This can't be fixed only in spot,  `StyledButton` needs to be refactored into a different component structure which breaks the component API.

Meaning that the actual `containerStyles` property doesn't make sense anymore when it's consumed in other components.

**Comment by Fatxx** [comment]
@Cal-L do you have in mind to refactor this component in the future? Or should we sit to find a final solution for this issue?
