### ISSUE TITLE
Users have problem exiting the pop up when they are choosing currency in settings on Android

### ISSUE THREAD

**Issue by gantunesr** [MetaMask/metamask-mobile#3611]
**Describe the bug**
Users have problem exiting the pop up when they are choosing currency in settings on Android

**Screenshots**
<img width="425" alt="Screen Shot 2022-01-20 at 17 11 43" src="https://user-images.githubusercontent.com/17601467/150414611-9ba21101-db5f-4c3e-bb45-48c091517b31.png">

**To Reproduce**
_Steps to reproduce the behavior_
1. Go to Settings > General > Currency

**Expected behavior**
Users should be able to exit 

**Smartphone (please complete the following information):**
 - OS: Android

**Comment by gantunesr** [comment]
@omnat Adding a dismiss button to solve this issue requires a lot of effort for a sev3 bug. @Fatxx recommends displaying the selected option as the first one as a simpler solution.

If someone else has a different idea please comment it in this issue.

**Comment by omnat** [comment]
@blackdevelopa worked on this issue as well, tagging in case he did something else or has ideas. cc @mobularay 

>  @Fatxx recommends displaying the selected option as the first one as a simpler solution.
How would this fix the issue of users not being able to exit? 

> Adding a dismiss button to solve this issue requires a lot of effort for a sev3 bug. 
by dismiss button, you mean the cross on top right?

**Comment by gantunesr** [comment]
@omnat 
> How would this fix the issue of users not being able to exit?

Yes, since in android it's necessary for an user to select an option to close the currency list

> ...by dismiss button, you mean the cross on top right?

Yes

**Comment by omnat** [comment]
Fatia and I synced earlier. Lets go with his suggestion

**Comment by chrisleewilcox** [comment]
Do we know the specific mobile device that was having this issue?  I have a Samsung A42 Android and it has standard UI controls at the bottom of the screen that allow to go back to previous screen and it works fine on the currency picker select view. Regardless the selected currency is defaulting to the top of the picker component.
