### ISSUE TITLE
Why is OpenSea used as an indexer?

### ISSUE THREAD

**Issue by rygo6** [MetaMask/metamask-mobile#3615]
As some in the community have pointed out:
https://www.youtube.com/watch?v=_1PSvqho8UE
https://moxie.org/2022/01/07/web3-first-impressions.html

MetaMask currently relies on the NFT indexer at OpenSea to display NFTs in your wallet. Which makes what should be a decentralized wallet end up being controllable by OpenSea.

I notice that Graph Token has supposedly had a NFT indexer running for a number of months now:
https://thegraph.com/hosted-service/subgraph/wighawag/eip721-subgraph

Is there a reason the decentralized index is not being used?

**Comment by omnat** [comment]
Thanks for raising this @rygo6 
This has been a topic of discussion internally, and something that we are researching actively. 
The over reliance on OpenSea API has been a concern for a while. We are looking into how we can decentralize our NFT data consumption. Added the NFT indexer you shared to include in our research. 

Meanwhile, with the latest app version, NFT auto-detection is turned off. You can choose to use dapps of your choice to view your NFTs.

**Comment by gantunesr** [comment]
I'll close this issue for now, please open a new one if have further questions
