### ISSUE TITLE
Allow users to input and send larger decimal numbers on the send flow

### ISSUE THREAD

**Issue by blackdevelopa** [MetaMask/metamask-mobile#3619]
**Describe the usability problem**
As a user I want to input large decimal numbers when sending ETH.

**Screenshots**
<img width="316" alt="Screen Shot 2022-01-21 at 20 17 03" src="https://user-images.githubusercontent.com/29962968/150587076-89a97a86-e6d4-4101-8474-f71f8fbc7f20.png">
<img width="315" alt="Screen Shot 2022-01-21 at 20 17 15" src="https://user-images.githubusercontent.com/29962968/150587085-70d980de-de3d-4e8a-a8c9-dc4c809d9513.png">

**Expected behavior**
As a user, I want to see the exact value I inputted without rounding it up

------------------------------------------------------------------------------------------------------
_filled out after submission_

**User impact | Usage frequency | Feasibility scores**
_How important is this to the user, what the user wants to accomplish | Daily, weekly, monthly | Small, medium, large_

**Comment by gantunesr** [comment]
This should be addressed in #3995
