### ISSUE TITLE
`wallet_addEthereumChain` doesn't work

### ISSUE THREAD

**Issue by alexdupre** [MetaMask/metamask-mobile#3629]
**Describe the bug**
The API call `wallet_addEthereumChain` should be implemented in metamask-mobile, but it's actually not working. No pop-up is displayed. For the records, the API to switch network, that was added later, works fine.

**To Reproduce**
```
const network = {
        chainId: '0x13',
        chainName: 'Songbird',
        nativeCurrency: { decimals: 18, symbol: 'SGB' },
        rpcUrls: ['https://songbird.towolabs.com/rpc'],
        blockExplorerUrls: ['https://songbird-explorer.flare.network/'],
    }
ethereum.request({
                    method: 'wallet_addEthereumChain',
                    params: [network],
                });
```

**Smartphone (any device):**
 - Device:  Samsung Galaxy S10 / iPhone XR
 - OS: Android 12 / iOS 15
 - App Version: 3.8.0

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by anxiubin** [comment]
params should be **Array**.

```js
const network = [{
        chainId: '0x13',
        chainName: 'Songbird',
        nativeCurrency: { decimals: 18, symbol: 'SGB' },
        rpcUrls: ['https://songbird.towolabs.com/rpc'],
        blockExplorerUrls: ['https://songbird-explorer.flare.network/'],
    }]
```

**Comment by alexdupre** [comment]
Sorry, it's an error in the extracted snippet, it is indeed an Array and it's not working. The same code in fact works in metamask extension.

**Comment by anxiubin** [comment]
is there any log or whatever? In my dapp, the api works well on the metamask mobile app.

**Comment by alexdupre** [comment]
Try opening [https://ftso.alexdupre.com/](https://ftso.alexdupre.com/) and check if it asks to add the network. You should see that it works with metamask extension and not with metamask mobile.

Debugging metamask mobile seems a hard task.

**Comment by anxiubin** [comment]
Maybe you should remove the code `if (switchError.code === 4902) {` in the function `setupNetwork` as [this issue](https://github.com/MetaMask/metamask-mobile/issues/3312). 
Try this!

**Comment by alexdupre** [comment]
I confirm it is indeed an error related on the returned error code, that is not `4902` but `-32603` on metamask mobile
