### ISSUE TITLE
some images not showing on android app

### ISSUE THREAD

**Issue by alonNftrade** [MetaMask/metamask-mobile#3636]
**Describe the bug**
some images are not showing on metamask android but showing on iPhone app. 

**Screenshots**

![WhatsApp Image 2022-01-25 at 2 01 57 PM (1)](https://user-images.githubusercontent.com/94784334/150973808-672e9d5c-2bf3-4df3-831f-418a7f45a00f.jpeg)
![WhatsApp Image 2022-01-25 at 2 01 57 PM](https://user-images.githubusercontent.com/94784334/150973813-729b696f-3b0b-4918-bc63-430d417b37a3.jpeg)

**To Reproduce**
_Steps to reproduce the behavior_
1. Go to 'nftrade.com'
2. Click on 'search and enter brokoli and enter collection'

**Smartphone (please complete the following information):**
 - App Version [e.g. 1.0.0] - find version number in app from Settings > About MetaMask

all android phones
-------------------------------------------------------------

- How critical is the impact of this bug on a user?
-  very critical some nfts are not showing on our website
- Add stats if available on % of customers impacted
- all android users
- Is this visible to all users?
- yes

**Comment by gantunesr** [comment]
Hey @alonNftrade, this seems to be an issue from nftrade.com
