### ISSUE TITLE
Auto detection fails to reimport after token/NFT was deleted. 

### ISSUE THREAD

**Issue by cortisiko** [MetaMask/metamask-mobile#3661]
**Describe the bug**
If I were to:
toggle on NFT or token detection so my assets are imported
toggle off NFT or token detection 
remove the imported NFT(s) or token(s) 
toggle on NFT or token detection 
the NFTs/tokens are not reimported. 

**Screenshots**
See token detection [here](http://recordit.co/R0whVpQ32H)
See NFT detection [here](http://recordit.co/57DST1U3gH)

**Smartphone (please complete the following information):**
 - App Version [e.g. 1.0.0] - find version number in app from Settings > About MetaMask

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by gantunesr** [comment]
@cortisiko this is the expected behaviour at the moment, I'm not sure if the NFT privacy feature should make it behave differently.

If you delete a NFT, this is added to an "ignore list" so the NFT is not being autodetect right away after the deletion. I'm pinging @omnat and @sethkfman here to know if we want to clear this "ignore list" when the toggle switches from OFF to ON.

**Comment by omnat** [comment]
> if we want to clear this "ignore list" when the toggle switches from OFF to ON.
I wouldn't clear this list. If the user ignored/deleting an NFT, we should respect that intention irrespective of autodetect preference. Until they custom import this NFT from the custom import form, let's keep the assets in the "ignore list". 
Wdyt?

**Comment by gantunesr** [comment]
Pinging @cortisiko to know if we can close this issue

**Comment by gantunesr** [comment]
Closing this issue for the moment @cortisiko
