### ISSUE TITLE
Err converting from cake to dollars 

### ISSUE THREAD

**Issue by oussamaBGZ** [MetaMask/metamask-mobile#3671]
![407406B0-28FD-43C1-9EF8-489DCB710121](https://user-images.githubusercontent.com/30552331/151862930-fad53783-51bf-499f-8df0-bb44e537e0fe.png)

err converting cake price to dollars

**Comment by gantunesr** [comment]
Hey @oussamaBGZ, in which version of the app you have this issue? is there any extra information relevant to this bug?

**Comment by Fatxx** [comment]
Hey @oussamaBGZ, we're not able to reproduce this. Please reopen if you still facing this issue.
