### ISSUE TITLE
Enable CTA even if "new password" and "confirm password" do not match

### ISSUE THREAD

**Issue by plasmacorral** [MetaMask/metamask-mobile#3677]
**Describe the usability problem**
The "Create password" CTA is not usable until the passwords match.  This can create a poor experience if mismatched passwords are provided.  With the CTA disabled, no error messages are presented to help the user remediate and move forward.  This may be related to changes made here: https://github.com/MetaMask/metamask-mobile/pull/1856

**Screenshots**
Mismatched password with CTA disabled prevents error message presentation
![63B918DC-4132-4FD8-A54A-36484942583E](https://user-images.githubusercontent.com/32695229/152025512-1901cbe4-3d80-4056-aa5c-863c23fa923c.png)

**Expected behavior**
CTA should be enabled so that user is given a proper error message and directed to correct the password mismatch.

------------------------------------------------------------------------------------------------------
_filled out after submission_

**User impact | Usage frequency | Feasibility scores**
_How important is this to the user, what the user wants to accomplish | Daily, weekly, monthly | Small, medium, large_

**Comment by gantunesr** [comment]
@omnat this is an interesting point that @plasmacorral is raising here, wdyt?

**Comment by omnat** [comment]
@plasmacorral Is the point you are stressing on about the CTA not enabled or limited error message when passwords don't match? 
What's the error message when passwords don't match (with same length inputs)?

If the former, I think it's OK to keep it disable till there's a match - to show when the user can proceed to the next step.

**Comment by plasmacorral** [comment]
> Is the point you are stressing on about the CTA not enabled or limited error message when passwords don't match?

CTA not being disabled inhibits error message presentation, leaving the user to have to figure out why they cannot create their password.

> What's the error message when passwords don't match (with same length inputs)?

There is no error message when the passwords are the same length but do not match, because the CTA `create password` is not enabled.  The CTA must be first be tapped to produce the error message and that is not currently possible.

What to do about it:
I suggest that we enable the CTA when submitted passwords do not match so that an error message can be presented for user remediation.

**Comment by omnat** [comment]
Oh thanks for the update! 
I think more responsive error feedback here could also be valuable from accessibility perspective.
Wdyt @jakehaugen about this one? I like Mike's suggested option as well, wondering if that's sufficient or could we be giving more system feedback as the user types.
