### ISSUE TITLE
TypeError: undefined is not an object (evaluating 'u.transaction.nonce')

### ISSUE THREAD

**Issue by cortisiko** [MetaMask/metamask-mobile#3684]
**Describe the bug**
I receive an alert message with `TypeError: undefined is not an object (evaluating 'u.transaction.nonce')` when the approval modal appears. 

**Screenshots**
_If applicable, add screenshots or links to help explain your problem_

**To Reproduce**

1. Using the test account I followed the paper trail: https://consensys.slack.com/archives/G8RSKCNCD/p1643832754695509?thread_ts=1643296355.079400&cid=G8RSKCNCD
2. switched my network to binance then went to this dapp: app.flurry.finance
3. I went ahead and tried to convert USD-T to rhoUSD-t. I entered “1” USD-T
4. submitted that transaction.
5. went to the txn history and noticed the txn was approved. it was taking forever for the approval modal to pop up so i attempted to cancel the txn. that did nothing
6. after a hot mintue the approval modal appeared. when i tried tapping “approve” the error would appear

See video below. It is a long video. The error is towards the end so you can probably skip through it. 

https://user-images.githubusercontent.com/12821081/152254921-b2da9496-e291-4aaa-90f1-336c02c8c585.mov

**Expected behavior**
_A clear and concise description of what you expected to happen_

**Smartphone (please complete the following information):**
 - App Version [e.g. 1.0.0] - find version number in app from Settings > About MetaMask

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by gantunesr** [comment]
@cortisiko can you check this in the current main branch, this could have been solved in teh commit [191fb0f2183fd1d908c226b36158ea0ed7642e4c](https://github.com/MetaMask/metamask-mobile/commit/191fb0f2183fd1d908c226b36158ea0ed7642e4c)  cc @andreahaku

**Comment by omnat** [comment]
@andreahaku fixed this with above & is merged, so moving to Done

**Comment by Yogeshwar267** [comment]
i had same issue now, with updated version of metamask
