### ISSUE TITLE
Color Rules for Overlay Alert Component

### ISSUE THREAD

**Issue by georgewrmarshall** [MetaMask/metamask-mobile#3693]
## Description
Update overlay colors to adhere to convention rules and to also meet requirements for contrast and what draws the eye more in darkmode.

## Technical Details
TBC

## Acceptance Criteria
TBC

**Comment by Akatori-Design** [comment]
@georgewrmarshall Is this still an active ticket?

**Comment by georgewrmarshall** [comment]
@Akatori-Design If the colors are done if figma it can be closed I'll create another issue for it's code implementation
