### ISSUE TITLE
Exception in create password screen

### ISSUE THREAD

**Issue by aoudiamoncef** [MetaMask/metamask-mobile#3694]
**Describe the bug**
When I try to create a password which is very long, I got:

Error: I/O error: javax.crypto.IllegalBlockSizeException: input must be under 384 bytes

**To Reproduce**

1. Go to create password screen
2. Write your 200 characters password
3. See error

**Expected behavior**
_ We should got a clear error message :

password must have maximum length of xxx characters.

**Smartphone**
 - Device: OnePlus 6T
 - OS: Android 11
 - App Version: 3.8.0

**Comment by zingero** [comment]
Happened to me as well.

Steps To Reproduce:
1. In my Android phone (Samsung Galaxy S22 Ultra, SM-S908E/DS, Android 15):
2. Install the Metamask app
3. Import an account using your seed
4. Create a very long password (let us say more than 2047 characters)
5. Log in using the same password

Please reconsider fixing it.
