### ISSUE TITLE
iOS app incorrectly reports "Sent yourself WETH" when asset sent to external address

### ISSUE THREAD

**Issue by epheph** [MetaMask/metamask-mobile#3780]
**Describe the bug**
I have worked with three different users who have been scammed. When assets are taken from their account, MetaMask on iOS reports the transfer as "Sent yourself WETH". I have also seen this for "Sent yourself USDC". In both cases, the user did NOT have the address for the recipient of these tokens.

This is really unfortunate because it gives them hope that their funds are just somewhere else they have access to.

**Screenshots**
Wallet history:
![](https://cdn.discordapp.com/attachments/944234622714265683/944287313175924837/IMG_1009.png)

Only has one account in their account config:
![](https://cdn.discordapp.com/attachments/944234622714265683/944291173076439050/IMG_1010.png)

The top transfer from above:
https://etherscan.io/tx/0xd51dfc97269b33cfbe372aa73f4741e72fba72f32050b69b5b48686d5b7f9039

**To Reproduce**
I am not sure how to reproduce, but the send in question was not originated by MetaMask on iOS, so it might be confused about transactions that were originated elsewhere?

**Expected behavior**
Account history should reflect that the ETH was sent to a third party and not "Yourself"

**Smartphone (please complete the following information):**
 - Device: iPhone
 - App Version: v4.0.1 (814)
![](https://cdn.discordapp.com/attachments/944234622714265683/944294243864834068/IMG_1012.png)

-------------------------------------------------------------

_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by epheph** [comment]
I'm not familiar with the iOS codebase, but this bit of code:

https://github.com/MetaMask/metamask-mobile/blob/cafc79d6c51e22caffda28b24711285a5ecc253a/app/util/transactions/index.js#L317-L324

seems like it is only verifying `from == selectedAddress` to indicate "Sent yourself" vs "from == selectedAddress && to == selectedAddress

**Comment by gantunesr** [comment]
Hey @epheph, thanks for reaching out and providing details about the issue. I'll take a look at this and update this issue during the week

**Comment by epheph** [comment]
I see the activity on PR #3792, looks great!

**Comment by epheph** [comment]
👏👏👏👏

**Comment by trevormoo** [comment]
Pls I have the same issue 
Says"sent yourself WETH"
What do I do pls? 
I sent from one wallet to another of my wallet

**Comment by epheph** [comment]
Did it arrive in your other wallet? If so, there's no problem?

**Comment by gantunesr** [comment]
Hey @epheph, the bug should solved now. If not, ping me in this issue to re-open it.
