### ISSUE TITLE
v4.1.0(816): Ethereum Main Network: Swap > Convert to lookup: TypeError: null is not an object... displayed

### ISSUE THREAD

**Issue by chrisleewilcox** [MetaMask/metamask-mobile#3807]
**Describe the bug**
After importing a wallet on the onboarding welcome screen, a `Console Warning` and `Render Error` is displayed after typing in "uni" for Uniswap on the "Convert to" token lookup.

**Screenshots**
https://recordit.co/jCNxVRWJJ8

**To Reproduce**
1. Install/Upgrade MM mobile
2. Import wallet
3. On the Ethereum Main Network
4. On wallet view
5. Tap Swap 
6. Enter amount of ETH to swap
7. Tap 'Select a token'
8. Type 'uni' in 'Convert to' lookup

You will see the errors shown at this point.

**Expected behavior**
No errors shown and can continue with swapping tokens.

**Smartphone (please complete the following information):**
 - Device: iPhone 11 Pro
 - OS: 15.2
 - App Version: v4.1.0(816)

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by Fatxx** [comment]
Duplicated of #3760, it's fixed already.
