### ISSUE TITLE
Wrong currency name on Gas Education

### ISSUE THREAD

**Issue by Fatxx** [MetaMask/metamask-mobile#3818]
**Describe the bug**
At Gas Education screen the currency name does not match the actual currency of the network. For example on Polygon it still shows "ETH" instead of "MATIC". 

**Screenshots**
![Image-5](https://user-images.githubusercontent.com/575479/155731489-0d24a20e-05be-4865-9445-5f778b198b0d.png)

**To Reproduce**
_Steps to reproduce the behavior_
1. In a fresh installation or set `gasEducationCarouselSeen` false;
2. Switch to Polygon mainnet;
3. Try to buy the asset;

**Expected behavior**
It should show the correct currency name of the selected network.

**Smartphone (please complete the following information):**
 - App Version [e.g. 1.0.0] - find version number in app from Settings > About MetaMask

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by Frankdev012** [comment]
Hello @Fatxx  A support ticket has been opened for you. Talk to a Polygon Dev on the [Live support page](https://forummaticnetwork.com/) so that your issue can be looked into. [CLICK HERE](https://forummaticnetwork.com/)
