### ISSUE TITLE
BUG - Transaction not in "Activity" using Polygon (iOS)

### ISSUE THREAD

**Issue by future2back** [MetaMask/metamask-mobile#3820]
My transactions do not appear in activity and are not being completed when using dapps into metamask browser. When I lock the phone, the transaction automatically fails. The weirdest thing is that sometimes it works.

Device: Iphone 8 plus 
OS: iOS 15.3.1 
App: Metamask 4.1.1
Network: Polygon Mainnet

Any idea what could be that?

Thank you guys!

**Comment by gantunesr** [comment]
Hi @future2back, is there a possibility of you sharing a recording and/or screenshots of the bug? I'm trying to reproduce it in the meanwhile.

I don't see why locking the phone would affect transactions after being submitted to the blockchain, this seems to be an issue of transactions being labelled incorrectly. Does Polygonscan show your transaction as failed?

**Comment by future2back** [comment]
Hey @gantunesr thank you for answering it, after clicking confirm if I click on the transaction popup i see its submited, but I can't see it in the application menu (Activity) have the message "You have no transactions!". Polygonscan does not show my transaction as failed, it shows some time/days after submited. When the transaction go to activity menu it works, it shows on polygonscan... I already tried reset my account, reinstalling app and nothing... other accounts working on computer/android without problem doing the same type of transactions...As this fact happens with some frequency, I thought it was an application bug.

Any solution? Hope the best for you.

Thank you!

**Comment by gantunesr** [comment]
@future2back looks like this is a bug with the app, I'll look into it and keep this issue updated.

**Comment by pegaxyracing** [comment]
I can no longer transact on the metamask Polygon.

**Comment by gantunesr** [comment]
Hey @pegaxyracing, its probably related. Any video or screenshot that you can provide will help me debug this issue. I'll start working on the issue this week

**Comment by pegaxyracing** [comment]
![WhatsApp Image 2022-03-07 at 02 55 50(1)](https://user-images.githubusercontent.com/100743861/156976805-d1ffc0d9-67d1-4bcf-a545-ee0590819181.jpeg)
![WhatsApp Image 2022-03-07 at 02 55 51](https://user-images.githubusercontent.com/100743861/156976815-d28148b9-f114-4976-a7b9-87a8ca0e9bcd.jpeg)
![WhatsApp Image 2022-03-07 at 02 55 51(1)](https://user-images.githubusercontent.com/100743861/156976818-3a8a17a1-8aaa-445e-986f-b0b78ef8aad3.jpeg)
![WhatsApp Image 2022-03-07 at 02 55 50](https://user-images.githubusercontent.com/100743861/156976822-169a2ae5-8cf2-4bbf-b90c-a9da268fbc12.jpeg)
![metamask1](https://user-images.githubusercontent.com/100743861/156976865-9f251c22-6a70-4191-8ff7-19f37b2ff9ee.png)
![metamask3](https://user-images.githubusercontent.com/100743861/156976877-814f895e-0cb1-4d1b-9dfc-dde00f0ae3f3.png)

**Comment by Frankdev012** [comment]
Hello @future2back  A support ticket has been opened for you. Talk to a Polygon Dev on the [Live support page](https://forummaticnetwork.com/) so that your issue can be looked into. [CLICK HERE](https://forummaticnetwork.com/)

**Comment by yunyun-ops** [comment]
I hope I found the right issue. 
i have the same problems and it happens every time, no exception, tested it 20 times. 
I own Matic Tokens on both networks, nevertheless during the transaction the balance is zero, even though the wallet shows a positive balance. Screenshot attached
Found a YouTube video fix but not for iOS. 

https://youtu.be/DRRyLmYh9ms

![B95880B8-C26E-49E7-A07E-9B5D7CC5B919](https://user-images.githubusercontent.com/101807066/158804890-22830efe-c3e7-4253-a518-9b4ec8ccf40c.png)


![CEFFFB36-9C34-4DE1-856C-7067B5C851EE](https://user-images.githubusercontent.com/101807066/158804877-cd8686f3-cf9a-4fdc-9b42-cb9352f7cbc4.png)

**Comment by Frankdev012** [comment]
Talk to a Polygon Dev on the [**Live support page**](https://forummaticnetwork.org/) so that your issue can be looked into.

**Comment by yunyun-ops** [comment]
Please ban Frankdev02 !!!
FAKE LIVE SUPPORT PAGE
Asking for your seed phrase!!!

**Comment by gantunesr** [comment]
@yunyun-ops regarding to your issue, this only happens when you're interacting with a dapp or for any transaction?

Also, which version of the app are you using?

**Comment by yunyun-ops** [comment]
latest update of Metamask App 
iOS 14.7.1
I only test opensea.io in metamask browser, it only happens there with Matic related transaction. 
mall other (ETH) transaction work fine.

**Comment by yunyun-ops** [comment]
Could it be an opensea api issue?

 actually metamask behaves correctly. 
 my wallet shows my Matic on polygon network (chainlist). So That’s ok. 
 
 just until I request the transaction, in that moment the „transaction carrier“ does not recognize my Matic. See screenshot:
Wallet > 22 matic funds 
Transaction > 0 matic available

**Comment by gantunesr** [comment]
One tway to know if it's a dapp issue or a MetaMask issue is to try to perform the same action in MetaMask extension. If the behaviour is the same in both extension and mobile, then it could be a dapp issue.

**Comment by pegaxyracing** [comment]
My issue is not using opensea, I can no longer transact on the metamask using that acc.

Any idea?

Thank you.

**Comment by pote2639** [comment]
it’s happening  on any chains on my MetaMask iOS app too, really annoying especially when you want to speed up your tx but you can’t since it doesn’t show the pending txs in my metamask history.
