### ISSUE TITLE
Cookie issue in MetaMask mobile app (Android only)

### ISSUE THREAD

**Issue by AdriGoM** [MetaMask/metamask-mobile#3828]
When I sign up with metamask account and the web redirects to the home page something happens because I'm not be able to get the cookie value a show the user info. Apparently its only an Android issue, in desktop and iOS all works fine.

**Comment by Yuxanju** [comment]
You will need to synchronize your wallet and then you debug it with bech3

**Comment by kakashigr** [comment]
Same thing, only on android the browser doesn't seem to respect cookies and users can't log in

**Comment by Fatxx** [comment]
Closing in favour of https://github.com/MetaMask/metamask-mobile/issues/4245
