### ISSUE TITLE
Validate password before showing Keep your SRP safe modal

### ISSUE THREAD

**Issue by cortisiko** [MetaMask/metamask-mobile#3829]
### **Description**

1. This issue was found during 4.2 regression and was not deemed a blocker for the release. Basically we are not validating the password before showing the Keep your SRP modal. For example I entered an incorrect password and the Keep your SRP modal appeared. When I tap and hold to reveal the SRP that's when the password validation "you have entered the incorrect password" was done.

see [here](http://recordit.co/uyh9d7KXlV)

2. Replace check icon with unlock icon

**Comment by gantunesr** [comment]
Closed in favor of https://github.com/MetaMask/metamask-mobile/issues/4781
