### ISSUE TITLE
On a custom network the incorrect native currency appears after editing a transaction 

### ISSUE THREAD

**Issue by cortisiko** [MetaMask/metamask-mobile#3833]
**Describe the bug**
If a user were to be on the MATIC network -> request MATIC on device A then on device B scan the request QR code. On device B if the user were to edit the transaction, the native currency shows ETH instead of MATIC

**Screenshots**
see recording [here](http://recordit.co/Hh8KXEp3Ia)

**To Reproduce**
1. Have two devices ready. Add polygon to your list of networks
2. On device A go through the request flow and generate a request QR-code
3. On device B, scan device A QR-code
4. On device B edit the transaction. Notice in the top dropdown "ETH" appears instead of "MATIC" 

**Expected behavior**
The correct native currency should appear

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by tommasini** [comment]
This was fixed on release 5.4: https://recordit.co/lmSM4B3LeJ
Can we close it? @cortisiko
