### ISSUE TITLE
Deeplink not opening the browser of metamask

### ISSUE THREAD

**Issue by Qiweih** [MetaMask/metamask-mobile#3855]
**Describe the bug**
I'm trying to open metamask with the deep link https://metamask.app.link/dapp. 
I tried it on two different phones, in one it open the browser in Metamask App, and all is working well. But on another phone, it opened metamask app but it did not trigger the browser, nothing happened. 

**Screenshots**
Here is two videos where we can see that in one phone all is working well and in another, it's not working.

This one is working
https://github.com/Qiweih/twino/blob/master/testmetamask.mp4
This one is not working
https://github.com/Qiweih/twino/blob/master/MetaMask%20(2).mp4

**Smartphone (please complete the following information):**
 - OS: [Android 12]
 - App Version [4.1.1] - find version number in app from Settings > About MetaMask

**Comment by andreahaku** [comment]
Hi Qiweih,
starting from version 4.1.x you need to provide a url after `/dapp/` to have the internal browser open a page.
Let me know if you still have problems with this.

**Comment by cmac2992** [comment]
I'm having this same issue on android. https://metamask.app.link/dapp/example.com or https://metamask.app.link/dapp/https://example.com just drops me into the wallet not into the browser. Works fine on ios/safari 

**smartphone**
- os: android 12
- app: 4.1.1

**Comment by Qiweih** [comment]
@andreahaku Yes i have the /dapp/  , i still have the problem with this.

**Comment by Programalyst** [comment]
Also having this issue. It was working for me in December but it's not working now. Tried generating the deep link again but it's the same and the metamask app browser doesn't open with the dapp URL.

**Comment by Qiweih** [comment]
I'll reopen another issue, we can't close an issue while nothing is solved

**Comment by andreahaku** [comment]
Hi,
Android 12 issues with deeplinks should be solved with the about to be released version 4.2.2.
Please test with this version and let me know if you still have issues with this.
Thanks

**Comment by Qiweih** [comment]
@andreahaku I'll do that and keep you update

**Comment by tejvirmann** [comment]
Hi everyone! Just wondering, was this issue fixed? Experiencing the same problem. Whenever I do: 
https://metamask.app.link/dapp/example.com or (https://metamask.app.link/dapp/https://example.com) I am directed to the wallet, not the browser. 

4.2.2 of metamask.
I have an iphone 12 pro with the latest update, using Xcode and Swift. Does it work on other devices?

**Comment by jacob-abe** [comment]
It doesnt make a difference if you add https://metamask.app.link/dapp/example.com or https://metamask.app.link/dapp/https://example.com as the code just replaces the https:// and http:// after /dapp.

**Comment by basememara** [comment]
It's really annoying.. however this seems like a platform issue. When I long-press the link in the mobile browser in iOS, one of the opens is to open MetaMask which does deep link into the in-app browser.

<img src="https://user-images.githubusercontent.com/892152/160253465-8b9e1fe9-30c8-40b4-a895-1a5512cfd3e0.png" width="300">

I'm not sure if MetaMask can do anything extra to make this without the long-press which would be ideal.

**Comment by liho00** [comment]
this is the code that i used to trigger the deep link navigation.
Im using IOS 15.3.1
```
window.open(`https://metamask.app.link/dapp/${window.location.host}`)
```

@andreahaku  Same not working with latest v5.0.1, here is the screen recording https://user-images.githubusercontent.com/77238199/165326244-c9471c12-f88b-4ff8-b207-80f410623c51.MOV

**Comment by andreahaku** [comment]
So we have investigated the issue and unfortunately it does not depend on MetaMask mobile but on a mix of restrictions from mobile browsers and our deep link service provider.

The issue **doesn't happen** if the link is "tapped/clicked" by the user. It does happen with redirects and similar programmatic link openings.

So there are two potential workaround to it:

1. make the link tappable by associating it to a button or something like that
2. "simulate" a tap/click

About point 2 I just developed and tested a quick and simple JS function that does that.

```
function openMetaMaskUrl(url) {
    const a = document.createElement("a");
    a.href = url;
    a.target = "_self";
    document.body.appendChild(a);
    a.click();
    a.remove();
}
```

and it can be used like this:

`openMetaMaskUrl("https://metamask.app.link/dapp/google.com");`

This works on Android and iOS Chrome. On iOS Safari still opens the app store instead of MetaMask mobile app.

Let me know if this helps you. Thanks.

**Comment by jacob-abe** [comment]
This worked for me. Thanks

**Comment by liho00** [comment]
> So we have investigated the issue and unfortunately it does not depend on MetaMask mobile but on a mix of restrictions from mobile browsers and our deep link service provider.
> 
> The issue **doesn't happen** if the link is "tapped/clicked" by the user. It does happen with redirects and similar programmatic link openings.
> 
> So there are two potential workaround to it:
> 
> 1. make the link tappable by associating it to a button or something like that
> 2. "simulate" a tap/click
> 
> About point 2 I just developed and tested a quick and simple JS function that does that.
> 
> ```
> function openMetaMaskUrl(url) {
>     const a = document.createElement("a");
>     a.href = url;
>     a.target = "_self";
>     document.body.appendChild(a);
>     a.click();
>     a.remove();
> }
> ```
> 
> and it can be used like this:
> 
> `openMetaMaskUrl("https://metamask.app.link/dapp/google.com");`
> 
> This works on Android and iOS Chrome. On iOS Safari still opens the app store instead of MetaMask mobile app.
> 
> Let me know if this helps you. Thanks.

@andreahaku  I personally thinking most Iphone user will be using safari as primary browser (im one of it), as you said this problem still persist in IOS safari when open deeplink of the metamask, I am trying the find the solution on it, lets reopen the issue?

**Comment by Spider149** [comment]
I'm still facing this problem although I try both ways: window.location.replace or your openMetaMaskUrl
My metamask version is 5.1.1, Android 11.
It's open metamask and after that prompt a password form, after enter the password it's just open the wallet not browser.

**Comment by lepadatumihail** [comment]
It works for me if I do location.href= "the link you want to open"

**Comment by Spider149** [comment]
> It works for me if I do location.href= "the link you want to open"

I tried your way but still the same result :(

**Comment by b-pmcg** [comment]
I'm having the same issue as @Spider149 with Android. None of the suggested solutions are working, the Metamask app opens, but it just shows the wallet page. 
MM: 5.1.1
Android: 12

**Comment by spectrl** [comment]
Just want to add that none of the suggested approaches are working for me either. The behaviour I want is that MetaMask is opened with the browser open, and the URL I pass in is loaded.

Here's what I've tried and every time it just lands on the MetaMask home (wallet) screen:
* `https://metamask.app.link/dapp/opensea.io/assets/ethereum/0xa9074445881ffd9bd1096414149f0feb8147b4a9/4346`
* `metamask://dapp/opensea.io/assets/ethereum/0xa9074445881ffd9bd1096414149f0feb8147b4a9/4346`

I'm on Android 12 and using this Intent launching code:
```
val intent = Intent(Intent.ACTION_VIEW, uri)
            .addCategory(Intent.CATEGORY_BROWSABLE)
            .addFlags(
                Intent.FLAG_ACTIVITY_NEW_TASK or Intent.FLAG_ACTIVITY_REQUIRE_NON_BROWSER
            )
startActivity(intent)
```

Hope this gets resolved soon! 🙏

**Comment by iners-max** [comment]
Still not working on iOS nor Android

Android 12 (Samsung Note 10), with Metamask Mobile 5.2.0
iOS 15.3.1, with Metamask Mobile 5.2.0

No matter `https://metamask.app.link/dapp/` nor `metamask://dapp/`. It will eventually only open Metamask app's wallet page. They are not opening the dapp URLs in the in-app browsers.

**Comment by luoei** [comment]
> Still not working on iOS nor Android
> 
> Android Chrome, Android 12 (Samsung Note 10), with Metamask Mobile 5.2.0 iOS Safari, iOS 15.3.1, with Metamask Mobile 5.2.0
> 
> No matter `https://metamask.app.link/dapp/` nor `metamask://dapp/`. It will eventually only open Metamask app's wallet page. They are not opening the dapp URLs in the in-app browsers.

Encountered the same problem, is there a solution?

**Comment by grantwwoodford** [comment]
This solution worked for me: https://github.com/MetaMask/metamask-mobile/issues/3965#issuecomment-1122505112

**Comment by mavcom12** [comment]
can we reopen this ticket? when I tested it's still the same opening only at wallet page and not directly to metamask browser

**Comment by mavcom12** [comment]
Is there a way where android will not have to change chooser settings?

**Comment by syahbes** [comment]
> Did anyone find a solution to this issue??

yes!!
this post "https://dev.to/miki-digital/working-with-smart-contract-on-the-frontend-3mem" 
help me undrestand that I need to add "\\" 
in the end of my 'metamaskAppDeepLink'
for exemple if my app link is syhabesapp.vercel.app

the link to open is :
  const metamaskAppDeepLink =
    `https://metamask.app.link/dapp/syahbesapp.vercel.app\\/`
    
    and than just 
      <a href={metamaskAppDeepLink}>
        <button className="btn">
          connect wallet
        </button>
      </a>
      
      that will open metamask browser on the link you provided

**Comment by hengshanMWC** [comment]
> \\/

Not OK
