### ISSUE TITLE
Deeplink do not open browser inside metamask mobile app

### ISSUE THREAD

**Issue by Qiweih** [MetaMask/metamask-mobile#3865]
**Describe the bug**
I'm trying to open metamask with the deep link https://metamask.app.link/dapp. 
I tried it on two different phones, in one it open the browser in Metamask App, and all is working well. But on another phone, it opened metamask app but it did not trigger the browser, nothing happened. 

**Screenshots**
Here is two videos where we can see that in one phone all is working well and in another, it's not working.

This one is working
https://github.com/Qiweih/twino/blob/master/testmetamask.mp4
This one is not working
https://github.com/Qiweih/twino/blob/master/MetaMask%20(2).mp4

**Smartphone (please complete the following information):**
 - OS: [Android 12]
 - App Version [4.1.1] - find version number in app from Settings > About MetaMask

**Comment by Qiweih** [comment]
Reopen #3855

**Comment by gantunesr** [comment]
#3855 was reopened, closing this one
