### ISSUE TITLE
After closing NFT detail view, tapping NFT thumbnail does not open detail view on first tap

### ISSUE THREAD

**Issue by jakehaugen** [MetaMask/metamask-mobile#3867]
**Describe the bug**
Can not tap an NFT thumbnail after closing NFT detail overlay.

**Screenshots**
https://user-images.githubusercontent.com/11967476/157293145-33d44b37-a7b6-4309-8eb4-9a5b19ca97d3.MOV

**To Reproduce**
1. Go to 'NFTs' tab
2. Tap on an NFT to open detail view
3. Close NFT detail view
4. See that tapping another NFT does not work for 1-2 taps

**Expected behavior**
Thumbnail would open detail view on the first tap

**Smartphone (please complete the following information):**
 - Device: iPhone 12 Pro
 - OS: iOS 15.3.1
 - App Version 4.1.1 (825)

**Slack thread (with videos)** 
https://consensys.slack.com/archives/CBW7S9FSN/p1646761031789679?thread_ts=1646761005.044549&cid=CBW7S9FSN

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by wachunei** [comment]
Just reproduced this. To add more context: it does not depend on how many times you tap after dismissing the view, I think there's a small amount of time after dismissing the view that the overlay keeps capturing the touches.
