### ISSUE TITLE
Application connectivity issue 

### ISSUE THREAD

**Issue by TauseefAhmaad** [MetaMask/metamask-mobile#3873]
Hi MetaMask-Mobile Support 
i observe an issue , when i download the application from Playstore (Android 12.0), then the other application could not connect with the metamask mobile application. i try many time but not work with user case.  but its working with when we install the metamask from GitHub releases. if we publish the application on playstore then every user download the metamask mobile from the GitHub release. please guide me , how we can sort out this issue

**Comment by gantunesr** [comment]
Hey @TauseefAhmaad, can you indicate the steps to reproduce the issue you are facing currently?

**Comment by TauseefAhmaad** [comment]
Hey @gantunesr, please follow the steps to reproduce the bug
UseCase 1- Download from **Google PlayStore**
1- download the Metamask from the

https://user-images.githubusercontent.com/99240552/158148565-fdb9a4f6-cb6e-411a-af99-042c41760afd.mp4

 google play store. login in metamask 
2- I am building the unity game using WebGL 3.0.
3- when I connect the unity game with MetaMask (downloaded from playstore). It opens the application but does not work with deep linking. 
4- The Metamask application not working. 
please see the attached Video 



UseCase 2- DownLoad from **Github**
when I MetaMask Application download the application from GitHub and install manually its works, and the unity application works with MetaMask (download from Github).

**Comment by TauseefAhmaad** [comment]
Hey, @gantunesr Kindly guide me.
