### ISSUE TITLE
deeplink issue with walletconnect when opened from native app

### ISSUE THREAD

**Issue by flejmer** [MetaMask/metamask-mobile#3874]
**Describe the bug**
MetaMask app won't display the connect request when I try to connect from native app using deeplink.
I tried this on [WalletConnectSwift-Example](https://github.com/WalletConnect/WalletConnectSwift-Example) app.

**Video**
https://user-images.githubusercontent.com/11304134/157484343-d15e2522-ca05-4507-bb15-c8f329d12383.MP4

**To Reproduce**
1. Install [WalletConnectSwift-Example](https://github.com/WalletConnect/WalletConnectSwift-Example)
2. In `MainViewController` of client example change `deepLinkUrl` value to `"https://metamask.app.link/wc?uri=\(connectionUrl)"`
3. Try to connect by pressing `Connect to WalletConnect` with MetaMask app installed.
4. A deeplink should open the MetaMask app
5. Error: MetaMask opens as expected but no connect request is shown.

**Expected behavior**
MetaMask app opens and connect request is displayed.

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone 11 Pro]
 - OS: [e.g. iOS15.3.1]
 - App Version [e.g. 4.2.2 (834)]

**Comment by flejmer** [comment]
Update. Seems like this issue only applies to universal links. I changed back to `wc://wc?uri=\(connectionUrl)` and it works but it isn't ideal. Are universal links not supported?

**Comment by dash7ou** [comment]
Hi man, it's not working with me, Can u explain to me what did u did ?

**Comment by Cydie** [comment]
This is still an issue and the thread I made about it on your forum is closed now without any new information. So I decided to bump the topic here.

https://community.metamask.io/t/ios-universal-links-with-wallet-connect-are-not-working/20694

Please re-visit the decision of closing this issue @cortisiko . This is still a problem on iOS

**Comment by grp06** [comment]
Still a problem in September 2022

**Comment by WingCH** [comment]
this work for me

https://github.com/WalletConnect/WalletConnectSwift-Example/issues/7#issuecomment-1328726509
