### ISSUE TITLE
Excess decimals places via Use Max button in Send Flow

### ISSUE THREAD

**Issue by Cal-L** [MetaMask/metamask-mobile#3876]
### **Description**

Pressing on the Use Max button in the Send Flow results in the input amount having an excess amount of decimals (greater than 5). Toggling between token amount vs dollar amount temporarily relieves this by showing only up to 5 decimal places.

### **Technical Details**

-  Can we limit the number of decimal places to 5?

### **Acceptance Criteria**

-  TBD

### **References**

-  Video - https://recordit.co/6Zwoa30aU3

**Comment by omnat** [comment]
We fixed this for Swaps flow if I remember correctly, and Pedro had thoughts on fixing for entire app (were there technical limitations?). @wachunei how did we resolve this for Swaps?

**Comment by wachunei** [comment]
When dealing with tokens this is not a bug, but a feature. A lot of tokens have up to 18 decimals, using max button in swaps shows the whole balance, otherwise there would be remainders. 

When dealing with ETH should be the same, but it is a little bit more complicated because the gas should be considered: max + gas = balance.

**Comment by bschorchit** [comment]
Related to https://github.com/MetaMask/metamask-mobile/issues/3619

**Comment by gantunesr** [comment]
I'm confused about what is the final UX decision over this issue. I can see that the issue recommends to show up to 5 decimals, but @bschorchit just referenced another issue where the user should be able to input a long number without rounding it up or truncating.

@jpcloureiro can you validate the final solution with @bschorchit and @omnat and post a comment in this issue? This should be consistent across all the views where the user can input an amount.

**Comment by jpcloureiro** [comment]
After discussing this with @wachunei, @omnat and @bschorchit we concluded that it is better to leave all the decimals when clicking "use max" to minimize token dust. Although we can improve the UX by reducing font size as the number grows in length, same way as Swaps. Created #4122 to address that.
