### ISSUE TITLE
Deep linking to the approval flow switches networks correctly but does not show approval modal

### ISSUE THREAD

**Issue by cortisiko** [MetaMask/metamask-mobile#3880]
**Describe the bug**
Basically If you deep link here: https://metamask.app.link/send/0x01BE23585060835E02B77ef475b0Cc51aA1e0709@4/approve?address=0x178e3e6c9f547A00E33150F7104427ea02cfc747&uint256=5e8

The network updates correctly but the approval modal does not appear. If you try interacting with the app nothing happens. You would need to kill the app and relaunch to start back interacting with the app. You would also need to deep link again for the approval modal to appear. 

**Screen recording**
[see recording](http://recordit.co/HQB8MEF0O1)

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by tommasini** [comment]
@cortisiko In this last main branch update it's working fine with me, can you re-check if it keeps happening with you please?

**Comment by Fatxx** [comment]
@chrisleewilcox can also re-check

**Comment by cortisiko** [comment]
@tommasini @Fatxx I can confirm this is still happening. See recording [here](https://github.com/MetaMask/metamask-mobile/issues/3880). This was on the v5.1 RC candidate based off on main. I used my physical iPhone device running iOS 14.8. I also tested on my physical iPhone 11 running iOS 15.2 and I still encountered the issue.
