### ISSUE TITLE
net::ERR_CLEARTEXT_NOT_PERMITTED

### ISSUE THREAD

**Issue by tomomoto** [MetaMask/metamask-mobile#3886]
No android permission for watching bscscan
net::ERR_CLEARTEXT_NOT_PERMITTED
![photo_2022-03-12_10-39-30](https://user-images.githubusercontent.com/11706519/158009062-70f0b48a-cc22-4fa8-a863-6f6ddadc12d1.jpg)

![photo_2022-03-12_10-39-30 (2)](https://user-images.githubusercontent.com/11706519/158009065-a0f50602-9e2f-4c23-b3e6-cb79d626dd8a.jpg)
![photo_2022-03-12_10-39-30 (3)](https://user-images.githubusercontent.com/11706519/158009073-6cef9d5e-5184-47f1-8564-9ed14438db00.jpg)

**To Reproduce**
_Steps to reproduce the behavior_
1. Go to 'Main page'
2. Click on 'View on Bscscan'
3. See error

**Expected behavior**
1. Go to 'Main page'
2. Click on 'View on Bscscan'
3. See Bscscan

**Smartphone (please complete the following information):**
 - Device: POCO X3 PRO
 - OS: MIUI Global 12.5.6 Stable based on Android 11 RKQ1,200826.002
 - App Version v4.1.1 (827)

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by tomomoto** [comment]
Network name: Smart Chain
New RPC URL: https://bsc-dataseed.binance.org/
Network ID: 56
Symbol : BNB
URL block-explorer: https://bscscan.com

**Comment by tomomoto** [comment]
@gantunesr Answered above.

**Comment by tommasini** [comment]
I'm not being able to reproduce it, @tomomoto can you please update the app and see if the problem persists

**Comment by tomomoto** [comment]
@tommasini Seems that app is updated and last version since google play doesn't suggest me to update.
Ye, the problem is persist.

**Comment by tommasini** [comment]
@tomomoto I'm not being able to reproduce it, maybe there is one step that I'm missing, could you provide more information?

I'm with an Android 10 and you with one Android 11 it's the only difference I can see right now 

Thank you!

**Comment by tomomoto** [comment]
@tommasini Does bscscan works for BNB network in android 10? 
By the way, my POCO get the update and currently it has Android 12 SKQ1.21106.001 
It doesn't work still

**Comment by tommasini** [comment]
@tomomoto I'm only be able to help if you send more step details to the issues that you are finding, could you share them please?

**Comment by tomomoto** [comment]
@tommasini What kind of details do you need? All the steps are provided, but probably I've missed something.

**Comment by tommasini** [comment]
@tomomoto Can you send a video please stepping into the error or errors that you are having, also, the steps you did to add the Binance smart chain network or the information of that network again, please.

**Comment by tomomoto** [comment]
@tommasini No, I wouldn't like to provide videos, all the steps are provided in the description.
The steps of the BSC - https://github.com/MetaMask/metamask-mobile/issues/3886#issuecomment-1072580936

**Comment by tomomoto** [comment]
This still doesn't work, why closed?

**Comment by phamhongphuc1999** [comment]
> This still doesn't work, why closed?

did something update yet? did you figure it out?

**Comment by tomomoto** [comment]
> > This still doesn't work, why closed?
> 
> [@tomomoto](https://github.com/tomomoto) did something update yet? did you figure it out?

Metamask updated to v.7.39.0 (1544), problem DOES NOT persist. BSC scan works correctly.

**Comment by tomomoto** [comment]
> > This still doesn't work, why closed?
> 
> [@tomomoto](https://github.com/tomomoto) did something update yet? did you figure it out?

@phamhongphuc1999 Metamask has updated to v.7.39.0 (1544), problem DOES NOT persist. BSC scan works correctly.
