### ISSUE TITLE
Release 4.2.2 on google store ?

### ISSUE THREAD

**Issue by CocoJr** [MetaMask/metamask-mobile#3889]
Hello,

Just want to know when the release 4.2.2 will be on the google play store ?
The current release (4.1) is bugged with android 12 so we really waiting for this release....

**Comment by wachunei** [comment]
Hello @CocoJr, it should be released to 100% percent of the users within the next 24 hours.

**Comment by CocoJr** [comment]
Thanks @wachunei !

Got the upgrade, but the deeplink still not work on Android 12....
