### ISSUE TITLE
Visual review for Dark Mode on Mobile - George

### ISSUE THREAD

**Issue by georgewrmarshall** [MetaMask/metamask-mobile#3890]
### **Description**

Run through dark mode Receive, Buy, Sell, Swap flows and note down any colors, icons, images that need updating

### **Technical Details**

-  Run through dark mode flows
-  Screenshot any images and create issues for updates

### **Acceptance Criteria**

- Noted flows have video recordings attached to this issue 

### **References**

-   [Slack thread](https://consensys.slack.com/archives/CBW7S9FSN/p1647030246325079)

**Comment by Cal-L** [comment]
Related to https://github.com/MetaMask/design-tokens/issues/50
