### ISSUE TITLE
Fix crasher when sending ERC20 token

### ISSUE THREAD

**Issue by Cal-L** [MetaMask/metamask-mobile#3895]
### **Description**

Attempting to send ERC20 token crashes when landing on confirmation page

### **Technical Details**

-  Patch AssetsContractController single balance call to use upgraded web3 syntax

### **Acceptance Criteria**

-   Attempting to send ERC20 token should not crash when landing on confirmation page
- Additionally, this would also affect token detection, so let's make sure that still works

**Comment by gantunesr** [comment]
Fixed in #3896
