### ISSUE TITLE
Transaction was submitted successfully but it got stuck

### ISSUE THREAD

**Issue by dragons3232** [MetaMask/metamask-mobile#3924]
**Describe the bug**
Transaction was submitted successfully but it got stuck because of incorrect nonce

**To Reproduce**
_Steps to reproduce the behavior_
1. Add besu testnet network
2. Import existing accounts
3. Select an account with available balance
4. Click on Send button in Wallet overview screen
5. Select send between internal accounts
6. Select another account as target recipient
7. Input amount and click on Next
8. Click Confirm to start transaction
9. Observe transaction submitted successfully
10. Submitted transaction nonce is very high and it could not be viewed on testnet explorer

**Expected behavior**
Nonce of transaction should NOT be high. And transaction should be proceeded successfully without getting stuck

**Smartphone (please complete the following information):**
 - Device: iPhone 8 Plus
 - OS: 15.2
 - App Version: 4.2.2

** Suggestion **
When removing "pending" status from getTransactionCount query at line 308 in node_modules/@metamask/controllers/dist/transaction/TransactionController.js, the problem was resolved.

**Comment by tommasini** [comment]
Hello @dragons3232, thank you for reporting this issue.
Could you please try to enable the toggle Customize transaction nonce in the burger menu -> Settings -> Advanced, and do a transaction customising the nonce for a lower value? Could you tell me if that solves the problem?
