### ISSUE TITLE
[5.3] After submitting a txn then killing and relaunching the app a "Oops Something went wrong" toast appears

### ISSUE THREAD

**Issue by cortisiko** [MetaMask/metamask-mobile#3927]
**Describe the bug**
A toast message "Oops Something went wrong" appears after a user submits a transaction > kills or backgrounds the app > reopen/relaunch the app

**Screenshots**
see [here](http://recordit.co/Pqa7Uq34hv)

**To Reproduce**
switch to rinkeby or ropsten then go to the test dapp
tap on create a token.
submit transaction
while transaction is submitting send the app to the background or kill the app
relaunch the app
notice the transaction goes through successfully and the toast error appears

**Smartphone (please complete the following information):**
 - App Version [e.g. 1.0.0] - find version number in app from Settings > About MetaMask

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by Fatxx** [comment]
FWIW: Only happens on Android

**Comment by Jens05** [comment]
I have the same bug. I submit a transaction and i get the same scenario as above. Furthermore, the transaction also **doesnt appear in activity**. Please let me know when this is fixed!

**Comment by khalilalilahmar** [comment]
Same issue after submitting transaction it's return the Txhash.
But that TxHash is no where to found  on etherScan 
and where going back to metamask i see green toast transaction completed after 2 seconds a red toast show with Oops Something went wrong

**Comment by cortisiko** [comment]
This was fixed in https://github.com/MetaMask/metamask-mobile/pull/4060 and will be in v5.3 release
