### ISSUE TITLE
Metamask generates incompatible QR codes

### ISSUE THREAD

**Issue by pvyhnal-generalbytes** [MetaMask/metamask-mobile#3935]
Hi,
We've got users with different wallets scanning their QR codes in our system to receive funds. 
Recently we got reports that users with Metamask cannot scan their QR codes.
The problematic part is the `@1` at the end of the content of the qr code. 
From a quick look the `1` seems to be a network or chain id. 
- Could you please confirm this? Does `1` mean main net and other values are different test nets?
- Is this according to some specification, or something like a BIP? Can you point me where to read more about that?
- Is it Metamask specific?
- If we only support main net, is it safe for us to 
  - strip the `@1` part IF it is `1` 
  - and fail the transaction if it is any other number?
- Did you consider using other format in BIP21 style like for example: `ethereum:0xfff...fffffff?amount=50&chain_id=1`? In that case we - and other wallets I believe - would ignore the parameters unknown to them

 

Example QR code:
![1646958761_374_Hoe-BNB-naar-een-Metamask-portemonnee-te-sturen](https://user-images.githubusercontent.com/44365000/159516153-f15c3a4f-9588-46c0-9859-3afb24077701.jpg)

**Comment by pvyhnal-generalbytes** [comment]
note I'm not sure what version is this screenshot from, is it possible it generates QR codes without the `@` in a newer version?

**Comment by pvyhnal-generalbytes** [comment]
Thanks @Fatxx  for the link to the EIP
We will use `@1` for mainnet  (and also when no chain-id is present)
but I think we should not send mainnet coins to an address containing `@2`, `@3` etc, right?

**Comment by Fatxx** [comment]
@pvyhnal-generalbytes yes you should try to prevent that as it may cause fund loss.

**Comment by Fatxx** [comment]
I will close this issue, please reopen it if you have further issues.

**Comment by pvyhnal-generalbytes** [comment]
Thank you
