### ISSUE TITLE
The latest update broke the browser on iOS

### ISSUE THREAD

**Issue by Mouradif** [MetaMask/metamask-mobile#3949]
**Describe the bug**

When trying to access the browser an error appears (twice):

```
View: BrowserTab
TypeError: undefined is not an object (evaluating 's.Device.isAndroid')
```

**Screenshots**
![image](https://user-images.githubusercontent.com/4118825/159850989-89bcb920-5658-439d-b6e9-70af4d63b96b.png)

**To Reproduce**
_Steps to reproduce the behavior_
1. Updated to the latest version
2. Try to access the browser
3. See error

**Expected behavior**
The browser should open

**Smartphone (please complete the following information):**
 - Device: iPhone SE
 - OS: iOS 15.3.1
 - App Version 4.3.0

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by Jaymz** [comment]
Same thing happening on android. No way to use browser as the error appears immediately with no option to open/close/switch tabs or get rid of the error.

**Comment by andreahaku** [comment]
@Mouradif @Jaymz please update to the latest updated version available in stores and this should be fixed. Please report here if it doesn't. Thanks

**Comment by Mouradif** [comment]
Yep the last update fixes it :)
