### ISSUE TITLE
Support Walletconnect V2

### ISSUE THREAD

**Issue by dokocat** [MetaMask/metamask-mobile#3957]
#Description
As a developer, I want to Walletconnect V2 support, so that connecting to my mobile dapp to metamask works better. Walletconnect has many improvements and stability enhancements as well.

**Comment by dokocat** [comment]
Can I put a bounty on this? 😅

**Comment by dokocat** [comment]
Any updates?

**Comment by kaylaatkrikey** [comment]
Any updates?

**Comment by dokocat** [comment]
whats the point of having this fake open source github if you don't even respond to people

**Comment by andreahaku** [comment]
Hi @dokocat, we plan to support Wallet Connect v2 by the end of Q1 2023.

**Comment by AlehUlitsionak** [comment]
Hi @andreahaku , according to WalletConnect's announcement wallets have to migrate by 16th of December 2022

**Comment by Doge-is-Dope** [comment]
Hi, will you support both `Sign` and `Auth`?

**Comment by andrearampin** [comment]
Hi @andreahaku do you have a more precise date on when the support will be provided? Thanks

**Comment by thanhduy26091995** [comment]
Hi there, any updates on Metamask?

**Comment by aksdevac** [comment]
Hi all, it is already mentioned by the team member that it will be integrated by the end of Q1, so mostly by the **last week** of March 2023. 
so no need to ask again & again before that.

**Comment by WyattMufson** [comment]
Wallet Connect V1 will end support on June 28th. MeteMask will upgrade to V2 on June 18th.

Source: https://medium.com/walletconnect/weve-reset-the-clock-on-the-walletconnect-v1-0-shutdown-now-scheduled-for-june-28-2023-ead2d953b595

**Comment by aksdevac** [comment]
Ok, so it seems its delayed above medium article is showing by Jun 15th for Metamask.

**Comment by duybvtit** [comment]
Today is end of Q1 2023, we're waiting for new update

**Comment by WyattMufson** [comment]
@duybvtit they announced the release more than a month ago, read my last comment

**Comment by duybvtit** [comment]
> @duybvtit they announced the release more than a month ago, read my last comment

Yes, I already read it. But I expected Metamask support V2 sooner.
As on Medium post, "Metamask will support on 15th June, Wallet connect V1 will end on 28th June", meaning as a developer we only have 13 days to read document, testing, migrating...
Also need to update to Play Store/ Apple Store. So I think 13 days is too short

**Comment by ldzoid** [comment]
Any updates on this, considering Q1 ended 2 days ago?

**Comment by nbutmickey** [comment]
any update？

**Comment by ardasatata** [comment]
Any update for V2?

**Comment by manoj2210** [comment]
Any Update for v2 ?

**Comment by Palashjain007** [comment]
Any update for v2?

**Comment by nmalzieu** [comment]
Hello! We're also waiting for MetaMask to support walletconnect v2 in order to migrate ! All other must have wallets for us (rainbow & ledger mostly) now support it, MetaMask is the blocker for us!
And since WalletConnect v2 is supposedly more stable, it's becoming quite a pain for us.

Thanks 🙏

**Comment by predrag-codetribe** [comment]
If a kitten died each time someone wrote "Any Update for v2 ?" we would have 6 dead kittens by now.

For people waiting for an update, 
I would suggest subscribing to the issue.

I am pretty sure that the WalletConnect devs will leave an update if they have any.

**Comment by predrag-codetribe** [comment]
Any update for v2? XD

**Comment by jewelsonn** [comment]
Why is it taking to long to update a simple uri ?

**Comment by jeffohbabygames** [comment]
any updates sirs?

**Comment by siosio34** [comment]
any updates ?

**Comment by kdenz** [comment]
Any updates?

**Comment by odin101** [comment]
any updateeeeeee?

**Comment by duybuikardiachain** [comment]
Seems Metamask delay by they're planning to introduce their SDK
Metamask SDK will replace WC, I think

**Comment by imaksp** [comment]
Hello all, I just found that work on v2 support has already been started on [walletconnect-v2](https://github.com/MetaMask/metamask-mobile/tree/feat/walletconnect-v2) branch. I think it will be integrated in live app before Jun 15 (as mentioned in Medium article)

**Comment by duybuikardiachain** [comment]
Any updated for now?

**Comment by chopperdaddy** [comment]
Any updates on this?

**Comment by imaksp** [comment]
Hello all, It looks like changes for this will be included in **v7** release.
See this release PR for details: https://github.com/MetaMask/metamask-mobile/pull/6465

**Comment by duybuikardiachain** [comment]
We're waiting new release

**Comment by siosio34** [comment]
It is understood that the schedule is later than planned. I'm really sorry, but I'm curious about the approximate time or schedule when the Metamask Wallet Connect v2 support version will be released.

**Comment by KangSungKyu** [comment]
any update? i want metamask mobile linking guide

**Comment by rabbitx-io** [comment]
Any updates for this?

**Comment by Z-Hayk** [comment]
We're waiting new release.

**Comment by ratio91** [comment]
June 15th was yesterday. Any updates?

**Comment by imaksp** [comment]
Hello all, it looks like it is delayed because of some blocking issues/bug due to RN & WC update, asking again & again won't make it faster, here are the issue list which needs to be fixed before the release:
[Click here to view blocking issues](https://github.com/MetaMask/metamask-mobile/labels/release-blocker)

& as you can see these issues are already assigned to someone from team.

**Comment by Z-Hayk** [comment]
@imaksp If you are talking about it:

https://github.com/MetaMask/metamask-mobile/issues/6583

I'm sorry you are wrong.

If you watch the video carefully you will see it is React but not React Native.

**Comment by Z-Hayk** [comment]
@imaksp If you are talking about it:
https://github.com/MetaMask/metamask-mobile/issues/6583

I'm sorry you are wrong

If you watch the video carefully you will see it is React (Browser) but not React Native.

**Comment by Z-Hayk** [comment]
https://github.com/MetaMask/metamask-mobile/issues/6626
https://github.com/WalletConnect/react-native-examples/issues/71
https://github.com/WalletConnect/web3modal-react-native/issues/61

**Comment by imaksp** [comment]
Hi @Z-Hayk , yes that is one issue with walletconnect & some others  
Metamask mobile app will be opened from browser using deeplink, 
he is testing integration with unreleased (7.x) metamask mobile & it had bugs as you can see connect popup does not appear in metamask app after app is opened from deeplink or app crashes :
https://images.zenhubusercontent.com/141427485/c6f25b9d-7db6-405e-8bb7-88afc160650d/screen_recording_2023_06_09_at_18_53_17.mov (React native is used in Metamask mobile app. but for testing you will need a web client)

Also this is the wallet app & it does not need web3-modal-react-native lib. there is big difference between wallet & dapp 
implementation. 
& Dapp can also be web based / native mobile app / react native/flutter mobile app & it needs to use Web3Modal SDK.
& Wallet apps need to use Web3Wallet lib.

I hope that this clears your confusion. & good news is that they have managed to fix #6583  bug now.

**Comment by mhm13dev** [comment]
Wallet Connect V2 is supported in Metamask Android now.

The new release is available on Android Play Store.

**Comment by mhm13dev** [comment]
But after Wallet Connect V2 support this issue is again occuring

I can't switch the chains.

https://github.com/MetaMask/metamask-mobile/issues/3546

**Comment by siosio34** [comment]
@imaksp 
hello should all the issues in the link below be able to release the wc2 support distribution supplement for too long?
https://github.com/MetaMask/metamask-mobile/labels/release-blocker
 
I'm really sorry, but the end of support for walletconnect v1 is approaching, and the team needs some time before switching to v2, so I'm asking a question to figure out the approximate support schedule.

Thank you for your hard work. I asked because the team's schedule was a bit rushed to wait. have a good day

**Comment by siosio34** [comment]
@mhm13dev Is it true that WC2 support is in the latest version of Metamask currently distributed? I'm not sure yet, so I'm asking.

**Comment by duybuikardiachain** [comment]
> > @duybvtit they announced the release more than a month ago, read my last comment
> 
> Yes, I already read it. But I expected Metamask support V2 sooner. As on Medium post, "Metamask will support on 15th June, Wallet connect V1 will end on 28th June", meaning as a developer we only have 13 days to read document, testing, migrating... Also need to update to Play Store/ Apple Store. So I think 13 days is too short

So close...

**Comment by Z-Hayk** [comment]
Who knows how soon Metamask will appear in WalletConnect v2?

**Comment by Z-Hayk** [comment]
https://github.com/WalletConnect/web3modal-react-native/issues/61#issuecomment-1595264752

**Comment by mhm13dev** [comment]
@siosio34 yes I used WC V2 in latest version of Metamask Android.

**Comment by muhammadsaddamnur** [comment]
I think this update is not yet available on the Play Store or App Store.

**Comment by siosio34** [comment]
@mhm13dev 

As far as I know, the https://github.com/MetaMask/metamask-mobile/labels/release-blocker issues below remain, so I know that the new version to which the walletconnect v2 version is applied has not been uploaded.

I'm really sorry to ask again, but have you tried connecting using Wallet Connect 2 after downloading the latest version from the App Store?

**Comment by siosio34** [comment]
I am currently experiencing the issue below.

https://github.com/MetaMask/metamask-mobile/issues/6583

Until this issue is fixed, it seems that you cannot use Wallet Connect v2 on Metamask Mobile.

**Comment by mhm13dev** [comment]
@siosio34 here are the screenshots from play store:
![Screenshot_20230619-093148.jpg](https://github.com/MetaMask/metamask-mobile/assets/28213822/5da84de8-fae5-4b5b-8093-272176c96123)

![Screenshot_20230619-093156.jpg](https://github.com/MetaMask/metamask-mobile/assets/28213822/ab300e7c-9af7-4e7f-bd36-441374196b63)

**Comment by siosio34** [comment]
It looks like you're using phased updates. In my play store history, it says version 6.6.0.
thank you for telling me. For now, I have no choice but to wait

**Comment by imaksp** [comment]
@siosio34 No need to wait for Android testing you can download current v7 build from apkmirror:
https://www.apkmirror.com/apk/metamask-web3-wallet/metamask-buy-send-and-swap-crypto/metamask-buy-send-and-swap-crypto-7-0-1-release/

**Comment by muhammadsaddamnur** [comment]
How about on iOS?

**Comment by Z-Hayk** [comment]
@imaksp @mhm13dev 
We are talking about something completely different.

**Comment by Z-Hayk** [comment]
Please don't confuse people!

**Comment by siosio34** [comment]
@imaksp  thanks!

**Comment by andriirak** [comment]
when is MetaMask release date for walletconnect v2 ?

**Comment by muhammadsaddamnur** [comment]
@imaksp I think it is not recommended to download a crypto wallet from a third-party store due to security reasons.

**Comment by benharvey1213** [comment]
Any updates on this?

**Comment by StepsOnes** [comment]
when the update???

**Comment by imaksp** [comment]
It is now available on Android:
play store (checked in India):
https://play.google.com/store/apps/details?id=io.metamask

Github release (it could be trusted now, for apk download):
 https://github.com/MetaMask/metamask-mobile/releases/tag/v7.0.1
 
& Still not available on Apple App Store.

**Comment by Z-Hayk** [comment]
@imaksp Please don't spam here.
I'm not interested in what Play Market !

Please don't spam here!!

Here is the reason for my waiting
Watch the video, read the information that I wrote there.
https://github.com/MetaMask/metamask-mobile/issues/6626

**Comment by imaksp** [comment]
Lol, reacting to your own comment by using different accounts won't get your issue resolved, & giving update about release is not spam.

& your issue is very different  that list in video is managed by WalletConnect registry not Metamask. 
& They have not added Metamask in v2 list may be because iOS release is pending.

**Comment by Z-Hayk** [comment]
I see no reason to continue!
Don't spam here!

**Comment by Z-Hayk** [comment]
Any updates on this?)

**Comment by georgecpp** [comment]
MetaMask still not showing in list although the walletconnect v2 integration is mentioned on Play Store...

**Comment by mqklin** [comment]
Oh nice, I have only 2 days to test WC2 integration!

**Comment by georgecpp** [comment]
> Oh nice, I have only 2 days to test WC2 integration!

@mqklin so is MetaMask showing up in the list using walletconnect v2 react native modal??? 2 days until walletconnect v1 sunset and we're in the middle of nowhere with MetaMask, by far the most used wallet for dev purposes...

**Comment by chadyj** [comment]
> @mqklin so is MetaMask showing up in the list using walletconnect v2 react native modal???

Yes it is.

**Comment by tmbv93** [comment]
MetaMask now shows up in Web3Modal on iPhone, but has anyone managed to connect and sign transactions?
On our tests on iOS with WC2 and Web3Modal, MetaMask doesn't respond to requests to connect. The app opens up, but nothing happens inside the app. Rainbow Wallet seems to work fine, and WC1 still works. 

Tested with Safari and Firefox on iPhone 13 Pro.

**Comment by chadyj** [comment]
> MetaMask now shows up in Web3Modal on iPhone, but has anyone managed to connect and sign transactions? On our tests on iOS with WC2 and Web3Modal, MetaMask doesn't respond to requests to connect. The app opens up, but nothing happens inside the app. Rainbow Wallet seems to work fine, and WC1 still works.
> 
> Tested with Safari and Firefox on iPhone 13 Pro.

@tmbv93 Can you confirm your Metamask version is >7?

**Comment by tmbv93** [comment]
@chadyj my mistake, I was not on version 7! Could have sworn I had the last version later today, but noticed I could update now. WC2 seems to be working smoothly on 7. Thanks guys -- and sorry about the confusion =)

**Comment by duybuikardiachain** [comment]
I'm using Android SDK
I'm able to connect with metamask, but when I try to request eth send transaction.
I cannot get callback to get redirectUri from SDK
So the app won't know when should to redirect, does anyone facing the same issue with me?
Also seem WC2 slower than WC1, my app using WC1 and callback very fast

**Comment by vfn** [comment]
> The following code can connect with Rainbow Wallet and return to our app after clicking "connect". We can also receive callbacks from sessionSettlePublisher. However, it does not work with Metamask iOS (7.0.1). Firstly, we cannot redirect back correctly, and secondly, we cannot receive callbacks either. I am unsure if there is something wrong with my code. Can you help me take a look?
> 
> ```swift
> // subscribe
> Sign.instance.sessionSettlePublisher.sink { session in
>     print("==== sessionSettlePublisher: ", session.accounts)
> }.store(in: &disposeBag)
> // connect
> let namespaces = ["eip155": ProposalNamespace(chains: [Blockchain("eip155:1")!],
>     methods: ["personal_sign"],
>     events: [])]
> let uri = try await Pair.instance.create()
> try await Sign.instance.connect(requiredNamespaces: namespaces, topic: uri.topic)
> // jump to mm
> let deepLinkUrl = "https://metamask.app.link/wc?uri=" + uri.deeplinkUri
> // let deepLinkUrl = "https://rnbwapp.com/wc?uri=" + uri.deeplinkUri
> await UIApplication.shared.open(URL(string: deepLinkUrl)!)
> ```

@ngn999 use the same value you used for `requiredNamespaces` for `optionalNamespaces`.
```swift
 try await Sign.instance.connect(requiredNamespaces: namespaces, optionalNamespaces: namespaces, topic: uri.topic)
```

If that works, that's because of a already known issue on the WalletConnect side that is getting fixed, and for now, this workaround might needed for your app to work with Metamask

**Comment by ngn999** [comment]
> > The following code can connect with Rainbow Wallet and return to our app after clicking "connect". We can also receive callbacks from sessionSettlePublisher. However, it does not work with Metamask iOS (7.0.1). Firstly, we cannot redirect back correctly, and secondly, we cannot receive callbacks either. I am unsure if there is something wrong with my code. Can you help me take a look?
> 
> > 
> 
> > ```swift
> 
> > // subscribe
> 
> > Sign.instance.sessionSettlePublisher.sink { session in
> 
> >     print("==== sessionSettlePublisher: ", session.accounts)
> 
> > }.store(in: &disposeBag)
> 
> > // connect
> 
> > let namespaces = ["eip155": ProposalNamespace(chains: [Blockchain("eip155:1")!],
> 
> >     methods: ["personal_sign"],
> 
> >     events: [])]
> 
> > let uri = try await Pair.instance.create()
> 
> > try await Sign.instance.connect(requiredNamespaces: namespaces, topic: uri.topic)
> 
> > // jump to mm
> 
> > let deepLinkUrl = "https://metamask.app.link/wc?uri=" + uri.deeplinkUri
> 
> > // let deepLinkUrl = "https://rnbwapp.com/wc?uri=" + uri.deeplinkUri
> 
> > await UIApplication.shared.open(URL(string: deepLinkUrl)!)
> 
> > ```
> 
> 
> 
> @ngn999 use the same value you used for `requiredNamespaces` for `optionalNamespaces`.
> 
> ```swift
> 
>  try await Sign.instance.connect(requiredNamespaces: namespaces, optionalNamespaces: namespaces, topic: uri.topic)
> 
> ```
> 
> 
> 
> If that works, that's because of an already known issue on the WalletConnect side that is getting fixed, and for now, this workaround might needed for your app to work with Metamask

It works. Thank you very much.

**Comment by StevenBarnett1** [comment]
Multichain connections doesn't work. When i add multiple chain ID's to chains array and i try to connect it just opens the metamask app and nothing happens. I have the latest metamask version. If i have one chain ID in the array it works, but it only tries to connect to the chain that metamask is currently connected to. I.e. if metamask is on polygon and i have id 1 in chains array (ethereum), it will attempt to connect to polygon.

`  const sessionParams = {
    namespaces: {
      eip155: {
        methods: ["eth_sendTransaction", "eth_sign", "personal_sign", "eth_signTypedData"],
        chains: ["eip155:1","eip155:42161", "eip155:10","eip155:137"],
        //chains: ["eip155:137"],
        events: ["chainChanged", "accountsChanged"],
  
        rpcMap: {},
      },
    },
  };`

**Comment by maltsevoff** [comment]
anybody knows how to connect metamask with wallet connect Auth protocol? Detailed issue below

https://github.com/MetaMask/metamask-mobile/issues/6704
