### ISSUE TITLE
Deep link opening iOS AppStore even when MetaMask is installed

### ISSUE THREAD

**Issue by epshtielsl** [MetaMask/metamask-mobile#3965]
**Describe the bug**
Deep links are opening up the App Store and prompting users to install MetaMask, even when the app is already installed on the devicie.

**Screenshots**
https://community.metamask.io/t/deeplink-opens-appstore-when-app-installed/18199/12

**To Reproduce**
Open any app that utilizes deep links to integrate with MetaMask, i.e. dapps that utilize WalletConnect.  When you attempt to sign a transaction, or other requests, MetaMask will open briefly, then the Apple AppStore opens up.

**Expected behavior**
MetaMask opens and performs the task requested.

**Smartphone (please complete the following information):**
 - Device: iPhone 12 Pro
 - OS: iOS 15.3.1
 - App Version: 4.2.2

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by andreahaku** [comment]
Thanks @epshtielsl for opening the issue. We are investigating it and trying to find the reason for this behaviour. Thanks again.

**Comment by rafaelaugustos** [comment]
any update?

**Comment by zosim** [comment]
> any update?

yes also hoping for some news. Thanks.

**Comment by thunderball1** [comment]
@andreahaku is there any update? this is happening for very long time

**Comment by liho00** [comment]
same issue, izit IOS or IOS version issues?

**Comment by andreahaku** [comment]
Did you try the latest version of the app (5.0.x) as most of the deep links related issue should be solved with it. Please let me know. Thanks!

**Comment by liho00** [comment]
> Did you try the latest version of the app (5.0.x) as most of the deep links related issue should be solved with it. Please let me know. Thanks!

Same not working, here is the screen recording https://user-images.githubusercontent.com/77238199/165326244-c9471c12-f88b-4ff8-b207-80f410623c51.MOV

**Comment by un7c0rn** [comment]
Same issue here, using Metamask version 5.0.1. The deeplink from WC is `https://metamask.app.link/wc`––is this to spec?

**Comment by un7c0rn** [comment]
According to this we're not generating the right deep link:

# For deep links
examplewallet://wc?uri=wc:00e46b69-d0cc-4b3e-b6a2-cee442f97188@1?bridge=https%3A%2F%2Fbridge.walletconnect.org&key=91303dedf64285cbbaf9120f6e9d160a5c8aa3deb67017a3874cd272323f48ae

# For universal links
https://example.wallet/wc?uri=wc:00e46b69-d0cc-4b3e-b6a2-cee442f97188@1?bridge=https%3A%2F%2Fbridge.walletconnect.org&key=91303dedf64285cbbaf9120f6e9d160a5c8aa3deb67017a3874cd272323f48ae

https://docs.metamask.io/guide/mobile-best-practices.html#the-provider-window-ethereum

**Comment by un7c0rn** [comment]
Our link doesn't even have the `uri` or `bridge` params in it, no wonder this fails.

**Comment by un7c0rn** [comment]
Tried with:

https://metamask.app.link/wc:bdff4633-75ae-4477-a895-8a09cc971130@1?bridge=https%3A%2F%2F[redacted]-secure-bridge.com&key=[redacted]

which seems to match the spec here [1] but the deep link still goes to the app store.

[1] https://docs.walletconnect.com/mobile-linking

**Comment by andreahaku** [comment]
So we have investigated the issue and unfortunately it does not depend on MetaMask mobile but on a mix of restrictions from mobile browsers and our deep link service provider.

The issue **doesn't happen** if the link is "tapped/clicked" by the user. It does happen with redirects and similar programmatic link openings.

So there are two potential workaround to it:

1. make the link tappable by associating it to a button or something like that
2. "simulate" a tap/click

About point 2 I just developed and tested a quick and simple JS function that does that.

```
function openMetaMaskUrl(url) {
    const a = document.createElement("a");
    a.href = url;
    a.target = "_self";
    document.body.appendChild(a);
    a.click();
    a.remove();
}
```

and it can be used like this:

`openMetaMaskUrl("https://metamask.app.link/dapp/google.com");`

This works on Android and iOS Chrome. On iOS Safari still opens the app store instead of MetaMask mobile app.

Let me know if this helps you. Thanks.

**Comment by gsyndromes** [comment]
I've tried your implementation but it still open up appstore on iOS chrome, anyone else facing this issue?

**Comment by varseb** [comment]
Same issue trying to integrate a dApp with WalletConnect.
Using Safari, after pressing MetaMask icon inside WalletConnect modal it opens the app store.

I saw the address bar changing to metamask.app.link.. and then app store is opened

MetaMask 5.0.1
IOS 15.4.1

**Comment by varseb** [comment]
↑ 
Similar behavior using Chrome, after pressing MetaMask icon inside WalletConnect modal, it prompts

"This page will open in another application"

and pressing "Open" redirects to app store as well

**Comment by KimJaekyoon** [comment]
this problem still goes on in safari, chrome, etc. only open app store

**Comment by anxolin** [comment]
Same issue in Safari, trying to connect to MM using web3-react library (with wallet connect provider). Users get a pretty bad UX

**Comment by un7c0rn** [comment]
You can fix this by overriding the default WalletConnect provider implementation of the URL redirect, which is specified as a handler of the `call_request_sent` event:

```
        if (isMobile) {
          provider.connector.off("call_request_sent");
          provider.connector.on("call_request_sent", () => {
            console.log(
              "passing call_request_sent event on with NOP"
            );
          });
        }
```

The logic above disables WalletConnects default handler, which sets window.location to the MM universal link (this doesn't work). Once disabled, make your own button to initiate the universal link action:

```
    <Button
      href={makeMobileUniversalTxSignLink()}
      rel={"noopener noreferrer"}
      target={"_blank"}
    >
```

**Comment by tuoomz** [comment]
> 

can you have the implementation of makeMobileUniversalTxSignLink()?

**Comment by andreahaku** [comment]
As an alternative to `https://metamask.app.link/dapp/` you can use `dapp://` schema. So for example instead of using: `https://metamask.app.link/dapp/google.com` you can do `dapp://google.com` and this opens MetaMask app browser with Google.com.

This is not a deep link, so the only disadvantage is that it won't check if MM mobile is installed and if not take the user to stores. It only works if the app is already installed.

**Comment by un7c0rn** [comment]
> > 
> 
> can you share the implementation of makeMobileUniversalTxSignLink()?

@tuoomz yes

```
const FALLBACK_TRANSACTION_SIGNING_APP_LINK =
  "https://metamask.app.link";

function makeMobileUniversalTxSignLink() {
  let result = FALLBACK_TRANSACTION_SIGNING_APP_LINK;
  try {
    result = JSON.parse(
      localStorage.getItem("WALLETCONNECT_DEEPLINK_CHOICE")
    ).href;
  } catch (e) {
    console.error(e);
  }
  return result;
}
```

**Comment by andreahaku** [comment]
Yesterday I developed a potential fix for this that you can find here: https://github.com/MetaMask/metamask-mobile/pull/4167

We are testing it internally and hopefully have it merged into one of the coming releases (hopefully 5.2.0).

If anyone has a way to test it and has some feedback it's more than welcome ;) Thanks

**Comment by liho98** [comment]
> Yesterday I developed a potential fix for this that you can find here: #4167
> 
> We are testing it internally and hopefully have it merged into one of the coming releases (hopefully 5.2.0).
> 
> If anyone has a way to test it and has some feedback it's more than welcome ;) Thanks

Can release this app now? And let public test, 8 days testing deep link quite slow, let public test this new feature can be faster.

**Comment by Fatxx** [comment]
Close in favour of https://github.com/MetaMask/metamask-mobile/pull/4167

**Comment by Saddam-tech** [comment]
> 

This one worked for me, thanks)
