### ISSUE TITLE
RelayChain Website Not Work In MetaMask Built-in Browser

### ISSUE THREAD

**Issue by fzhwenzhou** [MetaMask/metamask-mobile#3984]
**Bug Description**
The Relaychain website cannot be used in MetaMask Android APP, because I cannot connect to the wallet.

**Steps to Reproduce**
1. Open MetaMask Android Wallet
2. Click on the web3 browser
3. Visit the webpage
4. Click "Connect Wallet"

**Expected Behavior**
It should appear 4 options to connect the wallet. It seems well in mobile firefox or chrome, but not work on the built-in browser of Metamask.
It should be:
![Screenshot_20220330_233605_org.mozilla.firefox.jpg](https://user-images.githubusercontent.com/61855675/160874388-d297aef8-9fdc-4024-bb7c-0b73e6fb693b.jpg)

But actually:
![Screenshot_20220330_233546_io.metamask.jpg](https://user-images.githubusercontent.com/61855675/160874291-8da2b442-a040-479f-887c-9dcb2e8d2cfc.jpg)

**Comment by gantunesr** [comment]
Hey @fzhwenzhou, looks like you need to use` window.ethereum` and not `window.web3.currentProvider`. I'll leave here the warnings we're getting from your dapp

https://docs.metamask.io/guide/provider-migration.html#replacing-window-web3 

![Screen Shot 2022-06-08 at 14 59 47](https://user-images.githubusercontent.com/17601467/172695605-94e1bebb-77fb-4411-a0f8-971e9a2c0184.png)

**Comment by fzhwenzhou** [comment]
However, how could I do that? I'm just using the mobile phone app.
