### ISSUE TITLE
Bug(SendFlow): input `To:` overwrites itself

### ISSUE THREAD

**Issue by jpcloureiro** [MetaMask/metamask-mobile#4005]
**Describe the bug**
Scope: `SendFlow`
`To:` input field behaves erratic when the user tries to write an ENS address.
It looks like it has a race condition on the input onChange event while queries for the ENS string.
As soon as the user types something like `ethan.n` the next characters get overwritten frequently. It is more noticeable when on slow connections.

Also tested on 4.1.1 and it is not as bad as on 4.3.1.

**Screenshots**

https://user-images.githubusercontent.com/1649425/161142647-8cf27324-70da-4e9a-b1ba-449240d7598b.mp4

**To Reproduce**

1. Go to Wallet
2. Click on Send
3. Write ethan.notethereum.eth on the `To:` input field
4. Proof that is hard to write & delete

**Expected behavior**
The input field should have all the characters the user inputs with as low input lag as possible

**Smartphone:**
 - Device: Xiaomi 11 Lite
 - OS: MIUI 13 (Android 12)
 - App Version 4.3.1

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by tommasini** [comment]
This issue its fixed on this [PR ](https://github.com/MetaMask/metamask-mobile/pull/4089)

**Comment by tommasini** [comment]
This issue is solved 🚀
