### ISSUE TITLE
Chinese letter is broke on Metamask.

### ISSUE THREAD

**Issue by MernDev0603** [MetaMask/metamask-mobile#4007]
**Describe the bug**
_A clear and concise description of what the bug is_

**Screenshots**
_If applicable, add screenshots or links to help explain your problem_

**To Reproduce**
_Steps to reproduce the behavior_

**Expected behavior**
_A clear and concise description of what you expected to happen_

**Smartphone (please complete the following information):**
 - App Version [e.g. 1.0.0] - find version number in app from Settings > About MetaMask

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by MernDev0603** [comment]
fix

**Comment by gantunesr** [comment]
@MernDev0603 can you provide more information about your issue including screenshots and/or recordings?
