### ISSUE TITLE
[Android] MetaMask provider not injected when using react router

### ISSUE THREAD

**Issue by ipetrov22** [MetaMask/metamask-mobile#4019]
**Describe the bug**
The MetaMask provider is not correctly injected in the embedded browser when using react-router.
`window.ethereum` is available only on `/`.

If you navigate to another route (f.e. `/login`) using the router `window.ethereum` will still be available, **but if you refresh the page or directly open that route the provider won't be injected.**

The routes are wrapped in `<BrowserRouter>`

The functionality works correctly on iOS and Desktop. 

**Video material**

https://user-images.githubusercontent.com/62555364/161276208-3fb33761-b637-4e68-8280-9d409e8a3748.mp4

**Expected behavior**
`window.ethereum` to always be available on Android in the MetaMask browser.

**Smartphone**
 - Device: Xiaomi Pocophone F1 (tested on other Android devices with the same results)
 - OS: Android 10
 - App Version 4.3.1

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by phoax** [comment]
Hello, we have the same issue, on Android `window.ethereum` works only on `/`, but on other pages it is empty.

I tried routing with https://github.com/molefrog/wouter, but same behavior.

**Comment by p-hronesis** [comment]
Please does anyone know any way around this metamask bug. It's affecting my work/

**Comment by p-hronesis** [comment]
> Please does anyone know any way around this metamask bug. It's affecting my work/
I have tried every possible work around I know

**Comment by munawiki** [comment]
I'm using AWS CloudFront and have resolved the issue by creating a custom error response
