### ISSUE TITLE
Deep links doesn't work correctly from an external app(telegram, facebook, tiktok ...) built-in browser

### ISSUE THREAD

**Issue by ArtemKirilyuk** [MetaMask/metamask-mobile#4025]
**Describe the bug**
Same as [3534](https://github.com/MetaMask/metamask-mobile/issues/3534) and [3678](https://github.com/MetaMask/metamask-mobile/issues/3678), but I use an external app built-in browser (checked in telegram, facebook, tiktok in-app browsers) instead of using an external standalone browser (i.e. Chrome) as in the reported issues above.
The issue is not reproduced when using a standalone browser - all works fine in this case.
Note: I reproduced the issue on Android 9

The issue is critical for me because I run ads on facebook and tiktok to promote my project. Their apps open external links in its built-in browser by default. Thus, all the funnel is failing.

**Screenshots**

https://user-images.githubusercontent.com/37383460/161400325-74e81f81-68bd-4ae5-b164-c0fa41d10445.mp4

"GET METAMASK" button from the video leads to the deep link generated [here](https://metamask.github.io/metamask-deeplinks/#) : https://metamask.app.link/dapp/***/, where *** is my site domain

**To Reproduce**
_Steps to reproduce the behavior_
Please check the video above

**Expected behavior**
Expected to open Metamask Mobile > Browser > Link to website

**Smartphone (please complete the following information):**
 - Device: Honor 9 Lite 
 - OS: Android 9
 - App Version v4.3.1 (859)

**Comment by kirilyukkostia** [comment]
I've got the same problem.
