### ISSUE TITLE
approve screen problem

### ISSUE THREAD

**Issue by smarteasy** [MetaMask/metamask-mobile#4027]
In the general transaction screen, there is a part that receives and processes transaction information (gas price or eip1559 information) sent from the client, but that part is omitted in the approve screen.

**Comment by tommasini** [comment]
@smarteasy could you provide more information? If possible attach some screenshots with examples please!

**Comment by tommasini** [comment]
@smarteasy I'm closing this because no answer was provided, please feel free to open a new issue if this continues to happen with you
