### ISSUE TITLE
> Currently multiple tests are coupled to a single fixture data file. This becomes a problem if we update a fixture data file (e.g. test/e2e/fixtures/imported-account/state.json) multiple tests are affected. At the time of writing the `imported-account` fixture file is used in 10+ different specs.

### ISSUE THREAD

**Issue by JessePinkman48** [MetaMask/metamask-mobile#4037]
> Currently multiple tests are coupled to a single fixture data file. This becomes a problem if we update a fixture data file (e.g. test/e2e/fixtures/imported-account/state.json) multiple tests are affected. At the time of writing the `imported-account` fixture file is used in 10+ different specs.
> 
> AC:
> 
> * each spec has its own fixture data
> * fixture data is stripped down and only consists of data need for the test

_Originally posted by @JessePinkman48 in https://github.com/MetaMask/metamask-extension/issues/14340#issuecomment-1088344750_

**Comment by Fatxx** [comment]
Hey @JessePinkman48

I feel like this is not related with MM Mobile, I will close this for now.
