### ISSUE TITLE
2022 Q2 Mobile - Permission System Components

### ISSUE THREAD

**Issue by Cal-L** [MetaMask/metamask-mobile#4072]
### **Description**

This is the epic for the permission system feature.
https://www.figma.com/file/LRpO3E6SFcNs6KXCfolwyM/Permissions-System---Intermediate-Design?node-id=1399%3A19870&t=MfuswSUPnm2XCoZA-0

**Comment by omnat** [comment]
@Cal-L This Epic this doesn't reflect Permissions Controller merge step. Is this epic phase 1 (componentization) only? Could you please share the epic that would show Permissions Controller step? We'd like to add that Epic to Snaps Platform team's roadmap, as that's a dependency to bring Snaps on mobile.

**Comment by gauthierpetetin** [comment]
Closing this epic as all issues are completed.
