### ISSUE TITLE
[PS] Componentize Account Avatar

### ISSUE THREAD

**Issue by Cal-L** [MetaMask/metamask-mobile#4075]
### **Description**

Componentize the `AccountAvatar` component. This should support both Jazzicons as well as Blockies.

### **Technical Details**

Suggestion
<img width="719" alt="image" src="https://user-images.githubusercontent.com/10508597/163512812-3684bb5b-f5f3-45a2-8f04-cdc6f30b1cbe.png">

- [ ] Add component to Storybook
- [ ] Write unit test

### **Acceptance Criteria**

- [ ] Can view component in Storybook
- [ ] Unit test passes

### **References**

-  https://www.notion.so/Q2-Extension-IA-Nav-Design-System-Related-Tickets-9e403db21485420e91d1a6c64a3d7065#2852bb6e949f4451a1084f7866b7c3b4

**Comment by sethkfman** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/MetaMask-Mobile-5f984938ddc0e4001d4b79cb/issues/MetaMask/metamask-mobile/4075?planning-poker) with ZenHub @blackdevelopa @chrisleewilcox @cortisiko @jpcloureiro
