### ISSUE TITLE
[PS] Componentize Favicon Avatar

### ISSUE THREAD

**Issue by Cal-L** [MetaMask/metamask-mobile#4104]
### **Description**

Componentize the `FaviconAvatar` component.

### **Technical Details**

Suggestion
<img width="701" alt="image" src="https://user-images.githubusercontent.com/10508597/163512986-ff6fcb7f-84f9-4b3b-b43e-1465d8bc2185.png">

- [ ] Add component to Storybook
- [ ] Write unit test

### **Acceptance Criteria**

- [ ] Can view component in Storybook
- [ ] Unit test passes

### **References**

-  https://www.notion.so/Q2-Extension-IA-Nav-Design-System-Related-Tickets-9e403db21485420e91d1a6c64a3d7065#2852bb6e949f4451a1084f7866b7c3b4

**Comment by sethkfman** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/MetaMask-Mobile-5f984938ddc0e4001d4b79cb/issues/MetaMask/metamask-mobile/4104?planning-poker) with ZenHub @chrisleewilcox @cortisiko @blackdevelopa @jpcloureiro

**Comment by Cal-L** [comment]
Merged.
