### ISSUE TITLE
[5.3] RangeError: currency is not a well-formed currency code

### ISSUE THREAD

**Issue by AlexHerman1** [MetaMask/metamask-mobile#4107]
**Description:**
App is mostly crashing when trying to perform actions such as swap/claim/stake on a dapp, the error does break the core flow of the app, but will go away upon closing and reopening the app.

This error is produced when fiat currency is set to some of the alternative currencies in the settings-->general-->currency conversion list.

**Screenshots**
![image](https://user-images.githubusercontent.com/38788573/163408347-0a943f93-7d72-49c6-a13b-4f67844a8e9d.png)

**To Reproduce**
1. Go to settings-->general-->currency conversion and choose USDT - tether
2. Go to the browser, navigate to pancakeswap.finance
3. Try to perform a swap transaction
4. App will crash and produce error, txn will not go through

**Expected behavior**
Users can set any currency conversion and still interact with dapps successfully without producing the "well-formed currency" error

**Smartphone (please complete the following information):**
 - Device: Android and Apple devices
 - OS: multiple
 - App Version: 4.4.0

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by Fatxx** [comment]
Related with #4057
