### ISSUE TITLE
SendFlow: Amount input value overflows horizontally

### ISSUE THREAD

**Issue by jpcloureiro** [MetaMask/metamask-mobile#4122]
**Description**
Amount input overflows horizontally with big numbers or with numbers with a lot of decimals . This impacts UX by making more difficult for the user to confirm the amount to transfer.

**Evidence**
Video - https://recordit.co/6Zwoa30aU3

**Technical Details**
Font size could change based on the input value length, the way [swaps does it](https://recordit.co/Tr1PAtpfqn).

**Comment by gantunesr** [comment]
@tommasini could this issue next sprint
