### ISSUE TITLE
Deep links on Android fail due to browser application

### ISSUE THREAD

**Issue by jellearts** [MetaMask/metamask-mobile#4139]
### **Description**

On several Android devices Metamask deep links seem not to be working. After clicking the deeplink the phone opens the link within the device default browser, which in turn redirects the action towards the Metamask App. Metamask will open, but no action is being performed.

The solution is to prevent the default browser within the Android device to open the deeplink first. The only way to establish this is to manually change settings within Android app settings, in order to set Metamask as a prefered application when opening specific links that relate to Metamask (in this case metamask.app.link).

The problem here is that this needs to be manually adjusted by the Android user. Is it possible to have this feature turned on by default?

I've uploaded a video explaining the problem and the process towards the solution: https://www.youtube.com/watch?v=-o8GIJyOxSk

### **Technical Details**

Tested on a Galaxy S20 running Android 12.0 and Metamask 4.4.0
Tested on a Galaxy S7 running Android 8.0 and Metamask 4.4.0

**Comment by karacurt** [comment]
I'm also having the same problem with Galaxy S20 and Metamask 4.4.0

**Comment by andreahaku** [comment]
Please update to the latest version of the app (5.0.x) that should have solved issues related to deep links. Please report here if they still persist or if they are finally solved for you as well. Thanks!

**Comment by jellearts** [comment]
Works!

**Comment by andreahaku** [comment]
> Works!

Awesome. Thanks.
