### ISSUE TITLE
View:Root Error: Text strings must be rendered within a <Text> component.

### ISSUE THREAD

**Issue by anaamolnar** [MetaMask/metamask-mobile#4156]
**Description:**
Metamask app crashes when trying to transfer funds between accounts to an address that does not have a name associated with it. The error goes away upon closing and reopening the app or pressing the 'Try again' button which locks Metamask and asks for the password again.

**Screenshots:**
![F82C7265-E1A0-48C7-B4B2-795F552B6A31](https://user-images.githubusercontent.com/82837486/165310698-3d6450f6-c7f5-4460-b811-3a4b8673c76f.png)

**Steps to reproduce:**
1. Go to Account 1 on the main page
2. Long press the 'Account 1' text until it lets you edit the text field (name of the account)
3. Delete the name of the account and leave the text field empty
4. Switch to a different account and press the send button
5. Select 'Transfer between accounts' and choose the account with an empty text field
6. See error

**Expected behavior:**
Users are able to perform the transaction even if the destination address has an empty text field (does not have a name).

**Smartphone (please complete the following information):**
 
 - OS: Android and Apple devices
 - App Version: 5.0.1 

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by AlexHerman1** [comment]
FWIW there should probably be some kind of check in-app to make sure that users are entering at least one character as an account alias. Nice work @anaamolnar !

**Comment by gantunesr** [comment]
Proposed solution: Keep the last account name in case the string is empty

**Comment by Fatxx** [comment]
Closing in favor of #4684
