### ISSUE TITLE
Metamask browser opens many links in android default browser, instead of in-app

### ISSUE THREAD

**Issue by Naguz** [MetaMask/metamask-mobile#4162]
Note: This is NOT about deep links opened from other app not opening properly in MM browser. 
Problem description: Many links clicked on inside the MM browser, that are intended to open a new window or tab, does NOT open inside MM browser, but instead launches the android default internet browser.

Steps to reproduce:
1: Go to padswap.exchange in MM browser
2: Click either the "Swap" or "Farm" (or most any other) button on the page.
3: The new page opens in another browser (whichever browser is set to android default web browser), *not* inside MM browser

Correct behavior: Open all links not specifically bound to other apps, inside MM browser.

I have tried this with several other web browser that are not set to the default browser, and none of them exhibit the same behavior.

MetaMask version: 5.0.1
Phone: Galaxy S10 (Android 12, latest updates, non-carrier version)

**Comment by Great-Odin** [comment]
I can confirm that at least in my case new tabs don't even open in another browser.
Something like the following doesn't open a new tab. Other mobile browsers do.
```window.open(url, "about:blank", "noopener");```

 This is important because some apps will only work if using metamask due to connecting wallets, but require opening new tabs for some flows

**Comment by SteversIO** [comment]
This affects SSO and is a major issue for us

**Comment by mattdxn** [comment]
This is still an issue. Super annoying.

**Comment by abachmon7** [comment]
Still an issue

**Comment by juschief** [comment]
Still an issue, it's directing/pointing to the Metamask app in the App Store.

**Comment by thuyetnguyen95** [comment]
Can anyone solve it?

**Comment by LeftBrainCreated** [comment]
still an issue.
Nobody has taken ownership of this?

**Comment by livelybone** [comment]
Still an issue
