### ISSUE TITLE
iOS Metamask browser cache won't clear

### ISSUE THREAD

**Issue by siloitgroup** [MetaMask/metamask-mobile#4190]
v5.0.1 (877)
iPhone XR

I've cleared the cache using the three options in the app Settings. I've restarted my phone. I've tried switching to different networks. Some changes to our site are not showing in metamask. There is no cache on the server side. Other mobile iOS browsers are fine.

**Comment by Anastacia-43** [comment]
I will suggest you contact metamask support and click on the live chat message logo to talk with a Developer from metamask through their live chat Developers forum to help you sort this issue out right away. Click on the —> https://metamaskzendesk.helpsconnect.live/#

**Comment by tommasini** [comment]
Thanks for reporting @siloitgroup, could you please share some more detailed information.
It would be perfect if you tell us
- What are you trying to do
- What is not specifically happening
- What is your website 
- (5*) A small demo showing exactly the problem

**Comment by siloitgroup** [comment]
Our site has been updated. New button functions and text. On other browsers it looks right. On desktop Chrome in the Inspect mode with iPhone emulation, works fine. Only the metamask iOS app browser still shows the old content with broken button function. The website is built with wordpress. You need to be signed in as a Subscriber to see this stuff. If someone wants to help I can email them login credentials and more details.

**Comment by siloitgroup** [comment]
I installed Metamask on my iPad. The site works fine there. I think this confirms my iPhone has something cached in the Metamask browser that will not clear.

**Comment by siloitgroup** [comment]
I just deleted the app from my iPhone and then reinstalled it. Now the website shows the correct content. My iPhone XR is fully updated and not jailbroken.

Maybe the app can have a more aggressive Browser Reset option that restores the browser to defaults and clears all local temp files?

**Comment by gantunesr** [comment]
Hey @siloitgroup, we'll prioritize this bug and update this issue accordingly

**Comment by gantunesr** [comment]
We'll be using this issue to track the development https://github.com/MetaMask/metamask-mobile/issues/4245

**Comment by Fatxx** [comment]
Context: Probably look for a way to easily reset websites cache.

**Comment by Garito** [comment]
I understand that dealing with this kind of projects is hard but you should remember that, right now, metamask for ios is useless for startups that should change their code a lot
This should be priority high again

**Comment by thekesslereffect** [comment]
This is still a big issue. Can we get a fix for this v_v

**Comment by tanyeun** [comment]
I experienced the same issue. I am using iPhone SE2 and the MetaMask app version is v5.4.0(931)

**Comment by WalkToFreedom** [comment]
Wow, I can't believe this hasn't been fixed in 4 months. I have the same issue. iPhone SE2. MetaMask v5.6.0(950)

**Comment by gantunesr** [comment]
Hey @WalkToFreedom, we appreciate the patience since this issue wasn't easy to fix. Version v5.7.0 will include the fix.

**Comment by Pete4GAT** [comment]
> Hey @WalkToFreedom, we appreciate the patience since this issue wasn't easy to fix. Version v5.7.0 will include the fix.

I’m now on version v5.9.1 on iOS and it still seems impossible to clear the browser cache or force a page reload. This is causing significant issues in our project as we have old cached pages with a significant bug and we’re unable to guide MetaMask users to be able to “fix” it by forcing a reload of the page to get the most recent version.

It can be really critical for projects to be able to fix issues and the inability to force a page reload or clear the browser cache on MetaMask is a very serious flaw.
In our case it is now a security risk, just a functionality bug - but I imagine that some projects are not so fortunate.

**Comment by romansemko** [comment]
> Hey @WalkToFreedom, we appreciate the patience since this issue wasn't easy to fix. Version v5.7.0 will include the fix.

v5.9.0 on iPhone. I redeployed our DApp on Vercel with a critical hotfix. All other platforms pick up the changes, except Metamask. Metamask holds onto the old version like grim death. I am an inch away from putting up a big banner just for Metamask users to switch to something, anything else. I have been dealing with these cache issues for almost two years. Not just on iPhone but also on Android before.

Sorry for the rant. I know some things are hard to fix. Just totally frustrating at this point.

**Comment by witwit** [comment]
> Sorry for the rant. I know some things are hard to fix. Just totally frustrating at this point.

How difficult can it be to put a "Clear Cache" button on the UI - something browsers have had for decades already? Humans do have the necessary technology.

**Comment by ivanferrera** [comment]
This is by design. The proper way to clear the cache is to uninstall the app and then reinstall it. This is why there are 1,461,501,637,330,902,918,203,684,832,716,283,019,655,932,542,976 possible addresses. If for some strange reason you don’t want to uninstall and reinstall the app, you can also try buying a new mobile phone and phone plan, and downloading the app there. Hope this helps.

**Comment by gantunesr** [comment]
Thanks everyone for your patience, this issue is still in our backlog and we don't have the capacity to pick it up yet.

I also want to apologize for my previous incorrect [comment](https://github.com/MetaMask/metamask-mobile/issues/4190#issuecomment-1237582007), the solved issue was about cookies and not the cache.

**Comment by romansemko** [comment]
> This is by design. The proper way to clear the cache is to uninstall the app and then reinstall it. This is why there are 1,461,501,637,330,902,918,203,684,832,716,283,019,655,932,542,976 possible addresses. If for some strange reason you don’t want to uninstall and reinstall the app, you can also try buying a new mobile phone and phone plan, and downloading the app there. Hope this helps.

Are you serious or is this some kind of joke?

**Comment by gantunesr** [comment]
@romansemko @siloitgroup disregard that comment, that individual is not part of our team.

**Comment by emergenceart** [comment]
Still broken 3 years and 8 months later?!
