### ISSUE TITLE
As a new user I should not be able to enable Remember me (hide remember me)

### ISSUE THREAD

**Issue by owencraston** [MetaMask/metamask-mobile#4194]
### **Description**
A new install of the app should not be able to enable remember me.
- In order to help the the total deprecation of this feature, we want to stop new users from activating  this feature as it will just make the deprecation harder. 

### **Technical Details**
- New installs should not be able to enable Remember me
- This essentially means we are going to remove the front end that hooks up this feature but the "backend" will still exist
- We don't want to lock out users who have enabled this feature already so this feature must only effect people setting up a wallet
- Since @sethkfman has made many important changes to the [authentication flow](https://github.com/MetaMask/metamask-mobile/pull/3755) we must work off of what he has done in that PR

### **Acceptance Criteria**
Scenario 1:
- GIVEN A new user installs MM mobile
- WHEN The user goes to setup their wallet 
- THEN they will not see the remember me option!
- AND the wallet creation works as normal

Scenario 2:
- GIVEN An existing user who was using remember me updates the app
- WHEN The user opens the app
- THEN they should still be logged in

Scenario 3:
- GIVEN An existing user who was using remember me updates the app
- WHEN The the vault recovery fails and the user gets logged out
- THEN remember me is no longer an option for the user 
- AND they will need to use their SRP to recover the wallet

### **References**
-  Slack Thread: https://consensys.slack.com/archives/CBW7S9FSN/p1651026595955719
-  Figma:

**Comment by plasmacorral** [comment]
merged in PR4305
