### ISSUE TITLE
deep linking multiple times on different custom networks yields a “ooops something went wrong” error

### ISSUE THREAD

**Issue by cortisiko** [MetaMask/metamask-mobile#4220]
When I attempt to deep link multiple times on different custom networks i run into an “ooops something went wrong” error

To reproduce:
add polygon to your list of networks and make it your default network

next add BSC to your list of networks but don’t set it as your default network

now tap on https://metamask.app.link/send/0x0000000000000000000000000000000000001010@137/transfer?address=0xC5b2b5ae370876c0122910F92a13bef85A133E56&uint256=3e18
notice the deep link works correctly. 

next tap on 
https://metamask.app.link/send/0x3EE2200Efb3400fAbB9AacF31297cBdD1d435D47@56/transfer?address=0xC5b2b5ae370876c0122910F92a13bef85A133E56

the network switches correctly but notice the [error](http://recordit.co/asvfTPtxVZ)

**Comment by gantunesr** [comment]
Add a more actionable error message (Change the `Oops` message)
