### ISSUE TITLE
app/core/InpageBridgeWeb3.js: No such file or directory

### ISSUE THREAD

**Issue by thinhcnb297** [MetaMask/metamask-mobile#4232]
**Describe the bug**
InpageBridgeWeb3.js: No such file or directory
**Screenshots**

**To Reproduce**
_Steps to reproduce the behavior_
1. git clone ...
2. cd metamask-mobile
3. yarn setup # not the usual install command, this will run a lengthy postinstall flow
4. cd ios && pod install && cd .. # install pods for iOS
5.  cp .ios.env.example .ios.env && \
  cp .android.env.example .android.env && \
  cp .js.env.example .js.env

**Expected behavior**
Can't run project

**Smartphone (please complete the following information):**
 - Device:IP 13
 - OS: 15.2
 - App Version [e.g. 1.0.0] - find version number in app from Settings > About MetaMask

-------------------------------------------------------------

**Severity**

- How fix this problem ??. Thaks

**Comment by tommasini** [comment]
Thank you so much for the report and for trying to contribute.
Did you follow all the steps in the readme file?
You set up and generated your Infura key to the .js.env file?

I will remove the bug label since I am not being able to reproduce it
Please answer on this issue if you succeeded or if you have any other problem on your set up

**Comment by tommasini** [comment]
@thinhcnb297 Due to the inactivity of this issue I will close it, feel free to open a new one if you find any problem that you would like to discuss with us

**Comment by owencraston** [comment]
This randomly fails for me sometimes and I fix it with `cp node_modules/@metamask/mobile-provider/dist/index.js app/core/InpageBridgeWeb3.js`. It's part of our [build steps](https://github.com/MetaMask/metamask-mobile/blob/main/scripts/build.sh#L111).

**Comment by skys215** [comment]
> This randomly fails for me sometimes and I fix it with `cp node_modules/@metamask/mobile-provider/dist/index.js app/core/InpageBridgeWeb3.js`. It's part of our [build steps](https://github.com/MetaMask/metamask-mobile/blob/main/scripts/build.sh#L111).

Should it be mentioned on readme.md? Or integrate this step in the `yarn setup` process(or in other command)?

**Comment by Cal-L** [comment]
Update: The `InpageBridgeWeb3.js` file needs to be in android's asset dir. You may also need to run this command `cp -rf app/core/InpageBridgeWeb3.js android/app/src/main/assets/.`
