### ISSUE TITLE
Password manager proposal

### ISSUE THREAD

**Issue by icedmoca** [MetaMask/metamask-mobile#4253]
I know this may sound out there, but can we rebrand "Metamask blockchain etc.." to just Metamask.
Then make it a password manager for literally everything. iOS app and android app, and browser extensions.

Then I can log into any site that supports logging in with Metamask, even unlock my front door. I mostly want this done because I'm making a react app that will feature logging in with Metamask.

**Comment by anon238** [comment]
Password manager in a crypto wallet app, please no. You can use the in-app browser to log in to dapps and for opening the door there are lots of applications for it and even iOS has the Home app specifically for that. Let them first fix the slowness and support for Ledger hardware wallet.

**Comment by icedmoca** [comment]
> 

Fine ill make my own company lmao
