### ISSUE TITLE
[Bug]: open sea polygon error

### ISSUE THREAD

**Issue by yoon11201** [MetaMask/metamask-mobile#4256]
### Describe the bug

I'm trying to sell polygon-related nft, but it says there is no metric, so I can't sell nft.

### Steps to reproduce

1.
![image](https://user-images.githubusercontent.com/105095309/167238554-53173c72-cc6a-4edf-b529-0a8e5e27dfcd.png

### Version

v5.0.1(877)

### Browser

Chrome

### Operating system

Windows

**Comment by tommasini** [comment]
Hello @yoon11201, thanks for reporting!
I'm not being able to reproduce it, could you please share more information and a print screen of the error?
Thank you

**Comment by tommasini** [comment]
@yoon11201 I will close this issue due to inactivity, please if you have this issue again or any other, please open a new one.
