### ISSUE TITLE
Favorite sites in browser not visible

### ISSUE THREAD

**Issue by jakehaugen** [MetaMask/metamask-mobile#4273]
**Describe the bug**
Favorites not visible on browser home page. I tap "Add to Favorites" but it is not visible on the homepage. However, the option to "Add to Favorites" disappears which leads me to believe that my favorites have been saved, they are just not appearing. 

**Screenshots**
https://user-images.githubusercontent.com/11967476/167709292-f4a4d263-eb98-418d-af4a-5e6b91a17dfd.MP4

**To Reproduce**
_Steps to reproduce the behavior_
1. Go to browser
2. Go to a site
3. Tap the "..." menu
4. Tap "Add to Favorites"

**Expected behavior**
After adding to favorites, a link to the site should show up under your "Favorites" tab.

**Smartphone (please complete the following information):**
 - Device: iPhone 12 Pro
 - OS: iOS 15.4.1
 - App Version: v5.0.1 (877)

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by mobularay** [comment]
@Fatxx @sethkfman we've seen this issue before. This is a known issue. Can we link this issue together with the ones we've reviewed in the past?

**Comment by Fatxx** [comment]
Hey!

The fix for this is going to be out on version 5.2, related ticket is https://github.com/MetaMask/metamask-mobile/issues/3331
