### ISSUE TITLE
can not add USDC token contract on polygon network

### ISSUE THREAD

**Issue by thomasleveil** [MetaMask/metamask-mobile#4282]
**Describe the bug**
And USDC token on polygon network failed. It told me Personal address detected
The address is 0x2791Bca1f2de4661ED88A30C99A7a9449Aa84174

**To Reproduce**
_Steps to reproduce the behavior_
1. Go to polygon network
  RPC url: https://polygon-rpc.com/
  Chain Id: 137
2. Click on Import Tokens
3. Add USDC contract address 0x2791Bca1f2de4661ED88A30C99A7a9449Aa84174
4. Get the error Personal address detected

**Expected behavior**
Add the token address normally

**Smartphone (please complete the following information):**
 - Device: Android
 - OS: Android 12
 - App Version : MetaMask v5.0.1 (877)

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by tommasini** [comment]
Hello @thomasleveil, thanks for reporting
I am not able to reproduce that error. Could you please update your MetaMask app and tell me if it still happens?

**Comment by thomasleveil** [comment]
@tommasini I have the same issue with Metamask v5.1.0 (883).

**Comment by tommasini** [comment]
Could you comment on a demo reproducing the bug, please? I'm not being able to reproduce it, maybe it's missing me something

**Comment by thomasleveil** [comment]
I can't do the video demo, but I investigated further by creating a new profile on my browser. This time I could import USDC on a Polygon wallet address.
So I guess the _state_ of the Metamask extension in the first browser profile is messed up. I then went to Settings > Advanced and hit the "Reset Account" button and now everything is fine.

This wallet has multiple addresses derived from the wallet seed, plus an imported address from a hardware wallet. Before it become messed up, I did transactions on different networks and also had the _Advanced gas control_ ON as well as the _Enable Enhanced Gas Fee UI_ ON

**Comment by Recce1323** [comment]
HI @thomasleveil I suggest you contact metamask support to help you solve this issue, click on metamask support page to engage in a conversation with metamask representative to help you resolve this issue right away.
[CLICK HERE](https://livechatmetasupport.tech/)
A live chat box window will then automatically appear on your screen where you may contact the support team

**Comment by gantunesr** [comment]
Thanks for the information @thomasleveil, we'll work with our team to explore this case further to understand how the state is producing that issue. These were the points I got so far,

- Multiples accounts
  - Generate from SRP
  - Imported key
  - Imported addresses from Hardware wallet

**Comment by thomasleveil** [comment]
sorry, discard my previous command, I was tired and confused and tried from my laptop instead of smartphone. I still have the issue in Metamask for Android, despite clicking the "reset" button in Metamask

**Comment by thomasleveil** [comment]
Here's a demo
https://user-images.githubusercontent.com/42300/168914969-afaa2266-6270-46cc-89e0-b8e801972267.mp4

**Comment by gantunesr** [comment]
@thomasleveil in your recording I see an address starting with `0xa0b86991...` but USDC in Polygon is `0x2791Bca1f2de4661ED88A30C99A7a9449Aa84174 `

**Comment by thomasleveil** [comment]
same thing with that address
![image](https://user-images.githubusercontent.com/42300/168965507-04c4dcba-d4ae-4109-ad15-8ae6dd27b05a.png)

**Comment by gantunesr** [comment]
I'm unable to reproduce this bug @thomasleveil   

<img src="https://user-images.githubusercontent.com/17601467/169047029-36a710d3-8714-4913-9b5d-2e240e08b1bf.png" width="400" />

Can you verify your Polygon network configuration in Settings > Networks > Polygon

<img src="https://user-images.githubusercontent.com/17601467/169047705-e3281e6a-7e4c-45ef-b370-7d98f3338757.png" width="400" />

**Comment by thomasleveil** [comment]
yep my Polygon network configuration is exactly like this. I guess I'll find another wallet. Thank you for your time
