### ISSUE TITLE
Alert banner message on transaction confirmation view only shows ETH irrespective of the network 

### ISSUE THREAD

**Issue by cortisiko** [MetaMask/metamask-mobile#4294]
While on a custom network (BSC in this case) I attempted to edit the gas price above what I have in my wallet. Upon doing so I notice a red alert banner with the text "You need 0.00002 more ETH to complete this transaction." I should not see ETH on a custom network. I should see that native token. 

To reproduce:
launch the app with BSC or any other custom network set as your default network
ensure you have a little bit of funds on your account. I would say a couple cents worth of the network native currency 
go through the send flow. Send the max amount
notice on the transaction confirmation view the alert banner has "ETH" instead of the native currency of your network. 

Places where this exists:
[The edit gas modal](https://www.screencast.com/t/gzLjG2Ja)
The [transaction confirmation view](https://www.screencast.com/t/5K2FdRKAza)

**Comment by gantunesr** [comment]
The token ticker is wrong. It should not be hardcoded

**Comment by Fatxx** [comment]
@tommasini check if this is already fix

**Comment by tommasini** [comment]
This is fixed on release 5.4. I will close this issue 🚀
