### ISSUE TITLE
Unable to re-add account nickname after making it an empty string

### ISSUE THREAD

**Issue by cortisiko** [MetaMask/metamask-mobile#4308]
**Describe the bug**
 If i were to remove my account nick name i.e. leave it blank, I am unable to add a new nickname to my account. 

see [recording](http://recordit.co/blCne5klOv )

**To Reproduce**
- launch the app
- create/import your wallet
- while on the wallet view
- tap and hold the account nickname to highlight it
- remove the default nickname
- attempt to add a new account nick name. Notice you are unable to do so

**Expected behavior**
You should be able to update an account nick name.

**Comment by gantunesr** [comment]
Have in consideration the accounts that already have an empty string as name

**Comment by cortisiko** [comment]
was fixed in https://github.com/MetaMask/metamask-mobile/pull/4684
