### ISSUE TITLE
[5.2] Fix overflowed button when revealing SRP

### ISSUE THREAD

**Issue by Cal-L** [MetaMask/metamask-mobile#4311]
### **Description**

We need to make the body content of this screen scrollable so that the reveal button appears inside of the center overlay
![image.png](https://images.zenhubusercontent.com/5772d2f9bf93871ccd9d4f97/def90a9b-8c86-4da2-8c07-dad69f3f7774)

### **Technical Details**

-  We need to make the body content of this screen scrollable so that the reveal button appears inside of the center overlay

### **Acceptance Criteria**

-  Body content of page should be scrollable
- Overlay should fit content including reveal button

### **References**

-   Slack thread - https://consensys.slack.com/archives/G8RSKCNCD/p1652287901392319

**Comment by cortisiko** [comment]
closing since this issue was fixed in https://github.com/MetaMask/metamask-mobile/pull/4315
