### ISSUE TITLE
[5.1.1] undefined is not an object (evaluating 'n.split')

### ISSUE THREAD

**Issue by cortisiko** [MetaMask/metamask-mobile#4313]
When you scan a receiver QR code then proceed to send funds you get the undefined is not an object (evaluating 'n.split') error. 

See [here](http://recordit.co/3xAzH1AqZx) & [here](http://recordit.co/mANUWd6a2s)

To reproduce:
on device A scan the receive QR code on device B
proceed to send funds
notice the error.

**Comment by plingampally** [comment]
The QR code generated includes `@1` at the end of the string. This is causing the QR code to be non-readable by any third party wallet.
