### ISSUE TITLE
Failing MixPanel API call breaks wallet connection / browser opening (due to ad-blocking DNS)

### ISSUE THREAD

**Issue by pauldowman** [MetaMask/metamask-mobile#4338]
**Describe the bug**
I use [NextDNS](https://nextdns.io/) and the embedded browser doesn't work when it's enabled. (MetaMask opens but then does nothing. The embedded browser doesn't open as expected.)

Looking at the logs I can see that a call to MixPanel is blocked. When I switch my DNS to 1.1.1.1 the problem goes away.

I assume this would also occur due to the MixPanel API call failing for any reason (e.g. their back-end being down).

**To Reproduce**
_Steps to reproduce the behavior_
1. Use an app that uses a wallet connection flow via deep linking to the metamask browser. 
3. Trigger the wallet connection flow
4. See that MetaMask opens
5. See that it stays on the main screen rather than opening the browser

**Expected behavior**
The browser should open.

**Smartphone (please complete the following information):**
 - iPhone 13 Pro
 - iOS 15.4.1
 - App Version 5.0.1 (877)

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by gantunesr** [comment]
Hey @pauldowman, unfortunately there's not much we can do on that side. You should ask NextDNS if there's any configuration that may potentially solve this issue. But first you should find out which domain is blocked.

**Comment by pauldowman** [comment]
It's a call to MixPanel that is blocked. And the fix would be to gracefully handle that call not returning, it's just analytics right? It should not break the app.

**Comment by acmartinsalmeida** [comment]
i have the same problem and i share pauldowman opinion. Analytics should not break the app
