### ISSUE TITLE
Insufficient funds error does not update on account change

### ISSUE THREAD

**Issue by plasmacorral** [MetaMask/metamask-mobile#4346]
**Describe the bug**
If I tap a deeplink payment request with an account that has 0 balance, I get the insufficient funds alert.  When I switch to a different account that has a balance sufficient to cover the send and gas, the error message does not go away so I am unable to proceed with the transaction.

**Screenshots**
https://recordit.co/FaOQC7RLHq

**To Reproduce**
_Steps to reproduce the behavior_
1. Select an account with zero balance in wallet view
2. Scan a deeplink payment request without a network specified (or specified for the network where you have 0 balance)
3. From the send view, change to another account that has a sufficient balance
4. Note that the error does not go away and the confirm button is disabled.

**Expected behavior**
After switching accounts to one with a sufficient balance, the error should go away and the confirm button should be able to be tapped.

**Smartphone (please complete the following information):**
 - Device: Sumsung A51f
 - OS: Android 11
 - App Version v5.1.0 build 883

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by plasmacorral** [comment]
Also can confirm that I can reproduce this in PR 4178.

**Comment by gantunesr** [comment]
Reference: https://consensys.slack.com/archives/G8RSKCNCD/p1653076444562609
