### ISSUE TITLE
Amount view in send flow drops leading "0."

### ISSUE THREAD

**Issue by plasmacorral** [MetaMask/metamask-mobile#4348]
**Describe the bug**
In the send flow regardless of whether its a payment deep link or tapping send from wallet view, the leading "0." is dropped the very first time its attempted.  Subseqent re-entry does not behave the same but this will reappear if the app is closed and re-opened.  Have observed this in build 883 on both android 12 and iOS 15.4.1.

**Screenshots**
Android 12 on pixel 3a build 883:
https://recordit.co/mBSibqfQMa

iOs 15.4.1 on iphone 13 mini (@ 10s and @1m17 after app was killed):
https://recordit.co/J95RZpecAv

**To Reproduce**
_Steps to reproduce the behavior_
1. Get into send by either QR, deeplink, or tapping send from wallet view
2. Select recipient address and tap next
3. On amount view tap "0" and then "." and note that both characters are cleared

**Expected behavior**

- Tapping "0.xxxxx" should not require tapping "." twice.
- Should be able to enter in "0.xxx..." or ".xxx..." patterns without having to re-enter any characters

**Smartphone (please complete the following information):**
 - Device:Pixel 3a and iPhone 13 mini
 - OS: Android 12 and iOS 15.4.1
 - App Version v5.1.0 Build 883 

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by tommasini** [comment]
@plasmacorral I'm not being able to reproduce this on app version: 5.2.0, Android 12

https://user-images.githubusercontent.com/46944231/169911034-371a9072-19cb-404f-a3d9-674ceb01c4a9.mp4

**Comment by plasmacorral** [comment]
Unable to reproduce on Android 12, 11 or iOS 15.5.  Will close.
