### ISSUE TITLE
JazzIcons constantly changing

### ISSUE THREAD

**Issue by tommasini** [MetaMask/metamask-mobile#4353]
**Describe the bug**
In the send flow, the send to screen, the jazz icon is always changing.

**Screenshots**

**To Reproduce**
_Steps to reproduce the behavior_
1. Go to send
2. Search for ens name
3. Go to amount screen
4. Press back
5. The icon is not the same

**Expected behaviour**
The icon must be always the same

 - App Version 5.1.0

**Comment by cortisiko** [comment]
This was merged. Closing ticket.
