### ISSUE TITLE
Android Doesn't update chain status.

### ISSUE THREAD

**Issue by malcolm-dane** [MetaMask/metamask-mobile#4374]
**Describe the bug**
Internal JSON Error on sending transactions out from an online rpc end point. Network state doesn't correct itself in the json when a network becomes available again after being unavailable. This problem persisted despite numerous attempts to fix, I exported state logs then reset cache. 
**Screenshots**
_If applicable, add screenshots or links to help explain your problem_

**To Reproduce**
_Steps to reproduce the behavior_
1. Go to ""add a private test chain, and add it. Then take it down, try and send coin you get the network unavailable. Restart chain, and the message persists despite being able to receive incoming transactions.

**Expected behavior**
The internal state updates correctly when a network returns to availability. 

**Smartphone (please complete the following information):**
 - Device: [Samsung GAlaxy something Android 11]
 - App Version [5.1.0] - find version number in app from Settings > About MetaMask

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
Moderate. This issue persisted after updating, network changes, permission resets and more

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users? Not sure.
- Is this tech debt
- Could be from changing compile target's and not updating Android's storage.
No. My guess is it's android's storage fault.

**Comment by Fatxx** [comment]
Can you provide us more details on this subject, are you expecting MM to detect that a network is available again? Thank you.
