### ISSUE TITLE
Swipe to swap/swipe to confirm triggers navigation "go back to previous screen" behaviour

### ISSUE THREAD

**Issue by mobularay** [MetaMask/metamask-mobile#4377]
**Describe the bug**
"Swipe to confirm" function is interrupted by "swipe to go back one screen" navigation function. Reported by the head of Coinbase Cloud.
Slack thread: https://consensys.slack.com/archives/C0354T27M5M/p1652113374435429

**Screenshots**
![swipe to go back](https://user-images.githubusercontent.com/79168661/170066163-d85bef72-5751-4623-b181-feb981d2fd1c.png)

**To Reproduce**
1. Go to confirm swap UI
2. Swipe the button "Swipe to swap"
3. The swipe movement on the UI screen triggers the "go back previous screen" navigation function

**Expected behavior**
Swiping the "Swipe to swap" button actually does its job of confirming the user's intent to swap!

**Smartphone (please complete the following information):**
 - Device: tbd
 - OS: tbd
 - App Version [e.g. 1.0.0] - find version number in app from Settings > About MetaMask

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by Fatxx** [comment]
@jakehaugen working on a new design solution for the button

**Comment by jakehaugen** [comment]
Design file: https://www.figma.com/file/983rUOWGgfg2cPG01DTRG5/Swaps?node-id=1239%3A4517

@Cal-L worked on a prototype of the animation for web but it will need to be recreated for mobile. Exact animation details are in the Figma but may need tweaks once we see it live in code. Happy to review once there is a first draft and we can fine tune as needed.

https://user-images.githubusercontent.com/11967476/178364195-630fe6db-3765-4e2b-a857-43a6cf50f74d.mov

**Comment by jakehaugen** [comment]
We're also using the "hold" interaction to reveal your SRP and Private Key. We should replace those buttons with this new one once it's ready.

**Comment by bksingapore90** [comment]
the same issue, very annoyed

**Comment by szuwest** [comment]
met the same problem
