### ISSUE TITLE
Address validation warning appears briefly for legit address that is not stored in contacts

### ISSUE THREAD

**Issue by plasmacorral** [MetaMask/metamask-mobile#4393]
**Describe the bug**
Address validation warning appears briefly for legit address that is not stored in contacts

This was observed on Samsung A515f running Android 11 with build 911 v5.2 RC2 and confirmed to be present in production.

**Screenshots**

https://recordit.co/tUU5TCC91Y

**To Reproduce**

1. Be on testnet 
2. I wanted to make a new contact so I copied 0x0c54FcCd2e384b4BB6f2E405Bf5Cbc15a017AaFb from my etherscan history on rinkeby
3. Go into send flow from wallet view
4. Paste in the address
5. tap CTA to add to address book
6. put something in the for the name (I used 'idk') and tap save
7. tap next
8. On the amount view, tap cancel
9. On the confirm view, tap cancel
10. From wallet view change to Eth Mainnet
11.  Go into send flow from wallet view
12. Not that the contact previously saved on testnet is shown under 'Recents' without an ENS name initially, but then resolves as `metamask.eth`
13. Tap to select that address that was previously saved on testnet as 'idk' that shows on mainnet with the ENS name `metamask.eth` and note that the address warning flashes briefly

**Expected behavior**
The alert should not be presented when a legit address is entered, and instead should only be shown if the address fails validation.

**Smartphone (please complete the following information):**
 - Device: Samsung A515f
 - OS: Android 11
 - App Version v5.1.0 build 883 and v5.2 RC2 build 911

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user? Undermines user confidence, but does not impede usability
- Is this visible to all users? Any user that enters a send address that is not previously stored as a contact

**Comment by gantunesr** [comment]
This should be fixed in v5.2.0. @tommasini points out that it requires a performance improvement
