### ISSUE TITLE
Nag alert for "Protect your wallet" has no chill

### ISSUE THREAD

**Issue by plasmacorral** [MetaMask/metamask-mobile#4400]
### **Description**

When a user is in the process of completing a backup, could we stop showing this nag alert in yellow, please?  It seems to obstruct some of the CTAs that are needed to complete a backup.

If the user taps to "protect wallet" from the alert they are brought to a backup page that is not scroll able and has the button obstructed.

This was initially observed on a Samsung A515f running Android 11, testing RC v5.2 build 904.  This was confirmed in production build 906 v5.1.1

### **Acceptance Criteria**

-  Stop pestering users when they are trying to complete the thing you are pestering them about

Scenario: Chill on the nag
- GIVEN a user has not completed a backup of their SRP
- WHEN a user goes through settings>privacy>backup now, or when tapping the "protect wallet" CTA within the alert
- THEN lets stop presenting the "Protect your wallet" warning while the user is in the process of backing up

### **References**

-   https://recordit.co/XqX3oLJoq0

**Comment by Fatxx** [comment]
Possible fix: Hide the alert when users clicks "Backup now" and don't forget to show it back again if users wallet was kept not backed up.

**Comment by olenapankina** [comment]
I would like to point out that this alert is still on the screen when user taps 'Protect wallet' button **directly on the alert**

https://user-images.githubusercontent.com/116747263/208048357-86325b4e-c7a4-4b04-b1b5-b61cccdda106.mp4

**Comment by plasmacorral** [comment]
Fixed in https://github.com/MetaMask/metamask-mobile/pull/7534
