### ISSUE TITLE
Chainlist logo under developer tools

### ISSUE THREAD

**Issue by plasmacorral** [MetaMask/metamask-mobile#4401]
### **Description**

I know there was an ownership change recently, but can we address this missing logo?  You can see this on an Android device through the Browser after tapping on Developer tools.

### **Acceptance Criteria**

-   Include a logo for Chainlist.org

Scenario: Chainlist logo
- GIVEN a user is in the browser looking at explore sites tab
- WHEN a user taps on Developer Tools
- THEN a logo should appear for Chainlist

### **References**

![Screen Shot 2022-05-25 at 1 02 43 PM](https://user-images.githubusercontent.com/32695229/170320408-3491e7ab-0d77-4677-a3ef-0aa0485f05cf.png)

**Comment by gantunesr** [comment]
Most likely a website bug
