### ISSUE TITLE
Allow this site to add a network - informative link lands at zendesk page

### ISSUE THREAD

**Issue by plasmacorral** [MetaMask/metamask-mobile#4402]
### **Description**

Within the 'Allow this site to add a network' modal, there is blue text to "Learn about scams and network security risks".  When I tap this link I am prompted to select a browser and then taken to https://metamask.zendesk.com/hc/en-us

Should this link take the user to a specific article, or is our intent to plop them down into the main page of zendesk?

This was observed on Samsung A515f running Android 11 testing RC 5.2 build 904 and then confirmed on production builld 906 v5.1.1

https://recordit.co/7IwJ1bON9Q

![Screen Shot 2022-05-25 at 1 13 34 PM](https://user-images.githubusercontent.com/32695229/170323890-c0e7b21f-d908-4dd0-88de-aa18f82915e4.png)

**Comment by Fatxx** [comment]
Note: Check if the link is being opened correctly since the URL seems to be correct in code.
