### ISSUE TITLE
What "non-Metamask" means in README?

### ISSUE THREAD

**Issue by reedom** [MetaMask/metamask-mobile#4405]
### **Description**

On building a development build locally, I wondered whether I should follow the "non-Metamask" steps.

### **Technical Details**

-   document

### **Acceptance Criteria**

-   Newbies can decide which steps to take.

### **References**

-   README.md

**Comment by AkshayBhimani** [comment]
Steps written under **Non-MetaMask Only** is for other developers like us who need not have keys (eg. etherscan, opensea, etc.) for testing purpose. 

On the other hand **Metamask Only** is for MetaMask Mobile developers who will have keys and will put in empty fields defined under .env files
