### ISSUE TITLE
Add Tower token crashes the app

### ISSUE THREAD

**Issue by tommasini** [MetaMask/metamask-mobile#4423]
**Describe the bug**
When we visit the crazydefenseheroes.com, and add the Tower token to our wallet, the app crashes.

**Screenshots**
![Tower token error](https://user-images.githubusercontent.com/46944231/171050136-5476c003-c0ad-4aba-8b57-24b13e5d3808.png)

**To Reproduce**
_Steps to reproduce the behavior_
1. Browse to "crazydefenseheroes.com"
2. Change network to Polygon Mainnet
3. Press on the DApp menu
4. Press Swap Tower menu option
5. Press the phrase that says "Display Tower token in Metamask"
6. See error

**Expected behavior**
The token should be added, be visible on the wallet view and not crash the app.

**Smartphone (please complete the following information):**
 - Device: Simulator iPhone 11 pro
 - App Version 5.1.1

**Comment by Fatxx** [comment]
Can we try if it crashes the app in production build?
