### ISSUE TITLE
Android deeplink send/approval with network change while app is closed

### ISSUE THREAD

**Issue by plasmacorral** [MetaMask/metamask-mobile#4427]
### **Description**

I noticed in regression testing for 5.2 that send and approval deeplinks do not work on Android if the app is closed and a network change is required.  This was observed in v5.2 RC builds 904 and 913, then was confirmed in production with v5.1.1 build 906.  

Approval link tested: https://metamask.app.link/approve/0x1d7a9cd8c67e3c74a84bb76cbc1b606e2e460db5@3/approve?address=0x1FDb169Ef12954F20A15852980e1F0C122BfC1D6&uint256=3e18

https://recordit.co/5wDmsewJIq
9s tapped link with Mainnet selected and mobile client in background =pass
20s changed back to Mainnet and closed app
25s tapped link with Mainnet selected and mobile client closed = fail (network changes but approval modal does not appear)
54s closed app with Ropsten selected
1m tapped link with Ropsten selected and mobile client closed = pass
1m 16s closed app with Mainnet selected
1m 20s tapped link with Mainnet selected and mobile client closed = fail again
1m 39s changed back to Mainnet
1m 43s tapped link with Mainnet selected and mobile client in background =pass again

Also able to produce similar results with this link:
https://metamask.app.link/send/0x3dD3DfaAdA4d6765Ae19b8964E2BAC0139eeCb40@4/approve?address=0x178e3e6c9f547A00E33150F7104427ea02cfc747&uint256=5e8

https://recordit.co/7Htl5idEWo

### **Acceptance Criteria**

-   Approval/send related deeplinks should bring the user to the send/approve modal even if tapped while MetaMask mobile is closed, or if a network change is required, or both.

Scenario: Payment link with network change while app closed
- GIVEN the user closed the app with a different network selected than what the deeplink specifies
- WHEN a user has MetaMask Mobile closed
- AND a user taps on an approval or send related deeplink
- THEN MetaMask mobile should open
- AND the network specified in the link should be selected
- AND the approve or send modal is presented for the user to review and confirm

**Comment by tommasini** [comment]
Closing this issue because it's already reported [here](https://github.com/MetaMask/metamask-mobile/issues/3880)
