### ISSUE TITLE
WalletConnect Reject action callback issue : ERC20 contracts

### ISSUE THREAD

**Issue by nareshkatta99** [MetaMask/metamask-mobile#4431]
**Describe the bug**
When we use _WalletConnect_ and  initiate a ERC20 `approve` operation and we 'Reject' the transaction, it is _not reporting_ back  about _rejection_ to WalletConnect

The same 'Reject' operation on any other contracts is working properly.

**To Reproduce**
_Steps to reproduce the behavior_
1. Go to [_enzyme.finance_](https://app.enzyme.finance), select _Polygon Mainnet_ and use WalletConnect to connect.
2. Scan the QR Code with Metamask mobile app
3. Scroll down to 'Popular vaults' and select any one of them (ex [Insula™ Phaeacia](https://app.enzyme.finance/vault/0x6c4a43d136d695a80bab48732df1be2571429b0c)).
4. Click on 'Deposit', then select 'Dai' in the popup.
5. Enter some number less than your Dai Balance and then click on 'Approve'.
6. In Metamask Android app, Click Reject.
7. Even after 5-10 mins, the WalletConnect will not detect that the User rejected the transaction.

**Expected behavior**
Just like for other contract operations, say _Create a Vault_ in this case, which does not involve ERC20 transaction, the Metamask mobile app must report the rejection to WalletConnect.

**Smartphone (please complete the following information):**
 - Device: RedMi Note 8 pro
 - OS: Android 11
 - App Version 5.1.1

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by nareshkatta99** [comment]
@tommasini any update on this?

**Comment by nareshkatta99** [comment]
@tommasini 
Please help us know when can we expect an update on this.

**Comment by gantunesr** [comment]
Hi @nareshkatta99, thank you for your patience! We don't have any relevant updates at the moment
