### ISSUE TITLE
Two tabs opened when using `dapp://`

### ISSUE THREAD

**Issue by SMLaursen** [MetaMask/metamask-mobile#4436]
**Describe the bug**
While investigating alternatives to `https://metamask.app.link/...` deeplinks, that doesn't rely on the user granting metamask.app.link permissions first, I've stumbled upon the following two sporadic (but very often) issues with `dapp://` and `metamask://` schemes :

- `dapp://` after first usage, very often two tabs are opened when following a `dapp://` link;
One with the actual link and one with the previous opened tab in focus.

- `metamask://` after first usage, very often the previous opened tab is reopened when following a `metamask://` link.

**Screenshots**
The `dapp://` issue is illustrated here https://www.youtube.com/shorts/2UnaFPKDfvU

**To Reproduce**
_Steps to reproduce the behavior_
1. In MMM close all tabs, clear privacy data, browser history and browser cookies
2. Outside MMM click `dapp://medium.com` link
3. Focus should shift to MMM showing medium.com ✅
4. Outside MMM click `dapp://cointelegraph.com` link
5. Focus shifts to a reopened medium.com page in MMM ❌
	- but it also opened a non-focused cointelegraph.com tab 

**Expected behavior**
Only the link followed opened and focused in MMM

**Smartphone (please complete the following information):**
 - Device: OnePlus 9
 - OS: Android 12
 - App Version : 5.1.1

**Comment by andreahaku** [comment]
Hi @SMLaursen , we are aware of the issue and I'm already working on a fix ;) Thanks for reporting.

**Comment by razvandragomirescu** [comment]
Any updates on this? This is still happening in the latest version and it's annoying as hell (and breaks the UX of our Android app interaction, when we call MetaMask a second time via dapp:// our actual tab is obscured by a new one with the same content as the last opened one).

**Comment by andreahaku** [comment]
> Any updates on this? This is still happening in the latest version and it's annoying as hell (and breaks the UX of our Android app interaction, when we call MetaMask a second time via dapp:// our actual tab is obscured by a new one with the same content as the last opened one).

we are having difficulties to replicate this. But in the meantime, you can use universal links structured like that: `https://metamask.app.link/dapp/{url}` that do exactly the same thing and also have the advantage to check if the app is installed. if now the user is taken to app store. Thanks.

**Comment by razvandragomirescu** [comment]
I can confirm that the replacing dapp:// with https://metamask.app.link/dapp/ solves the issue for our case (single tab opened instead of current + last). I will use this as a workaround for now. dapp:// deep links very reliably open 2 tabs for us, Android 12 (Jelly 2 phone). Not sure how they are different in the Metamask Mobile code.

**Comment by andreahaku** [comment]
> I can confirm that the replacing dapp:// with https://metamask.app.link/dapp/ solves the issue for our case (single tab opened instead of current + last). I will use this as a workaround for now. dapp:// deep links very reliably open 2 tabs for us, Android 12 (Jelly 2 phone). Not sure how they are different in the Metamask Mobile code.

Thanks a lot. We'll try to investigate more the issue in any case. Cheers
