### ISSUE TITLE
Payment links - when deep linking - do not work in Chrome Mobile android

### ISSUE THREAD

**Issue by cryptovale-eth** [MetaMask/metamask-mobile#4439]
When clicking on deep links (also those generated by [https://metamask.github.io/metamask-deeplinks](https://metamask.github.io/metamask-deeplinks)) they do not correctly pre-fill the payment screen in MetaMask mobile.

Additional info: the link does not seem to work for opening a DApp as well

The same link works fine if clicked in 
- Outlook Mobile
- Firefox Mobile (101.1.1)

**To Reproduce**
1. Open latest Chrome app on a mobile phone
2. Navigate to [https://metamask.github.io/metamask-deeplinks](https://metamask.github.io/metamask-deeplinks)
3. Generate a payment link
4. Click on the URL
5. Access MetaMask
6. MetaMask opens the main screen, but not the payment

**Expected behavior**
It is expected to open the pre-filled payment screen (as it works in other apps).

**Smartphone (please complete the following information):**
- MetaMask App Version: v5.1.1 (906)
- App Version: Chrome Mobile (102.0.5005.78)
- OS: Android 12
- Device: Pixel 6 Build/SP2A.220505.002

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by tommasini** [comment]
Hey @cryptovale-eth, thank you so much for reporting.

I was trying to replicate your issue and everything seems to be working as expected.
The network changed correctly, and the amount it's the same as we registered on the Deeplink.
Could you provide more steps for us to be able to reproduce the bug?
If it's a suggestion for improvement please tell us as well, for we put the correct label.

https://user-images.githubusercontent.com/46944231/171883659-9e242807-32de-4e98-9cd8-34e0a9d94fc2.mp4

**Comment by cryptovale-eth** [comment]
Hi @tommasini , thanks for answering this quick. I have shot a video as well.
You appear to have a slightly different UX, probably because of the underlying operating system? I'm on a Pixel 6.
Otherwise I've executed the same steps, even with the same settings.

Here is the video with Chrome:

https://user-images.githubusercontent.com/35154290/171902794-0808f8b0-23c0-4204-8609-e19612343707.mp4

And the working example (same settings) with Firefox:
https://user-images.githubusercontent.com/35154290/171902859-d3707944-1b96-4d44-8f0b-bf9369569b4d.mp4





Have a great rest of the day!

**Comment by cryptovale-eth** [comment]
addition: a friend just has tested it on an iPhone, Chrome + MetaMask, and it works

**Comment by cryptovale-eth** [comment]
Hi @tommasini, I got to test it today with another phone (a Samsung Galaxy) and it didn't work as well on Chrome - apparently there is something in the handling of intents with Chrome that does not seem to work (perhaps the params on the deeplink get modified)

I don't know if this might be correlated: https://stackoverflow.com/questions/72181719/android-deeplink-via-chrome-intent-broke-since-april-2022

**Comment by cryptovale-eth** [comment]
Sorry to write again - the following steps manually performed on the Android settings seem to solve the issue:

1. Go to android settings
2. Search for "Standard Apps"
3. Search for MetaMask
4. Add the handler to the verified links

Retry the steps described in this bug: MetaMask is correctly opened with the right data from the intent

I hope this provides an hint on what to change on the intent manifest
could the be the culprit? android:autoVerify="true"

**Comment by andreahaku** [comment]
> Sorry to write again - the following steps manually performed on the Android settings seem to solve the issue:
> 
> 1. Go to android settings
> 2. Search for "Standard Apps"
> 3. Search for MetaMask
> 4. Add the handler to the verified links
> 
> Retry the steps described in this bug: MetaMask is correctly opened with the right data from the intent
> 
> I hope this provides an hint on what to change on the intent manifest could the be the culprit? android:autoVerify="true"

Hi @cryptovale-eth thanks. As you can see in the [AndroidManifest.xml](https://github.com/MetaMask/metamask-mobile/blob/main/android/app/src/main/AndroidManifest.xml) this is already set to true.

The fix that you've found has also been suggested many times in the past.

Specifically:
_Open Android settings , search 'default' and select "Choose Default apps' > "Choose Default apps" > Opening Links > scroll down to MetaMask and tap it > Supported Web addresses > check if links are selected or "verified/trusted" by default (most importantly metamask.app.link). If they are not, then check them/it._

I'm happy that you solved.

**Comment by cryptovale-eth** [comment]
Ciao @andreahaku ,
the suggestion is a huge workaround and not really a solution. 
It means telling all the users to manually add the verified link in their own Android settings, if they want to use MetaMask. 
This adds big friction.

I'm not in detail into Android intents, but maybe removing this android:autoVerify="true" could correct the bug. I was comparing the manifest with the one of TrustWallet, which works in Chrome mobile, and they don't use the autoVerify.

In my opinion, this is not solved...

Thanks
Vale
