### ISSUE TITLE
Error ‘Oops Something Went Wrong‘

### ISSUE THREAD

**Issue by xtiaan3** [MetaMask/metamask-mobile#4446]
We are building a web3 app with Wallet Connect and we’re getting an “Oops Something Went Wrong” message during minting on Rinkeby, but the transaction is still successful. Only happens on iPhone. Any help / insight would be appreciated. 

packages:
  dependencies:
    "@walletconnect/web3-provider": "^1.7.7",
    "web3": "^1.7.3",
    "web3modal": "^1.9.7"

  devDependencies:
    "@babel/core": "^7.17.9",
    "@babel/plugin-transform-runtime": "^7.17.0",
    "@babel/preset-env": "^7.16.11",
    "babel-loader": "^8.2.5",
    "webpack": "^4.46.0",
    "webpack-cli": "^4.9.2",
  

method implementation

contract: is instance of the contract created with web3.js
volume: amount of tokens to mint

```
contract.methods
        .publicMint(volume)
        .send({
          from: account,
          value: price,
        })
        .once("transactionHash", (hash) => {
          console.log({ hash });
        })
        .once("receipt", async (receipt) => {
          console.log({ receipt });
        })
        .on("error", (err) => {
          errorHandler(err);
        });
```
![2D4CCDF0-8FC6-4066-9EB8-576DB2628EF8](https://user-images.githubusercontent.com/16021630/171958295-733da758-8643-4976-a7b2-c14a34ff68e8.jpeg)

**Comment by WenLanBan** [comment]
@Fatxx this may be related to #3927 ?

**Comment by tommasini** [comment]
Thank you so much for reporting @xtiaan3 
Thank you so much for pointing out the relation between both issues!
It seems to be related, but to be sure, @xtiaan3 could you please tell us if you put the MetaMask mobile app in the background when you confirm the transaction?

We are working on one [solution](https://github.com/MetaMask/metamask-mobile/pull/4060) already for the #3927 🍀

**Comment by xtiaan3** [comment]
Hi @tommasini let me check with the dev and get back to you here. In the meantime you’re welcome to test the process here. Would appreciate any insights - https://drunkrobots.net/mint

**Comment by xtiaan3** [comment]
Hi @tommasini - Im not 100% sure what you mean by "put the MetaMask mobile app in the background when you confirm the transaction." We start the transaction on our website which launches the native MetaMask app where you confirm the transaction. From there you are returned to the website where the toast menu pops up with the error, however the transaction still goes through. Here is a video of the process... Any help here would be appreciated.

https://user-images.githubusercontent.com/16021630/172709564-2705b17e-86eb-448e-b97b-f260eca1c7f1.mov

**Comment by tommasini** [comment]
@xtiaan3 Thank you so much for giving more details!
There is one solution already to this problem we will try to release it as soon as we can!

**Comment by xtiaan3** [comment]
@tommasini - sounds good - thank you!

**Comment by xtiaan3** [comment]
@tommasini any ideas we can look at right now for a work around to this issue?

**Comment by cortisiko** [comment]
This was fixed in https://github.com/MetaMask/metamask-mobile/pull/4060 and will be in v5.3 release

**Comment by bandelewskim** [comment]
@cortisiko What's an ETA for v5.3?

**Comment by cortisiko** [comment]
@bandelewskim it should be out at the end of next week.
