### ISSUE TITLE
Can I recover multiple account with same seed phrase 

### ISSUE THREAD

**Issue by AkshayBhimani** [MetaMask/metamask-mobile#4449]
**Describe the usability problem**
I had created an one account (name Acc1 ) using MetaMask and I have stored secret recovery phrase for that. After that I have created another account (name Acc2 ) but now problem is there is only one way to recover my Acc2 is by using Acc2 private key and **not by seed phrase**(Mnemonic).  

Internally MetaMask is using HD wallet then why I am not able to recover both account using one seed phrase? 
Is this is scope of improvement for MetaMask ? 
Or any security or vulnerability that I need to consider before implementing this feature. 
Or something that I am missing or fundamentally incorrect.  

**Expected behavior**
 Would able to recover all accounts that I have previously created on MetaMask wallet using only one seed phrase that was created at time of first account creation.

**Comment by andreahaku** [comment]
The seed phrase is used to recover ALL the accounts that are and will be created with it. So it'll recover Account 1, Account 2, etc.
You can find more information here: https://metamask.zendesk.com/hc/en-us/articles/4404722782107-User-Guide-Secret-Recovery-Phrase-password-and-private-keys
