### ISSUE TITLE
Browser not sending POST

### ISSUE THREAD

**Issue by Raggaer** [MetaMask/metamask-mobile#4451]
**Describe the bug**
Any form I submit on the integrated browser does not work, the browser just makes a GET request instead. After inspecing the request on our servers I found out that no POST is ever sent on any form, ever.

I tried this on multiple sites (not even related to me, like Github and random forums on the Internet) and its the same issue on all of them. I even tried on a simple site with just a form element, no JavaScript.

I had no problem with other browsers like TrustWallet.

**To Reproduce**
Just trying to submit a form to login into a website.Any site is giving me the same issue.

**Expected behavior**
The browser should send a POST request instead of a GET request.

Any POST form is not working, when I try to submit any form it just sends a GET request instead (just reloads the page)

**Smartphone (please complete the following information):**
 - Device: Samsung s21 fe
 - OS: Android 12
 - App Version: 5.1.1

**Comment by tommasini** [comment]
Hey @Raggaer , thanks for reporting!

Could you provide a demo and a code snippet to help us reproduce this issue?

**Comment by Raggaer** [comment]
A very simple example I made quickly:

`<?php

if($_SERVER['REQUEST_METHOD'] === 'POST') {
  $username = $_POST['username'];
  echo "Welcome back <b>" . $username . "</b>";
}

?>

<html>
  <head>
    <title>DEMO</title>
  </head>
  <body>
    <form method="POST">
      <input type="text" name="username" placeholder="Username" />
      <input type="submit" value="Login" />
    </form>
  </body>
</html>
`

A simple POST form, using ngrok to expose it to the internet and using version v.5.3.0 (927) (downloaded today), everytime I click "Login" it sends a GET request, never a POST request.

**Comment by Raggaer** [comment]
It could be, inspecting the headers after the form submit, there are some missing, even after filling the form field, the data is never sent on the request, the browser sends a GET and not a POST:

```
GET / HTTP/1.1
Host: XXXX.ngrok.io
User-Agent: Mozilla/5.0 (Linux; Android 12; SM-G781B Build/SP1A.210812.016; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/103.0.5060.71 Mobile Safari/537.36
Accept-Encoding: gzip
X-Forwarded-For: XX.XX.XX.XXX
X-Forwarded-Proto: https
```

**Comment by 612crypto** [comment]
Did you ever find a solution to this? I'm having the same problem.
