### ISSUE TITLE
[5.5][Ledger Integration] Typed sign v1, v3 don’t work on with ledger

### ISSUE THREAD

**Issue by owencraston** [MetaMask/metamask-mobile#4454]
### **Description**

- when signing a typed message with the ledger nano x on the [ledger-modals](https://github.com/MetaMask/metamask-mobile/tree/ledger-modals) branch, only the v4 message works. 
- v1 and v3 do not work (i don't know what happened to v2 in the test dapp)

### **To Reproduce**

- connect the ledger
- go to [https://metamask.github.io/test-dapp/](https://metamask.github.io/test-dapp/)
- sign typed data
- notice that the sign typed data v1, v3 do not work
    - the modal will appear but there is no sign message prompt on the device
    - the modal instantly shows the device is disconnected
    - the `TypedMessageManager` throws a warning `message not found for id: undefined`
- signing typed data `v4` works

### **Acceptance Criteria**

-   When a user signs typed data v1 and v3
-   the modal should prompt the user to sign the message

### **References**
- discovered in [this pr](https://github.com/MetaMask/metamask-mobile/pull/4426)

#### Video

https://user-images.githubusercontent.com/22918444/172201535-8b4f416c-0c0f-4a45-b0bb-4137676bbbc6.mp4

**Comment by zoltanarvai** [comment]
That's correct we only support v4. How should we handle this from a UI perspective?

**Comment by AlexJupiter** [comment]
Here's the [docs](https://docs.metamask.io/guide/signing-data.html#a-brief-history) for MetaMask's `signTypedData` I don't think we need to worry about `v2` but perhaps `v3` and definitely `v4` of course. I guess we could include a specific error in this case such as `signTypedData_v2 not supported`.

**Comment by plasmacorral** [comment]
Build 938 shows an error message and the transaction does not appear to be sent to the Ledger device.
https://recordit.co/LQ5KPkFjiL

**Comment by plasmacorral** [comment]
resolved in 952
