### ISSUE TITLE
[5.5][Ledger Integration] Pressing the reject button on the LedgerConfirmationModal does not cancel action on ledger device

### ISSUE THREAD

**Issue by owencraston** [MetaMask/metamask-mobile#4455]
### **Description**
- when signing a message with the ledger nano x on the [ledger-modals](https://github.com/MetaMask/metamask-mobile/tree/ledger-modals) branch, pressing the reject button on the LedgerConfirmationModal does not cancel action on device,

### **To Reproduce**
- connect the ledger
- go to [https://metamask.github.io/test-dapp/](https://metamask.github.io/test-dapp/)
- sign transactions
- reject the transaction
- the modal dismisses `but the signature request is still present on the device`

### **Acceptance Criteria**

- GIVEN a user is signs a message with their ledger
- WHEN a user presses reject on the confirmation modal
- THEN the sign request should be cancelled on the device

### **References**

-   Discovered in [this PR](https://github.com/MetaMask/metamask-mobile/pull/4426)

### Video

https://user-images.githubusercontent.com/22918444/172202677-bbdd6f03-cc4a-44a5-b763-4b1332a72129.mp4

**Comment by AlexJupiter** [comment]
This isn't possible to do, we need to decide whether to remove this as per https://github.com/MetaMask/metamask-mobile/issues/4457

**Comment by zoltana-ledger** [comment]
This is not possible to do however now the device reports it's busy on follow up transactions. Fixed in this PR:
https://github.com/MetaMask/metamask-mobile/pull/4534

**Comment by plasmacorral** [comment]
This was from build 952 on Android 12 with the pixel 3a:

https://recordit.co/fUyaDgcntW

**Comment by plasmacorral** [comment]
resolved in 952
