### ISSUE TITLE
[5.5][Ledger integration] Rejecting a signature on the ledger device returns a state of disconnected to the LedgerConfirmationModal

### ISSUE THREAD

**Issue by owencraston** [MetaMask/metamask-mobile#4458]
### **Description**

- Rejecting a signature on the ledger device returns a state of disconnected to the LedgerConfirmationModal
- can be found on the [ledger-modals](https://github.com/MetaMask/metamask-mobile/tree/ledger-modals) branch

### **To Reproduce**
- connect the ledger
- go to [https://metamask.github.io/test-dapp/](https://metamask.github.io/test-dapp/)
- sign transactions
- reject the transaction `on the device`
- notice how the modal tells us that the device is disconnected

### **Acceptance Criteria**

Scenario: 1
- GIVEN a user signs a message on their ledger
- WHEN a user rejects the signing on their ledger device
- THEN the ledger confirmation modal should indicate that the signing was rejected

### **References**

-   Found in [this PR](https://github.com/MetaMask/metamask-mobile/pull/4426)

### Video

https://user-images.githubusercontent.com/22918444/172210824-dff8efd4-1ac6-44a2-958a-18844cf98b75.mp4

**Comment by zoltana-ledger** [comment]
Address this in this PR: https://github.com/MetaMask/metamask-mobile/pull/4534

**Comment by plasmacorral** [comment]
Using build 952 on Android 12 with pixel 3a.  

When transaction is rejected from Ledger, the transaction continues to show in Activity view with a status of "approved" and with the Speed up and Cancel CTAs.

I suspect we should consider NOT showing the CTAs and a better status description than "approved" for a transaction attempt that was in fact rejected.

https://recordit.co/6s4hwG2XCc

**Comment by plasmacorral** [comment]
Transaction now shows in activity with status of 'Failed' when the tx is rejected on Ledger in commit ddf9f3347c3b2e887f9e465d36f93406e01c147c

https://recordit.co/Bj7CWkxDtT
