### ISSUE TITLE
[5.5][Ledger Integration] Refactor LedgerTransactionModal 

### ISSUE THREAD

**Issue by owencraston** [MetaMask/metamask-mobile#4466]
### **Description**

Migrate the LedgerTransactionModal to use the ReusableModal pattern. The changes would be the same as the work done in [this pr](https://github.com/MetaMask/metamask-mobile/pull/4426). This requires modifying the stack navigator like [this](https://github.com/MetaMask/metamask-mobile/blob/main/app/components/Nav/Main/MainNavigator.js#L119)

### **References**

- This work would be basically identical to the work done in [this PR](https://github.com/MetaMask/metamask-mobile/pull/4426)

**Comment by zoltana-ledger** [comment]
Done in this PR: https://github.com/MetaMask/metamask-mobile/pull/4534
