### ISSUE TITLE
[5.5][Ledger Integration] Try again button gives no feedback to the user

### ISSUE THREAD

**Issue by owencraston** [MetaMask/metamask-mobile#4467]
### **Description**
- the try again button does not have a loading state after being pressed
- an action is being queued on the ledger device but it takes a while so it encourages the user to press the button several times

### **To Reproduce**
- connect the ledger
- go to [https://metamask.github.io/test-dapp/](https://metamask.github.io/test-dapp/)
- sign transactions
- reject the transaction `on the device`
- notice how the modal tells us that the device is disconnected and has a try again button
- click `try again`
- notice how there is no loading state after pressing try again
- the ledger eventually asks to sign another transaction but it takes a while after pressing the button

### **Acceptance Criteria**

Scenario: 1
- GIVEN a user signs a message on their ledger
- WHEN a user rejects the signing on their ledger device
- AND the user clicks try again
- THEN the ledger confirmation modal should indicate that it is trying to sign the message again

### **References**

-   Found in [this PR](https://github.com/MetaMask/metamask-mobile/pull/4426)

### Video

https://user-images.githubusercontent.com/22918444/172415487-ff771724-2a12-4fc5-b8c5-24802bcafce5.mov

**Comment by edsonayllon** [comment]
How are you connecting Ledger to metamask? I don't see this option in iOS

**Comment by zoltana-ledger** [comment]
Addressed this in this PR. https://github.com/MetaMask/metamask-mobile/pull/4534

**Comment by plasmacorral** [comment]
Unable to click try again after rejecting tx from Ledger:
https://recordit.co/6s4hwG2XCc

**Comment by plasmacorral** [comment]
resolved in 952
