### ISSUE TITLE
How to get MetaMask signature via personal_sign

### ISSUE THREAD

**Issue by qm921** [MetaMask/metamask-mobile#4476]
I can't get the signature via personal_sign

I can get the signature from trust wallet or imToken，But in this nothing happens to MetaMask
I want to know how to get signature in kotlin project

override suspend fun personalSign(message: String): Session.MethodCall.Response {
        return withContext(dispatchers.io) {
            suspendCoroutine { continuation ->
                sessionRepository.address?.let { address ->
                    sessionRepository.session?.let { session ->
                        val id = System.currentTimeMillis()
                        val messageParam = if (message.hasHexPrefix()) message else message.toHex()
                        session.performMethodCall(
                            Session.MethodCall.Custom(
                                id,
                                "personal_sign",
                                listOf(messageParam, address)
                            )
                        ) { onResponse(id, it, continuation) }
                        openWallet()
                    } ?: continuation.resumeWith(Result.failure(Throwable("Session not found!")))
                } ?: continuation.resumeWith(Result.failure(Throwable("Address not found!")))
            }
        }
    }

Android Phone: Redmi k50
Android Version:12
MetaMask Version:5.1.1

**Comment by afterlifehy** [comment]
I have encountered the same problem. How did you solve it

**Comment by qm921** [comment]
> I have encountered the same problem. How did you solve it

The parameters you pass in for production, I can get the signature by filling in the parameters for production.

**Comment by jiaweio** [comment]
> > I have encountered the same problem. How did you solve it
> 
> The parameters you pass in for production, I can get the signature by filling in the parameters for production.

Hello, what do you mean by production parameters? Hope to get your reply

**Comment by qm921** [comment]
> > > I have encountered the same problem. How did you solve it
> > 
> > 
> > The parameters you pass in for production, I can get the signature by filling in the parameters for production.
> 
> Hello, what do you mean by production parameters? Hope to get your reply

The formal parameters you need when publishing to the app market

**Comment by jiaweio** [comment]
> > > > I have encountered the same problem. How did you solve it
> > > 
> > > 
> > > The parameters you pass in for production, I can get the signature by filling in the parameters for production.
> > 
> > 
> > Hello, what do you mean by production parameters? Hope to get your reply
> 
> The formal parameters you need when publishing to the app market

Thank you for your reply, but I don't know what you mean by the parameters released to the application market? Where does it get this parameter and pass it in?

val messageParam = if (message.hasHexPrefix()) message else message. toHex()

Do you mean this? （messageParam）

**Comment by qm921** [comment]
> > > > > I have encountered the same problem. How did you solve it
> > > > 
> > > > 
> > > > The parameters you pass in for production, I can get the signature by filling in the parameters for production.
> > > 
> > > 
> > > Hello, what do you mean by production parameters? Hope to get your reply
> > 
> > 
> > The formal parameters you need when publishing to the app market
> 
> Thank you for your reply, but I don't know what you mean by the parameters released to the application market? Where does it get this parameter and pass it in?
> 
> val messageParam = if (message.hasHexPrefix()) message else message. toHex()
> 
> Do you mean this? （messageParam）

Sorry I didn't find the solution here, but I found the solution in other projects


https://github.com/pink-room/walletconnectkit-android

I was using this project to solve the problem

**Comment by jiaweio** [comment]
> 



> > > > > > I have encountered the same problem. How did you solve it
> > > > > 
> > > > > 
> > > > > The parameters you pass in for production, I can get the signature by filling in the parameters for production.
> > > > 
> > > > 
> > > > Hello, what do you mean by production parameters? Hope to get your reply
> > > 
> > > 
> > > The formal parameters you need when publishing to the app market
> > 
> > 
> > Thank you for your reply, but I don't know what you mean by the parameters released to the application market? Where does it get this parameter and pass it in?
> > val messageParam = if (message.hasHexPrefix()) message else message. toHex()
> > Do you mean this? （messageParam）
> 
> Sorry I didn't find the solution here, but I found the solution in other projects
> 
> https://github.com/pink-room/walletconnectkit-android
> 
> I was using this project to solve the problem

I know this project. I tried his personal sign method. After jumping to metamask, I won't pop up a window to prompt the user for authorization, so I want to know exactly what went wrong. Should you have the same problem? How did you solve it? What do you mean by the parameters released to the application market? I've been troubled by this problem for a long time. I hope to get your help, thank you

**Comment by qm921** [comment]
WalletConnectKitConfig need some parameters, including bridgeUrl = "https://bridge.walletconnect.org" I said means appUrl production environment parameters

**Comment by jiaweio** [comment]
> WalletConnectKitConfig need some parameters, including bridgeUrl = "https://bridge.walletconnect.org" I said means appUrl production environment parameters

val config = WalletConnectKitConfig(
    context = this,
    bridgeUrl = "wss://bridge.aktionariat.com:8887",
    appUrl = "walletconnectkit.com",
    appName = "WalletConnectKit",
    appDescription = "WalletConnectKit is the Swiss Army toolkit for WalletConnect!"
)

Is this the appurl? Does it mean the download link of the current application in the application market? Why does this affect the user authorized signature that metamask does not pop up?

**Comment by qm921** [comment]
Don't use the demo appUrl, it won't work, you have to change the appUrl to the address that your project is going to use
I'm not sure why it doesn't pop up. I found it by browsing other tutorials. It took me a long time

**Comment by jiaweio** [comment]
OK, how do you get your signature? Because you can't get a signature without pop-up authorization. Are you an Android Developer?

**Comment by qm921** [comment]
> 好的，你怎么得到你的签名？因为没有弹窗授权是无法得到签名的。你是安卓开发者吗？

I just Googled it and I forget the details   no

**Comment by qm921** [comment]
> OK, how do you get your signature? Because you can't get a signature without pop-up authorization. Are you an Android Developer?

I just Googled it and I forget the details no

**Comment by jiaweio** [comment]
> > OK, how do you get your signature? Because you can't get a signature without pop-up authorization. Are you an Android Developer?
> 
> I just Googled it and I forget the details no

OK, thanks for your reply. I may need to try again

**Comment by EthanChenccc** [comment]
我解决了这个问题，appurl要传你们官网的地址

**Comment by EthanChenccc** [comment]
> > > OK, how do you get your signature? Because you can't get a signature without pop-up authorization. Are you an Android Developer?
> > 
> > 
> > I just Googled it and I forget the details no
> 
> OK, thanks for your reply. I may need to try again
我解决了这个问题，appurl要传你们官网的地址

**Comment by jiaweio** [comment]
> > > > OK, how do you get your signature? Because you can't get a signature without pop-up authorization. Are you an Android Developer?
> > > 
> > > 
> > > I just Googled it and I forget the details no
> > 
> > 
> > OK, thanks for your reply. I may need to try again
> > 我解决了这个问题，appurl要传你们官网的地址

你好 使用这个库 [https://github.com/pink-room/walletconnectkit-android]，填写官网地址后，跳转到 metamask 就可以弹出签名弹窗了是么，方便加你的联系方式请教一下相关问题么？我被这个问题困扰很久了，希望得到你的回复  感谢
