### ISSUE TITLE
[5.3] Update What's New Modal

### ISSUE THREAD

**Issue by Cal-L** [MetaMask/metamask-mobile#4479]
### **Description**

Update What's New Modal to use templating system

### **Technical Details**

- Update `WhatsNewModal/index.js` to parse and render data from `whatsNewList.js`
- Update `whatsNewList.js` with template system

```
- Slides utilizes a templating system in the form of a 2D array, which is eventually rendered within app/components/UI/WhatsNewModal/index.js.
- The root layer determines the number of slides. Ex. To display 3 slides, the root layer should contain 3 arrays.
- The inner layer determines the content that will be rendered within each slide.
- The slide content takes the form of union types, where the possible types are `image`, `title`, `description`, or `button`.
- Both slide count and slide content will be rendered in the same order as the data set.
```
   
### **Acceptance Criteria**

- Template system should support any number of slides
- It should also support any order of the union types

### **References**

- Figma example of what these changes should support - https://www.figma.com/file/2h15YfvbT2q4q1FOMJFPP1/Token-Detection-V2?node-id=12%3A3663

**Comment by wachunei** [comment]
@Cal-L  Should we close this and mark it as superseded by #4484?

**Comment by Cal-L** [comment]
Included in https://github.com/MetaMask/metamask-mobile/pull/4484
