### ISSUE TITLE
IOS Wallet doesn't notify rejection for signature requests

### ISSUE THREAD

**Issue by anxolin** [MetaMask/metamask-mobile#4482]
**Describe the bug**
Metamask IOS doesn't report back to the Dapp when a user rejects a request

This makes the Dapp to be blind, so is not really aware if the user took any action or not.

You can reproduce it in CowSwap using WalletConnect

<img width="1044" alt="image" src="https://user-images.githubusercontent.com/2352112/172862460-d8ce21c7-eb84-4eec-8961-15c157568856.png">

**To Reproduce**

1. Open development tools for Chrome. 
2. Go to https://cowswap.exchange/
3. Connect wallet using Wallet Connect. Use Metamask IOS (not sure if Android has the same issue or not)
4. In the network tab of Dev Tools, find the Websocket for Wallet Connect. There click on the messages, to see already the first handshake for Wallet Connect connection
4. Select a token pair you've never traded before
5. Click on "Approve Token" 
6. Notice how the Dapp sent a message to the wallet
7. Reject the transaction from the wallet
8. Observe how the Websocket didn't get any new message after user's action

Weirdly enough, If you do other operations, like wrapping ETH or signing orders using EIP-712 we are notified when the user rejects the signature. 

Can you review what is the issue?

**Comment by tommasini** [comment]
Hey @anxolin, thanks for reporting!

Could you reproduce it on in app browser?
