### ISSUE TITLE
Google Play Store Build Not the Same as Github Release APK on Android 12

### ISSUE THREAD

**Issue by brian-kryptomon** [MetaMask/metamask-mobile#4489]
**Describe the bug**
We are experiencing an error where deep linking to do signing using Chainsafe is working if users download the APK from the Github release page but if they have the version from the Google Play store then it doesn't work. 

Please note we tried this with all versions of 5.x

**Screenshots**

**To Reproduce**
Use the chainsafe library to deeplink for a signing request on the version from Google Play and the pop up doesn't show up. Download the APK from github and it works fine.

**Expected behavior**
Deeplinking signing should work the same on both and should work

**Smartphone (please complete the following information):**
 - Device: All
 - OS: Android 12
 - App Version [e.g. 1.0.0] - 5.2 (but happens on all)

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by tommasini** [comment]
Hey, @brian-kryptomon  thank you for reporting.
There is an issue with some Android 12 devices when trying to use deep link, you will have to:
_Open Android settings , search 'default' and select "Choose Default apps' > "Choose Default apps" > Opening Links > scroll down to MetaMask and tap it > Supported Web addresses > check if links are selected or "verified/trusted" by default (most importantly metamask.app.link). If they are not, then check them/it._

Please let me know if it worked

**Comment by cryptovale-eth** [comment]
Apparently we are all experiencing a similar issue (see mine here #4439) 
Changing the Android settings works in my case, but, as stated in my comment, this is a huge UX problem for the end users.

@brian-kryptomon where is your link shown, in an App or in a Browser? In my case, it works in Firefox Mobile.

**Comment by brian-kryptomon** [comment]
@tommasini Thanks I'll have our users try that - its odd that the version in google play is different than the APK. I assume this is something thats being looked into.

**Comment by brian-kryptomon** [comment]
@cryptovale-eth ours is coming from a mobile game running on Android 12 built in Unity with Chainsafe.

**Comment by brian-kryptomon** [comment]
@tommasini - I can confirm that works - thanks. Obviously its important for that to be on by default if possible but at least now I understand why its happening.

**Comment by brian-kryptomon** [comment]
@tommasini any idea how to address these settings issues on MIUI 13 or Funtouch OS 12? I found an article to unlock hidden settings but when the user goes into the opening links settings its greyed out and disabled.
![image](https://user-images.githubusercontent.com/98599660/173467069-63c0b5ac-0a13-4b0c-bf06-6b4344694f80.png)
![image](https://user-images.githu

https://user-images.githubusercontent.com/98599660/173467142-caba5b35-ca28-40bf-bc80-fa6837f8894b.mp4

busercontent.com/98599660/173467102-5e6a9ea5-8068-4ca5-867f-dd88d456dae0.png)

**Comment by tommasini** [comment]
@brian-kryptomon could you confirm if the issue it's still happening to the users with those OS? 
Thank you!

**Comment by brian-kryptomon** [comment]
@tommasini After the settings change the players were able to get deep linking working on the standard Android 12 version but the option to update the supported links is greyed out on MIUI and Funtouch so there doesn't seem to be a solution on those. Also obviously the Google Play store version needs to be updated to support this.

I'm not sure whats different between the APK and play store versions.

**Comment by tommasini** [comment]
@brian-kryptomon Thank you so much for your reports and your help. Now we are investigating the deeplink issue with Branch.io.

About the apk and Google Play Store version, for me both versions are 5.2.0 and build (913), to verify the version and the build please go to _Left Menu -> Settings -> About MetaMask_
![Screenshot_20220614_113206_io metamask](https://user-images.githubusercontent.com/46944231/173557845-9522b033-54f5-4877-9187-c8d4234fcac5.jpg)
)

**Comment by iners-max** [comment]
I have tried 2 phones

1. Samsung Note 10 Android 12. <-- it works after allowing `metamask.app.link`
2. Google Pixel 4 Android 12 <-- it does not work after allowing `metamask.app.link`
