### ISSUE TITLE
Dark Mode - Cannot scan request for payment QR code

### ISSUE THREAD

**Issue by plasmacorral** [MetaMask/metamask-mobile#4490]
**Describe the bug**
I suspect that the fix will be similar to this issue raised on extension: https://github.com/MetaMask/metamask-extension/issues/14304

When I tap "receive" from wallet view while in dark mode, the QR code is presented without a white box around the QR.  This prevents "QR journal" app on mac from being able to read the QR until darkmode is disabled.

**Screenshots**

<img src="https://user-images.githubusercontent.com/32695229/173392515-dc82c11d-a3cb-4ee4-83d2-31d7fdb66aeb.png"
 width="200"/>

**To Reproduce**
_Steps to reproduce the behavior_
1. Go to wallet view
2. tap on "Receive"
3. attempt to scan QR
4. run out of patience and disable dark mode to actually scan QR

**Expected behavior**
QR should have a white box around it on dark mode, and with that would be promptly scanned when displayed.

**Smartphone (please complete the following information):**
 - Device: Pixel 3a and 4a
 - OS: Android 12
 - App Version v5.2 build 913

*White box is also missing on iOS.

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by plasmacorral** [comment]
Follow-up note: Looks like this may not impact every QR scanner.  The in-app scanner can handle the QR just fine, but this QR journal app from Apple's app store couldnt pick it up.  That said, that specific app also has not been updated in a few years.

Bottom line- All QR code readers are not created equal, and some have a problem with the lack of white border on the QR as presented in dark mode.

**Comment by cortisiko** [comment]
Was fixed in https://github.com/MetaMask/metamask-mobile/pull/4639
