### ISSUE TITLE
Can't add Optimism network on MetaMask mobile

### ISSUE THREAD

**Issue by ranmocy** [MetaMask/metamask-mobile#4492]
**Describe the bug**
Calling `wallet_addEthereumChain` to add Optimism network on MetaMask mobile will throw exception with message: `May not specify default MetaMask chain.`

**To Reproduce**

Send request from a dApp running within MetaMask mobile browser:

```javascript
window.ethereum.request({
  method: 'wallet_addEthereumChain',
  params: [
    {
      chainId: "0xa",
      chainName: "Optimism",
      rpcUrls: ["https://mainnet.optimism.io"],
      blockExplorerUrls: ["https://optimistic.etherscan.io"],
      nativeCurrency: {
        "name": "ETH",
        "symbol": "ETH",
        "decimals": 18
      }
    }
  ]
})
```

**Expected behavior**

Optimism is added successfully as a custom network.

**Smartphone (please complete the following information):**
 - Device: Pixel 5a
 - OS: Android 12
 - App Version: 5.2.0

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by ranmocy** [comment]
From what I can see, the exception is thrown from [this line in wallet_addEthereumChain.js](https://github.com/MetaMask/metamask-mobile/blob/bdb7f37c90e4fc923881a07fca38d4e77c73a579/app/core/RPCMethods/wallet_addEthereumChain.js#L105), where it checks the chainId against [this list `NetworksChainId`](https://github.com/MetaMask/controllers/blob/7256c7ec3942265df7dee1a5b9cef32189b8d02c/src/network/NetworkController.ts#L23).

The list contains `optimism` network, therefore it rejects the request.

I think the condition is incorrect, it should checks if the network has been added to the local network lists, instead of `NetworksChainId`. The list contains networks that are not really added as default networks (which is `optimism` and `optimismTest`.

**Comment by yichunsung** [comment]
still can not use mobile app for Calling `wallet_addEthereumChain`

ios app v5.12.3

same issue for `May not specify default MetaMask chain.`

> **Describe the bug** Calling `wallet_addEthereumChain` to add Optimism network on MetaMask mobile will throw exception with message: `May not specify default MetaMask chain.`
> 
> **To Reproduce**
> 
> Send request from a dApp running within MetaMask mobile browser:
> 
> ```js
> window.ethereum.request({
>   method: 'wallet_addEthereumChain',
>   params: [
>     {
>       chainId: "0xa",
>       chainName: "Optimism",
>       rpcUrls: ["https://mainnet.optimism.io"],
>       blockExplorerUrls: ["https://optimistic.etherscan.io"],
>       nativeCurrency: {
>         "name": "ETH",
>         "symbol": "ETH",
>         "decimals": 18
>       }
>     }
>   ]
> })
> ```
> 
> **Expected behavior**
> 
> Optimism is added successfully as a custom network.
> 
> **Smartphone (please complete the following information):**
> 
> * Device: Pixel 5a
> * OS: Android 12
> * App Version: 5.2.0
> 
> _to be added after bug submission by internal support / PM_ **Severity**
> 
> * How critical is the impact of this bug on a user?
> * Add stats if available on % of customers impacted
> * Is this visible to all users?
> * Is this tech debt?
