### ISSUE TITLE
How to Integrate metamask in native android application?

### ISSUE THREAD

**Issue by DarshanKSPL** [MetaMask/metamask-mobile#4500]
1. Creating a URL so users can open your app directly in MetaMask Mobile to interact with my application with their Ethereum account.
2. Providing a one-click experience such that users can easily make payments to another account (with pre-filled parameters like recipient address, amount, network, etc.)

How can I achieve this functionality in my android application?

Requirement:
I have my own android application. I need app flow where user can click on one button and user should be redirected to payment screen in metamask wallet with required details like from, to, amount, processing fees etc, So user can easily make transaction from wallet and navigate back to my android application with appropriate transaction status and other information.

I read this in documentation but haven't found any supported documentation for mobile application. So how can I archive this functionality with my android application?

![image](https://user-images.githubusercontent.com/103264769/173673351-d494c84f-28f3-4c42-aa36-05a1fd2ddea0.png)

**Comment by tommasini** [comment]
Heyy @DarshanKSPL you can use Wallet Connect 
https://docs.walletconnect.com/mobile-linking#for-android

I will close this issue

**Comment by DarshanKSPL** [comment]
I have integrated wallet connect v1.0 to my android application. The functionality of requesting for connection and accepting connection is also working fine for me but when I try to make any transaction on ethereum mainnet nothing happens. 

**Problem:**
The functionality of requesting for connection and accepting connection is working fine and once connection request is accepted we are able to get public address. But If I click on send transaction button to perform transaction on my android app user is not redirected to metamask application, Actually user should be redirect user to metamask application and show transaction screen with transaction details like from, to, gas amount, gas fees.  

**Device specification**
Samsung Galaxy F41
Android 12
