### ISSUE TITLE
stuck a start screen with a small orange diamond logo

### ISSUE THREAD

**Issue by SvenMeyer** [MetaMask/metamask-mobile#4520]
**Describe the bug**
- Installed Metamask a few months ago
- updated it since then
- actually never used
- wanted to use it now
- stuck a start screen with a small orange diamond logo

**Screenshots**
![Screenshot_20220617-111922](https://user-images.githubusercontent.com/25609/174214009-40f09d6a-d803-420a-a31d-543be5e9dcbd.png)

**To Reproduce**
_Steps to reproduce the behavior_
click on Metamask App

**Expected behavior**
Metamask starts

**Smartphone (please complete the following information):**
 - Device: Google Pixel 4 XL
 - OS: Android 12
 - App Version 5.2 

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by tommasini** [comment]
Hey @SvenMeyer, believe that you solved this problem because of your last github [issue](https://github.com/MetaMask/metamask-mobile/issues/4521), I will close this one
