### ISSUE TITLE
error when importing private key

### ISSUE THREAD

**Issue by SvenMeyer** [MetaMask/metamask-mobile#4521]
**Describe the bug**
error when importing private key

**Screenshots**
![Screenshot_20220617-124158](https://user-images.githubusercontent.com/25609/174215189-f11d7f06-6952-4855-acb9-d7cb159bc2d8.png)

**To Reproduce**
- exported private key from Metamask Chrome browser plugin on Linux PC
- fresh install of Metamask
- a) copy pasted private key as text
- b) scanned QR image (generated from private key string)
- Error (see screenshot)

**Expected behavior**
import private key, show account

**Smartphone (please complete the following information):**
 - Device: Google Pixel 4 XL
 - OS: Android 12
 - App Version : v5.2.0 (913)

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by tommasini** [comment]
Hey @SvenMeyer, thanks for reporting!
I exported one private key from MetaMask extension and imported it on mobile and everything went as expected.
Could you provide more detailed steps on how are you exporting your private key?

**Comment by SvenMeyer** [comment]
@tommasini there is actually much you can do wrong ;-)
Account Detail > Export Private Key > enter Metamask password > copy-paste to QR-code generator or USB-stick (which goes into mobile)

I am sure the private key is correct as I imported it into another Metamask on another computer, also made sure no character got lost.

P.S.: Why does Metamask plugin not show a QR-code of private key directly which I could scan with Metamask mobile ?

**Comment by hixus** [comment]
Noticed the same today with MetaMask iOS. Exactly same qr-code worked fine on Android but failed on iOS. What helped was to reinstall MetaMask on iOS. I'm guessing some internal state get's messed up and importing stops working.

**Comment by tommasini** [comment]
@hixus thanks for reporting, which version of MetaMask are you using?

**Comment by tommasini** [comment]
@SvenMeyer sorry for the delay! You can propose that feature on the MetaMask extension repository

**Comment by hixus** [comment]
> 

Did not check the version before reinstall but now it's the latest v5.6.1 (967). Last install was before summer but I guess iOS autoupdates.

**Comment by frenchfilm** [comment]
Hi, I'm trying to import private key via copy/paste on mobile (don't have QR code feature), and I get the same error message from above ("Ooops etc."), but it works on desktop.
FYI:
- Apple iPhone 13
- iOS 16.4.1 (a)
- Metamask v6.3.0 (1095)

Thanks for any help!
