### ISSUE TITLE
Handling of EIP-681 links completely broken. Ignores data, sends transaction that is gonna fail, and shows as confirmed when failed

### ISSUE THREAD

**Issue by php4fan** [MetaMask/metamask-mobile#4537]
**Describe the bug**

From Chrome, I clicked on a EIP-681 link with this URL:
```
ethereum:pay-0xf4BE4f05c35A82BD2369c0bFdcf3588dE07967aC@56/mintNFT?value=2000000000000000&uint8=0x1b&bytes32=0xee9725f4348f8c31e31d17511fb72f2a54a76edc929736ed354207251bdf1b1c&bytes32=0x0a7c6f44205f9d688067146d69148dc8fb9b78322f99d41c5f75ae391a2a6bbe&uint64=580&uint64=1655634660
```
and also tried one like this (without the `pay-` prefix as the specs are unclear as to when it's required or not):
```
ethereum:0xf4BE4f05c35A82BD2369c0bFdcf3588dE07967aC@56/mintNFT?value=2000000000000000&uint8=0x1b&bytes32=0x36fddabe076e355cafc658808984426a03df863ac5da1972cf8f698f8504272a&bytes32=0x21733225eb60a38426d4e249fd430410fe74fdb83cfd51aad0edd30cb58d45f6&uint64=581&uint64=1655634660
```

That transaction calls a method in the contract that I'd actually expect to succeed. But it's possible that I did something wrong (that I'm not able to see) in building the link and that, therefore, the transaction actually fails. Either way, MetaMask's behavior is completely broken as is detailed below.

**To Reproduce**
_Steps to reproduce the behavior_
1. In Chrome, click on an EIP-861 link with an url like the ones above

**Expected behavior**
1. Should open MetaMask
2. Should prompt me to confirm the transaction
3. Note this is a transaction to a contract, calling a method with parameters. Metamask should attempt to perform THAT transaction, calling that method with those parameters. That's the transaction that should be attempted.
4. If the link is malformed in any way, it should show me an error message saying so.
5. If the link is well formed but the transaction is going to fail, MetaMask should detect that during gas estimation, and should warn me of that. Like the browser extension does. It should warn me and give me the option to "continue anyway". Since gas estimation normally fails in that case, I would expect to see a very high estimated fee.
6. If I do choose to proceed and send the transaction and it fails, it should tell me that the transaction has failed

**Observed behavior (why is this section missing in the template???????)**

Absolutely none of the above.

First of all, it seems like Metamask completely ignores the method name and parameters in the link, and just sends a transaction with no data. This is what I seem to understand by looking at the transactions that were actually sent:
https://bscscan.com/tx/0xf318c2c12fe711134ac37be35c0374655b32865fcad4946618a824b01d21cee9
https://bscscan.com/tx/0x4beff0ba5536fb338781ca29fb3534525dd71e5f25549f52fa1a6c0e266d19f5

If that is the case, then it is obvious that the transaction was doomed to fail.
Yet MetaMask showed me the preview of the transaction with estimated gas fees that sounded about right. There was no warning about the transaction going to fail. Nor was there any error message about the link being invalid in any way.

All looked like the transaction was going to be succesful, so I clicked Send, and the transaction was sent.

After a few second, it said "Transaction confirmed" with a green checkmark or something, I don't remember exactly, but there was definitely no indication that it had failed.

So I thought the transaction had succeeded and went to look at it on BSCScan and to my surprise it had failed, with an error thrown by the contract (most likely because it was called with no data, it looks like).

So to sum up the many issues here:
- MetaMask seems to ignore the method name and/or at least the parameters in the link and sends a transaction with no data
- unless there's something wrong in the link in which case it's failing to detect it and warn about it
- either way, when sending a transaction that is certain to fail, it doesn't detect it and warn about it, and proceeds anyway
- and finally, after the transaction has actually failed on chain, shows a bogus confirmation message says the transaction has succeeded (where it probably means that it "has gone through" and been recorded on-chain, with no check whatsoever as to whether it has succeeded or failed).

Do you expect people to use this crap for transactions that actually involve real money in significant amounts?!?

**Smartphone (please complete the following information):**
 - Device: Redmi Note 10S
 - OS: Android 11
 - App Version: just installed from the Play Store, so you figure that out.

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by tommasini** [comment]
Thanks for the report @php4fan , what is your app version? You can find it in _settings -> About MetaMask_

I did some EIP-681 transactions with this generator https://brunobar79.github.io/eip681-link-generator/# and everything went as expected

My app version is: 5.2.0

**Comment by php4fan** [comment]
> what is your app version?

5.2.0 (913)

> I did some EIP-681 transactions with this generator and everything went as expected

Can you provide examples of the links you generated?

Did you try any of the two I provided?

**Comment by php4fan** [comment]
> I generated here: https://brunobar79.github.io/eip681-link-generator/

I know but I'd like to try or see the particular links that you generated from there.

**Comment by php4fan** [comment]
By the way, that link generator is broken.

If I need to call a contract's method that has multiple parameters of the same type, e.g. (as is the case for my very links above) multiple `bytes32` parameters, the resulting link would have `....&bytes32=.....&bytes32=....` (which might be a questionable design choice by those who designed EIP-681 but that's just aesthetics); but the link generator will output at most one parameter per type.

That's not related to the issue at hand however. When I try to generate a link for one of my original example transactions with the broken link generator, I get something like this:
```
ethereum:0xf4BE4f05c35A82BD2369c0bFdcf3588dE07967aC@56/mintNFT?value=2e15&uint8=0x1b&bytes32=0x0a7c6f44205f9d688067146d69148dc8fb9b78322f99d41c5f75ae391a2a6bbe&uint64=1655634660
```
which is not the correct link and is expected to fail; but MetaMask won't even send the transaction that this link encodes, it will send one with no data instead.

**Comment by lukoyanov** [comment]
I've tried to construct some QRs for smart-contract class using EIP-681 as well, and scan codes with MetaMask mobile. 

I can confirm that it's not working as expected: call data in the resulting transaction is displayed as "0x" meaning **neither the smart-contract method name nor the params were correctly encoded from QR to the transaction body.**

My QR content:
```
ethereum:0x149622EF78d2DE74e9B14fDA5da15fda6918A06B@56/payERC?value=000000000000000&address=0x14186C8215985f33845722730c6382443Bf9EC65
```

Resulting TX:
https://bscscan.com/tx/0x67f54a7e28b910ad84bd7bcd3ee667e7254217e353c1fad30d17389f26ce8103

If anyone has any information regarding how to construct a working QR code for Metamask, please kindly share.

My MM version is 7.2.0 (1142)

**Comment by dsapaev** [comment]
I have the same problem - we need to use EIP-681 on our project, but MM is not maintain this spec(

**Comment by php4fan** [comment]
And here we go again.

Will you kill the stupid bot?

**Comment by BB-301** [comment]
I'm having a similar same problem. I am working on an experimental project and stared adding support for [ERC-681](https://eips.ethereum.org/EIPS/eip-681) URIs to be able to generate quick transactions to interact with some of my smart contract's methods, but, while able to open the QR codes and the URIs, MetaMask is simply ignoring the method names, arguments, etc., resulting in the wrong transactions.

I found other similar issues (e.g., #4547 and #4577 ), but no definitive answer about whether or not ERC-681 URIs are supported by MetaMask.

What precedes having been say, my question is the following: **Does MetaMask implement support for ERC-681?**

Thank you! :)

**Comment by php4fan** [comment]
> my question is the following: Does MetaMask implement support for ERC-681?

It doesn't, as you have observed.

**Comment by BB-301** [comment]
@php4fan, thanks for confirming this.

Given the fact that this issue has been marked as closed, do you think that it is safe to assume that adding support for ERC-681 is not a priority for MetaMask?

By the way, have you been able to find actual wallets that do have support for ERC-681?

**Comment by php4fan** [comment]
> Given the fact that this issue has been marked as closed, do you think that it is safe to assume that adding support for ERC-681 is not a priority for MetaMask?

I think it's safe to assume that **none of the bugs or feature requests in this bug tracker is a priority** for MetaMask, as I've never seen any of them be fixed in years. Having MetaMask become remotely usable, or compliant to any standard or to anything that a wallet is supposed to be, doesn't seem to be a priority either. **Frankly I have no idea what the developers are doing**, as there seem to  be commits happening in this repository all the time, but as far as actual functionality is concerned, there's been no improvement whatsoever in the last 4 years or so (I don't know about before that). **I think they are just pretending to do work** so that they can keep scamming money out of investors.

**The reason this bug is closed** (just like most others) is that they have a **stupid bot** that automatically closes any issue that's inactive for a given time. Which means, **issues get closed "because" they don't get fixed**. That's the most idiotic thing ever, but that's not something that MetaMask invented. I've seen the same  thing in many repositories, I think it's a default in GitHub. It's run by Microsoft, right? So that's not surprising.

> By the way, have you been able to find actual wallets that do have support for ERC-681?

No, but I stopped searching long ago.

**Comment by BB-301** [comment]
@php4fan, thanks for your reply!

> No, but I stopped searching long ago.

So far, I have not found any either. It's such a shame, because I really like the idea behind [ERC-681](https://eips.ethereum.org/EIPS/eip-681). I think it would be a plus for the community to be able to generate transactions (for smart contract interactions) using a simple URI, without necessarily requiring to connect the wallet to a DApp. I honestly don't understand why there are not more people asking about this? I'm relatively new to Ethereum programming, so maybe there are some things I don't understand yet, which would help explain why that ERC-681 specification did not get any traction.

**Comment by nicky-ru** [comment]
With ai agents now able generating links/qrcodes to interact with smart contracts directly for users in the chat needs support from metamask. Would be happy to have it fixed too!
