### ISSUE TITLE
Hex data field does not work

### ISSUE THREAD

**Issue by php4fan** [MetaMask/metamask-mobile#4538]
**Describe the bug**
I can't f***ing believe this. How can such a basic feature be so broken.

**Screenshots**
![image](https://user-images.githubusercontent.com/13969584/174483003-9574e50f-c890-465e-b90a-8389c44dc803.png)

**To Reproduce**
1. Go to Settings, Advance, and turn on **"Hex data"**.
2. Go to Send, enter an address belonging to a smart contract, click Next, enter an amount, click Next
3. Click on **"Hex Data"**

**Expected behavior**
I should be able to enter the freaking hex data

**Actual behavior**
See the screenshot above.
There is no keyboard, and if I long-press on the "0x" no Paste option shows up. I have no way of entering or pasting hex data.

**Smartphone (please complete the following information):**
 - Device: RedMi Note 10S
 - OS: Android 11
 - App Version 5.2.0

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by php4fan** [comment]
This is a duplicate of #1932 (doesn't seem to be possible for me to close it as such)

**Comment by tommasini** [comment]
Thank for reporting @php4fan!
Closing this issue to #1932
