### ISSUE TITLE
On-chain NFTs do not render in the NFT tab

### ISSUE THREAD

**Issue by shanejonas** [MetaMask/metamask-mobile#4561]
**Describe the bug**
On-chain NFTs do not render in the NFT tab

**Screenshots**
<img width="423" alt="image" src="https://user-images.githubusercontent.com/364566/174907518-2ab3f530-469f-4c4d-bf4a-52c8e1646d84.png">

**To Reproduce**
(on rinkeby)
1. Go to https://oneclickdapp.com/scoop-sensor
2. Click on write
3. click mint
4. wait for tx
5. see collection show up but not the image

**Expected behavior**
I should see an image for on-chain SVGs

**Problem**
for on-chain SVGs `tokenURI(id)` returns base64 urls, they need to be parsed into JSON, then use the `image` key:
<img width="1217" alt="image" src="https://user-images.githubusercontent.com/364566/174907931-d79c2cb5-f8d5-4db7-9e66-8cc88531889a.png">

Here is what my mint site does to pull out the metadata: 
<img width="536" alt="image" src="https://user-images.githubusercontent.com/364566/175323691-b9f6a711-6900-44b8-a57e-12f4612be3ba.png">

**Comment by tommasini** [comment]
Move this on to the icebox until we decide what to do.

What I concluded with my Android native research for implementing the remote svgi t's that to render a local svg file it's easier, but when we talk about having the SVG code coming remotely, it's not so easy, why:
 * We need to convert the svg code to vector code (with a file we could use the [shapeshifter](https://shapeshifter.design/)). 
 * Shapeshifer uses [paperJS](http://paperjs.org/features/#svg-import-and-export), for my understanding do not support some tags of the svg code (tested on the shapeshifter website)

**Comment by shanejonas** [comment]
this is still a valid issue. MetaMask Mobile should support on-chain NFTs.

**Comment by mastergaurang94** [comment]
Very much still a valid issue.

**Comment by lampalork85** [comment]
Same problem on Chrome extension with On-Chain image of nft , the strange behavior is that in the preview of an NFT transfer, the image is displayed correctly :

![image](https://github.com/MetaMask/metamask-mobile/assets/38051081/8d4851d5-8ed7-4f54-b259-4e2429d6b27f)

 but not in the NFT panel where we see the default image from MM :
 
![image](https://github.com/MetaMask/metamask-mobile/assets/38051081/260a9f63-5a62-44ee-8b4f-ffff1090977e)

**Comment by vrde** [comment]
The issue is still valid. On-chain NFTs, which are fully embedded in the blockchain without external dependencies, represent the purest form of NFTs. Supporting them should be a priority.
