### ISSUE TITLE
Activity/Transactions only show the most recent transaction, should show all transactions up to supported limit

### ISSUE THREAD

**Issue by chrisleewilcox** [MetaMask/metamask-mobile#4565]
Related https://app.zenhub.com/workspaces/mobile-release-regression-6249e5242464b70013315a98/issues/metamask/mobile-planning/307

Not seeing all transactions for Swaps on Binance when swapping under different languages. Only seeing the most recent transactions after changing language and then swapping. Also, other token swap transactions are no longer displayed after swapping for a different token.
This does not impact Ethereum Mainnet.

```
Scenario: Transactions on Binance network should display all transactions executed on device based on view up to supported limit 

Given I added Binance network using Popular networks add
And I have English language selected in settings
When I swap BNB for USDT
Then swap transaction is successful (see recording, transaction time 11:53)
And swap transaction is displayed in BNB token view 
And swap transaction is displayed in USDT token view 
And swap transaction is displayed in Activity view 
When I change language to Filipino in settings
And I swap all USDT for BNB
Then swap transaction is successful (see recording, transaction time 12:22, you will also notice the previous transactions is not displayed during the swap)
And all swap transaction for BNB is displayed in BNB token view (FAILED: I'm only seeing the most recent transactions @ 12:22, not seeing previous transactions @ 11:53)
And all swap transaction for USDT is displayed in USDT token view (FAILED: I'm only seeing the most recent transactions @ 12:22, not seeing previous transactions @ 11:53)
And all swap transaction for all tokens is displayed in Activity view (FAILED: I'm only seeing the most recent transactions, @ 12:22, not seeing previous transactions @ 11:53)
When I swap BNB for CAKE
Then swap transactions is successful
And swap transactions for USDT is still displayed in USDT token view (FAILED: I am no longer seeing my USDT transactions after swapping BNB for CAKE)
And swap transactions for USDT is still displayed in Activity view (FAILED: I am no longer seeing my USDT transactions after swapping BNB for CAKE)
```

I have tried closing and reopening app and waiting a while but still not all transactions displayed for swaps on Binance. Happens on both android and iOS devices.  Further test still pending for other networks,  languages and tokens but please check to see if there is a pattern that will also impact other networks and other languages and other tokens.

https://recordit.co/qFlTtFSCyy

https://recordit.co/yQoAiLiEPm shows CAKE transactions no longer displayed after swapping BNB for USDT

**Comment by bschorchit** [comment]
Does this only happens with swaps transactions or with any transaction?

**Comment by bschorchit** [comment]
Does this also happens with non-swaps transactions?

**Comment by blackdevelopa** [comment]
@bschorchit yes it does.

**Comment by blackdevelopa** [comment]
This could be related to a specific behavior regarding controllers. -Seth.

**Comment by bschorchit** [comment]
Saya's design: https://www.figma.com/file/v8sBltXirh61z9CnGWc6lx/Activity%2F-Transaction-history?node-id=910%3A1321
