### ISSUE TITLE
Send transaction functionality is not working

### ISSUE THREAD

**Issue by DarshanKSPL** [MetaMask/metamask-mobile#4586]
I have integrated wallet connect v1.0 to my android application. The functionality of requesting for connection and accepting connection is also working fine for me but when I try to make any transaction on ethereum mainnet nothing happens.

**Describe the bug:**
The functionality of requesting for connection and accepting connection is working fine and once connection request is accepted we are able to get public address. But If I click on send transaction button to perform transaction on my android app user is not redirected to metamask application, Actually user should be redirect user to metamask application and show transaction screen with transaction details like from, to, gas amount, gas fees.

**Expected behavior**
When user click on send transaction button once connection request is approved, it should be redirected to metamask android application and display send transaction screen with required details filled.

**Smartphone:**
 - Device: Samsung Galaxy F41
 - OS: Android 12

**Severity**
This is very crucial issue for me as it is a blocker. Please help me to resolve this.

**Comment by tommasini** [comment]
@DarshanKSPL thanks for reporting!

Can you provide a snippet or a link for we test it?

In order to redirect to metamask it has to be a user click. Because deeplinks only work if opened in the same thread as the user click.

**Comment by gantunesr** [comment]
Hi @DarshanKSPL, can you provide reproduction steps and/or a recording of the issue for our team to investigate this issue?

**Comment by bschorchit** [comment]
Closing as there has been no response for repro steps.
