### ISSUE TITLE
Internal browser does not work with Auth0

### ISSUE THREAD

**Issue by IntelMin** [MetaMask/metamask-mobile#4588]
When an app calls an auth api which is built by Auth0, it is supposed to be redirected to the redirection url with access token.
Code logic is perfect and it really works well on other web browsers like Google Chrome.
However when we try such action on Metamask internal brower, it is redirected to url with empty access token.

**To Reproduce**
1. Go to 'https://attestation.id/'
2. Enter your email address and then input confirmation code by checking email
3. See the flow stucks

**Expected behavior**
When you click `Confirm` button, it requests an access token to backend and then should get redirected to the next step with a valid token

**Smartphone (please complete the following information):**
 - Device: Samsung
 - OS: Android 9
 - App Version: The latest version of Metamask App from PlayStore

**Comment by oleggrib** [comment]
https://attestation.id/ flow works perfect for desktop browsers, for android chrome, but doesnt work for Metamask internal browser, so its not a problem with  'https://attestation.id/'

**Comment by tommasini** [comment]
Hey @IntelMin , thanks for reporting


I can't reproduce the issue, could you provide what's your app version?

![Screenshot_20220712_172049_io metamask](https://user-images.githubusercontent.com/46944231/178543987-02faa4cc-af2c-495c-a528-0abe594e4671.jpg)

**Comment by oleggrib** [comment]
@tommasini , problem appear when you enter 6 digits from email and click confirm.

in Chrome it authorize Auth0 and opens wallet to sign message, but in Metamask browser it stucks with error in process or Auth0 authorization.

**Comment by IntelMin** [comment]
> Hey @IntelMin , thanks for reporting
> 
> I can't reproduce the issue, could you provide what's your app version?
> 
> ![Screenshot_20220712_172049_io metamask](https://user-images.githubusercontent.com/46944231/178543987-02faa4cc-af2c-495c-a528-0abe594e4671.jpg)

@oleggrib is right. This issue only happens when runs the app on metamask internal browser, and then inputs 6-digits code.

**Comment by AW-STJ** [comment]
@IntelMin is there any updates on this issue?

**Comment by IntelMin** [comment]
> @IntelMin is there any updates on this issue?

@AW-STJ , no update from dev team, waiting for their feedback.

**Comment by tommasini** [comment]
I can confirm this is happening on Android. We will research what's happening.
Thank you so much for reporting.

**Comment by AW-STJ** [comment]
Thank you so much @tommasini for looking into the issue.

**Comment by AW-STJ** [comment]
Hey Team - checking on this issue. Do you have any thinking around when this fix could be implemented?

**Comment by bneeland** [comment]
We have the same issue; any updates?

**Comment by AW-STJ** [comment]
Hey Team - any updates on this?

**Comment by rizkyrachyan** [comment]
any update on this? The issue is also happening on my project

**Comment by AW-STJ** [comment]
Any updates on this team?

**Comment by Cl2pp** [comment]
Any news on this issue. We also experience it
