### ISSUE TITLE
Transactions don't show up anywhere.

### ISSUE THREAD

**Issue by php4fan** [MetaMask/metamask-mobile#4591]
**Describe the bug**
And after using metamask for 10 more minutes, here I am reporting two more bugs that I've found in one single interaction

**To Reproduce**

On Android, in Chrome:

1. Visit a website that uses WalletConnect to connect to MetaMask and send a transaction
2. When prompted by the OS to choose an app to open, choose metamask
3. accept the transaction. The transaction succeeds.
4. now or at any moment, go back to MetaMask

**Expected behavior**
1. I should not see any error message or warning that something went wrong with the transaction, because nothing did. The transaction succeeded and can be seen on BSCScan

2. I should be able to see my past transactions somewhere in MetaMask. Not only the one that I just did, but at least every transaction that I have ever done with MetaMask from this device, and arguably MetaMask should be able to query the network for all my reasonably recent transactions sent from my account, whether or not they were made using MetaMask on this device

**Observed behavior (why is this field missing in this stupid template)**

1. When I manually go back to MetaMask, this shows up at the bottom of the screen for a few seconds:

![image](https://user-images.githubusercontent.com/13969584/175693459-dbd893e9-ae19-46f6-93cf-dae1dca01132.png)

That is not true. Nothing went wrong.

Even more irritatingly, tapping on **"tap to view this transaction" does NOTHING**.

When you instruct the user to tap on something to view something, can you at least make sure that it works, please??

2. I can't see my recent or past transactions anywhere. I've made a few from this account, and some of them (including the very one mentioned above) from this very device using MetaMask.

![image](https://user-images.githubusercontent.com/13969584/175695180-e1265a56-5ddc-4ae9-bf72-c572903294bd.png)

**Smartphone (please complete the following information):**
 - Device: Redmi Note 10S
 - OS: Android 11
 - App Version [e.g. 1.0.0] - 5.2.0 (913)

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by Ekoios-Henry** [comment]
I have same issue

**Comment by tommasini** [comment]
Hey @php4fan , thanks for reporting!
We are aware of this issue and we are working on a solution!
