### ISSUE TITLE
Ledger integration UI/UX issues

### ISSUE THREAD

**Issue by gantunesr** [MetaMask/metamask-mobile#4594]
**Describe the bug**
In the following issue, there are a series of UI/UX issues found in the ledger integration,

**Bug list**

- [ ] ANDROID - "View Settings" button has no margin or padding to the bottom of the screen
- [ ] Close button should be black (light mode) or white (dark mode)
- [ ] Error text is not clear. "If you want to pair your Ledger device **_using you'll need_** ..."

<img width="300" alt="image 1" src="https://user-images.githubusercontent.com/17601467/175830845-56fbebc4-4d04-4476-9f26-4270352f8ba2.png">

- [ ] Question mark image has white background in dark mode

<img width="300" alt="image 2" src="https://user-images.githubusercontent.com/17601467/175831141-98bbddab-460c-4891-aca7-68d858ed0235.PNG">

- [ ] Ledger image is pixelated
- [ ] The word Ledger sometimes is displayed as `Ledger` or `ledger`, we should be consistent in the casing. Let's use `Ledger` for all the occurrences.

<img width="300" alt="image 3" src="https://user-images.githubusercontent.com/17601467/175831185-3df05655-4552-4ae3-840e-348f0fac0e24.PNG">

- [ ] The "Hardware" label is not properly displayed

<img width="300" alt="image 4" src="https://user-images.githubusercontent.com/17601467/175831218-17c8fc37-da27-49c5-9a7b-1dc80b1ad778.PNG"> <img width="300" alt="image 5" src="https://user-images.githubusercontent.com/17601467/175831388-5359854c-c966-4094-a450-354d8e94d217.png">

- [ ] Transaction confirmation image is not shown properly

<img width="300" alt="bug-6" src="https://user-images.githubusercontent.com/17601467/175845428-281978ed-1323-4595-b98b-45317c25c531.png">

**Smartphone (please complete the following information):**
 - Device:
   - Galaxy A22
   - iPhone Xs Max
 - OS:
   - Android 11 
   - iOS 15.5
 - App Version: Ledger Integration

**Comment by GummyGod** [comment]
Addresed in this [PR](https://github.com/MetaMask/metamask-mobile/pull/4619)

**Comment by plasmacorral** [comment]
Hardware label is still showing white font on white background in Drawer when in light mode. (STILL NEEDS FIXED)Text is showing white on dark background (correct) in dark mode.
<div style="display: inline-block">{<img src="https://user-images.githubusercontent.com/32695229/190524124-76aa2c5b-3ee3-4228-96db-03f2fc019329.png" width="130">, 
<img src="https://user-images.githubusercontent.com/32695229/190524196-2431f3f4-c6da-4e40-a337-e8bad42651c2.png" width="150"/>


"View settings" was replaced with "Retry" and now has padding, copy was also replaced:
<img src="https://user-images.githubusercontent.com/32695229/190523858-ce4dd6f1-8ca3-4b32-9b34-a8724e7eecb9.png" width="150"/>



X is now white in darkmode or black in light mode:
<div style="display: inline-block">{<img src="https://user-images.githubusercontent.com/32695229/190523098-4283c4a5-c9da-4536-b4da-17e60f107c01.png" width="130">, 
<img src="https://user-images.githubusercontent.com/32695229/190523379-7a68d751-e9c7-4a00-8710-07519a034ac8.png" width="150">
}</div>

Ledger image is no longer pixelated ^ 

Question mark in dark mode has dark background:
<img src="https://user-images.githubusercontent.com/32695229/190523098-4283c4a5-c9da-4536-b4da-17e60f107c01.png" width="150"/>


Transaction confirm looks correct:
<img src="https://user-images.githubusercontent.com/32695229/190524422-90174add-12db-4a59-90c6-e77587c52e1c.png" width="150"/>

**Comment by plasmacorral** [comment]
Opened a unique ticket for the one item still unaddressed, everything else is confirmed in build 952.
