### ISSUE TITLE
Ledger integration - Connecting unpaired device

### ISSUE THREAD

**Issue by gantunesr** [MetaMask/metamask-mobile#4596]
**Describe the bug**
If the Android mobile app tries to connect to an unpaired Ledger device, the connection fails without a proper error message.

**Screenshots**

https://user-images.githubusercontent.com/17601467/175832386-e3364ba3-60d7-40bb-990c-a9d3de1a7000.mov

**To Reproduce**
_Steps to reproduce the behavior_
1. Unpair the Ledger device 
2. Ethereum app
  a. Closed - Ledger device works as expected 
3. Bluetooth and Location should be enabled
4. Press "Continue" and try to connect the Ledger device
5. Bluetooth paring OS modal should appear
6. The mobile app stay in the connection screen
7. After pressing "Continue" again the screen dismiss automatically and the error Toast shows up

**Expected behavior**
The app should connect properly with the Ledger device or display a more accurate error message

**Smartphone (please complete the following information):**
 - Device: Galaxy A22
 - OS: Android 11
 - App Version: Ledger Integration

**Comment by holantonela** [comment]
Why we cannot initiate the pairing flow again? Do you want/need users to do it manually in the OS settings?

**Comment by gantunesr** [comment]
I'm not sure why, but there's an issue when you try to pair it from MMM and the smoother way is to pair in the OS settings. I'm not sure technically why is not possible, I haven't dedicated too much time to it, but during my tests I was not able to pair it during the flow.

**Comment by plasmacorral** [comment]
Was able to pair again after forgetting device and did not see oops error in build 952
