### ISSUE TITLE
Ledger Integration - Issue when trying to connect while 2 devices are available

### ISSUE THREAD

**Issue by gantunesr** [MetaMask/metamask-mobile#4597]
**Describe the bug**
When the app tries to connect to a Ledger device, if another device is available, the app will improperly show both devices.

**Screenshots**

https://user-images.githubusercontent.com/17601467/176013188-97caa0c0-01a3-4351-b349-0f50be28c38f.mov

**To Reproduce**

1. The mobile device should have bluetooth and location enabled
2. Two Ledger devices should be available for connection and paired to the mobile device
3. Go to "Connect a hardware wallet" > "Ledger"
4. See how both devices switches erratically in the Device Selection dropdown 

**Expected behavior**
The dropdown should show the first device detected as default and the rest in a list

**Smartphone (please complete the following information):**
 - Device: Galaxy A22
 - OS: Android 11
 - App Version: Ledger Integration

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by GummyGod** [comment]
Adressed in this [PR](https://github.com/MetaMask/metamask-mobile/pull/4619)

**Comment by plasmacorral** [comment]
https://recordit.co/m6GLGC1pym
