### ISSUE TITLE
Fix missing Color type from theme

### ISSUE THREAD

**Issue by Cal-L** [MetaMask/metamask-mobile#4601]
### **Description**

Upgrading to design-tokens v1.7.0 broke the use of `Color` type in style sheets. This PR aims to fix those imports.

### **Technical Details**

-  Replace `Colors` with `ThemeColors` from @metamask/design-tokens library

Scenario: xxxx
- GIVEN a user is in x state
- WHEN a user does x
- AND a user does x
- THEN x should occur

### **References**

-   References go here.
-   Issue numbers. Links.
-   Slack threads.
-   Etc.

**Comment by cortisiko** [comment]
closing since this issue was fixed in https://github.com/MetaMask/metamask-mobile/pull/4602
