### ISSUE TITLE
TS check isn't working

### ISSUE THREAD

**Issue by Cal-L** [MetaMask/metamask-mobile#4605]
### **Description**

TS check for both pre-commit hook and in Github actions doesn't seem to be working at the moment. Need to look into why this is happening. Issue reported by Pedro - https://consensys.slack.com/archives/C02U025CVU4/p1658169660733469

### **Technical Details**

-  TBD by dev

### **Acceptance Criteria**

- Typescript check should work pre-commit hook
- Typescript check should work in Github actions

### **References**

- Issue that Pedro experienced - https://consensys.slack.com/archives/C02U025CVU4/p1658169660733469

**Comment by tommasini** [comment]
Thanks @Cal-L 
Please provide more details
