### ISSUE TITLE
Deeplinks to other apps not wokring in browser

### ISSUE THREAD

**Issue by thirdprize** [MetaMask/metamask-mobile#4615]
**Describe the bug**
Deeplinks to other apps on mobile phones do not work in the metamask mobile (MMM) apps browser. I have an app that opens a dapp in the MMM browser which in turn deeplinks back to the original app.  This is a duplicate of https://github.com/MetaMask/metamask-mobile/issues/4004
as it is still not working.  Well, it was fixed for a bit but then it stopped working again.  An example deeplink would be 

web3mobiledemoapp://address/0xce41b49d28800de3ba9925f68d82129dfc4b870b
where web3mobiledemoapp is registered to an app on my phone.

**Screenshots**
not applicable

**To Reproduce**
1. Open the browser tab in MMM and go to "https://www.redfivesoftware.com/Web3Metamask.htm?return=web3mobiledemoapp".
2. Wait until the screen has refreshed with the users eth address.
3. Tap the URL "return to app" and it should try opening an app whose datascheme is "web3mobiledemoapp".  It doesn't, it just sits there.
4. 

**Expected behavior**
It should open an existing app on the phone but it does not.

**Smartphone (please complete the following information):**
 - Device: Fairphone 3
 - OS: Android 11
 - App Version 5.2.0

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by Cherden** [comment]
Same problem for me in MetaMask v5.4.0 with Android 12.

**Comment by jiangwei1995** [comment]
Same problem for me in MetaMask v5.3.0 with Android 12.

**Comment by jiangwei1995** [comment]
Same problem for me in MetaMask v5.5.1(949) with iOS 15.4.1.

**Comment by thirdprize** [comment]
While it is still a bug,  what are you all using it for?   You might want to check out the Metamask sdk.   It is the way to go for connecting,  signing and sending via the app.

**Comment by jiangwei1995** [comment]
Thank you very much！
How to use metamask SDK? Can you send me a document？

**Comment by andreahaku** [comment]
@thirdprize @jiangwei1995 using a url scheme on the in-app browser doesn't work. The in-app browser is fundamentally a web view.

You have two options for now:
- one is to have the user open the dapp/web application on a mobile browser and connect to MM mobile with WalletConnect
- the second is to keep using the in-app browser but use deep linking services like Firebase, Branch.io, etc that allows you to create universal links to your app like our for example (https://metamask.app.link/something).

We are working on expanding these options but for now, those are the one ready available.

**Comment by jiangwei1995** [comment]
@andreahaku  I see. Thank you for your proposal

**Comment by thirdprize** [comment]
@andreahaku Have you got a link for signing up for the SDK beta?  Just in case anyone else wants to sign up for it.

**Comment by andreahaku** [comment]
> @andreahaku Have you got a link for signing up for the SDK beta? Just in case anyone else wants to sign up for it.

@thirdprize the SDK is in private beta. It'll be public in the coming weeks. When it'll be public I'll surely share all the info about it :)

**Comment by andreahaku** [comment]
> @andreahaku Have you got a link for signing up for the SDK beta? Just in case anyone else wants to sign up for it.

@thirdprize the SDK is in private beta. It'll be public in the coming weeks. When it'll be public I'll surely share all the info about it :)

**Comment by jiangwei1995** [comment]
@andreahaku 
I use firebase dynamic links on Google Pixel 4
Android 12, Metamask v5.4.0(931)
It works normally in Google Chrome and can pull up my app
Unable to pull up my app in metamask browser

https://user-images.githubusercontent.com/9276313/186565663-b5386ccf-fde6-41d2-837e-f2c6621cabfc.mov
