### ISSUE TITLE
Creates new network when replacing the RPC of an existing network

### ISSUE THREAD

**Issue by edsonayllon** [MetaMask/metamask-mobile#4620]
**Describe the bug**

A new network is created when replacing the RPC of an existing network. This leaves multiple network with the same name and chain id.

**Screenshots**
_If applicable, add screenshots or links to help explain your problem_

**To Reproduce**
_Steps to reproduce the behavior_
1. Have Polygon added as a network with an rpc
2. On MetaMask mobile, go to settings > network > polygon. Replace the RPC with a new URL

**Expected behavior**
_A clear and concise description of what you expected to happen_

Should replace the RPC, keeping the same network. No new networks added

**Smartphone (please complete the following information):**
 - App Version [e.g. 1.0.0] - find version number in app from Settings > About MetaMask

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by tommasini** [comment]
If the RPC URL it's different this is expected

**Comment by edsonayllon** [comment]
I don't think this is what I was expecting at all. I went to edit an existing network, wasn't expecting it to create a new network to select

**Comment by tommasini** [comment]
Thank you for reporting @edsonayllon, we will take a look on this
