### ISSUE TITLE
Transaction confirmation screen doesn't show recipient address!!!!

### ISSUE THREAD

**Issue by php4fan** [MetaMask/metamask-mobile#4622]
This is the confirmation screen for a transaction.

This can be a transaction initiated by a webpage that I have opened in the in-app browser and that is using the MetaMask javascript API, or it can be a transaction initiated from another device connected via WalletConnect.

Regardless, the recipient address, i.e. the address I'm sending the freaking money to, should be shown. You are only showing the sender address.

![image](https://user-images.githubusercontent.com/13969584/177053974-aeb9c478-6332-4920-a081-b55f549a3fe1.png)

**Comment by holantonela** [comment]
https://github.com/MetaMask/metamask-extension/issues/17313

**Comment by holantonela** [comment]
When triggered by a deeplink, the sender is not being shown in the confirmation screen. It may be because our send flow relies on a different view UI for this case. 

The sending flow in mobile exposes a Confirmation screen as part of the send flow (which has three steps, being the confirmation screen the 3rd step in this flow).

I propose to:

1. Move the send flow into a sheet component to achieve consistency with the send flow in other scenarios (eg. triggered by the users, not by a QR reading). We already have the sheet component used in the receive flow. 
2. Move the user to the 3rd of 3 steps of the flow in case the external trigger link defines the recipient. It will also allow users to edit the sender and amount on the predefined fields via known patterns.

**Comment by holantonela** [comment]
https://github.com/MetaMask/metamask-mobile/issues/2814

**Comment by bschorchit** [comment]
Small correction: the deeplink sendflow already works as described above. 
This is actually an issue for other types of transactions (like contract interactions). Should we also in this cases use the `from/to` component from the send flow (screenshot 1)? 
If yes, we're planning to have this header (screenshot 2) on those confirmations in the future, won't it be repetitive to have the same information (the `from` part) twice? Should we only add the `to` part

## Screenshots 

**Screenshot 1:**
![IMG_66505A480BC6-1](https://user-images.githubusercontent.com/34968356/218838247-8d4e8e35-c3f1-4ef9-bf0a-649cc20e8d1e.jpeg)

**Screenshots 2:**
<img width="506" alt="Screenshot 2023-02-14 at 16 37 29" src="https://user-images.githubusercontent.com/34968356/218839680-3edc017c-f466-44b6-a7dc-3cfdda6cc979.png">

**Comment by holantonela** [comment]
> Small correction: the deeplink sendflow already works as described above.
TRUE.

> Should we also in this cases use the from/to component from the send flow (screenshot 1)?

Can we have the entire send flow (tree steps) with the user in the 3/3 step? In this case, the user can edit fields if they want to. If this is too much refactoring, then yes from/to component is enough.

> If yes, we're planning to have this header (screenshot 2) on those confirmations in the future, won't it be repetitive to have the same information (the from part) twice? Should we only add the to part? Where should this live within the confirmation screen - below the header and origin pill?

I'd go to fix this missing input now and when we iterate this we will make sure that we don't have redundant data in the screen.

**Comment by bschorchit** [comment]
> Can we have the entire send flow (tree steps) with the user in the 3/3 step? In this case, the user can edit fields if they want to. If this is too much refactoring, then yes from/to component is enough.
The user should not be able to change fields in a contract interaction request as it would lead mostly to transaction failure and/or fund loss.

**Comment by bschorchit** [comment]
> I'd go to fix this missing input now and when we iterate this we will make sure that we don't have redundant data in the screen.

I just realized we already do have the from account info in this screen so this redundancy will happen anyway for now.

**Comment by jpuri** [comment]
@holantonela : can you plz check if this design looks ok:

![Screenshot 2023-03-01 at 5.07.45 AM.png](https://images.zenhubusercontent.com/61e70564eac52332e3564685/7c71dae2-25ca-41e3-a1aa-41630d89aeba)

**Comment by holantonela** [comment]
Thanks @jpuri, it looks good. I'm not sure why both borders have a different gray, but we can solve it with the DS team.

**Comment by holantonela** [comment]
@jpuri @bschorchit  let me know if there is anything else we should change here

![image](https://user-images.githubusercontent.com/87079938/223187320-3cc65487-acce-4b77-b930-d1fdf38335bb.png)

Figma
https://www.figma.com/file/ud5bXfGX3hzSeCMD6GqxDv/Consolidated-confirmations?node-id=187%3A23303&t=tTKWPXLL5kzsSXTl-1

**Comment by jpuri** [comment]
Hey @holantonela : in that case it will look very different from scenario where we do not have to address (new designs):

![Screenshot 2023-03-06 at 11 25 41 PM](https://user-images.githubusercontent.com/2182307/223191838-976051e1-178a-409d-8091-28d0414d0704.png)

@bschorchit : can you plz suggest.

**Comment by holantonela** [comment]
WIP here https://www.figma.com/file/ud5bXfGX3hzSeCMD6GqxDv/Consolidated-confirmations?node-id=191%3A26766&t=IHxynRJvhmDQvtwP-4

**Comment by holantonela** [comment]
UI 

![image](https://user-images.githubusercontent.com/87079938/223531235-30dc0b6d-1bad-490b-803a-4145d3217d42.png)


https://www.figma.com/file/ud5bXfGX3hzSeCMD6GqxDv/Consolidated-confirmations?node-id=191%3A29028&t=A208HBHRp18AffBp-4

**Comment by jpuri** [comment]
@holantonela : here is how it looks after latest code changes, can you plz suggest if this is ok:

![Uploading Screenshot 2023-03-09 at 1.14.59 PM.png…]()

**Comment by holantonela** [comment]
Thanks @jpuri. LGTM.

I'll make a PR to fix the from input bottom padding. Is not a blocker here.
