### ISSUE TITLE
Rejecting ETH Nano app install crash

### ISSUE THREAD

**Issue by ghost** [MetaMask/metamask-mobile#4641]
**Describe the bug**
_A clear and concise description of what the bug is_

**Screenshots**
_If applicable, add screenshots or links to help explain your problem_

**To Reproduce**
_Steps to reproduce the behavior_
1. open uniswap in MM browser
2. attempted to swap ETH for apecoin
3. Eth app not installed on Nano
4. Saw screen to inform me to install app :white_check_mark:
5. Clicked “reject”
6. Crash

**Expected behavior**
_A clear and concise description of what you expected to happen_

**Smartphone (please complete the following information):**
 - App Version [e.g. 1.0.0] - find version number in app from Settings > About MetaMask

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by AlexJupiter** [comment]
@zoltanarvai or @GummyGod has this been looked into at all? cc. @rickledge

**Comment by zoltanarvai** [comment]
Yes, it's addressed in upcoming PR.

**Comment by plasmacorral** [comment]
This is resolved.
