### ISSUE TITLE
Storage limit/corrupt data - reinstall mm

### ISSUE THREAD

**Issue by 4DR3N4L1N** [MetaMask/metamask-mobile#4645]
**Describe the bug**
Every few weeks I have to delete and reinstall mm on iPhone due to this corrupt local data that seems to occur after so much mm usage. This issue also seems to persist across other users as I hear about it in my chats sometimes. 

**Screenshots**
Attached
![CD52B88C-D726-4137-BAF3-3CA330ECF027](https://user-images.githubusercontent.com/108992634/178114629-0b2c7bb5-1236-4815-8467-a7db2f2970e3.jpeg)

**To Reproduce**
_Steps to reproduce the behavior_
1. it occurs a few weeks of steady use after fresh install 

**Expected behavior**
_A clear and concise description of what you expected to happen_

**Smartphone (please complete the following information):**
 - Device: iPhone 11 Pro
 - OS: iOS 15.5
 - App Version [e.g. 1.0.0] - v5.3.0 (927)

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user? It’s is a critical storage failure 
- Add stats if available on % of customers impacted
- Is this visible to all users? On multiple mobile users I have encountered 
- Is this tech debt?

**Comment by owencraston** [comment]
Hello @4DR3N4L1N,
Thank you for the logging the issue. We are aware of this issue and I am currently working on a solution to this exact problem. If possible, would you be able to let us know how much storage is being used on your phone (Settings/General/storage) as well as how much storage MetaMask is using? A simple screenshot would suffice.

**Comment by 4DR3N4L1N** [comment]
Hi thanks for getting back to me. The issue is not currently happening in mm but here are the screenshots [image0.png] [image1.png]

Devon.

On Jul 11, 2022, at 11:51 AM, Owen Craston ***@***.***> wrote:

﻿

Hello @4DR3N4L1N<https://github.com/4DR3N4L1N>,
Thank you for the logging the issue. We are aware of this issue and I am currently working on a solution to this exact problem. If possible, would you be able to let us know how much storage is being used on your phone (Settings/General/storage) as well as how much storage MetaMask is using? A simple screenshot would suffice.
