### ISSUE TITLE
Transactions shows wrong scan link

### ISSUE THREAD

**Issue by Cal-L** [MetaMask/metamask-mobile#4650]
### **Description**

Transactions shows wrong scan link

<img width="178" alt="image" src="https://user-images.githubusercontent.com/10508597/178332693-08f115c3-ff36-4d3c-ab43-89fae2ef9f24.png">

Video of issue - https://recordit.co/oZ9pNjXmfK

Steps to reproduce from @chrisleewilcox :
- After new install add Avalanche network using add popular networks
- Execute swap on Avalanche
- Add Binance network using add popular networks
- Execute swap on Binance
- The transactions will show view history on Avalanche in Activity > Transactions (This is where the scan link shows the wrong chain - Reference video)

### **Technical Details**

- The issue is most likely located in `components/UI/Transactions/index.js` since both Asset and Activity flows use this components + the issue has been seen in both places.
- More specifically - It might be related to storing `this.state.rpcBlockExplorer` in state and/or being a class component.
- A refactor to functional component is highly recommended and would be a good place to start.

### **Acceptance Criteria**

-  Transactions from Assets and Activity should both show correct scan links

Scenario: xxxx
- GIVEN a user is in x state
- WHEN a user does x
- AND a user does x
- THEN x should occur

**Comment by cortisiko** [comment]
this was fixed in https://github.com/MetaMask/metamask-mobile/pull/4963
