### ISSUE TITLE
Ledger logo seems pixelated

### ISSUE THREAD

**Issue by AlexJupiter** [MetaMask/metamask-mobile#4651]
**Describe the bug**
_A clear and concise description of what the bug is_
When looking closely at the Ledger logo on the connection screen the letter of the logo seems pixelated. 

**Screenshots**
_If applicable, add screenshots or links to help explain your problem_
![IMG_3893](https://user-images.githubusercontent.com/7900773/178470699-da706a8e-1ac5-4a86-8fad-ed342450507c.PNG)

**To Reproduce**
_Steps to reproduce the behavior_
1. Go to the "Connect hardware wallet screen"

**Expected behavior**
_A clear and concise description of what you expected to happen_
The letters should be clean and crisp.

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6] iPhone 13 pro
 - OS: [e.g. iOS8.1] iOS 15.5
 - App Version [e.g. 1.0.0] - find version number in app from Settings > About MetaMask 5.3.1

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by AlexJupiter** [comment]
This still seems pixelated on my current iOS build of 928. Did you say you'd already fixed this @gummygod? If so, could you link the PR?

**Comment by zoltanarvai** [comment]
It's addressed in upcoming PR.

**Comment by plasmacorral** [comment]
Build 952 on Android 12 pixel 3a with text and screen size set to max zoom:
![Screen Shot 2022-09-16 at 10 58 53 AM](https://user-images.githubusercontent.com/32695229/190673964-7047102a-0544-43ad-ab35-3a546f1f9b56.png)

**Comment by AlexJupiter** [comment]
From this screenshot I think we can close this now!
