### ISSUE TITLE
Cannot confirm transaction on Ledger device when Ledger locked

### ISSUE THREAD

**Issue by AlexJupiter** [MetaMask/metamask-mobile#4653]
**Describe the bug**
_A clear and concise description of what the bug is_
The Ledger device is locked, and then attempting to send a transaction the action sheet opens and then vanishes straight away without the chance to open the Ledger and confirm the transaction.

**Screenshots**
_If applicable, add screenshots or links to help explain your problem_

https://user-images.githubusercontent.com/7900773/178472119-eef32c00-d69f-4f0f-932b-59c2abcdf0d0.MP4

**To Reproduce**
_Steps to reproduce the behavior_
1. Go to 'submit a transaction between accounts with your Ledger account with the Ledger device locked'
2. Click on 'Confirm with Ledger'
3. See error

**Expected behavior**
_A clear and concise description of what you expected to happen_
The user should be prompted to unlock their Ledger device to confirm the transaction, as detailed here: https://docs.google.com/document/d/1PJveGQXOVRqq2ncev9UyFWQJJhRiyJbgPTFl-rQ4b54/edit#heading=h.qw8367d3ytyq 

**Smartphone (please complete the following information):**
Device: [e.g. iPhone6] iPhone 13 pro
OS: [e.g. iOS8.1] iOS 15.5
App Version [e.g. 1.0.0] - find version number in app from Settings > About MetaMask 5.3.1

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by montelaidev** [comment]
can't reproduce on 83f7a77. But received an error message of `Your device got disconnected` instead of locked device. In the logs, it is a LockedDeviceError

**Comment by montelaidev** [comment]
can't reproduce on 83f7a77. But received an error message of `Your device got disconnected` instead of locked device. In the logs, it is a LockedDeviceError

**Comment by plasmacorral** [comment]
I am seeing a message that the device is locked, when I unlock the device I am able to submit the transaction with no issue. 
<img width="150" alt="Screenshot 2023-03-24 at 6 21 49 PM" src="https://user-images.githubusercontent.com/32695229/227654179-d4f1e004-9089-4b46-a711-a64e81810879.png">
