### ISSUE TITLE
When completing a transaction the "Looking for device" screen doesn't reflect designs

### ISSUE THREAD

**Issue by AlexJupiter** [MetaMask/metamask-mobile#4659]
**Describe the bug**
_A clear and concise description of what the bug is_
When completing a transaction, the "Looking for device" screen doesn't contain all the instructions that a user needs to know to connect their Ledger and move to the next stage. 

**Screenshots**
_If applicable, add screenshots or links to help explain your problem_
![IMG_104C0A953AF5-1](https://user-images.githubusercontent.com/7900773/178545923-3f95f017-1096-45c0-be93-d5b4ea68b949.jpeg)

**To Reproduce**
_Steps to reproduce the behavior_
1. Go to 'complete a transaction with your Ledger account while the Ledger device is switched off'
2. See error

**Expected behavior**
_A clear and concise description of what you expected to happen_
As designed, this action sheet should look like this: https://www.figma.com/file/gw8z5Y9rT017ZKnc30M4dy/MetaMask-Mobile-ft-Ledger?node-id=701%3A4358

**Smartphone (please complete the following information):**
 - App Version [e.g. 1.0.0] - find version number in app from Settings > About MetaMask

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by AlexJupiter** [comment]
This issue is still prevalent, you can see it in this video: https://github.com/MetaMask/metamask-mobile/issues/4658#issuecomment-1195397699

**Comment by plasmacorral** [comment]
Build 952 on Android 12 with pizel 3a:
![Screen Shot 2022-09-15 at 7 18 02 PM](https://user-images.githubusercontent.com/32695229/190524962-d3b25338-cf31-4f42-a586-26ac30e84fa1.png)

**Comment by plasmacorral** [comment]
Have not observed this in build 952 in android 11, 12 or iOS 15.6.1
