### ISSUE TITLE
Sentry Error - TypedMessageManager: Message not found for id: undefined

### ISSUE THREAD

**Issue by gantunesr** [MetaMask/metamask-mobile#4668]
**Describe the bug**
_A clear and concise description of what the bug is_

TBD

Reference: https://sentry.io/organizations/metamask/issues/2865020065/?query=is%3Aunresolved+release.version%3A5.3.0+release.build%3A927&sort=freq&statsPeriod=30d

**Screenshots**
_If applicable, add screenshots or links to help explain your problem_

TBD

**To Reproduce**
_Steps to reproduce the behavior_

TBD

**Expected behavior**
_A clear and concise description of what you expected to happen_

TBD

**Smartphone (please complete the following information):**
 - App Version [e.g. 1.0.0] - find version number in app from Settings > About MetaMask

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by Jense5** [comment]
We are experiencing this issue whenever we call `wc.signTypedData([wallet,data])` from our SPA. When a metamask-mobile app is connected, the typed data is correctly shown but the 'sign button' is broken (you can tap it and the TouchableOpacity will flicker, but nothing happens). Once you click on cancel after clicking a few times on the "sign" button, this crash happens.

We experience this every time when we want to sign typed data. Please let me know if I can send some data over to help investigate.

@tommasini I see you added some try-catches in #4729, but I think this issue should be fixed and it's good that it shows in Sentry imo

**Comment by tommasini** [comment]
Hey, @Jense5  thank you so much for the comment.
We are trying to understand what causes this error and we have the intention to fix it.

Could you tell us your SPA and the steps for the crash so we are able to reproduce it?

**Comment by Jense5** [comment]
It's in development & repo isn't open source, but I found the reproducable issue: it's whenever the typed data includes an array. Whenever I try to sign the EIP712 payload below, sign button doesn't work & error is thrown on cancel.

Probably a result of https://github.com/MetaMask/metamask-mobile/issues/4441

```
 {
  "types": {
    "EIP712Domain": [],
    "credentialSubject": [
      {
        "name": "issuer",
        "type": "string"
      },
      {
        "name": "holder",
        "type": "string"
      }
    ],
    "credential": [
      {
        "name": "credentialSubject",
        "type": "credentialSubject"
      },
      {
        "name": "id",
        "type": "string"
      },
      {
        "name": "expires",
        "type": "uint256"
      },
      {
        "name": "issued",
        "type": "uint256"
      },
      {
        "name": "type",
        "type": "string[]"
      }
    ]
  },
  "message": {
    "@context": [
      "https://www.w3.org/2018/credentials/v1",
      "https://www.deth.co/credentials/deth/v1"
    ],
    "id": "some-random-id",
    "expires": "2023-07-26T13:37:51.157Z",
    "issued": "2022-07-26T13:37:51.157Z",
    "type": [
      "VerifiableCredential",
      "DethCredential"
    ],
    "credentialSubject": {
      "issuer": "did:ethr:0x0C67D443A924c3e86c8dcbE230F372c210076AA7",
      "holder": "did:ethr:0x0d856C597d8fAfb3745204C428217F66E5dAD4BB"
    }
  },
  "domain": {},
  "primaryType": "credential"
}
```

When I remove the list (attribute named "type"), everything works fine & signature works:

```
 {
  "types": {
    "EIP712Domain": [],
    "credentialSubject": [
      {
        "name": "issuer",
        "type": "string"
      },
      {
        "name": "holder",
        "type": "string"
      }
    ],
    "credential": [
      {
        "name": "credentialSubject",
        "type": "credentialSubject"
      },
      {
        "name": "id",
        "type": "string"
      },
      {
        "name": "expires",
        "type": "uint256"
      },
      {
        "name": "issued",
        "type": "uint256"
      },
    ]
  },
  "message": {
    "@context": [
      "https://www.w3.org/2018/credentials/v1",
      "https://www.deth.co/credentials/deth/v1"
    ],
    "id": "some-random-id",
    "expires": "2023-07-26T13:37:51.157Z",
    "issued": "2022-07-26T13:37:51.157Z",
    "credentialSubject": {
      "issuer": "did:ethr:0x0C67D443A924c3e86c8dcbE230F372c210076AA7",
      "holder": "did:ethr:0x0d856C597d8fAfb3745204C428217F66E5dAD4BB"
    }
  },
  "domain": {},
  "primaryType": "credential"
}
```

**Comment by gantunesr** [comment]
Hi @Jense5, as pointed out in https://github.com/MetaMask/metamask-mobile/issues/4441 MetaMask defaults to v3 which doesn't support arrays, we're considering validating the request to avoid the crash.
