### ISSUE TITLE
Imposibble to add custom network on iPhone SE2020

### ISSUE THREAD

**Issue by hixus** [MetaMask/metamask-mobile#4671]
**Describe the bug**

Can't scroll to and press "Add" button on iPhone SE2020. Because iPhone has this overflow scroll I can see that "Add" button is below the fold but when releasing press the form scrolls back to warning about "A malicious network" 

**Screenshots**
![Screenshot 2022-07-13 at 9 42 44](https://user-images.githubusercontent.com/1814734/178669338-62ea9cec-7873-41a1-bc15-f3ae44c1c4e2.png)
![Screenshot 2022-07-13 at 9 43 21](https://user-images.githubusercontent.com/1814734/178669351-84da0655-e79d-4f02-b40e-542ad865cdc1.png)

**To Reproduce**
Use phone size that does not fit whole Custom networks form
 
1. Go to "Networks"
2. Click on "Add network"
3. Click "Custom networks"
4. Fill the form and try to click  "Add" button

**Expected behavior**
Should be able to press "Add" button

**Smartphone (please complete the following information):**
 - Device: iPhone SE2020
 - OS: iOS 15.5
 - App Version v5.3.0

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by dohzya** [comment]
I have the same issue (SE2020 too).
Note that it is possible to click on the button when selecting one of the last fields.
(this comment is here to help any users blocked in this screen, it is definitively still a bug 🙂)

**Comment by aktwifis14uij** [comment]
#4945

**Comment by LuisNeves05** [comment]
Same here! 
Needed this fixed with some urgency if possible!

**Comment by LuisNeves05** [comment]
I got it to work by grabing the scroll bar. It's a bit glitchy but it worked! 
Hope this helps! 

https://user-images.githubusercontent.com/48102229/189367309-7cbb4b12-b73e-4a5a-ac03-d02612aefd34.mp4

**Comment by cortisiko** [comment]
relates to https://github.com/MetaMask/metamask-mobile/issues/4945

**Comment by artem-barmin** [comment]
Can reproduce at v7.15.0
