### ISSUE TITLE
With "unlock with device PIN" auth selected, unable to cancel device PIN and use the MetaMask password authentication

### ISSUE THREAD

**Issue by plasmacorral** [MetaMask/metamask-mobile#4675]
**Describe the bug**
On both android 11 and iOS 15.5, if I have selected to "Unlock with device PIN" authentication, I am unable to cancel the device PIN authentication and use the MetaMask password.  For other authentication factors, we support canceling and using the MetaMask password established at setup.

**Videos**
iOS example: https://recordit.co/Ka2cQUmwBJ
Android example: https://recordit.co/MGtXLgZLIa

**To Reproduce**
1. Have biometric factors available on the device
2. setup a wallet
3. access settings>security & privacy to enable biometric authentication
4. disable biometric authentication and enable device passcode authentication
5. Close the app
6. Relaunch the app
7. At the device PIN prompt, tap cancel
8. Note that you are stuck with an orange diamond on screen

**Expected behavior**
If a user taps "Cancel" on the device passcode prompt, they should be returned to the login page and able to access the wallet using the MetaMask password configured in setup.

**Smartphone (please complete the following information):**
 - Device: iPhone 13 mini & Samsung 515f
 - OS: iOS 15.5 & Android 11
 - App Version v5.3 build 927 (production)

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by plasmacorral** [comment]
Should be considered in the refactor PR https://github.com/MetaMask/metamask-mobile/pull/3755

**Comment by cortisiko** [comment]
@plasmacorral seems like the issue will be fixed in https://github.com/MetaMask/metamask-mobile/pull/4625

**Comment by cortisiko** [comment]
This was fixed in https://github.com/MetaMask/metamask-mobile/pull/4625
