### ISSUE TITLE
Browser: Cannot connect to pancakeswap.finance.  Getting Ooops! page on Android devices

### ISSUE THREAD

**Issue by chrisleewilcox** [MetaMask/metamask-mobile#4679]
This seems to be specific to Android devices.
http://recordit.co/4iSeJfC8kM

What's happening is that I am searching for 'pancakeswap' on home.metamask.io and I am tapping on "http://pancakeswap.finance" in the duckduckgo.com search results.  MMM browser on iOS devices and desktop browsers seem to auto-convert http to https and make everything smooth.  MMM browser on Android is not converting http to https.

**Comment by chrisleewilcox** [comment]
This is now working in 5.4.  Not sure what changed.  Will keep this open for now until 5.4 is in prod and homepage has been updated.

**Comment by cortisiko** [comment]
Closing this issue.
