### ISSUE TITLE
Error message while connecting Ledger, even though it did connect successfully 

### ISSUE THREAD

**Issue by AlexJupiter** [MetaMask/metamask-mobile#4691]
**Describe the bug**
_A clear and concise description of what the bug is_
When connecting my Ledger to my Android device an error screen appeared when it shouldn't have
**Screenshots**
_If applicable, add screenshots or links to help explain your problem_
![image](https://user-images.githubusercontent.com/7900773/179761723-768514ff-d987-4e05-bded-eaa052885fa6.png)

**To Reproduce**
_Steps to reproduce the behavior_
1. Go to 'Connect Ledger hardware wallet and follow all the steps'
2. See error screen
3. Notice that the Ledger has been connected successfully in any case

**Expected behavior**
_A clear and concise description of what you expected to happen_
This error screen shouldn't appear since the Ledger was connected successfully

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6] One Plus Nord N100
 - OS: [e.g. iOS8.1] Android 11
 - App Version [e.g. 1.0.0] - find version number in app from Settings > About MetaMask 5.3.1 (928)

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by rickledge** [comment]
Rick to test and see if this happens on a Pixel 5.

**Comment by rickledge** [comment]
I tested, see the same issue although it didn't immediately connect on hitting retry.

**Comment by AlexJupiter** [comment]
To fix, this might need resources from other Ledger teams. Which might be difficult to achieve.

**Comment by AlexJupiter** [comment]
@rickledge @zoltanarvai just picking this up again, are we sure there is no way that we can customise this screen on Android or simply make it not appear? Having this appear during every pairing journey on Android really isn't ideal.

**Comment by rickledge** [comment]
(messaged in Slack, proposal is to change the copy to be more user friendly, technical solution is likely to be lengthy)

**Comment by AlexJupiter** [comment]
Following on from the [Slack conversation](https://consensys.slack.com/archives/C02CYKAA8G1/p1658927627065869?thread_ts=1658920410.644329&cid=C02CYKAA8G1), how about we change this text to be a bit more user friendly if we know this screen is going to appear very often when it needn't. Perhaps:

`There's been a slight problem connecting your Ledger Nano X, tap "Retry" below to give this another go.

Sometimes this occurs due to the ETH app on your Ledger Nano X being open at the start of the pairing process with MetaMask Mobile.`

cc. @holantonela

**Comment by zoltanarvai** [comment]
Fixed in upcoming PR

**Comment by plasmacorral** [comment]
new error copy is presented in build 952, it does feel like this message shows frequently but in my experience was always successful on tapping "retry"
