### ISSUE TITLE
Update shadows with new design token shadows

### ISSUE THREAD

**Issue by georgewrmarshall** [MetaMask/metamask-mobile#4692]
### **Description**
Shadow tokens were recently merged into the design token repo and released in v`1.8`. Update the design tokens package and all of the shadows in the app to use the new tokens 

### **Technical Details**

- Update `@metamask/design-tokens` to v`^1.8.0`
- Update all components that use shadow to use the design tokens

### **Acceptance Criteria**

- All shadows in the app use the design tokens unless absolutely necessary  

### **References**
- [@metamask/design-tokens](https://github.com/MetaMask/design-tokens) repo
- [storybook design token shadow documentation](https://metamask.github.io/design-tokens/?path=/docs/shadows-shadows--shadow)

**Comment by brianacnguyen** [comment]
It seems that mobile does not use shorthand notation for shadows. Will need to update design tokens to also include specific shadow props
