### ISSUE TITLE
in dapp, use ethereum call contract，tips error undefined is not an object(evaluating 'e.toString')

### ISSUE THREAD

**Issue by zidianjian** [MetaMask/metamask-mobile#4695]
in dapp ,use ethereum call contract send erc20 token. sometimes tips error,maybe gas not Calculation completed，i click commit button

 - Device: oppo reno7 pro 5g
 - OS: colorOS v12.1
 - android:12
 - App Version5.3.0

![origin_img_v2_51981e0c-e591-4bda-9ffc-0983152952ag](https://user-images.githubusercontent.com/4725102/179889524-0fad2adf-a18e-4706-8c08-a19ff61e156b.jpg)

**Comment by tommasini** [comment]
Hey @zidianjian , thanks for reporting, we are already working on a solution.

Related to #4390
