### ISSUE TITLE
Address Rinkeby, Ropsten and Kovan deprecation

### ISSUE THREAD

**Issue by bschorchit** [MetaMask/metamask-mobile#4697]
Infura is currently planning on deprecating their Rinkeby, Ropsten and Kovan RPC endpoints almost immediately after the Merge. Once that happens, users won't be able to use these default networks as is in MM. Rinkeby won't be formally demised until Q2/Q3 2023 so users might still want to use those in the meantime. [Relevant slack thread](https://consensys.slack.com/archives/C028DKZAC79/p1658322079187659?thread_ts=1658248554.164459&cid=C028DKZAC79)

[Updated] Therefore, we should:

- [ ] add a yellow dismissible warning on Rinkeby, Ropsten and Kovan saying `Due to the protocol changes of Ethereum: Rinkeby, Ropsten, Kovan test networks may not work as reliably and will be deprecated soon. Learn more` - the learn more link will be provided soon.

In the future post merge, we will remove those networks from our default list.

**Comment by gantunesr** [comment]
@bschorchit Should this task also include the adding of the Sepolia testnet?

**Comment by bschorchit** [comment]
> @bschorchit Should this task also include the adding of the Sepolia testnet?

We'll include Sepolia in the future once Infura starts supporting it so we can ensure the RPC endpoint for a default network follows our privacy policy.

**Comment by bschorchit** [comment]
Closing as the PR linked to this has been merged 🎉
