### ISSUE TITLE
How to handle reject approve method in metamask mobile?

### ISSUE THREAD

**Issue by liyueran-bj** [MetaMask/metamask-mobile#4706]
**Describe the bug**
The exception message could not be caught when the Metamask mobile user rejected 'approve';
But the PC is normal:
`MetaMask - RPC Error: Error: MetaMask Tx Signature: User denied transaction signature.`

**Screenshots**
`try{`
`       const contract = new ethers.Contract(TOKEN_ADDRESS, ERC20.abi, jsonRpcProvider); // code 1`
`       const tx = await contract.approve(CONTRACT_ADDRESS, num); // code 2`
`       await tx.wait(); `
`    }catch(err){`
`      console.log(err); // unable to work code 3`
`    }`

**To Reproduce**
_Steps to reproduce the behavior_
1. Click on 'approve'
2. Click on 'rejected'
3. The program will get stuck at code 2

**Expected behavior**
_A clear and concise description of what you expected to happen_
It can execute normally, just like on PC

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone7P&iPhone8P]
 - OS: [e.g. iOS15&IOS16]
 - App Version [e.g. 5.3.0]

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by Sotatek-HiepNguyen2** [comment]
same here

**Comment by brad-playdon** [comment]
Experiencing this issue too.

**Comment by LucaTrip** [comment]
Same issue, any news?

**Comment by egorbond31** [comment]
same here

**Comment by cvetlicnifractional** [comment]
Same!

**Comment by Sotatek-DinhTran2** [comment]
Same!

**Comment by Sotatek-SonNguyen2** [comment]
same!

**Comment by belova412** [comment]
Same!

**Comment by amarpathak** [comment]
Still a problem
