### ISSUE TITLE
Disconnect Ledger

### ISSUE THREAD

**Issue by rickledge** [MetaMask/metamask-mobile#4709]
**Describe the usability problem**
_A clear and concise description of the specific usability issue_
If I have previously connected a Ledger, then want to disconnected it, I have to go through a flow that is a connect flow again, then click on Ledger, the forget. It's unintuitive. 

**Screenshots**
_If applicable, add screenshots or links to help explain the issue_

**Expected behavior**
_If possible, a clear and concise description / resolution of what you expected to happen_
There is a disconnect option on Ledger account screen.
------------------------------------------------------------------------------------------------------
_filled out after submission_

**User impact | Usage frequency | Feasibility scores**
_How important is this to the user, what the user wants to accomplish | Daily, weekly, monthly | Small, medium, large_

**Comment by AlexJupiter** [comment]
@rickledge are you referring to this screen here? https://www.figma.com/file/gw8z5Y9rT017ZKnc30M4dy/MetaMask-Mobile-ft-Ledger?node-id=571%3A3672 

I just checked this on my current iOS build and it seems to work fine. Agreed that the design could be improved but I think that'll be out of scope for launch.

**Comment by rickledge** [comment]
Yeah correct @AlexJupiter , not a bug. I labelled it as a UI improvement I thought? Just something for your backlog.
