### ISSUE TITLE
[GF UI] Componentize GasFeeCard

### ISSUE THREAD

**Issue by Cal-L** [MetaMask/metamask-mobile#4724]
### **Description**

Componentize the `GasFeeCard` component. Is not a component in Figma

### **Technical Details**

- [ ] Create a `GasFeeCard` component

### **Acceptance Criteria**

-  TBD

### **References**

- Figma - https://www.figma.com/file/aTBlkFLwSzzAXqQG6uf3fV/1559-mobile-exploration-v3?node-id=341%3A3385
<img width="526" alt="image" src="https://user-images.githubusercontent.com/10508597/180324090-a1c4d3c5-3fd2-49cc-8d15-f93a3138bcf4.png">

**Comment by georgewrmarshall** [comment]
No longer on the design system component roadmap
