### ISSUE TITLE
Internal JSON-RPC error on IOS Metamask App Token transactions

### ISSUE THREAD

**Issue by shivam-ln** [MetaMask/metamask-mobile#4744]
Hi , we have our website in Next.JS framework. We are using metamask for connecting to binance. On our platform we are doing BNB and token transaction. In browser everything is working fine but getting error in mobile app mainnet. On test net everything is working fine.
Browser (Mainnet) : 
a) Token transaction : Working
b) BNB transaction   : Working
but when i am opening web app in metamask mobile app browser then only token transaction is throwing error Internal JSON-RPC error.
Metamask mobile App (Mainnet): 
a) Token transaction : Not Working
b) BNB transaction   : Working

i have tried on 2-3 iPhone same error . Device specification
Device : iPhone 11
Metamask : 5.2.0 (913)

Solution : 
i was trying to resolve this issue so i found that after changing some setting in mobile app. token transaction started working fine.
i have done the following : 
1) Open settings
2) Click on Advance
3) Enable custom transaction nonce.
 
 i dont know if it is right solution or not. If their is another way to resolve it kindly let me know

**Comment by tommasini** [comment]
Hey @shivam-ln, thanks for reporting! Could you send one record of this issue with the latest version of the app?

**Comment by tommasini** [comment]
Since we are not being able to reproduce this, please feel free to open a new issue or comment on this one with more information
