### ISSUE TITLE
Cannot find inpagebridgeweb3.js? 

### ISSUE THREAD

**Issue by RNHaoHao** [MetaMask/metamask-mobile#4746]
Cannot find inpagebridgeweb3.js? How to inject Web3?

**Comment by tommasini** [comment]
Hey @RNHaoHao , thanks to report, related to [this](https://github.com/MetaMask/metamask-mobile/issues/4232)

**Comment by tommasini** [comment]
Closing this issue, please if find something that could improve MetaMask, open a new issue! Thanks
