### ISSUE TITLE
Invalid amount on transaction confirm screen

### ISSUE THREAD

**Issue by tommasini** [MetaMask/metamask-mobile#4747]
**Describe the bug**
The balance of the wallet is 10 tokens but when requesting a transaction of one token we have the error invalid amount.

**Screenshots**
<img src="https://user-images.githubusercontent.com/46944231/181522046-61e5d01a-8cbf-496c-897b-a8fa009b945e.png" width="400"/> <img src="https://user-images.githubusercontent.com/46944231/181522068-138503b3-710e-434f-89a5-ad58e9aef78a.png" width="400"/>

**Comment by leon-do** [comment]
Here's more detail about the issue

https://www.youtube.com/watch?v=8uBnnnHM27s

https://github.com/leon-do/transfer-erc20-html

**Comment by leon-do** [comment]
Update: This was tested on Goerli and Rinkeby. Same bug.

**Comment by gantunesr** [comment]
Hi @leon-do, can you provide more information about this issue. I tried to reproduce it, but the Dapp in the video only performs actions in Mainnet, but the contract address is from Rinkeby or Goerli according to the Dapp.

![Screen Shot 2022-08-21 at 23 14 46](https://user-images.githubusercontent.com/17601467/185831565-ca37b6d0-4aa2-40ea-ac49-87a430aa4746.png)

Error while trying to mint on testnet,

```
changed
(
  event="changed",
  network={
    "name":"homestead",
    "chainId":1,
    "ensAddress":"0x00000000000C2E074eC69A0dFb2997BA6C7d2e1e"
  },
  detectedNetwork={
    "name":"rinkeby",
    "chainId":4,
    "ensAddress":"0x00000000000C2E074eC69A0dFb2997BA6C7d2e1e"
  },
  code=NETWORK_ERROR,
  version=providers/5.6.8)
```

**Comment by leon-do** [comment]
Hey,

I didn't write logic to switch to testnets. You'll have to manually switch and refresh.

![](https://user-images.githubusercontent.com/19412160/185969780-ac2fdc0c-9862-4c04-8c14-a296c9bd6407.png)

The believe the video is trying on Goerli. I don't have mainnet funds in these addresses.

In the video, you can see the network (goerli) towards the top of he screen. Below are the links.
Goerli on desktop browser: https://youtu.be/8uBnnnHM27s?t=70
Goerli on mobile: https://youtu.be/8uBnnnHM27s?t=153

**Comment by gantunesr** [comment]
Hey @leon-do, I took a look at the issue and we already have a PR (https://github.com/MetaMask/metamask-mobile/pull/4404) to fix it.

**Comment by bschorchit** [comment]
Closing as the PR mentioned above has been merged.
