### ISSUE TITLE
'View in block explorer ' crashes app for Polygon.

### ISSUE THREAD

**Issue by einaralex** [MetaMask/metamask-mobile#4753]
**Describe the bug**
_A clear and concise description of what the bug is_

- App crashed when trying to view block explorer for a Polygon. Might effect other custom networks. With or without Block Explorer URL defined, it still crashes.

**Screenshots**
_If applicable, add screenshots or links to help explain your problem_
https://user-images.githubusercontent.com/2564144/181694325-34aaf6cf-e53b-468a-999d-afb6ac041ad1.MOV

![image](https://user-images.githubusercontent.com/2564144/181695997-a0f766db-a15a-4388-a302-0f9071565b75.png)

**To Reproduce**
_Steps to reproduce the behavior_

1. Be connected to Polygon.
2. Find any token in assets, click and view its details.
3. Press '...' in the upper right corner and choose 'View in block explorer'

**Expected behavior**
_A clear and concise description of what you expected to happen_
Show me error instead of crashing, should take me to the URL if defined.

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone11]
 - OS: [e.g. iOS15.5]
 - App Version [e.g. 5.4.0] - find version number in app from Settings > About MetaMask

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by gantunesr** [comment]
Hi @einaralex, thanks for reporting. There's already a [fix](https://github.com/MetaMask/metamask-mobile/pull/4780) dedicated to this issue

**Comment by cortisiko** [comment]
closing issue as it was fixed and merged in https://github.com/MetaMask/metamask-mobile/pull/4780
