### ISSUE TITLE
Large amount of WalletConnect sessions crashes application

### ISSUE THREAD

**Issue by wsf11** [MetaMask/metamask-mobile#4758]
**Describe the bug**
A user has a large amount (multi-hundred / thousand) open WalletConnect Sessions their app. When they go to scroll the app, or long press to kill the WalletConnect session, the app crashes with no indication

**Screenshots**
_If applicable, add screenshots or links to help explain your problem_

**To Reproduce**
_Steps to reproduce the behavior_
1. Have a large amount of WC sessions
2. Go to Settings -> Experimental -> View Sessions
3. Scroll down the sessions or try to long press to end a session
4. App crashes & boots you

**Expected behavior**
You should be able to scroll down all your sessions and kill them without being kicked out of the app

**Smartphone (please complete the following information):**
 - Device: iPhone 12 Pro
 - OS: iOS 15.5
 - App Version 5.3.0(927)

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by RNHaoHao** [comment]
Cannot find inpagebridgeweb3.js? How to inject Web3?

**Comment by cortisiko** [comment]
This should be addressed on https://github.com/MetaMask/metamask-mobile/pull/4861
