### ISSUE TITLE
Attempting to reconnect WalletConnect older sessions

### ISSUE THREAD

**Issue by wsf11** [MetaMask/metamask-mobile#4759]
**Describe the bug**
Each time a WC session is initiated, the app tries to reconnect to existing (older sessions). If you have many sessions, this causes many connections to be made. This can cause DDos behavior towards Relay Servers or bad ux as there are many WebSocket connections attempting to be made at once

**Screenshots**
_If applicable, add screenshots or links to help explain your problem_

**To Reproduce**
_Steps to reproduce the behavior_
1. Connect to a DApp
2. Monitor your application traffic to see the WebSocket connections being made to old connections

**Expected behavior**
Old WC Connections should have a TTL or cleaned up after some time. 

**Smartphone (please complete the following information):**
 - Device: iPhone 12 Pro
 - OS: iOS 15.5
 - App Version 5.4.0

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by RNHaoHao** [comment]
Cannot find inpagebridgeweb3.js? How to inject Web3?

**Comment by wsf11** [comment]
I also am seeing multiple websocket connects for the same topic, with no websocket disconnects. Is this related?
