### ISSUE TITLE
Deeplink not working from metamask browser to an iOS app

### ISSUE THREAD

**Issue by Dipankershah** [MetaMask/metamask-mobile#4792]
**Describe the bug**
So I have a iOS app call "Gaggle" and i want to open my app using metamask browser. I also have a website call https://gaggle.art 
So what I want is, my app supports deeplink called "gaggle://home" and if I open this on iOS browser like safari then it will open up my app directly but it's not working on metamask browser.

**To Reproduce**
_Steps to reproduce the behavior_
1. Go to Metamask app
2. Click on 'Browser"
3. Type "gaggle://home" and enter
4. Make sure gaggle app is installed first.

**Expected behavior**
It should open gaggle app directly 

**Smartphone (please complete the following information):**
 - Device: iPhone X
 - OS: iOS 16 beta
 - App Version - Latest iOS app

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by cortisiko** [comment]
@Dipankershah Unfortunately at this moment in time we do not support URL schema deep links inside our apps.
