### ISSUE TITLE
core/WalletConnect.js didn't import URL package

### ISSUE THREAD

**Issue by kgcdream2019** [MetaMask/metamask-mobile#4796]
**Describe the bug**

  core/WalletConnect.js used URL but it didn't import this function from package
 You should add following codes in the top of this file
 
 import URL from 'url-parse';

**Comment by gantunesr** [comment]
Thanks for pointing that out @kgcdream2019! It's fixed in v5.6.1

**Comment by kgcdream2019** [comment]
That's great
