### ISSUE TITLE
Install to Onboarding app crashes on Android 12 devices

### ISSUE THREAD

**Issue by chrisleewilcox** [MetaMask/metamask-mobile#4802]
Experiencing app crashes on Android 12 devices after install up to completing Onboarding.  These crashes have been happening randomly but mostly occurring after install and up to completion of Onboarding.  Crashes are not persistent 
 and do not seem to recur after relaunching and continuing.  I would say majority of the time I am not able to get pass onboarding without the app crashing.

Device: Samsung Galaxy A42 Android 12
- New install (you can do this from the google play store)
- Open app immediately after install
- On the Welcome to MetaMask screen swipe left
-- this is when the crash occurs
-- https://recordit.co/PKDEDyJ7kA
--- I have experienced other crashes occurring at various points during Onboarding
- This is my device showing [crash](https://sentry.io/organizations/metamask/issues/2976276287/?project=2299799) on Sentry

UPDATE: Looking for this [PR](https://github.com/MetaMask/metamask-mobile/pull/4748) to be a potential fix

UPDATE: [PR](https://github.com/MetaMask/metamask-mobile/pull/4748) did not fix the app crash issue.

**Comment by gantunesr** [comment]
https://stackoverflow.com/questions/56734877/getting-library-libjsc-so-not-found-after-upgrading-react-native-to-0-60-rc2

**Comment by chrisleewilcox** [comment]
I am seeing more crashes related to this.  I installed 5.10.0 on browserstack device Samsung Galaxy S22 Ultra Android 12....
<img width="1391" alt="image" src="https://user-images.githubusercontent.com/6626407/200089317-c99de2c5-5319-49d9-bb7e-e75bfcb0d762.png">

**Comment by chrisleewilcox** [comment]
Issue has been resolved with the RN upgrade

**Comment by ValentinOsvaldo** [comment]
> Issue has been resolved with the RN upgrade

What is your RN version now?
