### ISSUE TITLE
react-native-webview注入web3对象 pancakeswap交互不了  有偿请教问题

### ISSUE THREAD

**Issue by RNHaoHao** [MetaMask/metamask-mobile#4803]
react-native-webview注入web3对象 pancakeswap交互不了  有偿请教问题  有偿请教问题  Paid questions
QQ: 137717070
邮箱：java_haohao@163.com
电报：@BlockChainHash

**Comment by gantunesr** [comment]
@RNHaoHao please open a new issue following our template. Thank you
