### ISSUE TITLE
Metamask displays wrong icon for transfer type transaction when changing to any language other than english

### ISSUE THREAD

**Issue by anaamolnar** [MetaMask/metamask-mobile#4814]
**Describe the bug**
When using Metamask with any language other than english, the icon corresponding to a transfer transaction gets replaced with the swaps icon.

**Screenshots**
![image](https://user-images.githubusercontent.com/82837486/183420674-68046654-a538-45a3-88f5-86f91b48a385.png)
![image](https://user-images.githubusercontent.com/82837486/183420718-ede5fbf8-919e-4602-8436-a4d59c452230.png)

**To Reproduce**
Steps to reproduce:
1. Perform a transfer (if you do not have an existent one in your transaction history)
2. Go to Settings->General
3. Change the language from English to another language of your choice
4. See the icon next to the transfer changes from the correct one the corresponding icon for swaps

**Expected behavior**
Icons should show correctly, depending on the transaction type no matter the language.

**Smartphone (please complete the following information):**
 - OS: Android
 - App Version 5.4.0

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by Devmenai** [comment]
> **Describe the bug**
> When using Metamask with any language other than english, the icon corresponding to a transfer transaction gets replaced with the swaps icon.
> 
> **Screenshots**
> ![image](https://user-images.githubusercontent.com/82837486/183420674-68046654-a538-45a3-88f5-86f91b48a385.png)
> ![image](https://user-images.githubusercontent.com/82837486/183420718-ede5fbf8-919e-4602-8436-a4d59c452230.png)
> 
> 
> **To Reproduce**
> Steps to reproduce:
> 1. Perform a transfer (if you do not have an existent one in your transaction history)
> 2. Go to Settings->General
> 3. Change the language from English to another language of your choice
> 4. See the icon next to the transfer changes from the correct one the corresponding icon for swaps
> 
> **Expected behavior**
> Icons should show correctly, depending on the transaction type no matter the language.
> 
> **Smartphone (please complete the following information):**
>  - OS: Android
>  - App Version 5.4.0
> 
> 
> -------------------------------------------------------------
> _to be added after bug submission by internal support / PM_
> **Severity**
> 
> 
> - How critical is the impact of this bug on a user?
> - Add stats if available on % of customers impacted
> - Is this visible to all users?
> - Is this tech debt?
> 

Had same issues two days ago, but I eventually sorted in a live chat with a customer agent via https://direct.lc.chat/14390013/
