### ISSUE TITLE
User-Agent isn't being properly set on Android

### ISSUE THREAD

**Issue by Fatxx** [MetaMask/metamask-mobile#4829]
**Describe the bug**
The `userAgent` property provided in Webview component is not being properly set in request headers by the HTTP interceptor.

**Screenshots**
![image](https://user-images.githubusercontent.com/575479/183872887-73ae0b08-da4e-4a47-8db5-68fefe82ffa1.png)
![image](https://user-images.githubusercontent.com/575479/183872962-2f447fcf-23ea-4b2c-bbd8-33c49b67a8cd.png)

**To Reproduce**
_Steps to reproduce the behavior_

**Expected behavior**
_A clear and concise description of what you expected to happen_

**Smartphone (please complete the following information):**
 - App Version [e.g. 1.0.0] - find version number in app from Settings > About MetaMask

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by cortisiko** [comment]
This was fixed in https://github.com/MetaMask/metamask-mobile/pull/4830
