### ISSUE TITLE
Perscriptive error message and link to settings when location is turned off

### ISSUE THREAD

**Issue by plasmacorral** [MetaMask/metamask-mobile#4847]
### **Description**

**Edited to change title and provide an update: This was an issue driven by location being turned off, even though permissions were granted.  A more prescriptive error message and link to device location settings would be helpful for users.**

https://recordit.co/8NTmIgKaZr

When I attempt to add a Ledger hardware wallet, I am getting an error that blocks my ability to add the Ledger address to MMM.  When I was first presented the location permission request, I tapped "Only this time".  However the issue that was preventing me from adding the Ledger was that location services, while granted permission, were not actually turned on.  We do not instruct the user to enable location services in this condition.

This was initially observed on the mobile client build 938
Pixel 3a
Android 12
May 2022 security update

March 2023 edited to add: Also observed on Samsung a515f running Android 12. See comment [here](https://github.com/MetaMask/metamask-mobile/issues/4847#issuecomment-1458236976).

### **Acceptance Criteria**

-   Need to be able to guide the user on what is blocking them from adding the Nano X address in MMM

### **Reproduction steps**

1. Import a secret recovery phrase by QR code
2. Land at wallet view and dismiss the welcome tour
3. Tap the account icon
4. Tap "Import account" to import a private key by QR
5. Tap the account icon
6. Enter pin on Ledger device and open Ethereum app
7. Tap "Connect hardware wallet"
8. Tap "Ledger"
9. When prompted for location permission grant "Only this time"
10. see error that fails to mention anything about Location services

### **References**

-   https://recordit.co/8NTmIgKaZr

**Comment by AlexJupiter** [comment]
This should be fixed in an upcoming PR due to changes in the controllers.

**Comment by plasmacorral** [comment]
A note to confirm, as expected, my Samsung device also behaves the same way.

**Comment by plasmacorral** [comment]
Still observing this issue with build 952 on Samsung A515f with Android 11.

**Comment by plasmacorral** [comment]
Just another update here: this appears regardless of whether I grant "Only this time" or "When using the App" level of location permission.

**Comment by plasmacorral** [comment]
While location permissions were granted, Location was not actually enabled on the mobile device.  My bad.  

In this specific circumstance, we could provide a more meaningful error message here that leads the user into Location settings to enable location on the mobile device.

**Comment by AlexJupiter** [comment]
In this scenario, I suggest that we use the same screen as we have in [3.2](https://www.figma.com/file/gw8z5Y9rT017ZKnc30M4dy/MetaMask-Mobile-ft-Ledger?node-id=575%3A3838) however change the text to "If you want to pair your Ledger device using you’ll need to first enable location access to your phone." Tapping "View Settings" could then send the user to that specific part of their Android settings to turn this setting on.
