### ISSUE TITLE
Rpc method wallet_scanQRCode crash the app when user cancel qrCode scan through close button

### ISSUE THREAD

**Issue by Nickrosendo** [MetaMask/metamask-mobile#4848]
**Describe the bug**
Using the [docs code example](https://docs.metamask.io/guide/rpc-api.html#mobile-specific-rpc-methods) for scanning qrcode causes the app to crash when the user cancel the scan through the close button, using the back button on android seems to be working.
Investigating through the code base i've managed to find a possible starting point that could be causing this bug [here](https://github.com/MetaMask/metamask-mobile/blob/main/app/components/Views/QRScanner/index.tsx#L93) or maybe [here](https://github.com/MetaMask/metamask-mobile/blob/main/app/core/RPCMethods/RPCMethodMiddleware.ts#L466)

**Screenshots**
I've setup an [example application](https://codesandbox.io/s/drwe85?file=/index.html) on codesandbox to reproduce the problem on mobile.

**To Reproduce**
_Steps to reproduce the behavior_
1. Install the metamask app on mobile.
2. Using the Browser view, visit the example link provided above.
3. Click on the "scan qrcode" button
4. Click on the close button on the scanning view
5. The app should crash.

**Expected behavior**
The app shouldn't crash when the user cancel the qrcode scan through the close button.

**Smartphone (please complete the following information):**
 - Device: [Samsung galaxy zflip 3]
 - OS: [Android 12]
 - App Version [v5.5.0 ( 939 ) ]

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by cortisiko** [comment]
Hey @Nickrosendo unfortunately our browser does not support this behavior. This is something we would consider for future enhancements. Thanks!
