### ISSUE TITLE
Issue with Django Project

### ISSUE THREAD

**Issue by eps-vishnu** [MetaMask/metamask-mobile#4849]
**Describe the bug**
each request is identified as new session in Django because cookies are not working properly.

**To Reproduce**
_Steps to reproduce the behavior_
Just Create a new Django project and try logging in 

**Expected behavior**
User should be signed in

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by gantunesr** [comment]
Hi @eps-vishnu, we're currently working on fixing the cookies issue. You can follow the progress in this PR https://github.com/MetaMask/metamask-mobile/pull/4407
