### ISSUE TITLE
Deeplinks/QR transfer scans no longer estimate the needed gas limit: "intrinsic gas too low"

### ISSUE THREAD

**Issue by PaulAtFlexa** [MetaMask/metamask-mobile#4853]
**Describe the bug**
Previously, when opening an ERC20 transfer deeplink the gas limit would be estimated, allowing users to "just click" send.  Now, when a user opens an ERC20 transfer, the gas limit is set to the default of 21000, which is far too low.  Thus, when clicking send, they get an "intrinsic gas too low" error, as metamask knows the tx would fail so does not send it (Thanks there :D ).  What should be happening is the gas is set to something like 75k depending on the complexity of a contract's transfer function.

I'm pretty familiar with the EIP-681 standard, so I took a stab at using the query params "gasLimit" and "gas" in the deeplink to at least fix this for my users temporarily.  Luckily for me, "gas" is accepted in the deeplink and QR scanning formats (though gasLimit is not, and per the 681 standard, should be).  But with this solution, users have to pay more gas than they need to up front since I had to set it to a high default.

The desired UX is that gas estimation is always done if gas or gasLimit is not specified in the link.  This currently works when you click send on a token, so the functionality exists already within the app.

**Screenshots**
![image](https://user-images.githubusercontent.com/93164809/184445352-bc2c286b-627d-48d7-90e3-3c1b5e5aaa04.png)

**To Reproduce**
_Steps to reproduce the behavior_
1. Create a deeplink for an ERC20 transfer https://metamask.github.io/metamask-deeplinks/#
2. Open it using a mobile device
3. Try to send the transaction without editing gas parameters
4. See it fail

**Expected behavior**
1. Open a deeplink for an ERC20 transfer
2. MetaMask looks up the token contract and estimates gas needed
3. User clicks send, it works as the gas was estimated correctly

**Smartphone (please complete the following information):**
 - Device: iPhone 13 Pro,
 - OS: 15.6
 - App Version v5.5.0 (939)

Same behavior reproduced on some of my colleagues phones as well, will update with their info if needed.

PS:

I work at https://flexa.network/ , we're a digital assets payments firm.  We'd love to establish closer relationships with wallet organizations like MetaMask.  You can reach me at paul@flexa.co !  We're building a way for wallet developers to embed a top notch payment experience within their app that's usable at tens of thousands of stores, as well as some of the biggest crypto conferences like Consensus.

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by juscamarena** [comment]
On Polygon sending erc20 tokens has this same issue with payment links / deeplinks. Transactions will fail as the gasLimit is not calculated correctly most of the time.

Here's an example: https://polygonscan.com/tx/0x4b0d4d1d0024ced477aeef1a4f72751951ece6c9fd2f538820d97f440ac7913b

**Comment by seaona** [comment]
@bschorchit I've added this into the next sprint as this issues is very annoying and makes it impossible to test the complete flow, without having to manually manipulate the gas. 
If there is no scope in the next sprint, feel free to move it to another one, just wanted to highlight the relevancy of the bug

**Comment by bschorchit** [comment]
I've added to above to our backlog for the next sprint

**Comment by segun** [comment]
I can repro this on prod MM but I can't test it on Simulator.

**Comment by bschorchit** [comment]
@segun is this a blocker? @seaona are you aware of any workaround for testing it on a simulator?
