### ISSUE TITLE
"send to" flow produces "No address has been set for this name." dialogue box pop up no matter what is entered

### ISSUE THREAD

**Issue by AlexHerman1** [MetaMask/metamask-mobile#4871]
**Describe the bug**
even if you enter the exact alias of a contact you have previously added, the "send to" flow will still produce this dialogue box, and in some cases the search won't return your contacts in the list either. On IOS I also produced an issue in this flow where the keyboard pops up by default, and thus wont let you scroll down your contacts list.

**Screenshots**
![e9a067bf-e6bf-4237-89f1-e68bef348716](https://user-images.githubusercontent.com/38788573/184954886-7fd013f0-c4bc-433f-9a8a-44d034924d44.jpeg)

![IMG_4876](https://user-images.githubusercontent.com/38788573/184956222-bb9320db-2610-4d55-ac92-a1f8c1260e6b.PNG)

**To Reproduce**
_Steps to reproduce the behavior_
1. Go to mobile send flow
2. Click into "to" box
3. See dialogue box
4. keyboard on iOS appears to auto launch and doesn't allow scrolling down in contacts

**Expected behavior**
This search should always return relevant/matching contacts, and shouldn't always show "no address has been set for this name" regardless of user input

**Smartphone (please complete the following information):**
 - Device: iPhone 13 pro, OnePlus 9 Pro (Android 11, Model: LE2120)
 - OS: iOS 15.6,  Build: Oxygen OS 11.2.2.2.LE15DA
 - App Version 5.5.0

**Comment by AlexHerman1** [comment]
this was reported in ZD # 931220

**Comment by rafae667** [comment]
I can still reproduce it

**Comment by psladonna** [comment]
I’m still not getting how to get rid of No address has been set for this name

**Comment by Bittuq** [comment]
> I’m still not getting how to get rid of No address has been set for this name

Yes me also
Please help
![Screenshot_2024-01-30-07-23-58-43_99c04817c0de5652397fc8b56c3b3817](https://github.com/MetaMask/metamask-mobile/assets/158118779/e486f5f2-cd0f-4d18-971e-403c3f696d00)

**Comment by rafae667** [comment]
This issue is closed. Is there a way to reopen it since the bug isn't fixed?

**Comment by fosterdonkor** [comment]
I can't send crypto from my wallet due "No address has been set for this name"
