### ISSUE TITLE
undefined is not an object (evaluating ‘o(this,t,“f”).keyrings[0].mnemonic’)

### ISSUE THREAD

**Issue by AlexHerman1** [MetaMask/metamask-mobile#4875]
**Describe the bug**
According to the user who reported this, this error was produced when using the browser in MM, switched to another app and when switched back, this error appeared.
The user did NOT back up the SRP

according to sentry we have 258 reports over the last 30 days, and it first appeared in 5.3.0

**Screenshots**
_If applicable, add screenshots or links to help explain your problem_

**To Reproduce**
See description above

**Expected behavior**
Be able to use MM normally without encountering this error code

**Smartphone (please complete the following information):**
 - Device: iPhone 11 Pro Max
 - OS: 14.4
 - App Version 5.5.0

**Comment by AlexHerman1** [comment]
ZD # 931410

**Comment by cortisiko** [comment]
relates to https://github.com/MetaMask/metamask-mobile/issues/4840
