### ISSUE TITLE
[FIX] Populate missing token symbol and address for Token Detection analytics

### ISSUE THREAD

**Issue by Cal-L** [MetaMask/metamask-mobile#4876]
### **Description**

Certain events in Token detection v2 seem to be missing fields and are undefined in Mixpanel.
`Token Added` event is missing an address in certain scenarios from `Custom token` source.
`Tokens Hidden` event is missing `token` list, which should include both symbol and address.

### **Technical Details**

- Don't send `Token Added` with empty fields
- Check why the `token` array isn't being received on Mixpanel

### **Acceptance Criteria**

- Token Added shouldn't be reporting to Mixpanel with empty fields
- Tokens Hidden event should include token symbol and address information

### **References**

- Reported in Slack by Gal and Barbara - https://consensys.slack.com/archives/G01FXS64DFA/p1660690019085629?thread_ts=1658874318.378669&cid=G01FXS64DFA

**Comment by cortisiko** [comment]
this was fixed in https://github.com/MetaMask/metamask-mobile/pull/4882. Closing issue
