### ISSUE TITLE
Metamask mobile Cant sync BNB amount to desktop extension[Bug]: 

### ISSUE THREAD

**Issue by alvinChristianto** [MetaMask/metamask-mobile#4887]
### Describe the bug

I cant see my BNB amount on metamask mobile. But when I try on chrome extension, it show the correct number

### Steps to reproduce

1. install metamask mobile from playstore
2. enter metamask with 12 seed phrase
3. add BNB smart chain network
4. BNB amount not show

### Version

10.18.0

### Browser

Chrome

### Operating system

Windows

**Comment by tommasini** [comment]
Thanks for report @alvinChristianto , I can see the BNB value of my wallet, can you send us more information?
We appreciate one recording if possible

**Comment by alvinChristianto** [comment]
Thanks for replying @tommasini . I just send some BNB to my metamask wallet. when I check my wallet in my laptop (windows) with chrome extension(10.18.3) it shows the correct number of BNB. 

then I login with metamask mobile (android 10, metamask 5.4.0) but no amount of BNB show (0 BNB).
Trying to find the answer, at first I though it because the data is not sync so I try to sync it with [this ](https://metamask.zendesk.com/hc/en-us/articles/360032378452-How-to-Sync-Mobile-with-MetaMask-Extension) way but it currently disable now

ps : I connect with mainnet and I check bscscan, my BNB on that address is valid (I have correct number)

**Comment by tommasini** [comment]
How are you connecting to BSC on MetaMask mobile app?
Please update as well your MetaMask mobile app

**Comment by alvinChristianto** [comment]
Im connecting with Binance Smart Chain like usual
![WhatsApp Image 2022-08-23 at 16 21 14](https://user-images.githubusercontent.com/39409708/186122246-839b1fd7-a2c8-4325-a773-858d7446c71e.jpeg)
![WhatsApp Image 2022-08-23 at 16 21 16](https://user-images.githubusercontent.com/39409708/186122262-6424f5ce-03fb-4bd3-8a7c-04807b0e9a3a.jpeg)

**Comment by gantunesr** [comment]
Hi @alvinChristianto, are you seeing this issue only on BSC or also with other chains like Mainnet and Polygon? Could you also verify if the balance of other tokens in BSC are being displayed correctly?

**Comment by gantunesr** [comment]
Hi @alvinChristianto, I'll close this issue since for the moment. Please open a new one if you're still facing problems with the app
