### ISSUE TITLE
Any Attempted Microphone Access via Mobile Browser on iOS causes a crash.

### ISSUE THREAD

**Issue by MeffJills** [MetaMask/metamask-mobile#4899]
Description: MetaMask Mobile does not have permission or an entry in the Privacy settings of iOS for access to the microphone.

MetaMask will crash when the in built browser makes any attempt to access the microphone, likely because of the missing permissions.

Steps to Reproduce:
Visit any microphone testing website in the MetaMask browser and try to test.

Note: After searching the Issues for similar bugs it seems this has been reported several times, as far back as 11 months ago, yet is still tagged as low severity, this bug is causing restrictions to dApp usage on mobile and really isn't that large of an issue to fix, as far as I'm aware it's merely an Info.plist entry.

**Comment by tommasini** [comment]
@MeffJills Thanks for reporting!
We have already planned to fix this issue, so I will close this one since it's related to https://github.com/MetaMask/metamask-mobile/issues/4593
