### ISSUE TITLE
[ENHANCEMENT] Browser error content/copy

### ISSUE THREAD

**Issue by gantunesr** [MetaMask/metamask-mobile#4909]
**Describe the usability problem**
_A clear and concise description of the specific usability issue_

The browser is displaying a confusing error which should be updated

**Screenshots**
![simulator_screenshot_377FFAC7-C06C-4C26-A0FF-EEDFAB28E575](https://user-images.githubusercontent.com/17601467/186739566-c95468e3-cb0b-4c56-80ae-ac4aae40028e.png)

**Expected behavior**
_If possible, a clear and concise description / resolution of what you expected to happen_
Enhance the error message

------------------------------------------------------------------------------------------------------
_filled out after submission_

**User impact | Usage frequency | Feasibility scores**
_How important is this to the user, what the user wants to accomplish | Daily, weekly, monthly | Small, medium, large_

**Comment by coreyjanssen** [comment]
**Headline**
Something went wrong

**Subhead**
A server with that hostname couldn't be found. 

**Button**
Return to home page

**Comment by gantunesr** [comment]
Hi @coreyjanssen, wdyt?

<img src="https://user-images.githubusercontent.com/17601467/188519289-517a9b6b-2464-4d2f-af68-08182b1824be.png" width="400" />

**Comment by coreyjanssen** [comment]
I think we can remove the line that begins with “reason…” since the line above addresses it. Thanks so much!

**Comment by gantunesr** [comment]
Aah no, I read it wrongly, sorry for that. The `Reason: ...` usually is a text provided by the website response. So it's not always the same.

**Comment by coreyjanssen** [comment]
Ohhhh ok! Now I get it! Thanks for clarifying :) 

Curious whether we're able to remove just the word `reason`? Assuming it's just the following text that we can't control...or is the whole line itself provided by the website response?

Either way, here's what I think will work best given that the website response text is variable: 

**Header:**
**Something went wrong**

**Subheader:**
We couldn't load that page. 

**Body:** 
A server with that specified hostname couldn't be found.

**Comment by coreyjanssen** [comment]
Looks great! Could we delete the period at the end of the subhead (We couldn't load that page)? My bad!

**Comment by gantunesr** [comment]
Sure!
