### ISSUE TITLE
Unacceptably low gas tx fails, but returns user to confirm screen with spinning wheel on CTA

### ISSUE THREAD

**Issue by plasmacorral** [MetaMask/metamask-mobile#4911]
### **Description**

While testing low gas transactions for cancellation/speed up, I submitted a transaction that was not accepted on the test network.  I was attempting to send .00000003 Rinkeby Eth, and had used the advanced settings to edit gas and submitted the tx with gas limit = 21000, Max priority fee of 0 gwei, and a Max fee of 0.000008581 gwei. 

iPhone 13 mini
Running iOS 15.6.1
MMM build 952
Ledger Nano X firmware 2.0.2

### **Reproduction steps**

1. Have MMM with Ledger paired
2. tap send from wallet view
3. select a destination address and tap next
4. enter amount and tap next
5. On the confirm screen tap the Estimated gas fee amount
6. Tap Low
7. Tap Save
8. Tap the Estimated gas fee amount again
9. Then tap "Advanced options"
10. Use the subtraction button to reduce "Max priority fee"
11. Use the subtraction button to reduce "Max fee"
12. Tap Save
13. Tap "Confirm with Ledger"
14. Review and then "Accept and Send" from Ledger
15. Note that user is returned to Confirm and has a spinning wheel on the CTA

### **Acceptance Criteria**

-   When a transaction fails, the user should not be returned to the confirmation view and shown a CTA with a spinning wheel.. Should confirm this, but they should probably be returned to wallet view, or activity view to see the failed tx.

Scenario: Failed transaction returns user to activity view
- GIVEN a user has submitted a failed transaction
- WHEN the transaction fails
- THEN the user should be returned to either the wallet view or maybe even the the activity view

### **References**

-   [https://recordit.co/FhXYyV7nL3

**Comment by plasmacorral** [comment]
possibly related to https://github.com/MetaMask/metamask-mobile/issues/4915

**Comment by montelaidev** [comment]
can't replicate on 3d046febb84beae20ad5dbd269486d413eebb835

**Comment by plasmacorral** [comment]
This is resolved.
