### ISSUE TITLE
Transaction canceled from MMM shows as "Approved" in activity view

### ISSUE THREAD

**Issue by plasmacorral** [MetaMask/metamask-mobile#4912]
### **Description**

If the user taps "Reject" after sending a tx to Ledger, it will show in activity as "Approved".  It should not show in this status as the tx was specifically NOT approved.  while I would prefer to see it labeled as "cancelled", it would be an improvement to show it as "failed" with red text, ~~similar to how we present the activity view if the tx is Rejected from the Ledger device.~~ Update: Another issue report shows that rejection from ledger doesnt always result in failed status.

iPhone 13 mini
Running iOS 15.6.1
MMM build 952
Ledger Nano X firmware 2.0.2

### **Reproduction steps**

1. Have MMM with Ledger paired
2. tap send from wallet view
3. select a destination address and tap next
4. enter amount and tap next
5. Tap "Confirm with Ledger"
6. Instead of approving on Ledger, tap "Reject" on MMM
7. From wallet view tap the asset
8. Note that the tx shows in the activity view as "Approved"

### **Acceptance Criteria**

-   A transaction that was not approved, should not be presented as approved.

Scenario: Rejecting a tx from MMM after sending it to Ledger
- GIVEN a user sends a tx to Ledger to confirm
- WHEN a user taps Reject in MMM
- THEN the transaction should not be shown as approved in activity view

### **References**

-   https://recordit.co/4kRMp3RO5J

**Comment by plasmacorral** [comment]
related to https://github.com/MetaMask/metamask-mobile/issues/4458

**Comment by montelaidev** [comment]
can't replicate on 83f7a77, rejected transactions now show up as failed.

**Comment by plasmacorral** [comment]
This is still an issue in commit ddf9f3347c3b2e887f9e465d36f93406e01c147c with Samsung a515f running android 11.

When I reject a transaction from MMM, it is displayed in activity detail as 'approved' and the 'Sign with Ledger CTA' is presented. 

https://recordit.co/3yojjLskxR

<img width="150" alt="Screenshot 2023-03-24 at 6 03 58 PM" src="https://user-images.githubusercontent.com/32695229/227652079-7d7e4e7e-2cc9-4475-9f03-89aebd04a33f.png">

**Comment by montelaidev** [comment]
applied fix on 831c80f935f6f3e10427d7d4ff2d1d82058b2f4f
