### ISSUE TITLE
After forgetting bluetooth pairing from Ledger there is no error about bluetooth connection when attempting to send

### ISSUE THREAD

**Issue by plasmacorral** [MetaMask/metamask-mobile#4919]
### **Description**

I forgot Bluetooth pairings from the Ledger device in this test.  In this case the user would also need to remove Ledger from MMM as well as forget the Bluetooth connection in the device settings.   When MMM is unable to connect via Bluetooth the Ledger device, there should be an informative and actionable error presented to the user.

Currently, after forgetting Bluetooth pairings and then attempting to send, the only indication of a problem is that the "Next" CTA from the AMOUNT entry is disabled.

iPhone 13 mini
Running iOS 15.6.1
MMM build 952
Ledger Nano X firmware 2.0.2

### **Reproduction steps**
1.  Have MMM with Ledger paired
2. unlock Ledger
3. Press both buttons to access Settings
4. select "Security"
5. Scroll down and select "Reset pairings"
6. Confirm with Ledger PIN
7. From MMM wallet view tap send
8. select a recipient address and tap next
9. Enter an amount, and notice that the "Next" CTA is disabled

### **Acceptance Criteria**

-   If the device was previously paired but is no longer found, an informative and actionable error is presented

Scenario: Reset pairings on Ledger and then try to send a tx
- GIVEN a user has Ledger Bluetooth paired with MMM
- WHEN a user resets pairings from the Ledger device
- AND a user attempts to conduct a transaction
- THEN an informative and actionable error should be presented to the user rather than just disabling the Next button

### **References**

-   https://recordit.co/sZ7aOO8eS3

**Comment by montelaidev** [comment]
on 3d046febb84beae20ad5dbd269486d413eebb835 it will now ask to re-pair the device.

**Comment by plasmacorral** [comment]
No longer an issue in commit ddf9f3347c3b2e887f9e465d36f93406e01c147c

I get the error that the device is disconnected, when I tap 'Try again' the pairing is initiated and I am able to complete a transaction.

https://recordit.co/OlviZJGyZb
<img width="150" alt="Screenshot 2023-03-24 at 6 57 27 PM" src="https://user-images.githubusercontent.com/32695229/227658190-d6968598-7c7c-4388-8b44-8b95728a33b3.png">
