### ISSUE TITLE
If user rejects Bluetooth permissions for MMM app, error brings them to Bluetooth settings rather than app settings

### ISSUE THREAD

**Issue by plasmacorral** [MetaMask/metamask-mobile#4920]
### **Description**

I started this test off by uninstalling the MMM application and forgetting the device from Settings>Bluetooth in iOS.  In the video at 14s, you can see that on first launch I decline the Bluetooth permissions request.  At 28s I see the error message and a CTA labled "View Settings".  That CTA brings the user to Settings>Bluetooth, where you can see the device has Bluetooth already turned on. In this scenario, the user could be directed instead to Settings>MetaMask to be able to provide the app Bluetooth permission.

iPhone 13 mini
Running iOS 15.6.1
MMM build 952
Ledger Nano X firmware 2.0.2

### **Reproduction steps**
Reproduction steps
1.  Ensure that Bluetooth device connection has been forgotten in the mobile OS settings
2. Get a fresh install of MMM
3. When Bluetooth permissions are requested, decline/reject
4. Configure MMM by importing an SRP
5. From wallet view tap the account icon
6. Tap "Connect hardware wallet"
7. Tap "Ledger"
8. Notice error
9. Tap CTA "View Settings"
10. Note that user is brought to bluetooth settings rather than app level permissions

### **Acceptance Criteria**

-   When Bluetooth is turned on, but MMM does not have Bluetooth permissions.  The error message and helper button should bring the user to app level permissions rather than Bluetooth settings.

Scenario: Bluetooth turned on but no permission
- GIVEN a user has Bluetooth turned on
- WHEN a user declines the Bluetooth permissions prompt
- AND a user attempts to pair a Ledger
- THEN an error should be presented
- AND the user should be helped into the app level settings to enable the permission

### **References**

-  https://recordit.co/aOAFgUeXoK

**Comment by plasmacorral** [comment]
Almost the opposite observed on Android 11.  When the user has Bluetooth disabled on the mobile device, the error message helper brings the user to app level permissions when system level bluetooth menu is what is needed.  

(ANDROID VIDEO PLACEHOLDER)

**Comment by plasmacorral** [comment]
Still valid- observed this on RC 7.17.0 on iOS 17.3.1 Iphone Xs

**Comment by plasmacorral** [comment]
[Comment](https://github.com/MetaMask/metamask-mobile/issues/4920#issuecomment-1244763857) made previously about android remains valid in Android 11, as observed in testing PR [8745](https://github.com/MetaMask/metamask-mobile/pull/8745)

**Comment by Akaryatrh** [comment]
@plasmacorral for iOS (iPhone 13 - iOS 17.4.1) on main branch, I was successfully redirected to MetaMask app permissions, may you test again? Thanks 🙂 

![image](https://github.com/MetaMask/metamask-mobile/assets/574787/b20f96f6-5669-4ceb-9cec-0e51f323df29)

**Comment by vivek-consensys** [comment]
Tested on iPhone 13 iOS 17.4.1 and working as expected:- 

[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMEtqQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ed829ee30e3761a503a65e85186e8833c70c41e7/RPReplay_Final1714471322.MP4)

**Comment by plasmacorral** [comment]
Reviewed QA build 7.22.0 build 1325 (RC3) for Android [here](https://app.bitrise.io/build/bda2c50b-0826-4de9-a9c3-32fb73a6b263?tab=artifacts) and iOS [here](https://app.bitrise.io/app/be69d4368ee7e86d/pipelines/c21205ff-f6d5-46f7-b68b-f66d3acdd039).

Devices tested:

LNX 2.2.3 with Eth App 1.10.4
Moto G Play (Android 11, security update Feb 1, 2023)
Pixel 5a (Android 14, security update Apr 5, 2024)
iPhone Xs (iOS 17.4.1)

The issue described in the ticket is resolved on the iOS device. On both Android 11 and 14, the settings helper directs users to the app settings (Settings>Apps>MetaMask) instead of directly to `Settings>Apps>MetaMask>Permissions>Location` for older devices or `Settings>Apps>MetaMask>Permissions>Nearby devices` for newer ones. This might be considered for an enhancement to improve user navigation/experience by taking them directly to where they need to make setting adjustment and will open a fresh enhancement request rather than a bug.

Recording:
[Android 11](https://www.loom.com/share/5bdea042cc914c0e8c811a72e2c7d126?sid=9f3607a1-e7e1-4782-befb-edd2215f3761)
