### ISSUE TITLE
Uniswap tx completed with error

### ISSUE THREAD

**Issue by plasmacorral** [MetaMask/metamask-mobile#4925]
### **Description**

I completed a mainnet swap on Uniswap for an ERC20 after receiving a few quotes and received the attached error, even though the transaction was successful.

iPhone 13 mini
Running iOS 15.6.1
MMM build 952
Ledger Nano X firmware 2.0.2

### **Reproduction steps**

All these steps may not be needed, but these are the steps taken in the attached video:
1. Have MMM with Ledger paired
2. unlock Ledger
3. Unlock MMM
4. Be on mainnet
5. From wallet view, tap QR scanner
6. Scan QR to Uniswap (below)
7. Connect wallet
8. Select assets and amounts to get a quote
9. Tap "Swap"
10. Tap "Confirm swap"
11. Tap "Reject" on Confirm
12. Go back to wallet view and jump around
13. Come back to browser
14. Edit amount to swap
15. Go back to wallet view
16. Come back to browser
17. Tap "Swap"
18. Tap "Confirm swap"
19. Tap "Reject" on Confirm
20. Edit amount to swap
21. Tap "Swap"
22. Tap "Confirm swap"
23. Tap "Confirm"
24. Open the Ethereum app
25. Note error about blind signing
26. Go to Ledger settings and enable Blind signing
27. Tap "Try again"
28. Open the Ethereum app
29. Review tx and "Accept and send" from Ledger
30. Note error even though tx succeeded (below)

### **Acceptance Criteria**

-   If swap transaction succeeds then no error messages are presented

Scenario: Uniswap on mainnet with Ledger and MMM
- GIVEN a user has a Ledger device paired with the MMM wallet
- WHEN a user goes to Uniswap.eth
- AND a user approves a swap that executes successfully
- THEN no error should be presented

### **References**

-   Recording: https://recordit.co/Dz2s8jdqBe
-  Successful transaction: https://etherscan.io/tx/0xc5deaedaaa693b3cf3708f7b2571561da0b1a595ff3533403f6cb60b81d21b55
-  Screenshot of error: 
      <img src="https://user-images.githubusercontent.com/32695229/187005300-6596e7a0-fbd5-4dde-879d-7abbb8de75ed.png" width="300"/>

-  Screenshot of QR:
      <img src="https://user-images.githubusercontent.com/32695229/187005219-47328063-f613-474d-8950-a81ecdd690a0.png"  width="300"/>

**Comment by montelaidev** [comment]
the dns for uniswap.eth doesn't resolve
