### ISSUE TITLE
navigator.share on Android doesn't work

### ISSUE THREAD

**Issue by SpasiboKojima** [MetaMask/metamask-mobile#4929]
**Describe the bug**
I have a simple call in my React app:
```
    if (navigator.share) {
      try {
        await navigator.share({
           url: `${window?.location.origin}/something`,
           title: 'Title',
        })
      } catch (error) {}
    } else {
      setIsShareOpen(true);
    }
```
Which works everywhere on iOS and only in plain browsers on Android and does nothing inside MM browser there.

**Screenshots**
_If applicable, add screenshots or links to help explain your problem_

**To Reproduce**
1. Setup a button in React that would call navigator.share if it exists
2. Open the page in Metamask browser on Android
3. See the native sharing popup not opening.

**Expected behavior**
A native sharing popup to open like it does in other Android browsers and on iOS Metamask browser.

**Smartphone (please complete the following information):**
 - OS: Android
 - App Version 5.6.0

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

**Comment by cortisiko** [comment]
Hey @SpasiboKojima thanks for reporting the issue. Unfortunately Android web view does not support this issue, See [here](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/share#browser_compatibility). I will go ahead and close this ticket!

**Comment by Kebechet** [comment]
https://issues.chromium.org/issues/40540400
