### ISSUE TITLE
invalidate amount 

### ISSUE THREAD

**Issue by leilu000** [MetaMask/metamask-mobile#4931]
Start the transaction page, prompting to invalidate amount  

![微信图片_20220830181549](https://user-images.githubusercontent.com/15362883/187412111-80a63417-77aa-4bd9-b6b3-a476dc0837b1.jpg)

**Comment by tommasini** [comment]
@leilu000 , thanks for reporting, we are already workig on one solution for this, it will be release on a near future!

**Comment by tommasini** [comment]
Closing this, related [to](https://github.com/MetaMask/metamask-mobile/issues/3999)

@leilu000 Feel free to comment here or open a new issue if there is any more value you can add to this issue.
