### ISSUE TITLE
Metamask deeplink issue - not open Dapp url

### ISSUE THREAD

**Issue by terry-sixsheet** [MetaMask/metamask-mobile#4935]
Hi Guys

     I facing the deeplink problem on Metamask as recommended on this link 

https://metamask.github.io/metamask-deeplinks/#

sample - https://metamask.app.link/dapp/app.jnft.digital

Detailes Issue
-----------------------
1 - on Andriod, it open Metamask but not open to DApp URL
2 - on Apple, it go to Apple store not the MM app

I did search on this some said it fixed, but seem like it not to me.

Can anyone help or suggest, thank you in advance

**Comment by andreahaku** [comment]
@terry-sixsheet which version of the app are you using? How are you opening the deeplink? From where? They are not supposed to be opened from the in-app browser but only from external browsers/applications. Thanks

**Comment by spectrl** [comment]
I'm still having the same issue on Android version 9.

Opening (launching an Intent) with `https://metamask.app.link/dapp/opensea.io/assets/ethereum/0x543d43f390b7d681513045e8a85707438c463d80/11989` only opens the MetaMask app, and does not open the MetaMask browser. 

Is there a way to open that url in the metamask browser via an intent?

**Comment by andreahaku** [comment]
> I'm still having the same issue on Android version 9 as well.
> 
> Opening (launching an Intent) with `https://metamask.app.link/dapp/opensea.io/assets/ethereum/0x543d43f390b7d681513045e8a85707438c463d80/11989` from within my app only opens the MetaMask app, but does not open the MetaMask browser.
> 
> Is there a way to open that url in the metamask browser via an intent?
> 
>  device-2022-09-06-131433.mp4

did you try `dapp://opensea.io/assets/ethereum/0x543d43f390b7d681513045e8a85707438c463d80/11989`?

**Comment by terry-sixsheet** [comment]
> Have you tried reinstalling metamask, fixed the issue for me.
> 
> 1. **Make sure to backup your private key**
> 2. Clear the cache and app data
> 3. Uninstall MM
> 4. Reinstall MM

I tried, but unfortunately, it still not working thx for suggest

**Comment by terry-sixsheet** [comment]
> @terry-sixsheet which version of the app are you using? How are you opening the deeplink? From where? They are not supposed to be opened from the in-app browser but only from external browsers/applications. Thanks

I'm using Memamask v5.6.0 (950) Andriod 11, and I open from Chrome Browser on Mobile. 

Not sure anyone have this issue on Andriod or just me? I tried with other andriod, it result the same.

Thank you for reply

**Comment by terry-sixsheet** [comment]
> I'm still having the same issue on Android version 9 as well.
> 
> Opening (launching an Intent) with `https://metamask.app.link/dapp/opensea.io/assets/ethereum/0x543d43f390b7d681513045e8a85707438c463d80/11989` from within my app only opens the MetaMask app, but does not open the MetaMask browser.
> 
> Is there a way to open that url in the metamask browser via an intent?
> 
>  device-2022-09-06-131433.mp4

this is exactly what i facing :(

**Comment by terry-sixsheet** [comment]
> > @terry-sixsheet which version of the app are you using? How are you opening the deeplink? From where? They are not supposed to be opened from the in-app browser but only from external browsers/applications. Thanks
> 
> I'm using Memamask v5.6.0 (950) Andriod 11, and I open from Chrome Browser on Mobile.
> 
> Not sure anyone have this issue on Andriod or just me? I tried with other andriod, it result the same.
> 
> Thank you for reply

Same Thing happened to me, still not fixed

**Comment by terry-sixsheet** [comment]
any news for this issue will be open for fixing guys!?

**Comment by grp06** [comment]
Also having this issue

**Comment by gantunesr** [comment]
Hey, thanks for reporting this issue! We're working on some improvements regarding deeplinks, our team will update this issue properly. Thank you for your patience and cooperation! And please share any relevant information that can be useful in the comments.

**Comment by chrisleewilcox** [comment]
@andreahaku is reviewing this issue.

**Comment by qieman** [comment]
It took a long time, any news for this issue ?

**Comment by sawproduction** [comment]
same after a year
