### ISSUE TITLE
Xcode 13.4.1 Failed Build(s)

### ISSUE THREAD

**Issue by millerc13** [MetaMask/metamask-mobile#4936]
### **Description**
What version of Xcode are you guys using to build this? I have been trying to get this app to build for 4 days on Xcode 13.4.1 with absolutely 0 luck. 

Can anyone here verify that Xcode's version is not the issue?

**Comment by gantunesr** [comment]
Hi @millerc13, I also use 13.4.1 to build on my iOS mobile device and it works properly. Which issue are you seeing in your end?

**Comment by millerc13** [comment]
@gantunesr I think it may have been some weird issue from me doing some sudo gem installs and not fully know what I was doing. To be to be honest I have no idea what the issue was, but the fault was 100% on my end.

My solution **(which was not a good solution)**: Back up my files and reinstall macos, redownload Xcode and install all a fresh copy of node, react-native, and all the other dependencies and it worked flawless first run.

I have it up and running now and added my own infura keys and such. I'll close this ticket but wanted to ask another question.

The dApp I'm working on when built on my **physical ios device** can sign in and connect with by opening the metamask app and signing.  Then proceeds to show the wallets nfts, balances, etc _(using @walletconnect/web3-provider package)_ .  Should that same functionality work out the gate when building on a simulator? I hit connect with metamask on the simulator and it opens metamask but does not ask for any signing/authentication.

I do receive some of the following messages in console though:

`
2022-09-04 21:26:03.732628-0400 MetaMask[10325:65981] [branch.io] Branch.m(336) Error: Branch init error: The Branch user session has not been initialized.

2022-09-04 21:26:03.732769-0400 MetaMask[10325:65981] [branch.io] Branch.m(408) Error: Your Branch key is not set in your Info.plist file.

2022-09-04 21:26:03.921304-0400 MetaMask[10325:65982] [branch.io] BNCServerInterface.m(237) Error: An error prevented request to https://api2.branch.io/v1/install from completing: Error Domain=io.branch.sdk.error Code=1003 "The network request was invalid." UserInfo={NSLocalizedDescription=The network request was invalid., NSLocalizedFailureReason=The request was invalid.}
`
I'm guessing that the connect auth to another dApp isn't something that will work out of the box upon build. Any guidance would be appreciated! New to dApp development- just graduated from college and wanted to start to learn the basics in my free time.

**Comment by gantunesr** [comment]
Based on the logs it looks like you need to add a development Branch key @millerc13. You have to add it to the root files `.ios.env` and `.android.env` as,

```
MM_BRANCH_KEY_TEST=...
```
