### ISSUE TITLE
Android app shows "Install MetaMask for Android"  when trying to connect

### ISSUE THREAD

**Issue by stefan-girlich** [MetaMask/metamask-mobile#4956]
**Describe the bug**
I want to connect my wallet to a dApp on Android, but the MetaMask app shows me a "Install MetaMask for Android" web page.

**Screenshots**
![Screenshot_20220908-133810](https://user-images.githubusercontent.com/1755315/189116917-3734b233-025c-40f1-8c84-0f7aaf3bd5d8.png)

**To Reproduce**
1. Open [opensea.io](https://opensea.io/) in Chrome
2. Open mobile navigation, click _Connect wallet_
3. Android OS overlay shows different wallet apps; select MetaMask option
4. Select "MetaMask" option from overlay
5. [metamask.io/download.html](https://metamask.io/download/) briefly opens in browser, then opens MetaMask app
6. MetaMask opens [metamask.io/download.html](https://metamask.io/download/) in in-app browser

**Expected behavior**
MetaMask asks if I want to connect to dApp

**Smartphone (please complete the following information):**
 - Device: LG G7
 - OS: Android 10
 - App Version: v5.6.0 (950)

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by tommasini** [comment]
Hello @stefan-girlich, to connect to open sea via on chrome browser (not our in-app browser), you need to connect via wallet connect.
If you want you can use our in-app browser and connect via MetaMask.

This is our option for now. let me know if this worked for you.
