### ISSUE TITLE
Metamask mobile. Incorrect error handling using eth_sendRawTransaction method.

### ISSUE THREAD

**Issue by darksyd94** [MetaMask/metamask-mobile#4959]
**Describe the bug**
We have developed an interface imitating ethereum JSON RPC interface to integrate our blockchain with metamask desktop and mobile application. We developed eth_sendRawTransaction method that returns an error instead of transaction hash when a transaction is rejected in our blockchain for some reason. After receiving that error Provider uses an error code -32603 'Internal JSON-RPC error.' 
`{"code":-32603,"message":"[ethjs-query] while formatting outputs from RPC '{\"error\":306,\"message\":\"Error while executing account-script: FailedTransactionError(code = 1, error = AccountBalanceError(Map(3FY1GwbNSZyLKCVpwTkjnta2vgw676zn3gW -> negative waves balance: 3FY1GwbNSZyLKCVpwTkjnta2vgw676zn3gW, old: 999700000, new: -98900300000)), log =)\",\"transaction\":{\"type\":18,\"id\":\"EDKmKLayaBXorJJ1v9LUK65Hn5Pq1kyfbpMm12mFSeJJ\",\"fee\":500000,\"feeAssetId\":null,\"timestamp\":1662639042356,\"version\":1,\"chainId\":68,\"bytes\":\"0xf8b18601831d026f348502540be4008307a120947d1a54f985831a37bf2034e525a671cde171048380b84421d4a0390000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000000081aba010b91146f64fddc5e12b026890def83baf43a5b139d8a160dd97605a5a911964a018a8ed2f1238c2a3413abe8dafaa0561305f1ed91fec6e98912e6a69d8609200\",\"sender\":\"3Fbo3zW4F1MeZvbw54TGAkstzk4Kzrkm3Sh\",\"senderPublicKey\":\"3T9fL3XpeaHYbumohePPUmeuUqhyEeyzifi9vKouV8QoNtAT6kYV1oPAe9e2KCVquPcyXJpr2QwUiQKEUQPGZnc6\"}}' for method 'sendRawTransaction' Error: [ethjs-format] hex string '[object Object]' must be an alphanumeric 66 utf8 byte hex (chars: a-fA-F) string, is 0 bytes","stack":"{\n  \"code\": -32603,\n  \"message\": \"[ethjs-query] while formatting outputs from RPC '{\\\"error\\\":306,\\\"message\\\":\\\"Error while executing account-script: FailedTransactionError(code = 1, error = AccountBalanceError(Map(3FY1GwbNSZyLKCVpwTkjnta2vgw676zn3gW -> negative waves balance: 3FY1GwbNSZyLKCVpwTkjnta2vgw676zn3gW, old: 999700000, new: -98900300000)), ...`

Upon receiving that error metamask mobile starts permanently sending eth_getTransactionByHash requests with null hash params.
`{
  "id": 2145909897078296,
  "jsonrpc": "2.0",
  "method": "eth_getTransactionByHash",
  "params": [
    {}
  ]
}`

Here’s the screenshot of that transaction that was made in Android Metamask application via internal browser.
![image](https://user-images.githubusercontent.com/18382817/189151043-4ed01a8d-e360-4a0b-b357-0bd08235c82f.png)

In desktop Metamask extension problem doesn't reproduce - that transactions is tagged 'Failed' instead of 'Submitted', error is displayed correctly.

**Expected behavior**
After eth_sendRawTransaction method receives a response without transaction hash, mobile application doesn't start a loop of eth_getTransactionByHash requests with null hash params. Transaction in the transactions list is displayed as _Failed_.

**Smartphone:**
 - Xiaomi MI A1
 - Android 9
 - v5.6.0 (950)

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by tommasini** [comment]
Hey @darksyd94, thanks for reporting!
It would be helpful for us if you could give us an example of how to reproduce it so we can test it easily

**Comment by darksyd94** [comment]
Hello!  I give you a instruction how to reproduce it:

1. Login in Metamask account in Metamask Mobile.
2. Choose browser in Menu.
3. Go to next link in Metamask Browser: https://metamask.wvservices.com/metamask/. 
4. Push Gear Button and choose testnet. 
![image](https://user-images.githubusercontent.com/18382817/193287636-a92049ee-7204-41eb-8f92-5722e303a507.png)
5. Reload the Page.

6. Choose "Login via Metamask"
![image](https://user-images.githubusercontent.com/18382817/193287696-f66632b4-6981-40f9-b8a3-f3502e1fbd51.png)

7. Accept Allowance to add a network.
![image](https://user-images.githubusercontent.com/18382817/193287742-7a568a93-8ab3-4659-a0f7-94f5bd46109f.png)

8. In list of actions choose Invoke Script
![image](https://user-images.githubusercontent.com/18382817/193287784-6233a713-4d91-4006-b243-b338397e6472.png)

9. Use Transaction data below:
![image](https://user-images.githubusercontent.com/18382817/193287927-48c4e7b2-8472-4ae8-a485-971e7924cbed.png)

`
{
"dApp":"3MtEFgs9JgvadLTPHxmNTLoYdWeb2q6S8NB",
"call":{
"function":"fail",
"args":[]
}
}
`
10. Push Broadcast button.

11. Confirm Transaction.
![image](https://user-images.githubusercontent.com/18382817/193289283-1e793897-b2f3-4c14-beb8-94e76240ee36.png)

12. Look on Error.
![image](https://user-images.githubusercontent.com/18382817/193289320-eda0e7bf-6375-4748-815a-ab1f177a94ef.png)
13. Look on transaction in history:
![image](https://user-images.githubusercontent.com/18382817/193289431-68d19c82-0ac7-4745-8636-70368b0699bd.png)


Device - Samsung Galaxy S22 Ultra.

**Comment by cortisiko** [comment]
hey @darksyd94 I am unable to connect my metamask mobile app to your test dapp see screen shot
![image](https://user-images.githubusercontent.com/12821081/195159578-020fd952-c063-42f6-be62-a1a1ba311e64.png)

can you assist ?

**Comment by darksyd94** [comment]
Hey @cortisiko! We made an [issue](https://github.com/MetaMask/eth-phishing-detect/issues/7900) some time ago, to make our dApp trusted, unfortunately this issue still open by now time. 

Our another dApp: https://signer-sandbox.waves.tech/. Instruction the same, but before you should use a seed phrase in import an Account menu. Seed on spoiler below.
<details>
  <summary>seed</summary>
slender test hungry field dinosaur special dash dish accuse crack paddle fashion
</details>

**Comment by cortisiko** [comment]
thank you @darksyd94 for sharing. I will pass this onto the rest of the team!
