### ISSUE TITLE
Account disappears after closing mobile app and relaunching

### ISSUE THREAD

**Issue by plasmacorral** [MetaMask/metamask-mobile#4971]
### **Description**

I can consistently reproduce this with build 952.

Observed on both:
Samsung A515f with Android 11
iPhone 13 mini with iOS 15.6.1

After pairing Ledger with MetaMask mobile, and closing the mobile app.  Upon relaunch of the mobile app the Ledger account is missing.  This only occurs after the first pairing.  If I subsequently re-add the Ledger device and close the app, the Ledger 1 account persists. 

### **Reproduction steps:**
1. Fresh install of build 952
2. Open MMM and agree to Bluetooth permission (iOS)
3. Import SRP via QR code
4. Do not enable biometrics if present
5. Close the welcome message
6. From wallet view tap account icon and select "Connect Hardware Wallet"
7. Tap "Ledger"
8. Have Nano X unlocked with the Ethereum app present
9. Tap "Continue"
10. Return to wallet view and note that "Ledger 1" account is shown
11. Swipe up and close app from app tray
12. Relaunch app
13. Authenticate with password and tap "Unlock"
14.  From wallet view tap account icon and note that "Ledger 1" is no longer present in the account list

 

### **Acceptance Criteria**

-   After pairing and then closing the app, the Ledger 1 account should persist in the account list.

Scenario: Does get lost
- GIVEN a user completes pairing of Ledger Nano X with MetaMask mobile
- WHEN a user closes the mobile app from the app tray
- AND a user relaunches the mobile app
- THEN the Ledger 1 account should persist in the account list

### **References**

-   iOS video: https://recordit.co/rudIOxm14w
-   Android video (includes a send tx on testnet before closing app) https://recordit.co/xupAR85Jig

**Comment by AlexJupiter** [comment]
Zoltan cannot reproduce this right now, we need to try and reproduce this on the MetaMask side.

**Comment by AlexJupiter** [comment]
@gantunesr and @owencraston to have a look at this when they have time.

**Comment by owencraston** [comment]
I was **not** able to reproduce on my iPhone 12 running ios 16.0

**Comment by montelaidev** [comment]
can't reproduce on 83f7a77

**Comment by plasmacorral** [comment]
Confirmed resolved in commit ddf9f3347c3b2e887f9e465d36f93406e01c147c  
https://recordit.co/lH34oMzaxS
