### ISSUE TITLE
CSRF Token issue

### ISSUE THREAD

**Issue by merchant862** [MetaMask/metamask-mobile#4979]
Whenever I try to sign in or sign up in my web app using email and password on a metamask browser it says invalid CSRF token, however, my web app works perfectly on other browsers.

HTML code looks like this:

![Screenshot from 2022-09-13 18-47-30](https://user-images.githubusercontent.com/43372874/189920140-76de06ad-ab60-4a42-b8e9-8ea0c4d32621.png)

What could be the possible issue?

**Comment by tommasini** [comment]
@merchant862 Thanks for reporting! Can you tell us which device you are using? Also, it would be great if you could share an online website example so we try to replicate it easily.

**Comment by merchant862** [comment]
@tommasini on every mobile device in the metamask browser it is getting this issue, on a laptop or PC it's working perfectly, I think this is the issue with the metamask mobile browser, especially with the cookies, as I have signed an NDA with the company so can't reveal the website, thanks for the reply.

**Comment by tommasini** [comment]
@merchant862 We have already a solution for cookies on this [PR](https://github.com/MetaMask/metamask-mobile/pull/4407)
When we release this PR I will comment here, and if you can test your case and see if it solves we would appreciate it

**Comment by merchant862** [comment]
@tommasini unfortunately that PR didn't work,

**Comment by carlosbalsas** [comment]
Same issue here
