### ISSUE TITLE
When attempting to speed up/cancel transaction the Ledger confirm modal is not shown

### ISSUE THREAD

**Issue by plasmacorral** [MetaMask/metamask-mobile#4990]
### **Description**

Observed on Android 11, 12 and iOS 15.6.1

When attempting to speed up a transaction, the "Submit" CTA remains available to be tapped repeatedly because the Ledger confirmation modal is not being opened.  If the CTA is engaged more than once, an error is presented even if the speed up attempt has yet to fail.  

This also occurs when trying to Cancel a transaction.

### **Reproduction steps:**
1. Have Ledger paired with configured MMM
2. Be on a testnet and have assets available to send
3. From the wallet view select a recipient address tap next
4. select amount tap next
5. From confirm screen tap on estimated gas
6. Tap 'LOW' or used advanced settings to adjust super low
7. Tap Save
8. Tap "Confirm with Ledger"
9. Review transaction on Ledger and tap both buttons to "accept and send"
10. Once returned to wallet view, tap the asset to enter activity view (or can tap transaction in question to enter activity detail)
11. Tap "Speed up" from either activity view or activity detail
12. Tap Submit with "Market" default selected or chose 
13. Note that CTA is remains enabled and modal is not presented

### **Technical Details**

-  Speed up and Cancel "Submit" should open Ledger confirmation modal whether the Speed up/ cancel CTA is accessed from Activity view or Activity detail

### **Acceptance Criteria**

Scenario: Speed up/cancel 
- GIVEN a user is attempting to speed up/cancel  a transaction
- WHEN a user taps the "Submit" CTA
- THEN the Ledger modal should open over top of the Submit CTA
- AND the Submit CTA cannot be tapped multiple times

### **References**

-  Cancel: https://recordit.co/hhKYWKGubT
-  Speed up: https://recordit.co/uroPs0M2Xy
-  Tapping "Submit" CTA repeatedly and producing error: https://recordit.co/90JHHpYFiZ

**Comment by montelaidev** [comment]
applied a fix on 83f7a77d793ed6567a2a494ba3c90755e2d8b32b

**Comment by plasmacorral** [comment]
Can confirm in commit ddf9f3347c3b2e887f9e465d36f93406e01c147c using Samsung a515f that Ledger modals are present on speed up and cancel, both through activity view as well as activity detail.
