### ISSUE TITLE
Hardware label in drawer is white text on white background in light mode

### ISSUE THREAD

**Issue by plasmacorral** [MetaMask/metamask-mobile#5000]
### **Description**

New ticket created for the single remaining item from https://github.com/MetaMask/metamask-mobile/issues/4594

The hardware label in the drawer is white text on white background in light mode.

### **References*
![Screen Shot 2022-09-15 at 7 09 28 PM](https://user-images.githubusercontent.com/32695229/190657678-8fe4cfd6-394d-4f8a-b8c2-7db3d4b2213a.png)

**Comment by plasmacorral** [comment]
Also showing black text in dark mode on iOS 16
<img width="143" alt="Screen Shot 2022-09-20 at 1 25 51 PM" src="https://user-images.githubusercontent.com/32695229/191324545-82501aff-9507-47b2-943c-f0b3a1993bf3.png">

**Comment by montelaidev** [comment]
not able to reproduce on 1d556e9

**Comment by plasmacorral** [comment]
This is resolved
