### ISSUE TITLE
CSRF token is not accepted on metamask mobile app browser

### ISSUE THREAD

**Issue by uraxlizard** [MetaMask/metamask-mobile#5014]
**Description**
Ajax post request is returning 'Page Expired' when you try to use metmask mobile app browser on Android. On iOS is working. A registration/login flow was created with web3 auth. It was used csrf in order to protect requests, but metmask browser is not accepting them.

**To Reproduce**
Try to make post request with csrf(cors). Bare in mind that this problem occurs only on android devices.

**Expected behavior**
It is expected to be able to capture CSRF and complete the request as expected.

**Smartphone:**
 - Device: Samsung Galaxy S22 Ultra
 - OS: Android 12
 - App Version v5.6.1(967)

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- This is a major critical bug as, metamask auth can not be integrated for android users via web3

**Comment by tommasini** [comment]
Probably related to https://github.com/MetaMask/metamask-mobile/issues/4979

**Comment by cortisiko** [comment]
Thanks for reporting @uraxlizard! can you try to reproduce on v5.8 or v5.9?

**Comment by chrisleewilcox** [comment]
@omnat need product review.
