### ISSUE TITLE
How to generate deeplink of metamask wallet connect

### ISSUE THREAD

**Issue by KrishEnacton** [MetaMask/metamask-mobile#5078]
I want to connect metamask wallet with my react native application, I have implemente Linking.openURL("https://metamask.app.link/wc") its only open metamask app but it didn’t show connect wallet popup on metamask app

Is there any standard schema for deeplink?

I have seached about some deeplink of wallet connect and I found some urls like 
"https://metamask.app.link/wc?uri=wc:733faea4-4488-412e-88f9-42e77c5f3fea@1?bridge=https%3A%2F%2Fh.bridge.walletconnect.org&key=c67b668f5cf5f37e3705a1fe50ed02c707e4fb0d4ead12a2db0db727ac96fb6c"

But is there any way to find out how to generate uri & key for metamask url?

Thanks in advance

**Comment by tommasini** [comment]
Hello @KrishEnacton, did you consider to use `@walletconnect/react-native-dapp`? Here is the documentation on how to do it https://docs.walletconnect.com/quick-start/dapps/react-native

Let me know if this helped
