### ISSUE TITLE
Multi-Network Controller Integration

### ISSUE THREAD

**Issue by sethkfman** [MetaMask/metamask-mobile#5092]
### Background
A new network controller has been updated to support multiple networks at the same time. This ticket is for integrating the new network controller. 

### Technical Requirements
- Follow the instructions in the breaking changes section of this [NetworkController PR](https://github.com/MetaMask/controllers/pull/903)

### Acceptance Criteria
- The app should handle networks just as before but using the new network controller

**Comment by sethkfman** [comment]
@jakehaugen Do you know if there is any design work related to the MVP integration of the Multi-Network Contoller?

**Comment by vandan** [comment]
My expectation was that this milestone wouldn't require any Mobile app design changes (just parity with existing functionality and with no significant regressions).
