### ISSUE TITLE
Double tapping the screen above the MetaMask request crashes the application.

### ISSUE THREAD

**Issue by rafal2228** [MetaMask/metamask-mobile#5106]
**Describe the bug**
During the connect wallet or switch network flow the MetaMask request is displayed on screen, when the user double taps the screen above the MetaMask request the application will terminate

**Screenshots**
https://user-images.githubusercontent.com/9198051/194281352-f4a52777-683c-4768-b2ae-717f269dd63d.MP4

**To Reproduce**
- Open any dApp that tries to connect MM wallet
- Request wallet connection
- On the connection screen double tap above the dialog
- The app crashes

**Expected behavior**
The app shouldn't crash instead, the request should be simply rejected

**Devices:**
  - iPad 10.2 2021 (9th Gen) (16).
  - iPhone 7 Plus (15.7).
  - iPhone 12 Pro Max (16.1 beta).
  - Google Pixel 6 (13).
  - Samsung Galaxy A50 (11).
  - Samsung Galaxy Tab S4 10.5 (10).
 - OS: Android & iOS (versions next to the devices)
 - App Version - 5.7.0

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by gantunesr** [comment]
Thanks for reporting this issue @rafal2228, I'm going to bring this to our team

**Comment by rafal2228** [comment]
The issue no longer occurs - tested on v5.11.0. Probably fixed by https://github.com/MetaMask/metamask-mobile/pull/5119
