### ISSUE TITLE
[IPhone] 5.8.0 does not connecting to WalletConnect via Deep\Universal links

### ISSUE THREAD

**Issue by Foprta** [MetaMask/metamask-mobile#5111]
**Describe the bug**
_MetaMask 5.8.0_ on _IPhone_ does not connecting to _WalletConnect_ via deeplinks. It worked on _5.7.0_.
Universal links leads to _AppStore_, and if you open _MetaMask_ from there - nothing happens.
Deeplinks leads to _MetaMask_ and nothing happens.

**To Reproduce**
_Steps to reproduce the behavior_
1. Go to https://app.1inch.io/#/1/unified/swap/ETH/DAI
2. Click on "Connect Wallet"
3. Accept Terms
4. Select _Ethereum_
5. Select _WalletConnect_
6. Press "Connect" button in _WalletConnect_ modal

**Expected behavior**
Should show prompt with "connect" button.

**Smartphone (please complete the following information):**
 - Device: IPhone 12 Pro
 - OS: 16.0
 - App Version: 5.8.0

**Comment by tommasini** [comment]
Thank you for reporting @Foprta, we are not being able to reproduce it.
Could you provide a video?
Also, can you clean your browsing data, the browser that you used to open MetaMask app

**Comment by Foprta** [comment]
Reinstalling MM helped.
