### ISSUE TITLE
[Android Specific] The network picker on the wallet view does not update correctly when you are on a custom network then you delete that network

### ISSUE THREAD

**Issue by cortisiko** [MetaMask/metamask-mobile#5117]
If I were to:

- manually add a custom network via the custom network flow
- while on the custom network, delete it.
- Notice the network picker on the wallet still contains the custom network name

to reproduce:
- go to the networks view
- manually add xdai to your networks: `RPC URL`: https://rpc.gnosischain.com `ChainID`: 100 `Network Name`: xdai
- go back to the networks view
- remove xdai
- notice you are taken back to the wallet view and the network picker has xdai as the default network. 

see [recording](https://recordit.co/vhiJJcvaY4)

**Comment by olenapankina** [comment]
Issue fixed in https://github.com/MetaMask/metamask-mobile/pull/5219
