### ISSUE TITLE
ENS Resolved Incorrectly - Lost Funds on Transfer

### ISSUE THREAD

**Issue by pavlovcik** [MetaMask/metamask-mobile#5128]
# **Describe the bug**

I attempted to transfer funds from my gf wallet to mine (pavlovcik.eth) and when I entered pavlovcik.eth and clicked send right away it resolved to [0x000000000000000000000000000017f34c43bddb](https://etherscan.io/address/0x000000000000000000000000000017f34c43bddb) ?? 

Either it shouldn't resolve (so to 0x0) and ERC20 transfer would fail attempting to send to 0x0, or it should resolve to my wallet, as expected ([0x4007CE2083c7F3E18097aeB3A39bb8eC149a341d](https://etherscan.io/address/pavlovcik.eth))

I only realized after several minutes that I didn't receive the funds. I checked Etherscan of her wallet and tracked down the funds. Now I'm missing $672.61! 

Transactions:

- https://etherscan.io/tx/0x733a04e355b82d58d8e8bc6d1e8bd278c90c10de40567da70d82219b45846ed6
- https://etherscan.io/tx/0x7f10a69d10c35044a934f0f12aa941ecd172ca5e07e095738a872706f0bdd705

I'm livid because I've been using MetaMask since 2016 and ENS since 2017 never had anything like this happen to me. I need to be reimbursed for these. 

# **Screenshots**
_If applicable, add screenshots or links to help explain your problem_

Update: I tried again but this time from my phone. I didn't hit send, but in the recents, it shows this invalid `OxPAVLOVcIK.eth` address. There's some issue with the parser for the textbox input perhaps?

 ![IMG_2114](https://user-images.githubusercontent.com/4975670/196528455-9a354315-40b2-4b77-bf71-92de855b8540.PNG)

![IMG_2949326E1B86-1](https://user-images.githubusercontent.com/4975670/196529060-8f2d1234-7276-4efe-a9dc-c8b8dabc6e79.jpeg)

![IMG_2115](https://user-images.githubusercontent.com/4975670/196528447-9ee967b7-6b5a-4b32-a90b-ea8c21ee8965.PNG)

I'm able to constantly reproduce this. If you go very slowly, it resolves correctly. If you go at a normal speed, it resolves to an invalid address. I cropped the video because my keyboard doxxed a ton of people with their home addresses in my contacts.

https://user-images.githubusercontent.com/4975670/196533115-0d0311bb-722b-4564-88ae-6bce9baf2925.MP4

# **To Reproduce**

- Go to Wallet view
- Select any asset
- Input any amount
- Enter my ENS name in "to" field (pavlovcik.eth)
- Press next
- Hit send button 

# **Expected behavior**
_A clear and concise description of what you expected to happen_

MetaMask on Chrome resolves to the expected address. MetaMask on iOS resolves to the wrong address!

**Smartphone (please complete the following information):**

The issue exists on both of our devices.

iPhone 12 Mini; iPhone 13

16.0

 - App Version [e.g. 1.0.0] - find version number in app from Settings > About MetaMask

v5.8.1 (986)

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
# **Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by plasmacorral** [comment]
Can you please confirm exactly how you entered `pavlovcik.eth` into the TO field of the sending device?  Was it typed directly via the keyboard, pasted from the clipboard, or possibly scanned from a QR?

**Comment by pavlovcik** [comment]
> Can you please confirm exactly how you entered `pavlovcik.eth` into the TO field of the sending device? Was it typed directly via the keyboard, pasted from the clipboard, or possibly scanned from a QR?

Its in the video. I typed it

**Comment by plasmacorral** [comment]
> > Can you please confirm exactly how you entered `pavlovcik.eth` into the TO field of the sending device? Was it typed directly via the keyboard, pasted from the clipboard, or possibly scanned from a QR?
> 
> Its in the video. I typed it

Thank you for clarifying!  I saw you type in the video but wanted to confirm that it was also manually typed when this initially occured using your girlfriend's wallet.

**Comment by plasmacorral** [comment]
addressed in v5.9.1
