### ISSUE TITLE
Will Metamask support  registering ERC721 and ERC155 tokens with users ?

### ISSUE THREAD

**Issue by AaronLai** [MetaMask/metamask-mobile#5132]
### **Description**

According to this page, https://docs.metamask.io/guide/registering-your-token.html#code-free-example , user can add a token with one click but it does not support ERC721 & ERC1155 . Is support ERC 721 & ERC 1155 in the plan?

**Comment by ratio91** [comment]
would be very helpful for smooth UX!  
Also related to (https://github.com/ethereum/EIPs/blob/master/EIPS/eip-747.md)[EIP-747]
