### ISSUE TITLE
Wallet Connect – Connection dialog don't appear after MetaMask is in background for sometime ( timeout ) - 5.6.1

### ISSUE THREAD

**Issue by jayvs6341** [MetaMask/metamask-mobile#5133]
<strong>Describe the bug</strong>

I am working on android application to connect with MetaMask using WalletConnect protocol.
The connection works fine normally. But, if the MetaMask resided in background for some time, and then we again try to connect, it don't show the dialog prompt for the connection.

I think, MetaMask has some issue with the timeout duration.

Once this happens, MetaMask don't accept connections unless we remove it from recent.

This issue happens from the very beginning versions of MetaMask, I mainly focused on the latest version ( 5.6.1 ).

Launching metamask sometimes take less than 10 sec and sometimes take more than 20 sec.

<strong>Video Link for reference of the issue</strong>

https://drive.google.com/file/d/1hN7lQUcmoozfXCLLDArAm_bWkWnvamW_/view?usp=sharing

<strong>To Reproduce</strong>

Open MetaMask through connection protocol.It cannot connect first 2 times. Need to remove MetaMask app from RECENT and connect again.

<strong>Expected behaviour</strong>

It should accept the connection even though it's in background for sometime. Because, to open MetaMask after removing it from recent takes some time to load MetaMask.

**Comment by jayvs6341** [comment]
@gantunesr @andreahaku 

Please help me to resolve this.

**Comment by jayvs6341** [comment]
@andreahaku @gantunesr 

Any update Guys ?

**Comment by jayvs6341** [comment]
@andreahaku @gantunesr 

Hello guys,

Any update ?

Hope we will get update soon.

**Comment by jayvs6341** [comment]
> Sure, I will share the link again.

OK, you can concentrate now.

**Comment by jayvs6341** [comment]
> Hey @jayvs6341, thanks for reporting.
> 
> Could you elaborate and send us the recording again (it's unavailable)?
> 
> If you connect to the MetaMask via wallet connect and the app goes to the background for a while that will not kill the connection session.
> 
> We still couldn't begin to work on this issue, thank you for your understanding!

Please find the link below.

https://drive.google.com/file/d/1sNh54SOXSkF39O_JM44iJ33wlFl_H-yh/view?usp=share_link

**Comment by tommasini** [comment]
Thanks @jayvs6341 , could you try with the latest version of the app?

Also can you share which device are you using?

If it's possible to share the snippet of code that you are using for creating the connection, we appreciate too

**Comment by jayvs6341** [comment]
> Thanks @jayvs6341 , could you try with the latest version of the app?
> 
> Also can you share which device are you using?
> 
> If it's possible to share the snippet of code that you are using for creating the connection, we appreciate too

Sure, I will do this.

**Comment by jayvs6341** [comment]
@tommasini 

They latest build looks good.

Only issue I see is, first time it take almost 15 seconds to open the metamask.

Can we do something for it ?

**Comment by tommasini** [comment]
Nice!
We are working towards making the opening faster

Thanks, @jayvs6341, I will close this issue, since this last version solved this issue for you, if it happens again or you detect something else, we appreciate your support!
