### ISSUE TITLE
Metamask-mobile window.ethereum exists but becomes undefined if you reload on Android

### ISSUE THREAD

**Issue by dweng0** [MetaMask/metamask-mobile#5156]
This video explains it very clearly. But just incase you miss it...

- Loading the page for the first time and window.ethereum exists
- hit the reload button **(explicitly hit the reload button)** and window.ethereum becomes undefined
- Put the link in the URL and tap for it to navigate to it. window.ethereum exists
Video:

https://user-images.githubusercontent.com/5268627/198279404-89876836-a521-4106-aa79-4e3cc447db3d.mp4

**Expected behavior**
I expect window.ethereum to always exist on your own browser....

**Smartphone (please complete the following information):**
 - Device: All android devices...

**Comment by dweng0** [comment]
Just for relevance, the version of metamask-mobile on android was:
![image](https://user-images.githubusercontent.com/5268627/198282781-b07aaaf3-1365-4fac-b5fb-f98bc864c357.png)

**Comment by dweng0** [comment]
Any update on this?

**Comment by tommasini** [comment]
Hey @dweng0, thanks for reporting, I tried to replicate it on my android device with https://opensea.io/, and I'm not being able to, am I missing something?
My steps:
* Opened open sea on in-app browser
* Connected my wallet
* Reload

Tried the same steps with avalanche mainnet c-chain on https://traderjoexyz.com/home#/
Everything went like expected

**Comment by dweng0** [comment]
OK I'll try to narrow down the issue further, standby

**Comment by dweng0** [comment]
After stripping everything out, and slowly adding components back into the the Application. (And having to clear browser cache in the metamask browser every time i did this...).

I narrowed the issue down to the React-Router-rom, `<Redirect />` Component call

Not wanting to spend time in -another- framework debugging this issue. My guess is that the component produces malformed or non compliant HTML.

[I have raised an issue with them](https://github.com/remix-run/react-router/issues/9544)

Now really. Metamask-mobile browser shouldn't be crying foul here. it should just carry on, or atleast warn the user... But silently failing is definitely not the way to go: Here is a video of how to reproduce the issue:

https://user-images.githubusercontent.com/5268627/199492383-26abe754-e558-41dc-b0a0-34da26961338.mp4

**Comment by toteto** [comment]
Tried to create minimal reproduction https://codesandbox.io/s/stoic-murdock-67r563 but was unable. 

If you go to `https://67r563.csb.app/redirect` it will redirect you to `https://67r563.csb.app/`. The wallet is still connectable after that.

**Comment by chrisleewilcox** [comment]
@sethkfman please reach out to @omnat for details.

**Comment by PixsaOJ** [comment]
@toteto That says "Detected Provider" even tho I do not have Metamask installed. Then proceeds to fail on account request, because provider is actually null.

**Comment by Yezhiang** [comment]
Hi, I want to know if this problem has been solved？
