### ISSUE TITLE
Longpress not working for web apps

### ISSUE THREAD

**Issue by Yogeshwar267** [MetaMask/metamask-mobile#5157]
i have my react web app, and on longpress i want to perform specific task but in latest update magnifier is coming on longpress, how to overwrite this magnifier on longpress and use my custom function

**Comment by tommasini** [comment]
Hey @Yogeshwar267, thanks for reporting!

Are you talking about the in-app browser?
Can you send us a sample for we try to replicate it and see what we can do?
