### ISSUE TITLE
Using ButtonPrimary causes error

### ISSUE THREAD

**Issue by owencraston** [MetaMask/metamask-mobile#5166]
**Describe the bug**
- Using ButtonPrimary causes error due to faulty import

**Screenshots**
![Screenshot_1666909946 (1)](https://user-images.githubusercontent.com/22918444/198414629-450b5c9d-ac66-4f6f-bf55-74d504777c2c.png)

**To Reproduce**
_Steps to reproduce the behavior_
- checkout and [build this branch](https://github.com/MetaMask/metamask-mobile/pull/4917)
- after logging in it will crash with the above error 
- 

**Expected behavior**
- does not break

**Smartphone (please complete the following information):**
 - Device: iPhone
 - OS: iOS16
 - App Version [e.g. 1.0.0] - find version number in app from Settings > About MetaMask

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by owencraston** [comment]
replacing line 13 of ButtonBase.tsx with ...

```
import { ButtonBaseProps } from './ButtonBase.types';
import { ButtonSize } from '../../Button.types';
```

fixes the issue

**Comment by brianacnguyen** [comment]
Fix https://github.com/MetaMask/metamask-mobile/pull/5167
