### ISSUE TITLE
Why I can not add new library

### ISSUE THREAD

**Issue by hoatenhu** [MetaMask/metamask-mobile#5168]
I want to add 'react-native-code-push' but it always shows this error 
```
* What went wrong:
A problem occurred evaluating project ':ReactAndroid'.
> Could not get unknown property 'ANDROID_NDK_VERSION' for extension 'android' of type com.android.build.gradle.LibraryExtension.
```

**Comment by numanshahid995** [comment]
I am also facing same error 
This is 6 jan 2023 last year in month of december the error was different there was no installation error but installed package was not being added in Package.json File . Now it new library is being added in Package.json file but it result in error ANDROID_NDK_VERSION.
