### ISSUE TITLE
Couldn't confirm transaction

### ISSUE THREAD

**Issue by ClaireMao1996** [MetaMask/metamask-mobile#5193]
**Describe the bug**

When a user using walletconnect on our dapp - sends a transaction (`calling transfer method of smart contract of BEP-20 token`) - the tranfer popup show up but `confirm` button not working after click (reject is able to click)
Everything worked fine last week but failed yesterday for some reason. (same account but works well on metamask chrome extension.)

**Screenshots**

https://user-images.githubusercontent.com/101389820/199641281-d253f833-5b80-49cc-9752-10353e02addb.mp4

**Expected behavior**
User can click confirm and process the payment.

**Smartphone (please complete the following information):**
 - Device: Google pixel 4a / Google pixel 6a / samsung SM-G960F
 - OS: Android13 / Android13 / Android 10
 - App Version: v5.9.0(990) 

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by topaziotopazio** [comment]
hi I have the same problem listed above, both with ios and with ancroid, before the metamask was updated everything worked correctly, but now I can no longer confirm transactions, someone new to it?

thanks webmaster@keplercoins.site

[Share](https://ethereum.stackexchange.com/a/139270/111901)
[Edit](https://ethereum.stackexchange.com/posts/139270/edit)
Delete

**Comment by rmcmk** [comment]
Loads of our users are having this exact issue as well

**Comment by rmcmk** [comment]
@andreahaku A lot of our users are experiencing this same issue. It appears to be happening on any `payable` function. All other functions work as intended.

**Comment by ssa3512** [comment]
I'm experiencing this as a user of some dApps as well that use an ERC-20 token transaction. It's occurring on mobile (iOS) as of the latest update. Desktop browser extension works fine.

**Comment by amftokenofficial** [comment]
OMG, this "issue" has been open here for over 14 days now. I created the same #5235  , but nobody touched this issue.
It's really unprofessional.
I also contacted MM support but always received standard emails.
I hope someone from the team will answer and solve this problem as soon as possible.
@ssa3512 thanks for merging my issue.

**Comment by amftokenofficial** [comment]
> **Describe the bug**
> 
> When a user using walletconnect on our dapp - sends a transaction (`calling transfer method of smart contract of BEP-20 token`) - the tranfer popup show up but `confirm` button not working after click (reject is able to click) Everything worked fine last week but failed yesterday for some reason. (same account but works well on metamask chrome extension.)
> 
> **Screenshots**
> 
>  device-2022-11-02-165740.mp4 
> **Expected behavior** User can click confirm and process the payment.
> 
> **Smartphone (please complete the following information):**
> 
> * Device: Google pixel 4a / Google pixel 6a / samsung SM-G960F
> * OS: Android13 / Android13 / Android 10
> * App Version: v5.9.0(990)
> 
> _to be added after bug submission by internal support / PM_ **Severity**
> 
> * How critical is the impact of this bug on a user?
> * Add stats if available on % of customers impacted
> * Is this visible to all users?
> * Is this tech debt?

The same issue #5235

**Comment by urkishan** [comment]
I am also facing the same issue :( The confirm button on the transaction page is not working as the reject button is working fine. As I tried it on multiple dapp and same issue. The is happening when a user select Metamask from the wallet connect.

**Comment by ppemond-bkom** [comment]
We are also having the same issue. Seems to mostly affect Android device and iPhone are OK. This is quite an annoying bug, I don't see how we can go around it..

**Comment by amftokenofficial** [comment]
> We are also having the same issue. Seems to mostly affect Android device and iPhone are OK. This is quite an annoying bug, I don't see how we can go around it..

iPhone is not ok - the same problem for android and for ios.

**Comment by ledoandailoc** [comment]
Please fix!

**Comment by urkishan** [comment]
Got a comment from the contributor that they are fixing this bug https://github.com/MetaMask/metamask-mobile/issues/5260 and will release the fix asap.

**Comment by amftokenofficial** [comment]
It's been over 22 days since I first submitted a ticket to MM support and still no reasonable response.
Maybe we need to forget MM? and completely switch to another wallet and ask our users to do the same?
I really don't understand how it can be that such a company is ignoring this serious issue.
There are over 4 open issues here and a few others on stackoverflow.

**Comment by andreahaku** [comment]
Hi @amftokenofficial, the bug is not strictly related to WalletConnect but it's more general. A fix has already been developed and version 5.11.0, that is about to be released on stores, will fix this.
