### ISSUE TITLE
WalletConnect URIs (esp. Deep Link) do not connect when opened from Android browser

### ISSUE THREAD

**Issue by w4-jake** [MetaMask/metamask-mobile#5212]
### **Severity (reporter's perspective) and XY problem discussion**
Other developers may of course have different priorities, but for us it is **very high priority** that a user be able to connect their MetaMask wallet to our web app when our web app is accessed on an Android device's browser. Our preferred approach so far has been to open a deep link for the WalletConnect protocol, but if there is a better approach, then any guidance would be appreciated!

And if there is any more we can do to assist the team in looking into this issue, please do not hesitate to let us know. Thank you!

---

### **Describe the bug**

Similar to #5004 and #4955, but the scenario (Deep Link opened from Android browser) is slightly different, so I have made a new issue. Apologies if this comes across as a duplicate!

In a browser like Chrome, Firefox, DuckDuckGo, etc. on an Android mobile device, opening a deep link to MetaMask with a valid WalletConnect URI parameter results in the MetaMask app opening, but no option to 'Connect' appears.

### **Screenshots**

Please compare the two videos below. Opening an identically formatted deep link from a browser like Safari on an iOS device works as expected.

### **To Reproduce** 
1. Receive a WalletConnect session URI. It should start with `wc:` (see: [WalletConnect v1 docs](https://docs.walletconnect.com/1.0/mobile-linking#wallet-support))
2. With this received URI `walletConnectUri`, construct a deep link in the form `metamask://wc?uri=${walletConnectUri}`.
3. Open this deep link in a browser on a mobile device with MetaMask installed.
4. See whether option to 'Connect' appears after MetaMask opens.

Please reference the [sample Flutter app](https://github.com/w4-jake/flutter_wallet_connect_metamask) from the videos below, where this issue can be reproduced and tested on a variety of different environments. We discuss extensively which kind of links (raw `wc:` URI, deep link, universal link) work in which kind of environment [here](https://github.com/w4-jake/flutter_wallet_connect_metamask/blob/e51e28ad15bdd90b38cf7168cf9eacc4406cffca/lib/main.dart#L83).

### **Expected behavior**
After MetaMask opens, the connecting app information, account information, 'Connect' button, 'Cancel" button, and so on should show. Please see the iOS screen capture.

#### **Android**
 - Device: Galaxy S9
 - OS: Android 10
 - App Version: v5.9.1 (995)

#### **iOS**
 - Device: iPhone 6
 - OS: iOS 12.5.6
 - App Version: v5.9.1 (995)

#### **Android browser**

https://user-images.githubusercontent.com/52257615/200474088-50c03752-4707-484d-9b45-cced56db4bd9.mp4

#### **iOS browser**

https://user-images.githubusercontent.com/52257615/200474033-e5560a7d-1aed-439f-87ee-732611c033c3.MOV

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by lunajuan** [comment]
I noticed a similar behavior on android when using the `metamask` protocol. In my case it didn't work when the wallet-connect uri was encoded but it did work if it wasn't.

Seems encoded wallet-connect uri is considered invalid here:
https://github.com/MetaMask/metamask-mobile/blob/18dc20b8cc9f3f0707f5eb04f2ac88ee320c93bb/app/core/DeeplinkManager.js#L321

**Comment by w4-jake** [comment]
Hi @lunajuan, thanks for pointing that out. Just to make sure I fully understand, by the wallet-connect URI being 'encoded', do you mean the difference between ':' (not URI encoded) and '%3A' (URI encoded) in an address like `metamask://wc?uri=wc%3A50eb69e9...`?

It looks like the logic that parses the URI is provided from WalletConnect utils. I wonder if an encoded URI is not being correctly parsed.

https://github.com/MetaMask/metamask-mobile/blob/18dc20b8cc9f3f0707f5eb04f2ac88ee320c93bb/app/core/WalletConnect.js#L451-L457

In my sample app, I am anywhere encoding the Wallet Connect URI before attempting to open it. Hmm...do some operating systems automatically encode the URI, while others do not?

**Comment by w4-jake** [comment]
Ahh, I think I found the `parseWalletConnectUri` function. It is located now in the `walletconnect-legacy` repo, _not_ the current WalletConnect utils repo, as it is from the v1 protocol. 

https://github.com/WalletConnect/walletconnect-legacy/blob/4563223a9fe2ff099e7a66788813697e09b1e35c/packages/utils/src/session.ts#L14-L34

Looks like it is looking for that unencoded ':' character. Is there any way that MetaMask can unencode incoming deep links so that this legacy function will also work with a URL of the form `metamask://wc?uri=wc%3A50eb69e9...`? Or is there a better solution here?

**Comment by lunajuan** [comment]
yeah, that's what I meant by an encoded uri. I'm working in react native so I just went with your second option which is to not encode the uri. Interestingly, other wallets I tested wanted the uri to be encoded hahaha!

Seems like [WalletConnect team really wants everyone to use v2](https://medium.com/walletconnect/walletconnect-v1-0-sunset-notice-and-migration-schedule-8af9d3720d2e) so I would think your second choice is best option for now if you can  figure it out. 🤞

side note, I wonder why the uri is not validate in a similar way if you use the universal link
https://github.com/MetaMask/metamask-mobile/blob/18dc20b8cc9f3f0707f5eb04f2ac88ee320c93bb/app/core/DeeplinkManager.js#L223-L229

**Comment by w4-jake** [comment]
Yeah, that makes sense. I am very much looking forward to v2 support for MetaMask...looks like WalletConnect team wants all wallets to support v2 within just a few weeks, but I'm not sure if the MetaMask team's timeline will coincide. (Here's the most relevant [issue](https://github.com/MetaMask/metamask-mobile/issues/3957#issuecomment-1322034748) I could find.)

So it seems like a lost cause to get WalletConnect to change their legacy parser. If with Flutter we can't find a good way to make sure an unencoded URI is always sent regardless of device/OS, then it would be nice if MetaMask could simply decode the URI inside the `isValidUri` function before passing to WalletConnect's parser. But perhaps there is a good way to do just force unencoded URI launch in Flutter...

As for the universal link, interesting that the way to validate is different! My sample app [never once got universal link to work](https://github.com/w4-jake/flutter_wallet_connect_metamask/blob/e51e28ad15bdd90b38cf7168cf9eacc4406cffca/lib/main.dart#L120-L132) so I passed over considering it altogether.

**Comment by andreahaku** [comment]
we are planning to support WalletConnect v2 in late Q1 2023.
In the meantime we are working on a refactor of the Deeplink manager that should solve this issues.

**Comment by tarrouye** [comment]
> @andreahaku 
> we are planning to support WalletConnect v2 in late Q1 2023.
> In the meantime we are working on a refactor of the Deeplink manager that should solve this issues.

late Q1 2023 is far past the deadline WalletConnect has set for wallets of December 16th, 2022 https://medium.com/walletconnect/walletconnect-v1-0-sunset-notice-and-migration-schedule-8af9d3720d2e

MetaMask being one of the leading wallets in terms of adoption, dragging your feet on this holds the whole industry back as everyone must maintain v1 support because we can't drop MetaMask support 😞

**Comment by andreahaku** [comment]
@tarrouye WC v2 and v1 can and will live together. So you can keep compatibility with v1 while implementing v2.

The integration of v2 requires a series of changes that we are already implementing as they are already planned as part of MetaMask mobile evolution. When all those pieces will be completed, we'll be ready to integrate WCv2 as part of it. BTW, we are in close contact with WalletConnect and they are aware of our scheduling.

Most importantly, there are still standards to be fully defined and that both WC and MetaMask are contributing (along with other actors) to define. So we are not dragging anyone. We are just waiting for times to be mature for a secure standard implementation of such a shift.

**Comment by tarrouye** [comment]
> @tarrouye WC v2 and v1 can and will live together. So you can keep compatibility with v1 while implementing v2.
> 
> The integration of v2 requires a series of changes that we are already implementing as they are already planned as part of MetaMask mobile evolution. When all those pieces will be completed, we'll be ready to integrate WCv2 as part of it. BTW, we are in close contact with WalletConnect and they are aware of our scheduling.
> 
> Most importantly, there are still standards to be fully defined and that both WC and MetaMask are contributing (along with other actors) to define. So we are not dragging anyone. We are just waiting for times to be mature for a secure standard implementation of such a shift.

Per WC documentation, wallets can support v1 and v2 simultaneously but Dapps should only support one or the other. So until all major wallets use v2, Dapps cannot move to v2: https://medium.com/walletconnect/walletconnect-sign-v2-0-the-final-release-is-here-864b21e8d1ca and https://docs.walletconnect.com/2.0/advanced/migrating-from-v1.0

**Comment by ZZZDAD** [comment]
> @tarrouye WC v2 and v1 can and will live together. So you can keep compatibility with v1 while implementing v2.
> 
> The integration of v2 requires a series of changes that we are already implementing as they are already planned as part of MetaMask mobile evolution. When all those pieces will be completed, we'll be ready to integrate WCv2 as part of it. BTW, we are in close contact with WalletConnect and they are aware of our scheduling.
> 
> Most importantly, there are still standards to be fully defined and that both WC and MetaMask are contributing (along with other actors) to define. So we are not dragging anyone. We are just waiting for times to be mature for a secure standard implementation of such a shift.

Hello, I am very much looking forward to the fact that metamask can support the wallet connect2.0 protocol, and the development of our dapp is also waiting anxiously. May I ask if there is a time when the 2.0 protocol can be supported?

**Comment by ZZZDAD** [comment]
> @tarrouye WC v2 and v1 can and will live together. So you can keep compatibility with v1 while implementing v2.
> 
> The integration of v2 requires a series of changes that we are already implementing as they are already planned as part of MetaMask mobile evolution. When all those pieces will be completed, we'll be ready to integrate WCv2 as part of it. BTW, we are in close contact with WalletConnect and they are aware of our scheduling.
> 
> Most importantly, there are still standards to be fully defined and that both WC and MetaMask are contributing (along with other actors) to define. So we are not dragging anyone. We are just waiting for times to be mature for a secure standard implementation of such a shift.

Hello, I am very much looking forward to the fact that metamask can support the wallet connect2.0 protocol, and the development of our dapp is also waiting anxiously. May I ask if there is a time when the 2.0 protocol can be supported?

**Comment by siosio34** [comment]
any update for this issue?

**Comment by DailaYoffey** [comment]
I can't still connect metamask in the react native app in the mobile when I am using walletconnect v2.

**Comment by namdh03** [comment]
Any update for this issue?
