### ISSUE TITLE
Error: [number] while converting number 49.99289009

### ISSUE THREAD

**Issue by anaamolnar** [MetaMask/metamask-mobile#5221]
Metamask throws an error when buying USDT with Transak when the receiving amount has more than 6 decimals.
USDT contract has 6 decimals, so any amount with more decimals is “invalid” and throws an error.

Screenshots:
![image](https://user-images.githubusercontent.com/82837486/200875002-e13da719-95ef-4c89-8af6-7eef7865845a.png)

**To Reproduce**
1. Click the 'Buy' button
2. Buy 'USDT.'
3. Select the amount
4. Choose Transak as a provider
5. See error

**Smartphone (please complete the following information):**
 - OS: iOS/Android
 - App Version: 5.9.1

**Comment by wachunei** [comment]
This has been fixed in On-ramp API - v1.20.0
