### ISSUE TITLE
Cannot open new tab window.open

### ISSUE THREAD

**Issue by jalaguerom** [MetaMask/metamask-mobile#5225]
### **Description**

I am creating a website with React. I have a button which retrieves a file URL from an API call. When I get the URL, I use window.open(url, '_blank') to download the file, because the file associated with the URL has Content-Disposition: Attachment header. On desktop everything works fine: a new tab is open with the URL and downloads the file. On Android works too. But on iOS the button does nothing. I tried changing target window from '_blank' to '_self' and the file is downloaded but I get blank screen when browser returns to my website; no components are loaded, it is just my root node. I also tried to use deep links with dapp:// schema but it can only be used for mobile use case, not for desktop.

Is there a way to open a new tab inside metamask browser from my dapp? I need a cross browser solution, which can work inside metamask browser as well as desktop browsers such as Chrome.

**Comment by davigp** [comment]
I'm facing the same issue using the latest Metamask app in iOS, in Chrome and Safari the same dapp opens in a new tab, however in the Metamask browser, it opens in the same tab. Is there any option to allow opening in a new tab?
