### ISSUE TITLE
this session is already connected

### ISSUE THREAD

**Issue by chendaxia65** [MetaMask/metamask-mobile#5230]
Why is there a prompt this session is already connected every time I open metamask?

**Comment by 0xHristo** [comment]
I also got this pop up when I am trying to connect my Daap with WalletConnect.

**Comment by marqueeeeeee** [comment]
having this problem too, this does occur on android metamask, on iOS it's not prompting any session exist error

**Comment by marqueeeeeee** [comment]
even when session was cleared from metamask app before connecting, the error prompt still shows. 
![IMG_6787](https://user-images.githubusercontent.com/8085652/201591587-415f66d0-ea75-4413-9ee8-3e83d827e452.jpg)

**Comment by tiancaidao** [comment]
What dapp are you using? It is because a sesson from Dapp already attached to current session, while a second session is trying to connnect again.

**Comment by vicwtang** [comment]
> What dapp are you using? It is because a sesson from Dapp already attached to current session, while a second session is trying to connnect again.

This error occurs when there is no existing session. Going to settings/experimental/sessions shows "You have no active sessions". Selecting "Clear all Metamask SDK Connections" does not resolve the issue.
This has been replicated also on the Rarible sdk example dapp. The same dapp connects fine to Metamask via WalletConnect on IOS - so the issue is solely with Andriod devices.

**Comment by marqueeeeeee** [comment]
yup same issue only Android even connecting with a fresh session.

**Comment by Hattori224** [comment]
any update for this issue?

**Comment by buivanday96** [comment]
any update for this?

**Comment by stevenkeith85** [comment]
Also keen to hear an update.

Thanks

**Comment by kabaluyot** [comment]
Still experiencing this even the app is just minimized and back on foreground again

**Comment by TalhaCagatay** [comment]
this issue still exists

**Comment by devamitsharma101** [comment]
Any updated on this? Anything?

**Comment by ZiggStardust** [comment]
Also getting this issue - any updates ?

**Comment by vicwtang** [comment]
It's been months without any progress on this issue. I gave up and
incorporated the WAGMI/Web3Modal hooks, changed the way I accessed metamask
to direct interaction (as required for IOS) and have had much better
results. Not 100% - it seems just to flakey for that - but about 90%
stability. Still better than having to run within the Metamask Browser.
Would be nice if Metamask could get this working more reliably for PWA's

**Comment by ZiggStardust** [comment]
@vicwtang Thank you because i just did the same, only took around 1 day to implement some testing to do ... 

would be nice if a org like Metamask could fix these issues quicker

**Comment by joshstevens19** [comment]
Hey guys, this is quite a severe issue and means you can’t do any actions with the specific app. You have no way to disconnect the session on the mobile app, and you are just left unable to do it. Would class this as super important issue to get fixed, any news on this?
![307F3716-F1E9-4E5C-89BA-DE662205F838](https://user-images.githubusercontent.com/18472422/218288190-4d8a5615-fab9-44d9-a9e9-1fbcd9fc97f4.jpeg)

**Comment by andreahaku** [comment]
We are investigating the issue. Trying to replicate it and working on a fix. Thanks for your patience.

**Comment by vitamin33** [comment]
I have the same problem. No sessions in "Experimental" sections and "Clear all Metamask SDK Connections" does not help as well. And I still see this error.

Update: Only full clearing of Metamask app storage helped to solve it, but real user can't do it every time.

**Comment by techieanant** [comment]
I found a workaround for this issue: 

1. Clear all Metamask SDK sessions

<img src="https://user-images.githubusercontent.com/7658579/221267598-0f12ba96-9013-48b9-845b-e5b687cf3d15.png" width="280" height="400">


2. Clear all WalletConnect sessions

<img src="https://user-images.githubusercontent.com/7658579/221267684-86c137e7-c64d-40f5-9add-09e1bab2d54c.png" width="250" height="500">


3. Clear Data and Cache for the app you are trying to connect.

<img src="https://user-images.githubusercontent.com/7658579/221267787-a6d261aa-4aa2-434d-a620-48cd7f3b8d49.png" width="250" height="500">

**Comment by ratio91** [comment]
I tried all the potential solutions countless times but none work for me.
These metamask issues eat so much of my productive time, it's insane.
@MM team please try to fix this issue as soon as possible. Thank you.

(I use the lastest Android app release from last week).

**Comment by siosio34** [comment]
any update for this issue?
