### ISSUE TITLE
Unable to sign EIP712 request

### ISSUE THREAD

**Issue by rafagalan** [MetaMask/metamask-mobile#5232]
**Describe the bug**
The sign button for EIP712 sign requests (through **walletconnect**) does not work for a specific petition. Furthermore when touching the "show more" text the message disappears and the app closes unexpectedly. We have tried to reproduce this bug using another payload but it seems like there is a problem with that specific message. Trustwallet and Coinbase wallet are able to sign this payload as they should. This same payload works fine in the browser extension and when the request is made through the mm mobile browser.

**Screenshots**
https://user-images.githubusercontent.com/71089247/201333420-6a0913d3-33bb-42e7-bd5c-731d68fe32ba.MP4

**To Reproduce**
1. Request the mobile to sign this petition: 
`
{
    "domain": {
        "name": "DefaultMintOperator",
        "version": "1.0.0",
        "chainId": 137,
        "verifyingContract": "0xF52004055E8bc39B3E03399Dddd48c27ffac1093"
    },
    "types": {
        "BatchMint": [
            {
                "name": "from",
                "type": "address"
            },
            {
                "name": "tokenAddress",
                "type": "address"
            },
            {
                "name": "to",
                "type": "address[]"
            },
            {
                "name": "amount",
                "type": "uint256[]"
            },
            {
                "name": "nonce",
                "type": "uint256"
            }
        ]
    },
    "value": {
        "from": "0x62941E2A56DF10F3397C601599767480cF23c279",
        "tokenAddress": "0xFec503AD674a0bf07107Ce4cA78755dc7F9097A4",
        "to": [
            "0x62941E2A56DF10F3397C601599767480cF23c279"
        ],
        "amount": [
            "1000000000000000000"
        ],
        "nonce": 0
    }
}
`
3. Wait until the request shows up in metamask
4. Try to sign the message (it shouldn't work)
5. Click on "show more"

**Expected behavior**
Should sign the message.

**Smartphone (please complete the following information):**
 - iPhone & Android
 - iOs 15.6.1 & Android 12 SKQ1.211006.001
 - Metamask v.5.9.1 (995)

-------------------------------------------------------------
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by rafagalan** [comment]
Doing some tests we have figured out the cause of this error, metamask with walletconnect does nos support arrays in the typed data (EIP-712). Seems like #5103  solves this.

**Comment by tommasini** [comment]
Thanks for testing!

It will be on version 5.12, we are doing the final tests to release that version 
I will update this ticket once it gets to production

**Comment by creacodigos** [comment]
Hello.
We have seen that the mobile app has been updated to version 5.12.0 (1024), but we see that the `eth_signTypedData_v4` method is not used for the file data signatures:

metamask-mobile/app/core/WalletConnect.js (https://github.com/MetaMask/metamask-mobile/blob/18dc20b8cc9f3f0707f5eb04f2ac88ee320c93bb/app/core/WalletConnect.js)

Line 158:
```
if (payload.method === 'eth_signTypedData') {
   payload.method = 'eth_signTypedData_v3';
}
```

The error it returns: is `[Error: invalid arrayify value (argument="value", value="Keyring Controller signTypedMessage: Error: Arrays are unimplemented in encodeData; use V4 extension", code=INVALID_ARGUMENT, version=bytes/5.5.0 )`

I understand that what is needed is to use the method: `eth_signTypedData_v4`

Thank you

**Comment by bschorchit** [comment]
Closing as this seems to be solved.

**Comment by Sednaoui** [comment]
Hello @tommasini 

I tried sending a custom request for `eth_signTypedData_v4` with walletconnect as you suggested, but I still got the same error as @creacodigos above

`Keyring Controller signTypedMessage: Error: Arrays are unimplemented in encodeData; use V4 extension result`. 

ex of request
```
const customRequest = {
  jsonrpc: "2.0",
  method: "eth_signTypedData_v4",
  params: [from, msgParams],
};
```
I am on metamask-mobile version `6.0.0 (1068)`

**Comment by tommasini** [comment]
@Sednaoui Thanks for reporting!
Was it working on a previous version like 5.14.0? Also, could you provide which device and example of dapp so we try to replicate it on our side? 

I can recommend also using the Metamask SDK https://metamask.io/sdk/ if possible for your project

**Comment by Sednaoui** [comment]
Hello @tommasini , sorry for the delayed response. I haven't tried it with `v5.14.0`, only with `6.0.0 (1068)`. The dapp I am currently building uses etherjs `_signedTypedData` method. Here's the exact [method in the dapp](
https://github.com/candidelabs/security-center/blob/8ede70c58b75452421f839fe6faa0e270357791e/src/components/RecoveryRequestCard.js#L96)

I made another branch that uses a custom request to send `eth_signTypedData_v4`. See [here](https://github.com/candidelabs/security-center/blob/239738cbf47173c39d8275bd8791dabc6ac596b8/src/components/RecoveryRequestCard.js#L98).

I am using an metamask mobile on my iphone . The dapp is an account recovery interface for a smart contract wallet. It lets recovery contacts (example: a metamask mobile) sign a message to replace the owner of the current account. You would need to install the wallet, add recovery contacts, then initiate a recovery to try the dapp. 

Both of methods I shared work well with metamask extension, but not with metamask mobile. I haven't tried with metamask sdk yet, but I will be trying it out as well. 

Image below by metamask extension
![image](https://user-images.githubusercontent.com/7014833/224965026-955a0516-cab4-4ba2-8f84-17453969cebb.png)

**Comment by Hajto** [comment]
Having the same issue.
Metamask 6.1.1 (1079)

Tried two ways of submission:
```
const request = {
  jsonrpc: "2.0",
  method: "eth_signTypedData_v4",
  params: [from, JSON.stringify(message)],
}
const result = await window.webby3.currentProvider.request(request);
console.log(result)
```
and
```
const from = selectedAddress;
const params = [from, JSON.stringify(message)];
const method = 'eth_signTypedData_v4';

console.log("Sending request to sign the message")

window.webby3.currentProvider.sendAsync(
    {
        method,
        params,
        from,
    },
    function (err, result) {
        if (err){
            console.error(result.error.message);
            return reject(err)
        };
        if (result.error) {
            console.error(result.error.message)
            reject(result.error.message);
        };
        console.info(result.result)
        resolve(result.result)
    }
)
```

Message to sign:
```
{
    "domain": {
        "chainId": "137",
        "name": "Seaport",
        "verifyingContract": "0x00000000000001ad428e4906ae43d8f9852d0dd6",
        "version": "1.4"
    },
    "message": {
        "conduitKey": "0x0000000000000000000000000000000000000000000000000000000000000000",
        "consideration": [
            {
                "endAmount": "2000000000000000000",
                "identifierOrCriteria": "0",
                "itemType": "1",
                "recipient": "0x9e95cfc198e7c67686923280469b25304b3cc3e6",
                "startAmount": "2000000000000000000",
                "token": "0x7ceb23fd6bc0add59e62ac25578270cff1b9f619"
            }
        ],
        "counter": "0",
        "endTime": "1689254798",
        "offer": [
            {
                "endAmount": "1",
                "identifierOrCriteria": "423875",
                "itemType": "2",
                "startAmount": "1",
                "token": "0x67f4732266c7300cca593c814d46bee72e40659f"
            }
        ],
        "offerer": "0x9e95cfc198e7c67686923280469b25304b3cc3e6",
        "orderType": "0",
        "salt": "88174898202546984371302718973281111831789933536839056888910699563917350673720",
        "startTime": "1681392398",
        "zone": "0x0000000000000000000000000000000000000000",
        "zoneHash": "0x3000000000000000000000000000000000000000000000000000000000000000"
    },
    "primaryType": "OrderComponents",
    "types": {
        "ConsiderationItem": [
            {
                "name": "itemType",
                "type": "uint8"
            },
            {
                "name": "token",
                "type": "address"
            },
            {
                "name": "identifierOrCriteria",
                "type": "uint256"
            },
            {
                "name": "startAmount",
                "type": "uint256"
            },
            {
                "name": "endAmount",
                "type": "uint256"
            },
            {
                "name": "recipient",
                "type": "address"
            }
        ],
        "EIP712Domain": [
            {
                "name": "name",
                "type": "string"
            },
            {
                "name": "version",
                "type": "string"
            },
            {
                "name": "chainId",
                "type": "uint256"
            },
            {
                "name": "verifyingContract",
                "type": "address"
            }
        ],
        "OfferItem": [
            {
                "name": "itemType",
                "type": "uint8"
            },
            {
                "name": "token",
                "type": "address"
            },
            {
                "name": "identifierOrCriteria",
                "type": "uint256"
            },
            {
                "name": "startAmount",
                "type": "uint256"
            },
            {
                "name": "endAmount",
                "type": "uint256"
            }
        ],
        "OrderComponents": [
            {
                "name": "offerer",
                "type": "address"
            },
            {
                "name": "zone",
                "type": "address"
            },
            {
                "name": "offer",
                "type": "OfferItem[]"
            },
            {
                "name": "consideration",
                "type": "ConsiderationItem[]"
            },
            {
                "name": "orderType",
                "type": "uint8"
            },
            {
                "name": "startTime",
                "type": "uint256"
            },
            {
                "name": "endTime",
                "type": "uint256"
            },
            {
                "name": "zoneHash",
                "type": "bytes32"
            },
            {
                "name": "salt",
                "type": "uint256"
            },
            {
                "name": "conduitKey",
                "type": "bytes32"
            },
            {
                "name": "counter",
                "type": "uint256"
            }
        ]
    }
}
```

Error:
```
Keyring Controller signTypedMessage: Error: Arrays are unimplemented in encodeData; use V4 extension
```

The same code works perfectly fine on chrome extension.

**Comment by Hajto** [comment]
https://user-images.githubusercontent.com/8336429/231774866-258e14d4-0c82-4de0-87e5-bdbda6c201fa.mp4

**Comment by milaabl** [comment]
@Hajto have you ever figured it out? 🙏🙏🙏
