### ISSUE TITLE
Metamask mobile 5.10.0 not suggesting gas fee on custom hardhat node network

### ISSUE THREAD

**Issue by 0xHristo** [MetaMask/metamask-mobile#5245]
**Describe the bug**

 I have set up custom `hardhat node` which I have added to the Metamask mobile app. Every time when I try to submit transaction the Metamask app is not suggesting any gas and I cannot send the transaction, if I try to send it I am getting internal JSON RPC error.

**Screenshots**

 
![IMG_8255](https://user-images.githubusercontent.com/94007544/202219818-93133a93-34db-4dd4-a095-f18d3a14aa45.PNG) ![IMG_8251](https://user-images.githubusercontent.com/94007544/202219826-41d5c928-e0e4-408b-bcce-316bf66c944f.PNG)

**Expected behavior**
I expect Metamsk to suggest and fill the gas price fields

**Smartphone:**
 - Device: iPhone12, iPhone13 Pro, Shaomi Mi MI 5 Light, Google Pixel 5, Honor Play
 - OS: iOS16, iOS16, Android 15, Android 15, Android 9
 - App Version - 5.10.0 (It works on 5.9.1)

I've tried on all of the above phones and it doesn't work on version 5.10.0 but it works on 5.9.1

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by tommasini** [comment]
Thanks for reporting @0xHristo , we are aware and solving this issue ASAP

**Comment by 0xHristo** [comment]
Hi @tommasini,

May you provide me with further information about the resolving of this issue. How long it will take to resolve it? Should I expect it resolved in 5.10.1? If yes, when is the release of the 5.10.1?

Thank you in advance!

**Comment by tommasini** [comment]
Thanks for your patience, a fix already have been developed, and it's about to be available in the stores on version 5.11.0 

In Android, until it is available you can download the apk of version 5.9.1 here on our GitHub repo https://github.com/MetaMask/metamask-mobile/releases/tag/v5.9.1

**Comment by 0xHristo** [comment]
Hi @tommasini  thank you for the fast response. I have downloaded the updated version and it works fine on the normal transactions but when I try to do `approve` transaction it still has the above issue. The value is not `NaN` but instead it is totally missing.

![IMG_8306](https://user-images.githubusercontent.com/94007544/203057708-0eff10fb-7618-45a8-8def-e641a868ca10.PNG)

**Comment by tommasini** [comment]
@0xHristo Thanks for update the issue!

We are not being able to reproduce it on ethereum mainnet and on polygon mainnet, using the app.aave.com with an IOS on Version 5.11

Could you help us with more information? 
It would be awesome the steps you do and the network rpc URL and chain id that you are using to reproduce this bug

**Comment by 0xHristo** [comment]
@tommasini hi,

This is the information needed to reproduce the transaction.
I want to note that I am using WalletConnect to connect with Metamask.

rpc URL: `https://2488-206-189-108-140.ngrok.io/`
chaid id: `31337`

the transaction which I am trying to send(basically ERC20 approval to the USDC token smart contract address)
```
{
  "id": "1669044200605642",
  "jsonrpc": "2.0",
  "method": "eth_sendTransaction",
  "params": [
    {
      "from": "0x0e1751fb76a2f4a8288c0af347def0d5fd5313a7",
      "data": "095ea7b3000000000000000000000000151087e77a918d33df147e748e3bea54c2c08c21ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff",
      "to": "0x2791bca1f2de4661ed88a30c99a7a9449aa84174",
      "gas": "0x2dc6c0"
    }
  ]
}
```

The MetaMask's visualisation:

![IMG_8309](https://user-images.githubusercontent.com/94007544/203093817-e99cc12b-db33-44c1-ab34-60b714fc0c7a.jpeg)

**Comment by 0xHristo** [comment]
I think the problem is from MetaMask because when I am trying submitting the transaction bellow to the same network everything seems okay.

```
{
  "id": "1669044699708046",
  "jsonrpc": "2.0",
  "method": "eth_sendTransaction",
  "params": [
    {
      "from": "0x0E1751Fb76a2F4a8288C0AF347def0d5fD5313A7",
      "data": "c04a8a10000000000000000000000000151087e77a918d33df147e748e3bea54c2c08c21ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff",
      "to": "0x2791bca1f2de4661ed88a30c99a7a9449aa84174",
      "gas": "0x2dc6c0"
    }
  ]
}
```
<img width="444" alt="Screenshot 2022-11-21 at 17 36 09" src="https://user-images.githubusercontent.com/94007544/203095478-2390267a-0f40-4039-bbad-64bb45b34944.png">

**Comment by 0xHristo** [comment]
Hey @tommasini, any updates on this issue. Can I help in some way?

**Comment by tommasini** [comment]
Hey @0xHristo we tried to reproduce this on goerli network with the [usdc](https://goerli.etherscan.io/address/0x07865c6e87b9f70255377e024ace6630c1eaa37f#writeProxyContract) smart contract

And we were able to estimate the gas and approve the permission to access the token 
<img width=250 src="https://user-images.githubusercontent.com/46944231/203758861-130a790a-d46f-4710-a3df-4147df68b34c.jpeg" />

**Comment by 0xHristo** [comment]
@tommasini I understand. I agree that it is working on public testnets & mainnets but I hit this issue when I try to submit approval on selfhosted testnet. Please, can you try with the following network:

Network RPC URL: `https://3538-206-189-108-140.ngrok.io/` (Fork of the Polygon's mainnet, Forked with `Hardhat`)
Network Chain ID: `31338`

I am trying to submit the following transaction:
```
{
  "id": "1669044200605642",
  "jsonrpc": "2.0",
  "method": "eth_sendTransaction",
  "params": [
    {
      "from": "0x0e1751fb76a2f4a8288c0af347def0d5fd5313a7",
      "data": "095ea7b3000000000000000000000000151087e77a918d33df147e748e3bea54c2c08c21ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff",
      "to": "0x2791bca1f2de4661ed88a30c99a7a9449aa84174",
      "gas": "0x2dc6c0"
    }
  ]
}
```

Note: If I try submitting on any other public testnet/mainnet everything is populated just fine but not on the above network.
Note 2: Every other transaction (`transfer`. `transferFrom`, etc.) works perfectly fine with the above network.

**Comment by tommasini** [comment]
Thank you @0xHristo I will send this issue to our team!

**Comment by 0xHristo** [comment]
Yes it was working.

**Comment by 0xHristo** [comment]
@tommasini Hello, are there any updates on this topic?

**Comment by tenax002** [comment]
Also came across this issue for attempting to send and approval transaction on Avalanche Fuji testnet.

**Comment by chrisleewilcox** [comment]
@tenax002 can you confirm the MetaMask mobile app version?

**Comment by chrisleewilcox** [comment]
@0xHristo we are still not able to repro on other testnets and mainnet.

**Comment by tenax002** [comment]
@chrisleewilcox 5.12

**Comment by jarnaez728** [comment]
I can confirm this problem continues in Metamask mobile 5.12.0 Works fine as plugin in the browser. I have two custom networks and with one of them, gas is properly calculated but the other not. I'll gather all the information and will post it here so you can reproduce the issue and hopefully solve it :)

**Comment by tommasini** [comment]
@jarnaez728 thank you!

**Comment by bschorchit** [comment]
Is this still an issue?

**Comment by bschorchit** [comment]
Awesome news! Thanks for checking it :)
