### ISSUE TITLE
metamask deeplink not working in android 

### ISSUE THREAD

**Issue by siosio34** [MetaMask/metamask-mobile#5258]
**Describe the bug**
i uninstalled metamask mobile application. and i connect metamask to use walletconnect.
I expected to go to the google play metamask download link, but Nothing happens, just a black screen.

wallet connect example site, magiceden same situation 

**Screenshots**

**To Reproduce**
_Steps to reproduce the behavior_
1. select walletconnect  in mobile web

**Expected behavior**
go to google play metamask download link

**Smartphone (please complete the following information):**
 - Device: samsung galaxy 21
 - OS: android 8.0
 - App Version [e.g. 1.0.0] - find version number in app from Settings > About MetaMask

-------------------------------------------------------------

**Comment by chrisleewilcox** [comment]
@siosio34 can you provide the following info...

- MetaMask mobile app version
- confirm issue is on Android 8? (probably old, advise to update)


If possible updating to the latest version of our app and Android OS may resolve issue.  Please confirm.
