### ISSUE TITLE
Confirm button is blue but not working when press it (iPhone)

### ISSUE THREAD

**Issue by ledoandailoc** [MetaMask/metamask-mobile#5271]
It worked before but since I upgraded version to 5.10.0 it doesn't work anymore.
(Still work for transaction with value is 0)

**Comment by urkishan** [comment]
Got a comment from the contributor that they are fixing this bug https://github.com/MetaMask/metamask-mobile/issues/5260 and will release the fix asap.

**Comment by ledoandailoc** [comment]
> Got a comment from the contributor that they are fixing this bug #5260 and will release the fix asap.

Yeah, hope they fix soon

**Comment by tommasini** [comment]
Thanks for your patience, a fix already have been developed, and it's about to be available (Rollout Phase) in the stores on version 5.11.0 

In Android, until it is available you can download the apk of version 5.9.1 here on our GitHub repo https://github.com/MetaMask/metamask-mobile/releases/tag/v5.9.1
