### ISSUE TITLE
Improve MetaMetrics onboarding copy specificity and enable Add Custom RPC URL updates

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-mobile#5301]
Ensure the distinction between MetaMetrics and a provider are clearer. cc @coreyjanssen

Related to https://github.com/MetaMask/metamask-extension/issues/16711

Onboarding Screen with Copy

!![image (2).png](https://images.zenhubusercontent.com/602c3c981617aad4ad2160f8/b9912897-ecea-4307-af55-50e2b2e47d22)

[Screenshot 2022-11-30 at 12.24.48 PM.png](https://images.zenhubusercontent.com/602c3c981617aad4ad2160f8/c0e7f6f3-042c-4535-a160-d1032609a757)

**Technical Details**
[ ] Add new copy of text
[ ] Add link to allow the user to Add Custom Network and switch to network for new wallet creation
 

**Acceptance Criteria** 
- Translations are not required for this feature but should go out in next release
- New users have the option to change the RPC URL during opt-in
- New & existing users have the option to change the RPC URL of default networks (cannot delete)
- Existing users token detection and other related data still populates as expected
- Transactions, Swaps, Send, Approve
- Custom RPC for mainnet edit the RPC after wallet creation and confirm you are not seeing duplicate networks
- Test light/dark mode network input boxes not visible

**Comment by coreyjanssen** [comment]
2 versions here. Both have the same language around Infura, but the content format and grouping is a but different (though the same messaging applies in both!). Thoughts/changes @danfinlay? 

### **VERSION 1 (leverages current design)** 
Help us improve MetaMask
We would like to gather basic usage data to improve the usability of our product. 

MetaMask will… 

- Always allow you to opt-out via Settings 
- Send anonymized click and page view events 
- Never collect keys, addresses, transactions, balances, hashes, or any personal information
- Never collect your full IP address. RPC providers collect your IP address when you send a transaction, and Infura _(link to privacy policy)_ is the default for MetaMask. You can change this to a third-party provider in settings.
- Never sell your data for profit. Ever!   

This data is aggregated and is therefore anonymous for the purposes of General Data Protection Regulation (EU) 2016/679. For more information in relation to our privacy practices, see our Privacy Policy.

---------

### **VERSION 2 (leverages onboarding redesign by Sara)** 
**Help us improve MetaMask** 
We would like to gather basic usage data to improve the usability of our product.  

When we gather metrics, it's always:

**Anonymous** 
MetaMask only collects relevant data like your country, but not your specific location.  Your clicks and page views are anonymous.

**Private** 
MetaMask never collects keys, transactions, your full IP address, or any personal information. However, RPC providers collect your IP address when you send a transaction, and Infura _(link to privacy policy)_ is the default for MetaMask. You can change this to a third-party provider in settings. We will never sell your data for profit. Ever!

**Optional** 
You’re in control of whether to share your data. You can always change your preferences and delete your [in-app/extension] usage data via settings at any time.

This data is aggregated and is therefore anonymous for the purposes of General Data Protection Regulation (EU) 2016/679. Please see our Privacy Policy.

**Comment by omnat** [comment]
@kevinghim would love your thoughts on this. Which version do we go ahead with?

**Comment by omnat** [comment]
I like version 2 better. 

One suggestion for
**Private**
MetaMask never collects keys, transactions, your full IP address, or any personal information. However, RPC providers collect your IP address when you send a transaction, and Infura (link to privacy policy) is the default for MetaMask. You can change this to another provider in settings. We will never sell your data for profit. Ever!

Expand this to all 3rd party providers and then talk specifically about the RPC provider, as that's core to the functioning of the wallet. And emphasize the never selling your data.

**Private**
MetaMask never collects keys, transactions, your full IP address, or any personal information. However, we link to 3rd party service providers who might collect this information. Example, RPC providers collect your IP address when you send a transaction, and Infura (link to privacy policy) is the default for MetaMask. You can change this to another provider in settings.
We will never sell your data for profit. Ever!

**Comment by kevinghim** [comment]
I like the second option too. @omnat one thing to be certain of is if mobile also plans to implement [Uncorrelating accounts with RPC endpoints](https://github.com/MetaMask/metamask-extension/issues/15169) like how extension is doing. While information leaking from Infura is unlikely, in the event of that happening, a malicious actor can fingerprint account addresses to correlate to a user.

**Comment by coreyjanssen** [comment]
Is that something that could be addressed in terms and conditions or on an advanced settings screen etc?

**Comment by sethkfman** [comment]
@omnat It looks like version 2 is the preferred version. The team has updated the description and added acceptance criteria. Please confirm and add any further questions/comments. The engineers will start work tonight on enabling the editing of default RPC URLs and UI level details can be finished after your confirmation.

**Comment by coreyjanssen** [comment]
latest version here, reflecting updates to content. @sethkfman 

Help us improve MetaMask
Gathering basic usage data and error reporting helps us improve the usability of MetaMask.

When we gather metrics, it's always:

**Anonymous**
MetaMask only collects relevant data like your country, but not your specific location.  Your clicks and page views are anonymous.

**Private**
MetaMask never collects keys, transactions, your full IP address, or any personal information. However, we link to third-party service providers who might collect this information. For example, RPC providers collect your IP address when you send a transaction. Infura _(link to privacy policy)_ is the default RPC for MetaMask. You can change this to another provider in settings. _(link settings to Settings > Network screen)_ **We will never sell your data for profit. Ever!**

**Optional** 
You’re in control of whether to share your data. You can always change your preferences and delete your extension usage data via settings at any time. _(link settings to screen coming soon here https://github.com/MetaMask/metamask-extension/issues/16709)_

This data is aggregated and is therefore anonymous for the purposes of General Data Protection Regulation (EU) 2016/679. Please see our Privacy Policy.

**Comment by coreyjanssen** [comment]
@sethkfman updated content per the design sync feedback earlier today. this is the current iteration, but note that it's evolving and can potentially change again. just adding here for posterity! :) 

**Help us improve MetaMask**
Gathering basic usage data and error reporting helps us improve the usability of MetaMask. **We will never sell your data for profit. Ever!**

When we gather metrics, it's always:

**Anonymous**
MetaMask only collects relevant data like your country, but not your specific location.  Your clicks and page views are anonymous.

**Private**
Your keys, transactions, full IP address, and any personal information are private. MetaMask doesn’t collect this information, but to enable certain features we use third-party service providers who might. For example, RPC providers collect your IP address when you send a transaction. Infura _(link to privacy policy)_ is the default RPC for MetaMask. You can change this to another provider in settings. _(link settings to Settings > Network screen)_

**Optional** 
You’re in control of whether to share your data. You can always change your preferences and delete your in-app usage data via settings at any time. _(link settings to screen coming soon here https://github.com/MetaMask/metamask-extension/issues/16709)_

This data is aggregated and is therefore anonymous for the purposes of General Data Protection Regulation (EU) 2016/679. Please see our Privacy Policy.
