### ISSUE TITLE
Ensure private RPC and Chain explorer URLs are not sent to sent to MetaMetrics

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-mobile#5302]
Mobile version of https://github.com/MetaMask/metamask-extension/issues/15170

Should be updated on each of:
- Network Added
- Network Switched
- Network Requested
- Network Request Rejected

Could be ok to have a list of the most popular *public* RPCs and log only those and "other".

**Comment by sethkfman** [comment]
Close per PR linked
