### ISSUE TITLE
[PRIVACY] Offline support if user opts out of specific privacy settings

### ISSUE THREAD

**Issue by omnat** [MetaMask/metamask-mobile#5316]
If user opts out of the privacy options above, handle the impact on relevant functionality elegantly (i.e., clearly tell why something isn’t working with error pills, and let app that doesn’t require those APIs function “offline mode”

**Comment by sethkfman** [comment]
@holantonela or @omnat Do we have a list of things that we need to flag or will this be an exploratory effort by the developer?

**Comment by holantonela** [comment]
I don't have a list. Some tiny work on this [here]( https://www.figma.com/file/qmtRKfT3K9DBFZEYFwsS6f/Offline-screen?node-id=102%3A38&t=cu5Or39Gcatp47b6-0).

This is an opportunity to think about connectivity as a spectrum. Low-quality connections, insecure networks, or complete offline may raise different messages to users. 

I'd say that we should have a designer working on this and product scoping this before going to development or a designer and a developer working together on thinking about what is possible to make MM usable in these scenarios.
escenarios.

**Comment by omnat** [comment]
@yanrong-chen worked on this for extension. Where did we land on extension product definition for this @yanrong-chen? 

I think extension already handles some offline scenarios better than mobile today so scope maybe different but worth building upon what is defined already.

In terms of priority though, I'll be sitting through the privacy issues today and this is likely not making it to Q1 epic @sethkfman

**Comment by sethkfman** [comment]
@omnat I don't know if this is a privacy issue but could definitely be considered foundational UI.

**Comment by omnat** [comment]
It's not a privacy issue per-se. But the reason why its in this epic is to ensure we make app as functional as possible even when the user turns OFF APIs for privacy reasons.
