### ISSUE TITLE
Add the ability to edit the RPC url when you are prompted to Add or Switch Networks.

### ISSUE THREAD

**Issue by omnat** [MetaMask/metamask-mobile#5317]
### **Description**
Add the ability to edit the RPC url when you are prompted to Add or Switch Networks.

Example of network change triggers: QR code, Dapps, WalletConnect, SDK

(Must have) Edit their RPC provider for the network (add option to ‘Edit RPC URL’ on the screen, and trigger same screens that we show when user tries to do this from Advanced Privacy Settings (https://app.zenhub.com/workspace/o/metamask/mobile-planning/issues/492)

### **Technical Details**
-  Switching Network Prompt
-  Adding Network Prompt

### **Acceptance Criteria**
-  When a user connects to a Dapp allow the user the option to edit the RPC provider before connecting to the network

### **References**
-   Figma:

**Comment by sethkfman** [comment]
@omnat or @yanrong-chen Do you have any Figma designs for this feature?

**Comment by yanrong-chen** [comment]
@omnat  Hi Omna, do you mind repaste the zenhub link? The current link is no longer valid. Just want to make sure I understand which screen we want to show to users. Thank you!
