### ISSUE TITLE
Add toggle to opt-out of batching balance requests for multiple accounts

### ISSUE THREAD

**Issue by omnat** [MetaMask/metamask-mobile#5321]
## Description
Currently, the `AccountTrackerController` pulls balances for every account in a users wallet at all times. This feature will enable a user to have the ability (within the app in the form of a toggle in Settings) to opt-out of grabbing native token balances for every account in their wallet and only grab it for their selected account.
<img width="339" alt="image" src="https://user-images.githubusercontent.com/10508597/216190950-3eabf88f-da65-4ded-b4ec-c0e6a68288f3.png">

When toggle is off
<img width="241" alt="image" src="https://user-images.githubusercontent.com/10508597/228379774-76f7b9e6-65ec-4b4a-a440-22491c9a6a02.png">

## Technical Details
- [x] Introduce a new toggle to control batching account balance requests in the Security & Privacy page in settings.
- [x] Title of this section is `Batch account balance requests`.
- [x] Description is `We batch accounts and query Infura to responsively show your balances. If you turn this off, only active accounts will be queried. Some dApps won’t work unless you connect your wallet.`. 
- [x] If you turn this toggle off, only the active account in your wallet should be queried. Some dapps won't work unless you connect your wallet.
- [x] If you turn this toggle on, the balances of all of the accounts in your wallet will be queried together.
- [x] Need to patch both `@metamask/preferences-controller(PreferencesController)` and `@metamask/assets-controller(AccountTrackerController)`. Include a new state named `useMultiAccountBalanceChecker: boolean` (default value true) in `PreferencesController` , which the mobile app will use to both track user preferences and set the toggle state. Will also need a setter method `setUseMultiAccountBalanceChecker(val: boolean)` where `val` is the user’s preference for this setting. In the `AccountTrackerController` update refresh method to respect the `useMultiAccountBalanceChecker` state and fetch account balance(s) accordingly. May reference extension's PR in the references section for more info. Follow this PR up with PR to shared controllers repo.
- [x] Add translations
- [x] Add analytics - in `Analytics.js`, add user profile property `Batch account balance requests` with values `OFF` or `ON`
- [x] Default value for toggle is `true`
- [x] If toggle is off, non-active accounts should not show balances on the account selector sheet

## Testing
- When the toggle is OFF:
  - Native currency balance on the main wallet screen should show the same as before
  - Account selector sheet from the wallet screen should only show balance for active account
  - Account selector sheet from the browser screen should only show balance for active wallet account
  - Since native currency balances won't be fetched until you switch accounts, you should see a small delay between switching accounts and the native currency balances showing up. This indicates that the balance wasn't previously available and is only being triggered when you land on the account
  -  User performs these transactions with Native and ERC-20 tokens on popular networks:
      - Swap
      - Send 
      - Deploy contract 

     After the transaction is completed, the token balance should be updated correctly.

- When the toggle is ON:
   - The native currency balance should show the same as before. There should not be a delay between switching accounts and the native currency balance showing since the data should've already been fetched prior to switching accounts.

- Other Scenarios
   -  The user has a previous version of the app and then upgrades to this feature. The account balance should appear  correctly and the toggle should be on. (Needs Product)
   - The user performs these transactions on popular networks:
      -  Swap
      - Send 
      - Deploy contract 
       After the transaction is completed, the token balance should be updated correctly.
       The networks are as follows: Avalanche, Binance, Optimism, Polygon
   -  User imports an account via the private key, disabled toggle. Ensure the account balance only appears for the active account. The user then removes the account and verifies the token balance for the active account is correct. 
   - E2E test should pass 

## Reference
- Mobile Figma Design - https://www.figma.com/file/Tk6yWpz3ReDwX1X8gx4tHJ/Add-option-to-opt-out-of-batching-balance-requests-for-multiple-accounts?node-id=0%3A1&t=OzXE44XmTZ30QNLv-0
- Extension's Issue - https://github.com/MetaMask/metamask-extension/issues/15169
- Extension's PR - https://github.com/MetaMask/metamask-extension/pull/16746/files

**Comment by sethkfman** [comment]
@Cal-L Lets split this into two tickets 
- Controllers leverage patch-package dependency similar to changes related to: https://github.com/MetaMask/metamask-extension/pull/16746
- For mobile have a UI level ticket to add batch toggle to advance privacy

**Comment by omnat** [comment]
There's no extra requirement from my side for this, the definition we can keep consistent with how extension handled this. Moving to Ready for work for eng team to add technical details @sethkfman

**Comment by sethkfman** [comment]
Check with Core(shared libraries) group. If this will get fix per the Network refactor. @Gudahtt

**Comment by Gudahtt** [comment]
I do not expect the network controller related work to fix this, as the problem is not in that controller. It's with the asset controllers (especially the one that tracks account balances).

**Comment by sethkfman** [comment]
Split into 2 tickets one for controller & UI

**Comment by omnat** [comment]
Ah I see the ticket detailing. 
Some questions/suggestions:

1. What's the default? What did we keep default in extension? I'd recommend the more privacy preserving one, unless it breaks the app behavior in a significant way. 
2. I don't understand what's this consequence "Some dApps won't work unless you connect your wallet". You have to connect your wallet irrespective of this setting right? So what is the change in app behavior if accounts aren't queried to Infura in a batch? Will the view of Account switcher not show up-to-date account balance summary (only cacbelonhed from last time that account was queried?)? We don't have an "All accounts" view. I'd also explain user the trade-off of turning it on is on their privacy; i.e., Infura can determine that all the accounts related to their SRP belong to the same person (people won't know what it means to query Infura with batched request). @coreyjanssen thoughts on copy here?

**Comment by cortisiko** [comment]
@sethkfman @Cal-L Questions from a QA POV:

- Is this feature exclusive to mainnet? 
- It seems like this feature only apply to native tokens, What about ERC-20 tokens? Should we notice any difference in behavior there? 
- Does token detection affect this feature? For example If token detection is on and I toggle account balance batching off, should detect tokens still appear in my account? Meaning should I see the option on the wallet view "x tokens have been detected in your account"? If yes, when I import tokens via token detection, what should be the behavior?

**Comment by sethkfman** [comment]
Is this feature exclusive to mainnet? Or this feature only applies to infura supported networks?
- Same functionality for all networks.  This specific for user balance.
It seems like this feature only apply to native tokens, What about ERC-20 tokens? Should we notice any difference in behavior there?
- Non-native currency tokens are not related
Does token detection affect this feature? For example If token detection is on and I toggle account balance batching off, should detect tokens still appear in my account? Meaning should I see the option on the wallet view "x tokens have been detected in your account"? If yes, when I import tokens via token detection, what should be the behavior?

**Comment by Cal-L** [comment]
Note - What should we show on the account selector sheet, where it shows multiple accounts? It might not make sense to show $0 balance as long as other balances are not fetched. Should we remove the fiat balance on those instead?

Another note - Great opportunity to introduce loading states

**Comment by Cal-L** [comment]
@kevinghim What was the default value that extension set when this feature was introduced?

**Comment by Cal-L** [comment]
> Does token detection affect this feature? For example If token detection is on and I toggle account balance batching off, should detect tokens still appear in my account? Meaning should I see the option on the wallet view "x tokens have been detected in your account"? If yes, when I import tokens via token detection, what should be the behavior?

This feature is not related to token balances / detection.

**Comment by kevinghim** [comment]
> @kevinghim What was the default value that extension set when this feature was introduced?

The default value is True. As in, batch account balances. User has an option to opt out during onboarding as well as in settings if previously opted in.

**Comment by Cal-L** [comment]
> What's the default? What did we keep default in extension? I'd recommend the more privacy preserving one, unless it breaks the app behavior in a significant way. So my question is; how does it break the app's behavior?

The default value will be true. So by default, the app behavior is the same as before.

**Comment by Cal-L** [comment]
> I don't understand what's this consequence "Some dApps won't work unless you connect your wallet". You have to connect your wallet irrespective of this setting right? So what is the change in app behavior if accounts aren't queried to Infura in a batch? Will the view of Account switcher not show up-to-date account balance summary (only cacbelonhed from last time that account was queried?)? We don't have an "All accounts" view. I'd also explain user the trade-off of turning it on is on their privacy; i.e., Infura can determine that all the accounts related to their SRP belong to the same person (people won't know what it means to query Infura with batched request). @coreyjanssen thoughts on copy here?

cc @coreyjanssen for visbility

**Comment by Fatxx** [comment]
A few questions/notes after implementing the solution:

- As we store account balances by default meaning that when a user opens the app and all balances are present when the user opt-out to not enable multi-account balances, should we "zero" the other balances besides the current address?

- If we don't reset to zero other accounts I'm afraid that the end user will just see outdated values, for example:
<img width="384" alt="Screen Shot 2023-03-28 at 17 31 24" src="https://user-images.githubusercontent.com/575479/228307466-f071744f-091f-467f-8ccc-6d5a9c2d4677.png">

I'm on "Account 2" (this has actually 0 balance) with the toggle off but I still see the balances for other accounts since they were fetched before I opt out.

**Comment by Cal-L** [comment]
@yanrong-chen Fatia and I had a question on what should be shown if we're not fetching balances for other accounts on the account selector screen. How should we display the balance section for non-fetched accounts?

**Comment by yanrong-chen** [comment]
Since the default is to fetch all balances and users would have to manually disable it, I would suggest that we just not show anything for other accounts
<img width="372" alt="image(6)" src="https://user-images.githubusercontent.com/59982439/228365438-6d872be2-05f9-4bf5-a49b-85c4f0ef953c.png">

**Comment by sethkfman** [comment]
Translations and Analytics are not required to merge this ticket. Per standup discussion.
