### ISSUE TITLE
[Bug]: Metamask v5.11.0 (1018) unable click "Confirm" while doing any transaction

### ISSUE THREAD

**Issue by kahshin03** [MetaMask/metamask-mobile#5323]
### Describe the bug

Hi Metamask Team,

I am facing the issue below,

When doing purchase / minting, transfer by using android devices, stuck at the Metamask confirm section and only able to click reject. 

https://drive.google.com/file/d/1eexzmwQ5IA4JEIq8YlBci55GceDB3cFi/view?usp=share_link
Above link is the situation when click the "Confirm" button

Please assist to observe the issue.

Thank you, good day. 

### Steps to reproduce

1. Google Playstore
2. Install Metamask latest version which is v5.11.0
3. Setup the wallet
4. Login wallet using QR Code for Wallet Connect
5. Proceed transfer

### Error messages or log output

```shell
"Confirm" button no respond from the system
```

### Version

v5.11.0

### Browser

Chrome

### Operating system

Other (please elaborate in the "Additional Context" section)

### Additional context

Operating system: Android, from Metamask v5.11.0 download from Google Playstore.

**Comment by kahshin03** [comment]
Hi @blackdevelopa let me describe the issue in more details.

Smart contract: 
https://bscscan.com/token/0x25102c5af2d4faa83ddbd36d9f6af5d9c2b84093

Network RPC (Binance Testnet): 
https://data-seed-prebsc-2-s1.binance.org:8545/
https://bsctestapi.terminet.io/rpc
https://nd-236-609-532.p2pify.com/34a3dc9d67895924dd17270804765e5b

Chain id: 97

Steps to reproduce
1. Download and Install Metamask v5.11.0
2. Browse to https://nutsmet.xyz/login
3. Click the connect
4. Select WalletConnect
5. Using Metamask QR code scanner to scan the code login
6. Go to https://nutsmet.xyz/customer/profile and scroll down find BEP20 > My Assets
7. Click Transfer
8. Try to transfer the minimum amount of BNB to 0x388a698322267b9e999868c31ad1afbbd26ed701 by using BEP20 network.

**Comment by ClaireMao1996** [comment]
This is the same as https://github.com/MetaMask/metamask-mobile/issues/5260

**Comment by kahshin03** [comment]
> This is the same as #5260

any solution for now?

**Comment by blackdevelopa** [comment]
Hey @kahshin03 thank you for providing these details. From the app you shared, https://nutsmet.xyz/customer/profile. I can only select DCO coin for transfer. Do you mind sending the minimum value that allows me test the transfer option with that coin using the BEP20 network. I can't seem get to get that coin in BSC testnet. Here's an address: `0xCd5Ddd347B19A159731A5046f235328380B00bb7`

**Comment by kahshin03** [comment]
![image](https://user-images.githubusercontent.com/117708729/205197590-2203600f-e6cd-4994-bc92-21d5530bdea4.png)
can you show me the as image above, because I tried to transfer but can't reach

**Comment by kahshin03** [comment]
@blackdevelopa Hi, done transfer 3 token to your wallet. Please check, thank you very much.

**Comment by blackdevelopa** [comment]
Hey @kahshin03, thanks for the token sent. I was able to test and this is the result I find. Let me know if I missed something.

App Version: MM v5.11.0 (1018)
Network: BSC testnet
Steps: I used two devices (iOS and Android). The Android interacted with the dapp (https://nutsmet.xyz/login) while the iOS wallet was used for approvals and confirmations. You should have both videos playing simultaneously to follow the interaction.



https://user-images.githubusercontent.com/29962968/205683254-9fde66ce-e220-4b18-8744-1df80a893ae1.MP4

https://user-images.githubusercontent.com/29962968/205683425-6514214b-01b3-4981-a888-98dcdd289cd2.mp4

**Comment by kahshin03** [comment]
@blackdevelopa Hi, I has sent you another 3 token for test.

For Metamask iOS version is ok.

The Android version have issue with unable to click the confirm, that's mean maybe need to try click the confirm button on the android device.

Step to replicate issue:
1. download and install Metamask on your android device
2. import your Metamask Wallet to the android device
3.  go to https://nutsmet.xyz/login, login your account by using "Tap to Connect"
4.  Metamask prompt out and then you may accept let the web access your wallet
5. try to transfer the money again

Thank you very much and good day for you.

**Comment by blackdevelopa** [comment]
Hey @kahshin03 I tried and still the same result. It works regardless of the devices. The video is below. 

PS: If it's possible, can you make a screen record of this transaction from start to finish. It might help with something we are both missing. Also capture the version you are on.

https://user-images.githubusercontent.com/29962968/205920520-eff3344a-82de-463d-b9af-6a604c534719.mp4

https://user-images.githubusercontent.com/29962968/205919935-ac6de42f-58e0-4b84-bdff-3a345eca7bdc.MP4

**Comment by kahshin03** [comment]
Hi @blackdevelopa , we test cannot do. May I know the RPC you using? 

Example like this: 

![IMG_1777](https://user-images.githubusercontent.com/117708729/206060091-6fb1b7f7-7b17-445a-8963-0a3cc2fec461.png)

**Comment by blackdevelopa** [comment]
Hey, @kahshin03 here's the network detail.

![Screenshot_20221207-110254_MetaMask](https://user-images.githubusercontent.com/29962968/206148951-51221af4-ee1c-40b9-b2ab-6300ab64b442.jpg)

**Comment by tommasini** [comment]
Hey @kahshin03 , we are having trouble trying to mint. https://recordit.co/EcoTf96UUB

Could you elaborate on how we can try it?

**Comment by bschorchit** [comment]
Is this still an issue, @kahshin03?
