### ISSUE TITLE
iOS Repeat tx received notification

### ISSUE THREAD

**Issue by plasmacorral** [MetaMask/metamask-mobile#5354]
**Describe the bug**
When mainnet funds are received from an account not currently in the keyring, the toast notification "You received ...." is repeating.

Edited to add: seems to be limited to iOS.  Was not able to reproduce on android 11 with sch-i515f on build 1024 v5.12.

**Video**
iOS: Toast is displayed 7x in under a minute
https://recordit.co/4Of9dXfHRJ

Unable to reproduce on android:
https://recordit.co/NaHnMO7zEo

**To Reproduce**
_Steps to reproduce the behavior_
1. Send mainnet funds from another source (not within existing accounts).  
2. flip back and forth between activity and wallet view within the app drawer
3. note that toasts repeat

**Expected behavior**
One and done.

**Smartphone (please complete the following information):**
 - iOS 16.1.2
 - iPhone Xs
 - Observed in V5.12 build 1024 (not able to reproduce in 5.11)

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by tommasini** [comment]
Me and @Fatxx  were trying to replicate this on branch release/5.12.1 with ios simulator version 16.1, and the notification it's only appeared one time 
We navigate between the activity view and wallet view, and the notification does not appear a second time
