### ISSUE TITLE
In-app wallet doesn't respond to the web.

### ISSUE THREAD

**Issue by syukurER** [MetaMask/metamask-mobile#5356]
**Describe the bug**
_Wallet doesn't respond to user action_

**Screenshots**
_<img width="328" alt="Screenshot 2022-12-01 at 13 10 20" src="https://user-images.githubusercontent.com/119549769/205794535-e6a43d14-77a9-4054-8f3d-44ac7758865f.png">_

https://user-images.githubusercontent.com/119549769/205796467-bf0fd59c-41c8-461d-8cc8-404225085eaf.mp4

**To Reproduce**
_Steps to reproduce the behavior_
1. Go to our test site 'https://kenka-land.web.app/'
2. Username : username
Password : password
3. Connect to MetaMask wallet at the top next to language selection.
4. Put in price value to bid.
5. Click '入札'
6. MetaMask wallet should be shown to enable the transaction.

**Note**
We're using tBNB and our test token for this testing purpose. _Please supply wallet address to get test token._

**Expected behavior**
_MetaMask should be open and shown to enable transaction to happen_

**Smartphone (please complete the following information):**
 - Device: iPhone 14
 - OS: iOS 16
 - App Version 5.11

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by tommasini** [comment]
@syukurER thanks for reporting!
I'm not being able to reproduce it, for me everything went as expected
https://recordit.co/EGrbJhtMMY

**Comment by J-Eta** [comment]
> @syukurER thanks for reporting! I'm not being able to reproduce it, for me everything went as expected https://recordit.co/EGrbJhtMMY

it has a weird respond and it only happen to tester which is located in Japan. Is there any region difference of the app?

**Comment by tommasini** [comment]
No, the wallet should behaviour like on the recording that I sent, are you experiencing this consistently?

**Comment by SUPPORTTEAMHERR** [comment]
> **Describe the bug**
> _Wallet doesn't respond to user action_
> 
> **Screenshots**
> _<img width="328" alt="Screenshot 2022-12-01 at 13 10 20" src="https://user-images.githubusercontent.com/119549769/205794535-e6a43d14-77a9-4054-8f3d-44ac7758865f.png">_
> 
> https://user-images.githubusercontent.com/119549769/205796467-bf0fd59c-41c8-461d-8cc8-404225085eaf.mp4
> 
> **To Reproduce**
> _Steps to reproduce the behavior_
> 1. Go to our test site 'https://kenka-land.web.app/'
> 2. Username : username
> Password : password
> 3. Connect to MetaMask wallet at the top next to language selection.
> 4. Put in price value to bid.
> 5. Click '入札'
> 6. MetaMask wallet should be shown to enable the transaction.
> 
> **Note**
> We're using tBNB and our test token for this testing purpose. _Please supply wallet address to get test token._
> 
> **Expected behavior**
> _MetaMask should be open and shown to enable transaction to happen_
> 
> **Smartphone (please complete the following information):**
>  - Device: iPhone 14
>  - OS: iOS 16
>  - App Version 5.11
> 
> 
> -------------------------------------------------------------
> _to be added after bug submission by internal support / PM_
> **Severity**
> 
> 
> - How critical is the impact of this bug on a user?
> - Add stats if available on % of customers impacted
> - Is this visible to all users?
> - Is this tech debt?
> 

We'd be happy to look into this for you. kindly file a support ticket below 
https://forms.gle/Wmpm6NLzYm9uXYuU9
