### ISSUE TITLE
Uniswap connection not available

### ISSUE THREAD

**Issue by jimango** [MetaMask/metamask-mobile#5364]
**Describe the bug**
Connect to Uniswap on Metamask mobile Android not available. This issue is happening on my Samsung S20 Ultra 5G, model SM-G988B/DS, Android version 13.

**Notice**
I am able to connect to Uniswap using Metamask browser app on PC. So i suspect this is a bug in the mobile app. However I am able to connect with Metamask browser app using 1inch exchange.

**Screenshots**
![Screenshot_20221207_194544_MetaMask](https://user-images.githubusercontent.com/15493416/206269854-250bfa10-7ca5-48e2-8929-31fc4c35bfb4.jpg)

**Smartphone:**
 - Device: Samsung S20 Ultra 5G
 - OS: Android version 13
 - App Version: 5.11.0

-------------------------------------------------------------

**Comment by tommasini** [comment]
@jimango thanks for reporting!
It's under investigation right now

**Comment by SUPPORTTEAMHERR** [comment]
> **Describe the bug**
> Connect to Uniswap on Metamask mobile Android not available. This issue is happening on my Samsung S20 Ultra 5G, model SM-G988B/DS, Android version 13.
> 
> **Notice**
> I am able to connect to Uniswap using Metamask browser app on PC. So i suspect this is a bug in the mobile app. However I am able to connect with Metamask browser app using 1inch exchange.
> 
> **Screenshots**
> ![Screenshot_20221207_194544_MetaMask](https://user-images.githubusercontent.com/15493416/206269854-250bfa10-7ca5-48e2-8929-31fc4c35bfb4.jpg)
> 
> **Smartphone:**
>  - Device: Samsung S20 Ultra 5G
>  - OS: Android version 13
>  - App Version: 5.11.0
> 
> 
> -------------------------------------------------------------

We'd be happy to look into this for you. kindly file a support ticket below 
https://forms.gle/Wmpm6NLzYm9uXYuU9

**Comment by hesterbruikman** [comment]
Closing and continuing to track in #5290
