### ISSUE TITLE
Recording voice in the Metamask native browser(android and IOS) not working

### ISSUE THREAD

**Issue by MnogoDobur** [MetaMask/metamask-mobile#5367]
**Describe the bug**
Me and my team are developing a dapp which allows the user to record their voice and mint it on the blockchain as an NFT. Everything is working fine on Desktop (using MetaMask’s extension), but the moment we try to test it (enable voice recording) on mobile (andoid/IOS) MetaMask responds with error “Error: no Audio”. Same error we had on Brave and Chrome before we allowed the app to record voice from the permissions menu, BUT MetaMask doesn’t even have that function. We suspect that Metamask's mobile app cannot record voice or needs special permissions for this (which cannot be found in the app or app settings). Is this the case?

**Screenshots**
![de0345b74f88fdc3b0113494a70e9fc8e56b17f6_2_354x750](https://user-images.githubusercontent.com/28307240/206376863-b80d9231-0e75-444d-983f-e0dd09aa8709.jpeg)

**To Reproduce**
_Steps to reproduce the behavior_
1. Load up metamask mobile on any Android or IOS phone.
2. Open any website in the native Metamask browser which records audio and try to record.
3. See error - the app will respond with "no audio" and will do **nothing** . In some rare occasions Metamask will flash "no permissions" error for a second before showing the "no audio" error. 

**Expected behavior**
Expected behavior should be that the app ask for permission, or beforehand, and then records the user's audio.

**Smartphone (please complete the following information):**
 - Device: Any - we did test with Samsung, Iphone and Huawei.
 - OS: Both IOS and Android latest versions (Android - 12.0.0_r42 , IOS - 16.1.2)
 - App Version 5.12.0(1024) Latest from December 8 2022.

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by tommasini** [comment]
Probably related with https://github.com/MetaMask/metamask-mobile/issues/3907

**Comment by tommasini** [comment]
Since this issue is duplicated I will close it, the progress will be tracked on this one https://github.com/MetaMask/metamask-mobile/issues/3907
