### ISSUE TITLE
Remove "Send" button on NFTs for iOS

### ISSUE THREAD

**Issue by sethkfman** [MetaMask/metamask-mobile#5384]
### **Description**

The iOS application needs to disable the "Send" button for ERC-721 NFTs. The details view for the ERC-721 NFT there is a "Send" button which needs to be hidden on the iOS applications. This is a policy requirement from iOS. 

![IMG_8222.PNG](https://images.zenhubusercontent.com/602c3c981617aad4ad2160f8/f92a73cd-d47e-480c-843b-304787fe29b6)

![IMG_8223.PNG](https://images.zenhubusercontent.com/602c3c981617aad4ad2160f8/cf19587f-4bc8-48cf-944d-01541b5fbf78)

### **Technical Details**

-   On iOS only, hide the send button on ERC-721 NFTs
-   On iOS only, disable the display/sending NFT assets in the send flow
-   All other elements on the screen should maintain their position

### **Acceptance Criteria**

-   Are metrics required? NO
-   Are translations required? NO
-   Send button is disabled on all iOS apps. 
-   Ensure no dapp interaction functionality with NFTs are affected with this update. 

Scenario: Android users are able to send NFTs in Send flow
Scenario: iOS users are NOT able to send NFTs in Send flow
Scenario: Android users are able to send NFTs from NFT details view
Scenario: iOS users are NOT able to send NFTs from NFT details view
Scenario: importing an NFT and trying to send
Scenario: minting an NFT and then trying to import then send it
Scenario: trying to send an auto detected & displayed NFT

### **References**

-   References go here.
-   Issue numbers. Links.
-   Slack threads.
-   Etc.

**Comment by omnat** [comment]
Looks good. A few questions before we finalize

1. Specifying ERC- 721 NFTs, because ERC 1155s you already can't send? Are there any other NFT standards that user can view in their MM (e.g., by importing manually) to consider as well?

2. Can you say more about the red cross-outs on the screenshot on NFT details? (Source, Asset contract)

**Comment by sethkfman** [comment]
Specifying ERC- 721 NFTs, because ERC 1155s you already can't send? Are there any other NFT standards that user can view in their MM (e.g., by importing manually) to consider as well?

Can you say more about the red cross-outs on the screenshot on NFT details? (Source, Asset contract)
