### ISSUE TITLE
Gas fee is not calculated & involved to the transaction

### ISSUE THREAD

**Issue by ChallengeHandler** [MetaMask/metamask-mobile#5387]
**Describe the bug**
I'm trying to send some ETH to another wallet.
But once I've tried to make a transaction from the last confirmation screen I cannot see any gas fee calculated and the total amount required.
Anyway I clicked the Send button. The result is terrible. That transaction is not proceed anymore and I cannot even speed up or cancel that transaction.
For both cases the gas fee is not calculated again and it retrieves error.

**Screenshots**
![image](https://user-images.githubusercontent.com/115472206/207138687-922e04cb-ef0c-4e91-ac02-bfd117205f7b.png)
![image](https://user-images.githubusercontent.com/115472206/207138824-9e95e11a-dbf9-469b-b6be-f6a23332b6fd.png)
![image](https://user-images.githubusercontent.com/115472206/207138935-d3130197-38fd-4f77-97b3-4bd66288cd8b.png)

**To Reproduce**
_Steps to reproduce the behavior_
1. Click on eth
2. Click send
3. Add address
4. Set amount
5. See error

**Expected behavior**
_A clear and concise description of what you expected to happen_
I want to see the gas fee and confirm the transaction.

**Smartphone (please complete the following information):**
 - Device: Memu emulator
 - OS: 7.1 (64bit)
 - App Version [e.g. 1.0.0] - 5.11.0 (1018)

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by tommasini** [comment]
@ChallengeHandler Thank you for reporting!

I will bring this back to our team

**Comment by tommasini** [comment]
We notice that you are using app version 5.11.0, can you update to the latest version and try to replica te it? Thank you!

**Comment by ChallengeHandler** [comment]
@tommasini , Thank you for your reply.
I tried with the latest version.
But the result is same.

**Comment by tommasini** [comment]
@ChallengeHandler we are trying to understand what's going wrong.
Can you send us a recording of all steps you make when you open the app and end on the confirm transaction screen?

**Comment by chrisleewilcox** [comment]
@ChallengeHandler this may be fixed in 5.13.0 with our update for transaction gas fees.  Please confirm with 5.13.0 when it is released.
