### ISSUE TITLE
Custom nonce unable to be edited on Token Spending approval

### ISSUE THREAD

**Issue by plasmacorral** [MetaMask/metamask-mobile#5395]
### **Description**
When a user enables custom nonce in Settings>Advanced>custom Nonce, they should always have the nonce displayed and the ability to edit the value.  

### **Acceptance Criteria**

-   When a user has custom nonce enabled and is submitting a Token Spending approval, they should be able to see and edit the nonce prior to confirming the transaction.

Scenario: Custom nonce in token approval
- GIVEN the user has enabled custom nonce in Settings>Advanced
- AND is connected to the MetaMask test dapp
- WHEN a user taps "Create token" under "Send tokens" and confirms the transaction
- AND once the contract deployment is complete taps to "Approve Tokens"
- THEN the approval modal should display and allow editing of nonce value

### **References**

- https://recordit.co/L47hiW5TCx
-![Screenshot 2022-12-13 at 5 46 54 PM](https://user-images.githubusercontent.com/32695229/207463694-9ae2da11-0634-406d-bd07-c028f0c54151.png)

**Comment by bschorchit** [comment]
We'll prioritize the following issue https://github.com/MetaMask/MetaMask-planning/issues/177 and make sure we enable the nonce to be customized on that new screen.

**Comment by bschorchit** [comment]
For reference nonce editing should be added to this screen: https://github.com/MetaMask/MetaMask-planning/issues/177 
cc: @holantonela

**Comment by bschorchit** [comment]
The existing nonce component (see screenshot below) should be added to the `review spending cap` screen that is being worked on https://github.com/MetaMask/MetaMask-planning/issues/177 . 
It should not be added to the `set spending cap` screen (https://github.com/MetaMask/MetaMask-planning/issues/178).

![IMG_EA240CAEA952-1](https://user-images.githubusercontent.com/34968356/221642055-6c20a4b7-7121-4a31-a8be-d899c2ebcf2e.jpeg)
