### ISSUE TITLE
ENS handling error for names without a registered address

### ISSUE THREAD

**Issue by plasmacorral** [MetaMask/metamask-mobile#5396]
### **Description**

When an ENS name does not have an address registered, we expect to return an [error](https://github.com/ethjs/ethjs-ens#enslookup-name-) to users.  However, on mobile [evan.eth](https://app.ens.domains/name/evan.eth/details) currently resolves to 0x0000.....0000 (see right image in references).  

On extension we return the expected error (see left image in references)

Currently mobile and extension are not using the same packages and we have an opportunity to provide a more consistent user experience.

### **Technical Details**

-   Mobile uses this [package](https://github.com/ethjs/ethjs-ens) (util/ENSUtil.js line 38), but extension uses [ethers](https://docs.ethers.org/v5/api/providers/provider/#Provider-ResolveName) (ui/ducks/domain.js line 167).

### **Acceptance Criteria**

-   When user attempts to send to an ENS address that does not have an address registered, an error is shown that prohibits sending funds
-   When attempting to send to evan.eth the ENS name not found error is returned instead of 0x0000...0000

Scenario: Attempting to send to ENS name without a registered address
- GIVEN a user attempts to send to an ENS name
- WHEN that ENS name does not have address registered
- THEN "ENS name not found" error is presented
- AND "0x0000...0000" is NOT set as the "To:" address

### **References**

<div style="display: inline-block"> <img width="190" src="https://user-images.githubusercontent.com/32695229/207732115-70633fd4-f730-441d-8e4d-61e55fa8be05.png"><img width="220" src="https://user-images.githubusercontent.com/32695229/207732510-01b2d2ff-1bb3-44cb-b35e-880be295fea8.png"></div>

**Comment by bschorchit** [comment]
As a solution we could just persist this existing warning for ens without registered address.

![IMG_3536](https://user-images.githubusercontent.com/34968356/214119025-cf4fafae-71b9-4d2a-9913-1753b783ed8a.PNG)

**Comment by blackdevelopa** [comment]
I think this is a known [issue](https://github.com/ethjs/ethjs-ens/issues/13). I think we should consider  switching mobile to `ethers` like in the extension
