### ISSUE TITLE
[Bug] Xiden Network | Unable to Modify Gas Price Above 0

### ISSUE THREAD

**Issue by deshvin** [MetaMask/metamask-mobile#5397]
**Describe the bug**
On Xiden network, unable to modify gas price above 0. 
Error: Gas price is higher than necessary.

**Screenshots**
https://user-images.githubusercontent.com/2859402/207738390-818032d7-c02d-4d70-b1bd-abaec3a03dac.mp4

**To Reproduce**
_Steps to reproduce the behavior_
1. Make Xiden the current active network
2. Initiate a token transfer
3. Tap on estimated gas fee amount to bring up the gas options
4. Try to change the Gas price field to something above 0 (either manual entry or the + button)

**Network Details**
Xiden
https://rpc.xiden.com/
5381
XIDEN

**Expected behavior**
I should be able to set the gas price above 0 gwei without an error.
Modifying the gas price on extension works without issue.

**Smartphone (please complete the following information):**
 - Device: <model unknown>
 - OS: Android <version unknown>
 - App Version 5.11.0 & 5.12.0

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by tommasini** [comment]
@deshvin Thanks for reporting! 
I will bring this issue to our team
