### ISSUE TITLE
iOS: Creating your wallet takes ?forever if user denies biometrics system request

### ISSUE THREAD

**Issue by olenapankina** [MetaMask/metamask-mobile#5404]
**Tested on**
iPhone Xr iOS 16.1.1, 
Build: prod 5.11.0, prod 5.12.0, TestFlight 5.12.0
Not reproducible on Samsung Galaxy M21 Android 12, One UI Core version 4.1 with Biometrics configured 

**Steps to reproduce:**
1. Launch freshly installed application
2. Observe "Create a wallet" screen: biometrics allowed is ON by default
3. Tap "Create password" button
4. Observe getting redirected to the "Creating your wallet" screen
5. Deny system request to use FaceID/TouchID
6. Observe

**Actual result:** Step 6 - app is in a constant "Creating your wallet" state
Note: the same screen is in the background for 2-3 hours, the app is not crashing or relaunching. After manually relaunching the application _wallet is created_
**Expected result:** TBD
Since we are making a decision instead of a user with biometrics allowed being ON by default, I would suggest not showing any error messages.

https://user-images.githubusercontent.com/116747263/207965692-03cb5e8e-c754-48e2-9f36-3c27e97e1f04.mov

**Comment by WalletSupportt** [comment]
> **Tested on**
> iPhone Xr iOS 16.1.1, 
> Build: prod 5.11.0, prod 5.12.0, TestFlight 5.12.0
> Not reproducible on Samsung Galaxy M21 Android 12, One UI Core version 4.1 with Biometrics configured 
> 
> **Steps to reproduce:**
> 1. Launch freshly installed application
> 2. Observe "Create a wallet" screen: biometrics allowed is ON by default
> 3. Tap "Create password" button
> 4. Observe getting redirected to the "Creating your wallet" screen
> 5. Deny system request to use FaceID/TouchID
> 6. Observe
> 
> **Actual result:** Step 6 - app is in a constant "Creating your wallet" state
> Note: the same screen is in the background for 2-3 hours, the app is not crashing or relaunching. After manually relaunching the application _wallet is created_
> **Expected result:** TBD
> Since we are making a decision instead of a user with biometrics allowed being ON by default, I would suggest not showing any error messages.
> 
> https://user-images.githubusercontent.com/116747263/207965692-03cb5e8e-c754-48e2-9f36-3c27e97e1f04.mov

We'd be happy to look into this for you. kindly file a support ticket below 
https://forms.gle/Wmpm6NLzYm9uXYuU9

**Comment by chrisleewilcox** [comment]
Issue may be fixed in refactoring of https://github.com/MetaMask/metamask-mobile/pull/5374.  Please confirm when refactor is complete.
