### ISSUE TITLE
Update test network to match extension

### ISSUE THREAD

**Issue by sethkfman** [MetaMask/metamask-mobile#5406]
### **Description**

Currently the mobile app is displaying old test networks that have been deprecated. Update the app to display the two currently supported test networks post-merge.

### **Technical Requirements**
- Add Remove test network Kovan, Ropsten, Rinkeby
- Add Sepolia test network
   - Default Details
![Screenshot 2022-12-16 at 7.50.36 AM.png](https://images.zenhubusercontent.com/602c3c981617aad4ad2160f8/fed6993a-72ea-4bdb-aede-ae3e0167c77a)

### **Acceptance Criteria**
- User can no longer see test network Kovan, Ropsten, Rinkeby
- User can see Sepolia test network
 
Scenario: 
Scenario:

**Comment by WalletSupportt** [comment]
> ### **Description**
> 
> Currently the mobile app is displaying old test networks that have been deprecated. Update the app to display the two currently supported test networks post-merge.
> 
> ### **Technical Requirements**
> - Add Remove test network Kovan, Ropsten, Rinkeby
> - Add Sepolia test network
>    - Default Details
> ![Screenshot 2022-12-16 at 7.50.36 AM.png](https://images.zenhubusercontent.com/602c3c981617aad4ad2160f8/fed6993a-72ea-4bdb-aede-ae3e0167c77a)
> 
> ### **Acceptance Criteria**
> - User can no longer see test network Kovan, Ropsten, Rinkeby
> - User can see Sepolia test network
>  
> Scenario: 
> Scenario:
> 

We'd be happy to look into this for you. kindly file a support ticket below 
https://forms.gle/Wmpm6NLzYm9uXYuU9

**Comment by lukelu0520** [comment]
+1 this request is significant.
