### ISSUE TITLE
Android: when only Face Recognition is set up - metamask doesn't use it as Biometrics

### ISSUE THREAD

**Issue by olenapankina** [MetaMask/metamask-mobile#5407]
Samsung Galaxy M21 Android 12, One UI Core version 4.1 (Face Recognition&Fingerprints biometrics option)
Prod build 5.12.1 (1028)

**Steps to reproduce:** 
1. Set up your device with Face Recognition and Fingerprints
2. Launch metamask
3. Observe: user does have the ability to use Biometrics
4. Remove Fingerprints
5. Launch metamask
6. Observe: user doesn't have the ability to use Biometrics
7. Create a wallet
8. Observe: user doesn't have the ability to use Biometrics
9. Add Fingerprints
10. Observe: app relaunches - user is on the Welcome screen. Unlock with Biometrics option is ON by default

**Actual result:** user is not able to use Face Recognition as a biometrics option
**Expected behavior:** user is able to use Face Recognition and/or Fingerprints as a biometrics option

**Note:** reproducible in an initial (first) launch when only Face Recognition is set up
Was not tested on Android devices with Face Recognition only option available as Biometrics

Testing notes: if this is unexpected behavior - add TC to the regression flow after the fix.

https://user-images.githubusercontent.com/116747263/208141555-9d831dea-3702-467e-9444-b407b1b05df6.mov

**Comment by hesterbruikman** [comment]
Can still reproduce on 7.3.1
