### ISSUE TITLE
[Bug]: MM mobile (iOS) IERC20 approve always fail

### ISSUE THREAD

**Issue by OctoD** [MetaMask/metamask-mobile#5427]
### Describe the bug

On iOS, since version 5.12.0

All calls to `approve` fail

### Steps to reproduce

Steps to reproduce:

Go to https://coston-explorer.flare.network/token/0x8048C36831d8F7e40365Cf11cff6Db66293ec9e9/write-contract

Enter your address in approve->spender

Enter a value

Push write

This happens on iOS since version 5.12.0

### Version

5.12.0

### Build type

None

### Browser

Other (please elaborate in the "Additional Context" section)

### Operating system

Other (please elaborate in the "Additional Context" section)

**Comment by tommasini** [comment]
Hey @OctoD and @alexdupre , thanks for reporting!

We are trying to reproduce this, could you provide the RPC URL and chain ID of the network you are using to help us reproduce it?

We are having some issues, trying to replicate with the explorer you provided https://recordit.co/SyTC0ypmCP

**Comment by alexdupre** [comment]
Here you can find the RPC endpoints for Coston & Coston2: https://docs.flare.network/dev/reference/network-configs/

**Comment by Helpcenter101** [comment]
@alexdupre We'd be happy to look into this for you. kindly file a support ticket below 
https://forms.gle/Wmpm6NLzYm9uXYuU9

**Comment by Helpcenter101** [comment]
@OctoD We'd be happy to look into this for you. kindly file a support ticket below 
https://forms.gle/Wmpm6NLzYm9uXYuU9

**Comment by bschorchit** [comment]
Closing as fixed by https://github.com/MetaMask/metamask-mobile/pull/5440 - let us know in case this is still happening!
