### ISSUE TITLE
No emit event from mobile metamask wallet on transaction rejection

### ISSUE THREAD

**Issue by devsalman247** [MetaMask/metamask-mobile#5434]
I'm building dapp in react with integration of my own smart contract deployed on bsc testnet... I'm using walletconnect to connect wallet to connect my mobile wallet users and web3js to interact with smart contract and wallet.. I'm sending contract write transaction from my app to mobile metamask but when I reject transaction then I get no response from metamask... No rejected message and also not sending any response to my app..It's only in case of my contract approve function not others..
My contract:
https://testnet.bscscan.com/address/0xf3e5a8b4b290f0841506076e086f09ec1184fc78#readContract

**Comment by tommasini** [comment]
Thanks for reporting @devsalman247 , I will bring this to our team!

**Comment by chrisleewilcox** [comment]
@cortisiko once WalletConnect v2.0 is implemented we should test this.  Expected that this will also support WalletConnect v1 and v2 with different dapps.

- dapp with WallectConnect v1
- dapp with WallectConnect v2
