### ISSUE TITLE
Performance issue on Android

### ISSUE THREAD

**Issue by numanshahid995** [MetaMask/metamask-mobile#5435]
I am facing a serious issue on android i don't know if anybody else is facing the same issue on but metamask is runing slow on android phone even the build version >
The issue can be seen when app open on splash screen it is taking around 20-30 seconds or in some case more then 30 second if it is tested on phone with low computational power  if any body know this problem kindly explain it will  also help others

**Comment by tommasini** [comment]
Hey @numanshahid995, thanks for reporting, we are aware of this and already investigating the issue to solve it!

**Comment by Helpcenter101** [comment]
@numanshahid995 We'd be happy to look into this for you. kindly file a support ticket below 
https://forms.gle/Wmpm6NLzYm9uXYuU9

**Comment by muhammadUmar123** [comment]
I think the issue might be related to splash loading on android . It looks like when we try to load the splash image then it is taking way more time than expected I comment image and now it  is working a little bit faster
