### ISSUE TITLE
undefined is not an object (evaluating ‘o(this,t,“f”).keyrings[0].mnemonic’)

### ISSUE THREAD

**Issue by aliwdev** [MetaMask/metamask-mobile#5442]
**Describe the bug**
_ When I'm trying to login  show me this error message

 - Device: Samsung A8
 - OS: Android 1110
 - App Version last vrsion 5.12.1
 please help me

**Comment by tommasini** [comment]
Hey @aliwdev , thanks for reporting!

I will close it as duplicated, you can follow the status of the ticket [here](https://github.com/MetaMask/metamask-mobile/issues/4840)
