### ISSUE TITLE
Metamask mobile app not emitting any error on rejecting contract approve function

### ISSUE THREAD

**Issue by SaadNiaziDev** [MetaMask/metamask-mobile#5443]
Describe the bug
Android v5.12.1

Any coin approve transaction  rejection does not emit any kind of error

**Steps to reproduce**

Go to https://approve-token.netlify.app/

Click on connect button

Choose 4th one (Binance Smart Chain Testnet) as contract is deployed on testnet

Scan QR code through metamask mobile app

Click on Approve Button

Reject Transaction

Error handling is done in code and can be checked by connecting to metamask desktop extension

**Even this happens on pancakeSwap too**

Error messages or log output
Nothing Happens

Version
v5.12.1

Build type
None

Browser
Any

Operating system
Any

Hardware wallet
No response

Additional context
Code -> https://github.com/SaadNiaziDev/wagmi-boilerplate

**Comment by rafal2228** [comment]
We have observed the same issue with rejecting transactions connected via WalletConnect sessions. Basically, any transaction confirmation rejected by the user in the mobile app is not being propagated to dApp

**Comment by youtpout** [comment]
Hello, 
same problem here, I made some test with walletconnect and metamask.
The problem happen when you have data (Data parameter field) in the transaction but if your transaction don't have data the rejection correctly callback walletconnect.
With rainbow wallet no problem.

**Comment by amankakar** [comment]
still facing the same issue. i have updated metamask app to latest version. the issue is still there.

**Comment by afarkas128** [comment]
I have somewhat the same issue, when I try to swap for some coin in rabby, I am not getting the confirmation inside metamask, and I get the "Transaction rejected" "Missing or invalid. request() chainId: eip155:8453.
Rabby and metamask are up to date on the latest iOS.
