### ISSUE TITLE
Faviconkit not working

### ISSUE THREAD

**Issue by CaoThien96** [MetaMask/metamask-mobile#5456]
### **Description**

Favicon my website not working

### **Technical Details**

1. Incorrect
https://api.faviconkit.com/staging.onedex.io/32
2. Correct
https://gradual-amaranth-lemur.faviconkit.com/staging.onedex.io/32
<img width="1048" alt="Screen Shot 2023-01-06 at 11 10 24 AM" src="https://user-images.githubusercontent.com/21992719/210929856-e3322f4a-a701-4baf-be4b-fddfcc998eda.png">
![photo_2023-01-06_11-25-29](https://user-images.githubusercontent.com/21992719/210929961-715e1bbe-3c98-469f-aaf0-efaa0d4871cf.jpg)

### **Acceptance Criteria**

-   Are metrics required?
-   Are translations required?
-   Cases to satisfy
-   XYZ should work
-   Etc.

Scenario: xxxx
- GIVEN a user is in x state
- WHEN a user does x
- AND a user does x
- THEN x should occur

### **References**

-   References go here.
-   Issue numbers. Links.
-   Slack threads.
-   Etc.

**Comment by CaoThien96** [comment]
![photo_2023-01-06_11-25-29](https://user-images.githubusercontent.com/21992719/210930088-d5d9be61-e7e9-4941-8978-c413f3d73216.jpg)

**Comment by tommasini** [comment]
Hey @CaoThien96, thanks for reporting!

Not fully understood here the problem and the expected behaviour, could you elaborate?
