### ISSUE TITLE
'Learn more' link after backing up SRP redirects user to main support page

### ISSUE THREAD

**Issue by olenapankina** [MetaMask/metamask-mobile#5457]
**Tested on**
iPhone Xr iOS 16.1.1, main commit db9007bac476bd40c02dcbbd7b70a66fde3db52 

**Steps to reproduce:**
1. Launch the app
2. Create new wallet
3. Back up SRP
4. On the Congratulations screen tap 'Learn more' link

**Actual result:** user is redirected to https://metamask.zendesk.com/hc/en-us 
**Expected result:** TBD
Note: 'Learn more' link on Screenshot warning feature redirects user to https://metamask.zendesk.com/hc/en-us/articles/4404722782107-User-guide-Secret-Recovery-Phrase-password-and-private-keys

https://user-images.githubusercontent.com/116747263/211033769-f6fa07c2-7298-46ae-a996-c15ed99cdc73.mp4

**Comment by chrisleewilcox** [comment]
@AlexJupiter curious to how we should go with this.  How does extension handle this?

**Comment by AlexJupiter** [comment]
I think we should link to here like we do for the SRP quiz: https://support.metamask.io/hc/en-us/articles/360060826432-What-is-a-Secret-Recovery-Phrase-and-how-to-keep-your-crypto-wallet-secure
