### ISSUE TITLE
Can not use mobile app for Calling `wallet_addEthereumChain` to add Optimism chain

### ISSUE THREAD

**Issue by yichunsung** [MetaMask/metamask-mobile#5466]
still can not use mobile app for Calling `wallet_addEthereumChain` to add Optimism chain

ios MetaMask app v5.12.3

same issue for `May not specify default MetaMask chain.`

> **Describe the bug** Calling `wallet_addEthereumChain` to add Optimism network on MetaMask mobile will throw exception with message: `May not specify default MetaMask chain.`
> 
> **To Reproduce**
> 
> Send request from a dApp running within MetaMask mobile browser:
> 
> ```js
> window.ethereum.request({
>   method: 'wallet_addEthereumChain',
>   params: [
>     {
>       chainId: "0xa",
>       chainName: "Optimism",
>       rpcUrls: ["https://mainnet.optimism.io"],
>       blockExplorerUrls: ["https://optimistic.etherscan.io"],
>       nativeCurrency: {
>         "name": "ETH",
>         "symbol": "ETH",
>         "decimals": 18
>       }
>     }
>   ]
> })
> ```
> 
> **Expected behavior**
> 
> Optimism is added successfully as a custom network.
> 
> **Smartphone (please complete the following information):**
> 
> * Device: Pixel 5a
> * OS: Android 12
> * App Version: 5.2.0
> 
> _to be added after bug submission by internal support / PM_ **Severity**
> 
> * How critical is the impact of this bug on a user?
> * Add stats if available on % of customers impacted
> * Is this visible to all users?
> * Is this tech debt?

_Originally posted by @yichunsung in https://github.com/MetaMask/metamask-mobile/issues/4492#issuecomment-1376143234_

**Comment by chrisleewilcox** [comment]
@yichunsung adding Optimism Network is working in our 'Add Popular' network feature.  You can also add Optimism through other dapps like 1inch and chainlist.org.  Please try again with our latest version.

**Comment by etsraphael** [comment]
I'm having the same issue. I don't think `wallet_addEthereumChain` is working on the mobile app. We can manually use the mobile app to add a network, but the `wallet_addEthereumChain` seems not to work on the app
