### ISSUE TITLE
[UI] Notification about secret being copied to clipboard flashes or stutters

### ISSUE THREAD

**Issue by plasmacorral** [MetaMask/metamask-mobile#5472]
### **Description**
Observed on V5.12.3 build 1033:
- iPhone 13 mini running iOS 15.6.1 (left in video)
- Samsung a515f running Android 11 (right in video)

Clipboard copy notification has a weird flash after its presented.  This can be observed in both revealing SRP, as well as revealing private keys. In the attached video, you can clearly see this on the iOS device.  On the android device it looks more like a stutter than a flash, but I think its present there as well.

### **Acceptance Criteria**

-   Present the notification once, and do not flash or stutter

Scenario: Revealing private key
- GIVEN a user is in the show private key screen
- WHEN a user taps to copy to clipboard
- THEN the user should be notified that the secret has been copied to the clipboard

Scenario: Revealing Secret Recovery Phrase
- GIVEN a user is in the show Secret Recovery Phrase screen
- WHEN a user taps to copy to clipboard
- THEN the user should be notified that the secret has been copied to the clipboard

### **References**

-   Video shows iOS 15 on the left and Android 11 on the right
-    https://recordit.co/jXqyh4QdAp

**Comment by AlexJupiter** [comment]
I'm struggling to see the flash/stutter, is it definitely there in the video? Or is the quality of the video too bad to see?
