### ISSUE TITLE
BUG - Privacy & Security setting greyed out and blocked

### ISSUE THREAD

**Issue by gantunesr** [MetaMask/metamask-mobile#5478]
**Describe the bug**
A few users are unable to back up their secret recovery phrase because the Security & Privacy section in Settings is greyed out and cannot be accessed. The issue occurs in the latest mobile version, reported on iOS.

**Screenshots**
<img src="https://user-images.githubusercontent.com/17601467/211854143-101f6fc9-2499-40ec-aadd-29500116cfb4.png" width="300" />

**To Reproduce** (TO DO)
_Steps to reproduce the behavior_

**Expected behavior** (TO DO)
_A clear and concise description of what you expected to happen_

**Smartphone (please complete the following information):**
 - App Version [e.g. 1.0.0] - find version number in app from Settings > About MetaMask

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by chrisleewilcox** [comment]
@AlexHerman1 is this still an issue?  We have not seen this before during our RC regression testing.
