### ISSUE TITLE
wallet balance cannot be import

### ISSUE THREAD

**Issue by csk882** [MetaMask/metamask-mobile#5515]
metamask-mobile works fine in a test environment.
However, after building the Android app, the wallet balance cannot be imported normally on the mobile device.
Any workaround for this?

**Comment by cortisiko** [comment]
hey @csk882 can you provide a bit of context to what you mean by:

> the wallet balance cannot be imported normally on the mobile device.

**Comment by csk882** [comment]
Thank you for posting your reply.
In the test environment, the Ethereum balance is loaded normally.
However, after building Android and installing it on a real device, the Ethereum balance cannot be loaded.

Can't load balances on real device?

Or should I use another method?

It's so embarrassing.

**Comment by cortisiko** [comment]
Thanks @csk882 for the additional feedback. Let me follow up with the team and circle back to you!

**Comment by csk882** [comment]
@cortisiko 
I am waiting for a reply to any inquiries I have made in the past.
I'm urgent.
I'll be waiting for your reply.

**Comment by cortisiko** [comment]
@csk882 thanks for the patience. We need a bit more information. What do you mean by

> In the test environment, the Ethereum balance is loaded normally.

Are you trying to build a production version of the application?

Lastly, can you kindly list the steps you take to build the application?

**Comment by skchoi882** [comment]
Thanks @cortisiko 

We set up our development server as per the fold in the github readme.md file.
And the test runs too.
We are testing in Ubuntu environment.

- Metro run
terminal 1 - yarn watch

- Run Android
yarn start:android

It runs normally up to this point, and the balance is imported well on the main screen.

==========
What follows is the problem.

We set up keychain and proceeded to build.

-build command
metamask-mobile\android folder
./gradlew/assembleRelease

build success

After installing it on my actual phone, login proceeds normally.

I want to access the Goerli testnet and check my balance.
However, the balance is not displayed.

If there is no problem with the build process, I need help with other settings to release the product version.

**Comment by cortisiko** [comment]
@skchoi882 Thanks for the additional information. Are you building the application on a remote machine outside of your personal machine? If so ensure that the build machine has the required environment variables.

**Comment by csk882** [comment]
@cortisiko Thank you so much for continuing to show interest in my problem.
I need this issue resolved quickly.

I want to distribute my app developed with Metamask Mobile Source on the Play Store.

Is this possible?

The state of the development environment can be operated in the apk as it is.

infura id in js.env
has been set
It works fine in the emulator.

Is there anything that needs to be changed in the environment settings when building a release?

**Comment by csk882** [comment]
build process

csk882@q381-2414:~/metamask-mobile/android$ ./gradlew assemblerelease

> Configure project :@react-native-community_blur
WARNING:: The option setting 'android.disableResourceValidation=true' is experimental.
The current default is 'false'.
WARNING:: The option setting 'android.enableDexingArtifactTransform.desugaring=false' is experimental.
The current default is 'true'.

> Configure project :exodus_react-native-payments
WARNING:: Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.
It will be removed in version 7.0 of the Android Gradle plugin.
For more information, see http://d.android.com/r/tools/update-dependency-configurations.html.

> Configure project :lottie-react-native
publishNonDefault is deprecated and has no effect anymore. All variants are now published.

> Configure project :react-native-aes-crypto-forked
WARNING:: Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.
It will be removed in version 7.0 of the Android Gradle plugin.
For more information, see http://d.android.com/r/tools/update-dependency-configurations.html.

> Configure project :react-native-minimizer
Warning: Mapping new ns http://schemas.android.com/repository/android/common/02 to old ns http://schemas.android.com/repository/android/common/01
Warning: Mapping new ns http://schemas.android.com/repository/android/generic/02 to old ns http://schemas.android.com/repository/android/generic/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/addon2/02 to old ns http://schemas.android.com/sdk/android/repo/addon2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/addon2/03 to old ns http://schemas.android.com/sdk/android/repo/addon2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/repository2/02 to old ns http://schemas.android.com/sdk/android/repo/repository2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/repository2/03 to old ns http://schemas.android.com/sdk/android/repo/repository2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/sys-img2/03 to old ns http://schemas.android.com/sdk/android/repo/sys-img2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/sys-img2/02 to old ns http://schemas.android.com/sdk/android/repo/sys-img2/01

> Configure project :react-native-os
WARNING:: Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.
It will be removed in version 7.0 of the Android Gradle plugin.
For more information, see http://d.android.com/r/tools/update-dependency-configurations.html.

> Configure project :react-native-reanimated
AAR for react-native-reanimated has been found
/home/csk882/metamask-mobile/node_modules/react-native-reanimated/android/react-native-reanimated-66-jsc.aar
WARNING:: The specified Android SDK Build Tools version (23.0.1) is ignored, as it is below the minimum supported version (30.0.2) for Android Gradle Plugin 4.2.2.
Android SDK Build Tools 30.0.2 will be used.
To suppress this warning, remove "buildToolsVersion '23.0.1'" from your build.gradle file, as each version of the Android Gradle Plugin now has a default version of the build tools.
WARNING:: The specified Android SDK Build Tools version (26.0.1) is ignored, as it is below the minimum supported version (30.0.2) for Android Gradle Plugin 4.2.2.
Android SDK Build Tools 30.0.2 will be used.
To suppress this warning, remove "buildToolsVersion '26.0.1'" from your build.gradle file, as each version of the Android Gradle Plugin now has a default version of the build tools.

> Task :ReactAndroid:generateCodegenSchemaFromJavaScript
yarn node v1.22.19
Done in 0.69s.

> Task :ReactAndroid:generateCodegenArtifactsFromSchema
yarn node v1.22.19
Done in 0.19s.

> Task :app:bundleProdReleaseJsAndAssets
warning: the transform cache was reset.
                    Welcome to Metro!
              Fast - Scalable - Integrated


transform[stderr]: Browserslist: caniuse-lite is outdated. Please run:
transform[stderr]:   npx browserslist@latest --update-db
transform[stderr]:   Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating
transform[stderr]: Browserslist: caniuse-lite is outdated. Please run:
transform[stderr]:   npx browserslist@latest --update-db
transform[stderr]:   Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating
transform[stderr]: [BABEL] Note: The code generator has deoptimised the styling of /home/csk882/metamask-mobile/unknown as it exceeds the max of 500KB.
info Writing bundle output to:, /home/csk882/metamask-mobile/android/app/build/generated/assets/react/prod/release/index.android.bundle
info Writing sourcemap output to:, /home/csk882/metamask-mobile/android/app/build/generated/sourcemaps/react/prod/release/index.android.bundle.map
info Done writing bundle output
info Done writing sourcemap output
info Copying 168 asset files
info Done copying assets

> Task :app:bundleProdReleaseJsAndAssets_SentryUpload_1033
Processing react-native sourcemaps for Sentry upload.
> Analyzing 2 sources
> Rewriting sources
> Adding source map references
Uploading sourcemaps for release io.izzunft@5.12.3+1033 distribution 1033
> Bundled 2 files for upload
> Uploaded release files to Sentry
> File upload complete (processing pending on server)
> Organization: eroomsoft
> Project: 01023138614
> Release: io.izzunft@5.12.3+1033
> Dist: 1033

Source Map Upload Report
  Minified Scripts
    ~/index.android.bundle (sourcemap at index.android.bundle.map)
  Source Maps
    ~/index.android.bundle.map

> Task :app:lintVitalProdRelease
w: Runtime JAR files in the classpath should have the same version. These files were found in the classpath:
    /home/csk882/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-jdk8/1.4.10/998caa30623f73223194a8b657abd2baec4880ea/kotlin-stdlib-jdk8-1.4.10.jar (version 1.4)
    /home/csk882/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-jdk7/1.4.10/30e46450b0bb3dbf43898d2f461be4a942784780/kotlin-stdlib-jdk7-1.4.10.jar (version 1.4)
    /home/csk882/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib/1.4.10/ea29e063d2bbe695be13e9d044dcfb0c7add398e/kotlin-stdlib-1.4.10.jar (version 1.4)
    /home/csk882/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-common/1.4.10/6229be3465805c99db1142ad75e6c6ddeac0b04c/kotlin-stdlib-common-1.4.10.jar (version 1.4)
    /home/csk882/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-jdk8/1.5.31/ff5d99aecd328872494e8921b72bf6e3af97af3e/kotlin-stdlib-jdk8-1.5.31.jar (version 1.5)
    /home/csk882/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-jdk7/1.5.31/77e0f2568912e45d26c31fd417a332458508acdf/kotlin-stdlib-jdk7-1.5.31.jar (version 1.5)
    /home/csk882/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib/1.5.31/6628d61d0f5603568e72d2d5915d2c034b4f1c55/kotlin-stdlib-1.5.31.jar (version 1.5)
    /home/csk882/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-common/1.5.31/43331609c7de811fed085e0dfd150874b157c32/kotlin-stdlib-common-1.5.31.jar (version 1.5)
    /home/csk882/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib/1.6.21/11ef67f1900634fd951bad28c53ec957fabbe5b8/kotlin-stdlib-1.6.21.jar (version 1.6)
    /home/csk882/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-jdk7/1.6.20/f8629f336bad4001c89e9cffa5ef3d4b5d0f5e22/kotlin-stdlib-jdk7-1.6.20.jar (version 1.6)
    /home/csk882/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-jdk8/1.6.20/dab8089bca6ac0e394c37281ea8cff2f99acd421/kotlin-stdlib-jdk8-1.6.20.jar (version 1.6)
    /home/csk882/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-common/1.6.21/5e5b55c26dbc80372a920aef60eb774b714559b8/kotlin-stdlib-common-1.6.21.jar (version 1.6)
w: Some runtime JAR files in the classpath have an incompatible version. Consider removing them from the classpath
e: /home/csk882/.gradle/caches/modules-2/files-2.1/androidx.annotation/annotation/1.4.0/77e7b6bbe9803d890343716dd824dfdbc0f6fe77/annotation-1.4.0.jar!/META-INF/annotation.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.6.0, expected version is 1.4.0.
e: /home/csk882/.gradle/caches/transforms-3/ac153fa4d5a63ec1b51f382b52ad5e87/transformed/jetified-library-5.2.5/jars/classes.jar!/META-INF/Branch-SDK_release.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.6.0, expected version is 1.4.0.
e: /home/csk882/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib/1.6.21/11ef67f1900634fd951bad28c53ec957fabbe5b8/kotlin-stdlib-1.6.21.jar!/META-INF/kotlin-stdlib.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.6.0, expected version is 1.4.0.
e: /home/csk882/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-jdk7/1.6.20/f8629f336bad4001c89e9cffa5ef3d4b5d0f5e22/kotlin-stdlib-jdk7-1.6.20.jar!/META-INF/kotlin-stdlib-jdk7.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.6.0, expected version is 1.4.0.
e: /home/csk882/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-jdk8/1.6.20/dab8089bca6ac0e394c37281ea8cff2f99acd421/kotlin-stdlib-jdk8-1.6.20.jar!/META-INF/kotlin-stdlib-jdk8.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.6.0, expected version is 1.4.0.
e: /home/csk882/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-common/1.6.21/5e5b55c26dbc80372a920aef60eb774b714559b8/kotlin-stdlib-common-1.6.21.jar!/META-INF/kotlin-stdlib-common.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.6.0, expected version is 1.4.0.

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.9/userguide/command_line_interface.html#sec:command_line_warnings

BUILD SUCCESSFUL in 6m 45s
1384 actionable tasks: 18 executed, 1366 up-to-date

**Comment by cortisiko** [comment]
@csk882 we suggest working with the application in development mode. If you need a production version of the application, feel free to download it from the apple/google stores
