### ISSUE TITLE
Cannot send token on Metamask mobile

### ISSUE THREAD

**Issue by fromreto** [MetaMask/metamask-mobile#5517]
**Describe the bug**
- Estimated gas fee is NOT displayed 
- Happens on mobile only; chrome extensions have no issue sending transactions. 
- It happens on ALL users using Metamask Mobile
- After submitting the transaction, the transaction is pending forever. 
- Transaction sending(Receive is possible) is NOT working 

**Screenshots**
![photo_2023-01-14 23 21 36](https://user-images.githubusercontent.com/107421475/212476821-d0c2e44b-3026-4ed2-9798-076f48baaef1.jpeg)
![photo_2023-01-14 23 21 39](https://user-images.githubusercontent.com/107421475/212476826-694e6f0d-5238-4b2d-9bf1-726d09464ae9.jpeg)

**To Reproduce**
1. Add network Oasys via manual add network on Metamask Mobile.
RPC : https://rpc.mainnet.oasys.games/
Chain ID : 248
Token : OAS 
Explorer : https://scan.oasys.games/

3. Click on 'send'
4. Input 'Address'
5. Input 'Amount' 
6. See error
7. Click on 'Send'
8. See error

**Expected behavior**
- Estimated gas fee is displayed 
- After submitting the transaction, the transaction is pending forever. 

**Smartphone (please complete the following information):**
 - Device: [iPhoneXR, Galaxy Note S20 Ultra]
 - App Version v5.12.1

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % 
- Is this visible to all users?  
- Is this tech debt?

**Comment by cortisiko** [comment]
hey @fromreto! Thanks for reporting this issue. The bug has been fixed in https://github.com/MetaMask/metamask-mobile/pull/5439 and will be in version 5.13 which would be released in the coming week or so. I am going to close this issue. After 5.13 is released and the issue still persists feel free to reopen.

**Comment by MicahZoltu** [comment]
This problem also occurs for ETH.  It appears that connecting from certain countries or ISPs (not sure which) triggers this.  I assume that there is some kind of block against the conversion source.
