### ISSUE TITLE
 [Bug]: ENS resolution does not work on Goerli

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-mobile#5519]
**Describe the bug**
ENS resolution does not work on Goerli network. On the placeholder text for address is displayed that you can input an ENS domain but it never resolves on Goerli.

**Screenshots**

https://user-images.githubusercontent.com/54408225/212694147-ee958387-a29a-4ee3-9107-858d9a198207.mp4

**To Reproduce**
_Steps to reproduce the behavior_
1. Set Goerli Network
2. Click Send
3. Add an existing ENS domain on Goerli (i.e. `vitalik.eth` or `seaona.eth`)
4. See how ENS never resolves

**Expected behavior**
The ENS name should be resolved with its corresponding address, and user should be able to proceed with the Send flow.

**Smartphone (please complete the following information):**
- Device: Samsung SM-A217F
- OS: Android 11.0
- App Version: v5.12.3 (1033)

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by bschorchit** [comment]
Note: this is similar to extension's current state. When working through this, we should work on both platforms to ensure parity.

**Comment by seaona** [comment]
At the moment we do have ENS support on Goerli in Extension:

![image](https://user-images.githubusercontent.com/54408225/218077769-9e0504fb-330f-4857-98ab-3ce6e0425729.png)

**Comment by bschorchit** [comment]
This unblocks e2e tests on mobile for ENS send

**Comment by bschorchit** [comment]
The fix for this might require switching to the module that extension uses for ENS resolution

**Comment by bschorchit** [comment]
Switching the module might also solve this https://github.com/MetaMask/metamask-mobile/issues/5604

**Comment by bschorchit** [comment]
e2e tests now support ganache so I believe this is no longer a priority for unblocking e2e (please correct me if I'm wrong)
