### ISSUE TITLE
[Bug]: Approving a transaction for an ERC721 token displays the Approve screen for an ERC20 token

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-mobile#5520]
**Describe the bug**
Approving a transaction for an ERC721 token displays the Approve screen for an ERC20 token

Notice, on Set Approval for all, we display a contract interaction, which is okay, if there is no specific screen for this function at the moment.

**Screenshots**

https://user-images.githubusercontent.com/54408225/212696145-e7a41835-6ff8-4f61-a8ab-092d751de8a4.mp4

**To Reproduce**

1. Go to https://metamask.github.io/test-dapp/
2. Deploy Collectibles -- accept tx on MM
3. Click on Mint -- accept tx on MM
4. Click Approve -- see how the Approve for ERC20 token screen is displayed.

**Expected behavior**
Expected behaviour can be observed on the Extension.
In this case, we are approving the ERC721 token with id 3 , and the screen for approval displays the collection name and the token Id.

![image](https://user-images.githubusercontent.com/54408225/212697014-96c626ad-e871-4064-bca2-2fdbf822f554.png)

**Smartphone (please complete the following information):**

- Device: Samsung SM-A217F
- OS: Android 11.0
- App Version: v5.12.3 (1033)

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by danjm** [comment]
This was the PR to fix this on the extension side, but it is unclear whether this bug would have the same cause on mobile. https://github.com/MetaMask/metamask-extension/pull/16760

The root cause on the extension related to interaction between the network controller and the assetsContractController, but the extension and mobile use different network controllers.

**Comment by bschorchit** [comment]
The erc721 screen should look very similar to the current erc20 one, listed here the differences:
1. Title would read "Give permission to access your `erc721_name` (#`erc721_tokenID`)";
2. In the title, the `erc721_name` should be a link to check that NFT contract on the block explorer;
3. If there's an error and we cannot get the `erc721 name`, we should try to get its symbol and display that. The `erc721_symbol` should also be a link to check that NFT contract on the block explorer;
4. If there's an error and we cannot get the erc721 name or symbol, the fallback title should be "Give permission to access your `NFT` (#`erc721_tokenID`)" where NFT is also a link to check that NFT contract on the block explorer;
5. The "Access up to: value" part should be hidden.

![Screenshot 2023-01-23 at 11 51 17](https://user-images.githubusercontent.com/34968356/214073824-a10e3788-e143-4e89-80e4-b5d0cea3bcc5.png)

**Comment by bschorchit** [comment]
Extra scope: could this screen also apply to erc1155 with the exact same scope above?
