### ISSUE TITLE
Stabilize deep linking on the simulator/emulator for E2E

### ISSUE THREAD

**Issue by cortisiko** [MetaMask/metamask-mobile#5536]
I am experiencing an issue when trying to deep link on the simulator. I can successfully deep link to a dapp or to a particular transaction the first couple of times. Afterward, it is impossible to actually deep link.

 For example, I would attempt to deep link here: https://metamask.app.link/dapp/metamask.github.io/test-dapp/

the app launches but I am not taken to the mm test dapp in the browser view. See the recording [here](http://recordit.co/S8VZZW0xXc).

This is breaking the e2e deep linking tests. I can confirm that [this **DOES NOT** happen on physical devices](http://recordit.co/GKgEy9X8LO)

See my original slack message here: https://consensys.slack.com/archives/C02U025CVU4/p1671222774797949

To reproduce on your simulator/emulator:
- launch the app in the simulator
- attempt to deep link to any of the universal deep links [here](https://cortisiko.github.io)
- close and relaunch the app and attempt to deep link a few more times. After a while the app stops deep linking. 

Just an FYI: Wiping the device each time works but this does not make sense for E2E testing.

**Comment by tommasini** [comment]
Update: This happens to me on my Physical Android device on MM version 5.12.1

**Comment by tommasini** [comment]
The PR created #5543, doesn't solve this particular issue of universal links, I will move this issue to the icebox until we have enough resources to move forward 
I think it's a known issue and will attach some threads/articles below to justify it:
* https://help.branch.io/faq/docs/ios-redirection-is-not-working-and-i-have-universal-links-enabled
* https://stackoverflow.com/questions/59536192/ios-does-not-request-aasa-file-on-one-device-but-works-on-all-others
* https://developer.apple.com/forums/thread/123760
* https://developer.apple.com/forums/thread/123554

**Comment by hesterbruikman** [comment]
@andreahaku do you remember why this PR was closed? Did it not address the issue?

**Comment by andreahaku** [comment]
> @andreahaku do you remember why this PR was closed? Did it not address the issue?

I did not close it. I thinks it's been closed for inactivity. There is still no solution to it unfortunately.
