### ISSUE TITLE
metamask-mobile app

### ISSUE THREAD

**Issue by csk882** [MetaMask/metamask-mobile#5540]
I am trying to create my own app using the metamask-mobile source.
Is this possible?
In my app, I want to use the Ethereum mainnet.

**Comment by Walletsuppport** [comment]
We'd be happy to look into this for you. kindly file a support ticket below 
https://forms.gle/Wmpm6NLzYm9uXYuU9

**Comment by cortisiko** [comment]
Closing since this relates to https://github.com/MetaMask/metamask-mobile/issues/5515#issuecomment-1397380771
