### ISSUE TITLE
[Bug]: Editting a Send NFT tx and changing it to Send ETH displays the NFT tx on the Activity tab instead of the Send ETH

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-mobile#5541]
**Describe the bug**
When I start an NFT Send transaction and I am on the Confirmation page, if I click Edit, and I change the NFT for ETH, if I proceed with the Send transaction, this will complete, but on the Activity tab I will see as if I just sent the NFT.

**Screenshots**
_If applicable, add screenshots or links to help explain your problem_

https://user-images.githubusercontent.com/54408225/213192694-0ba2a208-4e76-4207-ac62-fed7cc1d5b46.mp4

**To Reproduce**
_Steps to reproduce the behavior_
1. Open Browser
2. Go to test dapp https://metamask.github.io/test-dapp/
3. Connect MM
4. Under Collectibles click Deploy and accept on MM (open Etherscan and copy the contract address)
5. Click Mint and accept on MM
6. Switch to MetaMask
7. Click NFT tab
8. Click Import NFT
9. Paste the collectibles contract you just deployed
10. Add the NFT # 1
11. Click Send the NFT
12. Insert any recipient
13. Select the NFT
14. Click Edit -- this will take you back to the previous screen
15. Change the Collectible for ETH
16. Introduce ETH amount
17. Click Next
18. Confirm tx
19. Go to Activity tab
20. See how it appears an NFT transaction, that never happened, as it was a Send ETH

**Expected behavior**
_A clear and concise description of what you expected to happen_

**Smartphone (please complete the following information):**
- Device: Samsung SM-A217F
- OS: Android 11.0
- App Version: v5.12.3 (1033)

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by sahar-fehri** [comment]
Closing this because it is no longer an issue 🙏
