### ISSUE TITLE
Add tags to e2e tests and enable running tests by specific label

### ISSUE THREAD

**Issue by cortisiko** [MetaMask/metamask-mobile#5547]
The time it takes to build and launch tests on bitrise is >90 mins. To prevent tests from timing out on bitrise, we need to add specific tags @smoke @regression on the different E2E tests.

**Comment by Fatxx** [comment]
[This code](https://github.com/MetaMask/metamask-mobile/blob/main/wdio.conf.js#L320) should be dynamic, possible by specifying tags in the command line `yarn test:android:qa --tags=smoke`
