### ISSUE TITLE
Ethereum not injected in Android after a POST form

### ISSUE THREAD

**Issue by jarnaez728** [MetaMask/metamask-mobile#5555]
**Describe the bug**
When I send a form in a web3 Dapp, ethereum is not injected for Android devices. It works fine in iOS.

**To Reproduce**
I've prepared a simple code to reproduce the problem
1. From MetaMask mobile browser, in an Android device go to https://loyalty.elredil.com/test
2. You will see that MetaMask is detected and the information of your browser
3. Click on the "Send" button (it just sends an empty form to the current page)
4. The page is loaded again but MetaMask is not longer detected

You can see easily the code used in the page. it is simple and works well on iOS

**Expected behavior**
MetaMask is detected after the POST.

**Smartphone:**
If tested this problem with three different Android devices (different OS version) using the last version of MetaMask (5.13)

**Comment by tommasini** [comment]
Hey @jarnaez728 , thanks for reporting!

Can you take a look on this [issue](https://github.com/MetaMask/metamask-mobile/issues/5156)? Are you using <Redirect />?

**Comment by jarnaez728** [comment]
Seems pretty similar. But in my case I was able to provide a simple example where it doesn't work so I hope is easier to find the problem :)

**Comment by tommasini** [comment]
Definitely, but do you confirm you are using the `Redirect` of `react-router-dom`?

**Comment by jarnaez728** [comment]
No, neither of them. I just use a standard POST HTML form, but seems the same error.

**Comment by tommasini** [comment]
Thanks, I will bring this to our team!
Please provide us with the version of the app and what device you are using and the android version of the device

**Comment by jarnaez728** [comment]
This seems solved in version 6.0.0. Did you solve it on purpose?

**Comment by jarnaez728** [comment]
I've just found another strange behaviour. Only happens in mobile. When loading a new page (it doesn't matter through a standard link or a POST) the event "accountsChanged" is triggered.
You can check this in the same simple example I indicated: [https://loyalty.elredil.com/test](https://loyalty.elredil.com/test). If you click on the button or link from a mobile, an alert is shown. That doesn't happen in browser extension.
