### ISSUE TITLE
Approve button not disabled for amounts higher than balance

### ISSUE THREAD

**Issue by christopherferreira9** [MetaMask/metamask-mobile#5557]
**Describe the bug**
When using one the MetaMask SDKs to perform eth_sendTransaction with higher amount than the balance that a given account has the confirm button on MetaMask is not disabled as it should.
Sometimes the button is disabled, sometimes it's not.

**Screenshots**
https://www.loom.com/share/1f6f21532e31456ab4debe5b7235b66d

**To Reproduce**
_Steps to reproduce the behavior_
1. Go to [SDK Dapp](https://christopherferreira9.github.io/sdk-bug/) on your 
2. Click on 'Connect'
3. Scan the QR code
4. Switch to Goeli network (also reproduced with mainnet)
5. Click on 'Send Transaction'
6. Check the MetaMask popup

**Expected behavior**
The confirmation button on MetaMask is disabled since the amount being transferred is higher than the balance owned by the user.

**Smartphone (please complete the following information):**
 - Device: iPhone 11 Pro
 - OS: 16.2
 - App Version: v5.13.0 (1042)

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by tommasini** [comment]
Thanks @christopherferreira9,
Extra information: This issue is happening as well without the SDK

**Comment by cortisiko** [comment]
awaiting confirmation from @bschorchit. Will link the ticket/PR associated with this fix after we get confirmation.

**Comment by bschorchit** [comment]
This actually should be a different fix where we disable buttons until content is fully loaded. Reference: https://github.com/MetaMask/mobile-planning/issues/735#issuecomment-1479392289
