### ISSUE TITLE
Incorrect method signatures displayed

### ISSUE THREAD

**Issue by noohp-epics** [MetaMask/metamask-mobile#5567]
**Describe the bug**
When calling certain methods on a contract, due to function signature collisions an incorrect/misleading method name is displayed.
Same bug as https://github.com/MetaMask/metamask-extension/pull/14937, just not fixed on mobile.

**Screenshots**
![image](https://user-images.githubusercontent.com/52841992/213994425-04050f0e-6963-45d3-bc76-3f9d26b59058.png)
The above method is a collision with setapprovalforall.

**To Reproduce**
1. Go to opensea.io
2. Try to list a new item
3. Observe bug when approving item

**Expected behavior**
Should show Set Approval For All as the method name.

**Smartphone (please complete the following information):**
 - Device: Oneplus Nord CE 2
 - OS: OxygenOS 12.1, Android 12
 - App Version v5.12.1 (1028)

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by bschorchit** [comment]
Thank you for your report. 
As reference for others, the fix for this issue is described here: https://github.com/MetaMask/mobile-planning/issues/309
