### ISSUE TITLE
[Bug]: Contact Name is not displayed on the Confirmation Screen

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-mobile#5571]
**Describe the bug**
When I am sending ETH to one of my Contacts, I can see that its name appears on the Send screen, but when I proceed and I land into the Confirmation screen, the contact name is not displayed anymore, displaying the address instead.

This can be inconvenient, specially when a transaction is triggered from a Dapp or from a Deeplink, where you jump directly onto the Confirmation screen, so you then don't really know if that Address is one of your Contacts or not.

**Screenshots**

https://user-images.githubusercontent.com/54408225/214022057-20a51890-5a03-40bc-b59e-40a27e698c6e.mp4

**To Reproduce**
_Steps to reproduce the behavior_
1. Go to Settings > Contacts
2. Add a Contact. I.e. `0x08E5FFD2fF489a149DFA476CfF4bA9448a893F8E`
3. Close Settings
4. Click Send
5. Add the new contact as the Recipient -- see that the Contact Name is displayed
6. Click Next
7. Add any amount and proceed to the Confirmation screen
8. See how the Recipient does not displays the Contact Name anymore

**Expected behavior**
The Contact Name should be displayed on the Confirmation screen, in the same way that it is displayed on the Send screen.

**Smartphone (please complete the following information):**
 

- Device: Samsung SM-A217F
- OS: Android 11.0
- App Version: v5.12.3 (1033)

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by bschorchit** [comment]
This is being addressed on https://github.com/MetaMask/metamask-mobile/pull/5887

**Comment by seaona** [comment]
@bschorchit thank you for pointing this. I thought the PR would only address the Contract Interaction address, that's why I opened a separate ticket for the Send flow inside MetaMask, but I've double-checked the PR and I can see that this issue is already fixed there too.
So this ticket can be closed with that PR too

**Comment by bschorchit** [comment]
Closing as https://github.com/MetaMask/metamask-mobile/pull/5887 has been merged
