### ISSUE TITLE
[ANDROID] bug- app lock timer is not enforced after screen timeout

### ISSUE THREAD

**Issue by plasmacorral** [MetaMask/metamask-mobile#5581]
**Describe the bug**
 App lock timer is not respected after second device screen timeout.  When the screen lock is unlocked after time out for the second time, then MMM authentication is not being requested and the app will open directly to wallet view.

Was able to reproduce this on multiple versions of android, but not on iOS.

I am also able to produce a variation where authentication is requested, however, the authentication request is overlaid on wallet view or the account menu. This is shown in the screenshot below, but I am still uncertain of the exact reproduction steps for the variation. 

**VIDEO**
https://recordit.co/FjZEG83XdT
Note: android 13 is light mode on the left, Android 11 in dark on the right
38s- Prove device pin auth is working as expected when killing app and relaunching
1m 11s- 1st screen unlock where PIN is requested as expected
2m 3s- Second unlock MMM not requesting authenticaton - FAIL
2m 49s- 3rd unlock no auth- FAIL
2m 57s- Changed app lock from 30s to Immediately
3m 14s- FAIL with app lock at Immediately
3m 16s- App-lock immediate functions as expected when multitasking with another app and locks MMM

**Screenshot of variation**
![Screenshot 2023-01-23 at 3 59 46 PM](https://user-images.githubusercontent.com/32695229/214150846-22400de0-b19c-4add-9a7f-5ddd0371a135.png)

**To Reproduce**
1. Reboot device(s)
2. Confirm device screen lock set at 30s
3. Wipe MMM app storage
4. launch MMM and import SRP with biometrics
5. turn off biometrics, and on device pin/passcode
6. turn on custom nonce
7. verify MMM app version
8. kill app and restart 
9. Confirm authentication by device PIN passcode
10. get to wallet view and swipe down and leave MMM in the foreground
11. start a timer
12. Let screen lock at 30s
13. Unlock devices before the subsequent 30s app lock kicks in (between 30-60s)
14. Note that no authentication required when MMM opens to wallet view
15. get to wallet view and swipe down
16. start a timer
17. Let screen lock at 30s
18. Let app lock be exceeded 30s after screen lock (60s+)
19. Wait another minute or two and Unlock the device at around 3m on the timer
20. Note that device PIN authentication requested
21. Provide the device pin/passcode
22. get to wallet view and swipe down
23. start a timer
24. Let screen lock at 30s
25. Let app lock be exceeded 30s after screen lock (60s+)
26. Wait another minute or two and Unlock the device at around 3m on the timer
27. Note that after unlocking the device that MMM is opened directly at wallet view without prompting for further authentication
28. Change app-lock to immediate
29. Note that multi tasking will prompt for authentication, but after screen lock MMM app does not as expected

**Expected behavior**
If the screen lock is activated with the app in the foreground, then the app lock timer should start shortly after the screen goes dark.  If the device is unlocked before the app-lock timer runs out, then no authentication should be required.  However, if device is unlocked after app-lock timer expires, then authentication should be required before any sensitive information is presented.

**Smartphone (please complete the following information):**
production v5.13 build 1042 & v6.2 build 1088
 - Pixel 5a running Android 13
 - Samsung a515f running Android 11

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by chrisleewilcox** [comment]
@plasmacorral can you retest with the latest mobile app?

**Comment by plasmacorral** [comment]
Still able to reproduce this on second screen timeout on both Samsung a515f running android 11, and Pixel 5a running android 13.  Tested today with latest production v6.2 build 1088.
