### ISSUE TITLE
Cucumber refactor Proposal

### ISSUE THREAD

**Issue by Andepande** [MetaMask/metamask-mobile#5582]
Details

QA team talking points regarding improvements we could make to cucumber:
- The decoupling of step definitions to feature files
- Avoiding Anti-patterns when defining steps
- Promoting step re-usability
- Promoting ease of readability 
- Ensuring cucumber steps provide useful information in report

**Comment by cortisiko** [comment]
We addressed the concerns mentioned here in one of our weekly automation syncs meetings. Closing.
