### ISSUE TITLE
Copy to clipboard missing for SRP and private key

### ISSUE THREAD

**Issue by plasmacorral** [MetaMask/metamask-mobile#5593]
**Describe the bug**
Noticed this in testing auth refactor, and then confirmed today that it is also missing in v5.13 build 1042.

Copy to clipboard is missing on both Android and IOS devices.  This should be presented for all users > Android version 10.

**Screenshots**

SRP (iOS then Android):
<img width="125" src="https://user-images.githubusercontent.com/32695229/214368911-d07c407a-6c82-4aa3-9362-b471c8ee887b.png"><img width="125" src="https://user-images.githubusercontent.com/32695229/214372324-2ed71bfa-d6f2-44fb-a9ef-e55810d707f0.png"></div>

Private Key (iOS then Android):
<img width="125" src="https://user-images.githubusercontent.com/32695229/214373402-7b925fab-26f5-48bb-8b87-55445716ea84.png"><img width="125" src="https://user-images.githubusercontent.com/32695229/214372767-38800ea0-3e10-464f-9623-15d419ad8cb2.png">

Expected (private key then SRP): 
<img width="125" src="https://user-images.githubusercontent.com/32695229/214374118-c8ddb2db-c51b-40cc-84f9-349f0c34739a.png"><img width="130" src="https://user-images.githubusercontent.com/32695229/214374025-b63038b5-2f55-462f-b614-e3d75ca8d046.png">

**To Reproduce**
_Steps to reproduce the behavior_
1. import SRP
2. Go to Settings> Security & Privacy
3. select either 'Reveal Secret Recovery Phrase' or 'Show private key'
4. Note that there is no option to copy the secret to clipboard

**Expected behavior**
Users should be able to copy SRP or private key to clipboard on their mobile device, as long as they are not running Android <=10. 

**Smartphone (please complete the following information):**
 - IPhone 14 mini running iOS 15.6.1
 - Samsung a515f runing android 11

Observed in v5.13 build 1042

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by chrisleewilcox** [comment]
@gantunesr Can you confirm this was intentional?

**Comment by gantunesr** [comment]
@chrisleewilcox I got confused with another development, this is a bug unless the OS is below Android 10.

**Comment by plasmacorral** [comment]
resolved with 5750
