### ISSUE TITLE
Redirect in Metamask internal browser

### ISSUE THREAD

**Issue by lampamazaza** [MetaMask/metamask-mobile#5610]
Problem
Our Auth flow uses Supabase. The magic link for auth should redirect user to our_domain.name/#access_token=X . The problem is that this redirect doesn't happen.

The response from magic link has http status 303 and location header that specifies the destination url

Device - Android
Version 5.13.0

**Comment by lampamazaza** [comment]
Hello @tommasini, thank you for such a quick reply!
Here are the steps.

First Option
1 - https://aurora.plus/signup -  sign up with email (pls turn of vpn)
2 - After sign up put magic link from email in metamask browser  (should fail here too, as there is the same redirect)
 
Second Option  (Sign up done through PC)
1 - Go through sign up on PC
2 - Import  wallet from PC to Metamask Mobile
3 -  Go to https://aurora.plus/login and Click Log in with Metamask

**Comment by tommasini** [comment]
In the meantime, while our team does their best to address this issue, please wonder about the possibility of integrating the [MetaMask SDK](https://metamask.io/sdk/) to your dapp interact with the MetaMask mobile app

**Comment by lampamazaza** [comment]
Sure, I will take a look. Meanwhile just to be clear, our flow works with Iphone devices but doesn't work with Anroids.

Thank you for taking a look at the issue.

**Comment by Karkunow** [comment]
@tommasini Hello! Could you please provide any information about when we should expect this issue to be resolved?
Thanks you! :)

**Comment by tommasini** [comment]
Hey @Karkunow, we are doing our best to address our community issues, we appreciate a lot for your patience! 
Meanwhile, if you want to try it and open a PR feel free to do it, we appreciate it!
All the updates will be posted here 🚀

**Comment by lampamazaza** [comment]
Hello guys any update ? It is been a while. Maybe we can at least have a confirmation from you , that this is a problem on your side (or not)?

**Comment by tommasini** [comment]
Hey @lampamazaza, we still don't have an update on this issue, thanks for your patience!

**Comment by cortisiko** [comment]
@Karkunow did you try to reproduce this on the latest version of the app? version 6.1.2?

**Comment by Karkunow** [comment]
@cortisiko Yes, I have tried it in v6.3.0 right now. And it is not working.
Magic link I receive from https://aurora.plus/ app transforms automatically into https://aurora.plus/onboarding for some reason in your browser line and I can't login into the app.

**Comment by Karkunow** [comment]
Login with Metamask doesn't work also.

**Comment by Karkunow** [comment]
@cortisiko @tommasini Hey! Any updates on this one?

**Comment by tommasini** [comment]
Hey @Karkunow,

What happened to me:

* Received magic link
* Paste it on the metamask in-app browser
* Connected my wallet
* It appeared to be sign in, just when pressed to add the network, nothing happened

If I pressed the top right corner of aurora dapp, on my address, I was able to sign out, so I believe I was able to sign in

I tested this on version 6.6.0 and it's almost released.


Let me know if there is something that I missed

**Comment by Karkunow** [comment]
@tommasini it is not working for me and for users. I've just received 2 or 3 complaints only the recent week.
And the problem is on Android only. And inside the built-in Metamask browser.
@cortisiko fyi

**Comment by Karkunow** [comment]
@lampamazaza could you please confirm?

**Comment by lampamazaza** [comment]
@tommasini 
Just tested with the latest version as of today.
Received a magic link via email, then put into internal Metamask browser. Got redirected back to login page. If go through same procedure in regular chrome mobile I manage to get to dashboard.

So I expect this to behave in the same way. 

Another problem that the regular login doesn't work also.  (via making a signature)
P.S. I think there is still some issues with redirect on your side.

**Comment by kilmane** [comment]
same issue here. Hope this gets resolved soon. thank you..

**Comment by Karkunow** [comment]
@lampamazaza we can close this ticket already, as we do not need it anymore to be fixed.
There are no magic links in the Aurora+ and users can connect via Aurora Pass now.
