### ISSUE TITLE
[e2e] [iOS] Send ETH from dapp using advanced gas controls (Legacy and EIP1559 tx)

### ISSUE THREAD

**Issue by jpuri** [MetaMask/metamask-mobile#5625]

**Comment by jpuri** [comment]
It will be useful to add user interactions tests also.
Ref: https://callstack.github.io/react-native-testing-library/docs/getting-started

**Comment by bschorchit** [comment]
It might be blocked on ios, but possible on android due to http issue.

**Comment by bschorchit** [comment]
Closing as completed with: https://github.com/MetaMask/metamask-mobile/pull/5888 that fixed https://github.com/MetaMask/metamask-mobile/issues/5696 (we don't need 1 tests per platform anymore)
