### ISSUE TITLE
Lint wdio (e2e tests) directory with eslint and fix issues

### ISSUE THREAD

**Issue by NicolasMassart** [MetaMask/metamask-mobile#5628]
### **Description**

As revealed by PR #5612, eslint attempt to check the content of the wdio directory raises some code errors.

These errors were hidden before as the wdio dir was ignored.

But now that we know, it's probably worth trying to fix the errors and stop ignoring the wdio dir with eslint.  

### **Technical Details**

- remove wdio from .eslintignore
- fix all the issues raised by eslint

### **Scope**

This is only fixing the eslint warning and errors. It doesn't include any changes in how code and tests are organised.
It's usually only some straightforward syntax changes.
If during the fix, it appear that unplanned more complex changes impacting code architecture are required to fix the issues: **require discussion and decision with team.**

### **Acceptance Criteria**

- eslint fully checking wdio directory
- no more errors or warning from eslint in the wdio directory.

### **References**

See #5612

**Comment by NicolasMassart** [comment]
For reference, the issues currently raised:

```
yarn run v1.22.19
$ eslint '**/*.{js,ts,tsx}'
=============

WARNING: You are currently running a version of TypeScript which is not officially supported by @typescript-eslint/typescript-estree.

You may find that it works just fine, or you may not.

SUPPORTED TYPESCRIPT VERSIONS: >=3.3.1 <4.5.0

YOUR TYPESCRIPT VERSION: 4.6.2

Please only submit bug reports when using the officially supported version.

=============

/Users/nicolas/Develop/Metamask/metamask-mobile/app/components/hooks/AppConfig/AppConfig.ts
  17:2  warning  Missing semicolon  semi

/Users/nicolas/Develop/Metamask/metamask-mobile/e2e/specs/wallet-tests.spec.js
  288:3  warning  Test title is used multiple times in the same describe block  jest/no-identical-title

/Users/nicolas/Develop/Metamask/metamask-mobile/wdio/config/android.config.browserstack.local.js
   4:22  error  Expected "import" instead of "require()"  import/no-commonjs
  32:3   error  Unexpected console statement              no-console
  34:5   error  Expected "export" or "export default"     import/no-commonjs
  35:5   error  Expected "export" or "export default"     import/no-commonjs
  37:7   error  Unexpected console statement              no-console
  45:3   error  Unexpected console statement              no-console
  47:5   error  Expected "export" or "export default"     import/no-commonjs
  49:7   error  Unexpected console statement              no-console

/Users/nicolas/Develop/Metamask/metamask-mobile/wdio/features/screen-objects/AddCustomImportTokensScreen.js
  27:11  error  'driver' is not defined  no-undef
  38:11  error  'driver' is not defined  no-undef
  39:11  error  'driver' is not defined  no-undef

/Users/nicolas/Develop/Metamask/metamask-mobile/wdio/features/screen-objects/ImportAccountScreen.js
  28:11  error  'driver' is not defined       no-undef
  38:27  error  'driver' is not defined       no-undef
  42:7   error  Unexpected console statement  no-console

/Users/nicolas/Develop/Metamask/metamask-mobile/wdio/features/screen-objects/Modals/AddressBookModal.js
  3:10  error  'ENTER_ALIAS_INPUT_BOX_ID' is defined but never used  no-unused-vars

/Users/nicolas/Develop/Metamask/metamask-mobile/wdio/features/screen-objects/Onboarding/CreateNewWalletScreen.js
  58:11  error  'driver' is not defined  no-undef
  64:11  error  'driver' is not defined  no-undef
  69:11  error  'driver' is not defined  no-undef

/Users/nicolas/Develop/Metamask/metamask-mobile/wdio/features/screen-objects/Onboarding/ImportFromSeedScreen.js
  87:7  error  Unexpected console statement  no-console

/Users/nicolas/Develop/Metamask/metamask-mobile/wdio/features/screen-objects/Onboarding/MetaMetricsScreen.js
  19:11  error  'driver' is not defined  no-undef
  33:11  error  'driver' is not defined  no-undef

/Users/nicolas/Develop/Metamask/metamask-mobile/wdio/features/step-definitions/create-new-wallet-account.steps.js
   1:10  error  'Given' is defined but never used  no-unused-vars
  12:9   error  'driver' is not defined            no-undef
  18:9   error  'driver' is not defined            no-undef
  27:9   error  'driver' is not defined            no-undef
  32:9   error  'driver' is not defined            no-undef
  36:9   error  'driver' is not defined            no-undef
  37:9   error  'driver' is not defined            no-undef

/Users/nicolas/Develop/Metamask/metamask-mobile/wdio/features/step-definitions/drawer-view.steps.js
  1:10  error  'Given' is defined but never used  no-unused-vars
  1:23  error  'Then' is defined but never used   no-unused-vars

/Users/nicolas/Develop/Metamask/metamask-mobile/wdio/features/step-definitions/import-tokens.steps.js
   5:5  error  'setTimeout' is never reassigned. Use 'const' instead  prefer-const
   8:9  error  'driver' is not defined                                no-undef
  13:9  error  'driver' is not defined                                no-undef
  22:9  error  'driver' is not defined                                no-undef

/Users/nicolas/Develop/Metamask/metamask-mobile/wdio/features/step-definitions/import-wallet-via-private-key.steps.js
   8:9  error  'driver' is not defined  no-undef
  13:9  error  'driver' is not defined  no-undef
  22:9  error  'driver' is not defined  no-undef
  27:9  error  'driver' is not defined  no-undef
  33:9  error  'driver' is not defined  no-undef
  39:9  error  'driver' is not defined  no-undef
  42:9  error  'driver' is not defined  no-undef

/Users/nicolas/Develop/Metamask/metamask-mobile/wdio/features/step-definitions/login-view.steps.js
  1:10  error  'Given' is defined but never used            no-unused-vars
  2:1   error  Do not import Node.js builtin module "path"  import/no-nodejs-modules
  2:10  error  'dirname' is defined but never used          no-unused-vars

/Users/nicolas/Develop/Metamask/metamask-mobile/wdio/features/step-definitions/onboarding.steps.js
   1:11  error  'driver' is defined but never used         no-unused-vars
  12:8   error  'BrowserScreen' is defined but never used  no-unused-vars

/Users/nicolas/Develop/Metamask/metamask-mobile/wdio/features/testIDs/Components/AndroidNativeModals.testIds.js
  1:1  error  Prefer default export  import/prefer-default-export

/Users/nicolas/Develop/Metamask/metamask-mobile/wdio/features/testIDs/Screens/LoginScreen.testIds.js
  1:1  error  Prefer default export  import/prefer-default-export

/Users/nicolas/Develop/Metamask/metamask-mobile/wdio/utils/generateTestReports.js
   1:12  error  Expected "import" instead of "require()"   import/no-commonjs
   1:12  error  Do not import Node.js builtin module "fs"  import/no-nodejs-modules
   2:16  error  Expected "import" instead of "require()"   import/no-commonjs
   3:22  error  Expected "import" instead of "require()"   import/no-commonjs
  46:1   error  Expected "export" or "export default"      import/no-commonjs

✖ 55 problems (53 errors, 2 warnings)
  1 error and 1 warning potentially fixable with the `--fix` option.

error Command failed with exit code 1.
```

**Comment by Fatxx** [comment]
> For reference, the issues currently raised:
> 
> ```
> yarn run v1.22.19
> $ eslint '**/*.{js,ts,tsx}'
> =============
> 
> WARNING: You are currently running a version of TypeScript which is not officially supported by @typescript-eslint/typescript-estree.
> 
> You may find that it works just fine, or you may not.
> 
> SUPPORTED TYPESCRIPT VERSIONS: >=3.3.1 <4.5.0
> 
> YOUR TYPESCRIPT VERSION: 4.6.2
> 
> Please only submit bug reports when using the officially supported version.
> 
> =============
> 
> /Users/nicolas/Develop/Metamask/metamask-mobile/app/components/hooks/AppConfig/AppConfig.ts
>   17:2  warning  Missing semicolon  semi
> 
> /Users/nicolas/Develop/Metamask/metamask-mobile/e2e/specs/wallet-tests.spec.js
>   288:3  warning  Test title is used multiple times in the same describe block  jest/no-identical-title
> 
> /Users/nicolas/Develop/Metamask/metamask-mobile/wdio/config/android.config.browserstack.local.js
>    4:22  error  Expected "import" instead of "require()"  import/no-commonjs
>   32:3   error  Unexpected console statement              no-console
>   34:5   error  Expected "export" or "export default"     import/no-commonjs
>   35:5   error  Expected "export" or "export default"     import/no-commonjs
>   37:7   error  Unexpected console statement              no-console
>   45:3   error  Unexpected console statement              no-console
>   47:5   error  Expected "export" or "export default"     import/no-commonjs
>   49:7   error  Unexpected console statement              no-console
> 
> /Users/nicolas/Develop/Metamask/metamask-mobile/wdio/features/screen-objects/AddCustomImportTokensScreen.js
>   27:11  error  'driver' is not defined  no-undef
>   38:11  error  'driver' is not defined  no-undef
>   39:11  error  'driver' is not defined  no-undef
> 
> /Users/nicolas/Develop/Metamask/metamask-mobile/wdio/features/screen-objects/ImportAccountScreen.js
>   28:11  error  'driver' is not defined       no-undef
>   38:27  error  'driver' is not defined       no-undef
>   42:7   error  Unexpected console statement  no-console
> 
> /Users/nicolas/Develop/Metamask/metamask-mobile/wdio/features/screen-objects/Modals/AddressBookModal.js
>   3:10  error  'ENTER_ALIAS_INPUT_BOX_ID' is defined but never used  no-unused-vars
> 
> /Users/nicolas/Develop/Metamask/metamask-mobile/wdio/features/screen-objects/Onboarding/CreateNewWalletScreen.js
>   58:11  error  'driver' is not defined  no-undef
>   64:11  error  'driver' is not defined  no-undef
>   69:11  error  'driver' is not defined  no-undef
> 
> /Users/nicolas/Develop/Metamask/metamask-mobile/wdio/features/screen-objects/Onboarding/ImportFromSeedScreen.js
>   87:7  error  Unexpected console statement  no-console
> 
> /Users/nicolas/Develop/Metamask/metamask-mobile/wdio/features/screen-objects/Onboarding/MetaMetricsScreen.js
>   19:11  error  'driver' is not defined  no-undef
>   33:11  error  'driver' is not defined  no-undef
> 
> /Users/nicolas/Develop/Metamask/metamask-mobile/wdio/features/step-definitions/create-new-wallet-account.steps.js
>    1:10  error  'Given' is defined but never used  no-unused-vars
>   12:9   error  'driver' is not defined            no-undef
>   18:9   error  'driver' is not defined            no-undef
>   27:9   error  'driver' is not defined            no-undef
>   32:9   error  'driver' is not defined            no-undef
>   36:9   error  'driver' is not defined            no-undef
>   37:9   error  'driver' is not defined            no-undef
> 
> /Users/nicolas/Develop/Metamask/metamask-mobile/wdio/features/step-definitions/drawer-view.steps.js
>   1:10  error  'Given' is defined but never used  no-unused-vars
>   1:23  error  'Then' is defined but never used   no-unused-vars
> 
> /Users/nicolas/Develop/Metamask/metamask-mobile/wdio/features/step-definitions/import-tokens.steps.js
>    5:5  error  'setTimeout' is never reassigned. Use 'const' instead  prefer-const
>    8:9  error  'driver' is not defined                                no-undef
>   13:9  error  'driver' is not defined                                no-undef
>   22:9  error  'driver' is not defined                                no-undef
> 
> /Users/nicolas/Develop/Metamask/metamask-mobile/wdio/features/step-definitions/import-wallet-via-private-key.steps.js
>    8:9  error  'driver' is not defined  no-undef
>   13:9  error  'driver' is not defined  no-undef
>   22:9  error  'driver' is not defined  no-undef
>   27:9  error  'driver' is not defined  no-undef
>   33:9  error  'driver' is not defined  no-undef
>   39:9  error  'driver' is not defined  no-undef
>   42:9  error  'driver' is not defined  no-undef
> 
> /Users/nicolas/Develop/Metamask/metamask-mobile/wdio/features/step-definitions/login-view.steps.js
>   1:10  error  'Given' is defined but never used            no-unused-vars
>   2:1   error  Do not import Node.js builtin module "path"  import/no-nodejs-modules
>   2:10  error  'dirname' is defined but never used          no-unused-vars
> 
> /Users/nicolas/Develop/Metamask/metamask-mobile/wdio/features/step-definitions/onboarding.steps.js
>    1:11  error  'driver' is defined but never used         no-unused-vars
>   12:8   error  'BrowserScreen' is defined but never used  no-unused-vars
> 
> /Users/nicolas/Develop/Metamask/metamask-mobile/wdio/features/testIDs/Components/AndroidNativeModals.testIds.js
>   1:1  error  Prefer default export  import/prefer-default-export
> 
> /Users/nicolas/Develop/Metamask/metamask-mobile/wdio/features/testIDs/Screens/LoginScreen.testIds.js
>   1:1  error  Prefer default export  import/prefer-default-export
> 
> /Users/nicolas/Develop/Metamask/metamask-mobile/wdio/utils/generateTestReports.js
>    1:12  error  Expected "import" instead of "require()"   import/no-commonjs
>    1:12  error  Do not import Node.js builtin module "fs"  import/no-nodejs-modules
>    2:16  error  Expected "import" instead of "require()"   import/no-commonjs
>    3:22  error  Expected "import" instead of "require()"   import/no-commonjs
>   46:1   error  Expected "export" or "export default"      import/no-commonjs
> 
> ✖ 55 problems (53 errors, 2 warnings)
>   1 error and 1 warning potentially fixable with the `--fix` option.
> 
> error Command failed with exit code 1.
> ```

Those global variables need to be defined as global in the config files

**Comment by NicolasMassart** [comment]
Note on the blocked status: e2e curently use 2 systems. I think we have to decide how to deal with that before making "cosmetic" cleanup in wdio folder. Once we agree on what we keep or how we deal with both at the same time, then we can unblock this.
