### ISSUE TITLE
 [Bug]: Customize tx Nonce not possible on ERC20 Approve screen when feature is enabled

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-mobile#5645]
**Describe the bug**
When I enable the Customize Tx Nonce feature from the Advance Settings, I am not able to see the Nonce nor Edit it on the ERC20 Approve screen.

**Screenshots**

https://user-images.githubusercontent.com/54408225/215754942-af3a67fc-738c-4772-97e4-5bb7141ebb8a.mp4

**To Reproduce**
_Steps to reproduce the behavior_

1. Go to Advance Settings
2. Enable Customize Tx Nonce
3. Go to Test Dapp https://metamask.github.io/test-dapp/
4. Connect MM
5. Click Create Token
6. Accept tx on MM
7. Click Approve Tokens -- see no Nonce is displayed nor can be edited

**Expected behavior**
Nonce should be visible and editable, when the functionality toggle is ON.

**Smartphone (please complete the following information):**
- Device: Samsung SM-A217F
- OS: Android 11.0
- App Version: v5.12.3 (1033)

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by bschorchit** [comment]
Let's prioritize this issue https://github.com/MetaMask/MetaMask-planning/issues/177 and making sure we enable the nonce to be customized on that new screen.

**Comment by plasmacorral** [comment]
Also reported here: https://github.com/MetaMask/metamask-mobile/issues/5395

**Comment by bschorchit** [comment]
I'll close this in favor of the previous report that Mike mentioned
