### ISSUE TITLE
 [Bug]: ENS resolving to a wrong address when using a Deeplink for an ERC20 Approve tx 

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-mobile#5648]
**Describe the bug**
 When I am performing an ERC20 Approve using a Deeplink, the ENS resolves to a wrong value

**Screenshots**

https://user-images.githubusercontent.com/54408225/215779167-e0389c09-177b-46c8-b937-c71e59dc9a1a.mp4

![image](https://user-images.githubusercontent.com/54408225/215779416-fd88b9d9-31d9-4455-ad6c-ef86ff626410.png)

**To Reproduce**
_Steps to reproduce the behavior_
1. Select Mainnet
2. Open MM Scanner
3. Scan this QR code. It represents this deeplink: https://metamask.app.link/approve/0xFd09911130e6930Bf87F2B0554c44F400bD80D3e@1/approve?address=seaona.eth&uint256=3e18

![image](https://user-images.githubusercontent.com/54408225/215779797-9c13749f-9afa-417c-89db-579a27ba1a78.png)

4. See MM popup
5. Check tx details -- see how the ENS address is resolved to a wrong value (not an address)

**Expected behavior**
ENS Should resolve to the correct address. The address should be seen as the first param of the hex data, after the signature.
See example:

![image](https://user-images.githubusercontent.com/54408225/215780230-77280b05-2aeb-4b7e-b769-e94aae2128d5.png)

**Smartphone (please complete the following information):**

- Device: Samsung SM-A217F
- OS: Android 11.0
- App Version: v5.12.3 (1033)

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by bschorchit** [comment]
Closing as https://github.com/MetaMask/metamask-mobile/pull/5656 was merged
