### ISSUE TITLE
[Bug]: ERC20 Approve screen is not displaying the `Granted to` address field

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-mobile#5651]
**Describe the bug**
As discussed with @blackdevelopa , we realized that the ERC20 Approve screen is not displaying the `Granted to` address field. This means that the user is not able to know to whom is approving the tokens to, unless they open the Tx hex data, and know where to look for the address.

**Screenshots**

https://user-images.githubusercontent.com/54408225/215830753-88af33fc-c057-4a99-b20d-13d7f52c3d34.mp4

**To Reproduce**
_Steps to reproduce the behavior_
1. Go to https://metamask.github.io/test-dapp/
2. Connect MM
3. Click Create Token
4. Accept MM prompt
5. Click Approve Tokens -- see you cannot find anywhere the `Granted to` field

**Expected behavior**
We should see a field where we display to whom we are granting the token approval, like we do on Extension

![image](https://user-images.githubusercontent.com/54408225/215811755-b11dc8d4-ca8b-499a-a5c8-62aa756aed2e.png)

**Smartphone (please complete the following information):**

- Device: Samsung SM-A217F
- OS: Android 11.0
- App Version: v5.12.3 (1033)

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by seaona** [comment]
@bschorchit the copy is also confusing

**Comment by bschorchit** [comment]
If you're comfortable with it, @seaona, I would prefer that we prioritize the new token allowance issues (it seems we're not far from completing it) over re-working copy and components on this screen.

**Comment by seaona** [comment]
Sounds good to me @bschorchit

**Comment by bschorchit** [comment]
Closing this as the new token allowance flow has been merged! 🥳
