### ISSUE TITLE
[Mobile] Create component: Label

### ISSUE THREAD

**Issue by georgewrmarshall** [MetaMask/metamask-mobile#5664]
### **Description**

Componentize `Label` according to the insight report 

Example Screenshot:
<img width="332" alt="Screenshot 2023-02-01 at 3 06 44 PM" src="https://user-images.githubusercontent.com/8112138/216186483-ae0579df-b884-4b5f-8ab5-6ec8c72fc5c4.png">

### **Technical Details**

Unless audited by Design System - Place component in `components-temp` directory location in `app/component-library/components-temp` directory.

- Component Structure (Assume `Label` = your component's name)

  - Under `Label` directory
    - [ ] `Label`.tsx - Actual component file.
    - [ ] `Label`.types.ts - Includes all TypeScript related types/interfaces/enums etc.
    - [ ] `Label`.styles.ts - Includes styles for the `Label` component.
    - [ ] `Label`.test.tsx - Includes both snapshots AND unit tests.
    - [ ] `Label`.stories.ts - Includes stories for the `Label` component.
    - [ ] `Label`.constants.ts - Includes any constants that is used in any `Label` file. For example, test IDs for tests, mappings for the component, etc.
    - [ ] `Label`.utils.ts - Includes any utility functions specific to be used with the `NAME` component.
    - [ ] index.ts - Exports both `Label` component as default and anything else such as types, test IDs, etc if needed.
    - [ ] README.md - Documentation on how the `Label` component will be used and the props associated with it.

- Caveat
  - Components may differ in terms of files to include depending on what is needed.
  - For example - you might not need a constants file or a styles file depending on how the component is built.
  - A more specific example - you can omit the styles file if your component doesn't require styles. Just use your best judgement.
- Refer to an example component such as `AvatarFavicon` for more details.

### **Acceptance Criteria**

- [ ] Snapshot and unit tests pass
- [ ] Storybook shows interactive version of component. Include screenshot or video in pull request for visual reference.
- [ ] Component structure should resemble the structure listed in the Technical Details section above.

### **References**

- [Figma](https://www.figma.com/file/HKpPKij9V3TpsyMV1TpV7C/DS-Components?node-id=7294%3A25180&t=QqFU9YJamwcKLvul-1)
- [FigJam Audit & Insight Report](https://www.figma.com/file/aGW8sk6X6Jf9ac0MRMD4kX/TextField-Audit?node-id=0%3A1&t=ULa7Q5OYfNcoF78F-1)

**Comment by xinnanyemm** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Design-System-61e8a2ae77c3a60012e5003c/issues/MetaMask/metamask-mobile/5664?planning-poker) with Zenhub @Akatori-Design @garrettbear @georgewrmarshall
