### ISSUE TITLE
[Mobile] Create component: BannerTip

### ISSUE THREAD

**Issue by georgewrmarshall** [MetaMask/metamask-mobile#5665]
### **Description**

Componentize `BannerTip` according to the insight report

Example Screenshot:
<img width="584" alt="Screenshot 2023-02-01 at 3 15 27 PM" src="https://user-images.githubusercontent.com/8112138/216188667-af126a15-b478-47af-a9ff-01729f75f9a2.png">

### **Technical Details**

Unless audited by Design System - Place component in `components-temp` directory location in `app/component-library/components-temp` directory.

- Component Structure (Assume `BannerTip` = your component's name)

  - Under `BannerTip` directory
    - [ ] `BannerTip`.tsx - Actual component file.
    - [ ] `BannerTip`.types.ts - Includes all TypeScript related types/interfaces/enums etc.
    - [ ] `BannerTip`.styles.ts - Includes styles for the `BannerTip` component.
    - [ ] `BannerTip`.test.tsx - Includes both snapshots AND unit tests.
    - [ ] `BannerTip`.stories.ts - Includes stories for the `BannerTip` component.
    - [ ] `BannerTip`.constants.ts - Includes any constants that is used in any `NAME` file. For example, test IDs for tests, mappings for the component, etc.
    - [ ] `BannerTip`.utils.ts - Includes any utility functions specific to be used with the `BannerTip` component.
    - [ ] index.ts - Exports both `BannerTip` component as default and anything else such as types, test IDs, etc if needed.
    - [ ] README.md - Documentation on how the `BannerTip` component will be used and the props associated with it.

- Caveat
  - Components may differ in terms of files to include depending on what is needed.
  - For example - you might not need a constants file or a styles file depending on how the component is built.
  - A more specific example - you can omit the styles file if your component doesn't require styles. Just use your best judgement.
- Refer to an example component such as `AvatarFavicon` for more details.

### **Acceptance Criteria**

- [ ] Snapshot and unit tests pass
- [ ] Storybook shows interactive version of component. Include screenshot or video in pull request for visual reference.
- [ ] Component structure should resemble the structure listed in the Technical Details section above.

### **References**

- https://www.figma.com/file/HKpPKij9V3TpsyMV1TpV7C/DS-Components?node-id=12175%3A43581&t=QqFU9YJamwcKLvul-1
- https://www.figma.com/file/ZRc86y4pTE33gLMdrobHCJ/Banner-Audit?node-id=0%3A1&t=SFnUqxHYB1d14p9k-1

**Comment by xinnanyemm** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Design-System-61e8a2ae77c3a60012e5003c/issues/MetaMask/metamask-mobile/5665?planning-poker) with Zenhub @Akatori-Design @garrettbear @georgewrmarshall
