### ISSUE TITLE
add bottom margin on iphone 12 mini add custom network

### ISSUE THREAD

**Issue by mshakeg** [MetaMask/metamask-mobile#5667]
**Describe the usability problem**
On an iPhone mini there isn't enough bottom padding/margin on the Add Custom Network's page, so it isn't possible to click the `Add` button.

**Screenshots**
[screenshots of issue on iPhone 12 mini](https://ibb.co/p14GyV2)

**Proposed behavior**
Add more bottom padding/margin so the Add button can be selected.

------------------------------------------------------------------------------------------------------
_filled out after submission_

**User impact | Usage frequency | Feasibility scores**
_How important is this to the user, what the user wants to accomplish | Daily, weekly, monthly | Small, medium, large_

**Comment by wachunei** [comment]
Comment for the team: the solution to this is to use a ScrollView
