### ISSUE TITLE
[e2e] [android] Edit Gas Fee: allows accessing advance gas fee popover from edit gas fee popover

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-mobile#5699]
ios PR for this for reference: https://github.com/MetaMask/metamask-mobile/pull/5888

**Comment by bschorchit** [comment]
This ios part of this issue might have been completed already with https://github.com/MetaMask/metamask-mobile/pull/5888.
Could you help me confirm this, @segun and @seaona ? If yes, we can update this issue to be android only and keep it in the backlog until while we get clarity from mobile core team on android test tooling migration.

**Comment by bschorchit** [comment]
This has been confirmed over slack. ios for this was completed with #5888 so I'm updating this to be android only and removing from the current sprint.

**Comment by bschorchit** [comment]
Closing as we don't need different tests per platform anymore and test was done for ios here: https://github.com/MetaMask/metamask-mobile/pull/5888
