### ISSUE TITLE
[e2e] [Android] Send ETH to an ENS domain

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-mobile#5705]

**Comment by bschorchit** [comment]
This might be blocked by being able to mock a server response

**Comment by bschorchit** [comment]
Supporting ens resolution on goerli on mobile could be a workaround

**Comment by bschorchit** [comment]
I believe this might be unblocked now that we have support for ganache on e2e?

**Comment by bschorchit** [comment]
Not fully unblocked as we need to mock API responses which we don't have ability to do so yet.

**Comment by seaona** [comment]
This issue is blocked. We need to first implement logic for mocking responses, so then we can mock the response for the ENS resolver contract and use the ENS feature.

**Comment by seaona** [comment]
This issue is unblocked now @bschorchit

**Comment by bschorchit** [comment]
Closing as we don't need separate test per platform anymore and we have completed this test here: https://github.com/MetaMask/metamask-extension/pull/18056
