### ISSUE TITLE
Ledger Bluetooth Sync with Android 12 and higher

### ISSUE THREAD

**Issue by montelaidev** [MetaMask/metamask-mobile#5720]
**Describe the bug**

The ledger nano x is not able to sync with MMM if the android os version is 12 or greater.

https://developer.android.com/guide/topics/connectivity/bluetooth/permissions

**To Reproduce**

1. Tap on Account Icon
2. Tap on 'Connect Hardware Wallet' when the account menu is open
3. Tap on Ledger
4. An error would be shown to prompt the user to open the Ethereum app on the Ledger.  The logs will also show the error `HwTransportError: Cannot start scanning operation. Origin: 600`

**Expected behavior**

A new ledger account will be added to the accounts menu. 

**Smartphone (please complete the following information):**
 - Device: Any android phone
 - OS: Version 12 or higher
 - App Version [e.g. 1.0.0] - find version number in app from Settings > About MetaMask

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by plasmacorral** [comment]
Even though this was closed by the stale bot, I wanted to make a comment that I was able to successfully pair LNX with an Android 14 device (pixel 5a) within 7.17.0 RC testing build 1266
