### ISSUE TITLE
[Bug] Ledger Keyring is missing after resetting password

### ISSUE THREAD

**Issue by montelaidev** [MetaMask/metamask-mobile#5721]
**Describe the bug**

**To Reproduce**
_Steps to reproduce the behavior_
1. Go to `Settings`
2. Tap on `Security & Privacy`
3. Scroll down to `Password` and tap on `Change Password`
4. Enter your current password and tap on `Confirm`
5.  Enter a new password and tap on `Reset password`

The ledger account will then be lost and require restarting the connect hardware flow to re-add the account. 

**Expected behavior**

The ledger account remains after the reset password. 

**Smartphone (please complete the following information):**
 - Device: Samsung A32
 - OS: Version 13
 - App Version v5.14.0(1055)

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by CharlesBlaqk** [comment]
@montelaidev We'd be happy to look into this for you. kindly file a support ticket below 
https://forms.gle/Wmpm6NLzYm9uXYuU9

**Comment by plasmacorral** [comment]
Can confirm this is resolved in 5cab41930adadafd3d37effdfbc9d4b3a418476e 
testing with Samsung a515f running android 11.

**Comment by plasmacorral** [comment]
No longer an issue in commit ddf9f3347c3b2e887f9e465d36f93406e01c147c

**Comment by plasmacorral** [comment]
Observed this in RC 7.17.0 RC testing with iOS 17.3.1 iPhone Xs, using Ledger nano X with FIrmware 2.2.3.

Of note, this is also impacting Keystone in RC 7.17.0.  Will update this issue report to mention that issue once I have a chance to confirm whether this is also impacting Keystone in Production.

**Comment by vivek-consensys** [comment]
Tested locally and working as expected on Samsung Android 13:-


[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNHVSQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--df3fd7cd568eaed7c07e69c223b6b0998fcd84b4/Screen_Recording_20240227_121016_MetaMask.mp4)
