### ISSUE TITLE
There is the same issue for a Token Transfer, see here https://github.com/MetaMask/metamask-mobile/issues/5176

### ISSUE THREAD

**Issue by irisduld1986** [MetaMask/metamask-mobile#5758]
There is the same issue for a Token Transfer, see here https://github.com/MetaMask/metamask-mobile/issues/5176

_Originally posted by @seaona in https://github.com/MetaMask/metamask-mobile/issues/5588#issuecomment-1401720614_

**Comment by tommasini** [comment]
@irisduld1986 thanks for reporting!

Both issues are already addressed and merged, do you mean another issue?
