### ISSUE TITLE
[Bug] Hex data is not cleared when chaging a Token Transfer to Send ETH tx

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-mobile#5759]
**Describe the bug**
When I am on the Confirmation screen for a Send ERC20 transaction, if I go back to Edit it and change the Asset to ETH (or Goerli ETH) and proceed, I see that the Hex Data from the previous Token Transfer is not cleared.

**Screenshots**

https://user-images.githubusercontent.com/54408225/218755988-3644d02a-b7aa-48c8-962c-399bddc148ec.mp4

**To Reproduce**
_Steps to reproduce the behavior_
0. Enable Hex Data from Advanced Settings
1. Import any ERC20 Token (you can use LINK faucet if you don't have any https://faucets.chain.link/)
2. Click on Send ERC20 Token
3. Select recipient
4. Select Amount
5. Proceed to Confirmation screen
6. Click Edit
7. Change Asset to ETH/GoerliETH
8. Proceed to Confirmation screen
9. Check how Hex Data is not emptied

**Expected behavior**
_A clear and concise description of what you expected to happen_
The Hex Data field should be cleared as we have updated the tx to be a Send ETH tx, where hex should be empty by default.

**Smartphone (please complete the following information):**
Device: Samsung SM-A217F
OS: Android 11.0
App Version: v5.14.0 (1055)

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by bschorchit** [comment]
question that came up during planning: what happens if you change back to a ERC-20 transaction?

**Comment by bschorchit** [comment]
> question that came up during planning: what happens if you change back to a ERC-20 transaction?

Tested now and it gets updated correctly. So the only fix needed is clearing up hex data for native token sends.

**Comment by DigitalsupportTeam** [comment]
We'd be happy to look into this for you
kindly file a support ticket below 
https://forms.gle/Wmpm6NLzYm9uXYuU9
