### ISSUE TITLE
[Bug] Gas Fee modal for Legacy tx is displaying the EIP1559 fee modal

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-mobile#5760]
**Describe the bug**
Gas Fee modal for Legacy tx is displaying the EIP1159 fee modal

**Screenshots**

https://user-images.githubusercontent.com/54408225/218763488-000a2c00-a600-41c0-9b8b-b29a3e094eb8.mp4

**To Reproduce**
_Steps to reproduce the behavior_
1. Go to the test-dapp https://metamask.github.io/test-dapp/
2. Connect MM
3. Click Send Legacy Transaction
4. Click Fees
5. Click Edit Fees
6. See the gas modal for EIP1159 tx

**Expected behavior**
_A clear and concise description of what you expected to happen_
On legacy transactions we don't have priority fees. We should display the Gas limit and the Gas price. Take Extension as a reference:

![image](https://user-images.githubusercontent.com/54408225/218763903-dc58ea38-a385-4494-8d1e-629469d60ebe.png)

**Smartphone (please complete the following information):**
Device: Samsung SM-A217F
OS: Android 11.0
App Version: v5.14.0 (1055)

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by DigitalsupportTeam** [comment]
We'd be happy to look into this for you
kindly file a support ticket below 
https://forms.gle/Wmpm6NLzYm9uXYuU9

**Comment by seaona** [comment]
I've added this for the next Sprint if possible, as it is an inconvenience for adding tests as I cannot rely on the correct gas info displayed

**Comment by bschorchit** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/-Confirmations-Secure-UX-6245e6e2348677001213b8d2/issues/MetaMask/metamask-mobile/5760?planning-poker) with Zenhub @blackdevelopa @jpuri @seaona @segun

**Comment by bschorchit** [comment]
Q: Do we have legacy modals on mobile or will this require design too? Not clear if we do have legacy modal

**Comment by SayaGT** [comment]
Hello, you can find the design here
https://www.figma.com/file/aHdSNvg9ahXZMtThzz3bUo/Bugs?type=design&node-id=1%3A13803&mode=design&t=tobOzS87YOReqDgm-1
