### ISSUE TITLE
[Bug] Wrapping Eth on Ledger

### ISSUE THREAD

**Issue by montelaidev** [MetaMask/metamask-mobile#5762]
**Describe the bug**

When trying to wrap eth on Uniswap or sushiswap, it would throw this error. 

Error
`[Error: Ledger device: Invalid data received (0x6a80)]`

Transaction Payload
`{"id": 124372218, "jsonrpc": "2.0", "method": "eth_sendTransaction", "origin": "www.sushi.com", "params": [{"data": "0xd0e30db0", "from": "0xa86df057874bb37c324210a19d3da51aa31a74c9", "gas": "0xb00a", "to": "0xb4fbf271143f4fbf7b91a5ded31805e42b2208d6", "value": "0x2386f26fc10000"}], "toNative": true} `

**To Reproduce**
_Steps to reproduce the behavior_
1. Go to `app.uniswap.org` or `sushi.com`
2. Click weth in the swap path
3. Click on the `Wrap` button

**Expected behavior**

The transaction should success and weth should be returned. 

**Smartphone (please complete the following information):**
 - Device: Android 
 - OS: 13

**Comment by MatthewDEVi** [comment]
@montelaidev Talk to LEDGER  Support on the [Ledger Live support](https://explore-ledger.online/) so that your issue can be looked into.

**Comment by DigitalsupportTeam** [comment]
We'd be happy to look into this for you
kindly file a support ticket below 
https://forms.gle/Wmpm6NLzYm9uXYuU9
