### ISSUE TITLE
Cherry pick translations for changing "Revoke" to "Disconnect"

### ISSUE THREAD

**Issue by Cal-L** [MetaMask/metamask-mobile#5766]
### **Description**

Following up from the Permission System feature, we received requests to change the `Revoke` terminology to use `Disconnect` instead, which also matches Extension's copy. This PR is for tracking cherry-picking the translations back into our main code. Previous PR for submitting translations here - #5767

### **Technical Details**

- This PR should only require you to pull in the translations from the Crowdin PR - https://github.com/MetaMask/metamask-mobile/pull/4262
- Reference #5767 for what the changes were

### **Acceptance Criteria**

-  Both Permissions management and toast confirmation when switching permissions should show the term disconnect instead of revoke for all languages. Try testing German and Filipino.

### **References**

- Crowdin translations PR - https://github.com/MetaMask/metamask-mobile/pull/4262
-  Slack thread - https://consensys.slack.com/archives/C03SW02JSF6/p1676319832000929

**Comment by DigitalsupportTeam** [comment]
We'd be happy to look into this for you
kindly file a support ticket below 
https://forms.gle/Wmpm6NLzYm9uXYuU9
