### ISSUE TITLE
Submit translations for changing "Revoke" to "Disconnect"

### ISSUE THREAD

**Issue by Cal-L** [MetaMask/metamask-mobile#5767]
### **Description**

Following up from the Permission System feature, we received requests to change the `Revoke` terminology to use `Disconnect` instead, which also matches Extension's copy. This ticket is used to track submitting translations for Crowdin to translate.

### **Technical Details**

Change from this in the en.json file
![image.png](https://images.zenhubusercontent.com/5772d2f9bf93871ccd9d4f97/9a10b8d5-730e-4347-8ae9-071cbb7eca5d)
to this in the en.json file
![image.png](https://images.zenhubusercontent.com/5772d2f9bf93871ccd9d4f97/67e6cba1-a8de-4447-a0c7-c5b28d282f80)

### **Acceptance Criteria**

-  Both Permissions management and toast confirmation when switching permissions should show the term disconnect instead of revoke for English only. Other languages will be applied once translations are returned from Crowdin.

### **References**

- Crowdin translations PR - https://github.com/MetaMask/metamask-mobile/pull/4262
-  Slack thread - https://consensys.slack.com/archives/C03SW02JSF6/p1676319832000929

**Comment by DigitalsupportTeam** [comment]
We'd be happy to look into this for you
kindly file a support ticket below 
https://forms.gle/Wmpm6NLzYm9uXYuU9
