### ISSUE TITLE
Follow up with AssetsContractController PR and remove patch

### ISSUE THREAD

**Issue by Cal-L** [MetaMask/metamask-mobile#5773]
### **Description**

In 6.0.0, we introduced a patch to the `AssetsContractController` to support watching an asset for an account other than the active account on a wallet. This PR is meant to address a follow up PR to introduce these changes into the core controllers and to remove the patch from the mobile codebase.

### **Technical Details**

- TBD - Reference the patch and make improvements

### Acceptance Criteria
- User should still have the ability to watch/add an assets to an account other than their active account on the wallet
- To test
   - Make Account#1 active on the wallet
   - Connect with Account#2 to Uniswap
   - Swap with a token that you do not currently own
   - After the swap, you should be prompted with the ability to add the token to Account#2
   - Proceed with adding the asset to Account#2
   - Navigate to the Wallet tab
   - Notice that the added asset does not show in Account#1
   - Switch the wallet account to Account#2
   - Notice the added asset appears in the asset list

### **References**

- Patch to remove - https://github.com/MetaMask/metamask-mobile/blob/release/6.0.0/patches/%40metamask%2Bassets-controllers%2B1.0.1.patch

**Comment by DigitalsupportTeam** [comment]
We'd be happy to look into this for you
kindly file a support ticket below 
https://forms.gle/Wmpm6NLzYm9uXYuU9

**Comment by Cal-L** [comment]
Will follow up with ticket for mobile repo to remove patch and upgrade library.
