### ISSUE TITLE
iOS app consumes a lot of traffic

### ISSUE THREAD

**Issue by hardloaf** [MetaMask/metamask-mobile#5781]
**Describe the bug**
The app consumes a lot of traffic. It makes it very expensive to run on limited data plans. Compared to competitors it's over 10 times more. Simple launch takes about 1.4Mb. It also makes app slow. This should be optimized.

**Screenshots**
<img width="310" alt="Screenshot 2023-02-17 at 09 29 18" src="https://user-images.githubusercontent.com/1706408/219726459-6e7b74c8-7e50-486b-add3-7bca29cbfcc1.png">

**To Reproduce**
Just launch the app on Apple Silicone macOS with network filter and check the stats.

**Expected behavior**
50-100K should be enough for basic operations.

**Smartphone (please complete the following information):**
iOS 13

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by DigitalsupportTeam** [comment]
We'd be happy to look into this for you
kindly file a support ticket below 
https://forms.gle/Wmpm6NLzYm9uXYuU9

**Comment by cortisiko** [comment]
hey @hardloaf we are currently investigating this issue. Once we have a solution in place, we will update this ticket.
