### ISSUE TITLE
Automation: Add ToU to Onboarding e2e for new mobile app installs

### ISSUE THREAD

**Issue by chrisleewilcox** [MetaMask/metamask-mobile#5783]
https://app.zenhub.com/workspaces/metamask-mobile-5f984938ddc0e4001d4b79cb/issues/gh/metamask/mobile-planning/466

```
Feature: Terms of Use

 Scenario: Install and launch app
  Given the app displayed the splash animation
  Then Terms of Use is displayed

 Scenario: Attempt to bypass ToU without accepting terms
  When I attempt to dismiss Terms of Use without agreeing to terms
  Then Terms of Use is displayed
  And I am not able to move forward
  When I restart app
  Then Terms of Use is displayed

 Scenario: Agree to terms
  When I agree to terms
  Then Terms of Use is not displayed
  When I have imported my wallet
  And I tap No Thanks on the Enable security check screen
  And I tap No thanks on the onboarding welcome tutorial

 Scenario: Restart app after accepting terms
  When app is restarted
  Then Terms of Use is not displayed
  And I am on Wallet view
```
Acceptance Criteria:
- add ToU steps to /step-definitions/onboaring.steps.js (will require new page objects for ToU)
- utilize existing feature file steps as much as possible
- test pass on browserstack

**Comment by NicolasMassart** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/MetaMask-Mobile-5f984938ddc0e4001d4b79cb/issues/MetaMask/metamask-mobile/5783?planning-poker) with Zenhub @Andepande @SamuelSalas @chrisleewilcox

**Comment by cortisiko** [comment]
this task is based on https://github.com/MetaMask/metamask-mobile/pull/5242
