### ISSUE TITLE
[Bug] `transfer` an ERC20 Token does not display Recipient, Contract nor Hex Data (if enabled) when performed from a Dapp

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-mobile#5786]
**Describe the bug**
_A clear and concise description of what the bug is_
When I perform an ERC20 Token Transfer, the Transfer screen does not display the following information:
- Recipient Address
- Token Contract Address
- Hex Data (if enabled on Settings)

**Screenshots**
_If applicable, add screenshots or links to help explain your problem_

![image](https://user-images.githubusercontent.com/54408225/220063330-22c673c7-4efb-41e4-8079-a903d0fafc69.png)

**To Reproduce**
_Steps to reproduce the behavior_
1. Go to Test Dapp https://metamask.github.io/test-dapp/
2. Connect MM
3. Click Create Token -- Accept MM prompt
4. Click Transfer Tokens -- see missing information from recipient address, token contract address and Hex Data (if enabled on Settings)

**Expected behavior**
_A clear and concise description of what you expected to happen_
I am expecting to see the information:
- Recipient Address
- Token Contract Address
- Hex Data (if enabled on Settings)

See Extension Transfer screen:

![image](https://user-images.githubusercontent.com/54408225/220063836-a6c58e47-1cf6-498a-ab91-19aec0144de5.png)

**Smartphone (please complete the following information):**

- Device: Pixel 6
- OS: Android 12
- App Version: v5.14.0 (1055)

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by DigitalsupportTeam** [comment]
We'd be happy to look into this for you
kindly file a support ticket below 
https://forms.gle/Wmpm6NLzYm9uXYuU9
