### ISSUE TITLE
[Bug] `transfer` an ERC20 Token from inside MetaMask does not display the Token Contract Address nor the method name

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-mobile#5787]
**Describe the bug**
_A clear and concise description of what the bug is_
`transfer` an ERC20 Token from inside MetaMask does not display the Token Contract Address nor the method name

**Screenshots**
_If applicable, add screenshots or links to help explain your problem_

![image](https://user-images.githubusercontent.com/54408225/220064892-dd7ba73d-c70a-485f-a0d2-6d7fdb345a5e.png)

**To Reproduce**
_Steps to reproduce the behavior_
1. Import an ERC20 Token
2. Click Send that token
3. Add recipient
4. Add amount
5. See how in the confirmation screen we don't see the contract address nor the method name `transfer`

**Expected behavior**
_A clear and concise description of what you expected to happen_
Display the Token Contract address and the token name in the same way we have on Extension:

![image](https://user-images.githubusercontent.com/54408225/220065361-725b17f8-e8e8-4057-b558-15ff518b37bb.png)

**Smartphone (please complete the following information):**
- Device: Pixel 6
- OS: Android 12
- App Version: v5.14.0 (1055)

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by DigitalsupportTeam** [comment]
We'd be happy to look into this for you
kindly file a support ticket below 
https://forms.gle/Wmpm6NLzYm9uXYuU9
