### ISSUE TITLE
Remember me toggle is ON in settings after login in with remember me toggle OFF

### ISSUE THREAD

**Issue by olenapankina** [MetaMask/metamask-mobile#5790]
**Tested on**
prod 5.14.0 (1055)
iPhone 12 iOS 16.3.1
Samsung Galaxy M21 Android 12, One UI Core version 4.1

**Steps to reproduce:**

1. Remember me is ON
2. Lock the app
3. Login with Remember me toggle off
4. Relaunch the app
5. Observe

**Actual result:** remember me is ON in settings, remember me is not working, toggle is presented on login page
**Expected result:** remember me is OFF in settings, remember me toggle is not presented on login page

https://user-images.githubusercontent.com/116747263/220120768-4dc9754e-09aa-4fba-9ada-e57e15cb42c7.mp4

**Comment by chrisleewilcox** [comment]
@SamuelSalas @cortisiko does the automation for Remember me test for this scenario?
https://app.zenhub.com/workspaces/metamask-mobile-5f984938ddc0e4001d4b79cb/issues/gh/metamask/mobile-planning/419

**Comment by chrisleewilcox** [comment]
Need product review for clarification on Remember me Settings toggle.

**Comment by DigitalsupportTeam** [comment]
We'd be happy to look into this for you
kindly file a support ticket below 
https://forms.gle/Wmpm6NLzYm9uXYuU9
