### ISSUE TITLE
App crashes when deep-linking to external app from in-app-browser

### ISSUE THREAD

**Issue by Cal-L** [MetaMask/metamask-mobile#5794]
### **Description**

Discovered in 6.0.0 production release - There is a crash that exists when a user tries to deep-link to an app from within the app-browser. Ex. In certain instances - opening CoinGecko from the in-app browser will show a prompt asking to open CoinGecko's app. Once tapped, the app will crash and display and error similar to this `View: Root TypeError: Invalid URL: null`. Wallet reset is needed at this stage since app will continue to crash after re-opening. There has been reports on both iOS and Android. Note - This was reproducible by @jpcloureiro on Android but is yet to be reproduced on iOS.

### **Technical Details**

- TBD @jpcloureiro is looking into this

### **Acceptance Criteria**

- TBD - What is the expected behavior. Should the Dapp be prompting open external app in the first place? Or is this expected and the deeplink should work?

### **References**

-  Slack thread with the report - https://consensys.slack.com/archives/C029JG63136/p1676913300770899?thread_ts=1676576106.582359&cid=C029JG63136

**Comment by jpcloureiro** [comment]
We should maintain the same behavior as 5.14.0 and present this screen to the user whenever they try to open these special URLs (deeplinks) from within In-App browser

<img width="387" alt="image" src="https://user-images.githubusercontent.com/1649425/220201130-537e458f-e3d0-4ef2-9751-dc1fa3112713.png">

**Comment by samlogic-ship** [comment]
I have also been locked out of the mobile app 

![IMG_5547](https://user-images.githubusercontent.com/113727328/220411905-daa42202-5efd-47fa-b39a-f4ea04dc7741.png)
