### ISSUE TITLE
gasLimit estimation issue in payment links

### ISSUE THREAD

**Issue by PieroEnriquez** [MetaMask/metamask-mobile#5798]
### **Description**

The gasLimit estimation on Polygon mainnet is failing when used a payment link and sometimes on manual transaction.

### **Technical Details**

The estimation of gasLimit through deeplinks and normal payment links is set it too low in Polygon Mainnet so the user has to modify it higher so the transaction is accepted.

**Comment by DigitalsupportTeam** [comment]
We'd be happy to look into this for you
kindly file a support ticket below 
https://forms.gle/Wmpm6NLzYm9uXYuU9

**Comment by juscamarena** [comment]
Here's an example of one: https://polygonscan.com/tx/0x6df18797e88f0fbc7d7726c331b923b71f1f0252747dae791996490ca393e450
