### ISSUE TITLE
Cache Yarn dependencies in Bitrise

### ISSUE THREAD

**Issue by Gudahtt** [MetaMask/metamask-mobile#5810]
### **Description**

We should cache dependencies in Bitrise to improve speed and reliability of CI workflows.

### **Technical Details**

We should ensure this cache does not make the build difficult to reproduce, which would make auditing difficult. The build must be reproducible, at least to the degree that the lockfile allows.

Caching `node_modules` could result in a difficult-to-reproduce build because it could lead to a different directory structure when the build runs, and it could cache the output of `postinstall` steps that aren't intended to be run multiple times.

However it should be save to cache the Yarn cache because it doesn't affect hoisting, and doesn't include any content that gets modified during the install process.

### **Acceptance Criteria**

- Dependencies are cached between CI runs
- Builds are no more difficult to reproduce locally than they were before
  - e.g. we're caching the Yarn cache directory, not `node_modules`

**Comment by DigitalsupportTeam** [comment]
We'd be happy to look into this for you
kindly file a support ticket below 
https://forms.gle/Wmpm6NLzYm9uXYuU9
