### ISSUE TITLE
Unable to intuitively set custom transaction nonce to 0

### ISSUE THREAD

**Issue by deshvin** [MetaMask/metamask-mobile#5817]
**Scenario**
This may be an edge case scenario, but consider the following:
A user creates a new MetaMask wallet. They modify the gas price for their first transaction to a value that is too low to be picked up any time soon, so they must cancel it with a self transaction. Since the first transaction of the account must be cancelled, they must submit the self transaction with a nonce of 0.

**Describe the bug**
When pressing the (-) button in the custom nonce screen, it does not go below 1. Furthermore, tapping into the nonce number seems to be a text area, but the keyboard does not show (though I don't necessarily think a keyboard _should_ show in this case). A clunky workaround is to copy the number 0 and paste it into the nonce area.

**Screenshots**
https://user-images.githubusercontent.com/2859402/220767859-ff25c14f-f5eb-42fa-979c-484d3783caa1.MP4

**To Reproduce**
_Steps to reproduce the behavior_
1. Enable **Customize transaction nonce** setting in Advanced settings
2. Start a transaction
3. On the transaction confirmation screen, tap **Edit** next to Nonce
4. Select the minus (-) button to lower the nonce value to 0 (doesn't work)
5. Tap into the nonce number area to manually set nonce value to 0 (no keyboard appears)
6. Copy-paste '0' into the nonce area to set the nonce value to 0

**Expected behavior**
I should be able to set the transaction once value to '0' by pressing the minus (-) button in the Edit transaction nonce screen

**Smartphone (please complete the following information):**
 - Device: iPhone 12 Pro Max
 - OS: iOS 16.3.1
 - App Version: 6.0.0

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by DigitalsupportTeam** [comment]
We'd be happy to look into this for you
kindly file a support ticket below 
https://forms.gle/Wmpm6NLzYm9uXYuU9

**Comment by bschorchit** [comment]
Related to https://github.com/MetaMask/metamask-mobile/issues/4813
