### ISSUE TITLE
Create component: CookieCutter 

### ISSUE THREAD

**Issue by georgewrmarshall** [MetaMask/metamask-mobile#5818]
### **Description**

Create `CookieCutter` component based on audit and insight report 

<img width="677" alt="Screenshot 2023-02-22 at 4 09 39 PM" src="https://user-images.githubusercontent.com/8112138/220784226-97a08642-3bde-4a28-b536-3ec515ac585d.png">

### **Technical Details**
- size: xs, sm, md, lg, xl
- children: any
- shape: circle, rectangle, hexagon
Customizable
- borderColor
- backgroundColor
- textColor

### **Acceptance Criteria**
- Component exists built to specifications outlined in insight report
 
### **References**

[FigJam](https://www.figma.com/file/pQa2vI7r08pHiqsAPTWdQ8/Avatar%2C-Token%2C-Network%2C-Icon%2C-Badge-Audit?node-id=607%3A121&t=fedx1fSP0xZPIvat-1)

**Comment by DigitalsupportTeam** [comment]
We'd be happy to look into this for you
kindly file a support ticket below 
https://forms.gle/Wmpm6NLzYm9uXYuU9
