### ISSUE TITLE
Automation: Fix app double launch issue

### ISSUE THREAD

**Issue by chrisleewilcox** [MetaMask/metamask-mobile#5821]
When running test suite some feature files will cause the app to launch two times before executing the feature test.  This may be causing some instability issues when running test suite on browserstack.

Ensure the app is only launched once between test.

Can `Background` keyword be what we need?

**Comment by DigitalsupportTeam** [comment]
We'd be happy to look into this for you
kindly file a support ticket below 
https://forms.gle/Wmpm6NLzYm9uXYuU9
