### ISSUE TITLE
Metamask SDK with React Native: disconnect doesn't work

### ISSUE THREAD

**Issue by eloudsa** [MetaMask/metamask-mobile#5828]
Hello,

I have a problem with Metamask SDK on React Native.

I developed a small application with React Native using Metamask SDK. I followed this [link] (https://c0f4f41c-2f55-4863-921b-sdk-docs.github.io/guide/metamask-sdk-js/metamask-sdk-react-native.html).

I deployed my dApp on a real Android device (Android 13 - Pixel 7 Pro). Metamask is installed and configured on this device.

I can connect to Metamask, get the network ID, the account and its balance.

I tried to disconnect the wallet as explained [here](https://support.metamask.io/hc/en-us/articles/360059535551-Disconnect-wallet-from-a-dapp).

But if I clear the Metamask privacy data to force a disconnect, my dApp does not receive a "disconnect" event. 

If I change my account, my dApp is still able to detect a change of account or network as if the wallet was still connected to the dApp.

How do I detect that the wallet has been disconnected from the application?

Thanks

**Comment by DigitalsupportTeam** [comment]
We'd be happy to look into this for you
kindly file a support ticket below 
https://forms.gle/Wmpm6NLzYm9uXYuU9
