### ISSUE TITLE
Two tabs are created when opening the browser in metamask using deep link in metamask app v6.

### ISSUE THREAD

**Issue by Rapid-Fire-y** [MetaMask/metamask-mobile#5831]
In metamask app v6, two tabs are created when opening the browser in metamask using deep link.
I would like to fix this bug because I would like to have only one tab for the session.

**Comment by DigitalsupportTeam** [comment]
We'd be happy to look into this for you
kindly file a support ticket below 
https://forms.gle/Wmpm6NLzYm9uXYuU9
