### ISSUE TITLE
Display internet protocol on the new origin pill 

### ISSUE THREAD

**Issue by bschorchit** [MetaMask/metamask-mobile#5832]
## Background
Currently on the new origin pill we don't display the internet protocol, but we should do it for security reasons.

More context here: https://github.com/MetaMask/metamask-mobile/pull/5309#issuecomment-1443471327

![image](https://user-images.githubusercontent.com/34968356/221197719-1520d19a-3c3e-46cd-b412-cbbf6e7e746a.png)

**Comment by DigitalsupportTeam** [comment]
We'd be happy to look into this for you
kindly file a support ticket below 
https://forms.gle/Wmpm6NLzYm9uXYuU9
