### ISSUE TITLE
Deep linking from metamask app browser

### ISSUE THREAD

**Issue by thefrankk** [MetaMask/metamask-mobile#5835]
### **Description**

Problem about opening a deep link from metamask app browser (Android).

We cannot open a deep link from metamask app browser, but we really can from normal web, like Chrome or an basic app with only 1 button to execute the deep link.

### **Technical Details**

We don't know if we have to make a custom install, from web or app, the deep link works well.

**Comment by DigitalsupportTeam** [comment]
We'd be happy to look into this for you
kindly file a support ticket below 
https://forms.gle/Wmpm6NLzYm9uXYuU9
