### ISSUE TITLE
While connected to zkSync, scanning a QR code with the camera switches the network back to mainnet

### ISSUE THREAD

**Issue by Montoya** [MetaMask/metamask-mobile#5836]
**Describe the bug**
A user is connecting to the zkSync network to send BUIDLBux: https://zksync2-testnet.zkscan.io/token/0xf551954D449eA3Ae4D6A2656a42d9B9081B137b4/token-transfers

Then they open the camera to scan a QR code, but the mobile app switches back to mainnet and they cannot copy the address that was scanned from the QR code. So they are unable to send on zkSync. 

**To Reproduce**
1. Set the network to zkSync
2. Open the camera to scan a QR code
3. Note that the network is set to mainnet after scanning

**Expected behavior**
The send flow should be on zkSync

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by chrisleewilcox** [comment]
If the QR code is generated from device that is connected to mainnet then it's a mainnet QR code and scanning it will switch to mainnet as expected.

Scanned zkSync QR code....
https://recordit.co/6ouplz8wZw
Working for me.

**Comment by Montoya** [comment]
Thank you
