### ISSUE TITLE
Problems with MetaMask in Android

### ISSUE THREAD

**Issue by Yezhiang** [MetaMask/metamask-mobile#5837]
I would like to ask that when we visit the H5 page from the browser on the mobile terminal, click on the H5 interface to connect the MetaMask wallet, then connect the wallet and open the browser in the MetaMask App, we can normally interact with the blockchain contract.  But at this time will report the Provider not set or invalid error is what is going on, and how to solve?  Visiting the H5 page directly from the browser inside the MetaMask App will not happen, and it will not happen on ios, only Android phones

**Comment by DigitalsupportTeam** [comment]
We'd be happy to look into this for you
kindly file a support ticket below 
https://forms.gle/Wmpm6NLzYm9uXYuU9
