### ISSUE TITLE
"Unable To Load Balance" Error on Release build (ETH Main network)

### ISSUE THREAD

**Issue by phuongcodelight** [MetaMask/metamask-mobile#5838]
**Describe the bug**
There's an error occured after adding a new token in **Ethereum Main Network**. When I tried to log the balanceError, it said: **{ reason:could not detect network, code:NETWORK_ERROR, event:noNetwork }**.

For many times of testing, I found that this error only happens with **Ethereum Main Network and on Release mode only**. Everything seems fine on Debug mode.

I tried to search this error log on the Internet and it seems relates to **etherjs** library?

**Screenshots**
![Simulator Screen Shot - iPhone 14 - 2023-02-27 at 02 50 18](https://user-images.githubusercontent.com/119278016/221433526-696fe336-a0d6-41e9-9219-d9d75362037b.png)

**To Reproduce**
1. Go to Wallet screen
2. Import a new Token
3. See the error in the token item

**Expected behavior**
Balance should be loaded normally.

**Smartphone:**
 - Device: iPhone 14 (simulator & real device)
 - OS: iOS
 - App Version: v6.0.1 (1072)

-------------------------------------------------------------

**Comment by DigitalsupportTeam** [comment]
We'd be happy to look into this for you
kindly file a support ticket below 
https://forms.gle/Wmpm6NLzYm9uXYuU9

**Comment by tommasini** [comment]
Hey @phuongcodelight thanks for reporting!

We will look into it!

**Comment by phuongcodelight** [comment]
@tommasini Thank you for responding. I finally found out the issue was from me. I set up **react-native-config** lib for environmental dev purposes. This caused Release mode could not read the **Infura API KEY in .js.env**. Move this key to my own .config file solved the problem!
