### ISSUE TITLE
TypeError: Invalid URL: null

### ISSUE THREAD

**Issue by ejwessel** [MetaMask/metamask-mobile#5867]
**Describe the bug**
Closing a `null` tab within the mobile browser results in `An Error Occurred` message that cannot be closed or moved away from.
The error is: 
```
View: Root
TypeError: Invalid URL: null
```
The error screen seems to persist through phone restarts and app force close/restarts.

**Screenshots**
![image](https://user-images.githubusercontent.com/3590816/222197944-720fa24a-778f-4f6d-93ee-728c4e22b06d.png)

**To Reproduce**
1. MetaMask Mobile refused to open (diamond would show, but never unfold to fox)
1. I upgraded MetaMask Mobile to the most recent version v6.0.0 (1068). Unsure what previous version I was on.
1. I visited the browser within the Mobile app
1. I saw there was an open tab labeled `null` - or something close to this
1. I closed the `null` tab resulting in the above error screen message
1. I attempted to force closed the app restart the phone many times. Each time the above error message continued to appear until I uninstalled and reinstalled.
1. I am unable to reproduce with the above steps however after I reinstalled the app; there is no longer a null tab.

**Expected behavior**
Closing tabs doesn't result in a failed crash stated that cannot be resolved.

**Smartphone (please complete the following information):**
 - Device: iPhoneXS
 - OS: iOS16
 - App Version v6.0.0

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by tommasini** [comment]
Hey @ejwessel, thanks for reporting, this is a know issue and we are working to release it, I will update this when the next version is released

**Comment by tommasini** [comment]
This issue still persists and will need reproduction!
@witmicko @ejwessel We really appreciate if you help us understand better how we reproduce it

**Comment by cortisiko** [comment]
This issue was addressed in v6.0.1. I will go ahead and close this issue. If it still persists we will reopen and investigate again.
