### ISSUE TITLE
Add Bridge icon

### ISSUE THREAD

**Issue by georgewrmarshall** [MetaMask/metamask-mobile#5885]
### **Description**

Add new Bridge icon svg

### **Technical Details**
- TBC svg files
- Add new Bridge svg

### **Acceptance Criteria**

- Icon name should match Figma and Extension

### **References**

- Bridge icon PR in extension https://github.com/MetaMask/metamask-extension/pull/17952
- Icon docs https://www.notion.so/Need-a-new-icon-b232f7c62a6f45bb81749cccb21904b8?pvs=4
- https://github.com/MetaMask/design-tokens/issues/402

**Comment by brianacnguyen** [comment]
PR https://github.com/MetaMask/metamask-mobile/pull/6145
