### ISSUE TITLE
metamask.request is not working on metamask browser

### ISSUE THREAD

**Issue by erik0612** [MetaMask/metamask-mobile#5889]
**Describe the bug**
metamask.request is not working if I back to dapp after went other url with taget="_blank"

**To Reproduce**
_Steps to reproduce the behavior_
1. Open dapp
2. Go to any other website
3. Click back button (to go back dapp)
4. send metamask.request in dapp

**Expected behavior**
metamask.request should work even if we open new website and then back to dapp by clicking `back` button in metamask browser.

**Smartphone (please complete the following information):**
 - Device: [iPhone12]
 - OS: [iOS16.3.1]
 - App Version [6.0.0]

**Comment by tommasini** [comment]
@erik0612 Hey, thanks for reporting!

Are you using the in-app browser or using your native browser like safari?

We would appreciate more details so we reproduce it! Thanks again!

**Comment by erik0612** [comment]
Hi @tommasini 
it happens on in-app browser.

**Comment by chrisleewilcox** [comment]
Thanks for your contribution @erik0612.  When you navigate back to the dapp what is the impact exactly?  Is the wallet no longer connected?  Can you provide a video for us to further investigate?
