### ISSUE TITLE
TypeError: undefined is not an object (evaluating 't.networkType')

### ISSUE THREAD

**Issue by anaamolnar** [MetaMask/metamask-mobile#5894]
![image](https://user-images.githubusercontent.com/82837486/222761266-bbd7ce38-3a65-4e3a-bf96-311d6bdb343c.png)
![image](https://user-images.githubusercontent.com/82837486/222761349-4240ba9b-4fdd-4910-851f-af27853adc7c.png)

OS: Android, iOS
Version: 6.0.0, 6.0.1

Steps to reproduce: 
	
1. Go to Settings->Networks
2. Search for any custom network name
3. Error appears

Workaround: 
Click Try again-> You are redirected to the login page-> Login->App works normally

**Comment by chrisleewilcox** [comment]
This issues was fixed in v6.1.0 of the app....
https://github.com/MetaMask/metamask-mobile/pull/5851
