### ISSUE TITLE
iOS - Cancel Biometric on Wallet Creation is Stuck on Creating Wallet View

### ISSUE THREAD

**Issue by sethkfman** [MetaMask/metamask-mobile#5897]
**Describe the bug**
On iOS when a user creates a wallet with biometrics enabled and is prompted to present their biometrics and the cancels the biometric prompt they are stuck on the "Creating Wallet View"

**Screenshots**
_If applicable, add screenshots or links to help explain your problem_

**To Reproduce**
_Steps to reproduce the behavior_
1. New app install Create Wallet
2. Click on create wallet
3. Enter password and enable biometric
4. Create wallet 
5. Biometric prompt displays
6. tap `Don't Allow` at the biometric permissions prompt
7. See creating wallet view continues to display. 

**Expected behavior**
The wallet should be created without biometrics enabled if the user cancels biometric.

**Smartphone (please complete the following information):**
 - Device: iPhone SE
 - OS: iOS 16
 - App Version [e.g. 1.0.0] - 6.0.0 and greater

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
   - Blocking iOS approval
- Add stats if available on % of customers impacted
- Is this visible to all users?
  - No, is an edge case and non-blocking
- Is this tech debt?
  - It does existing in previous versions ![Screenshot-0303-154841.png](https://images.zenhubusercontent.com/602c3c981617aad4ad2160f8/8bd00922-d040-4937-88b3-1f15bff58aa7)

![Screenshot-0303-154841.png](https://images.zenhubusercontent.com/602c3c981617aad4ad2160f8/4cb7b142-0b37-4b2b-9abb-7c2e6bcc693c)

**Comment by omnat** [comment]
Wallet authentication and access flows are part of our test suites correct? How come we didn't catch this issue before submitting for store review? @cortisiko

**Comment by plasmacorral** [comment]
It was already reported in 5404, and I just double checked to confirm that things resolved with auth refactor in my test of build 1073. PR 5374 has been merged to main and is targeted for 6.2. 

 https://github.com/MetaMask/metamask-mobile/issues/5404

https://github.com/MetaMask/metamask-mobile/pull/5374

**Comment by cortisiko** [comment]
hey @omnat as @plasmacorral mentioned above, this was caught a few months ago and reported in https://github.com/MetaMask/metamask-mobile/issues/5404, the fix should be in 6.2.

Surfacing this here, we also have [another instance](https://github.com/MetaMask/mobile-planning/issues/680) where the app is stuck in a loading state when rejecting biometrics authentication.

**Comment by plasmacorral** [comment]
Can confirm that this is resolved in production v6.4 build 1100 with iOS 15.6 on iPhone 13 mini. 

https://recordit.co/LSQpdQn2TC
