### ISSUE TITLE
[Bug] Converting native ETH to fiat and fiat to native ETH results in wrong values beign displayed on the Amount screen

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-mobile#5898]
**Describe the bug**
When I am performing a Send ETH and I introduce an amount, if I click to convert to fiat and back to native, the amounts are not correct anymore.

**Screenshots**

https://user-images.githubusercontent.com/54408225/223138506-62560219-f391-4431-86c2-9e8b41bedf70.mp4

**To Reproduce**
_Steps to reproduce the behavior_
1. Click Send ETH
2. Add Recipient
3. Introduce amount
4. Switch to fiat -- see incorrect amount
5. Switch to native -- see incorrect amount

**Expected behavior**
Conversion values should be correct

**Smartphone (please complete the following information):**

- 
- Device: Pixel 6
- OS: Android 12
- App Version: v6.0.1 (1078)

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by bschorchit** [comment]
Maybe related with https://github.com/MetaMask/metamask-mobile/pull/5777

**Comment by bschorchit** [comment]
Reopening this so the PR goes through QA and is added to a release :)
