### ISSUE TITLE
[Mobile] Create component: BottomSheetHeader

### ISSUE THREAD

**Issue by georgewrmarshall** [MetaMask/metamask-mobile#5914]
### **Description**

Create `BottomSheetHeader` component according to the insight report.

### **Technical Details**
See [insight report ](https://www.figma.com/file/hxYqloYgmVcgsoiVqmGZ8K/Modal-Audit?node-id=493%3A237&t=qT7tm4EFb9ZsczK5-1)

### **Acceptance Criteria**
- Built according to insight report

### References
[Modal Audit and Insight Report FigJam](https://www.figma.com/file/hxYqloYgmVcgsoiVqmGZ8K/Modal-Audit?node-id=0%3A1&t=WcWEbEnjEkGuOdXr-1)
[Figma component](https://www.figma.com/file/HKpPKij9V3TpsyMV1TpV7C/DS-Components?node-id=3180%3A13642)

**Comment by xinnanyemm** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Design-System-61e8a2ae77c3a60012e5003c/issues/MetaMask/metamask-mobile/5914?planning-poker) with Zenhub @Akatori-Design @brianacnguyen @garrettbear

**Comment by xinnanyemm** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Design-System-61e8a2ae77c3a60012e5003c/issues/MetaMask/metamask-mobile/5914?planning-poker) with Zenhub @georgewrmarshall
