### ISSUE TITLE
[Bug] Account Balance is not displayed on any Signature screen

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-mobile#5928]
**Describe the bug**
Account balance is not displayed on any of the Signature screens.

**Screenshots**

![image](https://user-images.githubusercontent.com/54408225/223647967-8d418492-dc13-45f0-8aa4-b08c1234689e.png)

**To Reproduce**
_Steps to reproduce the behavior_
1. Go to 'test dapp https://metamask.github.io/test-dapp/
2. Connect MM
3. Click on any signature
4. See no balance is displayed on the header

**Expected behavior**
We expect to see the account balance, in the same way we do on Extension.

![Screenshot from 2023-03-08 08-21-13](https://user-images.githubusercontent.com/54408225/223647863-4c840402-24b0-4fdd-af30-20ebbd7d8d84.png)

**Smartphone (please complete the following information):**

- Device: Pixel 6
- OS: Android 12
- App Version: v6.0.1 (1078)

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by bschorchit** [comment]
We should re-use the new header and origin pill components https://github.com/MetaMask/metamask-mobile/pull/5309 throughout all signatures screens.

**Comment by bschorchit** [comment]
Reopening as I believe this still require QA + being added to a release cc: @seaona @hilvmason
