### ISSUE TITLE
[Bug] Contract methods are not fetched, resulting in `Unknown method` for contract interactions

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-mobile#5929]
**Describe the bug**
Contract methods are not fetched, resulting in displaying `Unknown method` for contract interactions.
It happens with all contract interactions that don't have a custom screen.

**Screenshots**
![image](https://user-images.githubusercontent.com/54408225/223650954-4a559aa6-92d4-48a9-852a-bc7dcd515afe.png)

**To Reproduce**
_Steps to reproduce the behavior_
1. Go to test dapp https://metamask.github.io/test-dapp/
2. Connect MM
3. Deploy an ERC1155 token
4. Batch mint some tokens -- see `unknown method` on the confirmation screen
5. Batch transfer some tokens -- see `unknown method` on the confirmation screen

**Expected behavior**
We should fetch the contract method and display it on the confirmation screen. See example in Extension, for the same action of MINT BATCH:
![image](https://user-images.githubusercontent.com/54408225/223651372-9af3d47c-36d6-42cd-8f5a-0a7647340e0f.png)

**Smartphone (please complete the following information):**
- Device: Pixel 6
- OS: Android 12
- App Version: v6.0.1 (1078)

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by bschorchit** [comment]
This might be a duplicate of https://github.com/MetaMask/metamask-mobile/issues/5567

The ideal behavior (same as extension) is defined here: https://github.com/MetaMask/mobile-planning/issues/309

**Comment by IDontLikeOpen** [comment]
I had the same issue, and what helped me was including method data among other parameters.
You can get yours in the ABI of the token you are interacting with (in your case you go to https://etherscan.io/token/0xdd69db25f6d620a7bad3023c5d32761d353d3de9 and find your method's description) and insert it into you transaction parameters as data, so it will look like this: 
`yourTransferMethod()
      .send({
        from: senderAddress,
        gasPrice,
        data: {
            "anonymous": false,
            "inputs": [
              {
                "indexed": true,
                "internalType": "address",
                "name": "from",
                "type": "address"
              },
              {
                "indexed": true,
                "internalType": "address",
                "name": "to",
                "type": "address"
              },
              {
                "indexed": false,
                "internalType": "uint256",
                "name": "value",
                "type": "uint256"
              }
            ],
            "name": "Transfer",
            "type": "event"
          },
});`

I hope it works for you 👍

**Comment by galeriarodrigo** [comment]
Unfortunately, the above did not work for us. 
We still get the "Unknown Method" on latest Metamask mobile.
Using @web3modal/wagmi 4.1.0 writeContract method, if applicable. 
Just wondering it this is still a bug. https://github.com/MetaMask/metamask-mobile/issues/7199 https://github.com/MetaMask/metamask-mobile/issues/5929
Thanks
![UnknownMethod](https://github.com/MetaMask/metamask-mobile/assets/98978959/6eb516a0-55ed-45ac-badc-40eebde9505f)
