### ISSUE TITLE
Connect metamask prompt are not showing when i click on connect button

### ISSUE THREAD

**Issue by swagatikametaverk** [MetaMask/metamask-mobile#5932]
I have implemented MetaMask reactnative sdk,but on android the Connect prompts doesnt come at all. its only open the metamask wallet app .

### **Technical Details**

This is my code
import MetaMaskSDK from '@metamask/sdk';
import { Linking } from 'react-native';
import BackgroundTimer from 'react-native-background-timer';
// import { ethers } from "ethers";

const MMSDK = new MetaMaskSDK({
  openDeeplink: link => {
    Linking.openURL(link); // Use React Native Linking method or your favourite way of opening deeplinks
  },
  timer: BackgroundTimer, // To keep the app alive once it goes to background
  dappMetadata: {
    name: "My App", // The name of your application
    url: "https://myapp.com", // The url of your websiteThe url of your website
  },
});

const ethereum = MMSDK.getProvider();

export const metaMaskConnect = async() => {
  ethereum.on('chainChanged', chain => {
    console.log(chain);
    // setChain(chain);
  });
  ethereum.on('accountsChanged', accounts => {
    console.log(accounts);
    // setAccount(accounts?.[0]);

    // getBalance();
  });
  try {
    ethereum.request({ method: 'eth_requestAccounts' ,params: [],}).then(r=>console.log("My address  :  "+r)).catch(e=>console.log(e))
  } catch (e) {
    console.log('ERROR', e);
  }
  
  
}

-   

 i want that when i click on connect it should open metamask app and connect promt will show
 can you please help with this problem i am stuck here .

https://user-images.githubusercontent.com/127084184/223766394-7b11c359-4edb-47ff-bf3d-3205d9f53707.mp4

**Comment by darthmeme** [comment]
Hey @swagatikametaverk - I've had the same issues for a while on iOS. I've opened a ticket here: https://github.com/MetaMask/metamask-mobile/issues/4827

Seems that if the app is running in the background, it will work most of the time. But if the app is opened from a cold start, then the prompt never shows.

**Comment by swagatikametaverk** [comment]
Hi  Akira Laine
I am facing this issue on Android still i will check your solution and let
you know

Thanks

**Comment by amandakelake** [comment]
I'm facing the same issue on iOS safari, hope solution

**Comment by vandan** [comment]
Is this still an issue @ezgi-cengiz ?
(peeling off devex for now)

**Comment by Faisalnawaz953** [comment]
it is still an issue

**Comment by keyvan-m-sadeghi** [comment]
+1 still an issue!
