### ISSUE TITLE
Metamask bricked "View: Root Error: Missing chain id"

### ISSUE THREAD

**Issue by FBrinkkemper** [MetaMask/metamask-mobile#5939]
**Describe the bug**
Metamask is bricked, after showing this error message. I don't recall exactly what happened before this started happening, but I think it was when doing some internal transfers between accounts on Arbitrum or arbitrum goerli or something. I can now not use metamask mobile Android anymore.

**Screenshots**
_If applicable, add screenshots or links to help explain your problem_
![image](https://user-images.githubusercontent.com/11577750/224089295-892f0d56-c6ae-4c33-9a82-30438c688033.png)

**To Reproduce**
Not sure exactly (see description)

**Expected behavior**
Metamask works.

**Smartphone (please complete the following information):**
 - Device: Pixel 4a
 - OS: Android 13
 - App Version [e.g. 1.0.0] - I cannot see: as I bricked the metamask.
-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by tommasini** [comment]
@FBrinkkemper Thanks for reporting!

Could you re-install the app and see if you can reproduce it? It would help us a lot to fix it as soon as we can!

**Comment by tommasini** [comment]
Hey @FBrinkkemper Thanks again for reporting!

We believe this issue is fixed on the current version. Please if you are still experiencing this, feel free to reply to this ticket or create a new one.
