### ISSUE TITLE
[BUG] [#1011185] v6.1.2 Issues with metamask-ios-sdk following update 

### ISSUE THREAD

**Issue by ulmentflam** [MetaMask/metamask-mobile#5957]
**Describe the bug**
I have been testing an application using the MetaMask iOS SDK and I was able to successfully connect my Dapp up until I was auto-updated to the latest version of the MetaMask app. I started to receive this error whenever I attempted to connect my Dapp. I created a support request #1011185, and am raising an issue here. I also ensured `eth_sign` was enabled on the latest build of the MetaMask iOS app, but that appeared to have no effect. 

```
View: Root
TypeError: undefined is not an object (evaluating '(0,r(d[11]).getHost)(p).substr')
```

**Screenshots**
![Screenshot 2023-03-13 at 12 23 08 PM png](https://user-images.githubusercontent.com/6037314/224763981-f91e76ba-3447-4c82-9ce5-b1945e13d95c.png)

**To Reproduce**
1. Pod install the latest version of the [MetaMask Mobile iOS SDK](https://c0f4f41c-2f55-4863-921b-sdk-docs.github.io/guide/metamask-sdk-ios.html). `pod 'metamask-ios-sdk', :git => 'https://github.com/MetaMask/metamask-ios-sdk.git', :branch => 'main'`
2. Create a Dapp with the [MetaMask Mobile iOS SDK](https://c0f4f41c-2f55-4863-921b-sdk-docs.github.io/guide/metamask-sdk-ios.html)
3. Connect the Dapp to the MetaMask Mobile app v6.1.2 

**Expected behavior**
I should be able to connect my Dapp in the same way as the previous version of the application v6.0.0

**Smartphone (please complete the following information):**
 - Device: iPhone 14
 - OS: 16.3.1
 - App Version v6.1.2 (1082)

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by andreahaku** [comment]
@ulmentflam iOS SDK [v0.1.1](https://github.com/MetaMask/metamask-ios-sdk/releases/tag/0.1.1) has been released with the fix ;)

**Comment by ulmentflam** [comment]
@andreahaku Thank you for finding the bug! I tested again after updating the pod to v0.1.1 and it is working as expected!
