### ISSUE TITLE
[Bug] editing URL on iOS always moves cursor to the end of the address

### ISSUE THREAD

**Issue by plasmacorral** [MetaMask/metamask-mobile#5969]
**Describe the bug**
If I attempt to edit a URL in the MMM browser using iOS, the cursor is moved to the end with any change. This gets pretty annoying, delete a character and the cursor moves or add a character and the cursor moves.  This is not observed on my Android device.

**Video**
https://recordit.co/zP7xM1f6Dm
at 13s I deleted the `.` and the cursor jumps to the end
at 18s I type `b` three times, the first lands where I intended, the second two are appended to the end of the URL
at 23s I type `c` and the cursor again jumps to the end

**To Reproduce**

1. Import secret recovery phrase
2. open browser
3. attempt to edit URL
4. note that cursor moves to the end after any change

**Expected behavior**
User should be able to delete or add consecutive characters without the cursor position jumping

**Smartphone (please complete the following information):**
iPhone 13 mini
iOS 15
v6.1.2
build 1082

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by chrisleewilcox** [comment]
This issue has been fixed.
