### ISSUE TITLE
[Bug] Contract Deployment transactions display gas spent on the Amount field

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-mobile#6004]
**Describe the bug**
Contract Deployment transactions display the amount of gas spent in the transaction on the Amount field.

**Screenshots**

https://user-images.githubusercontent.com/54408225/226584731-72915469-5ad2-4a0e-9285-aeaecd58c201.mp4

**To Reproduce**
1. Go to https://metamask.github.io/test-dapp/
2. Click on Create Token
3. See how amount is 0 ETH
4. Accept tx
5. Check tx details
6. See how the amount is now the value of the gas payed

**Expected behavior**
If we are not sending ETH along deploying a contract (meaning Amount is 0), we should display 0 on the transaction amount.

**Smartphone (please complete the following information):**
 - Device: Pixel 6
 - OS: android
 - App Version: v6.1.2

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by bschorchit** [comment]
I've moved this to a future sprint as we have already lots of issues in the backlog for next sprint (I'm doing a pre-grooming for the call) and this is lower severity. Let me know if you disagree, @seaona :)
