### ISSUE TITLE
Metamask sdk connection gets disconnected  on switching between tabs in react native application

### ISSUE THREAD

**Issue by BejoJeffrin23** [MetaMask/metamask-mobile#6027]
Hi , 
I am using @metamask/sdk: ^0.1.0 in my React native app . I am able to establish the connection . After switching multiple tabs in my application the connection state gets automatically disconnected.

![Screenshot from 2023-03-24 00-13-10](https://user-images.githubusercontent.com/47322103/227317706-e12b7d69-f05a-4028-b14e-8b6c64c040bd.png)

To reproduce :
1) Create react native app with 3 tabs 
2) Establish metamask connection using metamask sdk
3) When tabs are changes the disconnect event gets triggered and connection is lost

**Expected behavior**
The connection is expected to stay. 

**Smartphone (please complete the following information):**
 - Nexus 5 emulator
 - OS: Android 11
 - App Version 6.1.1 (1079)

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?  It spoils the user experience
- Add stats if available on % of customers impacted - 80%
- Is this visible to all users? Yes
- Is this tech debt? Yes

**Comment by andreahaku** [comment]
Hi @BejoJeffrin23 we are aware of this issue and we are about to release a new feature for the MM JS SDK that is named "session persistence" that is meant to fix those kind of issues and improve the connection over time. We are testing it and should be out in a week or two.
