### ISSUE TITLE
iOS: Error is not being handled correctly when user fails biometrics right after enabling it for the first time

### ISSUE THREAD

**Issue by olenapankina** [MetaMask/metamask-mobile#6028]
**Tested on** 
iPhone Xr iOS 16.1.1
Prod build 5.14.0 (1055); 6.2.0 (1088); auth refactor commit d6cd272; 

**Steps to reproduce:**

1. Launch freshly installed application
2. Go through 'Import from seed' flow
3. Leave 'Unlock with Face ID' toggle ON
4. Tap 'Import' button
5. Accept biometrics request
6. Fail biometrics - press 'Cancel'
7. Observe error being shown on 'Import from seed' screen [6028.mp4](https://user-images.githubusercontent.com/116747263/227347582-cd20f633-a894-4544-aac9-b3f22d4770e3.mp4)

**Actual result:** Unclear/dev error is being shown [6028_5 14 0.jpeg](https://user-images.githubusercontent.com/116747263/227347732-17ba4216-f373-47c6-aee1-25f840cac965.jpeg); [6028_6 2 0.jpeg](https://user-images.githubusercontent.com/116747263/227347816-a6413446-0e93-423d-90b6-1e3ea1c8400e.jpeg)
**Expected result:** TBD

**Comment by chrisleewilcox** [comment]
Expected: https://recordit.co/9y81CfzPgO
