### ISSUE TITLE
Core: Implement new token list endpoint

### ISSUE THREAD

**Issue by tommasini** [MetaMask/metamask-mobile#6030]
### **Description**
This issue aims to implement the new token list endpoint.
The details of the endpoint can be found [here](https://consensys.slack.com/archives/C01V1L10W2E/p1677540168216399?thread_ts=1676666128.788699&cid=C01V1L10W2E).

### **Technical Details**
Core repo changes:
* On token-service.ts change`getTokensURL` for the new endpoint
* On TokenListController.ts delete line 280 `filteredTokenList` to line 297 (this logic is on the api side now)
* Do the necessary changes for this to work as with the previous endpoint

Mobile changes:
Suggestion (We should aim to instead of creating a patch, update the assets-controller version instead):
* Create a patch with the changes above 

### **Acceptance Criteria**
* The token list should be working the exact same way as it was.

Scenario: Token list on token detection feature
- GIVEN a user is in wallet view
- WHEN a user does have tokens to import 
- THEN it should show those tokens (Token detection feature)

Scenario: Token list on token detection feature
- GIVEN a user is in wallet view
- WHEN a user tries to import a token manually
- THEN it should be able to find the token by the name

### **References**

-   References go here.
-   Issue numbers. Links.
-   Slack threads.
-   Etc.

**Comment by gauthierpetetin** [comment]
More info about the new endpoint:

<img width="507" alt="Screenshot 2023-03-30 at 14 37 48" src="https://user-images.githubusercontent.com/7071180/228919079-a2f07e91-9d3c-4bf7-b631-3cdeacc5d3ab.png">

**Comment by tommasini** [comment]
Created an epic for it (The epic associated with this ticket), kept this issue to track the implementation of new token list endpoint

**Comment by gauthierpetetin** [comment]
Hi @Gudahtt , we came across that ticket during Mobile sprint planning session today and were wondering whether SL teams could help on this ticket? Would it make sense in terms of scope and does the SL team have bandwidth for it?
cc @Cal-L @sethkfman @hesterbruikman

**Comment by gauthierpetetin** [comment]
Thanks a lot @Gudahtt !

**Comment by Gudahtt** [comment]
Closing in favor of https://github.com/MetaMask/core/issues/1519 which covers this same task

**Comment by mcmire** [comment]
Reopening issue so that we can put it on our board.

**Comment by mcmire** [comment]
I don't think this is an issue now. We've been using TokenListController from `core` for a while.
