### ISSUE TITLE
The transaction is sent through walletconnect, and the method call throws an exception when intrinsic gas is too low, but matemask does not close the transaction

### ISSUE THREAD

**Issue by Spider-yuchen** [MetaMask/metamask-mobile#6036]
#Describe
The transaction is sent through walletconnect, and the method call throws an exception when intrinsic gas is too low, but matemask does not close the transaction
#To Reproduce
If you call the send transaction method on walletconnet and then lower the gas fee on matemask or perform this operation when the gas fee is very high, the send transaction method will throw an exception intrinsic gas too low and the transaction will fail, but the transaction can still be reconfirmed on matemask.
#Code
`await
      state.connector
        .sendTransaction(tx)
        .then((result) => {
          // Returns transaction id (hash)
          console.log(result);
          returnResult.result = true
          returnResult.txHash = result
        })
        .catch((error) => {
          // Error returned when rejected
          console.log(error);

          returnResult.result = false
          returnResult.msg = getErrorMsg(String(error))
        });`
#Expected result
I think the transaction should be closed on matemask after the method has reported an error (that is, the transaction can no longer be confirmed) so that when the transaction succeeds, I can get the transaction hash from the return value of the sent transaction

**Comment by bschorchit** [comment]
Hey @Spider-yuchen, sorry for only getting to this issue now. Are you still seeing this issue happen in the latest versions? Thank you for your report and input!
