### ISSUE TITLE
TypeError: undefined is not an object (evaluating '_r(_d[3]).stripHexPrefix(f).toLowerCase')

### ISSUE THREAD

**Issue by anaamolnar** [MetaMask/metamask-mobile#6038]
Metamask is throwing an error when initiating a mint on app.manifold.xyz

OS: Android, iOS
Metamask Version: 6.2.0
Error message:
TypeError: undefined is not an object (evaluating '_r(_d[3]).stripHexPrefix(f).toLowerCase')

![image](https://user-images.githubusercontent.com/82837486/227518425-91ec8d20-1f9a-401d-9bc4-f191edde6256.png)

Steps to reproduce:
1. Go to app.manifold.xyz
2. Initiate a mint
3. Confirm the signature
4. Metamask throws an error

Workaround: Reinstalling the app

**Comment by sirdaf** [comment]
Same here, error was identical on my Metamask for IOS.
I was trying to mint an enrollment student ID (NFT) on https://zenacademy.com/enroll.
During minting process my Metamask locked up and is now displaying above error.

Will try to reinstall.

**Comment by block-0x** [comment]
Me too.

**Comment by OwlWilderness** [comment]
Occurred using stealcam.com

**Comment by sethkfman** [comment]
@OwlWilderness @sirdaf @block-0x

**Comment by block-0x** [comment]
@sethkfman 
> Were you prompted to update the app during the minting process?

1. Signing via rainbowWallet
2. Call Metamask for signing
3. go to the AppStore's Metamask update screen
4. updated Metamask there
5. found the relevant bug

> What type of NFT were you attempting to mint ERC-1155 or ERC-721?

Tried to sign to remit an ERC20.

**Comment by walrus34565** [comment]
Same thing just  happened to me. Was trying to mint on manifold and the got retained to App Store and clicked “update” the app. Have anyone been able to get back in? I’m stressed because I don’t have my seed phrase :(

View: Root
TypeError: undefined is not an object (evaluating '_r(_d[3]).stripHexPrefix(f).toLowerCase')

**Comment by sirdaf** [comment]
> 

So far I think the only known solution is to delete and reinstall Metamask.
It also resolved the issue for me, I had to recover with my secret phrase and also re-import all my previously imported external accounts.

**Comment by OwlWilderness** [comment]
> Same thing just happened to me. Was trying to mint on manifold and the got retained to App Store and clicked “update” the app. Have anyone been able to get back in? I’m stressed because I don’t have my seed phrase :(
> 
> View: Root TypeError: undefined is not an object (evaluating '_r(_d[3]).stripHexPrefix(f).toLowerCase')

For me I see a link at the bottom of the page that says "save your Secret Recovery Phrase" and entering the pwd will show it.  I also do not want to unisntall. Probably good not having access to metamask on my phone :/

**Comment by OwlWilderness** [comment]
Hi @sethkfman,
I don't think I got the prompt to install/update - I was using safari on IOS (I found a workaround to the appstore always opening a bit ago)

I was on Arbitrum minting ERC-721 tokens

Thanks.

**Comment by cortisiko** [comment]
This bug was fixed in https://github.com/MetaMask/metamask-mobile/pull/6091 and will be in v6.3. v6.3 would be released in the coming week(s). If this bug still persists have v6.3 please reopen.
