### ISSUE TITLE
Can't scan QR code

### ISSUE THREAD

**Issue by grigorii-horos** [MetaMask/metamask-mobile#6048]
### **Description**

I can't connect via qr code scanner. I use walletconnect v2 and Mumbai test network.  Scan closes immediately

The bad part of this that i doesn't receive error message.

https://user-images.githubusercontent.com/4980269/227712675-3232f507-71a3-4ec5-bb3d-2a42bd948408.mp4

### **Technical Details**

Latest Metamask app from Google play or last Metamask app 5.x from GitHub releases page

**Comment by imaksp** [comment]
Walletconnect V2 is not yet supported, see issue #3957 for more details.
