### ISSUE TITLE
Adding and switching to custom network from external browser

### ISSUE THREAD

**Issue by kelemeno** [MetaMask/metamask-mobile#6059]
I could not add and switch to a custom network (polygon mumbai) from an external browser (chrome) on an android phone. I am using walletconnect and wagmi in the external browser, using the useSwitchNetwork hook.

This problem does not arise if the network is already added to the metamask app. 

**To Reproduce**
1. Remove network (e.g. polygon mumbai) from metamask
2. Go to website with walletconnect and wagmi in chrome. ()
3. network is not added, or switched to in app.

**Expected behavior**
When I do the same thing using the same app in the metamask inbuilt browser, the network is added and does switch. The app also works fine. 

**Smartphone **
 - Device: Xiaomi Redmi 9
 - OS: Android
 - App Version 6.1.1

**Comment by mh-jsx** [comment]
I also came across the same bug, I can't switch to a "BNB Chain" if the network is not added in the meta mask app.
