### ISSUE TITLE
eth_signTypedData_v4 over WalletConnect throws arrays not supported error

### ISSUE THREAD

**Issue by rileyg98** [MetaMask/metamask-mobile#6067]
**Describe the bug**
Error occurs when attempting to sign typed data v4 over walletconnect - if an array is in the data, "Keyring Controller signTypedMessage: Error: Arrays are unimplemented in encodeData; use V4 extension" will be returned 

This appears to be a result of this PR: #5103 as a very similar error was referenced but the contributing dev was unable to reproduce. 

I note the eth-sig-util module supports v4 and will return this "Arrays are unimplemented..." message if the typed message data version is V3 and an array exists within it - I have re-implemented my signing code to ensure a raw provider call to "eth_signTypedData_v4" is sent over the WalletConnect channel. I believe the error was not reproducible in #5103 because the dev attempting to reproduce did not consider that said error would need v4 array data to be present to be replicable.  

I believe this issue is somehow that a eth_signTypedData_v4 request is being converted into a v3 request silently in the WalletConnect processing. This would not cause a noticeable issue on v4 requests if there are no arrays or structs impacted by the v3 and v4 differences in said request. I have signTypedData_v4 requests being made on a separate dApp that does not use the arrays in v4 that work correctly, which leads credence to this theory.

This appears to be a regression of #3350 which brought support for v4 typed data to WalletConnect.

I've attempted to trace this through the codebase further, but am not familiar enough with the Metamask codebase to understand the concepts, but am willing to assist in patching this. 

**To Reproduce**
_Steps to reproduce the behavior_
1. Connect WalletConnect to mobile device
2. Attempt to sign a v4 typed data message including v4-specific features (arrays) - I can build a simple test dApp for this if required
3. Message notifies that signing failed - walletconnect returns the Keyring Controller error on PC via console

**Expected behavior**
v4 data is signed correctly - note V4 EIP712 format is used by Uniswap's Permit2 functionality for batch token transfers with SignatureTransfer
This works on the extension and also works on the in-built browser, so the issue is not the v4 signing itself. 

**Smartphone (please complete the following information):**
 - Device: Various android devices, Reasonably new iPhone (don't have specific model)
 - OS: latest iOS, Android 9 
 - App Version: v6.2.0 (1088)

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by tommasini** [comment]
Hey @rileyg98 , thanks for reporting!
I will bring this to our team

Just to be sure that I understood, you tried to do a custom request with wallet connect? Something like this:

```
const customRequest = { jsonrpc: '2.0', method: 'eth_signTypedData_v4', params: msgParams, };
connector.sendCustomRequest(customRequest)
```

**Comment by rileyg98** [comment]
Apologies for the delay - yes, i've done as follows:
`        return await provider.send("eth_signTypedData_v4", [
            address.toLowerCase(),
            JSON.stringify(_TypedDataEncoder.getPayload(populated.domain, types, populated.value))
        ]);`
        
This is a clone of what Ethers.js uses to send a signature request.

**Comment by tommasini** [comment]
Thanks! I will bring this to our team

**Comment by anaamolnar** [comment]
@tommasini Could you please provide a severity for this issue? Thank you! Related to #5103
