### ISSUE TITLE
View: Root Error: Invalid character in NaN

### ISSUE THREAD

**Issue by AksharPrajapati** [MetaMask/metamask-mobile#6075]
I've created one react web application which is simply pass token between two users using metamask wallet. The problem I'm facing is, It's perfectly working fine in web page but **getting errors from mobile application**. I simply open meta mask -> go to the browse tab and copy pasting my deployed link (netlify)deployed link: [https://chipper-kelpie-925251.netlify.app/](https://chipper-kelpie-925251.netlify.app/)-> then try to scan the QR code and click on getRewards button to call function of smart contract but it's giving me an error like, `View: Root Error: Invalid character in NaN` & `View: Root TypeError: undefined is not an object (evaluating 'o.negative').` I didn't get any solution for this.

https://user-images.githubusercontent.com/46050915/228809857-07aa6066-f3e7-4f94-bb61-4de0fd29eff5.mp4

**Smartphone (please complete the following information):**
 - Device: Android/iPhone

**Comment by Cal-L** [comment]
There were a couple of issues found while interacting with the Dapp. First, the Dapp is padding an invalid `gas` field to `eth_sendTransaction` RPC method. Please check that it is in hexadecimal format. Second, the Dapp seems to be calling `eth_sendTransaction` twice in a row and needs to be reduced to a single call. Please re-open an issue if the issue still persists after resolving the points above.
