### ISSUE TITLE
samsung tablet 

### ISSUE THREAD

**Issue by brelimari-0721** [MetaMask/metamask-mobile#6094]
TypeError: undefined is not an object (evaluating '_r(_d[3]).stripHexPrefix(f).toLowerCase')

**Comment by cortisiko** [comment]
hey @brelimari-0721 thanks for reporting. This bug was fixed in https://github.com/MetaMask/metamask-mobile/pull/6091 and will be in v6.3. v6.3 would be released in the coming week(s). If this bug still persists after v6.3 please reopen it.
