### ISSUE TITLE
View: Root TypeError: undefined is not an object (evaluating '_r(_d[3]).stripHexPrefix(f).toLowerCase')

### ISSUE THREAD

**Issue by anooprana4236** [MetaMask/metamask-mobile#6099]
Gerting below error post login on samsung android devices, wallet doesn't load and prompts to reset the wallet

View: Root
TypeError: undefined is not an object (evaluating '_r(_d[3]).stripHexPrefix(f).toLowerCase')

Users won't be able to use the wallet at all, this is a blocker for samsung devices

**Comment by cortisiko** [comment]
Hey @anooprana4236 thanks for reporting. This bug was fixed in https://github.com/MetaMask/metamask-mobile/pull/6091 and will be in v6.3. v6.3 would be released in the coming week(s). If this bug still persists have v6.3 please reopen.
