### ISSUE TITLE
Core: Improve of native balance of the ERC-20 tokens

### ISSUE THREAD

**Issue by tommasini** [MetaMask/metamask-mobile#6101]
### **Description**
This issue aims to optimize the `TokenBalancesController` on the assets-controller.

When we change of network or account, the native balance of the ERC-20 tokens is not reset. It shows a wrong value for a couple seconds and then updates.

We should reset the state and show a skeleton text instead of a wrong value.

### **Technical Details**
- https://recordit.co/E1TCSnJeM4
- Split this ticket with a patch and follow up with a non-blocking core PR

### **Acceptance Criteria**
- Be able to show consistently the right native balance to the user

Scenario: User detect tokens on mainnet
* GIVEN a user have 15 tokens to detect
* WHEN a user detect that tokens
* THEN switch network to polygon
* AND detect tokens
* THEN switch network
* THEN token native balance should always reset and appear with the right value

Scenario: User manually imports token
* GIVEN a user go to import token screen
* WHEN a user import an ERC-20 Token
* THEN the native balance should not take longer to appear

### **References**

-   References go here.
-   Issue numbers. Links.
-   Slack threads.
-   Etc.

**Comment by gauthierpetetin** [comment]
Hi @Gudahtt , do you think this falls in the scope of Shared Libraries team?

**Comment by Gudahtt** [comment]
Conceivably, but it's not related to anything we're focusing on this quarter

**Comment by salimtb** [comment]
hey @tommasini ,
i wasn't able to reproduce this bug , can you pls provide me more informations/recorded video

**Comment by tommasini** [comment]
hey @salimtb, if you look at the ApeCoin, you can see the the native balance of it when switching account for some initial seconds is not correct: https://recordit.co/6uxFuxhAHn (Iphone 12, testflight v7.16.0)
