### ISSUE TITLE
Dark Mode

### ISSUE THREAD

**Issue by bdresser** [MetaMask/metamask-mobile#611]
once https://github.com/MetaMask/metamask-extension/issues/577 is done, we can use the same palette for a dark mode in the app

**Comment by iamonuwa** [comment]
> once [MetaMask/metamask-extension#577](https://github.com/MetaMask/metamask-extension/issues/577) is done, we can use the same palette for a dark mode in the app

Was about to ask for this. But seems it's already planned. I love dark mode.

**Comment by omnat** [comment]
Closing as duplicate of #1381

**Comment by cyberfunk** [comment]
It’s 2021 has there been any progress with this project?
