### ISSUE TITLE
Bump Detox to v20.x.x

### ISSUE THREAD

**Issue by cortisiko** [MetaMask/metamask-mobile#6112]
We are long overdue for a version bump in detox. Let's proceed with upgrading Detox to the latest v20. There are breaking changes associated with Detox as well as some [depreciations](https://wix.github.io/Detox/blog/2022/11/10/detox-20-is-out/#deprecations).  During the upgrade process to the latest version, it's important not to be alarmed by the number of failing tests as this is expected. 

### Acceptance Criteria

After upgrading to v20.x.x all the E2E tests should be passing.

**Comment by cortisiko** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/MetaMask-Mobile-5f984938ddc0e4001d4b79cb/issues/MetaMask/metamask-mobile/6112?planning-poker) with Zenhub @Andepande @NicolasMassart @SamuelSalas @chrisleewilcox

**Comment by leotm** [comment]
FYI ^
- https://github.com/MetaMask/metamask-mobile/pull/5913#issuecomment-1477758387

**Comment by cortisiko** [comment]
Closing in favor of https://github.com/MetaMask/mobile-planning/issues/850, this task would be done as part of the RN upgrade to v0.71.6
