### ISSUE TITLE
[BUG] Deep link not work

### ISSUE THREAD

**Issue by TonyFich** [MetaMask/metamask-mobile#6140]
**Describe the bug**
Deep link not work !!!

**To Reproduce**
[_Steps to reproduce the behavior_
4. See error](https://metamask.github.io/metamask-deeplinks/)

**Smartphone (please complete the following information):**
 - Device: iPhone13
 - OS:  iOS16.4
 - App Version: v6.3.0

- Critical
- 100% of customers impacted
- Is this visible to all users? yes
- Is this tech debt? yes

**Comment by cortisiko** [comment]
hey @TonyFich thanks for reporting. Can you provide us with the specific deep link you use to encounter this bug?

**Comment by TonyFich** [comment]
https://metamask.app.link/payment/0x34620E1A170a5dc0e2f6cD79e3b3B17778536DC1?amount=111

**Comment by TonyFich** [comment]
If you try to open this link in Safari, you will be redirected to the app store.

**Comment by andreahaku** [comment]
you cannot open a universal link on a mobile browsers on iOS for security reasons. You have to "tap" them.
So try tapping the link from somewhere.
Also the link structure is wrong. It should be:

[https://metamask.app.link/send/0x34620E1A170a5dc0e2f6cD79e3b3B17778536DC1?amount=111](https://metamask.app.link/send/0x34620E1A170a5dc0e2f6cD79e3b3B17778536DC1?amount=111)

Try it and let me know.

**Comment by felddoteth** [comment]
All deep links are broken. I don't understand what's wrong.

> https://metamask.app.link/send/0x34620E1A170a5dc0e2f6cD79e3b3B17778536DC1?amount=111

clicking this does nothing. Metamask app opens, nothing happens.

Same with deep links for dapps. The browser doesn't open.

**Comment by christopherferreira9** [comment]
Hi all! This has been solved as of `v7.5.0`.
