### ISSUE TITLE
Adjust E2E tests to accommodate the "What's New" modal

### ISSUE THREAD

**Issue by cortisiko** [MetaMask/metamask-mobile#6149]
We missed adding e2e tests for the what's new modal. Can we add a step that closes the e2e tests?

This would need to be done for both Detox and Appium. 

In detox: 
Create helper methods to verify that the modal is visible and to dismiss the what's new modal. 
Please keep in mind that Bitrise may experience some lag during test execution, so it's important to account for that when you write your test.

In appium:
Create a step that verifies that whenever the what's new modal is visible, you can dismiss it. 

### Acceptance Criteria
E2E tests should pass on bitrise and browserstack.

**Comment by chrisleewilcox** [comment]
There is already existing code to close what's new modal.

**Comment by chrisleewilcox** [comment]
Not able to run locally.  SRP is not being read no matter what I try to do.

**Comment by cortisiko** [comment]
was addressed in https://github.com/MetaMask/metamask-mobile/pull/6151
