### ISSUE TITLE
Browser -> etherscan -> switch network -> crashes app

### ISSUE THREAD

**Issue by haochizzle** [MetaMask/metamask-mobile#6152]
**Describe the bug**
Using MetaMask Mobile's browser and accessing either Ethereum mainnet/Optimistic/Arbitrum etherscan.io's Token Approvals revoke page, on a first attempt with the "switch network" prompt, the entire app crashes when the "please take note this is a beta version feature..." warning message appears. 

This only happens on the first attempt. Thereafter if the app is restarted, the app doesn't crash and you can successfully switch network and connect your web3 wallet to etherscan.io's token approvals page. 

**Screenshots**
![image](https://user-images.githubusercontent.com/36713098/230828118-4bdeac46-2285-4612-9e3e-68f5a5e0503a.jpeg)

**To Reproduce**
_Steps to reproduce the behavior_
Described above 

**Expected behavior**
App should not crash, and the "connect to web3 wallet" button should connect to the metamask mobile address. 

**Smartphone (please complete the following information):**
 - Device: iPhone 13 Pro
 - OS: iOS 16.3.1
 - App Version 6.0.0 [1068] 

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by parmodkuma** [comment]
Hi
