### ISSUE TITLE
[Bug] *From* fields displayed twice when performing a transaction from a Dapp

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-mobile#6163]
**Describe the bug**
Whenever we perform a tx from a Dapp, we can see dupplicated *From* values. One on the top header, and the second on the new *From/To* section.

**Screenshots**

![Screenshot from 2023-04-11 11-56-42](https://user-images.githubusercontent.com/54408225/231127367-4b8fcab1-1006-4373-aadd-01d311ca6e53.png)

**To Reproduce**

_Steps to reproduce the behavior_
1. Go to test dapp https://metamask.github.io/test-dapp/
2. Click on Send Legacy / Send EIP1559
3. See MetaMask displays 2 fields for *From* address

**Expected behavior**
This is the new design added [here](https://github.com/MetaMask/metamask-mobile/pull/5887). I've looked it up again and I see that with the top Header where we display the current selected Account and the balance, now results in displaying the same information in both sides (the top selected account and the From field).

I think these 2 fields will always be the same, meaning we could remove one?
 @bschorchit 

**Smartphone (please complete the following information):**
 - Device: Pixel 6
 - OS: Android
 - App Version: Not in `6.3` but in `main`

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by bschorchit** [comment]
That's intended for now (see [here](https://github.com/MetaMask/metamask-mobile/issues/4622#issuecomment-1458705884)). 
We'll be working on a new design that will improve this during Q2 (it's part of our O2KR4 for Q2). Design is not ready yet so I'll remove this from the current sprint.

**Comment by seaona** [comment]
thank you @bschorchit !!
