### ISSUE TITLE
0.1.0 SDK Compatibility issue

### ISSUE THREAD

**Issue by christopherferreira9** [MetaMask/metamask-mobile#6175]
**Describe the bug**
Backwards compatibility to SDK 0.1.0 is broken with MetaMask mobile 6.3.0 (1095).
This only happens with iOS and specifically with the "Connect" action where it doesn't route the user back to the Dapp after connecting. This **doesn't** happen with other actions such as "Sign".
**When switching chains or accounts it is not reflecting the change on the dapp.**

**Screenshots**
https://user-images.githubusercontent.com/104831203/231446150-44dec516-1c24-41da-9072-971c24171ef0.mov

**To Reproduce**
1. Start a dapp using SDK 0.1.0
2. Open the dapp using a mobile browser
3. Tap connect

**Expected behavior**
- You're routed back to the dapp after connecting
- When you change accounts or active chain it is reflected on the dapp side as well

**Smartphone (please complete the following information):**
 - Device: iPhone 11
 - OS: 16.3.1
 - App Version: 6.3.0 (1095)

**Comment by TuNguyenThanh** [comment]
+

**Comment by wisepassisawesome** [comment]
Would be so great to have that fixed as we decided to use the MetaMask SDK and release this month on the App Store! 

If you guys could fix it within this month, it would be awesome

**Comment by sensactive** [comment]
i think my problem is related to this one. in my case i am using a browser application. My scenario:

1. const ethereum = new MetaMaskSDK().getProvider()
2. try {
          await ethereum.ethereum.request({ method:
          'eth_requestAccounts' })
          console log('connected')
        } catch (error) {
          console.log('error', error)
        }

  Actual result:
  None of the output is displayed in the console log. The promise remains in pending status all the time.

Expected Result:
Any of the console logs is displayed, depending on the user's action in the MetaMask mobile application

Detection Environment: Google Chrome 112.0.5615.49

P.S
I also want to add that this problem concerns only the mobile application, when you try to perform this action in the browser extension - everything works as expected, i.e. Promise changes its state to pending or rejected. It is also noticed that after the user has confirmed or not confirmed the connection in the mobile application, no incoming messages are received in the open web socket connection, this is probably the problem
