### ISSUE TITLE
SDK modal showing with the wrong timing 

### ISSUE THREAD

**Issue by christopherferreira9** [MetaMask/metamask-mobile#6176]
### **Description**
The SDK modal should only show when there will be the need for user input such as accepting incoming connection requests as currently it is showing anytime the wallet is doing something SDK related such as resuming connections.

### **Acceptance Criteria**
- When a user has an established "timed out" connection and opens the MetaMask wallet there should be no SDK modal being displayed
- When a user has an established "timed out" connection is browsing the MetaMask wallet there should be no SDK modal being displayed

Scenario: Browsing MetaMask
- GIVEN a user has an established SDK connection and MetaMask is closed
- WHEN a user opens the MetaMask wallet 
- THEN the user is presented with the lockscreen and no SDK modal is showing

**Comment by abretonc7s** [comment]
Unfortunately, we cannot know ahead of time if there will be an action (Signing, add chain, etc) sent to MetaMask.

**Comment by christopherferreira9** [comment]
Closing as "won't do"
