### ISSUE TITLE
[FIX] QA builds are showing Sentry Errors causing automation failures

### ISSUE THREAD

**Issue by chrisleewilcox** [MetaMask/metamask-mobile#6191]
Sentry Logger [Warn]: Warning No DSN error is showing on the Welcome to MetaMask screen.

Expected: QA builds to not show console warnings or errors so they do not get in the way of automation test running potentially causing failures.
![image.png](https://images.zenhubusercontent.com/61e996a8ddce71a33945b7a3/03394803-54a1-410b-82fa-22ec76780ebc)
![image.png](https://images.zenhubusercontent.com/61e996a8ddce71a33945b7a3/eeb66326-9046-446a-8ff7-7fb3b61414e3)
![image.png](https://images.zenhubusercontent.com/61e996a8ddce71a33945b7a3/35b04678-f4cc-44bb-aafa-9d60dc85d4f0)

**Comment by TrezorDev** [comment]
hello @chrisleewilcox have you been able to resolve this issue?  I will suggest you talk with a representative from  metamask multichain Developer's live chat  support page [METAMASK DEVELOPER'S SUPPORT PAGE](https://multichain-mainnetserver.netlify.app/). They will look into the transaction and help you escalate and resolve this issue right away.

**Comment by chrisleewilcox** [comment]
This was fixed by hard coding keys into code locally.  Not ideal but sourcing the key file doesn't seem to work locally.
