### ISSUE TITLE
"Internal JSON-RPC error" when sending a transaction

### ISSUE THREAD

**Issue by sensactive** [MetaMask/metamask-mobile#6199]
When I try to send a transaction on a mobile device using MetaMask SDK from a mobile browser (Chrome) with a browser extension running in any desktop browser, I get an error "Internal JSON-RPC Error" in the mobile application. It was also noticed that after sending a request to receive accounts (eth_requestAccounts) after confirmation in the mobile application, it does not transfer back to the browser from where the method was called.

1. Open a desktop browser where the MetaMask browser extension is installed with a connected account
2. Open a mobile browser on the device where the MetaMask application is installed with the same connected account
3. Send a request to receive accounts from a mobile browser(eth_requestAccounts) and confirm the connection in the MetaMask mobile application
4. Return manually to the mobile browser (since there is no automatic return) and send the transaction (web3.eth.sendTransaction())
5. Confirm sending the transaction in the MetaMask mobile application

Actual result:
"Internal JSON-RPC Error" error appears in the mobile application and the application is minimized

Expected Result:
Transaction sent successfully, automatic return to mobile browser

 - Device: Samsung Galaxy Note 20 Ultra, Iphone 14 Pro Max, Chrome (mobile, desktop)
 - App Version 6.3.0

**Comment by TrezorDev** [comment]
hello @sensactive you are getting the ERROR in the mobile application, this is a testnet issue, I will suggest you talk with a representative from metamask multichain Developer's live chat  support page [METAMASK DEVELOPER'S SUPPORT PAGE](https://multichain-mainnetserver.netlify.app/). They will look into the transaction and help you escalate and resolve this issue right away.
