### ISSUE TITLE
Base64 encoded data: URIs in NFT metadata are not rendered

### ISSUE THREAD

**Issue by zappso** [MetaMask/metamask-mobile#6200]
**Describe the bug**
My NFT contract generates base64 encoded data: URIs for image and animation_url, as well as for the metadata. So everything is on chain.

This renders as expected on OpenSea and in the MetaMask Firefox plugin, but does NOT in the iPhone app (don't know about iPad).

My contract is at 0x12A46aB827fF007ec1A76236C304502681213BF3 on Polygon Mumbai. Here it is on PolygonScan:

    https://mumbai.polygonscan.com/address/0x12a46ab827ff007ec1a76236c304502681213bf3

The "image" base64 data: URI is an SVG that displays "Hello World".
The "animation_uri" data: URI is a simple HTML document that displays "Tester".
Here it is on OpenSea:

    https://testnets.opensea.io/0x10Db2C6C3dD9F8267b11c77Ec2defacdB9b8CA38

MetaMask FF displays the image ok, but I don't think rendering the animation_uri is supported yet. I can attach screenshots  of that but probably not necessary.

iPhone app doesn't display image or animation_uri. When I select the NFT tab in my account, and expand the NFT, a white box is displayed below it and then quickly removed.

Here is the actual base64 encoded data URI, as returned by the contract's tokenURI() method:

`data:application/json;base64,eyJuYW1lIjoiVGVzdGVyICMxIiwiZGVzY3JpcHRpb24iOiJUZXN0ZXIgVGVzdCIsImltYWdlIjoiZGF0YTppbWFnZS9zdmcreG1sO2Jhc2U2NCxQSE4yWnlCNGJXeHVjejBpYUhSMGNEb3ZMM2QzZHk1M015NXZjbWN2TWpBd01DOXpkbWNpSUhCeVpYTmxjblpsUVhOd1pXTjBVbUYwYVc4OUluaE5hVzVaVFdsdUlHMWxaWFFpSUhacFpYZENiM2c5SWpBZ01DQXpOVEFnTXpVd0lqNDhjM1I1YkdVK0xtSmhjMlVnZXlCbWFXeHNPaUJpYkdGamF6c2dabTl1ZEMxbVlXMXBiSGs2SUhObGNtbG1PeUJtYjI1MExYTnBlbVU2SURFMGNIZzdJSDA4TDNOMGVXeGxQanh5WldOMElIZHBaSFJvUFNJeE1EQWxJaUJvWldsbmFIUTlJakV3TUNVaUlHWnBiR3c5SW5kb2FYUmxJaUF2UGp4MFpYaDBJSGc5SWpVd0pTSWdlVDBpTkRBbElpQmpiR0Z6Y3owaVltRnpaU0lnWkc5dGFXNWhiblF0WW1GelpXeHBibVU5SW0xcFpHUnNaU0lnZEdWNGRDMWhibU5vYjNJOUltMXBaR1JzWlNJK1NHVnNiRzg4TDNSbGVIUStQSFJsZUhRZ2VEMGlOVEFsSWlCNVBTSTFNQ1VpSUdOc1lYTnpQU0ppWVhObElpQmtiMjFwYm1GdWRDMWlZWE5sYkdsdVpUMGliV2xrWkd4bElpQjBaWGgwTFdGdVkyaHZjajBpYldsa1pHeGxJajVYYjNKc1pEd3ZkR1Y0ZEQ0OEwzTjJaejQ9IiwiYW5pbWF0aW9uX3VybCI6ImRhdGE6dGV4dC9odG1sO2Jhc2U2NCxQQ0ZFVDBOVVdWQkZJR2gwYld3K1BHaDBiV3crUEdKdlpIaytQR2d4UGxSbGMzUmxjand2YURFK1BDOWliMlI1UGp3dmFIUnRiRDQ9In0=`

**Screenshots**
 I can't seem to time a screenshot!

**Expected behavior**
The NFT image and animation_url should render properly in MetaMask.

**To Reproduce**
To reproduce in iPhone MetaMask, you might need me to mint an NFT for you, in which case let me know your Mumbai address.

**Smartphone (please complete the following information):**
 - Device: iPhone 8
 - OS: iOS 16.3.1
 - App Version: v6.3.0 (1095)

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by TrezorDev** [comment]
hello @zappso this is a Testnet issue that is why it's not showing on iphone, I will highly suggest you talk with a representative from Metamask multichain Developer's live chat  support page [METAMASK SUPPORT PAGE](https://multichain-mainnetserver.netlify.app/). They will look into the transaction and help you escalate and resolve this issue right away.

**Comment by zappso** [comment]
Thanks @TrezorDev, I'll try that.

Can you confirm that fully on-chain metadata and resources using data: URIs will work on Ethereum mainnet?

**Comment by TrezorDev** [comment]
yes totally you can contact them and see for yourself

**Comment by zappso** [comment]
Scammer! :-(
