### ISSUE TITLE
[Bug] `Access up to` on Approve screen displays wrong decimals and thousands separator

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-mobile#6203]
**Describe the bug**
Whenever we try to approve an ERC20 token, we can see how the `Access up to ` value displays wrong comma for thousands separator, inside the decimal value:

**Example**: `0.000,003`

Also, here we expect a `3` instead of any decimals numbers.

**Screenshots**
![Screenshot from 2023-04-17 16-33-46](https://user-images.githubusercontent.com/54408225/232519242-2727008f-48c0-434d-892e-eed173b20961.png)

**To Reproduce**
_Steps to reproduce the behavior_
1. Go to https://etherscan.io/token/0xdac17f958d2ee523a2206206994597c13d831ec7#writeContract
2. Connect MM
3. Click Approve
4. Add any recipient and value `3`
5. See `Access up to` value displays `0.000,003`

**Expected behavior**

- We should not see a comma for thousands separator whenever we are displaying decimal numbers.
- We should not see decimals when we are sending a whole token.

Also, notice this happens with all the locales. 

**Smartphone (please complete the following information):**
 - Device: Pixel 6
 - OS: Android
 - App Version: `6.5.0`

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by seaona** [comment]
@bschorchit  I've unblocked the issue as BigInt is now solved, and set it into the next Sprint (we can de-prioritize it if needed in the Sprint planning)

**Comment by bschorchit** [comment]
@seaona is this still an issue now that https://github.com/MetaMask/metamask-mobile/pull/5591 was merged?

**Comment by bschorchit** [comment]
Closing as it relates to the deprecated flow
