### ISSUE TITLE
[Bug] ERC20 Token Balance is pointing to the incorrect Account

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-mobile#6218]
**Describe the bug**
Whenever we are sending an ERC20 token from a Dapp, the `Balance` field we display is pointing to the Selected Account on the Wallet view, but not to the Selected Account which is performing the transaction.

**Screenshots**

https://user-images.githubusercontent.com/54408225/233124416-019420b1-a395-442e-9a69-0be59f3ad6fa.mp4

**To Reproduce**
_Steps to reproduce the behavior_
1. Go to the https://metamask.github.io/test-dapp/
2. Connect MM Account 2
3. Go to the Wallet, Select MM Account 1
4. Go back to the test dapp
5. Deploy an ERC20 Token Contract
6. Click Transfer
7. See how the Account 2 `Balance` amount is 0 (incorrect)
8. Go back to the Wallet
9. Switch to Account 2
10. Go back to test dapp
11. Click Transfer
12. See how the Account 2 `Balance` amount is 10 (correct)

**Expected behavior**
Balance displayed should indicate the balance from the Account which is displayed and performing the transaction.

**Smartphone (please complete the following information):**
 - Device: Pixel
 - OS: Android
 - App Version: `v6.3.0`

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by bschorchit** [comment]
Q: is the balance at the header also incorrect?

**Comment by seaona** [comment]
The balance of the header is correct @bschorchit
