### ISSUE TITLE
Create a single component to render Custom Gas Modals

### ISSUE THREAD

**Issue by jpuri** [MetaMask/metamask-mobile#6244]
At a lot of places in code we render CustomGasModal, depending on Network and Transaction Type , EIP-1559 or legacy gas controls are rendered like [here](https://github.com/MetaMask/metamask-mobile/blob/e8f8544e64a71d3846153a65e75149687324df31/app/components/Views/SendFlow/Confirm/index.js#L1378)

We should create a single component which can be used at all these places and it will display legacy or EIP-1559 gas controls depending on type of the transaction.

This component will be used at:

* [ ] Transaction Editor
* [ ] Approve
* [ ] Send Flow: #6287

**Comment by bschorchit** [comment]
Closing as completed with https://github.com/MetaMask/metamask-mobile/pull/6287
