### ISSUE TITLE
MetaMaskSdk's provider don't Resolve promise request({method: 'eth_requestAccounts'})

### ISSUE THREAD

**Issue by sensactive** [MetaMask/metamask-mobile#6251]
in my case i am using a browser application. My scenario:

const ethereum = new MetaMaskSDK().getProvider()
try {
await ethereum.request({ method:
'eth_requestAccounts' })
console log('connected')
} catch (error) {
console.log('error', error)
}
Actual result:
None of the output is displayed in the console log. The promise remains in pending status all the time.

Expected Result:
Any of the console logs is displayed, depending on the user's action in the MetaMask mobile application

Detection Environment: Google Chrome 112.0.5615.49
Device: Samsung Galaxy Note 20 Ultra, Android 13, One UI 5.1, App version 6.3.0

P.S
I also want to add that this problem concerns only the mobile application, when you try to perform this action in the browser extension - everything works as expected, i.e. Promise changes its state to resolve or rejected. It is also noticed that after the user has confirmed or not confirmed the connection in the mobile application, no incoming messages are received in the open web socket connection, this is probably the problem

**Comment by christopherferreira9** [comment]
Hi @sensactive ! 
Can try with:  ```await ethereum.request({ method: 'eth_requestAccounts' })``` instead of ```await ethereum.ethereum.request({ method:'eth_requestAccounts' })```?

**Comment by sensactive** [comment]
Hi @christopherferreira9! I'm sorry, I mistyped when I wrote the text. Of course I use `await ethereum.request({ method: 'eth_requestAccounts' })`

**Comment by christopherferreira9** [comment]
What's the SDK  you're using version you're using? What specific dapp are you using the SDK on?

**Comment by sensactive** [comment]
"@metamask/sdk": "^0.1.0" ,  my application is written in JS using Vue.js 3 framework

**Comment by sensactive** [comment]
just in case, I repeat that the problem is observed only when using the Metamask mobile application (Android, IOS), when I use the Metamask browser extension, then everything works correctly

**Comment by HoangKimDuc** [comment]
+1

**Comment by christopherferreira9** [comment]
Hi all, can you please open an issue on the [MetaMask SDK repo](https://github.com/MetaMask/metamask-sdk) for this?
