### ISSUE TITLE
a "Key not exchanged" Error occurs in the MetaMask SDK(MetaMask SDK v0.1.0, MetaMask v6.3.0(1095))

### ISSUE THREAD

**Issue by reese-1eco** [MetaMask/metamask-mobile#6252]
### **Description**
When ethereum.request({method: 'eth_requestAccounts'}) is called from the Dapp, A metamask-mobile app Runs, and after 1-2 seconds, a "Key not exchanged" Error occurs in the MetaMask SDK with React Native used by Dapp.

It's not a problem that happens 100% every run.

### **Technical Details**
- target: 
    - Model: iPhone XS 
    - iOS 16.3.1 (20D67)
- MetaMask v6.3.0(1095)
- @metamask/sdk": "0.1.0"
- dev env 
```shell
$ npx react-native info
info Fetching system and libraries information...
System:
    OS: macOS 13.3
    CPU: (8) arm64 Apple M1 Pro
    Memory: 76.20 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 16.16.0 - ~/.nvm/versions/node/v16.16.0/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.11.0 - ~/.nvm/versions/node/v16.16.0/bin/npm
    Watchman: 2023.02.20.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.12.0 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    Android SDK: Not Found
  IDEs:
    Android Studio: Electric Eel 2022.1.1 Patch 2 Electric Eel 2022.1.1 Patch 2
    Xcode: 14.2/14C18 - /usr/bin/xcodebuild
  Languages:
    Java: 16.0.2 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0 
    react-native: 0.71.1 => 0.71.1 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```
<img width="1000" alt="Error-Key-not-exchanged" src="https://user-images.githubusercontent.com/102128366/233929326-d06b5aca-9834-43df-a532-b20c610a5c00.png">

## Scenario: 
1. Call ethereum.request({method: 'eth_requestAccounts'}) api from Dapp
2. Run metamask-mobile app automatically
3. Display "Connecting to MetaMask" on the metamask-mobile app screen
4. Dapp console shows "Error: Key not exchanged"

**Comment by ardasatata** [comment]
Happened to me as well, I even ran the example code and got like 20% chance of apps being able to connect with metamask, but the rest of it just stuck on `connecting to MetaMask...`

I was running the example, from this docs: 

- https://docs.metamask.io/wallet/how-to/use-sdk/react-native
- https://c0f4f41c-2f55-4863-921b-sdk-docs.github.io/downloads/reactNativeApp_v0.1.0.zip

Here's the screen capture of it:
<img src="https://im5.ezgif.com/tmp/ezgif-5-2d408e3cf9.gif" />

**Comment by reese-1eco** [comment]
@andreahaku Thanks for the info on the new version. I look forward to the new version.

Thank a lot for your comment.
