### ISSUE TITLE
[Bug] Approve asset for an ERC20 token displays `undefined`

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-mobile#6271]
**Describe the bug**
Whenever we are approving an ERC20 token, if we check the token details we can see that we no longer see the token amount and ticker (i.e. `7TST`) but an `undefined` and `#7000` instead.

**Screenshots**

https://user-images.githubusercontent.com/54408225/234524255-dfc34ab0-33c6-43c7-9c45-78abd367ab4f.mp4

**To Reproduce**
_Steps to reproduce the behavior_
1. Go to the test dapp
2. Deploy an ERC20 token
3. Add token to wallet
4. Click Approve (we'll see a BigInt error, but that's a separate issue)
5. Click Details -- see `undefined #7000` 

**Expected behavior**
We expect to see `7TST`

**Smartphone (please complete the following information):**
 - Device: Pixel 6
 - OS: Android
 - App Version: `6.5.0`

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by gravestar** [comment]
im still having this issue it shows ERC20 Token Approval, my case is from opensea.io, and then to set approve for all, but it showing my smart contract proxy is ERC20 Token, and approve asset (undefined (#1))
