### ISSUE TITLE
[Bug] Wrong Account name displayed on the first Dapp interaction

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-mobile#6272]
**Describe the bug**
Whenever I perform a dapp interaction for the first time, I can see how the `To` field displays the correct address of the contract, but we also see an account name, i.e. `Account 2` which is not correct, nor corresponding to the address.

This seems to happen only the first time I start a dapp interaction with a new wallet. If I try again, the `Account` name is removed and I see only the correct address (expected).
Maybe there are more ways to repro this behaviour.

**Screenshots**

[mobile-acct-name-wrong.webm](https://user-images.githubusercontent.com/54408225/234528002-040e3a07-9eee-4bda-8400-d02619f31438.webm)

**To Reproduce**
_Steps to reproduce the behavior_
1. Build MM for the first time
2. Go to test dapp
3. Click Send tx (i.e. legacy
4. See recipient displays both an address an `Address 2` which are not matching

**Expected behavior**
`Address 2` should not be displayed as it's not the same address as the recipient.

**Smartphone (please complete the following information):**
 - Device: Pixel 6
 - OS: android
 - App Version: `6.5.0`

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by segun** [comment]
This could be related to [6331](https://github.com/MetaMask/metamask-mobile/issues/6331)

**Comment by blackdevelopa** [comment]
Hi @seaona, this seems to be related to [6131](https://github.com/MetaMask/metamask-mobile/issues/6331). I tested the [fix](https://github.com/MetaMask/metamask-mobile/pull/6419) we have for it and this issue is also handled. http://recordit.co/mqqZ2yRsZp

**Comment by bschorchit** [comment]
Closing as https://github.com/MetaMask/metamask-mobile/pull/6446 was merged
