### ISSUE TITLE
Impossible to accept terms of use

### ISSUE THREAD

**Issue by tommasini** [MetaMask/metamask-mobile#6276]
**Describe the bug**
It's impossible to press the checkbox on the terms of use modal. The user is incapable of using the app.
https://recordit.co/x3fyLwRHba

Probably bug origin: https://github.com/MetaMask/metamask-mobile/pull/6228

**Expected behaviour**
The user should be able to check the checkbox, pressing the text or the check icon

**Suggestion/Opportunity** 
The checkbox could have an optional text with it since a check button almost always has text next to it 

**Smartphone (please complete the following information):**
 - Device: Every device
 - App Version [e.g. 1.0.0] - not in production atm

**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by hesterbruikman** [comment]
@tommasini will this issue be fixed by updating the ToU url? #6182

**Comment by tommasini** [comment]
No, I think the better way for this to be fixed, is to update the checkbox component of the component-library

When the ToU url it's ready we could create a ticket and quicker change it, it's a really small change 🙏🏼

**Comment by hesterbruikman** [comment]
Thanks @tommasini!

**Comment by chrisleewilcox** [comment]
This issue is resolved.
