### ISSUE TITLE
[BUG] PollingBlockTracker now working when compiling for IOS

### ISSUE THREAD

**Issue by Ardziv** [MetaMask/metamask-mobile#6283]
**Describe the bug**
_A clear and concise description of what the bug is_

**Screenshots**
![Simulator Screen Shot - iPhone 12 Pro - 2023-04-27 at 14 54 51](https://user-images.githubusercontent.com/13898818/234783569-664582a0-877e-47a5-ba07-57febb40c4c8.png)

**To Reproduce**
1. Compile the metamask-mobile repo and launch the app in debug mode in a simulator (XCODE 14.2 - iPhone 12 Pro)
2. input a INFURA MAINNET API Key inside the `.js.env` file
3. Launch the Metamask on Simulator: `yarn setup` and `yarn watch` and `yarn start:ios`
4. Launching the Metamask app on IOS
5. Opening the Browser - getting the attached above issue

**Expected behavior**
able to open website without having the error popping up all the time which block me from using the app

**Smartphone (please complete the following information):**
 - Device: Simulator iPhone 12 Pro
 -  OS: 16.2
 - App Version v6.4.0 (1100)

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by Ardziv** [comment]
redundant with ticket https://github.com/MetaMask/metamask-mobile/issues/4752 - but still issue exist in `core/Engine.ts` that does not correctly get the INFURA key from process.env.MM_INFURA_PROJECT_ID 

`infuraProjectId: process.env.MM_INFURA_PROJECT_ID || NON_EMPTY,`

**Comment by tommasini** [comment]
Hey @Ardziv thanks for reporting, did you manage it hardcoding the infura key, how it was commented [here](https://github.com/MetaMask/metamask-mobile/issues/4752#issuecomment-1199922638)? 

It's also happening on android?
