### ISSUE TITLE
[Bug] Passing EIP-1559 gas params from a Dapp into MM while on non EIP-1559 network sets gas to `0`

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-mobile#6284]
**Describe the bug**
Whenever we are using a non EIP-1559 network, if a Dapp passes gas params according to EIP-1559 MetaMask accepts the transaction and sets Total gas value to `0`.

**Screenshots**

https://user-images.githubusercontent.com/54408225/234829930-143d88a8-5484-454e-a2cf-aa2c4da930a3.mp4

**To Reproduce**
_Steps to reproduce the behavior_
1. Go to the test dapp https://metamask.github.io/test-dapp/
2. Select a non EIP-1559 network (i.e. Polygon zkEVM testnet)
3. Deploy failing contract
4. Click Send failing transaction
5. See how total amount of gas is set to `0`

**Expected behavior**
In this case, on Extension we do not let MM open and the test dapp displays the following error message `Invalid transaction params: params specify an EIP-…but the current network does not support EIP-1559',` 

cc @bschorchit 

**Smartphone (please complete the following information):**
 - Device: Pixel 6
 - OS: android
 - App Version: `v6.5.0`

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by bschorchit** [comment]
I've added to this sprint backlog. 
Q: is the user able to confirm this transaction?

**Comment by segun** [comment]
@seaona  Not sure if it's just me but the attached video is not playing...

**Comment by seaona** [comment]
@bschorchit nope, as the gas params are not correct (see left side, where we are trying to pass mxPriorityFeeperGas, while we are on a non EIP1559 network)

![image.png](https://images.zenhubusercontent.com/621e5074355dc7130e44d3d0/f2546ad4-ad95-45db-bd30-508e0942b0a4)

@segun I believe the video is uploaded correctly. Are you still not able to see it? If not, ping me on slack and I can share it with you

**Comment by jpuri** [comment]
@bschorchit , @seaona : I would prefer to de-prioritise this issue reason being that change to throw error for such a transaction is required to be done in transaction controller. Transaction controller version used in mobile is not updated. Mobile is using `"@metamask/transaction-controller": "4.0.0"` while the latest version is `5.0.0`. Thus it will be major version update which can be a breaking change.

Since the issue is not critical, I avoid prefer to do this change only after transaction controller is updated.

Since user is not not passing gasPrice metamask is setting it to `0`. User is passing maxFee and priorityFee which are not used for legacy transactions.

Please suggest.

**Comment by jpuri** [comment]
@bschorchit : PR is actually only patching transaction controller not updating it. As I know mobile team is working towards un-blocking controller updates, its hard to do that as there are too many interdependencies between controllers and breaking changes to handle.

An option is that we make this fix in controller and wait for next update to include it.

**Comment by jpuri** [comment]
The behaviour of extension here has been reported as an issue: https://github.com/MetaMask/metamask-extension/issues/13862

I think correct approach in this case will be to use default network suggested gas price and not `0`.
