### ISSUE TITLE
[Bug] Send ETH from Deeplink stays loading indefinitely if switch network and not enough ETH

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-mobile#6286]
**Describe the bug**
Whenever we are performing a Send ETH using a Deeplink, if the Deeplink is pointing to a different network, and we don't have enough ETH on that network, MetaMask stays loading indefinetly.

**Screenshots**

https://user-images.githubusercontent.com/54408225/234872908-f37c7db5-6ac6-44a1-81e4-04c8b6cf2a59.mp4

**To Reproduce**
_Steps to reproduce the behavior_
1. Select Goerli network
2. Click scan
3. Scan this QR code

![Screenshot from 2023-04-27 15-14-34](https://user-images.githubusercontent.com/54408225/234873123-f947e5d6-dc04-4457-a24c-c91295e4e006.png)

4. See how MM changes to Mainnet and stays loading indefinitely

**Expected behavior**
Load the Send screen and disable the Send button + show not enough funds? @bschorchit 

**Smartphone (please complete the following information):**
 - Device: Pixel 6
 - OS: android
 - App Version: `v6.5.0`

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by bschorchit** [comment]
Closing as this is no longer an issue :)
