### ISSUE TITLE
[Bug] Trying to Send an ERC20 token amount with more decimals than expected, results in nothing

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-mobile#6295]
**Describe the bug**
Whenever we are trying to send an ERC20 token, if we input a value which has more decimals than the token contract expects, we see how clicking Next, does nothing and we stay in the Amount screen.

**Screenshots**

https://user-images.githubusercontent.com/54408225/235092277-f797774d-fb5b-4e6b-a29e-6f9ba11a2e9d.mp4

**To Reproduce**
_Steps to reproduce the behavior_
1. Go to test dapp
2. Deploy an ERC20 token
3. Add token to wallet
4. Go to the wallet view
5. Click Send TST token
6. Add amont with more than 4 decimals
7. Click Next
8. See nothing happens

**Expected behavior**
@bschorchit 
- Should we see a warning/indicator of what is happening ? 
- Should Next button be disabled ?

In extension, the value is rounded to the expected number of decimals - see here:

https://user-images.githubusercontent.com/54408225/235093778-a09273b5-6d6e-47a8-a916-3ff113245a75.mp4

**Smartphone (please complete the following information):**
 - Device: Pixel 6
 - OS: android
 - App Version 6.4

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by bschorchit** [comment]
Closing as a duplicate of https://github.com/MetaMask/metamask-mobile/issues/6324
