### ISSUE TITLE
[Bug] Swaps - not possible to select another Quote

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-mobile#6298]
**Describe the bug**
Whenever I'm performing a Swap, it is not possible to select a different Quote than the pre default one.

**Screenshots**

https://user-images.githubusercontent.com/54408225/235198987-75a0302e-e8f7-458c-b007-5db12c1732b3.mp4

**To Reproduce**
_Steps to reproduce the behavior_
1. Click Swap
2. Add any amount an asset
3. Click Quotes
4. See you cannot select any other quote, just see the details

**Expected behavior**
We should be able to select the Quote we want, as it's done in Extension. See:

![Screenshot from 2023-04-28 18-08-20](https://user-images.githubusercontent.com/54408225/235199159-5d57de50-fc2e-4c9f-9fea-a3a3eefa6ac3.png)

**Smartphone (please complete the following information):**
 - Device: Pixel 6
 - OS: android
 - App Version: `6.4.0`

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by wachunei** [comment]
For context: this was decided back then. (I wanted to say "it is not a bug, it is a feature")

**Comment by seaona** [comment]
oh I was not aware of this, thank you @wachunei ! I close the issue then

**Comment by wachunei** [comment]
Sure, we can revisit the feature. Probably is already scheduled for next quarter.
