### ISSUE TITLE
[Bug] `BigInt` module not found on Approve ERC20 on Android

### ISSUE THREAD

**Issue by sethkfman** [MetaMask/metamask-mobile#6307]
### **Description**

Whenever I try to make an Approve tx, the app crashes with this errror `Can't find variable: BigInt`

**[only-android]**

After first [reporting it here](https://github.com/MetaMask/metamask-mobile/pull/5591#issuecomment-1516330068), we've seen that it's a separate issue, happening on the RC branch `6.4`

**Screenshots**

https://user-images.githubusercontent.com/54408225/233622389-0dfcab94-7154-41f3-9504-fec4edbb545a.mp4

**Steps to reproduce the behavior**

1. Go to the test dapp
2. Deploy the Collectibles contract
3. Mint a token
4. Click Approve
5. MM crashes with the error  `Can't find variable: BigInt`

- Device: Pixel
- OS: Android
- App Version: v6.4.0

Related Issue: [#913](https://github.com/MetaMask/mobile-planning/issues/913)

**Comment by tibi77** [comment]
Has this one been solved? I can see the big int code being imported; cc @sethkfman ?

**Comment by sethkfman** [comment]
Closed due to this issue be completed: https://github.com/MetaMask/mobile-planning/issues/913
