### ISSUE TITLE
[Bug] Sending an ERC20 token from a Deeplink sets amount to a huge number, if the value passed has more decimals than the decimals defined on the Token Standard

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-mobile#6323]
**Describe the bug**
Whenever we are trying to Send an ERC20 token using a Deeplink, if the amount contains more decimals than the one that can be handled by the token standard, the Send page opens with a very big value.

**Screenshots**

https://user-images.githubusercontent.com/54408225/235891913-679eaa12-d853-4ba7-8156-d90843001ae0.mp4

**To Reproduce**
_Steps to reproduce the behavior_
1. Scan this QR code - which is setting a value of `0.0033` but the token standard only supports 0 decimals

![Screenshot from 2023-05-03 12-28-12](https://user-images.githubusercontent.com/54408225/235892174-85fe3bb9-b3b2-477f-a64f-c3655982ed7f.png)

2. See amount

Alternatively, you can generate the token contract and deeplink by yourself if you do the following:
1. on the test dapp, input `0` decimals and deploy the ERC20 token contract
2. Copy the contract address
3. Go to deeplink generator https://metamask.github.io/metamask-deeplinks/#
4. Select Send ERC20
5. Input the contract address
6. Add any recipient
7. Add 0 decimals
8. Add any value with decimals `0.003`
9. Scan the QR code from MM
10. See amount

**Expected behavior**
Not sure what should be the expected behavior @bschorchit . On Extensions when a case like this happens, the value it is rounded, meaning if we have `0.43` value set is `0` whereas if we have `0.53` value set is `1`.

**Smartphone (please complete the following information):**
 - Device: Pixel 6
 - OS: android
 - App Version: `6.4.0`

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by bschorchit** [comment]
Is the user able to send the transaction? What amount is used for the actual transaction?

**Comment by seaona** [comment]
Usually the transaction fails because the user has not enough token balance @bschorchit

**Comment by blackdevelopa** [comment]
@seaona, do you think this can be added to this sprint or the next. Then we can work on it
