### ISSUE TITLE
[Bug] Sending an ERC20 token with an amount with more decimals than the ones defined on the Token Standard, results in nothing

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-mobile#6324]
**Describe the bug**
Whenever we are trying to Send an ERC20 token, if we input an amount with more decimals than the contract is expecting, whenever we click Next, nothing happens.

This relates to https://github.com/MetaMask/metamask-mobile/issues/6323

**Screenshots**

https://user-images.githubusercontent.com/54408225/235894032-42019be5-f7a0-421a-b450-504a23af58e7.mp4

**To Reproduce**
_Steps to reproduce the behavior_
1. Import an ERC20 token
2. See token details, to check how many decimals supports
3. Click Send
4. Add an amount with more decimals than the supported ones
5. Click Next
6. Nothing happens

**Expected behavior**
Not 100% sure what to expect here. In Extension we round the values. @bschorchit 

**Smartphone (please complete the following information):**
 - Device: Pixel 6
 - OS: android
 - App Version: `6.4.0`

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by bschorchit** [comment]
Yes, let's mirror extension on this.
