### ISSUE TITLE
Legacy Transactions Shows EIP1559 Edit Gas Fee Modal

### ISSUE THREAD

**Issue by blackdevelopa** [MetaMask/metamask-mobile#6329]
**Describe the bug**
When editing gas fee for a legacy transaction while on an eip1559 supported network, the edit gas modal doesn't show the correct gas edit options. 

**Screenshots**
http://recordit.co/YjhKuXpnSn

**To Reproduce**
_Steps to reproduce the behavior_
1. Go to Mainnet (or any eip1559 supported network)
2. Go to MM test [dapp](https://metamask.github.io/test-dapp/)
3. Scroll down to Send Legacy Transaction
4. Click on the gas fees to edit
5. Click suggested gas fee
6. See error

**Expected behavior**
When you click to edit gas fee, it should show the legacy edit gas option

**Smartphone (please complete the following information):**
 - App Version [e.g. 1.0.0] - find version number in app from Settings > About MetaMask

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by seaona** [comment]
Same as https://github.com/MetaMask/metamask-mobile/issues/5760 ?
