### ISSUE TITLE
[Bug] ENS domain not displayed on the Confirmation screen

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-mobile#6330]
**Describe the bug**
Whenever we perform a Send to an ENS domain, we can see how when we land on the last Confirmation screen, only the recipient address is displayed but not the ENS domain.
 
**Screenshots**

[Screencast from 04-05-23 12:20:29.webm](https://user-images.githubusercontent.com/54408225/236177795-c4baa6eb-48af-4862-bc13-57a36a0872cf.webm)

**To Reproduce**
_Steps to reproduce the behavior_
1. Select Main network
2. Click Send
3. Add an ENS domain : `seaona.eth`
4. Click Next
5. Add amount
6. Proceed
7. See how only recipient address is displayed

**Expected behavior**
We should see the ENS domain as well as the address below, like we did before:

![Screenshot from 2023-05-04 12-20-01](https://user-images.githubusercontent.com/54408225/236177830-0569fec2-a4a8-4f6f-bf5c-4be40975c42e.png)

**Smartphone (please complete the following information):**
 - Device: Pixel 6
 - OS:  android
 - App Version: `6.6`

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by bschorchit** [comment]
This is a regression for 6.6 cc: @chrisleewilcox - we'll be prioritizing a fix for this over our next sprint
