### ISSUE TITLE
[Bug] Send ETH displays `Collectible` as predefault value in the `Amount` screen and `undefined` balance

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-mobile#6331]
**Describe the bug**
Whenever we install MetaMask for the first time (update into the release `6.5`) when I click to Send, I can see how the selected token is `Collectible` instead of ETH. Also we see how there is an `undefined` value in the Balance.

**Screenshots**

https://user-images.githubusercontent.com/54408225/236208836-d75ecf6c-7837-4d0c-a952-69b2114ad03d.mp4

**To Reproduce**
_Steps to reproduce the behavior_
1. Install MM for the first time
2. Click Send
3. Add recipient
4. See how `Collectibles` is displayed as the selected token and Balance `undefined`

**Expected behavior**
ETH should be selected by default when we click Send

**Smartphone (please complete the following information):**
 - Device: Pixel 6
 - OS: android
 - App Version: `6.5`

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by bschorchit** [comment]
This is a regression in 6.5 
ccing @chrisleewilcox for visibility

**Comment by sethkfman** [comment]
@chrisleewilcox @bschorchit @seaona This was changed to a sev1 which would be a release blocker. Can we clarify why and add the release blocker label?

**Comment by chrisleewilcox** [comment]
@sethkfman  This issue is a disruption in the Send flow and can have various unknown impact including potential fund loss.
