### ISSUE TITLE
App crashes when downloading an image generated from a data URL

### ISSUE THREAD

**Issue by rozztopher** [MetaMask/metamask-mobile#6346]
When using the Metamask browser the app crashes when I attempt to download an image using a data URL generated from a canvas DOM element. Below is the code that I have. The first is the download function (downloadQR) which uses a canvas to paint an existing canvas onto an image. The second is my download button.

```
const qrCanvas = document.getElementById("qr-canvas");
const downloadButton = document.getElementById("downloadButton");
const image = document.getElementById(`qr-image`);
const finalCanvas = document.createElement("canvas");
finalCanvas.width = image.width;
finalCanvas.height = image.height;

const ctx = finalCanvas.getContext("2d");
ctx.drawImage(image, 0, 0);
ctx.drawImage(qrCanvas, x, y, size, size);

downloadButton.href = finalCanvas.toDataURL("image/jpg");
```

```
<a
  id="downloadButton"
  onClick={downloadQR}
  download="QR.jpg"
  href="#"
>
  Download
</a>
```

On all devices and browsers, this download functionality works as expected and will download the image file to my device. The only place I am having this issue is with the Metamask mobile browser.

The device I've been testing with is a Pixel 7 with the Metamask version of 6.4.0

I'd be very grateful if this was addressed.

**Comment by gauthierpetetin** [comment]
Closing as duplicate from https://github.com/MetaMask/metamask-mobile/issues/2195
