### ISSUE TITLE
Metamask cannot connect with DApps after upgrade to version 6.5.0

### ISSUE THREAD

**Issue by duybuikardiachain** [MetaMask/metamask-mobile#6387]
I'm using WalletConnect V1 to connect with Metamask

I have just updated Metamask to the latest version (6.5.0), but now it cannot connect to my DApp
I working on older version (6.3.0)

**Comment by duybuikardiachain** [comment]
Seem something wrong with Metamask version 6.5.0

**Comment by duybuikardiachain** [comment]
Seem need to fill all data on WC PeerData. Problem will solved

**Comment by JayChowMu** [comment]
> 
Hi, I filled all the PeerData, but still can't connect to Metamask 6.5.0. Do u mind sharing a slice of your code?

**Comment by idelburgo-iomob** [comment]
Same here, Metamask stopped being able to connect through wallet connect. I also have all the PeerData filled.
Implementation is working with other wallets, and was working prior to 6.5.0

**Comment by JayChowMu** [comment]
Hi guys, I finally figured it out.  To connect to Metamask 6.5.0, you need to encode your 'wc://' uri like below:
`uriStr = 'metamask://wc?uri=${Uri.encodeComponent(uriStr)}';`

**Comment by JayChowMu** [comment]
> It did not work for me. I don't know why.
> 
> ```dart
>     final session = await connector.createSession(
>           onDisplayUri: (uri) async {
>             final uriStr = 'metamask://wc?uri=${Uri.encodeComponent(uri)}';
>             await launchUrlString(uriStr);
>           },
>         );
> ```

Try remove 'await' from your code: `await launchUrlString(uriStr);`, make sure metamask version >= 6.5.0. Only 6.5.0 need encoded uri

**Comment by phucnguyen1901** [comment]
Thank @JayChowMu, I filled all the PeerData and it works. We can use `Uri.https("metamask.app.link", 'wc', {'uri': uri}).toString()` or `metamask://wc?uri=${Uri.encodeComponent(uri)}` both work.

**Comment by idelburgo-iomob** [comment]
Unfortunately thats not working for me, Im using native app written in Kotlin. Tried all your approaches and still no luck.

**Comment by ioridev** [comment]
I still haven't resolved it.
