### ISSUE TITLE
Metamask does not display the Import token in the UI when screen is zoomed 

### ISSUE THREAD

**Issue by anaamolnar** [MetaMask/metamask-mobile#6388]
Problem:
Users with screen zoom/font size settings higher than the lowest value cannot scroll to access the Import token button to import their tokens when there are more than 6 tokens in the asset list. 

Steps to reproduce:
1. Set screen zoom from Settings → Display → Screen zoom to a higher value than the minimum
2. Log in to the wallet
3. Import some tokens so that it fills out the screen
4. Try to scroll to press the Import button
5. The scroll functionality does not work

![image](https://github.com/MetaMask/metamask-mobile/assets/82837486/c22c7c3b-b0b7-4405-ab36-32caae510935)

Device: Samsung S22, A53, etc.
OS: Android 13
 
Workaround:
Settings → Display → Font size and style → Set to the lowest value
Settings → Display → Screen zoom → Set to the lowest value

Expected behavior:
The scrolling functionality should work and the Import token link should appear in the UI even if the user is not using the lowest setting for screen zoom and font size on their devices.

**Comment by hesterbruikman** [comment]
fixed via #6431
