### ISSUE TITLE
[Bug] Gas is not correctly estimated when Sending ETH to a Contract using a Deeplink

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-mobile#6405]
**Describe the bug**
Whenever I am sending ETH to a contract address using a deeplink, I can see how the gas is not correctly calculated, resulting in the errror `intrinsic gas too low` if I try to Send the transaction.

**Screenshots**

https://github.com/MetaMask/metamask-mobile/assets/54408225/ac4c26b7-0d72-4ddf-9361-29ab11f24258

**To Reproduce**
_Steps to reproduce the behavior_
1. Select Sepolia network
2. Click on Scan

![image](https://github.com/MetaMask/metamask-mobile/assets/54408225/a417239a-6dc7-416e-bd7b-b0de0e2a8f76)

4. See gas is not correctly calculated
5. Click Send
6. See `intrinsic gas too low` error

**Expected behavior**
Gas should be correctly calculated.

**Smartphone (please complete the following information):**
 - Device: Pixel 6
 - OS: Android
 - App Version: it was working on `v6.5.0` and not working on `v6.6.0` onwards

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by bschorchit** [comment]
I was not able to reproduce this on ios v6.3.0 so this might have been introduced at a later release or is android specific.

**Comment by seaona** [comment]
I am able to reproduce this on iOS `v7.0.0` and also on Android `v6.6.0` and `v6.7.0` . I think that the issues about Intrinsic Gas were fixed at some point in time and later on re-introduced (maybe in `6.6.0` for android)

**Comment by chentschel** [comment]
I'm having the same issue with IOS v7.0.1. Looks like `gas` or `gasLimit` params are ignored in the links. 

This is some example link i'm testing. 
```
ethereum:0xdac17f958d2ee523a2206206994597c13d831ec7@1/transfer?address=0x69530F68541a5583F5B3D1dB1920b7523c55E77F&uint256=2.724e5&gas=75000
```

**Comment by bschorchit** [comment]
I'm able to reproduce this on ios v.7.7
