### ISSUE TITLE
[Bug] Approving an ERC20 token with an amount with more decimals than expected, results in nothing

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-mobile#6408]
**Describe the bug**
Whenever we are approving an ERC20 token, if we add a custom value with an amount with more decimals than the specified on the token contract, we see how the value is not changed, even though it seems that it has.

**Screenshots**

https://github.com/MetaMask/metamask-mobile/assets/54408225/6940fff2-42b2-4c31-b247-2f470f55ab07

**To Reproduce**
_Steps to reproduce the behavior_
1. Go to test dapp
2. Change decimals to 0
3. Deploy ERC20 token
4. Click Approve
5. Click Edit permission
6. Add any amount with decimals, i.e. `1.3`
7. Accept
8. See how value is not changed

**Expected behavior**
How should we handle this case @bschorchit ? cc @blackdevelopa 

Similar to what happens with the Send flow https://github.com/MetaMask/metamask-mobile/issues/6324

**Smartphone (please complete the following information):**
 - Device: Pixel 6
 - OS: Android
 - App Version: `v6.6.0` and possibly earlier

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by blackdevelopa** [comment]
Hi @seaona, I checked this against extension and from the UI, we are also unable to add a value with more decimals than the token contract. For mobile, we could replicate same or throw an error message. http://recordit.co/Pgc32F4GTK

**Comment by bschorchit** [comment]
I think we should replicate the extension behavior. Is this still an issue now that https://github.com/MetaMask/metamask-mobile/pull/5591 was merged?

**Comment by blackdevelopa** [comment]
@bschorchit yes it does with an even higher severity. I have created a PR for this. [fix: Approving an ERC20 token with an amount with more decimals than expected crashes approving](https://github.com/MetaMask/metamask-mobile/pull/6623)

**Comment by bschorchit** [comment]
Closing as PR was merged :)
