### ISSUE TITLE
[Bug] Cannot import an ERC20 token when on a network id `1337`

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-mobile#6410]
**Describe the bug**
I cannot import an ERC20 token when I am using a network with id `1337`. This would be beneficial both from user perspective and for e2e testing.

See https://consensys.slack.com/archives/C01U65ZUS2E/p1680206062768139

**Screenshots**

![image](https://github.com/MetaMask/metamask-mobile/assets/54408225/abd6326b-c8b4-431d-a6ed-6a6b28e1a533)

https://github.com/MetaMask/metamask-mobile/assets/54408225/2dfd13c3-6988-41e3-aa47-0537373f622e

**To Reproduce**
_Steps to reproduce the behavior_
1. Setup a local network (i.e. Ganache)
2. Select local network
3. Go to test dapp
4. Deploy an ERC20 token
5. Click Add Token
6. See error 

**Expected behavior**
Support `watch_asset` for chainId 1337

**Smartphone (please complete the following information):**
 - Device: Pixel 6
 - OS: Android
 - App Version: Android

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by JesseMorningstar** [comment]
I'm having the same issue with MetaMask on Desktop.
It would be lovely to get a sense of the UX of a token very early on while developing on a local testnet.
A fix would for this bug would be highly appreciated. 🙌
