### ISSUE TITLE
Metamask cannot see the option "Import tokens" after upgrade to version 6.5.0

### ISSUE THREAD

**Issue by hcc0000** [MetaMask/metamask-mobile#6417]
**Describe the bug**
I cannot see the option "Import tokens".

**Screenshots**
[Video](https://github.com/hcc0000/issue/blob/main/metamask/metamask-mobile/issue_6417/Screen_Recording_20230518_131323_MetaMask.mp4)

**To Reproduce**
_Steps to reproduce the behavior_
1. Go to Network (ETH, BSC, ... or others)
2. Add some new tokens (Maybe 3, 4, ... or 10)
3. You will not see the option "Import tokens"
4. Unable to add any new token

**Expected behavior**
However, after the token has increased to a certain number, it cannot be added.

**Smartphone (please complete the following information):**
 - Device: Samsung S23 Ultra
 - OS: Android 13
 - App Version: 6.5.0 (1104)

 -------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by anaamolnar** [comment]
Closing in favor of #6388.
