### ISSUE TITLE
[Bug] Account name incorrectly displayed on another address

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-mobile#6434]
**Describe the bug**
When I perform a transaction from a Dapp I can see how the `To` field displays `Account 2` to a recipient that it's not Account 2. It seems that this is caching the value from a previous transaction performed from inside MetaMask to Account 2.

**Screenshots**

https://github.com/MetaMask/metamask-mobile/assets/54408225/4a18af33-8816-4053-aad4-f05830cca273

**To Reproduce**
_Steps to reproduce the behavior_
1. Install MetaMask
2. Initiate a Send ETH to Account 2
3. Cancel Tx
4. Go to dapp
5. Connect MM
6. Click Send EIP1559
7. See how Account 2 name is displayed

**Expected behavior**
We should not cache the Account name whenever initiating a new transaction from a Dapp

**Smartphone (please complete the following information):**
 - Device: Pixel 6
 - OS: Android
 - App Version: `v6.5.0` or even earlier

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by bschorchit** [comment]
Seems possibly related with https://github.com/MetaMask/metamask-mobile/issues/6435
