### ISSUE TITLE
Confirm/Reject buttons not visible on shorter screens, hard to get to.

### ISSUE THREAD

**Issue by KholdStare** [MetaMask/metamask-mobile#6436]
**Describe the usability problem**
On phone screens that are not tall, the confirm/reject buttons are not visible at the bottom of the confirmation pop-up. Worse, _only the bottom part of the screen is scrollable and this is not obvious_. Specifically, the section that starts with "estimated gas fees" is a separate scrollable area.

Users try to scroll down in the middle of the screen but it doesn't go anywhere. There is no scroll bar on the bottom section so users have no idea that that tiny area needs to be scrolled to reveal the reject/confirm buttons

**Screenshots**
I censored a bunch of data since this came from one of our users to avoid any identifiable information. You can see that "estimated gas fees" section is at the bottom, and it is an extremely small area to scroll on. Not at all obvious.

![image](https://github.com/MetaMask/metamask-mobile/assets/836110/6ed459de-60e6-4e8c-89f5-b399e42a4211)

**Proposed behavior**
Make the entire pop-up scrollable so it's intuitive for users to scroll down to see more details.

------------------------------------------------------------------------------------------------------
_filled out after submission_

**User impact | Usage frequency | Feasibility scores**
_How important is this to the user, what the user wants to accomplish | Daily, weekly, monthly | Small, medium, large_

**Comment by jiwoongim** [comment]
This is a serious issue. There are people who don't see accept and reject from their phones. You have to scroll down, but it is not easy to tell between the bottom container vs. top container.

For example, see this example... 
https://github.com/MetaMask/metamask-mobile/assets/848514/24624f1a-5642-4695-a785-654483880ad1
This is quite a bet UX design

**Comment by KholdStare** [comment]
@bschorchit @hilvmason Has this been fixed?

**Comment by bschorchit** [comment]
> @bschorchit @hilvmason Has this been fixed?

Not yet @KholdStare . We're planning a re-design for confirmations and this will be fixed with this re-design. It will take a a couple of months before it's released to users though. We'll keep this issue open to track this specific issue.

**Comment by KholdStare** [comment]
Ok, thank you. Just wanted to make sure that the issue was not ignored as "stale"
