### ISSUE TITLE
Deeplink metamask://wc?uri=wc:..... broken in versión 6.5.0

### ISSUE THREAD

**Issue by jcorreapa** [MetaMask/metamask-mobile#6457]
**Describe the bug**
I am developing a native mobile application in Flutter, for this I use the library [https://pub.dev/packages/walletconnect_dart], at the moment of making the connection and generating the Uri, a uri of the type 'wc:... @1?bridge=https%3A%2F%2Fg.bridge.walletconnect.org&key=....'.

Before the current version 6.5.0, to open the metamask app, it worked perfectly for IOS and Android with the following structure: `launchUrlString('metamask://wc?uri=$uri', mode: LaunchMode.externalApplication)`. But with the current version it stopped working, because although the app is opened, the connection modal is not shown.

It is not a problem of the library used, because when opening the application with the following structure: `launchUrlString(uri, mode: LaunchMode.externalApplication)`, the modal is displayed. Which is not suitable for me, as this will open any wallet that supports the wc protocol, and my app only supports Metamask mobile.

**Screenshots**

https://github.com/MetaMask/metamask-mobile/assets/55594799/61db4ec9-26a2-4445-95ec-7726cf1d54f8

**To Reproduce**
Steps to reproduce the behavior
- Clone the flutter repository [https://github.com/jcorreapa/wallet_connect_dart_example.git](url) and follow the instructions to run the app.
- Explore the app, pressing buttons.

**Smartphone** (please complete the following information):

Device: Samsumng S20 
OS: Android
App Version: v6.5.0

**Comment by idelburgo-iomob** [comment]
You posted the same code for "incorrect" and "correct", which is the code that is working for you? I have similar problem too, but with a native Android app (Kotlin)

**Comment by ContrastPro** [comment]
This code dost work correctly and don't show modal in my case only on some Android devices:
`launchUrlString('metamask://wc?uri=$uri', mode: LaunchMode.externalApplication)`

But this code works perfectly
`launchUrlString('$uri', mode: LaunchMode.externalApplication)`

**Comment by ContrastPro** [comment]
To open Metamask, and not other crypto wallets, I like many developers, use the special prefix `metamask://wc?uri=$uri`. But it seems that after a recent update, the Metamask team changed some data associated with deep links, and they stopped working correctly.

**Comment by idelburgo-iomob** [comment]
I have tried all these (Im in a native app in Kotlin):

- link as "metamask://wc?uri=$uri" -> opens metamask but no modal to connect
- link as "wc://wc?uri=$uri" -> let me select which wallet to use, selecting metamask but no modal to connect
- link as "$uri" -> let me select which wallet to use, selecting metamask returns to my app with instant "Session rejected"

This error broke my implementation that was working prior to this version.

Any suggestion to make it work again?

**Comment by jcorreapa** [comment]
> You posted the same code for "incorrect" and "correct", which is the code that is working for you? I have similar problem too, but with a native Android app (Kotlin)

It's true, I just edited it. The one that really works is the: `launchUrlString(uri, mode: LaunchMode.externalApplication)`

**Comment by unicorndev99** [comment]
I am using React-Native and have same error in connecting the Metamask with App.
How can I solve this in the react native? @jcorreapa

**Comment by ioridev** [comment]
launchUrlString(
                _uri,.
                mode: LaunchMode.externalApplication,.
              ); 
I can connect on Android, but no connection modal on iOS. I've been having trouble for a month.
When will it be fixed?

**Comment by adrianotadao** [comment]
any updates on this?

**Comment by adrianotadao** [comment]
@unicorndev99 are you sure about it? It does not work for me. 😢

**Comment by unicorndev99** [comment]
Yes. I am sure.
I checked already in the react native.

**Comment by ContrastPro** [comment]
If someone managed to connect to Metamask using the [WalletConnect](https://pub.dev/packages/walletconnect_flutter_v2) library, please write an example of how you implemented it!

**Comment by unicorndev99** [comment]
Please check https://docs.walletconnect.com/2.0/reactnative/walletconnectmodal/installation
This is working with Metamask v7.0.1

**Comment by ContrastPro** [comment]
When I generate a link and try to open it with the launchUrlString or just launchUrl method, the metamask opens, but the modal window for the connection does not appear. But if you generate a qr code from this link and scan it with a regular smartphone camera, Metamask will open and a modal window for connection will appear. What could be the problem?
<img width="506" alt="Снимок экрана 2023-06-29 в 19 16 04" src="https://github.com/MetaMask/metamask-mobile/assets/49535226/dac62dbb-b894-4714-9b12-adf013e292d6">

**Comment by solsticesolutions** [comment]
@unicorndev99 the issue I am seeing is universal links are working but deep links are not. 
Is it working for you with a deep link on iOS?

**Comment by ContrastPro** [comment]
Guys check this [issue](https://github.com/WalletConnect/WalletConnectFlutterV2/issues/113) we discuss some points how to resolve problems with connections.

**Comment by christopherferreira9** [comment]
Closing this issue as it seems that the new MetaMask wallet solved it along side [this](https://docs.walletconnect.com/2.0/reactnative/walletconnectmodal/installation).
