### ISSUE TITLE
Since Version 6.5.0 Kotlin native app WalletConnect v1 deeplinks can't be handled by Metamask

### ISSUE THREAD

**Issue by idelburgo-iomob** [MetaMask/metamask-mobile#6469]
**Describe the bug**
Prior to this versions I have an implementation of WalletConnect v1 working smoothly with Metamask that allowed to connect the wallet to my app, and then sign a message with the wallet. All this using WalletConnect v1, using the deeplinks provided by it.

**Screenshots**
_If applicable, add screenshots or links to help explain your problem_

**To Reproduce**
Through my app
1. Generate a connection with WalletConnect v1 SDK 
2. With the Uri provided by the SDK launch an Intent to open it.
3. MetaMask opens but can't handle the deeplink.

Different attempts were done:
- link as "metamask://wc?uri=$uri" -> opens metamask but no modal to connect
- link as "wc://wc?uri=$uri" -> let me select which wallet to use, selecting metamask but no modal to connect
- link as "$uri" -> let me select which wallet to use, selecting metamask returns to my app with instant "Session rejected"

**Expected behavior**
MetaMask should open the modal to accept the connection and then with the next deeplink (to sign a message) open a new modal with the Signing Request. All this was already working with my implementation before.

**Smartphone (please complete the following information):**
 - Device: [Xiaomi Mi 10 T] (Tested others too, but same result)
 - OS: [Android 12]
 - App Version [6.5.0 (1104)]

# Code used
Add this to the Application class:
```
companion object {
        private lateinit var client: OkHttpClient
        private lateinit var moshi: Moshi
        private lateinit var storage: WCSessionStore
        private lateinit var bridge: BridgeServer
        lateinit var config: Session.Config
        lateinit var session: Session

        private const val bridgeUrl = "https://bridge.walletconnect.org"
        private val metaData = Session.PeerMeta(
            name = "<Name>",
            url = "<URL>",
            description = "WalletConnect Integration",
            icons = listOf("https://raw.githubusercontent.com/WalletConnect/walletconnect-assets/master/Icon/Gradient/Icon.png")
        )

        fun resetSession() {
            nullOnThrow { session }?.clearCallbacks()
            val key = ByteArray(32).also { Random().nextBytes(it) }.toNoPrefixHexString()
            config = Session.Config(UUID.randomUUID().toString(), bridgeUrl, key)
            session = WCSession(
                config,
                MoshiPayloadAdapter(moshi),
                storage,
                OkHttpTransport.Builder(client, moshi),
                metaData
            )
            session.offer()
        }
    }
```

and initialize the variables in the Application onCreate:
```
//  for v1
        moshi = Moshi.Builder().add(KotlinJsonAdapterFactory()).build()
        client = OkHttpClient.Builder().build()
        storage = FileWCSessionStore(File(cacheDir, "session_store.json").apply { createNewFile() }, moshi)
        bridge = BridgeServer(moshi)
        bridge.start()
```

After this, wherever you need to get the link use:
```
WalletIntegrationExample.resetSession()
        WalletIntegrationExample.session.addCallback(this)
        var deep = WalletIntegrationExample.config.toWCUri()
        println("WALLET_CONN -> V1 LINK: $deep")
//        _connectionUri.value = "metamask://wc?uri=${WalletIntegrationExample.config.toWCUri()}"
//        _connectionUri.value = "wc://wc?uri=${deep}"
        _connectionUri.value = deep
```
connectionUri is a LiveData that triggers the opening of the Link, allowing to select the wallet in the last two cases, whereas case 1 opens metamask directly. 

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by anaamolnar** [comment]
Hello, @idelburgo-iomob. Thanks for reporting! I will pass this on to the team.
