### ISSUE TITLE
[Bug] URL is not displayed complete after trailing slash

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-mobile#6470]
**Describe the bug**
Whenever we navigate into a website, we can see how the URL only displays the first part, but nothing after a trailing slash.

**Screenshots**

https://github.com/MetaMask/metamask-mobile/assets/54408225/9976fec7-ef34-463a-804e-11d95e80c54a

**To Reproduce**
_Steps to reproduce the behavior_
1. Go to the browser
2. Paste the following address `https://metamask.github.io/test-dapp/?contract=0x09f96738239647Cd70A5e181bbcfb20D72085B7C`
3. Click Enter
4. See how only the first part of the address is displayed `https://metamask.github.io`

**Expected behavior**
We should see the complete URL in the browser bar

**Smartphone (please complete the following information):**
 - Device: Pixel 6
 - OS: Android
 - App Version: `6.6`

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by gauthierpetetin** [comment]
This may not be a bug, but common practice on Mobile:

- Even on Android Chrome browser you don't have the entire url as well when it is too long.
- You have to click on it to see the entire url.
