### ISSUE TITLE
[Bug] Swap button is displayed on not supported networks

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-mobile#6472]
**Describe the bug**
Whenever I am on a network which does not support Swaps, I can see how the Swap button is displayed and if I click it nothing happens.

**Screenshots**

https://github.com/MetaMask/metamask-mobile/assets/54408225/0644b6cc-129e-4157-81e8-8f0902054ff0

**To Reproduce**
_Steps to reproduce the behavior_
1. Select any network which does not support Swaps (i.e. Goerli)
2. Click on Goerli ETH
3. See how Swap button is displayed

**Expected behavior**
Swap button should not be displayed on unsupported networks.

**Smartphone (please complete the following information):**
 - Device: Pixel 6
 - OS: android
 - App Version: `v6.7`

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by cortisiko** [comment]
was fixed in https://github.com/MetaMask/metamask-mobile/pull/6473
