### ISSUE TITLE
[Bug] Saved contract contact from a dapp transaction is not displayed when initiating a transaction from inside the Wallet

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-mobile#6483]
**Describe the bug**
Whenever we are performing a transaction from a dapp, we can save the contract recipient address into the Address Book.
Once we've saved the contact, if we go inside the main wallet view and initiate a Send transaction from there, we don't see our saved contact anywhere.

However we can see how the contact is saved on the Settings/Contacts tab.

**Notice**: this behavior only happens with Contact which are contract addresses.

**Screenshots**

https://github.com/MetaMask/metamask-mobile/assets/54408225/46803d74-cb20-4c5c-bc5b-d079d203b352

**To Reproduce**
_Steps to reproduce the behavior_
1. Go to test-dapp
2. Deploy a contract i.e. Multisig
3. Click Send ETH to Multisig
4. Save the address into the address book
5. Go back to the wallet
6. Click Send
7. See how the newly saved contact is not displayed on the recipients list
8. Go to Settings / Contacts
9. See how the contact is there

**Expected behavior**
We should see the contact on the recipient's list whenever we Send a transaction from inside the Wallet.

**Smartphone (please complete the following information):**
 - Device: Pixel 6
 - OS: Android
 - App Version: `6.7.1`

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by bschorchit** [comment]
I'm also able to reproduce on iOS v6.3.0. 
Possibly related with https://github.com/MetaMask/metamask-mobile/issues/4871

**Comment by Andepande** [comment]
![image.png](https://images.zenhubusercontent.com/62e3ac8349f945bda73b7fef/527db253-5afa-41a4-9a9b-7fdd77e52a2b)

**Comment by rafae667** [comment]
Still able to reproduce it

**Comment by bschorchit** [comment]
Removing team-confirmations label and adding team-bridge label as this is an issue specific of the send flow.

**Comment by seaona** [comment]
Still happening in current main

https://github.com/user-attachments/assets/90d2aab6-ab73-4122-a7a0-913ebb6397f8

**Comment by amitabh94** [comment]
Adding team-confirmations label as send flow is now owned by confirmations team.
@dylanbutler1
