### ISSUE TITLE
[Bug] Invalid character in NaN (Depositing tokens to LP)

### ISSUE THREAD

**Issue by deshvin** [MetaMask/metamask-mobile#6524]
**Describe the bug**
I'm unsure if this is a MetaMask bug or has to do with the dapp in question. My example shows this occurring on velodrome.finance (Optimism), but it also occurs on equalizer.exchange (Fantom network) 

**Screenshots**
![Screenshot 2023-06-02 at 11 58 48](https://github.com/MetaMask/metamask-mobile/assets/2859402/689fc36e-e154-4329-b544-7533ae2491eb)

https://github.com/MetaMask/metamask-mobile/assets/2859402/6a0e96af-bbe7-4806-b949-41dc5670ec8e

**To Reproduce**
1. Go to velodrome.finance on the Optimism network
2. Select the hamburger menu > Pools
3. Select Manage Liquidity
4. Choose a token pair that you're able to provide liquidity for
5. Scroll down and select Deposit LP
6. The error occurs
7. If you try again after the error is displayed, the error is no longer shown but it just stays on the page.

Notes:
The dapp should prompt for WETH and OP allowances, but they are skipped and it goes straight to Deposit tokens in the pool, which is I presume why this error occurs (since no token allowances were granted).

**Expected behavior**
Selecting Deposit LP should prompt for the associated token allowances.

**Smartphone (please complete the following information):**
 - Device: iPhone 12 Pro Max 
 - OS: iOS 16.5 (20F66)
 - App Version: v6.3.0 (1095)

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by anaamolnar** [comment]
Hey @deshvin. Thanks for reporting! I will pass this on to the team.
