### ISSUE TITLE
Protect your wallet modal doesn't clear causing confusion during onboarding steps

### ISSUE THREAD

**Issue by davibroc** [MetaMask/metamask-mobile#6545]
**Describe the bug**
When I go through the onboarding steps, if I click on **Protect Wallet** the modal doesn’t clear and then I can go through the **Secure your wallet** steps twice which is quite lengthy and confusing. Apparently this issue has been around for quite some time

**Screenshots**

https://github.com/MetaMask/metamask-mobile/assets/6082863/a7828334-39e7-4983-bc2f-3ae7bf6f9f73

**To Reproduce**
1. Install the App
2. Create a New Wallet
3. Go through the onboarding steps until the **Protect your wallet** modal appears
4. Click on **Protect Wallet**
The modal won't clear and it's blocking the view, also you can click on it once again

**Expected behavior**
Once I click on **Protect Wallet** the modal should clear

**Smartphone (please complete the following information):**
 - Device: Any device
 - App Version 7.0.0

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by plasmacorral** [comment]
Related https://github.com/MetaMask/metamask-mobile/issues/4400

**Comment by gantunesr** [comment]
This issue is not resolved yet
