### ISSUE TITLE
Console warning of unexpected account update without user interaction

### ISSUE THREAD

**Issue by jiexi** [MetaMask/metamask-mobile#6566]
**Describe the bug**
Calling `eth_accounts` from mobile browser causes a console warning of `MetaMask: 'eth_accounts' unexpectedly updated accounts. Please report this bug` to appear when debugging the webview with Safari. 

It seems to be triggered by the equality check in [providers here](https://github.com/MetaMask/providers/blob/23fff814dd4e975cc3bc525e0298c47880077bc1/src/BaseProvider.ts#L423) which sees an array of address with uppercase in saved state and compares it against incoming accounts that have been completely lowercased. May be related to [this lowercase coming from mobile](https://github.com/MetaMask/metamask-mobile/blob/1309c21a56ce909ee193b49365b0c08365c4fbb9/app/core/Permissions/index.ts#L181)?

**Screenshots**

https://github.com/MetaMask/metamask-mobile/assets/918701/836a18f2-cc60-4978-8f55-edcce179046a

**To Reproduce**
For iOS
1. Open Browser
2. Visit `https://app.uniswap.org/`
3. Click Connect -> MetaMask
5. Authorize an account
6. Open Safari
7. Open console for browser
  - Menu Bar -> Develop -> Simulator -> Uniswap View
8. Enter `await window.ethereum.request({method: "eth_accounts"})` into console
9. Error will appear
10. Can repeat `await window.ethereum.request({method: "eth_accounts"})`, and error remains even though account has not changed by user

**Expected behavior**
I expect this warning in console not to appear. Or at least I don't expect it to appear more than once since I as a user have not interacted with MetaMask to change my accounts since the last call.

Note that this warning does not seem to impact dapp behavior. 

**Smartphone (please complete the following information):**
 - Device: iPhone 12 Pro (Simulator)
 - OS: iOS 16.2
 - App Version: v.7.1.0 (1116)

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by anaamolnar** [comment]
Hey, @jiexi. Thanks for reporting! Could you try this again on the latest version available in the App Store (7.3.0)? Is this still occurring after updating? Please let me know. Thanks!
