### ISSUE TITLE
[Regression] Metamask mobile requires gas fees even for gasless, private networks

### ISSUE THREAD

**Issue by cortisiko** [MetaMask/metamask-mobile#6567]
We have a regression on https://github.com/MetaMask/metamask-mobile/issues/3305. I am unable to submit transactions on gasless networks. I am required to have funds in order to submit transactions. This was fixed in https://github.com/MetaMask/metamask-mobile/pull/3756 but now on this RN branch, the functionality is broken. 

To reproduce:
Follow the steps listed here https://consensys.net/docs/goquorum/en/latest/tutorials/quorum-dev-quickstart/ to run Quorum locally
Run the Pet Shop Daap
Try to adopt a pet
Notice the "Submit" button is disabled 
Now if you were to edit the gas price, you are prompted with an [error](https://www.screencast.com/t/AFzNbuHkn). 

See recording: http://recordit.co/R4FcIy1OTu 

This issue happens on both iOS and Android. 
The app version was: v7.1 build 1125

**Comment by bschorchit** [comment]
Hey @hesterbruikman, if this has been introduced by RN upgrade should this be assigned to confirmations team? I'm not sure if we have a lot of context on the RN upgrade, but I can check with the team. Is the RN upgrade being lead by mobile client team?

**Comment by cortisiko** [comment]
confirming this is an existing prod issue. I retested on v6.6(1114) and [encounter the same issue](http://recordit.co/ZlErfxTMkI).

**Comment by bschorchit** [comment]
Oh cool! Thank you, @cortisiko!! I'll triage it with the team 😊

**Comment by hilvmason** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Confirmations-Secure-UX-6245e6e2348677001213b8d2/issues/MetaMask/metamask-mobile/6567?planning-poker) with Zenhub @blackdevelopa @digiwand @jpuri @NiranjanaBinoy @seaona @segun

**Comment by Karkunow** [comment]
Hello! Seeing the same issue on our dApps on Aurora as stated in issue #7088 above.

**Comment by Karkunow** [comment]
@blackdevelopa @hilvmason Hello! Any updates about this case?

**Comment by blackdevelopa** [comment]
Hi @Karkunow thanks for the follow up. We are currently working on this and should have an update in the coming week.
