### ISSUE TITLE
Saved contact alias does not appear in the recipient input box on the send view

### ISSUE THREAD

**Issue by cortisiko** [MetaMask/metamask-mobile#6571]
When a user tries to go through the send flow and tries to add an address to their contacts, the alias does not appear in the recipient input box. 

If you were to:

open the send flow
enter an address
save the address to your contacts
Upon saving the address
The contact alias does not appear in the recipient input box

See recording here: http://recordit.co/3VCSVkUBE1 

Build: 1125
App version: RN v7.1
Device: iOS(iPhone XR)  and Android (pixel 3XL)

**Comment by hesterbruikman** [comment]
@cortisiko can you please try to reproduce this on a physical device?

**Comment by cortisiko** [comment]
hey @hesterbruikman I tested this on a physical device. I don't do feature testing on simulators.

**Comment by Cal-L** [comment]
Removed this from the RN bug report epic since this is an issue on main
