### ISSUE TITLE
routing issue on the settings view.

### ISSUE THREAD

**Issue by cortisiko** [MetaMask/metamask-mobile#6573]
There seems to be a routing issue on the settings view. when a user taps on the NFT auto detection banner the user is anchored down to the NFT auto detection section in the security and privacy view. Fine. From the bottom nav bar, if I were to tap on the wallet icon, then tap on the settings icon. I am taken to the settings view but a back button appears on top of the settings view. If I were to tap on the back button then I am taken back to the NFT auto detection section in the security and privacy view. 

To reproduce:
-  Fresh install of the app
- Go to the NFT’s tab
- Tap on “Turn on NFT detection” in the NFT detection banner
- When you are taken to the NFT auto detection section, tap on the wallet icon from the bottom nav bar
- Now tap on the settings icon
- Notice the back button in the top left corner of the settings view
- Tap on it
- Now you are taken back to the NFT auto-detection section. 
See recording here: http://recordit.co/yWRMzLXfSi 

App version and Build: v7.1 (1125)
Device: iOS (iPhone 11) and android (pixel 3XL)

**Comment by hesterbruikman** [comment]
@cortisiko can you please try to reproduce this on a physical device?

**Comment by cortisiko** [comment]
hey @hesterbruikman I tested this on a physical device. I don't do feature testing on simulators.

**Comment by cortisiko** [comment]
This is no longer an issue after updating the RN branch with main.
