### ISSUE TITLE
Yogakit is not found during iOS build

### ISSUE THREAD

**Issue by rivaratyr** [MetaMask/metamask-mobile#6579]
**Describe the bug**
`/Library/Developer/Xcode/DerivedData/MetaMask-efvlygmygtsivqfurylbvwuaedhh/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/YogaKit.build/Objects-normal/x86_64/YogaKit.swiftinterface:9:8: error: no such module 'yoga'
import yoga`

`The following build commands failed:
	SwiftVerifyEmittedModuleInterface normal x86_64 Verifying\ emitted\ module\ interface\ YogaKit.private.swiftinterface /Library/Developer/Xcode/DerivedData/MetaMask-efvlygmygtsivqfurylbvwuaedhh/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/YogaKit.build/Objects-normal/x86_64/YogaKit.private.swiftinterface (in target 'YogaKit' from project 'Pods')
	SwiftVerifyEmittedModuleInterface normal x86_64 Verifying\ emitted\ module\ interface\ YogaKit.swiftinterface /Library/Developer/Xcode/DerivedData/MetaMask-efvlygmygtsivqfurylbvwuaedhh/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/YogaKit.build/Objects-normal/x86_64/YogaKit.swiftinterface (in target 'YogaKit' from project 'Pods')
(2 failures)`

**To Reproduce**
1. Go to project dir
2. `cd ios`
3. `pod install`
4. `cd ..`
5. `npx react-native run-ios --simulator='iPhone 12 Pro'`

**Expected behavior**
App should be built to the simulator.

**Smartphone (please complete the following information):**
 - Device: iPhone 12 Pro
 - OS: 16.4
 - App Version: latest clone from Git 

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by anaamolnar** [comment]
Hello @rivaratyr. Thanks for reporting! I will pass this on to the team.

**Comment by heyacherry** [comment]
Hello @rivaratyr 

I have hit similar issue before, I suggest you you can do below: 
- Clean Build: Clean your Xcode project by going to `Product -> Clean Build Folder`.
- Update Cocoapods: `sudo gem install cocoapods`
- Use suggested command `yarn setup` & `yarn start:ios` 


Hope this can be helpful : )

**Comment by kristiantokarim** [comment]
any update on this?
