### ISSUE TITLE
[Bug] Balance amount displays `0` for several seconds and back the correct balance in a repeated sequence

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-mobile#6590]
**Describe the bug**
On the Home screen, I can see how balance is set to `0` for some seconds and then got back to my current balance. This happens very often (minimum once every 1 or 2 minutes).
I discard an API issue as I can see how it's working fine in production, with the same API and RPC node.

**Screenshots**

https://github.com/MetaMask/metamask-mobile/assets/54408225/f95fc28a-c480-4e07-8911-fbd238e5b0ac

**To Reproduce**
_Steps to reproduce the behavior_
1. Go to Home screen
2. Select Mainnet
3. Wait
4. See balance is set to `0` 
5. See balance is changed back to your current balance
6. See balance is set to `0`
(this sequence keeps repeating)

**Expected behavior**
Balance should not be `0` if I have funds

**Smartphone (please complete the following information):**
 - Device: Pixel 6
 - OS: Android
 - App Version: happening on current `main` (last commit https://github.com/MetaMask/metamask-mobile/commit/1b79574407323fc7bac30d1ac06190d8f0017644)

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by tibi77** [comment]
Does this happen just on mainnet ? 
can I reproduce it on a testnet as well? so I can faucet the fonds in there
