### ISSUE TITLE
1inch Swap API doesn't work on Native coins 

### ISSUE THREAD

**Issue by AmjadKhan2k18** [MetaMask/metamask-mobile#6593]
**Describe the bug**
Hey, I am using 1inch API to swap from BNB/MATIC/ETH to token but it doesn’t work

it work for token swap but when I try to swap native coin to any token it doesn’t work, on Android I get very big amount in confirmation pop up and IOS correct amount but couldn't confirm it error screenshot added

also I use same response on TrustWallet and it is working perfectly

here is API response that I send in params

```{
"from": "0xab4c8a98bd030029cf08ae5198bd6a347c2e12ec",
"to": "0x1111111254eeb25477b68fb85ed929f73a960582",
"data": "0x12aa3caf000000000000000000000000170d2ed0b2a5d9f450652be814784f964749ffa4000000000000000000000000eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee000000000000000000000000e9e7cea3dedca5984780bafc599bd69add087d56000000000000000000000000170d2ed0b2a5d9f450652be814784f964749ffa4000000000000000000000000ab4c8a98bd030029cf08ae5198bd6a347c2e12ec00000000000000000000000000000000000000000000000000017ff8d04c7800000000000000000000000000000000000000000000000000015c4a6093637b080000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000014000000000000000000000000000000000000000000000000000000000000001600000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000009b00000000000000000000000000000000000000000000000000007d00001a4041bb4cdb9cbd36b01bd1cbaebf2de08d9173bc095cd0e30db002a0000000000000000000000000000000000000000000000000015c4a6093637b08ee63c1e581cb99fe720124129520f7a09ca3cbef78d58ed934bb4cdb9cbd36b01bd1cbaebf2de08d9173bc095c1111111254eeb25477b68fb85ed929f73a9605820000000000cfee7c08",
"value": "422181600000000",
}
```

API : Update with your params, right now I don't have balance in this wallet

https://api.1inch.io/v5.0/56/swap?fromTokenAddress=0xEeeeeEeeeEeEeeEeEeEeeEEEeeeeEeeeeeeeEEeE&toTokenAddress=0xe9e7CEA3DedcA5984780Bafc599bD69ADd087D56&amount=422181600000000&fromAddress=0xab4c8a98bd030029cf08ae5198bd6a347c2e12ec&slippage=10

**Screenshots**
<img width="478" alt="metamask2" src="https://github.com/MetaMask/metamask-mobile/assets/44894621/7a4c5cd5-f305-457a-b42b-f06b2348eb82">
<img width="355" alt="metamask1" src="https://github.com/MetaMask/metamask-mobile/assets/44894621/f5df7426-a30f-4de0-a9ad-64503f97c0bd">

**To Reproduce**
_Steps to reproduce the behavior_
1. Connect Metamask using walletconnect v1
2. Swap from Native coin to non native token eg BNB to BUSD
3. Approve 
4. swap

**Expected behavior**
should successfully swap

**Smartphone (please complete the following information):**
 - Device: Google Pixel 4, Iphone 13 Pro, Iphone 14 Pro max Simulator
 - OS: Android 13, IOS 16.2

 - App Version [e.g. 1.0.0] - find version number in app from Settings > About MetaMask
    Latest version of Metamask at the moment on both Android & IOS

- Is this visible to all users? Yes

**Comment by anaamolnar** [comment]
Hello, @AmjadKhan2k18. Thanks for reporting! Unfortunately, I can't reproduce this issue. Could you please let me know if you are using the latest version of the mobile app available? Can you confirm you have sufficient native funds to perform the swap? Would you mind sending a short screen recording to see exactly how this occurs? Thank you.

**Comment by AmjadKhan2k18** [comment]
Hey @anaamolnar, Thanks for response

I added 20 MATIC to my wallet and tried now again to make sure I have sufficient funds

I am using latest version of metamask on android
here is 1Link API and Params I have sent 

[1inch]( https://api.1inch.io/v5.0/137/swap?fromTokenAddress=0xEeeeeEeeeEeEeeEeEeEeeEEEeeeeEeeeeeeeEEeE&toTokenAddress=0xc2132D05D31c914a87C6611C10748AEb04B58e8F&amount=1097300000000000000&fromAddress=0xab4c8a98bd030029cf08ae5198bd6a347c2e12ec&slippage=30
)

```
{
  "from": "0xab4c8a98bd030029cf08ae5198bd6a347c2e12ec",
  "to": "0x1111111254eeb25477b68fb85ed929f73a960582",
  "data": "0x12aa3caf000000000000000000000000cfd674f8731e801a4a15c1ae31770960e1afded1000000000000000000000000eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee000000000000000000000000c2132d05d31c914a87c6611c10748aeb04b58e8f000000000000000000000000cfd674f8731e801a4a15c1ae31770960e1afded1000000000000000000000000ab4c8a98bd030029cf08ae5198bd6a347c2e12ec0000000000000000000000000000000000000000000000000f3a648948094000000000000000000000000000000000000000000000000000000000000007c819000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001400000000000000000000000000000000000000000000000000000000000000160000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000c70000000000000000000000000000000000000000000000000000a900001a40410d500b1d8e8ef31e21c99d1db9a6444d3adf1270d0e30db00c200d500b1d8e8ef31e21c99d1db9a6444d3adf127055ff76bffc3cdd9d5fdbbc2ece4528ecce45047e6ae40711b8002dc6c055ff76bffc3cdd9d5fdbbc2ece4528ecce45047e1111111254eeb25477b68fb85ed929f73a960582000000000000000000000000000000000000000000000000000000000007c8190d500b1d8e8ef31e21c99d1db9a6444d3adf127000000000000000000000000000000000000000000000000000cfee7c08",
  "value": "1097300000000000000"
}
```

here are videos from Dapp & Metamask

https://github.com/MetaMask/metamask-mobile/assets/44894621/d501d8b5-a2b3-4983-a853-e24044cae02a

**Comment by anaamolnar** [comment]
Hey @AmjadKhan2k18. Thanks for the details. Could you let me know how you accessed the dapp? From the native phone browser? Can you please check if you are on the latest version of Metamask now and if the same occurs? Thank you!

**Comment by AmjadKhan2k18** [comment]
@anaamolnar Dapp is our mobile application 

I have accessed the dapp through WalletConnect and Yes I have latest Metamask android app installed

I tried with WalletConnect V2 and it's still same

same API work for TrustWallet without any issue

**Comment by AmjadKhan2k18** [comment]
the issue was in 1inch response `"value": "422181600000000",` 

value should be updated to toRadixString(16)
