### ISSUE TITLE
Update `Checkbox` component

### ISSUE THREAD

**Issue by georgewrmarshall** [MetaMask/metamask-mobile#6595]
Dependency: https://github.com/MetaMask/design-tokens/issues/484

### **Description**

Currently our `Checkbox` component is quite large. Make the appropriate updates according to the Figma design

### **Technical Details**

- Update component so `Checkbox` is an improved size
- Add new icon assets to Icon component 

### **Acceptance Criteria**

- Checkbox component has been updated according to design requirements
- New icon svg assets have been added to Icon component

### **References**
- Extension Checkbox ticket: https://github.com/MetaMask/metamask-extension/issues/15438
- Mobile Checkbox ticket: https://github.com/MetaMask/metamask-mobile/issues/6595
- [Notion tech sync document](https://www.notion.so/Technical-Sync-db6759fdb0bf4d39bf91e10517cee5f8?pvs=4)

**Comment by Akatori-Design** [comment]
@brianacnguyen 
Two new icons needed for the checkbox update
1. check-bold
2. minus-bold

SVG sprite
https://drive.google.com/file/d/1QwnjIns2xFtRvXBC4UWYB3gtkdJwBCpf/view?usp=drive_link
