### ISSUE TITLE
[Bug] `Unknown error`when rejecting an ERC721 Approve tx

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-mobile#6605]
**Describe the bug**
When Rejecting an Approve ERC721 transaction while having Customize transaction nonce deactivated, I got `Unknown error`.
This happened after this error https://github.com/MetaMask/metamask-mobile/issues/6604 appeared, which seems that it leaves MetaMask under a strange state.

**Screenshots**

https://github.com/MetaMask/metamask-mobile/assets/54408225/3094fade-205c-406d-8d95-86c6828d0b59

**To Reproduce**
_Steps to reproduce the behavior_
See video -- but need to find consistent steps

**Expected behavior**
No error should appear

**Smartphone (please complete the following information):**
 - Device: Pixel 6
 - OS: Android
 - App Version: 7.2.0

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by cortisiko** [comment]
I was unable to reproduce the original bug but I was able to reproduce another bug. When going through the approval flow for an ERC721 token, the approval button is disabled. The reason for this is that the custom spending cap modal does not appear.

see recording: http://recordit.co/DGRsQcYaS4 

To reproduce:
deploy an ERC721 
Mint the 721
attempt to approve the 721 and notice the bug.

**Comment by seaona** [comment]
thank you @cortisiko about the button being disabled, we opened an issue [here](https://github.com/MetaMask/metamask-mobile/issues/6654) and we have a PR ready for the fix

**Comment by seaona** [comment]
After this issue https://github.com/MetaMask/metamask-mobile/issues/6608 was fixed by [this PR](https://github.com/MetaMask/metamask-mobile/pull/6720/files#diff-a00fa937658e508f6da02d5b6e07f28e1601bd2317e40a5be549ba9ad20aa17dR446), the subsequent related issues have been fixed too. So this issue can be closed
