### ISSUE TITLE
[Bug] Reject Approve transaction from a dapp re-opens another Approve transaction

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-mobile#6607]
**Describe the bug**
It seems that MM entered into a weird state and wheneverI trigger an Approve transaction from a dapp and I Reject it, I see how another Approve transaction is opened. After I Reject the 2nd transaction, then the Approve is finally cancelled.

It seems that the first issue leaves MetaMask under a weird state.

**Screenshots**

https://github.com/MetaMask/metamask-mobile/assets/54408225/5b13070d-1b53-471f-be98-ef60f86d182a

**To Reproduce**
See video -- but need to find consistent steps

**Expected behavior**
Approve tx should be rejected at the 1st cancel.

**Smartphone (please complete the following information):**
 - Device: Pixel 6
 - OS: Android
 - App Version: `7.2.0`

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by cortisiko** [comment]
Confirming that this is an issue for me. The bug occurs when:
You have a fresh install of the app
You import a wallet
You go to a dapp (in my case I went to the test dapp)
You connect your wallet
You create a token
Then tap on "Approve"
Upon doing so, there is somewhat of a delay in opening the approval modal. 
Tapping on approve again triggers the approval modal
When tapping "reject" from the approval modal, another approval modal appears 🥴 

See [recording](http://recordit.co/UK2kjH4OgJ)

**Comment by seaona** [comment]
After [this issue was fixed](https://github.com/MetaMask/metamask-mobile/issues/6608) by [this PR](https://github.com/MetaMask/metamask-mobile/pull/6720/files#diff-a00fa937658e508f6da02d5b6e07f28e1601bd2317e40a5be549ba9ad20aa17dR446), the subsequent related issues have been fixed too. So this issue can be closed
