### ISSUE TITLE
[Bug] `undefined is not an object (evaluating num.negative)`

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-mobile#6608]
**Describe the bug**
I got the following error while trying a transaction from a dapp (ERC20 Approve / ERC20 Transfer):  `undefined is not an object (evaluating num.negative)`
It seems that the MetaMask entered into a weird state where several errors and undesired behaviours happen

**Screenshots**

https://github.com/MetaMask/metamask-mobile/assets/54408225/49182e6c-a16d-4fb9-9037-a39b490310ae

**To Reproduce**
See video -- but need to find consistent steps
Happens quite often when:
1. Deploy an ERC721
2. Mint an ERC721 token 
3. Revoke access 

**Expected behavior**
_A clear and concise description of what you expected to happen_

**Smartphone (please complete the following information):**
 - Device: Pixel 6
 - OS: Android 
 - App Version: 7.2.0

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by digiwand** [comment]
so far, I have been able to reproduce this bug by sending a legacy tx as well 

![Screenshot_1686846263](https://github.com/MetaMask/metamask-mobile/assets/20778143/870c7200-eac1-4690-9643-8fd7d1502df7)
![Screenshot_1686846351](https://github.com/MetaMask/metamask-mobile/assets/20778143/6378e823-8e01-40ce-9510-9c370ba54df1)

**Comment by cortisiko** [comment]
I was able to reproduce this issue. I noticed the bug occurs when you go to the test dapp and you:

- deploy an ERC20 token 
- attempt to approve a transaction but reject the transaction
- attempt to Transfer the ERC20
- notice approval modal appears. If you were to reject it, then the error appears. 

After trying a few times I can no longer reproduce consistently.

**Comment by seaona** [comment]
This issue has been fixed by this line of[ this PR](https://github.com/MetaMask/metamask-mobile/pull/6720/files#diff-a00fa937658e508f6da02d5b6e07f28e1601bd2317e40a5be549ba9ad20aa17dR446). Thanks for the great investigation @matthewwalsh0 !! The issue can be now closed
