### ISSUE TITLE
Walletconnect V2 Compatibility

### ISSUE THREAD

**Issue by frankfka** [MetaMask/metamask-mobile#6616]
### **Description**

Hello,

I see that WalletConnect V2 compatibility was added [here](https://github.com/MetaMask/metamask-mobile/issues/3957). However, the official WalletConnect demo: https://react-app.walletconnect.com/ does _not_ show Metamask as an available option.

Will Metamask be displayed by the time WalletConnect V1 is deprecated?

**Comment by alex-nax** [comment]
https://medium.com/walletconnect/weve-reset-the-clock-on-the-walletconnect-v1-0-shutdown-now-scheduled-for-june-28-2023-ead2d953b595 - here's written that 15th June was your deadline? Is it moved?

**Comment by fzavalia** [comment]
Being the 28th of June the sunset of WC1, can we expect iOS support before that date?

**Comment by anaamolnar** [comment]
Hello, @frankfka, @fzavalia, @alex-nax. We are excited to announce that the MetaMask Android app V7.0.1 now supports WalletConnect’s V2.0, offering enhanced functionality.
However, we are still pending App Store approval for the iOS app and we know this might cause some inconvenience to dapp developers. Rest assured, we are actively working with Apple to secure the app store approval as soon as possible.
