### ISSUE TITLE
Add the new shared header and origin pill to the wallet_watchAsset confirmation

### ISSUE THREAD

**Issue by bschorchit** [MetaMask/metamask-mobile#6620]
### Background
We're currently missing the account, network and origin information on the wallet_watchAsset confirmation. We want to re-use the new components in this confirmation to display those.

### Task
Similar as done here https://github.com/MetaMask/metamask-mobile/issues/5928, we should re-use the new header and origin pill components https://github.com/MetaMask/metamask-mobile/pull/5309 in the wallet_watchAsset confirmation.

The balance in the header should be the primary network token. 

### Repro Steps
1. Go to https://docs.metamask.io/openrpc-sidebar-support-two/wallet/reference/wallet_watchasset/
2. Click on “Send request”

**Comment by tibi77** [comment]
hey! the link that you provided does not work for me, @bschorchit 
Could you show me maybe another way i can reproduce it ?

**Comment by hilvmason** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Confirmations-Secure-UX-6245e6e2348677001213b8d2/issues/MetaMask/metamask-mobile/6620?planning-poker) with Zenhub @blackdevelopa @digiwand @jpuri @NiranjanaBinoy @seaona @segun

**Comment by bschorchit** [comment]
Closing as completed with https://github.com/MetaMask/metamask-mobile/pull/7261
