### ISSUE TITLE
[Bug] When I import a funded account on browserstack the account and balance is zero

### ISSUE THREAD

**Issue by davibroc** [MetaMask/metamask-mobile#6622]
**Describe the bug**
On for Android or iOS versions I noticed that when I import an account with the secure phrase and after that account balance is zero although I should see funds.  
Same thing happens if I create the account and import the private key and in this case I am not prompted to secure the account.
It reproduces on browserstack and local build as well with the emulator

Please note the following:

- If I upload 7.0.1 on my physical device I don't see the problem
- I am not sure with what version this started happening but the problem has been there for at least a few of weeks

**Screenshots**
<img width="277" alt="Screenshot 2023-06-15 at 3 44 01 PM" src="https://github.com/MetaMask/metamask-mobile/assets/6082863/5870bd33-697e-4a8b-ba46-ff6c005d05aa">

**To Reproduce**
1. Upload version 7.0.1 for Android and upload it to browserstack or build locally for the emulator
2. Install the app on any device import a funded account using the secret phrase
3. Look at the ETH balance and notice that in the wallet the balance is zero 
5. View the account on etherscan and you will see a balance

**Expected behavior**
The balance should be shown correctly

**Smartphone (please complete the following information):**
 - Device: Any
 - OS: Any
 - App Version - 7.0.1

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by NicolasMassart** [comment]
I believe this is due to a lack of the right API key that's not available on our local builds.
