### ISSUE TITLE
Update Label component font weight

### ISSUE THREAD

**Issue by georgewrmarshall** [MetaMask/metamask-mobile#6625]
### Description
Currently the `Label` component font weight is bold. We want to update it to medium

### Technical Details
- Update the `Label` component to use medium font weight using the appropriate design tokens

### Acceptance Criteria 
- `Label` font-weight has been update from bold to medium

**Comment by tibi77** [comment]
hey! @brianacnguyen I just saw that it s assigned to you. I m trying to get oriented. in the repo and this one seemed quite a low-hanging fruit, if you want I can close my PR.
 Sorry.... :'(

**Comment by georgewrmarshall** [comment]
Hey @tibi77, thanks for your contribution this issue has a dependency on a design token update

**Comment by tibi77** [comment]
thanks a lot @georgewrmarshall, did not know that
