### ISSUE TITLE
You have to press the login button twice.

### ISSUE THREAD

**Issue by MicahZoltu** [MetaMask/metamask-mobile#6633]
**Describe the bug**
On the login page, if the cursor is in the password entry box the "LOG IN" button doesn't work.  You have to first get the cursor out of the password entry box before you can press the LOG IN button.

**To Reproduce**
_Steps to reproduce the behavior_
1. Open MetaMask Mobile on Android.
2. Enter a password.
3. Touch LOG IN button.
4. Notice that nothing visible happens other than the cursor stops flashing in the password entry box.
5. Touch LOG IN button again.
6. Notice that you now log in.

**Expected behavior**
Upon entering my password, I can touch the log in button once and log in.

**Smartphone (please complete the following information):**
 - Device: Android
 - OS: 9
 - App Version: 6.6.0 (1114)

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by tibi77** [comment]
Opened a PR :)

**Comment by anaamolnar** [comment]
Hello, @MicahZoltu. Thanks for reporting! I will pass this on to the team.

**Comment by tibi77** [comment]
@anaamolnar I think my PR solved it
I m quite unsure how to ask for QA/PR review

**Comment by anaamolnar** [comment]
Hey, @hesterbruikman Can you help with checking the above PR? Thanks 😊

**Comment by hesterbruikman** [comment]
Thanks for logging the issue @MicahZoltu and creating the PR @tibi77. Would be a great improvement! Requested a a dev review. To be continued...

**Comment by leotm** [comment]
reopened, closed by
- https://github.com/MetaMask/metamask-mobile/pull/6663
