### ISSUE TITLE
Bug: ENS Offchain Resolution fails

### ISSUE THREAD

**Issue by z80dev** [MetaMask/metamask-mobile#6644]
**Describe the bug**
Lookup of ENS names using Offchain Resolution fails, lookup of the same names on desktop works as expected. Looks like it used to (or is supposed to) work: [PR](https://github.com/MetaMask/metamask-mobile/pull/5002)

**Screenshots**
![IMAGE 2023-06-19 15:33:20](https://github.com/MetaMask/metamask-mobile/assets/83730246/d76f7ff8-b2e9-4443-98a0-15f5ed3a6373)

**To Reproduce**
1. Open mobile metamask
2. Click on send
3. Type 'seoul.me.eth.id' as the recipient

**Expected behavior**
Lookup should resolve to an address

**Smartphone (please complete the following information):**
 - Device: iPhone 12
 - OS: Latest iOS
 - App Version [e.g. 1.0.0] - v6.3.0

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by z80dev** [comment]
any update on this❓🤨

**Comment by 70nyIT** [comment]
@z80dev so on mobile is not working, but yes on extension?
