### ISSUE TITLE
MetaMask Mobile iOS Release with WalletConnectV2 support

### ISSUE THREAD

**Issue by fzavalia** [MetaMask/metamask-mobile#6647]
Hey!

As far as I know, the version that supports WalletConnectV2 was released on Android but not on iOS, at least the app store still shows version 6.3.0 as the current.

Given that the 28th of this month WalletConnectV1 will be 💀 , can we expect the iOS release to hit the store before that date? Is the release being blocked by Apple or are there some unresolved issues on the iOS side?

Ty

**Comment by feririarte10** [comment]
WC 2.0 don't work yet, android and ios.

**Comment by muhammadsaddamnur** [comment]
I am also waiting for the release on iOS.

**Comment by imaksp** [comment]
even if they managed to make a app store release before 28th then switch chain might not work, as it is not working on current Android release (7.0.1), this will give bad experience to users.
See #6655 for details.

**Comment by anaamolnar** [comment]
Hello, @imaksp. Thanks for reaching out! We are excited to announce that the MetaMask Android app V7.0.1 now supports WalletConnect’s V2.0, offering enhanced functionality.
However, we are still pending App Store approval for the iOS app and we know this might cause some inconvenience to dapp developers. Rest assured; we are actively working with Apple to secure the app store approval as soon as possible.

**Comment by imaksp** [comment]
That's good to know, but also consider prioritizing mentioned switch chain issue with WC v2, it is also very important feature because mainnet has relatively higher gas fees & various custom networks with lower fees are now available.

**Comment by imaksp** [comment]
It looks like 7.0.1 is now available on app store, but it is still missing from this list/v2 cloud registry:
https://walletconnect.com/explorer?type=wallet&version=2

**Comment by adrianotadao** [comment]
> Hello, @imaksp. Thanks for reaching out! We are excited to announce that the MetaMask Android app V7.0.1 now supports WalletConnect’s V2.0, offering enhanced functionality. However, we are still pending App Store approval for the iOS app and we know this might cause some inconvenience to dapp developers. Rest assured; we are actively working with Apple to secure the app store approval as soon as possible.

Hey @anaamolnar, what is the status of the fix for ios + metamask login? This is still broken, right? I just tested version 7.0.1 and it didn't work 😢
