### ISSUE TITLE
[Bug] Approve button is always disabled for ERC721 tokens

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-mobile#6654]
**Describe the bug**
The Approve button for ERC721 tokens is always disabled

**Screenshots**

https://github.com/MetaMask/metamask-mobile/assets/54408225/ffd0d1f6-fef1-44c6-beb2-eb13b9beb6eb

**To Reproduce**
1. Go to test-dapp
2. Deploy an NFT contract
3. Mint a token
4. Click Approve
5. See how Approve button is always disabled

**Expected behavior**
Approve button should be enabled once gas estimation is ready

**Smartphone (please complete the following information):**
 - Device: Pixel 6
 - OS: Android
 - App Version: 7.2.0 / main

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by marctatham** [comment]
I'm still seeing this issue on Android 🙄 
**Device:** pixel 6 
**OS:** Android 15 

**Recording:** 
https://github.com/user-attachments/assets/7d2cb0f7-b346-4111-a59c-8572d6047b04
