### ISSUE TITLE
OAuth/Popup broken - not stale

### ISSUE THREAD

**Issue by tennox** [MetaMask/metamask-mobile#6658]
#2812 is still reprodicible and I cannot reopen the issue as suggested by the stale bot.

My app I needed it for was cancelled, so I don't personally care anymore about this, and if you don't think you want to solve it, so be it.
But it's not `stale` in the sense of not being relevant anymore.

**Comment by anaamolnar** [comment]
Hey, @tennox. Thanks for reporting! We have opened the issue again. Please don't hesitate to follow up or add any comments on the initial issue. I will close this one in favor of #2812. Thanks!
