### ISSUE TITLE
WalletConnect v2 requiredNamespaces  chains 

### ISSUE THREAD

**Issue by sapjax** [MetaMask/metamask-mobile#6670]
**Describe the bug**
the `chains` field in `requiredNamespaces` must be equal to the current active chain of Metamask mobile, otherwise, Metamask rejects the connection.
```
requiredNamespaces: {
      eip155: {
        methods: [
          'eth_sendTransaction',
          'eth_signTransaction',
          'personal_sign',
          'eth_signTypedData'
        ],
        chains: ['eip155:1'],  // this filed should not bind to the current active chain in Metamask
        events: ['chainChanged', 'accountsChanged']
      }
    }
```

**To Reproduce**
1. open https://react-app.walletconnect.com/
2. select a chain that is not equal to your Metamask active chain.
3. scan the QRCode with Metamask
4. check the console error in https://react-app.walletconnect.com/
5. ```{code : 5100 message : "Unsupported chains."}```

**Expected behavior**
It should be able to connect normally, and chains can specify multiple supported chains simultaneously.

**Smartphone :**
 - OS: Android
 - App Version v7.0.1(1126)

**Comment by anaamolnar** [comment]
Hello, @sapjax. Thanks for reporting! To ensure that everything works timely, WalletConnect helped MetaMask to support the v2.0 protocol before June 28th with a few changes. MetaMask doesn't have simultaneous multi-chain support despite migrating to WalletConnect V2. This is still compliant with CAIP-25 and the WalletConnect v2.0 protocol.
You are still able to call wallet_addEthereumChain and wallet_switchEthereumChain as before
So the UX will be the same, but the v2.0 protocol will be supported under the hood.
Let me know if I can clarify anything further. Thank you!

**Comment by sapjax** [comment]
> Hello, @sapjax. Thanks for reporting! To ensure that everything works timely, WalletConnect helped MetaMask to support the v2.0 protocol before June 28th with a few changes. MetaMask doesn't have simultaneous multi-chain support despite migrating to WalletConnect V2. This is still compliant with CAIP-25 and the WalletConnect v2.0 protocol. You are still able to call wallet_addEthereumChain and wallet_switchEthereumChain as before So the UX will be the same, but the v2.0 protocol will be supported under the hood. Let me know if I can clarify anything further. Thank you!

I got it, thanks!
Maybe it would be better to explain these situations in the release log.

**Comment by kecson** [comment]
> 

How to request `wallet_addEthereumChain ` and `wallet_switchEthereumChain `

**Comment by GabrielBuragev** [comment]
I was actually able to get things "working" by initializing the provider like so:

```ts
import WalletConnect from '@walletconnect/ethereum-provider';

const provider = await WalletConnect.init({
    chains: [1],
    optionalChains: chains,
    projectId: PROJECT_ID,
    optionalMethods: [
      'eth_sendTransaction',
      'wallet_switchEthereumChain',
      'wallet_watchAsset',
      'wallet_addEthereumChain',
    ],
    optionalEvents: ['accountsChanged', 'chainChanged', 'network', 'disconnect'],
    rpcMap: rpcList,
    showQrModal: true,
  });
  ```
  
Make sure you use `@walletconnect/ethereum-provider` version `2.8.4` and latest MetaMask Mobile version.

With this approach, you are able to switch between chains but only if you had them previously configured inside the MetaMask app. 
The `wallet_addEthereumChain` events are still broken so you cannot add new chains..

**Comment by christopherferreira9** [comment]
Hi all! Is this issue still applicable with the latest versions? We recently updated the WalletConnect SDK dependency which might fix this.

**Comment by christopherferreira9** [comment]
Hi all! We're going to close this issue due to inactivity. Please let us know if you want us to reopen it if it still applies.
