### ISSUE TITLE
Touchable opacity shadow does not consider border radius

### ISSUE THREAD

**Issue by tibi77** [MetaMask/metamask-mobile#6698]
**Describe the usability problem**
When clicking buttons in the app, the shadow(effect when the button is clicked) does not look like the shape of the button.

**Screenshots**
<img width="485" alt="image" src="https://github.com/MetaMask/metamask-mobile/assets/8665054/b8334b08-2065-4806-affc-df181173b3aa">

**Proposed behavior**
1. Open the wallet on android, long click on a button
2. See the issue
------------------------------------------------------------------------------------------------------

**Comment by anaamolnar** [comment]
Hello, @tibi77. Thanks for reporting! What device and firmware are you using? What Metramask version are you on? Is this a screenshot taken on a Macbook device? Thanks!

**Comment by tibi77** [comment]
<img width="447" alt="image" src="https://github.com/MetaMask/metamask-mobile/assets/8665054/a84b88a9-d538-4dcd-9d04-5eee55b76731">
device info ^
yes, macbook device
last version from main branch
