### ISSUE TITLE
Metamask iOS doesn't handle deep link parameters (WalletConnect v2)

### ISSUE THREAD

**Issue by maltsevoff** [MetaMask/metamask-mobile#6704]
### **Description**

On Metamask iOS version 7.0.1 doesn't work with WalletConnect Auth protocol and not respond to any redirected links. When will you turn on wc v2 support on iOS?

**Comment by pantaovay** [comment]
Any update on this issue?

**Comment by iPaulPro** [comment]
Yup completely broken. Guess it's time to switch to an alternative.

**Comment by maltsevoff** [comment]
Still doesn’t work. 

I’ll describe below steps to reproduce. 

versions: 
WalletConnectSwiftV2 - 1.6.8 
MetaMask iOS - 7.0.1 

Short code example to reproduce the issue. I create pair uri and pass it to metamask deep link as in docs. Then redirect to metamask. And nothing happens. Metamask opens but doesn’t respond to passed parameters. No error messages, no dialog screens, nothing. 

```swift
import Auth

let pairUri = try await Pair.instance.create()
self.pairUri = pairUri
try await Auth.instance.request(params, topic: pairUri.topic)

"metamask://wc?uri=\(pairUri.deeplinkUri)"

UIApplication.shared.open(url)
```

Also tried  `"https://metamask.app.link"`, nothing changed. 

Other wallets like Trust, Zeroin, Rainbow work fine with handling links. 
Metamask app works fine with scanning QR codes but not with handling links.

**Comment by maltsevoff** [comment]
@anaamolnar any updates about this?

**Comment by alexanderkhitev** [comment]
> Still doesn’t work.
> 
> I’ll describe below steps to reproduce.
> 
> versions: WalletConnectSwiftV2 - 1.6.8 MetaMask iOS - 7.0.1
> 
> Short code example to reproduce the issue. I create pair uri and pass it to metamask deep link as in docs. Then redirect to metamask. And nothing happens. Metamask opens but doesn’t respond to passed parameters. No error messages, no dialog screens, nothing.
> 
> ```swift
> import Auth
> 
> let pairUri = try await Pair.instance.create()
> self.pairUri = pairUri
> try await Auth.instance.request(params, topic: pairUri.topic)
> 
> "metamask://wc?uri=\(pairUri.deeplinkUri)"
> 
> UIApplication.shared.open(url)
> ```
> 
> Also tried  `"https://metamask.app.link"`, nothing changed.
> 
> Other wallets like Trust, Zeroin, Rainbow work fine with handling links. Metamask app works fine with scanning QR codes but not with handling links.

Hello guys, any news/updates/solutions? Thanks!

**Comment by SmartArray** [comment]
Can you try my PR? https://github.com/MetaMask/metamask-mobile/pull/6564

**Comment by dibuenio** [comment]
Hi, guys, when are you will solve this problem?.......

**Comment by pantaovay** [comment]
> This is not issue with Metamask or WalletConnect, it is a side effect of the iOS operating system. WalletConnect explains how to deal with the issue here:
> 
> https://docs.walletconnect.com/2.0/ios/guides/mobile-linking#ios-app-link-constraints

This issue is not related to the doc you mentioned. It's purly metamask's bug

**Comment by maltsevoff** [comment]
> This is not issue with Metamask or WalletConnect, it is a side effect of the iOS operating system. WalletConnect explains how to deal with the issue here:
> https://docs.walletconnect.com/2.0/ios/guides/mobile-linking#ios-app-link-constraints

This is a MetaMask error only, just check code above which strictly follows wallet connect's docs.

**Comment by andreahaku** [comment]
Hi, MetaMask supports a subset of WCv2 features and Auth protocol is not part of it. That's why it's not working.
Thanks for reporting.

**Comment by glitch-txs** [comment]
HI @andreahaku, are the any plans for MetaMask to support this in the near future?

**Comment by marctatham** [comment]
This is pretty disappointing
