### ISSUE TITLE
 MetaMask redirect's to the Dapp before sending the chainChanged event

### ISSUE THREAD

**Issue by nhatnguyen95** [MetaMask/metamask-mobile#6706]
**Describe the bug**
I am using @walletconnect/modal-react-native": "1.0.0-rc.2, when I try to connect to MetaMask and the chainId different with the chainId of activating network. chainChanged event didn't fire after returning to my app on Android (it works on iOS) so I can't know user has chosen the right network or not on Android.

**To Reproduce**
1. Open Metamask and active Polygon network
2. Connect with chainId of ETH(1) using Metamask over Wallet connect V2 modal
3. Click on Connect button and return to Dapp
4. chainChanged event doesn't notify on Android (It notifies on iOS)

**Expected behavior**
`chainChanged` should notify to the DApp on Android

**Smartphone:**
 - Device: Galaxy S10+
 - OS: Android 11
 - App Version: 7.0.1

I also created a discussion to ask Wallet connect team here: https://github.com/orgs/WalletConnect/discussions/2773

**Comment by imaksp** [comment]
I think It is because chain cannot be changed to dapp chain (if different) in metmask using RPC call, 
because currently wallet_switchEthereumChain is not working with WC v2. 
Are sure that chain is changed to chain which required by app inside metamask app?
& if chain cannot be changed then event is out of question.

check #6655 for issue details.

**Comment by nhatnguyen95** [comment]
> 
@imaksp 
Here is my code:
```const {isConnected, provider} = useWalletConnectModal();
useEffect(() => {
    const registerEvents = () => {
      provider?.on('chainChanged', (chainId: string) => {
        setChainIdConnected(parseInt(chainId));
      });
      provider?.on('connect', ({chainId}) => {
        setChainIdConnected(parseInt(chainId));
      });
    };
    registerEvents();
  }, [provider]);
  ```
  I just call to connect function with chainId and wait for these events when return to app, on iOS it will notify `chainChanged` event if chainId to connect different with the chainId selecting in Metamask, `but not for Android`. I 've worked with Wallet connect team and they have responded to me: `MetaMask redirect's to the dapp before sending the chainChanged event`.

**Comment by imaksp** [comment]
Ok for getting current chain initially you need to send eth_chainId (getChai) method & if it is returning wrong/previous chain id then it means wallet app chain is different & not changed. 
& until 6655 is fixed, this issue will stay.

**Comment by nhatnguyen95** [comment]
@imaksp it returned the chainId I called in `connect` function, (my expectation is current active chainId in Metamask). But after connected to Metamask successfully, I open Metamask and return to app again, "chainChanged" event is notified. It seems some Metamask functions is not called because it is suspended when open Dapp's deep link, then it will continue to execute functions when Metamask resume

**Comment by imaksp** [comment]
Ok if eth_chainId method is returning the expected id, you don't need to depend on chain changed event, just call eth_chainId when you need to match network.

**Comment by nhatnguyen95** [comment]
@imaksp no it returned wrong chainId, I expect it is chainId of active network in Metamask but now it isn't . So this is still an issue on Android

**Comment by imaksp** [comment]
Ok, can you check again. with latest (2.8.4) [walletconnect](https://github.com/WalletConnect/walletconnect-monorepo/releases/tag/2.8.4) version, it fixed switch chain issue. not checked eth_chainId & chainChanged event yet.

**Comment by nhatnguyenbp** [comment]
@imaksp this is still an issue in `@walletconnect/modal-react-native:: "1.0.0-rc.3"` with the latest 2.8.4 wallet connect core.

**Comment by imaksp** [comment]
has anyone checked this with MM 7.4 version, it has some fixes related to switch chain.

**Comment by Thormeard** [comment]
@imaksp Yes I tried yesterday yesterday with latest (7.4) MetaMask app and `@walletconnect/modal-react-native:: "1.0.0-rc.10".` on IOS
