### ISSUE TITLE
metamask app browser use " iframe src blob url "  not loading content

### ISSUE THREAD

**Issue by vic-x** [MetaMask/metamask-mobile#6709]
Description
Description: Metamask keeps popping up a warning message saying: "This website has been blocked from automatically opening an external application"

Open https://charting-library.tradingview-widget.com/ in metamask app browser

Is there any solution for such a problem?

**Comment by MapleDev423** [comment]
Same problem on my side. @vic-x   
Did you figure out the issue?

**Comment by anaamolnar** [comment]
I am closing this in favor of #6415.

**Comment by geraldchen890806** [comment]
Decentralised app browser loading error. Chart fails to load in wallet apps like MetaMask, Trust & Phantom. Enable the iframe_loading_compatibility_mode [featureset](https://www.tradingview.com/charting-library-docs/latest/customization/Featuresets) to enable compatibility with these browsers.
