### ISSUE TITLE
Metamask mobile 7.1.0 give weird chainid errors

### ISSUE THREAD

**Issue by hixus** [MetaMask/metamask-mobile#6710]
**Describe the bug**
After updating Metamask mobile 7.1.0 give weird chainid errors when calling _signTypedData `MetaMask - RPC Error: Provided chainId "137" must match the active chainId "311"`.  

Metamask mentions 137 and our dapp requests 137 (polygon) but not sure where 311 is coming from.

With Mubai version we got `MetaMask - RPC Error: Provided chainId "80001" must match the active chainId "524289"`.

Metamask 7.0.1 worked fine. This is WalletConnect2 based provider (tester notified that WalletConnect1 is also broken in metamask 7.1.0).

**Expected behavior**
Should sign the same as metamask 7.0.1.

**Smartphone (please complete the following information):**
 - Pixel 6A
 - Android 13
 - App Version 7.1.0

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users? 
- Is this tech debt?

**Comment by nschwermann** [comment]
Same issue here using cronos and cronos testnet chainid 25 and 338 
This bug has rendered our app unusable on metamask mobile, I hope you aren't pushing to ios as well.

**Comment by kr1p70n1c** [comment]
This used to work.  Seems to be issue that existed on the extension about 2 years ago: when dapps pass a non-hex string for chainId in signTypedData calls, it breaks.

Hope there is a fix soon!

**Comment by YakovL** [comment]
A small note, probably obvious for many: (311)_10 = (137)_16, (524289)_10 = (80001)_16

**Comment by nguyenhoaidanh** [comment]
same issues. a lot of users meet this bug, Hope there is a fix soon! 🙏

**Comment by tommasini** [comment]
Thanks a lot for reporting!

We addressed this problem on the 7.2.0 version with this [PR](https://github.com/MetaMask/metamask-mobile/pull/6712). 7.2.0 will start to be available later this week on Android and, next week on IOS.
