### ISSUE TITLE
`peer.metadata.icons` returns empty array

### ISSUE THREAD

**Issue by rohanharikr** [MetaMask/metamask-mobile#6713]
Not sure if this is an issue that needs to be opened at walletconnect repo - feel free to close otherwise. This was working before with iOS metamask 6.3.0 + walletconnect v1 (working = an icon url of metamask was being returned in `icons`)

**Describe the bug**
`peer.metadata` returns empty `icons` array
```
"peer": {
    "publicKey": "22b1d00cfdd845a0872e500cad9e138101b61c30e4716f59c262481a58c4e953",
    "metadata": {
      "name": "MetaMask Wallet",
      "description": "MetaMask Wallet Integration",
      "url": "https://metamask.io/",
      "icons": []
    }
  }
```

**To Reproduce**
1. Go to https://lab-walletconnect-modal.pages.dev/with-sign-api/html
2. Click on Connect
3. Scan QR with iOS metamask mobile
4. `peer.metadata.icons` array is empty

**Expected behavior**
`peer.metadata.icons` to have url of metamask icon.

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by anaamolnar** [comment]
Hello, @rohanharikr. Thanks for reporting! Apologies for the long time it took me to get back to you. Could you try this with the latest version (7.3.0) and let me know if you still experience the issue? Thank you!

**Comment by rohanharikr** [comment]
Hey @anaamolnar, no worries - thank you for the response. Looks like the issue still persists with iOS Metamask v7.3.0
```
"peer": {
    "publicKey": "81ad91a25a07ead613f2c0c7e7c722403755fac1769d405c167971412b639330",
    "metadata": {
      "name": "MetaMask Wallet",
      "description": "MetaMask Wallet Integration",
      "url": "https://metamask.io/",
      "icons": [] // empty :(
    }
  }
```
