### ISSUE TITLE
Internal Error : {"code": -32603, "message": "Internal error"}

### ISSUE THREAD

**Issue by jobinabraham** [MetaMask/metamask-mobile#6715]
**Describe the bug**

Hey Community...Trying to migrate Walletconnect v1 react-native dapp implementation to walletconnect v2 in my react-native application. When trying to migrate "sendTransation" call from V1 to "provider.request" in V2, getting JSON-RPC error from metamask. The v1 version is working correctly so I am assuming its not an issue with metamask. No params have changed just the function. It seems the maxFee and maxPriorityFee are not being considered. Please help me out.
`import {
WalletConnectModal,
useWalletConnectModal,
} from '@walletconnect/modal-react-native';
const connector = useWalletConnectModal();

//----------V1 Version start--------------------//
connector.sendTransaction({
data: encodedData,
from: account,
to: tokenAddress,
nonce,
maxFee: 1573479400382,
maxPriorityFee: 115446958670,
})
//----------V1 Version End--------------------//
//----------V2 Version Start------------------//
connector?.provider
?.request({
method: 'eth_sendTransaction',
params: [{
data: encodedData,
from: account,
to: tokenAddress,
nonce,
maxFee: 1573479400382,
maxPriorityFee: 115446958670,
},
],
})
//----------V2 Version End--------------------//

Error from Metamask: {"code": -32603, "message": "Internal error"}`

WalletConnect Modal SDK version
1.0.0-rc.2

**Screenshots**
![Screenshot_20230626-190946_MetaMask (1)](https://github.com/WalletConnect/modal-react-native/assets/9764162/e83ce74f-c17f-4696-a110-6a2e105850d2)
![Screenshot_20230626-190959_MetaMask (1)](https://github.com/WalletConnect/modal-react-native/assets/9764162/7cd5dccd-93b2-4a1b-aa0e-e00a0d9723cc)

**Expected behavior**
Transaction should successfully complete

**Smartphone (please complete the following information):**
 - Device: [e.g. OnePlus]
 - OS: Android
 - App Version : 7.10
 

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**
Very critical

**Comment by jobinabraham** [comment]
![Screenshot_2023-06-28-12-39-33-36_3ce871bb60cb313382b75690e63e41d0](https://github.com/MetaMask/metamask-mobile/assets/9764162/edb40875-0ddb-4bb4-9072-e951029e0cef)
![Screenshot_2023-06-28-12-39-27-56_3ce871bb60cb313382b75690e63e41d0](https://github.com/MetaMask/metamask-mobile/assets/9764162/80e17c56-3a4e-438d-a01d-1e2636892a98)

**Comment by jobinabraham** [comment]
@anaamolnar Please check this

**Comment by hixus** [comment]
Hit the same issue.  When calling signTypedData with wc2 on MetaMask Android 7.1.0 dapp logs produce {"code": -32603, "message": "Internal error"} and metamask opens but does not open signin modal. MetaMask Android 7.0.1 worked fine.

**Comment by daniiba** [comment]
Getting the same error when using metamask and calling this
`const typedSignature = await web3Provider.send('eth_signTypedData', [address, JSON.stringify(typedData)]);`

**Comment by jobinabraham** [comment]
Anything on this?

**Comment by jobinabraham** [comment]
@equalogix The error seems to be that somehow metamask is not able to read/calculate the proper gas limit. If I do initiate the transaction via WC->Metamask and manually alter the gas limit, the transaction goes through. So seems some issue with gas limit calculation maybe. Also, can you check if the maxFee & maxPriorityFee that I am sending are the correct parameters. Attaching the screen recording of the error on metamask mobile.

 Following is the eth request I am seding.
`      connector?.provider
        ?.request({
          method: 'eth_sendTransaction',
          //[
          params: [
            {
              data: encodedData,
              from: account,
              to: tokenAddress,
              nonce,
              maxFee: 1573479400382,
              maxPriorityFee: 115446958670,
            },
          ],
          // ],
        })`


https://github.com/MetaMask/metamask-mobile/assets/9764162/6e6a974a-6234-4615-a84c-ed7acdc46239

**Comment by syamsoul** [comment]
i'm using web3.js with metamask mobile app, but failed to call both `call` and `send` method.. it return `-32603` code error... 

but on desktop browser working fine.... what actually the problem is?
