### ISSUE TITLE
Transactions Failing: L.nonce.replace is not a function

### ISSUE THREAD

**Issue by jobinabraham** [MetaMask/metamask-mobile#6716]
**Describe the bug**
After updating the metamask app to version 7.1.0, all transactions are failing with error as show in screenshot

**Screenshots**
![Screenshot_2023-06-28-16-19-56-89_3ce871bb60cb313382b75690e63e41d0](https://github.com/MetaMask/metamask-mobile/assets/9764162/2b5def6b-1494-4b05-bddd-36984a344ae5)
![Screenshot_2023-06-28-16-18-36-05_3ce871bb60cb313382b75690e63e41d0](https://github.com/MetaMask/metamask-mobile/assets/9764162/1812e81f-0aaa-4b3b-8761-7a847df1fd4b)

**To Reproduce**
Check this transaction:

https://mumbai.polygonscan.com/tx/0x4c3e98c68b437e53d0428680fe71c7af3ceb4abe9352d0c64925e69ed5f91dd2

**Expected behavior**
_A clear and concise description of what you expected to happen_

**Smartphone (please complete the following information):**
 - Device: OnePlus
 - OS: Android
 - App Version : 7.1.0

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**
Very Critical

**Comment by anaamolnar** [comment]
Hey, @jobinabraham. Thanks for reporting! Could you please provide more details and the steps to reproduce this issue, the dapp, etc. ? Did this occur after clicking confirm? Thanks!
