### ISSUE TITLE
Rejecting signing a message throws Internal error

### ISSUE THREAD

**Issue by mqklin** [MetaMask/metamask-mobile#6733]
**Describe the bug**
Rejecting signing a message in a dApp connected with WC2 iOS MetaMask throws `"code": -32603, "message": "Internal error"`:
![image](https://github.com/MetaMask/metamask-mobile/assets/9456433/a43fa785-5cbc-43fb-b81b-2b31a272a295)

**Expected behavior**
Should throw something like "User rejected signing a message"

**Smartphone (please complete the following information):**
 - Device: iPhone 12 mini
 - OS: iOS 16.5.1
 - App Version: 7.0.1

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by anaamolnar** [comment]
Hello, @mqklin. Thanks for reporting! Could you please try to reproduce this on the latest version available and see if you still experience the issue? Thank you!

**Comment by mqklin** [comment]
hey @anaamolnar 
confirm `UserRejectedRequestError: User rejected the request.`
