### ISSUE TITLE
Wrong place to get title from using WC2

### ISSUE THREAD

**Issue by mqklin** [MetaMask/metamask-mobile#6734]
**Describe the bug**
When connecting with WC2, this modal appears: 
![image](https://github.com/MetaMask/metamask-mobile/assets/9456433/d7b1fdcb-83ab-4707-8359-6fc9e34d3e01)

I've checked how Uniswap works, and saw that you take title from `<meta name="description" content="#TITLE#">` head tag. Which is not correct, as you should take it from page `title` tag.

**Expected behavior**
Title should be taken from `title` HTML tag.

**Smartphone (please complete the following information):**
- Device: iPhone 12 mini
- OS: iOS 16.5.1
- App Version: 7.0.1

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by anaamolnar** [comment]
Hello, @mqklin. Thanks for reporting! Could you please let me know if you still experience this issue in the latest version? Thanks!

**Comment by mqklin** [comment]
hey @anaamolnar 
I can't get out of spinner state for some reason, so can't even scan a QR code to check. 
![telegram-cloud-photo-size-2-5321478606347685021-y](https://github.com/MetaMask/metamask-mobile/assets/9456433/1f4faa53-8b13-40ea-8422-d9fc4ea57cdf)

![telegram-cloud-photo-size-2-5321478606347685020-y](https://github.com/MetaMask/metamask-mobile/assets/9456433/eb327f6f-48e3-4198-bd5e-bb0713325d1b)

**Comment by mqklin** [comment]
This is not fixed.

**Comment by mqklin** [comment]
Closing the issue, seems like it's fixed in some newest version.
