### ISSUE TITLE
Sometime signMessage doesn't trigger a popup

### ISSUE THREAD

**Issue by mqklin** [MetaMask/metamask-mobile#6736]
**Describe the bug**
Sometime signMessage doesn't trigger a popup in MM iOS app to sign a message

**To Reproduce**
_Steps to reproduce the behavior_
1. Call signMessage several times

**Expected behavior**
signMessage should trigger popup modal every time it gets called

**Smartphone (please complete the following information):**
- Device: iPhone 12 mini
- OS: iOS 16.5.1
- App Version: 7.0.1

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by iPaulPro** [comment]
It no longer works for me, at all. Reinstalled, removed WC sessions, I've tried everything. The app is completely broken.

**Comment by Tsirov** [comment]
I am having the same issue steps to reproduce you can open [https://opensea.io/](url) from mobile phone.
1. Go to 'Connect Wallet`.
2. Select `Walletconnect`.
3.Select `Metamask` and after connect with the current account you have been redirect again to opensea
4. Sellec button 'Accept and sign' form the modal after that choose `Metamask` to sign messsage
  Expected behavior
   After opening metamask should trigger popup for sign message
   
   Actual behavior
   Only metamask is opening without trigger popup for sign message

**Comment by anaamolnar** [comment]
Hello, @mqklin @iPaulPro @Tsirov Thanks for the report and details. Do you encounter the same issue with the latest version of the app? Thank you!

**Comment by mqklin** [comment]
hey @anaamolnar 
No, now I encounter `Error: could not coalesce error (error={ "code": 1, "message": "Invalid Id" }` for EVERY trying to sign a message :D Seems like it's completely broken

**Comment by anaamolnar** [comment]
Hey, @mqklin. Can you please confirm you are using the latest version and still experiencing this? Are you trying to initiate the connection from Safari?

**Comment by mqklin** [comment]
Hey @anaamolnar . When I open MetaMask, I see this: nothing happens, just infinite loader.
<details>
<summary>Screenshot</summary>

![image](https://github.com/MetaMask/metamask-mobile/assets/9456433/8eec60ad-7869-4890-8a56-b3157ebbc7d1)

</details>

Also there is an error in Transactions tab:
<details>
<summary>Screenshot</summary>

![image](https://github.com/MetaMask/metamask-mobile/assets/9456433/44413e40-1f97-43d5-8deb-9f9b9e3407ce)

</details>

MetaMask is totally unworkable for me.

**Comment by mqklin** [comment]
Closing the issue, seems like it's fixed in some newest version.

**Comment by Sabriel1984** [comment]
I have the same issue - eth_sendTransaction ends with: 

onSessionRequestResponse SessionRequestResponse(topic=73e8b38daa81df141fd0cef805fc0ea877b2a122e0b3a987d0d252f3b8589e09, chainId=eip155:11155111, method=eth_sendTransaction, result=JsonRpcError(id=1718966885359214, code=1, message=Invalid Id)) 

when I use metamask - it looks like a kind of regression in last metamask versions - currently we're not able to send transactions using this wallet. From the other side, when we send the same transaction (we have WalletConnect library to support different wallets) via DeFi wallet it works perfectly. I have the same error on both iOS and Android - and it's a kind of release blocking issue for us.
