### ISSUE TITLE
Add metrics for Blockaid settings when it's turned on/off

### ISSUE THREAD

**Issue by segun** [MetaMask/metamask-mobile#6760]
### Background
We want to update our metric scheme to capture the adoption of this feature so we're able confidently iterate over and improve this feature.

### Acceptance Criterias
1. Create a new user profile property (more info [here](https://help.mixpanel.com/hc/en-us/articles/115004501966#user-profile-properties)) called `security_providers`. This property should be a type list property (more info [here](https://help.mixpanel.com/hc/en-us/articles/115004547063-Properties-Supported-Data-Types#list). This was done on extension here, for reference: https://github.com/MetaMask/metamask-extension/pull/17688
1.a. This property should receive the value `blockaid` if the user has enabled the under Settings > Experimental. 
1.b. If the user turns off the transactions security provider feature under Settings > Experimental, the user profile property `security_provider` should be updated to remove the `blockaid` value from it.

2. Whenever the user enables or disables this feature, we should also trigger a new event named `Settings Updated` with a property `security_alerts_enabled` with the value `true` if the user has enabled it or with the value `false` if user has disabled it. 

### References
Similar work is being done on extension here: https://github.com/MetaMask/MetaMask-planning/issues/527

**Comment by bschorchit** [comment]
This might be already be partially implemented - we should check what might have been already implemented or not

**Comment by bschorchit** [comment]
Re-opening as the PR was reverted
