### ISSUE TITLE
[Android BUG]Two minor versions of 7.x that crashed every time I upgraded. View: ActivitvView TypeError: undefined is not an object(evaluating e.toLowerCase)

### ISSUE THREAD

**Issue by crytoplus** [MetaMask/metamask-mobile#6771]
**Describe the bug**
 **[Android 13]Two minor versions of 7.x that crashed every time I upgraded.** 
 ### `I've had it happen to me 2 times now, and I'm going to crash each time I manually import dozens of wallets. You guys are so disappointing.`
### `Metamask earns so many transaction fees, I hope you do more things that are beneficial to users, please do a complete upgrade test, testing is important, testing is important, testing is important !!!!`

**Screenshots**
![Metamask Bug](https://github.com/MetaMask/metamask-mobile/assets/113655354/f20b63c0-2903-48af-b3f3-8556aa91f671)

**To Reproduce**
just upgrade then crashed.
**Expected behavior**
**Smartphone (please complete the following information):**

 - Device: Redmi K40Pro
 - OS: Android
 - App Version：
 **1. from 7.0 -> 7.1 crashed. uninstall it and install 7.1**
 **2. from 7.1 -> 7.2 crashed. uninstall it and install 7.2**

#  There's definitely something wrong with your upgrade compatibility, it crashes every time I upgrade!

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by anaamolnar** [comment]
Hey. @crytoplus. Thanks for reporting! Our team is investigating this issue but hasn't found the root cause. Please let us know if you think of anything specific you noticed before this happened or can reproduce it on another device.

**Comment by tommasini** [comment]
Hey, @crytoplus, thanks for reporting, did you update it the mobile app on the play store?

**Comment by plasmacorral** [comment]
Thanks for the report, sorry for the difficulty.  When you say: 

> manually import dozens of wallets

Can you please say more about that?  Are you going through initial setup and importing an existing Secret Recovery Phrase (SRP), and then later importing multiple private keys individually?  Or importing an existing SRP that has dozens of accounts with assets available to them?
