### ISSUE TITLE
[Bug] `MetaMask Tx Signature: Unknown problem` when Approve an ERC20/ERC721

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-mobile#6774]
**Describe the bug**
After deploying an ERC20/ERC721 token I've hit the Approve button and got into the following error: `MetaMask Tx Signature: Unknown problem`

**Screenshots**

![image](https://github.com/MetaMask/metamask-mobile/assets/54408225/0a9ddaa2-0b3a-4b3f-85c8-bfc023e59689)

**To Reproduce**
Further investigation is needed as the issue is hard to repro (I can only reproduce it the first time I hit Approve after a fresh build). Some hints:
- It was the first time I tried an Approve after building MM from scratch
- After closing the popup, everything worked normally again
- I could perform subsequent Approves without error

**Expected behavior**
No error should happen

**Smartphone (please complete the following information):**
 - Device: Pixel 6
 - OS: Android
 - App Version: current main (that would be 7.4.0, unsure if in other versions)

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by seaona** [comment]
@bschorchit not sure if this belongs to Confirmations UX or Systems. 
It needs further investigation in order to be able to repro consistently

**Comment by bschorchit** [comment]
I've set this as sev3 as it's hard to reproduce and not persistent - if user tries again, it works.

**Comment by seaona** [comment]
I cannot seem to repro this behaviour anymore @vinistevam after this PR was merged https://github.com/MetaMask/metamask-mobile/pull/6838. I close the issue
