### ISSUE TITLE
Issue with WalletConnect on MetaMask iOS App Versions 7.0.1 and 7.2.0

### ISSUE THREAD

**Issue by geraldchen890806** [MetaMask/metamask-mobile#6780]
I've encountered an issue with the WalletConnect functionality in the MetaMask iOS application after updating to versions 7.0.1 and 7.2.0. I've found that both versions of WalletConnect (V1 and V2) are not working as expected.

For instance, when attempting to use V1 or V2 in dYdX, the QR code scanning function doesn't elicit any response. This problem has significantly hindered the usability of the application, and I'm hoping to see a resolution soon.

Please let me know if you need more information to address this issue. Thanks.

**Comment by kuochsia** [comment]
Using Walletconnect2, even with the deeplink, Metamask seems to not respond on accepting a session while explicitly send a response on user rejection. Could someone fix it please?

**Comment by christopherferreira9** [comment]
Hi @kuochsia @geraldchen890806 ! I'm sorry we haven't managed to look at this issue before, is this issue still applicable?

**Comment by christopherferreira9** [comment]
HI all! I'm going to close this issue due to inactivity. Please feel free to open a new issue at any time.
