### ISSUE TITLE
Android Metamask app doesn't show connect dialog with WalletConnect V2 Dapp  

### ISSUE THREAD

**Issue by SashaMazurProger** [MetaMask/metamask-mobile#6783]
**Describe the bug**

Metamask mobile does not prompt you to connect when navigating from a dApp using walletconnectkit-android (could be others?) like it used to before.

https://github.com/pink-room/walletconnectkit-android/issues/29
When will WalletConnect V2 be fully supported with intent handling in Android Metamask?

**To Reproduce**

1. Import https://github.com/pink-room/walletconnectkit-android
2. Run dApp sample
3. Click on Connect Wallet
4. Wait for it to navigate you to the MM application
5. No connect prompt
6. Expected behavior
7. It should prompt you to connect, but it does not.

**Smartphone:**

- Device: Samsung S10 Plus
- OS: Android 12
- App Version 7.2.0

**Comment by anaamolnar** [comment]
Hey, @SashaMazurProger. Thanks for your report! Please update to 7.3.0 and let me know if you still experience this issue. Please tag me here in the thread if you still need help with the issue; otherwise, I will probably not see your message. Thanks for your patience!
