### ISSUE TITLE
Cannot open the token chart details when the app is running on landscape on iPad

### ISSUE THREAD

**Issue by davibroc** [MetaMask/metamask-mobile#6788]
**Describe the bug**
When iPad is on landscape mode I cannot open the token chart details. From the attached video notice the presence of the drawer overlay although the drawer is not actionable

**Screenshots**

https://github.com/MetaMask/metamask-mobile/assets/6082863/e42e74c6-8d26-4ad4-a107-4b9dbd6a6226

**To Reproduce**
1. Run the app on iPad mini
2. Rotate it to landscape
3. Click on the ETH token
4. See that the chart details won't open

**Expected behavior**
I am able to view the ETH chart in landscape mode

**Smartphone (please complete the following information):**
 - Device: iPad
 - OS: any
 - App Version 7.1.0

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by wachunei** [comment]
A potential solution in case we confirm the Drawer view will no longer be used is to remove it from `MainNavigator.js`

```diff
diff --git a/app/components/Nav/Main/MainNavigator.js b/app/components/Nav/Main/MainNavigator.js
index 73d412210..60473d38e 100644
--- a/app/components/Nav/Main/MainNavigator.js
+++ b/app/components/Nav/Main/MainNavigator.js
@@ -402,8 +402,6 @@ const HomeTabs = () => {
   }, []);
 
   return (
-    <DrawerContext.Provider value={{ drawerRef }}>
-      <Drawer ref={drawerRef}>
     <Tab.Navigator
       initialRouteName={Routes.WALLET.HOME}
       tabBar={({ state, descriptors, navigation }) =>
@@ -443,8 +441,6 @@ const HomeTabs = () => {
         component={SettingsFlow}
       />
     </Tab.Navigator>
-      </Drawer>
-    </DrawerContext.Provider>
   );
 };
 

```
