### ISSUE TITLE
[Bug] QA builds for ios and Android throws error ` ViewPropTypes will be removed from React Native, along with all other PropTypes. We recommend that you migrate away from PropTypes and switch to a type system like TypeScript`

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-mobile#6791]
**Describe the bug**
Whenever doing a qa build for android or ios we can see the following error in the `yarn watch` console: 
` ERROR  ViewPropTypes will be removed from React Native, along with all other PropTypes. We recommend that you migrate away from PropTypes and switch to a type system like TypeScript. If you need to continue using ViewPropTypes, migrate to the 'deprecated-react-native-prop-types' package.`

**Screenshots**

![image](https://github.com/MetaMask/metamask-mobile/assets/54408225/089d53c0-fbf7-43f1-b928-cacd4a180357)

**To Reproduce**
_Steps to reproduce the behavior_
1. Start a qa build `yarn start:android:qa`
2. Start `yarn watch`
3. Initialize metamask

**Expected behavior**
No error should appear

**Smartphone (please complete the following information):**
 - Device: Pixel 6
 - OS: Android
 - App Version: started seeing this a couple of days ago. [See thread](https://consensys.slack.com/archives/C02U025CVU4/p1688996794769399)

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by tommasini** [comment]
It's doing an infinite loop when I ran `yarn start:ios:qa`

Some of the logs are:

`
CompileC /Users/tomassantos/Documents/metamask-mobile/ios/build/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/RNSVG.build/Objects-normal/arm64/RNSVGLinearGradientManager.o /Users/tomassantos/Documents/metamask-mobile/node_modules/react-native-svg/apple/ViewManagers/RNSVGLinearGradientManager.m normal arm64 objective-c com.apple.compilers.llvm.clang.1_0.compiler (in target 'RNSVG' from project 'Pods')
    cd /Users/tomassantos/Documents/metamask-mobile/ios/Pods
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x objective-c -target arm64-apple-ios11.0-simulator -fmessage-length\=137 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit\=0 -fcolor-diagnostics -std\=gnu11 -fobjc-arc -fobjc-weak -fmodules -fmodules-cache-path\=/Users/tomassantos/Documents/metamask-mobile/ios/build/ModuleCache.noindex -fmodules-prune-interval\=86400 -fmodules-prune-after\=345600 -fbuild-session-file\=/Users/tomassantos/Documents/metamask-mobile/ios/build/ModuleCache.noindex/Session.modulevalidation -fmodules-validate-once-per-build-session -Wnon-modular-include-in-framework-module -Werror\=non-modular-include-in-framework-module -Wno-trigraphs -fpascal-strings -O0 -fno-common -Wno-missing-field-initializers -Wno-missing-prototypes -Werror\=return-type -Wdocumentation -Wunreachable-code -Wno-implicit-atomic-properties -Werror\=deprecated-objc-isa-usage -Wno-objc-interface-ivars -Werror\=objc-root-class -Wno-arc-repeated-use-of-weak -Wimplicit-retain-self -Wduplicate-method-match -Wno-missing-braces -Wparentheses -Wswitch -Wunused-function -Wno-unused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wempty-body -Wuninitialized -Wconditional-uninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wconstant-conversion -Wint-conversion -Wbool-conversion -Wenum-conversion -Wno-float-conversion -Wnon-literal-null-conversion -Wobjc-literal-conversion -Wshorten-64-to-32 -Wpointer-sign -Wno-newline-eof -Wno-selector -Wno-strict-selector-match -Wundeclared-selector -Wdeprecated-implementations -Wno-implicit-fallthrough -DPOD_CONFIGURATION_DEBUG\=1 -DDEBUG\=1 -DCOCOAPODS\=1 -DOBJC_OLD_DISPATCH_PROTOTYPES\=0 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator16.2.sdk -fstrict-aliasing -Wprotocol -Wdeprecated-declarations -g -Wno-sign-conversion -Winfinite-recursion -Wcomma -Wblock-capture-autoreleasing -Wstrict-prototypes -Wno-semicolon-before-method-body -Wunguarded-availability -fobjc-abi-version\=2 -fobjc-legacy-dispatch -index-store-path /Users/tomassantos/Documents/metamask-mobile/ios/build/Index.noindex/DataStore -iquote /Users/tomassantos/Documents/metamask-mobile/ios/build/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/RNSVG.build/RNSVG-generated-files.hmap -I/Users/tomassantos/Documents/metamask-mobile/ios/build/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/RNSVG.build/RNSVG-own-target-headers.hmap -I/Users/tomassantos/Documents/metamask-mobile/ios/build/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/RNSVG.build/RNSVG-all-non-framework-target-headers.hmap -ivfsoverlay /Users/tomassantos/Documents/metamask-mobile/ios/build/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/RNSVG.build/all-product-headers.yaml -iquote /Users/tomassantos/Documents/metamask-mobile/ios/build/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/RNSVG.build/RNSVG-project-headers.hmap -I/Users/tomassantos/Documents/metamask-mobile/ios/build/Build/Products/Debug-iphonesimulator/RNSVG/include -I/Users/tomassantos/Documents/metamask-mobile/ios/Pods/Headers/Private -I/Users/tomassantos/Documents/metamask-mobile/ios/Pods/Headers/Private/RNSVG -I/Users/tomassantos/Documents/metamask-mobile/ios/Pods/Headers/Public -I/Users/tomassantos/Documents/metamask-mobile/ios/Pods/Headers/Public/DoubleConversion -I/Users/tomassantos/Documents/metamask-mobile/ios/Pods/Headers/Public/FBLazyVector -I/Users/tomassantos/Documents/metamask-mobile/ios/Pods/Headers/Public/RCT-Folly -I/Users/tomassantos/Documents/metamask-mobile/ios/Pods/Headers/Public/RCTRequired -I/Users/tomassantos/Documents/metamask-mobile/ios/Pods/Headers/Public/RCTTypeSafety -I/Users/tomassantos/Documents/metamask-mobile/ios/Pods/Headers/Public/RNSVG -I/Users/tomassantos/Documents/metamask-mobile/ios/Pods/Headers/Public/React-Codegen -I/Users/tomassantos/Documents/metamask-mobile/ios/Pods/Headers/Public/React-Core -I/Users/tomassantos/Documents/metamask-mobile/ios/Pods/Headers/Public/React-RCTAnimation -I/Users/tomassantos/Documents/metamask-mobile/ios/Pods/Headers/Public/React-RCTBlob -I/Users/tomassantos/Documents/metamask-mobile/ios/Pods/Headers/Public/React-RCTText -I/Users/tomassantos/Documents/metamask-mobile/ios/Pods/Headers/Public/React-callinvoker -I/Users/tomassantos/Documents/metamask-mobile/ios/Pods/Headers/Public/React-cxxreact -I/Users/tomassantos/Documents/metamask-mobile/ios/Pods/Headers/Public/React-jsc -I/Users/tomassantos/Documents/metamask-mobile/ios/Pods/Headers/Public/React-jsi -I/Users/tomassantos/Documents/metamask-mobile/ios/Pods/Headers/Public/React-jsiexecutor -I/Users/tomassantos/Documents/metamask-mobile/ios/Pods/Headers/Public/React-jsinspector -I/Users/tomassantos/Documents/metamask-mobile/ios/Pods/Headers/Public/React-logger -I/Users/tomassantos/Documents/metamask-mobile/ios/Pods/Headers/Public/React-perflogger -I/Users/tomassantos/Documents/metamask-mobile/ios/Pods/Headers/Public/React-runtimeexecutor -I/Users/tomassantos/Documents/metamask-mobile/ios/Pods/Headers/Public/ReactCommon -I/Users/tomassantos/Documents/metamask-mobile/ios/Pods/Headers/Public/Yoga -I/Users/tomassantos/Documents/metamask-mobile/ios/Pods/Headers/Public/fmt -I/Users/tomassantos/Documents/metamask-mobile/ios/Pods/Headers/Public/glog -I/Users/tomassantos/Documents/metamask-mobile/ios/build/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/RNSVG.build/DerivedSources-normal/arm64 -I/Users/tomassantos/Documents/metamask-mobile/ios/build/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/RNSVG.build/DerivedSources/arm64 -I/Users/tomassantos/Documents/metamask-mobile/ios/build/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/RNSVG.build/DerivedSources -F/Users/tomassantos/Documents/metamask-mobile/ios/build/Build/Products/Debug-iphonesimulator/RNSVG -fmodule-map-file\=/Users/tomassantos/Documents/metamask-mobile/ios/Pods/Headers/Public/RCTTypeSafety/RCTTypeSafety.modulemap -fmodule-map-file\=/Users/tomassantos/Documents/metamask-mobile/ios/Pods/Headers/Public/React/React-Core.modulemap -fmodule-map-file\=/Users/tomassantos/Documents/metamask-mobile/ios/Pods/Headers/Public/ReactCommon/ReactCommon.modulemap -fmodule-map-file\=/Users/tomassantos/Documents/metamask-mobile/ios/Pods/Headers/Public/React_Codegen/React-Codegen.modulemap -fmodule-map-file\=/Users/tomassantos/Documents/metamask-mobile/ios/Pods/Headers/Public/folly/RCT-Folly.modulemap -fmodule-map-file\=/Users/tomassantos/Documents/metamask-mobile/ios/Pods/Headers/Public/yoga/Yoga.modulemap -include /Users/tomassantos/Documents/metamask-mobile/ios/Pods/Target\ Support\ Files/RNSVG/RNSVG-prefix.pch -MMD -MT dependencies -MF /Users/tomassantos/Documents/metamask-mobile/ios/build/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/RNSVG.build/Objects-normal/arm64/RNSVGLinearGradientManager.d --serialize-diagnostics /Users/tomassantos/Documents/metamask-mobile/ios/build/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/RNSVG.build/Objects-normal/arm64/RNSVGLinearGradientManager.dia -c /Users/tomassantos/Documents/metamask-mobile/node_modules/react-native-svg/apple/ViewManagers/RNSVGLinearGradientManager.m -o /Users/tomassantos/Documents/metamask-mobile/ios/build/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/RNSVG.build/Objects-normal/arm64/RNSVGLinearGradientManager.o -index-unit-output-path /Pods.build/Debug-iphonesimulator/RNSVG.build/Objects-normal/arm64/RNSVGLinearGradientManager.o
`
