### ISSUE TITLE
Ru translation doesn't fit the screen.

### ISSUE THREAD

**Issue by sleepytanya** [MetaMask/metamask-mobile#6797]
Ru text doesn't fit the screen.

Screenshots
<img width="350" alt="Screenshot 2023-07-12 at 4 02 22 PM" src="https://github.com/MetaMask/metamask-mobile/assets/104780023/66c56337-39c2-4ece-9e1e-2324f7ddd3cb">
<img width="470" alt="Screenshot 2023-07-12 at 3 52 22 PM" src="https://github.com/MetaMask/metamask-mobile/assets/104780023/f0395374-54e2-4745-890e-4ec5a9e03215">

Steps to reproduce the behavior.

First screenshot:
1. Go to 'Settings -> General -> Choose Ru
2. Go to back to 'Menu'
4. 'Поделиться моим публичным адресом'  ('Share my public address') is not fully visible

Second screenshot:
1. Go to 'Settings -> General -> Choose Ru
2. Go to back to 'Menu'
3. Choose 'Безопасность и конфиденциальность' ('Security & Privacy')
4. Choose 'Показать секретную фразу для восстановления' ('Reveal Secret Recovery Phrase')
5. Follow SRP procedure
6. The text is off the screen.

Expected behavior.
Full text should be visible.

 - Device: [Galaxy Note20 5G]
 - OS: [Android 13]
 - App Version [v7.1.0(1136)]

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by anaamolnar** [comment]
Hello, @sleepytanya. Thanks for the report! I will pass this on to the team.
