### ISSUE TITLE
**** Critical ***- Deep linking not estimate gas fee causing all transactions to fail

### ISSUE THREAD

**Issue by adirii** [MetaMask/metamask-mobile#6801]
**Describe the bug**
I am using Metamask on a mobile devices and used the payment request to send funds from the app.

for the last 4-5 weeks something changed and Metamask 7.2 (also 7.1) is not estimate gas fee on Polygon Mainnet.

this is the link that used to work: https://metamask.app.link/send/pay-0x2791Bca1f2de4661ED88A30C99A7a9449Aa84174@137/transfer?address=0xB6B5C5Ae9f31e10350d6614C00A5D92854ad054b&uint256=1e9

it will fail with an RPC error since no gas fee is calculated. 

**Screenshots**
_If applicable, add screenshots or links to help explain your problem_

**To Reproduce**
_Steps to reproduce the behavior_

**Expected behavior**
Gas fee should be calculated and transaction should be successfully submitted.

**Smartphone (please complete the following information):**
 - Device: Android Pixel 7 (also tested on 4 different androids and iPhones, still the same)
 - OS: Android 13 (also tested on other versions, same bug)
 - App Version [e.g. 1.0.0] - 7.2 also 7.1

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by adirii** [comment]
the link generator is not generating a payment request that is working with the mobile wallet.

https://metamask.github.io/metamask-deeplinks/

**Comment by adirii** [comment]
Any ETA for triage? Deeplinking and payment request are critical for my app.

**Comment by bschorchit** [comment]
The fix for this was made here https://github.com/MetaMask/metamask-mobile/pull/6677 and should be part of version 7.4 - which will be released to users in the coming weeks

**Comment by bschorchit** [comment]
We fixed this issue here https://github.com/MetaMask/metamask-mobile/pull/6677 and released the fix in version 7.2. Can you confirm you're seeing this issue in 7.2? If yes, are there any other repro steps or details that you could add? I've not been able to reproduce this on 7.2 yet.
