### ISSUE TITLE
Cycle Warning regarding BaseButton component

### ISSUE THREAD

**Issue by tommasini** [MetaMask/metamask-mobile#6807]
**Describe the bug**
Cycle Warning regarding BaseButton component, this can result on uninitialized values

**Screenshots**
![image](https://github.com/MetaMask/metamask-mobile/assets/46944231/92e01b70-bf4c-4f1b-a965-71caa1730634)

**To Reproduce**
* yarn setup
* yarn watch
* yarn start:ios
* When reloading the app it's one of the initial logs

**Expected behavior**
Warning be removed and no cycle needed.

**Comment by georgewrmarshall** [comment]
@tommasini @brianacnguyen does this PR https://github.com/MetaMask/metamask-mobile/issues/6808 fix this issue?

**Comment by georgewrmarshall** [comment]
Completed in https://github.com/MetaMask/metamask-mobile/pull/6808
