### ISSUE TITLE
Transaction failed on WalletConnect v2 with metamask connection

### ISSUE THREAD

**Issue by Doberman2029** [MetaMask/metamask-mobile#6815]
### **Description**

When using wallet connect v2 together with a metamask connection, data that contains a numeric value does not change from decimal to hexadecimal when encoded inside. And because of this, an "ERC721: owner query for nonexistent token" error occurs.

### **Technical Details**

Client: Next.js v13.4.8. ethers v 5.5.2, typechain v 8.1.0, wagmi 1.3.7

Error implementation
1. Connecting a Metamask wallet via Wallet Connect v2.
2. Calling the contract method, which contains the uint256 value (in my case, this is an approve)
3. When signing in the wallet, during the execution of the transaction, an "ERC721: owner query for nonexistent token" error occurs

Devices

Desktop
 - OS: Windows 10, macOs Ventura
 - Browser: Chrome, Safari
 
Smartphone
 - Device: iPhone13, iPhone14, Samsung Galaxy S23
 - OS: ios 16.5.1. Android 13
 - Browser: Chrome, Safari

### **Acceptance Criteria**

The transaction is correctly encoded and completed successfully

Scenario:
1. Connecting a Metamask wallet via Wallet Connect v2.
2. Calling the contract method, which contains the uint256 value (in my case, this is an approve)
3. Transaction completed successfully

### **References**

Method abi
![image](https://github.com/MetaMask/metamask-mobile/assets/20417138/87d35c45-b3dc-4be6-82ea-2d45044f9dae)
Example of tx signed by connection through metamask extensions (success)
https://mumbai.polygonscan.com/tx/0x929bb13fee7a594adc2ea5774db0baab3efc8d0002f5b021e53bc0054ace5fb8
And connection by MM + WalletConnectv2 (not success)
https://mumbai.polygonscan.com/tx/0x52bb3ce85b1400a21aaee7c798ff28ca5af77d31d15fb62b4cb7bc0a00070944
In both cases the same data is transmitted. Connection by trust wallet + wallet connect v2 works correctly

An example of data that is created in the application. 
![image](https://github.com/MetaMask/metamask-mobile/assets/20417138/369c735f-e3fb-492b-91af-6aeebd0265e1)
And here is the same data that I sign in the metamask browser. Last 4 digits changed from hexadecimal to decimal
![image](https://github.com/MetaMask/metamask-mobile/assets/20417138/aac51d20-7f90-41a8-af36-690f6a90b095)

**Comment by Doberman2029** [comment]
The problem is also in metamask browser. So problem is not in wallet connect

**Comment by anaamolnar** [comment]
Hello, @Doberman2029. Thanks for reporting! I will let the team know.

**Comment by JJSEONG** [comment]
Is this error resolved? I get the same "ERC721: owner query for nonexistent token" error when approving using wallet-connect v2.

**Comment by Doberman2029** [comment]
Hello, @anaamolnar is there any news on solving this problem? Users of my application are complaining about the possible risks due to the transition to allowing the entire collection to perform operations
![image](https://github.com/MetaMask/metamask-mobile/assets/20417138/d655be31-ce10-48b9-940d-2a15ce6f827b)

**Comment by bschorchit** [comment]
Thank you for your report @Doberman2029 . I believe this is a duplicate of https://github.com/MetaMask/metamask-mobile/issues/6800 that was fixed on early August. Could you test it with the app version 7.4 or higher and let us know if you're still seeing the same issue? Thank you!
