### ISSUE TITLE
Support for multi chain connection using walletconnect v2

### ISSUE THREAD

**Issue by ThalesBMC** [MetaMask/metamask-mobile#6822]
### **Description**

Add support for multi chain when using Walletconnect

**Comment by anaamolnar** [comment]
Hello, @ThalesBMC. Thanks for the report! I will pass your suggestion on to the team.

**Comment by christopherferreira9** [comment]
Hi all! Can you please verify this issue is still applicable with the latest MetaMask Wallet Versions?

**Comment by christopherferreira9** [comment]
Hi all! This issue will be closed due to inactivity. Please feel free to reply to this issue so that we can reopen it in case it is still applicable.
