### ISSUE TITLE
[Bug]: Why do I get ssl errors only in Android MetaMask App browsers

### ISSUE THREAD

**Issue by codinie** [MetaMask/metamask-mobile#6825]
### Describe the bug

I'm building an https domain environment with an ssl certificate issued. In the ios metamask app browser, it works well without ssl errors, but in the Android metamask app browser, the following ssl errors occur.
'SSL error: The certificate authority is not trusted'
Also, it doesn't keep happening, but it happens sometimes

### Steps to reproduce

1.

### Version

7.2.0(1142)

### Build type

None

### Browser

Chrome

### Operating system

Other (please elaborate in the "Additional Context" section)

**Comment by anaamolnar** [comment]
Hello, @codinie. Thanks for reporting! Is the dapp live so we can try to reproduce it? Could you please share a screenshot? Do you get any warnings about the certificate when trying on a desktop browser? Thanks!

**Comment by dotmilk** [comment]
@anaamolnar i'm getting something very similar but on ios ![image](https://github.com/MetaMask/metamask-mobile/assets/2097429/9d1ef96e-e4ff-406b-b8fc-433a9beeb30c)

![image](https://github.com/MetaMask/metamask-mobile/assets/2097429/9c171742-6ae0-480e-b9bd-92b28b16997d)

**Comment by hesterbruikman** [comment]
@codinie @dotmilk Could you specify whether or not this is a self-signed certificate?

**Comment by codinie** [comment]
@hesterbruikman @anaamolnar It is not a self-signed certificate. Certificate errors do not occur in either PC or mobile browsers. Again, it works fine on the desktop and iOS.

**Comment by codinie** [comment]
![Screenshot_20230721_182225_MetaMask](https://github.com/MetaMask/metamask-mobile/assets/97713099/53aa3302-d668-4614-aa50-8b2ff4c25e4e)
Sometimes, when a page is accessed, it seems that css is not applied

**Comment by codinie** [comment]
Could there be this issue when using TestNet?

**Comment by dotmilk** [comment]
> @codinie @dotmilk Could you specify whether or not this is a self-signed certificate?

It is not a self signed cert. And It happens both on goerli and mainnet

**Comment by hesterbruikman** [comment]
@dotmilk from the screenshot, it looks like you're attempting to deeplink to the dapp. Is that right? 
- Are you finding the same issue when you enter your dapp url in the in-app browser?
- Are you using [MetaMask SDK](https://metamask.io/sdk/)?

@codinie I don't think this is testnet related

**Comment by hesterbruikman** [comment]
To reiterate @anaamolnar 's question. It would really help to get dapp urls to be able to reproduce

**Comment by zhu-maofeng** [comment]
My DAPP is also the same on Android devices, but it works normally on an Apple phone and cannot be opened directly in the Metamsk browser, indicating that the SSL certificate is not trusted. My DAPP uses window.open directly（ https://MetaMask.app.link/dapp/xx ）

**Comment by zhu-maofeng** [comment]
i use Android13,my error like this
![微信图片_20230913122457](https://github.com/MetaMask/metamask-mobile/assets/121092649/09de04cb-ebb8-4245-86b1-9e95e8711965)

**Comment by vandan** [comment]
This is more of an issue for the Mobile team.
