### ISSUE TITLE
Sending a sign request from WAGMI action doesn't trigger the signing modal.

### ISSUE THREAD

**Issue by Fbartoli** [MetaMask/metamask-mobile#6835]
Packages version :
Viem: 1.3.0
Wagmi: 1.3.9
Metamask mobile: 7.3.0 on IOS 16.5.1
iPhone 14 Plus

Using walletConnect v2 as a connector, I can connect to a MetaMask mobile wallet using the QR code then when I use the signMessage() action nothing happens, it doesn't trigger an error also (at least the try and catch, doesn't catch anything).
It works with Rainbow Wallet, trust wallet etc.

**Comment by Fbartoli** [comment]
Metamask 7.2 sorry

**Comment by Fbartoli** [comment]
After investigation. I need to force a delay of around 3000 ms before performing any actions.
Scan WC QRcode -> accept connection on metamask mobile -> force a 3000 ms delay -> trigger signature -> signature modal appears on metamask mobile.

Less than 3000 ms and the signature modal doesn't appear.

**Comment by anaamolnar** [comment]
Hello, @Fbartoli. Thanks for reporting! Please check the App Store and see when you have 7.3.0 available. Once you update, could you please tag me in this thread and let me know if the situation continues to occur? Thank you!

**Comment by Fbartoli** [comment]
> Hello, @Fbartoli. Thanks for reporting! Please check the App Store and see when you have 7.3.0 available. Once you update, could you please tag me in this thread and let me know if the situation continues to occur? Thank you!

Hello @anaamolnar, thank you for coming back to me,

I have proceeded to update to 7.3.0, It still needs a delay of around 3000 ms before being able to proceed an action.

**Comment by buildtheui** [comment]
Since yesterday, the same issue has been happening to me after upgrading to WalletConnect v2. Interestingly, I added an exact 3000 ms delay as @Fbartoli did, and then the sign request showed up in Metamask.

After performing a deeper debugging process, I realized that Wagmi triggers the chainId change after a long time of connecting the wallet. By default, the chain id is set to 1 in Wagmi, but I'm actually connected to Sepolia (chainId 1155511). Consequently, when I sign the message, the chainId sent is 1 instead of 1155511, causing Metamask to refuse to show the sign modal. To verify my theory, I signed in with the main net (chainId 1), and since Wagmi's default network is also 1, the modal showed up correctly.

This situation raises the following questions:

Is Metamask reporting the current chain id with some delay?
Is WalletConnect delaying the report of the chain id?
Is Wagmi delaying the chain id report after connecting?

**Comment by Fbartoli** [comment]
> Since yesterday, the same issue has been happening to me after upgrading to WalletConnect v2. Interestingly, Yesterday I added an exact 3000 ms delay as @Fbartoli did, and then the sign request showed up in Metamask.
> 
> After performing a deeper debugging process, I realized that Wagmi triggers the chainId change after a long time of connecting the wallet. By default, the chain id is set to 1 in Wagmi, but I'm actually connected to Sepolia (chainId 1155511). Consequently, when I sign the message, the chainId sent is 1 instead of 1155511, causing Metamask to refuse to show the sign modal. To verify my theory, I signed in with the main net (chainId 1), and since Wagmi's default network is also 1, the modal showed up correctly.
> 
> This situation raises the following questions:
> 
> Is Metamask reporting the current chain id with some delay? Is WalletConnect delaying the report of the chain id? Is Wagmi delaying the chain id report after connecting?

May I ask how did you perform a deeper debug ?

**Comment by buildtheui** [comment]
> May I ask how did you perform a deeper debug ?

@Fbartoli Well nothing special TBH, while I was tuning the delay I saw that at 2000 sometimes I got in the metamask app this pop up alert saying "active chain is 0xaa36a7 but received 0x1" then I observed with an userEffect the `chain` data using `const { chain } = useNetwork();` I tried again connecting my wallet I then I realized that at first `chain.id` was 1 and after a few seconds `chain.id` was 1155511 (sepolia) but between that timeframe the sign request was sent to Metamask with chain id 1, causing the problem of this issue.

**Comment by Fbartoli** [comment]
Thank you, I am not well versed in React but I had to help my front-end team on that one, your method is helpful to explain to my colleagues how to check if that issue is solved.

**Comment by Fbartoli** [comment]
Opensea is affected also, if you connect to https://opensea.io/account and quickly click on 'Accept and sign' nothing will happen and the modal will be stuck.

**Comment by buildtheui** [comment]
> Opensea is affected also, if you connect to https://opensea.io/account and quickly click on 'Accept and sign' nothing will happen and the modal will be stuck.

I thought about this as well, and tried but I couldn't be faster than the sign in pop up to prove it, but I'm glad you could validate this.

**Comment by buildtheui** [comment]
I created a work around until metamask, wallet connect or wagmi solve it.

To sum up, before I sign a the message in case of connecting with wallet connect I add a listener to get the new chainId and await for it, then when I receive the chain I proceed to sign the message, like the following

```Typescript
import { Connector, ConnectorData, useNetwork } from "wagmi";
import { WalletConnectConnector } from "wagmi/connectors/walletConnect";

const resolveChain = async (
    chainId: number,
    connector: Connector
): Promise<number> => {
    // I instantiate the WalletConnectConnector to get the name and compare
    // it with the connector name, therefore projectId is fine as empty string
    const WalletConnectName = new WalletConnectConnector({
        options: { projectId: "" },
    }).name;

    if (connector.name === WalletConnectName) {
        const chainId = await new Promise<number>((resolve) => {
            const onWalletConnectChange = (data: ConnectorData) => {
                connector.removeListener("change", onWalletConnectChange);
                resolve(data.chain?.id ?? 1);
            };
            connector.addListener("change", onWalletConnectChange);
        });

        return chainId;
    }

    return chainId;
};
```
then I use it like:

```Typescript

const { chain } = useNetwork();

...

const chainId: number = await resolveChain(chain.id, connector);

// Sign message logic with the correct chain id

```

Hopefully this helps to @Fbartoli or anyone unblock for now

**Comment by buildtheui** [comment]
I added a code sample https://stackblitz.com/edit/new-wagmi-y9mxwp?file=src%2Fmain.tsx,src%2FApp.tsx to illustrate the problem with the chain id

**Comment by dingcxx** [comment]
same problem, I thought it was walletconnect‘s issue

this is my steps: 

1. connected wallet MetaMask(v7.2.0 (1142))
2. reload app
3.  request personal_sign method in MetaMask(v7.2.0 (1142)), can jump into wallet but no modal show in wallet, 
4. long time after, back to my app will receive a error, but no any message

I use [modal-react-native v1.0.0 rc-6](https://github.com/WalletConnect/modal-react-native) to connect wallet

**Comment by Fbartoli** [comment]
Metamask Mobile 7.4.0 fixed the issues on my side.
Please @buildtheui, does it work for you as well ?

**Comment by buildtheui** [comment]
@Fbartoli how did you get the version 7.4.0, on releases I only see up until v7.3.1?

**Comment by anaamolnar** [comment]
The issue seems to be solved, so I will go ahead and close this. Feel free to re-open this if the issue continues to occur. Thank you for your patience and understanding!

**Comment by damdafayton** [comment]
Having same problem with MetaMask 7.16
    "wagmi": "1.4.13"
    "@walletconnect/react-native-compat": "^2.11.2",
    "@web3modal/wagmi-react-native": "^1.2.0",
