### ISSUE TITLE
No Response on Reject Transaction eth_sendTransaction

### ISSUE THREAD

**Issue by AmjadKhan2k18** [MetaMask/metamask-mobile#6849]
I am working on dapp and when I try to send transaction using eth_sendTransaction method and on Metamask Android I reject transaction I am not getting any response from Metamask or if there is any error I am doesn't get response 

I am using Android latest version right now in play store
I use flutter for development and this package for connectivity of WC V2 https://pub.dev/packages/walletconnect_flutter_v2

**Expected behavior**
should return response on reject or on error

**Smartphone (please complete the following information):**
 - Device: Google Pixel 4
 - OS: Android 13
 - App Version latest

**Comment by anaamolnar** [comment]
Hello, @AmjadKhan2k18 Thanks for reporting! Can you confirm you are on 7.3.0? Thanks!

**Comment by AmjadKhan2k18** [comment]
@anaamolnar  on Android latest version is 7.2.0 

7.3.0 is not available on Android yet

**Comment by anaamolnar** [comment]
@AmjadKhan2k18 You should be able to see it now in the Play Store. Can you please update and let me know if it continues to occur? Thank you!

**Comment by AmjadKhan2k18** [comment]
@anaamolnar  it's fixed in 7.3.0 Thanks
