### ISSUE TITLE
[Bug] Signatures are not canceled and remain pending whenever tapping outside the modal, appearing later on any tx

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-mobile#6855]
**Describe the bug**
Whenever we perform any kind of signature (personal sign, typed data, etc) if we accidentally click outside the signature modal we can see how the signature seems to be cleared/cancel.
However, in our next dapp interaction, if we trigger a transaction, we can see how instead of the transaction, the previous signature appears.

**Screenshots**

https://github.com/MetaMask/metamask-mobile/assets/54408225/bb80c1dc-4c4b-483f-9952-4dcb2f076cd5

**To Reproduce**
_Steps to reproduce the behavior_
1. Go to the test dapp
2. Trigger any type of signature
3. Tap outside the signature modal
4. See how the modal disappears
5. Now trigger any send/deploy contract interaction
6. See how the modal for the signature appears again instead of the tx
7. After Canceling/Accepting signature, you can now see the tx you've triggered in step 5

**Expected behavior**
Signature should be canceled and cleared from the state whenever we tap outside the modal?
At least, this seems to be how it's handled with transactions.

**Smartphone (please complete the following information):**
 - Device: Pixel 6
 - OS: Android
 - App Version : `7.3.0` production (seems to be an old issue)

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by seaona** [comment]
@bschorchit @cryptotavares I've added the `team-confirmations-secure-ux` label but I'm not completely sure if this issue belongs to Secure UX or Systems. Feel free to re-assign it if appropriate.

**Comment by quy-txv** [comment]
@seaona 
same issue.
the first transaction is always shown.
> However, in our next dapp interaction, if we trigger a transaction, we can see how instead of the transaction, the previous signature appears.

**Comment by legiarung** [comment]
I have the same problem, when I signed for the first time, I deliberately didn't sign it and when I signed it for the second time, it showed the first signature, so I couldn't sign it. I'm having trouble using a mobile device to sign.
Please check it

**Comment by legiarung** [comment]
@seaona 
I think this is an issue that needs to be fixed soon, because thousands of our users have this problem

**Comment by bschorchit** [comment]
@legiarung clicking on the "Cancel" button should solve your issue in the meantime. Could you try that and let us know?

**Comment by legiarung** [comment]
@bschorchit  
I created an issue here, I think it's urgent because a lot of users have this problem when they skip the first sign and the subsequent signings don't show up and it only shows the first one.
https://github.com/MetaMask/metamask-mobile/issues/6886
