### ISSUE TITLE
MetaMask doesn't popup connect button if the app isn't initiated in background.

### ISSUE THREAD

**Issue by AthiraVGopi** [MetaMask/metamask-mobile#6856]
Using web3modal/html I created a wallet connector when connecting to metamask initially the popup doesn't shown-up, after going back and retry to connect then its working. Means initially the metamask doesn't run in background the popup doesn't come.

**To Reproduce**
_Steps to reproduce the behavior_
1. Go to any wallet connect (eg:https://web3inbox.com/)
2. Click on connect-wallet button
3. There is no connect button
4. Come back and re click on connect-wallet button, connect popup comes

Initially the connect popup should shown

**Smartphone (please complete the following information):**
 - Device: Any android phone
 - App Version 7.2.0 

-----------------------------------------------------------

Uploading Qliktag Issue.mp4… The video shows the exact issue what we facing

This is an our major issue, Our clients are frequently reporting this issue.

**Comment by AthiraVGopi** [comment]
https://github.com/MetaMask/metamask-mobile/assets/120572276/9704f4fd-0152-4ab7-a860-f51be92ef422

**Comment by Wandering-Consciousness** [comment]
I'm having the issue of the popup not appearing on Android even if the MetaMask app is already open and running in the background.

**Comment by AlexRFD** [comment]
+1 We're also facing the same issue.

Tested today
Device: Samsung Galaxy S21+
OS: Android 13
App Version: 7.9.1 (1184)

If the app is open in the background it might get the connect prompt but usually the user has to navigate back to the browser and click the Metamask icon again.

After connecting we need to get a signed message, this also fails the first time and usually works when retrying.

**Comment by adonesky1** [comment]
@sethkfman or @Cal-L this appears to be describing a similar issue to https://github.com/MetaMask/metamask-mobile/issues/7631. Are either of these on your radar? DevEx team is not currently equipped to handle mobile build specific issues like this.
