### ISSUE TITLE
The authorization limit has been passed, but the user needs to fill it out themselves.

### ISSUE THREAD

**Issue by liubin595338764** [MetaMask/metamask-mobile#6869]
**Describe the bug**
The authorization limit has been passed, but the user needs to fill it out themselves. The incoming authorization limit should be displayed directly in this location. 

Excessive input actions are unfriendly to user experience.

**Screenshots**
![image](https://github.com/MetaMask/metamask-mobile/assets/5274428/0b7c15de-e671-4a0a-bdfd-7ae0355445be)

**Expected behavior**
The incoming authorization limit should be displayed directly in this location.

**Smartphone (please complete the following information):**
 - Device: chrome extensions
 - OS: mac / windows

**Comment by anaamolnar** [comment]
Hello, @liubin595338764. Thanks for reporting! This is an extension-related issue. Could you please post this issue in the extension repository? Thank you! https://github.com/MetaMask/metamask-extension/issues
