### ISSUE TITLE
Deprecate CheckBox in favor of Checkbox

### ISSUE THREAD

**Issue by georgewrmarshall** [MetaMask/metamask-mobile#6885]
### Description

To prevent further tech debt and inconsistencies `CheckBox` can be deprecated in favor of `Checkbox`

`CheckBox` (old): `@react-native-community/checkbox`
`Checkbox` (new): `app/component-library/components/Checkbox/Checkbox.tsx`

Add the deprecation JSDoc format below to the deprecated code

```
/**
 * @deprecated The `<CheckBox />` component has been deprecated in favor of the new `<Checkbox>` component from the component-library.
 * Please update your code to use the new `<Checkbox>` component instead, which can be found at app/component-library/components/Checkbox/Checkbox.tsx.
 * You can find documentation for the new Checkbox component in the README:
 * {@link https://github.com/MetaMask/metamask-mobile/tree/main/app/component-library/components/Checkbox}
 * If you would like to help with the replacement of the old CheckBox component, please submit a pull request against this GitHub issue:
 * {@link https://github.com/MetaMask/metamask-mobile/issues/6882}
 */
```

### Technical Details

- Add deprecation message above old component function or class

### Acceptance Criteria

- Old component has been deprecated (deprecation indicator shows up in VS Code)
- Good first issue has been created for the community to contribute to reducing tech debt and improving the UI consistency of MetaMask

If the acceptance criteria is not met, PRs may be closed.

### Difficulty: Intermediate

Good first issue for: External contributors who are able to run the extension locally, familiar with React, component props and proficient at searching a codebase

**Comment by pedrosimao** [comment]
So, I have made a PR for this one. I was just not able to add the `[needs-dev-review](https://github.com/MetaMask/metamask-mobile/labels/needs-dev-review)` label

**Comment by pedrosimao** [comment]
One more thing:
I thought about copying and pasting the entire original type declaration, but I found it more practical to use the `typeof` operator, making everything a one liner.
If you thing this is a good approach I could go ahead and do the same for the other deprecation open issues:
https://github.com/MetaMask/metamask-mobile/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22+Deprecate

**Comment by georgewrmarshall** [comment]
This was completed by https://github.com/MetaMask/metamask-mobile/pull/6896
