### ISSUE TITLE
Deprecate Text in favor of Text

### ISSUE THREAD

**Issue by georgewrmarshall** [MetaMask/metamask-mobile#6888]
### Description

To prevent further tech debt and inconsistencies `Text` can be deprecated in favor of `Text`

`Text` (old): `app/components/Base/Text/Text.tsx`
`Text` (new): `app/component-library/components/Texts/Text/Text.tsx`

Add the deprecation JSDoc format below to the deprecated code

```
/**
 * @deprecated The `<Text />` component has been deprecated in favor of the new `<Text>` component from the component-library.
 * Please update your code to use the new `<Text>` component instead, which can be found at app/component-library/components/Texts/Text/Text.tsx.
 * You can find documentation for the new Text component in the README:
 * {@link https://github.com/MetaMask/metamask-mobile/tree/main/app/component-library/components/Texts/Text}
 * If you would like to help with the replacement of the old Text component, please submit a pull request against this GitHub issue:
 * {@link https://github.com/MetaMask/metamask-mobile/issues/6887}
 */
```

### Technical Details

- Add deprecation message above old component function or class

### Acceptance Criteria

- Old component has been deprecated (deprecation indicator shows up in VS Code)

If the acceptance criteria is not met, PRs may be closed.

### Difficulty: Intermediate

Good first issue for: External contributors who are able to run the extension locally, familiar with React, component props and proficient at searching a codebase

**Comment by kshavp** [comment]
@georgewrmarshallm I have submitted a PR for this issue (#6888)
