### ISSUE TITLE
Approve tokenID - Transaction data changes during loading

### ISSUE THREAD

**Issue by Pizajolo** [MetaMask/metamask-mobile#6905]
**Description**
When approving a new token (NFT) in the MetaMask app, first everything seems right, but I am not able to click the approve button. After a few seconds, the app changes the approve data. Then I am able to click the approve button but now the data is wrong.
What does the app do: it changes the token id in the transaction data from an hex number to an decimal number, which results in an error when executing the transaction.
Example:
Transaction executed through MetaMask App:
https://explorer.thetatoken.org/txs/0xc8e966521e139fda4d5cbe500b81a515b609fd42777aad9c03d8d5846fc4d121
Same transaction executed through MetaMask Chrome extension:
https://explorer.thetatoken.org/txs/0xf9a047aa29b4e22fa6727768be2aaec0e1c88b6b9cb103f8d5f22f648f3b010b

**Screenshots**
![IMG_2666](https://github.com/MetaMask/metamask-mobile/assets/53330806/6ce0b546-bdd7-4083-b09a-e87c55260b79)
![IMG_2665](https://github.com/MetaMask/metamask-mobile/assets/53330806/aed6d27f-082f-4981-8e8f-f1dc2b6ea23b)
![IMG_2667](https://github.com/MetaMask/metamask-mobile/assets/53330806/3afcf7f5-7393-4df4-a7df-9d5945fb559c)

**To Reproduce**
_Steps to reproduce the behavior_
1. Open the Metamask app (IOS)
2. Go to OpenTheta
3. Click on an NFT in your wallet
4. Click Sell and then Approve

**Expected behavior**
The token ID should stay a hex number so the transaction can go through

**Smartphone (please complete the following information):**
 - Device: iPhone 12 mini
 - OS: iOS 16.2
 - App Version v7.3.0 (1144)

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by anaamolnar** [comment]
Hello, @Pizajolo Thanks for reporting! We already have a fix (#6833 ) for this issue. It will come out in version 7.4.0, our next release. Thank you for your patience and understanding.
