### ISSUE TITLE
WalletConnect v2 "connect" does not work

### ISSUE THREAD

**Issue by itsallmememe** [MetaMask/metamask-mobile#6908]
**Describe the bug**

We have implemented the WalletConnect v2 Sign.connect flow so that we can then perform a `sendTransactions` request, however the initial connect request does not work.

- our iOS dApp sets up the Walletconnect v2 connection
- the MetaMask application opens
- MetaMask shows the connect popup
- the popup closes when I tap connect
- the dApp does not reopen
- MetaMask shows a message saying that it has connected to the dApp via WalletConnect
- I reopen the iOS dApp manually but WalletConnect does not get a response in the dApp

Here is the code setting up the WC uri and 

```
let methods: Set<String> = ["eth_sendTransaction"]
var blockchains: Set<Blockchain> = Set([Blockchain("eip155:1")!])
let namespaces: [String: ProposalNamespace] = ["eip155": ProposalNamespace(chains: blockchains, methods: methods, events: [])]

do {
    try await Sign.instance.connect(requiredNamespaces: namespaces, topic: uri.topic)
} catch {
    signingEvent.send(.failed(reason: .connectionFailed))
    try await createUri()
}

Task { @MainActor in
    openWallet(wallet: wallet, uri: uri)
}
```

There is a similar issue with WCv2 Auth, which I understand is not supported. 
https://github.com/MetaMask/metamask-mobile/issues/6704

Can you tell us if MetaMask supports WCv2 `Sign.connect` and `Sign.request`?

**Expected behavior**
Wallet Connect v2 Sign.connect should work

**Smartphone (please complete the following information):**
 - Device: iPhone
 - OS: iOS 16
 - App Version: 7.3.0
 - WalletConnect SDK Version: 1.16.12

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by anaamolnar** [comment]
@itsallmememe Thanks for reporting! Feel free to re-open this if the above does not work. Thank you!

**Comment by itsallmememe** [comment]
This is not appropriate to the bug.

MetaMask opens on but the communication between MetaMask and WalletConnect is not correct.

The flow above works perfectly with Rainbow and Trust, but using MetaMask we do not get any information about the Sign.connect request.

I'll reopen this.

**Comment by itsallmememe** [comment]
@equalogix @anaamolnar I can't seem to reopen, can you do this for me please?

**Comment by aquariumy** [comment]
Hopefully this bug will be fixed. iOS engineers at Metamask seem to be interpreting this as being outside the scope of Wallet Connect V2 support, but they are wrong. The Android version of Metamask is working fine.

**Comment by ldkfreetoplay** [comment]
I also found this problem before, and solved it by passing all parameters through Sign.instance.connect.

Like this:
```
                try await Sign.instance.connect(
                    requiredNamespaces: namespaces,
                    optionalNamespaces: [:],
                    sessionProperties: sessionProperties,
                    topic: uri.topic
                )
```

**Comment by itsallmememe** [comment]
@Idkfr This does work! Can you tell me what sessionProperties you used or, indeed, what they're for?

**Comment by itsallmememe** [comment]
@ldkfreetoplay - you don't happen to use WalletConnect 2 Auth as well? I can't get that to work with Metamask either.

**Comment by itsallmememe** [comment]
@anaamolnar @equalogix - See the point above by @ldkfreetoplay  

This method does not work with MetaMask
```
try await Sign.instance.connect(requiredNamespaces: namespaces, topic: uri.topic)
```

but this does. It's not clear why passing in dummy `sessionProperties` value fixes the issue
```
try await Sign.instance.connect(
                    requiredNamespaces: namespaces,
                    optionalNamespaces: [:],
                    sessionProperties: ["key": "value"],
                    topic: uri.topic
)
```

**Comment by ldkfreetoplay** [comment]
> @idkfr @ldkfreetoplay This does work! Can you tell me what sessionProperties you used or, indeed, what they're for?

I think metamask did not handle the data structure well, because these parameters are not necessary. On the other hand, I encounter the problem that metamask often does not automatically redirect the app after signing, do you know how to solve it?

**Comment by ldkfreetoplay** [comment]
> @ldkfreetoplay - you don't happen to use WalletConnect 2 Auth as well? I can't get that to work with Metamask either.

I'm not using Auth, I'm using the API `Sign`

**Comment by abretonc7s** [comment]
Hi @itsallmememe , could you please confirm if one of the solution above worked for you? If not, please share a repo so that we can try your dapp specifically.
