### ISSUE TITLE
Rejecting Connection Request from WalletConnect Mobile App Doesn't Redirect Back

### ISSUE THREAD

**Issue by Luzzotica** [MetaMask/metamask-mobile#6926]
**Describe the bug**
If I deep link to MetaMask using WalletConnect and accept the connection, then MetaMask redirects back to my dapp once it's approved the session.
However, if I cancel the session it doesn't deep link back.

**Screenshots**
None

**To Reproduce**
1. Connect using [this](https://lab.web3modal.com/with-wagmi/react) website on your mobile device
2. Tap on MetaMask
3. Reject/Cancel the connection request
4. MetaMask doesn't redirect

**Expected behavior**
MetaMask redirects even when the session is canceled/rejected.

**Smartphone (please complete the following information):**
 - Device: iPhone 14 Pro (I think)
 - OS: iOS 16
 - App Version 7.3.0 (1144)

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by anaamolnar** [comment]
Hello, @Luzzotica. Thanks for reporting! I will pass this on to the team.

**Comment by ldkfreetoplay** [comment]
I have the same problem, do you have a solution? @anaamolnar

**Comment by mertcankose** [comment]
same

**Comment by abretonc7s** [comment]
Hi @Luzzotica ,
We are investigating the issue and will get back to you shortly. Thanks for reporting.

**Comment by siosio34** [comment]
I have the same problem

**Comment by christopherferreira9** [comment]
Hi all! We are working on a fix for this issue and it'll be available in the coming releases.
Also, quick reminder that due to [iOS limitations](https://github.com/MetaMask/metamask-mobile/issues/7165) we're not able to redirect the user back to the dapp from iOS17 forward.

**Comment by christopherferreira9** [comment]
Closing this for now until there's an option for us to deal with it on iOS 17.
