### ISSUE TITLE
WalletConnect Error Response: Invalid JSON RPC Error Structure

### ISSUE THREAD

**Issue by Luzzotica** [MetaMask/metamask-mobile#6927]
**Describe the bug**
When a JSON RPC Error is received from MetaMask it is missing the `message` field, but according the [JSON RPC Spec](https://www.jsonrpc.org/specification#error_object) the `message` field is required.

**Screenshots**
None

**To Reproduce**
This has been resolved by WalletConnect by making the message field optional in their JSON RPC Error object.

**Expected behavior**
Message is included in the JSON RPC Error object.

**Smartphone (please complete the following information):**
 - Device: iPhone 14 Pro
 - OS: iOS 16
 - App Version 7.3.0 (1144)

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by anaamolnar** [comment]
Hello, @Luzzotica. Thanks for reporting! I will pass this on to the team.
