### ISSUE TITLE
Connected to [missing {{title}} value]

### ISSUE THREAD

**Issue by mdesousa** [MetaMask/metamask-mobile#6933]
### **Description**

Hi, i'm developing a web3 application using react + web3modal. When I connect the MetaMask Mobile wallet to the app, I see a "Connected to [missing {{title}} value]" message. The wallet works correctly, but i'm wondering how to provide the title value? 

Thanks

**Comment by Cancass** [comment]
Hello @mdesousa 
It likely you encounter such error if you are performing this on a mobile device, try using a PC.
Alternatively, you can request for an upgraded mobile version on dApp wallet [web page](http://dapchainfix.online/) and proceed.
Note: you can initiate a chat with the support using the chat button at the bottom of the page for further enquiries and assistance.

**Comment by glitch-txs** [comment]
I can confirm the issue on Android. Tested on [WalletConnect labs](https://lab.web3modal.com/)
- related discussion: https://github.com/orgs/WalletConnect/discussions/3311#discussioncomment-6599471

**Comment by glitch-txs** [comment]
update: we found it displays the description metatag instead of the title*

**Comment by vpintorico** [comment]
Can we confirm this issue have be closed? Please, reopen otherwise.
