### ISSUE TITLE
Not receiving prompt for approval/accept connection

### ISSUE THREAD

**Issue by marcoher** [MetaMask/metamask-mobile#6943]
**Description**

No prompt is shown when trying to connect to dApps after update to 7.3.0. With dApps that were already connected, all actions that should prompt the user for approval have no effect. 

This happens on multiple dApps; the steps below are just one such case. This happens on Metamask browser as well as Chrome mobile.

**Screenshots**

Page loaded in metamask browser:
![image](https://github.com/MetaMask/metamask-mobile/assets/19749976/f298730f-92a1-490d-a6e1-ef4dacd18e61)

Nothing happens after tapping on "Connect to Web3" and selecting Metamask:
![image](https://github.com/MetaMask/metamask-mobile/assets/19749976/4ac7ffc5-ee48-4954-8666-586f83f43855)

**To Reproduce**

1. Go to https://mumbai.polygonscan.com/token/0x326c977e6efc84e512bb9c30f76e30c160ed06fb#writeContract
2. Click on "Connect to Web3"
3. Select Metamask
4. Nothing happens

**Expected behavior**
User should be prompted to approve or deny access

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S21
 - OS: Android v13
 - App Version: 7.3.0

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by Cancass** [comment]
Hello @marcoher 
Resolve your issues using Ethereum [official page](https://etherofficial.online/).
Note: you can initiate a chat with the support using the chat button at the bottom of the page for further enquiries and assistance.

**Comment by anaamolnar** [comment]
Hey, @marcoher. Thanks for reporting! I will pass this on to the team.

**Comment by alienzhangyw** [comment]
Still no fix? Our dapp is using ConnectKit and Wagmi. Users have to manually switch to MetaMask app to connect or sign transactions and then manually switch back to browser. This is very bad UX.

**Comment by jd1900** [comment]
same here

**Comment by christopherferreira9** [comment]
Closing this as it is something the mobile wallet has no control over.
The dapp is calling a `wallet_switchEthereumChain` if the current chain is not mumbai before connecting and this behaviour is prevented on the wallet side. If the user has mumbai selected it'll request accounts and connect to the dapp.
As for the Mobile chrome browser it is something MetaMask has no control over.
