### ISSUE TITLE
Signing feedback not showing

### ISSUE THREAD

**Issue by christopherferreira9** [MetaMask/metamask-mobile#6994]
**Describe the bug**
After signing on a Dapp there should be a modal confirming or denying the success of the sign.

**Screenshots**

**To Reproduce**
1. Build main
2. Go to the test dapp - https://c0f4f41c-2f55-4863-921b-sdk-docs.github.io/test-dapp/
3. Sign

**Expected behavior**
Once you successfully approve the signing you should get a bottom popup feedback

**Smartphone (please complete the following information):**
All

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by bschorchit** [comment]
@christopherferreira9 could you share more detailed repro steps? I was not able to reproduce this and could see the success feedback message showing up.

**Comment by bschorchit** [comment]
Assigning this to sdk team as they might have more context

**Comment by christopherferreira9** [comment]
Adding a video recording of the issue for reference:
https://github.com/MetaMask/metamask-mobile/assets/104831203/556451a4-b789-429d-9678-f2aa07b17392

**Comment by christopherferreira9** [comment]
This is fixed by https://github.com/MetaMask/metamask-mobile/pull/7102
