### ISSUE TITLE
why sign client not redirect me to the dapp when i trigger the transaction through wallet

### ISSUE THREAD

**Issue by arbaz-meo** [MetaMask/metamask-mobile#6995]
i have one doubt or maybe i m missing something

when i connect wallet by signclient its open the wallet automatically by using deep link **### https://metamask.app.link/wc?uri=encode wcuri** .
i have wc uri so i genrate deep link on connection its redirect me to dapp after connect the wallet but when i go to trigger the transaction i have this deep link ### **https://metamask.app.link/** so its take me to the wallet but when i trigger transaction its not bring me back on dapp.

is i am missing something ???

using SignClient from wallect connect 2.0

so here is the signclient code 

```
const  {SignClient} = require ('@walletconnect/sign-client');
const uriMap = new Map();
const connectedMap = new Map();
const projectId = process.env.ProjectId;

let Client = {};

const intilizeSignClient = async () => {
 Client = await SignClient.init({ projectId ,  metadata: {
    name: 'Myapp',
    description: ' Dapp',
    url: 'https://walletconnect.com/', // Do we have this one
    icons: ['https://www.mywhoosh.com/wp-content/uploads/2022/10/my-whoosh-logo-white-v3.png']
   // redirect:"www.com.pk" // Looks like we need to deploy our splash somewhere
  
  },


},


);


   
   
} 



/*  
  we are paring session topic  every time for every user on behalf of DeviceID 
*/

async function connectWallet(deviceId){
  try {
   // intilizeSignClient();
  
    const{uri,approval}=  await Client.connect({
       requiredNamespaces: {
         eip155: {
           methods: ['personal_sign','eth_sendTransaction'],
           chains: ['eip155:1'],
           events: ["connect","accountsChanged"]
         }
       },
     
    
      
     })
     console.log(uri);
     uriMap.set(deviceId,uri);
     connectedMap.set(deviceId,approval());
   

  } catch(e){
    console.log(e.message);
  }

  


}

const getClient = () => {
  return Client
}

module.exports.connectWallet=connectWallet;
module.exports.uriMap=uriMap;
module.exports.connectedMap=connectedMap;
module.exports.signClient = getClient;
module.exports.intilizeSignClient = intilizeSignClient ;
```
from signclient i get the wc uri and create deep link https://metamask.app.link/wc?uri=encode wcuri so its connect my wallet and trigger back to dapp 

now  from signclient i trigger transaction and move to the wallet through this https://metamask.app.link/  universal link then i trigger transaction  but metamask  not redirect  me back to dapp

**Comment by arbaz-meo** [comment]
@christopherferreira9 can you give feedback on this . thanks !

**Comment by anaamolnar** [comment]
Hello, @arbaz-meo. Thanks for reporting! I will ask the team to look into this.

**Comment by arbaz-meo** [comment]
@anaamolnar waiting on this issue ???

**Comment by codepgq** [comment]
> @anaamolnar waiting on this issue ???

https://github.com/MetaMask/metamask-mobile/issues/7255 look my solution

**Comment by arbaz-meo** [comment]
@codepgq  one time mine also redirect but second time its not redirect me to the dapp . so is this your issue also same with mine ??

**Comment by abretonc7s** [comment]
Hi @arbaz-meo , we are investigating the issue and will get back to you as soon as possible

**Comment by codepgq** [comment]
> @codepgq 一次我的也重定向，但第二次它没有将我重定向到 dapp 。那么你的问题也和我的一样吗？

是的，如果是第一次有回复，第二次没有，使用下面的代码可以返回， topic是session.topic
```dart
var encodeUrl = Uri.encodeComponent(
        'wc:00e46b69-d0cc-4b3e-b6a2-cee442f97188@2?sessionTopic=$topic');
    return 'metamask://wc?uri=$encodeUrl';
```

**Comment by arbaz-meo** [comment]
> > @codepgq 一次我的也重定向，但第二次它没有将我重定向到 dapp 。那么你的问题也和我的一样吗？
> 
> 是的，如果是第一次有回复，第二次没有，使用下面的代码可以返回， topic是session.topic 关键点就是sessionTopic必须有且值正确，可以从session里面获取，保存起来
> 
> ```dart
> var encodeUrl = Uri.encodeComponent(
>         'wc:00e46b69-d0cc-4b3e-b6a2-cee442f97188@2?sessionTopic=$topic');
>     return 'metamask://wc?uri=$encodeUrl';
> ```

will try this

**Comment by codepgq** [comment]
> > > @codepgq 一次我的也重定向，但第二次它没有将我重定向到 dapp 。那么你的问题也和我的一样吗？
> > 
> > 
> > 是的，如果是第一次有回复，第二次没有，使用下面的代码可以返回， topic是session.topic 关键点就是sessionTopic必须有且值正确，可以从session里面获取，保存起来
> > ```
> > var encodeUrl = Uri.encodeComponent(
> >         'wc:00e46b69-d0cc-4b3e-b6a2-cee442f97188@2?sessionTopic=$topic');
> >     return 'metamask://wc?uri=$encodeUrl';
> > ```
> 
> will try this

There should be no need to do this in the next version，you can look this [7476](https://github.com/MetaMask/metamask-mobile/pull/7476)

**Comment by christopherferreira9** [comment]
Hi @arbaz-meo ! We've fixed an issue in the upcoming version where signing or connecting twice would not redirect back to the dapp. Please give that a try in version v7.9.0.

**Comment by christopherferreira9** [comment]
Closing since it was fixed on https://github.com/MetaMask/metamask-mobile/pull/7476 .
