### ISSUE TITLE
Fix Browser code coverage

### ISSUE THREAD

**Issue by bitpshr** [MetaMask/metamask-mobile#7]
The Browser component executes an asynchronous filesystem read in its `componentDidMount` method. This operation (or any other asynchronous operation) breaks the Istanbul code coverage produced by Jest and can't be ignored using any flavor of ignore syntax. If this single statement is commented out manually, 100% code coverage is achieved, hinting at a transpilation error.

Ideally, we should find a way to ignore this line or work around this issue to achieve 100% coverage.

**Comment by EtDu** [comment]
100% coverage is unrealistic for us at this point.
