### ISSUE TITLE
metamask-mobile 7.4.0 provide.request({ method: "wallet_switchEthereumChain modal "}) waiting indefinitely  Despite pressing the cancel button in the network change window after connecting Metamask in WalletConnect

### ISSUE THREAD

**Issue by siosio34** [MetaMask/metamask-mobile#7023]
**Describe the bug**

In the metamask 7.4.0 version, when click cancel after calling the network change modal with walletconnect, i cannot receive the cancellation event.

**code**
<img width="367" alt="image" src="https://github.com/MetaMask/metamask-mobile/assets/7166022/99ec26a1-9915-4765-8171-0d3e6dce4788">

**To Reproduce**
1. connect metamask via walletconnect
2. call switch network use code attached above
3. click cancel button in metamask mobile

**Expected behavior**
i want the function call (`await provider.request({ method: wallet_switchEthereumChain }) `) to exit when user cancel button click. Now, even if the user presses the cancel button, infinite blocking occurs in the function.

**Smartphone (please complete the following information):**
 - App Version [e.g. 1.0.0] - 7.4.0

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by anaamolnar** [comment]
Hello, @siosio34. Thanks for reporting! I will pass this on to the team.

**Comment by ankushswar1** [comment]
Hi @anaamolnar! Do you have any updates on this issue?

 We'd love to be able to programmatically switch chains with MetaMask mobile but we're seeing the same issue where sometimes the RPC request literally never responds. 
 
 If there's unlikely to be a fix for this soon, it would be good to know so we can update our guidance to users for how they should manually switch the chain themselves!

**Comment by abretonc7s** [comment]
Hi @siosio34 , Thank you for reporting. We are working on a fix as we are aware of an issue with redirect (especially from IOS17). We will get back to you as soon as possible.

**Comment by siosio34** [comment]
@abretonc7s Thank you very much for your efforts to create a good product. Well then, let’s wait!
