### ISSUE TITLE
Google GSI client loading error

### ISSUE THREAD

**Issue by ArtemFokin** [MetaMask/metamask-mobile#7046]
**Describe the bug**
Hello, i'm trying to load google script to use google sign-in button in metamask mobile browser i get some errors(hard to know which one)
<script src="https://accounts.google.com/gsi/client" async onerror="alert('error')" onload="alert('loaded')"></script>

**To Reproduce**
[https://q4d7vr.csb.app/](https://q4d7vr.csb.app/)

**Smartphone (please complete the following information):**
 - Device: iphone 11
 - OS: IOS 16.6
 - App Version: 7.5.0

**Comment by anaamolnar** [comment]
Hello, @ArtemFokin Thanks for reporting! I am sorry for the late response. Is this something that is still occurring for you? If so, I will pass this on to the team.
