### ISSUE TITLE
[Bug]: Import account formatting mismatch

### ISSUE THREAD

**Issue by profishional** [MetaMask/metamask-mobile#7051]
### Describe the bug

When importing a single account to the mobile app using the private key from Web Extension, you are given this error.

![import_account_pic](https://github.com/MetaMask/metamask-extension/assets/93366432/9539a432-ef53-4771-b2f0-92cbb3d1009e)

After some soul-searching, I remember a formatting bug in my own apps. The mobile app requires letters in the private key to be uppercase, but the Web extension displays it as lowercase letters! 

Display the private key with uppercase letters or accept lowercase letters in the mobile app PLEASE!

### Steps to reproduce

1. Open web extension
2. Unlock if you haven't already
3. Select an account
4. Click the 3 column dots on the top right corner
5. Click "Account details"
6. Click "Show private key"
7. Enter the password and click "confirm"
8. Copy the private key (I do this by using the text detect feature of the iPhone camera)
9. Open mobile app (iPhone 12 max pro)
10. Unlock
11. Click on the account card at the top
12. Click "Add account or hardware wallet"
13. Click "Import account"
14. Paste the private key that you copied from the camera text detection
15. Move the cursor to the beginning of the second line and delete the "\n" character
16. Click "Import"
17. Get Error.

### Error messages or log output

```shell
"Something went wrong
We couldn't import that private key. Please make sure you entered it correctly."
```

### Version

10.34.5

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by plasmacorral** [comment]
I would strongly discourage using iOS Live text for something as sensitive as a private key and even public addresses.  If you have any lower case `b` within your private key there is a tendency to represent that as a numeric `6` or vice-versa.  If that is what you are experiencing it is unlikely to be a valid private key.  

I will discourage the following with any address that you hold real assets on, but... 
For a private key that produces the error while using Apple's live text (look for b's or 6's):  If you are able to copy/paste the private key from extension into something like "offline QR generator" and still produce the `Something went wrong...` error after scanning the clipboard content represented in QR, then please open a fresh issue report and mention this issue. 

I will also encourage you to post this within Apple's support forum if you are able to confirm it was a bad Live text result.  They are unlikely to improve these occurrences without user feedback. 

With all this said, I do think there may be an opportunity to provide a QR code of the private key within the extension client, similar to what is offered when you reveal the Secret Recovery Phrase.  I can make no promises, but  I have opened https://github.com/MetaMask/metamask-extension/issues/20596 to formally make the request.
