### ISSUE TITLE
MetaMask App crashes on switching to a custom network

### ISSUE THREAD

**Issue by ankitboghra** [MetaMask/metamask-mobile#7061]
**Describe the bug**
2 ways to describe the issue:
1. MetaMask App crashes on switching to a custom network, when connected to a dApp using wallet connect.
2. A dApp does not receive network change event(`watchNetwork`), when an user switches the network.

**Screenshots**

**To Reproduce**
This bug is not reproducible for everyone. You need to have a custom network added with wrong/un-responsive rpc.
Since you can not add a custom network whose rpc is not rechable at the time of adding new custom network.
You can add an local working RPC and then shut down the RPC server when trying to switch network.

1. Go to MetaMask App
2. Connect your app to any dApp supporting wallet connect (e.g. [Simple dApp](https://github.com/ankitboghra/walletconnect-web3modal))
3. Currently on `Ethereum` network by default
4. Switch to `Mumbai` network
    My Network Config:
    - Network Name: `Mumbai`
    - RPC url: `https://matic-mumbai.chainstacklabs.com` (root cause)
    - Chain ID: `80001`
    - Symbol: `MATIC`
    - Block Explorer URL: `https://mumbai.polygonscan.com`
5. The dApp did not receive the updated network details using watchNetwork i.e. `Mumbai`
6. Switch to `Ethereum` network
7.  The dApp did not receive the updated network details using watchNetwork i.e. `Ethereum`

**Expected behavior**
When a user switches the network on Metamask Mobile, the dApp should have been notified of the switch in network.

**Smartphone (please complete the following information):**
 - Device: iPhone 12 Pro Max
 - OS: iOS Version 16.5.1
 - App Version: MetaMask v7.5.0 (1167)

> The issue is really critical, because the dApp is not aware of the correct network the user is on. And hence will perform the transaction on wrong chain, and loose/block assets.
e.g. User intending to transfer assets from goerli, might end up transferring the similar assets from ethereum.

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by anaamolnar** [comment]
Hello, @ankitboghra. Thanks for reporting! I will pass this on to the team.

**Comment by christopherferreira9** [comment]
Seems to be working as of `7.14.0` . Regardless of the chain being synced, if a request arrives at MetaMask for a chain different than the one selected it'll prompt to change first.

https://github.com/MetaMask/metamask-mobile/assets/104831203/b04fa8ce-3f1d-4333-a727-6f9ec93ef7ff
