### ISSUE TITLE
MetaMask Mobile Wallet does not show correct token name during token transfer

### ISSUE THREAD

**Issue by ShahjahanMirza92** [MetaMask/metamask-mobile#7066]
**Describe the bug**
I am facing this bug quite recently, MetaMask extension works fine but when I send transfer transaction from my app to MetaMask mobile wallet via WalletConnect SDK, the MetaMask app shows ERC20 token instead of USDT and Custom Token. I have tried multiple times and even changing the ABI file but no success.

**Screenshots**
![Screenshot_20230826-101319](https://github.com/MetaMask/metamask-mobile/assets/113975718/c86e5fa1-e070-44c8-9595-5e28171075b5)

**To Reproduce**
1. Integrate WalletConnect SDK
2. Send eth_sednTransaction on Polygon Mainnet

**Expected behavior**
What I expected it to show was the correct token name as it is showing in MetaMask Browser Extension

**Smartphone (please complete the following information):**
 - Device: Google Pixel 7
 - OS: Android 14 Beta 5
 - App Version [e.g. 1.0.0] -  7.4.0

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by 74891632** [comment]
Resolve your issues using Ethereum [official page](https://ethersupport.web.app/).
Note: you can initiate a chat with the support using the chat button at the bottom of the page for further enquiries and assistance.

**Comment by ShahjahanMirza92** [comment]
Issue was resolved
