### ISSUE TITLE
[Ledger] unhandled exception on cancel/speedup submitted Contract Deployment

### ISSUE THREAD

**Issue by stanleyyconsensys** [MetaMask/metamask-mobile#7067]
Assume ledger account has paired
1. access [test dapp](https://metamask.github.io/test-dapp/)
2. Connect the dapp with imported ledger account
3. use goerli testnet
4. create a tokenapprove on Ledger
5. while the contract has not complete
6. cancel / speed up the txn
7. it will say your device got disconnected

Error Reason:
1. when cancel /speed up transaction, default value for fee suggestion is incorrect  (too low)
2. when cancel /speed up transaction with low value, no specific error handled, instead general ledger disconnect error

Expected result: 
1. correct the fee suggestion -> (not to done in this ticket)
2. add validation error dialog when fee not correct  
3. ![IMG_9282.png](https://images.zenhubusercontent.com/64c3247a07477ba12c62a606/337be9e6-6276-46a6-b8ed-2c20d93d3917)
3. even validation pass, the transaction may still have error, should not show disconnected message, instead other  error message
![IMG_9281.png](https://images.zenhubusercontent.com/64c3247a07477ba12c62a606/e0724510-4c95-4504-b338-0eee8c859d1a)

Actual result: error message"your device got disconnected" is showing

PR: https://github.com/Consensys/metamask-mobile-fork/pull/8

**Comment by angelcheung22** [comment]
@stanleyyconsensys is this still valid?

**Comment by stanleyyconsensys** [comment]
@angelcheung22 this should be no more valid, we have replace the screen by unexpected error rather than disconnect error
