### ISSUE TITLE
[Android] Cannot read property 'mnemonic' of undefined

### ISSUE THREAD

**Issue by vikmyr** [MetaMask/metamask-mobile#7073]
Unble to login into android app with correct password after wallet has been created.

![Screenshot_20230827_213847_MetaMask](https://github.com/MetaMask/metamask-mobile/assets/101345804/4e48c516-1e04-4bf7-aff3-13aa90585cc5)

**Steps:**
Install MetaMask app from Google Play Market
Create a wallet, set password etc...
Restart app
Enter correct password and tap unlock

**Expected behavior**
App unlocked 
User can access his wallet 

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S20+
 - OS: Android 13. OneUI 5.1
 - App Version 7.5.0

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by anaamolnar** [comment]
Hello @vikmyr. Thanks for reporting. Do you have your secret recovery phrase saved, as well as any other imported private keys?  Do you remember doing anything specific before this happened? Do you have biometrics enabled? Have you tried to log in with both biometrics and password? Thank you!

**Comment by vikmyr** [comment]
Hi @anaamolnar. This is a newly created wallet. Immediately after installation and registration, I copied the wallet address and put the app in the background.
When I returned, I could not log in with a password or biometrics. After restarting the application, the option to log in with a fingerprint stopped appearing at all.
No srp or private keys.

**Comment by dart-bird** [comment]
![Screenshot_20230906_141049_MetaMask.jpg](https://github.com/MetaMask/metamask-mobile/assets/51515055/4df8dcd6-be01-42f0-93fd-5ee888834ce7)

It's the same for me. Is there any way to recover? I'm stumped. I didn't keep a backup key... :(

**Comment by robbie666** [comment]
This exact thing just happened to me ! 
I was trying to buy crypto so I downloaded metamask and so I downloaded metamask and then created a new wallet. I've used this wallet many times before so I chose to view the mnemonic phrase later because I was in a rush to get some polygon. After purchasing it on the screen that brings up moonpay the transaction completes It takes me back to my wallet and gives me the same error !

**Comment by faid123** [comment]
The same thing keeps happening to me as well. I have to reset the wallet every time it happens, after reset, I am able to log in to the wallet a few times before the error occurs again. Error: Cannot read property 'mnemonic' of undefined. When using biometrics to attempt the login, the app will stay on the same screen and nothing happens. If an incorrect password is entered it does know that it is incorrect, but if credentials match it throws the error above.

**Comment by robbie666** [comment]
Hey! Metamask support has actually contacted me in regards to our specific
error were experiencing!
They were going to help somehow! But I literally gave up hours before
seeing their reply and ended up deleting the wallet.
 Let me forward you the email. Between us maybe they can help you !

**Comment by robbie666** [comment]
Sorry I thought this was an email didn't see it was a reply on GitHub.
