### ISSUE TITLE
[E2E] Automate uploading QA builds to browserstack from bitrise

### ISSUE THREAD

**Issue by chrisleewilcox** [MetaMask/metamask-mobile#7079]
Upload QA builds from bitrise to browserstack.  Currently we do this manually which is a little time consuming and error prone.  We should have this automated for all release testing.

Browserstack docs: https://www.browserstack.com/app-live/rest-api

Test branch: https://github.com/MetaMask/metamask-mobile/tree/test-ios-upload

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBb0pTIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--0418741b18974da4889806b23014820f431e24ae/image.png)

### Acceptance Criteria
GIVEN QA builds are successful on bitrise
THEN QA builds file names are based on branch to easily identify
AND QA builds are uploaded to browserstack App Live

**Comment by cortisiko** [comment]
was addressed in https://github.com/MetaMask/metamask-mobile/pull/7286
