### ISSUE TITLE
Error while checking incoming transactions TypeError: Cannot read property 'toLowerCase of undefined

### ISSUE THREAD

**Issue by olenapankina** [MetaMask/metamask-mobile#7080]
Tested on
Samsung Galaxy M21 Android 12, One UI Core version 4.1
Pixel 4a API 31

commit c785d3d786963ab1f1d413541f63b21903885c73

Console error occurs after changing the password to the one with lowercase symbols only "12345678a". Selected auth method - password
The error occurs regardless of whether the Transaction tab was opened.
![image](https://github.com/MetaMask/metamask-mobile/assets/116747263/d9465690-1eb6-4433-bb07-a2eb238c7849)
![image](https://github.com/MetaMask/metamask-mobile/assets/116747263/debb951a-79e5-46dd-b5f3-5ab02c9521dd)
![image](https://github.com/MetaMask/metamask-mobile/assets/116747263/ad1eee92-662a-49ca-a474-82b3713812af)

**Comment by olenapankina** [comment]
Might be related/fixed by https://github.com/MetaMask/metamask-mobile/pull/7056 
cc @jpcloureiro

**Comment by jpcloureiro** [comment]
Hi Olena. 

The error appears to come from the TransactionController.

Unfortunately it won't be fixed by #7056 

It might be worth checking the `@metamask/transaction-controller` patch where toLowerCase function is called.

**Comment by seaona** [comment]
Encountered the same issue, logging out and logging in again to the Wallet in QA build. In my case, my password didn't have a lower case.

![Screenshot from 2023-10-20 10-35-00](https://github.com/MetaMask/metamask-mobile/assets/54408225/da4d67bf-f170-47c9-8555-0a66800c313f)

cc @bschorchit @cryptotavares maybe this should be assigned to Confirmations?

**Comment by hesterbruikman** [comment]
Closing in favor of [#8201](https://github.com/MetaMask/metamask-mobile/issues/8201) as it includes Sentry logs and an approach to resolve. #8201 is assigned to and investigated by `team-confirmations-system`

cc @gauthierpetetin
