### ISSUE TITLE
[Bug] Networks: Getting error `Callback was already called. Possible Unhandled Promise Rejection` when adding any popular or custom network

### ISSUE THREAD

**Issue by davibroc** [MetaMask/metamask-mobile#7082]
**Describe the bug**
As you see from the video when running the app in the iPhone simulator the the first time I add a popular network I get the warning `Error: Callback was already called. Possible Unhandled Promise Rejection` and the second network I add I get a bunch of warning saying `MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 newListener listeners added. Use emitter.setMaxListeners() to increase limit] `

**Screenshots**

https://github.com/MetaMask/metamask-mobile/assets/6082863/62fe0c3d-81ee-4bfd-bf79-8e8508715952

**To Reproduce**
1. Tap on the network selector on nav bar
2. Tap on `Add network`
3. Select any network and add it
4. Switch to the added network
5. Clear the educational modal
6. Look at the logs on Metro

**Expected behavior**
_A clear and concise description of what you expected to happen_

**Smartphone (please complete the following information):**
 - Device: iPhone 12 Simulator
 - OS: iOS 16.2
 - App Version: 7.5.0

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by chrisleewilcox** [comment]
- Run test e2e/specs/add-custom-rpc.spec.js and you will see these warnings being triggered and continues to be triggered after the test is complete.
- Run test e2e/specs/confirmations/send-erc721.spec.js. At the end of the test close and relaunch app without unlocking. You will see warnings continue, ganache server is not available. Unlock app and select Ethereum network and MaxListenersExceededWarning warnings goes away.


https://recordit.co/4rxx55U3Rj
