### ISSUE TITLE
[WalletConnect] Wallet doesn't send back on Android with WalletConnect after the 2nd attempt

### ISSUE THREAD

**Issue by christopherferreira9** [MetaMask/metamask-mobile#7084]
**Describe the bug**
When you connect + sign on the OpenSea android dapp the MetaMask Wallet sends the user back the first time but it doesn't on the second try.
Cleaning the dapp data makes it work but it still seems wallet related.

**Screenshots**
https://github.com/MetaMask/metamask-mobile/assets/104831203/b173732e-c685-4403-82c7-64fb271c33cd

**To Reproduce**
1. Download the OpenSea dapp on the google Play store
2. Connect + sign
3. Logout
4. Try to connect + sign again

**Expected behavior**
After signing the wallet should always send the user back to the dapp

**Smartphone (please complete the following information):**

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by abretonc7s** [comment]
Fixed on https://github.com/MetaMask/metamask-mobile/pull/7476
