### ISSUE TITLE
Gasless transactions can't be confirmed (Confirm button is disabled)

### ISSUE THREAD

**Issue by Karkunow** [MetaMask/metamask-mobile#7088]
**Describe the bug**
_Metamask Mobile wallet doesn't work with gasless transactions. They can not be confirmed on mobile. On desktop, it works as expected._

**Screenshots**
![telegram-cloud-photo-size-1-5131903435711556323-y](https://github.com/MetaMask/metamask-mobile/assets/2808283/41639870-e5a6-423f-9e81-b32c012de719)
![telegram-cloud-photo-size-2-5420226694826020364-y](https://github.com/MetaMask/metamask-mobile/assets/2808283/b29c743b-4bc2-431a-9d16-f75b62ee55b5)

**To Reproduce**
_Steps to reproduce the behavior_
1. Open Metamask mobile browser.
2. Go to https://pipeflare.io/flare2-token/spin or any other site which uses gasless transactions (https://aurora.plus/)
3. Connect your wallet (the connection happens via WalletConnect v2).
4. Click "Spin the wheel". 
5. See transaction confirmation popup in Metamask mobile with the disabled "Confirm" button.
(NOTICE: it doesn't reproduces on all devices, it seems. Some of my colleagues had it working, I've asked 5 different persons to try and it was 3 out of 5 who got the error).

**Expected behavior**
_We expect to be able to confirm the transactions with 0 gas on Metamask Mobile app._

**Smartphone (please complete the following information):**
 - Device: iPhone 13 Pro
 - OS: iOS 16.6
 - App Version: v.7.5.0(1167).

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by Karkunow** [comment]
Here is also the video of the screen while reproducing the bug:
https://www.youtube.com/shorts/pGyyUPyRxAw

**Comment by plasmacorral** [comment]
Hey @Karkunow, I am sorry for the difficulty here, but I want to thank you for taking the time to submit such a thorough report.  We are currently tracking this under https://github.com/MetaMask/metamask-mobile/issues/6567 and I will share this new report with the team.
