### ISSUE TITLE
[Bug] `Transaction error: maxFeePerGas cannot be less than maxPriorityFeePerGas`

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-mobile#7115]
**Describe the bug**
Whenever we trigger a transaction, if we edit the gas fees, we can set the Max priority fee greater than the max fee and proceed with the transaction (there is no input validation error). Whenever we trigger Save and Confirm, we get the error `Transaction error: maxFeePerGas cannot be less than maxPriorityFeePerGas` and in the case of the tx triggered from a dapp, the transaction is "lost", so we need to start a new one again.
This seems an undesired UX flow.

**Screenshots**

https://github.com/MetaMask/metamask-mobile/assets/54408225/dc946131-deeb-4b4f-962b-428abc40a6e8

**To Reproduce**
_Steps to reproduce the behavior_
1. Go to test dapp
2. Connect MM
3. Trigger any tx
4. Click Edit gas
5. Set priority fee to a higher value
6. Save
7. Click Confirm
8. See error

**Expected behavior**
On Extension, there is an input validation that prevents the user to save gas setting where the max base fee is lower than the priority fee. This avoids getting the transaction error and loosing the transaction as it happens at the moment in Mobile

![Screenshot from 2023-09-04 11-45-40](https://github.com/MetaMask/metamask-mobile/assets/54408225/f1981157-480b-4781-9884-6b746d382f6d)

**Smartphone (please complete the following information):**
 - Device: Pixel 6
 - OS: Android
 - App Version: `v7.5.0 (1167)` production

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by MetaMask-Support-io** [comment]
NEED HELP @seaona ??  Send us a message about you issues with MetaMask or contact us via email for quick responsed 
(meta.mask.help@mail.com) “Start a Conversation” 

We never DM. NEVER share your Secret Recovery Phrase with any site or person. Verify links are legitimate. Contact us now
( meta.mask.help@mail.com)
