### ISSUE TITLE
[Bug] After Swipe to Swap action a confirmation modal is shown that should't be there

### ISSUE THREAD

**Issue by davibroc** [MetaMask/metamask-mobile#7136]
**Describe the bug**
After use Swipe to Swap a confirmation modal is shown that should't be there. Swipe to Swap should be the final step for the user. 

**Screenshots**

https://github.com/MetaMask/metamask-mobile/assets/6082863/3821bf33-752e-460f-98ee-2b5abab4a1f7

**To Reproduce**
1. Use a mainnet funded account or Tenderly
2. Swap any tokens
3. After the Swipe to Swap action notice that a confirmation modal appear

**Expected behavior**
The confirmation modal shouldn't be there. Swipe to Swap should be the final step for the user

**Smartphone (please complete the following information):**
 - Device: Any
 - OS: Any 
 - App Version: 7.6.0
 

### This issue does not exist in current production.

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by chrisleewilcox** [comment]
@MetaMask/confirmations-system-team can we pinpoint the PR that introduced this issue?

**Comment by chrisleewilcox** [comment]
I confirmed this is happening in v7.7.0 build 1170...

https://recordit.co/kd0bwJXcZD

**Comment by chrisleewilcox** [comment]
https://github.com/MetaMask/metamask-mobile/pull/7152 cherry-picked fix for release.
