### ISSUE TITLE
[Question] Does MetaMask mobile browser support Web NFC?

### ISSUE THREAD

**Issue by kabaluyot** [MetaMask/metamask-mobile#7144]
Does metamask mobile browser support Web NFC https://googlechrome.github.io/samples/web-nfc/ ?

**Comment by hesterbruikman** [comment]
@kabaluyot NFC interfacing is currently not supported. Very curious about the use case you have in mind if you're open to share this!

**Comment by kabaluyot** [comment]
Oh .. It's for implementing PBTs (Physically-Backed Tokens) ... You scan merchandises via NFC, connect wallet via MetaMask, and redeem the PBT. Mostly used in supply chain ... and most likely in mobile phones

**Comment by hesterbruikman** [comment]
I see what you mean, that's pretty cool. So, we don't support NFC today and given our focus areas don't foresee support in the near future. That said, thanks for the suggestion! Can think of some more 2fA and Snaps use cases.

**Comment by anaamolnar** [comment]
I will go ahead and close this issue. Feel free to open a new one if you have any other questions regarding Metamask. Have a nice day!
