### ISSUE TITLE
[Bug] Cancel Legacy tx throws error `Cannot read property 'substr' of undefined`

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-mobile#7149]
**Describe the bug**

Whenever we initiate a legacy transaction from inside the wallet and cancel it, MetaMask breaks with the error `Cannot read property 'substr' of undefined`

**Screenshots**
![image](https://github.com/MetaMask/metamask-mobile/assets/54408225/5e1db3f5-e950-448d-b3c8-c3e04d9833bb)

https://user-images.githubusercontent.com/54408225/265946986-f66cb710-d1e0-4895-baa7-5296cec069a0.mp4

**To Reproduce**

1. Add Bnb Testnet https://chainlist.org/?testnets=true&search=bnb
2. Click Send
3. Add any amount and recipient
4. Cancel the tx
5. See error

**Expected behavior**
Tx should be canceled without breaking.

**Smartphone (please complete the following information):**
 - Device: Pixel 6
 - OS: Android
 - App Version: `v7.5.0 (1167)` production - possibly an old issue

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by OGPoyraz** [comment]
I think this is not valid anymore, fyi @sleepytanya @seaona 

https://github.com/MetaMask/metamask-mobile/assets/7644512/2085ab93-b380-4fe7-9f44-254c98f3db2e

**Comment by sleepytanya** [comment]
@goktug @seaona I don't see this error happening as well:

https://github.com/MetaMask/metamask-mobile/assets/104780023/7b9db6ef-b451-4ebd-a7f8-868642626ce7

**Comment by sleepytanya** [comment]
Just to clarify - this error doesn't happen on test builds, on Browserstack devices. I only get it on the real Android device.

https://github.com/MetaMask/metamask-mobile/assets/104780023/d99f072e-7066-48c5-8cc8-dafaa0a91f05


https://github.com/MetaMask/metamask-mobile/assets/104780023/da453b18-2fef-4525-8f37-93bd4e20cad3


https://github.com/MetaMask/metamask-mobile/assets/104780023/9b12ef08-dc18-4cfc-a0c4-568c1bbb7c13
