### ISSUE TITLE
BUG] Settings: Security & Privacy: Manage connections: cannot see text in dark mode

### ISSUE THREAD

**Issue by cortisiko** [MetaMask/metamask-mobile#7157]
**Describe the bug**

The text on the Manage Connections screen is unreadable in dark mode.

 

**Screenshots**
![image](https://github.com/MetaMask/metamask-mobile/assets/12821081/0dcc6de3-9e78-4071-a345-f8bba48b303f)

**To Reproduce**
Ensure dark mode is enabled on your device. 
Launch the app
Go to privacy and settings
screen down to the "manage connections section"
Tap on the manage connections CTA. 
Notice the text is in dark mode. 

**Expected behavior**
The text should be visible and readable in both light and dark mode. 

**Smartphone (please complete the following information):**
 - App Version [e.g. 1.0.0] - find version number in app from Settings > About MetaMask

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by PhantomOz** [comment]
Yes I would love to fix this

**Comment by cortisiko** [comment]
nice I have assigned it to you @PhantomOz !

**Comment by kaksv** [comment]
Was this solved?

**Comment by PhantomOz** [comment]
> Was this solved?

On it

**Comment by kaksv** [comment]
Alright.
