### ISSUE TITLE
Error Handling Customized Gas in MetaMask Mobile App

### ISSUE THREAD

**Issue by ariutokintumi** [MetaMask/metamask-mobile#7163]
**Describe the bug**
We are manually configuring transaction fees from our script as is described below, is important to note that this is working perfectly on desktop. This bug is just in Mobile, Android and iPhone with last updated version of MetaMask wallet. Just tested today as well to take the screenshots.

```
gas: 23000n, 
maxFeePerGas: parseEther( '1', 'gwei' ), 
maxPriorityFeePerGas: parseEther( '0.000000001', 'gwei' )
```

When the transaction is started, the UI shows many discrepancies as follows:
- Main UI Discrepancies: The custom settings for GAS, PRIORITY FEE, and GAS PRICE aren’t visible in the primary transaction window.
- Secondary Window Reflection: Intriguingly, these customized settings do appear when we access the secondary UI, specifically when clicking on the ETH gas price for adjustments.
- Transaction Inconsistencies: Despite the above point, transactions are sent with a different gas configuration, seemingly ignoring our customized inputs, that are valid.

**Screenshots**
<a href="https://ibb.co/FVqPxrp"><img src="https://i.ibb.co/5Fx7M0Z/bug-report-mobile.png" alt="bug-report-mobile" border="0"></a>

Please note that in the screenshots we ARE NOT configuring or chaning anything, just clicking the buttons to see (and confirm) that the manual configuration is being received by MetaMask.

Again: This is working perfectly on desktop

**To Reproduce**
Try to configure the transactions fees manually from any front-end script as seen in our example in the first point, it will work on Desktop but it will NOT WORK in Mobile.

**Expected behavior**
The gas configuration should be the configured one and user should just click "Confirm" and send the transaction. 

Note that we are not discussing here if the configured gas is enough or not to make the transaction happen fast, slow or get forever pending. This is not about that. The configured gas is enough by the standard and are valid transactions, it is tested and wotking on Desktop (again) and validated by nodes.

**Smartphone (please complete the following information):**
 - Device: iPhone11, Samsung S23
 - OS: iOS16, Android 13
 - App Version: MetaMask 7.6.0

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by anaamolnar** [comment]
Hello, @ariutokintumi. Thanks for taking the time to write such a detailed report! We are aware of certain inconsistencies between the two platforms, and it is in our plan to address them as soon as the bandwidth will allow us to.  I will pass this on to the team, and they will review the issue as soon as possible. Thank you!

**Comment by luisjang-wt** [comment]
There is a similar issue.
If you set maxFeePerGas and maxPriorityFeePerGas for other types of TXs, they will be displayed normally in the [advanced options] window. but
[approve] If you set maxFeePerGas and maxPriorityFeePerGas for tx,
It doesn't apply at all.

**Comment by ariutokintumi** [comment]
gm @anaamolnar, I hope you're doing well. I wanted to inquire if there's been any update regarding this issue or if there's a particular process to follow up on it. We're eager to resolve this as it has some impact on our project's timeline. Please let us know if we can assist or collaborate in any way to expedite a solution. Thank you for your time and understanding.

**Comment by ariutokintumi** [comment]
gm @bschorchit, thank you for adding the "needs-reproduction" label. We've consistently reproduced the issue across various devices and always observed the same behavior. We encourage the MetaMask team to test it out and confirm our findings. 

Please let us know how we can assist in resolving this, as it's currently preventing our customers from using MetaMask with our dApp.

**Comment by angelmc32** [comment]
If this is something that currently works on desktop, why not allow use on mobile? This is hurting UX for mobile users, let's get a look into this bug

**Comment by ariutokintumi** [comment]
gm @bschorchit, I hope this message finds you well. We are reaching out to kindly request an update on a critical issue we previously reported that significantly impacts mobile users. This matter is of urgent concern for not only our operations but also for numerous other dApps working diligently on gas optimization. We have noticed that many are currently testing only on Desktop, possibly overlooking the importance of the Mobile user experience.

Given the gravity of this issue, your timely update and support in resolving it would be greatly appreciated by our team and the broader community. 

Thank you very much for your attention and support on this matter. If you need assistance to expedite the resolution of this issue, please let us know the next steps, and we'll be more than willing to contribute to the process.

Looking forward to your guidance and prompt resolution of this critical issue.

**Comment by ariutokintumi** [comment]
gm, is here any update about this issue?

**Comment by ariutokintumi** [comment]
I don't think this should be closed, as it is a bug that affects many dApps that were tested only in the MetaMask Desktop Extension where it works correctly, but were not tested in Mobile App, where this do not work correctly, without the developers and users realizing it.
