### ISSUE TITLE
Update @walletconnect/sign-client to 2.10.0

### ISSUE THREAD

**Issue by Sinu5oid** [MetaMask/metamask-mobile#7175]
### **Description**

As versions of `@walletconnect/sign-client` have simpler `sendResult` / `sendError` flow where the `relayer.publish` method is used without await, it's known to cause issues in handling responses on React Native wallets (the wallet responds to a session request, awaits for method to finish, and closes itself (navigates out of foreground state), which aborts pending network requests, and the DApp never receives a response)

### **Technical Details**

- bump `@walletconnect/sign-client` version to 2.10.0

### **Acceptance Criteria**

- No acceptance criteria needed

### **References, Scenario**

- Please follow this issue discussion: https://github.com/WalletConnect/walletconnect-monorepo/issues/3607#issuecomment-1711195868

**Comment by abretonc7s** [comment]
Hi @Sinu5oid , This seems to be a wallet connect issue, please continue the thread on wallet connect.
