### ISSUE TITLE
the method eth_signTypedData_v4 does not exist/is not available

### ISSUE THREAD

**Issue by Faraday26** [MetaMask/metamask-mobile#7180]
**Describe the bug**
When I provide only one chain - [arbitrum] in wallet it gives me this error. If i provide more than one - e.g [arbitrum,arbitrumGoerli] or polygon for that matter it workes fine.

It is working fine on web just accessing a daap from mobile chrome is giving an issue.
i am connecting the mobile metamsk app in chrome daap

**Expected behavior**
it should work with arbitrum or arbitrumgoerli chain
**Smartphone (please complete the following information):**
 - Device: any device same issue
 - OS: ios or android
 - App Version [e.g. 1.0.0] - 7.5.0

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by anaamolnar** [comment]
Hello, @Faraday26. Thanks for reporting! I will pass this on to the team, and they will review this as soon they can.

**Comment by Faraday26** [comment]
I'll make a dummy app that you can try and reproduce the error.

**Comment by bschorchit** [comment]
That will be helpful, thank you!

**Comment by Haianh9999** [comment]
I got this error when signTransaction with metamask mobile app, some one please help me to resolve it 🙇 
<img width="994" alt="Screenshot 2023-10-26 at 10 25 32" src="https://github.com/MetaMask/metamask-mobile/assets/96808297/bd79d0e9-be36-4d83-af60-fd3a5078bea9">

**Comment by Haianh9999** [comment]
@bschorchit Please check 🙇

**Comment by SergioArrighi** [comment]
Hello,
I have the same error. I believe is related to this code

`if (action.type === orderbook.ActionType.SIGNABLE) {
    orderSignature = await (signer as any)._signTypedData(
      action.message.domain,
      action.message.types,
      action.message.value
    );
    console.log(action);
  }`

The same code works perfectly on desktop, but fails with this error when tested on mobile browser.
Thanks and best regards
