### ISSUE TITLE
UNKNOWN METHOD Showing in Metamask Wallet Mobile App 

### ISSUE THREAD

**Issue by TheQueenCho** [MetaMask/metamask-mobile#7199]
While request eth_sendTransaction along my contract data to metamask wallet .
my contract method name not showing instead of its showing UNKNOWN METHOD ,
But contract method running perfectly as expected

- I am using metamask from **Flutter** app and  i am using **WalletConnectFlutterV2** library 

![Screenshot_1693834525 (1)](https://github.com/MetaMask/metamask-mobile/assets/144307712/146d55a6-e36c-48d8-ab7e-2451747936a4)

**Comment by bschorchit** [comment]
Closing as this is a duplicate of https://github.com/MetaMask/metamask-mobile/issues/5929. We haven't solved it yet, but we should look into it in the near future.

**Comment by arihant763** [comment]
I'm still encountering the issue despite trying various approaches, including parseAbi and other solutions. It worked correctly the first two times, but after that, it stopped functioning. I'm using wagmi along with the latest MetaMask version.

Could this be related to my contract not being registered with MetaMask or something else?
