### ISSUE TITLE
When try to call the signMessage function in mobile with walletconnect, network conversion dialog will appear asking you to switch to the Ethereum chain.

### ISSUE THREAD

**Issue by siosio34** [MetaMask/metamask-mobile#7201]
**Describe the bug**
When try to call the signMessage function in walletconnect mobile,  popup network change modal to etherum mainnet.

**Screenshots**
_If applicable, add screenshots or links to help explain your problem_

**To Reproduce**
_Steps to reproduce the behavior_
1. connect metamask mobile via walletconnect and change the chain to any chain rather than the Ethereum mainnet.
2. call signMessage function https://wagmi.sh/examples/sign-message
3. I would like to see a signing modal, but a network chain modal appears asking me to switch to the Ethereum mainnet.

**Expected behavior**
I expect the signing modal to appear instead of the network chain modal.

**Smartphone (please complete the following information):**
 - Device: galaxy s21
 - OS: chrome, metamask mobile
 - App Version 7.6.0

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by anaamolnar** [comment]
Closing in favor of #7206.
