### ISSUE TITLE
selectedAddress from redux store becomes undefined

### ISSUE THREAD

**Issue by jpcloureiro** [MetaMask/metamask-mobile#7203]
### Description
One of the causes for selectedAddress being undefined is when redux persistor fails to hydrate. It could be caused by device OOM issues, bad store state migration.

The bug resolution should include R&D on other scenarios that can lead to `selectedAddress` becoming undefined

Ticket scoping in progress:
- selectedAddress should be initialised as an empty string if no initialState is provided to PreferencesController

### Technical details
- Identify scenario to consistently reproduce bug
- Apply fix to prevent selectedAddress from being undefined
- If the discovered scope is too big, reach out to @hesterbruikman or @Cal-L to revisit work to be done

### Acceptance criteria
- The bug is identified and reproducible
- List of scenarios reviewed/researched where bug is identified and reproducible 
- ~~The same reproducible bug is fixed by the solution~~
- ~~selectedAddress should no longer be undefined in the bug scenario~~

### Links
- PR that catches the error - https://github.com/MetaMask/metamask-mobile/pull/7056
- Issue of original error - https://github.com/MetaMask/metamask-mobile/issues/7080
- dev notes - https://www.notion.so/selectedAddress-from-redux-store-becomes-undefined-b5ff49d1e1b6408fb071f3045d4baca2

**Comment by Cal-L** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/MetaMask-Mobile-5f984938ddc0e4001d4b79cb/issues/MetaMask/metamask-mobile/7203?planning-poker) with Zenhub @Andepande @chrisleewilcox @cortisiko @frankvonhoven @jpcloureiro @MarioAslau @NicolasMassart @SamuelSalas @tommasini

**Comment by christopherferreira9** [comment]
I gave this a go and it's very hard to reproduce. 
The flow that made it happen more often is through an SKD Dapp:
- Clear app data (in iOS I'm assuming it would be a clean install)
- Onboard MetaMask without biometrics
- Connect to Dapp
- Kill wallet once it sends you back to dapp
- Tap `send_transaction` in the dapp
- Watch logs

I've hosted a [react dapp](https://chris-react-dapp.vercel.app/) to facilitate testing with the JS SDK (`v0.10.1`). 

https://github.com/MetaMask/metamask-mobile/assets/104831203/49970ce2-f82a-4e55-973d-2829c0be9a2a

**Comment by hesterbruikman** [comment]
Thank you @christopherferreira9 ! To dig in a bit more. Have you changed the connected account at all or connected multiple accounts to the dapp initially or when navigating back to the dapp?

**Comment by christopherferreira9** [comment]
Not at all, I only kept the one created on onboarding. It is still not reproducible 100% of the time but that was the flow I've encountered the issue the most 🙏

**Comment by jpcloureiro** [comment]
Issue not reproduced consistently.
User flows described in development notes that have higher chance of breaking PreferencesController state.
Those flow can be used to verify any improvement after Redux State management and Engine initialization gets revisited. 

Closing for now. We will keep an eye on related production events
