### ISSUE TITLE
Android displays SSL error

### ISSUE THREAD

**Issue by zhu-maofeng** [MetaMask/metamask-mobile#7208]
Using deep links in Dapp can wake up Metamsk mobile, but it is not possible to open my Dapp in Metamsk browser. My Dapp has HTTPS and external browser access is normal. How should I make my Android device work? Currently, my device is 1加 and the operating system is Android 13
![微信图片_20230913122457](https://github.com/MetaMask/metamask-mobile/assets/121092649/601fe52d-7edf-42bf-8494-6a24aa1bb702)

**Comment by anaamolnar** [comment]
Closing in favor of https://github.com/MetaMask/metamask-mobile/issues/6825
