### ISSUE TITLE
Deep links fail due to branch.io being on some block lists

### ISSUE THREAD

**Issue by feld** [MetaMask/metamask-mobile#7224]
Hello,

I've been reporting issues with deep links not working and I've finally tracked it down. 

`branch.io` happens to be on multiple blocklists. Their services are required by Metamask for deep link functionality. Unfortunately, when `api.branch.io` or `api2.branch.io` cannot be resolved there is no indication to the user that any error has occurred.

You can find `branch.io` on these lists:

AdGuard - many of their lists, some imported/aggregated from elsewhere - https://github.com/AdguardTeam/FiltersRegistry
EasyPrivacy - https://easylist.to/easylist/easyprivacy.txt
Fanboy's Annoyance List - https://secure.fanboy.co.nz/fanboy-annoyance.txt

Users of crypto financial assets are increasingly at risk of malware and scams targeting them. Using DNS and browser based block lists is one part of a good security posture and unfortunately this domain is on some popular blocklists which is breaking this functionality.

Please provide a way to communicate to the user that there was an issue communicating with this service.

edit: block api.branch.io and api2.branch.io at the DNS level to reproduce this behavior on iOS

**Comment by feld** [comment]
These domains are all part of the branch.io ecosystem and they're what are used for the deep linking

https://github.com/MetaMask/metamask-mobile/blob/main/ios/MetaMask/Info.plist#L23-L29

**Comment by anaamolnar** [comment]
Hey, @feld. Thank you for taking the time to write this report. I will ask someone to look further into this. Someone from the team will get back to you as soon as they can. Thanks for your patience and understanding!

**Comment by adonesky1** [comment]
> Their services are required by Metamask for deep link functionality

@feld can you elaborate on what you mean by this ☝️

**Comment by adonesky1** [comment]
I'm not sure if this is a real issue or what's even really being described here but I believe in any case that it will be more quickly understood and/or resolved by someone from the Mobile Platform Team. WDYT @sethkfman ?

**Comment by adonesky1** [comment]
> @feld can you elaborate on what you mean by "Their services are required by Metamask for deep link functionality"

@feld Please let us know if you're still experiencing this issue.

**Comment by adonesky1** [comment]
@Cal-L I can't speak to whether this is a legitimate finding. Please let me know what you think when you have a chance.

**Comment by christopherferreira9** [comment]
Hi all! We are aware of this issue and we've also been reporting it to Branh.io to have it sorted.
The best solution for this is to use deeplinks instead of Branch.io universal links.
Closing this issue as its solution is outside MetaMask's scope.
