### ISSUE TITLE
[Bug]: Site suggest gas fee: Wrong website name

### ISSUE THREAD

**Issue by Virgil0x** [MetaMask/metamask-mobile#7282]
### Describe the bug

Site suggest gas fee: the site name is the last visited site in MM’s built-in browser. But I called up MM mobile from another browser（via WalletConnect or MM SDK). You can see the correct site name at the top of the screenshot.

### Expected behavior

Display 'spd.socialswap.com suggested gas fee'

### Screenshots

![photo_2023-09-20_11-09-22](https://github.com/MetaMask/metamask-mobile/assets/145631440/bb3182ed-e477-4d87-9f38-7ae2bf53a9b1)

### Steps to reproduce

1. Visit a site A in MM mobile built-in browser
2. Visit Blur.io in Safari or Chrome，Connect MetaMask via WalletConnect
3. Send a transaction, jump to MetaMask and wait for the transaction confirmation pop-up window

### Version

v7.7.0(1171)

### Build type

None

### Device

iOS

### Operating system

iOS

**Comment by anaamolnar** [comment]
Hello, @Virgil0x. Thank you for taking the time to write this report! I will pass this on to the team.

**Comment by christopherferreira9** [comment]
This issue seems to be fixed as of `v7.14.0`.
https://github.com/MetaMask/metamask-mobile/assets/104831203/6cddb557-f76a-482d-8a14-424aae4a618f
