### ISSUE TITLE
[Bug]:  legacy gas missmatch and not preserved after change

### ISSUE THREAD

**Issue by blackdevelopa** [MetaMask/metamask-mobile#7290]
### Describe the bug

Whenever I trigger a legacy transaction from a dapp, I can see how the Estimated gas fees does not match the gas details (if I open the Edit gas). Furthermore if I change the suggested gas, I can see how the value is not changed and tx is submitted with the suggested gas value instead of the one I set.

### Expected behavior

Whenever I trigger a legacy transaction from a dapp, I expect to be able to edit existing values and have it submitted with the new values I select.

### Screenshots

https://github.com/MetaMask/metamask-mobile/assets/29962968/e4d83375-177d-4a31-8992-92dec80a4d22

### Steps to reproduce

Select a testnet (i.e. Goerli)
Go to testdapp
Click Send Legacy tx
Click Edit gas fees
Change its value and save
See how value is not updated on the confirmation screen
Send tx
Check Etherscan
See how gas was not saved

### Version

7.7.0

### Build type

None

### Device

iPhone

### Operating system

iOS

**Comment by bschorchit** [comment]
Closing as https://github.com/MetaMask/metamask-mobile/pull/7305 was merged
