### ISSUE TITLE
[Bug]: MM does not validate values coming from the dapp on `eth_sendTransaction`

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-mobile#7291]
### Describe the bug

**Problem**: whenever a dapp suggests a send ETH transaction, we can see how certain values are not validated and the wallet still triggers the transaction with incorrect UI:
- `gasLimit`: I can pass a string and tx is still triggered and could proceed
- `type`: I can pass a string and tx is still triggered and could proceed
- `value`: I can pass a raw number or any string and tx is still triggered and could proceed

**Even with the invalid values passed from the dapp, the transaction Succeeds,** meaning that those values, are in reality coming from MM and not from the dapp (which is then another issue).

### Expected behavior

If the values are incorrect, the transaction should not be displayed on the wallet  (ideally a dapp error should be shown).
This is at least how the Extension handles those cases.

### Screenshots

https://github.com/MetaMask/metamask-mobile/assets/54408225/d00cb984-4558-4d6f-ba51-1727834327cd

### Steps to reproduce

1. Checkout the test dapp locally
2. Change the Send ETH logic for this one:
```
    sendButton.onclick = async () => {
      const result = await ethereum.request({
        method: 'eth_sendTransaction',
        params: [
          {
            from: accounts[0],
            to: '0x0c54FcCd2e384b4BB6f2E405Bf5Cbc15a017AaFb',
            value: 343,
            gasLimit: 'efrweew',
            gasPrice: '0x2540be400',
            type: 'ewrew',
          },
        ],
      });
      console.log(result);
    };
```
3. Build the test dapp
4. Trigger the Send ETH Legacy
5. See how tx is triggered in the Wallet

### Version

7.8.0 (but seems an old issue)

### Build type

None

### Device

Pixel 6

### Operating system

Android

**Comment by shanejonas** [comment]
we should return invalid params errors if we don't want to allow this behaviour.

Ideally we use the [api-specs](https://github.com/MetaMask/api-specs) (and add more restricted schema) for this using the `validate` method on the [MethodCallValidator from `@open-rpc/schema-utils-js`](https://open-rpc.github.io/schema-utils-js/classes/methodcallvalidator.html#validate) for our api, could be a middleware maybe.
