### ISSUE TITLE
[Bug]: ERC20 Token is not added to the Wallet

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-mobile#7292]
### Describe the bug

**Problem**: whenever I try to add an ERC20 token to the wallet, I don't see the modal triggered and the token is not added.

### Expected behavior

A modal should be triggered for accepting/rejecting the watch asset functionality

### Screenshots

https://github.com/MetaMask/metamask-mobile/assets/54408225/6ad49c5c-75df-4ce0-909b-99b194824c3a

### Steps to reproduce

1. Go to the test dapp
2. Create an ERC20 token
3. Click Add Token to the wallet
4. See nothing happens

### Version

7.8.0 (build from the RC branch)

### Build type

None

### Device

Pixel 6

### Operating system

Android

**Comment by cortisiko** [comment]
hey @seaona can we confirm this doesn't happen on v7.7(current production version)

**Comment by chrisleewilcox** [comment]
Wrote this up but it eventually issue went away and wasn't able to consistently reproduce.
https://app.zenhub.com/workspaces/mobile-release-regression-6249e5242464b70013315a98/issues/gh/metamask/mobile-planning/1281

**Comment by seaona** [comment]
interesting :thinking: I haven't been able to reproduce this in production, but after resetting the wallet, I am not able to consistently reproduce this in `7.8.0`. Maybe this behaviour relates to what @chrisleewilcox is pointing?
I'll try to see if I can find some solid repro steps

**Comment by Andepande** [comment]
Tested on my devices (iOS iPhone 14, Android Pixel 5) but couldn't reproduce the issue on version 7.8.0 (build 1172).
https://recordit.co/L0uiswfjpn
