### ISSUE TITLE
[Bug]: Flask Mobile: "flask" string absent from `web3_clientVersion`

### ISSUE THREAD

**Issue by firnprotocol** [MetaMask/metamask-mobile#7302]
### Describe the bug

On Flask Mobile on Android—version `MetaMask Flask v0.0.3 (1128)`—the result of
```javascript
window.ethereum.request({
  method: "web3_clientVersion",
});
```
is `MetaMask/0.0.3/Mobile`. In particular, the string `flask` is absent from the version string.

this makes it impossible to detect presence of Flask on mobile.

### Expected behavior

the version returned should contain the (case-sensitive) string `flask`. For example, on Chrome Desktop Flask, I receive `MetaMask/v11.0.0-flask.0`.

### Steps to reproduce

Install MetaMask Flask on Android (Google Pixel 6a). run any website which calls `web3_clientVersion`.

### Version

MetaMask Flask v0.0.3 (1128) (mobile)

### Build type

Flask

### Device

Google Pixel 6a

### Operating system

Android

### Additional context

btw, I am actually not sure if (non-whitelisted) Snaps are supported on Flask Mobile. are they? thanks in advance for clarifying.

### Severity

impact is rather low.

**Comment by anaamolnar** [comment]
Hello,  @firnprotocol. Thanks for opening this ticket! I am really sorry for answering just now. Flask is not yet supported on mobile. Please keep an eye out on our official Twitter page for any announcements regarding this in the next few months.

**Comment by MetaMask-Support-io** [comment]
NEED HELP @firnprotocol ??  Send us a message about you issues with MetaMask or contact us via email for quick responsed 
(meta.mask.help@mail.com) “Start a Conversation” 

We never DM. NEVER share your Secret Recovery Phrase with any site or person. Verify links are legitimate. Contact us now
( meta.mask.help@mail.com)

**Comment by firnprotocol** [comment]
ok wait but that's absurd, there is an app MetaMask - Flask (Early Access) in the google PlayStore.

**Comment by firnprotocol** [comment]
are you saying that that app is actually completely and functionally identical to the standard MetaMask? or.....what?
