### ISSUE TITLE
[Bug]: Nonce not updated after Speed Up and a pending Transaction

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-mobile#7312]
### Describe the bug

**Problem**: whenever I perform a transaction with low gas, and before being Confirmed, I perform another transaction, if I then Speed Up the first one, once they are both Confirmed, the next transaction I trigger will have an incorrect nonce value (1 less than expected). Example:
- Trigger Transaction A with low gas --->  nonce 12
- Trigger Transaction B without waiting for A to being confirmed ---> nonce 13
- Speed Up Transaction A
- Both transactions are now Confirmed
- Trigger Transaction C ---> nonce is set to 13

### Expected behavior

Nonce should be updated always to the correct last value

### Screenshots

https://github.com/MetaMask/metamask-mobile/assets/54408225/ee876c90-ca8c-43d2-a624-d1245088a239

### Steps to reproduce

1. Enable Nonce from Advanced Settings
2. Perform a Send tx with low gas so it's not confirmed immediately
3. Perform a Send tx with normal gas values, without first transaction being confirmed
4. Speed up the first transactions
5. Once 2 transactions are confirmed, initiate another Send tx
6. See how nonce is not updated to the last value
7. Try to perform the tx
8. Get incorrect nonce error

### Version

main (possibly an old issue)

### Build type

None

### Device

Pixel 6

### Operating system

Android

**Comment by OGPoyraz** [comment]
It correctly calculate the nonce on "Send tx" screen, and I was able to get tx confirmed properly. 
@sleepytanya may I ask if you could try this as well?

**Comment by sleepytanya** [comment]
@OGPoyraz I can consistently reproduce this bug.
MetaMask v7.12.3, real Samsung device, custom nonce is enabled:

https://github.com/MetaMask/metamask-mobile/assets/104780023/711fca28-07dd-48cc-808c-9b7659ebff0c

**Comment by OGPoyraz** [comment]
This is `7.12.5` (current main) with iOS physical device.
https://github.com/MetaMask/metamask-mobile/assets/7644512/b850f03b-320f-4873-a72e-9e7186000ec1

As a last resort, could you please test it on latest (`7.12.5`)?
If you see the issue again then it could be Android issue (chances are low) so I could pass it to @vinistevam

**Comment by sleepytanya** [comment]
Current 7.12.5 physical Android device (still see the nonce error):

https://github.com/MetaMask/metamask-mobile/assets/104780023/2a54990f-a8cd-4291-86df-bea2150c910d

**Comment by sleepytanya** [comment]
Another physical Android,  MetaMask 7.12.5  -  the error:

https://github.com/MetaMask/metamask-mobile/assets/104780023/360f581d-baed-4ad7-98fa-159ec7f424c8

**Comment by vinistevam** [comment]
After a few tries I managed to reproduce it.
I assume that locally the nonce is set to the latest tx nonce even if it is a lower nonce.
I'm still investigating where is the place that is saving the nonce without checking if a higher nonce was saved previously.

https://github.com/MetaMask/metamask-mobile/assets/45455812/b0732f3b-1a1a-4dd4-b2b4-b9297c5c6213
