### ISSUE TITLE
[Bug]: Typed Signatures V3/4 display message when not following primary type

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-mobile#7316]
### Describe the bug

**Problem**: whenever a dapp proposes to Sign a Typed v3/4 message with a primary type that does not match the `message` object, we can see how the signature is still displayed and you can proceed to sign normally.
Notice when verifying this will fail.

### Expected behavior

Not sure what is the expected behaviour here and if we can take as reference Extension, or is there an issue there too. Reasoning:
- `primaryType` should assign the format of the message
- if the message does not comply with the `primaryType` should we:
  - not display the message at all (see Extension)
  - display the message, but let the user know it's not a correct Typed4 signature?
  - other?

### Screenshots

https://github.com/MetaMask/metamask-mobile/assets/54408225/12ddb5e5-d3ad-451c-aee6-065e79c9eabd

### Steps to reproduce

1. Checkout test dapp locally
2. Change Signature V4 for the code below
3. Run the test dapp
4. Click Typed Signature V4
5. See the that the message object is displayed

```
    const msgParams = {
      domain: {
        chainId: chainId.toString(),
        name: 'Ether Mail',
        verifyingContract: '0xCcCCccccCCCCcCCCCCCcCcCccCcCCCcCcccccccC',
        version: '1',
      },
      message: {
        test: 'lorem',
      },
      primaryType: 'EIP712Domain',
      types: {
        EIP712Domain: [
          { name: 'name', type: 'string' },
          { name: 'version', type: 'string' },
          { name: 'chainId', type: 'uint256' },
          { name: 'verifyingContract', type: 'address' },
        ],
      },
    };
```

### Version

main (but an old issue)

### Build type

None

### Device

Pixel 6

### Operating system

Android

**Comment by bschorchit** [comment]
I've shared this with Devex team as we probably should be validating specs on the API level

**Comment by vandan** [comment]
The system does check against the following JSON Schema:
https://github.com/MetaMask/eth-sig-util/blob/main/src/sign-typed-data.ts#L108-L130
Currently it's not that specific (probably to allow for flexibility).
Removing devex for now.
