### ISSUE TITLE
[Bug]: Gas too low warning on opBNB network 

### ISSUE THREAD

**Issue by bschorchit** [MetaMask/metamask-mobile#7321]
### Describe the bug

When on opBNB network, sometimes MM shows a gas fee too low warning and the gas value doesn't match what is being sent by the gas API. 

### Expected behavior

Gas suggested in MM matches gas values sent by the gas API.

### Screenshots

![IMG_0842](https://github.com/MetaMask/metamask-mobile/assets/34968356/88f940f0-f382-44cf-9280-7de50bad84f8)

### Steps to reproduce

The team that reported the issue didn't shared, but I was able to reproduce it by not having funds in my account (similar to the pattern reported [here](https://github.com/MetaMask/metamask-mobile/pull/6287#issuecomment-1641801950)). In the screenshot shared by then, the account did have enough funds for gas + amount so this might be happening also for transactions that are not likely to fail?

### Version

unknown

### Build type

None

### Device

unknown

### Operating system

Other (please elaborate in the "Additional Context" section)

### Additional context

[Slack thread](https://consensys.slack.com/archives/CBW7S9FSN/p1695403273809979)

**Comment by huihzhao** [comment]
The transaction can still proceed when you see this warning.

**Comment by hilvmason** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/-Confirmations-Secure-UX-6245e6e2348677001213b8d2/issues/MetaMask/metamask-mobile/7321?planning-poker) with Zenhub @blackdevelopa @digiwand @jpuri @seaona @segun

**Comment by bschorchit** [comment]
This is currently in api team backlog for further investigation
