### ISSUE TITLE
[Bug]: Rejecting a Send ETH with Hardware Wallet empties gas values

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-mobile#7332]
### Describe the bug

**Problem:** whenever we reject scanning a Send ETH while using a hardware wallet (keystone), we can see how we stay on the Confirmation screen and the gas values are then emptied. Trying to confirm the tx again leas to invalid amount error, since gas is empty and there is no way to edit it

### Expected behavior

- Gas should not be emptied
- Gas should still be able to edit
- Transaction should still be able to be confirmed again?

cc @bschorchit 

### Screenshots

https://github.com/MetaMask/metamask-mobile/assets/54408225/090da544-5660-4bd0-81f5-bcfacefa607e

### Steps to reproduce

1. Import a Hardware wallet account
2. Start a Send ETH
3. Add amount and recipient
4. Click Scan with Hardware wallet
5. Cancel the scan
6. See gas values are now emptied
7. Try to Confirm again
8. Tx is invalid as there are no gas values and it's not possible to edit

### Version

Happening in prod `7.7.0` (possibly an old issue)

### Build type

None

### Device

Pixel 6 + Keystone

### Operating system

Android

**Comment by bschorchit** [comment]
Expected behavior: 
Rejecting the scan should reject the transaction and close the confirmation

**Comment by seaona** [comment]
This issue is still present
