### ISSUE TITLE
[Bug]: `Approval request with id not found` after rejecting a Send from a dapp with Hardware Wallet

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-mobile#7333]
### Describe the bug

**Problem**: whenever we are using a Hardware wallet account (Keystone) and trigger a send ETH from a dapp, if we Reject the scan and click Confirm again, the transaction is closed with the error `Approval request with id not found`

### Expected behavior

After rejecting the scan, we should be able to confirm again the transaction and no error should be displayed.

### Screenshots

https://github.com/MetaMask/metamask-mobile/assets/54408225/6cf665fd-9812-4a13-ada3-0d94dc4ab5e7

### Steps to reproduce

1. Import a hardware wallet account
2. Trigger a Send ETH from a dapp
3. Click Confirm
4. Cancel the Scan
5. Click Confirm again
6. See tx is closed and error appears

### Version

7.8.0 production (but seems an old issue)

### Build type

None

### Device

Pixel 6 + Keystone

### Operating system

iOS, Android

**Comment by bschorchit** [comment]
> Expected behavior
> After rejecting the scan, we should be able to confirm again the transaction and no error should be displayed.

I believe the expected behavior is rejecting the transaction when the user clicks reject on the qr modal. Clicking there should close the confirmation.
