### ISSUE TITLE
[Bug]: The browser in the Metamask wallet under IOS cannot send transactions

### ISSUE THREAD

**Issue by TonightCta** [MetaMask/metamask-mobile#7342]
### Describe the bug

I cannot call the network contract in the Metamask built-in browser under IOS. He told me about ‘Internal JSON-RPC’ and some errors thrown under Metamask.app. The same contract does not have such problems in the browser extension.

### Steps to reproduce

1.Connect Network
2.Send transaction

### Version

7.7.0(1171)

### Build type

None

### Device

iPhone 14 Pro(IOS 16.6.1)

### Operating system

iOS

**Comment by anaamolnar** [comment]
Hello, @TonightCta. Thanks for reporting! Please ensure you are using the correct network details for the chain you are trying to perform this transaction on and that you have enough native funds to pay for the gas fee. Please let me know if you continue to experience this after ensuring the above. Thank you!
