### ISSUE TITLE
[Bug]:  The message sign function does not work well. [android mobile + metamask mobile + walletconnect ]

### ISSUE THREAD

**Issue by siosio34** [MetaMask/metamask-mobile#7370]
### Describe the bug

The message sign function does not work well. [android mobile + metamask mobile + walletconnect]

metamask mobile(7.6.0)
walletconnect(2.8.4)
wagmi

The sign message seemed to work well previously, but it doesn't seem to work well after adding a polygon chain to the JSONProvider.

Could this be related?

### Expected behavior

When calling sign message, I want a sign modal to appear in the MetaMask mobile app.

### Steps to reproduce

1. connect wallet 
2. call sign function

### Version

7.6.0

### Build type

None

### Device

android galaxy s23

### Operating system

Android

### Severity

- All Android users using our service cannot sign.

**Comment by anaamolnar** [comment]
Hello, @siosio34. Thanks for reporting! Please make sure you update to version 7.8.0. We just began the rollout for this version. Please let us know if the issue continues to occur after updating. Thank you!
