### ISSUE TITLE
[Bug]:  When a personal_sign is requested, the signature window appears only the first time, and after that, the signature window appears and disappears automatically.

### ISSUE THREAD

**Issue by siosio34** [MetaMask/metamask-mobile#7383]
### Describe the bug

We are currently implementing the sign Message function using walletconnect + android + metamask mobile. When you call personal_sign, a signature window appears in MetaMask at first, but once you sign, when you request personal_sign again, the signature window automatically turns off as soon as it turns on.

### Expected behavior

I would like to implement it so that the signature window does not automatically disappear and returns to the Dapp, but only returns to the Dapp by the user's action.

### Steps to reproduce

1. connect wallet
2. call personal_sign sign message
3. accept sign message modal
4. again call personal_sign message

### Version

7.7.0

### Build type

None

### Device

android s23

### Operating system

Android

**Comment by anaamolnar** [comment]
Hello, @siosio34. Thanks for reporting! I will pass this on to the team.

**Comment by siosio34** [comment]
@anaamolnar  nono this issue is my mistake. i fix my provider code then this issue work proper. sorry.
