### ISSUE TITLE
[Bug]: Speed UP/Cancel modal not closed after transaction is confirmed

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-mobile#7387]
### Describe the bug

**Problem:** whenever I have send a transaction (before being confirmed) I can click on Speed Up / Cancel the transaction. Whenever the modal is open, it remains open even after the initial transaction has been confirmed.

### Expected behavior

Once the initial transaction has been confirmed, the modal for Speeding up / Cancel that transaction should be closed, as it's not possible to speed up or cancel that transaction anymore.

This is the behaviour we observe on extension cc @bschorchit 

### Screenshots

https://github.com/MetaMask/metamask-mobile/assets/54408225/24bd51fe-cb14-41bb-9c3a-e092cf15039f

Extension:

https://github.com/MetaMask/metamask-mobile/assets/54408225/e2bf780a-8ddb-4da4-acd5-f9d8b895273f

### Steps to reproduce

1. Perform a transaction
2. Before being confirmed, click speed up / cancel
3. Wait with the modal open
4. Tx is confirmed
5. Try to Confirm the Spped up or cancel
6. See error
7. Try again (see you can try infinitely)

### Version

7.7.0 production (possible an old issue)

### Build type

None

### Device

Pixel 

### Operating system

Android

**Comment by seaona** [comment]
This issue is still present

**Comment by sleepytanya** [comment]
Present in v7.27.0:


https://github.com/user-attachments/assets/d94838b3-5f9b-42b3-ad39-da3b3fd8d81e
