### ISSUE TITLE
[Bug]: Confirm transaction button sometimes is disabled on the testnet rpc.

### ISSUE THREAD

**Issue by yamen98** [MetaMask/metamask-mobile#7388]
### Describe the bug

I am trying to send amount by my application using MetaMask, but when confirmation dialog appears on MetaMask, the Confirm button is disabled and I cannot click confirm the transaction.

There is no error shown on transaction details on MetaMask.

- Connection to MetaMask Code:

```
ConnectResponse resp = await (await connector).connect(requiredNamespaces: {
  'eip155': const RequiredNamespace(
    chains: ['eip155:100'], // Ethereum chain
    methods: [
      'eth_sendTransaction'
    ],
    events: [], // Resettable Methods
  ),
});
```

- Send Transaction in MetaMask Code:

```
Web3App connectorAsync = await connector;
EtherAmount gasPrice = await ethereum.getGasPrice();
String data = await connectorAsync.request(
  topic: session.topic,
  chainId: "eip155:100",
  request: SessionRequestParams(method: "eth_sendTransaction", params: [
    {
      "from": fromAddress,
      "to": receiverAddress,
      "value": BigInt.from(amount * 1000000000000000000).toRadixString(16),
      "gas":gasPrice.getInEther.toRadixString(16),
    },
  ]),
);
```

### Screenshots

![photo_2023-10-03_22-07-45](https://github.com/MetaMask/metamask-mobile/assets/106963641/db210b3b-3638-474f-a4d3-dcc3229bd9e7)

### Steps to reproduce

Steps from dApp application.
It is send transaction steps

### Version

7.8.0

### Build type

None

### Device

Xiaomi Note 8 Pro

### Operating system

Android

**Comment by anaamolnar** [comment]
Hello, @yamen98. Thanks for reporting! I will pass this on to the team.

**Comment by bschorchit** [comment]
@yamen98 could you share the test networks details that you saw this issue on? This will help us try to reproduce it. Ty!

**Comment by YAMMEN98** [comment]
Sorry for the late response, but the problem is 'currently'.  It was solved and no longer exists. Have you solved anything or should I send the testnet link?
@bschorchit
