### ISSUE TITLE
[Bug]: Import ERC721 does not display the Token Name anymore

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-mobile#7395]
### Describe the bug

**Problem**: whenever I am importing the ERC721 test dapp token, I can see how the token name is not displayed anymore.

### Expected behavior

Ideally, we should display the token image but since this was not supported before neither, I guess the fallback should be to display the token name as we did before (see images below)

### Screenshots

Now (`7.9`):

![Screenshot from 2023-10-05 13-03-19](https://github.com/MetaMask/metamask-mobile/assets/54408225/b5d202ab-7c28-401b-9998-1884e9475619)

Before (production `7.7`): 
![Screenshot_20231005-130255_MetaMask](https://github.com/MetaMask/metamask-mobile/assets/54408225/51a77302-6052-47f0-9e47-3d850c2bcf2c)

### Steps to reproduce

1. Go to the test dapp
2. Deploy an ERC721 contract
3. Mint some tokens
4. Import a token to your wallet
5. See no token image nor name is displayed anymore

### Version

`7.9`

### Build type

None

### Device

Pixel 6 + iPhone

### Operating system

iOS, Android

**Comment by vania221** [comment]
> ### Опишіть помилку
> **Проблема** : щоразу, коли я імпортую тестовий маркер dapp ERC721, я бачу, як назва маркера більше не відображається.
> 
> ### Очікувана поведінка
> В ідеалі ми повинні відобразити зображення маркера, але оскільки це також не підтримувалося раніше, я думаю, резервним варіантом має бути відображення імені маркера, як ми робили раніше (див. зображення нижче)
> 
> ### Скріншоти
> Зараз ( `7.9`):
> 
> ![Скріншот від 05.10.2023 13.03.19](https://user-images.githubusercontent.com/54408225/272880858-b5d202ab-7c28-401b-9998-1884e9475619.png)
> 
> Раніше (виробництво `7.7`): ![Скріншот_20231005-130255_MetaMask](https://user-images.githubusercontent.com/54408225/272880825-51a77302-6052-47f0-9e47-3d850c2bcf2c.jpg)
> 
> ### Кроки для відтворення
> 1. Перейдіть до тестової програми
> 2. Розгорніть контракт ERC721
> 3. Викарбуйте кілька жетонів
> 4. Імпортуйте токен у свій гаманець
> 5. Більше не відображається ні зображення маркера, ні ім’я
> 
> ### Повідомлення про помилки або журнал
> _Немає відповіді_
> 
> ### Версія
> `7.9`
> 
> ### Тип збірки
> Жодного
> 
> ### пристрій
> Pixel 6 + iPhone
> 
> ### Операційна система
> iOS, Android
> 
> ### Додатковий контекст
> _Немає відповіді_
> 
> ### Суворість
> _Немає відповіді_
