### ISSUE TITLE
[Bug]: Sdk method remains pending when pressing outside the "eth_requestAccounts" modal

### ISSUE THREAD

**Issue by judeProground** [MetaMask/metamask-mobile#7423]
### Describe the bug

When pressing outside the connect modal that appears upon opening a deep link using `provider.request({ method: "eth_requestAccount", params: [] })` from the MetaMask SDK on the mobile application, there is no response or rejection. However, it works fine when pressing the cancel or connect button.

It could be an issue with the MetaMask SDK, but based on [this issue](https://github.com/MetaMask/metamask-mobile/issues/6855), it seems to be a similar situation. 

### Screenshots

![IMG_0482](https://github.com/MetaMask/metamask-mobile/assets/122759638/f17cdfba-f85b-4a4a-90f8-17d6a9e6e035)

### Steps to reproduce

1. Go metamask-sdk react-native [examples](https://github.com/MetaMask/metamask-sdk/tree/main/packages/devreactnative)
2. build app and try to call `provider.request({ method: "eth_requestAccount", params: [] })` or `sdk.connect` 
3. click outside the connect modal (screenshot above) 

### Version

v7.8.0 (1174)

### Build type

None

### Device

iPhone XR real device

### Operating system

iOS

**Comment by christopherferreira9** [comment]
Hi @judeProground ! This is a known behaviour and we will look for a solution that can applied to these situations. We will keep this issue updated as soon as we do. Thank you for reporting!

**Comment by judeProground** [comment]
Hi @christopherferreira9! Thank you for your response. 

I apologize for bothering you, but I'm keep facing some issues. MetaMask Android mobile app(v.7.8.0) is providing very delayed responses for "eth_requestAccounts" today. After the "Connecting..." modal closes, there's no response, and it automatically returns to my dApp after about 50 seconds. Last week, I didn't encounter any issues during multiple tests, so could you please take a look at this problem as well?

To provide more details, the initial connection receives a fast response, but when both the dApp and the MetaMask app are restarted and try to connect, the response is delayed, as shown in the video. Also, `connect` event comes right after the MetaMask app's modal is closed, but `provider.request` method is still not resolved.

This type of app-to-app transition using deep links feels unnatural and seems difficult for users to use at a production level. Would developing a web page and using the MetaMask app's in-browser feature be a more stable option?

https://github.com/MetaMask/metamask-mobile/assets/122759638/9d8bec7a-6dc1-405a-8e9f-a3d3e553b24b
