### ISSUE TITLE
Create component: Address Display

### ISSUE THREAD

**Issue by georgewrmarshall** [MetaMask/metamask-mobile#7485]
### Description
Create Address Display component to display an ethereum addresses. 

Related issues:
- https://github.com/MetaMask/metamask-extension/issues/20966

### Technical Details (Things to think about)
- It should at minimum show 12 characters (first 7 + last 5)
- Truncation should happen in the middle of the address
- Displaying as checksum
- Way to view full address
- Responsiveness can the address take up as much space as available?

### Acceptance Criteria
TBC

**Comment by AlexJupiter** [comment]
Hey @georgewrmarshall , do you have any rough designs on this at all? This is something that @raulmono might look at soon.

**Comment by georgewrmarshall** [comment]
> Hey @georgewrmarshall , do you have any rough designs on this at all? This is something that @raulmono might look at soon.

We do not, that would be great! We could use @raulmono's work and integrate it into the Design System if it's on his radar

**Comment by raulmono** [comment]
It's on my radar 📻 – I'll have something tangible soon
