### ISSUE TITLE
Migrate chain id from decimal to hexadecimal

### ISSUE THREAD

**Issue by tommasini** [MetaMask/metamask-mobile#7490]
### What is this about?

The main focus of this pull request is to migrate chain id from decimal format to hexadecimal format and update the controllers that support that chain id format. There is also another small breaking changes that some of these controllers updates need, specific to each own.

We need to update the following controllers:
* AddressBookController -> ^3.0.0 
* AssetsController -> ^8.0.0
* ControllerUtils -> ^4.0.0
* GasFeeController -> ^6.0.0
* NetworkController -> ^9.0.0
* TransactionController -> ^6.0.0 (reach out to @matthewwalsh0 for rebase the patch)

Each of these controllers have also their breaking changes that we can find [here](https://github.com/MetaMask/core/commit/a99db4d3ce45fcad0f0af9b3c0fdd1ea7324a9f1#diff-d2a0ba2c61bc1c4862fd8cf52c56eeecf51037b90a3e9eb832b68ad9706195bc) 

When updating the transaction controller to v5, we should include eth_getTransactionCount middleware to preserve the behavior of that method (draft branch here: [MetaMask/metamask-mobile@refactor-get-transaction-count](https://github.com/MetaMask/metamask-mobile/tree/refactor-get-transaction-count?rgh-link-date=2023-08-31T16%3A19%3A38Z))
PR will need to be merged before or with v53. getNextNonce should have already been included in v49

[SwapsController have the chain ids on decimal format](https://github.com/MetaMask/metamask-mobile/blob/feat/swaps-on-send-flow/node_modules/@metamask/swaps-controller/dist/constants.d.ts#L2), we would need to patch that or convert from decimal to hexadecimal when interacting with the SwapsController. (Ideally we patch it and propose the change)

### Scenario

The E2E tests should cover swaps, AddressBook, part of the gasFeeController, and transactions controller. 

Scenarios to test manually:
This feature file: https://www.notion.so/Custom-Mainnet-feature-ef50c9aab25d4cb2963302d2a21ddfd2?pvs=4 

```
Scenario: Sending ERC721 between accounts

Given I imported the orangefox.eth test account
And I am on polygon with BoredHipster NFTs imported
When I send the BoredHipster NFT to myself
Then the transaction should submit successfully


Scenario: NFT auto detection

Given I imported the orangefox.eth test account
And I am on mainnet
When I go to the NFT auto detection tab
And I enable NFT auto detection
Then all my NFTs should import successfully


Scenario Outline: Account Token Detection
    Given I imported a wallet
    And I import the orange fox.eth account
    And I am on the <chain> network
    When I tap "{count} new tokens found in this account"
    Then I see the "{count} new tokens found" view
    And I can interact with detected tokens
    Examples:
      | chain       | 
      | Ethereum| 
      | Polygon  |
      | Binance  | 
      | Avalance |
 

Scenario: Add and Edit Network Name
    Given I imported a wallet with token balances
    When I add Polygon from the popular network list 
    Then I edit the network name to "My Renamed Network"
    And I confirm the changes
    Then I see "My Renamed Network" in the network list
    And Polygon is not on my network list
    And my account balance appears correctly


Scenario: Adding a network via chainlist

Given I am on the browser
And I visit chainlist.org
Then I am about to add "Celo" to my network list

```

### Technical Details

- Update each controller
- Verify each controller method and usability of it
- Re-do patches and remove unnecessary code (ControllerUtils, NetworkController, TransactionController, AssetsController)
- Migration of chainId from decimal to hexadecimal format
- Migration for change on networkController.providerConfig.rpcTarget to networkController.providerConfig.rpcUrl
- NetworkChainId replaced by ChainId
- Json from controller-utils is now deprecated, use the one from metamask/utils
- isSafeChainId method needs to be replaced for the on on controller-utils
- Visit every breaking change on each controller and address it
- The eth_getTransactionCount method behaves identically to how it did before

### Acceptance Criteria

 - [ ] All controller updated to the version above
-  [ ] Links to bitrise E2E test pipeline are added to the ticket description
- [ ] Trigger all the E2E tests against this PR:
      - Run e2e smoke test pipeline on bitrise
      - Run the regression tests locally: 
          - For android: `yarn test:e2e:android:debug --testNamePattern="Regression"`
          - For iOS: `yarn test:e2e:ios:debug --testNamePattern="Regression"`
          - Reach out to the QA team if you need assistance with this. 
- [ ] Ensure that all scenarios have passed. 
- [ ] Chain id is on decimal format on analytcs

### References

 - https://github.com/MetaMask/core/commit/a99db4d3ce45fcad0f0af9b3c0fdd1ea7324a9f1#diff-d2a0ba2c61bc1c4862fd8cf52c56eeecf51037b90a3e9eb832b68ad9706195bc

**Comment by tommasini** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/MetaMask-Mobile-5f984938ddc0e4001d4b79cb/issues/MetaMask/metamask-mobile/7490?planning-poker) with Zenhub @Cal-L @jpcloureiro @frankvonhoven @MarioAslau @NicolasMassart @SamuelSalas @chrisleewilcox @Andepande @cortisiko

**Comment by cortisiko** [comment]
was done as part of https://github.com/MetaMask/metamask-mobile/pull/7999
