### ISSUE TITLE
[Bug]: TypedData with BigInteger/uint256 Param Which Exceeds 16 Characters Does Not Prompt for Signature

### ISSUE THREAD

**Issue by underclockeddev** [MetaMask/metamask-mobile#7499]
### Describe the bug

While trying to perform an eth_signTypedData_v4 signature request through the WalletConnect SDK in Unity, if a BigInteger/uint256 property of the TypedData is more than 16 digits long, MetaMask will not prompt for the signature. But if I drop down to 16 or fewer digits, it will prompt me for the signature. I tried `9999999999999999999` (17x9's) as a literal and tried BigInteger.Parse("99....") and the outcome was the same, I did not get a prompt when the value was >16 digits.

I can work around this issue by changing the BigInteger into a string and passing in a stringified BigInt, but that's just a hacky workaround and loses the benefit of the strongly-typed nature of C#.

### Expected behavior

MetaMask should prompt user for signature

### Screenshots

![image](https://github.com/MetaMask/metamask-mobile/assets/71031886/11819d4c-6e77-43c0-bb1a-7bad7d1dffe1)

### Steps to reproduce

1. Create a Unity project with the WalletConnect + Nethereum packages
2. Build a `TypedData<Domain>` object with a `PrimaryType` of `Nethereum.ABI.EIP712.EIP2612.Permit`
3. Set one of the Permit's BigInteger values to a number with 17+ digits
4. Attempt to request a signature from the wallet e.g. `WalletConnectClient.Request<WCEthSignTypedDataV4, string>(topic, typedData, chainId);`

### Version

v7.8.0 (1174)

### Build type

None

### Device

Google Pixel 6a, with custom OS GrapheneOS

### Operating system

Android

### Additional context

Using the MetaMask Unity SDK, I did not run into this issue, it seemed to handle BigIntegers just fine. But using WalletConnect's Unity SDK I run into this issue. I thought it was a WalletConnect issue and raised an issue on their github https://github.com/WalletConnect/WalletConnectSharp/issues/135 but they could not reproduce the issue on other wallets, only MetaMask, so we deduced it is a MetaMask issue.

**Comment by Madeindreams** [comment]
This is because you are passing the value as an integer. 16 digits is the limit in javascript. Instead, you should pass the value as a string.

`Value = '9999999999999999000'`

**Comment by charlesteets** [comment]
I'm working in C#, not javascript. And I mentioned that I tried passing the value as a BigInteger 

>[I] tried BigInteger.Parse("99....") and the outcome was the same, I did not get a prompt when the value was >16 digits
