### ISSUE TITLE
[Bug]: Unable to copy the private key on mobile

### ISSUE THREAD

**Issue by Madeindreams** [MetaMask/metamask-mobile#7511]
### Describe the bug

Once we reveal the private key. It is not possible to copy the value.

### Expected behavior

Expecting to be able to copy the key

### Screenshots

Useless

### Steps to reproduce

Hold the button till you private key appear.
Hold the private key text to copy.
Copy option never comes up.

### Error messages or log output

```shell
NA
```

### Version

7.8.0

### Build type

None

### Device

Android Samsung 

### Operating system

Android

### Severity

Since it's impossible to copy and paste the private key. It requires us to write it down and leave a paper trail.

**Comment by DanielTech21** [comment]
Hello,

We cannot reproduce the issue of being unable to copy the private key from the MetaMask app on Andriod.
Can you ensure you do not have any security feature or app running to block from copying the private key?

**Comment by Madeindreams** [comment]
@DanielTech21 There is no such button

**Comment by Madeindreams** [comment]
I don't think i have any security feature that would prevent this button from showing up.

**Comment by DanielTech21** [comment]
@Madeindreams It would be great to better understand your device settings to find the reason why you cannot see the clipboard button after holding it to reveal the private key in your MetaMask app.
Can you please provide further details of your mobile device?
What is your screen size?
Do you use the screen zoom to a higher value?
What are your font settings?

**Comment by vania221** [comment]
> @MadeindreamsБуло б чудово краще зрозуміти налаштування вашого пристрою, щоб знайти причину, чому ви не бачите кнопку буфера обміну, утримуючи її, щоб відкрити закритий ключ у вашій програмі MetaMask. Чи можете ви надати додаткові відомості про свій мобільний пристрій? Який у вас розмір екрану? Ви використовуєте масштабування екрана до більшого значення? Які у вас налаштування шрифту?

**Comment by plasmacorral** [comment]
Sorry for the difficulty here, but thank you for taking the time to share this report.  I am not able to reproduce on my Samsung A515f running android 12, even with the font display at the largest and the zoom set at max. Is there any further info you can share to help us reproduce?

**Comment by plasmacorral** [comment]
Unable to reproduce and no additional information to aid in reproduction.  Please open a fresh issue and cite this one if this situation persists.
