### ISSUE TITLE
[Bug]: PPOM - See details arrow icon missmatch between platforms

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-mobile#7514]
### Describe the bug

**Problem**: Whenever details are hidden, we can see how the icon arrow is looking up, instead of looking down (see comparison with Extension). 

### Expected behavior

Not sure which one is correct and which one is wrong, but seems that Extension might be the correct one? cc @bschorchit 

### Screenshots

![image](https://github.com/MetaMask/metamask-mobile/assets/54408225/7f759967-815b-425f-b27d-4fbe543592d7)

### Steps to reproduce

1. Enable Blockaid
2. Go to the test dapp
3. Trigger a malicious signature
4. See arrow

### Version

Integrate PPOM branch  (behind feature flag) https://github.com/MetaMask/metamask-mobile/pull/7363
In main once the PR is merged

### Build type

None

### Device

Pixel 6

### Operating system

Android

**Comment by bschorchit** [comment]
cc: @SayaGT to confirm the correct behavior

**Comment by bschorchit** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/-Confirmations-Secure-UX-6245e6e2348677001213b8d2/issues/MetaMask/metamask-mobile/7514?planning-poker) with Zenhub @blackdevelopa @digiwand @jpuri @seaona @segun
