### ISSUE TITLE
[Bug]: PPOM - `Security Advice` vs `Powered by` discrepancy between platforms

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-mobile#7515]
### Describe the bug

**Problem:** In Extension we show `Powered by Blockaid` wheres in Mobile we show `Security advice by Blockaid`.
Should we consolidate this into the same message? cc @bschorchit 

### Expected behavior

which one is correct? cc @bschorchit 

### Screenshots

![Screenshot from 2023-10-16 13-07-24](https://github.com/MetaMask/metamask-mobile/assets/54408225/444d454b-8f3b-406e-a4d4-74565f356d36)

### Steps to reproduce

1. Enable Blockaid
2. Go to the test dapp
3. Trigger a malicious signature
4. See text

### Version

Integrate PPOM branch  (behind feature flag) https://github.com/MetaMask/metamask-mobile/pull/7363
In main once the PR is merged

### Build type

None

### Device

Pixel 6

### Operating system

Android

**Comment by bschorchit** [comment]
Yes, thank you for catching that! We should use `Powered by`
