### ISSUE TITLE
[Bug]: PPOM - Malicious transactions triggered from Deeplinks are not flagged

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-mobile#7543]
### Describe the bug

**Problem**: malicious transactions triggered from Deeplinks are not flagged by Blockaid

### Expected behavior

Malicious transactions triggered from deeplinks should also be flagged by Blockaid.

### Screenshots

https://github.com/MetaMask/metamask-mobile/assets/54408225/edbe2046-6046-4c26-a2ad-3037807d9b71

### Steps to reproduce

1. Generate a malicious link
2. Scan the QR code
3. See how no warning appears

To generate a malicious link. You can use:
- https://metamask.github.io/metamask-deeplinks/# and add the malicious recipeint 0x5FbDB2315678afecb367f032d93F642f64180aa3
-Or modify any links from here, to use the same data as the test dapp https://cortisiko.github.io/ I.e.

Links
- Send ETH: https://metamask.app.link/send/0x5FbDB2315678afecb367f032d93F642f64180aa3?value=3e13
- Malicious Approve: https://metamask.app.link/approve/0x4fabb145d64652a948d72533023f6e7a623c7c53@1/approve?address=0xe50a2dbc466d01a34c3e8b7e8e45fce4f7da39e6&uint256=3e18

### Version

Integrate PPOM branch  (behind feature flag) https://github.com/MetaMask/metamask-mobile/pull/7363
In main once the PR is merged
 
### Build type

None

### Device

Pixel 6

### Operating system

Android

**Comment by seaona** [comment]
great finding @jpuri !! do you think we need separate tickets for that? or is it the same fix for all the cases?

**Comment by jpuri** [comment]
I reverted the changes in my [PR](https://github.com/MetaMask/metamask-mobile/pull/7680) and need to re-open this issue as:

1. The issue does not address all deeplink transactions, only send ones are addressed
2. Validation is now done for all transaction, in fact its triggered from `componentDidUpdate` in this component and thus can result in validation running multiple times: https://github.com/MetaMask/metamask-mobile/pull/7705/files#diff-a98dd54fd9ed5e3af27fda49f55d518002dcd6dd934915bc3c94da5433c5b8f0
