### ISSUE TITLE
[Bug]: Connecting to Optimism Failed, dApp thinks Ethereum

### ISSUE THREAD

**Issue by mccabe-david** [MetaMask/metamask-mobile#7555]
### Describe the bug

On a React Native app using WalletConnectModal from '@walletconnect/modal-react-native', MetaMask mobile scans the QR Code provided while connected to Optimism, but the app has a chainId of 1 instead of 10.

    import {useWalletConnectModal, WalletConnectModal} from '@walletconnect/modal-react-native';

    function MyComponent()
    {
        const {isConnected, provider, open} = useWalletConnectModal();

        const disconnectWallet = () => {
            if (isConnected) {
                setConnectionID(null);
                return provider?.disconnect();
            }
        }

        const w3p = useMemo(
            () => (provider ? new ethers.providers.Web3Provider(provider) : undefined),
            [provider],
        );

        const [connectionID, setConnectionID] = useState(null);

        useEffect(() => {
            async function bar(){
                try {
                    if (connectionID == null){
                        let {chainId} = await w3p.getNetwork();
                        setConnectionID(chainId);
                    }
                }
                catch (error){
                    console.info("connection not yet established", isConnected);
                }
          }
          bar();
        }, [isConnected]);

      console.log("current chainId: " + connectionID);
      return (<Text>{connectionID}</Text>)
    }

### Expected behavior

I expected the chainId to be 10, but it was 1. 

### Screenshots

![image0](https://github.com/MetaMask/metamask-mobile/assets/43038510/451ccf34-1e81-4374-a7aa-41553a3c6f01)

### Steps to reproduce

1. Create and run the React Component with the code above
2. Create an account on Optimism (You may need to fund it)
3. Switch Networks in app to Optimism
4. Scan provided QR Code from WalletConnect

### Error messages or log output

```shell
LOG  Shims Injected:
 LOG    - atob
 LOG    - btoa
 LOG    - nextTick
 LOG    - FileReader.prototype.readAsArrayBuffer
 LOG  current chainId: null
 INFO  connectionID not yet established false
 INFO  {"context": "core"} Core Initialization Success
 INFO  {"context": "client"} SignClient Initialization Success
 LOG  current chainId: null
 LOG  current chainId: null
 INFO  Cleaning up inactive pairings...
 INFO  Inactive pairings cleared: 0
 INFO  {"context": "core"} {"context": "core/relayer"} {"context": "core/relayer/subscription"} Emitting subscription_created
 INFO  {"context": "core"} {"context": "core/expirer"} Emitting expirer_created
 INFO  {"context": "core"} {"context": "core/history"} Emitting history_created
 INFO  {"context": "core"} {"context": "core/expirer"} Emitting expirer_created
 INFO  {"context": "core"} {"context": "core/history"} Emitting history_updated
 INFO  {"context": "core"} {"context": "core/relayer"} {"context": "core/relayer/subscription"} Emitting subscription_created
 INFO  {"context": "core"} {"context": "core/expirer"} Emitting expirer_created
 INFO  {"context": "core"} {"context": "core/history"} Emitting history_created
 INFO  {"context": "core"} {"context": "core/history"} Emitting history_updated
 INFO  {"context": "core"} {"context": "core/expirer"} Emitting expirer_created
 LOG  current chainId: null
 LOG  current chainId: null
 LOG  current chainId: null
 INFO  {"context": "core"} {"context": "core/history"} Emitting history_created
 INFO  {"context": "core"} {"context": "core/history"} Emitting history_updated
 LOG  current chainId: 1
 INFO  {"context": "core"} {"context": "core/history"} Emitting history_created
```

### Version

v7.8.0

### Build type

None

### Device

IPhone 13 - IOS 16.6.1

### Operating system

iOS

### Additional context

After additional disconnects/reconnects, the chainId magically becomes 10:

 LOG  current chainId: null
 LOG  current chainId: null
 LOG  current chainId: null
 INFO  {"context": "core"} {"context": "core/history"} Emitting history_created
 INFO  {"context": "core"} {"context": "core/history"} Emitting history_updated
 LOG  current chainId: 1
 INFO  {"context": "core"} {"context": "core/history"} Emitting history_created
 INFO  {"context": "core"} {"context": "core/relayer"} {"context": "core/relayer/subscription"} Emitting subscription_created
 INFO  {"context": "core"} {"context": "core/relayer"} {"context": "core/relayer/subscription"} Emitting subscription_created
 INFO  {"context": "core"} {"context": "core/expirer"} Emitting expirer_expired
 LOG  current chainId: 1
 LOG  current chainId: 1
 LOG  current chainId: null
 INFO  {"context": "core"} {"context": "core/history"} Emitting history_created
 INFO  {"context": "core"} {"context": "core/relayer"} {"context": "core/relayer/subscription"} Emitting subscription_deleted
 LOG  current chainId: null
 LOG  current chainId: null
 INFO  connectionID not yet established false
 INFO  {"context": "core"} {"context": "core/expirer"} Emitting expirer_deleted
 INFO  Cleaning up inactive pairings...
 INFO  {"context": "core"} {"context": "core/expirer"} Emitting expirer_expired
 INFO  {"context": "core"} {"context": "core/expirer"} Emitting expirer_created
 INFO  Inactive pairings cleared: 1
 INFO  {"context": "core"} {"context": "core/relayer"} {"context": "core/relayer/subscription"} Emitting subscription_deleted
 LOG  current chainId: null
 LOG  current chainId: null
 INFO  connectionID not yet established false
 INFO  Cleaning up inactive pairings...
 INFO  Inactive pairings cleared: 0
 LOG  current chainId: null
 INFO  {"context": "core"} {"context": "core/relayer"} {"context": "core/relayer/subscription"} Emitting subscription_created
 INFO  {"context": "core"} {"context": "core/expirer"} Emitting expirer_created
 INFO  {"context": "core"} {"context": "core/history"} Emitting history_created
 INFO  {"context": "core"} {"context": "core/expirer"} Emitting expirer_created
 INFO  {"context": "core"} {"context": "core/history"} Emitting history_created
 INFO  {"context": "client"} Unsupported request method wc_pairingDelete
 INFO  {"context": "core"} {"context": "core/relayer"} {"context": "core/relayer/subscription"} Emitting subscription_deleted
 INFO  {"context": "core"} {"context": "core/expirer"} Emitting expirer_deleted
 LOG  current chainId: null
 INFO  Cleaning up inactive pairings...
 INFO  Inactive pairings cleared: 0
 LOG  current chainId: null
 INFO  {"context": "core"} {"context": "core/relayer"} {"context": "core/relayer/subscription"} Emitting subscription_created
 INFO  {"context": "core"} {"context": "core/expirer"} Emitting expirer_created
 INFO  {"context": "core"} {"context": "core/history"} Emitting history_created
 INFO  {"context": "core"} {"context": "core/expirer"} Emitting expirer_created
 INFO  {"context": "core"} {"context": "core/history"} Emitting history_updated
 INFO  {"context": "core"} {"context": "core/relayer"} {"context": "core/relayer/subscription"} Emitting subscription_created
 INFO  {"context": "core"} {"context": "core/expirer"} Emitting expirer_created
 INFO  {"context": "core"} {"context": "core/history"} Emitting history_created
 INFO  {"context": "core"} {"context": "core/history"} Emitting history_updated
 INFO  {"context": "core"} {"context": "core/expirer"} Emitting expirer_created
 ERROR  {"context": "core"} {"context": "core/pairing"} {"context": "core/pairing/pairing"} No matching key. pairing: 31c71df0df972b338096d20bab922a380964215abae65598debb0f30a759d20b
 INFO  {"context": "core"} {"context": "core/expirer"} Emitting expirer_created
 LOG  current chainId: null
 LOG  current chainId: null
 LOG  current chainId: null
 LOG  current chainId: 10
 INFO  {"context": "core"} {"context": "core/history"} Emitting history_created
 INFO  {"context": "core"} {"context": "core/history"} Emitting history_updated
 WARN  Possible Unhandled Promise Rejection (id: 0):
Error: No matching key. pairing: 31c71df0df972b338096d20bab922a380964215abae65598debb0f30a759d20b
Error: No matching key. pairing: 31c71df0df972b338096d20bab922a380964215abae65598debb0f30a759d20b
    at getData 
    ... ( I removed the rest of the log here)
 INFO  {"context": "core"} {"context": "core/history"} Emitting history_created

**Comment by mccabe-david** [comment]
Not sure why connectionID is ever 1, but the fix is to replace
`
const w3p = useMemo(
        () => (provider ? new ethers.providers.Web3Provider(provider) : undefined),
        [provider],
    );
`
with
`
const w3p = useMemo(
        () => {
            let rez = provider ? new ethers.providers.Web3Provider(provider) : undefined;
            provider?.on("session_event", ( event ) => {
                try {
                    if (event.params.event.name == "chainChanged"){
                        setConnectionID(event.params.event.data);
                    }
                }
                catch {
                    console.log("session_event", event,);
                }
            });
            return provider ? rez : undefined
        },
        [provider, connectionID],
    );
`

**Comment by anaamolnar** [comment]
Hello, @mccabe-david. Thanks for reporting! I will pass this to the appropriate team. They will follow up once they have an update on this.

**Comment by abretonc7s** [comment]
It seems to be an issue on the `@walletconnect/modal-react-native` with the wallet connect client flow, could try to post the issue on their github?
