### ISSUE TITLE
[Bug]: `NEAR` token transfer amount does not correspond to the dapp suggested one

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-mobile#7572]
### Describe the bug

**Problem:** whenever triggering a NEAR transfer from a dapp, the suggested amount does not correspond to the one seen in the Confirmations screen.

**Note:** that NEAR has 24 decimals, so maybe this affects the way the value is parsed.
**Note 2:** the hex data is correct, so if the tx is sent, it seems that the value will be the one suggested by the dapp - but does not correspond by the one seen in the UI

### Expected behavior

The dapp suggested value should be the one displayed on the Confirmations screen

### Screenshots/Recordings

https://github.com/MetaMask/metamask-mobile/assets/54408225/253274ce-29fd-40c9-8b34-2fd8d9f77389

### Steps to reproduce

1. Select Mainnet
2. Go to this contract https://etherscan.io/token/0x85f17cf997934a597031b2e18a9ab6ebd4b9f6a4#writeContract
3. Connect MM
4. Click transfer
5. Add any recipient and any amount
6. See how the amount in Confirmation screen is different

### Version

7.8.0 Seen on a feature branch, but after double-checking this is already happening in production `7.8.0`

### Build type

None

### Device

Pixel 6

### Operating system

Android

**Comment by vania221** [comment]
> ### Опишіть помилку
> **Проблема:** кожного разу, коли запускається переказ NEAR із dapp, запропонована сума не відповідає тій, що відображається на екрані підтвердження.
> 
> **Примітка:** NEAR має 24 знаки після коми, тому, можливо, це впливає на спосіб аналізу значення. **Примітка 2:** шістнадцяткові дані правильні, тому, якщо надіслано передачу, здається, що значення буде запропоноване dapp, але не відповідає тому, яке видно в інтерфейсі користувача
> 
> ### Очікувана поведінка
> Значення, запропоноване dapp, має бути таким, яке відображається на екрані підтвердження
> 
> ### Скріншоти/записи
>  біля передачі.mp4 
> ### Кроки для відтворення
> 1. Виберіть Mainnet
> 2. Перейдіть до цього контракту https://etherscan.io/token/0x85f17cf997934a597031b2e18a9ab6ebd4b9f6a4#writeContract
> 3. Підключіть ММ
> 4. Натисніть перенести
> 5. Додайте будь-якого одержувача та будь-яку суму
> 6. Подивіться, як відрізняється сума на екрані підтвердження
> 
> ### Повідомлення про помилки або журнал
> _Немає відповіді_
> 
> ### Версія
> 7.8.0 Виявлено на гілці функцій, але після повторної перевірки це вже відбувається у виробництві`7.8.0`
> 
> ### Тип збірки
> Жодного
> 
> ### пристрій
> Pixel 6
> 
> ### Операційна система
> Android
> 
> ### Додатковий контекст
> _Немає відповіді_
> 
> ### Суворість
> _Немає відповіді_
