### ISSUE TITLE
[Bug]: Autodetect tokens display Mainnet tokens on another network (MXC zkEVM Mainnet)

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-mobile#7587]
### Describe the bug

**Problem:** I have some tokens on Mainnet, which are auto-detected by the wallet. Whenever I switch to MXC zkEVM Mainnet network, those same tokens are still auto-detected (now with 0 balance).

### Expected behavior

We should not auto-detect mainnet tokens when I am on another network

### Screenshots/Recordings

https://github.com/MetaMask/metamask-mobile/assets/54408225/e532eb5d-5b7d-47d3-a280-6ab4fd12d29e

### Steps to reproduce

1. Select Mainnet and have some tokens auto-detected
2. Add MXC zkEVM Mainnet chain https://chainlist.org/?testnets=true&search=mxc+zk
3. Switch to this network
4. See how same tokens in step 1 are auto-detected in this new network

### Version

7.8.0 production (possibly old issue)

### Build type

None

### Device

Pixel 6

### Operating system

Android

**Comment by vania221** [comment]
> ### Опишіть помилку
> **Проблема:** у мене є кілька токенів у мережі Mainnet, які автоматично визначаються гаманцем. Кожного разу, коли я перемикаюся на мережу MXC zkEVM Mainnet, ті самі токени все одно виявляються автоматично (тепер із балансом 0).
> 
> ### Очікувана поведінка
> Ми не повинні автоматично виявляти маркери основної мережі, коли я перебуваю в іншій мережі
> 
> ### Скріншоти/записи
>  mobile-autodetect-tokens.mp4 
> ### Кроки для відтворення
> 1. Виберіть Mainnet і автоматично виявляйте деякі маркери
> 2. Додайте ланцюг основної мережі MXC zkEVM https://chainlist.org/?testnets=true&search=mxc+zk
> 3. Переключитися на цю мережу
> 4. Подивіться, як ті самі маркери на кроці 1 автоматично виявляються в цій новій мережі
> 
> ### Повідомлення про помилки або журнал
> _Немає відповіді_
> 
> ### Версія
> Версія 7.8.0 (можливо, стара версія)
> 
> ### Тип збірки
> Жодного
> 
> ### пристрій
> Pixel 6
> 
> ### Операційна система
> Android
> 
> ### Додатковий контекст
> _Немає відповіді_
> 
> ### Суворість
> _Немає відповіді_
