### ISSUE TITLE
[Bug]: Information modal does not dismiss when editing gas

### ISSUE THREAD

**Issue by wachunei** [MetaMask/metamask-mobile#7592]
### Describe the bug

When using the send flow the information modals from the gas editing UI are not responding to the dismiss X or backdrop press.

### Expected behavior

The information modal to be dismissed when pressing the X button or backdrop

### Screenshots/Recordings

https://github.com/MetaMask/metamask-mobile/assets/1024246/b494e523-cbd4-4cd9-b925-fd60af6c133f

![image](https://github.com/MetaMask/metamask-mobile/assets/1024246/91051429-4854-46eb-9ea9-c06258125f52)

### Steps to reproduce

1. Go to send flow
2. Create a transaction
3. Edit the gas values
4. Press information icons to show modals

### Version

7.8.0

### Build type

None

### Device

iPhone 13 Pro Max

### Operating system

iOS

**Comment by vania221** [comment]
> ### Опишіть помилку
> Під час використання потоку надсилання модальні відомості з інтерфейсу редагування газу не реагують на відхилення X або натискання фону.
> 
> ### Очікувана поведінка
> Інформаційний модаль, який буде закрито при натисканні кнопки X або фону
> 
> ### Скріншоти/записи
>  RRPeplay_Final1698168665.MP4 
> ![зображення](https://user-images.githubusercontent.com/1024246/277769379-91051429-4854-46eb-9ea9-c06258125f52.png)
> 
> ### Кроки для відтворення
> 1. Перейти до потоку надсилання
> 2. Створіть транзакцію
> 3. Відредагуйте значення газу
> 4. Натискайте інформаційні значки, щоб показати моди
> 
> ### Повідомлення про помилки або журнал
> _Немає відповіді_
> 
> ### Версія
> 7.8.0
> 
> ### Тип збірки
> Жодного
> 
> ### пристрій
> iPhone 13 Pro Max
> 
> ### Операційна система
> iOS
> 
> ### Додатковий контекст
> _Немає відповіді_
> 
> ### Суворість
> _Немає відповіді_

**Comment by vania221** [comment]
> ### Опишіть помилку
> Під час використання потоку надсилання модальні відомості з інтерфейсу редагування газу не реагують на відхилення X або натискання фону.
> 
> ### Очікувана поведінка
> Інформаційний модаль, який буде закрито при натисканні кнопки X або фону
> 
> ### Скріншоти/записи
>  RRPeplay_Final1698168665.MP4 
> ![image](https://user-images.githubusercontent.com/1024246/277769379-91051429-4854-46eb-9ea9-c06258125f52.png)
> 
> ### Кроки для відтворення
> 1. Перейти до потоку надсилання
> 2. Створіть транзакцію
> 3. Відредагуйте значення газу
> 4. Натискайте інформаційні значки, щоб показати моди
> 
> ### Повідомлення про помилки або журнал
> _Немає відповіді_
> 
> ### Версія
> 7.8.0
> 
> ### Тип збірки
> Жодного
> 
> ### пристрій
> iPhone 13 Pro Max
> 
> ### Операційна система
> iOS
> 
> ### Додатковий контекст
> _Немає відповіді_
> 
> ### Суворість
> _Немає відповіді_

**Comment by vania221** [comment]
> ### Опишіть помилку
> Під час використання потоку надсилання модальні відомості з інтерфейсу редагування газу не реагують на відхилення X або натискання фону.
> 
> ### Очікувана поведінка
> Інформаційний модаль, який буде закрито при натисканні кнопки X або фону
> 
> ### Скріншоти/записи
>  RRPeplay_Final1698168665.MP4 
> ![image](https://user-images.githubusercontent.com/1024246/277769379-91051429-4854-46eb-9ea9-c06258125f52.png)
> 
> ### Кроки для відтворення
> 1. Перейти до потоку надсилання
> 2. Створіть транзакцію
> 3. Відредагуйте значення газу
> 4. Натискайте інформаційні значки, щоб показати моди
> 
> ### Повідомлення про помилки або журнал
> _Немає відповіді_
> 
> ### Версія
> 7.8.0
> 
> ### Тип збірки
> Жодного
> 
> ### пристрій
> iPhone 13 Pro Max
> 
> ### Операційна система
> iOS
> 
> ### Додатковий контекст
> _Немає відповіді_
> 
> ### Суворість
> _Немає відповіді_

**Comment by vania221** [comment]
- type: textarea
  attributes:
    label: Operating System
    description: What operating system are you using?
    placeholder: "Example: macOS Big Sur"
    value: operating system
  validations:
    required: true
- type: dropdown
  attributes:
    label: Version
    description: What version of our software are you running?
    multiple: false
    options:
      - 1.0.2 (Default)
      - 1.0.3 (Edge)
    default: 0
  validations:
    required: true
- type: checkboxes
  attributes:
    label: Code of Conduct
    description: The Code of Conduct helps create a safe space for everyone. We require
      that everyone agrees to it.
    options:
      - label: I agree to follow this project's [Code of Conduct](link/to/coc)
        required: true
- type: markdown
  attributes:
    value: "Thanks for completing our form!"

**Comment by blackdevelopa** [comment]
Hey @wachunei, thanks for reporting this. However, seeing it's been reported already, I will be marking this as a duplicate of #6399, and a fix for this will be worked on.

**Comment by vania221** [comment]
> привіт@wachuneiдякую, що повідомили про це. Однак, оскільки про це вже повідомлялося, я позначаю це як дублікат #6399 , і буде працювати над виправленням цього.
