### ISSUE TITLE
Що саме за проблема  у вас сталася 

### ISSUE THREAD

**Issue by vania221** [MetaMask/metamask-mobile#7594]
### What is this about?

/ #7587 #7426 
![Screenshot_20231025_063700_Wallet](https://github.com/MetaMask/metamask-mobile/assets/129567053/78f014d7-a881-4dca-9063-21e37d9039d0)
@

### Scenario

[![.github/workflows/azure-webapps-node.yml](https://github.com/vania221/Zalipyha/actions/workflows/azure-webapps-node.yml/badge.svg?branch=main)](https://github.com/vania221/Zalipyha/actions/workflows/azure-webapps-node.yml)

**Comment by anaamolnar** [comment]
Hello, @vania221. Thank you for the report! Please provide more details about your issue.
