### ISSUE TITLE
[Bug]: WalletConnect lands to Wallet Homepage and cannot establish a connection

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-mobile#7631]
### Describe the bug

**Problem:** whenever I want to use walletconnect on a dapp, I land into the Home page of the wallet but nothing happens. This happens both with the QR code and the link.

This might be related to https://github.com/MetaMask/metamask-mobile/issues/7421 ?

### Expected behavior

A connect popup should show up in the wallet

### Screenshots/Recordings

https://github.com/MetaMask/metamask-mobile/assets/54408225/4a809692-a8c0-48ac-a989-ff5a3c738ff6

https://github.com/MetaMask/metamask-mobile/assets/54408225/959f68cb-defb-4c5e-ae82-67cf4f7d0151

### Steps to reproduce

1. Go to https://app.uniswap.org/swap
2. Click Connect
3. Click Wallet Connect
4. Use Metamask
5. See you land at the home page and nothing happens

### Version

seen in this PR https://github.com/MetaMask/metamask-mobile/pull/7491, but I can also reproduce in `main`

### Build type

None

### Device

Pixel 6

### Operating system

Android

**Comment by Holybasil** [comment]
same with #6457, fixed in v7.0.1 and the latest version has this problem again, so weird

Device: iphone 15 pro
App Version: MetaMask v7.9.1(1184)

**Comment by christopherferreira9** [comment]
Hi @Holybasil is there any dapp we can test that on?

**Comment by Holybasil** [comment]
> Hi @Holybasil is there any dapp we can test that on?

https://app.uniswap.org/swap

**Comment by christopherferreira9** [comment]
Hi @Holybasil . Would you mind sharing the exact steps you're performing with the Uniswap Dapp?

**Comment by Holybasil** [comment]
I've recorded a video; you can take a look.

https://github.com/MetaMask/metamask-mobile/assets/21138718/f64aa93d-8dc4-4300-809c-6d76513c4fdd

In the end, I waited for a long time, and the connect modal did not pop up in MetaMask.

In addition, my IOS version is 17.0.3 and my coworker who holds IOS version 16.2 can go through the whole flow.

**Comment by christopherferreira9** [comment]
@Holybasil that is very weird. I'm using wallet 7.9.1 (1184) with iOS 17.1 and it seems to work properly. I wonder if it's related to the iOS version... Can you try to clear the WalletConnect sessions in the wallet by going into Settings -> Experimental -> View Sessions -> Long tap on each connection to clear individually.

https://github.com/MetaMask/metamask-mobile/assets/104831203/a5779c7b-b811-44a8-8413-25a5841f2a52

**Comment by Holybasil** [comment]
@christopherferreira9 
I cleared the session and went through the flow again, but there was still no popup. I'll try again after upgrading the phone's operating system.
btw, after successfully connecting and returning to the Uniswap page, could you try switching networks to see if MetaMask prompts you with a popup to switch networks?

**Comment by christopherferreira9** [comment]
@Holybasil 
let me know how it goes after upgrading the OS 🙏
As for the switch networks go, we don't support network switching as an rpc method for WalletConnect V2. What happens is that when you make a network switch on the dapp (do a network you already have in MetaMask) and try to do another RPC call like `personal_sign` the wallet will first ask you to change to the chain you have in the dapp. If you don't have the network you want to use on the Mobile wallet it will initially ask you to add it.

**Comment by Holybasil** [comment]
After upgrading to ios 17.1.1, I can still not go through the flow and no popup appears in the MetaMask. 😢 
Regarding the switch, thanks for your explanation, although I'm still not able to get to this step.

**Comment by christopherferreira9** [comment]
Hi @Holybasil ! It seems this could be related to a network issue when using WalletConnect. Can you please retry again?
In the meantime to make it clear, can you please do the following?
- Disable any sort of VPN you might be using.
- Use mobile data instead of Wi-FI  
- Update MetaMask to the latest version to date
- Clear all WalletConnect related sessions and have MetaMask opened before trying to connect

**Comment by christopherferreira9** [comment]
Closing as it seems to be fixed in `7.14.0`.

https://github.com/MetaMask/metamask-mobile/assets/104831203/4186fdcc-6dae-4e06-a9ad-71fde20280de
