### ISSUE TITLE
Fix approve-custom-erc20 detox test

### ISSUE THREAD

**Issue by SamuelSalas** [MetaMask/metamask-mobile#7649]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMFNHQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--bd8caec75cbd0ad2ce45d71d74ee5e9dc043bfb6/image.png)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBME9HQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--192194756a0901c5ab116d38fd07d7c2e7339eec/image.png)

**Comment by cortisiko** [comment]
This is no longer an issue.
