### ISSUE TITLE
[Bug]: Incorrect token in Receive notification: `You received xxx ETH` on Polygon network

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-mobile#7669]
### Describe the bug

**Problem:** whenever I receive some MATIC on Polygon testnetwork, I see the notification saying `You received xxx ETH` instead of MATIC.

### Expected behavior

The token in the Receive notification should be correct, according to the network I have selected

### Screenshots/Recordings

![Screenshot from 2023-11-02 09-55-21](https://github.com/MetaMask/metamask-mobile/assets/54408225/d17fec94-73fe-4f33-8164-306ae9148a6d)

![Screenshot from 2023-11-02 09-59-14](https://github.com/MetaMask/metamask-mobile/assets/54408225/95b36cec-91ca-4b39-8a2f-1bf87f01ef38)

### Steps to reproduce

1. Add Polygon Mumbai network https://chainlist.org/?testnets=true&search=mumbai ||  you can also check Polygon Mainnet
2. Claim some MATIC tokens on the faucet https://faucet.quicknode.com/polygon/mumbai/?transactionHash=0xa65ef3490c395247c5c9ec52d236144dd911c087afbed5fcb367603a7269780c
3. See notification appear in the wallet, saying you received xxx ETH, instead of MATIC

### Version

7.9.0 production

### Build type

None

### Device

Pixel 6

### Operating system

Android

**Comment by seaona** [comment]
this shouldn't be closed as it's still present in prod

**Comment by NicolasMassart** [comment]
Given Mumbai network is deprecated and [soon to be removed from MM](https://github.com/MetaMask/metamask-mobile/pull/9047), @seaona could you update the test instructions please?

**Comment by gauthierpetetin** [comment]
Draft PR [#8699](https://github.com/MetaMask/metamask-mobile/pull/8699) needs decision on asset symbol and source to use

**Comment by seaona** [comment]
hey @NicolasMassart  this also happens with Polygon Mainnet and I suspect to other networks too (I don't have funds to try, but I defer to the assets team to double-check the rest of the networks)

![Screenshot from 2024-07-25 17-50-57](https://github.com/user-attachments/assets/cf34b49b-6e41-47a0-ac0c-de1ed7e6dc6f)
