### ISSUE TITLE
Update "Buy Crypto" options based on user's location

### ISSUE THREAD

**Issue by bdresser** [MetaMask/metamask-mobile#767]
Some of the fiat on-ramps we're suggesting aren't available in certain countries. We could make an effort to understand the user's location and only show them options available in their reigon. This might apply to some exchanges as well.

Q's
* is this possible (even fuzzily) without asking for a location permission?
* if not, is this feature worth asking for a location permission?
* should we ask the user: "Do you only want to see dapps available in your country?" and then prompt for the system location permission

**Comment by EtDu** [comment]
as of V1, the Transak fiat onramp displays all the supported countries. I believe this is enough to inform the user if this is accessible to them. I don't think it's worth asking for location permissions.

dApps are typically borderless. 

Please reopen if this needs to be discussed further.
