### ISSUE TITLE
[Bug]: metamask 7.9.1 on android ,When reload dapp, or use window.location.href ，connection disconnected,I cannot get address 

### ISSUE THREAD

**Issue by TouchFan** [MetaMask/metamask-mobile#7677]
### Describe the bug

metamask 7.9.1 on android ,When reload dapp, or use window.location.href ，connection disconnected,I cannot get address 

### Steps to reproduce

1. use window.location.href navigate to second page, the second page cannot getAddress , the status is disconnect

### Version

7.9.1

### Build type

None

### Device

android

### Operating system

Android

**Comment by anaamolnar** [comment]
Hello, @TouchFan. Thanks for reporting! Could you provide more details about your issue so we can further investigate? Thank you!
