### ISSUE TITLE
[Bug]: Send transaction with SDK displays `null` in the domain pill

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-mobile#7679]
### Describe the bug

**Problem**: whenever I am performing a Send transaction using the SDK, I can see how the domain pill displays `null` as origin

### Expected behavior

We should display the correct origin, as we do in Signatures.

### Screenshots/Recordings

https://github.com/MetaMask/metamask-mobile/assets/54408225/e4541dd6-1c34-435e-a741-25b6bdd93c3b

### Steps to reproduce

1. Go to https://chris-react-dapp.vercel.app/
2. Click Connect and accept connection
3. Click Send
4. See `null` in the domain pill

### Version

Seen here https://github.com/MetaMask/metamask-mobile/pull/7601 but it's also in `main`

### Build type

None

### Device

Pixel 6

### Operating system

Android

**Comment by A-Feder** [comment]
@seaona thanks, I am labeling this as team-sdk to fix it on on that end. As a quick fix you can initialize the SDK using https in front of the domain

**Comment by seaona** [comment]
hi there @A-Feder , we've seen that the issue is still present in `main` so we are re-opening it.
cc @blackdevelopa

**Comment by A-Feder** [comment]
Hey @seaona can you please let me know if it's still persisting with the latest version of the SDK?

**Comment by christopherferreira9** [comment]
Closing this as it has been fixed on `v7.14.0`. 

https://github.com/MetaMask/metamask-mobile/assets/104831203/11733ccc-25ef-4280-98d1-d6736f2b9206
