### ISSUE TITLE
[Bug]: First NFT in collection gets displayed no matter which is tapped

### ISSUE THREAD

**Issue by sreyemnayr** [MetaMask/metamask-mobile#7699]
### Describe the bug

In the NFTs list, when tapping an image - if it’s not the first in the list, it will display the information for the first in the list.

### Expected behavior

Display the one tapped

### Screenshots/Recordings

https://github.com/MetaMask/metamask-mobile/assets/8558670/bd386680-dd17-4285-bb89-54f1cba86ff8

https://we.tl/t-UEH1Ons7BB

### Steps to reproduce

1. open MetaMask app
2. Choose an account with NFTs in it
3. Choose a collection of which more than one token is owned by the chosen account
4. Notice it showing you the wrong information

### Version

7.9.4

### Build type

None

### Device

Apple iPhone 13 Pro

### Operating system

iOS

### Additional context

Same was noticed on a friend’s device (that’s what brought it to my attention)

**Comment by anaamolnar** [comment]
Hello, @sreyemnayr. Thank you for reporting! I will pass this on to the team.

**Comment by anaamolnar** [comment]
@sreyemnayr Did you mean version 7.9.1 in your report?

**Comment by hesterbruikman** [comment]
Could reproduce on iOS version 7.10.0

**Comment by sreyemnayr** [comment]
> @sreyemnayr Did you mean version 7.9.1 in your report?

Not sure, it looks like I'm on 7.10.0 now but it's still present.

**Comment by DanielTech21** [comment]
@hesterbruikman 
The issue persists, as the NFT only shows the first one from the collection.

Can you please look into it?
https://github.com/MetaMask/metamask-mobile/assets/145437274/84dd2540-3291-460b-95e9-fca11627aa6e
