### ISSUE TITLE
[Bug]: PPOM - Malicious transactions triggered from SDK Connect are not flagged

### ISSUE THREAD

**Issue by segun** [MetaMask/metamask-mobile#7709]
### Describe the bug

**Problem**: malicious transactions triggered from SDK Connect are not flagged by Blockaid

### Expected behavior

Malicious transactions triggered from SDK Connect should also be flagged by Blockaid.

### Screenshots

https://github.com/MetaMask/metamask-mobile/assets/54408225/edbe2046-6046-4c26-a2ad-3037807d9b71

### Steps to reproduce

TBD

### Version

Integrate PPOM branch  (behind feature flag) https://github.com/MetaMask/metamask-mobile/pull/7363
In main once the PR is merged
 
### Build type

None

### Device

Pixel 6

### Operating system

Android

**Comment by blackdevelopa** [comment]
About this, I can see Blockaid triggered when deeplinked via sdk connect. https://recordit.co/EXft1a8UFv
So closing this issue.
