### ISSUE TITLE
[Bug]: Metamask crashes on the Protect your wallet flow on iOS 17.2 beta

### ISSUE THREAD

**Issue by anaamolnar** [MetaMask/metamask-mobile#7729]
### Describe the bug

The app crashes on version 7.9.1 on mobile when users go through the Protect your wallet flow to set a password and back up their SRP.

Edit from: @Cal-L @hesterbruikman 
Navigating to another screen after going full screen on a video for iOS 17 causes a crash in the app. It has been reported here https://github.com/react-native-video/react-native-video/issues/3329. Based on the logs provided by the MM user and the issue report, the theory aligns.

### Expected behavior

Users should be able to go through the Protect your wallet flow and back up their SRP normally without the application closing.

### Screenshots/Recordings

Original thread:  https://consensys.slack.com/archives/C8RSKCNCD/p1699369438003369

### Steps to reproduce

1. Create a wallet on an iPhone using iOS 17.2 beta (the only one confirmed at this time)
2. Skip the SRP backup
3. Add funds
4. You will be prompted to the **Protect your wallet** flow
5. After watching the video and going to the password screen, the crash happens

### Error messages or log output

```shell
None
```

### Version

7.9.1

### Build type

None

### Device

iPhone on iOS 17.2 beta

### Operating system

iOS, Other (please elaborate in the "Additional Context" section)

**Comment by KrzysztofMoch** [comment]
Just to let you know - this issue will be fixed by next react-native-screens release
