### ISSUE TITLE
Error 32603: Internal JSON-RPC Error

### ISSUE THREAD

**Issue by ebennaga** [MetaMask/metamask-mobile#7753]
### What is this about?

I got error 32603 when i sell nft

### Scenario

user open metamask browser in phone for selling nft. When user sell nft to marketplace, they got error internal JSON-RPC Error. 

what should i do to fix error?

### Design

![err-metamask](https://github.com/MetaMask/metamask-extension/assets/2337413/e524e867-6c44-46d9-aa92-5b3891790825)

### Technical Details

 I am using nextjs 12.1.6

**Comment by anaamolnar** [comment]
Hello, @ebennaga. Thanks for the report! I recommend making sure you are on the correct network when performing the transaction. Any questions regarding the errors you might be seeing locally, I suggest you post them on https://ethereum.stackexchange.com/
