### ISSUE TITLE
[Bug]: ask/sdk-react can't  connect metamask-mobile  at android

### ISSUE THREAD

**Issue by zhangxiangqiang** [MetaMask/metamask-mobile#7767]
### Describe the bug

Using @metamask/sdk-react in mobile browsers ,  I can call metamask  on iOS, but I cannot call metamask on Android( HarmonyOs ) in the same way;

### Steps to reproduce

import { useSDK } from '@metamask/sdk-react';

... 

const { sdk, connected, connecting, provider, chainId } = useSDK();

 const connect = async () => {
    try {
      const accounts: any = await sdk?.connect();  // Blocked here
      setAccount(accounts?.[0]);
      loginHandle(accounts?.[0])
    } catch (err) {
      console.warn(`failed to connect..`, err);
    }
  };

### Version

7.10.0

### Build type

None

### Device

Huawei Mate60

### Operating system

Other (please elaborate in the "Additional Context" section)

### Additional context

 HarmonyOs 4.0.0

**Comment by anaamolnar** [comment]
Hello, @zhangxiangqiang. Thanks for reporting! I will pass this on to the appropriate team for review.

**Comment by christopherferreira9** [comment]
Hi @zhangxiangqiang ! 
Can you please try to run our [example dapp](https://github.com/MetaMask/metamask-sdk/tree/main/packages/examples/create-react-app) that uses `sdk-react`?

**Comment by zhangxiangqiang** [comment]
> Hi @zhangxiangqiang ! Can you please try to run our [example dapp](https://github.com/MetaMask/metamask-sdk/tree/main/packages/examples/create-react-app) that uses `sdk-react`?

Still not, but a pop-up window shows that it is useless to run Google applications。

so I guess it is because Android and harmonyOs mobile phones in Chinese Mainland have intercepted at the system level, because it is difficult to download metamask in Chinese Mainland. 

So it shouldn't be a problem with metamask; But I cannot test whether this SDK can work properly on Android in other regions

**Comment by christopherferreira9** [comment]
Hi @zhangxiangqiang , can you try to use a vpn to see if it fixes the connection?

**Comment by gauthierpetetin** [comment]
Hi @ezgi-cengiz , we've classified this bug as a sev2, but feel free to update the severity label if not appropriate

**Comment by gauthierpetetin** [comment]
Hi @zhangxiangqiang do you still encounter that issue?

**Comment by christopherferreira9** [comment]
Hi! We're closing this issue as there hasn't been any activity on it. Please feel free to open a new issue at any time.
