### ISSUE TITLE
[Bug]: Send ETH using Deeplinks sets incorrect amount if is way higher than balance

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-mobile#7769]
### Describe the bug

**Problem:** whenever we are Sending ETH using a Deeplink if the amount we set is way higher than our balance, we can see how the amount is then changed to a random smaller value (i.e. trying to Send `1000 Sepolia ETH` converts it to `0.000000000000023522 Sepolia ETH`)

### Expected behavior

We should see the correct amount and if we try to send it, we should see a warning saying we don't have enough balance (see below)

### Screenshots/Recordings

https://github.com/MetaMask/metamask-mobile/assets/54408225/9f6c2acb-4876-4866-82a6-4c3998425847

Expected: correct amount and when clicking Send, we see the warning

![Screenshot from 2023-11-13 10-34-05](https://github.com/MetaMask/metamask-mobile/assets/54408225/e7323927-d5ab-44b4-90e8-882576626722)

### Steps to reproduce

1. Go to https://metamask.github.io/metamask-deeplinks/#
2. Generate a Send ETH deeplink
3. Set a huge amount
4. Scan
5. See how the amount displayed is `<0.0000....1`
6. Send the tx
7. Go to Etherscan
8. Check the real value sent - it's a random small value i.e. `000000000000023522`

### Version

7.11.0 (seems an old issue)

### Build type

None

### Device

Pixel 6

### Operating system

Android

**Comment by bschorchit** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/-Confirmations-Secure-UX-6245e6e2348677001213b8d2/issues/MetaMask/metamask-mobile/7769?planning-poker) with Zenhub @blackdevelopa @digiwand @jpuri @seaona @segun

**Comment by bschorchit** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/-Confirmations-Secure-UX-6245e6e2348677001213b8d2/issues/MetaMask/metamask-mobile/7769?planning-poker) with Zenhub @segun
