### ISSUE TITLE
[Bug]: app crashing when trying to reveal secret phrases 

### ISSUE THREAD

**Issue by SKIZZOO** [MetaMask/metamask-mobile#7771]
### Describe the bug

iPhone 14 Pro Max, app crashes when trying to reveal secret phrases 

### Steps to reproduce

Go to security
Reveal secret phrases 
Complete the 2 questions 
App closes 

### Version

7.10

### Build type

None

### Browser

Other (please elaborate in the "Additional Context" section)

### Operating system

MacOS

**Comment by sethkfman** [comment]
Addressed by https://github.com/MetaMask/metamask-mobile/commit/facb8020036dd8106653f7ff51694ee292b85b85
