### ISSUE TITLE
[Bug]: PPOM - real device (Android) loading time for resolving is too long

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-mobile#7778]
### Describe the bug

**Problem:** ppom resolving with a response still seems to take too long. Timings below for a real device Android (Pixel 6) with a QA build:
- First transaction (ex. Send ETH): ~ 1min 10 seconds
- Subsequent transaction (ex. Send ETH): ~10 seconds

### Expected behavior

Shorter times

### Screenshots/Recordings

https://github.com/MetaMask/metamask-mobile/assets/54408225/88c7598c-9d90-4678-9194-5d717cab9747

### Steps to reproduce

1. Build the wallet on a real device
2. Select Mainnet
3. Trigger a transaction

### Version

develop (with blockaid feature flag on)

### Build type

None

### Device

Pixel 6

### Operating system

Android

**Comment by hilvmason** [comment]
@seaona pls add the referenced/ applicable issues for this bug

**Comment by seaona** [comment]
- https://github.com/MetaMask/metamask-mobile/issues/7791
- https://github.com/MetaMask/metamask-mobile/issues/7801

**Comment by hilvmason** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/-Confirmations-Secure-UX-6245e6e2348677001213b8d2/issues/MetaMask/metamask-mobile/7778?planning-poker) with Zenhub @blackdevelopa @digiwand @jpuri @seaona @segun

**Comment by hilvmason** [comment]
close as duplicate of #1701
