### ISSUE TITLE
[Bug]: PPOM - What's New copy text refers to OpenSea previous feature - non existing in Mobile

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-mobile#7782]
### Describe the bug

**Problem:** the What's new message displays a reference to Opensea security, but that feature was never released in Mobile

### Expected behavior

Should we remove the last sentence completely? @bschorchit 

### Screenshots/Recordings

![Screenshot from 2023-11-13 17-40-26](https://github.com/MetaMask/metamask-mobile/assets/54408225/fb9f1014-7af8-41f3-a667-9edc661a4aba)

![Screenshot from 2023-11-13 17-42-34](https://github.com/MetaMask/metamask-mobile/assets/54408225/2509e6c3-7ae1-4660-a544-42e5f8e91fdd)

### Steps to reproduce

1. Enable Blockaid feature flag
2. Build the wallet
3. Onboard
4. Check What's new

### Version

develop (with blockaid feature flag on)

### Build type

None

### Device

Pixel 6

### Operating system

Android

**Comment by bschorchit** [comment]
Great catch! 

Copy should be:

```
Steer clear of known scams while still preserving your privacy with security alerts powered by Blockaid on Ethereum Mainnet.

Always do your own due diligence before approving requests.
```
