### ISSUE TITLE
[Bug]: PPOM - Some signatures are not displayed completed when the PPOM is enabled, only after several seconds

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-mobile#7801]
### Describe the bug

**Problem:** whenever we are triggering some signatures, we can see how the modal is not displayed completed. Only after several seconds we see the complete Signature modal.
This seems to happen only to certain signatures. (i.e. V2, V3 test-dapp)

### Expected behavior

Modal should be fully visible when triggering any signature with Blockaid enabled

### Screenshots/Recordings

Android

https://github.com/MetaMask/metamask-mobile/assets/54408225/fd3809b0-5a42-4a20-8f7f-cbc2210ebf60

iOS

https://github.com/MetaMask/MetaMask-planning/assets/34968356/a8c281c7-e1f1-41d2-b4a6-e5fbdd6d75ce

### Steps to reproduce

1. Enable Blockaid
2. Go to the test dapp
3. Click on Signature V2 or V3
4. See modal is cut for some seconds

### Version

develop (with blockaid feature flag on)

### Build type

None

### Device

Pixel 6 and iPhone 11

### Operating system

Android and iOS

**Comment by jpuri** [comment]
This again looks like android issue,  this is not happening on IOS.

**Comment by bschorchit** [comment]
Update: this issue is also happening on iOS
