### ISSUE TITLE
[Bug]: PPOM - ERC20 Approve screen hides the warning after the validation has completed

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-mobile#7807]
### Describe the bug

**Problem:** on the ERC20 Approve screen, the ppom warning is hidden after the validation ends

### Expected behavior

We should display the warning

### Screenshots/Recordings

https://github.com/MetaMask/metamask-mobile/assets/54408225/69241c81-019f-4c94-9c44-5dd5b74c0129

### Steps to reproduce

1. Enable Blockaid
2. Go to the test dapp
3. Trigger a Malicious ERC20 Approval
4. See warning in loading state
5. After validation finishes, the warning is then hidden

### Version

develop (with blockaid feature flag on)

### Build type

None

### Device

Pixel 6

### Operating system

Android

**Comment by jpuri** [comment]
This seems to work well on IOS, there is a very small delay of result appearing after loading information. That may be more visible in android:


https://github.com/MetaMask/metamask-mobile/assets/2182307/ee7f655f-3b5c-43a8-9a48-49a1b1756c1b
