### ISSUE TITLE
[Bug]: Inputting any manual char into `Recipient` field breaks the wallet with `Invalid address` (implications: ENS is broken now)

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-mobile#7862]
### Describe the bug

**Problem:** whenever I try to enter a ENS domain, the wallet breaks at the first char with the error `Invalid address`

### Expected behavior

The wallet should not break.
ENS should be supported.

### Screenshots/Recordings

![Screenshot from 2023-11-17 10-51-06](https://github.com/MetaMask/metamask-mobile/assets/54408225/a3e76868-4973-4135-916a-ddc88fdddc02)

https://github.com/MetaMask/metamask-mobile/assets/54408225/bc9041ce-aaca-4c71-a6ac-393530f32ee7

### Steps to reproduce

1. Start Send flow
2. Add any char for recipient
3. Wallet breaks

### Version

7.11.0 (1200)- not present in 7.10.0

### Build type

None

### Device

Pixel 6

### Operating system

Android

**Comment by seaona** [comment]
hi @chrisleewilcox I can reproduce deterministically with my Pixel 6 and also iPhone 14 Pro Max (real devices). For the first one, it was a local build, and for the iPhone one, I was with the current testflight version `7.11.0` (1200).
@blackdevelopa could also repro on iPhone.
:thinking: not sure if might be something specific about upgrading?

**Comment by seaona** [comment]
[Update] After conversation in Slack, it's been confirmed that the production version will be `7.11.0` (1197). This means that this issue won't impact `7.11.0` production. To follow up, if this then impacts the next version `7.12.0`

**Comment by dawnseeker8** [comment]
i can confirm that this is caused by this [PR](https://github.com/MetaMask/metamask-mobile/pull/7641/files#), the `getKeyringByAddress()` method break in`address/index.ts` file. the fix will be easy.
