### ISSUE TITLE
Remove all instances of strings in TestID property in the app code

### ISSUE THREAD

**Issue by SamuelSalas** [MetaMask/metamask-mobile#7863]
## Description
We have instances where testIDs are not consistently stored in variables. This lack of uniformity can lead to redundant testID declarations throughout the codebase, resulting in code that is harder to maintain and prone to errors.

For instance, consider the following code snippet: `testID={'request-qrcode-button'}.` This line directly specifies a testID value within the code, and similar declarations may be scattered throughout the codebase.

A more effective and best-practice approach is to store the testID value as a variable and then reference that variable when defining the testID property. By doing so, we centralize the testID values, reducing redundancy and making it easier to manage and maintain these identifiers throughout the codebase. This approach enhances code consistency and reduces the likelihood of introducing errors, ultimately contributing to a more robust and maintainable codebase.

## Technical details:

Replace all string definitions used for testIDs. For example: `testID={BrowserUrlModalSelectorsIDs.CONTAINER}`
All variables should be group by the file where they're being call
All variables should be group in a JSON
File structure should follow a similar structure as the main app structure

- Files with testIDs strings inside the code:
  - app/component-library/components/Icons/Icon/Icon.test.tsx
  - app/components/UI/AccountOverview/index.js
  - app/components/UI/AccountRightButton/index.tsx
  - app/components/UI/AddCustomCollectible/index.tsx
  - app/components/UI/AddressInputs/index.js
  - app/components/UI/ApproveTransactionReview/index.js
  - app/components/UI/AssetList/index.js
  - app/components/UI/AssetSearch/index.tsx
  - app/components/UI/CollectibleContractOverview/index.js
  - app/components/UI/Collectibles/index.js
  - app/components/UI/DrawerView/index.js
  - app/components/UI/FoxScreen/index.js
  - app/components/UI/Navbar/index.js
  - app/components/UI/NavbarBrowserTitle/index.js
  - app/components/UI/NavbarTitle/index.js
  - app/components/UI/Notification/BaseNotification/index.js
  - app/components/UI/PaymentRequest/index.js
  - app/components/UI/PaymentRequest/AssetList/index.tsx
  - app/components/UI/SearchTokenAutocomplete/index.tsx
  - app/components/UI/Tokens/index.tsx
  - app/components/UI/Transactions/index.js
  - app/components/Views/AccountBackupStep1/index.js
  - app/components/Views/AccountBackupStep1B/index.js
  - app/components/Views/AddAsset/AddAsset.tsx
  - app/components/Views/AddBookmark/index.js
  - app/components/Views/AddressQRCode/index.js
  - app/components/Views/ChoosePassword/index.js
  - app/components/Views/Collectible/index.js
  - app/components/Views/CollectibleView/index.js
  - app/components/Views/ConnectQRHardware/SelectQRAccounts/index.tsx
  - app/components/Views/EnterPasswordSimple/index.js:
  - app/components/Views/GasEducationCarousel/index.js
  - app/components/Views/ImportFromSecretRecoveryPhrase/index.js
  - app/components/Views/ImportPrivateKey/index.tsx
  - app/components/Views/ImportPrivateKeySuccess/index.js
  - app/components/Views/Login/index.js:
  - app/components/Views/ManualBackupStep1/index.js
  - app/components/Views/ManualBackupStep3/index.js
  - app/components/Views/Onboarding/index.js
  - app/components/Views/OnboardingCarousel/index.js
  - app/components/Views/ResetPassword/index.js
  - app/components/Views/RevealPrivateCredential/RevealPrivateCredential.tsx
  - app/components/Views/SDKSessionsManager/SDKSessionsManager.tsx
  - app/components/Views/Settings/AdvancedSettings/index.js
  - app/components/Views/Settings/AppInformation/index.js
  - app/components/Views/Settings/NetworksSettings/index.js
  - app/components/Views/Settings/SecuritySettings/SecuritySettings.tsx
  - app/components/Views/Settings/SecuritySettings/Sections/LoginOptionsSettings.tsx
  - app/components/Views/WalletConnectSessions/index.js
 
Acceptance Criteria:

- E2E tests should pass on all tests

**Comment by cortisiko** [comment]
all issues in this EPIC has been closed
