### ISSUE TITLE
[Bug]: WC goes back after switchChain and before sign

### ISSUE THREAD

**Issue by christopherferreira9** [MetaMask/metamask-mobile#7878]
### Describe the bug

When trying to sign to a different chain than the one selected in the wallet, it first asks the user to switch to the chain on the Dapp which is correct. The issue is that the Wallet should send back to dapp after the sign request.

### Expected behavior

The wallets sends the user back to the dapp after Sign if accepting the chain switch or right after denying the chain switch

### Screenshots/Recordings

https://github.com/MetaMask/metamask-mobile/assets/104831203/8314a301-8419-4ce4-9d41-81a9a0b0e8b3

### Steps to reproduce

1. Set your MetaMask Wallet to Goerli chain
2. Go to https://release-2-3-0.web3modal-dev.pages.dev/v2Base
3. Connect
4. Sign -> Approve switch chain to mainnet -> See error

### Error messages or log output

```shell
The wallet sends the user back after switching chain and not after signing.
```

### Version

*

### Build type

None

### Device

*

### Operating system

Other (please elaborate in the "Additional Context" section)

### Additional context

Both platforms

**Comment by siosio34** [comment]
#7206  It seems similar to the issue. This is an issue that has not been fixed since version 7.4.

**Comment by siosio34** [comment]
@christopherferreira9 

hellohello. Has this issue been fixed yet?

We have currently contacted the wagmi team and the walletconnect team, but the issue only occurs on Metamask Mobile, so the solution has been delayed for several months.

Chain conversion is a fairly essential function for our exchange and other exchanges that sell multiple NFTs.

How about raising the importance of the issue and making it a priority?

**Comment by omridan159** [comment]
This PR resolves the issue:
https://github.com/MetaMask/metamask-mobile/pull/8496
