### ISSUE TITLE
[Bug]: unexpected application redirection happen when iframe src ends with `*.xyz`

### ISSUE THREAD

**Issue by ellemedit** [MetaMask/metamask-mobile#7880]
### Describe the bug

`<iframe src="https://(...).xyz" />` redirects to `https://(...).xyz` in MetaMask browser.
It breaks our application's basic assumption. So our service cannot be used in MetaMask browser at this moment as iframe redirection breaks usual flow.

I would like to contribute if you guide some entry points or contexts. Thank you.

### Expected behavior

Just render iframe without redirection.

### Steps to reproduce

1. Go to `https://nk77pl.csb.app/` with MetaMask browser.
2. It redirects `https://app.velocore.xyz` when loading completed.

### Version

latest iOS MetaMask

### Build type

None

### Device

iPhone, iOS 17

### Operating system

iOS

**Comment by anaamolnar** [comment]
Hello, @ellemedit. Thanks for reporting! I will assign this to the appropriate team for review.
