### ISSUE TITLE
[Bug]: Viewing Token Detail Page displays $0 and "Unable to load your balance" from delayed loading (USDC example)

### ISSUE THREAD

**Issue by digiwand** [MetaMask/metamask-mobile#7887]
### Describe the bug

Token balance takes significant time to load and displays "Unable to load your balance". From the token list, there is a rounded, loading placeholder. Clicking in the token list, the user sees "Unabled to load your balance" and the token price displays as "$0". 

This appears to the user as a bug though it may be a slow loading issue. After some time and clicking through the app, the balance and token price displays as expected. 

### Expected behavior

Clicking on a token detail page (e.g. "USD Coin") should show token price and total balance as expected.

#### Incident 1:
<img src='https://github.com/MetaMask/metamask-mobile/assets/20778143/8fb54155-285b-44c7-b1ca-6d382d5571b6' width='250'>
<img src='https://github.com/MetaMask/metamask-mobile/assets/20778143/18802321-053e-4f66-9059-d6211598fd51' width='250'>

#### Incident 2: 
<img src='https://github.com/MetaMask/metamask-mobile/assets/20778143/a7803537-75e7-45b9-86df-f72c2563b4ec' width='250'>
<img src='https://github.com/MetaMask/metamask-mobile/assets/20778143/5edaa5d4-e3e9-4e34-90c9-d0dc51762d88' width='250'>

### Steps to reproduce

- Own another token (USDC)
- View "USD Coin" from token list
- Click "USD Coin" row
- Observe "$0" and "Unable to load your balance

### Version

v7.10.0

### Build type

None

### Device

iPhone 13 pro

### Operating system

iOS 17.1.1

### Additional context

build specs not available

**Comment by digiwand** [comment]
should be fixed by https://github.com/MetaMask/metamask-mobile/issues/7903

**Comment by sethkfman** [comment]
This issue has been address in the hot fix 7.12.1. An additional ticket addresses the PriceAPI implementation.
