### ISSUE TITLE
[BUG] Fix the TokenRateController API

### ISSUE THREAD

**Issue by sethkfman** [MetaMask/metamask-mobile#7903]
### What is this about?

This issue is to replace the CoinGecko API on the [TokenRates controller](https://github.com/MetaMask/core/blob/fda42694d534e1a49cf97d072178615a63ad732b/packages/assets-controllers/src/TokenRatesController.ts#L141). The API should be replaced with the public PriceAPI written by the codefi team which is documented [here](https://price-api.metafi.codefi.network/docs#/Spot%20Prices/PriceController_getSpotPriceByTokenAddressAsync).

### Scenario

- GIVEN a user has an account and assets in their wallet
- WHEN they navigate to the wallet view
- AND they review their assets 
- AND they have a network connection
- THEN there is a fiat balance displayed

### Technical Details

- Create a TokenRatesController patch that replaces the  [CoinGecko API](https://github.com/MetaMask/core/blob/fda42694d534e1a49cf97d072178615a63ad732b/packages/assets-controllers/src/TokenRatesController.ts#L141)
   - Replace the `getTokenPriceURL` to uses the PriceAPI call GET
[/v1/chains/{chainId}/spot-prices/{tokenAddress}](https://price-api.metafi.codefi.network/docs#/Spot%20Prices/PriceController_getSpotPriceByTokenAddressAsync)
   - Remove the `getSupportedVsCurrencies` this should not be needed
   - Return a hardcode list for `getPlatformsURL` 
```
  1: 'ethereum',
  10: 'optimistic-ethereum',
  25: 'cronos',
  56: 'binance-smart-chain',
  57: 'syscoin',
  66: 'okex-chain',
  70: 'hoo-smart-chain',
  82: 'meter',
  88: 'tomochain',
  100: 'xdai',
  106: 'velas',
  122: 'fuse',
  128: 'huobi-token',
  137: 'polygon-pos',
  250: 'fantom',
  288: 'boba',
  321: 'kucoin-community-chain',
  324: 'zksync',
  361: 'theta',
  1088: 'metis-andromeda',
  1284: 'moonbeam',
  1285: 'moonriver',
  8453: 'base',
  8545: 'shiden network',
  10000: 'smartbch',
  42161: 'arbitrum-one',
  42220: 'celo',
  42262: 'oasis',
  43114: 'avalanche',
  59144: 'linea',
  333999: 'polis-chain',
  1313161554: 'aurora',
  1666600000: 'harmony-shard-0', 

```

- Create a core PR that applies these changes to the TokenRatesController
- Test the API calls and confirm data objects have the same format as what CoinGecko returns

### Data flow
![image](https://github.com/MetaMask/metamask-mobile/assets/46944231/c3f5fd73-4e99-4588-bb1d-d944d8796a47)

### Threat Modeling Framework

This is a public API and does not require an API token.

### Acceptance Criteria

Token rates are displaying with the new API integration when there is a network connection.

### References

Slack - https://consensys.slack.com/archives/C065W3877E3/p1700574338429709

**Comment by sethkfman** [comment]
Related to issue #7887

**Comment by tommasini** [comment]
Moving this to done since it was done on this https://github.com/MetaMask/metamask-mobile/pull/8143
