### ISSUE TITLE
[Bug]: unable to receive ethers on the Sepolia testnet, although the website indicates that the ethers have been transferred, Version 7.10.0

### ISSUE THREAD

**Issue by SudipVdoit** [MetaMask/metamask-mobile#7906]
### Describe the bug

Unable to receive ethers on the Sepolia testnet, although the website indicates that the ethers have been transferred.
![1](https://github.com/MetaMask/metamask-mobile/assets/127386852/732528d2-0dbe-4a4e-b29d-fed996de342e)
![2](https://github.com/MetaMask/metamask-mobile/assets/127386852/dad6da81-ec10-4996-9b4f-722420ef2d94)

### Steps to reproduce

1. login using credentials, 
2. on the homepage select sepolia test network,
3. after clicking on the history tab on the bottom bar there is no transaction shown.

### Version

7.10.0

### Device

OnePlus Nord CE EB2101

### Operating system

Android

**Comment by gauthierpetetin** [comment]
Hi @SudipVdoit , when you go in "Settings > Security & Privacy" are incoming transactions enabled for Sepolia network?
![IMG_9042](https://github.com/MetaMask/metamask-mobile/assets/7071180/5c261bf9-341d-44d8-85f9-b767a7a21770)
