### ISSUE TITLE
[Bug]: -On the transcations history page there is no information about the gas fees deducted, Version 7.10.0

### ISSUE THREAD

**Issue by SudipVdoit** [MetaMask/metamask-mobile#7910]
### Describe the bug

On the transcations history page there is no information about the gas fees deducted.

### Steps to reproduce

1. After clicking on the history tab on the bottom tab bar, we get to see no details about the gas fees deduction on every transaction.

![4](https://github.com/MetaMask/metamask-mobile/assets/127386852/a2a0ead4-cb58-4d0a-9725-500298444e8f)

### Version

7.10.0

### Device

OnePlus Nord CE EB2101

### Operating system

Android

**Comment by anaamolnar** [comment]
Hello, @SudipVdoit. Thanks for the report! You can see the details on the expanded transaction details and the blockchain explorer. Feel free to re-open this if that is not the case. Thank you!
