### ISSUE TITLE
[Bug]: After a transaction the token displayed on the home screen are much higher than the actual transaction, Version 7.10.0

### ISSUE THREAD

**Issue by SudipVdoit** [MetaMask/metamask-mobile#7911]
### Describe the bug

We received an amount of 0.5 MATIC, as shown in the Transaction page, but on the home page, it is displaying an amount greater than 0.5 even after transactions are completed
This issue arises when we've already created an account on the website and try to access the app using those credentials

### Screenshots/Recordings

![5](https://github.com/MetaMask/metamask-mobile/assets/127386852/1f5c2d4e-7723-4eee-88fa-8d24801acc79)
![6](https://github.com/MetaMask/metamask-mobile/assets/127386852/1c409618-b651-48da-b953-f8e96ab91dbf)

### Steps to reproduce

1. login using existing credentials, 
2. in home screen, wrong amount of tokens are displayed as balance.
3. amount of token that we have recieved and the balance showing in the home screen does not match.

### Version

7.10.0

### Device

OnePlus Nord CE EB2101

### Operating system

Android

**Comment by anaamolnar** [comment]
Hello, @SudipVdoit. Thanks for reporting! Are you still seeing the wrong balance after dragging down the screen from the main asset page so it refreshes? Are you getting the same issue on 7.11?
