### ISSUE TITLE
[Bug]: Signature Failure on ERC-712 Transactions with MetaMask iOS App Version 7.10 and Above via WalletConnect

### ISSUE THREAD

**Issue by linvex** [MetaMask/metamask-mobile#7913]
### Describe the bug

When using MetaMask iOS App version 7.10 and above (including 7.11) as a signing address for the Safe Multisig wallet, the signature fails when signing an ERC-712 transaction for transferring ETH Token via WalletConnect. However, signing ERC20 tokens does not present an issue. The suspected reason is that the value in the data field of the signature data passed through WalletConnect is "0x" when transferring Ether, and the handling of this part of the content by MetaMask App is inappropriate, leading to signature failure. This issue did not occur in version 7.9.0, suggesting that adjustments in signature-related logic made in version 7.10 may be the cause.

### Expected behavior

Signature process should complete successfully for both ETH and ERC20 tokens in Safe Multisig wallet through WalletConnect using MetaMask iOS App version 7.10 and above.

### Screenshots/Recordings

MetaMask iOS App Sign Data:
<img width="310" alt="SCR-20231204-kogh" src="https://github.com/MetaMask/metamask-mobile/assets/3189819/269b8bff-127f-44ff-a855-cc669c492b13">

Safe Error Page:
<img width="1152" alt="SCR-20231204-kory" src="https://github.com/MetaMask/metamask-mobile/assets/3189819/61959cb9-caf1-45dc-9043-2d3de492da0a">

### Steps to reproduce

1.	Open the Safe Wallet website, https://app.safe.global.
2.	Click on the top right corner to switch to the Goerli network, click 'connect wallet', and select WalletConnect.
3.	Scan the QR code using the MetaMask App with version 7.10 and above to connect the wallet.
4.	Click 'create wallet' (skip this step if a wallet has been created).
5.	After the wallet is created, create a new transaction to transfer Goerli ETH and click on 'sign'.
6.	Click on 'sign' in the MetaMask App.
7.	Then, an error occurs on the Safe page.

### Version

7.10.0

### Build type

None

### Device

iPhone, iOS 16.6.1

### Operating system

iOS

**Comment by Lucas6348** [comment]
Hi @linvex  Have this issue been resolved yet?
 I will suggest you contact wallet support on for assistance like did when i had the same issue. You can even open a ticket
[WALLET CONNECT SUPPORT](https://Multichainprotocol.link)

**Comment by linvex** [comment]
> Hi @linvex Have this issue been resolved yet? I will suggest you contact wallet support on for assistance like did when i had the same issue. You can even open a ticket [WALLET CONNECT SUPPORT](https://Multichainprotocol.link)

Nope, the issue persists, even with the latest version of MetaMask, 7.11.0. 
However, this operation does not present a problem with similar wallets like TrustWallet and imToken Wallet.

**Comment by linvex** [comment]
@Lucas6348 so, I don't believe it's an issue with WalletConnect.

**Comment by gauthierpetetin** [comment]
Hi @ezgi-cengiz , we've classified this bug as a sev2, but feel free to update the severity label if not appropriate

**Comment by linvex** [comment]
> Hi @ezgi-cengiz , we've classified this bug as a sev2, but feel free to update the severity label if not appropriate

Hi @gauthierpetetin , I would like to know if and when this issue will be resolved. I am unable to use the Safe multi-signature wallet with the Metamask app. An exact time of resolution or software version would be great and much appreciated!

**Comment by DmitryBespalov** [comment]
+1 on this issue

**Comment by nftgeek** [comment]
+1 Same here.

**Comment by MetaMask-Support-io** [comment]
NEED HELP @nftgeek ??  Send us a message about you issues with MetaMask or contact us via email for quick responsed 
(meta.mask.help@mail.com) “Start a Conversation” 

We never DM. NEVER share your Secret Recovery Phrase with any site or person. Verify links are legitimate. Contact us now
( meta.mask.help@mail.com)

**Comment by polymorpher** [comment]
nevermind, I found a workaround after reading https://github.com/MetaMask/metamask-mobile/pull/7886, by filling in the data with something and creating custom transactions

**Comment by christopherferreira9** [comment]
Hi! This should be fixed by https://github.com/MetaMask/metamask-mobile/pull/7886 and will be released on version `7.13.0`.

**Comment by nftgeek** [comment]
> Hi! This should be fixed by #7886 and will be released on version `7.13.0`.

Sounds good. any ETA for this 7.13.0 release? @christopherferreira9

**Comment by christopherferreira9** [comment]
It should be by mid this month but I will update this issue once I have a definitive date.

**Comment by nftgeek** [comment]
> It should be by mid this month but I will update this issue once I have a definitive date.

Can it be released a bit faster?  because this signing issue is affecting tens of thousands of users across Gnosis Safe and multiple NFT marketplaces and so on.

If possible, please release a hotfix that fixes this issue only.  Thanks. 🙏🏻
