### ISSUE TITLE
[Bug]: The application closes automatically when selecting any main network and we have to log in again, Version 7.10.0

### ISSUE THREAD

**Issue by SudipVdoit** [MetaMask/metamask-mobile#7914]
### Describe the bug

The application closes automatically when selecting any main network and we have to open the app and log in again.

### Steps to reproduce

1. go to home screen
2.  on the top center click on the dropdown and try to change the network to a main network,
   app will close immediatly as a fail and we have to open the app again and login. then it will work.

### Version

7.10.0

### Device

OnePlus Nord CE EB2101

### Operating system

Android

**Comment by anaamolnar** [comment]
Hello, @SudipVdoit. Thanks for reporting! Are you able replicate this after updating manually from the Play Store to 7.11? Thank you!

**Comment by gauthierpetetin** [comment]
Hi @SudipVdoit , is this still an issue on your end? If not, we're going to close it by end of week.
