### ISSUE TITLE
[Bug]: The swap tokens screen is not responding properly, Version 7.10.0

### ISSUE THREAD

**Issue by SudipVdoit** [MetaMask/metamask-mobile#7915]
### Describe the bug

The swap tokens screen is not responding properly; we have to click several times to select the dropdown for 'from tokens' and then enter the values

https://github.com/MetaMask/metamask-mobile/assets/127386852/4965c1dc-c2d0-47d5-ac07-49b23ed2dea1

After selecting any option from the 'from' dropdown and the 'to' dropdown, when we click on the proceed button to swap the tokens, it redirects us to the error page attached below.
![7](https://github.com/MetaMask/metamask-mobile/assets/127386852/4a1d4ec7-ff37-4aa1-9421-6bf7175e57bd)

### Steps to reproduce

please check the attached video.

### Version

7.10.0

### Device

OnePlus Nord CE EB2101

### Operating system

Android

**Comment by anaamolnar** [comment]
Hello, @SudipVdoit. Thanks for reporting! I will pass this information on for review.
