### ISSUE TITLE
[Bug]: Crash when signing message

### ISSUE THREAD

**Issue by Gudahtt** [MetaMask/metamask-mobile#7920]
### Describe the bug

The application crashes when signing an `eth_signTypedData_v4` message on the main branch. Various Bitrise test runs hint that the same is true of other types of messages as well.

### Expected behavior

The application should not crash when signing a message

### Screenshots/Recordings

<img width="427" alt="Screenshot 2023-11-23 at 10 11 02 AM" src="https://github.com/MetaMask/metamask-mobile/assets/2459287/9bc43041-2c53-4020-8ba3-d407fdc5ae2c">

### Steps to reproduce

* Navigate to https://metamask.github.io/test-dapp using a build from `main` (tested with https://github.com/MetaMask/metamask-mobile/commit/69c79dfa4ae7ea495fc454669363ceaffefed494)
  * I have tested this with a development build, I am not sure if that matters for this reproduction though
* Connect an account to the dapp
* Trigger an `eth_signTypedData_v4` signature, and the application with crash

### Error messages or log output

Initially the error shown is `Attempting to define a property on object that is not extensible`. However this error is itself caused by the underlying error, and is related to `ses`.

I removed `ses` locally to find the underlying error here, which was `_imageSource$uri.endsWith is not a function`. It is from this line: https://github.com/MetaMask/metamask-mobile/blob/69c79dfa4ae7ea495fc454669363ceaffefed494/app/util/favicon/index.ts#L163

### Version

69c79dfa4ae7ea495fc454669363ceaffefed494

### Build type

None

### Device

iPhone 13 Pro simulator

### Operating system

iOS

**Comment by seaona** [comment]
Thanks for logging this @Gudahtt :pray:  I've triggered a run for Confirmations tests and indeed this is catched by our tests. We have [a PR](https://github.com/MetaMask/metamask-mobile/pull/7710) that flags all the Confirmations tests (including Signatures) as `Smoke` tests, so they are run on every PR.
Hopefully we can get it merge soon, so we can capture more of these issues ahead of time. :pray: 

![Screenshot from 2023-11-23 15-16-01](https://github.com/MetaMask/metamask-mobile/assets/54408225/6fe26982-56eb-46dd-b4b2-082c2b7d2f3a)

**Comment by Gudahtt** [comment]
Fixed by #7917
