### ISSUE TITLE
[Bug]: iOS Development build warnings/errors trigger SES error

### ISSUE THREAD

**Issue by Gudahtt** [MetaMask/metamask-mobile#7923]
### Describe the bug

Any warnings or errors in development builds are triggering an error from `ses`. The error is "Attempting to define a property on object that is not extensible", and it comes from a module in the `react` package that is only used for development builds. This error hides the underlying error/warning, making local development much more difficult.

Various development-build-only dependencies are not compatible with SES lockdown. On the MetaMask extension we worked around this by not calling lockdown in development builds. We should consider doing the same thing here.

### Expected behavior

Errors and warnings should not trigger additional errors.

### Screenshots/Recordings

<img width="427" alt="Screenshot 2023-11-23 at 7 00 47 PM" src="https://github.com/MetaMask/metamask-mobile/assets/2459287/120df33b-a5a5-469d-a688-bf3851900b82">

### Steps to reproduce

Follow the reproduction steps for this issue: https://github.com/MetaMask/metamask-mobile/issues/7920

### Error messages or log output

```
 ERROR  TypeError: Attempting to define property on object that is not extensible.

This error is located at:
    in Unknown (created by SignatureRequest)
    in RCTView (created by View)
    in View (created by AnimatedComponent)
    ...
```

### Version

`main`

### Build type

None

### Device

iPhone 13 Pro simulator

### Operating system

iOS

**Comment by leotm** [comment]
makes sense for now for a better devexp running our debug builds 👍
as you mentioned we've done on the MetaMask extension
