### ISSUE TITLE
Issues with signature message in Ukrainian 

### ISSUE THREAD

**Issue by Badk0m** [MetaMask/metamask-mobile#7932]
### What is this about?

Цe are getting confusing characters when confirming the transaction in the mobile app.
Error appear whet I use chat in my Dapp and try send message in Ukrainian.
![image-2023-11-22-12-52-14-463](https://github.com/MetaMask/metamask-extension/assets/124700285/571cdcab-3468-4a94-a229-851e5e726bca)
Contact me in Discord plz -k0m.

**Comment by anaamolnar** [comment]
Hello, @Badk0m. Thanks for reporting! I will pass this on to the team.

**Comment by Badk0m** [comment]
> Hello, @Badk0m. Thanks for reporting! I will pass this on to the team.

TY, keep in touch me,  plz)

**Comment by Badk0m** [comment]
@anaamolnar plz answer!)

**Comment by Badk0m** [comment]
@metamaskbot 
@anaamolnar 
@makoto 
@bschorchit

**Comment by bschorchit** [comment]
Hey @Badk0m, sorry for the delay. Could you add repro steps to this issue? Ty!
