### ISSUE TITLE
[Bug]: PPOM - Warning details use double quotes

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-mobile#7995]
### Describe the bug

**Problem:** the malicious warning display the details information on double quotes

### Expected behavior

Not display double-quotes, like in Extension

### Screenshots/Recordings

Mobile
![Screenshot_20231204-093709](https://github.com/MetaMask/metamask-mobile/assets/54408225/09a12ae6-9859-4797-9eed-0b8bc9c35191)

Extension
![Screenshot from 2023-12-04 09-38-33](https://github.com/MetaMask/metamask-mobile/assets/54408225/a28dbb24-cc67-41d2-9b24-7c81ceaa7a47)

### Steps to reproduce

1. Enable Blockaid
2. Go to the test dapp
3. Trigger a Malicious tx
4. See warning details
5. See information in double quotes

### Version

main (with blockaid feature flag on)

### Build type

None

### Device

Pixel 6

### Operating system

Android

**Comment by MetaMask-Support-io** [comment]
NEED HELP??  Send us a message about you issues with MetaMask or contact us via email for quick responsed 
(meta.mask.help@mail.com) “Start a Conversation” 

We never DM. NEVER share your Secret Recovery Phrase with any site or person. Verify links are legitimate. Contact us now
( meta.mask.help@mail.com)

**Comment by Nitro-jr** [comment]
Exactly the same problem i encountered, write to them at (meta.mask.help@mail.com) they will aid to you.
Their Support team is always active to assist you, I’ll advise you go directly to them at 👇👇👇 (meta.mask.help@mail.com)
