### ISSUE TITLE
[Bug]: Not redirect from MetaMask mobile app to the original Dapp browser in iOS

### ISSUE THREAD

**Issue by toshiboy86** [MetaMask/metamask-mobile#8003]
### Describe the bug

From a browser page in iOS, invoking the `eth_requestAccounts` method successfully opens MetaMask mobile app and establishes the connect but not redirect back to the browser page.
(EOA can successfully returned in the browser page though)

### Expected behavior

Redirect back to the browser page once you connects successfully in the MetaMask mobile app.

### Steps to reproduce

1. Git clone and `yarn serve` the original demo app in your local: https://github.com/MetaMask/metamask-sdk/tree/main/packages/examples/vuejs
2. Visit locally hosted page via your iphone and click "Connect" button

### Error messages or log output

```shell
[Warning] Message ignored because invalid key exchange status. step=key_handshake_SYNACK (2) (bundle.js, line 17615)
[Debug] RCPMS::_write method metamask_getProviderState doesn't need redirect. (bundle.js, line 25251)
[Debug] RCPMS::_write method eth_getBalance doesn't need redirect. (bundle.js, line 25251)
```

### Version

v7.11.0

### Build type

None

### Device

iOS version: 17.1.1

### Operating system

iOS

### Additional context

Relevant community thread: https://community.metamask.io/t/not-redirect-from-metamask-mobile-app-to-the-original-browser-app/27575

**Comment by sindtext** [comment]
i got same issue. in iOS success open MetaMask, "connect to MetaMask” and not redirect back. And in android, success open MetaMask, than “connect to MetaMask” and redirect back to my webApp. But when i do it again in same page with other call (transfer, check allowing or something else), chrome blocked to open MetaMask mobile.

**Comment by sindtext** [comment]
> > i got same issue in iOS browser. 3 days ago : success open MetaMask, not "connect to MetaMask” and not redirect back. this days : success open MetaMask, "connect to MetaMask” and not redirect back.
> 
> I realized something, when i clear the privacy data of my dapp at metamask, they connect me and redirect me too. but after that, the privacy data is recorded. than not redirecting again

don;t know why, now is working fine in my device (iphone 12 mini iOS 16.6) but not in my other device (iphone 13 Ios 16.6.1)

**Comment by MetaMask-Support-io** [comment]
> ### Describe the bug
> 
> From a browser page in iOS, invoking the `eth_requestAccounts` method successfully opens MetaMask mobile app and establishes the connect but not redirect back to the browser page.
> (EOA can successfully returned in the browser page though)
> 
> ### Expected behavior
> 
> Redirect back to the browser page once you connects successfully in the MetaMask mobile app.
> 
> ### Screenshots/Recordings
> 
> _No response_
> 
> ### Steps to reproduce
> 
> 1. Git clone and `yarn serve` the original demo app in your local: https://github.com/MetaMask/metamask-sdk/tree/main/packages/examples/vuejs
> 2. Visit locally hosted page via your iphone and click "Connect" button
> 
> ### Error messages or log output
> 
> ```shell
> [Warning] Message ignored because invalid key exchange status. step=key_handshake_SYNACK (2) (bundle.js, line 17615)
> [Debug] RCPMS::_write method metamask_getProviderState doesn't need redirect. (bundle.js, line 25251)
> [Debug] RCPMS::_write method eth_getBalance doesn't need redirect. (bundle.js, line 25251)
> ```
> 
> 
> ### Version
> 
> v7.11.0
> 
> ### Build type
> 
> None
> 
> ### Device
> 
> iOS version: 17.1.1
> 
> ### Operating system
> 
> iOS
> 
> ### Additional context
> 
> Relevant community thread: https://community.metamask.io/t/not-redirect-from-metamask-mobile-app-to-the-original-browser-app/27575
> 
> ### Severity
> 
> _No response_

NEED HELP @toshiboy86 ??  Send us a message about you issues with MetaMask or contact us via email for quick responsed 
(meta.mask.help@mail.com) “Start a Conversation” 

We never DM. NEVER share your Secret Recovery Phrase with any site or person. Verify links are legitimate. Contact us now
( meta.mask.help@mail.com)

**Comment by Nokhal** [comment]
^ The above user ([MetaMask-Support-io](https://github.com/MetaMask-Support-io)) is a scammer.

**Comment by anaamolnar** [comment]
Hello, @toshiboy86 Thanks for reporting! I will pass this on to the team.

**Comment by leo-2408** [comment]
any update here? I am experience the same thing @anaamolnar

**Comment by gauthierpetetin** [comment]
Hi @leo-2408 ,I'll reach out to SDK team and let you know.
cc @ezgi-cengiz for visibility

**Comment by christopherferreira9** [comment]
Hi all! Unfortunately, the redirect from MetaMask back to dapp is [no longer supported since iOS 17](https://github.com/MetaMask/metamask-mobile/issues/7165) as the OS api that allowed us to use that functionality was removed. We're very sorry for that. 
As for the warning message it should no longer be present on the SDK side as of v0.15.0.

**Comment by dnovacik** [comment]
This issue is also present for us when using react-sdk in electron application.

**Comment by vadempur** [comment]
still issue exist for me also

**Comment by gauthierpetetin** [comment]
Hi @vadempur ! Would you be able to share more details about your issue?
If the issue you're experiencing exists on the SDK side please feel free to open an issue in the [MetaMask SDK repository](https://github.com/MetaMask/metamask-sdk).

**Comment by christopherferreira9** [comment]
Hi @ishkash69 ! What kind of connections are you referring to? WalletConnect or MetaMaskSDK?

**Comment by ishkash69** [comment]
HI @christopherferreira9  I am using Thirdweb react native SDK for wallet connections.
