### ISSUE TITLE
BDD scenario for dapp testing

### ISSUE THREAD

**Issue by cortisiko** [MetaMask/metamask-mobile#8039]
### What is this about?

We want to ensure that we have manual test scenarios for Dapp testing. 

Also a great starting point here is to have a preselected list of the most popular dapps to test against. Maybe the top 5 dapps to test. Feel free to reach out to @cortisiko on getting the list of popular dapps. 

### Scenario

To be defined

### Design

- NA

### Technical Details

- TBD

### Threat Modeling Framework

- TBD

### Acceptance Criteria

- Update the regression board with the created feature file

### Stakeholder review needed before the work gets merged

- [] Engineering (needed in most cases)
- [ ] Design
- [ ] Product
- [X] QA (automation tests are required to pass before merging PRs but not all changes are covered by automation tests - please review if QA is needed beyond automation tests)
- [ ] Security
- [ ] Legal
- [ ] Marketing
- [ ] Management (please specify)
- [ ] Other (please specify)

**Comment by chrisleewilcox** [comment]
BDD scenario for dapp testing: https://www.notion.so/DappsMarketplace-feature-5cabb30aab5c40ff9e2d87320c307352
