### ISSUE TITLE
BDD scenario for NFTs

### ISSUE THREAD

**Issue by cortisiko** [MetaMask/metamask-mobile#8040]
### What is this about?

We want to ensure that we have manual test scenarios for the NFT flow. 

### Scenario

To be defined

### Design

- NA

### Technical Details

- TBD

### Threat Modeling Framework

- TBD

### Acceptance Criteria

- Update this [task](https://app.zenhub.com/workspaces/mobile-release-regression-6249e5242464b70013315a98/issues/gh/metamask/mobile-planning/515) with the newly created feature file

### Stakeholder review needed before the work gets merged

- [] Engineering (needed in most cases)
- [ ] Design
- [ ] Product
- [X] QA (automation tests are required to pass before merging PRs but not all changes are covered by automation tests - please review if QA is needed beyond automation tests)
- [ ] Security
- [ ] Legal
- [ ] Marketing
- [ ] Management (please specify)
- [ ] Other (please specify)

**Comment by chrisleewilcox** [comment]
BDD scenarios for NFTs: https://www.notion.so/Feature-files-Mobile-826b98bfa63e4eaead89d8d8ba9806e9?pvs=4#8d5f4e17c9df4efc977f2a6fe3336044
