### ISSUE TITLE
Transactions speed up and cancel

### ISSUE THREAD

**Issue by cortisiko** [MetaMask/metamask-mobile#8041]
### What is this about?

We want to ensure that we have manual test scenarios for:

Cancelling a transaction
Speeding up a transaction

Enabling and verifying notifications for transactions.  

### Scenario

To be defined

### Design

- NA

### Technical Details

- TBD

### Threat Modeling Framework

- TBD

### Acceptance Criteria

- Update this [task](https://app.zenhub.com/workspaces/mobile-release-regression-6249e5242464b70013315a98/issues/gh/metamask/mobile-planning/517) with the created feature file

### Stakeholder review needed before the work gets merged

- [] Engineering (needed in most cases)
- [ ] Design
- [ ] Product
- [X] QA (automation tests are required to pass before merging PRs but not all changes are covered by automation tests - please review if QA is needed beyond automation tests)
- [ ] Security
- [ ] Legal
- [ ] Marketing
- [ ] Management (please specify)
- [ ] Other (please specify)

**Comment by chrisleewilcox** [comment]
Linked task has been updated.
