### ISSUE TITLE
How do I set the metamask app to redirect back to a PWA after metamask wallet is connected via deeplink

### ISSUE THREAD

**Issue by tycooperaow** [MetaMask/metamask-mobile#8055]
### What is this about?

I am trying to simulate this experience. 
https://github.com/MetaMask/metamask-mobile/assets/35544142/3c3e2508-581c-4622-90d4-0270f257cbd6

This app uses web3auth, but I prefer not to use them and allow users to confirm their metamask through a deep link.

I have the deeplink part set up as:
`window.location.href = 'https://metamask.app.link/dapp/strmline.co/pass;'`
but the only issue becomes that the link opens within metamask browser not open back to the PWA. It also does not prompt the user to confirm their wallet either, any tips?

### Scenario

- When user presses connect to metamask in a custom button
- It should open the metamask app on ios device
- prompt user to connect their wallet
- redirect user back to the PWA

### Stakeholder review needed before the work gets merged

- [ ] Engineering (needed in most cases)
- [ ] Design
- [ ] Product
- [ ] QA (automation tests are required to pass before merging PRs but not all changes are covered by automation tests - please review if QA is needed beyond automation tests)
- [ ] Security
- [ ] Legal
- [ ] Marketing
- [ ] Management (please specify)
- [ ] Other (please specify)

**Comment by christopherferreira9** [comment]
Hi @tycooperaow ! 
Are you trying to open the MetaMask inapp browser to connect the user? If so, you won't be able to direct the user back to your dapp. 
This is an awesome scenario to use the [MetaMask SDK](https://github.com/MetaMask/metamask-sdk). Take a look at it and feel free to report any issues you encounter on that repository.
