### ISSUE TITLE
[Bug]: PPOM - Signature Metric events have the `flagged_as_malicious` and Blockaid info when using a different network than Mainnet

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-mobile#8065]
### Describe the bug

**Problem:** whenever I am on a different network than Mainnet (i.e. Sepolia) if I perform signatures from the test dapp I can see how the metrics information for that event displays PPOM information (i.e. flagged as malicious, reason, RPC counts, etc).

```
Analytics 'trackEventWithParameters' - {"category": "Signature Rejected"} {"account_type": "MetaMask", "chain_id": "11155111", "dapp_host_name": "metamask.github.io", "ppom_debug_traceCall_count": 1, "ppom_eth_call_count": 12, "ppom_eth_getBalance_count": 1, "ppom_eth_getBlockByNumber_count": 1, "request_platform": undefined, "request_source": "In-App-Browser", "security_alert_reason": "seaport_farming", "security_alert_response": "Malicious", "signature_type": "eth_signTypedData_v4", "ui_customizations": ["flagged_as_malicious"], "version": "V4"}
```

### Expected behavior

For not supported networks, we should see the same as we see in Extension:

```
    security_alert_reason: 'NotApplicable',
    security_alert_response: 'NotApplicable',
```
and no RPC counts

![Screenshot from 2023-12-11 11-53-24](https://github.com/MetaMask/metamask-mobile/assets/54408225/166f001c-75ef-4cf4-8380-00ae2a7f6bc8)

### Screenshots/Recordings

https://github.com/MetaMask/metamask-mobile/assets/54408225/ac0acb8f-4b08-4a48-b546-746642b9e047

### Steps to reproduce

1. Enable Blockaid
2. Select Sepolia network
3. Go to test dapp
4. Trigger any signature
5. Reject/Accept the signature
6. See log metrics events, with Blockaid information (flagged as malicious,etc)

### Version

7.14.0

### Build type

None

### Device

Pixel 6

### Operating system

Android

**Comment by bschorchit** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/-Confirmations-Secure-UX-6245e6e2348677001213b8d2/issues/MetaMask/metamask-mobile/8065?planning-poker) with Zenhub @blackdevelopa @digiwand @jpuri @seaona @segun
