### ISSUE TITLE
[Bug]: PPOM - `Request failed` for SendERC20, ApproveERC20 and ApproveERC721 transactions using Wallet Connect

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-mobile#8066]
### Describe the bug

**Problem:** whenever I am using Wallet Connect I can see how the PPOM module fails to return a response for the case of:
- Malicious SendERC20
- Malicious ApproveERC20
- Malicious ApproveERC721

Using the same account and transactions without wallet connect, results into flagging the transactions as malicious, but when using wallet connect I see the ` LOG  [MetaMask DEBUG]: Error validating JSON RPC using PPOM: Error: simulation: error: execution reverted` on the logs and the fallback UI warning.

### Expected behavior

These tx should alse be flagged as malicious when using Wallet Connect.

### Screenshots/Recordings

https://github.com/MetaMask/metamask-mobile/assets/54408225/364c4dfd-595b-4849-8e9e-3dff6733db53

### Steps to reproduce

1. Go to https://seaona.github.io/test-dapp/
2. Click Connect Wallet Connect
3. Scan the QR from your mobile wallet
4. Click again  Wallet Connect in the test dapp --- this is necessary for the dapp to detect the mobile account
5. Trigger any malicious: SendERC20, ApproveERC20 or ApproveERC721 tx
6. See error in the console `LOG  [MetaMask DEBUG]: Error validating JSON RPC using PPOM: Error: simulation: error: execution reverted`

### Version

7.14.0

### Build type

None

### Device

Pixel 6

### Operating system

Android

**Comment by bschorchit** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/-Confirmations-Secure-UX-6245e6e2348677001213b8d2/issues/MetaMask/metamask-mobile/8066?planning-poker) with Zenhub @blackdevelopa @digiwand @jpuri @seaona @segun

**Comment by segun** [comment]
Hi @seaona I fixed the wallet connect issue for 

- Malicious ApproveERC20
- Malicious ApproveERC721
- Malicious Approval for All

But I couldn't find the issue with `Malicious SendERC20` I noticed this was an issue too when you connect without wallet connect. The error is coming from PPOM. This is the response from PPOM 
```
{"providerRequestsCount": {"debug_traceCall": 2, "eth_getBalance": 1, "eth_getBlockByNumber": 1}, "result": {"block": 18791372, "description": "Transaction reverted: error: execution reverted", "features": [], "reason": "reverted", "result_type": "Benign"}}
```
