### ISSUE TITLE
[Bug]: PPOM - Interrupted initialization makes PPOM not work and not recover unless disabled and re-enabled again

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-mobile#8068]
### Describe the bug

**Problem:** whenever we enable the  Blockaid feature, if the internet is down in the moment we are initializing PPOM, we can see how then, there is no way to "re-store" the functionality, unless you disable and enable it again.

### Expected behavior

It should eventually be initialized?
Not sure if there should be a mechanism for re-try cc @bschorchit @jpuri 

### Screenshots/Recordings

https://github.com/MetaMask/metamask-mobile/assets/54408225/ae023577-1e66-475d-933a-8a101c5ef92c

### Steps to reproduce

1. Enable Blockaid
2. Turn off the internet
3. Turn on the internet
4. See setting is enabled
5. Trigger a malicious tx
6. See Fallback warning

### Version

7.14.0

### Build type

None

### Device

Pixel 6

### Operating system

Android

**Comment by bschorchit** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/-Confirmations-Secure-UX-6245e6e2348677001213b8d2/issues/MetaMask/metamask-mobile/8068?planning-poker) with Zenhub @blackdevelopa @digiwand @jpuri @seaona @segun

**Comment by bschorchit** [comment]
This issue should cover showing to the user that activation failed

**Comment by jpuri** [comment]
The PR covers the requires PPOMController changes for the task: https://github.com/MetaMask/ppom-validator/pull/107

@blackdevelopa : can you plz check. the changes required on UI side ?

**Comment by jpuri** [comment]
@bschorchit , @SayaGT : I am thinking of a design like this for the task:


[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeWxsQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9b73a4a61899e2cad18fce566be6083ac26bac96/Screen%20Recording%202023-12-15%20at%204.27.58%E2%80%AFPM.mov)

if initialisation fails we show message to user with option to re-start initialisation.
