### ISSUE TITLE
[Bug]: Cannot deploy any contract - rare case

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-mobile#8098]
### Describe the bug

**Problem:** whenever I try to deploy a contract nothing happens and the modal for confirmation is not open

### Expected behavior

A confirmations modal should be displayed

### Screenshots/Recordings

https://github.com/MetaMask/metamask-mobile/assets/54408225/1d2a69a5-a845-40da-b7c3-9626f85e8368

### Steps to reproduce

It seems that the wallet entered into a weird state, and then this is how it was repro:
1. Go to the test dapp
2. Connect MM
3. Try to deploy any contract (ERC20/ERC721/Multisig etc)
4. See nothing happens

After removing the wallet and rebuilding, the behaviour was not happening anymore.

### Version

7.14.0

### Build type

None

### Device

Pixel 6

### Operating system

Android

**Comment by PressGarden** [comment]
Hello,

Thank you for reporting this issue. This has been assigned to the appropriate team to look into.

Best regards,
Axel
