### ISSUE TITLE
[Bug]: "Select an account" page should highlight the active account 

### ISSUE THREAD

**Issue by yanrong-chen** [MetaMask/metamask-mobile#8099]
### Describe the bug

The active account on the select account page should be highlighted. There's currently no account highlighted on the account selection page. Not consistent with [design](https://www.figma.com/file/yueOvghWxXK464CTzUmFXf/Multichain-(MC)-v0.5-mobile?type=design&node-id=177-11117&mode=design&t=ewCKwxa9huRNzbzw-0). 

### Screenshots/Recordings

Should be highlighted like this:
<img width="329" alt="Screenshot 2023-12-14 at 11 39 14 AM" src="https://github.com/MetaMask/metamask-mobile/assets/59982439/b3f45329-f0a5-42de-9458-a2000ff71547">

### Steps to reproduce

Go to wallet page
Click on the active account to go to "Select an account" page
Notice that the account is not selected

### Version

7.12.2

### Build type

None

### Device

iphone

### Operating system

iOS

**Comment by Cal-L** [comment]
An issue for this exists - https://github.com/MetaMask/mobile-planning/issues/1340
