### ISSUE TITLE
[Bug]: Issues with connecting to Optimism chain in Metamask Mobile Browser

### ISSUE THREAD

**Issue by meri-maki** [MetaMask/metamask-mobile#8158]
### Describe the bug

In my dapp (web) I use wagmi and web3modal to connect to the app

Since MetaMask has issues with connecting in default mobile browsers we are forcing users to connect to dapp via MM mobile browser

We configured only optimism chain but when it connects on desktop browser I get this error:

![image](https://github.com/MetaMask/metamask-mobile/assets/97887955/f1aa7a57-ef11-4406-b992-7aa360839f92)

In MM mobile browser it doesn't ask me to switch chain (or add it, which is more important in our case) and displays chain as chain 1

![IMG_4659](https://github.com/MetaMask/metamask-mobile/assets/97887955/e3f407c5-b3c4-48bf-9c97-b2c10d60af50)

I'm suspecting it's because in wagmi the chain id is '0xa' while in Metamask is '10'

Is there a way around this? this is not for sure a wagmi issue, optimism chain works perfectly fine on other wallet apps

### Expected behavior

In Metamask mobile browser dapp should smoothly connect to optimism chain (asking to add it if needed)

### Steps to reproduce

To see console error
1.https://wagmi-read.vercel.app/ opn in browser with MM chrome extension
2. connect wallet that doesn't have OPTIMISM in added chains
3. see error when trying to add chain

In Metamask mobile browser
1. open https://wagmi-read.vercel.app/
2. try connecting
3. see weird behavior in showing chain

repo https://github.com/meri-maki/useSwitchNetwork

### Error messages or log output

```shell
VM434:1 MetaMask - RPC Error: Unrecognized chain ID "0xa". Try adding the chain using wallet_addEthereumChain first. {code: 4902, message: 'Unrecognized chain ID "0xa". Try adding the chain using wallet_addEthereumChain first.', stack: '{\n  "code": 4902,\n  "message": "Unrecognized chain…gaeaoehlefnkodbefgpgknn/background-3.js:12:51003)'}
```

### Version

7.12.3(1230)

### Build type

None

### Device

Iphone 11

### Operating system

iOS

### Additional context

https://github.com/MetaMask/metamask-mobile/issues/4492

### Severity

affects hugely the release of the app, considering removing Metamask as an option to connect completely

**Comment by vandan** [comment]
Might be a little slow to investigate due to holiday. While we recognize you're using a few libraries that may abstract some of this away, you can find our official guidelines for working with networks here: https://docs.metamask.io/wallet/how-to/add-network/

Please let us know if that helps at all.

**Comment by tmashuang** [comment]
Upon investigation, I was successfully added, switch, and connect to network.

**Comment by meri-maki** [comment]
> Upon investigation, I was successfully added, switch, and connect to network the extension. Is there any additional information that can help reproduce this issue's behavior?

Hi! Did you connect wallet with optimism chain already added? If it's added, it works fine
Try connecting a fresh wallet, with only ETH chain added

**Comment by tmashuang** [comment]
Yes, no issues when I tried reproducing. Could you provide a step by step reproduction?

**Comment by meri-maki** [comment]
> Yes, no issues when I tried reproducing. Could you provide a step by step reproduction?

@tmashuang 
https://github.com/MetaMask/metamask-mobile/assets/97887955/1ee436b0-9bbe-4d2d-a9f0-eead1adefccb

As you can see I'm connecting wallet with only eth and linea 
Browser wallet doesn't work, but metamask does
The app is only configured with 1 chain - optimism
It "connects", but with ethereum, not optimism
And chain name is displayed as "Chain 1"
The only way I can add it is manually adding optimism to networks, then it works correct

**Comment by danilpyregov** [comment]
I have the same error

**Comment by gauthierpetetin** [comment]
Hi @meri-maki , it seems like an error on dapp side: dapp needs to call [wallet_switchEthereumChain](https://docs.metamask.io/wallet/reference/wallet_switchethereumchain/).

[Uniswap's](https://app.uniswap.org/) network switching interaction is an example to follow.
