### ISSUE TITLE
Change mobile token list item component format for consistency

### ISSUE THREAD

**Issue by yanrong-chen** [MetaMask/metamask-mobile#8168]
### What is this about?

To sync with extension and portfolio, we want to change the format and rearrange the token list item on mobile wallet. 
On the left, we will have the token ticker on the top and name of the token on the bottom as the secondary text. We will have token price on the right (whether it's fiat or ETH value on top depends on user settings preference).

<img width="709" alt="Screenshot 2023-12-18 at 2 30 46 PM" src="https://github.com/MetaMask/metamask-mobile/assets/59982439/7b869b45-5cfd-4220-a1ef-75f99f76f640">

@Akatori-Design @hesterbruikman for visibility

### Design

[Design file](https://www.figma.com/file/MlBUrNnIXlftX4TSjqiUYg/Core-Components?type=design&node-id=1270-12529&mode=design&t=VZs4SMvVogDU6cIs-0) for reference

### Stakeholder review needed before the work gets merged

- [X] Engineering (needed in most cases)
- [ ] Design
- [X] Product
- [ ] QA (automation tests are required to pass before merging PRs but not all changes are covered by automation tests - please review if QA is needed beyond automation tests)
- [ ] Security
- [ ] Legal
- [ ] Marketing
- [ ] Management (please specify)
- [ ] Other (please specify)

**Comment by amandaye0h** [comment]
Resolved IA issues in with additional feature work, this is the state as of Sept 16 2024
<img width="852" alt="Screenshot 2024-09-18 at 7 19 29 AM" src="https://github.com/user-attachments/assets/717b59ab-d622-4db3-867d-0c11c42e526d">

Will follow up with mobile CSS/ centering issues in a separate ticket
