### ISSUE TITLE
[Bug]: 'Backspace' button doesn't work on Huawei keyboard (Browserstack).

### ISSUE THREAD

**Issue by sleepytanya** [MetaMask/metamask-mobile#8189]
### Describe the bug

'Backspace' button doesn't work on Huawei keyboard (Browserstack) on any screen where this button is available. It is also impossible to type from computer keyboard like on other devices keyboards.

### Expected behavior

'Backspace' button should work properly. (Not sure if input from the computer keyboard should work)

### Screenshots/Recordings

https://github.com/MetaMask/metamask-mobile/assets/104780023/3c4e5814-6b26-4aa8-8bf1-02975a081566

### Steps to reproduce

1. Go to Browserstack, App Live
2. Upload the app
3. Choose Huawei P30 9
4. Try use 'backspace' button on device keyboard or try to type anything using computer keyboard.

### Version

7.14.0

### Build type

Other (please specify exactly where you obtained this build in "Additional Context" section)

### Device

Huawei P30 9

### Operating system

Android

### Additional context

[Bitrise QA build](https://app.bitrise.io/build/be7d0939-c6d8-4750-a6cc-14af3cb8d9a7?tab=artifacts)

**Comment by plasmacorral** [comment]
I think this is likely a browserstack issue, rather than something for one of our teams to fix.  Does backspace work on other devices in browserstack?  What about other Huawei devices in browserstack?

**Comment by sleepytanya** [comment]
@plasmacorral I didn't check all the devices but most of them, backspace didn't work on Huawei only. There is 1 Huawei device available on Browserstack. I agree that this can be Browserstack issue. I'll ask mobile team if they have Huawei phone.

**Comment by plasmacorral** [comment]
Making a note here....I encountered an issue with the single Huawei device in Browserstack recently where every input to the keyboard was doubled on a single tap.
