### ISSUE TITLE
[Bug]: Rounding issue in approval amount (use site suggestion) 

### ISSUE THREAD

**Issue by RanGojo** [MetaMask/metamask-mobile#8199]
### Describe the bug

While testing our dApp using metamask webview / metamask android, I saw that the approval transaction amount is modified by metamask even if the user clicks on "Use site suggestion".
I believe there is a rounding issue when metamask decodes and encodes the user amount.

For example, this is the tx data which is generated by dApp:
```
0x095ea7b300000000000000000000000069460570c93f9de5e2edbc3052bf10125f0ca22d000000000000000000000000000000000000000000000000576129d2d21d64a5
```

and this is the final data used by metamask even if user clicks on use site suggestion:

```
0x095ea7b300000000000000000000000069460570c93f9de5e2edbc3052bf10125f0ca22d000000000000000000000000000000000000000000000000576129d2d21d6400
```

as you can see, the amount part is slightly changed. 
Expected amount based on original data: 6.2963597394856**76709**
Metamask modified version: 6.2963597394856**76544**

### Screenshots/Recordings

None

### Expected behavior

I think when user clicks on use site suggestion, dapp transaction data should not be changed.

### Steps to reproduce

1. Go to Metamask Webview
2. Send an approval transaction with this 'data' (0x095ea7b300000000000000000000000069460570c93f9de5e2edbc3052bf10125f0ca22d000000000000000000000000000000000000000000000000576129d2d21d6**4a5**)
3. Click on use site suggested amount and accept the approval transaction.
4. Final transaction data is changed by mistake to this  one:
(0x095ea7b300000000000000000000000069460570c93f9de5e2edbc3052bf10125f0ca22d000000000000000000000000000000000000000000000000576129d2d21d6**400**)

### Error messages or log output

There is no specific error log. 

### Version

7.12.3

### Build type

None

### Device

Samsung S21 

### Operating system

Android

### Additional context

I faced this bug in Metamask android version several times, but I'm not sure if it is only related to Metamask mobile or the android version. 

### Severity

It creates some bugs during the next steps of dapps transactions flow.

**Comment by gauthierpetetin** [comment]
Hi @bschorchit , we've assigned this issue to the Confirmations teams during triage but weren't sure whether this is for UX or System team.

**Comment by gauthierpetetin** [comment]
@RanGojo could you please let us know:
- What dApp you are using?
- Is this an ETH transfer or a token transfer?

**Comment by dexkim-metabora** [comment]
I have also encountered a similar issue. On ERC20 approval request through Metamask mobile, I've observed discrepancies between the number displayed inside the input box and the requested approval amount. This inconsistency seems to occur more frequently when the specified number has a decimal less than 1e-14 or exceeds 30,000. To demonstrate this issue, I created a test application forked from the original at https://github.com/MetaMask/test-dapp.

[https://mtmtest.boralabs.net/](metamask e2e tester)

NOTE: This test app may not be available without any farther notice.

The only modification I made to the original application is in the user input customization for token approval requests:

```
// index.js line # 1553
const result = await hstContract.approve(
      approveTokensToInput.value,
      // Following parameter is changed from static "7 * 10 ** 18"
      ethers.utils.parseUnits(
        approveAmountInput.value,
        decimalUnitsInput.value,
      ),
...
)
```

https://github.com/MetaMask/metamask-mobile/assets/126214856/32d4d725-d512-47a9-833f-f17d6c3a360d

## Description to the video

The test is performed on Polygon Testnet Chain (Mumbai, Network Id: 80001)
On user input amount 50,000 -> MTM input shows: 49999.9999...5696 ( < 50,000 )
On user input amount 47,500 -> MTM input shows: 47499.9999...4272 ( < 47,500 )
On user input amount 55 -> MTM input shows: 55 ( = 55 )

Here is raw tx input data for case no.1 (input 50,000)
desired:
```
0x095ea7b30000000000000000000000009bc5baf874d2da8d216ae9f137804184ee5afef4000000000000000000000000000000000000000000000a968163f0a57b400000
```

actual:
```
0x095ea7b30000000000000000000000009bc5baf874d2da8d216ae9f137804184ee5afef4000000000000000000000000000000000000000000000a968163f0a57b000000
```

## Version

7.12.3

## Device

Samsung Galaxy S9, iPhone 12 mini, Samsung Galaxy A32 and more...

## Operating System

Android & iOS

## Additional Context

The same problem occurred in the previous version too, where specifying input amounts with many decimal places led to the input not being processed as intended.

**Comment by seaona** [comment]
Might relate to https://github.com/MetaMask/metamask-mobile/issues/7671

**Comment by digiwand** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/-Confirmations-Secure-UX-6245e6e2348677001213b8d2/issues/MetaMask/metamask-mobile/8199?planning-poker) with Zenhub @blackdevelopa @digiwand @jpuri @seaona @segun

**Comment by blackdevelopa** [comment]
Hey @dexkim-metabora, thanks for forking the test dapp and sharing your link. There is a proposed [PR](https://github.com/MetaMask/metamask-mobile/pull/8485) that should fix this.

cc @RanGojo. Thanks for reporting this issue.
