### ISSUE TITLE
[Bug]: Development environment installation fails due to boost checksum mismatch

### ISSUE THREAD

**Issue by Gudahtt** [MetaMask/metamask-mobile#8220]
### Describe the bug

When running `yarn setup` locally, I was seeing the `pod:install` step failing (it prints "Skipping pod install" to the console when this happens). I tried running `yarn pod:install` directly and saw this error:

```
[!] Error installing boost
Verification checksum was incorrect, expected f0397ba6e982c4450f27bf32a2a83292aba035b827a5623a14636ea583318c41, got 5e89103d9b70bba5c91a794126b169cb67654be2051f90cf7c22ba6893ede0ff
```

It seems that the `boost` pod is not installed correctly due to this checksum mismatch. The rest of the pods get installed successfully.

### Expected behavior

All dependencies should be installed correctly.

### Steps to reproduce

* Delete `ios/Pods` to remove cached pods
* Run `yarn pod:install`

### Version

main branch

### Build type

None

### Device

N/A

### Operating system

Other (please elaborate in the "Additional Context" section)

**Comment by plasmacorral** [comment]
I also see this when attempting to build android locally.

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native:ReactAndroid:prepareBoost'.
> Could not read /Users/mb/Dev/Mobile/metamask-mobile/node_modules/react-native/ReactAndroid/build/downloads/boost_1_76_0.tar.gz.
   > Not in GZIP format
```

**Comment by wachunei** [comment]
Here is a workaround https://github.com/facebook/react-native/issues/42180

**Comment by PressGarden** [comment]
Hello,

Thank you for reporting this issue. This has been assigned to the appropriate team to look into.

Best regards,
Axel

**Comment by vandan** [comment]
This issue is more appropriate for Mobile Platform.
