### ISSUE TITLE
[Bug]: Nonce discrepancy during ongoing transaction approval if another transaction is confirmed

### ISSUE THREAD

**Issue by OGPoyraz** [MetaMask/metamask-mobile#8261]
### Describe the bug

When a user initiates a transaction and it is in the `submitted` state, and concurrently starts the approval process for another transaction, an error occurs if the `submitted` transaction gets `confirmed` while the user is still on the approval screen for the ongoing transaction. After the user approves the ongoing transaction, it results in an error. (Nonce error can be seen in dev mode)

### Expected behavior

- Nonce should be correctly handled

### Steps to reproduce

Please see @sleepytanya's recording to reproduce steps here:  https://github.com/MetaMask/metamask-mobile/issues/7311#issuecomment-1888468018

### Version

7.12.5

### Build type

None

### Device

Any Android or iOS device

### Operating system

iOS, Android

**Comment by sleepytanya** [comment]
Steps to reproduce:
1. Go to [metamask.github.io/test-dapp](metamask.github.io/test-dapp)
2. Initiate 'Legacy' transaction with low gas
3. 'Create token'
4. Go to 'Activity' tab and speed up 'Legacy' transaction
5. Go back to [metamask.github.io/test-dapp](metamask.github.io/test-dapp)
6. Click 'Approve' when button becomes available

The error on real Android device can be seen [here](https://github.com/MetaMask/metamask-mobile/issues/7311#issuecomment-1888468018).

Here is video for Browserstack device - iPhone 13 v16.3 - error is not happening (so we need to confirm if bug occurs on real physical device):


https://github.com/MetaMask/metamask-mobile/assets/104780023/33972cc4-1532-4201-a94d-b2ffb0c532e3

**Comment by sleepytanya** [comment]
Android test build (`main`) - no error:

https://github.com/MetaMask/metamask-mobile/assets/104780023/795bb0b6-f0e7-404a-94a7-28aa70a4a809

**Comment by OGPoyraz** [comment]
I can confirm this is also happening on real device on Android
![2024-01-15 11 04 42](https://github.com/MetaMask/metamask-mobile/assets/7644512/60cabf74-a0b9-4cc3-bc42-af8fe350e3e2)
![2024-01-15 11 04 37](https://github.com/MetaMask/metamask-mobile/assets/7644512/4a079bb1-0257-4e97-ba99-83418779173d)

**Comment by OGPoyraz** [comment]
Unfortunately I couldn't repro once again after seeing that on my phone with retail version. 

This is @vinistevam 's Android test recording, it doesn't happen on his device too.

https://github.com/MetaMask/metamask-mobile/assets/7644512/01d5d847-cc78-4882-bd6e-c060f2dcac67

I will put this issue into -dormant section on our backlog
