### ISSUE TITLE
[Bug]: Signatures stopped working on a weird wallet state

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-mobile#8307]
### Describe the bug

**Problem:** while I was using the test dapp, suddenly triggering signatures stopped working. I saw some errors previously to that, indicating that the wallet was on a weird state. Not sure if those are related and not yet determined how to reproduce it.
After closing and opening the wallet, Signatures worked back again.

### Expected behavior

No errors.
Signatures should work

### Screenshots/Recordings
Screenshot from 2024-01-17 11-47-15

Errors seen

https://github.com/MetaMask/metamask-mobile/assets/54408225/337971ad-07d0-4306-8db1-a69fb949f8bb

Signatures not working / Tx working, after errors seen

https://github.com/MetaMask/metamask-mobile/assets/54408225/47f0c1dd-ad54-40db-9ad1-7af2c39067d6

### Steps to reproduce

[update from @seaona ] found one way to reproduce it consistenly:
1. checkout this branch of the test dapp https://github.com/MetaMask/test-dapp/pull/294
2. go to the test dapp
3. connect mm
4. trigger send Eth malicious batch
5. now trigger any signature -- signatures won't work

https://github.com/MetaMask/metamask-mobile/assets/54408225/e9ad06ad-0ded-4772-8ccf-a43e74d40947

### Error messages or log output

- `Cannot read property 'negative' of undefined`
-  `Cannot read property 'postMessage' of null`

### Version

7.15.0 - but nothing indicates it's a regression (might be an old issue) // to determine repro steps first

### Build type

None

### Device

Pixel 6

### Operating system

Android

**Comment by plasmacorral** [comment]
I encountered this recently in testing for the mobile RC 7.17.0 on iOS 17.3.1 iPhone XS.  Unable to reproduce, so uncertain how I arrived in the condition, but signature buttons simply would not respond within the MMM browser, after I had previously connected, successfully sent tx's, and deployed multiple contracts.  Will continue to monitor.

**Comment by plasmacorral** [comment]
Just a quick note here....Uncertain if what I encountered is a variation of Mariona's original issue, some variant, or unrelated.  Regardless, wanted to make a note here about https://github.com/MetaMask/metamask-extension/pull/21709#issuecomment-1967942759

**Comment by seaona** [comment]
I've encountered this again. It seems that one way to reproduce it is with a MM freash install, going to the test dapp, performing a couple of Sends (reject&accept) and then performing a signature
