### ISSUE TITLE
[Bug]:  Switchnetwork error when connecting metamask-mobile via walletconnect

### ISSUE THREAD

**Issue by siosio34** [MetaMask/metamask-mobile#8380]
### Describe the bug

There are many issues where switch chain does not work within walletconnect as shown below.

https://github.com/MetaMask/metamask-mobile/issues/6655
https://github.com/MetaMask/metamask-mobile/issues/7206
https://github.com/MetaMask/metamask-mobile/issues/7878
https://github.com/WalletConnect/walletconnect-monorepo/issues/4089
https://github.com/wevm/wagmi/issues/3350
https://github.com/wevm/references/issues/393

If other wallet applications don't work, you'd think it's an issue with walletconnect, but it hasn't been resolved only in metamask mobile for several months.

This issue has been posted not only on MetaMask but also on wagmi and walletconnect repo. However, they are saying that it is not their fault because this issue only occurred on MetaMask Mobile, and in fact, it seems that this issue is a MetaMask Mobile issue.   I'm wondering if the reason it hasn't been resolved for several months is a technical issue or if it's just not planned for support in the future.

Depending on the answer, we need to change the UX so that the switchNetwork function is not called for mobile users.

### Steps to reproduce

call switchNetwork in metamask mobile via walletconnect2

### Version

all metamask mobile version

### Build type

None

### Device

all device

### Operating system

iOS, Android

**Comment by jurosh** [comment]
It's also not working with Ethers https://github.com/WalletConnect/web-examples/blob/main/dapps/ethereum-provider/src/App.tsx#L25

It should work like this in Ethers v6

```TypeScript
const provider = await EthereumProvider.init({ ...params });
const ethersProvider = new ethers.BrowserProvider(provider);
// Activate wallet
const signer = await ethersProvider.getSigner();
// Try to call RPC method - switch chain
signer.provider.send("wallet_switchEthereumChain", {chainId: "0x2802ddd4"})
```

The error is

```
Uncaught Error: unsupported operation (operation="wallet_switchEthereumChain", info={ "error": { "code": -32601, "message": "the method wallet_switchEthereumChain does not exist/is not available" }, "payload": { "id": 2, "jsonrpc": "2.0", "method": "wallet_switchEthereumChain", "params": { "chainId": "0x2802ddd4" } } }, code=UNSUPPORTED_OPERATION, version=6.9.0)
```

It seems to work tho if used with `provider` directly. Bur problems start when used standardized way with `BrowserProvider`.

**Comment by christopherferreira9** [comment]
Hi @siosio34 .
As we've said before in those other issues, MetaMask only supports a subset of the **WalletConnect** protocol.
In fact, there are two parts for it.
The first is that `wallet_switchEthereumChain` will work the first time the user tries to change chain programatically but in all subsequent requests the wallet gets no request whatsoever. Without a request there is no possibility of acting upon. 
Here's an example:
```
ethersProvider.provider.request({
    method: 'wallet_switchEthereumChain',
    params: [{ chainId: '0xa4b1' }]
})
```

Here's the video:

https://github.com/MetaMask/metamask-mobile/assets/104831203/4e96c86f-e911-4f0f-8c38-a52f6cad35cf

Details about the video:
- Wallet logs on the left, dapp in the middle and screen recording of the wallet on the right
- At 0:16, right after connecting you can see me tap the "Switch chain" button and that prompts a chain request on the wallet
- This first chain change request was manually denied on the wallet
- At 0:26 you can see my prompting the second chain switch (keep in mind that the first request was denied so there hasn't been an approved chain switch request yet) 
- At 0:40 I manually switch chains on the wallet side and that gets synced on the dapp side
- At 0:52 you can see that no matter how many times I try to prompt a chain switch there are no logs coming in, meaning that there is no request being sent to the wallet.

The second part to it is that if the dapp is on a different chain that the wallet has active and the user tries to sign he should get a request asking to switch to the Chain on the dapp side:

https://github.com/MetaMask/metamask-mobile/assets/104831203/6d355e5b-6b96-4cda-a14b-9e008526f858

I hope to have clarified this issue.

**Comment by siosio34** [comment]
@christopherferreira9

The first thing you said is that you think this issue is caused by WalletConnect not sending any requests to the Metamask wallet?

If no logs are received, I think the opinion is valid and I think I will have to ask WalletConnect about the issue again.

**Comment by ganchoradkov** [comment]
Hey @siosio34 @christopherferreira9, chiming in from WalletConnect team.
I think there is misunderstanding in the expectations how chain switching should work and how its actually working. 
In WalletConnect v2, chain switching is done locally on the dapp side on all chains that were approved in the session. 
This means that users can switch between all approved chains without being required to approve the switch in their wallets.

If user tries to switch to chain that is not yet approved, the switch chain is sent to the wallet for approval. This allows the wallet to switch to that chain but also update the current session with appropriate address for that new chain.

This behaviour is consistent with @christopherferreira9 explanation above where only the first chain switch is sent to the wallet and all after are done locally without any request to the wallet.The chains were already approved for the session after all. 

I hope this clarifies how chain switching works and why sometimes you're not receiving any prompt in the wallet

**Comment by siosio34** [comment]
@ganchoradkov 
I understand what you are saying. However, although it also depends on the issue link in the text, the two issues below do not seem to be a normal flow for the average user. If this was intentional, please let me know.

first Unlike desktops, chain change requests do not work smoothly on mobile devices.
second If it is connected to a chain different from Ethereum, the chain is unnecessarily switched to the Ethereum chain when calling the sign function.

**Comment by BradMoeller** [comment]
> In WalletConnect v2, chain switching is done locally on the dapp side on all chains that were approved in the session.
This means that users can switch between all approved chains without being required to approve the switch in their wallets.

I'm currently struggling with this, in combination with the limitation of metamask only supporting 1 network for the requiredNamespace. https://github.com/WalletConnect/WalletConnectKotlinV2/issues/1325

If we can only request 1 network, the user can never switch between all approved chains, because they can only request 1.

**Comment by christopherferreira9** [comment]
Hi all. I'm closing this issue but I'll be sure to reference it if we ever change this behaviour when interacting with WalletConnect.
