### ISSUE TITLE
[Bug]: Deep links to dApps fail on iOS

### ISSUE THREAD

**Issue by UnfortuN8** [MetaMask/metamask-mobile#8388]
### Describe the bug

Deep links to dApp URLs open MetaMask but do not navigate to the dApp URL. 

### Expected behavior

I expected the MetaMask to open and then navigate to the dApp URL in the deep link.

### Screenshots/Recordings

https://github.com/MetaMask/metamask-mobile/assets/2441535/fbb108f5-3982-4cfc-9a15-c4eb8a48e974

### Steps to reproduce

1. On an iOS device, make sure the MetaMask app is closed (not in the background) by swiping it up from the recent apps view
2. Open Safari 
3. Go to https://metamask.github.io/metamask-deeplinks
4. Enter https://opensea.io/ as the dApp url
5. Tap on the generated deep link

### Version

7.14.0

### Build type

None

### Device

iPhone 14 Pro (iOS 17.1.2)

### Operating system

iOS

### Additional context

This issue seems to happen when the MetaMask app is launched in response to the deep link. Meaning, it does not occur if MetaMask is already open in the background.

If you are having trouble reproducing the issue, make sure the MetaMask app is closed, and not in the background, by swiping it away from the recent apps view in iOS.

**Comment by deshvin** [comment]
related to #7928

**Comment by christopherferreira9** [comment]
Fixed by https://github.com/MetaMask/metamask-mobile/pull/8469

https://github.com/MetaMask/metamask-mobile/assets/104831203/9271ed2a-206e-4880-9624-a96efc3938da
