### ISSUE TITLE
Allow connecting to custom RPCs over http

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-mobile#839]
I could not connect to `http://mycomputer.local:8545` because a validation said `https` is required.

I understand the security concern, but I think we should provide a checkbox with that validation to allow bypassing it.

**Comment by githubbrunob** [comment]
I used a nginx reverse proxy server to allow https over cloudflare.

**Comment by EtDu** [comment]
This appears to work fine on 0.2.19. Just make sure the server is listening on the local IP or `0.0.0.0` & not `localhost`.
