### ISSUE TITLE
Bell Icon for component-library

### ISSUE THREAD

**Issue by tommasini** [MetaMask/metamask-mobile#8406]
### What is this about?

We need a bell icon to replace the one used on [BackupAlert](https://github.com/MetaMask/metamask-mobile/blob/55d3aee20d1eab692324a72b31b89aab87ba9956/app/components/UI/BackupAlert/BackupAlert.tsx#L127)
![image](https://github.com/MetaMask/metamask-mobile/assets/46944231/3b258c3a-5326-4797-b871-8a60a0289dae)

### Stakeholder review needed before the work gets merged

- [X] Engineering (needed in most cases)
- [X] Design
- [X] Product
- [ ] QA (automation tests are required to pass before merging PRs but not all changes are covered by automation tests - please review if QA is needed beyond automation tests)
- [ ] Security
- [ ] Legal
- [ ] Marketing
- [ ] Management (please specify)
- [ ] Other (please specify)

**Comment by brianacnguyen** [comment]
The bell icon is currently already existed in the icon library under the Notification name
https://github.com/MetaMask/metamask-mobile/blob/main/app/component-library/components/Icons/Icon/assets/notification.svg

**Comment by tommasini** [comment]
Thanks Brian! Will close this issue!
