### ISSUE TITLE
[Mobile Account Snaps] Migrate all accounts references to selectors

### ISSUE THREAD

**Issue by owencraston** [MetaMask/metamask-mobile#8482]
Currently the account information is derived from the preferences controller. In order to make this migration easier we should first migrate these references into isolated selectors that will serve as the API for accessing account information. These selectors will still use the preference controller as their source of truth. 

[Here](https://github.com/MetaMask/metamask-extension/blob/3fe1f55488a19779c5ba3a7a1b049d1f055bf32e/ui/selectors/selectors.js#L303-L354) are the newly added selectors on the extension.

### References
Here are the relevant PRs on the extension
- https://github.com/MetaMask/metamask-extension/pull/21437
- https://github.com/MetaMask/metamask-extension/pull/21553
- https://github.com/MetaMask/metamask-extension/pull/21554
- https://github.com/MetaMask/metamask-extension/pull/21709

**Comment by gantunesr** [comment]
From a discussion with @owencraston, 

1. Replace all direct calls to the `preferences-controller` state (`selectedAddress` or `identities`) to either a selector or the `useAccounts` hook depending on the case. This should be also a good opportunity to add unit test in critical parts if they're missing.
2. Resolve the inconsistency regarding `importTime` between the data type in the `accounts-controller` and `preferences-controller`. The easiest option is to use the `preferences-controller` data. Important to take into consideration a similar approach as extension of blocking the user of adding duplicated accounts
3. Change the `preference-controller` selectors to `accounts-controller` selectors (`selectSelectedAddress` or `selectIdentities`).

Considerations,

- Keep in mind the [`InternalAccountStruct`](https://github.com/MetaMask/keyring-api/blob/main/src/internal/types.ts) against the `Identity` type
