### ISSUE TITLE
Fix local e2e for IOS

### ISSUE THREAD

**Issue by jpuri** [MetaMask/metamask-mobile#8501]
Local e2e on mobile for IOS is broken after this change was introduced: https://github.com/MetaMask/metamask-mobile/pull/8292/commits/b2d08e9b271144ef5e83528a5f3ef15e621cc544

More discussion here: https://consensys.slack.com/archives/C02U025CVU4/p1706727207245809

We need to fix this.

### Bug
<img width="680" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNjlIQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e7542ca8f8970e7562eb4625a93a27ba6b39bf06/image.png" alt="image.png" />
<img width="680" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN0JIQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--cd615f3b4fb63c6dd2b6366fe81f8d830d977763/image.png" alt="image.png" />

**Comment by digiwand** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/-Confirmations-Secure-UX-6245e6e2348677001213b8d2/issues/MetaMask/metamask-mobile/8501?planning-poker) with Zenhub @blackdevelopa @jpuri @seaona @digiwand
