### ISSUE TITLE
[Bug]: Recovering Personal Sign throws error `personal_ecRecover not available` when using WalletConnect

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-mobile#8518]
### Describe the bug

**Problem: ** whenever I am using Wallet Connect with the test dapp, if I use the Personal Sign signature and try to verify it I get the error  `personal_ecRecover not available` 

### Expected behavior

Recovering Personal Signatures should work with wallet connect

### Screenshots/Recordings

![Screenshot from 2024-02-04 10-14-47](https://github.com/MetaMask/metamask-mobile/assets/54408225/bd8e4fab-b8a2-467f-ad3d-c8b6b8af8093)

https://github.com/MetaMask/metamask-mobile/assets/54408225/0daa97a0-a9e4-4fe3-a48d-c168de5d2d8e

### Steps to reproduce

1. Connect Wallet connect to the test dapp- using this version: https://github.com/MetaMask/test-dapp/pull/284/files#diff-bfe9874d239014961b1ae4e89875a6155667db834a410aaaa2ebe3cf89820556
2. Click Personal Sign
3. Accept in Mobile wallet
4. Click Verify Signature
5. See error

### Version

7.14 prod (possible earlier too)

### Build type

None

### Device

Pixel 6

### Operating system

Android

**Comment by christopherferreira9** [comment]
works via SDK so means WC client (their side) makes it not available 
Hi @seaona ! I've tried this with the MetaMask SDK that uses the handling from the mobile wallet itself and it appears to be working so it seems that this error comes from the interaction with WalletConnect itself
