### ISSUE TITLE
[Bug]: Sign Type Data throws error `JSON Parse Error: Unexpected token : x, data` when using WalletConnect

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-mobile#8519]
### Describe the bug

**Problem: ** whenever using the test dapp with Wallet Connect, if I try the Typed Signature, I get the error `JSON Parse Error: Unexpected token : x, data`

### Expected behavior

Typed Signature should work with wallet connect

### Screenshots/Recordings

![Screenshot from 2024-02-04 10-17-57](https://github.com/MetaMask/metamask-mobile/assets/54408225/739a97bd-601f-49aa-867f-db1738365120)

https://github.com/MetaMask/metamask-mobile/assets/54408225/ff289fdc-c9ca-428a-be79-426d598892e5

### Steps to reproduce

1. Connect Wallet connect to the test dapp- using this version: https://github.com/MetaMask/test-dapp/pull/284/files#diff-bfe9874d239014961b1ae4e89875a6155667db834a410aaaa2ebe3cf89820556
2. Click Typed Signature
3. See error

### Version

7.14 prod (possible earlier too)

### Build type

None

### Device

Pixel 6

### Operating system

Android

**Comment by christopherferreira9** [comment]
Hi @seaona ! After looking a this in more detail it seems that when using WalletConnect this method is being [overwritten](https://github.com/MetaMask/metamask-mobile/blob/fcbff653e5486b92118c16ac47a147d782f33bcf/app/core/WalletConnect/WalletConnectV2.ts#L348) with `eth_signTypedData_v3`. I'm not sure if this is a requirement from WalletConnect themselves but will circle back after syncing with them.
