### ISSUE TITLE
[Bug]:Company Logo is not displayed in connect wallet popup  

### ISSUE THREAD

**Issue by davidli108** [MetaMask/metamask-mobile#8534]
### Describe the bug

When I click `Connect Wallet` button in my website (iPhone, chrome browser), I am redirected to metamask app and connect wallet popup is displayed.
But the logo is no displayed in that popup and I only see the first letter of site origin.
After I checking your codebase, you are getting the favIcon to display the logo in useFavIcon hook.
But seems like this hook is not working properly.

### Expected behavior

The logo should be displayed properly

### Steps to reproduce

1. Go to https://app.cibola.finance on iphone
2. Click Connect Wallet button and redirect to metamask app
3. ConnectWallet popup is displayed but the logo is not displayed. Instead `A` is shown

### Version

v7.15.0 (1245)

### Build type

None

### Device

Any iphone

### Operating system

iOS

### Additional context

Inside app/util/favicon/index.ts file, please check `fetchHtmlSource` method
I think fetch function returns cors error sometimes

**Comment by ZbrancaI** [comment]
Hey @davidli108 ! Thank you for reporting this issue! The team is looking into it!

**Comment by davidli108** [comment]
Hi!
For connect wallet, i used Web3Modal and i resolved this issue after upgrading web3Modal to v4
