### ISSUE TITLE
[Bug]: What's New not displayed on Android after upgrade (no fresh install) & Multiple issues with upcoming migrations `7.16` and `7.17`

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-mobile#8553]
### Describe the bug

**Problem:** 
- the What's New message is not displayed on Android after an upgrade. It is displayed on iOS and also with Android fresh installs
- The What's New message is not displayed in Android nor in iOS for migrations from `7.15` to `7.16` . It is for fresh installs
- The What's New message won't be displayed in Android nor in iOS for migrations from `7.16` to `7.17` . It seems it will for fresh installs

### Expected behavior

The What's New should be displayed

### Screenshots/Recordings

https://github.com/MetaMask/metamask-mobile/assets/54408225/7f43a057-792e-44a6-a618-78860ca335d7

### Steps to reproduce

1. Install 7.15 on Android 
2. Upgrade to 7.16
3. See no What's New is displayed

After checking a previous version, this seems to be also the case from 7.14 to 7.15 for Android 
cc @hesterbruikman I think this explains what you experienced a couple of days ago

### Version

7.15.0 7.16

### Build type

None

### Device

Pixel 6

### Operating system

Android

**Comment by digiwand** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/-Confirmations-Secure-UX-6245e6e2348677001213b8d2/issues/MetaMask/metamask-mobile/8553?planning-poker) with Zenhub @blackdevelopa @jpuri @seaona
