### ISSUE TITLE
Error: Unknown error: Attempt to invoke virtual method 'java.security.PublicKey java.security.cert.Certificate.getPublicKey()' on a null object reference

### ISSUE THREAD

**Issue by Godmahadev** [MetaMask/metamask-mobile#8568]
### What is this about?

![Screenshot_20240210-202530](https://github.com/MetaMask/metamask-mobile/assets/159863723/a3200215-813b-4bab-924e-b31f24f9dddc)

### Scenario

Error: Unknown error: Attempt to invoke virtual method 'java.security.PublicKey java.security.cert.Certificate.getPublicKey()' on a null object reference

### Stakeholder review needed before the work gets merged

- [ ] Engineering (needed in most cases)
- [ ] Design
- [ ] Product
- [ ] QA (automation tests are required to pass before merging PRs but not all changes are covered by automation tests - please review if QA is needed beyond automation tests)
- [x] Security
- [ ] Legal
- [ ] Marketing
- [ ] Management (please specify)
- [ ] Other (please specify)

**Comment by anaamolnar** [comment]
Hello, @Godmahadev. Thanks for reporting! Please reach out to Metamask support, where our colleagues will be able to assist you with this issue. You can find them at this link: https://support.metamask.io/hc/en-us
