### ISSUE TITLE
[Bug]: Network change to Linea from dapp produces error

### ISSUE THREAD

**Issue by plasmacorral** [MetaMask/metamask-mobile#8577]
### Describe the bug

I was attempting to claim the community edition drop from Phosphor during the in an hour series and observed an issue trying to change the network to Linea on an android 14 device.  The work around is to tap the network drop-down and just manually select the network.

### Expected behavior

Given When I am connected to a dapp in a browser outside of MetaMask Mobile
When I attempt to switch RPC from the dapp
Then the active RPC changes in the mobile client

### Screenshots/Recordings

Recording: https://recordit.co/v6GH4rLh4q

<img width="200" alt="Screenshot 2024-02-13 at 2 20 34 PM" src="https://github.com/MetaMask/metamask-mobile/assets/32695229/4f15984b-c50a-455a-97df-76ca36f4c97d">

### Steps to reproduce

1. Use Offline QR generator extension (or similar) in chrome desktop to make a QR of `https://app.phosphor.xyz/5fac8d35-680c-4891-8118-4eda5f6d3763/drops/5f8e8605-1fc6-42cc-8de1-ef10c3d3862e/9133303b-c97f-458f-811b-fc2f0f40c7e7/3bc32b9b-2829-43c5-b396-d8728a52957f`
2. Open android device camera and scan
3. Open link in chrome browser v121.0.6167.144 on mobile
4. Tap `Claim Now`
5. Tap `Connect Wallet`
6. Tap `MetaMask`
7. Tap `Just once` on the Open with MetaMask prompt
8. Unlock MetaMask v7.15.0
9. Tap to `Connect` in connection confirmation
10. Return to browser and tap `Switch Network`
11. Note console error and eth mainnet remains active

### Error messages or log output

```shell
LOG  Sentry Logger [log]: [TouchEvents] Touch event within element: View
 LOG  [MetaMask DEBUG]: WC2Manager::connect wc:78818e9a2ac93f7da05a7015c41d165751258451f7d23f6ebda57ccc9754db60@2/wc?requestId=1707850390123685&sessionTopic=7158cdfdc01820fff66e79f9b270d58aeceee12da04e21e7407de0db9ab59898 origin=deeplink redirectUrl=undefined
 LOG  [MetaMask DEBUG]: WalletConnect2Session::handleRequest chainId=1 method=wallet_addEthereumChain [{"blockExplorerUrls": ["https://lineascan.build"], "chainId": "0xe708", "chainName": "Linea Mainnet", "nativeCurrency": {"decimals": 18, "name": "Linea Ether", "symbol": "ETH"}, "rpcUrls": ["https://linea-mainnet.infura.io/v3/ef50df4b1bc54dab997967df86f10e47"]}]
```

### Version

7.15.0

### Build type

None

### Device

Pixel 5a

### Operating system

Android

### Additional context

Pixel 5a
Android 14
Initially observed on 7.14.0 from the store but then reproduced on MetaMask Mobile v7.15.0-RC-4  ce323b61a4b92001aafc6ecc2f4fb64e7e5e22f1

### Severity

There is a work around, but this is annoying.

**Comment by christopherferreira9** [comment]
Hey hey @plasmacorral !
The mobile app doesn't currently support Chain Switching the way we are used to. If the dapp would allow you to tap "Mint" directly, the wallet would then ask you to switch networks but that's something we have no control over, it should work just fine with the inapp browser though.
Here's a reference for the issue: https://github.com/MetaMask/metamask-mobile/issues/8380
