### ISSUE TITLE
[Bug]: the pressedIn state for the link also overrides the spacing in BottomSheetFooter

### ISSUE THREAD

**Issue by georgewrmarshall** [MetaMask/metamask-mobile#8596]
### Describe the bug

The pressedIn state for the link also overrides the spacing

### Expected behavior

The spacing should remain the same if pressed 

### Screenshots/Recordings

https://github.com/MetaMask/metamask-mobile/assets/8112138/a6a38108-520f-47fe-a29a-d11f72febbe0

### Steps to reproduce

1. Use the BottomSheetFooter with link button
2. Press link button

### Version

develop

### Build type

None

### Device

ios

### Operating system

iOS

### Severity

- Blocker for ramps

**Comment by georgewrmarshall** [comment]
@Pedro-vk please add any additional information if needed

**Comment by wachunei** [comment]
I have a reproducible branch here https://github.com/MetaMask/metamask-mobile/pull/8627, in that branch the BottomSheet has only 1 button and the spacing issue behaves different than the video posted on this issue.
