### ISSUE TITLE
[Bug]: Missing METAMASK_BUILD_TYPE; set to 'main' for a standard release, or 'flask' for a canary flask release. The default value is 'main'.

### ISSUE THREAD

**Issue by cain1980** [MetaMask/metamask-mobile#8622]
### Describe the bug

Missing METAMASK_BUILD_TYPE; set to 'main' for a standard release, or 'flask' for a canary flask release. The default value is 'main'.

### Steps to reproduce

yarn start:ios

### Version

7.13.0

### Build type

None

### Device

mac

### Operating system

iOS

**Comment by Bullcoiner** [comment]
Hi There! Thank you for reporting this, it has been assigned to the appropriate team to be looked at. If possible can you please provide some more information about the issue you are experiencing?

**Comment by gauthierpetetin** [comment]
Default MM build type: main
Default MM environment: local

**Comment by bdtren** [comment]
For a temp workaround, you can put these to the top of `build.sh`, below `readonly REPO_ROOT_DIR="$(dirname "${__DIRNAME__}")"`:

```
METAMASK_BUILD_TYPE="main"
METAMASK_ENVIRONMENT="local"
```
