### ISSUE TITLE
[Bug]: `This netowrk URL doesn't match a known provider for this chain ID` when switching to popular networks

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-mobile#8626]
### Describe the bug

**Problem:** whenever I switch to BNB Smart Chain, or Optimism or other popular networks I see the warning 
- `This netowrk URL doesn't match a known provider for this chain ID` 
- `It looks like this network's display name doesn't match its chain ID`

### Expected behavior

We should not see any of these warnings for our popular networks

### Steps to reproduce

1. Go to Settings // Networks
2. Click Add Network
3. Click Add Optimism -- see warnings
4. Click Add Polygon -- see warning
5. Click Add BNB -- see warnings

### Version

7.17.0

### Build type

None

### Device

Pixel 6

### Operating system

Android

**Comment by Bullcoiner** [comment]
Hi There! Thank you for reporting this, it has been assigned to the appropriate team to be looked at. If possible can you please provide some more information, such as screenshots or a recording of the error messages and how to reproduce them?

**Comment by tommasini** [comment]
@seaona I'm tagging assets, team I believe it's assets team that owns this work

**Comment by sleepytanya** [comment]
The bug is present in RC 7.23.0:
<img width="358" alt="Screenshot 2024-05-16 at 18 40 22" src="https://github.com/MetaMask/metamask-mobile/assets/104780023/b19c39d6-b98a-48bc-91bf-89b26d8d77c3">
