### ISSUE TITLE
[Bug]: PPOM - `No alerts received` disappears after checking Signature details

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-mobile#8633]
### Describe the bug

**Problem:** whenever I trigger a signature and I get the `No alerts received` from PPOM, if I check the signature details and go back, I see that the No alerts received has disappeared 

### Expected behavior

It should not disappear if the user doesn't actively close it

### Screenshots/Recordings

https://github.com/MetaMask/metamask-mobile/assets/54408225/547e9684-8509-4c85-8820-f40c52664966

### Steps to reproduce

1. Enable Blockaid
2. Select mainnet
3. Go to the test dapp
4. Trigger a SIWE signature

### Version

7.16.0

### Build type

None

### Device

Pixel 6

### Operating system

Android

**Comment by jpuri** [comment]
This bug is no longer relevant as `No alerts received` message is removed now.
