### ISSUE TITLE
[Bug]: MetaMask stops when pairing request is rejected from Ledger Nano X

### ISSUE THREAD

**Issue by plasmacorral** [MetaMask/metamask-mobile#8641]
### Describe the bug

Observed in RC 1 testing for 7.17.0 on Pixel 5a with android 14: When initiating add hardware for Ledger if the user declines the pairing request from the Ledger device, MetaMask stops.

### Expected behavior

MetaMask handle user rejection of pairing gracefully, and provide actionable instructions in an error message.

### Screenshots/Recordings

<img width="236" alt="Stopped" src="https://github.com/MetaMask/metamask-mobile/assets/32695229/b523a3dd-ce0e-45cd-883f-74ca8712e829">

Recording: https://recordit.co/Y4JaFbIsEe

### Steps to reproduce

1. From Android settings>connected devices> see all make sure LNX not currently paired
2. Have LNX unlocked and the Ethereum app opened
3. Unlock MMM
4. Tap accounts menu from wallet view
5. Select `add account or hardware wallet`
6. Tap `Add hardware wallet`
7. Tap `Ledger`
8. Grant location permission with `Only this time`
9. Tap `Continue` when LNX is found
10. From LNX select `Cancel pairing`
11. Note app closes
12. On second attempt, note `MetaMask keeps stopping`

### Version

[7.17.0 RC1 build 1266](https://app.bitrise.io/app/be69d4368ee7e86d/pipelines/8e47bc85-2c5b-4f1d-b643-7abb6e878827)

### Build type

None

### Device

Pixel 5a with android 14

### Operating system

Android

### Additional context

iOS device presents no error on first rejection, but then gives a generic error when the second attempt to pair is rejected from the LNX device.

Tested with Ledger Nano X hardware v2.0,  firmware 2.2.3, micro controller 2.30, bootloader 1.16
LNX Ethereum version 1.10.3

**Comment by plasmacorral** [comment]
Related to https://github.com/MetaMask/metamask-mobile/pull/8246

**Comment by angelcheung22** [comment]
This was an Edge case previously deprioritised after the first release, as it requires a new update mechanism from Ledger. 
Reference ticket https://app.zenhub.com/workspaces/cet-metamask-hardware-wallets-6566ee6aedc46007d5a260bb/issues/zh/111

**Comment by angelcheung22** [comment]
Lets add timeout.

**Comment by angelcheung22** [comment]
@vivek-consensys lets discuss why this is moved to blocked?

**Comment by dawnseeker8** [comment]
The app crash was caused by `bluetooth disconnected` error thrown from native code. so `timeout` implementation will not work here.

We need to find a way to catch this `bluetooth disconnected` exception to prevent this app crash happening again.

**Comment by angelcheung22** [comment]
related fix https://github.com/MetaMask/metamask-mobile/pull/8873
