### ISSUE TITLE
[Bug]: Rejecting location permission when pairing Ledger Nano X

### ISSUE THREAD

**Issue by plasmacorral** [MetaMask/metamask-mobile#8643]
### Describe the bug

In the add hardware flow for Ledger on Android, if the user rejects the location permission request, it is simply requested a second time.  When the user rejects a second time, then MMM looks for a Nano with a spinning wheel until MMM closes.  On relaunch of MMM, the user is returned to Connect Ledger with an indefinite spinner.

### Expected behavior

If user rejects a necessary permission, then an error message is gracefully presented with suggested actions for the user. 

This is failing at [Scenario 3.H](https://docs.google.com/document/d/1PJveGQXOVRqq2ncev9UyFWQJJhRiyJbgPTFl-rQ4b54/edit) in that no error message is being presented.

### Screenshots/Recordings
<div style="display: inline-block"> <img width="183" src="https://github.com/MetaMask/metamask-mobile/assets/32695229/6c637e42-4c40-4e63-8e8a-f3f7e48a2374"><img width="190" src="https://github.com/MetaMask/metamask-mobile/assets/32695229/1563ebeb-d88a-4b6e-ba01-e2a59812d1c0"></div>

Sped up recording: https://recordit.co/XKMLZz0BDt
Half speed recording to see the second permission request: https://recordit.co/vqiQb7KQgS

### Steps to reproduce

1. From Android settings>connected devices> see all make sure LNX not currently paired
2. Have LNX unlocked and the Ethereum app opened
3. Unlock MMM
4. Tap accounts menu from wallet view
5. Select `add account or hardware wallet`
6. Tap `Add hardware wallet`
7. Tap `Ledger`
8. When location permission is requested, decline it
9. When location permission is requested again immediately, decline it again
10. Note that app will close
11. Relaunch and observe peristant spinner next to `Looking for device`

### Version

[7.17.0 RC1 build 1266](https://app.bitrise.io/app/be69d4368ee7e86d/pipelines/8e47bc85-2c5b-4f1d-b643-7abb6e878827)

### Build type

None

### Device

Pixel 5a android 14

### Operating system

Android

### Additional context

Location permission not required on iOS

Tested with Ledger Nano X hardware v2.0,  firmware 2.2.3, micro controller 2.30, bootloader 1.16
LNX Ethereum version 1.10.3

**Comment by plasmacorral** [comment]
Related to https://github.com/MetaMask/metamask-mobile/pull/8246

**Comment by plasmacorral** [comment]
An update to add that I produce similar behavior when Bluetooth and Location are both turned on, but MetaMask has permission to location, but with precise location turned off.  When I decline, I am asked a second time and then left with an indefinite spinner and no error message.

Steps to reproduce

1. From Android settings>connected devices> see all make sure LNX not currently paired
2. In Settings>Apps>MetaMask have location permission enabled
3. In that same app level permissions menu, disable precise location
4. Have LNX unlocked and the Ethereum app opened
5. Unlock MMM
6. Tap accounts menu from wallet view
7. Select add account or hardware wallet
8. Tap Add hardware wallet
9. Tap Ledger
10. When location permission is requested, tap `Only this time`
11. When prompted to `Change MetaMask's location access...` select `Keep approximate location`
12. You'll be asked a second time in case you werent sure, answer again `Keep approximate location`
13. Note that you land at `Connect Ledger` with a spinner next to `Looking for device` for an extended period with no errors and no pairing

<div style="display: inline-block"> <img width="190" src="https://github.com/MetaMask/metamask-mobile/assets/32695229/7553d631-31a7-4e8b-bd42-53866aafabac"><img width="190" src="https://github.com/MetaMask/metamask-mobile/assets/32695229/2eac7ae8-9196-4d92-afce-30fe236cc20c"></div>
 Recording: https://recordit.co/V05k73c541

**Comment by angelcheung22** [comment]
Only when rejecting twice, the setting in Andriod is set to Denied.

**Comment by angelcheung22** [comment]
Andriod 11 requires location permission, Andriod 12 or above requires only nearby permission

**Comment by angelcheung22** [comment]
needs to downgrade andriod 11 to debug further

**Comment by angelcheung22** [comment]
Leo tested on andriod 9 with a patch, now the situation improves, the user is redirected to retry at the 2nd time of deny. Now pending for the patch to merge until we can ask Mike to retry this ticket.

**Comment by angelcheung22** [comment]
pending from https://github.com/MetaMask/metamask-mobile/pull/8887

**Comment by angelcheung22** [comment]
Fix for this https://github.com/MetaMask/metamask-mobile/pull/8745

**Comment by vivek-consensys** [comment]
Tested on Samsung S21 using Android 14. 
Bitrise build:- https://app.bitrise.io/build/ce998116-a194-487f-a46d-315a8386cecb?tab=artifacts

[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMXdxQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--fe572b992817ccdecc86d6b683f9d0f633e128bb/Screen_Recording_20240402_152101_MetaMask-QA.mp4)
