### ISSUE TITLE
[Bug] Whats new modal redirecting to Experimental Security screen

### ISSUE THREAD

**Issue by SamuelSalas** [MetaMask/metamask-mobile#8659]
### What is this about?

When installing or upgrading the app, the what is new modal will show information regarding the security alerts. If the user taps the got it button, the app will relocate the user to the Experimental Security screen. This behavior does not seems correct. If the user taps the x icon located on the top right, the app will close the modal and stay on the wallet screen.

[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd1Y4QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--138b263c89bb9d3a9d69bb075e464637641e95a8/upgrade-7-14--7-17.mp4)

### Acceptance Criteria

- 

### Stakeholder review needed before the work gets merged

- [ ] Engineering (needed in most cases)
- [ ] Design
- [ ] Product
- [ ] QA (automation tests are required to pass before merging PRs but not all changes are covered by automation tests - please review if QA is needed beyond automation tests)
- [ ] Security
- [ ] Legal
- [ ] Marketing
- [ ] Management (please specify)
- [ ] Other (please specify)

**Comment by seaona** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/-Confirmations-Secure-UX-6245e6e2348677001213b8d2/issues/MetaMask/metamask-mobile/8659?planning-poker) with Zenhub @blackdevelopa @digiwand @jpuri @segun

**Comment by bschorchit** [comment]
Closing as no longer relevant

**Comment by chrisleewilcox** [comment]
Reopening.  This is still a problem.
