### ISSUE TITLE
[Bug]: ERC20 swap attempt does not succeed on Ledger account when token spending approval is required

### ISSUE THREAD

**Issue by plasmacorral** [MetaMask/metamask-mobile#8667]
### Describe the bug

Attempted to swap an ERC20 and the approval tx was presented to the Ledger device, and was approved on device and then broadcast to mainnet as expected.  However, the actual swap transaction was never presented to the Ledger device.  This was observed both with the default Ethereum app v1.10.3 setting of blind signing off, as well as when blind signing was enabled.

- Initial attempt to swap Dai to Shib [approval](https://etherscan.io/tx/0x0675d7832d19c5c831cff9ebe984b60d1ce9a3b1d6ec2ab83d7d1c771ac3beaf) but the swap was never presented to Ledger.
- Then I came back and attempted to swap Dai for Shib a second time relying on that earlier approval, and was [successful](https://etherscan.io/tx/0xd30eda7d08053c83834360bd37a177b447496273a7e480da8148c71ba797a4ce) after enabling blind signing on the Ledger Ethereum app. 
- Then I reproduced this dangling  [approval](https://etherscan.io/tx/0xd27d8225f4fd77850e0d3adc1916aa67910caafbaa0ad96da2a57713c867cef9) without the swap when I attempted to swap GRT to USDC.

### Expected behavior

User attempting an ERC20 swap should have two approvals on the Ledger device.  The first for the spending approval and the second for the actual swap.

Actual results: Approval is presented for signing, but swap itself is lost and never presented on Ledger

### Screenshots/Recordings

Recording: https://recordit.co/Vg7MLtediW

### Steps to reproduce

1. Setup MMM with an existing SRP
2. Add Ledger address to MMM
3. [check](https://etherscan.io/tokenapprovalchecker) your address and make sure you do not have any preexisting token spending approvals for the MM swaps router
4. Use etherscan to revoke any prior approvals for the token you are swapping from, if needed
5. Attempt mainnet swap of an ERC20 that requires a token spending approval
6. Note that approval tx is sent to Ledger, but the swap itself never appears at the Ledger device or in the MMM activity for the token being swapped out

### Version

[7.17.0 RC1 build 1266](https://app.bitrise.io/app/be69d4368ee7e86d/pipelines/8e47bc85-2c5b-4f1d-b643-7abb6e878827)

### Build type

None

### Device

Iphone Xs running iOS 17.3.1

### Operating system

iOS

### Additional context

This occurs regardless of whether blind signing is enabled or disabled in the Ledger Ethereum app.

Tested with Ledger Nano X hardware v2.0,  firmware 2.2.3, micro controller 2.30, bootloader 1.16
LNX Ethereum version 1.10.3

**Comment by plasmacorral** [comment]
related https://github.com/MetaMask/metamask-mobile/pull/8246

**Comment by angelcheung22** [comment]
ios specific issue

**Comment by angelcheung22** [comment]
Waiting for Gustavo's response on the expected flow to determine if valid bug

**Comment by plasmacorral** [comment]
Also observed on Polygon that approval was sent to Ledger, but not the actual swap.  When testing with Pixel 5a Android 14, with LNX running fw 2.2.3

**Comment by plasmacorral** [comment]
Observed today with a swap on Polygon, using Android 14 Pixel 5a with LNX fw 2.2.3 and eth app 1.10.3.  Approval is sent to Ledger device, but the actual swap does not appear. 

https://www.loom.com/share/131276669965400585bbd41f99861705?sid=20ff5692-d211-421d-a5ba-f8858cff9d79

**Comment by angelcheung22** [comment]
waiting for funds to retry the sceanrio.

**Comment by Akaryatrh** [comment]
Quick update: a temporary fix has been proposed (please see link above), but:
- we may try to integrate [the recommended modal](https://github.com/MetaMask/metamask-mobile/tree/main/app/component-library/components/BottomSheets/BottomSheet) component to see if it helps resolving the issue
- IMO we should not have a succession of modal displayed but just one modal that will sit on screen until both transactions are confirmed (not sure if it's feasible though)
