### ISSUE TITLE
[Bug]: PPOM - Migrating to `v7.17.0` does not enable Blockaid by default

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-mobile#8669]
### Describe the bug

**Problem:** Blockaid is not enabled by default if I perform a migration from a previous version to `v7.17.0`. 

### Expected behavior

Migrating from a previous version to 7.17.0 should enable Blockaid by default in the same way it's done with 7.17.0 fresh installs

### Screenshots/Recordings

https://github.com/MetaMask/metamask-mobile/assets/54408225/c36853ea-2bdf-4296-b1f8-8bcecc4b916b

### Steps to reproduce

1. Install v7.16
2. Update to v7.17
3. Check settings --> see Blockaid is disabled

### Version

7.17.0

### Build type

None

### Device

Pixel 6

### Operating system

iOS, Android

**Comment by blackdevelopa** [comment]
Setting this ticket to a 2 because the code was pretty straightforward once I was able to get some help from the mobile platform team.
