### ISSUE TITLE
[Bug]: Transaction on zkSync-Era using Paymaster does not return transaction receipt

### ISSUE THREAD

**Issue by ZkSwapFinance** [MetaMask/metamask-mobile#8671]
### Describe the bug

I'm attempting to perform a swap on the zkSync-Era chain using a Paymaster (zkSync Era). The swap itself is successful; however, the finished transaction receipt is not returned, and the spinner keeps spinning. If I remove the Paymaster from the transaction, the transaction completes normally.

The entire process works without any issues using Trust Wallet, with or without the Paymaster.

### Expected behavior

The transaction receipt/notification should appear once the transaction is finished.

### Screenshots/Recordings

![image](https://github.com/MetaMask/metamask-mobile/assets/126151208/40431bd3-33b6-41d8-878d-f7cd9055e6a5)
![image](https://github.com/MetaMask/metamask-mobile/assets/126151208/69841b76-37f2-4964-82fa-6a4a51ba24c6)

### Steps to reproduce

**Case 1:**
1. Go to https://zkswap.finance and select the Swap section (on mobile).
2. Enable "Use ZF for gas (Paymaster)."
3. Perform any swap.

**Case 2:**
1. Visit https://syncswap.xyz/swap.
2. In the upper right corner, select any fee token (except ETH).
3. Perform any swap.

### Version

7.15.0 (1245)

### Build type

None

### Device

iphone 13

### Operating system

iOS

### Additional context

This bug actually happens on MetaMask on both iPhone and Android. It works when using Trust Wallet

### Severity

- Critical level: Normal
- Is this visible to all users: Yes
- Is this tech debt: Yes

**Comment by Bullcoiner** [comment]
Hi There, Thank you for reporting this to us. It has been reported to a team and will be looked at.
