### ISSUE TITLE
[Bug]: Sign Permit with Test dapp returns v:0

### ISSUE THREAD

**Issue by plasmacorral** [MetaMask/metamask-mobile#8689]
### Describe the bug

When testing Sign permit with a Ledger account on the [test dapp ](https://metamask.github.io/test-dapp/) I am observing `v:0`.

### Expected behavior

Expecting v=27, 28, or >=37 according to EIP [155](https://eips.ethereum.org/EIPS/eip-155). 

Similar issue addressed for Extension previously [here](https://github.com/MetaMask/eth-ledger-bridge-keyring/pull/152).

### Screenshots/Recordings

![Screenshot 2024-02-22 at 5 32 59 PM](https://github.com/MetaMask/metamask-mobile/assets/32695229/0788691a-3114-43cf-bf36-4a14399efa71)

### Steps to reproduce

1. Pair Ledger address with MMM in the add hardware flow
2. Connect to the [test dapp ](https://metamask.github.io/test-dapp/)
3. Scroll down to `Sign Permit` and tap `Sign`
4. Approve signature on Ledger
5. Note v:0

### Version

[7.17.0 RC1 build 1266](https://app.bitrise.io/app/be69d4368ee7e86d/pipelines/8e47bc85-2c5b-4f1d-b643-7abb6e878827)

### Build type

None

### Device

iPhone Xs with iOS 17.3.1

### Operating system

iOS

### Additional context

Tested with Ledger Nano X hardware v2.0,  firmware 2.2.3, micro controller 2.30, bootloader 1.16
LNX Ethereum version 1.10.3

EDIT: Can also reproduce on Pixel 5a with Android 14 using RC1 build 1266

**Comment by plasmacorral** [comment]
related https://github.com/MetaMask/metamask-mobile/pull/8246

**Comment by Akaryatrh** [comment]
@plasmacorral I can not reproduce on OnePlus 11 - Android 14, is it a iOS only issue?

Output from latest bitrise QA build:
![Screenshot_2024-02-28-14-12-49-21_f688294473d4180e24579faf1f9e8d4b](https://github.com/MetaMask/metamask-mobile/assets/574787/4f0f42da-e6f5-43c8-9d6a-78774b2279b8)

Output from local setup with `main` branch:
![Screenshot_2024-02-28-14-10-54-44_3ce871bb60cb313382b75690e63e41d0](https://github.com/MetaMask/metamask-mobile/assets/574787/2703d744-1b76-48c0-b0a0-60fa8878c4f8)

**Comment by plasmacorral** [comment]
Interesting, I do not think this is an IOS specific issue.  I can also reproduce with Pixel 5a on android 14, using RC build 1266 and Ledger Nano X firmware 2.2.3.  Can you please confirm the build and firmware combination that is able to produce 27 or 28 for the screenshots above?

**Comment by Akaryatrh** [comment]
I now reprodoce the issue, so i'm not sure what happens the last time, maybe i tested with the wrong account. I'm currently investigating this :)

**Comment by vivek-consensys** [comment]
Tested using main branch Bitrise build after the PR fix was merged. 

PR: https://github.com/MetaMask/metamask-mobile/pull/8932
Bitrise build: https://app.bitrise.io/app/be69d4368ee7e86d/pipelines/eb3218f5-d100-42c8-bc47-7745b24b5aab

Screen recording on iPhone 13 using iOS 17.3.1:


https://github.com/MetaMask/metamask-mobile/assets/106310394/b67a8ddc-4141-4749-8391-0bc3d09d47f7
