### ISSUE TITLE
[Enhancement]: Long press and hold to remove an account with hardware wallets (Ledger and QR)

### ISSUE THREAD

**Issue by plasmacorral** [MetaMask/metamask-mobile#8690]
### Describe the bug

This worked in the past but it seems that in RC 7.17.0 on iOS 17.3.1 iPhone Xs, I can no longer long press and hold to remove either a Ledger account or a QR account.  

This also impacts QR addresses in production 7.16.0 build 1265.

Notably though, and the reason I am filing this issue is that this functionality is still working with accounts imported by private key.  

### Expected behavior

If I long press and hold an account from the drop-down list, I am presented the option to remove the account.  This is expected on Imported and Hardware wallets, but not on an HD account from the SRP.

Given I have the accounts drop-down open
When I long press on an imported/hardware account
Then I am presented the option to remove the account
When I consent to removal
Then the account is removed from the list

### Screenshots/Recordings

<img src="https://github.com/MetaMask/metamask-mobile/assets/32695229/feb40c13-f388-4ff5-aa92-fa419f276daf" width="280"/>

https://github.com/MetaMask/metamask-mobile/assets/32695229/8ecc0238-3e34-4dd2-83de-375ed1ded758

### Steps to reproduce

1. Setup a wallet
2. Import an account by private key
3. Bind with a QR hardware wallet
4. Pair with a Ledger device
5. Open the accounts drop-down
6. Long press and hold each account type
7. Note that only Imported accounts present the confirmation to remove

### Version

[7.17.0 RC1 build 1266](https://app.bitrise.io/app/be69d4368ee7e86d/pipelines/8e47bc85-2c5b-4f1d-b643-7abb6e878827)

### Build type

None

### Device

iPhone Xs iOS 17.3.1

### Operating system

iOS

### Additional context

This worked in the past, but seems to no longer be supported on hardware wallets within this RC, and is confirmed to impact Keystone in production v7.16.0 build 1265 (Ledger is not yet available in 7.16.0)

Tested with Ledger Nano X hardware v2.0,  firmware 2.2.3, micro controller 2.30, bootloader 1.16
LNX Ethereum version 1.10.3

**Comment by dawnseeker8** [comment]
Metamask mobile currently only have `forget Ledger` and `forget QR device`.  and there is not way to delete one accouints associated with that hardware wallet. `forget ledger` and `forget QR device` will remove all accounts associated with that hardware wallet. 

Is `forget ledger` or `forget QR device` what we want in `long press` story? @AlexJupiter

**Comment by angelcheung22** [comment]
discussed with Alex, pull this back to backlog for enhancement later after multiple accounts

**Comment by angelcheung22** [comment]
removed , follow the new spec https://docs.google.com/document/d/1OEXeaq2Bu5PwfajefeZdR88I6CPZGdNCVKtOzCMCJ4I/edit#heading=h.bj944qneo5ka
