### ISSUE TITLE
[Bug]: QR address not showing in account list when app is relaunched

### ISSUE THREAD

**Issue by plasmacorral** [MetaMask/metamask-mobile#8693]
### Describe the bug

Observed this when testing RC 7.17.0 on iOS 17.3.1 iPhone Xs with a QR wallet, and confirmed this to be present in production v7.16.0 build 1265.

If I kill the mobile app after adding a QR address, on the next launch the QR address is not shown in the accounts drop-down list.  

If I go thru the add hardware flow at this point, the account is reflected as present in the QR address selection list but is absent on the accounts drop-down.  If I select another address at this time, then both the missing address and the newly selected address will show up.

If instead of going through the add hardware flow I simply kill the app and relaunch it a second time, the QR address once again appears in the accounts drop-down list.

### Expected behavior

Once added, a QR address persists in the account list until removed or QR wallet is forgotten.

Given I have completed the add hardware flow for a QR address
When I kill the app
And I relaunch
Then the QR address remains present in the account drop-down list

### Screenshots/Recordings

https://github.com/MetaMask/metamask-mobile/assets/32695229/eb32945c-d9a5-464c-af3e-df997160c0c3

### Steps to reproduce

1. Import an SRP and complete setup using FaceID authentication
2. Import an address by private key
3. Bind with QR address
4. Verify both imported and QR addresses appear in the accounts drop down
5. swipe up to access the app tray
6. swipe up to kill the MMM app
7. Relaunch MMM
8. Open accounts drop down and note that QR address is missing
9. Engage add hardware flow and note that account is still selected
10. Return to wallet view
11. Open accounts drop down and note account is still not shown
12. swipe up to access the app tray
13. swipe MMM away to kill the app
14. Relaunch MMM
15. Open accounts drop down and note that QR address is now showing

### Version

7.16.0

### Build type

None

### Device

iPhone Xs iOS 17.3.1

### Operating system

iOS

### Additional context

Account is consistently missing on first launch after being added, and reappears at second launch and beyond.

### Severity

This is unsettling and undermines user confidence.

**Comment by dawnseeker8** [comment]
After deep investigation and testing, confirm this issue have same cause as #8694 

After testing the fix in this [PR](https://github.com/MetaMask/metamask-mobile/pull/8741), confirm that this issue not longer exists with that PR fix.  so will link this issue to that PR now.

**Comment by vivek-consensys** [comment]
Tested locally and working as expected:- 

[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNkdlQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--49a8b9df96f603250a0d9833dd9d4f48b66c91e3/Screen_Recording_20240227_114302_MetaMask.mp4)

**Comment by vivek-consensys** [comment]
Tested bitrise build using iPhone 13 on iOS v17.3.1:-
https://app.bitrise.io/build/c1f688f7-3e14-4d01-8db4-21f918894167?tab=artifacts


[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM09xQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--fc8c59a8983b9350253819cbcf2bfd5efbe7512e/RPReplay_Final1709558628.MP4)

**Comment by dawnseeker8** [comment]
https://github.com/MetaMask/metamask-mobile/pull/8741 has been merged, and @vivek-consensys have confirmed this issue has been fixed with above PR merged.
