### ISSUE TITLE
[Bug]:  QR address disappears after a password change

### ISSUE THREAD

**Issue by plasmacorral** [MetaMask/metamask-mobile#8694]
### Describe the bug

Observed this when testing RC 7.17.0 on iOS 17.3.1 iPhone Xs with a QR wallet, and confirmed this to be present in production v7.16.0 build 1265.

When I change the password, the QR address disappears from the accounts drop-down list.

If I attempt to initiate the add hardware flow a second time, the previously added account is not shown as selected.  If I select it and follow through with adding it again, it then appears in the accounts drop-down list twice.

Otherwise, the account appears to have otherwise disappeared.

### Expected behavior

All accounts are persisted across a password change

Given I have a QR address present in the account list
When I attempt a password change
Then all accounts persist in the accounts list after the password change is completed succesfully

### Screenshots/Recordings

https://github.com/MetaMask/metamask-mobile/assets/32695229/62abf78f-6a60-451f-8990-ade1cba84c0c

### Steps to reproduce

1. Import SRP using FaceID authentication
2. From wallet view add hardware
3. Select QR hardware
4. Scan QR
5. Confirm account added
6. Go to Settings>Security and Privacy
7. Change password
8. On successfull password change, close out of settings and return to wallet view
9. Open accounts drop-down
10. Note that recently added QR address is absent
11. Initiate add hardware flow
12. Note that addresses list is already present without needing to rescan
13. Note that previously selected address appears to not be selected
14. Select the same address a second time and confirm
15. Return to accounts drop-down list and note that the missing account now appears 2x

### Version

7.16.0

### Build type

None

### Device

iPhone Xs iOS 17.3.1

### Operating system

iOS

**Comment by vivek-consensys** [comment]
Tested locally and working as expected on Samsung Android 13:- 

[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM0NSQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--673359e7a784ab509201e42c69d64a961c155481/Screen_Recording_20240227_114302_MetaMask.mp4)
