### ISSUE TITLE
[Bug]: User input for custom gas is ignored

### ISSUE THREAD

**Issue by plasmacorral** [MetaMask/metamask-mobile#8708]
### Describe the bug

I noticed when trying to test speed up and cancel that any input I make and save on the custom gas screen is simply ignored in what is broadcast to network on Sepolia as well as on mainnet in 7.16.0

Initially observed with Ledger in RC 7.17.0, also observed on QR and HD accounts.

Whether I edit custom gas amounts, or choose the preselected `Aggressive` option, my input is ignored and the original market amount is what is submitted to the network on Sepolia as well as Mainnet.

I am aware of a similar issue being actively worked for Linea Goerli [here](https://github.com/MetaMask/metamask-mobile/pull/8581)

### Expected behavior

Given that I am conducting a tx
When I tap gas to edit
And I save custom gas values 
Then the custom amount I save is what is sent to network

### Screenshots/Recordings

Custom input:

https://github.com/MetaMask/metamask-mobile/assets/32695229/b320a2c0-8745-4772-ba90-e992778a9dd2

<div style="display: inline-block"> <img width="154" src="https://github.com/MetaMask/metamask-mobile/assets/32695229/c4f5c34e-3175-4e6d-aa02-5b414ebfdf97""><img width="155" src="https://github.com/MetaMask/metamask-mobile/assets/32695229/7c99cbb0-4545-4c6d-ab0e-de2f8a299496"><img width="147" src="https://github.com/MetaMask/metamask-mobile/assets/32695229/75409a93-1627-4179-81cc-7eb9ed118b5f"></div>

https://sepolia.etherscan.io/tx/0xcd6c65d069baa8748899f5804258fac1fb7c5ed37c6f4ad5d1b8fb5fa31a8a54

Using aggressive:

https://github.com/MetaMask/metamask-mobile/assets/32695229/e4e52424-eff3-4293-9b26-8fa1f54a4eb2

<div style="display: inline-block"> <img width="154" src="https://github.com/MetaMask/metamask-mobile/assets/32695229/a0c6a037-fe7c-4415-852e-7b1de63e918c"><img width="154" src="https://github.com/MetaMask/metamask-mobile/assets/32695229/05e33246-431c-45c5-8ba6-bbdd6aa2567f"><img width="154" src="https://github.com/MetaMask/metamask-mobile/assets/32695229/0fb50a7e-4c81-49f1-bcd9-339176ece695"></div>

https://sepolia.etherscan.io/tx/0x9ea35755188cb301d94881eb070fb9135a02c1cc008e3402a8b1a38ae11998e9

Mainnet:
I failed to capture a recording, but I submitted the following tx with custom input of 2 wei max priority fee and 1 wei max fee, and it appears in etherscan at the original suggested market rates: 
https://etherscan.io/tx/0x7cfce9e6413b0619013b3de5fd5a040bd73e6353c7b81db58fed0573a43b7b23

### Steps to reproduce

Custom input:
1. Have a wallet setup
2. Be on Sepolia and have testnet assets (preferably, but can also observe on mainnet)
3. Start a send tx 
4. Select a destination address
5. Set an amount
6. On the confirmation screen tap the blue link on the estimated gas fee
7. On edit priority, tap `Advanced options`
8. For max priority enter any amount less than what was populated but more than 0.000000002 (2 wei)
9. For max fee enter any amount less than what was populated but more than 0.000000001 (1 wei)
10. Tap `Save`
11. Tap to confirm
12. Once returned to wallet view tap on the asset under tokens
13. scroll to the pending tx and tap on it
14. In the tx details, tap to `View on Etherscan`
15. Once confirmed, note that gas values do not match user input'

Aggressive:
1. Have a wallet setup
2. Be on Sepolia and have testnet assets
3. Start a send tx 
4. Select a destination address
5. Set an amount
6. On the confirmation screen tap the blue link on the estimated gas fee
7. On edit priority select `Aggressive`
8. Save
9. Send
10. Note that TX fee is less than the estimated gas fee at market rates, and is significantly lower than the estimated gas for the Aggressive option 

### Version

7.16.0

### Build type

None

### Device

iPhone Xs ios 17.3.1

### Operating system

iOS

### Additional context

This was initially discoverd in 7.17.0 RC testing, but can be observed in production 7.16.0. Given the undermining of trust by failing to honor user input I have marked this as a release blocker for 7.17.0, but feel free to adjust that as necy.

Notably, this is making it incredibly challenging if not impossible to test speed up/cancel transactions for the Ledger integration which is included in 7.17.0 RC.

### Severity

Not many people may use this feature but for those that try, the severity of this defect is high.

**Comment by matthewwalsh0** [comment]
Concerning the PR referenced above: https://github.com/MetaMask/metamask-mobile/pull/8581

This was originally to introduce alternate gas fee estimation on Linea networks rather than resolving any pre-existing bug.

Though I can confirm we've also noticed this error in the send flow so that PR now also includes a general fix to ensure customised gas fee values are respected on submit.

**Comment by matthewwalsh0** [comment]
Fixed in #8581.
