### ISSUE TITLE
[Bug]: When editing custom gas amounts the keyboard is minimized when gas estimates refresh

### ISSUE THREAD

**Issue by plasmacorral** [MetaMask/metamask-mobile#8710]
### Describe the bug

This became apparent when trying to understand the issue reported in https://github.com/MetaMask/metamask-mobile/issues/8708

This was observed in 7.17.0 RC and confirmed to exist in 7.16.0 when testing with iPhone Xs iOS 17.3.1.

While I am trying to input custom values for gas, when quotes refresh the keyboard is minimized.  This requires me to click into the input field a second time, and hope to complete the input value before the next quote refresh.

### Expected behavior

Given I am editing custom gas amounts
When quotes refresh
Then my progress inputting a custom amount is not interupted or otherwise interfered with

### Screenshots/Recordings

See ~26s for what this looks like:

https://github.com/MetaMask/metamask-mobile/assets/32695229/433ba4f9-f825-43b7-955c-e2458a073295

### Steps to reproduce

1. Have a wallet setup
2. Be on Sepolia and have testnet assets (preferably, but can also observe on mainnet)
3. Start a send tx
4. Select a destination address
5. Set an amount
6. On the confirmation screen tap the blue link on the estimated gas fee
7. On edit priority, tap Advanced options
8. For max priority enter any amount less than what was populated but more than 0.000000002 (2 wei) dont rush tho
9. For max fee enter any amount less than what was populated but more than 0.000000001 (1 wei)
10. Before you are able to save, if the quotes refresh while the keyboard is open and you are typing it will be closed.
11. User has to tap into the field a second time and wait for the keyboard to come up to continue

### Version

[7.17.0 RC1 build 1266](https://app.bitrise.io/app/be69d4368ee7e86d/pipelines/8e47bc85-2c5b-4f1d-b643-7abb6e878827)

### Build type

None

### Device

iPhone Xs iOS 17.3.1

### Operating system

iOS

### Severity

User can work around this, but its not easy to use and does not reinforce confidence in performance, and thus undermines trust and feelings of safety.  Did I mention its frustrating?

**Comment by cryptotavares** [comment]
Assigning it to Confirmations UX team as this feels like a pure UX issue

**Comment by blackdevelopa** [comment]
I am unable to reproduce this issue as described. After the quotes are refreshed, the input field resumes focus and I can continue editing the values. However, they can be some improvement that can be done from looking at the extension UX.


https://github.com/MetaMask/metamask-mobile/assets/29962968/dbbbe838-46b4-48f9-8bc1-23a276557989


https://github.com/MetaMask/metamask-mobile/assets/29962968/13ad02ba-a673-4ac1-87ad-bc2af75a0bbe

**Comment by blackdevelopa** [comment]
I will be closing this issue as I am unable to reproduce it as described. I will also be adding `needs design` as a future fix will require design feedback.
