### ISSUE TITLE
[Enhancement]: Unable to pair Ledger if the user has not first generated an Ethereum address in Ledger Live

### ISSUE THREAD

**Issue by plasmacorral** [MetaMask/metamask-mobile#8715]
### Describe the bug

On any fresh install of the Ethereum app on Ledger, if the user has not yet generated an Ethereum account they are unable to pair with MMM.  User can arrive here after creating a new seed on Ledger and installing Ethereum app, restoring an SRP on Ledger and installing the Ethereum app, or uninstalling and reinstalling the Ethereum app.  There is no error message and instead, they face a spinner on the looking for device page.

This step doesn't seem to be mentioned within on-device instructions for pairing, and may be helpful to include in the `Connect Ledger` instructions.

### Expected behavior

Given I am a new user, or have setup a new SRP on a freshly reset Ledger Nano X
When I install the Ethereum app in Ledger Live
And I do NOT add an Ethereum address
Then I do not have an address to add to MMM
When I attempt to pair with MMM in this condition
Then I get an actionable error message to instruct me to first add an account in Ledger Live

### Screenshots/Recordings

Video is too large to attach

Instead, here is a screenshot of Ledger Live adding a new account for the Ethereum app v1.10.3
![Screenshot 2024-02-23 at 8 39 07 PM](https://github.com/MetaMask/metamask-mobile/assets/32695229/75e6da26-63bb-4575-95e1-5dc3c06bed64)

### Steps to reproduce

1. Go to settings>Bluetooth on the mobile device and forget the LNX device
2. Use Settings on the Ledger device to reset, or possibly have a new device out of box
3. Complete new setup on device and generate an SRP without connecting to Ledger Live
4. Once SRP backup is confirmed, attempt to pair with MetaMask but do not yet install the Ethereum app
5. Note that spinner continues spinning while looking for device and no error is generated
6. Read the instructions and then launch Ledger Live to install the Ethereum app
7. Consent to connect to Ledger Live from the hardware
8. Install the Ethereum app (1.10.3)
9. Retry pairing from mobile device
10. Again note spinner on CTA and no error generated
11. Finally return to Ledger Live and go to My Device> Apps Installed and see the `Add Account` Option
12. Hit `Add account`
13. Confirm on hardware
14. Tap`Retry` on mobile device `Connect Ledger` page
15. Note that this will continue to fail
16. Use settings on Ledger to power off device
17. Power back on and unlock
18. Open Ethereum app 
19. Now retry and successfully pair

### Version

[7.17.0 RC1 build 1266](https://app.bitrise.io/app/be69d4368ee7e86d/pipelines/8e47bc85-2c5b-4f1d-b643-7abb6e878827)

### Build type

None

### Device

iPhone Xs iOS 17.3.1

### Operating system

iOS

### Additional context

While this may be an edge case, it may pose a significant challenge for anyone that doesnt have the context and experience with a Ledger device to understand that after setting up a new SRP that they still need to approve adding an account with the Ledger Ethereum app that can then be paired with MetaMask.

This impacts both a freshly generated SRP on Ledger, SRP restored from a backup, and anyone that removes the Ledger Ethereum app and reinstalls it.

Tested with Ledger Nano X hardware v2.0,  firmware 2.2.3, micro controller 2.30, bootloader 1.16
LNX Ethereum version 1.10.3

**Comment by coreyjanssen** [comment]
How about this?

**Heads up!**
Before continuing, select "Add Account" in the Ledger Ethereum app.
