### ISSUE TITLE
[Bug]: MetaMask closes when attempting to pair with a Ledger that is locked OR with the screensaver showing

### ISSUE THREAD

**Issue by plasmacorral** [MetaMask/metamask-mobile#8716]
### Describe the bug

Observed in RC 7.17.0 with Pixel 5a Android 14 in build 1266.  If I attempt to add hardware with the Ledger screensaver showing (or with no screensaver at the Enter PIN screen=device locked) then MetaMask will close.  After the first failure, on retry the Ledger device drop down shows that a device with no name is selected.  After the second attempt, I produce the `MetaMask keeps stopping` system message.

### Expected behavior

Given that the Ledger device is locked regardless of whether its the PIN screen or screensaver
When I attempt to add hardware
And pairing cannot be completed
Then an actionable error message is presented to the user
And the app does not stop

### Screenshots/Recordings

<div style="display: inline-block"> <img width="190" alt="SecondAttemptToAddHardwareWhileScreensaverRuns" src="https://github.com/MetaMask/metamask-mobile/assets/32695229/624a4d9b-a6c3-4df4-91e3-c6a9297a6c91"><img width="190" alt="AppCloses" src="https://github.com/MetaMask/metamask-mobile/assets/32695229/7bacd0fe-c6c9-4e50-a347-8d42922e9224"></div>

https://recordit.co/JJ4QmYX0qC

### Steps to reproduce

1. Have Ledger device setup, with Ethereum app installed,  address added, but screensaver showing (you can adjust this to 1 minute in Ledger settings) or just locked at the PIN entry screen
2. Go to Android Settings>Connected devices and make sure Ledger is not currently paired.  If it is, forget the device
3. Check Settings>Location and make sure location is enabled
4. Unlock MetaMask
5. Initiate Add hardware flow
6. Approve Location permission request
7. Approve nearby device permission request
8. On the Connect Ledger page, tap `Continue` while Ledger remains locked
9. When pairing request is presented tap `Pair & connect`
10. Note that MetaMask closes
11. repeat steps 4-9 but note that this time around the drop down box that usually has the Ledger device name is blank and that system message is presented about MetaMask keeps stopping

### Version

[7.17.0 RC1 build 1266](https://app.bitrise.io/app/be69d4368ee7e86d/pipelines/8e47bc85-2c5b-4f1d-b643-7abb6e878827)

### Build type

None

### Device

Pixel 5a Android 14

### Operating system

Android

**Comment by vivek-consensys** [comment]
I am unable to replicate this issue, MM does not close when Ledger is locked. MM throws an error to unlock the Ledger device when locked and trying to connect: 
<img width="369" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBektMQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f9a28c61dda9b139d2a1b5c36fdb5a7c427cdb14/image.png" alt="image.png" />

**Comment by angelcheung22** [comment]
@plasmacorral we re unable to reproduce this issue.

**Comment by angelcheung22** [comment]
Leo to retest on Andriod 14, potentially version specific issue only

**Comment by angelcheung22** [comment]
Error coming from native level, cannot be really catch from our side, may or may not be fixed by the ledger firmware issue.
