### ISSUE TITLE
[Bug]: Transaction attempt with Ethereum app not OPEN or not Installed causes MetaMask to close

### ISSUE THREAD

**Issue by plasmacorral** [MetaMask/metamask-mobile#8717]
### Describe the bug

Observed in RC 7.17.0 with Pixel 5a Android 14 in build 1266.  If I have Ledger Ethereum app installed but not open and attempt a transaction, then I am prompted to Open the Ethereum app.  However, once I open the Ethereum app, MetaMask closes.  On retry it closes again and presents the `MetaMask keeps closing` system notification.

This was reported initially with the Ethereum app not open, but when it is not installed MetaMask also closes.

### Expected behavior

Given I have Ledger device paired and unlocked
And the Ethereum app is NOT opened (or not Installed)
When I attempt to conduct an EIP1559 send with the [test dapp](https://metamask.github.io/test-dapp/)
Then I am prompted to open/install the Ethereum app
When I open/install the Ethereum app
Then I can see the transaction on Ledger
And I can approve
When I approve the TX on Ledger
Then the TX is broadcast to the network
And MetaMask does not close

### Screenshots/Recordings

![Screenshot 2024-02-24 at 12 21 54 AM](https://github.com/MetaMask/metamask-mobile/assets/32695229/885164d2-0b73-4094-a9a3-59ca10f626ef)

Recording of Ethereum app not open: https://recordit.co/vMhE97NwyT
Recording of Ethereum app not installed: https://recordit.co/1iF0hFqUsG

### Steps to reproduce

1. Have Ledger and MetaMask paired
2. Ledger device is unlocked, with Ethereum app installed and account created, but NOT open
3. Connect to the [test dapp](https://metamask.github.io/test-dapp/)
4. Scroll down to `Send Eth` and tap `Send EIP 1559 transaction`
5. Confirm transaction
6. Note if you have conducted this test already you may be asked again for location permissions that were previously granted
7. Error message encouraging to open the Ethereum app
8. Tap both buttons on Ledger to open the Ethereum app
9. Message switches on MetaMask to approve tx on ledger, but before Tx is sent to Ledger MetaMask closes
10. Open the app again
11. Run through steps 4-8 again and note that MetaMask stops and android presents the message about it stopping

### Version

[7.17.0 RC1 build 1266](https://app.bitrise.io/app/be69d4368ee7e86d/pipelines/8e47bc85-2c5b-4f1d-b643-7abb6e878827)

### Build type

None

### Device

Pixel 5a Android 14

### Operating system

Android

**Comment by angelcheung22** [comment]
Related to known issue, pending Ledger to provide fix related to their firmware issue, target not to include in first release as tentative timeline is late March from Ledger. 
refer https://app.zenhub.com/workspaces/cet-metamask-hardware-wallets-6566ee6aedc46007d5a260bb/issues/zh/127
