### ISSUE TITLE
[Bug]: v7.16 release on GitHub has a different signing key than the previous version.

### ISSUE THREAD

**Issue by NotMainstream** [MetaMask/metamask-mobile#8726]
### Describe the bug

Cannot update app because v7.16 release on GitHub has a different signing key than the previous release.
I use Obtainium to automatically update MetaMask directly from GitHub on a Android device that doesn't have Google Play and GSF.

### Steps to reproduce

Update app using GitHub release.

### Version

7.15

### Build type

None

### Device

Google

### Operating system

Android

**Comment by Cal-L** [comment]
@NotMainstream There was a mismatch in the APK that was uploaded. Please try again when you have the chance. Will close the issue for now. Let us know if you're still experiencing the issue.
