### ISSUE TITLE
[MOB] Remove top spacing maxHeight restriction for BottomSheet

### ISSUE THREAD

**Issue by brianacnguyen** [MetaMask/metamask-mobile#8754]
Currently the BottomSheet has a 250px gap on top calculated into the maxHeight restrictions for the BottomSheet. This has caused multiple teams to have the need to adjust the gap to fit their content. After talking with Hiro, DS designer, this gap should be removed so that the BottomSheet can provide more room for developers and designers to control.

**Comment by wachunei** [comment]
This is blocking #8627 cc: @bkirb
