### ISSUE TITLE
[Bug]: Nonce values displayed randomly next to the transactions  in the Activity list.

### ISSUE THREAD

**Issue by sleepytanya** [MetaMask/metamask-mobile#8761]
### Describe the bug

Nonce values are shown above the transactions in random order creating a possible confusion for the user.

### Expected behavior

Transactions should be displayed uniformly within the Activity list for enhanced clarity and coherence.

### Screenshots/Recordings

![Screenshot_20240227_201304_MetaMask](https://github.com/MetaMask/metamask-mobile/assets/104780023/a81e771f-b3be-48d8-8d70-642ca66d003e)
![Screenshot_20240219_221421_MetaMask-QA](https://github.com/MetaMask/metamask-mobile/assets/104780023/40898e0b-0acc-44a5-85fa-6540ca64a1f3)

### Steps to reproduce

1. Open MetaMask
2. Create several transactions of any type
3. Notice that in Activity list some of the transactions have nonce value next to them

### Error messages or log output

```shell
No errors
```

### Version

7.17.0, 7.16.0 and older

### Build type

None

### Device

Samsung s24+

### Operating system

Android

**Comment by cryptotavares** [comment]
@bschorchit what would be the desirable data to be displayed?

**Comment by bschorchit** [comment]
> @bschorchit what would be the desirable data to be displayed?

Not desirable to be displayed where it's currently showing up in the screenshots, but it's desirable info to be displayed within the transactions details page.
