### ISSUE TITLE
[Bug]: Our website is not in the block list, but still getting the Phishing Warning Message pop up

### ISSUE THREAD

**Issue by alsonyecrypto** [MetaMask/metamask-mobile#8764]
### Describe the bug

Here is our dapp website : [https://fulcrom.finance](https://fulcrom.finance), which is not a phishing one,  and checked in the [https://github.com/MetaMask/eth-phishing-detect](https://github.com/MetaMask/eth-phishing-detect), not listed but still getting Phishing error
![image](https://github.com/MetaMask/metamask-mobile/assets/104058983/1d591f33-80b4-4c09-bdad-b226912666e5)

### Expected behavior

Can open the website [https://fulcrom.finance](https://fulcrom.finance) correctly

### Screenshots/Recordings

![image](https://github.com/MetaMask/metamask-mobile/assets/104058983/68ac5683-bc51-4a86-b306-185ac368a093)

https://github.com/MetaMask/metamask-mobile/assets/104058983/1cc2e382-0068-4402-b345-dc75d980fe29

### Steps to reproduce

1. uninstall old metamask
2. install the latest one (v7.16.0)
3. type in `https://fulcrom.finance/`
4. getting the Phishing error

### Version

7.16.0(1265)

### Build type

None

### Device

iPhone 11

### Operating system

iOS

### Additional context

iOS version 17.3.1

**Comment by anaamolnar** [comment]
Hello, @alsonyecrypto. I am sorry for responding so late. This should be solved now. Feel free to reopen this issue if that is not the case. Have a nice day!
