### ISSUE TITLE
[Bug]: Signatures - batch of signature requests are displayed one over the other without a way out

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-mobile#8771]
### Describe the bug

**Problem:** for context, in Mobile there is no possibility to display several signature/tx requests and navigate to them like on Extension. Now, if I trigger a batch of 10 transactions, I see that only 1 is effectively emitted, and no matter if I accept or reject, no more transaction popup will appear.
However, on singatures it seems that this is not the case and there are 10 popup signatures one over the other one, and no matter if I accept or reject, the rest keep appearing, until all of them have been accepted/rejected

### Expected behavior

It seems that this could be used as spam, so the convenient way of handling this case would be what we already do with transactions: just trigger one and that's it ? cc @bschorchit 

### Screenshots/Recordings

https://github.com/MetaMask/metamask-mobile/assets/54408225/ca700688-72dd-4a16-bf9f-87bc0d6fca2b

### Steps to reproduce

1. checkout this branch of the test dapp https://github.com/MetaMask/test-dapp/pull/294
2. go to the test dapp
3. connect mm
4. trigger signature x10 batch
5. See you need to accept/reject 10 times, no way to get out

### Version

found in 7.17.0 but might be on other versions too

### Build type

None

### Device

Pixel 6

### Operating system

Android

**Comment by arielsbecker** [comment]
Closely related to #8251.

**Comment by bschorchit** [comment]
I agree we should copy the behavior we have in place for transactions until we introduce some queue to mobile

**Comment by bschorchit** [comment]
This is still an issue that we would like to fix
