### ISSUE TITLE
feat: configurable Segment flush limit

### ISSUE THREAD

**Issue by NicolasMassart** [MetaMask/metamask-mobile#8772]
### What is this about?

In order to ease development and testing, make it possible to modify the flush limit for which the events are sent to Segment.
Using an env var that developer could set to anything in their local `.js.env`.
Have a default to 1 on dev build (Segment SDK default flush is 20 events queue and 30s interval)

### Technical Details

- add 2 new env var to be defined in `.js.env`, one for flush interval, one for flush at.
- both are optionnal.
- use these var in `MetaMetrics` configure to setup Segment client flush policy. See [Segment SDK doc](https://segment.com/docs/connections/sources/catalog/libraries/mobile/react-native/) `flushAt` and `flushInterval `.
- add var template in `.js.env.example`
- add a log at MetaMetrics configure to confirm the flush was customised (on dev build only).
- update MetaMetrics unit tests

### Acceptance Criteria

- dev can configure both interval and event number limit for Segment SDK flush in `.js.env`
- customised values are displayed in logs on dev build only
- unit tests are updated
- `.js.env.example` contains template for these new variables.

### Stakeholder review needed before the work gets merged

- [X] Engineering (needed in most cases)
- [ ] Design
- [ ] Product
- [ ] QA (automation tests are required to pass before merging PRs but not all changes are covered by automation tests - please review if QA is needed beyond automation tests)
- [ ] Security
- [ ] Legal
- [ ] Marketing
- [ ] Management (please specify)
- [ ] Other (please specify)

**Comment by NicolasMassart** [comment]
FYI @seaona

**Comment by seaona** [comment]
thank you v much @NicolasMassart . This will help a lot QA :bow: :heart:
