### ISSUE TITLE
[Bug]: PPOM - `Error: Cannot assign to read-only to property version`

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-mobile#8781]
### Describe the bug

**Problem**: after migrating or when opening the app I see the error `Error: Cannot assign readOnly to property version`

### Screenshots/Recordings
![Screenshot_20240229-090647](https://github.com/MetaMask/metamask-mobile/assets/54408225/593bcfd3-cf16-41f9-9fd1-9c7c67d07db3)

![Screenshot_20240229-090638](https://github.com/MetaMask/metamask-mobile/assets/54408225/07e9de06-100c-4b69-88ab-1a2952d1db99)

### Steps to reproduce

1. Perform an app migration // reload the wallet
2. Open the wallet
3. See error

### Version

7.17.0 but seems it was present earlier too

### Build type

None

### Device

Pixel 6

### Operating system

Android

**Comment by bschorchit** [comment]
Does this crash the app for the user? Is this something we want to fix before making it default?

**Comment by seaona** [comment]
It does not break the wallet and I'm not sure on what's the impact of the issue. From what I've seen, the feature continues to work normally, but the potential impact should be investigated further on the codebase

**Comment by seaona** [comment]
I've tried a couple of times but I'm not encountering the issue. I've added the `needs-reproduction` label and I guess it could be de-prioritized if there are no more occurrences 
cc @blackdevelopa @bschorchit

**Comment by bschorchit** [comment]
That makes sense, thank you for looking into this @seaona!

**Comment by blackdevelopa** [comment]
I will be temporarily closing this issue at this time as it can't be reproduced. Anyone can always reopen this issue if this happens again
