### ISSUE TITLE
[Bug]: PPOM - Closing alert icon overloads text box

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-mobile#8782]
### Describe the bug

**Problem:** with the new copy text for `No alerts received` we see how the closing icon is now overloading the text box

### Screenshots/Recordings

![closing-icon-ppom](https://github.com/MetaMask/metamask-mobile/assets/54408225/31364611-e14b-4280-86fb-3213c7f81519)

### Steps to reproduce

1. Trigger a benign request

### Version

7.17.0

### Build type

None

### Device

Pixel 6

### Operating system

Android

**Comment by blackdevelopa** [comment]
Closing this issue as I can't seem to reproduce it on main branch

https://github.com/MetaMask/metamask-mobile/assets/29962968/24de74dd-10cd-4413-9fa0-f51de810d5a4

**Comment by blackdevelopa** [comment]
Reopened as I reproduced on an android device

https://github.com/MetaMask/metamask-mobile/assets/29962968/ab8d31d5-69fa-495a-a4c5-b804be3e5b2f
