### ISSUE TITLE
[Bug]: What's New not displayed migrating from 7.16 to 7.17

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-mobile#8793]
### Describe the bug

**Problem:** the What's new popup is not displayed when migrating from 7.16 to 7.17
See: https://github.com/MetaMask/metamask-mobile/issues/8553
This was fixed for 7.16 but again appearing for 7.17

### Screenshots/Recordings

https://github.com/MetaMask/metamask-mobile/assets/54408225/39f7b180-55f5-4ffa-8c00-ca54376b19af

### Steps to reproduce

1. Install 7.16 -- see Blockaid whats'new
2. Migrate to 7.17 -- no what's new appear

### Version

7.17.0

### Build type

None

### Device

Pixel 6

### Operating system

iOS

**Comment by bschorchit** [comment]
Closing as no longer relevant
