### ISSUE TITLE
Reduce enzyme usage in unit test down to 50% - [2 of 3]

### ISSUE THREAD

**Issue by kylanhurt** [MetaMask/metamask-mobile#8806]
### What is this about?

Convert the list of unit tests to use react-testing-library instead of enzyme. In total there are 53 files to convert. To make PRs easier to review and more manageable, this covers 17 test files.

### Technical Details

Convert these files:

```
 'app/components/UI/OnboardingWizard/Step5/index.test.tsx',
  'app/components/UI/OnboardingWizard/Step6/index.test.tsx',
  'app/components/UI/OnboardingWizard/Step4/index.test.tsx',
  'app/components/UI/OnboardingWizard/Step2/index.test.tsx',
  'app/components/UI/OnboardingWizard/Step1/index.test.tsx',
  'app/component-library/components/Tags/TagUrl/TagUrl.test.tsx',
  'app/components/Views/confirmations/components/SignatureRequest/ExpandedMessage/index.test.tsx',
  'app/component-library/components/Avatars/Avatar/foundation/AvatarBase/AvatarBase.test.tsx',
  'app/components/Views/SimpleWebview/index.test.tsx',
  'app/components/Views/OnboardingCarousel/index.test.tsx',
  'app/components/Views/ManualBackupStep3/index.test.tsx',
  'app/components/UI/NavbarTitle/index.test.js',
  'app/components/UI/SkipAccountSecurityModal/index.test.tsx',
  'app/components/UI/EditGasFeeLegacy/index.test.tsx',
  'app/components/UI/EditGasFee1559/index.test.tsx',
  'app/component-library/components/Badges/BadgeWrapper/BadgeWrapper.test.tsx',
  'app/components/UI/HintModal/index.test.tsx',
  ```

### Acceptance Criteria

Unit tests for the updated files should all pass. Snapshots may be updated

### Stakeholder review needed before the work gets merged

- [ ] Engineering (needed in most cases)
- [ ] Design
- [ ] Product
- [ ] QA (automation tests are required to pass before merging PRs but not all changes are covered by automation tests - please review if QA is needed beyond automation tests)
- [ ] Security
- [ ] Legal
- [ ] Marketing
- [ ] Management (please specify)
- [ ] Other (please specify)

**Comment by Cal-L** [comment]
Closing this in favor of the new batch of enzyme tickets  in https://github.com/MetaMask/mobile-planning/issues/835
