### ISSUE TITLE
[Bug]: PPOM - No blockaid data is included in Metrics events for transactions triggered from inside the wallet

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-mobile#8824]
### Describe the bug

**Problem:** there is no Blockaid information on metric events for transactions triggered from inside the wallet

### Expected behavior

We should have the same metrics as we have for transactions triggered from a dapp, for the following events:
- Tx added
- Tx rejected
- Tx acceptdd

### Screenshots/Recordings

https://github.com/MetaMask/metamask-mobile/assets/54408225/12153f52-baeb-4344-b6f6-0c00c2a1d1fc

### Steps to reproduce

1. Enable Blockiad
2. Enable metrics
3. Send a malicious tx from inside the wallet
4. See no blockaid info is included in the metrics event

### Version

7.17.0

### Build type

None

### Device

Pixel 6 

### Operating system

Android

**Comment by cryptotavares** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/-Confirmations-Secure-UX-6245e6e2348677001213b8d2/issues/MetaMask/metamask-mobile/8824?planning-poker) with Zenhub @blackdevelopa @digiwand @jpuri @seaona @segun

**Comment by segun** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/-Confirmations-Secure-UX-6245e6e2348677001213b8d2/issues/MetaMask/metamask-mobile/8824?planning-poker) with Zenhub @pedronfigueiredo

**Comment by segun** [comment]
NOTE: We don't send blockaid metrics on transaction started for DAPP as well. Only for rejected/cancelled.

**Comment by seaona** [comment]
re-opening as I'm still not seeing this fixed :thinking:
