### ISSUE TITLE
[Bug]: PPOM - Enabling Blockaid lands me to the Experimental Settings page

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-mobile#8830]
### Describe the bug

**Problem:** whenever enabling Blockaid I land into the Experimental settings screen

### Expected behavior

I should stay into the security settings page

### Screenshots/Recordings

https://github.com/MetaMask/metamask-mobile/assets/54408225/44d48168-56c1-48fd-9150-32e88f2e7974

### Steps to reproduce

1. Go to security settings
2. Disable blockaid
3. Enable it
4. See how you land into the experimental settings

### Version

7.17.0

### Build type

None

### Device

Pixel 6

### Operating system

Android

**Comment by jpuri** [comment]
This issue is not replicating any more.
