### ISSUE TITLE
[Bug]: Asset's type is always ETH in the notification

### ISSUE THREAD

**Issue by thanks173** [MetaMask/metamask-mobile#8832]
### Describe the bug

When receiving (native) tokens, the notification always shows the assets type as ETH

### Expected behavior

Display the correct asset's type, ERC20 or native

### Screenshots/Recordings

![307285267-976c0f53-fd09-49fb-be1a-6b9dd84d0835](https://github.com/MetaMask/metamask-mobile/assets/30585557/33f5edbf-5d10-4ab0-b9f4-ae77cbd2013a)
This is 750 USDT incomming transaction

### Steps to reproduce

1. Send token to the wallet
2. Wait for the notification

### Version

7.15.0

### Build type

None

### Device

iPhone

### Operating system

iOS

### Additional context

I created PR #8699 for this

**Comment by seaona** [comment]
Same/Similar as https://github.com/MetaMask/metamask-mobile/issues/7669
