### ISSUE TITLE
[Bug] redux storage error for swap

### ISSUE THREAD

**Issue by angelcheung22** [MetaMask/metamask-mobile#8900]
https://consensys.slack.com/archives/C026NDN79JB/p1709923847197369

@Akaryatrh 
Could you supplement the steps to reproduce, and what build/what device you tested.

**Comment by vivek-consensys** [comment]
Tested on iPhone 13 on iOS 17.3.1 using Bitrise build:- https://app.bitrise.io/build/6a2bd46b-4134-45be-a1af-5eca5f5fc796?tab=artifacts


[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOG52QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--96fa7fad0376303019982bf2f936feaa3149c66e/RPReplay_Final1710843240.MP4)
