### ISSUE TITLE
Crash: UI update after INPAGE_RESPONSE

### ISSUE THREAD

**Issue by brunobar79** [MetaMask/metamask-mobile#893]
https://fabric.io/metamask/ios/apps/io.metamask.metamask/issues/5c941e69f8b88c296304614b/sessions/f24199e63de24336afc9ec3f6d01600e_DNE_0_v2?

**Comment by brunobar79** [comment]
I believe that what's going on is the following:

- We load a site and inject web3
- The site starts making RPC calls
- While there's an RPC call still pending ( dapp => provide => Background Brige ) the page gets reloaded with force = true, which will re-render the webview.
- The RPC call promise resolves and we try to return the call to the previous site
- The webview ref doesn't exist anymore and the dapp crashes

A way to reproduce it is to tap the home button several times very fast until you run in that scenario.

**Comment by nelwincatalogo** [comment]
> I believe that what's going on is the following:
> 
> * We load a site and inject web3
> * The site starts making RPC calls
> * While there's an RPC call still pending ( dapp => provide => Background Brige ) the page gets reloaded with force = true, which will re-render the webview.
> * The RPC call promise resolves and we try to return the call to the previous site
> * The webview ref doesn't exist anymore and the dapp crashes
> 
> A way to reproduce it is to tap the home button several times very fast until you run in that scenario.

Looks like this issue has resurfaced

device: android
version: 7.75.1
