### ISSUE TITLE
[Bug]: Unable to activate the ETH Sign requests toggle.

### ISSUE THREAD

**Issue by sleepytanya** [MetaMask/metamask-mobile#8949]
### Describe the bug

There's a misalignment in the ETH Sign requests modal, which has resulted in the Confirm button being half-visible and not visible at all.

### Expected behavior

Confirm button is fully visible.

### Screenshots/Recordings

https://github.com/MetaMask/metamask-mobile/assets/104780023/8794cb99-1d27-43ef-8bd7-809abbcc79bf

### Steps to reproduce

1. Go to Settings -> Advanced
2. Turn on ETH_sign requests toggle
3. See Confirm button on the first Confirmation screen is half-visible
4. Click Confirm
5. Type 'I only sign what I understand'
6. Notice the Confirm button in not visible at the screen

### Version

7.16.0

### Build type

None

### Device

Samsung s24+

### Operating system

Android

**Comment by hesterbruikman** [comment]
@sleepytanya Can you please check if this issue can reproduced on 7.18.0 and other devices? I'm not able to reproduce on Samsung s10e and devices with smaller screen sizes.

**Comment by sleepytanya** [comment]
@hesterbruikman 7.18.0 ETH-sign request toggle works as expected.

**Comment by hesterbruikman** [comment]
Thanks for the efforts to reproduce the issue @sleepytanya ! What I'm getting is that the issue could only be reproduced on s24x physical device, and was magically fixed. 7.18.0 is in rollout.

**Comment by sleepytanya** [comment]
Sure! There were plans to deprecate this feature anyway.
