### ISSUE TITLE
[Ledger] Mobile transactions fail on main branch

### ISSUE THREAD

**Issue by angelcheung22** [MetaMask/metamask-mobile#8968]
**Description**
After the TransactionController upgrade to 8.0.1, it use `@ethereumjs/tx: 4.2.0 version, this library have break change on tx.common class which drop function chainIdBN(), and the old version @ethereumjs/tx: 3.5.0 used in @consensys/ledgerhq-metamask-kering still use the old version of tx.common and deprecated chainIdBN() function in BaseTransaction.ts.

**Comment by vivek-consensys** [comment]
Tested on iPhone 13 on iOS 17.3.1 using Bitrise build:- https://app.bitrise.io/build/6a2bd46b-4134-45be-a1af-5eca5f5fc796?tab=artifacts


[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOHp2QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3073b88eeb8adfa907210c0c5e9b1611e96edc93/RPReplay_Final1710843065.MP4)
