### ISSUE TITLE
Forcing LTR on RTL Android devices

### ISSUE THREAD

**Issue by AboShanab** [MetaMask/metamask-mobile#897]
Hello there, the experience was really good but the UI looks not easy to use on RTL language devices because it's forced from the Android system (Android 9 here) to be RTL while the design is for LTR for now. Here is some screenshots while digging into the app:
![Screenshot_1](https://user-images.githubusercontent.com/12101368/61691025-51debd00-ad33-11e9-983c-03c21a9ef7a9.jpg)
![Screenshot_2](https://user-images.githubusercontent.com/12101368/61691032-55724400-ad33-11e9-9616-dfa09d16256c.jpg)
![Screenshot_3](https://user-images.githubusercontent.com/12101368/61691039-586d3480-ad33-11e9-820e-1de46e8fc533.jpg)
![Screenshot_4](https://user-images.githubusercontent.com/12101368/61691047-5d31e880-ad33-11e9-9dc8-81a3b9998b26.jpg)
![Screenshot_5](https://user-images.githubusercontent.com/12101368/61691055-6458f680-ad33-11e9-9959-6d2ef1299e72.jpg)

**Comment by AboShanab** [comment]
@gbugyis @danfinlay Doesn't that issue easy to fix?
Hope this help: https://stackoverflow.com/questions/44211307/force-rtl-on-ltr-devices#44213077

**Comment by EtDu** [comment]
Are you still experiencing this? Enabling RTL in the developer options does not seem to make a difference in the UI.
