### ISSUE TITLE
User unable to send tx after enabling nearby devices option

### ISSUE THREAD

**Issue by angelcheung22** [MetaMask/metamask-mobile#8972]
Tested locally using Samsung Android 13. 

Branch: fix/8643-location-permission-issue

The user is unable to send a transaction after enabling the 'Nearby Devices' option in settings:-

Steps to reproduce:
1. Import SRP
2. Connect Ledger device
3. Go to Settings>Apps>MetaMask and disable Nearby Devices
4. Open MetaMask
5. Attempt to send testnet eth
6. After selecting a destination and an amount tap Confirm with Ledger
7. When prompted for permission select Don't allow
8. Go to Settings>Apps>MetaMask and enable Nearby Devices
9. Open MetaMask
10. Click try again tx 
11. Error appears

[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeTJ3QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a324d70fe7860c3fa6e758cefb6dedabaa5921f8/Screen_Recording_20240304_140126_MetaMask.mp4)

**Comment by vivek-consensys** [comment]
Tested on Samsung S21 Android 13 using Bitrise build:- 
https://app.bitrise.io/app/be69d4368ee7e86d/build/621f920f-fb77-4938-a491-8d070ebabe13/artifact/029c22d088a13921/p/c933828c816e9a10a9d61bab3c85e4f6

Error message still appears, please see screen recording: 

[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNVR3QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d9bcbf55fd4b96e54375a359d2e7f28d0c1db2bf/Screen_Recording_20240319_125740_MetaMask.mp4)

Please check @dawnseeker8
