### ISSUE TITLE
explorer.livepeer.org not working

### ISSUE THREAD

**Issue by chrishobcroft** [MetaMask/metamask-mobile#898]
When browsing to explorer.livepeer.org, the site does not connect to MetaMask Mobile.

It has worked for over a year with the browser extension.

![Screenshot_20190723-101517](https://user-images.githubusercontent.com/2212651/61695057-13e19900-ad33-11e9-840d-63b462c096e5.png)

cc @iameli @livepeer

**Comment by brunobar79** [comment]
@chrishobcroft  I've tapped where it says  "METAMASK" in the red warning and got the right "Connect" prompt and it looks like it's working fine.

**Comment by chrishobcroft** [comment]
I tap that and it takes me to MetaMask.io

Are you doing this on Android?

**Comment by chrishobcroft** [comment]
Not fixed.

Version 0.2.4 (17) on Android.

**Comment by brunobar79** [comment]
@chrishobcroft  We haven't release this yet but the issue has been fixed. A new version should be live early next week.
