### ISSUE TITLE
[Bug]: MetaMask browser erroring out due to script tag when connecting via DApp

### ISSUE THREAD

**Issue by 612crypto** [MetaMask/metamask-mobile#8999]
### Describe the bug

When connecting to a webapp via WalletConnect modal in the MetaMask mobile browser, MetaMask is reporting an error regarding a properly formatted script tag.

### Expected behavior

Script tag should not be causing an error

### Screenshots/Recordings

![image](https://github.com/MetaMask/metamask-mobile/assets/116190424/050fb262-f205-4367-b348-6e5f82518348)

### Steps to reproduce

Attempt to connect wallet to DApp via WalletConnect modal

### Error messages or log output

```shell
View: Root
Error: Expected > (16:52). If this is valid SVG, it's probably a bug. Please raise an issue


  <script type="module" crossorigin src="/assets/index-2563fea1.js"></script>

                                     ^
```

### Version

7.16.0 (1265)

### Build type

None

### Device

iPhone 15

### Operating system

iOS

**Comment by anaamolnar** [comment]
Hello, @612crypto . Thanks for reporting! What is the dapp you attempt to connect to so we can try to reproduce the issue?
