### ISSUE TITLE
Can we add cross app communication api for other mobile app?

### ISSUE THREAD

**Issue by harryfei** [MetaMask/metamask-mobile#900]
Both iOS and Android have cross app communication mechanism. Can we implement some APIs for other mobile apps to sign the transactions?
Some developers (including me) may want to implement their dapps in the form of mobile native app.

**Comment by ligi** [comment]
Would also love this. Perhaps we can reuse WalletConnect for this.

**Comment by brunobar79** [comment]
We had plans for an SDK in the roadmap around v1. 
Just opened #902  feel free to add your comments to it.

**Comment by harryfei** [comment]
I think we can close this now.
