### ISSUE TITLE
[Security] Bypass fingerprint lock for iOS and android Metamask apps

### ISSUE THREAD

**Issue by jpopxfile** [MetaMask/metamask-mobile#901]
Issue
Able to login to wallet with fingerprint log without any proper authentication

For the Metamask android (v0.2.0 (13)) and iOS (v0.2.0 (225)) app, the only option for requiring authentication for the app is to set a fingerprint lock.
There is no feature to set the password for app authentication.
However, if you try to enter an empty password on the app login page, you can access the wallet without the need for the fingerprint

Reproduction steps
1. Enable fingerprint login
2. Terminate the metamask app
3. Start up metamask app and see the fingerprint login prompt
4. Press cancel to go in to the password login screen
5. With an empty password, press login
6. Verify that you have access to the wallet

**Comment by brunobar79** [comment]
@jpopxfile Thanks for reporting this!

Just adding some clarification to avoid people freaking out...

This is the reason why this is happening:

We don't ask you to enter a password unless:
a) You receive funds
b) You import a wallet via seed phrase or sync with extension.

In the scenario that you're mentioning you're manually enabling biometrics under settings without having a password set, which lets you proceed with an empty password but the risk is almost null cause you have an empty wallet.

I agree that's not a nice experience so we might just disable biometrics from settings until you set a password, which will completely mitigate this issue.

 *potentially* we might add an option to set a password "optionally" even when you didn't receive funds.

I'll discuss with the rest of the team and report back.

**Comment by jpopxfile** [comment]
> which lets you proceed with an empty password but the risk is almost null cause you have an empty wallet.

There might be a scenario where this has some risk; If someone manages to get the private key for the empty wallet where there is fingerprint authentication, and you use it later on.

In my opinion, I think that once you create a wallet, even if funds are not received, having the option to set a password would be a more secure option for users, rather than removing authentication for empty wallets entirely.

**Comment by brunobar79** [comment]
Fair point. I agree with you and I think we should do both.

- Disable biometric authentication until you have a password set
- Ability to add a password at any time (even without funds).

**Comment by brunobar79** [comment]
Actually a better approach that @cjeria  Ask for a password at the time of turning biometrics on (if you don't have one yet).  IMO That's the most secure / best UX route we can take.  We'll try to ship a new version later today.

**Comment by jpopxfile** [comment]
Just curious, but does something like (severity is different though) this apply for this Metamask mobile?
https://medium.com/metamask/seed-phrase-issue-bounty-awarded-e1986e811021

**Comment by bdresser** [comment]
@jpopxfile we issue bounties at the team's discretion. We very much appreciate you flagging this issue, but it's small enough and affects a beta application so we don't think it's severe enough for a bounty. Thank you again.

**Comment by jpopxfile** [comment]
Ok. In my opinion, severity is a valid and understandable reason, but it being a beta application should not be used when reasoning for eligibility for bounties, especially when the beta would most likely be released as production in the near future. Otherwise there might be some out there who might not report security issues as soon as they are found in beta stage. Again, that is if there is a working active bounty program in place.

Anyway, you are welcome, and great job fixing it so quickly.

**Comment by Superhopeman** [comment]
So far in 2021, I noticed that when you open the MM on your Android phone, the login process does not end and switch between apps, then comes back to MM, the fingerprint scan is not available. This seems to be a big problem, because you can't get to your wallet quickly enough at the desired time
