### ISSUE TITLE
[DETOX] Unable to close Price difference of % error on swap test script on ios

### ISSUE THREAD

**Issue by SamuelSalas** [MetaMask/metamask-mobile#9017]
### Describe the bug

From time to time, in some occasions, while executing `e2e/specs/swaps/swap-action-regression.spec.js` or `e2e/specs/swaps/swap-action-smoke.spec.js` detox test, an error might appear making the user know that the price difference of the token swap is elevated. So there's a step that close the alert if the alert appears. But consistently, detox is unable tap the `I understand` button to close the alert.

### Expected behavior

Detox should be able to tap the `I understand` button from the Price difference of % alert when the percentage of the token swap is above average. 

### Screenshots/Recordings

<img width="386" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMGY2QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--bad0c1b52fa7a72484d260eda72632d26eb2d305/image.png" alt="image.png" />

### Steps to reproduce

Execute the detox automated scripts `e2e/specs/swaps/swap-action-regression.spec.js`.

### Version

[7.19.0 RC1 build 1282](https://app.bitrise.io/app/be69d4368ee7e86d/pipelines/e7de48ec-dfb3-4700-a258-9dfda7940f78)
This issue is also present on main.

### Build type

None

### Device

iPhone 13 pro

### Operating system

ios

### Additional context

Already tried to add a testID to the `I understand` button, but still detox was not able to detect the button.

**Comment by cortisiko** [comment]
Closing as completed
