### ISSUE TITLE
Peepeth sign up not working

### ISSUE THREAD

**Issue by brunobar79** [MetaMask/metamask-mobile#904]
Peepeth works fine if you signed up using the extension, but if you try to go through the entire flow from mobile you'll get stuck and potentially crash the app.

**Comment by bitpshr** [comment]
Are there any additional details around this? I compared every relevant RPC request (of which there were _tons_, good lord, Peepeth is doing some stuff...) and requests and responses matched the extension.

I hit no issues when signing up using the simulator:

<img width="545" alt="welcome" src="https://user-images.githubusercontent.com/334586/62179169-952fc180-b319-11e9-8fae-5d058284ebf7.png">

<img width="545" alt="start" src="https://user-images.githubusercontent.com/334586/62179173-9660ee80-b319-11e9-89cc-9dca45b25e25.png">

<img width="545" alt="home" src="https://user-images.githubusercontent.com/334586/62179178-97921b80-b319-11e9-93bf-3b957e32dc81.png">

**Comment by estebanmino** [comment]
no longer an issue
