### ISSUE TITLE
[Bug]: website suggest gasprice is not take for erc20 token approve transaction

### ISSUE THREAD

**Issue by weequan93** [MetaMask/metamask-mobile#9043]
### Describe the bug

I have a evm compatible chain (Arbitrum Orbit) which have the 0 gas fee for certain transaction ( include token approve).
During web3js sending the transaction, it set the gas price to "0x0" already, However when try to do signing in metamask mobile wallet, it appear that gas fee is not sufficient warning (and no option to choose for website suggest gas fee). 

### Expected behavior

When user address without enough gas token, should be stil able to send the gas price 0 transaction.

### Steps to reproduce

1. Open [dev.deriw.com
](https://dev.deriw.com/#/transaction)
2. Claim USDT from top right corner. 
3. Adjust leverage to more than 1
4. enter usdt amount (more than 10,  eg.15)
5. approve token
6. should be able to sign , and grant approver

### Error messages or log output

```shell
you need 0.0009 more deriw to complete this transaction
```

### Version

7.18.0

### Build type

None

### Device

Xiaomi Mi 13T Pro

### Operating system

Android

**Comment by DanielTech21** [comment]
Hi @weequan93 

Thanks for reporting this issue to us.
Our team will investigate it and provide further updates.

**Comment by seaona** [comment]
thank you @weequan93 I don't see the Claim button you mention in your repro steps, but I've tried the gasless Mint and it also gives problems.

Context: we had another issue in the past with gasless transactions, [for reference](
https://github.com/MetaMask/metamask-mobile/issues/6567)

Suggestion: we should follow the same approach as done in Extension

https://github.com/MetaMask/metamask-mobile/assets/54408225/adb5e787-1785-4a8a-bd77-abbb3c43f112

**Comment by weequan93** [comment]
> thank you @weequan93 I don't see the Claim button you mention in your repro steps, but I've tried the gasless Mint and it also gives problems.
> 
> Context: we had another issue in the past with gasless transactions, [for reference](https://github.com/MetaMask/metamask-mobile/issues/6567)
> 
> Suggestion: we should follow the same approach as done in Extension
> 
>  0-fee-txs.mp4

@seaona  should be the "mint" button.

**Comment by weequan93** [comment]
> thank you @weequan93 I don't see the Claim button you mention in your repro steps, but I've tried the gasless Mint and it also gives problems.
> 
> Context: we had another issue in the past with gasless transactions, [for reference](https://github.com/MetaMask/metamask-mobile/issues/6567)
> 
> Suggestion: we should follow the same approach as done in Extension
> 
>  0-fee-txs.mp4

can you try https://dev.deriw.com/#/transaction here? 
1) after you minted
2) enable leverage first (set it to 10x)
3) enter a usdt value more than 10(example 15)
4) click approve button (upon here unable to adjust the gas price or other related setting )

**Comment by weequan93** [comment]
Seem like now erc20 approval have the option to adjust the gas price now, but reading from injected parameter still no working.
