### ISSUE TITLE
Buy ETH with credit card

### ISSUE THREAD

**Issue by lastmjs** [MetaMask/metamask-mobile#905]
General inquiry about credit cards: I see a button for buying ETH with credit card, and it says coming soon. I'm curious the timeline on this and also what service will be utilized for the payments, and what countries/states will have access to this. I think this could have a large impact on the industry, because right now you have to maintain at least two separate accounts to buy ETH or other tokens and then to use them in MetaMask. Thanks!

**Comment by lastmjs** [comment]
One thing I'd like to add is that I hope the integration with Wyre or whoever occurs directly within the app, without requiring the user to leave the app and sign up with another service. For example, using the Wyre Widget

**Comment by EtDu** [comment]
Coming in V1 - #1666
