### ISSUE TITLE
[Bug]: automated regression Custom RPC Tests is consistently failing on android device

### ISSUE THREAD

**Issue by chrisleewilcox** [MetaMask/metamask-mobile#9050]
### Describe the bug

Custom RPC Tests regression test has been failing on the nightly tests runs since March 21st.

First reported failure: https://app.bitrise.io/build/4f44c048-f6c0-42c1-9bb1-d01ea05001ee

### Expected behavior

Custom RPC Tests regression test should pass.

### Screenshots/Recordings

![image](https://github.com/MetaMask/metamask-mobile/assets/6626407/8ce50f12-1294-4f9b-ac88-78d7b8fc92a7)

### Steps to reproduce

1. Run `pr_regression_e2e_pipeline` on main branch
2. Failure for Custom RPC Tests

### Error messages or log output

```shell
See logs and screenshot from https://app.bitrise.io/build/4f44c048-f6c0-42c1-9bb1-d01ea05001ee
```

### Version

7.20.0

### Build type

None

### Device

Android

### Operating system

Android

**Comment by Cal-L** [comment]
Failure may be related to a change in app behavior. Work with a dev to debug

**Comment by Andepande** [comment]
https://github.com/MetaMask/metamask-mobile/pull/9181
