### ISSUE TITLE
[Bug]: app freezes, no longer to open after playing video using in-app browser on android device

### ISSUE THREAD

**Issue by chrisleewilcox** [MetaMask/metamask-mobile#9052]
### Describe the bug

Playing a video on the in-app browser freezes the mobile app and app is no longer able to open after restarting it.

### Expected behavior

Playing video using in-app browser should not freeze up app.  App should continue to function as normal after playing video.

### Screenshots/Recordings

https://github.com/MetaMask/metamask-mobile/assets/6626407/e225fb2e-e518-4dbe-99c7-8f676e6d229c

### Steps to reproduce

- with in-app browser navigate to https://testfile.org/
- tap video
- tap download 33MB video file
- after video starts playing pause the video
- app is unresponsive
- not able to tap on anything in the app
- log output is continuous

Expected:
- app continues to respond pausing or playing video with in-app browser
- log output is not continuous

### Version

7.18.0

### Build type

None

### Device

Android emulator

### Operating system

Android

**Comment by Cal-L** [comment]
@chrisleewilcox Can we verify this on physical device?
