### ISSUE TITLE
[Bug] Imported account balance is outside the box in sign this message modal

### ISSUE THREAD

**Issue by SamuelSalas** [MetaMask/metamask-mobile#9057]
### Describe the bug

While using an imported account, when the "sign this message" modal is displayed, the balance would be displayed incorrectly.

### Expected behavior

The account name and the balance should be displayed correctly inside the expected box

### Screenshots/Recordings

<img width="360" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeklRQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4b47c704248d8be6b92d1424c3b87a4b4b7720d8/image.png" alt="image.png" />

### Steps to reproduce
1. Tap on the Import Token on Etherium Main Network
2. Tap on Search Tokens bar
3. Tap the space bar key on the phone keyboard

**Comment by sleepytanya** [comment]
Same on the NFT and ERC1155 contract interactions screens:
![Screenshot_20240329_212910_MetaMask (1)](https://github.com/MetaMask/metamask-mobile/assets/104780023/dc273e47-3792-466b-9162-582d0d177886)
