### ISSUE TITLE
 [Bug]: Text misalignment "for unable to find conversion rate" for non English languages

### ISSUE THREAD

**Issue by SamuelSalas** [MetaMask/metamask-mobile#9081]
### Describe the bug

On the Wallet scree, in some occasions the app won't be able to render the conversion rate of a token. So, a label "unable to find conversion rate" would be displayed without any issue in English. In multiple languages, the label is to large and could make the label of the token misalign.

### Expected behavior

The label should not affect the token name.

### Screenshots/Recordings

<img width="369" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNFVZQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1982e73cf66c49975500f36ac481a8dc81d64a5a/image.png" alt="image.png" />
<img width="369" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNFlZQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e6d90cd9c66ec52e5824fc30d2ee1693ec204914/image.png" alt="image.png" />
<img width="369" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNGNZQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--abfbbe1c6b5aa6ccee72d2bbcd7f0fbc233fc778/image.png" alt="image.png" />

**Comment by anaamolnar** [comment]
Related to https://github.com/MetaMask/metamask-mobile/issues/8523
