### ISSUE TITLE
Deep links in Wallet Connect Web3Modal directs to 404 page (Android) or the app page on the App store (iOS)

### ISSUE THREAD

**Issue by Nick-Son** [MetaMask/metamask-mobile#9095]
### Describe the bug
The user has integrated Wallet Connect's Web3Modal into their app (https://easnft.com/), using a MetaMask deep link (https://metamask.app.link/dapp/easnft.com/), but the link from the Web3Modal does not direct the user correctly to the MetaMask browser.

- On Android, when the user selects the MetaMask option from the modal, the user is directed to a 404 page in the MetaMask mobile browser.
- On iOS, when the user selects the MetaMask from the modal, they are taken to the MetaMask app page in the app store.

### Expected behavior
When the user selects the MetaMask option, the app is opened in the MetaMask mobile app browser and prompted to connect their wallet.

### Screenshots/Recordings
![Screenshot 4 (Android error)](https://github.com/MetaMask/metamask-mobile/assets/13466714/2d36b255-758c-4ad6-9277-7b0999172805)

Code snippet (as suggested by the Wallet Connect documentation):
![Screenshot 2024-03-29 at 4 57 59 pm](https://github.com/MetaMask/metamask-mobile/assets/13466714/ede1eebc-1350-4f86-9b97-7ebe8e10c51e)

### Steps to reproduce

1. In a mobile browser, go to https://easnft.com/
2. Tap the hamburger menu in the top-right
3. Tap Connect Wallet
4. Select MetaMask (Mobile)

### Version
Tested on 7.17.0 & 7.18.0

### Device
Android and iOS devices

### Operating system
Android & iOS

**Comment by christopherferreira9** [comment]
Closing this issue but in the meantime feel free to open it again if you need any other clarification from our side.
