### ISSUE TITLE
[Bug]: Approval Requests Not Showing up in the Metamask iOS App

### ISSUE THREAD

**Issue by arturdev** [MetaMask/metamask-mobile#9096]
### Describe the bug

From dApps, when trying to send an Approval Request through WC to the Metamask, after navigating to the Metamask App, the bottom sheet does not appear (or appears only the very first time).  This happens only with Metamask Wallet App... All other wallet apps work as expected with the same code in our dapp.. 
Note, that this happens only for Approval Requests.. For Other transaction types the bottom-sheet always appears.

### Expected behavior

The Transaction Approval bottom sheet should always appear

### Steps to reproduce

1. Open any dApp that has WC2 integrated (f.e. CoinStats). 
2. Connect Metamask wallet
3. Go To Swap in CoinStats app. 
4. Choose From and To coins, and set some amount. 
5. Click Approve (you must choose a non-approved coin first) 
6. You get navigated to Metamask app. 
7. Nothing happens in Metamask app. the Approval bottom sheet doesn't appear. (or might appear only one time).

### Error messages or log output

```shell
No error messages
```

### Version

7.18.0

### Build type

None

### Device

iPhone

### Operating system

iOS

### Severity

100% impacted!!!

**Comment by webdevatn** [comment]
Having the same issue

**Comment by christopherferreira9** [comment]
Hi all! Can you please try to leave the MetaMask mobile wallet open for a few minutes to see it it appears? WalletConnect is currently experiencing issues on their relays causing responses to be delayed. We are also updating `@walletconnect/se-sdk` which should help improve this behaviour.

**Comment by judeProground** [comment]
Hi @christopherferreira9.
Do you happen to know when the next update is scheduled?

**Comment by christopherferreira9** [comment]
Hi @judeProground ! We've just merged a PR that bumps the version of `@walletconnect/se-sdk` but we should have a another one with a minor bump being merged next week so we're targeting wallet version `7.21.0`

**Comment by christopherferreira9** [comment]
Hi! `7.21.0` is right around the corner so I'll be closing this issue. If you still experience issues with this please feel free to open a new issue.
