### ISSUE TITLE
[Bug]: Fake Site Connections

### ISSUE THREAD

**Issue by koltigin** [MetaMask/metamask-mobile#9105]
### Describe the bug

When I connected to the following site in the Metamask mobile application, it did not give any warning. If a browser has a plug-in, the site is blocked. However, Metamask did not do this in its mobile browser.

 ⚠️🚨 I don't write the site as a URL, I just add a friend's post as a screenshot so that novice users or anyone else does not accidentally click and go to the address.
 
 ![image](https://github.com/MetaMask/metamask-mobile/assets/102043225/851d899c-17a9-4b57-a302-85d89bebb133)

When you connect to the site and press the connect button, the button starts rotating and performs unknown or unknown operations in the background.

I expect you to review this site and explain what the site is trying to do or what it does. I connected to the site on the ZetaChain Athens 2 Testnet network. However, I have not seen any movement in my wallet for now. If it has the words, it will take time to understand.

Then in Security & Privacy settings I did the following:
1. I cut off all connections from Manage Connections
2. I cleared the data from the Clear privacy data section.
3. I cleared the cookies from the Clear browser cookies section.

### Expected behavior

When the mobile application accesses such fake phishing sites, it should give a warning in the browser, such as the wallet working as an add-on, as seen in the picture below.

![image](https://github.com/MetaMask/metamask-mobile/assets/102043225/dac00f36-c42f-459b-8085-ce9085d20e82)

### Steps to reproduce

1. A person accidentally or absentmindedly logs into such a site.
2. Before the site is opened, Metamask presents the user with a screen stating that this site is harmful.
3. When the user sees this screen, person gives up visiting the site.

### Error messages or log output

```shell
There is no error message.
```

### Version

v7.18.0(1281)

### Build type

None

### Device

Apple iPhone 11

### Operating system

iOS

**Comment by anaamolnar** [comment]
Hello, @koltigin. Thanks for reporting! Chainlist.org is the official website. They have a typo which leads them to a scam website. I will close this request for now. Please reopen if you have further questions on this. Have a nice day!

**Comment by koltigin** [comment]
Hello, @anaamolnar. 
There may be such fake sites that appear at the top when people search. Even advanced users can fall for these in a moment of distraction. Here, it will be important for the browser of the mobile application to present a screen that will warn people, as in the add-on wallet. It would be very useful for the developer team to integrate this into the mobile application.

Thank you too.
