### ISSUE TITLE
[Bug]: Not able to send assets with Keystone HW account, Transaction error shown on Confirm screen

### ISSUE THREAD

**Issue by chrisleewilcox** [MetaMask/metamask-mobile#9108]
### Describe the bug
Not able to send any assets with Keystone hardware wallet account.  Getting error on confirm screen.  This seems to be Keystone hardware wallet specific.  I am not able to reproduce with Ledger.
When I retry this scenario on a non-hw wallet account I am either able to send or if low on asset balance for cost of transaction then an error is shown indicating insufficient funds for gas * price + value, which seems to be proper handling.  
Similar error occurs for iOS

- Was able to successfully reproduce on v7.19.0.  Issue was introduced in v7.19.0.
- Was not able to reproduce on v7.18.0.  

### Android
![image](https://github.com/MetaMask/metamask-mobile/assets/6626407/742ad84d-5945-4090-bda9-d332d4b1c41f)

### iOS
![image](https://github.com/MetaMask/metamask-mobile/assets/6626407/a2223769-144a-41aa-a995-25634d38deef)

### Expected behavior
- Previous mobile app versions would prevent users getting pass the Amount screen if there was a zero asset balance by not enabling the Next button.  
- Currently if a user is able to get all the way to the Confirm screen we seem to be handling this properly for non-hw accounts.

Same scenarios using wallet account, not a hardware wallet account
![image](https://github.com/MetaMask/metamask-mobile/assets/6626407/fb24747e-6703-4e0d-9d96-a90851e013e3)

### Screenshots/Recordings

https://github.com/MetaMask/metamask-mobile/assets/6626407/eb1bd919-2d52-4dab-b23e-baf57a6e6c14

https://github.com/MetaMask/metamask-mobile/assets/6626407/5e2b7c2d-2577-4756-abde-65e00743f735

### Steps to reproduce
Scenario: Send using HW account
GIVEN I have Sepolia Test Network selected
AND I have hardware wallet account selected
WHEN I send assets
THEN assets are successfully sent (FAIL: error shown on Confirm screen)
AND send transaction is properly shown on all transactions screen

Scenario: Send asset using HW account with not enough asset balance
GIVEN I have Ethereum Main Network selected
AND I have hardware wallet account selected
WHEN I send assets
AND I make it to the Confirm screen
AND I send assets
THEN error message is shown on Amount screen
AND error message matches error message for non-hardware wallet account selected (FAIL: "CBOR encoding..." error, see screenshot)

### Version

7.20.0

### Build type

None

### Device

Any

### Operating system

Android and iOS

### Severity
Sev1 blocker

**Comment by plasmacorral** [comment]
Do we know if this is limited to Keystone, or does it impact all qr hw wallets?

What Keystone hardware and firmware version(s) were tested?

**Comment by vivek-consensys** [comment]
It was only Keystone that was affected using v1.2.2

**Comment by eayala604** [comment]
I am also experiencing the same issue with my Keystone 3 Pro V1.3.4 and Meta Mask V7.19.0(1292).

**Comment by katkopel** [comment]
This issue is also present in D'CENT and MM v.7.19.0. No QR code is generated upon txn confirmation.

**Comment by owencraston** [comment]
@vivek-consensys mentioned to me that the signature verification for sign permit on a keystone is also not working. We tested it with airgap and it was working so the issue seems to be keystone specific. This was on the production version of 7.19.0.
