### ISSUE TITLE
[Bug]: "Network not found..." alert message when scanning a QR code for network that has been added to wallet

### ISSUE THREAD

**Issue by chrisleewilcox** [MetaMask/metamask-mobile#9112]
### Describe the bug

After scanning a QR code for wallet address that is on AVAX, and scanning device has AVAX network already added, a device alert is displayed indicating network cannot be found. 

### Expected behavior

Networks that are added on scanning device should properly switch network without alert error.

### Screenshots/Recordings

https://recordit.co/oZnEZhojRV

### Steps to reproduce

GIVEN I have Ethereum Mainnet Network selected
AND I have AVAX network already added
WHEN I scan a QR code that is for AVAX network address
THEN scanning device switches to AVAX network
AND Send To screen is displayed with To address populated with scanned address
AND no alert error is displayed

### Version

7.20.0

### Build type

None

### Device

Any

### Operating system

iOS, Android

### Severity

Sev 3

**Comment by NicolasMassart** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/MetaMask-Mobile-Platform-5f984938ddc0e4001d4b79cb/issues/MetaMask/metamask-mobile/9112?planning-poker) with Zenhub @Cal-L @jpcloureiro @kylanhurt @MarioAslau @tommasini
