### ISSUE TITLE
[Bug]: Request Payment: Scan QR incorrect and extremely high gas fee, for 1 Link shows estimated gas fee over $5K and over 1 eth gas fee

### ISSUE THREAD

**Issue by chrisleewilcox** [MetaMask/metamask-mobile#9117]
### Describe the bug

When I scan a QR code generated from mobile app to receive 1 Link the scanning devices loads send Confirm screen of 1 Link for over $5k or 1 eth for gas fee.  This is not correct.  

### Expected behavior

After scanning a QR code from mobile app for 1 Link the gas fee on the scanning device should show a way more accurate gas fee which is a lot lower than described in this issue.

### Screenshots/Recordings

https://github.com/MetaMask/metamask-mobile/assets/6626407/2a5aa5d7-b7a3-4a9b-a2d6-330ba46d68dc

### Steps to reproduce

GIVEN I have scanned a MMM Request Payment QR code for 1 Link
WHEN scanning is successful
THEN scanning device navigates to Confirm screen for sending assets
AND correct asset to received is shown
AND correct asset balance to receive is shown
AND correct estimated gas fee is shown (FAIL: gas fee is extremely high)

### Version

7.20.0

### Build type

None

### Device

Any

### Operating system

iOS, Android

**Comment by digiwand** [comment]
From Confirmation Secure UX discussion:
- high gas fee is expected when account has insufficient balance
- it is expected the transaction will fail with the high gas fee + insufficient balance
- we should expect mobile to behave similarly to extension and display an alert for this case

Action Item:
- display alert banner when account has insufficient funds

**Comment by digiwand** [comment]
possibly related: https://github.com/MetaMask/metamask-mobile/pull/8866

**Comment by digiwand** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Confirmations-Secure-UX-6245e6e2348677001213b8d2/issues/MetaMask/metamask-mobile/9117?planning-poker) with Zenhub @cryptotavares @pedronfigueiredo @segun

**Comment by digiwand** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Confirmations-Secure-UX-6245e6e2348677001213b8d2/issues/MetaMask/metamask-mobile/9117?planning-poker) with Zenhub @blackdevelopa @jpuri
