### ISSUE TITLE
[Bug]: View: Root TypeError: undefined is not an object (evaluating 't.toLowerCase')

### ISSUE THREAD

**Issue by Deamaniging** [MetaMask/metamask-mobile#9126]
### Describe the bug

Metamask allows me to login using my face ID or password, acknowledges when my password is entered incorrectly or not with capital/non capital letters, but won't load any accounts. Stuck on a loading screen, shows there's no accounts, doesn't let me do any transactional things like swap etc as it doesn't identify any account, and also won't let me pull my SRP or passkey because it shows up with an error, images attached. I tried updating, restarting phone etc. 

I'm now worried that if I ever have anything happen to the app in the state it's in (Being password protected) I'll lose access to my account for good.

![thumbnail_image0](https://github.com/MetaMask/metamask-mobile/assets/165962336/e77db010-b31d-43a0-9191-b3558b1bc350)
![download](https://github.com/MetaMask/metamask-mobile/assets/165962336/ab824ba3-7d6e-4d01-b9f7-51d75f8b08b1)

### Steps to reproduce

Just by logging in. Was working the night before, stopped working the next morning out of the blue. I used biometrics to login usually, then I went into the app and once the problems kept occurring I turned off biometrics in my settings. 

It kept this update as now I can only login with my PW moving forward, and can't turn face ID back on, but that's the only modification it seemed to have saved.

### Version

7.19.0(1292)

### Build type

None

### Device

Iphone 13 pro max

### Operating system

iOS

### Severity

Highly impactful, I have no other way of accessing my port :/...

**Comment by gauthierpetetin** [comment]
Hi [Deamaniging](https://github.com/Deamaniging), thanks for reporting this, it's a known issue we've been trying to fix for some time already. Here's where we track the resolution: https://github.com/MetaMask/metamask-mobile/issues/7365

**Comment by gauthierpetetin** [comment]
Closing as duplicate
