### ISSUE TITLE
[Bug]: Not able to delete MetaMetrics data

### ISSUE THREAD

**Issue by chrisleewilcox** [MetaMask/metamask-mobile#9152]
### Describe the bug

In Settings > Security & Privacy when I tap Delete MetaMetrics data button and I tap Clear on the alert message I get an error indicating not able to delete metrics data.

Was able to reproduce in 7.19.0.
Not able to reproduce with 7.18.0.

### Expected behavior

I should be able to delete metametrics data.

### Screenshots/Recordings

https://github.com/MetaMask/metamask-mobile/assets/6626407/b1eaedd8-d7fa-42de-a1ca-3aa52f26b58d

### Steps to reproduce

GIVEN I am on Settings > Security & Privacy screen
WHEN I delete MetaMetrics
THEN MetaMetrics is deleted (FAIL: metrics not deleted, alert with error message is displayed)

### Version

7.20.0 --> 7.24

### Build type

None

### Device

Any

### Operating system

iOS, Android

**Comment by gauthierpetetin** [comment]
The proxy url stored in Bitrise secrets was using `http` protocol instead of `https`, which broke this feature.
This is now fixed and will be released as part of v7.24.1 hot fix.
