### ISSUE TITLE
[Bug]: V7.19.0: Invalid parameters: must provide a permitted Ethereum address.

### ISSUE THREAD

**Issue by monkjuice** [MetaMask/metamask-mobile#9164]
### Describe the bug

When trying to request to sign a message we are getting back the error message:

Invalid parameters: must provide a permitted Ethereum address.

It looks like this was introduced with this commit at this line:

https://github.com/MetaMask/metamask-mobile/commit/386d9be1b0a450fef82ed06cc29a394235b5e54f#diff-5f97a8db92c37dcdf7a575d4e7226b84e0dca1719f9c906fdcf59faae0cbb092R138

```
        if (accounts.length > 0) {
          // Permissions issue --- requesting incorrect address
          throw ethErrors.rpc.invalidParams({
            message: `Invalid parameters: must provide a permitted Ethereum address.`,
          });
        }
```

Steps to reproduce:

Send the rpc request: https://docs.metamask.io/wallet/reference/personal_sign/ with a valid address to a connected account

### Expected behavior

Before v7.19.0 we were correctly getting a request to sign on the end-users phone and thus receiving the signed message when the user signed.

### Steps to reproduce

1) Authorize a connection via WalletConnect

2) Send the RPC request: https://docs.metamask.io/wallet/reference/personal_sign/ to a connected account

**Note:** We are sending this request via WalletConnect. It might be useful to know.

### Error messages or log output

```shell
Invalid parameters: must provide a permitted Ethereum address.
```

### Version

7.19.0

### Build type

None

### Device

Tested on Ios and Android

### Operating system

iOS & Android

### Additional context

Adding some additional context: 

We are keeping Wallet Connect V1 alive through our bridge server. Given that we are one of the few SDK's that support WalletConnect for game engines like Unity and Unreal we feel like it's really valuable for the ecosystem. We've been working on migrating to WalletConnect V2 for the past few months but we are not yet there. As you may imagine there are a lot of hard to solve problems when trying to make Wallet Connect V2 work in C++. 
During this time we were able to find workarounds the V1 deprecation, but this looks like a hard barrier for us. 

Our sdk:
https://www.unrealengine.com/marketplace/en-US/product/emergence
https://assetstore.unity.com/packages/decentralization/infrastructure/emergence-sdk-252187

### Severity

This is impacting our entire user base given that we rely on this method for signing in.

**Comment by monkjuice** [comment]
Edit: It looks like the issue is related to WalletConnect V1. Added some info on Additional context

**Comment by christopherferreira9** [comment]
Hi @monkjuice ! Thank you for reporting! 
Unfortunately, with the sunset of WalletConnect v1 we also stopped supporting that protocol and I wasn't able to reproduce this issue in V2.
Although, the implementation of WalletConnect v2 has been done a few versions before 7.19.0 so it seems to be related to the permission system itself. Will check internally with the team to see if we manage to find a way to accommodate this.

**Comment by christopherferreira9** [comment]
Hi @monkjuice ! After trying to use your demo it seems that it needs Goerli to work. Please keep in mind that Goerli is getting [deprecated](https://blog.ethereum.org/2023/11/30/goerli-lts-update) and the next Wallet version will no longer support it.

**Comment by christopherferreira9** [comment]
Hi hi! 
We've pin pointed the root cause for this issue which is related to WalletConnect v1 and unfortunately we can't maintain it anymore even though we tried our best to keep backward compatibility as long as possible.
We're very sorry for the inconvenience.

**Comment by monkjuice** [comment]
@christopherferreira9 We have been working around the clock since last Monday, in order to wrap up the V1->V2 migration. And the WalletConnect team has been really helpful with us. 

But we have now hit this hard barrier. We would really appreciate some help here. In the meantime, we are also reviewing metamask-mobile's source code to see if we can help with a pull request to address this problem.

**Comment by monkjuice** [comment]
It's actually related to this issue:

https://github.com/MetaMask/metamask-mobile/issues/9232

**Comment by christopherferreira9** [comment]
Hi! The delays you're experiencing are known and have been improved in https://github.com/MetaMask/metamask-mobile/pull/9150 and https://github.com/MetaMask/metamask-mobile/pull/9188 and will be released with the version currently being tested.
