### ISSUE TITLE
URI format for clicking links to make payments

### ISSUE THREAD

**Issue by jjs2484** [MetaMask/metamask-mobile#917]
Hi,

On android the following URI format successfully opens the wallet and fills out the address field but fails to fill out the amount field... Is this something that will be fixed in the future? Or is there another URI format being utilized?

`<a href="ethereum:0x4A7f51F4c9AD183bdfD1A43cd6CeF4ef8c73788c?amount=0.00720891">Pay ETH</a>`

**Comment by brunobar79** [comment]
Hey there! We’re supporting the standard ERC-681 ( https://github.com/ethereum/EIPs/blob/master/EIPS/eip-681.md) where the value needs to be expressed in wei.

Here’s the relevant part:

```

The amount is specified in value parameter, in the atomic unit (i.e. Wei). The use of scientific notation is strongly encouraged. For example, requesting 2.014 ETH to address 0xfb6916095ca1df60bb79Ce92ce3ea74c37c5d359 would look as follows: ethereum:0xfb6916095ca1df60bb79Ce92ce3ea74c37c5d359?value=2.014e18

```

By looking at your example you’re missing `e18’ at the end of the value
