### ISSUE TITLE
[Bug]: Address connected with the D-App return wrong value

### ISSUE THREAD

**Issue by trimn-1012** [MetaMask/metamask-mobile#9170]
### Describe the bug

When I connect metamask with D-App in the browser of metamask then the wallet address return for D-App is the wallet address previously connected to D-App. But when I sign message then signature return is the signature of current address.

### Expected behavior

The wallet address connected will return the current address.

### Screenshots/Recordings

https://github.com/MetaMask/metamask-mobile/assets/64879807/b79532c6-9ac4-4423-9f0d-38de80957f34

### Steps to reproduce

1. Go to https://stackblitz.com/edit/stackblitz-starters-szudyw?file=src%2Fpages%2Findex.tsx and clone it to run localhost.
2. Click on the Metamask button and connect with other account.
3. You can see wallet address displayed (wallet address previously connected) and compare with account have choose to connect. The 2 accounts are different.
4. Click on the Sign message button and click sign on the metamask popup.
5. The signature and wallet address displayed. You can see wallet address is the current address you have choose at step 2.
6. If the first time you check and it not have problems. Please help me click on disconnect button and execute again from step 2 to step 5.

### Version

7.19.0

### Build type

None

### Device

Iphone 11 pro IOS version: 17.3

### Operating system

iOS, Android

**Comment by ZbrancaI** [comment]
Hey, @trimn-1012! Thank you for reporting this! Does this issue occur only regarding this dApp, or have you experienced this issue with other dApps as well?

**Comment by trimn-1012** [comment]
> Hey, @trimn-1012! Thank you for reporting this! Does this issue occur only regarding this dApp, or have you experienced this issue with other dApps as well?

@ZbrancaI I encountered this issue in my app but my app is not published yet so I can't show it to you, so now I create a demo so that everyone can investigate and fix it together 🙇🏼
