### ISSUE TITLE
Allow to use http://your_local_ip for development

### ISSUE THREAD

**Issue by rstormsf** [MetaMask/metamask-mobile#923]
If I try to open http://192.168.1.10:3000 it says

ERR_CLEARTEXT_NOT_PERMITTED

Here it explains how to fix it
https://github.com/flutter/flutter/issues/30368

OS: Android

**Comment by rstormsf** [comment]
I also wasn't able to open website with self-signed ssl certificate

**Comment by danfinlay** [comment]
Related to #260. HTTPS requirement was added in response to a security audit, but is not developer friendly. We need to at least allow a bypass of this restriction.

**Comment by danfinlay** [comment]
Oh I actually meant #839.

**Comment by jrainville** [comment]
I second the need for this.
I was trying to debug my Dapp on a local network on Metamask mobile but couldn't because of `ERR_CLEARTEXT_NOT_PERMITTED`

**Comment by gcoban** [comment]
I am facing the same issue, we need an option for developers.

**Comment by pi0neerpat** [comment]
Can we increase priority for this issue? This is a huge blocker for MM mobile development, and over a year old.

**Comment by EtDu** [comment]
As of now, MM mobile can connect to webpages with LAN IPs such as a dev server running on `localhost` on a computer connected to the same wifi as the phone. Works on iOS & Android phones.

1) Find the local IP of the machine running the dev server
2) instead of `localhost`, use `0.0.0.0` to run the server, example:
For webpack, specify `devServer.host` in the config:
`devServer: {
    host: '0.0.0.0',
    contentBase: DIST,
    port: 9011,
    writeToDisk: true,
  },`
3) In MM mobile browser, head to `http://LOCALIP:PORT`
4) Profit

**Comment by pi0neerpat** [comment]
> As of now

I just checked and still doesn't work. Is this in a recent update? What version do I need?

**Comment by EtDu** [comment]
@pi0neerpat that version should work. Could you please post some screenshots? Also, make sure your dev server isn't listening on `localhost`, but on `0.0.0.0` or the computer's local IP. It doesn't work with `localhost`

**Comment by pi0neerpat** [comment]
I've always been using the `-H` flag. I'm running  `gatsby develop -H 0.0.0.0` in a VM. Then from the host machine, or any device on my network, I can see my app at `http://192.168.1.213:9000/`.

with `http` I get

with `https` I get

**Comment by EtDu** [comment]
Upon further investigation, I'm encountering this error when I use an android simulator, but not when I use an actual device. Looking into it.

**Comment by EtDu** [comment]
MetaMask/metamask-docs#169

**Comment by ArinCantCode** [comment]
Encountered this today:

- [x] Running on machine's local IP address 192.168.x.x 
- [x] Added xip.io when accessing the page as instructed `http://192.168.x.x.xip.io:5000`
- [x] I'm able to access `http://192.168.x.x.xip.io:5000` from my PC browser and mobile firefox
- [x] I'm using android

**Comment by EtDu** [comment]
@ArinCantCode Are you getting `CLEARTEXT_NOT_PERMITTED`?

**Comment by Neozaru** [comment]
Can we update the doc https://docs.metamask.io/guide/mobile-best-practices.html#website-testing-and-debugging
The doc mentions `http://192.168.x.x.xip.io:8000` with absolutely no context given and one has to figure out what we are trying to do here.
![image](https://user-images.githubusercontent.com/1905292/134362776-67f9a901-a12d-45fe-ae82-da276ef1df9c.png)
Could benefit from updating the URL as well as giving a bit more detail

**Comment by metadan** [comment]
This is still an issue v4.1.0 - can't connect to local network ip non-ssl. I get the ERR_CLEARTEXT...
OS Android 11

**Comment by Neozaru** [comment]
> Can we update the doc https://docs.metamask.io/guide/mobile-best-practices.html#website-testing-and-debugging The doc mentions `http://192.168.x.x.xip.io:8000` with absolutely no context given and one has to figure out what we are trying to do here. ![image](https://user-images.githubusercontent.com/1905292/134362776-67f9a901-a12d-45fe-ae82-da276ef1df9c.png) Could benefit from updating the URL as well as giving a bit more detail

Somebody has again sneakily updated the docs and changed the recommended URL.
Please make it clearer that `sslip` in whitelisted in a manifest to allow this specific domain and that others won't want (https://github.com/MetaMask/metamask-mobile/blob/cafc79d6c51e22caffda28b24711285a5ecc253a/android/app/src/main/res/xml/react_native_config.xml -> switch branch/tag once you are on this file to see which URL is supposed to work for your version)

**Comment by Threnos** [comment]
Only this conversation helped me to resolve an issue, that has not a single word about in docs.
I was able to access `192.168.x.x.sslip.io:port` from Metamask app's browser. Finally I can access a local dev environment from my android phone.

**Comment by jmynes** [comment]
The documentation link in this thread is outdated:
https://docs.metamask.io/wallet/how-to/use-sdk/#website-testing-and-debugging

I browsed to `192.168.x.x.sslip.io:port` without any additional configuration, and that worked, but this is an incredibly obscure workaround it seems, and I did not arrive to this conclusion by googling, but rather by going to this repo, and searching through at least 6 issues, mostly closed ones, and with multiple different search terms.
