### ISSUE TITLE
[Bug]: WalletConnect aftering using switch chain, and request another signature and android metamask seemed nothing happened.

### ISSUE THREAD

**Issue by Stephen-Song** [MetaMask/metamask-mobile#9232]
### Describe the bug

I am in Android client. I use walletConnect to switch chains. After the switch is completed, I re-initiate a signature behavior. Metamask does not respond after jumping to metamask. At the same time, the ios client performs the above operation and responds after 30 seconds.

### Steps to reproduce

1. use Android metamask
2. switch to 137 from 1
3. request personal signature
4. jump to metamask
5. expected metamask modal to show details and comfirm but in fact nothing shows up.

### Error messages or log output

```shell
not any error message
```

### Version

7.19.1(1306)

### Build type

None

### Device

google pixel 6

### Operating system

Android

**Comment by marctatham** [comment]
Can confirm that I'm observing the same behaviour. Other wallets seem to be behaving correctly, having tested on Rainbow & Trust wallets without issue, this appears to be a Metamas-specific issue as far as I can tell. 

I wonder if [this](https://github.com/MetaMask/metamask-mobile/issues/9096) is in-actual fact a duplicate, given that this is a hybrid React Native application that is simply affecting Android and iOS dApps equally.

**Comment by marctatham** [comment]
I'll say that I observed the following error in the logs:`Invalid parameters: must provide an Ethereum address.`

Which leads me to think that _perhaps_ this is a case of WalletConnect not passing the `account` in properly via the `Sign.Params.Request` in when interacting with Metamask's API:  https://metamask.github.io/api-playground/api-documentation/#personal_sign

But this is just speculation as I'm not familiar with relevant WalletConnect, nor Metamask source code, just sharing in case it's of value. I also wouldn't be surprised if the socket connection API has no bearing whatsoever on the metamask API 🤷

**Comment by Stephen-Song** [comment]
> I'll say that I observed the following error in the logs:`Invalid parameters: must provide an Ethereum address.`
> 
> Which leads me to think that _perhaps_ this is a case of WalletConnect not passing the `account` in properly via the `Sign.Params.Request` in when interacting with Metamask's API: https://metamask.github.io/api-playground/api-documentation/#personal_sign
> 
> But this is just speculation as I'm not familiar with relevant WalletConnect, nor Metamask source code, just sharing in case it's of value. I also wouldn't be surprised if the socket connection API has no bearing whatsoever on the metamask API 🤷

@marctatham  Thanks for replying. I am familiar with some parameter information about Ethereum's signatures and transactions. I am very sure that there is no problem with the parameters I passed, and before switching chains, the metamask can pop up the modal for transactions and signature operations normally on the previous chain. , so I guess metamask will handle it incorrectly when accepting the incoming chainId after switching, resulting in the modal being unable to pop up.

**Comment by christopherferreira9** [comment]
Hi all! The delays you're experiencing are known and have been improved in https://github.com/MetaMask/metamask-mobile/pull/9150 and https://github.com/MetaMask/metamask-mobile/pull/9188 and will be released with the version currently being tested.

**Comment by christopherferreira9** [comment]
Hi! `7.21.0` is right around the corner so I'll be closing this issue. If you still experience issues with this please feel free to open a new issue.
