### ISSUE TITLE
[Bug]: Not able to send assets with Keystone HW account, Transaction error shown on Confirm screen

### ISSUE THREAD

**Issue by chenlocus** [MetaMask/metamask-mobile#9235]
### Describe the bug

This bug was raised up: https://github.com/MetaMask/metamask-mobile/issues/9108
However, it happens again in the latest metamask version in Android.

### Expected behavior

populate a QR code for HW wallet to scan.

### Screenshots/Recordings

 Transaction error, CBOR encoding not supported.
![image](https://github.com/MetaMask/metamask-mobile/assets/15951769/0f29e658-ec76-4d3e-85f2-a63d8be56643)

### Steps to reproduce

Scenario: Send using HW account
GIVEN I have Sepolia Test Network selected
AND I have hardware wallet account selected
WHEN I send assets
THEN assets are successfully sent (FAIL: error shown on Confirm screen)
AND send transaction is properly shown on all transactions screen

Scenario: Send asset using HW account with not enough asset balance
GIVEN I have Ethereum Main Network selected
AND I have hardware wallet account selected
WHEN I send assets
AND I make it to the Confirm screen
AND I send assets
THEN error message is shown on Amount screen
AND error message matches error message for non-hardware wallet account selected (FAIL: "CBOR encoding..." error, see screenshot)

### Version

7.19.1 (1306)

### Build type

None

### Device

Google pixel 7a

### Operating system

Android

### Severity

severe, block.

**Comment by angelcheung22** [comment]
Hi @chenlocus thanks for your report, as the issue has been fixed with PR #9185 and pending for just release for v7.20. Please retest upgrade to the new release.
