### ISSUE TITLE
[Bug]: app closes when tapping portfolio button on wallet view

### ISSUE THREAD

**Issue by chrisleewilcox** [MetaMask/metamask-mobile#9242]
### Describe the bug

Tapping the portfolio button on wallet view closes the app for both iOS and Android.

Comms: https://consensys.slack.com/archives/C02U025CVU4/p1713171912524269

### Expected behavior

After tapping the portfolio button on wallet view the app should navigate to the browser and open a browser tab to portfolio webapp.

### Screenshots/Recordings

See convo here: https://consensys.slack.com/archives/C02U025CVU4/p1713171912524269

### Steps to reproduce

GIVEN I am on wallet view
WHEN I tap portfolio
THEN app navigates to browser view
AND browser tab is open to portfolio app
AND browser tab will connect wallet a current session is still active
BUT browser tab will not connect wallet if there is no active session with portfolio

### Version

7.21.0

### Build type

None

### Device

Any

### Operating system

iOS, Android

### Severity

Sev1

**Comment by ameliejyc** [comment]
PR fix in progress: https://github.com/MetaMask/metamask-mobile/pull/9243
