### ISSUE TITLE
[Bug]: tapping stake in token list on wallet view opens "undefined" in browser

### ISSUE THREAD

**Issue by chrisleewilcox** [MetaMask/metamask-mobile#9244]
### Describe the bug

Tapping on stake link for a token on wallet view navigates browser to "undefined" URL.

See convo: https://consensys.slack.com/archives/C02U025CVU4/p1713171912524269

### Expected behavior

After tapping stake app navigates browser to stake page??? (need stake team to confirm expected behavior).

### Screenshots/Recordings

See convo: https://consensys.slack.com/archives/C02U025CVU4/p1713171912524269

### Steps to reproduce

Needs proper specs on functionality.

### Version

7.21.0

### Build type

None

### Device

Any

### Operating system

iOS, Android

### Severity

Sev1

**Comment by ameliejyc** [comment]
Hi Chris, the expected Portfolio Stake page is: https://portfolio.metamask.io/stake?metamaskEntry=mobile
