### ISSUE TITLE
[Bug]: PPOM - WalletConnect SIWE/Personal Sigm signature triggers`Error validating JSON RPC using PPOM: Error: invalid type: map, expected a sequence at line 1 column 831`

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-mobile#9245]
### Describe the bug

Whenever I trigger a WalletConnect SIWE signature I get the following error `Error validating JSON RPC using PPOM: Error: invalid type: map, expected a sequence at line 1 column 831` and PPOM fails to validate that signature.

### Expected behavior

It was working in 7.20 but not in current develop.
However, I believe we shouldn't validate SIWE signatures at all? cc @bschorchit 

### Screenshots/Recordings

![Screenshot from 2024-04-15 18-41-09](https://github.com/MetaMask/metamask-mobile/assets/54408225/5ec55cb8-4675-4403-a08f-fd4e3e043f04)

https://github.com/MetaMask/metamask-mobile/assets/54408225/515a1ad6-a5a2-49df-9144-2903adf62f12

### Steps to reproduce

1. Go to the test dapp
2. Click Wallet Connect
3. Scan the QR code with the phone
4. Trigger SIWE signature

### Version

develop (7.21), not happening in 7.20

### Build type

None

### Device

Pixel 6

### Operating system

Android

**Comment by bschorchit** [comment]
Yes, we can skip validating SIWE

**Comment by jpuri** [comment]
As part of this task I can skip validation for SIWE in mobile and I will create a corresponding task for extension.

**Comment by jpuri** [comment]
`siwe` detection method using controller-utils `detectSIWE` is failing in latest code. It is preventing completing this task.

**Comment by bschorchit** [comment]
Closing as this has been solved with this PR https://github.com/MetaMask/metamask-mobile/pull/9842
