### ISSUE TITLE
[Bug]: Signatures - Triggering Sign Typed Data signature returns `Error: "JSON Parse error: Unexpected token: x","data":{"originalError":{}}}`

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-mobile#9248]
### Describe the bug

Whenever we trigger the Typed Data Signature with Wallet Connect, we get the following error `Result: Error: {"code":-32603,"message":"JSON Parse error: Unexpected token: x","data":{"originalError":{}}}`.

This only happens if we use Wallet Connect, but the signature works fine if using the in-browser.

Notice: this issue is now hidden by [this other erro](https://github.com/MetaMask/metamask-mobile/issues/9246)r, so in order to reproduce it, you can use the 7.20 prod version

### Screenshots/Recordings

https://github.com/MetaMask/metamask-mobile/assets/54408225/e6679973-0d69-4c4c-89f3-a7f4b14bc77b

### Steps to reproduce

1. Go to the test dapp in the computer browser
2. Connect Mobile device by scanning the Wallet Connect QR code
3. Trigger the Sign Typed Data signature

### Version

7.20 prod

### Build type

None

### Device

Pixel 6

### Operating system

Android

**Comment by HavenCTO** [comment]
This is still an issue not sure why it's not planned. Here is my code that is having issues with eip-712 signing in-app https://github.com/Haven-hvn/haven-mobile/blob/cfcf9d3558c1417aab4a6721cba03cf7239d8a37/mobile-app/core-wallet/src/main/kotlin/haven/mobile/core/wallet/WalletSessionImpl.kt#L333-L342
