### ISSUE TITLE
[Bug]: app very slow and sluggish when switching networks especially on android

### ISSUE THREAD

**Issue by chrisleewilcox** [MetaMask/metamask-mobile#9249]
### Describe the bug

Switching networks is noticeably slow and sluggish in the app.  Essentially all steps can be very slow to execute when switching networks.  It's especially slow when switching networks on android.

Physical device: Samsung A42 Android 13
iPhone 12 iOS 17.4

Wallet setup:
- 3 wallet accounts
- 1 imported account
- 1 imported ENS account (notice that ENS accounts in the wallet seem to contribute to slowness)
- 2 hw accounts

### Expected behavior

Switching networks should be very responsive.

### Screenshots/Recordings

https://github.com/MetaMask/metamask-mobile/assets/6626407/948ecc28-f704-4f51-99ab-35384a77fe22

### Steps to reproduce

GIVEN I am on wallet view
WHEN I tap network drop-down (randomly very slow to display select network modal)
AND I tap network to select (randomly very slow to switch to network and select network modal goes away)
THEN wallet view is displayed (randomly wallet view is shaded before for awhile before I can tap or interact)
AND I can immediately tap or interact with wallet view (randomly very slow when I tap a component on wallet view)

### Version

7.21.0

### Build type

None

### Device

Any

### Operating system

iOS, Android

**Comment by sleepytanya** [comment]
Same problem with the 7.22.0, Samsung s24+, Android 14:


https://github.com/MetaMask/metamask-mobile/assets/104780023/5d52d5f6-fbf6-4f0c-a564-983eb71ac4b6

**Comment by frankvonhoven** [comment]
5/16/24 - Noticed that calls to non-mainnet networks when switching were failing for me. The id was undefined in the url. The calls would repeatedly be retried. So when switching to another network and it failed, now there were 2 repeatedly failing calls, like every second. Switch again and now there’s 3 calls in the queue like every second. And so on…
For one network we hardcoded the id into the url but it was still showing as undefined in the network call, and the call was still failing and repeating.

So
1) Failed network calls aren’t failing gracefully or timing out
2) for some reason my network ids were undefined, leading to 401s

5/20/24 - After more debugging with Tomas:
1. noticed that multiple calls are being made per Account in wallet when switching networks (4 accounts === 4 calls) - this can be disabled in security settings > batch network calls OFF
2. calls are happening repeatedly with the app just sitting idle on the WalletView
3. Traced it to `useAccounts()` hook being used multiple places and possibly triggering multiple renders --> multiple calls





Frank von Hoven
  [13 hours ago](https://consensys.slack.com/archives/C02U025CVU4/p1716217227899999?thread_ts=1715952207.276739&cid=C02U025CVU4)
You can test it by in Flipper’s Network tab, and just change networks to see the calls. There’s a ton of calls happening every second idk why

**Comment by tommasini** [comment]
Moving this to closed since It was merged a [PR](https://github.com/MetaMask/metamask-mobile/pull/9721) to improve performance

Not sure if we should close it or remain it open @gauthierpetetin

**Comment by gauthierpetetin** [comment]
Sounds good, thanks @tommasini
