### ISSUE TITLE
Crash: Fatal Exception: RCTFatalException: Error calling JSTimers.callTimers Unhandled JS Exception: undefined no stack

### ISSUE THREAD

**Issue by brunobar79** [MetaMask/metamask-mobile#925]
Can be related to BG timers: https://fabric.io/metamask/ios/apps/io.metamask.metamask/issues/5c941e69f8b88c296304614b/sessions/df7c3326bf1446c1b9b86a9fac12c2c3_DNE_0_v2?

**Comment by EtDu** [comment]
Closing, no more fabric & issue doesn't seem to be relevant anymore
