### ISSUE TITLE
[Bug]: Connection Modal - Incorrect URL displayed in the Connectg Account modal when using the in-browser

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-mobile#9259]
### Describe the bug

Whenever I am trying to connect to a site, I can see how the domain URL is pointing to the previous page URL instead of the current one.
[Update] this seems to be related to a previous session with WC, where I was connected to the test-dapp, which is the URL displayed instead of the current one

### Screenshots/Recordings

https://github.com/MetaMask/metamask-mobile/assets/54408225/3d4fdc16-b43c-4e76-9b8e-456ca45367e6

### Steps to reproduce

1. Go to the test dapp with your computer
2. Click Wallet Connect button
3. Scan the QR code with your MM ph
4. Now to another site ie https://app.uniswap.org/swap
5. Connect MM
6. See Connect modal is pointing to the test dapp URL

### Version

7.20 prod

### Build type

None

### Device

Pixel 6

### Operating system

Android

**Comment by christopherferreira9** [comment]
fixed by https://github.com/MetaMask/metamask-mobile/pull/9284
