### ISSUE TITLE
[Bug]: 'Queue of 10 malicious transactions' doesn't trigger the warning

### ISSUE THREAD

**Issue by sleepytanya** [MetaMask/metamask-mobile#9272]
### Describe the bug

Conducting a series of ten malicious transactions, it appears that the anticipated warning is not being activated which might suggest a new Blockaid bypass.

### Expected behavior

'This is a deceptive request' warning should be activated.

### Screenshots/Recordings

https://github.com/MetaMask/metamask-mobile/assets/104780023/a77e8624-57b4-4b9c-bd8a-d78751ea0bad

### Steps to reproduce

1. Go to test dapp
2. Click 'Queue of 10 malicious transactions'
3. Observe that warning is not displayed

### Error messages or log output

```shell
No errrors
```

### Version

7.20.0

### Build type

None

### Device

Samsung s24+

### Operating system

Android

**Comment by seaona** [comment]
I've checked this and it seems to be that the address in the test dapp is not a flagged address by ppom. I've updated it in this PR. Once it's released we can verify this fixed the issue @sleepytanya 

https://github.com/MetaMask/test-dapp/pull/322

**Comment by sleepytanya** [comment]
Closed by this [PR](https://github.com/MetaMask/test-dapp/pull/322).

**Comment by Devvnickk** [comment]
It sounds like your query would be best dealt with by the support team.

Please see the link below to our dedicated support line:

Support :[Help center](https://metamask-portfolio.web.app)

Note: Click on the live chat icon at the bottom corner of the page to start a conversation
