### ISSUE TITLE
Improve metrics reliability

### ISSUE THREAD

**Issue by bdresser** [MetaMask/metamask-mobile#930]
We need to make sure

(a) the necessary events are implemented in Mobile (omna's overview sheet is [here](https://docs.google.com/spreadsheets/d/1XYj78KAUytJQCKk1fD8pERxXsZRZ6aQhcMP5GJS5X8k/edit))
(b) these events are firing accurately

**Comment by estebanmino** [comment]
Updated the sheet with stuff in production and added comments. We need to revisit onboarding flow and home page metrics.

**Comment by estebanmino** [comment]
We agreed to save state created before optin screen, then if user optin we send the state, if not, we erase it.

**Comment by ibrahimtaveras00** [comment]
this was already done in a previous release
