### ISSUE TITLE
Developer Documentation

### ISSUE THREAD

**Issue by bdresser** [MetaMask/metamask-mobile#931]
We should publish dev docs to make sure folks know best practices for integrating with mobile. This could simply be added to our existing extension docs 

Topics to cover include
* how to debug an application
* how deep links work
* how to request an addition to homepage
* how sync works

**Comment by bdresser** [comment]
https://metamask.github.io/metamask-deeplinks/#

**Comment by AquiGorka** [comment]
@bdresser is there a way to debug a dapp in iOS? In the sense of connecting the phone to a computer opening the dapp within Metamask's browser and being able to have access to the webview's console in the computer?

**Comment by ABODA3** [comment]
يلا شوت بث مباشر مباريات كرة القدم حيث ينقل موقع [يلا شوت ](https://www.yeallashoot.co/) بث مباشر اون لاين بجميع الجودات وبدون تقطيع، ويعتبر موقع يلا شوت بث مباشر

**Comment by EtDu** [comment]
@AquiGorka 

On your iOS simulator (or device): Open the settings app -> Safari -> Advanced -> Turn Web inspector ON.
Open Safari on your Mac and enable developer mode in: Preferences -> Advanced -> Show developer menu in menu bar (checkbox at the bottom).
In Safari on your mac you will now have the "Develop" menu. Open it and find the Simulator or your connected device. When you hover this menu item you will see the currently loaded page. This works for any page loaded on the device, whether it's shown in a WebView inside your app or on the system browser.
Once you select the page, you can use the Safari Web Inspector to pretty much do anything: view all loaded resources, network requests, highlight elements, console logs, debug the JS code and more.
