### ISSUE TITLE
[Bug]: dapp connect modal not showing

### ISSUE THREAD

**Issue by chrisleewilcox** [MetaMask/metamask-mobile#9319]
### Describe the bug

Using deep link [tests app](https://cortisiko.github.io/) in device browser (Chrome) after tapping "Dapp connect Warning" deeplink my device switches to mobile app but the dapp connect modal never shows up.

### Expected behavior

After tapping "Dapp connect warning" the mobile app should launch if not already opened and be fore-fronted and the dapp connect modal should briefly display to simulate connecting to a dapp.

### Screenshots/Recordings

https://github.com/MetaMask/metamask-mobile/assets/6626407/6067a374-46f1-4d1e-8f0b-6b0b88f3b8ce

### Steps to reproduce

GIVEN I am using device browser
AND in browser I have https://cortisiko.github.io/ open
WHEN I tap "Dapp connect Warning"
THEN mobile app should be fore-fronted
AND dapp connect modal is displayed in mobile app (FAIL: modal is not displayed)

### Version

7.21.0

### Build type

None

### Device

Any

### Operating system

iOS, Android

**Comment by christopherferreira9** [comment]
This no longer applicable since the SDK connect feature is available since version `5.8`.
