### ISSUE TITLE
Enable DOM Storage in the WebView?

### ISSUE THREAD

**Issue by Canada77** [MetaMask/metamask-mobile#932]
The front-end of my dapp is not displaying properly despite working on all mobile browsers. I managed to reproduce the issue with a bare-bones Android WebView app. The fix was to set ```setDomStorageEnabled``` to ```true``` for the web view. Would it be possible to please implement this?

**Comment by brunobar79** [comment]
We already have that setting enabled. See: https://github.com/brunobar79/react-native-web3-webview/blob/master/android/src/main/java/com/web3webview/Web3WebviewManager.java#L564

Might be something else. Have you tried [connecting to Chrome's remote debugger](https://developers.google.com/web/tools/chrome-devtools/remote-debugging/webviews)? 

There could be other issue in the console that might be useful.

**Comment by Canada77** [comment]
Oh darn, ok. Thank you for the remote debugger suggestion. I just spent a few hours playing around with it and unfortunately I am now more stumped than when I started. My only thought at this point is that it is some issue with my styles but I'm really not sure what. I will keep looking at it and open a new issue if I have another lead. Thanks again.
