### ISSUE TITLE
[Bug]: Notifications - When enabling notifications, MM breaks with error `MMKV::set: 'value' argument is not of type bool,number, string or buffer!`

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-mobile#9366]
### Describe the bug

When I enable the notifications, I get the error `MMKV::set: 'value' argument is not of type bool,number, string or buffer!`

### Screenshots/Recordings

![screencap-2024-04-23T084202 294Z](https://github.com/MetaMask/metamask-mobile/assets/54408225/9d8d9d82-e3b5-4128-9b8b-5f6e75aec3f1)

https://github.com/MetaMask/metamask-mobile/assets/54408225/0f866550-c04e-484b-89bf-563e9aa15bb8

### Steps to reproduce

1. Go to home
2. Click the bell on top menu
3. Enable notifications

### Version

main branch

### Build type

None

### Device

Pixel 6

### Operating system

Android

**Comment by Jonathansoufer** [comment]
Ok, so on main we have access to notifications but no bug as this one is shown, so I'm wondering from which branch is this coming from. In any case, based on main, I created [this PR](https://github.com/MetaMask/metamask-mobile/pull/9406) to hide notifications under feature flag.

**Comment by Prithpal-Sooriya** [comment]
From discussion this is not on any released version, just on main.

So no major issues here.

Will tag your PR on this bug
