### ISSUE TITLE
[Bug]: PPOM - Error validating `Cannot read properties of undefined (reading '__wbindgen_malloc)`

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-mobile#9367]
### Describe the bug

Whenever I was trying to deploy a contract, I got the error `Error validating JSON RPC using PPOM: Error: Cannot read properties of undefined (reading '__wbindgen_malloc` and the `Request may not be safe` warning.

- Note: this seem to affect all transactions and signatures and all networks. Even after switching networks I still see the same error
- Note2: the issue was gone after quitting the app and re-starting it again

### Screenshots/Recordings

![screencap-2024-04-23T090358 534Z](https://github.com/MetaMask/metamask-mobile/assets/54408225/2d806d92-2a1b-43b9-9e04-a5706f97e8b8)

https://github.com/MetaMask/metamask-mobile/assets/54408225/ae97ed4e-b768-4adc-85cc-04e4637837b6

### Steps to reproduce

1. Go to the test dapp
2. Click Deploy ERC20 token
3. See error and `Request may not be safe` warning

### Version

main branch (possibly earlier)

### Build type

None

### Device

Pixel 6

### Operating system

Android

**Comment by jpuri** [comment]
Closing the issue as it is not replicating any more.
