### ISSUE TITLE
[Bug]: Gas - New gas values are saved even without clicking Save on the preferences

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-mobile#9369]
### Describe the bug

Whenever I am performing a transaction, if I click Edit gas and change its values, if I don't click Save but just the return button, I see how the new values were indeed saved unintended.

### Expected behavior

We shouldn't save the values if the user doesn't click save

### Screenshots/Recordings

https://github.com/MetaMask/metamask-mobile/assets/54408225/59a76022-d4af-41f1-9bb5-42d2fa60697c

### Steps to reproduce

1. Trigger any tx
2. Click Edit gas
3. Change the gas preference
4. Without clicking Save, click the back arrow
5. See how the new gas preferences was saved

### Version

7.20.0 possibly earlier too

### Build type

None

### Device

Pixel 6

### Operating system

Android

**Comment by jpuri** [comment]
I am not able to replicate this in latest code.

https://github.com/MetaMask/metamask-mobile/assets/2182307/437c3823-f368-4ca8-a16f-d9ca0b98c2e4
