### ISSUE TITLE
Can't recover old accounts from seed phrase

### ISSUE THREAD

**Issue by bdresser** [MetaMask/metamask-mobile#938]
"I was using metamask beta on my old phone. I got a new phone and recovered from seed phrase. 

My initial account was loaded and contained expected balances. 

When I create a new account I do not see my expected balances on account#2,3,4,... Etc.

I would expect all derived keys to be deterministic. I know the seed phrase is correct because account 1 has the full balance"

@igor.lilic on slack if you need followup

**Comment by brunobar79** [comment]
Talked to igor.  Not an issue!
