### ISSUE TITLE
E2E: Update permission-system-revoking-multiple-accounts test script

### ISSUE THREAD

**Issue by SamuelSalas** [MetaMask/metamask-mobile#9383]
Currently, `e2e/specs/permission-systems/permission-system-revoking-multiple-accounts.spec.js` is failing after a latest change from Sushi swap. Before this change, the app was expected to navigate to the Sushi swap website and the connect modal should pop up. Right now, to connect is required to tap the Metamask option from the Connect dropdown. So, it would be required to update the connect steps or to change the swap expected to connect. Here is the exact snipped of code that is failing:

```
// should connect to sushi swap dapp
await Browser.tapUrlInputBox();
await Browser.navigateToURL(SUSHI_SWAP);
await Assertions.checkIfVisible(ConnectModal.container);
await ConnectModal.scrollToBottomOfModal();
await Assertions.checkIfNotVisible(ConnectModal.container);
await TabBarComponent.tapBrowser();
```

Sushi swap screenshot:
<img width="386" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK3VIQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--790fd6a51730aba0f27f46d20a9d9a565094619f/image.png" alt="image.png" />

**Comment by cortisiko** [comment]
This is no longer an issue.
