### ISSUE TITLE
Collectible not removed after send

### ISSUE THREAD

**Issue by bdresser** [MetaMask/metamask-mobile#939]
When I send a erc721 collectible to another account i own myself on Ropsten, the collectible is successfully send, but the collectible is not removedfrom my list of collectibles. When i try to send the collectible again, it says that i do not own the token. Have tried to restart app, but that did not solve the issue

"1. Send collectible to other account you own
2. Wait for successfull transaction
3. Collectible should be removed, but is not"

row117

**Comment by estebanmino** [comment]
this is only working fine on mainnet, we should auto delete the collectible when sending it for other networks
