### ISSUE TITLE
Pooltogether.us doesn't connect to wallet

### ISSUE THREAD

**Issue by bdresser** [MetaMask/metamask-mobile#940]
"No prompt to open wallet"

probably a dapp issue. once confirmed, I or @JSON-LEE13 can reach out

**Comment by brunobar79** [comment]
Just tried and it worked fine on iOS. Took me a whole to find where to do it since the pool is currently locked

**Comment by brunobar79** [comment]
![IMG_4342](https://user-images.githubusercontent.com/1247834/61957736-ed6b6a00-af8d-11e9-9d24-47592b0e270d.PNG)

**Comment by MicahZoltu** [comment]
Same issue with https://augur.casino.  Clicking "Connect a Wallet" dropdown in the top right and then choosing "Metamask" results in no prompt from the wallet to sign-in.  Same issue whether privacy mode is enabled or not in the wallet settings.

Android + Firefox + MetaMask + https://augur.casino works, though the MetaMask pop-up is in a background tab that is easy to miss.

**Comment by estebanmino** [comment]
@MicahZoltu thanks for reporting, I've been looking at this and created a separate issue for augur https://github.com/MetaMask/metamask-mobile/issues/1072

**Comment by estebanmino** [comment]
no longer an issue
