### ISSUE TITLE
[Bug]: Unable to add custom network that lacks a network symbol

### ISSUE THREAD

**Issue by cortisiko** [MetaMask/metamask-mobile#9422]
### Describe the bug

As the title says, I am able to proceed with adding a custom network without the network symbol filled in. The network verification sheet appears and I can "proceed" with adding the network.

### Expected behavior

A user should still not have the ability to add a network with the network symbol missing

### Screenshots/Recordings

https://github.com/MetaMask/metamask-mobile/assets/12821081/7f634920-6abb-4614-804b-7fcb010e30fb

### Steps to reproduce

Create a wallet
Go to the networks view
Attempt to add a custom network without the network symbol
Notice the network verification modal appears and you can proceed with the current network configuration

### Version

7.21.0

### Build type

None

### Device

iOS and Android

### Operating system

iOS

### Additional context

Relates to https://github.com/MetaMask/metamask-mobile/pull/8572

**Comment by sahar-fehri** [comment]
I was able to reproduce this bug on v7.21.0 and v7.22.0, but not in v7.23.0

**Comment by sahar-fehri** [comment]
This is what fixed the bug for newer versions : https://github.com/MetaMask/metamask-mobile/blob/a680bb1036a190c99988149a5ecec9746d2e8b6e/app/components/Views/Settings/NetworksSettings/NetworkSettings/index.js#L1058

**Comment by cortisiko** [comment]
Hey @sahar-fehri, so the network verification sheet no longer appears, but I can still not add the network with the empty symbol field.  I tested on v7.27.0 (the latest prod at this moment).  

https://github.com/user-attachments/assets/300b10ce-4f62-4be2-891f-b08778ea80fd

See recording:

**Comment by cortisiko** [comment]
After digging a bit further, this issue is resolved. A user cannot proceed with adding a network without a symbol. A follow-up here should be to add a warning to the symbol input field, letting users know the symbol is required.
