### ISSUE TITLE
[Bug]: View: Root TypeError:cannot read property 'toLoweCase' of undefined

### ISSUE THREAD

**Issue by jbelor89** [MetaMask/metamask-mobile#9429]
### Describe the bug

I have a hard issue since i had update form play store. When i access the main page not load and looks an spin.... My eth address(i could recovery my eth address from a moonpay transaction, you can check it 0xD06B2f09d4D1F57D9973616341AEf82b8428Be7B ) dont appear and any fo his transactions.... when i acces to general it rise an error when i try to show my private key also rise an error.
![1000009870](https://github.com/MetaMask/metamask-mobile/assets/168377975/24348464-5781-442b-8178-867ce41dfcbe)
![1000009872](https://github.com/MetaMask/metamask-mobile/assets/168377975/ae2b2ca8-fc19-4651-a660-0f8642ed687a)
![1000009871](https://github.com/MetaMask/metamask-mobile/assets/168377975/1dfb8364-d24b-4488-b129-db86c07929f9)

Please i have a lot of tokens form blockdag presale took 3 moths ago....... i cant loose it. 
i share state logs and screen shots.

Please help, thanks
[6534723968807.txt](https://github.com/MetaMask/metamask-mobile/files/15144110/6534723968807.txt)

### Expected behavior

Use my wallet normally

### Screenshots/Recordings

![1000009871](https://github.com/MetaMask/metamask-mobile/assets/168377975/9a79a045-c53f-4a94-930b-e975a5446b1a)
![1000009870](https://github.com/MetaMask/metamask-mobile/assets/168377975/25665b30-93af-46e2-ad53-50490fc7e259)
![1000009872](https://github.com/MetaMask/metamask-mobile/assets/168377975/b1f7bf77-3404-4413-87d4-62d362cc70f0)

### Steps to reproduce

Just open wallet

### Version

7.20.1(1314)

### Build type

None

### Device

Samsung galaxy S24 ultra

### Operating system

Android

### Severity

Very critical, i have lot of presale tokens asigned

**Comment by jbelor89** [comment]
Even i had tried to install in another device and use my secret phrase and appear another addres 0x246E4a0e36476911bfC02A9F81e70ADc8d10DEB3 ????... wt hell... please give me help.... my original address is 0xD06B2f09d4D1F57D9973616341AEf82b8428Be7B and it looks at logs attached...

**Comment by jbelor89** [comment]
Any help? please?

**Comment by gauthierpetetin** [comment]
Hi @jbelor89 , unfortunately, like mentioned in this [duplicate issue](https://github.com/MetaMask/metamask-mobile/issues/7365#issuecomment-2074880177), we have no way to help you recover your Secret Recovery Phrase (SRP), if you haven’t saved it.
