### ISSUE TITLE
[Bug]: Transactions - All tx's are displayed as Contract Deployments and Hex Data displays `Function: Contract Deployment`

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-mobile#9433]
### Describe the bug
Note: this might be only happening on the Transaction/Approval controller PR.

Whenever we are performing any transaction, we can see how:
- the tx pill displays `Contract Deployment`
- the `Hex Data` associated with that transactions displays `Function: Contract Deployment`.

### Expected behavior
- For contract interactions, display the appropiate function name on both the tx pill and the hex data.

- For Send ETH, on Extension this is what we do for the hex data details:
  - if there is not hex data with a send ETH transaction, the HEX data tab is not displayed
  - if there is hex data with a send ETH transaction, we display
    - Function Type: Sending ETH
    - Hex Data: the length and the embedded hex data

### Screenshots/Recordings

![screencap-2024-04-29T104702 408Z](https://github.com/MetaMask/metamask-mobile/assets/54408225/0877dffd-78bd-4b8d-bb7b-e97c8b88ddc9)

![screencap-2024-04-29T085234 326Z](https://github.com/MetaMask/metamask-mobile/assets/54408225/ee9d654e-66cd-4a41-9a6c-7904bdfdb4cf)

![screencap-2024-04-29T084736 303Z](https://github.com/MetaMask/metamask-mobile/assets/54408225/47b8dffc-bafa-415b-a057-962b04eb2c43)

https://github.com/MetaMask/metamask-mobile/assets/54408225/fa8132cc-b83c-4506-9599-f1e190de2272

### Steps to reproduce

1. Go to the test dapp
2. Trigger any tx type (send, contract interaction..)
3. See `Contract deployment` in the tx pill
4. Check Hex Data
5. See `Contract deployment` in the function type field

### Version

this seems to be happening to this branch only https://github.com/MetaMask/metamask-mobile/pull/9088

### Build type

None

### Device

Pixel 6

### Operating system

Android

**Comment by cryptotavares** [comment]
@seaona can we close this issues as they seemed to have been fixed ([per your comment](https://github.com/MetaMask/metamask-mobile/pull/9088#issuecomment-2092616085))

**Comment by bschorchit** [comment]
Closing this. Please re-open if it's still an issue.
