### ISSUE TITLE
Browser doesn't connect to cdpsaver

### ISSUE THREAD

**Issue by bdresser** [MetaMask/metamask-mobile#944]
Could be the dapp. If so, @JSON-LEE13 or I can reach out

**Comment by estebanmino** [comment]
just connected 

![image](https://user-images.githubusercontent.com/12115171/64202101-516f3100-ce5e-11e9-9c7a-9690740cd19b.png)

can we close this or it is something more? @bdresser

**Comment by estebanmino** [comment]
no longer an issue
