### ISSUE TITLE
[Bug] Browser: not able to connect to opensea using MetaMask with in-app browser on android device

### ISSUE THREAD

**Issue by SamuelSalas** [MetaMask/metamask-mobile#9443]
Expected: Wallet can connect to opensea.io with MetaMask option without creating a new browser tab or being asked to sign into Google Play. Just connected to opensea like how it's working with iOS devices.

Actual: A message will constantly appear when tapping the metamask option to connect. In some occasions,  making it hard close the tab and to open a new one in the browser. 

Samsung Galaxy s21 ultra Android 13:
Prod v7.20.1

[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOUdmQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b03c56cd9482650e476a49868c7e16223e0a68e8/Screen_Recording_20240426_215941_MetaMask.mp4)

Release 7.22

[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOVNmQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d2807f8ec9b7c826baa2ca5cea31e0a7be05a7aa/Screen_Recording_20240426_210605_MetaMask.mp4)

**Comment by Cal-L** [comment]
Will be resolved by https://github.com/MetaMask/mobile-planning/issues/1618
