### ISSUE TITLE
[Bug] English copy is not change when selecting non English language on privacy basic functionality section.

### ISSUE THREAD

**Issue by SamuelSalas** [MetaMask/metamask-mobile#9485]
Expected Result: All copies should change to the selected Language on the General section on Settings

Actual Result: The Privacy Basic Functionality section from the Security and Privacy section on the Settings is not changing to the selected language.

[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN2FuQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f9cbaf19909ba7e683f0aea6dfaf0187623d3e6f/RPReplay_Final1714528735.MP4)

**Comment by hesterbruikman** [comment]
Closing as translations have been merged in the meantime.
