### ISSUE TITLE
[Bug]: Invalid deeplink error when importing a private key by QR

### ISSUE THREAD

**Issue by plasmacorral** [MetaMask/metamask-mobile#9517]
### Describe the bug

When importing a valid private key by QR code, user is shown an error: "Invalid deeplink Invalid URL:" and the private key string is displayed in the error message. The account is successfully imported, but the error message is not appropriate in this scenario.

Was [observed](https://github.com/MetaMask/metamask-mobile/pull/9508#issuecomment-2091383880) with QA build from PR 9318/9508, with multiple devices:
Pixel 5a- Android 14
Samsung a515f- Android 12
iPhone Xs- iOS 17.4.1

Not present on 7.21.0, but can be reproduced on the RC build 1321 for 7.22.0 as well as Main

### Expected behavior

Account is imported , user does not have to click `OK` on an error to proceed.

### Screenshots/Recordings

<img src="https://github.com/MetaMask/metamask-mobile/assets/32695229/1ef58050-97be-4a85-9bc7-a946a94c2f10" width="200"/>

### Steps to reproduce

1. Import an SRP and get to wallet view
2. Follow add account flow for importing private key
3. Scan QR of valid private key
4. Observe error

### Version

7.22.0

### Build type

None

### Device

Several

### Operating system

iOS, Android

### Additional context

Account is imported successfully, even though inappropriate error is shown and includes private key as entered

**Comment by christopherferreira9** [comment]
Closing this as it was fixed in https://app.zenhub.com/workspaces/mobile-release-testing-6249e5242464b70013315a98/issues/gh/metamask/metamask-mobile/9569
