### ISSUE TITLE
[Bug]: wallet_addEthereumChain doesn't work with Aurora Mainnet.

### ISSUE THREAD

**Issue by paouvrard** [MetaMask/metamask-mobile#9520]
### Describe the bug

Cannot add or switch to Aurora Mainnet as a custom network. Works correctly with other networks.

### Expected behavior

Add and switch to Aurora Mainnet custom network.

### Steps to reproduce

- Go to https://chainid.network/, search Aurora Mainnet, click Add Chain
- Go to aurora.dev/start, click Add network.

### Version

7.21.0

### Build type

None

### Device

All

### Operating system

iOS

### Severity

All users are affected.

**Comment by minichris** [comment]
afaik this seems to effect all non-standard networks, at least for adding a chain

**Comment by alfeng6** [comment]
I can't seem to reproduce, will close for now.
