### ISSUE TITLE
[Bug]: Deleted accounts reappear

### ISSUE THREAD

**Issue by plasmacorral** [MetaMask/metamask-mobile#9560]
### Describe the bug

Observed in while testing PR [9203](https://github.com/MetaMask/metamask-mobile/pull/9203) and confirmed to be present on production v7.20.1.  After deleting a wallet with QR hardware present and creating a new one, prior QR accounts re-appear after setup.

### Expected behavior

Accounts present prior to delete should not reappear after creating a new wallet.

### Screenshots/Recordings

https://www.loom.com/share/c5c3d92db6da419eabf8aabbcb63afab?sid=d597eead-d642-4de1-bbbe-3476f1311728

### Steps to reproduce

1. Setup wallet with QR hardware accounts and using biometric auth
2. Go to Settings>Security & Privacy
3. Scroll all the way to the bottom and select `Delete Wallet`
4. Tap `I understand, continue`
5. input `delete`
6. Tap `Delete my wallet`
7. Tap `Create new wallet`
8. Complete setup flow
9. Kill the app from tray
10. re-open and authenticate
11. Tap accounts menu and note QR accounts have re-appeared

### Version

7.20.1

### Build type

None

### Device

Iphone Xs with iOS 17.4.1

### Operating system

iOS

### Additional context

Was testing side by side with Android devices, but this seems to be limited to just iOS.

**Comment by angelcheung22** [comment]
@ccharly could you take a look at this one, as its related to the testing of #9202

**Comment by plasmacorral** [comment]
@angelcheung22 while this was discovered in feature testing for PR 9303, once I confirmed this was present in our latest production version at the time 7.20.1 we can be confident that it was not introduced within that PR.  My suspicion is that this may be related to some of the hardware changes within 7.19.0, but I have not had time to explore that theory.  Could @vivek-consensys take a look?

cc @ccharly

**Comment by vivek-consensys** [comment]
> @angelcheung22 while this was discovered in feature testing for PR 9303, once I confirmed this was present in our latest production version at the time 7.20.1 we can be confident that it was not introduced within that PR. My suspicion is that this may be related to some of the hardware changes within 7.19.0, but I have not had time to explore that theory. Could @vivek-consensys take a look?
> 
> cc @ccharly

@plasmacorral  I can confirm that I can reproduce this issue on the latest 7.22 RC3 build on TestFlight, the issue is only with the QR account as the Ledger account does not display when following the steps. @dawnseeker8 is looking into this issue.
