### ISSUE TITLE
https://app.friendsfingers.com not working correctly

### ISSUE THREAD

**Issue by brunobar79** [MetaMask/metamask-mobile#959]
Received via email:

https://app.friendsfingers.com/dashboard/

I'm having an issue after clicking on Connect.

It calls the ethereum.enable() method and it works fine. 
Then it reloads page and it should select ethereum.selectedAddress.

But... it works fine on chrome with metamask extension but on iOS it:
calls the onAccountsChanged event [code]
calls the onNetworkChanged event [code]
ethereum.selectedAddress is undefined [code]
ethereum._selectedAddress is filled with right value [code]
I tried to debug it loading website locally.
So I added some console.log to show you values and events.

It would be very appreciated if you could give a look.
It works properly on chrome so it could be amazing having it working on mobile.

**Comment by bitpshr** [comment]
Responded via email:

```
Hi Vittorio,

Thanks again for reporting this issue.

After digging into the provided code a bit more, we noticed that you’re calling ethereum.selectedAddress, which isn’t technically part of the current Ethereum provider API.  The extension happens to expose ethereum.selectedAddress, but this is just an implementation detail and not a public API that should be used in production. Instead of accessing the current account via ethereum.selectedAddress, the best method would be to use ethereum.send(‘eth_accounts’) or to cache the value received on the onAccountsChanged event.

Don’t hesitate to let us know if you have any additional questions, and thanks again for helping to test MetaMask mobile.

Best,
```
