### ISSUE TITLE
Deeplink to open a site iniside browser is not working when unlocking the Metmask app with password

### ISSUE THREAD

**Issue by mahfouzhseineweev** [MetaMask/metamask-mobile#9632]
### Describe the bug

When trying to open a website inside Metamask browser using deeplink `https://metamask.app.link/dapp/google.com`  nothing is happening only in the following case:

* Remember me is turned off
* Metamask app is initially closed

So when opening the deeplink after entering the password, nothing is happening.

### Expected behavior

What is expected when clicking the deeplink is to have the site `google.com` for example, opened and shown inside Metamask browser

### Steps to reproduce

1. Set remember me to off from Security & Privacy
2. Have the Metamask app initially closed
3. Click on the deeplink https://metamask.app.link/dapp/google.com

### Version

7.22.0

### Build type

None

### Device

iPhone Xs Max, software version 15.4.1

### Operating system

iOS

### Additional context

Note that the problem is also reproducible on Android devices

**Comment by omridan159** [comment]
Hey @mahfouzhseineweev

This PR contains a fix for it:
https://github.com/MetaMask/metamask-mobile/pull/9843
