### ISSUE TITLE
[BUG] Error message on Send to screen after filling ens address + space char

### ISSUE THREAD

**Issue by SamuelSalas** [MetaMask/metamask-mobile#9675]
### Describe the bug

Filling the receiver field with an ens address from the Send to screen, wait to validate the address and immediately add a space bar char next to the end address, will shown the "an error occur" screen.

### Screenshots/Recordings

https://github.com/MetaMask/metamask-mobile/assets/22276767/4a2c948b-d0af-4745-937a-7f6a9a1c91b1

### Expected behavior

Should just ignore the space char at the end of the field

### Steps to reproduce
1. Tap the send button from the tab bar actions
2. Fill the To: field from the send to screen with an ens address
3. Wait to validate the ens address
4. Add an space bar char next to the end address

**Comment by sethkfman** [comment]
Expectation is that the root cause of the crash is caught to handle many different scenarios like the one below.

linked to #8582

**Comment by EtherWizard33** [comment]
This is now fixed in this PR 
https://github.com/MetaMask/metamask-mobile/pull/9720

**Comment by SamuelSalas** [comment]
Ens address does not break after adding an space character at the end. Closing this issue.

![image](https://github.com/MetaMask/metamask-mobile/assets/22276767/344f72f4-2cb7-4add-9a17-f01ed19a8b2f)
