### ISSUE TITLE
[BUG] Differences from Searches between extension and mobile 

### ISSUE THREAD

**Issue by SamuelSalas** [MetaMask/metamask-mobile#9679]
### Describe the bug

When comparing Swaps Search, Import Token Search and Receive Asset Search between the extension and mobile app, the values returned are not the same.

### Screenshots/Recordings

<img width="720" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNFR4QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b7690ba8b26f57a90269b5a79cc06fea020dae21/image.png" alt="image.png" />
<img width="333" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNFh4QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--04f58cb6165864ba00519ecec60436f4b494acab/image.png" alt="image.png" />
<img width="333" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNGJ4QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--122dae913a7b196dedcfe75579cfec5eca9e7fff/image.png" alt="image.png" />
<img width="719" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNGZ4QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3f43a3ebe7aebe2708aefd437c19f1a07c9a256f/image.png" alt="image.png" />

### Expected behavior

Swaps Search, Import Token Search and Receive Asset Search should be the same between the extension and the mobile app

**Comment by alfeng6** [comment]
@SamuelSalas can you help take new screenshots?
