### ISSUE TITLE
[Bug]: NFTs displayed during the Send flow does not align with the NFT assets visible in the account's NFT tab

### ISSUE THREAD

**Issue by sleepytanya** [MetaMask/metamask-mobile#9726]
### Describe the bug

Although the NFT tab accurately displays NFT collection, the NFT shown within the Send flow only reflect a subset of these NFTs (in the video below account has 10 NFTs while only 5 NFT available to select during Send transaction).

### Expected behavior

All NFTs are consistently and fully accessible across different functionalities.

### Screenshots/Recordings

https://github.com/MetaMask/metamask-mobile/assets/104780023/fbc64b19-c4d1-4629-a556-c5587c5157df

### Steps to reproduce

1. Turn on 'NFT Auto-detection' in Security and Privacy settings
2. Observe NFT assets in the NFT tab
3. Start Send transaction
4. Proceed to select token other than ETH 
5. Scroll down to NFT
6. Notice that amount of NFTs shown is less than within the NFT tab

### Version

7.22.0(1325)

### Build type

None

### Device

Samsung S24+

### Operating system

Android

**Comment by sahar-fehri** [comment]
Thank you @sleepytanya! I think this behavior is expected. Mobile does not support yet sending ERC1155. The NFTs you see are only the ERC721 NFTs.
