### ISSUE TITLE
InstaDApp - error w/ multiple web 3 batch call 

### ISSUE THREAD

**Issue by dpazdan** [MetaMask/metamask-mobile#975]
Getting an error with multiple web3 batch call on Metamask beta IOS. Single batch call is working fine.

Multiple batch calls are working on Metamask chrome extension, Trust & other web3 providers.

**Comment by brunobar79** [comment]
@bitpshr ping in case this is related to the issues that you have seen with other dapps.

**Comment by rekmarks** [comment]
Appears to be working fine now.
