### ISSUE TITLE
 Encountering an issue where the pop-ups for connect #9756 [Bug]: 

### ISSUE THREAD

**Issue by VijiHithub** [MetaMask/metamask-mobile#9757]
### Describe the bug

Hello Team !!!

I'm currently utilizing the Metamask app version 7.22.0 on my Android device. Unfortunately, I'm encountering an issue where the pop-ups for connect, approve, or sign transactions are not appearing. I'm working on integrating wallet connect functionalities with ethers.js. I would greatly appreciate it if you could investigate this issue and provide a prompt solution.

Thank you very much in advance!

### Steps to reproduce

Go to

### Version

7.22.0

### Build type

None

### Device

Maximum all devices ( especially one plus 11 R ) 

### Operating system

Android

**Comment by gauthierpetetin** [comment]
Hi @VijiHithub , thanks for reporting this issue.
Can you please specify what Android version and what device you're using?
Did this start to happen in version 7.22.0 or did you already encounter this issue before?
cc @MetaMask/mobile-platform for visibility

**Comment by VijiHithub** [comment]
Hi @gauthierpetetin , @MetaMask/mobile-platform ,

Thank you for your reply. I have an Android device (one of the OnePlus 11Rs 5G) with an Android version of 14. I have been experiencing this problem since version 7.21.0.

**Comment by VijiHithub** [comment]
Hi @gauthierpetetin , 

Any solution regarding this issue ?

**Comment by tommasini** [comment]
Hey @VijiHithub thanks for reporting!

Just to make sure can you do a recording using the in app browser and your dapp for to see the issue?

Also if you could share the link for the dapp or a online snippet of it, it would be ideal for us on our side debug it!

**Comment by VijiHithub** [comment]
Hi @tommasini thanks you for your reply. 

Okay sure. I'll share the website link and working video.

**Comment by VijiHithub** [comment]
Hello @tommasini ,

Please visit our website here: https://onebillion.osiztech.com

I have provided two videos for your reference. The first video is from a mobile device where everything is functioning correctly, and the second video is from a mobile device where it's not working.

**Video 1 :** 

https://github.com/MetaMask/metamask-mobile/assets/94688437/4e1a1eb7-ab7b-4e8f-a8ae-919879f384f6

**Video 2 :**

https://github.com/MetaMask/metamask-mobile/assets/94688437/7fecfcbd-82c7-4ce1-b7cf-9069b21b897d

https://github.com/MetaMask/metamask-mobile/assets/94688437/3c0d49bf-e65f-4436-80f0-8234e1efd4ec

Thank you.

**Comment by VijiHithub** [comment]
Hi @gauthierpetetin & @tommasini ,

I have added video FYR. Kindly check and provide the solution ASAP.

**Comment by tommasini** [comment]
Thanks @VijiHithub connecting with wallet connect is not working, we will start to understand what's the issue and come back here with an answer!

**Comment by VijiHithub** [comment]
@tommasini thanks you for your reply.

Okay sure. I am waiting your valuable response. 

Thanks in advance !!!

**Comment by VijiHithub** [comment]
Hi @gauthierpetetin , @tommasini ,

Good Day !!!

Any solution regarding this issue ?

Thanks !!!

**Comment by gauthierpetetin** [comment]
Hi @VijiHithub , not yet.
This issue has been assigned to one of our teams ( @MetaMask/sdk-devs ), they'll keep you informed once they'll progress on this task.

**Comment by VijiHithub** [comment]
Hi @gauthierpetetin , 

Okay thank-you !!!

**Comment by VijiHithub** [comment]
Hi @gauthierpetetin @tommasini , 

Any progress regarding this issue ?

Thank you !!!!

**Comment by gauthierpetetin** [comment]
Hi @MetaMask/sdk-devs , do you have any update to share with @VijiHithub regarding this issue?

**Comment by christopherferreira9** [comment]
Hi! We will be having a sync with a pair programming session with WC and we'll take this to it.

**Comment by abretonc7s** [comment]
Hi @VijiHithub  , This seems to be a walletconnect implementation issue. 
I have dicussed with WalletConnect team, you can re-open the issue on their repo.

**Comment by VijiHithub** [comment]
Hi @abretonc7s thanks you for your reply.

Can you please share the exact wallet-connect repo ?
