### ISSUE TITLE
Analytics & tracking QA

### ISSUE THREAD

**Issue by bdresser** [MetaMask/metamask-mobile#979]
Placeholder issue for a round of QA closer to launch date to make sure events are firing as expected.

Metrics sheet is [here](https://docs.google.com/spreadsheets/d/1XYj78KAUytJQCKk1fD8pERxXsZRZ6aQhcMP5GJS5X8k/edit#gid=1878986372)

**Comment by bdresser** [comment]
should happen after https://github.com/MetaMask/Design/issues/119

**Comment by ibrahimtaveras00** [comment]
Solved in previous release
