### ISSUE TITLE
Trigger the force upgrade from the 1333 release (v7.23.0)

### ISSUE THREAD

**Issue by sethkfman** [MetaMask/metamask-mobile#9799]
### What is this about?

Update appMinimumBuild from 1242 to 1333 (version 7.23) by June 3.

Trigger users to update app before June date

### Technical Details

The appMinimumBuild shall be incremented from 1242 to 1333 (version 7.23)

Follow the [recommended process](https://github.com/MetaMask/metamask-mobile/tree/gh-pages#app-config-api) for testing then rolling out the update in production.

Test update using a [PR](https://github.com/MetaMask/metamask-mobile/blob/b84e334d90ca8b0beeb57aa3e08f4f07787d3b54/AppConfig/test/MockAppConfig.json#L4) in the test directory
Production update using a [PR](https://github.com/MetaMask/metamask-mobile/blob/b84e334d90ca8b0beeb57aa3e08f4f07787d3b54/AppConfig/v1/AppConfig.json#L4) in the production directory

### Acceptance Criteria

- MinAppVersion set to 1333
- Test recordings provided
- Force upgrade added to log on [Notion](https://www.notion.so/Minimum-versions-history-750c91610b614f3e88601650099e77b8?pvs=4)

### Stakeholder review needed before the work gets merged

- [ ] Engineering (needed in most cases)
- [ ] Design
- [ ] Product
- [ ] QA (automation tests are required to pass before merging PRs but not all changes are covered by automation tests - please review if QA is needed beyond automation tests)
- [ ] Security
- [ ] Legal
- [ ] Marketing
- [ ] Management (please specify)
- [ ] Other (please specify)

**Comment by NicolasMassart** [comment]
Can you confirm this requires to create a PR to increase the minimal build number and release it in a new version that will be versioned with an incremented build number and semVer to 7.23.1 ?
Or do we send this forced upgrade in the next 7.24.0?

**Comment by NicolasMassart** [comment]
Done

**Comment by NicolasMassart** [comment]
Done
