### ISSUE TITLE
Collectible detection sometimes doesn't work

### ISSUE THREAD

**Issue by bdresser** [MetaMask/metamask-mobile#980]
e.g. 

> The wallet doesn't auto populate if a new 721 is received. It requires contract address and token Id manually. This seems like a very bad solution, especially if say, I was trying to send a business card NFT to someone, the only way they could see it in metamask mobile is by looking up the address and the token Id via txhash.... Then see the card. Whereas trust wallet just autopopulates using an Api call.

> It would be great if erc20 tokens are automatically recognized. I had to import the token address in order for metamask to show the custom token I had created and set to myself. 
Additionally I love that we are able to transfer collectibles from the collectible tab!g

perhaps this isn't a bug just a fact of how we implement collectibles? if so, we should have a way to let users know some collectibles aren't autodetected.

**Comment by vikmeup** [comment]
Please add **automagically** feature to see all your collectables. 🚀

**Comment by estebanmino** [comment]
fix in https://github.com/MetaMask/gaba/pull/138
