### ISSUE TITLE
Swap serialization error related to redux persist post swapping

### ISSUE THREAD

**Issue by Cal-L** [MetaMask/metamask-mobile#9818]
### What is this about?

There's currently a bug on `main` where an error stating `redux-persist/createPersistoid:error serializing...` occurs post swap. The error is thrown in `redux-persist/lib/createPersistoid.js` line 78 when it attempts to cache incoming data from Redux.

https://github.com/MetaMask/metamask-mobile/assets/10508597/178d2086-8865-479e-be12-8dbd1990fdf0

### Scenario

- Run the app on simulator
- Import an account with a native balance
- Perform a swap action on mainnet or linea mainnet
- Notice that the redux-persist error appears
- The error continues to appear even after dismissal since the app continues to serialize + cache data occasionally

### Technical Details

- Investigate the data changes post swap. Serialization works prior to a swap, which implies some data changes may be failing to serialize post swap

### Acceptance Criteria

- Error disappears after swapping

### Stakeholder review needed before the work gets merged

- [ ] Engineering (needed in most cases)
- [ ] Design
- [ ] Product
- [ ] QA (automation tests are required to pass before merging PRs but not all changes are covered by automation tests - please review if QA is needed beyond automation tests)
- [ ] Security
- [ ] Legal
- [ ] Marketing
- [ ] Management (please specify)
- [ ] Other (please specify)

### References

- Visible in video attached to this PR - https://github.com/MetaMask/metamask-mobile/pull/9565
  - Note: The error exists on main already

**Comment by NicolasMassart** [comment]
- does this prevent swap to work properly?
- once the error happened, is it popping again even if we restart app?
