### ISSUE TITLE
[Bug]: why i not use fingerprint

### ISSUE THREAD

**Issue by Agus378** [MetaMask/metamask-mobile#9820]
### Describe the bug

my account sing out, i want try sing in account why i not use fingerprint
![Screenshot_20240601-021151](https://github.com/MetaMask/metamask-mobile/assets/109218689/dd6c634e-13cd-4582-a471-69632d43a806)

### Expected behavior

help me 

### Screenshots/Recordings

![Screenshot_20240601-021151](https://github.com/MetaMask/metamask-mobile/assets/109218689/2506f169-1115-44ac-99f0-cb05e8ef8be7)

### Steps to reproduce

![Screenshot_20240601-021151](https://github.com/MetaMask/metamask-mobile/assets/109218689/c55ae681-b66d-4d2c-9be5-8389202fa337)

### Error messages or log output

```shell
Error: Unknown error: Attempt to invoke virtual method 'java.security.PublicKey java.security.cert.Certificate.getPublicKey()' on a null

object reference
```

### Version

7.22.0

### Build type

None

### Device

android infinix hot 10s 

### Operating system

Android

### Additional context

please help me my account sir

### Severity

penting banget tolong di perbaiki

**Comment by NicolasMassart** [comment]
Hi @Agus378, can you please describe the steps leading to your issue in detail?
- have you tried login with the password?
- have you manually locked MetaMask from the settings "Lock" or has it locked itself (timer, closing the app, ...)?
- have you had the fingerprint prompt and canceled or fail the authentication?
- would you be able to record a small video from the start of the app to the error message?

NOTE: if you feel more comfortable writing in your native language in this issue, please do, we will translate.

**Comment by gauthierpetetin** [comment]
Hi @Agus378, is this issue still happening on your end. If so please let us know, and we'll re-open it.
