### ISSUE TITLE
[Bug]: Duplicate Account Issue in MetaMask 7.23.0 on iPhone 14

### ISSUE THREAD

**Issue by fricklik** [MetaMask/metamask-mobile#9823]
### Describe the bug

After updating MetaMask to version 7.23.0 on my iPhone 14, the same account appears duplicated in the app. When attempting to open the duplicated account, it displays the original account with the same address. A friend with an iPhone 14 Pro has experienced the exact same issue.

### Expected behavior

I expected to see only one instance of each account and be able to access each account individually without duplication.

### Screenshots/Recordings

Attached is a screenshot showing the duplicated accounts. The original account is highlighted with a red
![314C098B-0977-4515-926D-BBE277213B74](https://github.com/MetaMask/metamask-mobile/assets/11188188/341da84b-26c6-4ddb-9a55-07c1ac4d2901)
 frame.

### Steps to reproduce

1. Update MetaMask to version 7.23.0 on an iPhone 14 or iPhone 14 Pro.
2. Open MetaMask and check the list of accounts.
3. Notice the duplicated accounts.
4. Try to open the duplicated account, which displays the original account instead.

### Error messages or log output

```shell
No specific error messages are shown.
```

### Version

7.23.0

### Build type

None

### Device

iPhone 14, iPhone 14 Pro

### Operating system

iOS

### Additional context

This issue affects multiple users with similar devices and the same version of MetaMask.

**Comment by gantunesr** [comment]
Hey @fricklik, it would be really helpful if you can post a video reproducing this issue

**Comment by NicolasMassart** [comment]
Users state logs (2 reports kept private) are showing the duplicated accounts have a checksummed address for the original one (the properly named one) and the same address but lowercased for the duplicate.

## Redacted example

```json
"accounts": {
            "XXXXXXXX-XXXX-XXXX-bXXX-XXXXXXXXXX": {
              "address": "0x0...AD",
              "id": "XXXXXXXX-XXXX-XXXX-bXXX-XXXXXXXXXX",
              "options": {},
              "metadata": {
                "name": "xxxxxx.eth",
                "keyring": { "type": "HD Key Tree" },
                "lastSelected": 1234567890123
              },
              "methods": [
                "personal_sign",
                "eth_sign",
                "eth_signTransaction",
                "eth_signTypedData_v1",
                "eth_signTypedData_v3",
                "eth_signTypedData_v4"
              ],
              "type": "eip155:eoa"
            },
            "XXXXXXXX-XXXX-XXXX-bXXX-XXXXXXXXXX": {
              "id": "XXXXXXXX-XXXX-XXXX-bXXX-XXXXXXXXXX",
              "address": "0x0...ad",
              "options": {},
              "methods": [
                "personal_sign",
                "eth_sign",
                "eth_signTransaction",
                "eth_signTypedData_v1",
                "eth_signTypedData_v3",
                "eth_signTypedData_v4"
              ],
              "type": "eip155:eoa",
              "metadata": {
                "name": "Account 7",
                "keyring": { "type": "HD Key Tree" },
                "lastSelected": 1234567890123
              }
            },
```

Notice `"address": "0x0...AD"` and `"address": "0x0...ad"`

**Comment by montelaidev** [comment]
I think it's a migration issue. Mobile uses checksummed addresses in the PreferencesController, but the extension uses lowercase addresses. When the AccountsController adds or removes accounts from the KeyringController, the addresses are all in lowercase. The checksummed addresses create different account IDs during the migration, and this also causes the AccountsController to create duplicate accounts since it thinks it's a new account.

**Comment by Razzbird8** [comment]
I have this same issue on Galaxy Note20 Ultra 5G
