### ISSUE TITLE
[Bug]: QR account names are not matching

### ISSUE THREAD

**Issue by vivek-consensys** [MetaMask/metamask-mobile#9829]
### Describe the bug

When the user adds QR hardware wallet accounts, the account names should be matching to when the user edits those account names. 

### Expected behavior

QR account name should be matching from the account list dropdown to when editing account name

### Screenshots/Recordings

https://github.com/MetaMask/metamask-mobile/assets/106310394/27427b69-d909-4761-8275-acfc5be39b6f

### Steps to reproduce

1. Recover from SRP
2. Click add hardware wallet
3. Click QR based
4. Add 3 accounts from QR-based wallet
5. Click on QR account 1
6. Click on Edit account name
7. Verify the account name matches on the edit screen to the account list

### Version

7.24.0 RC1

### Build type

Beta

### Device

iPhone 13

### Operating system

iOS

### Severity

sev-3

**Comment by plasmacorral** [comment]
I noted yesterday while trying to prepare a migration test, that there is something similar with HD accounts.  I added an HD account to a wallet that already had hardware and imported accounts present. The new HD account was listed as `Account 4` in the accounts drop-down list, but when I went to edit the label the same account was presented as `Account 8`.

This was observed on multiple devices with a QA build of v7.23.0.  It is something I had noted to explore further after I finish my feature QA testing.

**Comment by vivek-consensys** [comment]
Bitrise build: https://app.bitrise.io/app/be69d4368ee7e86d/pipelines/0352b752-cae2-4f7a-afd8-ec267f09c85e

**Comment by vivek-consensys** [comment]
Tested using iPhone 13 using 17.5.1 on Bitrise build:- 

[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOTVZQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0df2407a1e7fd4c4dcc957e40f672d2414d21110/RPReplay_Final1718194292.MP4)

**Comment by vivek-consensys** [comment]
Tested using iPhone 13 using 17.5.1 on https://app.bitrise.io/app/be69d4368ee7e86d/build/fc782601-c757-4c6c-bbd4-f1ab103a7f71/artifact/63250b61dd48d55b/p/31601566974aab131ec42cc34dbd7177:-


[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMlZaQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0566f719ca6c3177f2d954607231a15f1b4f4d41/RPReplay_Final1718199420.MP4)
