### ISSUE TITLE
[Bug]:  Invalid "from" address when use signMessage

### ISSUE THREAD

**Issue by EF09FE** [MetaMask/metamask-mobile#9840]
### Describe the bug

Called in React Native app with WalletConnect on Android side

```
const sign = await provider.send("personal_sign", [{
            challenge: hexlify(toUtf8Bytes(message)),
            address: evmAddress.toLowerCase(),
        }]);
```

Got this error:
```
 [Error: could not coalesce error (error={ "code": 5000, "message": "{\"code\":-32603,\"message\":\"Invalid \\\"from\\\" address: undefined must be a valid string.\",\"data\":{\"originalError\":{}}}" }, payload={ "id": 4, "jsonrpc": "2.0", "method": "personal_sign", "params": [ { "address": "0x6cff6f7c0c3848009437ceb72967b83e297d313d", "challenge": "0x3c42797465733e636573732d6a732d73646b2d313731373438383739353838363c2f42797465733e" } ] }, code=UNKNOWN_ERROR, version=6.12.1)]
```

I've check MetaMask docs about `personal_sign` at [here](https://docs.metamask.io/wallet/reference/personal_sign/), it seems params are as expected

### Steps to reproduce

1. in My ReactNative app click to request signMessage
2. MetaMask will launch and shows a bottom sheet modal of `Connecting to MetaMask...`
3. after few seconds, modal dismissed and MetaMask also dismissed, back to my App
4. console log shows `Error: Invalid "from" address....`

### Version

7.23.0(1333)

### Build type

None

### Device

Mi13

### Operating system

Android

**Comment by christopherferreira9** [comment]
Hi @EF09FE ! 
Can you quickly double check you're sending the correct `from` address?

I wasn't able to reproduce this issue on my dapp. In the following video you can see 2 requests, one with the address as undefined and another with a proper address. The request made with `from` as `undefined` throws the error you're getting which is expected.

https://github.com/MetaMask/metamask-mobile/assets/104831203/955eb038-7d52-4ac5-bfda-6a67ff8a49c8
