### ISSUE TITLE
Fingerprint unlock with fingerprint unlocking disabled!

### ISSUE THREAD

**Issue by MicahZoltu** [MetaMask/metamask-mobile#985]
1. Install MetaMask app from Play Store.
2. Sync with desktop browser extension.
3. Go to security settings in app and ensure Fingerprint unlock is _disabled_.
4. Close MetaMask app.
5. Open MetaMask app.
--> Notice that you are prompted for a fingerprint to unlock the app!

This is a pretty big security issue for me as biometrics alone are _NOT_ secure.  While I have them setup for unlocking my phone, all of my financial apps are secured behind _something I know_, not something I have since getting into my phone in the first place requires something I have (biometrics + device).

**Comment by brunobar79** [comment]
Hey there.  thanks for reporting. I can confirm that this is definitely a bug on our end and it's not intended to work that way.

The first problem is related to #927  where we are enabling it by default without actually asking the user if they want to do it.

The second problem is that the option "Sign in with Fingerprint" it's not reflecting the ON state after the sync.

Both problems will get fixed on our next release.

**Comment by MicahZoltu** [comment]
When is this expected to land in a release?

**Comment by brunobar79** [comment]
Monday / tuesday the latest.

**Comment by jumpnkick** [comment]
Two months now. Still having this problem... Funny thing it used to work fine on previous releases.
No solution yet, or is it on my side the prob?
Thanx!

**Comment by estebanmino** [comment]
Hi @jumpnkick  thanks for reporting, I've been trying to reproduce in a Samsung S9 but I can't. Which device are you using? Also, metamask version? Thanks!

**Comment by jumpnkick** [comment]
OnePlus 3t.
MetaMask 0.2.8
Thank you!

**Comment by jumpnkick** [comment]
Just tried it again. It started working now.
Funny thing I didn't update or reinstall it.
Simply started working.
