### ISSUE TITLE
fix: "data collection for marketing" toggles have bugs and redundant addTraitsToUser and events added in PR #9687

### ISSUE THREAD

**Issue by NicolasMassart** [MetaMask/metamask-mobile#9862]
### What is this about?

https://github.com/MetaMask/metamask-mobile/pull/9687/ adds `addTraitsToUser` calls that should be grouped with the existing calls. Traits should be consolidated first then passed all at once as this makes the Segment SDK send an API call for identify.

In addition, passing traits to tracking events is redundant as values are already on the user profile.
This makes the `ANALYTICS_PREFERENCE_SELECTED` event itself redundant as it's then becomes similar to the already sent `ANALYTICS_PREFERENCE_SELECTED`.
The `location: 'onboarding_metametrics'` event prop is also a duplicate of `updated_after_onboarding: false` prop and we probably have to chose only one.

To be discussed as data team may have good reasons to need these data, but we should not just add them to the code as if nothing was already there...

### Stakeholder review needed before the work gets merged

- [x] Engineering (needed in most cases)
- [ ] Design
- [ ] Product
- [ ] QA (automation tests are required to pass before merging PRs but not all changes are covered by automation tests - please review if QA is needed beyond automation tests)
- [ ] Security
- [ ] Legal
- [ ] Marketing
- [ ] Management (please specify)
- [x] Other (please specify)
  - data team @worldlyjohn

**Comment by worldlyjohn** [comment]
agree we only need 1.  it's not necessarily redundant as the new event has new properties important for referencing whether a user has opted in to the marketing consent toggle.

**Comment by NicolasMassart** [comment]
We already have these informations in the user profile and the existing event. This new one seems redundant to me.

**Comment by worldlyjohn** [comment]
hey @NicolasMassart , sorry i think i miss understood and missed the nuance of this line:
> passing traits to tracking events is redundant as values are already on the user profile

it's actually not redundant. the event tells us what was changed and when.  the profile update holds the current state.

**Comment by NicolasMassart** [comment]
As per our Slack discussion, and your agreement to fix this, I will provide a PR to prevent duplicated calls.

If have well noted that the `analytics_option_selected` looks not to be used in any reporting so I can change the property name/values to match what we've defined with `is_metrics_opted_in` and `has_marketing_consent`.
