### ISSUE TITLE
Buy crypto buttons should direct to affiliate links

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-mobile#987]
Example: Coinbase should link to an affiliate link per [their affiliate program](https://www.coinbase.com/affiliates). Ideally it would use the same one as our desktop client.

**Comment by brunobar79** [comment]
@bdresser can you help us get those?

**Comment by EtDu** [comment]
Does not appear to be relevant anymore, please reopen if I'm mistaken
