### ISSUE TITLE
[Bug]: STX opt-in dialog not appearing on fresh install

### ISSUE THREAD

**Issue by davibroc** [MetaMask/metamask-mobile#9889]
### Describe the bug

After doing a fresh install of the app and going through the onboarding,  the STX opt-in dialog should pop up. It only happens after an app upgrade

### Expected behavior

Opt-in dialog should appear after onboarding

### Screenshots/Recordings

https://github.com/MetaMask/metamask-mobile/assets/6082863/33766af0-6563-4d05-a1ad-767c247ae6d7

### Steps to reproduce

1. Do a fresh install
2. Go through the on-boarding process
3. Notice the opt-in dialog never appears

### Version

7.24.0

### Build type

None

### Device

Samsung Galaxy

### Operating system

Android

**Comment by forest-diggs-consensys** [comment]
@davibroc does this happen if you don't skip the 'account security' step?

**Comment by davibroc** [comment]
> @davibroc does this happen if you don't skip the 'account security' step?
I tried and it does

**Comment by davibroc** [comment]
This was due to `export IS_TEST="true"` in my ENV. I will close the bug
