### ISSUE TITLE
add increase allowance E2E

### ISSUE THREAD

**Issue by OGPoyraz** [MetaMask/metamask-mobile#9939]
**Goal**

Create E2E tests to verify increase allowance confirmation.

**Notes**

- Required to update test-dapp pkg to latest (issue on android)

**Comment by vinistevam** [comment]
Create PR adding increase allowance https://github.com/MetaMask/metamask-mobile/pull/9969 .
I also investigated the issue bumping the test-dapp version:

The problem first appeared in version v8.2.0, introduced in [this PR](https://github.com/MetaMask/test-dapp/pull/284). The issue arises whenever @web3modal/ethers5 is imported, causing the tests to break. This behavior is observed only on Android and within the Detox build.

I have implemented a workaround that resolves the issue, but it's not an ideal solution. I'm open to suggestions for a better fix. You can review the changes here: [fix/issue-android-detox-e2e](https://github.com/MetaMask/test-dapp/compare/main...fix/issue-android-detox-e2e).
