### ISSUE TITLE
Ropsten Custom Token Shows Balance of 0 After Switching Networks 

### ISSUE THREAD

**Issue by ibrahimtaveras00** [MetaMask/metamask-mobile#994]
Steps:
- add this custom token (preferably you have a balance already greater than 0)
0xe9f786dfdd9ae4d57e830acb52296837765f0e5b
- take note of your balance for HACK 
- switch networks to main
- ensure you don't see HACK, now switch network back to Ropsten, it'll show as 0 

seen here = https://recordit.co/TJJ6FTbZKy

FYI = this works if I do mainnet adding custom token BLT (https://etherscan.io/token/0x107c4504cd79c5d2696ea0030a8dd4e92601b82e)

**Comment by estebanmino** [comment]
closing, is not really an bug
