### ISSUE TITLE
Confusing between clearnet and ens domains

### ISSUE THREAD

**Issue by AboShanab** [MetaMask/metamask-mobile#998]
I was tried to enter [Mailchain](https://inbox.mailchain.xyz/#/) website from the url, but the app is response with 'we couldn't resolve that ENS name', I'm on MetaMask version 0.2.2 (15) @ Android 9.

Screenshot:
![Screenshot_1](https://user-images.githubusercontent.com/12101368/63075734-5d409500-bf3b-11e9-87cc-68479d80147d.jpg)

**Comment by estebanmino** [comment]
thanks for reporting @AboShanab, we'll take a look

**Comment by trumhemcut** [comment]
I have same issue with https://alpha.baoswap.xyz/#/swap. Could you pls take a look?

**Comment by mightymatth** [comment]
Still issue with https://ibetyou.xyz

**Comment by ffakira** [comment]
Guys could you please follow up with this issue, it was first opened in 2019. And we're still having problems with iOS and Android, accessing external links.

**Comment by Ty-Sir** [comment]
Seems to be a problem with .xyz dapps, I'm trying to view the dapp I just built, avaxmonkeys.xyz, on MM mobile and am running into the same problem. Has anyone found a fix?
