### ISSUE TITLE
[Bug]:  Button click is working (unable to login)

### ISSUE THREAD

**Issue by hi-nikhil** [MetaMask/metamask-mobile#9992]
### Describe the bug

-When you log in the wallet you have to enter the password, but I am clicking a certain button it is writing something else in the input box or sometimes in one click it is writing more than one character in the input box.
- Also when I trying to delete written characters using delete button this is also not working.

### Expected behavior

- Everytime when I click on button it should write character of that button in the input box.
- It should delete the text in the input box by using delete key from the keyboard.

### Screenshots/Recordings

https://github.com/MetaMask/metamask-mobile/assets/70910601/59f0f934-40b1-4b3d-a6aa-e8f9c583ae55

### Steps to reproduce

Open Metamask and write your password to login instead of using face id or touch id.

### Version

7.23.0

### Build type

None

### Device

POCO M4 Pro ,  Model - 2201117P

### Operating system

Android

**Comment by NicolasMassart** [comment]
Are you using a specific keyboard app? If so can you provide infos on keyboard app and version please?
What happens if you use Google Gboard default keyboard?

**Comment by hi-nikhil** [comment]
My phone has a default keyboard, i.e. "Emoji&Font Keyboard", Version - 4.2.4. On this keyboard I am facing above issue, but 
on Google Gboard it is working fine.

**Comment by Cal-L** [comment]
hi @hi-nikhil It seems Emoji&Font keyboard is a custom keyboard. Do you experience issues with other apps as well while using this keyboard?

**Comment by gauthierpetetin** [comment]
This issue looks like a duplicate: https://github.com/MetaMask/metamask-mobile/issues/10276

**Comment by hi-nikhil** [comment]
> hi @hi-nikhil It seems Emoji&Font keyboard is a custom keyboard. Do you experience issues with other apps as well while using this keyboard?

This is an issue only related to the Metamask app, on all other apps it is working fine."
When I am using 'Gboard' it is working fine, issue is only while using 'Emoji&Font Keyboard' .
