### ISSUE TITLE
IOS - Metamask 7.23 to 7.24

### ISSUE THREAD

**Issue by FireFoxer** [MetaMask/metamask-mobile#9995]
### What is this about?

After update, cant login.
![IMG_3732](https://github.com/MetaMask/metamask-mobile/assets/1117506/ca3db709-3a81-476c-9b52-7c82a6837146)

### Stakeholder review needed before the work gets merged

- [X] Engineering (needed in most cases)
- [ ] Design
- [ ] Product
- [ ] QA (automation tests are required to pass before merging PRs but not all changes are covered by automation tests - please review if QA is needed beyond automation tests)
- [ ] Security
- [ ] Legal
- [ ] Marketing
- [ ] Management (please specify)
- [ ] Other (please specify)

**Comment by duncanchiu409** [comment]
Same issue here. Please fix it right away. Really serious issue here.

**Comment by gauthierpetetin** [comment]
Fixed in this PR: https://github.com/MetaMask/metamask-mobile/pull/9978
